### ISSUE TITLE
getting a lot of "warning: URI.escape is obsolete"

### ISSUE THREAD

**Issue by timorkal** [chef/chef#10026]
## Description
After upgrade to chef-client 16.2.44, I am getting a lot of "warning: URI.escape is obsolete".
I am using the "docker cookbook" but I can't tell who is the source of it, is it the chef-client or the "docker cookbook"
## Chef Version
16.2.44

## Platform Version
Ubuntu 20.04 LTS

## Replication Case
Just run a simple docker image and container resource (via docker cookbook) with this chef-client version.

## Client Output
Starting Chef Infra Client, version 16.2.44
resolving cookbooks for run list: ["edge_device::graylog"]
Synchronizing Cookbooks:
  - sshd (2.0.0)
  - docker (6.0.3)
  - edge_device (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 7 resources
Recipe: edge_device::graylog
  * docker_network[graylog] action create/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/network.rb:54: warning: URI.escape 
is obsolete
 (up to date)
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/network.rb:54: warning: URI.escape is obsolete
  * docker_image[mongo] action pull/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
 (up to date)
  * docker_container[mongo] action run/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape 
is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
 (up to date)
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
  * docker_image[elasticsearch] action pull/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
 (up to date)
  * docker_container[elasticsearch] action run/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
 (up to date)
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
  * docker_image[graylog] action pull/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
 (up to date)
  * docker_container[graylog] action run/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete
 (up to date)
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/container.rb:346: warning: URI.escape is obsolete
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/docker-api-1.34.2/lib/docker/image.rb:129: warning: URI.escape is obsolete

Running handlers:
Running handlers complete
Chef Infra Client finished, 0/7 resources updated in 24 seconds

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it. -->

```

```

**Comment by tas50** [comment]
This isn't actually an issue in Chef Infra Client. This is a problem with the docker-api gem: https://github.com/swipely/docker-api/issues/557

We've forked the gem and resolves the warnings when running kitchen-dokken in Chef Workstation, but the upstream maintainer will need to resolve the issues so that all users (including cookbooks) get the benefits.

**Comment by timorkal** [comment]
Thanks, Do I need to wait for a new version for Chef Infra Client with this gem fix once upstream maintainer will fix it? or the current version will start working with the new gem automatically?

**Comment by timorkal** [comment]
Hi @tas50 please look at this https://github.com/swipely/docker-api/issues/559 it looks like there is an official fix that the chef-client should work with.

**Comment by tas50** [comment]
We don't directly bundle the docker-api in chef itself and the docker cookbook has been updated to use the 2.x release. We only ever bundled our own released with chef-workstation, which prevented those errors from being shown when you ran kitchen dokken there.

**Comment by timorkal** [comment]
Ok, so please can you explain who is responsible for taking out these errors/warnings during the chef-client run?
