### ISSUE TITLE
transient knife error reported on STDOUT

### ISSUE THREAD

**Issue by in4mer** [chef/chef#10048]
## Description

While running knife, a transient 500 error was received from the hosted Chef server.   This error was announced by knife through stdout!!!
## Chef Version

13.4.19
## Platform Version

Ubuntu 18.04.4
## Replication Case

Use hosted chef during a period of transient errors when piping knife output through a script!
## Client Output

```
% for box in $(knife search node name:app-\* -i); do
echo -n "${box%%[0-9]*}${box[-1,$]}:\t"; curl -qqs http://${box}.prod:8080/ping | jq -r '.version'
done
15 items found

ERROR:::        Serverr:        returnedd:      errorr: 0:      forr:   https://api.opscode.com/organizations/lolwut/search/node?q=name:app-*&start=,:     retryingg:      5:i
nn:     s:      app-ui-1:       3.613.0


```

**Comment by lamont-granquist** [comment]
chef-13 and chef-14 are EOL, you're going to have to replicate this on a supported version.
