### ISSUE TITLE
Default configuration of `ssl_ca_file` is only set on Windows, but not on any other platforms

### ISSUE THREAD

**Issue by kapilchouhan99** [chef/chef#10073]
## Description
Default configuration of `ssl_ca_file` is only set on Windows, but not on any other platforms
## Related Issue
https://github.com/chef/customer-bugs/issues/102
## Replication Case
Execute the recipe locally on any non-Windows platform. Contents of /tmp/env.log will be empty after the run completes.
```
file '/tmp/env.log' do
  content "#{Chef::Config['ssl_ca_file']}" 
end
```

## Expected Results
Both Windows and non-Windows will return a valid path, when executing the above recipe.

## Actual Results:
The above recipe when executed on a Windows node, It returns `C:/opscode/chef/embedded/ssl/certs/cacert.pem`
When executed on Linux it returns empty (nil)

**Comment by dheerajd-msys** [comment]
Closing based on https://github.com/chef/chef/pull/10100#discussion_r482012014
