### ISSUE TITLE
osx_profile no longer supports the "install" action as of macOS Big Sur

### ISSUE THREAD

**Issue by erikng** [chef/chef#10075]
## Description
Apple has now removed the entire `profiles -I` and `profiles install` verb. Because of this, the `:install` action is no longer going to be an option.

The `:nothing` and `:remove` actions still work.

## Chef Version
All versions of chef

## Platform Version
macOS Big Sur

## Replication Case
https://docs.chef.io/resources/osx_profile/ use any of the `install` examples

**Comment by jho26** [comment]
I have the same issue in big sur

**Comment by erikng** [comment]
There's nothing Chef can do here without a MDM.

**Comment by tas50** [comment]
Closing this out since this is outside our control for the most part.

**Comment by btm** [comment]
We will have to solve this issue with new work outside of chef/chef and then come back. That will be a major effort and is under discussion.

**Comment by erikng** [comment]
Perhaps the chef team could update the profile resource to warn on Big Sur that it cannot work?

I feel like that should be done, as well as updating the documentation.
