### ISSUE TITLE
potential fix for macos_userdefaults and complex values

### ISSUE THREAD

**Issue by erikng** [chef/chef#10086]
### Describe the Enhancement:
The following descriptions may be able to make this resource work for complex values

#### Reading a defaults file
```
/usr/bin/defaults export payload_domain -
```

The key is the `-` at the very end.

```
defaults export /Library/Preferences/com.apple.timezone.auto.plist -

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Active</key>
	<true/>
</dict>
</plist>
```

This would then allow you to consume this with the `plist` gem and properly compare values.

#### Writing a defaults file
```
defaults import payload_domain - < /path/to/file.plist
```

Using this, you would have to do the following:
1. Read the current configuration with `defaults import` and save it in memory
2. Append the desired changes to the plist, overwriting what is necessary
3. Saving the plist to disk
4. importing it with the above example command

```
defaults import /Library/Preferences/com.apple.timezone.auto.plist - < /tmp/tz.plist
(plist file has Active set to false)

defaults export /Library/Preferences/com.apple.timezone.auto.plist -

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Active</key>
	<false/>
</dict>
</plist>
```

One secondary concern is spawning multiple `import` commands simultaneously (say setting 10 values to one preference domain). There is no guarantee that `cfprefsd` will write to disk quickly enough, which would not be run-time safe.

One alternative would be for chef to look at all preferences being set for a specific domain and hashing the written plist with the expected plist. This is exactly what @natewalck did when implementing the `osx_profile` resource.

### Describe the Need:
There are several bugs
- https://github.com/chef/chef/issues/7131
 - this should be fixed with the `defaults export` command
- https://github.com/chef/chef/issues/10083
  - this should be fixed with the `defaults import` command
- https://github.com/chef/chef/issues/10084
  - this should be fixed with the `defaults export` command

I think these may all be solved with this

### Current Alternative
N/a

### Can We Help You Implement This?:
Not at this moment

**Comment by erikng** [comment]
so essentially during compilation phase, compile all of the `macos_userdefaults` to a plist per payload domain, then run `defaults export` and compare with the plist chef expects to deploy. If it's not identically hashed, run `defaults import` with the plist created during compilation phase.

**Comment by natewalck** [comment]
Using `defaults export` it will be the *entire* plist and you may only want to manage a handful of keys.

In that case, you may be able to defaults export, compare the keys to manage vs the current state, then do the defaults shell out to write them if they do not match.

**Comment by erikng** [comment]
I was told by a colleague that you do not actually have to write the plist to disk when using import. It can just take it from stdin.

```
cmd = ["/usr/bin/defaults", "import", target_pref, "-"]
execute cmd.join(" ") do
    input xml_for_stdin
end
```

This is untested, but may work.

**Comment by tas50** [comment]
I'm going to close this out since the export has been implemented for loading the current value and it was pointed out that importing the plist would result in a race condition where we overwrite values set by an app.
