### ISSUE TITLE
Knife bootstrap password prompt can't be exited from

### ISSUE THREAD

**Issue by tas50** [chef/chef#10080]
It appears we're rescuing too agressively here somewhere. If you bootstrap a node you cant ctl-c out of the boostrap password prompt:

```
WARNING: Failed to authenticate  to ec2-54-187-152-162.us-west-2.compute.amazonaws.com - trying password auth
Enter password for @ec2-54-187-152-162.us-west-2.compute.amazonaws.com:
```

**Comment by vsingh-msys** [comment]
It's due to highline gem known issue https://github.com/JEG2/highline/issues/236, an alternative to this we can use 
[IO.html#method-i-getpass](https://ruby-doc.org/stdlib-2.5.0/libdoc/io/console/rdoc/IO.html#method-i-getpass)

**Comment by tas50** [comment]
I'd love to get off highline. We've pretty universally adopted the gems in the TTY project, which are actively maintained and have nice interfaces: https://ttytoolkit.org/
