### ISSUE TITLE
Add an option to specify Chef server hostname

### ISSUE THREAD

**Issue by jackivanov** [chef/chef#10109]
### Describe the Enhancement:
We need to add a new option `chef_server_hostname`, so it can be used separately of `chef_server_url`.
This is useful when the connection is proxied over the SSH tunnel, and `chef_server_url` obviously can't include a valid hostname (eg: `https://127.0.0.1:2443/organizations/yada`)

### Describe the Need:
This is pretty important for those who use SSH/TCP tunnels to reach an internal Chef server and still have SSL validation in place.

### Current Alternative
- /etc/hosts: `127.0.0.1 you-chef-server-name.com`
- knife.rb: `ssl_verify_mode :verify_none`

**Comment by lamont-granquist** [comment]
if you set the http_proxy settings to something like 127.0.0.1:2443 does it work?

**Comment by lamont-granquist** [comment]
closing due to lack of response
