### ISSUE TITLE
chef-client run causes yum_helper.py to trigger "new" python exceptions

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/chef#10108]
## Description

A change in `/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.9.17/lib/chef/provider/package/yum/yum_helper.py", line 202` introduced in chef/chef#7155 appears to be causing an abort event on Redhat 6 & 7 servers for the user during chef-client runs. User was able to manually revert this change and proceed with a chef-client run without trigging the exception. It's not clear if this is a desirable change and/or if yum_helper.py is getting invalid arguments.

## Related Issue
https://github.com/chef/customer-bugs/issues/206
## Replication Case

Original code
199 try:
200 command = json.loads(line)
201 except ValueError, e:
202 raise RuntimeError("bad json parse")

Changed code
199 try:
200 command = json.loads(line)
201 except ValueError, e:
202 base.closeRpmDB()
203 sys.exit(0)
## Expected Behaviour
chef-client run completes with no Python exception/no abrt event
## Client Output
```
Contents of an email about a RH7 abrt event with some debug info.
abrt email for yum_helper.py
reason: yum_helper.py:202::RuntimeError: bad json parse
cmdline: /usr/libexec/platform-python /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.9.17/lib/chef/provider/package/yum/yum_helper.py 11 10
executable: /opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.9.17/lib/chef/provider/package/yum/yum_helper.py
package: chef-15.9.17-1.el7
component: chef
pid: 13528
hostname: ld0082.healthpartners.com
count: 9
abrt_version: 2.1.11
analyzer: Python
architecture: x86_64
duphash: 40706b1ad5be8514ca4625deffb4c0e71f82623c
event_log:
kernel: 3.10.0-1127.el7.x86_64
last_occurrence: 1592331631
os_release: Red Hat Enterprise Linux Server release 7.8 (Maipo)
pkg_arch: x86_64
pkg_epoch: 0
pkg_fingerprint: 2940 ABA9 83EF 826A
pkg_name: chef
pkg_release: 1.el7
pkg_vendor: Omnibus omnibus@getchef.com
pkg_version: 15.9.17
runlevel: N 3
time: Tue 16 Jun 2020 09:01:10 AM CDT
type: Python
uid: 0
username: root
uuid: 40706b1ad5be8514ca4625deffb4c0e71f82623c

backtrace:
:yum_helper.py:202::RuntimeError: bad json parse
:
:Traceback (most recent call last):
: File "/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.9.17/lib/chef/provider/package/yum/yum_helper.py", line 202, in
: raise RuntimeError("bad json parse")
:RuntimeError: bad json parse
:
:Local variables in innermost frame:
:compareEVR: <function compareEVR at 0x7f0f35b2e140>
:setup_exit_handler: <function setup_exit_handler at 0x7f0f3335ff50>
:exit_handler: <function exit_handler at 0x7f0f3335fed8>
:inpipe: <open file '', mode 'r' at 0x7f0f3382ee40>
:query: <function query at 0x7f0f3335fe60>
:string_to_prco_tuple: <function string_to_prco_tuple at 0x7f0f34c6f758>:stringToVersion: <function stringToVersion at 0x7f0f35b2e6e0>
:package: None
:re: <module 're' from '/usr/lib64/python2.7/re.pyc'>
:json: <module 'json' from '/usr/lib64/python2.7/json/init.pyc'>
:install_only_packages: <function install_only_packages at 0x7f0f3335fde8>
:command: {u'action': u'whatinstalled', u'provides': u'BESAgent'}
:outpipe: <open file '', mode 'w' at 0x7f0f3382eed0>
:doc: None
:get_base: <function get_base at 0x7f0f3335fcf8>
:builtins: <module 'builtin' (built-in)>
:file: '/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.9.17/lib/chef/provider/package/yum/yum_helper.py'
:versioncompare: <function versioncompare at 0x7f0f3335fd70>
:sys: <module 'sys' (built-in)>
:base: <yum.YumBase object at 0x7f0f33357d90>
:name: 'main'
:line: ''
:ppid: 13398
:getBaseArch: <function getBaseArch at 0x7f0f34c4e140>
:signal: <module 'signal' (built-in)>
:getArchList: <function getArchList at 0x7f0f34c42b90>
yum <module 'yum' from '/usr/lib/python2.7/site-packages/yum/init.pyc'>
:os: <module 'os' from '/usr/lib64/python2.7/os.pyc'>
:e: ValueError('No JSON object could be decoded',)
environ:
:LANG=en_US.UTF-8
:INTERVAL=1800
:SPLAY=300
:HOME=/
:PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
:PYTHONUNBUFFERED=1
:CONFIG=/etc/chef/client.rb
:OPTIONS=
:PIDFILE=/var/run/chef/client.pid
machineid:
:systemd=a309c582cbf4437fac7a601f6a18ae02
:sosreport_uploader-dmidecode=47d444b9f1e0e1a81353c853067f850af73bf603dbd4c32ac1ec14718c288b13
os_info:
:NAME="Red Hat Enterprise Linux Server"
:VERSION="7.8 (Maipo)"
:ID="rhel"
:ID_LIKE="fedora"
:VARIANT="Server"
:VARIANT_ID="server"
:VERSION_ID="7.8"
:PRETTY_NAME="Red Hat Enterprise Linux Server 7.8 (Maipo)"
:ANSI_COLOR="0;31"
:CPE_NAME="cpe:/o:redhat:enterprise_linux:7.8:GA:server"
:HOME_URL="https://www.redhat.com/"
:BUG_REPORT_URL="https://bugzilla.redhat.com/"
:
:REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
:REDHAT_BUGZILLA_PRODUCT_VERSION=7.8
:REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
:REDHAT_SUPPORT_PRODUCT_VERSION="7.8"
```

**Comment by lamont-granquist** [comment]
That is very clearly the wrong fix.  That code needs to stay in.  The determination needs to be made of why the ruby side is sending some kind of garbage to the python side.

**Comment by btpier** [comment]
Seeing this with 15.13.8 as well.

**Comment by lamont-granquist** [comment]
Needs and actual replication case or more information.  The proposed fix of backing out the prior change is incorrect, but there's no useful information here to determine what the actual buggy behavior is.

**Comment by btpier** [comment]
Understood. I wasn't suggesting the proposed fix should be implemented. I just wanted to raise awareness that this issue is affecting more than just the original reporter. I will attempt to gather more information on what's actually failing on my clients.

**Comment by lamont-granquist** [comment]
More people being affected won't help this one get solved any faster though.  I can't guess how to replicate it, and don't have a clue as to the real cause, so it can't be worked on until there's more information.

**Comment by olqs** [comment]
I have the same behaviour with chef-16.3.45 and can reproduce this.

**Comment by lamont-granquist** [comment]
I still need a replication case, or some information on what people are doing to trigger this bug, since without a replication case there is still way to guess what the problem is or how to fix it.

I'm going to delete any future comments that offer nothing more than observations that people are affected by the bug.  They amount to nothing more than a "+1" or "me too".  Sending `-l trace` logs of the whole context of the yum_package execution might be useful at a minimum.

**Comment by olqs** [comment]
The abrt error is raised while verifying the packages in the selinux::_common recipe. I can reproduce this with only recipe[selinux::_common] in the runlist and have attached the trace log of the chef-client. I have added the mail i get from abrt too.

If you need any additional debug output, then just ask. 
[abrt-selinux.txt](https://github.com/chef/chef/files/5089126/abrt-selinux.txt)
[chef-client.trace.log](https://github.com/chef/chef/files/5089128/chef-client.trace.log)

**Comment by kapilchouhan99** [comment]
Hi @olqs I have checked it on `Red hat 7.8` with cookbook `selinux 2.0.0`, and i am not getting any type of error:
```
[root@ip-address ec2-user]# sudo chef-client
Starting Chef Infra Client, version 16.4.41
resolving cookbooks for run list: ["selinux::_common"]
Synchronizing Cookbooks:
  - selinux (2.0.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: selinux::_common
  * selinux_install[selinux os prep] action install
    * yum_package[policycoreutils] action install
      - install version 0:2.5-34.el7.x86_64 of package policycoreutils
    * yum_package[selinux-policy] action install
      - install version 0:3.13.1-266.el7_8.1.noarch of package selinux-policy
    * yum_package[selinux-policy-targeted] action install
      - install version 0:3.13.1-266.el7_8.1.noarch of package selinux-policy-targeted
    * yum_package[libselinux-utils] action install (up to date)
    * yum_package[mcstrans] action install
      - install version 0:0.3.4-5.el7.x86_64 of package mcstrans
    * directory[/etc/selinux] action create (up to date)
Running handlers:
Running handlers complete
Chef Infra Client finished, 5/7 resources updated in 14 seconds
```
after the chef-client run, i have also checked `abrt-cli list` but its not showing any detected problems.
```
[root@ip-address ec2-user]# abrt-cli list
[root@ip-address ec2-user]# 
```
could you please provide me steps to reproduce this issue?

**Comment by dheerajd-msys** [comment]
@olqs Please check ^ if we are missing anything reproducing this issue.

**Comment by lamont-granquist** [comment]
That trace log doesn't show any exceptions thrown from the python helper.

From the abort trace the command is showing:

```
:command: {u'action': u'whatinstalled', u'provides': u'nfs-utils'}
```

So that wasn't from the selinux recipe

**Comment by lamont-granquist** [comment]
Well at least it wasn't from the selinux recipe in isolation, that was probably the prior command that was received.

**Comment by lamont-granquist** [comment]
```
:line: ''
```

that is what it is failing on, but it isn't clear if there's an actual command in the pipe and that is somehow a stray `\n` being sent (can't really guess where that'd come from though).  still need an accurate `-l trace` that shows a failure talking to the python helper with the python helper being restarted.

**Comment by jblaine** [comment]
Confirming same failure. Nothing interesting shows in the `-l trace` output though. The basics from abrt are below. @lamont-granquist What specifically should I be looking for in the output of `-l trace` when this is happening.

```
:sys: <module 'sys' (built-in)>
:base: <yum.YumBase object at 0x7f0f88cc9d90>
:__name__: '__main__'
:line: ''
:ppid: 2296
:getBaseArch: <function getBaseArch at 0x7f0f8a5c0140>
:signal: <module 'signal' (built-in)>
:getArchList: <function getArchList at 0x7f0f8a5b4b90>
:yum: <module 'yum' from '/usr/lib/python2.7/site-packages/yum/__init__.pyc'>
:os: <module 'os' from '/usr/lib64/python2.7/os.pyc'>
:e: ValueError('No JSON object could be decoded',)
```

**Comment by MrCyrus** [comment]
I've the same issue on 400+ servers and I just upgraded to chef-client 16.9.32 on 1 server as a test to see if that helped, but it did not. On the 400+ servers, the error is occurring in /opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.2.73/lib/chef/provider/package/yum/yum_helper.py at line 202 is:
    199         try:
    200             command = json.loads(line)
    201         except ValueError, e:
    202             raise RuntimeError("bad json parse")

I believe the issue is line 202 uses Python's default error handler which today is generating the 'abrt' msg instead of gracefully handling the error itself.
