### ISSUE TITLE
Resource override warning indicates incorrect behavior

### ISSUE THREAD

**Issue by kimbernator** [chef/chef#10105]
## Description
Upon startup, chef-client indicates the following:

```
WARN: Resource chef_client_scheduled_task from the client is overriding the resource from a cookbook. Please upgrade your cookbook or remove the cookbook from your run_list.
```

This is due to the `chef-client` cookbook still being present in the run-list (this cookbook contains a custom resource called `chef_client_scheduled_task`) while running chef 16, which now includes `chef_client_scheduled_task` natively. Since there is further functionality in that cookbook that didn't make it into chef 16 (namely client.rb management), the cookbook remains in the runlist.

The warning above implies to me that the native version of the resource takes precedence and the custom resource in the chef-client cookbook will be disregarded. However, after noticing the splay not being applied to the scheduled task, I found that the chef-client cookbook resource is indeed still the one being used. I put a few simple "puts" statements in each and ran chef, it indicated that I was on the cookbook version.

## Chef Version
16.1.16

## Platform Version
Windows Server 2016

## Replication Case

Have a cookbook with a dependency on the chef-client cookbook, edit the local copy of the scheduled_task resource's `:add` action to include a "puts" indicating that it is being executed, then attempt to execute a chef_client_scheduled_task resource and look for the puts output. I'm sure there's a more "correct" way to do this but it works.

## Client Output

None aside from the warning above.

**Comment by lamont-granquist** [comment]
fixed the warning message in #10117
