### ISSUE TITLE
Restore net-dss support to knife

### ISSUE THREAD

**Issue by mattray** [chef/chef#10130]
The upgrade to net-ssh > 6 removed net-dss being enabled by default. It's still supported until version 7.

This train patch should restore support, but it's worth verifying once it's available in Chef.
https://github.com/inspec/train/pull/603/files

Workstation 20.7.81 does not have this patch.
https://github.com/net-ssh/net-ssh#supported-algorithms details the change

**Comment by tas50** [comment]
This should be fixed in https://github.com/chef/chef/pull/10133
