### ISSUE TITLE
unable to compile httpd after Chef-client 16 update

### ISSUE THREAD

**Issue by sid-bitra** [chef/chef#10152]
Our httpd cookbook is based on the community cookbook https://github.com/chef-cookbooks/httpd

while it is working fine until chef 15 we are unable to installl httpd when we moved to chef- client 16.

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/base_httpd/libraries/httpd_config_debian.rb
================================================================================
 
NameError
undefined local variable or method `use_automatic_resource_name' for HttpdCookbook::HttpdConfigDebian:Class
 
Cookbook Trace:
  /var/chef/cache/cookbooks/base_httpd/libraries/httpd_config_debian.rb:3:in `<class:HttpdConfigDebian>'
  /var/chef/cache/cookbooks/base_httpd/libraries/httpd_config_debian.rb:2:in `<module:HttpdCookbook>'
  /var/chef/cache/cookbooks/base_httpd/libraries/httpd_config_debian.rb:1:in `<top (required)>'
 
Relevant File Content:
/var/chef/cache/cookbooks/base_httpd/libraries/httpd_config_debian.rb:
 
  1:  module HttpdCookbook
  2:    class HttpdConfigDebian < HttpdConfig
  3>>     use_automatic_resource_name
  4:      provides :httpd_config, platform_family: 'debian'
  5:
  6:      action :create do
  7:        if new_resource.httpd_version.to_f < 2.4
  8:          directory "/etc/#{apache_name}/conf.d" do
  9:            owner 'root'
 10:            group 'root'
 11:            mode '0755'
 12:            recursive true

**Comment by lamont-granquist** [comment]
Yeah that line needs to be deleted.  Probably got missed in the release notes.

Scanning the supermarket cookbooks it comes up in the httpd cookbook, the old deprecated compat_resource cookbook and 2 other cookbooks and that's it.

That was deliberately removed though as a 16.0 breaking change, that cookbook needs to be updated.
