### ISSUE TITLE
Import tools do not display cookbook name in error messages

### ISSUE THREAD

**Issue by jonlives** [chef/chef#10174]
When uploading data into Chef Server 12, error messages like this:

`ERROR: /cookbooks failed to write: HTTP error writing: 400 "Bad Request" cause: {"error":["Field 'metadata.maintainer' invalid"]}`

do not display the name of the cookbook which produced that error - would be nice if they did :)

**Comment by tas50** [comment]
I moved this since it's probably a knife issue, but in order to troubleshoot it we'd need to see the cookbook being uploaded and have it reproduced in knife 16.x. If anyone runs into this again open a new ticket and we'll track it down.
