### ISSUE TITLE
Replace highline ui.list with tty-table gem

### ISSUE THREAD

**Issue by vsingh-msys** [chef/chef#10208]
In order to replace `ui.list` Highline methods to equivalent [tty-table](https://github.com/piotrmurach/tty-table) gem, need some wrapper to be implemented to provide compatibility with the exiting use cases.

**Comment by sanga1794** [comment]
@tas50 is there anything pending from this issue OR we are okay to close as the PR got merged?

**Comment by tas50** [comment]
Highline is still a dependency in knife so this cant be closed
