### ISSUE TITLE
Include the Line Cookbook as a resource

### ISSUE THREAD

**Issue by kmf** [chef/chef#10224]
### Describe the resource:
Please include the `line` cookbook

### Why should this be included out of the box?:
It's almost as useful as the file cookbook

### Current cookbook implementation:
Yes.
https://github.com/sous-chefs/line

**Comment by tas50** [comment]
Buried on @lamont-granquist's laptop is a CFEngine inspired set of file edit resources that we'd like to add to core instead of the specific ones in the line cookbook. We just need to clone @lamont-granquist so he has time to do that.

**Comment by lamont-granquist** [comment]
Yeah the answer to including line directly is 'nope' and this duplicates #7043.
