### ISSUE TITLE
`archive_file` should support removing leading directory on extraction

### ISSUE THREAD

**Issue by jakauppila** [chef/chef#10229]
### Describe the Enhancement:
Add an additional configuration to `archive_file` to allow removing the leading directory within an archive upon extraction.

### Describe the Need:
When dealing with archives that are packaged with a leading directory often you want to extract it to a particular location removing that top level directory.

For example, Tomcat.

- https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.37/bin/apache-tomcat-9.0.37.tar.gz

This archive at the top level has a folder `apache-tomcat-9.0.37`, if I have a resource:

```ruby
archive_file 'apache-tomcat-9.0.37.tar.gz' do
  destination '/tomcat-9.0.37'
end
```

It will be extracted to `/tomcat-9.0.37/apache-tomcat-9.0.37` when I really want to strip out that top directory.

Currently in [sous-chefs/tomcat the cookbook utilizes `tar` to extract](https://github.com/sous-chefs/tomcat/blob/master/resources/install.rb#L106) which has `--strip-components` available at the command line, allowing for the extraction to go a folder deep.

**Comment by jasonwbarnett** [comment]
I just ran into this and it seems like this would be semi trivial to implement, although I can't say when I'd be able to do this. For whoever runs into this, I think it would be just adding something like...

```ruby
archive.each_entry do |e|
  file_dest = new_resource.strip_components > 0 ? strip_components(e.pathname) : nil
  archive.extract(e, flags.to_i, destination: file_dest)
end

def strip_components(path)
  path.split("/").drop(new_resource.strip_components).join("/")
end
```
