### ISSUE TITLE
issue with knife bootstrap - No candidate version available for ntp

### ISSUE THREAD

**Issue by AnamikaN** [chef/chef#10271]
* No candidate version available for ntp
    ================================================================================
    Error executing action `install` on resource 'dnf_package[ntp]'
    ================================================================================

    Chef::Exceptions::Package
    -------------------------
    No candidate version available for ntp

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/ntp/recipes/default.rb

     43:     package ntppkg do
     44:       source node['ntp']['pkg_source']
     45:       action :install
     46:       # Non-interactive package install fails on Solaris10 so we need to manually the ntp package
     47:       not_if { node['platform_family'] == 'solaris2' && node['platform_version'].to_f <= 5.10 }
     48:     end
     49:   end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/ntp/recipes/default.rb:43:in `block in from_file'

    dnf_package("ntp") do
      package_name "ntp"
      action [:install]
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "ntp"
      recipe_name "default"
      not_if { #code block }
    end

    System Info:
    ------------
    chef_version=15.13.8
    platform=redhat
    platform_version=8.2
    ruby=ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
    program_name=/bin/chef-client
    executable=/opt/chef/bin/chef-client

Running handlers:
[2020-08-06T23:26:45+00:00] ERROR: Running exception handlers
Running handlers complete
[2020-08-06T23:26:45+00:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 09 seconds
[2020-08-06T23:26:45+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2020-08-06T23:26:45+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-08-06T23:26:45+00:00] FATAL: Chef::Exceptions::Package: dnf_package[ntp] (ntp::default line 43) had an error: Chef::Exceptions::Package: No candidate version available for ntp
ERROR: The following error occurred on 10.200.186.171:
ERROR:

**Comment by AnamikaN** [comment]
updated ntp cookbook and it worked.

**Comment by suman148** [comment]
@AnamikaN What changes did you had to make to the ntp cookbook?
