### ISSUE TITLE
Accumulator pattern design issue: delayed notifications are always executed

### ISSUE THREAD

**Issue by dud225** [chef/chef#10299]
Hello

when one needs to edit a single file from multiple pieces collected from several places, the common implementation relies on the accumulator pattern: https://github.com/chef/chef/issues/5438#issuecomment-351153222.

This suffers from a design issue: delayed notifications are always executed, even when the current Chef run had just failed.
As I understand it, in the normal case, for example a service that should be reloaded after a configuration change, this is exactly what is desired to prevent from leaving the system in a broken state.
However, in the accumulator pattern, this wreaks havoc if Chef fails while the accumulator has only been half filled.

This issue has already been discussed in some places:
- https://github.com/sous-chefs/samba/issues/96
- https://github.com/chef-cookbooks/firewall/issues/106

however there doesn't seem to be any solution.

This issue has already been discussed here in the past https://github.com/chef/chef/issues/2084. The answer at that time was to resort to a definition to leverage the fact that it is executed at compile time. Howerver, today "definitions are not yet deprecated, [but] we strongly advise migrating to custom resources immediately".

~As far as I understand it, there is a way to force a custom resource to be execute once at compile time thanks to the recent unified_mode setting. I'm not sure if this is what you had in mind @damacus when you added this into the HAproxy cookbook as your commit doesn't say much about your motivation: https://github.com/sous-chefs/haproxy/pull/440 ?~ (EDIT: please disregard that part, I misunderstood how unified_mode is working)
Even with the option of forcing a custom resource to be run at compile time, I don't feel it is enough to handle all cases, for example this would probably not work for a custom resource embedded within another custom resource (eg if my application cookbook has a custom resource that calls one of the HAproxy custom resource), would it?

A easy way to work around this would be to get access to the status of the run (run_status). Is there any way to know if the current run has failed so that we could use that information within a not_if guard?

Is there any other option that we may consider?

dud

**Comment by dud225** [comment]
I finally found some workaround by browsing through all the resources executed so far and checking their status:
```
only_if { run_context.action_collection.select { |action_record| action_record.status.nil? || action_record.status == :failed }.count == 0 }
```
The status is nil if Chef is interrupted eg (CTRL+C).
This allows to inhibit the notification if any of the previous has failed or if the run has been interrupted.
@Poohblah you may want to try this workaround.

**Comment by Poohblah** [comment]
Oh, wow, thank you so much.  I would love to try that out.  However, my team is in the middle of migrating away from Chef to Ansible, so it's very unlikely that I will get the chance to test that particular workaround.

**Comment by lamont-granquist** [comment]
This is a dup of another ticket, I can't find it think morning though

**Comment by tas50** [comment]
Closing this out based on the previous comment.
