### ISSUE TITLE
API based macos_userdefaults resource

### ISSUE THREAD

**Issue by OBrienCommaJosh** [chef/chef#10307]
Create a new macos\_userdefaults resource and associated library to configure the user defaults preferences system on macOS using the API rather than the `defaults` command line tool.

We created a new macos\_userdefaults resource for Infra Client 16.3 after learning that the existing one was fundamentally flawed. This was created on priority given that macOS 11 Big Sur removed the ability to install profiles from the command line, which removed that system as a common mechanism for configuring macOS. However for full functionality we need a library connecting to the system API.

The API docs for the Preferences system we want to access are here: [https://developer.apple.com/documentation/corefoundation/preferences\_utilities](https://developer.apple.com/documentation/corefoundation/preferences_utilities)

I presume we'd want to write a macos-userdefaults ffi based library for `/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation`.

Aha! Link: https://chef.aha.io/features/SH-170

**Comment by johnmccrae** [comment]
Hi, I would like to add a Design Change Request here:

Tim reports this work is part of an FFI gem to get us OS access on Mac to do interesting things, yes? If true, please add a work block to do the following items: 

**Note - this is all part of ongoing work to get certificates off disk and stored securely in KeyChain or Certstore (Windows certificate store). Ideally the end state is that during bootstrap, the chef-client creates the local pfx/p12 object, stores it, then uses the key from that object in place of the client.pem. When registering the client with Chef Server via the validation.pem or knife bootstrap, we'd use that p12 key. Then we'd kill the validation.pem and we'd have no certs on disk. Tada!

1) Access to Keychain - need to be able perform the same commands via the gem that we can execute via the 'security' command line tool - specifically we need the ability to create a new keychain, or add certificates and secrets to an existing keychain, like the system Keychain so we can abstract our settings from user settings and not have the user unintentionally delete our things. 

2) The ability to Generate a .p12 file and auto-import it. On Windows, we have some code that generates a .pfx file (a Windows .p12) and that code automagically imports that cert/key combo, sets the key as exportable and later adds a password for export. The file should be named, always, 'chef-<node name>" where nodename is the name that chef derives (as opposed to the admin or some other mechanism deriving it). 

* Note: This item below is predicated on the belief that any keys exported via command line require a password to secure them. I am assuming a code based approach might also require this but if not, you can ignore this step.
3) Code to generate a random password of configurable length that is used where necessary to export the key from the p12 with. That password should be autostored in the keychain above under the label of 'PfxPass' for consistency.

4) The ability to extract the key from the .p12 you just stored and pass it back to the calling object as a variable of some sort. For reference - here is the PR for the Chef-Client https://github.com/chef/chef/pull/11834 - the hook for your work will be in the Authenticator.rb at line 129 I'll call retrieve_certificate_key(Chef::Config[:node_name]) - that method will contain the corresponding code to retrieve the key from the p12 in Keychain with. 

5) The ability to delete that p12 as need be. We assume admins will want to use this approach by default but will need to bypass as necessary 

6) The ability to merely search for the presence of the p12, named "chef-<node name>". 

7) Finally, we'll need a way to update that key as need be, even if that is only to call a delete and create on the p12.

**Comment by tas50** [comment]
Done
