### ISSUE TITLE
'osx_profile' big sur error raised on macOS catalina

### ISSUE THREAD

**Issue by jho26** [chef/chef#10326]
I am using the latest chef client and I am noticing the big sur error raised on my macOS Catalina (10.15.4) VM

          chef_version=16.4.35
           platform=mac_os_x
           platform_version=10.15.4
           ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin17]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client
           
line 45) had an error: RuntimeError: The osx_profile resource is not available on macOS Bug Sur or above due to the removal of apple support for CLI installation of profiles

https://github.com/chef/chef/blob/7fb14323429eac7fbcc2294bb934586d1544821c/lib/chef/resource/osx_profile.rb#L84

**Comment by tas50** [comment]
This is fixed in the 16.4.38 release
