### ISSUE TITLE
windows_package isn't idempotent

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#10336]
## Description

Windows package reinstalls the package every run.

## Chef Version
15.10.12 and 16.4.41

## Platform Version
Windows 10

## Replication Case
Given this resource:
```
windows_package 'vim' do
  source 'https://github.com/vim/vim-win32-installer/releases/download/' +
    'v8.2.1364/gvim_8.2.1364_x64.exe'
end
```

It seems to reinstall gvim each run.

## Client Output

The icons all go away and come back as you can see it re-install each time. Chef also tells you it installed it:

```
[2020-08-20T19:45:31-07:00] INFO: Processing windows_package[vim] action install (vcrs_windows::default line 9)
[2020-08-20T19:45:31-07:00] INFO: Processing remote_file[C:\chef\cache\package\gvim_8.2.1364_x64.exe] action create (dynamically defined)
[2020-08-20T19:45:49-07:00] INFO: windows_package[vim] installed vim at latest
```

**Comment by jaymzh** [comment]
Note I also tried adding `version '8.2.1364'` but that did not fix it.

**Comment by phiggins** [comment]
@jaymzh This was already mentioned in the docs, but it was a bit buried. I opened a PR to improve things here if you'd like to chime in: #10342

**Comment by tas50** [comment]
I think with the new ohai package behavior on windows and the updated docs we're probably good to close this one out. Feel free to correct me if I missed something @jaymzh
