### ISSUE TITLE
ZD - chef-client stop init.d service stopping other process

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/chef#10355]
## Description

It was observed that chef-client init.d stop service is killing process id of some other process. The code snippet shows that it usage killproc function of init.d on rhel 6 but only considering the PID from file not considering the program path.
stop() {
echo -n $"Stopping $prog: "
killproc -p $pidfile $exec
retval=$?
echo
[ $retval -eq 0 ] && rm -f $lockfile
return $retval
}

killproc -p /var/tmp/test.pid /usr/bin/chef-client

If you put any other process id of some other process suppose which were allocated by OS when chef-client was not running then this killproc will kill that process while it should also recognize the "/usr/bin/chef-client".
## Related Issue
https://github.com/chef/customer-bugs/issues/221
## Replication Case

1. created a simple script with sleep 180 second so that get new process id into some file.
2. run below
    killproc -p /var/tmp/test.pid /usr/bin/chef-client
3. it's killing the process which does not belong to this "/usr/bin/chef-client" program which is unexpected.

**Expected behaviour**

make sure that the init script does not kill anything not belonging to chef processes

**Actual behaviour**

Non-chef processes are being killed on init stop
## Additional context
Please find the script snippet below:
```
#!/bin/bash
#
# chef-client Startup script for the Chef client
#
# chkconfig: - 98 2
# description: Client component of the Chef systems integration framework.

### BEGIN INIT INFO
# Provides: chef-client
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Should-Start: $named $time
# Should-Stop: $named $time
# Short-Description: Startup script for the Chef client
# Description: Client component of the Chef systems integration framework.
### END INIT INFO

# Source function library
. /etc/init.d/functions

exec="/usr/bin/chef-client"
prog="chef-client"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

config=${CONFIG-/etc/chef/client.rb}
pidfile=${PIDFILE-/var/run/chef/client.pid}
lockfile=${LOCKFILE-/var/lock/subsys/$prog}
interval=${INTERVAL-1800}
splay=${SPLAY-20}
options=${OPTIONS-}

start() {
    [ -x $exec ] || exit 5
    [ -f $config ] || exit 6
    echo -n $"Starting $prog: "
    daemon $exec -d -c "$config" -P "$pidfile" -i "$interval" -s "$splay" "$options"
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $pidfile $exec
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart () {
    stop
    start
}

reload() {
    echo -n $"Reloading $prog: "
    killproc -p $pidfile $exec -HUP
    retval=$?
    echo
    return $retval
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status -p $pidfile $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
exit $?
```

**Comment by lamont-granquist** [comment]
Isn't the fix for this just using `killproc -p $pidfile -b $exec`?

Also that initscript doesn't appear to be in chef/chef so this issue is misfiled.

https://github.com/chef-cookbooks/chef-client/blob/master/templates/default/redhat/init.d/chef-client.erb#L46

**Comment by lamont-granquist** [comment]
hmm -b is terrible and `killproc -b $pidfile -b /opt/chef/embedded/bin/ruby /usr/bin/chef-client` is better but requires the path to the actual ruby, and doesn't match chef-client at all for some reason.

```
pkill -s `cat $pidfile` chef-client
```

is probably what should be used instead of killproc then and instead of rolling our own bad version of that.

since pkill doesn't seem to support matching by pid i put the pidfile into the -s argument which matches the sid and the sid should match the pid for the chef-client process since we should be calling setsid to become the process group leader (or just from the double-fork to daemonize).  the ppid should also work since ppid should == pid for the chef-client process by the same rationale.

still misfiled though.
