### ISSUE TITLE
ZD 25979 - /Users created on nodes after knife bootstrap

### ISSUE THREAD

**Issue by vsingh-msys** [chef/chef#10367]
#### Describe the bug

----------------------------------------------

```
r-goto@Mac:1.r-goto_admin +[master]%chef -v
Chef Workstation version: 20.8.125
Chef Infra Client version: 16.4.38
Chef InSpec version: 4.22.8
Chef CLI version: 3.0.24
Chef Habitat version: 1.6.56
Test Kitchen version: 2.6.0
Cookstyle version: 6.15.5
```

```
[vagrant@localhost /]$ ls /Users
ls: cannot access Users: no such directory
```

After `knife bootstrap`:

```
[vagrant@localhost /]$ ls /Users/r-goto/.chef/cache/chef-client-running.pid 
Users/r-goto/.chef/cache/chef-client-running.pid
```

`knife bootstrap` is creating chef directory right under `root` directory, which is not acceptable.
How can we change the directory location and where is it recommended to place? 

**To Reproduce**

Steps to reproduce the behavior.

**Expected behavior**

**Actual behavior**

A clear and concise description of what actually happened.

**Additional context**

Any other additional context here.

**Associated GitHub Issue**

Any associated public GitHub Issue URL link will be included here

**Comment by vsingh-msys** [comment]
it seems that by default `cache_path` picking up workstation home dir instead of node home dir

```
> cat /etc/chef/client.rb 

chef_server_url  "https://chef-server.test/organizations/4thcoffee"
validation_client_name "4thcoffee-validator"
chef_license "accept"
log_location   STDOUT
node_name "node2.test"
trusted_certs_dir "/etc/chef/trusted_certs"
file_cache_path "/home/vivek.singh/.chef/cache"  # workstion home dir /home/vivek.singh
file_backup_path "/home/vivek.singh/.chef/backup"

```

**Comment by r-goto** [comment]
Adding these lines in the `knife.rb` will place the `Users` directory where it's used to be.  

```
file_cache_path "/var/chef/cache"
file_backup_path "/var/chef/backup"
```

Could this be a workaround for this bug? 
Could this change cause any impact after fix release?

--

Also for those already bootstrapped and `Users`/ already placed under /, is it okay to relocate the directory to any intended location manually or should those nodes be bootstrapped again with above lines in `knife.rb`?

**Comment by vsingh-msys** [comment]
Hi @r-goto 

> Could this be a workaround for this bug?

_Yes, it will be a workaround. the problem only arises when `file_cache_path` and `file_backup_path`
taking default values._

> Could this change cause any impact after fix release?

_Nothing to worry, as the fixes only taking consideration when `file_cache_path` and `file_backup_path` are not set._


> Also for those already bootstrapped and Users/ already placed under /, is it okay to relocate the directory to any intended location manually or should those nodes be bootstrapped again with the above lines in knife.rb?

_Manually moving to any intended location probably will work, if the node's `/etc/chef/client.rb` file gets updated accordingly._

So please update `/etc/chef/client.rb` with:

```
file_cache_path "/var/chef/cache"
file_backup_path "/var/chef/backup"

```

**Comment by r-goto** [comment]
@vsingh-msys Thank you. 
Does the bug also occur on Windows OS? Windows workstation and Windows nodes?

**Comment by shail248** [comment]
Hi @vsingh-msys When can we expect the release with the fix

**Comment by vsingh-msys** [comment]
Hey @shail248 the fixes required some major changes related to target mode, will re-look into this Thanks!

**Comment by r-goto0510** [comment]
Hi @vsingh-msys 

The workaround above (https://github.com/chef/chef/issues/10367#issuecomment-700567676) does not work when bootstrapping a linux node from windows workstation. 

config.rb: 
```
current_dir = File.dirname(__FILE__)
node_name                'r-goto'
client_key               "#{current_dir}/r-goto.pem"
chef_server_url          "https://automate.cl/organizations/first-service"
file_cache_path "/var/chef/cache"
file_backup_path "/var/chef/backup"
```

Bootstrapped node's client.rb will have; 
```
[root@Cent7-node04 chef]# cat client.rb 
chef_server_url  "https://automate.cl/organizations/first-service"
validation_client_name "first-service-validator"
chef_license "accept"
log_location   STDOUT
node_name "node4"
trusted_certs_dir "/etc/chef/trusted_certs"
file_cache_path "C:\chef\cache". --------> does not work with Linux 
file_backup_path "C:\chef\backup"
```

Could you advise us if any reliable workaround exists when using Windows workstation? 

--
Tested workstation version;
```
PS C:\Users\vagrant\Desktop\automate-server-repo> chef -v
Chef Workstation version: 21.1.247
Chef Infra Client version: 16.9.32
Chef InSpec version: 4.26.4
Chef CLI version: 3.0.36
Chef Habitat version: 1.6.181
Test Kitchen version: 2.10.0
Cookstyle version: 7.5.3
```

**Comment by r-goto0510** [comment]
Also;
How does having file_cache_path "C:/var/chef/cache" in client.rb in linux machine would affect chef ops?

**Comment by djcoster** [comment]
I am running into this same issue.

All I did was update my Chef Workstation and now these two values are getting set in my `client.rb` file on each node I bootstrap. This is **not** in my config.rb and I consider this a very bad bug. If this is not specified it needs to be left out on nodes being bootstrapped.

I found a workaround, by setting this in my `.chef/knife.rb` file:

```
file_cache_path nil
file_backup_path nil
```

If that helps anyone else, and possibly for @r-goto0510 on the "windows" machine.

For me, this made the lines not get added to `/etc/chef/client.rb` as was the previous results.

**Comment by skylerto** [comment]
It's obviously not the best, would be great to have the fix but in the meantime here's another work around is to use knife bootstrap templates (https://docs.chef.io/workstation/knife_bootstrap/#custom-templates).

From the doc you would run something like this on mac:
```
find /opt/chef-workstation/embedded/lib/ruby -type f -name chef-full.erb -exec cat {} \; > template.erb
```

The idea here is using the bootstrap template to remove the offending values. Running something like this `sed` to strip out the `file_cache_path` and `file_backup_path`. Alternatively instead of replacing with `''` (empty string) you could replace it with the platform specific value you're looking for.

```
sed -i "s/config_content/config_content.gsub(\/(file_cache_path *.+)\/, '').gsub(\/(file_backup_path *.+)\/, '').strip/g" template.erb
```

**Comment by snehaldwivedi** [comment]
@btm @lamont-granquist I tested the changes on #11592 its resolving this issue and has done as suggested changes by both of you. So can you please review it once?

**Comment by tas50** [comment]
Fixed by https://github.com/chef/chef/pull/11592
