### ISSUE TITLE
cannot delete config profiles in macOS 11.0

### ISSUE THREAD

**Issue by chilcote** [chef/chef#10384]
## Description
We are migrating to MDM-delivered profiles, but we still need to remove profiles with the osx_profile resource. Gating this resource from running at all in 11.0 is too much; while apple has removed the ability to _install_ profiles in the cli, _removing_ profiles is still allowed. The resource should only alert on installing (creating) profiles, and still allow for the removal.

## Chef Version
16.5.26

## Platform Version
macOS 11.0 (20A5364e)

## Replication Case
In 10.15.x do this:

Using an open source cookbook (https://github.com/pinterest/it-cpe-cookbooks/tree/master/cpe_loginwindow is a simple one)

And feeding it a node attribute like so:
```
{
  'LoginwindowText' =>
    'I think chef done broke it',
}.each { |k, v| node.default['cpe_loginwindow'][k] = v }
```
Let that profile install via chef.

Upgrade the Mac to 11.0

Remove that profile node attribute, and run chef.  It should clean up the profile by deleting it, and then the profile will be managed via MDM outside of (or driven by) chef.

## Client Output

This is the error when it tried to delete one of our profiles. 
```
================================================================================
Error executing action `remove` on resource 'osx_profile[com.facebook.chef.filevault.enforce]'
================================================================================

RuntimeError
------------
The osx_profile resource is not available on macOS Big Sur or above due to Apple's removal of support for CLI profile installation

Resource Declaration:
---------------------
# In /opt/chef-solo/cpe_init/cache/cookbooks/cpe_profiles_local/resources/cpe_profiles.rb

 53:       osx_profile identifier do
 54:         profile nr_profile unless nr_profile.nil?
 55:         action nr_action
 56:       end
 57:     end

Compiled Resource:
------------------
# Declared in /opt/chef-solo/cpe_init/cache/cookbooks/cpe_profiles_local/resources/cpe_profiles.rb:53:in `block in osx_profiles_resource'

osx_profile("com.facebook.chef.filevault.enforce") do
  action [:remove]
  default_guard_interpreter :default
  declared_type :osx_profile
  cookbook_name "cpe_profiles_local"
end

System Info:
------------
chef_version=16.5.26
platform=mac_os_x
platform_version=11.0
ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin17]
program_name=/opt/chef/bin/chef-client
executable=/opt/chef/bin/chef-client
```

**Comment by erikng** [comment]
+1 on needing this functionality.

**Comment by tas50** [comment]
Fixed on master
