### ISSUE TITLE
support pwsh interpreter in powershell_script resource

### ISSUE THREAD

**Issue by mwrock** [chef/chef#10428]
Related to epic #10330 

By default, `powershell_script` will continue to use powershell.exe, but users can optionally specify `pwsh` as an interpreter. This will require pwsh (cross platform powershell) to be installed and on the path.

**Comment by lydz1209** [comment]
> Lié à des [#10330 épiques](https://github.com/chef/chef/issues/10330)
> 
> Par défaut, continuera d’utiliser powershell.exe, mais les utilisateurs peuvent éventuellement spécifier en tant qu’interprète. Cela nécessitera l’installation de pwsh (powershell de plate-forme croisée) et sur le chemin.`powershell_script``pwsh`
