### ISSUE TITLE
I'm curious if (and suggesting that) this could be approached in a non-disruptive way by adopting the "pwsh" or "core" nomenclature instead of "powershell" for all of the replacements that would opt into PowerShell Core. Using the above examples:

### ISSUE THREAD

**Issue by lydz1209** [chef/chef#10431]
I'm curious if (and suggesting that) this could be approached in a non-disruptive way by adopting the "pwsh" or "core" nomenclature instead of "powershell" for all of the replacements that would opt into PowerShell Core. Using the above examples:

- Infra Client internals updated for PowerShell Core (e.g. Chef::Pwsh, pwsh_out, pwsh_exec)
- Infra Client resources updated for PowerShell Core (e.g. pwsh_script)
- Infra Client resources updated for DSC Core (e.g. dsc_core_script, dsc_core_resource)

This would also give those wanting to consume PowerShell on non-Windows machines a clearly named resource for their use.

_Originally posted by @jeremyciak in https://github.com/chef/chef/issues/10330#issuecomment-690715064_

**Comment by mwrock** [comment]
closing this since it just contains duplicate content from #10330. I'm assuming this may have been opened by mistake but if we want to discuss this specific topic, we should continue to do so in #10330

**Comment by lamont-granquist** [comment]
If we do that then on day 1 there is zero powershell core support in any cookbook in the world, which seems like the wrong way to go and would require a lot of defensive coding like:

```
if powershell_core?
  pwsh_script "stuff do
  end
else
  powershell_script "stuff" do
  end
end
```

where the resources are nearly identical.

I'm not 100% against it if there's some good reason for it, but on the face of it, it seems the wrong approach.
