### ISSUE TITLE
The archive_file resource seems backwards

### ISSUE THREAD

**Issue by mal** [chef/chef#10448]
### Describe the Enhancement
The API of the `archive_file` resource is not immediately intuitive when coming to it with knowledge of other core Chef resources such as `file`, `remote_file`, `directory`, `scm` subtypes etc. It feels backwards since it's designed for the inverse purpose of what the obvious lizard-brain pattern-match assumption would be - that `archive_file '/path'` creates an archive file at that location.

A potential idea for a more "expected" way of doing things could be something like an `archive_directory "/path" { source "/archive" }` resource, which would be very close to the current `archive_file`  with some attribute swaps `path -> source`, `destination ->path` with the "new" `path` being the "name" attribute. This could extend `directory` and would end up with an API comparable to those resources mentioned previously, and `remote_directory` (itself a very oddly named resource - why isn't this `cookbook_directory`?)

### Describe the Need
It's not a need, more an API suggestion to help avoid potential confusion when encountering the `archive_file` resource. Having just been part of an internal effort to onboard and educate new Chef users this was one of the points raised as confusing. A parallel was even drawn to PHP's infamous method signature inconsistencies! D:

### Current Alternative
Learn the idiosyncrasies.

### Can We Help You Implement This?
Suspect this is sort of thing that might suffer the same fate as #7434, so just understanding if there is any appetite for it really. The current API is by now established, and while at times frustrating for new users, this isn't too much more than a small stumbling block in the grand scheme of things.

**Comment by lamont-granquist** [comment]
Yeah, this is an issue that needs a time machine to fix.  That ship sailed and the userbase doesn't have the tolerance for breaking changes that are necessary for functional reasons -- it definitely doesn't have the tolerance for breaking changes for ideosyncracies.  We've had devs in the past who tried to fix issues like this and it was not a good scene and the devs burned out and quit.
