### ISSUE TITLE
DRY HTTP chef server rest API object

### ISSUE THREAD

**Issue by vsingh-msys** [chef/chef#10458]
As of now, the chef server HTTP rest object has been initialized at various places like `Chef::ApiClient`, `Chef::ApiClientV1`, `Chef::Org`, `Chef::User` & `Chef::UserV1`, `Chef::DataBag`, `Chef::DataBagItem`, `Chef::Client` `Chef::Environment` etc.

To make this uniform need to create a mixin so it can accessible wherever we required.

Based on detailed discussion in PR https://github.com/chef/chef/pull/10187/ I would prefer we can decide  which version we should consume.

This issue will cover:

- Create a uniform rest object in chef mixin so that it can utilize everywhere.
- Refactored the code based on right version of the chef server API.

Some of code references:

1. https://github.com/chef/chef/blob/ebd04152f0310280c397ef4a269753cf34ef1c37/lib/chef/api_client/registration.rb#L159-L166

2. https://github.com/chef/chef/blob/ebd04152f0310280c397ef4a269753cf34ef1c37/lib/chef/api_client.rb#L149-L151

3. https://github.com/chef/chef/blob/ebd04152f0310280c397ef4a269753cf34ef1c37/lib/chef/api_client.rb#L223-L225

4. https://github.com/chef/chef/blob/ebd04152f0310280c397ef4a269753cf34ef1c37/lib/chef/api_client_v1.rb#L59-L69

5. https://github.com/chef/chef/blob/ebd04152f0310280c397ef4a269753cf34ef1c37/lib/chef/org.rb#L37-L39

6. https://github.com/chef/chef/blob/ebd04152f0310280c397ef4a269753cf34ef1c37/lib/chef/user.rb#L51-L53

7. https://github.com/chef/chef/blob/ebd04152f0310280c397ef4a269753cf34ef1c37/lib/chef/user.rb#L158

8. https://github.com/chef/chef/blob/ebd04152f0310280c397ef4a269753cf34ef1c37/lib/chef/user.rb#L175

9. https://github.com/chef/chef/blob/ebd04152f0310280c397ef4a269753cf34ef1c37/lib/chef/user_v1.rb#L57-L63

10. https://github.com/chef/chef/blob/ebd04152f0310280c397ef4a269753cf34ef1c37/lib/chef/data_bag.rb#L76-L82

**Comment by lamont-granquist** [comment]
This needs to not be done as a one-off and needs to be done as an epic to extract an entire chef-http gem with an object model, making something standalone which is similar to the ridley or chef-api gems, the object model objects should them inherit from common code and have common syntax.

This is not something that MSYS should be doing.

**Comment by lamont-granquist** [comment]
Also when you randomly start to DRY things you run into this issue:

https://sandimetz.com/blog/2016/1/20/the-wrong-abstraction

Where removing code duplication for only the sake of removing code duplication without larger thought into how the design should work and what the abstractions should be, you wind up creating a mess of abstractions which are hard to use.  There are examples of this in the codebase where for example clogeny "DRY"d the user providers and created a mess of inheretence and strange APIs which had to be backed out by re-duplicating the code and extracting the linux_user resource.
