### ISSUE TITLE
ifconfig resource can create lots of blank lines for an interface config file

### ISSUE THREAD

**Issue by haidangwa** [chef/chef#10457]
### Describe the Enhancement:

Improve the template defined by https://github.com/chef/chef/blob/master/lib/chef/provider/ifconfig/redhat.rb#L29-L47 and used to generate `/etc/sysconfig/network-scripts/ifcfg-*` files so it isn't loaded with blank lines when the if statements return a false value.

### Repro
Define this resource in a chef recipe:
```
ifconfig 'my-interface' do
  device 'my-interface'
  mask '255.255.255.255'
  bootproto 'none'
  onboot 'no'
end
```

### Describe the Need:

We use the ifconfig resource and many of the options referenced by https://github.com/chef/chef/blob/master/lib/chef/provider/ifconfig/redhat.rb#L29-L47 return false. This results in a file that has a lot of blank lines. It would be preferrable to have a compact file with little or no empty lines.

I setup an ifconfig resource configures a dummy interface successfully, then I look in the file to verify the contents I noticed a lot of empty lines.

```
# cat /etc/sysconfig/network-scripts/ifcfg-my-interface

DEVICE=my-interface

BOOTPROTO=none
IPADDR=192.168.20.18
NETMASK=255.255.255.255












          
```
Everything you see above after the `NETMASK` line was added by the ifconfig resource.

### Current Alternative

none that I know of

**Comment by jmherbst** [comment]
Would this just entail using the `'-'` trim mode on the ERB object https://github.com/chef/chef/blob/master/lib/chef/provider/ifconfig.rb#L239
```
template = ::ERB.new(@config_template, nil, '-')
```

Then refactoring the `config_template`s to leverage that trim mode? 
Example: 
```
<% if new_resource.device -%>
DEVICE=<%= new_resource.device %>
<% end -%>
<% if new_resource.onboot == "yes" -%>
ONBOOT=<%= new_resource.onboot %>
<% end -%>
```

I'd be happy to make this change, if desired.

Thanks

**Comment by phiggins** [comment]
Hi @jmherbst,

That is my impression as well, that using ERB's trim mode would fix the problem. If you'd like to submit a patch for that it would be appreciated.

Alternatively, using ERB for this seems a bit overkill so it might make sense to refactor the code to generate a string in a simpler fashion.

**Comment by jmherbst** [comment]
I believe this can be closed out now. Thanks for the suggestion @haidangwa and for the help @phiggins 👍
