### ISSUE TITLE
install.sh script doesn't install chef correctly in MacOS

### ISSUE THREAD

**Issue by ajayaa** [chef/chef#10477]
## Description

We deploy chef to a thousands of MacOS machines using the below script.
`curl -L -o /opt/foo/setup/install.sh https://chef.io/chef/install.sh && sudo bash /opt/foo/setup/install.sh -v 12.17.44`
Recently we started seeing issues where `chef-solo` wasn't found in the path `/usr/local/bin/`. Instead we found out that `/usr/local/bin` gets symlinked to `/opt/chef/bin/chef-client`. Ideally `/usr/local/bin/chef-client` should get symlinked to `/opt/chef/bin/chef-client` and likewise for `chef-solo`. Not sure if this is an issue with Apple installer or chef install script. As a temporary fix, we are using `chef-solo` from `/opt/chef/bin/chef-client`.

## Chef Version

12.17.44
## Platform Version

MacOS Catalina
## Client Output

```

```

**Comment by tas50** [comment]
@ajayaa Chef 12.17 has not been supported for several years. We currently support 15.x and 16.x releases. Those have had significant changes to how they're packages over 12.x. Please give this a try with a new release of Chef Infra Client and feel free to open it back up if you're still seeing the issue.
