### ISSUE TITLE
yum_package cannot :install libstdc++.i686 in common situations

### ISSUE THREAD

**Issue by karmix** [chef/chef#10485]
It is currently not possible to use the `:install` action of `yum_package` to ensure that multilib packages (those available as multiple packages for different architectures, such as `libstdc++.i686` and `libstdc++.x86_64`) are always present on a system; it fails in common scenarios.  (`dnf_package` probably has the same problem.)

## Description

I need to ensure that a number of prerequisite packages, including `libstdc++.i686`, are present during a converge before I begin to configure another application.  Ideally, I could just declare `package 'libstdc++.i686'` in the cookbook, but this often produces a YUM error.

`libstdc++.x86_64` gets installed with the core packages on every CentOS system.  When `yum_package` installs `libstdc++.i686`, it tries to install the latest version available.  If the version of `libstdc++.i686` that `yum_package` tries to install does not match the version of `libstdc++.x86_64` already present on the system, `yum` produces an error regarding a multilib version mismatch.  (Note: Where I talk about package version, I'm referring to the whole EVR (Epoch:Version-Release) of an RPM, not just an RPM's "version" attribute.)

I know of two methods for addressing this with YUM.  The first is to install the same version of the `libstdc++.i686` package as is already installed for `libstdc++.x86_64`.  The second is to pass both packages to yum in the install command, such as `yum install libstdc++.i686 libstdc++.x86_64`, in which case `yum` will install `libstdc++.i686` and update `libstdc++.x86_64` to a matching version at the same time.  The replication cases show the challenges with trying to make chef do each of these things, below.

Regardless whether I can find a good work around for this problem, I believe that a basic resource definition like `package 'libstdc++.i686'` should not fail on supported platforms when the package is readily available to install.  I am considering this behavior to be a bug.

## Chef Version
16.5.77

## Platform Version
All platforms that use YUM.  I used CentOS 7 to replicate, below.

## Replication Case

1. Create  the following files:
   * `metadata.rb` containing:

      ```ruby
      name 'example'
      version '1.0'
      ```

   * `recipes/scenario1.rb` containing:

      ```ruby
      package 'libstdc++.i686'
      ```

   * `recipes/scenario2.rb` containing:

      ```ruby
      package 'libstdc++' do
        arch 'i686'
        pkg = node['packages']['libstdc++']
        if pkg.key?('versions')
          pkg = pkg['versions'].find { |p| p['arch'] == 'x86_64' }
        end
        version "#{pkg['version']}-#{pkg['release']}"
      end
      ```

   * `recipes/scenario3.rb` containing:

      ```ruby
      package [ 'libstdc++.i686', 'libstdc++.x86_64' ]
      ```

   * `kitchen.yml` containing:

      ```yaml
      driver: { name: vagrant }
      provisioner: { name: chef_zero }
      platforms: [ { name: centos-7.6 } ]
      suites:
        - name: scenario1
          run_list: [ 'recipe[example::scenario1]' ]
        - name: scenario2
          run_list: [ 'recipe[example::scenario2]' ]
        - name: scenario3
          run_list: [ 'recipe[example::scenario3]' ]
      ```

1. Run `kitchen converge scenario1-centos-76` (see gist for output).

   `yum` will produce a large error message and `chef-client` will fail.  Specifically note the last few lines of output:

   ```
   Protected multilib versions: libstdc++-4.8.5-39.el7.i686 != libstdc++-4.8.5-36.el7_6.2.x86_64
   ---- End output of ["yum", "-y", "install", "libstdc++-0:4.8.5-39.el7.i686"] ----
   Ran ["yum", "-y", "install", "libstdc++-0:4.8.5-39.el7.i686"] returned 1
   ```

   Even though the package resource definition did not specify a package version, `chef-client` found the latest candidate version and specifically required that version when it ran `yum -y install libstdc++-0:4.8.5-39.el7.i686`.  `yum` aborted because installing the requested version would have produced a multilib version mismatch between `libstdc++.i686` and `libstdc++.x86_64`.  This is a rudimentary operation that I believe Chef should be able to handle successfully on the platforms it supports.

1. Run `kitchen converge scenario2-centos-76` (see gist for output).

   It will also fail.  This is my attempt to tell Chef to install the same version of `libstdc++.i686` as is being used by the already installed `libstdc++.x86_64`.  It works in many cases, but this time it fails because `libstdc++-4.8.5-36.el7_6.2.i686` is no longer in CentOS's primary yum repository; it has been rotated to the `C7.6.1810-updates` vault.  To install the package on this platform, you would first need to update your CentOS repo definitions so you could see the vault with `yum -y update centos-release`.  You could then install the package with `yum -y --enablerepo=C7.6.1810-updates install libstdc++-4.8.5-36.el7_6.2.i686`.

   This mostly seems like a CentOS issue, but in this case I can't easily predetermine whether a package has already been rotated out of a repository from the cookbook level, nor is this an error I can easily handle because `chef-client` aborts.  Also note that the code is getting hard to read; making chef choose a package version that `yum` can successfully install should not be this complicated.

1. Run `kitchen converge scenario3-centos-76` (see gist for output).

   It will fail with another multilib version conflict.  In this case, I tried to tell Chef to have yum install both packages at the same time.  Chef determined that `libstdc++.x86_64` was already installed and left it out of the request, as you can see from the last line of output `Ran ["yum", "-y", "install", "libstdc++-0:4.8.5-39.el7.i686"] returned 1`.  If I also set action `:update` for the resource, `chef-client` will succeed in installing a missing package, but it will also update the packages even when both are already present, which is not what I am trying to accomplish.

## Client Output
https://gist.github.com/karmix/4071eb9494adba4613b71714c8565758

## Stacktrace
Not Applicable.

**Comment by lamont-granquist** [comment]
Is this overly complicated bit important to the failure case or not?

```
package 'libstdc++' do
  arch 'i686'
  pkg = node['packages']['libstdc++']
  if pkg.key?('versions')
    pkg = pkg['versions'].find { |p| p['arch'] == 'x86_64' }
  end
  version "#{pkg['version']}-#{pkg['release']}"
end
```

My first suggestion would be to never use the arch+version properties if you're doing anything complicated, and to instead just do `package "libstdc++-#{pkg['version']}-#{pkg['release']}.i686"` because that goes through a much simpler codepath in the python helper which should perfectly mimic the `yum install` semantics.  The version+arch properties go through some code which hacks it up to try to make it behave like Chef expects and that tends to fail in certain circumstances.

**Comment by karmix** [comment]
No, it is not important to the failure case.  The failure case is simply scenario1, which shows that `package 'libstdc++.i686'` fails to install a package.  scenario2 and scenario3 are only there to illustrate that it is difficult to find a way to work around this problem in a cookbook.  They were meant to support my case that this should be addressed in `chef-client`, but perhaps they are making the report less clear.

After writing the PR, I know the code you are referring to and agree with your suggestion.  Even still, the code becomes something like
```ruby
pkg = node['packages']['libstdc++']
pkg = pkg['versions'].find { |p| p['arch'] == 'x86_64' } if pkg.key?('versions')
package "libstdc++-#{pkg['version']}-#{pkg['release']}.i686"
```
and it only gets more complicated if you aren't certain whether another package is actually present on a system.

I'm of the opinion that it should not be this complicated to safely install each multilib package, especially if you don't really care what the version is.  I believe `package 'libstdc++.i686'` is much easier to understand and maintain.

**Comment by lamont-granquist** [comment]
closing per discussion in #10487
