### ISSUE TITLE
undefined method to_yaml

### ISSUE THREAD

**Issue by paulatAppd** [chef/chef#10492]
## Chef Version
Starting Chef Infra Client, version 16.5.77

## Platform Version
  platform=centos
  platform_version=7.8.2003
  ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]

## Replication Case
running chef-client
The recipe chef-client is failing on has been functioning since 2018 and worked in the previous version of chef-client.

# Recipe
# In /var/chef/cache/cookbooks/base/recipes/_gemrc.rb
      template chef_gemrc do
        source 'gemrc.erb'
        owner 'root'
        group 'root'
        mode '644'
     end.run_action(:create)

# Template Context:
<%= JSON.parse((node['appd-base']['gemrc']).to_json, symbolize_names: true).to_yaml %>

## Client Output
    ================================================================================
    Error executing action `create` on resource 'template[/opt/chef/embedded/etc/gemrc]'
    ================================================================================

    Chef::Mixin::Template::TemplateError
    ------------------------------------
    undefined method `to_yaml' for #<Hash:0x0000000004d28e68>

## Stack Trace 
>>>> Caused by NoMethodError: undefined method `to_yaml' for #<Hash:0x0000000004af5628>
/var/chef/cache/cookbooks/base/templates/default/gemrc.erb:5:in `block in evaluate'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `evaluate'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.77/lib/chef/mixin/template.rb:161:in `_render_template'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.77/lib/chef/mixin/template.rb:146:in `render_template'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.77/lib/chef/provider/template/content.rb:77:in `file_for_provider'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.77/lib/chef/file_content_management/content_base.rb:42:in `tempfile'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.77/lib/chef/provider/file.rb:455:in `tempfile'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.77/lib/chef/provider/file.rb:329:in `do_generate_content'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.77/lib/chef/provider/file.rb:141:in `block in <class:File>'
(eval):2:in `block in action_create'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.77/lib/chef/provider.rb:276:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.77/lib/chef/provider.rb:276:in `compile_and_converge_action'
(eval):2:in `action_create'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.77/lib/chef/provider.rb:217:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.77/lib/chef/resource.rb:599:in `block in run_action'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.77/lib/chef/resource.rb:626:in `with_umask'
/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.5.77/lib/chef/resource.rb:598:in `run_action'
/var/chef/cache/cookbooks/base/recipes/_gemrc.rb:27:in `from_file'

**Comment by phiggins** [comment]
This was an unfortunate regression caused by changing how ruby dependencies were loaded in order to speed up loading times. See  #10470 for more information.

You've got a few ways to fix this in your code:
* `require yaml` before any code that uses the `to_yaml` extension
* Change uses of `object.to_yaml` to `YAML.dump(object)`

**Comment by paulatAppd** [comment]
Thank you for those workarounds. 
Do you know when the regression be fixed in chef?

**Comment by phiggins** [comment]
I'm not sure it will be. If your code is relying on something from ruby's stdlib to be loaded, your code should explicitly handle that dependency.

**Comment by phiggins** [comment]
> Is that the recommended best practice then, Whenever you need something from ruby's stdlib is to use 'require THING'?

I can't speak for Chef's official position on this, but yes that would be my recommendation.

> When functionality like this changes does it normally get documented?

The underlying change was from using `require` to `autoload` to load ruby libraries. This is mostly seamless as code that, for example, referenced the `YAML` constant would continue to work with no changes. Depending on Chef requiring yaml causing the `to_yaml` extension is the type of thing that broke. This wasn't an intentional change so its unlikely it would get documented.

**Comment by lamont-granquist** [comment]
using `YAML.dump( <stuff> )` instead of `<stuff>.to_yaml` will also cause the library to autoload correctly, and avoid the monkeypatch, which is in general a good thing.

**Comment by tas50** [comment]
I've added a Cookstyle rule to catch this in the Cookstyle 6.21 release. It will autocorrect any .to_yaml code to be YAML.dump() instead. You can either pull in that new gem or make that change manually.
