### ISSUE TITLE
value_for_platform is evaluating all the values despite of the OS 

### ISSUE THREAD

**Issue by enrico-usai** [chef/chef#10493]
Hi,

I have the following use case.
One of the values to be used in `value_for_platform` is calculated with a function that is RHEL specific and that should be called only for `centos` cases. 

The function is defined in the `helpers.rb` file. The bad is that the function is called in the `ubuntu` case too.
```
default['myattribute'] = value_for_platform(
  'centos' => {
    '>=8' => "https://package/el/8/x86_64/",
    'default' => "https://package/el/7.#{get_rhel7_kernel_minor_version}/x86_64/"
  },
  'ubuntu' => { 'default' => "https://package/ubuntu" }
)
```

How can I get this behaviour?

**Comment by phiggins** [comment]
The `value_for_platform` function decides on a value from the hash by looking at values on `node`. If you want very specific behavior that `value_for_platform` does not support, you're probably better off writing custom code to handle that.

**Comment by enrico-usai** [comment]
Ok, thanks @phiggins
