### ISSUE TITLE
Resource "benchmarking"

### ISSUE THREAD

**Issue by Lasering** [chef/chef#10497]
### Describe the Enhancement:
The Chef client should list at the end of the run the resources which took the longest to run.

### Describe the Need:
This would allow the developer to optimize those resources and get a faster development cycle.

### Can We Help You Implement This?:
Here is a working implementation, further improvements could be made like having a flag in client.rb.

```ruby
chef_gem 'time_difference' do
  compile_time true
end
require 'time_difference'
require 'time'

times = {}
zero = Time.at(0)
Chef.event_handler do
  on :resource_completed do |resource|
    time = resource.elapsed_time.to_i
    if time > 0
      human_time = TimeDifference.between(zero, zero + time).humanize
      times[resource.to_s] = [time, human_time]
      print("\t\t Took #{human_time}\n")
    end
  end
  on :run_completed do
    print("Slowest resources to run:\n")
    times.sort_by { |_, v| v.first }.reverse!.take([10, times.size].min).each do |name, time|
      print("\t\t#{name} took #{time[1]}\n")
    end
  end
end
```

**Comment by tas50** [comment]
I think it would potentially be really helpful to have some sort of per resource timing exposed by a flag in chef-client.  chef-client --benchmark would give you additional benchmark logging.

**Comment by lamont-granquist** [comment]
resources already have elapsed time in them, this can be done by using the action collection to not waste more memory capturing every resource object:

https://github.com/chef/chef/blob/master/docs/dev/design_documents/action_collection.md

**Comment by tas50** [comment]
While I think this would be pretty useful it's not something that's going to get prioritized by the team. If you'd like to build this sort of functionality using the data that lamont mentioned that would be great, but at this point I'm going close this issue out.
