### ISSUE TITLE
Ruby 2.6 endless Range syntax cause syntax error

### ISSUE THREAD

**Issue by Paxa** [chef/chef#10496]
This commit https://github.com/chef/chef/commit/6ecacec32423b116e64fdcc11be0e8e18ce94706 make it incompatible with ruby < 2.6. We use chef 12, and somehow in CI it use 

```
$ bundle exec berks install
/home/gitlab-runner/builds/n9ma2zXY/0/gopay_apps_infra/gobills_inquiry_service_cookbook/.local/ruby/2.3.0/bin/berks:23:in `load': /home/gitlab-runner/builds/n9ma2zXY/0/gopay_apps_infra/gobills_inquiry_service_cookbook/.local/ruby/2.3.0/gems/chef-config-16.5.77/lib/chef-config/config.rb:652: syntax error, unexpected ']' (SyntaxError)
        value[1..].to_sym
                  ^
	from /home/gitlab-runner/builds/n9ma2zXY/0/gopay_apps_infra/gobills_inquiry_service_cookbook/.local/ruby/2.3.0/bin/berks:23:in `<main>'
```

Possible solution: set required_ruby_version in gemspec

https://guides.rubygems.org/specification-reference/#required_ruby_version

<img width="404" alt="Screen Shot 2020-10-12 at 20 38 30" src="https://user-images.githubusercontent.com/26019/95747761-8be70680-0ccb-11eb-8162-ead7bda5a801.png">

https://rubygems.org/gems/chef-config/versions/16.5.77

**Comment by tas50** [comment]
Chef 12 is EOL as is both 13 and 14. At this point you're going to need to pin pretty aggressively to avoid bringing in dependencies with that old of a release. You'll want to look at what gem is trying to pull in chef-utils and pin to an older version of that in your CI.

**Comment by Paxa** [comment]
I'm not asking to fix chef 12 or 13 or 14. But to set `required_ruby_version` in gemspec for sub-gems, so bundler will pick a right version or show meaningful error message

It will also help whose who use chef 15 with ruby < 2.6

In my case chef-config comes from `berkshelf -> ridley -> chef-config`

**Comment by lbjay** [comment]
Excuse me, why was this closed? I'm experiencing the same issue, same situation.
