### ISSUE TITLE
Update ifconfig resource to support the new Network Manager keyfile format

### ISSUE THREAD

**Issue by tas50** [chef/chef#10556]
Fedora 33 and later (and probably RHEL 9+) switched from the legacy ifcfg format used by Network Manager to the keyfile format. This stores all network configs at /etc/NetworkManager/system-connections instead. The format is probably workable with the set of properties we have. We just need to build a provider for Fedora 33+ / RHEL 9+ that uses this format.

**Comment by tas50** [comment]
Testing of ifconfig on Fedora 33+ disabled in https://github.com/chef/chef/pull/10555

**Comment by tas50** [comment]
See https://fedoraproject.org/wiki/Changes/NetworkManager_keyfile_instead_of_ifcfg_rh for details on the change

**Comment by tas50** [comment]
Related to https://github.com/chef/chef/issues/3862

**Comment by lamont-granquist** [comment]
closing as dup of #3862
