### ISSUE TITLE
Ruby 3.0 Deprecation Warnings. Chef Client needs to Ruby 3.0.

### ISSUE THREAD

**Issue by balkarsinghkang** [chef/chef#10571]
## Description
After upgrading chef client to 16.6.14, ruby depreciation warnings are generated from win32-process gem.

Chef Infra Client finished, 7/140 resources updated in 02 minutes 12 seconds
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/win32-process-0.8.3/lib/win32/process.rb:744:in `kill': warning: $SAFE
 will become a normal global variable in Ruby 3.0 (StructuredWarnings::BuiltInWarning)
C:/opscode/chef/embedded/lib/ruby/gems/2.7.0/gems/win32-process-0.8.3/lib/win32/process.rb:744:in `kill': warning: $SAFE
 will become a normal global variable in Ruby 3.0 (StructuredWarnings::BuiltInWarning)

## Chef Version
chef-client version 16.6.14

## Platform Version
Windows 2016

## Replication Case
Upgraded the cookbook with cookstyle.
Upgraded the client with version 16.6.14
Chef-client throws these warning messages.
When we commented audit repipe from the run_list, these warning message disappear. It seems like audit cookbook is causing this.

## Client Output

```
[debug.txt](https://github.com/chef/chef/files/5455229/debug.txt)
```

**Comment by tas50** [comment]
This is technically for win32-process gem, but it's useful to track it here since the impact is on chef/chef.
