### ISSUE TITLE
windows_audit_policy fails when using chef in local mode

### ISSUE THREAD

**Issue by trickyearlobe** [chef/chef#10624]
## Description
When calling `windows_audit_policy` resource in chef-client local mode (-z), we get a notice about a missing DLL.

Problem doesn't occur if I install Chef Client package instead of workstation package.

There is some [some seemingly relevant context](https://discourse.chef.io/t/using-powershell-exec-in-chef-shell-could-not-open-library-chef-powershell-wrapper-dll/16082) suggesting that `powershell_exec` (used by the `windows_audit_policy` resource) has questionable support status, but since its used by `windows_audit_policy` which is a supported resource, we should probably ship the DLL in workstation or have the chef-client team rewrite the `windows_audit_policy` resource.

```
LoadError
---------
Could not open library 'Chef.PowerShell.Wrapper.dll': The specified module could not be found.

Cookbook Trace: (most recent call first)
----------------------------------------
  c:/chef/local-mode-cache/cache/cookbooks/lbg_na_windows_10/recipes/default.rb:14:in `from_file'

Relevant File Content:
----------------------
c:/chef/local-mode-cache/cache/cookbooks/lbg_na_windows_10/recipes/default.rb:

  7:  windows_audit_policy 'Logon' do
  8:    action :set
  9:    subcategory "Logon"
 10:    success true
 11:    failure true
 12:  end
 13:

System Info:
------------
chef_version=16.4.38
platform=windows
platform_version=10.0.18363
ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]
program_name=C:/opscode/chef-workstation/bin/chef-client
executable=C:/opscode/chef-workstation/bin/chef-client
```

## Chef Workstation Version
20.8.125

## Platform Version
Windows 10

**Comment by tas50** [comment]
Moving this to chef/chef where it belongs

**Comment by mwrock** [comment]
Looking at 20.8.125, the DLL is definitely not where it is supposed to be. I installed the latest version 20.10.168 and the DLLs are installed correctly and I have confirmed that `powershell_exec` works.
