### ISSUE TITLE
Error when running knife solo cook command

### ISSUE THREAD

**Issue by mgivi** [chef/chef#10636]
Hi there,
I installed the latest version of chef with these configuration
`gem "berkshelf", "~> 7.0.10"

gem "chef", "~> 16.6.14"
gem "knife-solo", "~> 0.7.0"
gem "knife-ec2", "~> 2.1.0"`

But when I run the command knife solo cook ubuntu@xxxx.com I get these errors:
Traceback (most recent call last):
	14: from /usr/local/bin/knife:23:in `<main>'
	13: from /usr/local/bin/knife:23:in `load'
	12: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/bin/knife:24:in `<top (required)>'
	11: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/application/knife.rb:165:in `run'
	10: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife.rb:224:in `run'
	 9: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife.rb:161:in `subcommand_class_from'
	 8: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:129:in `command_class_from'
	 7: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:115:in `load_command'
	 6: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:105:in `load_commands'
	 5: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:105:in `each'
	 4: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:105:in `block in load_commands'
	 3: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:105:in `load'
	 2: from /Library/Ruby/Gems/2.6.0/gems/knife-windows-0.8.2/lib/chef/knife/winrm.rb:20:in `<top (required)>'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- chef/knife/winrm_base (LoadError)
	21: from /usr/local/bin/knife:23:in `<main>'
	20: from /usr/local/bin/knife:23:in `load'
	19: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/bin/knife:24:in `<top (required)>'
	18: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/application/knife.rb:165:in `run'
	17: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife.rb:224:in `run'
	16: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife.rb:161:in `subcommand_class_from'
	15: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:129:in `command_class_from'
	14: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:115:in `load_command'
	13: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:105:in `load_commands'
	12: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:105:in `each'
	11: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:105:in `block in load_commands'
	10: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:105:in `load'
	 9: from /Library/Ruby/Gems/2.6.0/gems/knife-windows-0.8.2/lib/chef/knife/winrm.rb:20:in `<top (required)>'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:217:in `try_activate'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1418:in `activate'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:2302:in `raise_if_conflicts': Unable to activate em-winrm-0.6.0, because winrm-2.3.5 conflicts with winrm (~> 1.2.0) (Gem::ConflictError)
	22: from /usr/local/bin/knife:23:in `<main>'
	21: from /usr/local/bin/knife:23:in `load'
	20: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/bin/knife:24:in `<top (required)>'
	19: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/application/knife.rb:165:in `run'
	18: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife.rb:224:in `run'
	17: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife.rb:161:in `subcommand_class_from'
	16: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:129:in `command_class_from'
	15: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:115:in `load_command'
	14: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:105:in `load_commands'
	13: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:105:in `each'
	12: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:105:in `block in load_commands'
	11: from /Library/Ruby/Gems/2.6.0/gems/chef-16.6.14/lib/chef/knife/core/subcommand_loader.rb:105:in `load'
	10: from /Library/Ruby/Gems/2.6.0/gems/knife-windows-0.8.2/lib/chef/knife/winrm.rb:20:in `<top (required)>'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:216:in `try_activate'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:223:in `rescue in try_activate'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1418:in `activate'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:2302:in `raise_if_conflicts': Unable to activate em-winrm-0.6.0, because winrm-2.3.5 conflicts with winrm (~> 1.2.0) (Gem::ConflictError)

**Comment by phiggins** [comment]
Hi,

`knife-solo` looks to be unmaintained and specifically mentions not keeping up with development of recent releases of Chef: https://github.com/matschaffer/knife-solo

It is likely that knife-solo does not work with recent releases of Chef. Your best options then are to figure out an alternative to knife-solo or figure out the last compatible release of Chef and pin to that.

Regardless, supporting unmaintained 3rd party software is out of scope for Chef's issue tracker.
