### ISSUE TITLE
user resource doesn't say what changed

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#10645]
Same as #10640 but for the `user` resource

## Description

Just says "user altered" which is not useful, it should say what changed as other resources do.

## Chef Version
16.6.14

## Platform Version
Windows, Linux

**Comment by bby-bishopclark** [comment]
you may be able to pull something from my discarded pull/7716 .

**Comment by jaymzh** [comment]
Thanks @bby-bishopclark looks like you did similar to what I did for the `group` resource in #10642 ... so yeah I imagine fixing user will be similar.

**Comment by bby-bishopclark** [comment]
Yeah.  Sorry it didn't get anywhere back then.

**Comment by jaymzh** [comment]
I'll have a PR today

**Comment by bby-bishopclark** [comment]
that's great news!  I can't use 15+, but I'm glad it'll be fixed somewhere.

**Comment by jaymzh** [comment]
@bby-bishopclark you can use cinc if the licensing is an issue. Same code.

**Comment by bby-bishopclark** [comment]
> @bby-bishopclark you can use cinc if the licensing is an issue. Same code.

Yep.  As mentioned elsewhere, that's the plan once they figure out yum repos and if they don't have the same trapdoor.  Thanks for the suggestion, though.

**Comment by jaymzh** [comment]
> Yep. As mentioned elsewhere, that's the plan once they figure out yum repos and if they don't have the same trapdoor.
> Thanks for the suggestion, though.

Huh? It doesn't require accepting EULAs, if that's what you mean by "trap door"... been using it for over a year now.

**Comment by bby-bishopclark** [comment]
We're getting off-topic, but that's great news if Cinc avoids the trapdoor.  Now, if they can look back in time and recover the lost art of yum repos, it'll achieve minimal viability.
