### ISSUE TITLE
knife bootstrap gateway forces identity

### ISSUE THREAD

**Issue by ct0br0** [chef/chef#10649]
ubuntu - chef-workstation 0.17.5
fedora - chefdk 4.7.73

Trying to bootstrap a node with a gateway errors out.

It seems like it is trying to use a gateway identity.

Someone else was using chefdk 3.9.0 and able to bootstrap the same box.
Installed 3.9.0 and sure enough it works.

```
knife bootstrap -G user@jump x.x.x.x -U root -N hostname.com --sudo --environment prod
Connecting to x.x.x.x
user@jump: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password,keyboard-interactive).
ERROR: Train::Transports::SSHFailed: SSH command failed (command failed: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o BatchMode=yes -o LogLevel=ERROR -o ForwardAgent=no user@jump -p 22 -W x.x.x.x:22)
```

Aha! Link: https://chef.aha.io/features/SH-1712

**Comment by tas50** [comment]
Closing this out since we were unable to get additional information on the problem.

**Comment by hachi** [comment]
Hang on, you didn't ask for more information, you said it was needing testing... This is still a problem (I'm hitting it today)

```
hachi@bastion-sjc3226:~$ knife --version
Chef Infra Client: 15.7.32
```
