### ISSUE TITLE
windows_user resource always updates password

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#10657]
## Description

Kinda related to #10455 it turns out that the `windows_user` resource doesn't seem to be able to set (or perhaps check) the password. No matter what you set it to, it tries to reset it everytime (and the password doesn't work, so I'm pretty sure it's failing to set it).

## Chef Version
15.9.17

## Platform Version
Windows 10

## Replication Case
```
user 'test' do
  ...
  password 'test'
end
```

**Comment by jaymzh** [comment]
CC @mwrock and @phiggins who probably can dig into this

**Comment by jaymzh** [comment]
Silly GH, I said it does _not_ close this.

**Comment by snehaldwivedi** [comment]
Hello @jaymzh, 
I have tried to replicate this issue on chef 17 as well as on chef 15 on Windows 10 but it's working fine. Following are the steps I have followed with an `admin account`

Here I have created a user
```
user 'testuser' do
  comment 'A random user'
  shell '/bin/bash'
  password 'Pass@123456'  
  action :create
end
```

```
recipe: (chef-apply cookbook)::(chef-apply recipe)
  * windows_user[testuser] action create
    - create user testuser
```
 
here I have modified its password 
  
recipe:
```
user 'testuser' do
  comment 'A random user will be changed'
  uid 2001
  shell '/bin/bash'
  password 'pass@12345' 
  action :modify # :create 
end
```

```
PS C:\users\Administrator\chef> chef-apply C:\Users\Administrator\Documents\user_test.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * windows_user[testuser] action modify
    - modify user testuser
```

It works fine if we created or modify users through the admin account, without admin access it gives the following issue 

```
Missing Windows Admin Privileges
    --------------------------------
    chef-client doesn't have administrator privileges. This can be a possible reason for resource failure.
```
 
 Please try it once on the latest chef version, also check which account you are using for this. And if still, you face the same issue please let us know with more details.
 
 Thanks

**Comment by snehaldwivedi** [comment]
Hello @jaymzh, have you checked with the latest version?

**Comment by snehaldwivedi** [comment]
@jaymzh we are closing this issue, for now, please check it on the latest version and if the issue still persists please reopen it.
