### ISSUE TITLE
Knife bootstrap throws error after successful run

### ISSUE THREAD

**Issue by mcascone** [chef/chef#10655]
## Description
Bootstrap windows operation throws an error at the end of the run, even though it's successful. I see this happen when the `powershell` download attempt fails, but the backup method works.

It appears to be rooted in a TLS error, i have been able to get around this when curl'ing with powershell manually by using `-k` (i think) to either ignore TLS or force it to a higher version (i don't remember the details of that one).

The bootstrap succeeds and i can proceed normally, but the error message is unnerving and could throw downstream scripts off if it is coming back as `failed` when it actually hasn't.

## Chef Version
> chef -v
Chef Workstation version: 20.9.136
Chef Infra Client version: 16.4.41
Chef InSpec version: 4.22.22
Chef CLI version: 3.0.27
Chef Habitat version: 1.6.56
Test Kitchen version: 2.6.0
Cookstyle version: 6.16.10
## Replication Case
```powershell
knife bootstrap -o winrm my-vm-fqdn -N my-vm-name -U $user -P $pass --node-ssl-verify-mode none --tags 'tag1, tag2' -y
```

## Client Output
```
... initial bootstrap stuff ...

> No existing installation of Chef Infra Client detected
> Checking for existing downloaded package at "C:\Users\SP_PIP~1\AppData\Local\Temp\chef-client-latest.msi"
> No existing downloaded packages to delete.
> Attempting to download client package using PowerShell if available...
> powershell.exe -ExecutionPolicy Unrestricted -InputFormat None -NoProfile -NonInteractive -File  C:\chef\wget.ps1 "https://www.chef.io/chef/download?p=windows&pv=2012r2&m=x86_64&DownloadContext=PowerShell&channel=stable&v=16" "C:\Users\SP_PIP~1\AppData\Local\Temp\chef-client-latest.msi"
> Warning: Failed to download "https://www.chef.io/chef/download?p=windows&pv=2012r2&m=x86_64&DownloadContext=PowerShell&channel=stable&v=16" to "C:\Users\SP_PIP~1\AppData\Local\Temp\chef-client-latest.msi"
> Warning: Retrying download with cscript ...
> Download via cscript succeeded.

.... chef-client install proceeds and succeeds ....

ERROR: The following error occurred on FR4VPARESS01.consilio.com:
ERROR: cmd.exe : Exception calling "DownloadFile" with "2" argument(s): "The request was
         + CategoryInfo          : NotSpecified: (Exception calli...he request was :String) [], RemoteException
         + FullyQualifiedErrorId : NativeCommandError
     aborted: Could not create SSL/TLS secure channel."
     At C:\chef\wget.ps1:14 char:1
     + $webClient.DownloadFile($remoteUrl, $localPath);
     + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
         + FullyQualifiedErrorId : WebException

     Failed download: download completed, but downloaded file not found
> <end>
```

## Stacktrace
N/A. Thanks everyone!

**Comment by mwrock** [comment]
This should go away when #10574 is shipped.

**Comment by mcascone** [comment]
Thank you Matt! I'll keep an eye on the changelogs!

**Comment by mcascone** [comment]
@mwrock , i just noticed in another recipe of mine, that i was having a similar issue rooted in the TLS version. 
The native `windows_package` resources were failing because of the TLS error. I had to add `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12` to get `Install-Module` and `Install-PackageProvider` in a `powershell_script` resource to be able to install these items. Will the PR you referenced address this type of TLS issue as well?
Thanks in advance!

**Comment by mwrock** [comment]
Hmm. No it will not. But for modules, you can use `powershell_package` which will ensure TLS level.
