### ISSUE TITLE
support winget package manager

### ISSUE THREAD

**Issue by mwrock** [chef/chef#10668]
This spring (2020) Microsoft announces the new [Windows Package Manager](https://devblogs.microsoft.com/commandline/windows-package-manager-preview/). We should probably create a resource to support this.

**Comment by johnmccrae** [comment]
Blocked - The 'enabled' features aren't sufficient to let us create idempotency. I'll reconvene when the tool is more complete.

**Comment by tas50** [comment]
Closing this pending winget having full support in the OS

**Comment by johnmccrae** [comment]
Winget finally released in early-ish 2021. We can put this ticket back into rotation again.
