### ISSUE TITLE
chef-utils required ruby version constraint `>= 2.6.0` conflicts with InSpec cloud resource packs

### ISSUE THREAD

**Issue by omerdemirok** [chef/chef#10698]
Ruby version **2.5** is still supported by the InSpec cloud resource packs.

`chef-utils` requires ruby **2.6.0** minimum, and this conflict breaks the CI tests.
https://github.com/chef/chef/blob/59959ba8678d5fbfc8e612c3b994e8b799c393f3/chef-utils/chef-utils.gemspec#L16

https://buildkite.com/chef-oss/inspec-inspec-azure-master-verify/builds/505#f7e89f79-a91e-4523-8ba5-56a78dd6e6d6

```
Gem::RuntimeRequirementNotMetError: chef-utils requires Ruby version >= 2.6.0.
--
  | The current ruby version is 2.5.8.224.
  | An error occurred while installing chef-utils (16.7.61), and
  | Bundler cannot continue.
  | Make sure that `gem install chef-utils -v '16.7.61' --source
  | 'https://rubygems.org/'` succeeds before bundling.
  |  
  | In Gemfile:
  | inspec-bin was resolved to 4.23.15, which depends on
  | inspec was resolved to 4.23.15, which depends on
  | inspec-core was resolved to 4.23.15, which depends on
  | chef-telemetry was resolved to 1.0.14, which depends on
  | chef-config was resolved to 16.7.61, which depends on
  | mixlib-shellout was resolved to 3.2.2, which depends on
  | chef-utils
  | 🚨 Error: The command exited with status 1
```

Could this change be reverted until **2.5** is deprecated entirely throughout all products?
What would be the best approach?

**Comment by tas50** [comment]
Chef Infra has a N-1 support cycle with Ruby so we currently support Ruby 2.6 and 2.7. It was pointed out that we weren't properly setting the ruby version required in chef-config and chef-utils so we added that for the 16.7 release. Previous releases didn't fully work on Ruby < 2.6 either as made calls in several places that requires 2.6. The InSpec project has chosen to support older releases of Ruby, but that may require some pinning of other libraries to be possible. This is pretty common requirement once you start using older version of Ruby and it's something we have to do ourselves quite a bit to keep some of our libraries working on older Ruby releases. It's possible we could just drop Ruby 2.5 in InSpec, but until that time you'll want to pin chef < 16 in your Gemfile if you need InSpec on Ruby 2.5
