### ISSUE TITLE
Determine if we can speed up the 25 minute windows certificate tests

### ISSUE THREAD

**Issue by tas50** [chef/chef#10696]
By far the worst offender in our Windows tests is the windows_certificate testing we perform. The tests in spec/functional/resource/windows_certificate_spec.rb take ~25 minutes to run in CI. Anything we can do there would be a huge win for the overall test times.

**Comment by Xorima** [comment]
Hey @tas50 

how do I get these tests to run locally so I can look into fixing this stuff?

Thanks
