### ISSUE TITLE
cron_d resource is not adding job under crontab -l using chef

### ISSUE THREAD

**Issue by AnamikaN** [chef/chef#10712]
i have created this cron resource in my recipe. It is creating file 'log-deletion' in /etc/cron.d. But when i ran crontab -l to see list of cron jobs. I dont see my cron job. What am i missing?

cron_d 'log-deletion' do
    minute '30'
    hour '00'
    user 'root'
    command '/usr/bin/find /var/log/kafka -mtime +365 -exec rm {} \;'
    action :create
end

[root@server1]# crontab -l
0 0 */3 * * /home/tmp_cleanup.sh

[root@server1]# cat /etc/cron.d/log-deletion
# Generated by Chef. Changes will be overwritten.

30 00 * * * root /usr/bin/find /var/log/kafka -mtime +365 -exec rm {} \;

[root@server1]# ps -ef | grep cron
root      1042     1  0 May09 ?        00:01:06 /usr/sbin/crond -n
root     22189 17656  0 09:15 pts/1    00:00:00 grep --color=auto cron

**Comment by tas50** [comment]
@AnamikaN Can you give more details on the version of Chef Infra Client you're running and the platform you're running it on?

**Comment by AnamikaN** [comment]
@tas50 Thank you for your response. But i think, i am good. cron_d resource create cron file under /etc/cron.d and when i checked the logs, i can see that my job ran.

Dec  7 00:01:01 server1 run-parts(/etc/cron.hourly)[23507]: finished 0anacron
Dec  7 00:10:01 server1 CROND[24983]: (root) CMD (/usr/lib64/sa/sa1 1 1)
Dec  7 00:20:01 server1 CROND[26680]: (root) CMD (/usr/lib64/sa/sa1 1 1)
**Dec  7 00:30:01 server1 CROND[28317]: (root) CMD (/usr/bin/find /var/log/kafka -mtime +365 -exec rm {} \;)** (my cron job)
Dec  7 00:30:01 server1 CROND[28318]: (root) CMD (/usr/lib64/sa/sa1 1 1)
Dec  7 00:40:01 server1 CROND[29991]: (root) CMD (/usr/lib64/sa/sa1 1 1)

**Comment by tas50** [comment]
Thanks for the heads up @AnamikaN
