### ISSUE TITLE
rhsm_subscription doesn't clear cache leading to yum_package failures

### ISSUE THREAD

**Issue by jasonwbarnett** [chef/chef#10722]
## Description

When you attach to a new subscription using the `rhsm_subscription` resource and then the `package` resource to install something sourced from that subscription it fails.

## Chef Version

v15.3.8

## Platform Version

Red Hat Enterprise Linux 7.8

## Replication Case

```ruby
rhsm_subscription 'pool_id_goes_here'

package 'package_from_subscription'
```

I wish I could give a publicly available example but my use case is a private RPM in our internal Red Hat Satellite server.

## Client Output

```text
           * No candidate version available for package_from_subscription
           ================================================================================
           Error executing action `install` on resource 'yum_package[package_from_subscription]'
           ================================================================================

           Chef::Exceptions::Package
           -------------------------
           No candidate version available for package_from_subscription

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/test-cookbook/recipes/default.rb
            33: package 'package_from_subscription'
            34: 

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/test-cookbook/recipes/default.rb:33:in `from_file'
           yum_package("package_from_subscription") do
             package_name "package_from_subscription"
             action [:install]
             default_guard_interpreter :default
             declared_type :package
             cookbook_name "test-cookbook"
             recipe_name "default"
           end

           System Info:
           ------------
           chef_version=15.13.8
           platform=redhat
           platform_version=7.8
           ruby=ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client
```

**Comment by jasonwbarnett** [comment]
I would expect this resource to call `PythonHelper.instance.reset` when it's updated. Does that even make sense?

**Comment by jasonwbarnett** [comment]
@tas50 are you IS with the proposed solution? If not, can you give me some general guidance so I can work on a bugfix for this?

**Comment by tas50** [comment]
@lamont-granquist should probably chime in on how to reload the cache there.

**Comment by lamont-granquist** [comment]
`instance.restart` is what you'd need, which is what `flush_cache` calls (which is the workaround which is to send a `:flush_cache` event to any package provider as a notify from the rhsm_subscription resource)

**Comment by jasonwbarnett** [comment]
> `instance.restart` is what you'd need, which is what `flush_cache` calls (which is the workaround which is to send a `:flush_cache` event to any package provider as a notify from the rhsm_subscription resource)

Sorry, I'm unable to make the lateral connection. Can you be more specific on the correct solution?
