### ISSUE TITLE
locale resource times out after 600 s

### ISSUE THREAD

**Issue by janskarvall** [chef/chef#10737]
## Description

Cooking a node with a recipe that includes:
<pre>
locale 'set locale' do
    lang "en_US.UTF-8"
end
</pre>
fails before completed.

I'm lacking a way to extend the timeout value.

## Chef Version

Chef Infra Client, version 16.6.14
## Platform Version

Ubuntu 20.04 LTS
## Replication Case

This is too hard to replicate. I am cooking the same node as the Chef Workstation runs on using a modified version of [knife solo](https://github.com/matschaffer/knife-solo).
## Client Output

<pre>
  * locale[set locale] action update
    
    ================================================================================
    Error executing action `update` on resource 'locale[set locale]'
    ================================================================================
    
    Mixlib::ShellOut::CommandTimeout
    --------------------------------
    Command timed out after 600s:
    Command exceeded allowed execution time, process terminated
    ---- Begin output of locale-gen ----
    STDOUT: Generating locales (this might take a while)...
      aa_DJ.ISO-8859-1... done
      aa_DJ.UTF-8... done
     :
      sm_WS.UTF-8...
    STDERR: 
    ---- End output of locale-gen ----
    Ran locale-gen returned 
    :
</pre>

## Stacktrace

N/A

**Comment by tas50** [comment]
We should be able to just kick up the timeout in the shell_out call in this method. I've tagged this for our sustaining engineering team so it can be updated. Thanks for the issue @janskarvall
