### ISSUE TITLE
Evaluate all uses of Dir.glob to see if we want to turn off sorting in Ruby 3

### ISSUE THREAD

**Issue by tas50** [chef/chef#10795]
Ruby 3.0 sorts Dir.glob by default now, which is handy but also slows down execution. We should look at all the places we use Dir.glob and determine if we care if the results are sorted or not:

https://rubyreferences.github.io/rubychanges/3.0.html#dirglob-and-dir-result-sorting

**Comment by coldiron** [comment]
Hello,

Could I work on this, please?

**Comment by tas50** [comment]
@coldiron certainly. One of the big questions we had was could we use the Ruby 3.x syntax for disabling the sorting on Ruby 2.7 without causing errors.

**Comment by coldiron** [comment]
Great, thanks. 

Just to be sure, I'll make and test the changes using 3.0 against the `expeditor/inspec-core-bin_4.24.28` branch, right?

>  could we use the Ruby 3.x syntax for disabling the sorting on Ruby 2.7 without causing errors.

Could we do something like `rescue ArgumentError` and call the old syntax, or is that a code smell?

**Comment by coldiron** [comment]
We could also do `Dir.method(:glob).parameters.include?([:key, :sort])`. I'm not aware of other avenues besides `rescue` or a conditional, though.

**Comment by coldiron** [comment]
@tas50

Ah!

https://github.com/apalmblad/ruby-shadow/issues/26

Looks like it's untestable. Here's my list of Dir.glob locations until testing is possible using 3.0.0:

<details>
<summary>Table</summary>

|Filename|Sorted|
|---:|---:|
|chef-universal-mingw32.gemspec|no|
|chef.gemspec|no|
|Gemfile|no|
|chef-bin.gemspec|no|
|chef-config.gemspec|no|
|chef-utils.gemspec|no|
|data_bag.rb:|
|    99|YES|
|    127|no|
|pwsh.rb|no|
|role.rb|no|
|ssl_policies.rb|no|
|data_bag_from_file| no|
|ssl_check.rb|no|
|bootstrap_context.rb|no|
|object_loader.rb|no|
|subcommand_loader.rb|no|
|windows_boostrap_context|no|
|remote.directory.rb 103|YES|
|msu.rb|no|
|aixinit.rb|no|
|debian.rb|no|
|gentoo.rb|no|
|insserv.rb|no|
|macosx.rb|no|
|dscl.rb|no|
|more-ruby-cleanup.rb:||
|    31|no|
|    38|no|
|    72|no|
|    91|no|
|    104|no|
|    136|no|
|aixinit_service_spec.rb|no, but typo in file: valide > valid|
|file_spec.rb|no|
|insserv_spec.rb|no|
|path_helper_spec.rb|no|
|file_resource.rb|no|
|cookbook_site_streaming_uploader_spec.rb|no|
|windows_boostrap_context_spec.rb|no|
</details>

**Comment by coldiron** [comment]
@tas50: so I've been thinking about this, and I've put together a quick benchmark:

https://gist.github.com/coldiron/3ee242d524425774887cb7e13893b22f

Run from the root directory of the Chef source. A couple of those lines traverse a good chunk of the Chef codebase, so they are probably fairly representative of what users might encounter.

1000 iterations of 8 `Dir.glob` calls:
```
Rehearsal ----------------------------------------------
sorted:     13.511877  17.178653  30.690530 ( 30.904177)
unsorted:   12.076176  17.094806  29.170982 ( 29.367741)
------------------------------------ total: 59.861512sec

                 user     system      total        real
sorted:     13.740223  17.043309  30.783532 ( 31.019568)
unsorted:   12.544705  16.558649  29.103354 ( 29.306799)
```
So,

> determine if we care if the results are sorted or not

My opinion is that no, we don't care. The difference between sorted and unsorted is minimal (~5%); it would seem that most of the run time is spent on FS calls or whatever. 

This benchmark was run on an Intel SATA SSD. On spinning rust, unless the files are sitting in cache, the difference would likely be unnoticeable.

**Comment by tas50** [comment]
Thanks for checking the stats on this. It looks like we can clean those up potentially as we see them, but shouldn't invest time otherwise.
