### ISSUE TITLE
Setup CI to fail hard with Ruby deprecations

### ISSUE THREAD

**Issue by tas50** [chef/chef#10792]
Ruby 3 expands how deprecations work in a way that could potentially be very useful for us. Traditionally we've shipped Chef with code that produces deprecation warnings and then customers see these and panic. We really want to resolve them before any end-user ever sees the warnings. We can do this in CI by defining our own deprecation method and forcing it to raise.

https://rubyreferences.github.io/rubychanges/3.0.html#warningwarn-category-keyword-argument

**Comment by snehaldwivedi** [comment]
@tas50 Can you help me out with some more details about this thicket. Currently, I am looking into the builds and trying to solve the deprecation warning we are getting. If anything else you would like to add please let me know.

**Comment by tas50** [comment]
This is not something we can do due to the number of File.exists? warnings
