### ISSUE TITLE
archive_file resource can't handle ZIP64

### ISSUE THREAD

**Issue by ibcomputing** [chef/chef#10833]
# Describe the problem
Zip files over 4GB in size are compressed using ZIP64. See https://en.wikipedia.org/wiki/ZIP_(file_format)#:~:text=The%20maximum%20size%20for%20both,1%20byte)%20for%20standard%20ZIP
archive_file reports "Damaged Zip archive" when trying to expand these files.
Looks like archive_file does not support ZIP64 whereas the windows_zipfile resource expands these files no problem.

## Software Version
Chef 16. 

## Replication Case
```
archive_file 'c:\temp\large zip file.zip' do
  destination 'c:\temp\test'
  action :extract
end
```

## Stacktrace
```
Archive::Error
           --------------
           Damaged Zip archive

           Resource Declaration:
           ---------------------
           # In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/xxxxxxx/recipes/default.rb

            53: archive_file 'c:\temp\large zip file.zip' do
            54:   destination 'c:\temp\test'
            55:   action :extract
            56: end
            57:
```
</details>

**Comment by tas50** [comment]
We're going to need to look into our upstream usage of libarchive for this issue. There are some historical issues there where users had issues with zip64 detection. It may be that you need to manually pass the option in this resource to turn on zip64 support, but I'll see if I can get the next step for you there.

**Comment by tas50** [comment]
It looks like libarchive does not include automatic detection of zip64 archive so unfortunately there isn't a way we can resolve this. If that longstanding issue in libarchive is resolved the fix would come into chef automatically, but that would involve someone from that project digging in.

**Comment by dsopscak** [comment]
This continues to be a problem. It seems rather disingenuous to dismiss it as not a bug in chef when chef is forcing us to abandon a resource that worked (windows_zipfile) while failing to provide equivalent functionality in the supposed replacement.
