### ISSUE TITLE
New compliance fetcher breaks on automate usernames containing @ chars

### ISSUE THREAD

**Issue by sspans** [chef/chef#10862]
Automate usernames can be email addresses - and contain '@' characters. The new automate fetcher uses uri.host parsing for automate usernames which breaks on legitimate account names.

https://github.com/chef/chef/blob/474bea9632c6863aa05bc3689f8d4d8d54e72c13/lib/chef/compliance/fetcher/automate.rb#L35

Sample automate server logging from a client running Chef 16.7.61:
```
"GET /compliance/profiles/int-sec-team@schubergphilis.com/security-baseline-minimal-centos8-level1-server/tar HTTP/1.1" 200 "0.012" 42787 "-" "Ruby" "127.0.0.1:2000" "200" "0.012" 334
```

Sample automate server logging from a client running Chef 16.9:
```
"GET /compliance/profiles/schubergphilis.com/security-baseline-minimal-centos8-level1-server/tar HTTP/1.1" 404 "0.008" 74 "-" "Ruby" "127.0.0.1:2000" "404" "0.008" 321
```

Note the 'int-sec-team@' which has been stripped, resulting in a 404.

**Comment by trickyearlobe** [comment]
@sspans , could you check and confirm if this is fixed in 16.9.20 and above?
I spoke to one of your colleagues today who believes that we fixed "one of your issues", but I'm not sure if it was this one.

**Comment by tas50** [comment]
@trickyearlobe We fixed the code that used the compliance phase instead of the legacy audit cookbook. Anyone with the audit cookbook on their runlist should not be executing this compliance phase anymore, but the problem remains here and we'll need to fix it in the new codebase.

**Comment by sspans** [comment]
Profile downloads work for me with 16.9.29 and the audit cookbook. 

The underlying issue indeed needs to be fixed or we will run into it again in the future.
