### ISSUE TITLE
Add backup functionality to windows_task resource

### ISSUE THREAD

**Issue by kimbernator** [chef/chef#10883]
### Describe the Enhancement:
Back up task configuration just like a file resource would on windows nodes when the task exists but is modified. This provides rollback functionality.

As far as I understand it, windows task data is stored in (I believe) XML within C:\Windows\system32\Tasks. This may be as simple as backing the file named after the task up to the chef backup dir.

### Describe the Need:
Anyone doing large-scale deployments that modify windows tasks

### Current Alternative
parsing the event log maybe

### Can We Help You Implement This?:
I may be able to, just a matter of when. If I get free time I may work on this, assuming it's considered worthwhile.

**Comment by jaymzh** [comment]
This seems like an obvious win to me, so if you have the time, please do submit a PR.

It would be extra awesome if it could use this to show what was changing in the way we do for other resources, something like:

```
windows_task[foo]: Updated command from X to Y
windows_task[foo]: Updated frequency from A to B
```

**Comment by kimbernator** [comment]
I've opened https://github.com/chef/chef/pull/10894 to address this

**Comment by lamont-granquist** [comment]
merged
