### ISSUE TITLE
load_current_resource for systemd_unit could be more efficient

### ISSUE THREAD

**Issue by joshuamiller01** [chef/chef#10921]
### Describe the Enhancement:
Establishing the status of a systemd_unit resource (per load_current_resource) currently shells out to systemctl five times; this could be refactored to perform a single shellout for speed and CPU wins. In my crude experimentation, a single systemctl call costs ~20ms; a single typical systemd_unit resource has three actions ([:create, :start, :enable]), each of which triggers the five shellouts. This reduces the steady-state cost from ~300ms (3 actions * 5 shellouts *20ms) to 60ms (~80% reduction).

### Describe the Need:
Anybody managing a systemd_unit resources on a systemd host

### Current Alternative
None

### Can We Help You Implement This?:
I'll submit a PR shortly.

**Comment by lamont-granquist** [comment]
merged
