### ISSUE TITLE
Add CLI output to the Compliance Phase

### ISSUE THREAD

**Issue by aknarts** [chef/chef#10938]
### Describe the Enhancement:
In deprecated Audit phase the results of the audit were put at the end of the chef converge log
![Screenshot from 2021-01-26 21-37-35](https://user-images.githubusercontent.com/252905/105902313-c1b3bf00-601e-11eb-857c-079b4a154d1c.png)

This was removed and is now replaced by inspec and the Compliance Phase

### Describe the Need:
We want to be able to easily see the results of the compliance during the chef converge.

### Current Alternative
The only alternative is to create a wrapper around chef client that parses the resulting json file and/or rely on Chef Automate for the reporting

### Can We Help You Implement This?:
I do have a PR ready that implements this in a reasonable way for us: https://github.com/chef/chef/pull/10939

**Comment by tas50** [comment]
Merged
