### ISSUE TITLE
`knife user create` should work without requiring six positional arguments. 

### ISSUE THREAD

**Issue by marcparadise** [chef/chef#10948]
### Describe the Enhancement:
`knife user create username` should just work.  Additional fields currently required (first/last/display name, email address, password) are moved to optional via flags or interactive prompt, and `display_name` is defaulted to be the same as the given username if not provided.

To safely deprecate the old behavior, we could still require all six arguments when 2+ arguments are given.  This would be incompatible (cause error) when used alongside the new flags like `--first-name`, `--last-name` etc. 

When given  just one argument (username) it will use the new behavior and expect additional fields to be provided via CLI flag arguments. 
```
USAGE: knife user create USERNAME (options)
```

### Describe the Need:

`user create` requires six arguments. .  However, the `/users` endpoint on Chef Server[0] only requires two fields: `username` and `display_name`. 

```
USAGE: knife user create USERNAME DISPLAY_NAME FIRST_NAME LAST_NAME EMAIL PASSWORD (options)
```
### Implementation Notes
`lib/chef/user_v1` knows that the fields are optional [1]  but it still sends them[2] - this would need to be changed so that only available fields are sent.  Also, display_name should be made required at this level too. 

### Related
#4814 will be fixed with this change. It currently occurs because `knife user create` wants six arguments, but `knife configure --initialize` only provides it with one. 

This may also impact `chef-server-ctl` and other internal tooling that creates users demand. 

[0] https://github.com/chef/chef-server/blob/8e5e0e23f5dbbdd9d05265b0f12a99cead2f9315/src/oc_erchef/apps/chef_objects/src/chef_user.erl#L189-L205
[1] https://github.com/chef/chef/blob/460c3331c0395a6d7f650c78e332129bbda416d5/lib/chef/user_v1.rb#L115-L130
[2] https://github.com/chef/chef/blob/460c3331c0395a6d7f650c78e332129bbda416d5/lib/chef/user_v1.rb#L141-L153

**Comment by msys-sgarg** [comment]
User create Api call on chef-server need an `email` argument to be passed, we see it here -> `valid_email line 208` -> https://github.com/chef/chef-server/blob/8e5e0e23f5dbbdd9d05265b0f12a99cead2f9315/src/oc_erchef/apps/chef_objects/src/chef_user.erl#L189-L205

May be we can allow `knife user create username` to work but along with a mandatory option of `--email` otherwise the call fails and we get the following error - 
```ERROR: The data in your request was invalid
Response: email must be valid```

**Comment by marcparadise** [comment]
Thanks @msys-sgarg; I like your suggestion of having these as required flags in this case, so that it would look like: `knife user create USERNAME --email EMAIL --password PASSWORD`; this is still considerably less typing and more clarity than the current six-arg behemoth. 

@chef/ux-team do you have any thoughts here?

**Comment by tas50** [comment]
Fixed in https://github.com/chef/chef/pull/11224
