### ISSUE TITLE
`knife bootstrap` on Windows always prepends drive letters to `file_cache_path`

### ISSUE THREAD

**Issue by jfcantu** [chef/chef#10964]
## Description
When running `knife bootstrap` on Windows, `knife` seems to always prepend a drive letter to the `file_cache_path` configuration option when it generates the `client.rb` for the remote node. *nix nodes do not like this.

## Chef Version
`knife` 16.9.20
`chef-client` 14.12.9

## Platform Version
`knife`: MS Windows 10 Professional
`chef-client`: CentOS 7

## Replication Case
Pretty straightforward - attempt to run `knife bootstrap` from a Windows machine against a *nix node, using any custom value for `file_cache_path`, e.g.:

```knife bootstrap XXX.XXX.XXX.XXX -N NODE.NAME.FQDN -U root -r "recipe[basic_linux_cookbook]" -E MY_ENVIRONMENT --config-option file_cache_path="/tmp/chef/cache"```

## Client Output (truncated)
The bootstrap process fails with the following error:
```
[2021-02-02T16:40:26+00:00] FATAL: Stacktrace dumped to /C:/tmp/chef/cache/chef-stacktrace.out
[2021-02-02T16:40:26+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2021-02-02T16:40:26+00:00] FATAL: ArgumentError: different prefix: "/" and "C:/tmp/chef/cache/cookbooks/basic_linux_cookbook"
```

Additionally, `/etc/chef/client.rb` shows:

```
file_cache_path "C:/tmp/chef/cache"
```

(Bootstrapping can be completed by simply removing the invalid line from the `client.rb` on the node and re-running `chef-client`, but... that adds some extra steps to the provisioning process.)

**Comment by cpj-radian** [comment]
This isn't just happening when overriding the default file_cache_path via an argument -- it happens with the default value, too. I've hit this problem multiple times already trying to bootstrap Linux systems from a Windows instance and the Linux team is very unhappy about seeing Windows-style paths at the filesystem root. 

Running Chef Workstation 21.4.365.

We're enterprise customers, so I'm putting a ticket in with support, too.

**Comment by msys-sgarg** [comment]
This issue will be resolved once fix for issue  https://github.com/chef/chef/issues/10367 is at place. The fix is pending on some response on the discussion - https://github.com/chef/chef/pull/11189#discussion_r600197351

**Comment by skylerto** [comment]
Added another work around to the similar issue: https://github.com/chef/chef/issues/10367#issuecomment-840774181

**Comment by msys-sgarg** [comment]
@skylerto  The PR resolves the issue of prep-ending drive letter to `file-cache-path` but right now file_cache_path is set to `file_cache_path "/var/chef/cache" ` irrespective of the value given in flag `config-option file_cache_path`. So this issue is partly solved as of now

**Comment by msys-sgarg** [comment]
Commit by @skylerto  https://github.com/chef/chef/pull/11592 seems to be resolving this issue as well. Once merged both can be closed.

**Comment by kailashv** [comment]
@jfcantu  I was also getting same errors. Updated the knife.rb file with below mentioned variables and it worked:

```
file_cache_path          nil
file_backup_path         nil
```

This is a version specific issue. On another workstation having different chefdk version(older version), same cookbook is working fine.

My workstation version details :
```
C:\chef-starter\chef-repo> chef -v
ChefDK version: 4.9.7
Chef Infra Client version: 15.12.22
Chef InSpec version: 4.21.3
Test Kitchen version: 2.5.2
Foodcritic version: 16.3.0
Cookstyle version: 5.23.0
```

**Comment by tas50** [comment]
Fixed by https://github.com/chef/chef/pull/11592
