### ISSUE TITLE
Unable to create a user with `knife user create` in version 16.10.8

### ISSUE THREAD

**Issue by jmvbxx** [chef/chef#11064]
## Description
When attempting to use `knife user create` it returns an error of `Response: Field 'name' missing` despite that not being part of the documentation. Furthermore, I manually added a `name` field to the JSON output from the command and it still failed with the same error.

## Chef Version
Chef Workstation version: 21.2.278
Chef Infra Client version: 16.10.8
Chef InSpec version: 4.26.4
Chef CLI version: 3.1.1
Chef Habitat version: 1.6.181
Test Kitchen version: 2.10.0
Cookstyle version: 7.8.0

## Platform Version
macOS Catalina 10.15.7

## Replication Case
I ran the following command based on the documentation:
knife user create test_user test_user Test User test@user.com "$(cat /dev/random | base64 | head -c 10)" -s "https://our.chef.server.com" --key "~/.chef/test_user.pem" --user test_user

## Client Output

```
{
  "username": "test_user",
  "display_name": "test_user",
  "first_name": "Test",
  "last_name": "User",
  "email": "test@user.com",
  "password": "/MaCgchirj",
  "create_key": true
}
```

**Comment by jmvbxx** [comment]
For clarity I'm including the full error message:
```
ERROR: The data in your request was invalid
Response: Field 'name' missing
```

**Comment by jmvbxx** [comment]
Updated to `Chef Infra Client: 16.10.17` and still seeing the same behaviour.

**Comment by jmvbxx** [comment]
We have tested this further and have discovered that it works in `13.x.x` & `14.x.x` but stopped working in `15.x.x` and now `16.x.x`.

**Comment by jmvbxx** [comment]
It's been two weeks since I submitted this issue. Is there any chance of at least getting this triaged any time soon?

**Comment by tas50** [comment]
I believe this is a duplicate of https://github.com/chef/chef/issues/10948

**Comment by jmvbxx** [comment]
Thanks for looking into this @tas50. Yes, it does appear to be a duplicate.  I'll go ahead and close this one and follow the other one.
