### ISSUE TITLE
Create a helper for fetching values from AWS Secrets Manager

### ISSUE THREAD

**Issue by tas50** [chef/chef#11070]
AWS Secrets Manager is a simple secrets manager that uses existing IAM credentials for authentication making it relatively easy to get started for AWS users. We should support fetching secrets from AWS Secrets Manager since all the auth is handled by IAM permission policies on the node. This should be relatively straightforward with the AWS SDK.

See the Amazon FAQ on the service: https://aws.amazon.com/secrets-manager/faqs/

## Definition of Done

- Helper method for accessing secrets in aws secrets manager
- Documentation on docs.chef.io
- Helpers included in the chef vscode plugin via the method -> YARD -> vscode automation

**Comment by tas50** [comment]
@mbaitelman pointed out that we could potentially just use the parameter store helper here with a different path since there's a passthru functionality:

https://docs.aws.amazon.com/systems-manager/latest/userguide/integration-ps-secretsmanager.html

We'll want to test if we can do that with just the single param store gem

**Comment by jakauppila** [comment]
@tas50 I'd be curious on your thoughts on how this should behave at a high level. Particularly in terms of caching the results within the run, etc.

I will be working on a solution for this internally in the coming weeks and would certainly be open to sharing the result if it fits the need.
