### ISSUE TITLE
windows_security_policy Resource missing policies

### ISSUE THREAD

**Issue by cookiecurse** [chef/chef#11145]
We recently switched from a Custom Resource that handles the windows security policy to the chef client one and discovered that these are not available in the windows_security_policy resource:

policy: 'LockoutObservationWindow'
policy: 'LockoutThreshold'
policy: 'AuditPolicyChange'

The errror exception I get when attempting to run this resource with the policies above:

```
================================================================================
           Error executing action `set` on resource 'windows_security_policy[LockoutObservationWindow]'
        ================================================================================
       
           Chef::Exceptions::ValidationFailed
           ----------------------------------
           Option secoption must be equal to one of: "LockoutDuration", "MaximumPasswordAge", "MinimumPasswordAge", "MinimumPasswordLength", "PasswordComplexity", "Passwo
rdHistorySize", "LockoutBadCount", "ResetLockoutCount", "RequireLogonToChangePassword", "ForceLogoffWhenHourExpire", "NewAdministratorName", "NewGuestName", "ClearTextPas
sword", "LSAAnonymousNameLookup", "EnableAdminAccount", "EnableGuestAccount"!  You passed "LockoutObservationWindow".
```
Any chance we can add those policies to the list of available security policies? Please let me know if you need assistance with that resource.

For reference, this is the Custom resource we used that had all of them included

```
resource_name :our_windows_sec_policy
provides :our_windows_sec_policy

property :id, String, name_property: true
property :secoption, String, required: false, default: ''
property :secvalue, String, required: true
property :sensitive, [true, false], default: true

default_action :set

action :set do
  new_resource.secoption.empty? ? (security_option = new_resource.id) : (security_option = new_resource.secoption)

  sec_hash = {
    security_option => new_resource.secvalue,
  }

  dsc_resource 'AccountSettings' do
    module_name 'cSecurityOptions'
    resource :AccountAndBasicAuditing
    property :Enable, '$true'
    property :AccountAndBasicAuditing, sec_hash
    sensitive new_resource.sensitive
  end
end
```

**Comment by johnmccrae** [comment]
@cookiecurse 'LockoutThreshold' is actually implemented by Windows as LockoutBadCount. What shows up in a Security Policy is Account Lockout Threshold but what gets written to disk when you change it is LockoutBadCount. That item is available to you in the list of policy objects above. I updated the code to add AuditPolicyChange; that was mssing. I also added ResetLockoutCount which pairs with the Lockout Threshold so users aren't permanently locked out. The last item, LockoutObservationWindow, does not appear in a Security Policy as exported by secedit but you can get to it via PowerShell. It is part of a customized fine grain password policy. Read more [here](http://woshub.com/fine-grained-password-policy-in-windows-server-2012-r2/).
