### ISSUE TITLE
knife error - table size exceeds the currently set width.Defaulting to vertical orientation

### ISSUE THREAD

**Issue by rishichawda** [chef/chef#11179]
## Description

Running `knife config list profiles` shows the following error: 

![Screenshot 2021-03-15 at 9 26 05 PM](https://user-images.githubusercontent.com/26366288/111182582-0eeeee80-85d5-11eb-9b34-c7dd3d748c86.png)

## Chef Version

Chef Workstation version: 20.11.180
Chef Infra Client version: 16.6.14
Chef CLI version: 3.0.33

## Platform Version

macOS 10.15.5 (Catalina)

## Replication Case

It happens when we reduce the terminal width. Resizing it to fit the output results in no errors.

## Stacktrace

```
The table size exceeds the currently set width.Defaulting to vertical orientation.
ERROR: knife encountered an unexpected error
This may be a bug in the 'config list profiles' knife command or plugin
Please collect the output of this command with the `-VVV` option before filing a bug report.
Exception: NoMethodError: undefined method `size' for nil:NilClass
```

**Comment by snehaldwivedi** [comment]
Hi, @rishichawda I have tested the command on the latest and mention version and it's working fine for me, please check the below results.  And if you are still facing the issue please try upgrading your chef version or share more details to replicate the issue.

<img width="681" alt="config profile latest and mention version" src="https://user-images.githubusercontent.com/62747690/119335432-ff151a00-bca9-11eb-969b-9adebeaffe2b.PNG">

**Comment by rishichawda** [comment]
@snehaldwivedi Looks like it's still there. From the screenshot you attached in your comment, it seems like you had enough terminal width to accommodate the rendered table. The bug is only when the terminal width is small enough that the content wraps. That is crucial to reproducing the bug. 
![Screenshot 2021-05-25 at 9 44 26 PM](https://user-images.githubusercontent.com/26366288/119532313-644c3680-bda2-11eb-9432-0e677ea8931c.png)

**Comment by snehaldwivedi** [comment]
@btm @tas50 I have tested this on mac and on windows too. This issue is only replicated when we minimize the screen that much that the table cannot be formed either vertically or horizontally. This can also be replicate if we increase the font size to very large. As per the code if the table size is greater than the screen width we show the table in vertical orientation as follows:

```
PS C:\Users\Administrator\chef\knife> bundle exec  knife config list profiles
Profile  *default
Client   chefadmin
Key      ~/.chef/ec2-chefadmin.pem
Server   https://ec2-34-219-25-251.us-west-2.compute.amazonaws.com/organizations/4thcoffee

Profile  test
Client   chefadmin
Key      ~/.chef/ec2-chefadmin.pem
Server   https://ec2-34-219-25-251.us-west-2.compute.amazonaws.com/organizations/4thcoffee

Profile  prod
Client   chefadmin
Key      ~/.chef/ec2-chefadmin.pem
Server   https://ec2-34-219-25-251.us-west-2.compute.amazonaws.com/organizations/4thcoffee

Profile  dev
Client   chefadmin
Key      ~/.chef/ec2-chefadmin.pem
Server   https://ec2-34-219-25-251.us-west-2.compute.amazonaws.com/organizations/4thcoffee

Profile  web.preprod
Client   chefadmin
Key      ~/.chef/ec2-chefadmin.pem
Server   https://ec2-34-219-25-251.us-west-2.compute.amazonaws.com/organizations/4thcoffee

Profile  example.org
Client   chefadmin
Key      ~/.chef/ec2-chefadmin.pem
Server   https://ec2-34-219-25-251.us-west-2.compute.amazonaws.com/organizations/4thcoffee
```

and if the table size is smaller than the width of screen its shown horizontally as follows:

```
PS C:\Users\Administrator\chef\knife> bundle exec  knife config list profiles
 Profile      Client     Key                        Server
-----------------------------------------------------------------------------------------------------------------------------------
*default      chefadmin  ~/.chef/ec2-chefadmin.pem  https://ec2-34-219-25-251.us-west-2.compute.amazonaws.com/organizations/4thcoffee
 test         chefadmin  ~/.chef/ec2-chefadmin.pem  https://ec2-34-219-25-251.us-west-2.compute.amazonaws.com/organizations/4thcoffee
 prod         chefadmin  ~/.chef/ec2-chefadmin.pem  https://ec2-34-219-25-251.us-west-2.compute.amazonaws.com/organizations/4thcoffee
 dev          chefadmin  ~/.chef/ec2-chefadmin.pem  https://ec2-34-219-25-251.us-west-2.compute.amazonaws.com/organizations/4thcoffee
 web.preprod  chefadmin  ~/.chef/ec2-chefadmin.pem  https://ec2-34-219-25-251.us-west-2.compute.amazonaws.com/organizations/4thcoffee
 example.org  chefadmin  ~/.chef/ec2-chefadmin.pem  https://ec2-34-219-25-251.us-west-2.compute.amazonaws.com/organizations/4thcoffee
```

In vertical orientation the width of table mainly depends on the server value as its longer in windth size. I tried several ways but  I didn't find any solution. As there are multiple cases like font, screen size because of which this table cannot be form. Ideally, we work on maximum or half screen width size only. But if it still needs to be solved please suggest to me any way to do it.

**Comment by snehaldwivedi** [comment]
@rishichawda can you please confirm if you're getting proper output full screen?

**Comment by snehaldwivedi** [comment]
@rishichawda I am closing this issue for now as on the ideal terminal & font size it's working fine. If you face an issue on the ideal size please reopen the issue.

**Comment by sutarmaheshs** [comment]
I'm facing similar problem. I have chef workstation 22.5.923 installed on my Windows 10 x64 version 21H2 with screen resolution 1920x1080 with 100% scaling with default CW PowerShell.
Running "knife config list" command is throwing the same error "The table size exceeds the currently set width.Defaulting to vertical orientation."

It was working until last week and I have not made any changes to the system or the CW Powershell. The Font and Screen size is the same default but it's throwing this error today.
I even tried changing the CW PowerShell Default Font to the lowest size (like 5) and increased the Screen Buffer Width to the widest like 500 points but I still see the same issue.

Any thoughts? I Googled/Binged it but I couldn't find a solution to this issue.

To add, knife node search does return good results with proper formatting with the default settings. It is just the knife config list that's complaining.

I don't see to have access to reopen this issue as it's reported by someone else. Let me know if I should open a new issue.
