### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by luis33338** [chef/chef#11256]
[](url) #11254 []([https://www.paypal.me/luisalbertop27](url)``)[](url) plataformas oline #11254

**Comment by luis33338** [comment]
`[lukinatk@sina.com

**Comment by luis33338** [comment]
`[lukinatk@sina.com](url)`

**Comment by luis33338** [comment]
`[lukinatk@sina.com

**Comment by luis33338** [comment]
`[lukinatk@sina.com](url)`

**Comment by luis33338** [comment]
Httpsgooglgleplatsformas.oline

**Comment by kmf** [comment]
@tas50 Spam

**Comment by tas50** [comment]
@kmf Thanks. I reported it.
