### ISSUE TITLE
Enabling network mounts with a root of / not idempotent and the / is stripped out

### ISSUE THREAD

**Issue by eheydrick** [chef/chef#11255]
## Description

Enabling network (nfs) mounts with a root of `/` is not idempotent and the `/` is getting striped. The result is a new `fstab` entry every run. Specifying a root other than `/` works fine. The problem occurs when the device is like `something:/`

## Chef Version

```
# chef-client  --version
Chef Infra Client: 16.11.7
```

Looks like there's been several PRs dealing with `/` root on network devices.

I did some bisecting and found the problem was introduced in https://github.com/chef/chef/commit/7fe69a2a865e24314540e2c8a9c0d28375b22eed. 

As of https://github.com/chef/chef/commit/c600ba4886fd5ab9af333f57ae95d5ed6a71164b the `/` was getting stripped out but the fstab update was idempotent. With https://github.com/chef/chef/commit/950a3e4e7c85ccdc88162f89a7f6eba8807f02d7 it reverted back to the fstab update not being idempotent and still stripping the `/`.

## Platform Version

Debian 10

## Replication Case

Can repro with a simple `chef-apply` script:

```
mount '/tmp/foo' do
  device 'something:/'
  fstype 'nfs4'
  options 'defaults'
  pass 0
  action [:enable]
end

```

## Client Output

```
# chef-apply mounttest.rb  
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * mount[/tmp/foo] action enable
    - enable something:/
```
Running it again results in the same output. `/etc/fstab` contains multiple entries with the `/` stripped off:

```
something: /tmp/foo nfs4 defaults 0 0
something: /tmp/foo nfs4 defaults 0 0
```

**Comment by ramereth** [comment]
I'll take a closer look at this and provide a fix since I introduced the regression (apologies for that). Thanks for the example code so I could replicate it on my end!

**Comment by ramereth** [comment]
@eheydrick I think #11261 fixes this issue. It should be easily patched on a current chef-16 codebase. Please let me know if it does or I still missed something that needs fixed. Thanks!

**Comment by eheydrick** [comment]
@ramereth I tested the patch under Chef 16 and can confirm that it's doing the right now. Thanks for the quick fix!
