### ISSUE TITLE
Fix Dnf package provider functional tests on fedora

### ISSUE THREAD

**Issue by marcparadise** [chef/chef#11272]
dnf package provider tests on Fedora are timing out.  We need to look at what they're doing and find out what's taking so long. 

https://buildkite.com/chef-oss/chef-chef-master-verify/builds/8485#f1b4166b-cd29-4b21-888f-3d18921db022/102-302)

**Comment by tas50** [comment]
Fixed in https://github.com/chef/chef/pull/11535
