### ISSUE TITLE
When using the --attribute option in knife search the JSON format changes

### ISSUE THREAD

**Issue by jordan3825** [chef/chef#11292]
## Description
When using knife search with `--format JSON`, two formats of JSON can be returned. When running `knife search` without the any extra arguments, the JSON output is for the format of key:value and allows for easy ingesting of the returned JSON in to other systems.

`knife search node "platform:*" --format json`
```
{
  "results": 61,
  "rows": [
    {
  "name": "myhostname",
  "chef_environment": "env",
  "json_class": "Chef::Node",
  "automatic": { <snip> },
  "normal": { <snip> },
  "chef_type": "node",
  "default": { <snip> },
  "override": { <snip> },
  "run_list": [
    <snip>
  ]
}
,
...
<snip>
...

  ]
}
```

When running the same command, but added an `--attribute` option to show a specific attribute, the format changes completely. Instead of key:value data, the JSON is returned as value:value. One would expect the same format as previously but with the additional attributes shown as stated in the documentation. The complete change is JSON format is very un-expected.

https://docs.chef.io/workstation/knife_search/#options

`knife search node "platform:*" --format json --attribute platform`
```
{
  "results": 61,
  "rows": [
    {
      "myhostname": {
        "platform": "windows"
      }
    },
   ...
   <snip>
   ...
  ]
}
```

One would expect the JSON to be fairly consistent to aid in consumption of the JSON. 

## Chef Version
Chef Workstation version: 20.12.187

## Platform Version
Windows 10 1809

## Replication Case
Run the following two commands and check the output
`knife search node "platform:*" --format json`
`knife search node "platform:*" --format json --attribute platform`

**Comment by tas50** [comment]
The format here does change, but since we've had this functionality since the very early days of Chef Infra it's not really something we can change at this point. Due to that, I'm going to close this out and something we won't be taking on.
