### ISSUE TITLE
Knife Bootstrap against Windows does not respect the config_log_level setting

### ISSUE THREAD

**Issue by brywilliamsCF** [chef/chef#11367]
## Description
When using the 'config_log_level' setting in the knife configuration, `knife bootstrap` will still always set the log_level to ':auto'.

I have not tested this, but after looking at the code I am almost certain that the check for `config[:config_log_level]` in the windows_bootstrap_context.rb needs to actually look for `chef_config[:config_log_level]`.  That would match the Linux bootstrap code and the code for config_log_location setting, both of which do work as expected.

https://github.com/chef/chef/blob/fa1c86cd6cf94da14b62b368c2cc45f681be8249/knife/lib/chef/knife/core/windows_bootstrap_context.rb#L89-L90

## Chef Version
16.12.3

## Platform Version
Windows Server 2019

## Replication Case
Create a knife.rb file with "config_log_level :info" set in it.  Pass this configuration file to `knife bootstrap` using `--config`.  The output will still show the C:\chef\client.rb file being created with "echo.log_level        :auto".

## Client Output

```

```

**Comment by msys-sgarg** [comment]
Changes are merged .. hence closing this issue
