### ISSUE TITLE
Template Helper Function

### ISSUE THREAD

**Issue by jakauppila** [chef/chef#11402]
### Describe the Enhancement:
It would be great if there was a template helper function that behaved like the `template` resource but rather than writing the resulting file, simply returned the content to be used in other resources.

### Describe the Need:
I want to be able to templatize the content of a `systemd_unit` resource utilizing an erb in my cookbook so that if a consumer wants to override it, they can simply reference an erb in their wrapper cookbook.

https://github.com/sous-chefs/tomcat/pull/358#discussion_r492897903

### Current Alternative
I am not aware of an an alternative. In this particular use-case we are simply not utilizing the `systemd_unit` resource and instead resorted to manually manage the unit file via the `template` resource and then interacting with systemd via `execute`.

**Comment by lamont-granquist** [comment]
you can expose a `template_cookbook` property that you feed into the cookbook property of the template resource so that callers can point the template resource at their own erb.  there's example of this in the sous-chef cookbooks.

**Comment by jakauppila** [comment]
@lamont-granquist Yep, I get that. This request was more around being able to utilize the templating engine to generate content to utilize in another resource.

For example:

While simplified here, we have a pretty complex unit file that we're generating.
```
systemd_unit new_resource.instance_name do
  unit_name "#{new_resource.service_name}.service"
  content <<~EOU
  [Unit]
  Description=Java Service Application
  After=syslog.target network.target

  [Service]
  ExecStart=/bin/java \\
            -XshowSettings:properties \\
            #{new_resource.start_class} \\
            #{new_resource.start_params.map { |s| "\"#{s}\"" }.join(' ')}
  SuccessExitStatus=143
  Restart=on-failure
  RestartSec=10

  [Install]
  WantedBy=multi-user.target
  EOU

  action :create
end
```

I'd rather generate that content from a template so I could expose the ability to override the template file to generate content for the `systemd_unit` resource.

```
systemd_unit new_resource.instance_name do
  unit_name "#{new_resource.service_name}.service"
  content get_template_content('my_template.erb', {'foo' => 'bar'})

  action :create
end
```
