### ISSUE TITLE
knife search node showing different results that knife node show

### ISSUE THREAD

**Issue by MrCyrus** [chef/chef#11411]
## Description
The following 2 knife commands are returning different results but I'm expecting them to be returning identical results. Specifically I'm expecting the 'knife search' to show me the values for policy_group and policy_name yet they are blank even though the 'knife node show' is showing valid values for these 2

1) knife node show some.servers.fqdn.com -F json -a name -a run_list -a platform -a policy_group -a policy_name
2) knife search node '(name:some.servers.fqdn.com)' -F json -a name -a run_list -a platform -a policy_group -a policy_name

The 'knife node show' shows me:
{
  "some.servers.fqdn.com": {
    "name": "some.servers.fqdn.com",
    "run_list": [
  "recipe[policy_linux_enterprise::default]"
]
,
    "platform": "redhat",
    "policy_group": "sandbox",
    "policy_name": "linux_enterprise_intranet_amer"
  }
}

while the 'knife search' is showing:
{
      "some.servers.fqdn.com": {
        "name": "some.servers.fqdn.com",
        "run_list": [
          "recipe[policy_linux_enterprise::default]"
        ],
        "platform": "redhat",
        "policy_group": null,
        "policy_name": null
      }
    }

## Chef Workstation Version

21.1.247

## Platform Version

RedHat 8.3 (x86_64)

**Comment by tas50** [comment]
Since this is related to an EOL release it's not something we can fix or further troubleshoot. I'd recommend upgrading to the very latest release possible to see if that resolves. Other than that, the only option is to upgrade to a supported Redhat release.
