### ISSUE TITLE
Windows testing exiting with code 1 and no reason

### ISSUE THREAD

**Issue by tas50** [chef/chef#11427]
Multiple windows systems are failing with an exit status 1 and no logging of any sort to indicate the failure:

https://buildkite.com/chef/chef-chef-master-omnibus-release/builds/1186#22c54fae-ec3b-46f0-86d6-9585f5930a76/109-721

**Comment by lamont-granquist** [comment]
those were suspected to be due to the parallelizer on ruby 3.0

**Comment by tas50** [comment]
Related to https://github.com/chef/chef/issues/10911
