### ISSUE TITLE
Windows_pagefile resource needs some clear documentation 

### ISSUE THREAD

**Issue by thirumoorthir** [chef/chef#11487]
### Describe the Enhancement:
Windows_pagefile resource needs some clear documentation 

### Describe the Need:
windows_pagefile resource have some linux examples , we need those to be removed , and we can't use this resource without
'automatic managed false' option in the resource . instead of doing that why can't we enable it by default

### Current Alternative
use 'automatic_managed false' in every time we use this resource 

### Can We Help You Implement This?:
please help me to make this possible

**Comment by tas50** [comment]
@thirumoorthir Are you having issues with the examples here? https://docs.chef.io/resources/windows_pagefile#examples

**Comment by thirumoorthir** [comment]
The documentation is good but latest version on windows needs this as default , 
```
windows_pagefile 'Enable automatic management of pagefiles' do
  automatic_managed true
end
```
if we didn't add automatically manage option whole resource is not working and chef run fails
