### ISSUE TITLE
Systemd service state detection fails

### ISSUE THREAD

**Issue by bmhughes** [chef/chef#11496]
## Description
 
Systemd service state detection fails due to a missing double splat [here](https://github.com/chef/chef/blob/4f19535d24dd5dfd4a705034df8512b5db1651cc/lib/chef/provider/service/systemd.rb#L83) and the options hash as a string is passed to the `systemd` cli command as a service name which causes it to attempt to resolve the pair of braces to a service name alongside the correct service name.

## Chef Version
Chef 17+

## Platform Version
Anything systemd. Tried with CentOS, Fedora, Debian, Ubuntu.

## Replication Case
Service resource set to disable an enabled service, stop a running service etc. Anything that causes the initialise service state to be incorrect.

**Comment by dkowis** [comment]
I wonder if this also caused another issue. I used to have `service "sshd"`, I had to change them all to "ssh". About a few days ago, it started failing with an error about how it wouldn't enable an alias. Is that related?
