### ISSUE TITLE
Rocky Linux Support

### ISSUE THREAD

**Issue by hanzzen94** [chef/chef#11504]
# Describe the problem

Rocky Linux was recently released as a Release Candidate. Would love to see Chef add support for it in time for the first proper release.

## Software Version

chef-client 17.0.242

## Replication Case

Client installs just fine in the current Release Candidate, but does not recognize the distro as rhel based. Attribute 'platform_family' is set to null.

![image](https://user-images.githubusercontent.com/47220811/116856725-e611cf80-abfb-11eb-81ba-c157a7336575.png)

**Comment by kmf** [comment]
@hanzzen94 There was a Ohai Pull Request for this 14 Hours ago 
https://github.com/chef/ohai/blob/master/CHANGELOG.md

**Comment by hanzzen94** [comment]
Ah my bad, should've taken a look at ohai. This issue can be closed then.

**Comment by tas50** [comment]
This will ship in 17.1
