### ISSUE TITLE
Unified Mode warnings shouldn't fire on resources that don't run on Chef 17+

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#11508]
warning on a resource that declares this:

```
chef_version_for_provides '< 14.0' if respond_to?(:chef_version_for_provides)
```

is not useful and that should stop.  the chef_version_for_provides API is particularly well suited to ignore, iterating through all the chef_version constraints on the resource and disabling the warning if they all declare `chef_version` might be a bit more difficult.

**Comment by tas50** [comment]
Fixed on master
