### ISSUE TITLE
Add native habitat resources and it's required toml dump resource

### ISSUE THREAD

**Issue by sam1el** [chef/chef#11532]
### Describe the Enhancement:
The ability to manage the configuration and drift of Habitat installs as well as it's supervisor and Package/Service system. This would allow us to do so from a cookbook.

### Describe the Need:
Any customer who owns both the Chef infra as well as the Habitat product or is currently using the effortless pattern would benefit. This would allow them to stop relying on an external cookbook.

### Current Alternative
Right now they can use the [Habitat cookbook](https://github.com/chef-cookbooks/habitat)

### Can We Help You Implement This?:
I currently have a Draft PR in the pipeline. I need some guidance on where the tests need to go in the folder structure and likely will need some help making the toml_dumper helper work correctly a chef class.

**Comment by tas50** [comment]
Done
