### ISSUE TITLE
windows_uac resource not setting correct registry value

### ISSUE THREAD

**Issue by Pr0meth3us** [chef/chef#11570]
## Description
When using the `windows_uac` resource and setting the property `consent_behavior_users` (or not using it and letting it default) to `:prompt_for_creds`, chef-client attempts to set the registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\ConsentPromptBehaviorUser` to value `2`. 

Microsoft does not have the value of `2` [listed as a valid value for this registry key](https://docs.microsoft.com/en-us/windows/security/identity-protection/user-account-control/user-account-control-group-policy-and-registry-key-settings#registry-key-settings). The only valid values are 0 (deny), 1 (prompt for creds on secure desktop, 3 (default, prompt for creds)

Suggested fix: 
update the `windows_uac: consent_behavior_users` resource property to set the `:prompt_for_creds` registry value to `3`

## Chef Version
chef-client v17.1.35

## Platform Version
Windows Server 2012r2, x64

## Replication Case

1. create a recipe file, for example `uac_test.rb`, with the following contents:
```
windows_uac 'Disable UAC prompts for the admin' do
  enable_uac true
  prompt_on_secure_desktop true
  detect_installers true
  consent_behavior_admins :no_prompt
  consent_behavior_users :prompt_for_creds
end
```

2. run chef-client in local-mode and in "WhatIf" mode, using this new recipe file:
`chef-client -z uac_test.rb -W`

3. check the output and see that it says:
```
* windows_uac[Disable UAC prompts for the admin] action configure
    * registry_key[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\
Policies\System] action create
      - Would set value {:name=>"ConsentPromptBehaviorUser", :type=>:dword, :dat
a=>2}
```

4. since the default value for Windows is `3`, it will update this registry key with a value of `2`, which is not listed as a valid number.

## Client Output

```
Recipe: @recipe_files::C:/chef/testing_recipes/test.rb
  * windows_uac[Disable UAC prompts for the admin] action configure[2021-05-12T12:26:40-04:00] INFO: Processing windows_uac[Disable UAC prompts for the admin] action configure (@recipe_files::C:/chef/testing_recipes/test.rb line 1)

    * registry_key[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System] action create[2021-05-12T12:26:40-04:00] INFO: Processing registry_key[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System] action create (C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.1.35-universal-mingw32/lib/chef/resource/windows_uac.rb line 78)

      - Would set value {:name=>"ConsentPromptBehaviorUser", :type=>:dword, :data=>2}

[2021-05-12T12:26:40-04:00] DEBUG: Saving the current state of node xxxxxxxxxxxx
[2021-05-12T12:26:40-04:00] WARN: In why-run mode, so NOT performing node save.
[2021-05-12T12:26:40-04:00] INFO: Chef Infra Client Run complete in 0.5513106 seconds
```

## Stacktrace
No error encountered during run so no stacktrace.out is generated.

**Comment by Pr0meth3us** [comment]
After looking in the repo for the [actual windows_uac resource](https://github.com/chef/chef/blob/master/lib/chef/resource/windows_uac.rb#L109), it looks like it gets the value based on an array index. There would need to be a check to see if the symbol matches `prompt_for_creds` and either increment the value by 1, or statically set it to 3.

**Comment by tas50** [comment]
Thanks for reporting this @Pr0meth3us. We fixed this in https://github.com/chef/chef/pull/11987
