### ISSUE TITLE
Compliance Phase runs cli and json-file reporters unexpectedly

### ISSUE THREAD

**Issue by collinmcneese** [chef/chef#11585]
## Description

When using Compliance Phase and a custom `reporter` is set, the `cli` and `json-file` reporters always run as well if `node['audit']['reporter']` is set to an array.  When `node['audit']['reporter']` is set to a string value, such as `default['audit']['reporter'] = 'chef-server-automate'`, then the single reporter will run as expected.

While these reporter outputs are good options as default without other reporters specified, users should have the choice to only include `json-file` and `cli` reporters if they are specified within the `reporter` array, they should not be enabled if the system has a different discreet reporter set configured as an array, the same way the logic works if it is a String value.

In environments with sensitivity to consumed disk space, this results in extra files being created (`json-file` reports) and syslog contains the contents of the report as `STDOUT`.  This also makes troubleshooting more difficult with client runs when large profiles such as CIS checks are being run where the output would fill up the terminal buffer on the screen when an operator is not wanting it to render and instead wants to see the details of the Infra client run.

## Chef Version

17.1.35

## Platform Version

linux

## Replication Case

Configure reporter attributes as follows as an Array value:
`default['audit']['reporter'] = %w(chef-server-automate)` or `default['audit']['reporter'] = %w(chef-server-automate json-file)`
When running, `json-file` and `cli` will be added to the array.

When running with a String value, the single reporter type is used as expected, `default['audit']['reporter'] = 'chef-server-automate'`

**Comment by lamont-granquist** [comment]
This is due to array merging at the default level which is core to how attributes work:

https://docs.chef.io/attribute_arrays/

The workaround for now is to use the override level which does not do array merging with the defaults:

```
override['audit']['reporter'] = %w(chef-server-automate)
```

The correct solution to this is that the node attribute API for compliance mode will be replaced and deprecated and this issue will go away.
