### ISSUE TITLE
corrupted new.sdb file will cause isses in future runs

### ISSUE THREAD

**Issue by fgarcia-cnb** [chef/chef#11596]
https://github.com/chef/chef/blob/3a5b225af9c28d5bdb828fa3a3ec6cab35c4d1d9/lib/chef/resource/windows_security_policy.rb#L128

we had an issue where the windows_security_policy resource kept creating a MaximumPasswordAge entry under hklm\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters with an invalid type. We suspect the new.sdb file referenced here was corrupted from a previously bad chef cookbook that was setting that registry value incorrectly. However, it seemed like the setting stuck on new.sdb and kept getting reimported whenever this resource ran. deleting new.sdb manually fixed the issue.

Shouldnt new.sdb be deleted after every run?

**Comment by fgarcia-cnb** [comment]
i take it back. gpupdate is changing the maximumpasswordage to 90. whcn chef runs, it should change it back to 45... but instead it creates the following entry:


[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Netlogon\Parameters]
"MaximumPasswordAge"=hex(2d):33,00,30,00,00,00

notice the 2d = 45. so its setting the reg type to 45 instead of the dowrd value. Any ideas? this seems like an issue with secedit

**Comment by fgarcia-cnb** [comment]
i take it back... we were using v16.6.14 of the chef client, which uses an outdated method for local security policy updates. This error appears to go away with v17.

**Comment by tas50** [comment]
@fgarcia-cnb Is this resolved with 17 then?

**Comment by fgarcia-cnb** [comment]
it appears so... in a version between 16.6.14 and the latest version
