### ISSUE TITLE
Produce packages for FreeBSD 13

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [chef/chef#11644]
## Description
Chef Client for FreeBSD 13 not listed in downloads page: https://downloads.chef.io/tools/infra-client/current?v=17.2.12&os=freebsd

## Chef Version
any

## Platform Version
FreeBSD 13.0

**Comment by tas50** [comment]
At the moment we don't validate packages for FreeBSD 13, which is how the downloads page gets a new platform added to it. It's on our 2021 roadmap to add FreeBSD 13 testers, but it's behind a few other build infrastructure projects.

**Comment by mateuszkwiatkowski** [comment]
@tas50 thank you for your response. I installed Chef Infra Client compiled for FreeBSD 12 but it didn't work on 13.0:
```
# chef-client
ld-elf.so.1: Shared object "libncursesw.so.8" not found, required by "ruby"
```

**Comment by mateuszkwiatkowski** [comment]
Hi @tas50,

Any news on this issue? Can FreeBSD community help with this in any way?

**Comment by tas50** [comment]
This is in our releng team queue. I don't have a date on when it'll be completed.

**Comment by edgar-moran** [comment]
To make it work you can copy the libraries he indicates that are needed from version 12.0 (you have to install or have a version 12 installed from where you can copy the libraries he asks for "libncursesw.so.8") to version 13, usually they are in the /lib/ folder.

**Comment by tas50** [comment]
Moving this to Chef Ideas where we're tracking feature requests: https://chef-software.ideas.aha.io/ideas/INFRA-I-40

**Comment by mateuszkwiatkowski** [comment]
Please consider treating this as bug as there are functional packages for older releases of FreeBSD. Thank you.
