### ISSUE TITLE
CHEF 16+ ohai packages on Windows does not include (x86) packages due to reg_key collection order

### ISSUE THREAD

**Issue by knightorc** [chef/chef#11683]
## Description
Chef 16+ does not include (x86) packages in node['packages'] due to the order of registry keys queried.

## Chef Version
Chef 16/17+

## Platform Version
Windows (all versions)

## Replication Case
ohai packages on cli when a (x86) program is installed. it will failed to be included.

## Purposed fix:

PR: https://github.com/chef/ohai/pull/1669

Move 
```
collect_programs_from_registry_key(Win32::Registry::HKEY_CURRENT_USER, 'Software\Microsoft\Windows\CurrentVersion\Uninstall')
```
After
```
collect_programs_from_registry_key(Win32::Registry::HKEY_LOCAL_MACHINE, 'Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall')
```

Problem is `Win32::Registry::HKEY_CURRENT_USER, 'Software\Microsoft\Windows\CurrentVersion\Uninstall` does not exist on all systems, and ohai registry collection stops when this registry tree fails.

**Comment by tas50** [comment]
If there's anything we need to ship here still it can get backported to the 16-stable branch in ohai.
