### ISSUE TITLE
Investigate potential designs for cloud secrets helpers

### ISSUE THREAD

**Issue by tas50** [chef/chef#11684]
For Chef Infra Client 17.x we would like to integrate with Azure / AWS secrets managers. We know we can do this with basic helpers, but there may be better implementations that can be achieved with a small amount of additional engineering effort.

This issue tracks our investigation of potential implementations we could build with aws/azure.

**Comment by jakauppila** [comment]
I'll be curious on designs for this.

For our immediate use-case, we're planning to pass AWS Secrets Manager ARNs to our run, retrieve the secrets (with metadata as we want the tags for some processing) and then utilize them by pushing to various configuration files, etc.
