### ISSUE TITLE
New pattern for data bag item ID is breaking existing data bags.

### ISSUE THREAD

**Issue by sergeisantoyo** [chef/chef#11692]
With the changes introduced in this commit 19f127b7ff177bed0a0ebdfd2e0720f6acfc6bd2, a lot of recipes in my organization got broken, since we use `firstname.lastname` naming convention for our users data bag.

I am sure that we are not the only organization using that format for data bags.

The solution as of now, was downgrading the chef-client version inside our nodes managed by chef (we were using 17.2.29 and downgraded to 14.2.3), so when we try to access a data bag item, we don't get an InvalidDataBagItemID Exception.

The commit says that this pattern change only applies for versions from 17.2.10 to 17.2.32. Will this be a permanent change? Is there a way to provide a custom ID pattern for the data bag items?

We have a lot of code relying on data bags using dot inside the ID's and we wouldn't like to miss new chef-client versions only because of this change.

**Comment by mvangoor** [comment]
I just ran into this issue aswell and find it strange this breaking change was done in a released version already. There seems to be some kind of corner case/bug being 'fixed' here, but can't see/find the actual reason for this commit.

From my point of view this commit needs to either be rolled back and pushed to 18 as a breaking change or some extensive explanation why we need a breaking change in 17 post release date..

**Comment by barracksbuilder** [comment]
I can confirm this also we are using: Chef Infra Client version: 17.2.29

Our IDs are domain names so they have "." in them.

I'm not sure what they fixed other than changing the regex to remove periods as valid characters. I also agree this needs to be rolled back and pushed to 18 as a breaking change or explain out why they need to remove period's from the IDs.

I have paid support so I will open a ticket with chef and report back what they say.

**Comment by hrak** [comment]
Is there going to be a new stable infra client release soon that includes this fix?
