### ISSUE TITLE
upgrade on preinstalled dnf_package resource downgrades 

### ISSUE THREAD

**Issue by snehaldwivedi** [chef/chef#11694]
## Description
upgrade on preinstalled dnf_package resource downgrades https://github.com/chef/customer-bugs/issues/359

## Platform Version

RHEL 8

## Replication Case
```
dnf_package 'splunkforwarder' do
  action :upgrade
end

```
is actually downgrading a package. And allow_downgrade false is deprecated.
Complete details are in the attached MS Word document.

I need to be able to install without fear of having a package downgraded on me.

## To reproduce

Install splunkforwarder dnf_package version 0:7.0.2-03bbabbd5c0f.x86_64.
Attempt upgrade with:
```
dnf_package 'splunkforwarder' do
   action :upgrade
end

```
note the epoch version prefix value "0:"

## Client Output

chef-client run output:
```
- upgrade(allow_downgrade) package splunkforwarder from 0:8.1.2-545206cc9f70.x86_64 to 0:7.0.2-03bbabbd5c0f.x86_64
```

**Comment by snehaldwivedi** [comment]
I have tried upgrading dnf package on ChefDK version: 4.13.3 and its working correctly for me not getting downgreaded. Following are the steps I have followed:

I have installed `splunkforwarder-8.1.2-545206cc9f70.x86_64` on my system RHEL 8.

default.rb
```
dnf_package 'splunkforwarder' do
  source "/home/ec2-user/splunkforwarder-8.1.4-17f862b42a7c-linux-2.6-x86_64.rpm"
  action :upgrade
end
```

Output:
```
$ sudo chef-apply cookbooks/first_cookbook/recipes/default.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * dnf_package[splunkforwarder] action upgrade
    - upgrade(allow_downgrade) package splunkforwarder from 0:8.1.2-545206cc9f70.x86_64 to 0:8.1.4-17f862b42a7c.x86_64
```

Please let me know if you are still facing the issue with some more details.

**Comment by TerrieB1** [comment]
From the customer: Hi. Your recreation scenario doesn’t exactly match what I’m seeing. In your scenario, I would expect splunkforwarder to get upgraded from 8.1.2 to 8.1.4.

Do this instead:

Install the 8.1.4 package, and use the same dnf_package resource with 8.1.2 as the source.

But really, that’s not the same recreation scenario either.

In our case, we have down level version of the package in an enabled yum repo. We don’t specify the source.

Thanks for looking.

Mike

Mike Wood

Global Unix Systems Engineer III

210-219-8493

Mike.Wood@gmfinancial.com

**Comment by snehaldwivedi** [comment]
Hi Mike,

I have tried both of the scenarios. In first case I have installed splunkforwarder-8.1.2 and ran following recipe without `source` as your trying still it don't get downgraded. If the source is not passed it will not  apply any action.

```
dnf_package 'splunkforwarder' do
  action :upgrade
end
```
output:
```
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * dnf_package[splunkforwarder] action upgrade (up to date)
```

Another scenario, I have installed splunkforwarder-8.1.4 and added splunkforwarder-8.1.2-545206cc9f70-linux-2.6-x86_64.rpm in source path. In this case I am able to replicate the issue but ideally if in system install any package it get installed. So in case of upgrade action I agree that scenario doesn’t exactly match.

`- upgrade(allow_downgrade) package splunkforwarder from 0:8.1.2-545206cc9f70.x86_64 to 0:7.0.2-03bbabbd5c0f.x86_64`
 
So I will try to handle it before installing any package if the given version is higher to the installed version then only it should get installed directly  or prompt a msg/ask for confirmation before installing

**Comment by TerrieB1** [comment]
From the customer after sharing the response above: I’m not quite sure how to reply to

“So I will try to handle it before installing any package if the given version is higher to the installed version then only it should get installed directly or prompt a msg/ask for confirmation before installing. Let us know how you get on with this."

IMHO, if you have version N installed on the system, and only version N-1 in your repo, then the dnf_package resource with action :upgrade should never downgrade the package. And it shouldn’t prompt for a msg/ask for confirmation either. That goes against the idea of having a running chef-client service. Why was the allow_downgrade attribute removed from the dnf_package resource?

As for “Let us know how you get on with this.” – are you asking how we get around the issue? We don’t have a workaround for RHEL8 yet. We’re just lucky we don’t have too many of them right now, and we have to be very careful with our Artifactory repos.

**Comment by snehaldwivedi** [comment]
Hi Mike,

I was just informing you that I was able to replicate the issue. I will move forward to work on it, I will be working on the second option explained below in detail.

By adding msg/prompt I mean there are two options as a solution for this issue. In case of prompt  to take confirmation before installing any lower version on upgrade action.
Another option is to just give a fatal message that "The version you have provided is lower than the installed one, please try with upper version"  and end the process with the msg.


Thanks

**Comment by snehaldwivedi** [comment]
@marcparadise / @lamont-granquist I have done my analysis on this issue as explained in [comment](https://github.com/chef/chef/issues/11694#issuecomment-867618532). To solve this I was trying to compare the installed and given version and if the given version is lower than the installed version I was thinking to add a fatal message that "The version you have provided is lower than the installed one, please try with the upper version" and end the process with the msg. But there is one case where if the user changed the name of downloaded package provided in the `source` then I in code we will not be able to find the original name/version of the package. 
For example, if the correct source value is  ` splunkforwarder-8.1.4-17f862b42a7c-linux-2.6-x86_64.rpm` and if it got updated to something like `foo-8.1.4-17f862b42a7c-linux-2.6-x86_64.rpm` or `splunkforwarder.rpm` then in first case we will get `name: "foo"`, `version: "8.1.4-17f862b42a7c-linux-2.6-x86_64.rpm"`. In second,  `name: "splunkforwarder"`, `version: nil`. 

In such cases, I will not be able to get the exact package name or version and will not be able to compare it. Other than the source I am not able to find any other source to get the package we are about to installed/upgrade. So for such cases shall I add another fatal msg "We are not able to find the given package or version, please check if the source value is correct".

Or if you have any other suggestions please let me know.

**Comment by chef-davin** [comment]
Passing this on from the original requester:

Hi. I don't understand why 'allow downgrade' must be/has been deprecated for dnf_package, whereas it isn't for yum_package.  I did put the real RHEL8 example in the original attached .doc. dnf upgrade does NOT downgrade the package when a lower version of an installed package is the only version available in the repo. 
It's probably my lack of understanding of the code underneath, but I do think it's a fair question.

**Comment by mikeinsa77** [comment]
Test comment.

**Comment by lamont-granquist** [comment]
This should be able to be handled by:

```ruby
dnf_package 'splunkforwarder >= 8.1.4' do
  action :upgrade
end
```

You can also do this which won't upgrade until you bump the constraint:

```ruby
dnf_package 'splunkforwarder >= 8.1.4' do
  action :install
end
```

**Comment by snehaldwivedi** [comment]
@lamont-granquist I have tried this but it also installed a downgrade version if we provide `source` and without source it dose nothing as follows:

cat cookbooks/dnf_test/recipes/default.rb 
```
dnf_package 'splunkforwarder >= 8.2.2' do
  source "/home/ec2-user/splunkforwarder-8.2.1-ddff1c41e5cf-linux-2.6-x86_64.rpm"
  action :upgrade
end
```
o/p:
```
$ sudo chef-client recipes/default.rb 
Chef Infra Client, version 17.4.38
Patents: https://www.chef.io/patents
Infra Phase starting
[2021-09-24T10:33:13+00:00] INFO: *** Chef Infra Client 17.4.38 ***
[2021-09-24T10:33:13+00:00] INFO: Platform: x86_64-linux
[2021-09-24T10:33:13+00:00] INFO: Chef-client pid: 18799
[2021-09-24T10:33:16+00:00] INFO: Run List is []
[2021-09-24T10:33:16+00:00] INFO: Run List expands to []
[2021-09-24T10:33:16+00:00] INFO: Starting Chef Infra Client Run for snehaldwivedi
[2021-09-24T10:33:16+00:00] INFO: Running start handlers
[2021-09-24T10:33:16+00:00] INFO: Start handlers complete.
Resolving cookbooks for run list: []
[2021-09-24T10:33:16+00:00] INFO: Loading cookbooks []
Synchronizing cookbooks:
Installing cookbook gem dependencies:
Compiling cookbooks...
[2021-09-24T10:33:16+00:00] WARN: Node snehaldwivedi has an empty run list.
Converging 1 resources
Recipe: @recipe_files::/home/ec2-user/cookbooks/dnf_test/recipes/default.rb
  * dnf_package[splunkforwarder >= 8.2.2] action upgrade[2021-09-24T10:33:17+00:00] INFO: Processing dnf_package[splunkforwarder >= 8.2.2] action upgrade (@recipe_files::/home/ec2-user/cookbooks/dnf_test/recipes/default.rb line 6)
[2021-09-24T10:33:25+00:00] INFO: dnf_package[splunkforwarder >= 8.2.2] upgraded(allow_downgrade) splunkforwarder >= 8.2.2 to 0:8.2.1-ddff1c41e5cf.x86_64

    - upgrade(allow_downgrade) package splunkforwarder >= 8.2.2 from 0:8.2.2-87344edfcdb4.x86_64 to 0:8.2.1-ddff1c41e5cf.x86_64
[2021-09-24T10:33:28+00:00] INFO: Chef Infra Client Run complete in 12.545101209 seconds

Running handlers:
[2021-09-24T10:33:28+00:00] INFO: Running report handlers
Running handlers complete
[2021-09-24T10:33:28+00:00] INFO: Report handlers complete
Infra Phase complete, 1/1 resources updated in 14 seconds
```

For upgrade, we can use `dnf upgrade` command instead of `dnf install` that don't downgrade the package check as follows 

On my system, I have already installed  splunkforwarder-8.2.2
```
$ sudo dnf upgrade splunkforwarder-8.2.1-ddff1c41e5cf-linux-2.6-x86_64.rpm
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.

Last metadata expiration check: 2:41:18 ago on Fri 24 Sep 2021 07:54:02 AM UTC.
The same or higher version of splunkforwarder is already installed, cannot update it.
Dependencies resolved.
Nothing to do.
Complete!
```
So I will be working on making these changes, please let me know if you would like me to go with any other solution.

**Comment by mikeinsa77** [comment]
I'm still concerned that this is not a version-agnostic solution.  You are still doing version specific management in the chef code with this construct:  dnf_package 'splunkforwarder >= 8.2.2' do
-
If you use a repo, and not the source attribute like we want to, the allow_downgrade false in yum_package for RHEL7 works perfectly, but it's deprecated in Chef for dnf_package for RHEL8.  I'm still unclear why that happened, as native dnf doesn't behave like the resource does (evidenced in my original .docx attachment).

Thanks.
mike.wood@gmfinancial.com

**Comment by snehaldwivedi** [comment]
Hi mikeinsa77,

As I have explained in my previous comment for upgrade I am going to use `dnf upgrade` command instead of `dnf install` that doesn't downgrade the package even if the lower version is provided. 

Thanks

**Comment by mikeinsa77** [comment]
Hi.  I somehow missed that bit in the discussion.  Thanks for the update.

**Comment by lamont-granquist** [comment]
It'd be useful to be really clear about the use case here because its difficult to infer.  What is installed, what is the candidate version, what is the exact command being run, what is the expected behavior, and overall what the is the job which is trying to get done.

> I'm still concerned that this is not a version-agnostic solution.  

My gut response to this, based on 25 years of configuration management work on unix systems, is that having chef be authoritative for the RPM and the version of the RPM is always the correct thing to do.  And the problem here is that I sort of can't quite guess what you're really trying to do or how you've arrived at these kinds of requirements.  The use case being discussed also seems to change a bit throughout this issue and I can't quite track what is the real concern (I think the original use was probably cut down to the point where the meaning may have been lost).  

What this issue needs is just a real simple use case of how the server is configured, what happened to get it there and why, and exactly what the desired goal is.  Why is :update being used over :install?  What part of the system is responsible for the authoritative source of what the version should be?  Is this just a case of people hand managing installing RPMs that shouldn't ever be downgraded or something?  I honestly can't quite tell what the real use case is.  It is probably in here somewhere but this issue is turning into quite a wall of text.

**Comment by mikeinsa77** [comment]
Sorry for the lengthy post before.  Replying to the original via E-mail was obviously a bad idea in hindsight...lol

My original use case in the Chef Support ticket I opened was in the attached .docx file, but I don't see it here.
In a nutshell, using dnf_package with the action :upgrade option would actually downgrade a package if the version installed on the system was higher than what was available in an enabled yum repo.  

That presents an issue when a package upgrade is installed manually on RHEL8 servers running Chef, which does happen for more than 1 application in our environment (as part of the testing process).  

Later, once a version of a packaged is approved, we can update it in our repo (Artifactory in this case), and not have to make version-specific Chef cookbook edits.

[Response to the last bit - I respect the 25 years in Unix Configuration Management.  I have almost that long myself in Unix+ some other disciplines.  I did Configuration Management the hard way for a long time with Perl/ksh etc., but I'm relatively new to the automated configuration management game (Puppet / Chef / Ansible / etc.).  I didn't assert how I think Chef should or shouldn't behave, but merely asked the question  - why did allow_downgrade false disappear?  I also ack'd not understanding the code underneath.  But what I did know is that
# dnf upgrade 

didn't act like

dnf_package
  action :upgrade
end

On the surface to me, allow_downgrade false seemed like the simple solution.  If internally it's not, then so be it.  You guys are the Chef experts...:) ]
