### ISSUE TITLE
Chef Infra Client FIPS mode support for RHEL on Power PC is broken

### ISSUE THREAD

**Issue by msys-sgarg** [chef/chef#11712]
## Description
https://github.com/chef/customer-bugs/issues/394

The release notes for version 17.0 of the Chef Infra Client claim to support FIPS mode for RHEL systems running on PowerPC hardware. After testing version 17.1.35 in Kitchen with PPC image templates with FIPS enabled we see the following error:

>  /opt/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-config-17.1.35/lib/chef-config/config.rb:1262:in `fips_mode=': This version of OpenSSL does not support FIPS mode (OpenSSL::OpenSSLError)

## Chef Version
 chef-client version 17.1.35 

## Platform Version
RHEL 7 PPC node

## Replication Case
```
Install chef-client version 17.1.35 on a RHEL 7 PPC node.
Set `fips true` in client.rb.
```
Test kitchen should be a success 

## Expected Output 
chef-client run completes in fips mode

## Actual Behaviour
chef-client fails with "This version of OpenSSL does not support FIPS mode (OpenSSL::OpenSSLError)"
https://docs.chef.io/release_notes_client/#powerpc-rhel-fips-support states "PowerPC RHEL FIPS Support"

**Comment by msys-sgarg** [comment]
For executing `knife bootstrap with --fips options` We need the chef ruby to point an OpenSSL version where fips_mode can be set to true. Right now its not happening, with chef-workstation installation if I navigate to directory - `/opt/chef-workstation/embedded/bin` and 
run this command - `ruby -ropenssl -e "puts OpenSSL::OPENSSL_VERSION"` 
I get this output 
`OpenSSL 1.1.1  11 Sep 2018`

While In my current environment, I have enabled OpenSSL to use fips mode. So my current system's `openssl version` is :-
`OpenSSL 1.0.2g-fips  1 Mar 2016`

I am not sure why ruby is not pointing to host OS's openssl version and what settings which may need to be done for it to work that ways. Or is there any other chef-workstation build that has a ruby which supports `OpenSSL fips_mode` ? 

I am still working on tweaking it though

**Comment by tas50** [comment]
Workstation on the mac is openssl 1.1.1 so relying on that being enabled for FIPS is very very wrong. We need to know what the client is and you don't know that until the client is actually installed.

**Comment by msys-sgarg** [comment]
@tas50 Currently knife bootstrap command with `--fips` option does not install chef-infra client to the remote server. Instead fails on the workstation itself with following error : - 
`ERROR: OpenSSL::OpenSSLError: This version of OpenSSL does not support FIPS mode`

The above error comes even before knife tries to perform ssh to the remote client. 

I had earlier assumed that probably workstation openssl needs to be fips complaint as well and hence was trying to find a solution on those lines. But the issue is happening due to following line of code in `knife/lib/chef/knife.rb`

```
def maybe_setup_fips
      unless config[:fips].nil?
        Chef::Config[:fips] = config[:fips]
      end
HERE => Chef::Config.init_openssl
    end
```
If i comment out the above line of code and run knife bootstrap.. The client node which is currently RHEL 8 is bootstrapped properly with fips mode enabled 

```
Compiling Cookbooks...
[2021-06-18T05:45:01+00:00] WARN: Node issue_10964_default_1615370663911_2590 has an empty run list.
 [3.143.108.201] Converging 0 resources
 [3.143.108.201] 
Running handlers:
Running handlers complete
Chef Infra Client finished, 0/0 resources updated in 03 seconds
root@vagrant:/vagrant# bundle exec knife bootstrap 3.143.108.201 -i smriti.pem -N issue_10964_default_1615370663911_2590 -U ec2-user --bootstrap-version 17.1.35 --fips --use-sudo-password --sudo
root@vagrant:/vagrant# bundle exec knife bootstrap 3.143.108.201 -i smriti.pem -N issue_10964_default_1615370663911_2590 -U ec2-user --bootstrap-version 17.1.35 --fips --use-sudo-password --sudo
Connecting to 3.143.108.201 using ssh
The authenticity of host '3.143.108.201 ()' can't be established.
fingerprint is SHA256:mQN9yqkHBYbYzYVvul/Xt1pABd9K2/WzfjA7augQbr4.

Are you sure you want to continue connecting
? (Y/N) Y
Connecting to 3.143.108.201 using ssh
Node issue_10964_default_1615370663911_2590 exists, overwrite it? (Y/N) Y
Client issue_10964_default_1615370663911_2590 exists, overwrite it? (Y/N) Y
Creating new client for issue_10964_default_1615370663911_2590
Creating new node for issue_10964_default_1615370663911_2590
Bootstrapping 3.143.108.201
 [3.143.108.201] -----> Existing Chef Infra Client installation detected
 [3.143.108.201] Starting the first Chef Infra Client Client run...
 [3.143.108.201] Starting Chef Infra Client, version 17.1.35
Patents: https://www.chef.io/patents
OpenSSL FIPS 140 mode enabled
 [3.143.108.201] resolving cookbooks for run list: []
 [3.143.108.201] Synchronizing Cookbooks:
 [3.143.108.201] Installing Cookbook Gems:
Compiling Cookbooks...
[2021-06-18T06:35:07+00:00] WARN: Node issue_10964_default_1615370663911_2590 has an empty run list.
 [3.143.108.201] Converging 0 resources
 [3.143.108.201] 
Running handlers:
Running handlers complete
Chef Infra Client finished, 0/0 resources updated in 02 seconds
```
For test-kitchen this issue I could not reproduce. It is not picking up `fips` settings from my config.rb while installing OS on rhel 7 node and the installation is successful but without FIPS.

**Comment by msys-sgarg** [comment]
https://github.com/chef/customer-bugs/issues/405 - This bug is also talking about same issue

**Comment by tas50** [comment]
This was fixed with a new version of Expeditor that properly passes the FIPS env vars to these PPC systems.

**Comment by msys-sgarg** [comment]
@tas50 but what I reported as `knife bootstrap` behaviour in above comment. Is that not a different issue ?
