### ISSUE TITLE
Knife Bootstrap not working with --fips option enabled

### ISSUE THREAD

**Issue by msys-sgarg** [chef/chef#11758]
## Description
When we try to bootstrap a node using `knife  bootstrap` command and option `--fips`, it throws an error. According to documentation here https://docs.chef.io/workstation/knife_bootstrap/ - Bootstrap operation should start with an output something similar to 
```
OpenSSL FIPS 140 mode enabled
...
192.0.2.0 Chef Infra Client finished, 12/12 resources updated in 78.942455583 seconds
```
As per a discussion with Tim over here - 
https://github.com/chef/chef/issues/11712#issuecomment-863626518

Knife is trying to enable fips on the host OS while this should not be case. Currently a non fips host cannot run `knife bootstrap --fips` for a fips enabled client. 

## Chef Version
Chef Infra Client version: 17.2.29

## Platform Version
Ubuntu-18.04

## Replication Case

Execute command - 
`knife bootstrap 3.143.108.201 -i "~/Downloads/smriti.pem" -U ec2-user -r "/home/smriti/Work/chef-client/initi-rhel-client/recipes/default.rb" --bootstrap-version 17.1.35 --fips` 

## Client Output
```
ERROR: OpenSSL::OpenSSLError: This version of OpenSSL does not support FIPS mode
```

**Comment by lamont-granquist** [comment]
So `knife bootstrap --fips` should fail on a non-fips host.  always.  for any command.

What could be done is to have `knife bootstrap --bootstrap-fips` for a non-fips knife workstation to bootstrap a fips host, where the fips setting was rendered into the bootstrap_context or windows_bootstrap_context.

**Comment by msys-sgarg** [comment]
As per comment from Lamont, this is not an issue and working as per standards. I am closing this issue
