### ISSUE TITLE
Unable to install Omnibus RPM on EL8 FIPS systems: Digest Errors

### ISSUE THREAD

**Issue by collinmcneese** [chef/chef#11790]
## Description

The Chef Infra Client omnibus RPM installation fails when trying to install on EL8 systems with FIPS mode enabled with `digest` errors, likely due to missing or improper parsing of SHA256 sum which is the required signing for RPM packages when running in FIPS mode on EL8 (details on install types below)

## Chef Version

16 & 17, tested with:
- 16.13.16 - `package chef-16.13.16-1.el7.x86_64 does not verify: no digest`
- 16.13.44 - `error: unpacking of archive failed on file /opt/chef/LICENSE;60e5b3f5: cpio: Digest mismatch`
- 17.2.29 - `error: unpacking of archive failed on file /opt/chef/LICENSE;60e5b3fc: cpio: Digest mismatch`
- 17.3.21 - `error: unpacking of archive failed on file /opt/chef/LICENSE;60e5b404: cpio: Digest mismatch`

## Platform Version

EL8-variant systems (RHEL8, CentOS8, etc).  Output below is from `CentOS 8.3.2011` & `8.4.2105`

## Replication Case

- Enable FIPS mode on an EL8 system (`sudo fips-mode-setup --enable && shutdown -r now`)
- Attempt to install Chef Infra Client 16 or 17 via omnitruck install script or directly via RPM from packages.chef.io

## Client Output

```plain
[root@localhost tmp]# rpm -Uvh  /tmp/install.sh.5331/chef-16.13.16-1.el7.x86_64.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
	package chef-16.13.16-1.el7.x86_64 does not verify: no digest


[root@localhost tmp]# rpm -Uvh /tmp/install.sh.6022/chef-16.13.44-1.el8.x86_64.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
removing /opt/chef...
Updating / installing...
   1:chef-16.13.44-1.el8              ################################# [100%]
error: unpacking of archive failed on file /opt/chef/LICENSE;60e5b3f5: cpio: Digest mismatch
error: chef-16.13.44-1.el8.x86_64: install failed


[root@localhost tmp]# rpm -Uvh /tmp/install.sh.5500/chef-17.2.29-1.el8.x86_64.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
removing /opt/chef...
Updating / installing...
   1:chef-17.2.29-1.el8               ################################# [100%]
error: unpacking of archive failed on file /opt/chef/LICENSE;60e5b3fc: cpio: Digest mismatch
error: chef-17.2.29-1.el8.x86_64: install failed
[root@localhost tmp]# 


[root@localhost tmp]# rpm -Uvh /tmp/install.sh.5978/chef-17.3.21-1.el8.x86_64.rpm
Verifying...                          ################################# [100%]
Preparing...                          ################################# [100%]
removing /opt/chef...
Updating / installing...
   1:chef-17.3.21-1.el8               ################################# [100%]
error: unpacking of archive failed on file /opt/chef/LICENSE;60e5b404: cpio: Digest mismatch
error: chef-17.3.21-1.el8.x86_64: install failed

```

**Comment by lamont-granquist** [comment]
https://access.redhat.com/solutions/148653

https://bugzilla.mozilla.org/show_bug.cgi?id=1064588

**Comment by lamont-granquist** [comment]
we might be shipping libgcc, that tickles one of my braincells.

**Comment by tas50** [comment]
This was resolved in omnibus
