### ISSUE TITLE
RPM --import failing due to "not an armoured key"

### ISSUE THREAD

**Issue by dpresling** [chef/chef#11799]
## Description
when running `rpm --import https://packages.chef.io/chef.asc`  as per the installation instructions here https://docs.chef.io/packages/#enterprise-linux I'm getting the following error:

```error: https://packages.chef.io/chef.asc: key 1 not an armored public key```

## Chef Version
Trying to install any version

## Platform Version
Running on CentOS/Amazon Linux

## Replication Case
On Amazon Linux run `$ rpm --import https://packages.chef.io/chef.asc`

## Client Output
```
$ sudo rpm --import https://packages.chef.io/chef.asc
error: https://packages.chef.io/chef.asc: key 1 not an armored public key.
```

**Comment by dpresling** [comment]
Using wget to fetch the file locally then adding a new line to the end of the file fixes this but that shouldn't be a necessary work-around.

**Comment by tduffield** [comment]
@dpresling I'm unable to replicate the issue on Amazon Linux 2. Is this still an issue for you? If so, can you provide a more specific replication case? Maybe the specific AMI or OS version on which you're having the issue?

**Comment by dpresling** [comment]
This does now appear to be working. Thanks for looking into it. I'll roll back our local workarounds.
