### ISSUE TITLE
Add warning to secrets method

### ISSUE THREAD

**Issue by tas50** [chef/chef#11835]
We need to make sure it's well understood that this is a beta that is likely to change.

"The secrets Chef Infra language helper is currently in beta. This helper will most likely change over time in potentially breaking ways. If you have feedback or you'd like to be part of the future design of this helper e-mail us at secrets_management_beta@progress.com"

**Comment by marcparadise** [comment]
@tas50 is a warning log entry sufficient, or do we want something more visible? 

Separately, it might be cool if we emitted something in `knife upload` when a cookbook is uploaded.
