### ISSUE TITLE
Ruby 3.0 Slowness while Installing Gems (from Private Artifactory Repo) 

### ISSUE THREAD

**Issue by vinayakvakkund** [chef/chef#11832]
While installing Gems from internal private repo (Artifactory) experiencing slowness. When version is not explicitly not mentioned , all the dependency gemspecs are getting downloaded to cache.

**Comment by tas50** [comment]
Can we get this tested out with Infra Client 17.3

**Comment by vinayakvakkund** [comment]
> Can we get this tested out with Infra Client 17.3

I tested it in 17.3 but no luck.

**Comment by tas50** [comment]
Closing this out since it turned out to be a known issue in artifactory
