### ISSUE TITLE
installed Windows Chef Infra Client v17.2.29 but chef-client run reports 15.14.0

### ISSUE THREAD

**Issue by csol01** [chef/chef#11855]
## Description
I've just downloaded and pushed out Chef Infra Client v17.2.29 to my AWS hosted EC2 instances, but if I run Chef-Client manually I'm seeing this at the start of the run:

Starting Chef Infra Client, version 15.14.0

I'm just a bit confused as to whether the version I've downloaded is correct or not?

## Chef Version
17.2.29 (x64 Windows)

## Platform Version
AWS EC2 Windows 2016

## Replication Case
Installing the latest version and running chef-client

**downloaded file:** chef-client-17.2.29-1-x64.msi

## Client Output
Starting Chef Infra Client, version 15.14.0

## Stacktrace

N/A

**Comment by tas50** [comment]
The system probably still has old files left around. You probably want to uninstall 17. Remove the install directory and reinstall.

**Comment by csol01** [comment]
Hey @tas50 

The client is running on cattle (AWS Windows EC2), so they're built from scratch daily and thus don't have any chef related files on them until it's finished being bootstrapped.

any other ideas?

**Comment by csol01** [comment]
Hi @tas50 ,

Might have leapt here...

I've got Chef Infra Client and ChefDK installed on the same box so I'm assuming they're interferring with each other somehow as the version issue isn't showing up on other boxes with just the infra client installed.

just run some version checks and yep, they're both in the PATH variable but chefdk version of chef-client is getting used rather than the chef infra client.

Sorry for the hassle.

Chris.
