### ISSUE TITLE
'registry_key' resource's values can't be set lazily.

### ISSUE THREAD

**Issue by sjethvani** [chef/chef#11877]
In one of chef recipe , I am reading one of existing registry & trying to set its updated value lazily through 'registry_key' block. However it seems `lazy` evaluation for `values` is not working properly & simply gives an error like `ArgumentError: Bad type for RegistryKey resource, use Hash or Array`

_Sample recipe_
```
# Simple Recipe:: rectify-java-param-heapdump

node.default['options_value1'] = []
  
#Fetching existing registry value of abc service
ruby_block "heapdump - Proceeding for modifying registry" do
      block do
        existing_value = registry_get_values("HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Apache Software Foundation\\Procrun 2.0\\ABC\\Parameters\\Java", :x86_64)
        Chef::Log.info("heapdump existing value is - service is  ")
        Chef::Log.info(existing_value)
        #Checking existing registry value & storing conditionally modified registry object in variable
        existing_value.each{|e| 
           if e[:name] == "Options" 
            		node.override['options_value1'] = e[:data]
            		node.override['options_value1'].insert(-1, "-XX:+HeapDumpOnOutOfMemoryError")
           end
        }
		Chef::Log.info("here heapdump options node value is ")
		Chef::Log.info(node['options_value1'])  //Here , I get above heapdump jvm param added in node['options_value1']
      end
	  action :run
end

#Setting updated 'Options' param's value for given abc tomcat service in registry
registry_key "HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Apache Software Foundation\\Procrun 2.0\\ABC\\Parameters\\Java" do
	 values lazy {[{
        name: 'Options',
        type: :multi_string,
        data: node['options_value1']
      }]}
      action :create
end
```

This gives
```
[2021-07-29T14:25:02+05:30] DEBUG: ArgumentError: Bad type for RegistryKey resource, use Hash or Array
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.32-universal-mingw32/lib/chef/resource/registry_key.rb:86:in `values'
```

, which is because below block in registry_key resource accepts only these 2 types of values & since 'lazy' is a method , it simply fails at compile time.

https://github.com/chef/chef/blob/1021d5e517c65dabde7902bcad35e439156dcc19/lib/chef/resource/registry_key.rb#L167-L177

I have discussed this in slack chef channel & was suggested a workaround to create a custom chef resource (may be to bypass this lazy thing , IMO) , however filing this issue as reference here , so that people like me troubleshooting these kinda thing know that _'registry_key' resource's value can't be set lazily._

**Comment by lamont-granquist** [comment]
The values method needs to be converted to be a property, while carefully retaining all the type checking, coercion, and validation that the existing method does:

https://github.com/chef/chef/blob/4d471fb960ab2130a856e4b36ab7ce23df5bb563/lib/chef/resource/registry_key.rb#L166-L195

**Comment by tas50** [comment]
I believe there's an issue for that somewhere. This resource can't be documented right now since it's not a real property.

**Comment by tas50** [comment]
Fix merged to main branch
