### ISSUE TITLE
Compliance phase: Make CLI reporter always run

### ISSUE THREAD

**Issue by tas50** [chef/chef#11916]
```
As a Chef Infra operator
I want to always see the compliance phase output
so that I can see the status of compliance on my nodes from the CLI
```

## Acceptance criteria

- Not including the CLI reporting in the attributes no longer changes output
- CLI output always runs

**Comment by lamont-granquist** [comment]
you mean like this?  27c70a4ac01

**Comment by tas50** [comment]
If you set you're own attribute it goes away though

**Comment by lamont-granquist** [comment]
ohhhhh gotcha

well we should do #11924 anyway, but that doesn't solve that problem.
