### ISSUE TITLE
undefined method `elements' for nil:NilClass for windows_task resource in chef-client v13.8.0

### ISSUE THREAD

**Issue by hiyer** [chef/chef#11926]
## Description
We're hitting the same error as described in https://github.com/chef/chef/issues/6585. This issue was ostensibly fixed in 13.7, however we're observing it on at least 2 machines with 13.8 as well.

## Chef Version

13.8.0

## Platform Version

Windows 10 Pro

## Replication Case

Our resource definition is as follows:
```
windows_task 'chef-solo-windows' do    
    command '<redacted>'     
    run_level :highest    
    frequency :minute    
    frequency_modifier 2    
    execution_time_limit '600'    
    action [:delete, :create, :enable]    
    ignore_failure true    
end    
```

## Client Output

```
0m  * windows_task[chef-solo-windows] action enable[2021-06-07T08:20:39-04:00] INFO: Processing windows_task[chef-solo-windows] action enable (self::default_windows line 160)
[2021-06-07T08:20:44-04:00] ERROR: windows_task[chef-solo-windows] (self::default_windows line 160) had an error: NoMethodError: undefined method `elements' for nil:NilClass; ignore_failure is set, continuing

[0m
================================================================================[0m
[31mError executing action `enable` on resource 'windows_task[chef-solo-windows]'[0m
================================================================================[0m

[0m    NoMethodError[0m
-------------[0m
undefined method `elements' for nil:NilClass[0m
```

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it. -->

```

```

**Comment by tas50** [comment]
13.8 is not a version of Chef Infra Client we support. You'll need to reproduce this issue on 16.x or later. If you're still running into the problem feel free to open this again.

**Comment by hiyer** [comment]
Thanks for your response @tas50 . We shall try the same and get back to you.
