### ISSUE TITLE
Bug: knife client create

### ISSUE THREAD

**Issue by jasonwbarnett** [chef/chef#11985]
## Description
 
https://github.com/chef/chef/pull/11241 broke knife client create. The method name indicates it's *or* but it's obvious from the [#check_writable_or_exists][2] method that it was implemented incorrectly and the [unit test][3] is validating the bad behavior. Additionally the [integration test change][4] is effectively implementing the workaround of "touching" the file before create. If the file does not exist (which it shouldn't) it will simply fail stating the file does not exist (which again, it shouldn't; this is a new client and we wish to save the key to the file that does not exist).

## Chef Version

v17.4.38

## Platform Version

Red Hat 7

## Workaround

Simply touch the file where you wish to save the new client key to.

```
$ touch /home/user/my-new-node-name.pem
$ knife client create my-new-node-name --file /home/user/my-new-node-name.pem --disable-editing --config /home/user/my-client-config.rb
```

## Replication Case / Client Output

```text
$ knife client create my-new-node-name --file /home/user/my-new-node-name.pem --disable-editing --config /home/user/my-client-config.rb -VVV
INFO: Using configuration from /home/user/my-client-config.rb
FATAL: File /home/user/my-new-node-name.pem does not exist.
```

[2]: https://github.com/chef/chef/blob/fb087a1dce8addb27fd2dd3eb134bc7f28e1f23f/knife/lib/chef/knife/client_create.rb#L108-L119
[3]: https://github.com/chef/chef/blob/fb087a1dce8addb27fd2dd3eb134bc7f28e1f23f/knife/spec/unit/knife/client_create_spec.rb#L187-L193
[4]: https://github.com/chef/chef/blame/fb087a1dce8addb27fd2dd3eb134bc7f28e1f23f/knife/spec/integration/client_create_spec.rb#L53

**Comment by snehaldwivedi** [comment]
I have also tested it from our side PR https://github.com/chef/chef/pull/11986 is working fine and fixing the breaking issue.
