### ISSUE TITLE
Add a `:yaml` verifier to file resource

### ISSUE THREAD

**Issue by gogsbread** [chef/chef#12019]
### Describe the Enhancement:
Add a yaml buit-in verifier to check the syntax of yaml Chef resources as alluded in [design document](https://github.com/chef/chef/blob/main/docs/dev/design_documents/resource_file_content_verification.md)

### Describe the Need:
Users can use this functionality in their `file` resources 
```
   file 'foo.yaml' do
     content "--- foo: 'foo-"
     verify :yaml
   end
```
### Current Alternative
Write a helper library function in the recipe that is using a yaml template.

### Can We Help You Implement This?:
Implementation is [here](https://github.com/chef/chef/pull/12020). Would be great if one can assist in review.

**Comment by marcparadise** [comment]
Fixed with #12020
