### ISSUE TITLE
Chef 16 mount resource strips trailing / even for root directory

### ISSUE THREAD

**Issue by jiokmiso** [chef/chef#12021]
## Description

Since #10614, mount resource is updated to have coerce in mount_point attribute. root directory 
There were several issues around for root of the network mount, but the same change is also affecting the plain root directory. After the coercion, it is simply going to be nil. This can be checked in the trace log that I attached in gist by looking at the log 
```
TRACE: mount[/] is enabled at 
INFO: mount[/] enabled 
```

This new behavior leaves unwanted consequences like below
```
vagrant@test-mp-oel-77-chef16.vagrantup.com:~ ( test-mp-oel-77-chef16.vagrantup.com )
12:03:25 $ cat /etc/fstab
/dev/mapper/vg00-rootlv00 / xfs defaults 0 2
/dev/mapper/vg00-rootlv00  xfs defaults 0 2
```

## Chef Version

16.7.34 or after is affected(based on the tag in this repo)

## Platform Version

I tested this in Oracle Linux 7.7 but this should be problematic across RHEL based OS at least.

## Replication Case

Calling mount resource having '/' on mount_point attribute like below will have the issue.
```
mount '/' do
  action :enable
  device '/dev/mapper/vg00-rootlv00'
  fstype 'xfs'
end
```

## Client Output

https://gist.github.com/jiokmiso/2b200bf555b5b6fecefbb49367d86fdd

**Comment by tas50** [comment]
Closing this since the fix is merged. Thanks @jiokmiso
