### ISSUE TITLE
automate updates from new powershell-shim releases 

### ISSUE THREAD

**Issue by rishichawda** [chef/chef#12030]
### Describe the Enhancement:

Automate updates to the `distro` directory when the https://github.com/chef/chef-powershell-shim package is updated.

### Describe the Need:

Currently we have to manually run `update_chef_exec_dll` task in windows to pull in the updates from the new release. 

### Current Alternative

manually run `bundle exec rake update_chef_exec_dll`, commit the changes, create a PR and merge it to `main`.

**Comment by lamont-granquist** [comment]
This issue will be rendered obsolete by moving powershell_exec and the dlls into their own gem.

**Comment by tas50** [comment]
Yep let's just make sure to get an expeditor subscription setup for the new gem name so releases trigger a gemfile.lock update
