### ISSUE TITLE
Allow including compliance profiles from Automate / Supermarket / Github via DSL

### ISSUE THREAD

**Issue by tas50** [chef/chef#12101]
This is a placeholder issue.

I need to do interviews with folks in the field / customers to understand the usage before we come up with a design here.

**Comment by lamont-granquist** [comment]
It probably is more or less "as simple" as just:

`include_profile "a2://mya2/myprofile"`

and 

`inspec_profile "a2://mya2/myprofile"`

With some thinking about what kinds of schemes to support (and i think there's prior art there already)

**Comment by tas50** [comment]
Replaced with https://chefio.atlassian.net/browse/INFC-79
