### ISSUE TITLE
See if we can install knife on client on all platforms / add test

### ISSUE THREAD

**Issue by tas50** [chef/chef#12134]
See if we can install the client onto all platforms and add a test to ensure we don't break that by accident again.

fixes: https://github.com/chef/customer-bugs/issues/473

**Comment by vkarve-chef** [comment]
@tas50 i believe we can start with remediating the knife gem install failure on Win2012. additionally, we'll assume tests need to be in place to check knife installs successfully on all supported platforms?

**Comment by tas50** [comment]
Potentially fixed by https://github.com/chef/chef/pull/12142

We can't build this right now do to issues with our pipelines, but once those are resolved we'll be able to see if this works.

**Comment by tas50** [comment]
We did this
