### ISSUE TITLE
Add the ability to use include_profile in a Policyfile + InSpec

### ISSUE THREAD

**Issue by kmf** [chef/chef#12138]
### Describe the Enhancement:
It would awesome to have an `include_profile` in a Policyfile

```
include_profile 'cis-mysql', github: 'cis-benchmarks/cis-mysql', branch: 'main'
include_profile 'cis-docker', git: 'https://gitlab.com/cis-benchmarks/cis-docker.git', tag: 'v1.1.0'
```

### Describe the Need:
- Build an Immutable Reusable Artifact with external InSpec Profiles
- Give you the ability to reuse InSpec Profiles in other Policyfiles, increases the ability to scale

**Comment by tas50** [comment]
@kmf this is a dupe of a few other issues we had to tackle this and we're tracking it internally in https://chefio.atlassian.net/browse/INFC-79
