### ISSUE TITLE
Spike - Powershell DLL and chef client

### ISSUE THREAD

**Issue by marcparadise** [chef/chef#12173]
Determine how to best distribute the powershell DLLs that are installed with the powershell gem and chef-client. 

The concern here is that we might be breaking windows `gem install chef` path.  However, discussion in standup suggests that this is already broken.  

Let's find out if it is first, by installing the chef gem on a clean machine (that does not have any our powershell DLLs installed), and converging `chef-client` with a recipe that uses powershell.   Based on what we saw, we expect the DLLs will not load and the converge will fail.  

Assuming it fails - which means that we won't break it any worse, we have a couple of options to explore:

1) Let's see if providing the explicit path the to library in ffi_lib declaration works.  If it does, that will let us incidentally fix the currently-broken chef client gem install as part of this change. 

2) If it does not work, then we can continue down the original path - modify the omnibus install to put the powershell gem DLLs in the correct location, but do not  take steps to do anything when installed by `gem install`. We may need to also remove the existing logic from the gem post-install since (presumably) that loc
ation isn't currently working for the DLLs anyway.

If the chef-client standalone gem install /does/ work currently, we can instead see if modifying the chef-powershell gem to take similar post-install actions as chef-gem will keep it working.

**Comment by johnmccrae** [comment]
Did a clean ruby install then used gem from that distro to install the chef gem. As expected the powershell files are not copied to the same folder as ruby.exe. However, chef-vault and chef-zero ARE copied there. It might be interesting to understand that better but adjusting the path to correct load the PowerShell DLL's probably makes more sense.

**Comment by johnmccrae** [comment]
At the top of any file that loads a powershell dll add this requires statement:
`requires "chef-powershell"`

then modify the load statement from this:

`@dll ||= "Chef.PowerShell.Wrapper.dll"`

to this:

```Ruby
powershell_dll = Gem.loaded_specs['chef-powershell'].full_gem_path + "/bin/ruby_bin_folder/#{ENV["PROCESSOR_ARCHITECTURE"]}/Chef.PowerShell.Wrapper.dll"
@dll ||= powershell_dll
```

This is working in testing so far. Need to do more but it solves all the problems.
