### ISSUE TITLE
Add support for upcoming Ubuntu 22.04

### ISSUE THREAD

**Issue by tas50** [chef/chef#12253]
We need to make sure that we support Ubuntu 22.04 before it's released in April 2022. This work should be done so that we have a released build of 16/17 out before Ubuntu 22.04 is released.

**Comment by nielsbuus** [comment]
Hey @tas50, from what I can see at https://www.chef.io/downloads/tools/infra-client?os=ubuntu, it looks like there still isn't a chef-client for Ubuntu 22.04 available and this GitHub issue is the first result on Google on the topic.

Is it correct that chef-client won't run on Ubuntu 22.04 LTS ?

**Comment by axl89** [comment]
Also interested in this topic. @tas50 is there any update on this?

**Comment by nielsbuus** [comment]
@axl89 If you follow the link I posted above you can see that Chef 18 has now been released for Ubuntu 22.04

When I added my comment 2½ months ago, only Ubuntu 20.04 was supported.
