### ISSUE TITLE
Merge dependabot PRs

### ISSUE THREAD

**Issue by RajeshPaul38** [chef/chef#12262]
Merge dependabot PRs:
https://github.com/chef/supermarket/pull/2346/commits
https://github.com/chef/supermarket/pull/2345/commits
https://github.com/chef/supermarket/pull/2344/commits
https://github.com/chef/supermarket/pull/2343/commits
https://github.com/chef/supermarket/pull/2319/commits
https://github.com/chef/supermarket/pull/1935/commits

**Comment by tas50** [comment]
I moved this to supermarket. Closing here
