### ISSUE TITLE
Knife bootstrap issues when max-wait is specified

### ISSUE THREAD

**Issue by jritchie-nullable** [chef/chef#12281]
## Description
When specifying -max-wait on the CLI for knife bootstrap the variable is passed through to winrm module as a float.  The winrm module tests for the value to be an integer which throws the following RuntimeError:

`ERROR: RuntimeError: retry_limit must be a Integer`

The problem is is with this line of code calling to_f:
https://github.com/chef/chef/blob/a90cddca0af69895415cb34051b15966a9b28277/knife/lib/chef/knife/bootstrap.rb#L933

## Chef Version
n/a

## Platform Version
n/a

## Replication Case
`knife bootstrap doesnt.really -o winrm --connection-user matter --connection-password tome --max-wait 60`

## Client Output
`Connecting to doesnt.really using winrm
ERROR: RuntimeError: retry_limit must be a Integer`

**Comment by vkarve-chef** [comment]
need to check if similar error occurs when using ssh.

**Comment by jritchie-nullable** [comment]
@vkarve-chef The runtime error is thrown in the winrm module (called by winrm-train).

https://github.com/inspec/train-winrm/blob/3f458ab7f2fcdefb2b25fe822ad4397154c5a516/lib/train-winrm/connection.rb#L95
https://github.com/WinRb/WinRM/blob/ebbed119340c665d8220298c0103f0f106b3bc6b/lib/winrm/connection_opts.rb#L77
