### ISSUE TITLE
PFXExportCertStoreEx function in win32-certstore

### ISSUE THREAD

**Issue by johnmccrae** [chef/chef#12367]
This function is stubbed out in the crypto,rb file in the Win32-certstore project. It needs to be fully implemented and then use that to replace the PowerShell code in store_base.rb which we currently use to retrieve PFX objects with. In spending time investigating using this for Chef Client work I came across 2 problems that will require deeper development time than I had to give.

1) The function, by definition, returns all PFX objects in the given store. So if you're in LocalMachine Root, you might get back a blob of like 30 pfx files all combined into one giant blob. How in the world do you separate those objects out into individual files or PFX objects? There does not seem to be any byte-marker or EOF marker in the blob to distinguish the end of one object from the beginning of the next. This sort of implies that you'll need to write more CPP code to pull back corresponding data about individual certs/keys, get the size from that, then use THAT size data to iteratively pull PFX's out of the giant blob.

2) That function appears to add additional data to the blob output or, the current flags are allowing more objects to export than should be allowed. For example, individual pfx objects on disk are about 3k in size. When you run this function, the blob you get back isn't 3k, If you have, say, 5 PFX's in a given store, you would expect the blob you get back to be about 15k in size on disk but what you really get back is a blob of 25k. So that means either the function is retrieving more than we expect or adding additional data that needs to be dealt with. 

More reading https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-pfxexportcertstoreex

**Comment by johnmccrae** [comment]
Here's a start to the Ruby method. This thing takes 3 parameters

certstore_handler is the incoming handle to whichever store you are using
password is the password stored in the registry to use to export the pfx with
output_file can be the location of the expored pfx object. 

```ruby
      def cert_get_pfx(certstore_handler, password, output_file)
        # Need to find the number of certs in the store that could be exported
        # pfx size is ~3k

        if password == nil?
          password = get_cert_password
        end

        pfx_blob = CRYPT_DATA_BLOB.new # Will hold all the pfx objects located in the store described by certstore_handler
        key_properties = EXPORT_PRIVATE_KEYS.to_i

        # call Export the first time with a null data blob, the function returns how much memory you need to allocate
        # for the certs in the :cbData field
        PFXExportCertStoreEx(certstore_handler, pfx_blob, password, nil, key_properties)
        buffer_size = pfx_blob[:cbData]
        # create a new memorypointer type (as opposed to just FFI::Pointer) so you don't have to clear memory yourself and you pass in the size of memory you need
        location = FFI::MemoryPointer.new(buffer_size)
        pfx_blob[:pbData] = location
        # call the Export a second time with the correct amount of memory allocated to hold all the PFX objects
        PFXExportCertStoreEx(certstore_handler, pfx_blob, password, nil, key_properties)
        # method should have dumped the cert to the location specified in the pbData
        cert_blob_in_bin = location.read_bytes(pfx_blob[:cbData])
        bin_data = cert_blob_in_bin.b

      end
```

**Comment by johnmccrae** [comment]
https://stackoverflow.com/questions/44996810/exporting-pfx-file-from-windows-certificates-store
After doing more reading, here is what you need to do to get a single PFX out of a certstore

1) Open a cert store 
```cpp
if(hSystemStore = CertOpenSystemStore(
    0,
    pszStoreName))
{
  printf("The %s system store is open. Continue.\n", pszStoreName );
}
else
{
  MyHandleError("The first system store did not open.");
}
```
2) Find your cert
```cpp
// Get a certificate that has the desired friendly name. 
if(pCertContext=CertFindCertificateInStore(
      hSystemStore,
      MY_ENCODING_TYPE,             // Use X509_ASN_ENCODING
      0,                            // No dwFlags needed 
      CERT_NAME_FRIENDLY_DISPLAY_TYPE,        // Find a certificate
      pszNameString, // The Unicode string to be found
                                    // in a certificate's subject
      NULL))                        // NULL for the first call 
{
  printf("The %s certificate was found. \n", pszNameString);
}
else
{
   MyHandleError("Could not find the %s certificate.");
}```

3) Create a new temporary cert store in-memory
```cpp
HCERTSTORE hMemStore = CertOpenStore(CERT_STORE_PROV_MEMORY, 0, 0, CERT_STORE_CREATE_NEW_FLAG, 0 )
```

4) Add your cert to that temporary new location
```cpp
CertAddCertificateContextToStore(hMemStore, pCertContext, CERT_STORE_ADD_NEW, 0)
```

5) Finally you dump out THAT cert store using
```cpp
PFXExportCertStoreEx(hMemStore, &db, szPassword, 0, EXPORT_PRIVATE_KEYS|REPORT_NOT_ABLE_TO_EXPORT_PRIVATE_KEY)
```

**Comment by johnmccrae** [comment]
Use the examples here : https://docs.microsoft.com/en-us/windows/win32/seccrypto/example-c-program-listing-the-certificates-in-a-store

**Comment by PrajaktaPurohit** [comment]
close in favor of: https://chefio.atlassian.net/browse/INFC-7
