### ISSUE TITLE
Chef::Exceptions::JSON::ParseError in Chef Infra Client v17.8.25

### ISSUE THREAD

**Issue by mnazir23** [chef/chef#12378]
# Describe the problem
In one of my cookbooks, I am using the resource `windows_feature` to install some Windows features related to IIS. However, recently the resource has started failing with the following error.

      Error executing action install on resource windows_feature_powershell[Web-WebServer, Web-Asp-Net45, Web-Net-Ext45, Web-Default-Doc]
      Chef::Exceptions::JSON::ParseError
      ----------------------------------
      input must be a string or IO

      Resource Declaration:
      ---------------------
      # In C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.8.25-universal-mingw32/lib/chef/resource/windows_feature.rb

      131:           declare_resource(new_resource.install_method, new_resource.name) do
      132:             action desired_action
      133:             feature_name new_resource.feature_name
      134:             source new_resource.source if new_resource.source
      135:             all new_resource.all
      136:             timeout new_resource.timeout
      137:             management_tools new_resource.management_tools if new_resource.install_method == :windows_feature_powershell
      138:           end
      139:         end

      Compiled Resource:
      ------------------
      # Declared in C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.8.25-universal-mingw32/lib/chef/resource/windows_feature.rb:131:in `run_default_subresource'

The cookbook in which this code is running has not been changed for over a year and has been running fine since then which makes it clear that it is not the cookbook that's at fault.

The problem is with the latest chef-client version 17.8.25. When I downgraded to v17.7.29, the same cookbook started working without any issues as it had been doing previously.

## Software Version
Chef Infra Client v17.8.25

## Replication Case

1. Use chef-client v17.8.25.
2. Use the following piece of code `windows_feature ['Web-WebServer', 'Web-Asp-Net45', 'Web-Net-Ext45'] do
     action :install
     install_method :windows_feature_powershell
end`
3. Run the code and you should see the above mentioned error.

## Stacktrace
      Chef::Exceptions::JSON::ParseError
      ----------------------------------
      input must be a string or IO

      Resource Declaration:
      ---------------------
      # In C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.8.25-universal-mingw32/lib/chef/resource/windows_feature.rb

      131:           declare_resource(new_resource.install_method, new_resource.name) do
      132:             action desired_action
      133:             feature_name new_resource.feature_name
      134:             source new_resource.source if new_resource.source
      135:             all new_resource.all
      136:             timeout new_resource.timeout
      137:             management_tools new_resource.management_tools if new_resource.install_method == :windows_feature_powershell
      138:           end
      139:         end

      Compiled Resource:
      ------------------
      # Declared in C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.8.25-universal-mingw32/lib/chef/resource/windows_feature.rb:131:in `run_default_subresource'

Please fix this in the next release of the chef infra client.
Thank you.

**Comment by tas50** [comment]
The fix for this issue has been merged to main and will ship shortly in Chef Infra Client 17.9.

**Comment by mnazir23** [comment]
@tas50 
Thank you for letting me know
