### ISSUE TITLE
docker installation recipe returning undefined method `trace' for nil:NilClass

### ISSUE THREAD

**Issue by vynguyenchantal** [chef/chef#12373]
## Description
Encountered an error running a recipe to install docker.
`Running handlers: [2021-12-14T16:38:17+00:00] ERROR: Running exception handlers`
`Running handlers complete [2021-12-14T16:38:17+00:00] ERROR: Exception handlers complete`
`Chef Client failed. 0 resources updated in 35 seconds`
`[2021-12-14T16:38:17+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out`
`[2021-12-14T16:38:17+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report`
`[2021-12-14T16:38:17+00:00] FATAL: NoMethodError: yum_package[docker] (testcookbook::docker line 17) had an error: NoMethodError: undefined method `trace' for nil:NilClass`

Upon further investigation, /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/provider/package.rb has:
`      def initialize(new_resource, run_context)`
`        super`
`        @candidate_version = nil`
`      end`

I assume super invoking initialize() in /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/provider.rb as shown below. However, it does NOT seem to. Hence, the logger variable is NEVER instantiated.
`    def initialize(new_resource, run_context)`
`      @new_resource = new_resource`
`      @action = action`
`      @current_resource = nil`
`      @run_context = run_context`
`      @converge_actions = nil`

`      @logger = if run_context`
`                  run_context.logger.with_child({ resource: new_resource.name, cookbook: cookbook_name, recipe: recipe_name })`
`                else`
`                  Chef::Log.with_child({ resource: new_resource.name, cookbook: cookbook_name, recipe: recipe_name })`
`                end`

`      @recipe_name = nil`
`      @cookbook_name = nil`
`      self.class.include_resource_dsl_module(new_resource)`
`    end`

## Chef Version
14.10.9 (server is 12.19.26)

## Platform Version
RHEL 7

## Replication Case
test.rb
`package 'docker' do
  action [ :install, :upgrade ]
end
`

## Client Output
`chef-client -o testcookbook::test  -l info`
`Starting Chef Client, version 14.10.9`
`[2021-12-14T17:58:13+00:00] INFO: *** Chef 14.10.9 ***`
`[2021-12-14T17:58:13+00:00] INFO: Platform: x86_64-linux`
`[2021-12-14T17:58:13+00:00] INFO: Chef-client pid: 9585`
`[2021-12-14T17:58:15+00:00] WARN: Run List override has been provided.`
`[2021-12-14T17:58:15+00:00] WARN: Original Run List: []`
`[2021-12-14T17:58:15+00:00] WARN: Overridden Run List: [recipe[testcookbook::test]]`
`[2021-12-14T17:58:15+00:00] INFO: Run List is [recipe[testcookbook::test]]`
`[2021-12-14T17:58:15+00:00] INFO: Run List expands to [testcookbook::test]`
`[2021-12-14T17:58:15+00:00] INFO: Starting Chef Run for testcookbook08`
`[2021-12-14T17:58:15+00:00] INFO: Running start handlers`
`[2021-12-14T17:58:15+00:00] INFO: Start handlers complete.`
`[2021-12-14T17:58:15+00:00] INFO: Error while reporting run start to Data Collector. URL: 
https://10.10.21.33/organizations/test/data-collector Exception: 404 -- 404 "Not Found"  (This is normal if you do not have Chef Automate)`
`resolving cookbooks for run list: ["testcookbook::test"]`
`[2021-12-14T17:58:15+00:00] INFO: Loading cookbooks [testcookbook@0.0.1, bds@0.2.50, docker@4.9.2, sysctl@0.0.0, commonUtils@11.3.2, line@0.5.1, test_platform@0.1.0, cert_and_key@0.1.0]`
`[2021-12-14T17:58:15+00:00] INFO: Skipping removal of obsoleted cookbooks from the cache`

`Synchronizing Cookbooks:`
`  - testcookbook (0.0.1)`
`  - bds (0.2.50)`
`  - docker (4.9.2)`
`  - sysctl (0.0.0)`
`  - commonUtils (11.3.2)`
`  - line (0.5.1)`
`  - test_platform (0.1.0)`
`  - cert_and_key (0.1.0)`
`Installing Cookbook Gems:`
`[2021-12-14T17:58:37+00:00] INFO: Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root users on this machine.`
`Fetching gem metadata from https://www.rubygems.org/..........`
`Resolving dependencies...`
`Using bundler 1.16.1`
`Using excon 0.89.0`
`Using multi_json 1.15.0`
`Using docker-api 1.34.2`
`Bundle complete! 1 Gemfile dependency, 4 gems now installed.`
Use `bundle info [gemname]` to see where a bundled gem is installed.

`Compiling Cookbooks...`
`Converging 1 resources`
`Recipe: testcookbook::test`
`  * yum_package[docker] action install[2021-12-14T17:58:37+00:00] INFO: Processing yum_package[docker] action install (testcookbook::test line 15)`

`    NoMethodError`
`    ---------------------`
`    undefined method `trace' for nil:NilClass`

`    Resource Declaration:`
`    ---------------------`
`    # In /var/chef/cache/cookbooks/testcookbook/recipes/test.rb`

`     15: package 'docker' do`
`     16:   action [ :install, :upgrade ]`
`     17: end`
`     18:`

`    Compiled Resource:`
`    ------------------`
`    # Declared in /var/chef/cache/cookbooks/testcookbook/recipes/test.rb:15:in `from_file'`

`    yum_package("docker") do`
`      package_name "docker"`
`      action [:install, :upgrade]`
`      default_guard_interpreter :default`
`      declared_type :package`
`      cookbook_name "testcookbook"`
`      recipe_name "test"`
`    end`

`    System Info:`
`    ------------`
`    chef_version=14.10.9`
`    platform=redhat`
`    platform_version=7.9`
`    ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]`
`    program_name=/bin/chef-client`
`    executable=/opt/chef/bin/chef-client`

`[2021-12-14T17:58:39+00:00] INFO: Running queued delayed notifications before re-raising exception`

`Running handlers:`
`[2021-12-14T17:58:39+00:00] ERROR: Running exception handlers`
`Running handlers complete`
`[2021-12-14T17:58:39+00:00] ERROR: Exception handlers complete`
`Chef Client failed. 0 resources updated in 26 seconds`
`[2021-12-14T17:58:39+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out`
`[2021-12-14T17:58:39+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report`
`[2021-12-14T17:58:39+00:00] FATAL: NoMethodError: yum_package[docker] (testcookbook::test line 15) had an error: NoMethodError: undefined method `trace' for nil:NilClass`
```

```

## Stacktrace
`NoMethodError: yum_package[docker] (testcookbook::test line 15) had an error: NoMethodError: undefined method 'trace' for nil:NilClass`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/provider/package.rb:523:in block in target_version_array'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/provider/package.rb:595:in 'block in each_package'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/provider/package.rb:591:in 'each'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/provider/package.rb:591:in 'each_with_index'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/provider/package.rb:591:in 'each_package'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/provider/package.rb:483:in 'target_version_array'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/provider/package.rb:86:in 'block in <class:Package>'
(eval):2:in 'block in action_install'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/provider.rb:236:in 'instance_eval'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/provider.rb:236:in 'compile_and_converge_action'
(eval):2:in 'action_install'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/provider.rb:182:in 'run_action'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/resource.rb:578:in 'run_action'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/runner.rb:70:in 'run_action'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/runner.rb:98:in 'block (2 levels) in converge'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/runner.rb:98:in 'each'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/runner.rb:98:in 'block in converge'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/resource_collection/resource_list.rb:94:in 'block in execute_each_resource'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/resource_collection/stepable_iterator.rb:114:in 'call_iterator_block'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/resource_collection/stepable_iterator.rb:85:in 'step'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/resource_collection/stepable_iterator.rb:103:in 'iterate'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/resource_collection/stepable_iterator.rb:55:in 'each_with_index'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/resource_collection/resource_list.rb:92:in execute_each_resource'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/runner.rb:97:in 'converge'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/client.rb:720:in 'block in converge'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/client.rb:715:in 'catch'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/client.rb:715:in 'converge'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/client.rb:754:in 'converge_and_save'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/client.rb:286:in 'run'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application.rb:303:in 'run_with_graceful_exit_option'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application.rb:279:in 'block in run_chef_client'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/local_mode.rb:44:in 'with_server_connectivity'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application.rb:261:in 'run_chef_client'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application/client.rb:444:in 'run_application'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application.rb:66:in 'run'`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/bin/chef-client:25:in '<top (required)>'
/bin/chef-client:74:in 'load'`
`/bin/chef-client:74:in '<main>'`

`>>>> Caused by NoMethodError: undefined method 'trace' for nil:NilClass`
`/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/provider/package.rb:523:in 'block in target_version_array'`

**Comment by tas50** [comment]
It looks like you're using Chef 14 which has been EOL for several years now. First step should be to update to a supported version of Chef Infra Client to confirm this is still an issue. We've entirely rewritten how yum packages are handled in more recent version of Chef so there's a solid chance any issue with yum packages in Chef has been resolved.
