### ISSUE TITLE
homebrew_tap.rb is still trying to use the :full property which was removed in #12345

### ISSUE THREAD

**Issue by jweyer8** [chef/chef#12390]
## Description
homebrew_tap.rb is failing because it is still trying to use the :full property which was removed in #12345. 

## Fix 
Line 56 needs to be modified from this:

`shell_out!("#{new_resource.homebrew_path} tap #{new_resource.full ? "--full" : ""} #{new_resource.tap_name} #{new_resource.url || ""}",`

to this:
`shell_out!("#{new_resource.homebrew_path} tap #{new_resource.tap_name} #{new_resource.url || ""}",`

## Chef Version
17.6

## Platform Version
macOS

## Replication Case
Any use of the homebrew_tap resource will replicate this. 
```
homebrew_tap 'chef/chef' 
```

## Client Output
NoMethodError: undefined method `full' for Chef::Resource::HomebrewTap

**Comment by tas50** [comment]
This is fixed on main and will ship in 17.9. Super soon.

**Comment by jweyer8** [comment]
@tas50 This was not fixed in version 17.9.18. #12346 removed the full property because it was depreciated by homebrew; however, the resource still tries to use the full property which results in a no method error (see above)

**Comment by tas50** [comment]
@damacus Can you fix the use of full on https://github.com/chef/chef/blob/main/lib/chef/resource/homebrew_tap.rb#L56 and make sure we get some sort of kitchen test here that would catch this?

**Comment by jweyer8** [comment]
@tas50 I think the PR above should do the trick.
