### ISSUE TITLE
Incorrect version and architecture assignment for list of packages in dnf_package

### ISSUE THREAD

**Issue by skywalk7** [chef/chef#12442]
## Description
When using dnf package resource for list of packages and providing version and/or architecture, it is expected for all packages in the list to use the defined version. But in `safe_version_array` and `safe_arch_array` only first element would get defined version/arch. Remaining packages in the list would get latest version.

Code:
```
        def safe_version_array
          if new_resource.version.is_a?(Array)
            new_resource.version
          elsif new_resource.version.nil?
            package_name_array.map { nil }
          else
            [ new_resource.version ]
          end
        end
```

Proposed fix to return list filled with version defined in resource:
```
        def safe_version_array
          if new_resource.version.is_a?(Array)
            new_resource.version
          elsif new_resource.version.nil?
            package_name_array.map { nil }
          else
            package_name_array.map { new_resource.version }
          end
        end
```

## Chef Version
Chef Infra Client: 15.13.8

## Platform Version
CentOS Stream release 8

## Replication Case
Case can be replicated when installing not latest versions of packages available.

## Client Output

Declared resource:
```
dnf_package("git, perl-Git, git-core, git-email, git-core-doc, gitk, git-gui") do
  package_name ["git", "perl-Git", "git-core", "git-email", "git-core-doc", "gitk", "git-gui"]
  action [:install]
  default_guard_interpreter :default
  declared_type :package
  cookbook_name "fbit_devtools"
  recipe_name "rhel"
  version "2.30.2-2.fb"
end
```

What actually it tries to do (check different versions for git and all other packages):
```
Begin output of ["dnf", "-y", "install", "git-0:2.30.2-2.fb.x86_64", "perl-Git-0:2.31.1-2.el8.noarch", "git-core-0:2.31.1-2.el8.x86_64", "git-email-0:2.31.1-2.el8.noarch", "git-core-doc-0:2.31.1-2.el8.noarch", "gitk-0:2.31.1-2.el8.noarch", "git-gui-0:2.31.1-2.el8.noarch"]
```

**Comment by lamont-granquist** [comment]
No, its intended that you need to have an array of versions that matches the package array.  Your code will also coerce the version to an array even if the package provider isn't given an array (if you try your fix lots of specs in `spec/functional/resource/dnf_package_spec.rb` should fail).

The correct way to do what you want is just this:

```
  version [ "2.30.2-2.fb" ] * 7
```

Or possibly less brittle but i haven't checked:

```
  version  [ "2.30.2-2.fb" ] * package_name.length
```

And the general case people wouldn't want that if they're installing multiple packages that have nothing at all to do with each other:

```
dnf_package "lsof", "tcpdump", "strace", "zsh", "git"
```

**Comment by tas50** [comment]
@lamont-granquist any reason not to create a cookstyle rule on this one?

**Comment by skywalk7** [comment]
@lamont-granquist If recipe should accept array of versions it should fail if value is not array or length of array doesn't match length of array of packages. This inconsistent behavior led to the configuration issue which was hard to identify.

> version [ "2.30.2-2.fb" ] * 7
This is direct invitation for bug to happen when array of packages is extended.

Anyway, thanks a lot for looking into it!
