### ISSUE TITLE
Fix omnibus healthchecks

### ISSUE THREAD

**Issue by PrajaktaPurohit** [chef/chef#12453]
Our Omnibus healthchecks are designed to let us know when binaries or libraries in omnibus packages are trying to reach out to the system libraries. These are critical for developing self contained binaries. After our libarchive failures it came to our attention that these checks are failing on at least FreeBSD. Investigate these failures and make sure we have a working omnibus setup so we can produce working packages.

-[ ] aix - fixed
-[ ] solaris - fixed
-[ ] freebsd - more likely that this will fix https://app.zenhub.com/workspaces/infra-packages-team-614b70e63e840100102cd73d/issues/chef/infra-packages-team/29 rather then libarchive
-[ ] windows - not an issue
-[ ] mac - not an issue

See:
https://github.com/chef/omnibus/issues/1051

**Comment by tas50** [comment]
Potentially related to https://github.com/chef/customer-bugs/issues/561

**Comment by PrajaktaPurohit** [comment]
https://github.com/chef/omnibus/pull/1056
