### ISSUE TITLE
yum_package: No candidate version available for <package>

### ISSUE THREAD

**Issue by aknarts** [chef/chef#12557]
## Description
resource
```ruby
     20:     yum_package 'sssd' do
     21:       allow_downgrade false
     22:       action :upgrade
     23:       version '>= 1.16.5-10.el7_9.11'
     24:     end
````

Fails with: 
```
    * No candidate version available for sssd
    ================================================================================
    Error executing action `upgrade` on resource 'yum_package[sssd]'
    ================================================================================
    
    Chef::Exceptions::Package
    -------------------------
    No candidate version available for sssd
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/systems/recipes/ldap_client.rb
    
     20:     yum_package 'sssd' do
     21:       allow_downgrade false
     22:       action :upgrade
     23:       version '>= 1.16.5-10.el7_9.11'
     24:     end
     25:   elsif node.centos6?
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/systems/recipes/ldap_client.rb:20:in `from_file'
    
    yum_package("sssd") do
      package_name "sssd"
      action [:upgrade]
      default_guard_interpreter :default
      declared_type :yum_package
      cookbook_name "systems"
      recipe_name "ldap_client"
      version ">= 1.16.5-10.el7_9.11"
      flush_cache {:before=>false, :after=>false}
    end
    
    System Info:
    ------------
    chef_version=17.9.42
    platform=centos
    platform_version=7.9.2009
    ruby=ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
    program_name=/usr/bin/chef-client
    executable=/opt/chef/bin/chef-client
```
This works ok on the older versions up to 17.8.25 included, but breaks, I think something in the yum resource rewrite is to blame but was not able to pinpoint what from looking at the diff.

This is an output from `yum info sssd`
```
Installed Packages
Name        : sssd
Arch        : x86_64
Version     : 1.16.5
Release     : 10.el7_9.11
Size        : 34 k
Repo        : installed
From repo   : centos-updates
Summary     : System Security Services Daemon
URL         : https://pagure.io/SSSD/sssd/
License     : GPLv3+
Description : Provides a set of daemons to manage access to remote directories and
            : authentication mechanisms. It provides an NSS and PAM interface toward
            : the system and a pluggable backend system to connect to multiple different
            : account sources. It is also the basis to provide client auditing and policy
            : services for projects like FreeIPA.
            : 
            : The sssd subpackage is a meta-package that contains the deamon as well as all
            : the existing back ends.
```
While this might be something strange with the package itself, this does come from upstream centos repositories and there is no reason for this to break between the two chef client versions

## Chef Version
Broken in 17.9.18
Still Broken in 17.9.42
Last known working version 17.8.25

## Platform Version
    platform=centos
    platform_version=7.9.2009
    ruby=ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]

## Chef trace and stacktrace.out

https://gist.github.com/aknarts/8ecf3b0fe03d9bf1182b9980534ec731

**Comment by lamont-granquist** [comment]
does `version '>= 0:1.16.5-10.el7_9.11'` work?  Also does either of `yum_package 'sssd >= 1.16.5-10.el7_9.11' do` or `yum_package 'sssd >= 0:1.16.5-10.el7_9.11' do` work without using the version property?

**Comment by lamont-granquist** [comment]
The stacktrace.out will probably not be so useful on this one, but i could still use the `-l trace` output logs from relevant bit around execution of the yum_package resource.

**Comment by aknarts** [comment]
> does `version '>= 0:1.16.5-10.el7_9.11'` work? Also does either of `yum_package 'sssd >= 1.16.5-10.el7_9.11' do` or `yum_package 'sssd >= 0:1.16.5-10.el7_9.11' do` work without using the version property?

Yeah noticed the epoch being discovered as 0 in the trace log, will try that tomorrow.

Added the two logs as a gist.

**Comment by aknarts** [comment]
Still fails with an epoch...
```ruby
    yum_package("sssd") do
      package_name "sssd"
      action [:upgrade]
      default_guard_interpreter :default
      declared_type :yum_package
      cookbook_name "systems"
      recipe_name "ldap_client"
      version ">= 0:1.16.5-10.el7_9.11"
      flush_cache {:before=>false, :after=>false}
    end
```

**Comment by lamont-granquist** [comment]
`[2022-02-07T20:19:44+00:00] TRACE: sending '{"action":"whatinstalled","provides":"sssd->= 1.16.0-19.el7_5.8"}' to python helper`

The problem is in the "sssd->= 1.16.0" bit where there's some mangling of the version string which isn't handling the `>=` constraint at all.

It is the code that handles mangling version strings and adding "0:" epochs if they're missing, but it must not handle constraints correctly at all.

**Comment by lamont-granquist** [comment]
There's also another bug around the version mangling behavior that manifests when using an empty string as a version (which I had literally no idea was valid syntax and probably shouldn't be but it broke some people on upgrade)
