### ISSUE TITLE
Locale resource executes locale-gen on every run

### ISSUE THREAD

**Issue by hrak** [chef/chef#12832]
## Description
The `locale` resource unnecessarily executes `locale-gen` on every chef run, which can be very costly on some systems.

This is caused by `define_resource_requirements` checking whether `locale-gen` is available by doing the following:

```ruby
requirements.assert(:all_actions) do |a|
  # RHEL/CentOS type platforms don't have locale-gen
  a.assertion { shell_out("locale-gen") }
  a.failure_message(Chef::Exceptions::ProviderNotFound, "The locale resource requires the locale-gen tool")
end
```

This is causing locale-gen to be executed, regenerating all installed locales on every Chef run.

## Chef Version
17.x

## Platform Version
Ubuntu 20.04 LTS

## Replication Case

Execute `locale` resource like so:

```
  locale 'set locale' do
    lang 'en_US.UTF-8'
  end
```

## Client Output

```
[2022-04-29T08:38:57+00:00] DEBUG: Converging node log-ingest1.example.com
Recipe: lsw-base::locale
  * locale[set locale] action update[2022-04-29T08:38:57+00:00] INFO: Processing locale[set locale] action update (lsw-base::locale line 13)
Generating locales (this might take a while)...
  en_AG.UTF-8... done
  en_AU.UTF-8... done
  en_BW.UTF-8... done
  en_CA.UTF-8... done
  en_DK.UTF-8... done
  en_GB.UTF-8... done
  en_HK.UTF-8... done
  en_IE.UTF-8... done
  en_IL.UTF-8... done
  en_IN.UTF-8... done
  en_NG.UTF-8... done
  en_NZ.UTF-8... done
  en_PH.UTF-8... done
  en_SG.UTF-8... done
  en_US.UTF-8... done
  en_ZA.UTF-8... done
  en_ZM.UTF-8... done
  en_ZW.UTF-8... done
Generation complete.
[2022-04-29T08:39:38+00:00] DEBUG: Skipping update of locale[set locale]: has not changed any of the specified properties lang="en_US.UTF-8", lc_env={}.
 (up to date)
```

**Comment by hrak** [comment]
Since all related PR's are merged ( #12833  #12904 #12905 ) and this issue is rather annoying or even causes problems (f.e. with PostgreSQL that suddenly gets its locale files pulled from underneath it on every Chef run), could you please roll a new stable release of infra client 16, 17 and 18 to fix this issue?

**Comment by RolphH** [comment]
@PrajaktaPurohit can you help out?

**Comment by PrajaktaPurohit** [comment]
Chef-16 release https://www.chef.io/downloads/tools/infra-client?v=16.18.30 should have the fix.
We are currently in the process of getting the Chef-17 release out that will include the fix.
Chef-18 release https://www.chef.io/downloads/tools/infra-client?v=18.0.185 and later should include the fix

**Comment by johnmccrae** [comment]
Solved, as noted above by Prajakta. PR is here for Chef-17 - https://github.com/chef/chef/pull/12905
