### ISSUE TITLE
snap_package resource fails due to missing argument

### ISSUE THREAD

**Issue by gene1wood** [chef/chef#13024]
## Description

When attempting to use the `snap_package` resource to install a snap package, Chef client errors out with the error

```
ArgumentError: wrong number of arguments (given 1, expected 2)
```

due to the fact that when the [`install_package` method in the `snap.rb` provider](https://github.com/chef/chef/blob/f2a10272c29c80c06143d094c87f182827de12c5/lib/chef/provider/package/snap.rb#L65) calls the `install_snap` method, it [calls it passing in only the snap name](https://github.com/chef/chef/blob/f2a10272c29c80c06143d094c87f182827de12c5/lib/chef/provider/package/snap.rb#L69), when the `install_snap` method [actually requires two arguments, the snap name and the version](https://github.com/chef/chef/blob/f2a10272c29c80c06143d094c87f182827de12c5/lib/chef/provider/package/snap.rb#L266).

## Chef Version

17.10.3

## Platform Version

Ubuntu 18.04

## Replication Case

Create a `default.rb` recipe that installs a snap package which isn't already installed like this

```
snap_package "plex-htpc"
```

Ensure that you don't set a `source` attribute as this bypasses the bug.

## Client Output

```
ArgumentError: wrong number of arguments (given 1, expected 2)
```

## Stacktrace

https://gist.github.com/gene1wood/b3263f9fc87844f4d91f814a4455bbb1

**Comment by johnmccrae** [comment]
@gene1wood has a PR to fix this in place. We just reviewed it and have asked him for an Integration test. I am following up separately to give him pointers on setting a test up.
