### ISSUE TITLE
macOS: group resource fails to fully edit group membership

### ISSUE THREAD

**Issue by chilcote** [chef/chef#13021]
## Description
Using the group resource to manage group membership fails to fully edit the group attributes, leaving the membership in a half-enabled state.

## Chef Version
17.8.25

## Platform Version
macOS 12.x

## Replication Case

Create a group resource to remove a user from the admin group, like this:
```
  group 'admin' do
    action :modify
    members username.to_s
    append true
  end
```

Expected results:
The user will be removed from the admin group

Actual results:
The user is removed from the `GroupMembership` attribute, but the user's `GeneratedUID` still exists in the `GroupMembership` attribute, resulting in an incomplete edit of the group record. 

After running this resource, `dseditgroup` still reported my user as being in the admin group 
```
% dseditgroup -o checkmember -m username admin
yes username is a member of admin
```

Using `dseditgroup` to edit the admin group also changes the `GroupMembers` attribute in the group record, which completes the act of removing the user from admin.

**Comment by tpowell-progress** [comment]
addressed in v16.0.257 release / PR #9275 / tag v16.0.41
