### ISSUE TITLE
chef_client_scheduled_task splay property doesn't accept 0

### ISSUE THREAD

**Issue by Stromweld** [chef/chef#13094]
## Description
chef_client_scheduled_task splay property doesn't accept 0 even though the description says it'll take any integer from 0-x

## Chef Version
17.10.3

## Platform Version
any windows version

## Replication Case
use the chef_client_scheduled_task resource to configure windows to run chef-client and try to make property  splay = 0

## Client Output
Error requiring integer larger than 0

**Comment by PrajaktaPurohit** [comment]
Could you give more context about why the splay would beed to be 0? It sounds like the documentation does say that splay is a number between 0 and x. https://docs.chef.io/config_rb_client/.

**Comment by Stromweld** [comment]
Documentation does say 0 and x but the way the code is written it doesn't allow 0. You have to use greater than or equal to allow 0. Right now code only allows 1 and x. A user may not want a splay and may want all clients to run exactly on their normal interval which would mean a splay of 0. They may be running servers at different intervals, relying on different boot up times for the randomness or have other coded means to control chef-client runs.

**Comment by Stromweld** [comment]
In the case of Optum they are configuring the splay in the client.rb file and this resource would add an extra splay as it wouldn't start the chef-client until it's splay is being hit which then makes them additive since client.rb would then add another splay waiting period. They want to be able to set the cron or systemd timer splay to 0 and rely on the client.rb splay they have set.
