### ISSUE TITLE
snap_package actions documentation lists unsupported actions

### ISSUE THREAD

**Issue by gene1wood** [chef/chef#13123]
## Description
The [`snap_package` documentation's actions list](https://docs.chef.io/resources/snap_package/#actions), which is generated from [`resource/snap_package.rb`](https://github.com/chef/chef/blob/main/lib/chef/resource/snap_package.rb), incorrectly lists actions inherited from [`resource/package.rb`](https://github.com/chef/chef/blob/805df23576c2ff7c6468933ebc7c90d286672d16/lib/chef/resource/package.rb#L36) which are not implemented in `snap_package`.

## Chef Version
v18.0.140

## Replication Case
If you look at the  [`snap_package` documentation's actions list](https://docs.chef.io/resources/snap_package/#actions) you'll see that it lists

* `:lock`
* `:unlock`
* `:reconfig`

for actions, all of which aren't implemented in `snap_package.rb`. These are inherited from `package.rb`. 

The thing I don't understand is that if you look at another package resource, like [`resource/rpm_package.rb`](https://github.com/chef/chef/blob/main/lib/chef/resource/rpm_package.rb) which appears to be written about the same as `resource/snap_package.rb`, and which also inherits from `resource/package.rb` which is where these actions (`:lock`, `:unlock` and `:reconfig`) are defined, the [`rpm_package` documentation's action list](https://docs.chef.io/resources/rpm_package/#actions) is correct and does not list unsupported actions.

What is it about `resource/snap_package.rb` that's causing the documentation to be incorrect? How does `snap_package.rb` differ from `rpm_package.rb` which works?

Or is it worse than that, and though `snap_package` doesn't implement these 3 actions, Chef is allowing them to be set as an action when the resource is used?

**Comment by IanMadd** [comment]
I think what's going on is we've got a [rake task](https://github.com/chef/chef/blob/main/tasks/docs.rb) that generates the yaml files that these pages are based on, but it's not 100% accurate and requires some manual editing after the files are generated. These actions probably slipped through the last time these files were generated.

**Comment by gene1wood** [comment]
> requires some manual editing after the files are generated

Ugh, that sucks.

# Rake task interrogates code?

> we've got a [rake task](https://github.com/chef/chef/blob/main/tasks/docs.rb) that generates the yaml files that these pages are based on

I wonder if there would be some way for the rake task to interrogate the code to see that use of the, for example `:lock` action [raises an exception](https://github.com/chef/chef/blob/af2813a5fe1ce014967ad7833075ac5bf831b8d4/lib/chef/provider/package.rb#L297-L303) if attempted with a `snap_package` or `rpm_package`, and doesn't raise an exception in [these 4 package types](https://github.com/chef/chef/search?q=lock_package++path%3A%2Flib%2Fchef%2Fprovider%2Fpackage) because they implement the `lock_package` method, overriding the one in `package.rb` which raises an exception

# Solve it with CI?

Or maybe that determination could only be made by CI which would attempt to use all of the actions defined for a given resource, finding that some cause exceptions and some don't, and use that output to programmatically create some kind of metadata file that the rake task can use to filter out invalid actions.

# The package resources are setup wrong?

Or is this actually as simple as there being a problem with all the package resources because their resource files don't override the `allowed_actions` variable?

In the parent [`resource/package.rb` it defines `allowed actions`](https://github.com/chef/chef/blob/af2813a5fe1ce014967ad7833075ac5bf831b8d4/lib/chef/resource/package.rb#L36), however in the child [`resource/rpm_package.rb` it does not](https://github.com/chef/chef/blob/af2813a5fe1ce014967ad7833075ac5bf831b8d4/lib/chef/resource/rpm_package.rb#L19-L42). This is despite the fact that the child inherits from the parent.

Would this all be fixed if in `resource/rpm_package.rb` there was a line like
```
      allowed_actions :install, :upgrade, :remove
```

The upside to this solution is that it would be Chef alerting the user that they've attempted to invoke an action that isn't allowed, instead of an [exception being thrown by the resource](https://github.com/chef/chef/blob/af2813a5fe1ce014967ad7833075ac5bf831b8d4/lib/chef/provider/package.rb#L273-L303).

**Comment by gene1wood** [comment]
I opened #13166 with [the fix I mentioned above](https://github.com/chef/chef/issues/13123#issuecomment-1234612938).
