### ISSUE TITLE
Set :non_interactive option for Net::SSH to false when RequestTTY is configured in user ssh config file

### ISSUE THREAD

**Issue by lytao** [chef/chef#13271]
## Description

In latest versions of EL8 (CentOS, RedHat, Rocky, etc), OpenSSH sever doesn't privide TTY for connections unless it is requested by SSH client explicitly:

```
$ ssh 10.0.0.2 "sh -c '(sudo echo) < /dev/null'"
Private IP: 10.0.0.2

sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
```
It causes issue for `knife bootstrap` using `sudo` to failed. Providing password in command line also doesn't help.

For OpenSSH client, we can solve it by add `RequestTTY yes` in `~/.ssh/config`. However, it doesn't work for knife. _RequestTTY_ is not an option which can be parsed by [Net::SSH::Config](https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh/config.rb#L9). 

We could ask Net::SSH to translate the value of `RequestTTY` to `non_interactive`. However, they are not meant to the same option. Could you add pieces of code for knife to set the SSH connection option `:non_interactive` to `false` when _RequestTTY_ is set `yes`?

## Chef Version

knife: 17.10.0 (from Chef-Workstation)

## Platform Version

CentOS/Rocky Linux release 8.6

## Replication Case

Follow the steps to reproduce:
- Create a latest CentOS/Rocky 8 server. Create a normal user on it and grant sudo access. Password is required for sudo. Here is the sample sudoer config:
  ```
  myuser ALL=(ALL) ALL
  ```
- Try to bootstrap it with knife:
  ```bash
  knife bootstrap "10.0.0.2" --node-name "my_chef_node" --connection-user "myuser" --sudo --use-sudo-password
  ```
## Client Output

```
$ knife bootstrap "10.0.0.2" --node-name "my_chef_node" --connection-user "myuser" --sudo --use-sudo-password
Connecting to 10.0.0.2 using ssh
ERROR: Sudo password is required for this operation. Please enter password using -P or --ssh-password option
Creating new client for my_chef_node
Creating new node for my_chef_node
ERROR: Train::UserError: Sudo failed: Sudo cannot prompt for password because there is no terminal. Please provide the sudo password directly
$
$ knife bootstrap "10.0.0.2" --node-name "my_chef_node" --connection-user "myuser" --sudo --use-sudo-password -P "mypassword"
Connecting to 10.0.0.2 using ssh
WARN: [SSH] connection failed, terminating (#<Net::SSH::AuthenticationFailed: Authentication failed for user myuser@10.0.0.2>)
ERROR: Train::Transports::SSHFailed: SSH session could not be established
```

**Comment by shail248** [comment]
@vkarve-chef Could you please provide an update on this one from customer https://github.com/chef/customer-bugs/issues/753
