### ISSUE TITLE
Add AssociatedBundleIdentifiers key to launchd resource

### ISSUE THREAD

**Issue by chilcote** [chef/chef#13287]
### Describe the Enhancement:
New to Ventura is the ability to associate a bundle id with the system settings Login Items display
https://developer.apple.com/documentation/servicemanagement/updating_helper_executables_from_earlier_versions_of_macos

### Describe the Need:
Will be helpful for making the system settings pane more digestible 

### Current Alternative
n/a

### Can We Help You Implement This?:
incoming PR

**Comment by tpowell-progress** [comment]
Addressed in 18.1.0 release / #13288 / tag v18.0.190
