### ISSUE TITLE
chef_client_config resource raises error unless log_location is string

### ISSUE THREAD

**Issue by williamtheaker** [chef/chef#13345]
## Description
I think I'm seeing a regression in the `chef_client_config` resource when running 18.x. If you don't set the `log_location` property, you get `TypeError: no implicit conversion of nil into String`.  You can set the property to `:syslog` if you want to change the error to `TypeError: no implicit conversion of Symbol into String`. It works if I set the `log_location` to a string though.

## Chef Version
18.0.169 (replicated with both cinc and chef client)
This issue doesn't occur in 17.x.

## Platform Version
macOS 13.0

## Replication Case

Create a recipe with a `chef_client_config` resource and omit the `log_location` property, such as in the [bare minimum example](https://docs.chef.io/resources/chef_client_config/#examples) :

```
chef_client_config 'Create client.rb' do
  chef_server_url 'https://chef.example.dmz'
end
```

## Client Output

```
[2022-11-08T12:44:09-05:00] DEBUG: TypeError: chef_client_config[Cinc Client configuration file] (internal_helpers::cinc_client line 45) had an error: TypeError: no implicit conversion of Symbol into String
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/resource/chef_client_config.rb:258:in `dirname'
/opt/cinc/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.169/lib/chef/resource/chef_client_config.rb:258:in `block in <class:ChefClientConfig>'
```

**Comment by Stromweld** [comment]
This PR ^^^ should fix the issue now. File.dirname class expects a string so when it got anything else it was throwing the type conversion error. Unless it's a directory string we don't want the value in the array for directories to be created so the if clause will remove it properly now if it's not a string but will updated client.rb with correct value.
