### ISSUE TITLE
References to non existing gem version for chef-powershell

### ISSUE THREAD

**Issue by mattkoziy** [chef/chef#13357]
Building chef opensource on windows is failing due to wrong versions of the chef-powershell gem. if you go to https://github.com/chef/chef/search?q=chef-powershell and see refs for ~> 1.0.12 you will notice that version of that gem doesnt exist https://rubygems.org/gems/chef-powershell/versions/1.0.0. That version needs to be changed to 1.0.13 in the files that mention 1.0.12 in that search url

**Comment by tpowell-progress** [comment]
This is resolved in Chef versions 18.2.46 and later.
