### ISSUE TITLE
Chef Infra Client 18 displays passwords with sensitive true set

### ISSUE THREAD

**Issue by johngidt** [chef/chef#13419]
## Description
Chef Infra Client 18 displays passwords with sensitive true set. 

## Chef Version

Chef Infra Client, version 18.0.185

## Platform Version

centos 7

## Replication Case

Recipe code.
```
user 'root' do
  action :manage
  password '$6$examplepassword'
  sensitive true
end
```

## Client Output

```
         * linux_user[root] action manage
           - manage user root
           - change password from $6$oldpassword to $6$examplepassword
```

**Comment by RiotMac** [comment]
Seeing the same thing with 17.10.3 
https://github.com/chef/chef/issues/13442

**Comment by PrajaktaPurohit** [comment]
https://chefio.atlassian.net/browse/CHEF-1948 - This issues is planned to be looked into in this PI (Between May - July'23)

**Comment by johnmccrae** [comment]
This appears to be fixed in this PR but needs to be verified - https://github.com/chef/chef/pull/13014

**Comment by johnmccrae** [comment]
@decoyjoe Thanks! Got any logs for me to pour over?

**Comment by decoyjoe** [comment]
@johnmccrae Sure, reproduced via the resource in the description. Attached both `info` and `debug` logs.

- [default-rocky-8.info.log](https://github.com/chef/chef/files/11888336/default-rocky-8.info.log)
- [default-rocky-8.debug.log](https://github.com/chef/chef/files/11888337/default-rocky-8.debug.log)

**Comment by johnmccrae** [comment]
Sorry, I missed updating this: Solved: https://github.com/chef/chef/pull/13897
