### ISSUE TITLE
Buildkite pipelines default to `blocked` for unauthenticated users in (at least) ffi-* repos

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#13863]
This is related to https://github.com/chef/chef/issues/13765 - another buildkite-related community blocker.

In a variety of repos (and some testing seems to imply it's all ffi-* repos, maybe others), `expeditor` creates the `buildkite` pipelines in a `Blocked` state for all "unauthenticated" users. This means that any external contributor's PRs do not get tests run.

@tpowell-progress has reported it happens to him as well, which implies it may well be happening to authenticated users as well.

Some examples:
* *ffi-libarchive*:
  * https://github.com/chef/ffi-libarchive/pull/75 created it's buildkite tests in Blocked state as you can see here: https://buildkite.com/chef-oss/chef-ffi-libarchive-main-verify/builds/194#0189aa6c-e4aa-4e70-a0cb-2bab75d69a95
  * I just created https://github.com/chef/ffi-libarchive/pull/76 which also ended up (and is still in) Blocked state: https://buildkite.com/chef-oss/chef-ffi-libarchive-main-verify/builds/196
* *ffi-win32-extensions*:
  * I created https://github.com/chef/ffi-win32-extensions/pull/11 which ended up  (and is still in) blocked state:  https://buildkite.com/chef-oss/chef-ffi-win32-extensions-main-verify/builds/17
* *ffi-yajl*:
  * Thomas' PR ended up in blocked state (https://buildkite.com/chef-oss/chef-ffi-yajl-main-verify/builds/167)

**Comment by tpowell-progress** [comment]
There's a bit of expeditor code that prevents build configuration changes without an authenticated user that is failing on repositories that do not have a `.buildkite/` folder. @sean-simmons-progress is currently working on a pull request to fix this error.

**Comment by sean-simmons-progress** [comment]
A PR was merged today that should address this issue.

**Comment by sean-simmons-progress** [comment]
After the changes were made on expeditor I opened a PR here:

https://github.com/chef/ffi-yajl/pull/122

the build was not blocked: 

https://buildkite.com/chef-oss/chef-ffi-yajl-main-verify/builds/172#0189fa29-b1b0-4201-93bc-0198b0e2b045

would like someone to test on their external account, just to make sure.

**Comment by tpowell-progress** [comment]
@sean-simmons-progress did you merge the follow-up PR for the `$?` code?

**Comment by sean-simmons-progress** [comment]
Yes, merged and pushed!

**Comment by tpowell-progress** [comment]
Closing per @sean-simmons-progress's feedback
