### ISSUE TITLE
Create a user (or provide a access token to existing user) for Danger CI

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#13977]
It'd be great to use [Danger CI](https://danger.systems/) to enforce a bunch of stuff we do manually in code review. It's free and flexible. For example we could enforce our new Gems rules with:

```ruby
if git.modified_files.include?('Gemfile.lock') && !github.pr_body.include('--conservative')
  failure "Gem/Bundle changes were not documented in the Description."
end
```

However, it needs a user and an API token. I can easily make one, but I'm guessing we already have one we'd like to use.

Here's the details: https://danger.systems/guides/getting_started#setting-up-an-access-token

I'm happy to create a ChefDanger user or some such and share the password with the rest of @chef/chef-infra-owners  if that's what people want. LMK.

**Comment by Stromweld** [comment]
For implementation internally this would work, for github actions it wont work on forks as any secrets aren't carried over to the fork and thus wont run in external users pipelines when creating a PR back to chef.

**Comment by jaymzh** [comment]
Not needed, implemented here without it: https://github.com/chef/chef/pull/13976
