### ISSUE TITLE
Chef Infra Client 18 is being marked as End Of Life as of May 1, 2024

### ISSUE THREAD

**Issue by jjperry** [chef/chef#14370]
## Description

Chef Infra Client 18.x including 18.4.12 (the latest release available on the Chef Infra Client page) is reporting: `This release of Chef Infra Client became end of life (EOL) on May 1st, 2024.  Please update to a supported release to receive new features, bug fixes, and security updates`

## Chef Version

18.4.12

## Platform Version

Linux
Windows

## Replication Case

1. Install any version of Chef Infra Client. 
2. Run `chef-client`

## Client Output

```
[2024-05-08T19:02:28+00:00] WARN: This release of Chef Infra Client became end of life (EOL) on May 1st #{eol_year}. Please update to a supported release to receive new features, bug fixes, and security updates.
```

## Stacktrace

None

**Comment by jjperry** [comment]
The code in question is [client.rb](https://github.com/chef/chef/blob/cfbb21d73cd0e8ad17c9f5d6d279a27dc92c1368/lib/chef/client.rb#L339-L349). 

I don't know the EOL plans for the Chef client releases, so I can't even suggest a change to this block as it would change the EOL message for multiple versions now and in the future.

**Comment by fern4lvarez** [comment]
Duplicate of https://github.com/chef/chef/issues/14365, please close.

**Comment by jjperry** [comment]
Closed. Duplicate of https://github.com/chef/chef/issues/14365

**Comment by Asif-123** [comment]
$chef-client -zr "recipe[my-cookbook::recipe1]" not working in the latest chef infra version 18.4.12
which command uses to execute chef-client please help us
