### ISSUE TITLE
Give bootstrap the ability to configure arbitrary config values at the target node

### ISSUE THREAD

**Issue by sersut** [chef/chef#1448]
We've seen a few instances of some config values needs configuration during bootstrap. Some examples are #1090, #1416. 

We should have a mechanism in knife that enables users to configure any config value at the nodes.

**Comment by lamont-granquist** [comment]
Pretty certain https://github.com/chef/chef-rfc/blob/master/rfc071-knife-bootstrap-client-config.md and the PRs that implemented that closed this issue quite awhile ago
