### ISSUE TITLE
Allow specification of default log_location in knife.rb

### ISSUE THREAD

**Issue by bknowles** [chef/chef#1452]
Also prompt for default log_location when doing an interactive "knife configure".

**Comment by btm** [comment]
This is fixed in https://github.com/chef/chef/issues/5502 and https://github.com/chef/knife-windows/pull/407.

The Chef changes are in 12.17.25+, with a stable release targeted for release on Monday. The knife-windows changes will be an upcoming release.

**Comment by btm** [comment]
https://github.com/chef/knife-windows/pull/407 was released in knife-windows 1.8.0 today.
