### ISSUE TITLE
chef-client should run local-mode if a config file and chef_server_url is not specified

### ISSUE THREAD

**Issue by sersut** [chef/chef#1460]
One of the steps in the new LearnChef tutorials is to create a simple recipe that contains:

```
# hello.rb
file '/tmp/hello' do
   content "Hello world!"
end
```

and run this recipe by `chef-client hello.rb`. 

In order to achieve this we need `chef-client` to automatically assume `local-mode` when invoked with a recipe name as an argument.

/cc: @opscode/client-eng

**Comment by andreacampi** [comment]
@sersut anything left here after you landed your pull request?

**Comment by jkeiser** [comment]
PR #1969 solves this; it still needs to be updated for the latest Chef, and I haven't quite had time to finish the work.

**Comment by lamont-granquist** [comment]
The need for this seems to be very low, and we've generally gone the chefdk-generator route, and the workstation project would own generating this as a feature.
