### ISSUE TITLE
`node` not available in template partials

### ISSUE THREAD

**Issue by sersut** [chef/chef#1506]
https://tickets.opscode.com/browse/CHEF-4530

`node` variable is not available in template partials after 11.6.0. 

This error message occurs because the `@node` instance variable is nil. Adding `:node => @node` to the variables you pass in should work around it.

**Comment by lamont-granquist** [comment]
Dan made a comment in #2513 that this was done deliberately, but it does seem like his use case still should work if we made the node object accessible to partials by default.  So it seems like this still is a bug.

**Comment by lamont-granquist** [comment]
fixed via #3510 i think (at least it works for me on 12.18.x)
