### ISSUE TITLE
c:\chef directory is too permissive

### ISSUE THREAD

**Issue by sersut** [chef/chef#1516]
https://tickets.opscode.com/browse/CHEF-5285

The directory which is holding the *.pem files are too permissive on windows. We need to make sure that the directory is created with the correct permissions during the MSI installation.

/cc: @adamedx, @btm

**Comment by adamedx** [comment]
This has been resolved with https://github.com/chef/chef/commit/4cbb4d02371ac8489f0966735a3caf6dca92577b.
