### ISSUE TITLE
Don't crash when chef-zero port is already bound

### ISSUE THREAD

**Issue by jkeiser** [chef/chef#1521]
Running multiple chef-client or knife -zs simultaneously causes one or more of them to crash.  Since the latest revision of chef-zero supports a port range, we should:

* spin up chef-zero on a range by default (8900-9900)
* allow user to specify port ranges on the command line (--chef-zero-port=80,8080,9090-10101) and in `Chef::Config.chef_zero.port` ('80,8080-8090' or 8080.upto(8090))

**Comment by lamont-granquist** [comment]
@jkeiser didn't you fix this?

**Comment by jkeiser** [comment]
Pretty sure...
