### ISSUE TITLE
chef-client daemon holds onto file descriptor for rotated log

### ISSUE THREAD

**Issue by bhouse** [chef/chef#1523]
We're having issues with rotating the chef-client log `/var/log/chef/client.log`, as the chef-client daemon doesn't release the file descriptor when sent `SIGHUP`. This is on ubuntu, haven't tested against other distros.

See an example here: https://gist.github.com/bhouse/4737034b51e654838d4d

As a work-around we're using `copytruncate` with logrotate until this is resolved.

Thanks!

**Comment by lamont-granquist** [comment]
The other PR seems like it was closed due to failure to replicate.

If we can get a replication case, please reopen the ticket.
