### ISSUE TITLE
chefignore not found in `upload --all` when multiple cookbook paths

### ISSUE THREAD

**Issue by reesew** [chef/chef#1537]
Multiple cookbook paths appears to have chefignore searched for in the concatenation of the paths. I see a bunch of lines in the debug info when running `knife cookbook upload --all`

```
DEBUG: No chefignore file found at /home/reesew/.chef/chef-repo/cookbooks/home/reesew/.chef/chef-repo/app-cookbooks/chefignore no files will be ignored
```

my knife.rb contains the line 
`cookbook_path  [ File.join(repo, 'cookbooks'), File.join(repo, 'app-cookbooks') ]`

and there are chefignore files in the cookbook root directories

```
chef-repo/
    cookbooks/
        chefignore
        ...
    app-cookbooks/
        chefignore
        ...
```

**Comment by lamont-granquist** [comment]
We want to deprecate the multiple cookbook paths feature.  This bug is unlikely to get fixed.
