### ISSUE TITLE
Dependency Errors with RPM 5.4.9 & chef-10.32.2-1.el6.x86_64.rpm

### ISSUE THREAD

**Issue by OBrienCommaJosh** [chef/chef#1557]
In systems that use RPM 5.4.9 (rpm5.org), the standard omnibus chef-client RPM package doesn't install cleanly. In this version of RPM they do stricter dependency checks, in particular making sure all directories are owned by a package.

When one tries to install the package, it throws dependency errors, apparently due to lack of %dir directives in the RPM spec file for all of chef's directories. It will install if passed '--no-deps' to rpm, but some have expressed the need to have it install properly.

**Comment by lamont-granquist** [comment]
We don't use fpm any more in omnibus builds as of omnibus 4.0.  If this is still a problem, please reopen or submit an issue against http://github.com/chef/omnibus.
