### ISSUE TITLE
Service provider needs to be able to handle services on Ubuntu 13.10+

### ISSUE THREAD

**Issue by sersut** [chef/chef#1587]
Chef currently uses `Chef::Provider::Service::Debian` service provider on `:ubuntu` platform. This provider can not handle most of the services in 13.10+. 

Currently `Chef::Provider::Service::Upstart` provider needs to be manually specified on the service resources in order to get the services to be controlled in these ubuntu versions. We've tried to enable this provider by default on the newer versions of ubuntu with https://github.com/opscode/chef/pull/1412 but this caused some regressions because not all of the existing services have files under `/etc/init` which is a requirement of `Chef::Provider::Service::Upstart`. 

We've reverted this attempt with https://github.com/opscode/chef/pull/1582. This issue is to keep track of this bug and fix it in later releases of chef.

**Comment by lamont-granquist** [comment]
closed by ProviderResolver
