### ISSUE TITLE
chef-server 11.1.3-1 upgrade fails

### ISSUE THREAD

**Issue by mjkravetz** [chef/chef#1595]
On CentOS 6.4 currently running chef-server-11.1.0-1.el6, I attempted to upgrade to chef-server-11.1.3-1.el6. as follows:
# chef-server ctl stop
# yum upgrade chef-server-11.1.3-1.el6.x86_64.rpm
# chef-server-ctl upgrade
# The upgrade fails with:
# Error executing action `create` on resource 'chef-server_pg_user[opscode_chef]'
## PG::ConnectionBad

could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
## Cookbook Trace:

/opt/chef-server/embedded/cookbooks/chef-server/libraries/ec_postgres.rb:22:in `initialize'
/opt/chef-server/embedded/cookbooks/chef-server/libraries/ec_postgres.rb:22:in`new'
/opt/chef-server/embedded/cookbooks/chef-server/libraries/ec_postgres.rb:22:in `block in with_connection'
/opt/chef-server/embedded/cookbooks/chef-server/libraries/ec_postgres.rb:40:in`as_user'
/opt/chef-server/embedded/cookbooks/chef-server/libraries/ec_postgres.rb:21:in `with_connection'
/opt/chef-server/embedded/cookbooks/chef-server/providers/pg_user.rb:28:in`block in class_from_file'
## Resource Declaration:
# In /opt/chef-server/embedded/cookbooks/chef-server/recipes/postgresql.rb

170: chef_server_pg_user node['chef_server']['postgresql']['sql_user'] do
171:   password node['chef_server']['postgresql']['sql_password']
172:   superuser false
173: end
174:
## Compiled Resource:
# Declared in /opt/chef-server/embedded/cookbooks/chef-server/recipes/postgresql.rb:170:in `from_file'

chef_server_pg_user("opscode_chef") do
  action :create
  retries 0
  retry_delay 2
  guard_interpreter :default
  cookbook_name :"chef-server"
  recipe_name "postgresql"
  password "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
end

It appears that posgreSQL needs to be running for the new recipe.  Note that if the service was not explicitly stopped with "chef-server-ctl stop", it is stopped by the pre_11.1_upgrade_setup recipe which is run previously as part of the upgrade process:

Recipe: chef-server::pre_11.1_upgrade_setup
- execute[pkill -9 -f epmd] action run
  - execute pkill -9 -f epmd
- execute[/opt/chef-server/bin/chef-server-ctl start postgresql] action run
  - execute /opt/chef-server/bin/chef-server-ctl start postgresql
- ruby_block[check-for-sqitch] action run (skipped due to only_if)
- execute[apply-widen-cookbook-version] action nothing (skipped due to action :nothing)
- execute[sqitchfy_database] action nothing (skipped due to action :nothing)
- execute[migrate_database] action nothing (skipped due to action :nothing)
- execute[/opt/chef-server/bin/chef-server-ctl stop postgresql] action run
  - execute /opt/chef-server/bin/chef-server-ctl stop postgresql
- ruby_block[sleep 5] action run
  - execute the ruby block sleep 5

**Comment by atul86244** [comment]
Hi,

I am getting this error while installing Chef server 12, has anyone faced this? This is on RHEL6.2.

Mixlib::ShellOut::ShellCommandFailed: execute[chef-server-schema] (private-chef::erchef_database line 14) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0, 1], but received '2'
---- Begin output of sqitch --db-name opscode_chef deploy --verify ----
STDOUT: Adding metadata tables to opscode_chef
STDERR: User name may not contain "<" or start with "["
---- End output of sqitch --db-name opscode_chef deploy --verify ----
Ran sqitch --db-name opscode_chef deploy --verify returned 2

**Comment by lamont-granquist** [comment]
server bugs need to go to http://github.com/chef/chef-server
