### ISSUE TITLE
Chef can't remove apt packages if they don't exist in a repo

### ISSUE THREAD

**Issue by tas50** [chef/chef#1600]
Chef will fail to remove a package if it can't be found in apt-cache.  Unfortunately this is a completely valid use case for the remove action.  We had a repo for an inventory management package.  We stopped using it so we had chef remove the repo, then remove the package.  When doing that we received the following error (sanitized a bit)

```
  * package[crappy-inventory-agent] action remove
================================================================================
Error executing action `remove` on resource 'package[crappy-inventory-agent]'
================================================================================


Chef::Exceptions::Package
-------------------------
crappy-inventory-agent has no candidate in the apt-cache


Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/common/recipes/debian.rb

 16:   package 'crappy-inventory-agent' do
 17:     action :remove
 18:   end
 19:



Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/common/recipes/debian.rb:16:in `from_file'

package("crappy-inventory-agent") do
  action [:remove]
  retries 0
  retry_delay 2
  guard_interpreter :default
  package_name "crappy-inventory-agent"
  cookbook_name "common"
  recipe_name "debian"
end
```

**Comment by nomadium** [comment]
Can somebody reproduce this bug? I was taking a look at this issue but I couldn't reproduce it.

**Comment by kevsgithub** [comment]
@nomadium This just happened to me.
I download a remote .deb using remote_file.
installed it using package and provider Chef::Provider::Package::Dpkg
failed to remove it using package action :remove

dpkg_package action :remove does work as a workaround, Thanks.

**Comment by lamont-granquist** [comment]
#4888 should have fixed this, the apt_package provider will now return 'nil' for the candidate_version instead of raising an exception.

**Comment by stuartnelson3** [comment]
I encountered this problem on `jessie`. The suggested workaround `dpkg_package` was successful.
