### ISSUE TITLE
powershell_script: flags is confusing and hard to use

### ISSUE THREAD

**Issue by docwhat** [chef/chef#1604]
The documentation for `flags` for the `powershell_script` resource implies you can use an array, but it requires a string.  http://docs.opscode.com/resource_powershell_script.html#attributes

Furthermore, you don't override the default flags, you add to them: 
https://github.com/opscode/chef/blob/master/lib/chef/provider/powershell_script.rb#L63-L87

I feel like it should always append `-NoLogo, -NonInteractive -InputFormat None, -File` but that `-NoProfile, -ExecutionPolicy RemoteSigned` should both be able to be overridden.

Perhaps this should be changed to two different elements:

* `use_profile` -- default `false`
* `execution_policy` -- `:remote_signed`

And then build the flags internally.

**Comment by smurawski** [comment]
The docs are correct now in specifying the flags attribute takes a string.

**Comment by adamedx** [comment]
@brendonmartino, thanks for your comment on leaving the script behind for debugging. This might be useful for all script resources, so feel free to open a specific issue for that.

**Comment by smurawski** [comment]
There is a second issue, about the defaulting of the executionpolicy and the noprofile and I've set up https://github.com/chef/chef/issues/3057 to track that issue.

**Comment by eric-tucker** [comment]
I just stumbled upon this - how is this in any way valid that Chef ignores setting a blank flags parameter?  How the hell am I supposed to set my own values?  I don't want -NoProfile as I'm trying to run Chef to configure things specific to my user account on which I'm running Chef (configuring my local machine).

**Comment by DamonStamper** [comment]
+1 to allow powershell_script to load a profile.
