### ISSUE TITLE
Package resource should support .msu files

### ISSUE THREAD

**Issue by Tech356** [chef/chef#1614]
### Version:

chef-client 11.12.8
### Environment:

Windows 7 x64 and x32
### Scenario:

Install an `.msu` file with chef package resource. 

Microsoft provides `.msu` files as update packages. It would be good to have the package resource recognize and install the msu.

`wusa.exe D:\934307\Windows6.0-KB934307-x86.msu /quiet /norestart`

http://support.microsoft.com/kb/934307

**Comment by smurawski** [comment]
@btm We should circle wagons on this and knock this out.

**Comment by btm** [comment]
@smurawski here's where I left off back in October: https://github.com/chef/chef/tree/btm/win_package_updates

**Comment by aarsan** [comment]
If this does get implemented, is there a way to do this without using wusa.exe? The reason is wusa is async and does not wait for the installation to complete so there is no installation progress or success / failure return.

**Comment by artemyarulin** [comment]
@aarsan, I'm not sure what else you can use, but I solved async problem with `start wait`, like here:
```
batch "Update.#{params[:name]}" do 
    code "start /wait wusa.exe \"#{tmpFolder}\\#{params[:name]}.msu\" /quiet /norestart"
    not_if "wmic qfe | findstr /i \"#{params[:name]}\""
  end
```

**Comment by aarsan** [comment]
Thanks @artemyarulin - i'll give that a shot!

**Comment by adamedx** [comment]
In terms of making this work with the package resource, I think the task scheduler approach is the way to go since it bypasses any restrictions that are checked by wuapi when run remotely (e.g. winrm).

**Comment by btm** [comment]
You can install cab's remotely over winrm, which are in MSUs, which works around the silly update over winrm issue. Silly because this is how Microsoft tells you to work around it: https://support.microsoft.com/en-us/kb/2773898

That's where I was headed with writing a cab provider that would be used by an MSU provider. We'll get back in the next couple of months.

**Comment by djmbm** [comment]
I'd really like to upvote this. Currently we're using a completely unsupported procedure to repackage MSU as MSI, and then installing the MSI package.

**Comment by btm** [comment]
It's almost made it to our roadmap for a couple of quarters. I did this work a while ago but didn't finish so it is unmerged:

https://github.com/chef/chef/commit/3fe7f021b84371bbdb7faafa4de10ed2a0ff50b3

I started writing an MSU provider that used wusa, but then realized if I extracted the MSU to a CAB, I could install updates in a remote session successfully when you would previously get an "Access is Denied" error, see http://www.hurryupandwait.io/blog/safely-running-windows-automation-operations-that-typically-fail-over-winrm-or-powershell-remoting for @mwrock's work arounds.

@djmbm so in the interim you might find it less "completely unsupported" to have your installation use extract to get a cab and then dism to install the cab file.

**Comment by btm** [comment]
We're finishing up support for cab files over in https://github.com/chef/chef/pull/5285. After that, we can do MSU. When I originally worked on this I found that unpacking an MSU to CAB and then installing the CAB provided some benefits like avoiding some privilege limitations noted in https://github.com/chef/chef/issues/1614#issuecomment-151856730.

**Comment by eedwardsdisco** [comment]
Would really like msu support for installing WMF 5.0

**Comment by djmbm** [comment]
WMF is one of our use cases as well, in fact I think it's our primary one.

**Comment by btm** [comment]
This was fixed in https://github.com/chef/chef/pull/5445 and is in Chef 12.17.11+. It is scheduled to be released to stable on Monday as I previously mentioned.
