### ISSUE TITLE
Chef-Client: Error 413 - Disabling Ohai plugin does not work.

### ISSUE THREAD

**Issue by Freajka** [chef/chef#1615]
Hello,

When installing Chef, version 11.12.8, on a machine with Debian 6 and trying to register to a server i get the HTTP Error 413: "Request entity is too large" because i have thousands of users on that machine.

The issues is that disabling the OHAI plugin: "passwd" by adding

Ohai::Config[:disabled_plugins] = [ "passwd" ]

to /etc/chef/client.rb does not work. Checked that by:

chef-client -l debug > /tmp/chefClient.txt
grep "Skipping" /tmp/chefClient.txt

I had to manually move the passwd.rb from its default location in order for the chef-client to start and the debug log still does not show that it skips the "passwd" plugin.

**Comment by sdrycroft** [comment]
Thanks @mfarrar, I too was guilty of saving a full search result to the node object and was also experiencing this issue. Your post helped me to fix my code and resolve the problem.

**Comment by AReshma** [comment]
Will be there any side effects if we disable the 'passwd' ohai plugin?
