### ISSUE TITLE
yum_package flush_cache shouldn't need to be an array

### ISSUE THREAD

**Issue by kcd83** [chef/chef#1640]
The documentation doesn't make it clear that flush_cache needs to be an array http://docs.opscode.com/resource_yum.html.

Works:

```
flush_cache [:before]
```

Doesn't:

```
flush_cache :before
```

```
NoMethodError
-------------
undefined method `any?' for :before:Symbol
```

Surely this doesn't need to be an array of one?

**Comment by smurawski** [comment]
I think we should do the right thing and convert the scalar value to an array for you.  This is a broader issue with how we parse resource attributes.

**Comment by kcd83** [comment]
Great thanks
