### ISSUE TITLE
Knife upload skips environments/roles in .RB

### ISSUE THREAD

**Issue by tas50** [chef/chef#1641]
.rb is a supported format for environments and roles and a lot of setups use the format, but knife upload completely skips over the files.  Both knife upload and knife upload / in the base of a chef-repo with .rb files does nothing, but upload cookbooks.  It would be great to get this working for all setups

**Comment by smurawski** [comment]
This impacts both chef-client --local-mode and knife.

**Comment by tas50** [comment]
This is fixed by #4887
