### ISSUE TITLE
Group resource doesn't handle delayed evaluators that evalutate to strings

### ISSUE THREAD

**Issue by stevendanna** [chef/chef#1668]
The group resource can't handle delayed evaluators that result in a string rather than an array:

```
chef:recipe > r = group "foo" do
chef:recipe > members lazy { "foo" }
chef:recipe ?> end
 => <group[foo] @name: "foo" @noop: nil @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :create, :remove, :modify, :manage] @action: :create @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: "(irb#1):4:in `irb_binding'" @guard_interpreter: :default @elapsed_time: 0 @resource_name: :group @group_name: "foo" @gid: nil @members: #<Chef::DelayedEvaluator:0x007fe82f8dfbe8@(irb#1):5> @excluded_members: [] @append: false @non_unique: false @cookbook_name: nil @recipe_name: nil>
chef:recipe > r.members
Chef::Exceptions::ValidationFailed: Option members must be a kind of [Array]!  You passed "foo".
```

Most proximately, this is because the validation in set_or_return is set to only allow arrays. Strings are handled by coercing them into arrays when the attribute is set:

  https://github.com/opscode/chef/blob/master/lib/chef/resource/group.rb#L58

**Comment by smurawski** [comment]
This is similar to the root cause of https://github.com/chef/chef/issues/1640 where scalar values aren't cast into an array.

**Comment by lamont-granquist** [comment]
think this got fixed due to converting to properties at some point along the way.
