### ISSUE TITLE
Possible enhancement: catch #exec

### ISSUE THREAD

**Issue by coderanger** [chef/chef#1689]
Something I've not seen before tonight, but probably isn't the only time this has happened:

```ruby
template ...

exec 's3cmd ...'
```

The user meant to use an execute resource, but instead they are calling Kernel#exec which bails out of chef. We could add a Recipe#exec that just raises an error or make it an alias for execute.

**Comment by dpnl87** [comment]
@lamont-granquist I'm I correct this issue can be closed with the merge of #2041?

**Comment by lamont-granquist** [comment]
think so
