### ISSUE TITLE
Chef-client should support unattended upgrades regardless of init system

### ISSUE THREAD

**Issue by stevendanna** [chef/chef#1691]
Currently, upgrading chef-client can be wrought with danger for users on operating systems using SysV init.  After installation of the new package, the chef-client daemon needs to be restarted.  Simply notifying a service restart (the strategy taken by omnibus_updater, one of the more popular recipes for managing Chef) can leave orphaned chef-client processes.

One possible solution would be to support a new signal that would force the chef-client to re-exec itself after any running convergences were complete.

**Comment by smurawski** [comment]
This should be resolved as of Chef 12.  If you hit this same issue in Chef 12, please open a new issue.
