### ISSUE TITLE
Line endings depending on chef runtime platform

### ISSUE THREAD

**Issue by LeoCavaille** [chef/chef#1718]
My configuration:
- cookbooks are modified in a GNU/Linux environment
- cookbooks are used on Windows by people using chef-solo 11.12.8
- it is used to provision a Linux Virtual Machine

In a cookbook I define this resource:

```
cookbook_file "zshrc" do
  path "/home/#{workspace_user}/.zshrc"
  action :create
  owner workspace_user
  mode "0644"
end
```

When chef creates the resource, it replaces the Unix line endings with Windows ones `^M` which makes the files not usable in the Linux VM.
I tried monkey patching the template code which is doing that, but I haven't had much success:
https://github.com/opscode/chef/blob/11.12.8/lib/chef/mixin/template.rb#L143-L145

Is there another option I missed to get rid of Windows line endings? If not, could it be considered to add one? Or even a workaround will be great!
Thanks

**Comment by smurawski** [comment]
Related to https://github.com/chef/chef/issues/2466

**Comment by lamont-granquist** [comment]
^ so after reading this closer I understand the problem:

chef-solo is running on Windows and converting line endings to Windows.

then those files are sent to a Linux box with Windows line endings.   so in this case what chef does to translate line endings to the target O/S is not what the user wants (the reverse of the normal complaint we were getting before 11.6.0)

**Comment by epu** [comment]
Was there a resolution to this? I think I am hitting this developing with chefdk 0.6 on windows (with debian/ubuntu/osx test-kitchen guests). I would like to either set CRLF / LF endings by specifying in resource / file attributes.

**Comment by lamont-granquist** [comment]
What we need to do here is reinstate an old PR of mine to add a 'binmode' flag to every file resource as part of the massive 11.6.0 file provider refactor, which was backed out in #795

**Comment by stiller-leser** [comment]
Is there any update on this topic? We ran into the same issues, which is really quite hindering when developing on windows (had to use to virtual servers in the cloud, which is suboptimal).
