### ISSUE TITLE
CHEF-4028:  log resource should not report as updated but should fire notifications

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#1727]
The proposed patch for CHEF-4028 had to be reverted because people expect this to work:

``` ruby
execute "bar" do
  command 'echo "Bar"'
  action :nothing
end

log "foo" do
  notifies :run, "execute[bar]", :immediately
end
```

The proposed CHEF-4028 patch also still updated the log resource when it logged, which was explicitly not what the user wanted.

One problem is that people are abusing a side effect of the log resource in order to group notifications.    We could construct a 'null' resource instead that did nothing but was always updated (unless action :nothing'd) that people could hang their notifications off of.

It has been argued that the CHEF-4028 patch is correct and should be the way the log resource works, but this means that the log resource will fire and be updated if and only if it actually logs in the log level.  That means that the resource updated count and any notifications you hang off of it would differ based on the log level that chef-client was invoked as.   That would make hanging notifications off of the log resource largely crazy which is the driver for the null resource.  This also does not solve the stated problem in CHEF-4028 which is that the log resource must log, yet not be updated.

Ways I can think of to implement this:
1.  The log resource could never be updated and never fire notifications, and only log (this would be a breaking change and would require implementing the null resource)
2.  The log resource could set a flag that resource reporting and resource counting at the end of the run would use to ignore the updated status of the resource (marking itself as blacklisted for reporting).
3.  The Chef::Runner and Chef::Resource could be modified so that the log resource could tell them to fire notifications even though it didn't mark itself as updated (the more i think about it the worse of an idea this seems).

All of these break the resource model in one way or another.

We should arguably implement the 'null' resource in any case, and push folks towards using that instead of abusing the log resource.  That may be somewhat orthogonal.

**Comment by juliandunn** [comment]
Since this has come up again on the [feedback forum](https://feedback.chef.io/forums/301644-chef-product-feedback/suggestions/8278359-log-resource-that-logs-during-converge), and the RFC process didn't exist when we first implemented and rolled back this change, do you think that would be an appropriate way to establish direction for what we should do? Or is that too heavyweight?

**Comment by lamont-granquist** [comment]
Yep RFC is appropriate for this.
