### ISSUE TITLE
"knife upload" doesn't freeze cookbooks "knife cookbook upload" does

### ISSUE THREAD

**Issue by petecheslock** [chef/chef#1728]
Using the latest chef 11.12.8 - and using `knife upload` does not freeze the cookbooks when the option is chosen.  

```
$ knife cookbook delete lvm
Do you really want to delete lvm version 1.2.2? (Y/N)y
Deleted cookbook[lvm version 1.2.2]
$ knife upload cookbooks --freeze true
Created cookbooks/lvm
$ knife cookbook show lvm latest
attributes:
chef_type:     cookbook_version
cookbook_name: lvm
definitions:
files:
frozen?:       false
json_class:    Chef::CookbookVersion
```

`knife cookbook upload` does though.

```
knife cookbook upload --freeze lvm
Uploading lvm            [1.2.2]
Uploaded 1 cookbook.
$ knife cookbook show lvm latest | grep frozen
frozen?:       true
```

**Comment by lamont-granquist** [comment]
If you've got metadata.json with the frozen attribute set to true I think it probably will freeze it.

You might also be able to drop a `frozen true` tag into metadata.rb

**Comment by jekriske** [comment]
This is still an issue as of knife 12.3.0

**Comment by luckymike** [comment]
Any updates here? It would be pretty handy for this to work as described.

**Comment by pmacdougall** [comment]
This 4 year old bug bit me this week.
