### ISSUE TITLE
Solaris mount resource enhancements

### ISSUE THREAD

**Issue by MarkGibbons** [chef/chef#1737]
The upcoming implementation of the solaris mount command is missing a few things and I think has a pretty bad bug.  I've merged the version of the mount command that I use with the version Mr Grandquist created in hopes it will fix problems for some people.  I've been using a version of this code for a year or more.  I'll change this issue to a pull request soon.

1) The fsck device field in vfstab was always set to -.  Added a means to set it.
2) The no auto option reasonably sets mount at boot to no.  Load current resources adds noauto if mount at boot is set to yes.  I think this is 180 degrees backwards and causes some really bad problems.
3) Handle the option changes needed to deal with adding or removing noauto from a resource's options.
4) Allow vxfs as a file system type.
5) Refactor some of the stuff that was really hard to figure out.

I believe I added tests that cover the additions and fixed some tests that depended on the reversed noauto behavior.

Thanks,
  Mark

**Comment by manderson26** [comment]
Fix merged in #1788
