### ISSUE TITLE
knife cookbook site install fails on Windows in directories with spaces

### ISSUE THREAD

**Issue by Tech356** [chef/chef#1753]
The tar command cannot find the file and fails. The path parameter given to the command is not quoted.

    username@hostname /d/Box Sync/Projects/chef/chef-repo {chef-vendor-windows}                                      
    $ knife cookbook site install windows                                                                                 
    Installing windows to d:/Box Sync/Projects/chef/chef-repo/cookbooks                                                   
    Checking out the master branch.                                                                                       
    Pristine copy branch (chef-vendor-windows) exists, switching to it.                                                   
    Downloading windows from the cookbooks site at version 1.34.0 to d:/Box Sync/Projects/chef/chef-repo/cookbooks/windows
    .tar.gz                                                                                                               
    Cookbook saved: d:/Box Sync/Projects/chef/chef-repo/cookbooks/windows.tar.gz                                          
    Removing pre-existing version.                                                                                        
    Uncompressing windows version 1.34.0.                                                                                 
    ERROR: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'                      
    ---- Begin output of tar zxvf /d/Box Sync/Projects/chef/chef-repo/cookbooks/windows.tar.gz ----                       
    STDOUT:                                                                                                               
    STDERR: tar (child): /d/Box: Cannot open: No such file or directory                                                   
    tar (child): Error is not recoverable: exiting now                                                                    
    tar: Child returned status 2                                                                                          
    tar: Sync/Projects/chef/chef-repo/cookbooks/windows.tar.gz: Not found in archive                                      
    tar: Exiting with failure status due to previous errors                                                               
    ---- End output of tar zxvf /d/Box Sync/Projects/chef/chef-repo/cookbooks/windows.tar.gz ----                         
    Ran tar zxvf /d/Box Sync/Projects/chef/chef-repo/cookbooks/windows.tar.gz returned 2                                  

I found the same issue detailed in this issue:
https://tickets.opscode.com/browse/CHEF-4209

**Comment by lamont-granquist** [comment]
Simple to fix this:

```Begin output of tar zxvf /d/Box Sync/Projects/chef/chef-repo/cookbooks/windows.tar.gz```

The path needs to be quoted.
