### ISSUE TITLE
package resource fails on .deb package

### ISSUE THREAD

**Issue by paulczar** [chef/chef#1763]
this worked on `11.12.8-2`

```
package 'redis-server' do
  source "#{Chef::Config[:file_cache_path]}/redis-server-2.8.8_amd64.deb"
  action [:install]
end
```

```
           Chef::Exceptions::Package
           -------------------------
           apt package provider cannot handle source attribute. Use dpkg provider instead
```

As you might expect I can work around this by adding `provider Chef::Provider::Package::Dpkg` to the package resource .... but it seems like an unwanted regression and should be marked as a bug.

**Comment by wolf31o2** [comment]
Just curious, by why isn't `package` "smart" here, instead? I mean, there's two providers on a platform, with one really being a wrapper for the other, and only one of them can successfully fulfill the request. Why not switch provider on "source" being applied without forcing the user to do this? Now, I cannot use:
```ruby
s = '/path/to/somefile.rpm' if node['platform_family'] == 'rhel'
s = '/path/to/somefile.deb' if node['platform_family'] == 'debian'
package 'somefile' do
  source s
end
```

**Comment by spuder** [comment]
Running into this as well on chef 12.18.31 on ubuntu 16.04

The documentation makes it appear that the package resource should intelligently switch between the appropriate package manager. I swear this used to work. 

https://docs.chef.io/resource_dpkg_package.html

>In many cases, it is better to use the package resource instead of this one (dpkg_package). This is because when the package resource is used in a recipe, the chef-client will use details that are collected by Ohai at the start of the chef-client run to determine the correct package application. Using the package resource allows a recipe to be authored in a way that allows it to be used across many platforms.
