### ISSUE TITLE
Metadata should support a source url

### ISSUE THREAD

**Issue by btm** [chef/chef#1776]
[Supermarket](http://supermarket.getchef.com) takes a URL to the source in the details for a cookbook and provides a link, hopefully to github or something similar, where you can view the cookbook. This information should be in the cookbook itself though. We should add a SOURCE_URL parameter to the metadata for this information, and then file an [issue against Supermarket](https://github.com/opscode/supermarket/issues/new) to have it suck in this information if it exists.

I think this is relevant to https://github.com/opscode/supermarket/issues/32 which discusses what sort of metadata should be present on Supermarket for a cookbook, although not all of it necessarily should be in the cookbook itself.

**Comment by smurawski** [comment]
@agh I moved your request for arbitrary data to https://github.com/chef/chef/issues/3104
