### ISSUE TITLE
FreeBSD service fails to set if service_enabled is duplicated in comments

### ISSUE THREAD

**Issue by johnko** [chef/chef#1791]
/etc/rc.conf
```
# sshd_enabled="YES"
sshd_enable="NO"
```

cookbooks/my-ssh-config/recipes/default.rb
```
include_recipe "openssh"
```

**Comment by Aevin1387** [comment]
This looks like it was fixed in f74eb6c47e6bcb373f0f1e214c7f42b5715fb6f3. I tested this out and it enables the service, though it leaves in the comment. I've submitted #2842 to remove commented out versions of the service being enabled or disabled.

**Comment by martinisoft** [comment]
As @Aevin1387 mentioned earlier here. Is this issue resolved for you @johnko ?

**Comment by johnko** [comment]
No idea. I haven't used in a while. I'll close for now.
