### ISSUE TITLE
Enhancement: Pin 'Latest Frozen' cookbook version in environment

### ISSUE THREAD

**Issue by jhmartin** [chef/chef#1794]
Enhancement: Allow pinning cookbook versions to 'highest version that is frozen' in environment files.

In environments with significant number of environments, it is cumbersome to increment a cookbook version across all of the environments. 

The workflow is often: Version X for all 'production' environments, and latest for all others for testing purposes. I suggest an operator for chef environment files that allows the selection of the highest version number that is in the frozen state.  This would allow non-production environments to live on the 'bleeding edge' and have them update based on the frozen marker, as opposed to directly updating many environments.

**Comment by thommay** [comment]
Our recommended workflow for this will be to use the upcoming PolicfyFiles feature, as described above.
