### ISSUE TITLE
Windows Service identity configuration (from CHEF-4921)

### ISSUE THREAD

**Issue by adamedx** [chef/chef#1797]
System services on Windows can be configured to run as an arbitrary identity, often a domain user. The service resource on Chef should support this capability -- it currently does not have required attributes (both a user name and password are required unless you configure the service to run as system, local service, or network service). The resource and provider should be updated on Windows to support this.  Among other things, this will also allow users to configure the Chef service itself to run as an arbitrary user.

More from the original source, [CHEF-4921](https://tickets.opscode.com/browse/CHEF-4921)

> Currently, Chef::Provider::Service::Windows on Windows only supports very basic operations, such as enabling, stopping, and starting services.
The Windows Service configuration model supports many more attributes. A common use case is to configure "Logon As" user credentials for a Windows service (for example to grant access to network resources, or run as a less privileged user). Other attributes include setting service recovery methods, dependencies, etc. These attributes are supported by the win32-service library.
See: https://github.com/djberg96/win32-service/blob/ffi/doc/service.txt

**Comment by adamedx** [comment]
This feature has been implemented in Chef 12.0.0: https://github.com/chef/chef/commit/be28ba90bde1fe0240f313151e3d564ce57e8b29#diff-7d9446b811004164149933221ef24277.

**Comment by jdmundrawala** [comment]
This went in for 12.1 i think
