### ISSUE TITLE
remount unmounts/mounts a filesystem when remount is unavailable

### ISSUE THREAD

**Issue by JamesBelchamber** [chef/chef#1798]
When remount is not supported, the remount action instead unmounts and then mounts the filesystem. This isn't the same thing and is possibly not desirable - a remount preserves file handles, for example, which is much less intrusive than a full unmount and then mount of the filesystem.

Bah, I don't know what the right behaviour should be - I would expect remount to just do a `mount -o remount`, and fail if that doesn't work.

**Comment by thommay** [comment]
It would be good to address this in #1795 as a general clean up of the mount resource.

**Comment by akilunov** [comment]
It's been almost a year... any update on this? I'm running into this problem right now :(

**Comment by lamont-granquist** [comment]
This feels like correct behavior to me.  Nobody has suggested what the behavior should be.  Doing the umount/mount if remount is actually what I'd expect.  Blowing up feels a bit useless to me.  I also don't really understand the use case where this comes up as a bug.  And it feels like there's either going to be some people doing special handling to manually translate remount to umount/mount in their recipes based on if remount is supperted vs. the people today that need to maybe special case this behavior that it is just pushing around pain to try to solve this.
