### ISSUE TITLE
Search specificity (anchoring?)

### ISSUE THREAD

**Issue by pdf** [chef/chef#1855]
It's currently impossible to search for a specific attribute at the top level.  This makes it extremely difficult to produce a search that actually reference the attribute you're trying to restrict results to.  Nested attributes, especially if they're deeply nested, you can probably get away with, because you're less likely to have collisions for the whole tree, but for top-level attributes, it's very likely that you will be unable to produce results that don't require post-processing to obtain what you're actually looking for.

I haven't worked out how this flattening stuff happens yet (I'm pretty convinced this was a terrible idea to start with - if you don't know what you're searching for, how can you expect to get useful results??), but my thinking is that perhaps we can work around this by adding an anchor character to force specificity, eg:

`knife search node ^fqdn:foo.bar.com`

The above would only match the top-level `fqdn` attribute, and not any nested attribute that might have the same name.

This behaviour is hurting pretty badly, so I'll submit a PR for it, but I'd like some feedback (and optimally some pointers on where to find the code responsible for search resolution) before I go ahead and get stuck in.

**Comment by thommay** [comment]
Conceivably this requires an RFC for the search syntax change, but even if that's not the case we're going to touch the server and client, and possible chef-zero too.

**Comment by lamont-granquist** [comment]
closing this since resources and interest in fixing search is low.
