### ISSUE TITLE
11.14 alters behavior of chef_gem

### ISSUE THREAD

**Issue by dpetzel** [chef/chef#1866]
I'm not sure if this is a bug, or an expected behavior change, but I wanted to get clarification here before we work around the issue. FWIW, we have a private chef ticket open with support about this issue.

The Background:
We have a custom library that adds additional (internal) Gem Sources via the GEM API. After which a set of in house gems are deployed from these additional sources. We are not altering the sources via the gem binary.  As recently as 11.12.8 this has been working just fine, however since 11.14, its failing saying it can't find a gem in any valid source.

The Issue:
I've tracked this back to this commit https://github.com/opscode/chef/commit/58810790bd94953a4f2c28c77487f29d435b5ab5. This is now altering the behavior of the check in this line: https://github.com/opscode/chef/blob/11.14.6/lib/chef/provider/package/rubygems.rb#L509

Before this commit `@new_resource.gem_binary.nil?` would return true, and the GEM API would be used. However after this commit, `@new_resource.gem_binary.nil?` returns false, forcing chef_gem to use the gem binary installation method. Since we are not setting the sources via the binary, our custom sources are not in the list and the installation is failing.

It is possible for us to change the sources via the gem binary if need be, but I'm not sure if that is the best way to proceed. Based on the change log entry, it seems like maybe this is intentional, but I'd like confirmation that the expected behaviour is that `chef_gem` should **never** use the Gem API for installation anymore.

cc @lamont-granquist

**Comment by lamont-granquist** [comment]
closing this as old, would need to get replicated against chef-15 and reopened.
