### ISSUE TITLE
Knife bootstrap should create initial node and API client, not use the validator

### ISSUE THREAD

**Issue by jtimberman** [chef/chef#1886]
Instead of using the validation client key to automatically create new API clients for bootstrapped nodes, `knife bootstrap` should use the configured API user (human) running it from their workstation to provision the node and API client object for the node to be bootstrapped.

Internal reference implementation (private repository) is in the knife-hec plugin by ops:

* https://github.com/opscode/knife-hec/blob/master/lib/chef/knife/hec_node_create.rb
* https://github.com/opscode/knife-hec/blob/master/lib/templates/knife_hec_template.erb

**Comment by juliandunn** [comment]
I'm closing this since we shipped validator-less bootstrap via the mentioned PR.

**Comment by jtimberman** [comment]
:+1: :icecream:
