### ISSUE TITLE
Silent installation using windows_package resource

### ISSUE THREAD

**Issue by tortuga90** [chef/chef#1891]
Hi, I want to install a package on my windows machine, without any user intervention. I am using windows_package resource for installation, following is the code for same - 
windows_package "Install Open Office" do 
source 'file:////10.132.17.53/e$/CHEFREPO/OpenOffice 4.1.0 (en-US) Installation Files/setup.exe'
	options '/q'
	installer_type :inno
	action :install
end

By default windows_package uses /verysilent and /norestart as options. But the recipe run requires a user intervention. While installing, it gives me an Open File : Security warning, to proceed from here user click is needed. How can I bypass this for complete silent installation with zero user intervention required.

**Comment by samsonkolge** [comment]
Guys,
I am having issues with upgrading powershell from version2 to latest version 5 using windows_package.
The task is to upgrade package without having to go to the internet...hence not using powershell resource. I am getting below error:

$ kitchen converge
-----> Starting Kitchen (v1.8.0)
-----> Converging <default-windows-2008-r2>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.3.3...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)

       Transferring files to <default-windows-2008-r2>
       Starting Chef Client, version 12.13.37
       resolving cookbooks for run list: ["m1-2.0::default"]
       Synchronizing Cookbooks:
         - m1-2.0 (0.1.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 1 resources
       Recipe: m1-2.0::install_ps
         * windows_package[powershell5_install] action install
         Recipe: <Dynamically Defined Resource>
           * remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\package\Win7.msu] action create[2016-08-22T18:45:24-07:00] WARN: remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\package\Win7.msu] cannot be downloaded from https://192.168.33.92/foo/Win7.msu: 503 "Service Unavailable"


             ================================================================================
             Error executing action `create` on resource 'remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\package\Win7.msu]'
             ================================================================================

             Net::HTTPFatalError
             -------------------
             503 "Service Unavailable"

             Compiled Resource:
             ------------------
             # Declared in

             remote_file("C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\package\Win7.msu") do
        provider Chef::Provider::RemoteFile
        action [:create]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        source ["https://192.168.33.92/foo/Win7.msu"]
        use_etag true
        use_last_modified true
        checksum "e290bb51dd66e63331bb6ba0a1a0c8c9"
        path "C:\\Users\\vagrant\\AppData\\Local\\Temp\\kitchen\\cache\\package\\Win7.msu"
        atomic_update true
             end

             Platform:
             ---------
             x64-mingw32


           ================================================================================
           Error executing action `install` on resource 'windows_package[powershell5_install]'
           ================================================================================

           Net::HTTPFatalError
           -------------------
           remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\package\Win7.msu] (dynamically defined) had an error: Net::HTTPFatalError: 503 "Service Unavailable"

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/m1-2.0/recipes/install_ps.rb

             8: windows_package 'powershell5_install' do
             9:   checksum 'e290bb51dd66e63331bb6ba0a1a0c8c9'
            10:   installer_type :custom
            11:   source 'https://192.168.33.92/foo/Win7.msu'
            12:   options '/quiet /norestart'
            13:   action :install
            14: end

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/m1-2.0/recipes/install_ps.rb:8:in `from_file'

           windows_package("powershell5_install") do
             package_name "powershell5_install"
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :windows_package
             cookbook_name "m1-2.0"
             recipe_name "install_ps"
             checksum "e290bb51dd66e63331bb6ba0a1a0c8c9"
             installer_type :custom
             source "https://192.168.33.92/foo/Win7.msu"
             options "/quiet /norestart"
           end

           Platform:
           ---------
           x64-mingw32


       Running handlers:
       [2016-08-22T18:45:24-07:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-08-22T18:45:24-07:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 01 minutes 22 seconds
       [2016-08-22T18:45:24-07:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2016-08-22T18:45:24-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-08-22T18:45:24-07:00] FATAL: Net::HTTPFatalError: windows_package[powershell5_install] (m1-2.0::install_ps line 8) had an error: Net::HTTPFatalError: remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache\package\Win7.msu] (dynamically defined) had an error: Net::HTTPFatalError: 503 "Service Unavailable"
>>>>>> Converge failed on instance <default-windows-2008-r2>.
>>>>>> Please see .kitchen/logs/default-windows-2008-r2.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [
$env:PATH = [System.Environment]::GetEnvironmentVariable("PATH","Machine")

& $env:systemdrive\opscode\chef\bin\chef-client.bat --local-mode --config $env:TEMP\kitchen\client.rb --log_level auto --force-formatter --no-color --json-attributes $env:TEMP\kitchen\dna.json --chef-zero-port 8889]
>>>>>> ----------------------

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
