### ISSUE TITLE
"ERROR: can't dup NilClass" when bootstrap --server-url is not a URI

### ISSUE THREAD

**Issue by ghost** [chef/chef#1909]
command issued : 
chef-client -S 172.16.60.2 -K /root/temp.key

same problem seen here: 
http://permalink.gmane.org/gmane.comp.sysutils.chef.user/17314

stacktrace:
Generated at 2014-08-23 04:51:15 +0300
TypeError: can't dup NilClass
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/http/http_request.rb:146:in `dup'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/http/http_request.rb:146:in`build_headers'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/http/http_request.rb:78:in `initialize'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/http/basic_client.rb:58:in`new'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/http/basic_client.rb:58:in `request'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/http.rb:262:in`block in send_http_request'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/http.rb:294:in `retrying_http_errors'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/http.rb:256:in`send_http_request'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/http.rb:143:in `request'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/http.rb:126:in`post'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/api_client/registration.rb:92:in `create'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/api_client/registration.rb:83:in`create_or_update'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/api_client/registration.rb:56:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/client.rb:323:in`register'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/client.rb:416:in `do_run'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/client.rb:213:in`block in run'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/client.rb:207:in `fork'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/client.rb:207:in`run'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/application.rb:236:in `run_chef_client'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/application/client.rb:338:in`block in run_application'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/application/client.rb:327:in `loop'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/application/client.rb:327:in`run_application'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/lib/chef/application.rb:55:in `run'
/usr/local/rvm/gems/ruby-1.9.3-p547/gems/chef-11.14.6/bin/chef-client:26:in`<top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p547/bin/chef-client:23:in `load'
/usr/local/rvm/gems/ruby-1.9.3-p547/bin/chef-client:23:in`<main>'
/usr/local/rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-1.9.3-p547/bin/ruby_executable_hooks:15:in`<main>'

info:
app chef # chef-client --version
Chef: 11.14.6
app chef # ruby --version
ruby 1.9.3p547 (2014-05-14 revision 45962) [x86_64-linux]
app chef # 
app chef # gem --version
2.2.2
app chef # 
app chef # gem list --local

**\* LOCAL GEMS ***

bigdecimal (1.1.0)
bundler (1.7.2)
bundler-unload (1.0.2)
chef (11.14.6)
chef-zero (2.2)
coderay (1.1.0)
diff-lcs (1.2.5)
erubis (2.7.0)
executable-hooks (1.3.2)
ffi (1.9.3)
ffi-yajl (1.0.2)
gem-wrappers (1.2.5)
hashie (2.1.2)
highline (1.6.21)
io-console (0.3)
ipaddress (0.8.0)
json (1.5.5)
libyajl2 (1.0.1)
method_source (0.8.2)
mime-types (1.25.1)
minitest (2.5.1)
mixlib-authentication (1.3.0)
mixlib-cli (1.5.0)
mixlib-config (2.1.0)
mixlib-log (1.6.0)
mixlib-shellout (1.6.0.rc.0)
net-ssh (2.9.1)
net-ssh-gateway (1.2.0)
net-ssh-multi (1.2.0)
ohai (7.2.4)
plist (3.1.0)
pry (0.10.1)
rack (1.6.0.beta)
rake (0.9.2.2)
rdoc (3.9.5)
rest-client (1.6.7)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
slop (3.6.0)
systemu (2.6.4)
wmi-lite (1.0.0)
app chef #

**Comment by amaltson** [comment]
:+1: to get a bit better error messages for this. Had several people hit this and also happens when your `knife.rb` doesn't define the protocol.

**Comment by thommay** [comment]
Closing, since the Chef Client error is fixed.
