### ISSUE TITLE
rpm_package fails to install with conflicts

### ISSUE THREAD

**Issue by bbaugher** [chef/chef#1915]
When switching from chef `11.14.2` to `11.14.6` the rpm_package seems to fail installation of an rpm with conflicts. This seems to be caused by [this commit](https://github.com/opscode/chef/commit/0561d743ed3edb039a62b0fb7ace89388e463c85).

Using test-kitchen and debug logging I see the command it ran previously `11.14.2` is,

    rpm  -U /tmp/kitchen/cache/mysql-server-5.6.12-1.el6.x86_64.rpm

But instead now it does this,

    [2014-08-25T10:44:05-05:00] ERROR: rpm_package[/tmp/kitchen/cache/mysql-server-5.6.12-1.el6.x86_64.rpm] (mysql::server line 161) had an error: Chef::Exceptions::Exec: rpm  -i /tmp/kitchen/cache/mysql-server-5.6.12-1.el6.x86_64.rpm returned 1, expected 0
       ---- Begin output of rpm  -i /tmp/kitchen/cache/mysql-server-5.6.12-1.el6.x86_64.rpm ----
       STDOUT: STDERR: 	file /usr/share/mysql/czech/errmsg.sys from install of MySQL-server-5.6.12-1.el6.x86_64 conflicts with file from package mysql-libs-5.1.71-1.el6.x86_64
       	file /usr/share/mysql/danish/errmsg.sys from install of MySQL-server-5.6.12-1.el6.x86_64 conflicts with file from package mysql-libs-5.1.71-1.el6.x86_64
       	file /usr/share/mysql/dutch/errmsg.sys from install of MySQL-server-5.6.12-1.el6.x86_64 conflicts with file from package mysql-libs-5.1.71-1.el6.x86_64
       	file /usr/share/mysql/english/errmsg.sys from install of MySQL-server-5.6.12-1.el6.x86_64 conflicts with file from package mysql-libs-5.1.71-1.el6.x86_64
       	file /usr/share/mysql/estonian/errmsg.sys from install of MySQL-server-5.6.12-1.el6.x86_64 conflicts with file from package mysql-libs-5.1.71-1.el6.x86_64

And here is the defined resource,

    # Declared in /tmp/kitchen/cookbooks/mysql/recipes/server.rb:161:in `block in from_file'

           rpm_package("/tmp/kitchen/cache/mysql-server-5.6.12-1.el6.x86_64.rpm") do
             provider Chef::Provider::Package::Rpm
             action [:install]
             retries 0
             retry_delay 2
             guard_interpreter :default
             package_name "/tmp/kitchen/cache/mysql-server-5.6.12-1.el6.x86_64.rpm"
             source "/tmp/kitchen/cache/mysql-server-5.6.12-1.el6.x86_64.rpm"
             version "5.6.12-1.el6"
             timeout 900
             cookbook_name :"mysql"
             recipe_name "server"
           end

I don't know enough about RPM so I'm hoping someone knows what the right solution is here.

**Comment by steven-a-burns** [comment]
It would appear that I am experiencing a similar issue when using `rpm_package` since we upgraded to 11.16.2 that also appears to be related to Issue #1554. I'll provide a capture of some logs as soon as I get in to the office in the morning.

**Comment by lamont-granquist** [comment]
But reports on 11.16.2 (or even 11.18.6) aren't too useful and will most likely not get fixed unless they replicate on the latest chef-12 (which is 12.1.0.rc.0 right now and should be 12.1.0 shortly).
