### ISSUE TITLE
'knife node edit' fails on Windows with git-bash

### ISSUE THREAD

**Issue by jblaine** [chef/chef#1917]
### Version:

11.14.0.rc.2
### Environment:

Windows 8.1
### Scenario:

Trying to edit a node object
### Steps to Reproduce:

See 'Actual Result'
### Expected Result:

An editor running
### Actual Result:

Git-Bash:

```
Jeff@PATCHY ~/chef-repo (master)
$ grep EDITOR $HOME/.bashrc
export EDITOR=vim

Jeff@PATCHY ~/chef-repo (master)
$ echo $EDITOR
vim

Jeff@PATCHY ~/chef-repo (master)
$ knife node edit dev
ERROR: RuntimeError: Please set EDITOR environment variable

Jeff@PATCHY ~/chef-repo (master)
$ knife node edit dev -e vim
ERROR: RuntimeError: Please set EDITOR environment variable

Jeff@PATCHY ~/chef-repo (master)
$
```

**Comment by stuartpreston** [comment]
I'm going to close this ancient issue, the TLDR is that on Windows we require an editor that supports Windows paths (ref: http://take-your-vitamins.blogspot.com/2013/05/chef-error-runtimeerror-please-set.html).  Vim in the latest git-bash on Windows does actually work for this now:

```bash
echo "export EDITOR=vim" >> ~/.bashrc
source ~/.bashrc
knife node edit vm1306
```

![image](https://user-images.githubusercontent.com/6384654/42879442-887396fc-8a88-11e8-9471-c2fcdadb6730.png)
