### ISSUE TITLE
Chef fails to create directories when it has permission to do so

### ISSUE THREAD

**Issue by Tech356** [chef/chef#1936]
### Version:
Chef Client 11.14.6

### Environment: 
Windows 7 x64

### Scenario:
Create a directory in `C:\Program Files`

### Steps to Reproduce:

    directory "C:\\Program Files\\test" do
        action :create
    end

### Expected Result:
I would expect the directory to be created.

### Actual Result:

The chef client throws an `InsufficientPermissions` error

      * directory[C:\Program Files\test] action create
        * Cannot create directory[C:\Program Files\test] at C:\Program Files\test due to insufficient permissions
        ================================================================================
        Error executing action `create` on resource 'directory[C:\Program Files\test]'
        ================================================================================

        Chef::Exceptions::InsufficientPermissions
        -----------------------------------------
        Cannot create directory[C:\Program Files\test] at C:\Program Files\test due to insufficient permissions

        Resource Declaration:
        ---------------------
        # In C:/chef/cache/cookbooks/test/recipes/default.rb

         15: directory "C:\\Program Files\\test" do
         16:     action :create
         17: end
         18:

        Compiled Resource:
        ------------------
        # Declared in C:/chef/cache/cookbooks/test/recipes/default.rb:15:in `from_file'

        directory("C:\Program Files\test") do
          provider Chef::Provider::Directory
          action [:create]
          retries 0
          retry_delay 2
          guard_interpreter :default
          path "C:\\Program Files\\test"
          cookbook_name "test"
          recipe_name "default"
        end
        
In the [code](https://github.com/opscode/chef/blob/master/lib/chef/provider/directory.rb#L72), it looks like this is caused by `File.writable?` returning `false` for `C:\Program Files` even though the user has enough permissions.
    
    C:\Windows\system32>irb
    irb(main):001:0> ::File.writable?("C:\\Program Files")
    => false
    irb(main):002:0> require 'fileutils'
    => true
    irb(main):003:0> FileUtils.mkdir("C:\\Program Files\\test")
    => ["C:\\Program Files\\test"]
    irb(main):004:0> File.exists?("C:\\Program Files\\test")
    => true
        
This bug is also documented at: https://tickets.opscode.com/browse/CHEF-4453

**Comment by echohack** [comment]
+1 on this.

**Comment by pburkholder** [comment]
@charlesjohnson Can we get this some attention?  Thank!

**Comment by tarak** [comment]
+1. If I'd found this issue earlier it would have saved me a lot of work!!!

**Comment by tarak** [comment]
btw: @carpnick thx for the workaround!!!

**Comment by carpnick** [comment]
Validated 12.1 worked as expected:
```
directory "my_test_folder"  do
   path "C:\\program files\\test\\abc"
	 recursive true
	 action    :create
 end
```

```
 [2015-03-03T18:46:01-05:00] INFO: Processing directory[my_test_folder] action create (eis_lib_chefcore::test line 1)
[2015-03-03T18:46:01-05:00] INFO: directory[my_test_folder] created directory C:\program files\test\abc
10.80.4.60 U
```

**Comment by jdmundrawala** [comment]
Awesome,
Thanks @carpnick

**Comment by vikas8** [comment]
+1
