### ISSUE TITLE
Improve client.rb file parsing

### ISSUE THREAD

**Issue by mffrench** [chef/chef#1940]
Hello,

you can remove a billion dollar mistake (ie: a nill exception ;)) by raising a badly formated URL error while parsing the server url in the client.rb file.

Full context of this improvment request can be found on this thread : 

http://lists.opscode.com/sympa/arc/chef/2014-08/msg00328.html
http://lists.opscode.com/sympa/arc/chef/2014-08/msg00329.html

Regards,

Mathilde

**Comment by lamont-granquist** [comment]
closing due to lack of interest in fixing the PR
