### ISSUE TITLE
powershell_script guards written as strings do not work

### ISSUE THREAD

**Issue by mrobinet** [chef/chef#1943]
### Version:

11.12.8
### Environment:

Windows 2012 Server R2 (possibly all windows)
### Scenario:

None of my string `powershell_script` guard expressions were working until I converted them to blocks. This is not required for other similar resources, such as `execute`.
### Steps to Reproduce:

Does not work (guardtest.log is written to):

``` ruby
powershell_script "Powershell guard testing" do
  code "\"Script executed\" >> \"C:/chef/cache/guardtest.log\""
  not_if "$True"
  guard_interpreter :powershell_script
  convert_boolean_return true
end
```

This does work (guardtest.log is not written to):

``` ruby
powershell_script "Powershell guard testing" do
  code "\"Script executed\" >> \"C:/chef/cache/guardtest.log\""
  not_if { "$True" }
  guard_interpreter :powershell_script
  convert_boolean_return true
end
```
### Expected Result:

Powershell guards should work written as a string and as a block.
### Actual Result:

Powershell guards only works as a block, either using curly braces or do/end.

**Comment by spuder** [comment]
This appears to still be an issue in 11.18.12 (Can't run newer versions of chef due windows bug https://github.com/chef/chef/issues/2814 )

Is there a release version for this fix?
