### ISSUE TITLE
Chef::Knife::SSH should support outgoing proxy settings

### ISSUE THREAD

**Issue by yvovandoorn** [chef/chef#1965]
Recreated from https://tickets.opscode.com/browse/CHEF-2447, while closed to be part of a master ticket, this was never implemented and no cause of why it wasn't isn't given. 

Title pretty much explains it.

```
require 'net/ssh'
require 'net/ssh/proxy/http'

proxy_host = 'my.proxy.com'
proxy_port = 8080
proxy = Net::SSH::Proxy::HTTP.new( proxy_host, proxy_port )

Net::SSH.start( 'host', :proxy => proxy ) do |session|
```

end
http://net-ssh.github.com/ssh/v1/chapter-7.html
The proxy value should also be read in from the http_proxy env variable if set.

**Comment by tas50** [comment]
Tagging this for sustaining so we can try to reproduce the issue. I know we've done a lot of proxy work in the last five years. It's quite possible we support this now.
