### ISSUE TITLE
Controlling no_lazy_load on client.rb during knife bootsrap

### ISSUE THREAD

**Issue by erez-rabih** [chef/chef#1972]
Hi,

I was wondering if there is an option to control the client.rb file generated by knife bootstrap so that no_lazy_load option is set to true instead of false.

Thanks in advance!

**Comment by lamont-granquist** [comment]
fixed by https://github.com/chef/chef-rfc/blob/a77a398e56277b52dffc09f0fbb4d7ac20a68a1c/rfc071-knife-bootstrap-client-config.md
