### ISSUE TITLE
flush_cache does not seem to work on AWS Linux

### ISSUE THREAD

**Issue by gnowxilef** [chef/chef#1991]
### Version:

11.12.8
### Environment:

OS: AWS Linux 2013.09
any cookbook using the flush_cache attribute for yum_package
### Scenario:

yum cache should be flushed
### Steps to Reproduce:

run a cookbook that contains a flush_cache resource for a yum_package when either upgrading or installing a specific package version
### Expected Result:

yum cache is flushed so the new version of a package can be detected
### Actual Result:

yum errors saying that package cannot be found (yum clean expire-cache needs to be run manually)

**Comment by jkanywhere** [comment]
Based on this mapping,
https://github.com/chef/chef/blob/c3552dc11831379a4b4753964451498e1340611e/lib/chef/platform/provider_mapping.rb#L119
, packages on the `amazon` platform are provided by Yum
https://github.com/chef/chef/blob/c3552dc11831379a4b4753964451498e1340611e/lib/chef/provider/package.rb

**Comment by felix-okta** [comment]
[bug.txt](https://github.com/chef/chef/files/118442/bug.txt)

i have attached debug logs from a `chef-apply` run.

**Comment by felix-okta** [comment]
this bug also affect chef 12.

**Comment by lamont-granquist** [comment]
This seems to be based on a misunderstand of what this option does.  There's a YumCache ruby object inside the chef-client that this flushes.  This does not flush the system wide on disk yum cache and does not attempt to replicate the behavior of e.g. `yum clean expire-cache`.
