### ISSUE TITLE
Template resource fails updating some existing files

### ISSUE THREAD

**Issue by Tech356** [chef/chef#1992]
### Version:
11.14.6

### Environment:
Windows 7 x32

### Scenario:
Use the template resource to updated a pre-created file in Program Files. 

### Steps to Reproduce:
I have not figured out a way to create a file that causes this issue. I have just found some existing files that cause this issue.

Here is the code I am using that causes the issue:

    template "C:\\Program Files\\test\\example.ini" do
        source "example.ini.erb"
        variables(
            :test => 'foo',
            :things => ['foo', 'bar']
        )
    end

This is the template:
    
    this is test=<%= @test %>

    Things go here
    <% @things.each_with_index do |data, index| %>
    <%= "#{index}=#{data}" %>
    <% end %>
    
### Expected Result:
I am expecting the file to be updated with the output from the template file. 

### Actual Result:
When `C:\\Program Files\\test\\example.ini` already exists (with whatever properties cause this), the chef client throws `NoMethodError: private method 'select' called for nil:NilClass`. If the file is missing, chef can create it just fine. If the file is created manually on the machine, chef can update it without issues. I believe the issue comes in since I am copying the file from another machine so it must lack some attributes/properties or something. 

    3:09-04:00] DEBUG: Re-raising exception: NoMethodError - template[C:\Program Files\test\example.ini] (test::default line 10) had an error: NoMethodError: private method `select' called for nil:NilClass
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/file_content_management/deploy/mv_windows.rb:71:in `deploy'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/provider/file.rb:341:in `update_file_contents'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/provider/file.rb:372:in `block in do_contents_changes'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/mixin/why_run.rb:52:in `call'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/mixin/why_run.rb:52:in `add_action'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/provider.rb:156:in `converge_by'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/provider/file.rb:371:in `do_contents_changes'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/provider/file.rb:121:in `action_create'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/provider.rb:121:in `run_action'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/resource.rb:648:in `run_action'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/runner.rb:49:in `run_action'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/runner.rb:81:in `block (2 levels) in converge'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/runner.rb:81:in `each'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/runner.rb:81:in `block in converge'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/resource_collection.rb:96:in `execute_each_resource'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/runner.rb:80:in `converge'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/client.rb:345:in `converge'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/client.rb:431:in `do_run'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/client.rb:227:in `run'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/application.rb:236:in `run_chef_client'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/application/client.rb:338:in `block in run_application'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/application/client.rb:327:in `loop'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/application/client.rb:327:in `run_application'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/lib/chef/application.rb:55:in `run'
    c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.14.6-x86-mingw32/bin/chef-client:26:in `<top (required)>'
    c:/opscode/chef/bin/chef-client:23:in `load'
    c:/opscode/chef/bin/chef-client:23:in `<main>'

**Comment by ramarnat** [comment]
I am having this same issue. I believe this is due to the fact that the volume I am using is exFat and as such has no acl.

**Comment by SteveLowe** [comment]
FYI - this is the same as [CHEF-4653](https://tickets.opscode.com/browse/CHEF-4653)
I have run across the same problem.

Using accesschk shows the same issue as @Tech356 - the non-working file has [SE_SACL_PRESENT].

Changing mv_windows.rb as follows did allow chef to apply the template:
```ruby
dacl_present = false
if dst_sd.dacl_present? && !dst_sd.dacl.nil?
    dacl_present = true
    apply_dacl = ACL.create(dst_sd.dacl.select { |ace| !ace.inherited? })
end

sacl_present = false
if dst_sd.sacl_present? && !dst_sd.sacl.nil?
    sacl_present = true
    apply_sacl = ACL.create(dst_sd.sacl.select { |ace| !ace.inherited? })
end

...

dst_so.set_dacl(apply_dacl, dst_sd.dacl_inherits?) if dacl_present
dst_so.set_sacl(apply_sacl, dst_sd.sacl_inherits?) if sacl_present
```

**Comment by johnnyramos** [comment]
I was actually getting this error as well and @SteveLowe's edit fixed it.

**Comment by johnnyramos** [comment]
Just confirmed that 12.1.1-1 still gives this issue.

**Comment by jaymzh** [comment]
@SteveLowe do you wanna send a PR for that?

**Comment by adamedx** [comment]
@btm, @jdmundrawala and I were just discussing this issue recently, if needed we can get together and sync on best approach.

**Comment by btm** [comment]
@adamedx *nod* this has been in our backlog for a couple months now, we'll talk today about prioritizing it.

**Comment by jdmundrawala** [comment]
We need to validate if https://github.com/chef/chef/pull/3066 is correct
