### ISSUE TITLE
Question: Creating node attribute in recipe

### ISSUE THREAD

**Issue by bijugs** [chef/chef#2017]
In a recipe ruby block I am creating a "normal" attribute and it doesn't seem to get saved back into chef server after the chef client run as mentioned in the documentation. Probably it is an issue with my understanding. The following is the code. Let me know if there is any problem with this. Thank you in advance

```
node.set['bcpc']['hadoop']['datanode']['restart'] = false
```

**Comment by adihassan** [comment]
> # [**_``_**](url)

- 

- [ ] @ #1.
