### ISSUE TITLE
Bootstrap failure

### ISSUE THREAD

**Issue by agenerette** [chef/chef#2018]
Hi,

My name is Anthony and I'm hoping to find a solution to a problem that I just ran into.  Essentially, I'm not able to bootstrap a host that I'm trying to set up on Chef Server 10 (non-hosted).  My admin workstation is a Mac running OS 10.9.2, the node that I'm trying to bootstrap is an Ubuntu 12.04 VM running on an EC2 instance.

Here's the command that I ran along with the output that it generated:

ageneretteair2:chef-repo abgenerette$ sudo knife bootstrap -d chef-full --sudo -x agenerette -i ~/.ssh/id_agenerette_rsa -N transform-staging -r "role[transform]" ec2-184-169-240-136.us-west-1.compute.amazonaws.com
Password:
Bootstrapping Chef on ec2-184-169-240-136.us-west-1.compute.amazonaws.com
ec2-184-169-240-136.us-west-1.compute.amazonaws.com --2014-09-09 17:05:53--  https://www.opscode.com/chef/install.sh
ec2-184-169-240-136.us-west-1.compute.amazonaws.com Resolving www.opscode.com (www.opscode.com)...
ec2-184-169-240-136.us-west-1.compute.amazonaws.com 184.106.28.91
ec2-184-169-240-136.us-west-1.compute.amazonaws.com
ec2-184-169-240-136.us-west-1.compute.amazonaws.com Connecting to www.opscode.com (www.opscode.com)|184.106.28.91|:443...
ec2-184-169-240-136.us-west-1.compute.amazonaws.com connected.
ec2-184-169-240-136.us-west-1.compute.amazonaws.com HTTP request sent, awaiting response...
ec2-184-169-240-136.us-west-1.compute.amazonaws.com 200 OK
ec2-184-169-240-136.us-west-1.compute.amazonaws.com Length: 16519 (16K) [application/x-sh]
ec2-184-169-240-136.us-west-1.compute.amazonaws.com Saving to: `STDOUT'
ec2-184-169-240-136.us-west-1.compute.amazonaws.com
 0% [                                       ] 0           --.-K/s
ec2-184-169-240-136.us-west-1.compute.amazonaws.com
ec2-184-169-240-136.us-west-1.compute.amazonaws.com 100%[======================================>] 16,519      --.-K/s   in 0.004s
ec2-184-169-240-136.us-west-1.compute.amazonaws.com
ec2-184-169-240-136.us-west-1.compute.amazonaws.com
ec2-184-169-240-136.us-west-1.compute.amazonaws.com 2014-09-09 17:05:54 (3.75 MB/s) - written to stdout [16519/16519]
ec2-184-169-240-136.us-west-1.compute.amazonaws.com
ec2-184-169-240-136.us-west-1.compute.amazonaws.com Downloading Chef 11.6.2 for ubuntu...
ec2-184-169-240-136.us-west-1.compute.amazonaws.com downloading https://www.opscode.com/chef/metadata?v=11.6.2&prerelease=false&nightlies=false&p=ubuntu&pv=12.04&m=x86_64
ec2-184-169-240-136.us-west-1.compute.amazonaws.com   to file /tmp/install.sh.27064/metadata.txt
ec2-184-169-240-136.us-west-1.compute.amazonaws.com trying wget...
ec2-184-169-240-136.us-west-1.compute.amazonaws.com url	https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef_11.6.2-1.ubuntu.12.04_amd64.deb
ec2-184-169-240-136.us-west-1.compute.amazonaws.com md5	a809b8cfeaea71c20c0de0e492c7f86f
ec2-184-169-240-136.us-west-1.compute.amazonaws.com sha256	74d5283b597299efbff3c66897c79876cc11aade6dc8810ddf38101526203651
ec2-184-169-240-136.us-west-1.compute.amazonaws.com downloaded metadata file looks valid...
ec2-184-169-240-136.us-west-1.compute.amazonaws.com downloading https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef_11.6.2-1.ubuntu.12.04_amd64.deb
ec2-184-169-240-136.us-west-1.compute.amazonaws.com   to file /tmp/install.sh.27064/chef_11.6.2-1.ubuntu.12.04_amd64.deb
ec2-184-169-240-136.us-west-1.compute.amazonaws.com trying wget...
ec2-184-169-240-136.us-west-1.compute.amazonaws.com Comparing checksum with sha256sum...
ec2-184-169-240-136.us-west-1.compute.amazonaws.com Installing Chef 11.6.2
ec2-184-169-240-136.us-west-1.compute.amazonaws.com installing with dpkg...
ec2-184-169-240-136.us-west-1.compute.amazonaws.com (Reading database ...
(Reading database ... 5%est-1.compute.amazonaws.com
(Reading database ... 10%st-1.compute.amazonaws.com
(Reading database ... 15%st-1.compute.amazonaws.com
(Reading database ... 20%st-1.compute.amazonaws.com
(Reading database ... 25%st-1.compute.amazonaws.com
(Reading database ... 30%st-1.compute.amazonaws.com
(Reading database ... 35%st-1.compute.amazonaws.com
(Reading database ... 40%st-1.compute.amazonaws.com
(Reading database ... 45%st-1.compute.amazonaws.com
(Reading database ... 50%st-1.compute.amazonaws.com
(Reading database ... 55%st-1.compute.amazonaws.com
(Reading database ... 60%st-1.compute.amazonaws.com
(Reading database ... 65%st-1.compute.amazonaws.com
(Reading database ... 70%st-1.compute.amazonaws.com
(Reading database ... 75%st-1.compute.amazonaws.com
(Reading database ... 80%st-1.compute.amazonaws.com
(Reading database ... 85%st-1.compute.amazonaws.com
(Reading database ... 90%st-1.compute.amazonaws.com
(Reading database ... 95%st-1.compute.amazonaws.com
(Reading database ... 116591 files and directories currently installed.)
ec2-184-169-240-136.us-west-1.compute.amazonaws.com Preparing to replace chef 10.18.2-2 (using .../chef_11.6.2-1.ubuntu.12.04_amd64.deb) ...
ec2-184-169-240-136.us-west-1.compute.amazonaws.com invoke-rc.d: initscript chef-client, action "stop" failed.
ec2-184-169-240-136.us-west-1.compute.amazonaws.com dpkg: warning: subprocess old pre-removal script returned error exit status 1
ec2-184-169-240-136.us-west-1.compute.amazonaws.com dpkg - trying script from the new package instead ...
ec2-184-169-240-136.us-west-1.compute.amazonaws.com dpkg: error processing /tmp/install.sh.27064/chef_11.6.2-1.ubuntu.12.04_amd64.deb (--install):
ec2-184-169-240-136.us-west-1.compute.amazonaws.com  there is no script in the new version of the package - giving up
ec2-184-169-240-136.us-west-1.compute.amazonaws.com invoke-rc.d: initscript chef-client, action "start" failed.
ec2-184-169-240-136.us-west-1.compute.amazonaws.com dpkg: error while cleaning up:
ec2-184-169-240-136.us-west-1.compute.amazonaws.com  subprocess installed post-installation script returned error exit status 1
ec2-184-169-240-136.us-west-1.compute.amazonaws.com Errors were encountered while processing:
ec2-184-169-240-136.us-west-1.compute.amazonaws.com  /tmp/install.sh.27064/chef_11.6.2-1.ubuntu.12.04_amd64.deb
ec2-184-169-240-136.us-west-1.compute.amazonaws.com Installation failed
ec2-184-169-240-136.us-west-1.compute.amazonaws.com Please file a bug report at http://tickets.opscode.com
ec2-184-169-240-136.us-west-1.compute.amazonaws.com Project: Chef
ec2-184-169-240-136.us-west-1.compute.amazonaws.com Component: Packages
ec2-184-169-240-136.us-west-1.compute.amazonaws.com Label: Omnibus
ec2-184-169-240-136.us-west-1.compute.amazonaws.com Version: 11.6.2
ec2-184-169-240-136.us-west-1.compute.amazonaws.com
ec2-184-169-240-136.us-west-1.compute.amazonaws.com Please detail your operating system type, version and any other relevant details
ec2-184-169-240-136.us-west-1.compute.amazonaws.com bash: line 74: chef-client: command not found

**Comment by lamont-granquist** [comment]
Looking at the error message that you're getting again, you're trying to replace a very old non-omnibus system package of 'chef' with an omnibus-chef package.  I'm not surprised that it doesn't work.  I also got nothing.  I hope you've figured something out.

**Comment by btm** [comment]
A quick google search recommends running ```dpkg --configure -a``` to fix that error coming from apt-get (then reboot?), after which you should be able to remove the old debian platform version of the chef pacakge. After which you should be able to install a fresh omnibus chef package.
