### ISSUE TITLE
First run of dsc_script will fail if powershell 4.0 is not installed

### ISSUE THREAD

**Issue by adamedx** [chef/chef#2027]
@jdmundrawala, a quick fix might be to move this detection to execution phase rather than compile:
http://www.getchef.com/blog/2014/09/08/chef-11-16-gets-into-powershell-dsc/#comment-1582426718. 

See this comment:
Regarding dsc_script and the Powershell 4 requirement, it seems that on a vanilla 2008 machine (no PS4) this presents a problem using this in the very first run; even if the very first recipe in the run list is the installation of PS4, if any other recipe contains the usage of dsc_script, the compile phase will break with the message 'Powershell 4.0 or higher
was not detected on your system and is required to use the dsc_script resource' thus preventing the installation of PS4, thus preventing from ever finishing the run.

**Comment by lamont-granquist** [comment]
looks fixed.
