### ISSUE TITLE
Upstart provider should disable services using override files on 1.3 or later

### ISSUE THREAD

**Issue by jtimberman** [chef/chef#2034]
Via [CHEF-3624](https://tickets.opscode.com/browse/CHEF-3624)

The Upstart provider (Chef::Provider::Service::Upstart) doesn't disable Upstart services properly if upstart >= 1.3 is installed.

The prescribed way to do this is to to create a file called /etc/init/<service>.manual with the content "manual" in it.

Source: http://upstart.ubuntu.com/cookbook/#override-files

This is a bit more robust than modifying the /etc/init/<service> file in place.
### Comments

> Stephan Renatus added a comment - 08/Aug/13 8:01 AM
> Please note that the current implementation can lead to unexpected behavior when an override file is present, since the upstart provider only checks its own way of handling enabling/disabling services: https://github.com/opscode/chef/blob/master/lib/chef/provider/service/upstart.rb#L120
> Unfortunately, there seem to be three^Wfour ways of disabling a service,
> "Chef's way", commenting "start on"
> adding "manual" to the service.conf file
> creating a service.override file with the content "manual"
> deleting the service.conf
> which complicates this issue...
> 
> Dan Razzel added a comment - 27/Sep/13 6:00 PM
> "Chef's way", commenting "start on" naively assumes that this stanza is a single line. (Being misled by published instructions: http://upstart.ubuntu.com/cookbook/#disabling-a-job-from-automatically-starting.)
> We're hitting this with the avahi-daemon package which uses a multiline "start on". Multiline format is permitted when the events are enclosed in parentheses (http://upstart.ubuntu.com/cookbook/#start-on.)

**Comment by tas50** [comment]
I'm going to close this out since we 99.9% won't be making any major improvements to Upstart at this point. Ubuntu 14.04 goes EOL soon and at that point Upstart becomes more of a historical artifact than a thing we actively maintain support for.
