### ISSUE TITLE
chef-full.erb bootstrap template only supports bash

### ISSUE THREAD

**Issue by mike-pt** [chef/chef#2037]
ec2ip.compute-1.amazonaws.com Installing Chef Client... ec2ip.compute-1.amazonaws.com bash: /dev/fd/63: No such file or directory 
ec2-ip-compute-1.amazonaws.com Starting first Chef Client run... 
ec2ip.compute-1.amazonaws.com bash: line 94: chef-client: command not found

Most likely related with the use of bash <(...)

Also I would like to suggest that maybe sh should b used instead of bash, for example FreeBSD doesn't ship with batch in a fesh install.

**Comment by chris-rock** [comment]
+1 this is annoying on AIX, see #2836

**Comment by juliandunn** [comment]
@chris-rock if you can help, it'd be great -- looks like all the work has been done in https://github.com/chef/chef/issues/2037#issuecomment-57401663; just need to steal some of the shell functions from there.

**Comment by chris-rock** [comment]
@juliandunn your fix for install.sh is working great, I used it for installing chef client. I just figured out, that knife is missing the option to use sh

**Comment by lamont-granquist** [comment]
merged to master, so closing (should go in 12.4.0)
