### ISSUE TITLE
Permission denied to script file in TMPDIR

### ISSUE THREAD

**Issue by brauliobo** [chef/chef#2050]
The `script` resource doesn't check if file is really accessible by the specified `user`. For example, if the system uses the pattern `/tmp/user/<uid>/` for `TMPDIR` (used by ruby's `Tempfile`), then the file won't be accessible as the parent directories aren't accessible (`/tmp/user` and `/tmp/user/<uid>`). It works when `TMPDIR` is `/tmp` because it is accessible to all users.

http://lists.opscode.com/sympa/arc/chef/2014-09/msg00118.html
    
Workaround: use `ENV['TMPDIR'] = '/tmp'` on `client.rb` or `solo.rb`

    ================================================================================
    Error executing action `run` on resource 'rvm_shell[noosfero-bundle-install]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    script[noosfero-bundle-install] (/home/braulio/chef-solo/cookbooks-2/rvm/providers/shell.rb line 75) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '126'
    ---- Begin output of "bash"  "/tmp/user/1000/chef-script20140806-8138-15wlsi2" ----
    STDOUT: 
    STDERR: bash: /tmp/user/1000/chef-script20140806-8138-15wlsi2: Permission denied
    ---- End output of "bash"  "/tmp/user/1000/chef-script20140806-8138-15wlsi2" ----
    Ran "bash"  "/tmp/user/1000/chef-script20140806-8138-15wlsi2" returned 126
    
    Cookbook Trace:
    ---------------
    /home/braulio/chef-solo/cookbooks-2/rvm/providers/shell.rb:98:in `script_wrapper'
    /home/braulio/chef-solo/cookbooks-2/rvm/providers/shell.rb:46:in `block in class_from_file'

**Comment by axos88** [comment]
Damn it, i lost about 3 hours hunting down this. Please validate presence and throw a meaningful error asap.

**Comment by lamont-granquist** [comment]
Since 12.1.0 Chef throws warning messages now:

https://github.com/chef/chef/commit/1b3705ca383b64092c9ef54d7e46201fab6271c7

**Comment by wildinstinct** [comment]
Hi all, i face the same issue while i tried to remove the file inside bash resource

ls -lart /tmp/stage/artifacts/XYZ.jar 
-rwxrwxrwx 1 root root 12425 Jul 22 09:56 /tmp/stage/artifacts/XYZ.jar

I am also not able to delete the file from non tmp directory.

Could some one help me to resolve it
