### ISSUE TITLE
Customers would like Windows "user" resource to gracefully handle existing groups

### ISSUE THREAD

**Issue by sean-horn** [chef/chef#2056]
ZenDesk 900: Customers would like Windows "user" resource to gracefully handle existing groups

Running the "user" resource on windows with a defined group attribute against an already existing group results in a chef-client failure.

**Comment by smurawski** [comment]
@sean-horn This should be resolved with the aforementioned update.  If this is still an issue, please reopen with a repro for the issue that you are seeing.  Thanks!
