### ISSUE TITLE
Provide more helpful error message when accidentally using --secret instead of --secret-file

### ISSUE THREAD

**Issue by sparr** [chef/chef#2113]
### Version:
11.16.2

### Environment:
non-specific

### Scenario:
trying to show/edit an encrypted data bag from the command line

### Steps to Reproduce:
`knife data bag show foo bar --secret /etc/chef/encrypted_data_bag_secret`

### Expected Result:
successful decryption using secret from the indicated file, or at least a helpful error message reminding me to use --secret-file instead of --secret

### Actual Result:
`ERROR: Chef::EncryptedDataBagItem::DecryptionFailure: Error decrypting data bag value: 'bad decrypt'. Most likely the provided key is incorrect`

**Comment by dansteen** [comment]
I've created:
https://github.com/chef/chef/pull/3183
for this issue

**Comment by rileyrileyrose** [comment]
The PR for this is still open -- does this issue still need to be addressed?

**Comment by dansteen** [comment]
Yes.  I've adjusted the PR per Lamont and smurawski.

**Comment by tyler-ball** [comment]
Closed by merging https://github.com/chef/chef/pull/3183
