### ISSUE TITLE
could not create server using chef

### ISSUE THREAD

**Issue by thdotnet** [chef/chef#2121]
I'm new with Chef and I'm trying to create a new server on Azure running Windows.

I've followed your quick tutorial in here :https://github.com/opscode/knife-azure but I'm getting the following error, what I'm doing wrongly?:

C:\chef>knife azure server create --azure-dns-name 'thchef1' --azure-vm-size Medium --azure-source-image 8fcc3d_Win2012-amd64-30GB --azure-service-location 'West US' --winrm-user myuser --winrm-password 'mypassword' --bootstrap-protocol winrm --distro 'windows-chef-client-msi' -VV
INFO: validating...
INFO: creating...
INFO: calling get hostedservices/thchef1 synchronously
.DEBUG: <?xml version="1.0"?>
<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
  <Code>ResourceNotFound</Code>
  <Message>The hosted service does not exist.</Message>
</Error>

WARN: ResourceNotFound : The hosted service does not exist.
WARN: Unable to find hosted(cloud) service:ResourceNotFound : The hosted service does not exist.
INFO: calling get storageservices synchronously
.INFO: calling get images synchronously
.ERROR: Invalid image. Use the command "knife azure image list" to verify the im
age name
ERROR: Failed to create the server -- exception being rescued: exit
DEBUG: SystemExit: exit
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/knife-azure-1.3.0/lib/chef/
knife/azure_base.rb:76:in `exit'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/knife-azure-1.3.0/lib/chef/
knife/azure_base.rb:76:in `is_image_windows?'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/knife-azure-1.3.0/lib/chef/
knife/azure_server_create.rb:676:in `create_server_def'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/knife-azure-1.3.0/lib/chef/
knife/azure_server_create.rb:476:in `run'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/chef-11.16.2-x86-mingw32/li
b/chef/knife.rb:493:in `run_with_pretty_exceptions'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/chef-11.16.2-x86-mingw32/li
b/chef/knife.rb:174:in `run'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/chef-11.16.2-x86-mingw32/li
b/chef/application/knife.rb:139:in `run'
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/chef-11.16.2-x86-mingw32/bi
n/knife:25:in `<top (required)>'
C:/RailsInstaller/Ruby1.9.3/bin/knife:23:in `load'
C:/RailsInstaller/Ruby1.9.3/bin/knife:23:in `<main>'
WARNING: Cleaning up resources...
INFO: calling get hostedservices/thchef1 synchronously
.DEBUG: <?xml version="1.0"?>
<Error xmlns="http://schemas.microsoft.com/windowsazure" xmlns:i="http://www.w3.
org/2001/XMLSchema-instance">
  <Code>ResourceNotFound</Code>
  <Message>The hosted service does not exist.</Message>
</Error>

WARN: ResourceNotFound : The hosted service does not exist.
WARN: Unable to find hosted(cloud) service:ResourceNotFound : The hosted service
 does not exist.
C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/knife-azure-1.3.0/lib/chef/
knife/azure_server_create.rb:767:in `cleanup_and_exit': undefined method `conten
t' for nil:NilClass (NoMethodError)
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/knife-azure-1.
3.0/lib/chef/knife/azure_server_create.rb:483:in `rescue in run'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/knife-azure-1.
3.0/lib/chef/knife/azure_server_create.rb:475:in `run'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/chef-11.16.2-x
86-mingw32/lib/chef/knife.rb:493:in `run_with_pretty_exceptions'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/chef-11.16.2-x
86-mingw32/lib/chef/knife.rb:174:in `run'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/chef-11.16.2-x
86-mingw32/lib/chef/application/knife.rb:139:in `run'
        from C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/chef-11.16.2-x
86-mingw32/bin/knife:25:in `<top (required)>'
        from C:/RailsInstaller/Ruby1.9.3/bin/knife:23:in `load'
        from C:/RailsInstaller/Ruby1.9.3/bin/knife:23:in `<main>'

**Comment by adamedx** [comment]
This was really an issue for a different repository which eventually got filed here: https://github.com/chef/knife-azure/issues/161.
