### ISSUE TITLE
Ohai output is not reflected in the Chef output during chef-solo runs

### ISSUE THREAD

**Issue by sersut** [chef/chef#2145]
While debugging with @curiositycasualty we've discovered that with this config file:

```
log_level :debug
Ohai::Config[:log_level] = :debug
```

we can see the Ohai output during local mode runs like this:

`chef-client -z -c .chef/client.rb -o ""`

whereas we can't see Output with chef-solo:

`chef-solo -c .chef/client.rb`

**Comment by curiositycasualty** [comment]
Oh boy, ancient history now eh @lamont-granquist ?
