### ISSUE TITLE
Sequential cookbook file downloads in local-mode?

### ISSUE THREAD

**Issue by JeanMertz** [chef/chef#2150]
I'm using local-mode to setup a machine image using www.packer.io.

I'm also using the ([pending upload][]) [transip cookbook][] to work with the www.transip.eu API. This cookbook has some gems vendored inside its cookbook files folder. When running `chef-client --local-mode`, I am seeing the message `Storing updated cookbooks/transip/files/*` sequentially and very-slowly appearing in the log output.

In the end, it takes more than an hour to download the vendored gems and as far as I can tell, no parallelization is happening. Of course, the files are present on the system, so a `cp` would suffice, but I guess Chef is trying to keep `--local-mode` as close to the normal `chef-client` functionality as possible, and thus files are transferred from one place on the drive to another, using a locally running web API.

This is slow, but I can understand the reasoning behind this. However, the fact that the downloads aren't happening in parallel surprised me.

Is this expected behaviour?

```
$ chef-client --version
Chef: 11.16.2
```

[pending upload]: https://github.com/opscode/chef/issues/2149
[transip cookbook]: https://github.com/kabisa-cookbooks/transip

**Comment by lamont-granquist** [comment]
Yeah as of now I think `chef_gem` is better than seth's approach.
