### ISSUE TITLE
Can't disable status check for redhat init service

### ISSUE THREAD

**Issue by issacg** [chef/chef#2168]
I seem to be running into an odd issue on creating services for RedHat (specifically, CentOS 6.4+ and Amazon Linux)

Given a simple template for a chkconfig-aware service, and a "service" block, the behavior observed is that the service is enabled on start runlevels, but not on the stop runlevels, nor is the service "started" at converge time, but rather only on reboot time.

Testing the same recipe on Ubuntu worked as expected (enabled in start and stop runlevels + run on converge)

```
#!/bin/bash
# chkconfig: 2345 90 10
# desription: test script

. /etc/init.d/functions
my_log="/var/log/testmememe.log"

case "$1" in
        stop)
	echo "STOPPED" >> "$my_log"
	echo "OK"
        ;;
        start)
	echo "STARTED" >> "$my_log"
	echo "OK"
        ;;
*)
        echo $"Usage: $0 {start|stop}"
        exit
esac
```

```
# init.d template
template "/etc/init.d/test" do
  source "test.erb"
  mode 0755
end

service "test" do
   supports :start => true, :stop => true, :restart => false
   priority 90
   action [:enable, :start]
end
```

After converging ```/var/log/testmememe``` does not exist.  After reboot, it contains the single word "STARTED"

Issuing ```chkconfig --add test``` on a converged machine does add the service to stop runlevels.

**Comment by jespada** [comment]
Any idea if someone is already working on this?

**Comment by smurawski** [comment]
https://github.com/chef/chef/pull/1120 covers this issue.

**Comment by lamont-granquist** [comment]
This is one of three problems with the RedHat service provider:

- #1120 is for adding an `:add` action
- #3793 to add run_levels property to the resource
- this one to allow overriding the supports[:status]
