### ISSUE TITLE
 Encrypted cookbook_file resource

### ISSUE THREAD

**Issue by idea360** [chef/chef#2176]
Request to support encryption in the cookbook_file resource similar to data bags resources. The same 'encrypted_data_bag_secret' default should be shared between the resources so that the cookbook_file resource defaults to '/etc/chef/encrypted_data_bag_secret'.

The issues stems from that data bags are global to the Chef Server, and there is no way to limit their scope. Having this would give the ability to limit the scope of files, passwords, keys, etc... where it doesn't make sense to share them globally, but these files still must be encrypted and in source control.

**Comment by smurawski** [comment]
Closing due to no further update as to context for the feature.
