### ISSUE TITLE
dsc_script `code` (code-attribute usage) does not support (e.g.) Resource Kit DSC resources

### ISSUE THREAD

**Issue by bheuvel** [chef/chef#2195]
dsc_script `code` (code-attribute usage) does not support (e.g.) Resource Kit DSC resources

When using DSC resources which are not present by default, such as the DSC Resource Kit Waves, within the code attribute, LCM gives back errors. E.g. when using xADDomain:
```
ERROR: DSC operation failed: Powershell Cmdlet failed: PSDesiredStateConfiguration\node :
The term 'xADDomain' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that
the path is correct and try again.
```

Reason for this is that the respective module needs to be imported into the LCM session, by using the keyword `Import-DscResource`.

* This keyword is only allowed at a specific scope within the DSC Configuration, namely outside/before the `node` definition.
* Unfortunately dsc_script places the code contained in the `code` attribute, WITHIN a `node` definition

The ConfigurationGenerator ([configuration_generator.rb#L84, Chef 11.16.0] (https://github.com/opscode/chef/blob/11.16.0/lib/chef/util/dsc/configuration_generator.rb#L84)) uses the following code (I inserted 'illegal' linebreaks here for clarification of scope, and comment lines starting with '# BvdH'):
```
def configuration_code(code, configuration_name)
    "$ProgressPreference = 'SilentlyContinue';Configuration '#{configuration_name}'
    {
        # BvdH: Import-DscResource should be inserted here
        node 'localhost'
        {
            # BvdH: Import-DscResource is not allowed here, within this node scope and therefore cannot be included in the code attribute
            #{code}
        }
    }
    "
end
```

Possible solution could be to leave out the `localhost` definition, which MAY require the user to implement this within the `code` attribute, but will also allow usage of the `Import-DscResource` keyword in the `code` attribute.

Without this functionality, the code attribute is basically only usable for the (about) 12 natively provided resources, instead of the (about) 80 resources in the DSC Resource Kit Wave 7.

Leaving out the `localhost` definition will also make the `code` and `command` attribute behave more similar; providing, or complete control, DSC script code.

Alternative solution might be to use a separate attribute which needs to list the required/used DSC modules, which would then be inserted before the `localhost` block. This would be somewhat similar to what dsc_rource does ([dsc_provider.rb#L106](https://github.com/opscode-cookbooks/dsc/blob/master/libraries/dsc_provider.rb#L106)), but as dsc_resource takes a specific named (`resource_name`) DSC resource, the required import-code is relatively easily and automatically generated ([dsc_provider.rb#L119](https://github.com/opscode-cookbooks/dsc/blob/master/libraries/dsc_provider.rb#L119)). In this case the entire code would need to be parsed and analyzed for DSC resources.

In the end, dsc_script CAN off course be used with (e.g.) DSC Resource Kit Waves provided resources, but requires usage of (creation of) an external file. This could be a cookbook file, but would rather see this "enabled" for the (inline) code attribute.

Or perhaps I overlooked something?

**Comment by bheuvel** [comment]
Should be solved by implementation of @jdmundrawala   [#2779](https://github.com/opscode/chef/pull/2779). Cool!

**Comment by aarsan** [comment]
I'm running 12.2.1 and am unable to use the resources provided in wave 10 (The term 'xFailOverCluster\xCluster' is not recognized). I see this was merged to master but does that mean it's in 12.2.1?

**Comment by jdmundrawala** [comment]
@aarsan can you post the resource and any log output you get

**Comment by JackChance** [comment]
Similar issue to Aarsan.

Example is using 'imports' in the dsc_script call, but when Import-DSCResource -ModuleName xFailOverCluster is used in the .erb file itself Chef doesn't recognize the .erb syntax and throws an error on 'Configuration'.

Chef client 12.3.0 

dsc_script 'create_cluster' do
  imports 'xFailOverCluster'
  command create_cluster
end



Configuration create_cluster
{

  xCluster ensureCreated
  {
    Name = <%= @cluster_name %>
    StaticIPAddress = <%= @cluster_ip %>
    DomainAdministratorCredential = $creds

    DependsOn = "[WindowsFeature]RSATClusteringCmdInterface"
  }
  xWaitForCluster waitForCluster
  {
    Name = <% @cluster_name %>
    RetryIntervalSec = 10
    RetryCount = 60

    DependsOn = "[WindowsFeature]RSATClusteringCmdInterface"
  }
  xCluster joinCluster
  {
    Name = <%= @cluster_name %>
    StaticIPAddress = <%= @cluster_ip %>
  }
  $user = <%= @user %>
  $pass = <%= @pass %>
  $creds = New-Object -TypeName System.Management.Automation.PSCredential -argumentlist $user,($pass | ConvertTo-SecureString)
}


        ================================================================================
        Error executing action `run` on resource 'dsc_script[create_cluster]'
        ================================================================================

        Chef::Exceptions::PowershellCmdletException
        -------------------------------------------
        Powershell Cmdlet failed: trap [Exception] {write-error -exception ($_.Exception.Message);exit 1};.
        '/create_cluster.ps1';create_cluster -outputpath 'C:/Users/vagrant/AppData/Loca
        l/Temp/chef-dsc-script20150507-2656-h8ngum/create_cluster'  4>
        'C:/Users/vagrant/AppData/Local/Temp/verbose20150507-2656-fj555o';if ( ! $? )
        { exit 1 } : At C:\create_cluster.ps1:4 char:3
        +   xCluster ensureCreated
        +   ~~~~~~~~
        Undefined DSC resource 'xCluster'. Use Import-DSCResource to import the
        resource.
        At C:\create_cluster.ps1:12 char:3
        +   xWaitForCluster waitForCluster
        +   ~~~~~~~~~~~~~~~
        Undefined DSC resource 'xWaitForCluster'. Use Import-DSCResource to import the
        resource.
        At C:\create_cluster.ps1:20 char:3
        +   xCluster joinCluster
        +   ~~~~~~~~
        Undefined DSC resource 'xCluster'. Use Import-DSCResource to import the
        resource.
     + CategoryInfo          : NotSpecified: (:) [Write-Error], Exception
     + FullyQualifiedErrorId : System.Exception

**Comment by smurawski** [comment]
@JackChance ```imports``` only works with the code attribute, not the command attribute.  If you are supplying the command via a template you are generating, you are responsible for adding the import-dscresource statements.  I filed https://github.com/chef/chef-docs/issues/595 to update the docs to mention this.
