### ISSUE TITLE
Chef::Resource.attribute should raise if the method already exists

### ISSUE THREAD

**Issue by mfischer-zd** [chef/chef#2219]
If I compose a new resource type ("widget") using a LWRP like this:

```
attribute :id, :type => String, :name_attribute => true
attribute :name, :type => String
```

If I then declare a resource using this new provider:

```
widget "foo" do
  name "sue"
end
```

Expected result: in the provider, `new_resource.id == "foo"` and `new_resource.name == "sue"`. 

Actual result: in the provider, `new_resource.id == "foo"` and `new_resource.name == "foo"`.

**Comment by lamont-granquist** [comment]
I'm going to narrow the scope of this down to something that could actually get done.   When defining resource parameters in the LWRP DSL we can raise if the resource already `respond_to?` the new parameter.  We can't rename `name` to `_name` or do much to really fix the problem because that would be a (massively) breaking API change to every bit of code that expected resource.name to be the name.  But we could raise and give the user better feedback.

**Comment by mfischer-zd** [comment]
I don't understand why this would be a breaking change.  `resource.name` *should* return the name.  However, it should not necessarily return the attribute called "name," as you've make it clear from Day One that they are not identical.

**Comment by tas50** [comment]
With the changes in Chef 14 to require referencing property by new_resource.property_name we can probably close this out at this point. The potential for collision is gone.

**Comment by coderanger** [comment]
@tas50 It can still come up if you try to define a property with the same name as an existing resource method, though that fortunately doesn't come much outside of some weird cases.

**Comment by lamont-granquist** [comment]
it is better, but you can still scribble over methods on Chef::Resource that aren't properties and cause all kinds of chaos.

`property :node` would probably produce fun results.

`property :resources` might break notifications.

`property :action` would hoze the world.

subscribes, notifies, not_if/only_if, none of those are implemented as properties.

`property :inspect` or if anyone thought `property :as_json` or `property :to_json` were good ideas for some reason...

**Comment by lamont-granquist** [comment]
```
ArgumentError
-------------
Property `node` of resource `` overwrites an existing method. A different name should be used for this property.
```

at some point we fixed this.  unsure when, but closing.
