### ISSUE TITLE
considering making "include" part of recipe DSL

### ISSUE THREAD

**Issue by juliandunn** [chef/chef#2234]
A lot of people get trolled by the fact that Chef recipes look like regular Ruby, so they think they can just do things like:

``` ruby
include Opscode::OpenSSL::Password
```

to mixin modules. But of course that doesn't work, 'cause `include` isn't part of the DSL. Thus users have to dive into ugly Ruby metaprogramming, with syntax like:

``` ruby
::Chef::Recipe.send(:include, Opscode::OpenSSL::Password)
```

to effectively monkeypatch the Recipe class to mixin the module.

It gets even gnarlier if they want `ruby_block` to mixin modules; now they need to know the provider class:

``` ruby
Chef::Provider::RubyBlock.send(:include, Some::Thingy)
```

Is there a way we could make the user experience better? Say, by making `include` part of the DSL? Other ideas?

**Comment by lamont-granquist** [comment]
`not_if` blocks are evaluated in the context of the Chef::Resource::Whatever object so its reasonable that people would want that as well.  There should probably be an easy way to mixin to Chef::Recipe, Chef::Resource and Chef::Provider all in one go, although that's a rather large footgun.

Something like:

`use Opscode::OpenSSL::Password, in_resource: :ruby_block`

Could be used to wire up to the resource and provider that :ruby_block evaluates to, but with service providers that'd be problematic to determine.  Could also take a class name and something like :all_resources to engage the full footgun mode....

**Comment by ranjib** [comment]
i love it :-). may be use 
```ruby
use Foo::Bar
```
for inclusion in all resources & recipes. and 
```ruby
use Foo::Bar, in: :ruby_block, :execute
```
if user want to mixin their module only in one resource, they can do it directly, without `use` DSL
```ruby
ruby_block 'mixin_demo' do
  exten Foo::Bar
  block do
  end
end
```
we can a generic middle ware API for these mixins using the top level Chef.* DSL methods.

**Comment by lamont-granquist** [comment]
I'd probably want `use Foo::Bar` to only hit the recipe DSL.  For the footgun I think you should have to type a bit more.  Its pretty dangerous because if you collide with any internal method names or collide with any properites of any Resources or LWRPs then you may get very odd behavior, and you may see that odd behavior very distant from where you launched the footgun at.

**Comment by lamont-granquist** [comment]
per discussion in #4674 we probably want to be more targeted with this.  so by default `use Foo::Bar` should ideally only infect the instance of the object of the current DSL context.

so:

```
use Opscode::OpenSSL::Password
node['whatever'] = random_password
```

would not inject `random_password` into other recipes.  global inclusion across the board should be handled in library files and not by the end user writing recipe code (i.e. the openssl cookbook should inject its methods into the global DSL if it wants to do that and not pass the buck to the end user).

similarly for ruby_block would probably want it to get written like:

```ruby
ruby_block "whatever" do
  block do
    use Opscode::OpenSSL::Password
    puts random_password # wut security?
  end
end

ruby_block "boom" do
  block do
    random_password   # will raise
  end
end
```

means typing more and being more explicit, but avoids polluting resources in other cookbooks that are totally orthogonal.  and again it should be up to the cookbook that is offering the module, or something core like chef-sugar or chef-client itself to mix those methods in globally.

**Comment by lamont-granquist** [comment]
After https://github.com/chef/chef/pull/8243 the following all works:

```
Chef::DSL::Universal.send(:include, MyMethods)
Chef::DSL::Core.send(:include, MyMethods)
Chef::DSL::Recipe.send(:include, MyMethods)
```

One of those is probably the correct thing for injecting methods into DSLs.  The DSL file have large comment banners explaining their usage.

```
Chef::Resource::RubyBlock.send(:include, MyMethods)
```

Remains the correct way to inject methods only into one resource.

Due to lack of interest in creating DSL helper methods, I'm closing this.
