### ISSUE TITLE
Env resource implementation and documentation inconsistent

### ISSUE THREAD

**Issue by jdmundrawala** [chef/chef#2262]
## Version:
master

## Scenario
When using the :modify action, https://docs.getchef.com/resource_env.html says that the path is appended. This is not aligned with the implementation:
```ruby
      def modify_env
        if @new_resource.delim
          #e.g. add to PATH
          @new_resource.value(@new_resource.value + @new_resource.delim + @current_resource.value)
        end
        create_env
      end
```
where the new value is being prepended.

## Expected
The documentation should specify prepend. We should also provide a way the specify where to element should be added (beginning or end).

**Comment by thommay** [comment]
Closing in favour of chef/chef-docs#520
