### ISSUE TITLE
chef-server throws 500 at random searches

### ISSUE THREAD

**Issue by szymonpk** [chef/chef#2268]
chef-server open source 11.12.2 running at lxc on debian testing
chef-client 11.12.2 - 11.14.6

We're getting 500 at random searches, I'm not sure origin of the issue. I've gather some debug data:

    # from client side
    DEBUG: Net::HTTPFatalError: 500 "Internal Server Error" /usr/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'

    # from nginx logs on chef-server
     "GET /search/node?q=recipes:fluentd_server&sort=X_CHEF_id_CHEF_X%20asc&start=0&rows=1000 HTTP/1.1" 500 "7.018" 36 "-" "Chef Client/11.12.8 (ruby-2.1.3-p242; ohai-7.0.4; x86_64-linux-gnu; +http://opscode.com)" "127.0.0.1:8000" "500" "7.018" "11.12.8" "algorithm=sha1;version=1.0;" "appserver.hostname" "2014-10-16T09:42:29Z" "2jmj7l5rSw0yVb/vlWAYkK/YBwk=" 1091

    # logs from erchef/log/crash.log
    https://gist.github.com/szymonpk/142560761ea968570f79

Looks like issue with pg connection, however postgres log is clean. We're not reaching any conn limit. Re-run chef-client right after failure always helps.

**Comment by lamont-granquist** [comment]
If you can get a repro please file a bug against chef-server
