### ISSUE TITLE
Incorrect User already exists ERROR

### ISSUE THREAD

**Issue by alexpop** [chef/chef#2278]
When trying to create two different users using the same email address, the error message complains about a duplicate username. For example:

```bash
[root@ip-172-31-2-113 ~]# chef-server-ctl user-create alex My Name alex@example.com aaa
-----BEGIN RSA PRIVATE KEY-----
...
[root@ip-172-31-2-113 ~]# chef-server-ctl user-create alextwo My Name alex@example.com aaa
ERROR: Conflict
Response: User 'alextwo' already exists
```
The error message is misleading and should specify that the email address is already used.

This is the behavior when I try to register a new user with an existing email in the Manage WEB UI. I get "This email is already in use"

Using server:
```bash
[root@ip-172-31-2-113 ~]# head -1 /opt/opscode/version-manifest.txt
chef-server 12.0.0-rc.5
```

**Comment by lamont-granquist** [comment]
Closing this in favor of moving this to the chef-server issues tracker.
