### ISSUE TITLE
11.16.4 Omnibus install on Windows = ruby not found

### ISSUE THREAD

**Issue by jblaine** [chef/chef#2291]
Between 11.12.2 (worked) and 11.16.4 (fails), someone modified the code somewhere (I'm assuming) that generates (?) the C:\opscode\chef\bin\*.bat files so that only

```
@"ruby.exe" ... args ...
```

is called instead of something like the following found in your UNIX/Linux-land builds:

```
@"C:\opscode\chef\embedded\bin\ruby.exe" ...args...
```

As a result, the 11.16.4 on Windows is a dead-end for us. After install, running `chef-client` fails to find Ruby.

To replicate:

1. Run the installer by hand in a cmd.exe with: `msiexec /qb /i chef-windows-11.16.4-1.windows.msi ADDLOCAL="ChefClientFeature"`
2. Then immediately try to run `chef-client` from that same cmd.exe.

**Comment by smurawski** [comment]
@jdmundrawala @jblaine Has this been resolved by the referenced pull request?

**Comment by jblaine** [comment]
Yes, no problems with 11.18.0-1 or 12.3.0-1 for us.
