### ISSUE TITLE
Chef-client buffers the log and spits out the log in the end of the recipe

### ISSUE THREAD

**Issue by medyagh** [chef/chef#2292]
The Chef client does not put out any log when I create a machine using vagrant until very end

I saw there was ticket for it in old platform and it is marked as solved but the issue is there for me so it is NOT solved.I have newest version of everything (chef-dk, chef-client, vagrant)

link to the old ticket : https://tickets.opscode.com/browse/CHEF-1777

```
==> default: Starting Chef Client, version 11.16.4

chef -v
Chef Development Kit Version: 0.3.0

vagrant -v
Vagrant 1.6.5
```

**Comment by lamont-granquist** [comment]
I'm pretty certain this got fixed and was actually a vagrant issue if i recall correctly.  Please reopen if my memory is bad.
