### ISSUE TITLE
windows_package installation shows "Run as" dialog

### ISSUE THREAD

**Issue by JGutierrezC** [chef/chef#2302]
Hello,

Im trying to install SmartBear through windows_package, however when it is executing the resource, a CMD prompt says "installing service", it closes, and then a "Run As" dialog shows, of course that dialog won't go anywhere except for a user intervention.

the error raised if i click on cancel (after waiting for a while) is:

```powershel
[2014-10-25T22:42:10+00:00] FATAL: Mixlib::ShellOut::CommandTimeout: windows_package[SmartBear TestExecute 9.31] (smartbear::testexecute line 61) had an error: Mixlib::ShellOut::CommandTimeout: command timed out:
---- Begin output of start "" /wait "C:\chef\cache\TestExecute\setup.exe" /s /sms ----
STDOUT:
STDERR:
---- End output of start "" /wait "C:\chef\cache\TestExecute\setup.exe" /s /sms ----
```

Is there any workaround for it?

Thanks in advance!

**Comment by lamont-granquist** [comment]
So if I'm reading correctly, @adamedx's advice was the fix to the issue?  If not, can you reopen with more information?

**Comment by JGutierrezC** [comment]
The issue was that wrong :installer_type value was used. Hope to helps someone else.
