### ISSUE TITLE
yum groupinstall

### ISSUE THREAD

**Issue by ror6ax** [chef/chef#2304]
Have found this on jira https://tickets.opscode.com/browse/CHEF-1392 in opened state.
Looks like it was not migrated here. 

Will have a look at it myself, but if anybody has valuable insights - feel free to guide the lost soul.

**Comment by smurawski** [comment]
Channeling @someara - Group installs are a tough thing to track because it is difficult to verify what is in the group versus what is currently installed on the box.

**Comment by ror6ax** [comment]
Do we necessary need to track? I can live without this functionality, just curious.

**Comment by smurawski** [comment]
@ror6ax I believe so.  Yum isn't my strong point, but @someara had some thoughts there - as this has come up a lot in the past.  He'll chime in on this thread at some point in the near future.

**Comment by docwhat** [comment]
From [CHEF-1392](https://tickets.opscode.com/browse/CHEF-1392) by Matthew Kent:

> I think the components are there for breaking this into it's own yum_group provider - there's a concept of installed and available groups, commands to install and remove them, even updating by running the install again.

I'm no yum expert, but that looks like enough.

**Comment by thenoid** [comment]
:+1: Anyone associated with this come up with a interim solution?

**Comment by lamont-granquist** [comment]
we have no plans to add this functionality to core in the near future, the cookbook looks like right solution here.  i'm going to close this since we're not planning on taking any action with it.
