### ISSUE TITLE
bash creates attribute vs. report handlers

### ISSUE THREAD

**Issue by petere** [chef/chef#2335]
### Version:
Chef Client, version 11.16.4

### Environment:
CentOS 6

### Scenario:
I have a resource that does:
```ruby
bash 'install_libevent' do
  code %(rpm -i #{Chef::Config[:file_cache_path]}/#{packages['libevent']})
  creates '/usr/lib64/libevent-2.0.so.5'
end
```
to install a previously downloaded RPM package.  This works, but the report handler (I use `chef/handler/mail`) reports that the resource `bash[install_libevent]` is updated on every run.  This can also be seen by the report

    Chef Client finished, 1/7 resources updated in xxx seconds

at the end of the run.

If I remove the `creates` and replace it with
```ruby
  not_if 'test -e /usr/lib64/libevent-2.0.so.5'
```
I get

    Chef Client finished, 0/6 resources updated in xxx seconds

and the report handler doesn't report it as updated anymore.

(The fact that it now reports 6 rather than 7 resources is an interesting side issue, but I just want the report handler to shut for now. ;-) )

(AFAICT, the `code` isn't actually run, so that part is working correctly.)

### Steps to Reproduce:
Take a simple resource such as
```ruby
bash "true" do
  creates '/etc/passwd'
end
```
and run it.  It will report as 1 resource updated.  It should report 0 resources updated, if the file already exists.

**Comment by lamont-granquist** [comment]
I think this is fixed by a patch I did to clean up the execute and script resources and I found this converge_by and removed it.  I haven't validated that the problem went away, but that would have certainly caused a problem and the converge_by is gone now.  Please reopen if you can reproduce the bug.
