### ISSUE TITLE
Resource execute rights problem

### ISSUE THREAD

**Issue by maoueh** [chef/chef#2342]
This might be a misunderstanding from my part, but the current behavior seems weird enough to justify a bug report.

### Version:
Chef: 11.16.4

### Environment:
CentOS 6.5 x86_64

### Scenario:
In the real case scenario, I run a command via the `execute` resource as user `git` and as group `git`. This command connects to a `redis` database via a socket. This socket has owner `redis` and group `redis` and the file permissions are `srwxrwx---` (0770).

The user `git` is a member of group `redis` so it has access to socket file. When I converge my node, it fails running the `execute` recipe saying permission denied on the socket file. However, when I log in as `git` and run the exact same command, it works.

### Steps to Reproduce:
I created a trimmed down recipe file that can be run using `chef-apply` to reproduce the problem. In this recipe, user `git` is renamed to `user1` (and group `user1`) while user `redis` is renamed to `user2` (and group `user2`).

```
# File recipe.rb
group "user1"
group "user2"

user "user1" do
  gid "user1"
end

user "user2" do
  gid "user2"
end

group "user1" do
  action :modify
  members ["user1"]
  append true
end

group "user2" do
  action :modify
  members ["user1", "user2"]
  append true
end

file "/tmp/testfile" do
  user "user2"
  group "user2"
  mode "0440"
end

execute "user1 reads file with owner user2 and group user2 with mode 0440" do
  command "cat /tmp/testfile"
  user "user1"
  group "user1"
end
```

Then simply run `chef-apply recipe.rb` as user root (so you can create required users and groups).

### Expected Result:
I would have expected the command to run successfully without a permission denied problem since it runs as user `user1`, `user1` is a member of group `user2` and file mode is `0440`.

### Actual Result:
A permission denied is instead encountered when applying the `recipe.rb` cookbook and the chef run fails. 

```
$ chef-apply recipe.rb
(output removed)

---- Begin output of cat /tmp/testfile ----
STDOUT:
STDERR: cat: /tmp/testfile: Permission denied
---- End output of cat /tmp/testfile ----
Ran cat /tmp/testfile returned 1
```

[Full output](https://gist.github.com/maoueh/5a21d106e13a6e6ba459)
[cat /var/chef/cache/chef-stacktrace.out](https://gist.github.com/maoueh/173f6b7af0b053bd1217)

Best regards,
Matt

**Comment by smurawski** [comment]
Part of this issue was moved to #87 and part to #2347, so I'm closing this issue.
