### ISSUE TITLE
undefined local variable or method `trusted_certs' 

### ISSUE THREAD

**Issue by jedipunkz** [chef/chef#2343]
I develop ruby code with chef such as.

<pre>
Chef::Config[:node_name] = $chef_node_name
Chef::Config[:client_key] = $chef_secret_key
Chef::Config[:validation_key] = $chef_validation_key
Chef::Config[:chef_server_url] = $chef_server_url

Chef::Config.from_file(File.expand_path('/root/helion/.chef/knife.rb'))
kb = Chef::Knife::Bootstrap.new
kb.name_args = [ipaddr]
kb.config[:ssh_user] = "root"
kb.config[:chef_node_name] = instancename
kb.config[:identity_file] = $ssh_secret_key
kb.config[:run_list] = "recipe[ntp]"
kb.config[:use_sudo] = false
kb.config[:template_file] = $chef_bootstrap_file
kb.run
</pre>

and I bootstraped the chef to some nodes. I got these error.

<pre>
Connecting to 10.0.0.182
(erubis):52:in `block in evaluate': undefined local variable or method `trusted_certs' for #<Chef::Knife::Core::BootstrapContext:0x00000002444d30> (NameError)
        from /usr/lib64/ruby/gems/2.1.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `instance_eval'
        from /usr/lib64/ruby/gems/2.1.0/gems/erubis-2.7.0/lib/erubis/evaluator.rb:74:in `evaluate'
        from /usr/lib64/ruby/gems/2.1.0/gems/chef-11.16.4/lib/chef/knife/bootstrap.rb:207:in `render_template'
        from /usr/lib64/ruby/gems/2.1.0/gems/chef-11.16.4/lib/chef/knife/bootstrap.rb:275:in `ssh_command'
        from /usr/lib64/ruby/gems/2.1.0/gems/chef-11.16.4/lib/chef/knife/bootstrap.rb:254:in `knife_ssh'
        from /usr/lib64/ruby/gems/2.1.0/gems/chef-11.16.4/lib/chef/knife/bootstrap.rb:227:in `run'
        from chef.rb:64:in `chef_create_node'
        from chef.rb:109:in `<main>'
</pre>

my knife.rb includes these lines.

<pre>
ssl_verify_mode :verify_peer
verify_api_cert         true
</pre>

and I have no /etc/chef/trusted_certs dir. because I use Hosted Chef Server.

any idea ?

Thanks.

**Comment by smurawski** [comment]
This is resolved in Chef 12, but I haven't seen how far back this change goes.

**Comment by lamont-granquist** [comment]
It kind of looks like the `$chef_bootstrap_file` you are using is pointing at a template from a different version of chef?  Its difficult to say without seeing the content of the template to see what is trying to call `trusted_certs`.  This isn't a bug in current knife bootstrap in chef-12.x as far as we can tell though.
