### ISSUE TITLE
Remote file support for ftp protocol

### ISSUE THREAD

**Issue by melezhik** [chef/chef#2344]
It'd be fine if one can download ftp resources by remote_file, given 'ftp://' not 'http://' link

**Comment by smurawski** [comment]
You can specify an FTP source for the remote_file resource.

Check out the source attribute in the documentation for a further description and examples - https://docs.chef.io/resource_remote_file.html

**Comment by melezhik** [comment]
great! thank you!

2015-02-02 23:40 GMT+03:00 Steven Murawski <notifications@github.com>:
