### ISSUE TITLE
bash (and possibly other script resources) documentation problem

### ISSUE THREAD

**Issue by maoueh** [chef/chef#2347]
I'm reporting what seems to be a documentation problem with the `bash` resource (and probably others) found by @lamont-granquist while reviewing an issue I have (#2342)

I was using `bash` resource as what I thought a good workaround for the problem I had. The `bash` resource was like that:

```
bash "user1 reads file with owner user2 and group user2 with mode 0440" do
  command "cat /tmp/testfile"
  user "user1"
  group "user1"
end
```

Running this was succeeding, while it was failing with a permission denied problem when using the `execute` one.

But it was only succeeding because the `command` attribute is not used for `bash` resource and it was simply creating an empty script file which was run correctly because the `code` attribute was empty. This was an error on my part because using `code "cat /tmp/testfile"` was exhibiting the same permission denied problem.

The [documentation](https://docs.getchef.com/resource_bash.html) should be more clear about this behavior because. @lamont-granquist even suggested to add some validation for this. Here a copy of [his write-up](https://github.com/opscode/chef/issues/2342#issuecomment-61521361) about this:

> What we probably need to do is have the execute resource run a @provider.command which load_current_resource in the provider sets to @new_resource.command. Then we stop mutating @new_resource.command in the script provider. We need to add validation on the resource that @new_resource.code is not nil and I think we can even override the validation on @new_resource.command in the script resource to throw an error if its not nil. Then we also need to be careful about other thing which may inherit from those like powershell. 

Regards,
Matt

**Comment by lamont-granquist** [comment]
@jamescott we need to update the `command` parameter on all the script resources -- everything bash or perl or whatever -- but *not* execute -- to more clearly show that the command parameter must not be set on those resources, its for internal use only.

**Comment by jamescott** [comment]
https://github.com/chef/chef-docs/commit/40b96bd1286a8eb5d1b85181f322d65bead8dcd7

What about powershell_script and batch?

**Comment by lamont-granquist** [comment]
Those are the same.

The dsc_script resource is a unique script resource which does not inherit from script/execute and the command property there does work to inject a user-specified command to run -- so dsc_script is its own special snowflake (*sigh*) and should not have its docs changed.

**Comment by cheeseplus** [comment]
The main issue was addressed in docs.
