### ISSUE TITLE
Getting exit codes from PowerShell scripts for powershell_script resources

### ISSUE THREAD

**Issue by ericrlarson** [chef/chef#2348]
### Version:
Chef_Client 11.16.4

### Environment: [Details about the environment such as the Operating System, cookbook details, etc...]
OS: Windows Server 2008 R2 & Windows Server 2012 R2
Cookbook: Proprietary cookbook that wraps existing PowerShell scripts enabling them to be used as part of a Chef converge.

### Scenario:
We have some PowerShell scripts that we use as part of our Chef cookbooks.  These script files are used in other contexts than Chef and so are designed to be self-contained and to inform the calling process of the result via exit codes.  Each script ends with an Exit statement that provides a number: 0 for success, positive numbers for warnings and negative numbers for errors.

This means that the exit code for the script is set and can be queried/inspected by another process.  When we added these scripts to Chef we expected this exit code to be returned to the powershell_script resource when the script is completed, and to cause the resource to fail if the result was not zero.  This is not happening.

### Steps to Reproduce:
* Create a PowerShell script that ends with `Exit -27`
* Run this script using a powershell_script resource in a recipe.  

### Expected Result:
I am expecting to see this kind of output from the Chef Client run:
```
  * powershell_script[ScriptName] action run

    ============================================================================
    Error executing action `run` on resource 'powershell_script[ScriptName]'
    ============================================================================
    <error details>

    Ran "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy RemoteSigned -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20141103-1424-19ko4f5.ps1" returned 65509
```

### Actual Result:
The script will run and no error is reported in Chef.  The output from the converge is `Chef Client finished, 1/1 resources updated`

### Additional Analysis/Information
I captured the script that chef generates in order to understand why our result code was not being returned to Chef.  It looks to me like this script file is supposed to be able to do this since it includes the code `exit $LASTEXITCODE`.  It looks to me like there may be a bug in this generated script file.

In the script file that the resource generates there is a line of code that set the `$LastExitCode` PowerShell automatic variable: `$LASTEXITCODE=0`.  Doing this prevents a script invocation from setting the $LastExitCode via the `Exit <exitCode>` statement.  This means that the conditional `if ($LASTEXITCODE -ne 0)` always fails because `$LASTEXITCODE` is *ALWAYS* zero.

As an experiment I modified my local copy of chef/lib/chef/provider/powershell_script.rb so that the `$LASTEXITCODE=0` line does not get added to the script file, and my converge works as I expect it to.  When the script returns a non-zero result code the resource reports an error.

Is there a way that this code can be removed from the generated PowerShell script file so that our return values make it all the way back to Chef?  If it is there for a specific reason then can the script be created in some other way so that the statement `exit $LASTEXITCODE` can be reached in some other way?

Thank you,
Eric Larson
GE Healthcare.

**Comment by brendonmartino** [comment]
Thanks Nick. @ericrlarson let me know if you need a better example of how to use this code. You can probably write your own simple cookbook to install the gem and then you will have the functionality available to you to use.

**Comment by ericrlarson** [comment]
Truth be told an example would be a huge help.  If you have an example cookbook for installing the gem that would be helpful as well.  

Normally I am very up for figuring out stuff like this on my own, but I am a bit under the gun at the moment.

**Comment by brendonmartino** [comment]
@ericrlarson Here is the quick and dirty method: 1) first do a 'chef gem install' of the gem from rubygems repo. You can use a default recipe to get this done in your cookbook. 2) Once the gem is there, you can use this model as an example for usage: (This is a snippet from an LWRP I wrote to do windows updates -- I haven't open-sourced it yet)


# provider file
.
.
use_inline_resources
def lazy_load
   	# This sets up the mixlib windows_script_out...we need to delay this load until the gem can be installed...
	require 'mixlibrary/core/apps/shell'	
end
  

def load_current_resource         
     # to delay the mixlibrary gem reference until the default recipe can install it...    
     lazy_load
.
.
.
.

      
        checkupdate = " -- a bunch of powershell code goes in here, etc. --"
        
        # get the result object (and exit code) from the above code execution:    
        result = Mixlibrary::Core::Shell.windows_script_out(:powershell,checkupdate)
        # :powershell is the type of script and the var holds all the code. This is how to properly call the gems function and get the exit code from the object it returns
        exit_status = result.exitstatus
.
.
.


	if (exit_status == 100)                      
            @current_resource.exists = false
.
.
.
# You get the idea. Test it out and give us your feedback. Thanks.

**Comment by ericrlarson** [comment]
@brendonmartino @carpnick,

I have put in an issue on the mixlibrary-core issues tracker (https://github.com/ebsco/mixlibrary-core/issues/1).  Not sure if that was the right thing or not.  Any help you can provide would be great.

Thanks,
Eric

**Comment by ericrlarson** [comment]
@jdmundrawala How long before this fix hits an official chef-client build (our QMS process does not allow me to use anything else)

**Comment by brendonmartino** [comment]
@ericrlarson I hope Nick and/or I was able to help resolve your issue...hopefully we gave you the advice you needed to get things going -- it's hard to know what other people's environment looks like, but we're here to help if you get stuck. When you get a chance, perhaps you can give us an update and let us know if you were able to be successful with the gem Nick wrote. Thanks

**Comment by ericrlarson** [comment]
@brendonmartino Sorry for the long silence.  We are in the process of getting a release out the door.  But yes we have successfully implemented an LWRP using the gem that Nick wrote it is working great.

**Comment by brendonmartino** [comment]
@ericrlarson No apologies necessary! We've been busy here too :) I thought @carpnick did a fantastic job with this gem in a short period of time, and produced something useful to many, many people who needed exit codes from powershell scripts. We're glad you were able to leverage this gem since Chef did not have a way of delivering what we both seemed to need. Now, if only we can get them to absorb this into core Chef! ;-)  Let us know if you have any other feedback or suggestions. Thanks

**Comment by smurawski** [comment]
@ericrlarson That update is scheduled for the next minor release of Chef Client (currently slated to be 12.1.0).  I don't have a hard date for that's release, but we shouldn't be too far out.
