### ISSUE TITLE
powershell_script removes file after execution

### ISSUE THREAD

**Issue by brendonmartino** [chef/chef#2352]
When the powershell_script resource creates a .ps1 file (in a temp directory), it removes it shortly after execution. For debugging purposes, I would like to see an option to preserve the file                 (e.g.   --delete [ boolean] flag) 

This way, we can keep the file around to test with, in case we need to do some debugging.

**Comment by smurawski** [comment]
We do dump the script contents and command line executed to the debug log, which should be suitable for this purpose.

**Comment by adamedx** [comment]
Here's the code that dumps the log if you run with debug logging enabled:
https://github.com/chef/chef/blob/12.3.0/lib/chef/provider/powershell_script.rb#L56-L57
