### ISSUE TITLE
Windows Service Provider Ignores Alternate Service States

### ISSUE THREAD

**Issue by sean-horn** [chef/chef#2363]
As a customer, I would like to see chef-client understand other possible service states on Windows hosts, so that retries may be useful.

Suggested fixes in https://tickets.opscode.com/browse/CHEF-4791

**Comment by btm** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms685996%28v=vs.85%29.aspx

We have the same list of states in our code that appear to be available in the API. Either we've got this covered now, or there's a bug in how we handle one of them. But we use an intermediary library so there could be a bug there too.

**Comment by deployable** [comment]
Those changes were pulled in with https://github.com/chef/chef/pull/1166. The change only gracefully handles the `start_pending` and `stop_pending` states. Any `pause` or `continue` states will produce exceptions, even though they have all been populated. 

I didn't have a use case for handling the other states, or ever hit a situation with a service in those other states.

**Comment by adamedx** [comment]
For completeness, it would be nice to support the other states even though we don't see very common usage.

**Comment by deployable** [comment]
What would you do with a `pause`, `pause pending` or `continue pending` state?

**Comment by btm** [comment]
One example from https://github.com/chef/chef/issues/5586 is being able to stop a service that was paused.

**Comment by deployable** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ee126211%28v=vs.85%29.aspx
![Service State Transitions](https://i-msdn.sec.s-msft.com/dynimg/IC498931.png)

That would mean a chef `stop` implies `continue`+`stop` and then possibly that `start` implies `continue`.

Send `stop`
On `continue pending`, wait for `running` to send `stop`.
On `paused`, send `continue`
On `pause pending`, wait for `paused` to send `continue`

Send `start`
On `continue_pending`, wait.
On `paused`, send `continue`
On `pause pending`, wait for `paused` to send `continue`

**Comment by axos88** [comment]
Paused services should be able to be stopped, and restarted (seems straightforward) I would argue that they should also be able to be started, which would either do a restart, or an unpause. In my use case it should do a restart.

Our problem is that a service ran with nssm that fails too quickly wounds up in paused state. Any subsequent chef runs will fail, although the problem causing the service to exit too quickly would have been fixed, and the service should be restarted.

**Comment by axos88** [comment]
Any progress on this?

**Comment by axos88** [comment]
ping @thommay
