### ISSUE TITLE
recipe_eval in provider does not converge all included recipes

### ISSUE THREAD

**Issue by brugidou** [chef/chef#2366]
The `recipe_eval` method defined at https://github.com/opscode/chef/blob/master/lib/chef/provider.rb#L189 is useful when you need to include some recipes or converge some resources while executing the provider's action.

It duplicates the current run context, compiles to a new resource collection and converges the resources defined.

However this does not work when including already compiled recipes. Already included recipes will not be compiled in the recipe_eval block, thus it won't be converged. This is OK if and only if the already included recipe have been included before calling the provider, but sometimes they are included after.

The correct behavior would be to not re-compile already included recipes but to converge them at that time.

Steps to reproduce: you must have a provider that does a `recipe_eval` call, let's say that the `test` provider does a `recipe_eval` that includes `build-essentials`.

This works fine:
```ruby
test 'this is a test resource'
# build-essentials have been converged after this
```

This works fine too:
```ruby
include_recipe 'build-essentials'
test 'this is a test resource'
# build-essentials was compiled and converged only once
```

This fails:
```ruby
test 'this is a test resource'
# build-essentials was NOT converged after this
include_recipe 'build-essentials'

**Comment by lamont-granquist** [comment]
`recipe_eval` is private method that shouldn't be used like this.  #3483 may fix the use case, however, by allowing `include_recipe` from within a provider.
