### ISSUE TITLE
Chef service provider on OSX does not handle homebrew installs well

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef#2367]
Run the following recipe on OSX:

``` ruby
package "mysql" do
  version "5.6"
end

service "mysql" do
  action :enable
  service_name "homebrew.mxcl.mysql"
  provider Chef::Provider::Service::Macosx
end
```

You should see the following exception:

```
Chef::Exceptions::Service
-------------------------
Could not find service's label in plist file ''!
```

I don't think this linking is an issue because Homebrew recommends doing the same thing, except linking it to the user's directory.  But we could probably use better communication to customers about this, or perhaps provide a homebrew resource attribute (`link_to_system` maybe?) to do this automatically.

**UPDATE** - homebrew has a `service` keg that manages this better, see http://robots.thoughtbot.com/starting-and-stopping-background-services-with-homebrew
**UPDATE2** - It looks like `service` is not maintained?  Investigate https://github.com/Homebrew/homebrew/issues/33815

This is happening because the OSX service provider is only searching /Library and /System/Library for .plist files and homebrew installs mysql to /user/local/Cellar/mysql.  Updating the recipe to the following fixes that:

``` ruby
package "mysql" do
  version "5.6"
end

link "mysql" do
  target_file "/Library/LaunchAgents/homebrew.mxcl.mysql.plist"
  to "/usr/local/opt/mysql/homebrew.mxcl.mysql.plist"
end

service "mysql" do
  action :enable
  service_name "homebrew.mxcl.mysql"
  provider Chef::Provider::Service::Macosx
end
```

The chef run completes successfully but trying to enable the resource causes launchctl to output `/usr/local/Cellar/mysql/5.6.21/homebrew.mxcl.mysql.plist: Path had bad ownership/permissions` on stdout.  It returns a 0 status code so Chef thinks it successfully enabled the service.  But executing `sudo launchctl list | grep mysql` returns nothing because the service is not enabled.

Running chef again shows `Warning: mysql-5.6.21 already installed` - it looks like we're not correctly checking whether mysql is installed by homebrew before trying to trying to execute the install again.

**Comment by mikedodge04** [comment]
/Library/LaunchAgents/ must be owned by root and not have write access to them (Ex: 755) by any one other than root.

Are you trying to run mysql as a user? If not you should move the symlink to /Library/LaunchDaemons/ and then it will run as root.
