### ISSUE TITLE
Bash resource should support `set -eu`

### ISSUE THREAD

**Issue by pjungwir** [chef/chef#2369]
Something like this will "succeed" even if compilation fails in the `make` step:

    bash "compile_nginx_source" do
      cwd ::File.dirname(src_filepath)
      code <<-EOH
        set -eu
        tar zxf #{::File.basename(src_filepath)} -C #{::File.dirname(src_filepath)}
        cd nginx-#{node['nginx']['version']} && ./configure #{node.run_state['nginx_configure_flags'].join(' ')}
        make && make install
        rm -f #{node['nginx']['dir']}/nginx.conf
      EOH
    end

Normally in a bash script I can use `set -eu` so that if any line fails the whole thing will abort. With chef this doesn't seem to work, so that if a line in the middle fails, chef will not notice and just keep going. Chef's bash resource should honor `set -eu` so you don't have to add `&&` between every line.

**Comment by lamont-granquist** [comment]
closing this as we can't replicate it
