### ISSUE TITLE
remote_file resource uses Tempfile from Chef::HTTP which does not obey file_staging_uses_destdir

### ISSUE THREAD

**Issue by johusta** [chef/chef#2401]
I rebuilt my chef-client as it appeared this issue was resolved sometime in Sept and stated to be fixed in 12.0.0. 

It still tries to stage to /tmp with this set in my client.rb file.

**Comment by axos88** [comment]
+1

**Comment by msgarbossa** [comment]
+1
It seems like Chef::Config[:file_staging_uses_destdir] isn't really defaulting to true in the client config.  Also a bigger problem on AIX where filesystems are not as large as Linux.
