### ISSUE TITLE
Lightweight resources should have access to run_context and node during class definition, for use in DSL (e.g. attribute default values) 

### ISSUE THREAD

**Issue by alambike** [chef/chef#2403]
Despite unit test in https://github.com/opscode/chef/blob/11.16.4/spec/unit/lwrp_spec.rb#L121 I couldn't make it work, maybe I'm doing something wrong

For example, this attribute in my LWRP resource:
```
attribute :uid, :kind_of => String, :default => node["appserver"]["uwsgi"]["user"]
```
Always returns error:
```
NoMethodError
-------------
undefined method `node' for nil:NilClass

```
I've found this exact old issue: [CHEF-1946](https://tickets.opscode.com/browse/CHEF-1946) that seems not resolved.

**Comment by lamont-granquist** [comment]
The `Chef.node` and `Chef.run_context` facades which were introduced in 12.3.0 should allow this to work, in addition to allowing access to those from libraries and at class evaluation time in libraries, etc.

If this does not work, please reopen.
