### ISSUE TITLE
knife bootstrap - issue with zookeeper

### ISSUE THREAD

**Issue by ctippur** [chef/chef#2413]
Hello,

I see this error while installing zookeeper.

ArgumentError: zookeeper[3.4.6] (zookeeper::install line 22) had an error: ArgumentError: chef_gem[zookeeper] (dynamically defined) had an error: ArgumentError: Illformed requirement [""]

Error I see in the knife command - * chef_gem[zookeeper] action install[2014-11-13T09:01:41-08:00] WARN:  failed to find gem zookeeper (>= 0) from [http://rubygems.org/]

**Comment by stevendanna** [comment]
@ctippur As with #2412  this appears to be a problem with a particular cookbook.  Are you still experiencing this issue?

**Comment by smurawski** [comment]
@ctippur As Steven noted above, this is more of an issue with the cookbook or recipe you are using and the Chef mailing list or IRC channel are more appropriate forums for help with that.
