### ISSUE TITLE
dpkg_package with + in filename causes reinstall when not necessary

### ISSUE THREAD

**Issue by bantl23** [chef/chef#2417]
I created a ruby file called ```devel.rb``` which has the following content
```
dpkg_package "libtinfo5" do
  version "5.9"
  source "libtinfo5_5.9+20140118-1ubuntu1_amd64.deb"
  action :install
end

dpkg_package "tmux" do
  source "tmux_1.8-5_amd64.deb"
  action :install
end
```
I have the two deb package in the same directory as ```devel.rb``` which I downloaded from ubuntu mirror site:

http://mirrors.kernel.org/ubuntu/pool/main/n/ncurses/libtinfo5_5.9+20140118-1ubuntu1_amd64.deb
http://mirrors.kernel.org/ubuntu/pool/main/t/tmux/tmux_1.8-5_amd64.deb

When I run: ```chef-apply devel.rb -W -l debug``` there is a version mismatch reported and it reports that the package will get installed unnecessarily.

I seem to have narrowed this down to the deb file having a + within the filename.
For libtinfo5 dpkg reports 5.9+20140118-1ubuntu1
For libtinfo5 chef report 5.9.
It seems like chef stops at the first + instead of stopping at the _amd64.deb.

If possible could this behavior be changed so the version mismatch stops occurring and reinstalling of an already installed package not not performed.

I need to do this because I have to configure machines that have no internet access so I'm creating a cookbook that will contain deb packages because it can't see the ubuntu mirror sites.

**Comment by lamont-granquist** [comment]
we fixed this
