### ISSUE TITLE
knife diff only uses repo chefignore and should also use cookbook chefignore

### ISSUE THREAD

**Issue by iroller** [chef/chef#2429]
Chef: 11.16.4

When executing

```
p1/p2/cookbook_name $ knife diff
```

It looks for chefignore file in p1 and p2, but not in `cookbook_name`.

Is it a bug or a feature?

**Comment by vsingh-msys** [comment]
Reference to https://github.com/chef/chef/pull/7156

**Comment by vsingh-msys** [comment]
Verified with master now it's respecting cookbook dir chefignore path. as Fixed in #8925
