### ISSUE TITLE
Chef template throws Errno::EINVAL when trying create file on nfs mount point

### ISSUE THREAD

**Issue by poliva83** [chef/chef#2432]
Was trying to create file using template resource to directory on node that mounted via nfs configured in /etc/fstab.

/etc/fstab
```
172.32.32.11:/mandolin/ /srv/mandolin nfs rw 0 0
```

```
template "Config for chefdeploy.rb" do
  source "chef-deploy-config.erb"
  path "/srv/mandolin/poliva/poliva_bbsl-auto_orion.cfg"
  owner 'root'
  group 'root'
  mode 0755
  variables(
    :name => "#{node.chef_environment}"
  )
end
```

Chef Client failed. 0 resources updated in 1.657872282 seconds
[2014-11-16T17:54:30-05:00] ERROR: template[Config for chefdeploy.rb] (chef-server::chef_deploy_config line 2) had an error: Errno::EINVAL: Invalid argument - /srv/mandolin/poliva/poliva_bbsl-auto_orion.cfg
[2014-11-16T17:54:30-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

The strange this is the file is actually created albeit the mode, owner, and group was messed up. 

When I can the path to directory that is local to node everything is fine.

```
template "Config for chefdeploy.rb" do
  source "chef-deploy-config.erb"
  path "/tmp/poliva/poliva_bbsl-auto_orion.cfg"
  owner 'root'
  group 'root'
  mode 0755
  variables(
    :name => "#{node.chef_environment}"
  )
end
```

This was seen on Chef: 11.10.2

**Comment by jfbibeau** [comment]
Same issue, did you ever find a fix? Seems intermittent for me, doesn't always happen. But only affects file creation on NFS mountpoint (with Vagrant).

**Comment by lamont-granquist** [comment]
^ i still need the answer to those questions.   Also could use the full stacktrace.

**Comment by jfbibeau** [comment]
Just to confirm. you want me to try with `file_stating_uses_destdir` set to true in client.rb? I'm using Chef 11.16.4.

**Comment by lamont-granquist** [comment]
Yeah, or just try to replicate with Chef 12.1.1

**Comment by jfbibeau** [comment]
Alright, I'll get back to you shortly. Only 2 of my users so far have encountered this problem, so I need to figure out how to consistently reproduce before I can confirm whether it has any impact. Thanks for the reply.

**Comment by lamont-granquist** [comment]
No response to this, hopefully `file_staging_uses_destdir` and/or Chef 12 fixed it.

**Comment by poliva83** [comment]
Sorry kind of lost track that I logged this issue. I'll try to remember next week to check if I can try to reproduce this on a Chef 12 workstation. I believe I was running chef-solo locally to produce some configuration files for a deployment script (which is now being deprecated in favor of chef-provisioning).
