### ISSUE TITLE
[Git resource] Provide a way to specify git config environment parameters

### ISSUE THREAD

**Issue by kiiranh** [chef/chef#2437]
When running behind a proxy, one needs to set the http(s)_proxy and other git options in .gitconfig for git to work. One other way to do this is set the http(s)_proxy and other GIT attributes as environment variables in knife.rb. But if these variables are to be set for a specific recipe, currently there seems to be no way to do it.
Could we add an "environment" resource attribute to the git resource where one can specify environment variables for that specific git run? The bash resource has such an environment attribute.

**Comment by gimler** [comment]
i think the latest chef version has this feature https://github.com/chef/chef/blob/master/lib/chef/provider/git.rb#L314 not shure.

**Comment by smurawski** [comment]
The git resource does have an environment attribute as of Chef 12 - http://docs.chef.io/resource_git.html
