### ISSUE TITLE
Add configurable warnings to changing the run_list, chef_environment, etc

### ISSUE THREAD

**Issue by uwebartels** [chef/chef#2443]
We are configuring simple attributes in the cookbooks depending on the environment, e.g.

```
default[:application][:port]="1234" if node.chef_environment=="DEV"
```

Works generally fine.

If a cookbook developer makes an error and types instead

```
default[:application][:port]="1234" if node.chef_environment="DEV"
```

then the node where the chef-client is running changes the environment in the chef server!!

This is bad and very unexpected behavior.
Additionally that works even if the environment does not exist on the chef server.

Then the web-gui blows up and I cannot display the host or edit the host.
workaround at that point is creating the missing environment, change the environment to its original state and remove the bad environment.

**Comment by lamont-granquist** [comment]
Narrowed the topic of this to just warning on modifications to these kinds of variables.  Making it so that the chef server doesn't accept nodes updating their own desired state is an extremely large yak.

**Comment by dreamnite** [comment]
Going slightly beyond just the warning: if we're allowing assignments, could the server not allow changes to the environment if the destination environment doesn't exist?

**Comment by lamont-granquist** [comment]
so like don't allow bad foreign key values?

i can dig it, but that's a server issue and should be filed against http://github.com/chef/chef-server/issues/new -- the client should definitely not be doing that validation on the node object, but the server could hand back some 4xx code if the node POST had an invalid environment.

**Comment by lamont-granquist** [comment]
this would be better handled by https://github.com/chef-boneyard/chef-rfc/blob/master/rfc045-node_state_separation.md
