### ISSUE TITLE
If using Chef to apply DSC resources, the LCM ConfigurationMode should be set to ApplyOnly

### ISSUE THREAD

**Issue by smurawski** [chef/chef#2470]
The default setting for the Local Configuration Manager (LCM) ConfigurationMode is ApplyAndMonitor, which means the LCM will be doing consistency checks for whatever the last successful DSC configuration applied was.  Rather than having the LCM spinning cycles checking things that we'll also be checking, we should change the LCM ConfigurationMode to ApplyOnly.

**Comment by MattHodge** [comment]
Those that find this and want to configure the LCM with Chef, here is how I have done it:

```
powershell_script "Confgire LCM" do
  code <<-EOH
    Configuration ConfigLCM
    {
        Node "localhost"
        {
            LocalConfigurationManager
            {
                ConfigurationMode = "ApplyOnly"
                RebootNodeIfNeeded = $true
            }
        }
    }

    ConfigLCM -OutputPath "#{Chef::Config[:file_cache_path]}\\DSC_LCM"

    Set-DscLocalConfigurationManager -Path "#{Chef::Config[:file_cache_path]}\\DSC_LCM"
  EOH
end
```

@smurawski Let me know if I am wrong or there is a better way :)

**Comment by smurawski** [comment]
@MattHodge You should add a guard to check the LCM rather than re-configuring it every time, but other than that, it is the best.

**Comment by smurawski** [comment]
@MattHodge Read it too quickly - I wouldn't let DSC reboot the node - handle that in Chef or it'll look like your Chef run errored or aborted.

**Comment by lamont-granquist** [comment]
bump to get this off our list.

**Comment by MattHodge** [comment]
My above script fails now with `Configuration is not supported in a Windows PowerShell x86-based console. Open a Windows PowerShell x64-based console, 
and then try again. ` Have tried it using the powershell_script resource with `architecture :x86_64`

This stopped working in 12.4.X

**Comment by smurawski** [comment]
@matthodge the exact same script?  I ran that today with 2012r2 and 12.4.1 and it worked flawlessly

**Comment by MattHodge** [comment]
I am getting the issue on a Windows 2008 R2 x64 machine with WMF 4.0 installed.

check PS version:
```powershell
$PSVersionTable.PSVersion
```
results:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1
```
check if 64 bit powershell process:
```powershell
[Environment]::Is64BitProcess
```
result:
```
true
```

Here is the full script used..

cookbook file:
```ruby
powershell_script "Confgire LCM" do
  code <<-EOH
    Configuration ConfigLCM
    {
        Node "localhost"
        {
            LocalConfigurationManager
            {
                ConfigurationMode = "#{node["dsc_lcm"]["ConfigurationMode"]}"
                RebootNodeIfNeeded = $#{node["dsc_lcm"]["RebootNodeIfNeeded"]}
            }
        }
    }

    ConfigLCM -OutputPath "#{Chef::Config[:file_cache_path]}\\DSC_LCM"

    Set-DscLocalConfigurationManager -Path "#{Chef::Config[:file_cache_path]}\\DSC_LCM"
  EOH
  not_if "(Get-DscLocalConfigurationManager).ConfigurationMode -eq '#{node["dsc_lcm"]["ConfigurationMode"]}'"
end
```

attributes file:
```ruby
default["dsc_lcm"]["ConfigurationMode"] = "ApplyOnly"
default["dsc_lcm"]["RebootNodeIfNeeded"] = false
```

Here is the full error message:
```
powershell_script[Confgire LCM] (dsc_lcm::default line 10) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -Command C:/Users/matthodge/AppData/Local/Temp/chef_powershell_script-user-code20150805-580-1xmtfp5.ps1 ----
STDOUT: 
STDERR: At C:\Users\matthodge\AppData\Local\Temp\chef_powershell_script-user-code20150805-580-1xmtfp5.ps1:1 char:6 
+ {    Configuration ConfigLCM 
+      ~~~~~~~~~~~~~ 
Configuration is not supported in a Windows PowerShell x86-based console. Open a Windows PowerShell x64-based console, 
and then try again. 
At C:\Users\matthodge\AppData\Local\Temp\chef_powershell_script-user-code20150805-580-1xmtfp5.ps1:1 char:1 
+ {    Configuration ConfigLCM 
+ ~ 
Missing closing '}' in statement block. 
At C:\Users\matthodge\AppData\Local\Temp\chef_powershell_script-user-code20150805-580-1xmtfp5.ps1:2 char:5 
+     { 
+     ~ 
Unexpected token '{' in expression or statement. 
At C:\Users\matthodge\AppData\Local\Temp\chef_powershell_script-user-code20150805-580-1xmtfp5.ps1:16 char:1 
+ } 
+ ~ 
Unexpected token '}' in expression or statement. 
At C:\Users\matthodge\AppData\Local\Temp\chef_powershell_script-user-code20150805-580-1xmtfp5.ps1:1 char:6 
+ {    Configuration ConfigLCM 
+      ~~~~~~~~~~~~~ 
   + CategoryInfo          : ParserError: (:) [], ParseException 
   + FullyQualifiedErrorId : ConfigurationDoesNotSupportWOW64
---- End output of "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -Command C:/Users/matthodge/AppData/Local/Temp/chef_powershell_script-user-code20150805-580-1xmtfp5.ps1 ----
Ran "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -Command C:/Users/matthodge/AppData/Local/Temp/chef_powershell_script-user-code20150805-580-1xmtfp5.ps1 returned 1
```

**Comment by MattHodge** [comment]
Hey @smurawski did you get a chance to test this one out?

Can confirm that this exact cookbook works with chef-client 12.3.0 on Windows 2008 R2 x64

**Comment by mmcelreath** [comment]
I just got the same error today telling me "Configuration is not supported in a Windows PowerShell x86-based console. Open a Windows PowerShell x64-based console, and then try again."

This was on a 2012R2 machine with WMF 4.0

**Comment by smurawski** [comment]
@MattHodge @mmcelreath I was able to replicate the problem.  I haven't dug much into it yet (I've been out on PTO).  I'm back to work on Tuesday and will dig further then, but @chef/client-windows may have an idea why we have reverted to getting caught by syswow redirection.

**Comment by smurawski** [comment]
@MattHodge @mmcelreath @chef/client-windows There is definitely something broken between 12.3 and 12.4.

**Comment by MattHodge** [comment]
Thanks @smurawski :) Look forward to it !

**Comment by btm** [comment]
@smurawski would it make sense to have `dsc_resource` check the LCM and change it to ApplyOnly? that way we don't mess with the setting by default, but do so if people use `dsc_resource`.

**Comment by smurawski** [comment]
@btm I'd rather see an LCM resource in core to make it clear what is happening to the state of the LCM.  We could warn if not in ApplyOnly.  I have an LCM resource in the `dsc_contrib` cookbook on Supermarket  in the meantime.

**Comment by stuartpreston** [comment]
I think the original issue here was resolved when WMF5 allowed us to support configurations where RefreshMode is set to Enabled.  See https://github.com/chef/chef/commit/9f6a1bbe020c2664fbe96f18ed8d5861a9e3da84 

We will put the porting of the LCM configuration resource to core on the backlog.
