### ISSUE TITLE
Allow cron provider to work when Chef Client is run as non-root (or not privileged) user

### ISSUE THREAD

**Issue by kwilczynski** [chef/chef#2491]
A great majority of the `crontab` (the user space binary) implementations would only ever accept the `-u` will only ever accept the "-u" flag when the user is either root or said user has elevated privileges (effective UID is 0 via "sudo", etc.).

For example:
- RHEL / CentOS (where either `vixie-cron` or `cronie` is usually installed):

```
[vagrant@centos65 ~]$ crontab -u whiskers -l
must be privileged to use -u
[vagrant@centos65 ~]$ crontab -u vagrant -l
must be privileged to use -u
[vagrant@centos65 ~]$
```

Above will fail because of the `-u` flag even despite that it's for the same user.
- Debian / Ubuntu (where quite an old release of original `vixie-cron` is present):

```
vagrant@ubuntu1404:~$ crontab -u whiskers -l
must be privileged to use -u
vagrant@ubuntu1404:~$ crontab -u vagrant -l
no crontab for vagrant
vagrant@ubuntu1404:~$
```

Above does not fail for the same user even when the `-u` flag is added, only when asking for cron jobs for different users - one might argue that this behaviour is more correct.

Given the two different outcomes, we could safely remove adding (currently, hard-coding rather) of the `-u` flag when user is neither root nor privileged (effective UID is not 0). In other words, when not running as root the `-u` flag is not useful.

In the past, to circumvent `crontab` exiting with non-zero exit code (as we were hard-coding `-u` to be added for all users, etc.), one would have to stop using `cron` resource in recipes and resort to utilising `execute`, which some users found not delightful.

**Comment by jekriske-lilly** [comment]
bump.
We ran into this issue today. Difficult to troubleshoot as docs fail to mention one needs to be root but it's obvious when seeing the current source code.

**Comment by kwilczynski** [comment]
@jekriske-lilly let me see if I can get this done.

In terms of documentation - one could argue that most of the time Chef has to run as root anyway to be able to modify files all over the file system, plus to restart services, etc. The use case where it is run under a dedicated user (with or without sudo set accordingly) is very niche, which is the reason why this received not a lot of attention.
