### ISSUE TITLE
Remove 1.8 and 1.9 specific code

### ISSUE THREAD

**Issue by danielsdeleo** [chef/chef#2497]
This is what I found with `git grep -n '1.8':
- [ ] https://github.com/opscode/chef/blob/0760983e7aff5bafe5b2c8c43891fbb3d0fd3ed3/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb#L121-L124
- [ ] https://github.com/opscode/chef/blob/45167319996c4fc7e65351a459ae2ee8a5960b31/lib/chef/mixin/securable.rb#L115-L119
- [ ] https://github.com/opscode/chef/blob/45167319996c4fc7e65351a459ae2ee8a5960b31/lib/chef/mixin/template.rb#L26-L36
- [x] https://github.com/opscode/chef/blob/master/lib/chef/monkey_patches/numeric.rb#L1-L15
- [x] https://github.com/opscode/chef/blob/master/lib/chef/monkey_patches/regexp.rb#L22-L34
- [x] https://github.com/opscode/chef/blob/master/lib/chef/monkey_patches/string.rb#L19-L49
- [x] https://github.com/opscode/chef/blob/master/lib/chef/monkey_patches/tempfile.rb
- [ ] https://github.com/opscode/chef/blob/45167319996c4fc7e65351a459ae2ee8a5960b31/lib/chef/node/immutable_collections.rb#L78-L83
- [ ] https://github.com/opscode/chef/blob/45167319996c4fc7e65351a459ae2ee8a5960b31/lib/chef/resource/lwrp_base.rb#L76-L87
- [ ] https://github.com/opscode/chef/blob/45167319996c4fc7e65351a459ae2ee8a5960b31/lib/chef/resource/template.rb#L105-L107
- [ ] https://github.com/opscode/chef/blob/45167319996c4fc7e65351a459ae2ee8a5960b31/lib/chef/run_context.rb#L197-L208
- [ ] https://github.com/opscode/chef/blob/45167319996c4fc7e65351a459ae2ee8a5960b31/lib/chef/run_lock.rb#L97-L102
- [ ] https://github.com/opscode/chef/blob/45167319996c4fc7e65351a459ae2ee8a5960b31/lib/chef/search/query.rb#L135-L136
- [ ] https://github.com/opscode/chef/blob/45167319996c4fc7e65351a459ae2ee8a5960b31/lib/chef/util/path_helper.rb#L104-L106
- [ ] https://github.com/opscode/chef/blob/45167319996c4fc7e65351a459ae2ee8a5960b31/spec/support/platform_helpers.rb#L26-L28
- [ ] https://github.com/opscode/chef/blob/45167319996c4fc7e65351a459ae2ee8a5960b31/spec/unit/chef_fs/parallelizer.rb#L223-L225
- [ ] https://github.com/opscode/chef/blob/45167319996c4fc7e65351a459ae2ee8a5960b31/spec/unit/node/attribute_spec.rb#L1028-L1036
- [ ] https://github.com/opscode/chef/blob/45167319996c4fc7e65351a459ae2ee8a5960b31/spec/unit/policy_builder/policyfile_spec.rb#L344-L348
- [ ] https://github.com/opscode/chef/blob/45167319996c4fc7e65351a459ae2ee8a5960b31/spec/unit/provider/mount/solaris_spec.rb#L97
- [ ] https://github.com/opscode/chef/blob/45167319996c4fc7e65351a459ae2ee8a5960b31/spec/unit/provider/remote_file/cache_control_data_spec.rb#L161-L162
- [ ] https://github.com/opscode/chef/blob/45167319996c4fc7e65351a459ae2ee8a5960b31/spec/unit/provider/remote_file/cache_control_data_spec.rb#L161-L162
- [ ] https://github.com/opscode/chef/blob/45167319996c4fc7e65351a459ae2ee8a5960b31/spec/unit/provider/remote_file/cache_control_data_spec.rb#L161-L162

**Comment by lamont-granquist** [comment]
a lot of this got done.  there's probably more.  wherever it is found it should be killed.  closing this issue since nobody is working on it directly.
