### ISSUE TITLE
knife diff / ChefFS / chef-zero and JSON vs ruby DSL files

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#2502]
Berkshelf does not upload a metadata.rb file and instead only uploads the compiled metadata.json file, this generally results in `knife diff /` reporting diffs on every single metadata.rb and metadata.json file in the repository, which makes knife diff much less useful than it should be to check for diffs against your repository.

This also is a problem for ruby DSL roles.  And the fact that ChefFS does not handle ruby DSL files is also a blocker for replacing chef-solo which chef-zero mode according to the RFC.

It looks like ChefFS needs to be modified to support reading ruby DSL files.  It would also good to be able to teach knife diff to be able to compile the ruby DSL file and compare against the uploaded JSON (it could do similar to grep's binary compare and just report that there are or are not differences without trying to do a diff between the two different formats which might be a bit crazy -- although the diff of the computed JSON might work).

As a stopgap it might be useful to somehow extend the chefignore concept to be more useful.  What I'd like is to be able to ignore metadata.rb and metadata.json for knife diff but to obviously not ignore those files on cookbook upload / berks upload.

**Comment by keen99** [comment]
:headdesk:

so chef-zero doesnt work with ruby roles at all.

can we get this mentioned in docu somewhere since we now have 3 operating modes and only 2 of those work with ruby rules?  and the cross section of those two modes that work with chef-provisioning leaves me without ruby roles for the -metal infra I was building.

bah.

**Comment by lamont-granquist** [comment]
should have been fixed in #4887 or related PRs
