### ISSUE TITLE
remote_directory ressource don't create empty directories

### ISSUE THREAD

**Issue by gmauleon** [chef/chef#2507]
### Version:

Chef: 11.18.0.rc.1
### Environment:

CentOS 7
### Scenario:

Using a simple structure in files/default/ as the source of the remote_directory ressource like:
test
--dir01
--dir02
----file01

WIth a simple recipe like:

``` ruby
remote_directory "/home/test" do
    source      'test'
end
```
### Expected Result:

All directories and files should be created on the client
### Actual Result:

Only files and directories containing files are created. 
Need to use a 'dummy' file in empty directories in order for everything to be properly created.

**Comment by lamont-granquist** [comment]
This may just be a doc bug that people need to use a `.dummy` or `.save` file in the directory in order to create it.  We're unlikely to prioritize fixing this and its unlikely to get done by an external contributor.
