### ISSUE TITLE
Create CLI options for policyfile

### ISSUE THREAD

**Issue by jtimberman** [chef/chef#2509]
While the Policyfile feature is experimental, I think it would be good to expose the `use_policyfile` and `deployment_group` options to the `chef-client` CLI so that they can be used for experimenting (heh). Example use:

```
chef-client --use-policyfile --deployment-group provisioner
```

Would be the same as:

```ruby
use_policyfile true
deployment_group 'provisioner'
```

**Comment by smurawski** [comment]
Rather than doing this through chef-client, we've introduced the chef provision command in ChefDK 0.6.0 - https://www.chef.io/blog/2015/05/15/chefdk-0-6-0-released/

Thanks!
