### ISSUE TITLE
Cannot render partials inside partials with variables

### ISSUE THREAD

**Issue by Rapsey** [chef/chef#2513]
*This issue is about the same problem as described [here](https://tickets.opscode.com/browse/CHEF-5143). It was closed because it couldn't be reproduced but it's actually really easy to do so. My apologies if this isn't a bug. I couldn't find if Chef is supposed to support nested partials.*

How to reproduce:

*recipes/default.rb*
```ruby
template 'testtemp' do
  path '/tmp/testtemp'
  variables(:foo => 'bar')
end
```
*templates/default/testtemp.erb*
```ruby
<%= render 'partial1.erb', :variables => {:foo => @foo} %>
```
*templates/default/partial1.erb*
```ruby
<%= render 'partial2.erb' %>
```
*templates/default/partial2.erb*
```ruby
This is will never be rendered.
```

This results in a `Chef::Mixin::Template::TemplateError (You cannot render partials in this context)`. Without the `<%= render 'partial2.erb' %>` in the first partial everything works as it should.

This only happens when you try to render a partial **inside a partial with variables**. So if we make the following change...

*templates/default/testtemp.erb*
```ruby
<%= render 'partial1.erb', :variables => nil %>
```

...then rendering the nested templates works fine. Not passing the `:variables` option to the `render` method achieves the same result.

I have confirmed this behaviour using Chef 11.16.4 on Debian Wheezy 7.7.

**Comment by thommay** [comment]
Closed by #3510
