### ISSUE TITLE
CHEF-3865: Create or delete a Windows service 

### ISSUE THREAD

**Issue by SteveLowe** [chef/chef#2518]
See: https://tickets.opscode.com/browse/CHEF-3865#

It would very nice to be able to create & delete windows services natively in chef.

**Comment by chrisevett** [comment]
Is anything going on with this? I noticed the linked pull request but it has been stale for a while. I need this functionality so I can take this over if nobody is working on it

**Comment by axelrtgs** [comment]
Reviving this to hopefully generate some interest in this. would be nice to see this added in to chef core so that we can create services.

**Comment by jakauppila** [comment]
We are doing some of this within our own cookbooks so I hope to try and integrate it into the core and get a PR submitted when I have some time to work on it, I couldn't provide any timelines though.

**Comment by axelrtgs** [comment]
thank you, it will be nice to move away from an execute block and be able to configure things like what to do on failure easily. looking forward to your PR

**Comment by jasonwbarnett** [comment]
My goal is to submit a PR by end of day with both create/delete actions for the `windows_service`.

**Comment by stuartpreston** [comment]
Merged in #6595 so closing this issue.
