### ISSUE TITLE
Chef's rspec tests not easily stopable

### ISSUE THREAD

**Issue by stevendanna** [chef/chef#2520]
When running Chef's rspec tests via either:

    rake spec

or 

    rspec

The test run can become very hard to kill at the terminal.  Sending an interrupt (^c) simply causes the currently running test to fail and then proceeds to the next test.  Suspending the job (^z) and sending a SIGKILL to the rspec process works, but feels pretty ugly.

**Comment by thommay** [comment]
This annoys Lamont.

**Comment by lamont-granquist** [comment]
Rake itself is just calling system which detaches a process to run rspec:

https://github.com/rspec/rspec-core/blob/master/lib/rspec/core/rake_task.rb#L79

Somehow the SIGINT is not getting propagated correctly to the child process or rspec is ignoring it, so it continues in the background.

**Comment by lamont-granquist** [comment]
So, running `rspec spec/**/*_spec.rb` on the command line and ctrl-c only quits the current test being run.

**Comment by lamont-granquist** [comment]
It looks like the interrupt handler in rspec-core is never getting called, so something in the chef codebase is presumably scribbling over it.

**Comment by lamont-granquist** [comment]
(but throwing puts in various trap blocks did not find which trap statement in the chef codebase is handling the interrupt)

**Comment by lamont-granquist** [comment]
Based on adding this code to spec_helper.rb:

```ruby
class Object
  alias_method :original_trap, :trap

  def trap(*args, &block)
    puts "========================================================================================================================"
    puts caller
    puts "========================================================================================================================"
    original_trap(*args, &block)
  end
end
```

A strong contender for the culprit is TinyServer which creates a thread and then loads up rack which spits out:

```
========================================================================================================================
/home/lamont/.rvm/gems/ruby-2.2.3/gems/rack-1.5.5/lib/rack/server.rb:256:in `start'
/home/lamont/oc/chef/spec/tiny_server.rb:69:in `block in start'
========================================================================================================================
```

**Comment by lamont-granquist** [comment]
Commenting out the code for the INT handler in the rack gem fixes the problem
