### ISSUE TITLE
tar does not support -z on Solaris and AIX (chef solo -r flag specifically)

### ISSUE THREAD

**Issue by scotthain** [chef/chef#2535]
As seen here:
https://github.com/opscode/chef/blob/master/lib/chef/application/solo.rb#L205
we make the assumption that the platform has a gnu tar that supports the -z flag.

I feel we should either:
1. not make the assumption of -z and change this to the 'oldest common denominator" uncompression tools OR
2. document that gnu tar needs to be a pre-req and first on your path (as 'tar') in the runtime environment.

**Comment by lamont-granquist** [comment]
Okay, so turns out i was incorrect and some neurons got crossed.  So `tar xf foo.tar.bz2` will magically decompress it, but `tar xzf foo.tar.gz` errors out with a complaint about it not being gzipped.

**Comment by lamont-granquist** [comment]
Note to anyone that does this which is that chef-client -z also has the ability to do this so there's at least two places to change the code for both solo and client.

**Comment by lamont-granquist** [comment]
Closing this one as "PRs Welcome" (but you need to make CERTAIN not to break anyone using bzip on linux, etc so it may not be as trivial as you think)
