### ISSUE TITLE
Cookbook upload failed due to file not found

### ISSUE THREAD

**Issue by laratamayo** [chef/chef#2539]
Hi,

I'm trying to do a cookbook upload using this knife command.

`knife cookbook upload apache2 --verbose`.

However, it returns a 400 error:

```bash
INFO: HTTP Request Returned 400 Bad Request: Cannot update sandbox 0000000000002e98358e4114d26d9ceb: the following checksums have not been uploaded: 256a1d4eff83835fa58f38b8583176d5, 4f3b3cbb9bde3d40cc359c1def2df078, 50ce3f9b83085e6628617215bccfeed3, 6306207659362f6d0bd014417d040cda, 7487a051e59cf6dc06bdf3592a05e1f3, 8f7bb094c7232b058c7e9f2e431f389c, 9d5e006e4a02592bd9821c911dd76cb3, a67a0204d4c54848aad67a8e9de5cad1, c51df4e763f02fde253718cc06a0d075, cd1b44bd0abdbcdff2f01672d3a13ea0, e4bcd8d228a65708636a96d83956b6c7, e5600a5296cb1b69f978b6c2c4a1b1c1, e8703460ba62760210f156cae6fd38d5, fb50812eb39a4731290fa6032837bc87
```

Looking at the Chef server logs:

```bash
=ERROR REPORT==== 5-Dec-2014::13:57:46 ===
2014-12-05_00:57:46.15484 Checking presence of file (checksum: <<"e5600a5296cb1b69f978b6c2c4a1b1c1">>) for org <<"00000000000000000000000000000000">> from bucket "bookshelf" (key: "organization-00000000000000000000000000000000/checksum-e5600a5296cb1b69f978b6c2c4a1b1c1") failed because the file was not found
```

I'm using Open source Chef server 11.0.8 on CentOS 6.5.

Running `knife client list` gives me the list of clients.

Any ideas?

Thanks a lot.

**Comment by thommay** [comment]
Hi,
I'm really sorry that our response is so delayed, but if you're still seeing this, could we ask for
1. The complete output from the `knife cookbook upload` command
2. Considerably more output from the chef server logs.

This is really a chef-server issue, so if you could raise a bug with the logs at https://github.com/chef/chef-server/issues that would be great.
Thanks, and once again our apologies for the delay.
