### ISSUE TITLE
Deploy_branch undefined method 'dir' when deploying in Windows

### ISSUE THREAD

**Issue by Kendallsr** [chef/chef#2546]
### Version:

11.16.4
### Environment:

Windows 7, deploy_branch resource
### Scenario:

I am trying to use Deploy_Branch to deploy a Github repo on my Windows machine.  The deployment resource works perfectly fine in a Linux environment (specifically Ubunutu 12.04) but throws the following error in Windows:

FATAL: NoMethodError: deploy_branch[private_repo](my_repo::default line 52) had an error: NoMethodError: undefined method `dir' for nil:NilClass
### Steps to Reproduce:

Here is the code I'm using for the deploy resource:

deploy_branch "private_repo" do
  repo "#{deploy_repo}"
  user node['code']['user']
  branch "master"
  deploy_to "#{deploy_dir}"
  action :deploy
  ssh_wrapper "#{ssh_wrapper}"
  rollback_on_error  true
  symlink_before_migrate.clear
  create_dirs_before_symlink.clear
  purge_before_symlink.clear
  symlinks.clear
end
### Expected Result:

The branch in github gets deployed without error.
### Actual Result:

The error above in the scenario

**Comment by smurawski** [comment]
@Kendallsr Do you have a stacktrace from the error?

**Comment by blueo** [comment]
If it helps, I got this error on windows when the wrong user was passed - it fails to get the home dir in the git provider (line 284)

**Comment by Kendallsr** [comment]
I'd kinda given up on getting any feedback on this issue, I just happened to notice the email from blueo.  Here's my stacktrace:

Generated at 2015-05-08 16:02:16 -0700
NoMethodError: deploy_branch[private_repo] (llnw_shortname_create_script::default line 58) had an error: NoMethodError: undefined method `dir' for nil:NilClass
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/provider/git.rb:283:in `run_options'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/provider/git.rb:250:in `remote_resolve_reference'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/provider/git.rb:229:in `target_revision'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/provider/deploy/revision.rb:65:in `release_slug'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/provider/deploy.rb:55:in `load_current_resource'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/provider.rb:104:in `run_action'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/resource.rb:648:in `run_action'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/runner.rb:49:in `run_action'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/runner.rb:81:in `block (2 levels) in converge'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/runner.rb:81:in `each'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/runner.rb:81:in `block in converge'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/resource_collection.rb:98:in `block in execute_each_resource'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/resource_collection.rb:96:in `execute_each_resource'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/runner.rb:80:in `converge'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/client.rb:345:in `converge'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/client.rb:431:in `do_run'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/client.rb:227:in `run'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/application.rb:236:in `run_chef_client'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/application/solo.rb:226:in `block in run_application'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/application/solo.rb:218:in `loop'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/application/solo.rb:218:in `run_application'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/lib/chef/application.rb:55:in `run'
c:/opscode/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.16.4-x86-mingw32/bin/chef-solo:25:in `<top (required)>'
c:/opscode/chef/bin/chef-solo:23:in `load'
c:/opscode/chef/bin/chef-solo:23:in `<main>'

**Comment by blueo** [comment]
yeah that's failing on the same line as me `Etc.getpwnam(@new_resource.user).dir`. I'm not sure if it is because the user doesn't exist or the command doesn't have windows support (though [this](http://www.thecodingforums.com/threads/platform-independant-getpwnam.820204/) suggests it does).  Unfortunately that's the limit of my knowledge on the subject... I ended up just using the git provider directly to checkout the repo as deploy also failed to make a symlink on windows.

**Comment by Kendallsr** [comment]
Hey Blueo,

Thanks for the insight.  I suppose I could try it with my own username for the user param (or make a folder under the users dir to match) to see if that passes through.  The primary target for the deployment is a Linux box so it all worked once we placed it on there, but it would have been nice to have it work on my Windows box first for a local test.

**Comment by stuartpreston** [comment]
The deploy resource was removed from Chef 14.0. The resource is now part of the deploy_resource backwards compatibility cookbook available on the Supermarket. If this reproduces there, please raise an issue against the repo for the cookbook.
