### ISSUE TITLE
Conflicts with Omnibus rubygems and system rubygems

### ISSUE THREAD

**Issue by glasschef** [chef/chef#2548]
(This issue has been fixed in Chef 12, but not in 11-stable)

If the environment variables GEM_HOME and GEM_PATH get set by something else (like RVM, for example), then it will make an Omnibus-installed ruby unable to see or use its internal gems, completely breaking things like chef-client.

This can cause major problems for anyone trying to use Chef to manage nodes where ruby is used.

This had been previously filed as OC-4959 internally, and on the public-facing JIRA the following related tickets:

https://tickets.opscode.com/browse/CHEF-4296
https://tickets.opscode.com/browse/CHEF-4169
https://tickets.opscode.com/browse/CHEF-3581
https://tickets.opscode.com/browse/CHEF-4931

**Comment by lamont-granquist** [comment]
This is fixed in Chef-12.  Backporting to Chef-11 needs to be brought up with Charles Johnson since he owns the product now.

**Comment by jdmundrawala** [comment]
@lamont-granquist is right in that this is fixed in chef-12. The fix we employed in Chef 12 has the potential to break people in unknown ways, and it's these unknown unknowns which sort of scares me about doing this for Chef 11. I think it's better that we encourage people to move to Chef 12.
