### ISSUE TITLE
resource_matching_provider fails for :chef_gem

### ISSUE THREAD

**Issue by dpetzel** [chef/chef#2558]
Opening this after a quick exchange on the mailing list.

We use minitest-chef-handler for testing and we have a common pattern of doing something like this:

```
require_relative "support/test_helper.rb"

describe_recipe 'cookbook::default' do
  include MyCokbook::Test::Helper
  MiniTest::Chef::Resources.register_resource(:chef_gem)
  describe "gems" do
    it "ensures the netaddr gem is installed" do
      chef_gem("netaddr").must_be_installed
    end
  end
end
```

This worked on Chef 11, however is failing on Chef 12 with this error

```
ArgumentError: Cannot find a provider for chef_gem[netaddr] on centos version 6.5
from /opt/chef/embedded/apps/chef/lib/chef/platform/provider_mapping.rb:552:in `find_provider'
```

I was able to debug this as far as [resource_matching_provider](https://github.com/opscode/chef/blob/12.0.0/lib/chef/platform/provider_mapping.rb#L563) method, but then I started to get pretty lost in the bowels of the resource to provider magic. I tested a few different types of resources (package, file, gem_package, package). **gem_package also failed, but plain old package seemed to work**. Stepping through that code its hitting the rescue on the name error and returns nil.

```
[6] pry(Chef::Platform)> resource_type
=> <chef_gem[netaddr] @name: "netaddr" @noop: nil @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :install, :upgrade, :remove, :purge, :reconfig] @action: :install @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: nil @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @sensitive: false @candidate_version: nil @options: nil @package_name: "netaddr" @resource_name: :chef_gem @response_file: nil @response_file_variables: {} @source: nil @version: nil @timeout: 900 @gem_binary: "/opt/chef/embedded/bin/gem">
[7] pry(Chef::Platform)> Chef::Provider.const_get(resource_type.class.to_s.split('::').last)
NameError: uninitialized constant Chef::Provider::ChefGem
from (pry):13:in `const_get'
```

**Comment by thommay** [comment]
The minitest-chef-handler codebase has been updated to support chef 12, but unfortunately no new release of the gem has been made, and it's a third party tool.
@calavera would it be possible to get a release made?
