### ISSUE TITLE
chef 12 windows MSI not adding embedded/bin to the path

### ISSUE THREAD

**Issue by mwrock** [chef/chef#2559]
This is probably not the right place for this so if someone could comment on the right place. I'm happy to recreate in the right place.

This causes test-kitchen to fail during setup when it calls `gem install busser` but gem is not on the path. I confirmed this comparing a installed 11.16.4 client and 12.0.0-1 install.

**Comment by btm** [comment]
https://github.com/chef/omnibus-chef/pull/238
