### ISSUE TITLE
CookbookVersion#preferred_manifest_record can destroy file lists

### ISSUE THREAD

**Issue by hannesg** [chef/chef#2561]
Hi

`CookbookVersion#preferred_manifest_record` uses `map!` to strip the root_dir which leaves the `CookbookVersion` with a broken file list. This is often not a problem since an exception is raised right afterward. However, the exception may be caught or the `CookbookVersion` may be inspected later and then it gets weird. I think this is pretty easy to address by using `map` and a local variable.

Cheers'
Hannes

**Comment by MurgaNikolay** [comment]
HI.
Hi. I have a issue in my library.
If I use this method again and again after exception, I have empty file list in the end.
This bug located in: 
https://github.com/chef/chef/blob/master/lib/chef/cookbook_version.rb#L304

**Comment by dduponchel** [comment]
I have the same issue : my code uses the chef-helpers gem to do a `try_sources("#{application_name}/logger.erb", "default_logger.erb", :templates)`.
Here is a test case to reproduce this issue :
```
chef-solo -c solo.rb -j node.json
# with :
.
|-- cookbooks
|   `-- show_issue
|       |-- metadata.rb
|       |-- recipes
|       |   `-- default.rb
|       `-- templates
|           `-- default
|               `-- default.erb
|-- node.json
`-- solo.rb
```
node.json :
```json
{ "run_list": "recipe[show_issue]" }
```
solo.rb :
```ruby
cookbook_path "/home/vagrant/chef-issue/cookbooks"
```
cookbooks/show_issue/recipes/default.rb :
```
chef_gem 'chef-helpers' do
        compile_time false
end

require 'chef-helpers'

try_sources("not_found.erb", "default.erb", :templates)
try_sources("not_found.erb", "default.erb", :templates)
try_sources("not_found.erb", "default.erb", :templates)
try_sources("not_found.erb", "default.erb", :templates)
```

In` cookbook_version.rb` the `existing_files` has the following states :
- `["/home/vagrant/chef-issue/cookbooks/show_issue/templates/default/default.erb"]`
- `["templates/default/default.erb"]`
- `[nil]`

which leads to a 
```
NoMethodError
-------------
undefined method `[]' for nil:NilClass
```

**Comment by lamont-granquist** [comment]
bad line is currently 314:

https://github.com/chef/chef/blob/master/lib/chef/cookbook_version.rb#L314
