### ISSUE TITLE
knife bootstrap fails without any message

### ISSUE THREAD

**Issue by pssompura** [chef/chef#2590]
We use Scientific Linux 6.1 for our environment. While knife bootstrap the node few of the nodes fail without any message. It does not create node or client. However knife bootstrap is completely successful on some nodes. All nodes have exactly the same configuration. knife bootstrap creates the folders /etc/chef and /opt/chef.

$ knife bootstrap <HOSTNAME> -x root

Connecting to 
Failed to authenticate root - trying password auth
Enter your password: 
 Installing Chef Client...
 --2014-12-09 19:20:33--  https://www.opscode.com/chef/install.sh
 Resolving www.opscode.com... 184.106.28.90
 Connecting to www.opscode.com|184.106.28.90|:443... connected.
 HTTP request sent, awaiting response... 200 OK
 Length: 18285 (18K) [application/x-sh]
 Saving to: “STDOUT”

100%[======================================>] 18,285      --.-K/s   in 0.003s  

 2014-12-09 19:20:33 (5.10 MB/s) - written to stdout [18285/18285]

 Downloading Chef 11 for el...
 downloading https://www.opscode.com/chef/metadata?v=11&prerelease=false&nightlies=false&p=el&pv=6&m=x86_64
   to file /tmp/install.sh.16652/metadata.txt
 trying wget...
 url    https://opscode-omnibus-packages.s3.amazonaws.com/el/6/x86_64/chef-11.16.4-1.el6.x86_64.rpm
 md5    2355a7a93bc4cc353bee6de9e3bcb7ba
 sha256 278599ff185b680703e7a779db8674eeba843e9fe42a0ae06e01a9dfa9ac4d0e
 downloaded metadata file looks valid...
 downloading https://opscode-omnibus-packages.s3.amazonaws.com/el/6/x86_64/chef-11.16.4-1.el6.x86_64.rpm
   to file /tmp/install.sh.16652/chef-11.16.4-1.el6.x86_64.rpm
 trying wget...
 Comparing checksum with sha256sum...
 Installing Chef 11
 installing with rpm...
 warning: /tmp/install.sh.16652/chef-11.16.4-1.el6.x86_64.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
 Preparing...                ########################################### [100%]
    1:chef                   ########################################### [100%]
 Thank you for installing Chef!
 Starting first Chef Client run...

```
Folder contents are:
```

ls -ls /etc/chef /opt/chef
/etc/chef:
total 12
4 -rw-r--r-- 1 root root  154 Dec  9 19:20 client.rb
4 -rw-r--r-- 1 root root   16 Dec  9 19:20 first-boot.json
4 -rw------- 1 root root 1676 Dec  9 19:20 validation.pem

/opt/chef:
total 12
4 drwxr-xr-x 2 root root 4096 Dec  9 19:20 bin
4 drwxr-xr-x 7 root root 4096 Dec  9 19:20 embedded
4 -rw-r--r-- 1 root root 1899 Oct  7 22:40 version-manifest.txt

**Comment by thommay** [comment]
Hi,
sorry for the slow response. Did you ever get to the bottom of this problem? If it's still occurring, could you try running `sudo chef-client -j /etc/chef/first-boot.json` after bootstrapping fails and attach the output of that to this ticket?

**Comment by cheeseplus** [comment]
Closing given the age and lack of response.
