### ISSUE TITLE
git resource should honor deploy wrapper even for submodules

### ISSUE THREAD

**Issue by peterneubauer** [chef/chef#2601]
Hi there, with something like 

```
git "synch" do
  destination "#{Chef::Config[:file_cache_path]}/project"
  repository "git@github.com:test/project.git"
  revision "HEAD"
  action :sync
  enable_submodules true
  ssh_wrapper "#{Chef::Config[:file_cache_path]}/project_deploy_wrapper.sh"
end
```

The fetching of private submodule repos still requires login. Can you please change that to use the deploy wrapper even for submodules?

**Comment by msys-sgarg** [comment]
created a git repo with a submodule here - 

[](https://github.com/msys-sgarg/test-repo)

Created a test recipe file to create a git resource like this - 

```
git "synch" do
  destination "/vagrant"
  repository "git@github.com:msys-sgarg/test-repo.git"
  revision "HEAD"
  action :sync
  enable_submodules true
  ssh_wrapper "/vagrant/chef_repos/chef/lib/chef/project_deploy_wrapper.sh"
end

```
This is how my deploy_wrapper.sh file looks 

```
#!/bin/bash

/usr/bin/ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $@

```
Once I ran this recipe using chef-client. I see a git repo was created on the destination specified along with submodule git repo 

**Conclusion** - I don't see the error happening as of now and ssh command is run on submodule as well along with git repo.
