### ISSUE TITLE
chef-solo always throwing "invalid metadata" exceptions about 'name' attribute, even though it's included.

### ISSUE THREAD

**Issue by ibawolf** [chef/chef#2619]
I have a few ubuntu machines that I need to have configured the same, so I use chef-solo against chef cookbooks in a shared directory to accomplish this.  I've been using chef-solo for over a year, starting with chef version 10.  Today, after rebuilding the VMs using packer, which I use to test my cookbooks before I use them on the "real" machines, my cookbooks began failing with the error:

ERROR: Cookbook loaded at path(s) [/chef/cookbooks/ack-grep] has invalid metadata: The `name' attribute is required in cookbook metadata

I'm getting the same error for every cookbook that I have.

I've used these cookbooks many times on several machines, tested them repeatedly in VMs, but I noticed that the newly rebuilt VM had installed chef 12.0.0.  An older VM running chef 11 still works great.  I began investigating and researching this issue using google, and everything I found on the subject said to put the "name" entry in the metadata.rb file.  But my metadata.rb files already contain a "name" entry.  For example, here's my metadata file:

----  Begin metadata.rb ---------

name             'ack-grep'
maintainer       'Southwest Airlines'
maintainer_email 'Ron.Wolf@wnco.com'
license          'All Rights Reserved'
description      'Installs/Configures ack-grep'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'

------    End metadata.rb -------

The single recipe that is in this cookbook is very simple:

------  Begin default.rb  -------
#
# Cookbook Name:: ack-grep
# Recipe:: default

package 'ack-grep' do
  action :install
end

------    End default.rb  -------

One Article that I read while researching said creating a metadata.json file would help, so I ran the command:

-------------

knife cookbook metadata ack-grep

-------------

This command created a metadata.json file, which contained a similar "name" field with the same info as the metadata.rb file plus a lot of other info, all in json format.  But running the same chef-solo command again resulted in exactly the same error message.  

I'm guessing that since it's complaining about a missing field in the metadata, that exists in both the metadata.rb and the metadata.json files, that I'm missing something else and the error message is wrong.

**Comment by ibawolf** [comment]
I tried to use 'chef-client --local-mode', but although it worked well for testing a single cookbook, this was MUUUUUUUUCH slower than chef-solo, and I never was able to install a full physical machine with it.  While syncing all of the cookbooks to the chef-zero server, the server would crash and the whole install would fail.  

For a work-around, I've figured out how to go back and install the latest revision of chef v11, and am back to using chef-solo.  I just won't upgrade until you've fixed the issues with v. 12.

**Comment by esterp** [comment]
@ibawolf just wondering if you remember how you downgraded to chef v11?

**Comment by ibawolf** [comment]
I use the command:

curl -L http://www.opscode.com/chef/install.sh > /tmp/install.sh; chmod a+x /tmp/install.sh; /tmp/install.sh -v 11

**Comment by jekriske** [comment]
I am unable to reproduce this error with the same versions of chef-client and your metadata.rb and your recipe (assuming you meant ``__FILE__`` in metadata.rb). 

You must make sure when using chef-client 12.x that EVERY cookbook in your cookbook directory has a name. If even a single cookbook is missing a name it will not run. It doesn't matter if you're only trying to run a single cookbook.

**Comment by ibawolf** [comment]
Thank you, That was the piece of info I was lacking.  I had one cookbook that didn't have a 'name' entry in the metadata.rb file (not the one I was testing with).  That was the issue.
