### ISSUE TITLE
package's response_file attribute fails with local path, only accepts template or cookbook_file

### ISSUE THREAD

**Issue by tercenya** [chef/chef#2648]
### Scenario:

The [documentation](https://docs.chef.io/resource_package.html) describes the response_file attribute as "The direct path to the file used to pre-seed a package."   However, the [implementation](https://github.com/opscode/chef/blob/master/lib/chef/provider/package.rb#L201-L211) requires this to be a template or cookbook_file.  You get FileNotFound when the file exists and is local (or is being provided by a separate template directive).  At the very least the docs are misleading, but not supporting local files also seems to be a misfeature.
### Steps to Reproduce:

simple example

``` ruby
  package 'slapd' do
    action :install
    response_file '/path/to/existing/file/slapd.seed'
  end
```

There is also a use-case for accepting local path - namely when calling package from inside a provider, where there is no way to set the correct cookbook to get a the correct template or cookbook_file:

``` ruby
require 'chef/provider/lwrp_base'

class Chef
  class Provider
    class LdapDirectory < Chef::Provider::LWRPBase
      use_inline_resources if defined?(use_inline_resources)

      def whyrun_supported?
        true
      end

      action :create do
        template '/var/cache/chef/preseed/slapd.seed' do
          cookbook 'ldap'
          variables(config: new_resource)
        end

        package 'slapd' do
          action :install
          # No way to specify cookbook attribute, if we instead call
          #   response_file 'slapd.seed.erb'
          # Unfortunately, this fails as a local path
          response_file '/var/cache/chef/preseed/slapd.seed'  
        end
      end
    end
  end
end
```
### Expected Result:

Ideally, response_file should accept local paths.

Alternatively, documentation needs updated to clarify that the source of response_file must be a cookbook_file or template.  And you'll get a new bug on response_file needing a way to toggle the cookbook context, since you can't specify the correct template when inside a provider.
### Actual Result:

``` ruby
Chef::Exceptions::FileNotFound: apt_package[slapd] (...) had an error: 
  Chef::Exceptions::FileNotFound: No template or cookbook file found for response file ldap/slapd.seed.erb
```
##### Version:

chef 11.16.0 / 12.0.1
##### Environment:

ubuntu 14.04.1

**Comment by tpowell-progress** [comment]
Spent a few helping troubleshoot an Ubuntu cookbook only to run into this issue myself. I think it at least needs to have documentation updated.
