### ISSUE TITLE
windows_package is missing checksum attribute

### ISSUE THREAD

**Issue by bheuvel** [chef/chef#2659]
The Chef 12 client resource windows_package does not have a `checksum` attribute.
The windows cookbook has/had.
Perhaps due to the name clash, only the "internal" windows_package can be used?

In any way, this attribute is used by many (me thinks;) cookbooks for Windows apps, such as PowerShell or dotnetframework.

If the "internal" allways overrules the windows cookbook, this (currently) requires a lot of (community) cookbook adjustments before v12 can be used, not to mention loss of useful functionality.

Perhaps checksum should by added to the "parent" package resource?
How did they/others manage without it? :-)

**Comment by tyler-ball** [comment]
It seems valid to me to support the `checksum` attribute on our internal windows_package.  Until then, can you use the latest cookbook as @jdmundrawala mentions in #2668 ?

**Comment by btm** [comment]
https://github.com/chef/chef/pull/3318 is in progress to fix this.

**Comment by btm** [comment]
#3318 has been merged to master and will be in the next minor release.

**Comment by btm** [comment]
https://github.com/chef/chef/blob/6fe51cb8facde96fb5d40cd61d0a2ddb28e8b431/RELEASE_NOTES.md#windowspackage-resource-supports-urls
