### ISSUE TITLE
Chef-client local on windows give exception when trying to run cookbook: Invalid handle

### ISSUE THREAD

**Issue by pvandervelde** [chef/chef#2671]
### Version:
Chef 12.0.1

### Environment: 
Windows 2012R2 Datacenter in Azure

### Scenario:
Trying to set up a machine in Azure with Chef-client in local mode. I managed to get everything installed but chef-client is terminating with an invalid handle error.

### Steps to Reproduce:
I first install ruby 2.0.0.57600 and ruby2.devkit 4.7.2.2013022402 (using Chocolatey in case that matters). And then install the following gems:

    gem install win32-process --version 0.7.4 --no-document --conservative --minimal-deps --verbose
    gem install win32-nio --version 0.1.3 --no-document --conservative --minimal-deps --verbose
    gem install win32-service --version 0.8.6 --no-document --conservative --minimal-deps --verbose
    gem install win32-eventlog --version 0.6.2 --no-document --conservative --minimal-deps --verbose
    gem install windows-pr --version 1.2.4 --no-document --conservative --minimal-deps --verbose
    gem install chef --version 12.0.1 --no-document --conservative --minimal-deps --verbose

I've put the cookbook in `c:\installers\cookbooks`. The cookbook only has a default.rb file in the recipe directory containing:

    directory "c:/temp" do
        action :create
    end

    file "c:/temp/myfile.txt" do
      content 'This is a test'
    end

I then created a `knife.rb` file in the `~\.chef`directory that contains the following entries:

    cookbook_path ["c:\installers/cookbooks"]

Finally I call 

    chef-client -z -o azurejenkins

Note that all of this is done using by pushing all the files over a WinRM connection and then running a powershell script that takes the described actions. That powershell script is running as the local administrator and should thus have all the permissions required (and no UAC problems in theory).

### Expected Result:
I'm expecting chef to create the file with the given content.

### Actual Result:
I get the following output:

Running chef-client ...
    [2014-12-16T00:44:07+13:00] INFO: Started chef-zero at http://localhost:8889 with repository at C:/installers
        One version per cookbook
    [2014-12-16T00:44:35+13:00] INFO: *** Chef 12.0.1 ***
    [2014-12-16T00:44:35+13:00] INFO: Chef-client pid: 2980
    [2014-12-16T00:45:14+13:00] INFO: HTTP Request Returned 404 Not Found : Object not found: http://localhost:8889/nodes/ajm-350-001806
    [2014-12-16T00:45:14+13:00] WARN: Run List override has been provided.
    [2014-12-16T00:45:14+13:00] WARN: Original Run List: []
    [2014-12-16T00:45:14+13:00] WARN: Overridden Run List: [recipe[jenkinsmaster]]
    [2014-12-16T00:45:14+13:00] INFO: Run List is [recipe[jenkinsmaster]]
    [2014-12-16T00:45:14+13:00] INFO: Run List expands to [jenkinsmaster]
    [2014-12-16T00:45:14+13:00] INFO: Starting Chef Run for ajm-350-001806
    [2014-12-16T00:45:14+13:00] INFO: Running start handlers
    [2014-12-16T00:45:14+13:00] INFO: Start handlers complete.
    [2014-12-16T00:45:14+13:00] INFO: HTTP Request Returned 404 Not Found : Object not found: /reports/nodes/ajm-350-001806/runs
    [2014-12-16T00:45:15+13:00] ERROR: Running exception handlers
    [2014-12-16T00:45:15+13:00] ERROR: Exception handlers complete
    [2014-12-16T00:45:15+13:00] FATAL: Stacktrace dumped to C:/Users/TheBigCheese/.chef/local-mode-cache/cache/chef-stacktrace.out
    [2014-12-16T00:45:15+13:00] FATAL: Chef::Exceptions::Win32APIError: The handle is invalid.
    ---- Begin Win32 API output ----
    EXEC : System error Code: 6 [E:\documents\Petrik\documents\operations\cloudjenkins\src\build.master.msbuild]
    EXEC : System error Message: The handle is invalid. [E:\documents\Petrik\documents\operations\cloudjenkins\src\build.master.msbuild]
    ---- End Win32 API output ----

And the `stacktrace.out` file contains:
    Generated at 2014-12-16 00:45:15 +1300
    Chef::Exceptions::Win32APIError: The handle is invalid.
    ---- Begin Win32 API output ----
    System Error Code: 6
    System Error Message: The handle is invalid.
    ---- End Win32 API output ----

    C:/tools/ruby200/lib/ruby/gems/2.0.0/gems/chef-12.0.1/lib/chef/win32/error.rb:69:in `raise!'
    C:/tools/ruby200/lib/ruby/gems/2.0.0/gems/chef-12.0.1/lib/chef/win32/security.rb:377:in `open_process_token'
    C:/tools/ruby200/lib/ruby/gems/2.0.0/gems/chef-12.0.1/lib/chef/win32/security.rb:490:in `has_admin_privileges?'
    C:/tools/ruby200/lib/ruby/gems/2.0.0/gems/chef-12.0.1/lib/chef/client.rb:468:in `has_admin_privileges?'
    C:/tools/ruby200/lib/ruby/gems/2.0.0/gems/chef-12.0.1/lib/chef/client.rb:341:in `do_windows_admin_check'
    C:/tools/ruby200/lib/ruby/gems/2.0.0/gems/chef-12.0.1/lib/chef/client.rb:395:in `run'
    C:/tools/ruby200/lib/ruby/gems/2.0.0/gems/chef-12.0.1/lib/chef/application.rb:243:in `run_with_graceful_exit_option'
    C:/tools/ruby200/lib/ruby/gems/2.0.0/gems/chef-12.0.1/lib/chef/application.rb:220:in `block in run_chef_client'
    C:/tools/ruby200/lib/ruby/gems/2.0.0/gems/chef-12.0.1/lib/chef/local_mode.rb:38:in `with_server_connectivity'
    C:/tools/ruby200/lib/ruby/gems/2.0.0/gems/chef-12.0.1/lib/chef/application.rb:201:in `run_chef_client'
    C:/tools/ruby200/lib/ruby/gems/2.0.0/gems/chef-12.0.1/lib/chef/application/client.rb:355:in `block in interval_run_chef_client'
    C:/tools/ruby200/lib/ruby/gems/2.0.0/gems/chef-12.0.1/lib/chef/application/client.rb:345:in `loop'
    C:/tools/ruby200/lib/ruby/gems/2.0.0/gems/chef-12.0.1/lib/chef/application/client.rb:345:in `interval_run_chef_client'
    C:/tools/ruby200/lib/ruby/gems/2.0.0/gems/chef-12.0.1/lib/chef/application/client.rb:335:in `run_application'
    C:/tools/ruby200/lib/ruby/gems/2.0.0/gems/chef-12.0.1/lib/chef/application.rb:58:in `run'
    C:/tools/ruby200/lib/ruby/gems/2.0.0/gems/chef-12.0.1/bin/chef-client:26:in `<top (required)>'
    C:/tools/ruby200/bin/chef-client:23:in `load'
    C:/tools/ruby200/bin/chef-client:23:in `<main>'

**Comment by tyler-ball** [comment]
Paging @adamedx @jdmundrawala @randomcamel

**Comment by AnneTheAgile** [comment]
>I first install ruby 2.0.0.57600 and ruby2.devkit 4.7.2.2013022402 (using Chocolatey 
does it work with ruby 1.9 or have you not tried that? I'm trying to do similar and no luck yet.

**Comment by lamont-granquist** [comment]
Please install the omnibus packages on windows.  We don't support manual gem installs.
