### ISSUE TITLE
Chef 12 changes to checksum

### ISSUE THREAD

**Issue by tejaycar** [chef/chef#2681]
https://tickets.opscode.com/browse/CHEF-4647 changed the behavior of checksum for remotefile resources.  This is GREAT, but it is also a breaking change that needs to be documented in the release notes.  Furthermore, the documentation for the remote_file resource needs to be updated to reflect this change.

**Comment by lamont-granquist** [comment]
Yeah, looks like it somehow got missed out of the CHANGELOG, DOC_UPDATES, the release notes on the website, etc.
