### ISSUE TITLE
Chef client 12 does not execute guard resource in why run mode

### ISSUE THREAD

**Issue by hirose31** [chef/chef#2694]
Chef client 12 (12.0.1 and 12.0.3) does not execute command-line style guard resource **in why run mode**.

For example, following resource:

```
execute 'date' do
  only_if "[ ! -e /etc/passwd ]"
end
```

Chef 12 (why run) **ALWAYS** say `* execute[date] action run // Would execute date`.
Chef 11.14.6 (why run) say `* execute[date] action run (skipped due to only_if)`.

Chef 12 and ruby-block style guard (`only_if { ... }`) are OK (evaluate in why run mode).

**Comment by sersut** [comment]
I'm in favor of option 1 especially thinking that 1 has been the behavior prior to 12.0.0. Looks like this was a regression in the commit @tyler-ball pointed out.
