### ISSUE TITLE
ffi-yajl / yajl-ruby compatibility issues with Chef 12.0.1

### ISSUE THREAD

**Issue by jawroper** [chef/chef#2701]
Any recommendations on how to resolve this? The server is running a minimum image of CentOS6.5 and the only Ruby on the system was installed by the Chef RPM. It's a bit surprising the RPM installs gems with incompatible dependencies.

I have seen past posts that this issue has existed in previous releases of Chef.

**Comment by tyler-ball** [comment]
@jawroper do you get the same issue with 12.0.3?

**Comment by lamont-granquist** [comment]
this should be fixed now.
