### ISSUE TITLE
Circular dependency

### ISSUE THREAD

**Issue by sethvargo** [chef/chef#2703]
On 11-stable:

[`lib/util/selinux.rb`](https://github.com/opscode/chef/blob/11-stable/lib/chef/util/selinux.rb) requires [`chef/mixin/shell_out`](https://github.com/opscode/chef/blob/11-stable/lib/chef/mixin/shell_out.rb) which requires [`chef/config`](https://github.com/opscode/chef/blob/11-stable/lib/chef/config.rb) which [requires selinux](https://github.com/opscode/chef/blob/11-stable/lib/chef/config.rb#L25).

The side effect is that it is now incredibly difficult to load pieces of Chef (as required in ChefSpec). The mixin is [not loaded in time](https://travis-ci.org/sethvargo/chefspec/jobs/45103715). The ChefSpec build is currently failing because it is not possible to *just* load `chef/provider`.

The reason we do not want to load all of Chef is because Chef takes ~5s to load on my machine, and it has been reported to load at times ~30s on other other Windows machines. Users do not want to wait even 1s for their tests to load.

This bug appears to have been fixed or is not present in Chef 12.

/cc @danielsdeleo because you'll think this is fun :smile:

**Comment by lamont-granquist** [comment]
Pretty sure we fixed this with all the chef-config extraction work.
