### ISSUE TITLE
Chef Solo 12.x '--no-fork' is broken

### ISSUE THREAD

**Issue by fujin** [chef/chef#2709]
It looks like the code in application.rb regarding specific recipes https://github.com/opscode/chef/blob/12.0.3/lib/chef/application.rb#L203-L205 introduces a new cli/cfg parameter which was not added to Solo, so it ends up passing a nil through from `Chef::Config[:specific_recipes]` inside solo.rb @ https://github.com/opscode/chef/blob/12.0.3/lib/chef/application/solo.rb#L217

Looks like introducing the cli argument from client.rb into solo.rb outta fix it, but I haven't tested that yet.

**Comment by tyler-ball** [comment]
This looks to me like https://github.com/opscode/chef/blob/12.0.3/lib/chef/application/client.rb#L255 needs to be copied into solo.rb or into the super `reconfigure` method in application.rb

**Comment by fujin** [comment]
hey @tyler-ball thanks for checking. I do have that `Chef::Config[:specific_recipes]` line already, but the solo application is bailing saying that `cli_arguments` is invalid. I'll take another look soon.

I don't think it was intended for solo to have this feature? (it looks like it was half added) which explains the lack of banner updates. I think it would be fine for both solo/client to have this feature.

**Comment by fujin** [comment]
not sure if adding it to application.rb was the right call now :question:

**Comment by tyler-ball** [comment]
@fujin Would you mind opening a PR and linking that to this bug?  That will make it easier to review the code.

I don't think we want to modify application.rb.  Knife is also a `Chef::Application` and it has a different CLI contract.  The applications that look like they need this are application/apply.rb, application/client.rb and application/solo.rb

**Comment by fujin** [comment]
the PR is here: https://github.com/opscode/chef/pull/2710 I'll move the specific recipes to apply,client,solo despite the duplication

**Comment by juliandunn** [comment]
Closing, #2710 was merged
