### ISSUE TITLE
Error executing action `create` on resource 'private-chef_pg_database[opscode-pgsql]'

### ISSUE THREAD

**Issue by veera1989** [chef/chef#2715]
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
execute[create_database_opscode-pgsql] (/opt/opscode/embedded/cookbooks/private-chef/providers/pg_database.rb line 13) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
STDOUT:
STDERR: createdb: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
---- End output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
Ran createdb --template template0 --encoding UTF-8 opscode-pgsql returned 1

**Comment by manderson26** [comment]
Filing this under chef-server, since this appears to be an install failure. 

More detail would be welcome, including:
* What command was being run. Was this an install?
* What version of chef-server
* What OS
