### ISSUE TITLE
At least the knife upload/environment Subcommands Do Not Properly Validate Objects

### ISSUE THREAD

**Issue by sean-horn** [chef/chef#2731]
I can upload an environment which is not valid using `knife upload ...`, like this one
https://gist.github.com/sean-horn/1a7e761958c3486d5f66

This environment then breaks Manage's ability to display it.

We should ensure that an object like this gets kicked back.

Then, when I go to check it out, it also breaks `knife environment show ...`

```
knife environment show test-sean-environment -c .chef/knife-seantest-centos-6.3-chef12-rc4.rb
ERROR: Chef::Exceptions::ValidationFailed: Option default_attributes must be a kind of Hash!  You  passed someplace_wsol_inhouse.
```

**Comment by echohack** [comment]
Additionally, you won't be able to delete the environment using `knife environment delete my_environment`.

As a workaround you can issue a raw http request to the Chef server to remove the rogue environment as so:
`knife raw -m DELETE "https://chef.example.com/organizations/example/environments/my_environment"`

**Comment by stevendanna** [comment]
@sean-horn Thanks for filing this.  This is an interesting one.  To clarify, the error you get when loading it is:

```
chef > Chef::Environment.load("test-sean-environment")
Chef::Exceptions::ValidationFailed: Option default_attributes must be a kind of Hash!  You passed #<Chef::Environment:0x007f8f1a35dcd8 @name="someplace_wsol_inhouse", @description="", @default_attributes={"someplace-wsol"=>{"customer-number"=>"0000001", "deployment-type"=>"vsso", "wsol-customer-root"=>"\\\\WSOL-3333333FS\\wsolsupport\\Setup\\ClientInfo\\", "wsol-bpr-root"=>"f:/BPRDW/"}, "app-server"=>{"vsso"=>{"worksmart-wsapi"=>{"agency"=>"0000000-1"}}}}, @override_attributes={}, @cookbook_versions={}>.
```

When using `knife environment from file` this is caught before upload, but when `knife upload` is used, the upload succeeds but then your chef-client will fail.

Re @echohack's issue, that is being tracked here: https://github.com/opscode/chef/issues/2402

**Comment by lamont-granquist** [comment]
closing this in favor of tracking it in #8829
