### ISSUE TITLE
knife should use Chef::REST or Chef::ServerAPI correctly

### ISSUE THREAD

**Issue by kwilczynski** [chef/chef#2737]
It would be beneficial to certain customers if `knife` (including number of sub-commands e.g., `ssl fetch`, etc.), would respect HTTP/HTTPS proxy when such is present and set.

This is a feature request driven by questions from our customers who have heavily policed network environments (i.e., enterprises, banks, etc.).

**Comment by poelzi** [comment]
we see this problem as well, the rest seems to respect proxy settings

**Comment by lamont-granquist** [comment]
Some of this may have been fixed in the last proxy overhaul, but some knife commands are probably not using Chef::REST / Chef::ServerAPI correctly.

**Comment by kwilczynski** [comment]
Thank you @lamont-granquist :+1:
