### ISSUE TITLE
node attribute method_missing gives different results to node['attribute'] in Chef 12.0.3 

### ISSUE THREAD

**Issue by phcyso** [chef/chef#2745]
The issue Is accessing attributes in a wrapper cookbook.
in my base cookbook i have the following attributes:

    default['passenger']['version']     = '4.0.14'
    default['passenger']['root_path']   = "passenger-#{passenger['version']}"
    default['passenger']['root_path_2']   = "passenger-#{passenger['version']}"

and in the wrapper cookbook i override them:

    default['passenger']['version']     = '4.0.57'
    default['passenger']['root_path']   = "passenger-#{node['passenger']['version']}"
    default['passenger']['root_path_2']   = "passenger-#{passenger['version']}"

in this example the 'root_path'  attribute gets set correctly with a version of "4.0.57' but the 'root_path_2' variable has a version of '4.0.14'

in the wrapper cookbook 
Running `node['passenger'].to_hash` returns: ` {"version"=>"4.0.57", "root_path"=>"passenger-4.0.57", "root_path_2"=>"passenger-4.0.14"}`
and `node.passenger.to_hash` just returns `{"version"=>"4.0.14"}`

This may be related to issue #2712 or #2700 

I have a example at the following repo:
https://github.com/phcyso/chef_attribute_weirdness
There is a vagrantfile in that repo i have been using for testing.
The issue does not occur in chef-client 11.16.4 

Please let me know if there is any further information i can provide that would help resolve this as it is is stopping our org from updating to chef-client 12

**Comment by lamont-granquist** [comment]
closed by #2753
