### ISSUE TITLE
Specs fail when /etc/chef/client.rb is present and not readable.

### ISSUE THREAD

**Issue by ranjib** [chef/chef#2747]
While trying to set up a build grid for Chef, i realized the if the host running unit tests (rake spec:all) has /etc/chef/client.rb file present and the spec running user does not read permissions, then 11 tests fails. If /etc/chef/client.rb file is absent or the spec running user get read privileges on the /etc/chef/client.rb, then those test passes,

Following is the list of specs:
./spec/unit/application/client_spec.rb:58
./spec/unit/application/client_spec.rb:87
./spec/unit/application/client_spec.rb:100
./spec/unit/application/client_spec.rb:114
./spec/unit/application/client_spec.rb:119
./spec/unit/application/client_spec.rb:151
./spec/unit/application/client_spec.rb:151
./spec/unit/application/client_spec.rb:151
./spec/unit/application/client_spec.rb:151
./spec/unit/application/client_spec.rb:158
./spec/unit/application/client_spec.rb:158
./spec/unit/application/client_spec.rb:250

The build environment is:
ubuntu 14.04,
chef - master branch
ruby 2.2

**Comment by lamont-granquist** [comment]
@tball @mcquin this is trolling me as well, it looks like its from audit mode tests and you need to stub out a File.exist? check for /etc/chef/client.pem somewhere.
