### ISSUE TITLE
supports :status => false is ignored on RHEL platforms

### ISSUE THREAD

**Issue by juliandunn** [chef/chef#2756]
Not all rc scripts support 'status' -- many vendor scripts don't have such a thing. These scripts will break a Chef run because the provider forcibly sets the service resource to support 'status':

https://github.com/opscode/chef/blob/master/lib/chef/provider/service/redhat.rb#L42

This breaks Chef, but I'm not totally sure why. Normally before taking a `:start` action, Chef should check status, and that would return exit code 1 in this situation, so the only thing I can think of is that it's blindly ignoring the exit 1 (maybe another bug...?) The output I'm seeing is that Chef then just blindly tries to start an already-running service, causing the below error.

```
---- Begin output of /sbin/service jira start ----
STDOUT: Starting jira
STDERR:
---- End output of /sbin/service jira start ----
Ran /sbin/service jira start returned 1
    # In /var/chef/cache/cookbooks/jira/recipes/server.rb

    100: service 'jira' do
    101:   supports :status => false
    102:   action [:enable, :start]
    103: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/jira/recipes/server.rb:100:in `from_file'

    service("jira") do
      action [:enable, :start]
      supports {:status=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "jira"
      enabled true
      pattern "jira"
      declared_type :service
      cookbook_name "jira"
      recipe_name "server"
    end
```

**Comment by lamont-granquist** [comment]
This is a dup of a bunch of other bugs.

**Comment by tas50** [comment]
Closing this out since RHEL is going full systemd and the need to fix this is considered low.
