### ISSUE TITLE
Centos 6.5 Service process Restart: process dead but pid file exists 

### ISSUE THREAD

**Issue by DavidSie** [chef/chef#2764]
When I'm running Chef-Client:
service  "mysqld" do
  action :restart
end
the result is : 
Processing service[mysqld] action restart ()
 INFO: service[mysqld] restarted

but when I check service manually I get:
mysqld dead but pid file exists

**Comment by lamont-granquist** [comment]
That doesn't look like a chef bug that looks like the service restarted successfully but then crashed and left a pid file.  You need to check your mysqld logs and see what happened.

**Comment by DavidSie** [comment]
Yes I figure out that when I'm run some process on Docker, with next opening I got process down (as it should be) but the pid file remains
