### ISSUE TITLE
Consistent log_level after knife bootstrap

### ISSUE THREAD

**Issue by alexpop** [chef/chef#2768]
Linux nodes are bootstraped with no 'log_level' entry in client.rb, defaulting to :auto

Windows nodes are bootstraped with 'log_level        :info' in client.rb

I haven't tested other operating systems, but please have consistency of log_level across platforms.

**Workstation:**
[07:53:29 ~/gitin/chef-repo (master) ]$ chef -v
Chef Development Kit Version: 0.3.5

**Nodes:**
CentOS 6.6 and Windows2012r2 bootstrapped with chef-client 12.0.3

**Comment by lamont-granquist** [comment]
"knife bootstrap windows" is from knife-windows so this issue should probably go under that repo to remote that default?
