### ISSUE TITLE
knife cookbook site unshare redirect fails due to old supermarket.getchef.com domain.

### ISSUE THREAD

**Issue by petecheslock** [chef/chef#2777]
knife cookbook site unshare my-cookbook
Do you really want to unshare the cookbook mycookbook? (Y/N)y
ERROR: Invalid Redirect: DELETE request was redirected from https://supermarket.getchef.com/api/v1/cookbooks/my-cookbook to https://supermarket.chef.io/api/v1/cookbooks/my-cookbook. Only GET and HEAD supp
ort redirects.
Change your server location in knife.rb to the server's FQDN to avoid unwanted redirections.

Looks like it's hard coded in a few spots in the various `knife cookbook site` knife commands.  Although I tried to manually change them to the right location but the unshare didn't work so maybe this is set elsewhere?  

https://github.com/opscode/chef/blob/master/lib/chef/knife/cookbook_site_unshare.rb#L44

**Comment by lamont-granquist** [comment]
Yeah, when we switched to supermarket the way that happened was knife-supermarket was written as a plugin that implements only uploads, but the old knife cookbook site commands were left untouched and largely broken, and its kind of a mess.  Either the old functionality needs to be fully ported to knife-supermarket and knife cookbook site commands need to just raise an error to point people at knife-supermarket or else knife-supermarket needs to be merged into knife cookbook site commands and all the bugs need to get fixed.

**Comment by prometheanfire** [comment]
:+1:
