### ISSUE TITLE
Specifying Version for yum_package reports "up to date", but is still old version.

### ISSUE THREAD

**Issue by whiteadam** [chef/chef#2778]
### Version:
Seen on :latest, 11.10.4, & 11.18.0

### Environment:
Reproduced on local RHEL 6.5 and Amazon Linux 2014.09

### Scenario:
yum_package bash >= 4.1.2-29.el6 reports up to date on converge, but on a login and checking "yum list installed |grep bash", it shows the old version. Confirmed it is older version by running yum clean all, re-converge, and re-checking, then manual yum update bash.

### Steps to Reproduce:
1. Put yum_package 'bash >= 4.1.2-29.el6' into recipe for EL6 (or 'bash >= 4.1.2-15.23.amzn1' for Amazon)
2. Converge and see something along the lines of: * yum_package[bash >= 4.1.2-15.23.amzn1] action install [2015-01-20T18:58:32+00:00] INFO: Processing yum_package[bash >= 4.1.2-15.23.amzn1] action install (up to date)
3. Log into server and run: sudo yum list installed |grep bash
4. Version should NOT match, eg: bash.x86_64  4.1.2-15.21.amzn1  installed
5. Profit

### Expected Result:
1. To see up to date
2. For the version specified to be installed (or greater)

### Actual Result:
Specified version is not installed, but states that it is up-to-date.

**Comment by ojab** [comment]
Same here, [-l debug output with some addition logging](https://gist.githubusercontent.com/ojab/58a6b6d51b4d347d777a/raw/78ac62390822a97106fe31a346483f652b64bdf4/gistfile1.txt).
AFAIU basically new_version_array is called first time before the version parsing, so  @new_version_array becomes [nil] and is not filled with actual version on subsequent runs.

Will try to investigate this later today or tomorrow.

**Comment by whiteadam** [comment]
@ojab Thanks for validating that I'm not crazy. I figured this would be a much bigger deal than it is, but I guess not. One of my primary uses of Chef is rolling out security updates, but it appears that they haven't been working for some time.

**Comment by jdmundrawala** [comment]
verified. As a workaround, you can specify the exact version:
```ruby
yum_package 'bash' do
  version '4.1.2-29.el6'
end
```

**Comment by ojab** [comment]
So basically pkgs with version constraints are parsed in parse_dependency [here](https://github.com/chef/chef/blob/master/lib/chef/provider/package/yum.rb#L1049), but new_version_array is called in the second arg, which sets @new_version_array to [nil].
Looks like it was unfortunate clash between 40c1983eb3e59b56ecf71562050cfb926b90f54e & 3386dff3694a229993eb11c21baa493fa09a025f: if I revert new_version_array change in 40c1983eb3e59b56ecf71562050cfb926b90f54e -- package installs correctly.
Trying to understand how it was supposed to work and why there is new_version_array in package.rb that is used only in yum.rb :/

**Comment by ojab** [comment]
And after some digging I think that reverting new_version_array change is actually a proper fix.

**Comment by whiteadam** [comment]
Thanks @ojab and @jdmundrawala !

**Comment by whiteadam** [comment]
Sorry to be daft, but @btm or @ojab, do you know what version of Chef-Client this update will be in? I have a feeling, when I update it, I will have lots of servers updating packages :)

**Comment by ojab** [comment]
Chef 12.4.0 will surely has this fix, not so sure about 12.3 branch.

**Comment by whiteadam** [comment]
Thanks @ojab I'm still on 11, so I guess I need to make a game plan :)
