### ISSUE TITLE
knife bootstrap windows winrm - wrong chef server url

### ISSUE THREAD

**Issue by zetan503** [chef/chef#2796]
I'm trying to bootstrap Windows nodes but the chef server-url is not being passed correctly resulting in connection refused to http://localhost:8889/ during client.pem generation.

Oracle Linux 6.6 chef-server
chef-server-11.1.6-1.el6.x86_64
chef-12.0.3-1.x86_64

Remote host is Windows 2012

[root@chef-server ~]# knife bootstrap windows winrm 10.86.22.214 -N build-win-02 -E test --server-url https://chef-server.test.com:444 -x Administrator -l debug

Waiting for remote response before bootstrap.Enter your password:
10.86.22.214 .
10.86.22.214 Response received.
Remote node responded after 0.04 minutes.
Bootstrapping Chef on 10.86.22.214
10.86.22.214 "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-24081-1422057699.bat" chunk 1"
10.86.22.214 "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-24081-1422057699.bat" chunk 2"
10.86.22.214 "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-24081-1422057699.bat" chunk 3"
10.86.22.214 "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-24081-1422057699.bat" chunk 4"
10.86.22.214 "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-24081-1422057699.bat" chunk 5"
10.86.22.214 "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-24081-1422057699.bat" chunk 6"
10.86.22.214 "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-24081-1422057699.bat" chunk 7"
10.86.22.214 "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-24081-1422057699.bat" chunk 8"
10.86.22.214 "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-24081-1422057699.bat" chunk 9"
10.86.22.214 "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-24081-1422057699.bat" chunk 10"
10.86.22.214 "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-24081-1422057699.bat" chunk 11"
10.86.22.214 "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-24081-1422057699.bat" chunk 12"
10.86.22.214 "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-24081-1422057699.bat" chunk 13"
10.86.22.214 "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-24081-1422057699.bat" chunk 14"
10.86.22.214 "Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-24081-1422057699.bat" chunk 15"
10.86.22.214 Checking for existing directory "C:\chef"...
10.86.22.214 Existing directory not found, creating.
10.86.22.214
10.86.22.214 C:\Users\Administrator>(
10.86.22.214 echo.url = WScript.Arguments.Named("url")
10.86.22.214  echo.path = WScript.Arguments.Named("path")
10.86.22.214  echo.proxy = null
10.86.22.214  echo.Set objXMLHTTP = CreateObject("MSXML2.ServerXMLHTTP")
10.86.22.214  echo.Set wshShell = CreateObject( "WScript.Shell" )
10.86.22.214  echo.Set objUserVariables = wshShell.Environment("USER")
10.86.22.214  echo.
10.86.22.214  echo.rem http proxy is optional
10.86.22.214  echo.rem attempt to read from HTTP_PROXY env var first
10.86.22.214  echo.On Error Resume Next
10.86.22.214  echo.
10.86.22.214  echo.If NOT (objUserVariables("HTTP_PROXY") = "") Then
10.86.22.214  echo.proxy = objUserVariables("HTTP_PROXY")
10.86.22.214  echo.
10.86.22.214  echo.rem fall back to named arg
10.86.22.214  echo.ElseIf NOT (WScript.Arguments.Named("proxy") = "") Then
10.86.22.214  echo.proxy = WScript.Arguments.Named("proxy")
10.86.22.214  echo.End If
10.86.22.214  echo.
10.86.22.214  echo.If NOT isNull(proxy) Then
10.86.22.214  echo.rem setProxy method is only available on ServerXMLHTTP 6.0+
10.86.22.214  echo.Set objXMLHTTP = CreateObject("MSXML2.ServerXMLHTTP.6.0")
10.86.22.214  echo.objXMLHTTP.setProxy 2, proxy
10.86.22.214  echo.End If
10.86.22.214  echo.
10.86.22.214  echo.On Error Goto 0
10.86.22.214  echo.
10.86.22.214  echo.objXMLHTTP.open "GET", url, false
10.86.22.214  echo.objXMLHTTP.send()
10.86.22.214  echo.If objXMLHTTP.Status = 200 Then
10.86.22.214  echo.Set objADOStream = CreateObject("ADODB.Stream")
10.86.22.214  echo.objADOStream.Open
10.86.22.214  echo.objADOStream.Type = 1
10.86.22.214  echo.objADOStream.Write objXMLHTTP.ResponseBody
10.86.22.214  echo.objADOStream.Position = 0
10.86.22.214  echo.Set objFSO = Createobject("Scripting.FileSystemObject")
10.86.22.214  echo.If objFSO.Fileexists(path) Then objFSO.DeleteFile path
10.86.22.214  echo.Set objFSO = Nothing
10.86.22.214  echo.objADOStream.SaveToFile path
10.86.22.214  echo.objADOStream.Close
10.86.22.214  echo.Set objADOStream = Nothing
10.86.22.214  echo.End if
10.86.22.214  echo.Set objXMLHTTP = Nothing
10.86.22.214 ) 1>C:\chef\wget.vbs
10.86.22.214
10.86.22.214 C:\Users\Administrator>(
10.86.22.214 echo.param(
10.86.22.214  echo.   [String] $remoteUrl,
10.86.22.214  echo.   [String] $localPath
10.86.22.214  echo.)
10.86.22.214  echo.
10.86.22.214  echo.$webClient = new-object System.Net.WebClient;
10.86.22.214  echo.
10.86.22.214  echo.$webClient.DownloadFile($remoteUrl, $localPath);
10.86.22.214 ) 1>C:\chef\wget.ps1
10.86.22.214
10.86.22.214 C:\Users\Administrator>(
10.86.22.214
10.86.22.214
10.86.22.214
10.86.22.214 )
10.86.22.214 Detected Windows Version 6.2 Build 9200
10.86.22.214
10.86.22.214 C:\Users\Administrator>goto Version6.2
10.86.22.214
10.86.22.214 C:\Users\Administrator>goto architecture_select
10.86.22.214
10.86.22.214 C:\Users\Administrator>goto Architecture
10.86.22.214
10.86.22.214 C:\Users\Administrator>goto ArchitectureAMD64
10.86.22.214
10.86.22.214 C:\Users\Administrator>goto install
10.86.22.214 Checking for existing downloaded package at "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
10.86.22.214 Found existing downloaded package, deleting.
10.86.22.214 Attempting to download client package using cscript...
10.86.22.214
10.86.22.214 C:\Users\Administrator>cscript /nologo C:\chef\wget.vbs /url:"http://10.197.163.16/sysrepo/chef-client-12.0.3-1.msi" /path:"C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
10.86.22.214 Failed download: download completed, but downloaded file not found
10.86.22.214 Warning: Failed to download "http://10.197.163.16/sysrepo/chef-client-12.0.3-1.msi" to "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
10.86.22.214 Warning: Retrying download with PowerShell if available...
10.86.22.214 powershell.exe -ExecutionPolicy Unrestricted -NoProfile -NonInteractive -File  C:\chef\wget.ps1 "http://10.197.163.16/sysrepo/chef-client-12.0.3-1.msi" "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
10.86.22.214 Download via PowerShell succeeded.
10.86.22.214 Installing downloaded client package...
10.86.22.214
10.86.22.214 C:\Users\Administrator>msiexec /qn /log "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-msi26714.log" /i "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"

10.86.22.214 Successfully installed Chef Client package.
10.86.22.214 Installation completed successfully
10.86.22.214 Writing validation key...
10.86.22.214 Validation key written.
10.86.22.214
10.86.22.214 C:\Users\Administrator>(
10.86.22.214 echo.log_level        :info
10.86.22.214  echo.log_location     STDOUT
10.86.22.214  echo.
10.86.22.214  echo.chef_server_url  "http://localhost:8889"
10.86.22.214  echo.validation_client_name "chef-validator"
10.86.22.214  echo.client_key        "c:/chef/client.pem"
10.86.22.214  echo.validation_key    "c:/chef/validation.pem"
10.86.22.214  echo.
10.86.22.214  echo.file_cache_path   "c:/chef/cache"
10.86.22.214  echo.file_backup_path  "c:/chef/backup"
10.86.22.214  echo.cache_options     ({:path => "c:/chef/cache/checksums", :skip_expires => true})
10.86.22.214  echo.
10.86.22.214  echo.node_name "build-win-02"
10.86.22.214 ) 1>C:\chef\client.rb
10.86.22.214
10.86.22.214 C:\Users\Administrator>(echo.{"run_list":[]}) 1>C:\chef\first-boot.json
10.86.22.214 Starting chef to bootstrap the node...
10.86.22.214
10.86.22.214 C:\Users\Administrator>SET "PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\opscode\chef\bin;C:\ruby\bin;C:\opscode\chef\bin;C:\opscode\chef\embedded\bin"
10.86.22.214
10.86.22.214 C:\Users\Administrator>chef-client -c c:/chef/client.rb -j c:/chef/first-boot.json -E test
10.86.22.214 [2015-01-24T00:03:37+00:00] INFO: *** Chef 12.0.3 ***
10.86.22.214 [2015-01-24T00:03:37+00:00] INFO: Chef-client pid: 2780
10.86.22.214 [2015-01-24T00:03:43+00:00] INFO: Client key c:/chef/client.pem is not present - registering
10.86.22.214 [2015-01-24T00:03:46+00:00] ERROR: Connection refused connecting to http://localhost:8889/clients, retry 1/5
10.86.22.214 [2015-01-24T00:03:53+00:00] ERROR: Connection refused connecting to http://localhost:8889/clients, retry 2/5
10.86.22.214 [2015-01-24T00:04:00+00:00] ERROR: Connection refused connecting to http://localhost:8889/clients, retry 3/5
10.86.22.214 [2015-01-24T00:04:07+00:00] ERROR: Connection refused connecting to http://localhost:8889/clients, retry 4/5

[root@chef-server ~]# more /root/.chef/knife.rb
log_level                :info
log_location             STDOUT
node_name                'root'
client_key               '/root/.chef/root.pem'
validation_client_name   'chef-validator'
validation_key           '/etc/chef-server/chef-validator.pem'
chef_server_url          'https://chef-server.test.com:444'
syntax_check_cache_path  '/root/.chef/syntax_check_cache'
cookbook_path [ '/root/csec-chef-repo/cookbooks' ]

[root@chef-server ~]# more /etc/chef/client.rb
chef_server_url "https://chef-server.test.com:444"
validation_client_name "chef-validator"
node_name "chef-server"

Dir.glob(File.join("/etc/chef", "client.d", "*.rb")).each do |conf|
  Chef::Config.from_file(conf)
end

**Comment by gleg** [comment]
Did you find a work around for this issue? My windows nodes will not register either because of this. Thanks

**Comment by zetan503** [comment]
1) Chef 12.x clients (Windows) don't want to key exchange with chef 11 servers.
2) "-l debug" was invalid syntax for knife bootstrap, causing the server url to be changed (chef zero?)

**Comment by smurawski** [comment]
To get verbose logging for knife, you can use -V or -VV for very verbose.  -l is not a valid switch on for knife and can cause parameter parsing issues.
