### ISSUE TITLE
Possibly support passing an array to creates attribute for execute

### ISSUE THREAD

**Issue by evaryont** [chef/chef#2798]
This way if a command needs to generate multiple files (like a multitude of symlinks for a dotfiles deployment script) and is interrupted in the middle of the run, chef will detect that only some of the passed list of files exist an re-run the command.

Thus:

```ruby
execute "deploy dotfiles" do
  command "./symlink.sh"
  creates ["/home/user/.bashrc", "/home/user/.vimrc", "/home/user/.irbrc"]
end
```

Will only not be run if all 3 files do exist.

**Comment by ranjib** [comment]
Currently this can be done using the not_if predicate. Im unsure if the scenario you have described is common enough to put in core chef,

```ruby
execute "deploy dotfiles" do
  command "./symlink.sh"
  not_if do
    %w{/home/user/.bashrc /home/user/.vimrc /home/user/.irbrc}.all?{|f| File.exist?(f) }
  end
end
```

**Comment by evaryont** [comment]
@ranjib indeed, and that is what I do currently.

I do it often in my own personal cookbooks, but perhaps I just do weird things.

**Comment by lamont-granquist** [comment]
Yeah the example above also looks like it'd be better handled by 3 symlink resources rather than an execute to a shell script with a array of creates.

**Comment by evaryont** [comment]
The particular example, perhaps, but the shell script I use actually
generates ~20 symlinks and then does some prepatory work. (Lots of
dotfiles, compiling for CmdT vim plugin, ensuring termporary directories
exist for caches, etc.) The example is a bit contrived, but I think it
illustrates my point.

But it's also quite true that an array of creates can usually be worked
around.

**Comment by lamont-granquist** [comment]
Usually when I do something like that I ensure that the script is idempotent itself and then simply always call it.  Otherwise if you can wind up with edge conditions when chef doesn't enforce idempotency correctly (either running it when it shouldn't or not running it when it should), and enforcing or duplicating the idempotency of the script in the chef code violates separation of concerns.

**Comment by thommay** [comment]
I think Lamont's advice to just ensure that your script is entirely idempotent (or just drops a flag file at the end which you can use as the creates target) is probably the correct answer here.
