### ISSUE TITLE
Chef client does not accept relative dir

### ISSUE THREAD

**Issue by h4ck3rm1k3** [chef/chef#2809]
as normal user, If I invoke

```
chef-client --local --config config_dir/file.rb
```

I get

```
[2015-01-25T18:32:19-06:00] ERROR: Permission denied @ dir_s_mkdir - /config_dir
```

And if I use a abs path it works!

**Comment by thommay** [comment]
This needs a thorough review of all config loading code to ensure it all DTRT.

**Comment by vsingh-msys** [comment]
Have tested with chef-15 seems it working as expected.
