### ISSUE TITLE
man pages not installed on OS X

### ISSUE THREAD

**Issue by wyardley** [chef/chef#2818]
OS X Chef DK 0.3.6 doesn't appear to install man pages:
% man chef-client 
No manual entry for chef-client
% man chef
No manual entry for chef
% man knife 
No manual entry for knife

Since it appears that man pages can be automatically generated, and are already installed on other platforms, it seems like it would be a good idea to install them on OS X. I know that there is help for the CLI apps if you use '-h' or run without arguments, and I know that some programs (like SVN) decided that man pages are unnecessary, but it really is a standard thing that should always exist on UNIX-y systems, and, more to the point, should not be difficult to add.

**Comment by thommay** [comment]
Hi, this is a bug in omnibus (our packaging system); I've created a bug report there (chef/omnibus-chef#401)
