### ISSUE TITLE
Kitchen converge fails with 1.6GB of cookbook files

### ISSUE THREAD

**Issue by Maniacal** [chef/chef#2824]
Details:  https://gist.github.com/Maniacal/1bc92cfc566b1a4e041c

In my case I happened to have 4 files over 350MB each for a total of about 1.6GB.  The files just happened to be staged there, won't be part of the finished cookbook, but I noticed it causes kitchen converge to fail (otherwise blank cookbook) with every OS I tried (ubuntu 12.04, centos 6.5, 6.6) when using chef 12.0.x and chefdk 0.3.5 or 0.3.6 (didn't test any other versions of chefdk).  Same error(s) every time (see above gist).

**Comment by lamont-granquist** [comment]
That's failing in test-kitchen not chef-client, you haven't even invoked chef-client yet.  Bug report needs to be submitted to https://github.com/test-kitchen/test-kitchen

**Comment by Maniacal** [comment]
Oh.  I thought this line signified the start of the chef-client run:   Starting Chef Client, version 12.0.1

Thanks

**Comment by lamont-granquist** [comment]
Actually you're right, still nothing much useful to suggest.  You need to hunt down where chef-client-run-from-test-kitchen drops its stacktrace.out file and see what failed.  I also suspect that you just ran a filesystem out of space somewhere (either /var or /tmp or something like that).

**Comment by lamont-granquist** [comment]
If you can let us know if the filesystem just ran out of space we might be able to do something about tweaking where TK or chef drops its files on the virt.  Other than that, we don't really recommend using chef cookbooks as file distribution mechanisms for massive files, so the better solution here is probably to put the big files in s3 and use remote_file to download them.
