### ISSUE TITLE
knife cookbook test doesn't work with cookbook_path set to an array

### ISSUE THREAD

**Issue by juliandunn** [chef/chef#2825]
Given a setting like this in `knife.rb`:

```
cookbook_path            [File.join(home, 'devel', 'path1'), File.join(home, 'devel', 'path2')]
```

`knife cookbook test` on any cookbook fails with:

```
WARNING: No cookbooks to test in /Users/juliandunn/devel/path1,/Users/juliandunn/devel/path2 - is your cookbook path misconfigured?
```

I'm honestly happy to put in a PR to rip out `knife cookbook test` as I suspect it is very rarely used these days (and a misnomer since it's really "syntax check")

**Comment by lamont-granquist** [comment]
We do a syntax check on knife cookbook upload anyway.  I wouldn't be sorry to see it go away.

**Comment by thommay** [comment]
We probably want to deprecate the command with a useful error message suggesting that the user should use rubocop in favour of knife cookbook test.

**Comment by tas50** [comment]
Closing this issue out since we need to deprecate this feature entirely
