### ISSUE TITLE
dsc_script Fails to Pass Along timeout Parameter

### ISSUE THREAD

**Issue by sean-horn** [chef/chef#2831]
As a customer, I would like a dsc_script resource like this to modify the powershell default timeout of 600s. Many meaningful runs of the dsc_script resource may take longer than 600s.

    dsc_script "thing" do
        timeout 800
    end

Versions
-------------
* Chef Client 11.16.4
* Windows Server 2012 R2

Process
-----------
Added a debugging command output statement at https://github.com/chef/chef/blob/11.16.4/lib/chef/util/powershell/cmdlet.rb#L64 of

    Chef::Log.info("Found this info about the timeout setting ------ #{command.inspect}")

Example Run and test-dsc-script-script.rb: https://gist.github.com/sean-horn/3925be080780736b0f5b

Problem
-----------

As shown in the Example Run above, the `timeout` attribute of the `dsc_script` is not making it all the way down to the cmdlet invocation. Thus, the default timeout of 600s is always in effect in the chef-client run of the resource, no matter the setting in the resource.

ZenDesk 2655

**Comment by btm** [comment]
This is fixed in the next release via #2885. This can currently be tested in the 12.1.0.rc.0 release. Instructions for downloading that can be found here: http://lists.opscode.com/sympa/arc/chef/2015-02/msg00352.html

Otherwise we expect 12.1.0 to go out this week.
