### ISSUE TITLE
Docs: broken link https://docs.chef.io/essentials_cookbook_attribute_files.html

### ISSUE THREAD

**Issue by wjimenez5271** [chef/chef#2832]
This link returns page not found: https://docs.chef.io/essentials_cookbook_attribute_files.html. It is the first result in Google for the saerch "chef attribute precedence".

**Comment by lamont-granquist** [comment]
seems like this'll fix itself when google re-indexes the site.

**Comment by brianhays** [comment]
Hey guys, It looks like this issue can be closed. I confirmed that the link above now has a 301 redirect to the page https://docs.chef.io/attributes.html

**Comment by wjimenez5271** [comment]
OK closing. Thanks
