### ISSUE TITLE
Knife bootstrap does not work with AIX

### ISSUE THREAD

**Issue by chris-rock** [chef/chef#2836]
With the latest version of ChefDK, I was not able to bootstrap an AIX machine. @juliandunn do you know a working fix?

```bash
knife bootstrap -x u0015844  172.29.144.235
Connecting to 172.29.144.235
u0015844@172.29.144.235's password: 
172.29.148.235 ksh: bash:  not found.
```

**Comment by juliandunn** [comment]
@chris-rock It's always been the case; see https://github.com/chef/chef/issues/2037 (I'll close this in favor of that one)

**Comment by chris-rock** [comment]
@juliandunn thanks for pointing this out
