### ISSUE TITLE
for Solaris packages 'candidate_version' doesn't have the same kind of protection as 'load_current_resource'

### ISSUE THREAD

**Issue by tnarik** [chef/chef#2840]
in `chef/lib/chef/provider/package/solaris.rb`, the `candidate_version` method should have the same kind of checks as `load_current_resource`: 

```
 if @new_resource.source
            @package_source_found = ::File.exists?(@new_resource.source)
```

Failing to do so (or a similar check), results in the failed invocation of `pkginfo -l -d` without a source.
To reproduce this, you can check the `ant` cookbook for a solaris box.

**Comment by lamont-granquist** [comment]
So is the use case here that there is no file but its installed, so we should be able to behave idempotently and do nothing since its already installed?

**Comment by tnarik** [comment]
Let me see if I remember and it makes sense: if the Solaris package provider is used, but no 'source' attribute is specified (as it is optional), the following was failing:

`status = shell_out_with_timeout("pkginfo -l -d #{@new_resource.source} #{new_resource.package_name}")` 

, when trying to obtain the 'candidate_version'.

I don't recall the rest of the details because since then I moved to use 'pkgutil_package', so maybe my recipe was using 'package' the wrong way and 'source' wasn't meant to be optional.
