### ISSUE TITLE
platform_version required by spec_helper

### ISSUE THREAD

**Issue by rychipman** [chef/chef#2843]
In line 87 of spec_helper, it is assumed that there is a platform_version for the test machine:
    
    TEST_PLATFORM_VERSION = OHAI_SYSTEM["platform_version"].dup.freeze

While this will often be true, it will not always be the case (like, for example, when someone is running Arch Linux like I am). This needs to be made optional to support rolling-release distros.

**Comment by lamont-granquist** [comment]
is there a way to get a datestamp or something else in for platform_verison in ohai, since I doubt this'll be the only time this kind of bug comes up?  if something is in there, it'll be much less likely to regress, since I can guarantee I'm never thinking about this edge case when submitting or reviewing code.

**Comment by rychipman** [comment]
I can see if there's a way to replace version with a date. Another
potential solution may be making the atomic version equal to the kernel
version (since that is one package we know will be installed).

Of course, that would also really on alternate kernels to have a version
number available to ohai, which may or may not be the case.

**Comment by rychipman** [comment]
It seems that this will reliably give the running kernel version, which could be used in place of a version number for arch:

    cat /proc/version | awk '{ print $3 }'

**Comment by jdmundrawala** [comment]
I've been using `uname -r` inside of ohai:
```diff
diff --git a/lib/ohai/plugins/linux/platform.rb b/lib/ohai/plugins/linux/platform.rb
index 90347a4..157ccc9 100644
--- a/lib/ohai/plugins/linux/platform.rb
+++ b/lib/ohai/plugins/linux/platform.rb
@@ -83,6 +83,7 @@ Ohai.plugin(:Platform) do
       platform "arch"
       # no way to determine platform_version in a rolling release distribution
       # kernel release will be used - ex. 2.6.32-ARCH
+      platform_version `uname -r`.strip
     elsif File.exists?('/etc/exherbo-release')
       platform "exherbo"
       # no way to determine platform_version in a rolling release distribution
```

**Comment by rychipman** [comment]
That makes sense. We should be able to use the kernel plugin, as in 

    depends 'kernel'
    ...
    platform_version kernel[:release]

but even when I depend on the kernel, running the rspec tests gives me

    undefined method `[]' for nil:NilClass

**Comment by btm** [comment]
Does https://github.com/chef/ohai/pull/473 fix this?

**Comment by rychipman** [comment]
Yes, that should fix this
