### ISSUE TITLE
Pacman options

### ISSUE THREAD

**Issue by rychipman** [chef/chef#2848]
The pacman and aur package providers do not take full advantage of pacman's command-line options. For example, removal and purging both currently run <code>pacman -R package</code>, while other options like <code>pacman -Rs package</code> (removes orphaned dependencies as well) may be more appropriate.

**Comment by lamont-granquist** [comment]
If you know you're going to submit a PR you don't need to submit the associated issue, it just creates two things to track and potentially leaves litter if the issue isn't closed with the PR.

**Comment by lamont-granquist** [comment]
closing due to lack of interest.
