### ISSUE TITLE
Bootstrapping a windows node from a windows workstation fails with a SSL error

### ISSUE THREAD

**Issue by alifsarker** [chef/chef#2859]
We have a dedicated chef server on a CentOS machine. We are trying to bootstrap a windows node (our chef client) from a windows workstation. We installed knife-windows on our workstation and opened ports 5985 and 5986 on the windows node. 

We bootstrap with the following command: knife bootstrap windows winrm 172.25.32.84 -x kanaeng -P 'k4na2n!2' -p 5985

The bootstrap fails with the following SSL error:

172.25.32.84 C:\Users\kanaeng>(echo.{"run_list":[]}) 1>C:\chef\first-boot.json
172.25.32.84 Starting chef to bootstrap the node...
172.25.32.84
172.25.32.84 C:\Users\kanaeng>SET "PATH=C:\oraclexe\app\oracle\product\11.2.0\se
rver\bin;;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\Sys
tem32\WindowsPowerShell\v1.0\;C:\ImportantData\apache-ant-1.9.2-bin\apache-ant-1
.9.2\bin;C:\MySQL\MySQL Server 5.1\bin;C:\Java\JDK6\bin\bin;C:\Program Files\Tor
toiseSVN\bin;C:\ImportantData\apache-maven-3.1.0\bin;C:\ImportantData\apache-ant
-1.9.2-bin\apache-ant-1.9.2\bin;C:\Java\JDK6\bin;C:\opscode\chef\bin;C:\ruby\bin
;C:\opscode\chef\bin;C:\opscode\chef\embedded\bin"
172.25.32.84
172.25.32.84 C:\Users\kanaeng>chef-client -c c:/chef/client.rb -j c:/chef/first-
boot.json -E _default
172.25.32.84 [2015-02-03T16:22:02-08:00] INFO: *** Chef 12.0.3 ***
172.25.32.84 [2015-02-03T16:22:02-08:00] INFO: Chef-client pid: 2744
172.25.32.84 [2015-02-03T16:22:27-08:00] INFO: Client key c:/chef/client.pem is
not present - registering
172.25.32.84 [2015-02-03T16:22:28-08:00] ERROR: SSL Validation failure connectin
g to host: CentOS69.kana-test.com - SSL_connect returned=1 errno=0 state=SSLv3 r
ead server certificate B: certificate verify failed
172.25.32.84
172.25.32.84 ===================================================================
=============
172.25.32.84 Chef encountered an error attempting to create the client "WINDOWS1
85.kana-test.com"
172.25.32.84 ===================================================================
=============
172.25.32.84
172.25.32.84 [2015-02-03T16:22:28-08:00] FATAL: Stacktrace dumped to c:/chef/cac
he/chef-stacktrace.out
172.25.32.84 [2015-02-03T16:22:28-08:00] FATAL: NoMethodError: undefined method
`run_id' for nil:NilClass
ERROR: Failed to execute command on 172.25.32.84 return code 1

Does anyone know what I have to do to get the bootstrap working successfully?

**Comment by smurawski** [comment]
Chef 12 turns on SSL certificate verification by default.  You can either (less secure) customize your bootstrap template to set the ssl_verify_mode to :verify_none or (more secure) include the cert from your Chef server on the clients.  There is an example of how to do that here - http://jtimberman.housepub.org/blog/2014/12/11/chef-12-fix-untrusted-self-sign-certs/

You could also add that step into your bootstrap template.
