### ISSUE TITLE
Git resource's user attribute does not properly support whyrun mode

### ISSUE THREAD

**Issue by zwant** [chef/chef#2860]
### Version:

12.0.3
### Environment:

CentOS 6.5
### Scenario:

If a recipe is using the git-resource with the "user" attribute:

```
git /tmp/mydir do
  repository 'ssh://git@somehost.tld/myrepo.git'
  revision 'master'
  user user_created_in_chef_run
  group user_created_in_chef_run
  action :sync
end
```

And the "user" (in this case user_created_in_chef_run) does not yet exist (since we're in whyrun mode), the git provider will error out with:

```
Could not determine HOME for specified user 'user_created_in_chef_run' for resource 'git[/tmp/mydir/]
```

It seems the error lies in a workaround done here: https://github.com/chef/chef/blob/59236f77e5ce61dea27bb99ac259e59ef9436705/lib/chef/provider/git.rb#L305

```
if @new_resource.user
  run_opts[:user] = @new_resource.user
  # Certain versions of `git` misbehave if git configuration is
  # inaccessible in $HOME. We need to ensure $HOME matches the
  # user who is executing `git` not the user running Chef.
  env['HOME'] = begin
    require 'etc'
    Etc.getpwnam(@new_resource.user).dir
  rescue ArgumentError # user not found
    raise Chef::Exceptions::User, "Could not determine HOME for specified user '#{@new_resource.user}' for resource '#{@new_resource.name}'"
  end
end
```

The 'Etc.getpwnam' call needs to take into account whyrun mode as well.

**Comment by lamont-granquist** [comment]
yeah the exception needs to be raised in define_resource_requirements
