### ISSUE TITLE
Why output `new_run_list.inspect` in chef-client logs?

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef#2863]
Why do we output `new_run_list.inspect` in chef-client logs?

I get this in my logs.

```
[2015-02-04T20:57:11+00:00] INFO: Setting the run_list to [#<Chef::RunList::RunListItem:0x00000001f75840 @version=nil, @type=:recipe, @name="test">] from CLI options
```

Shouldn't this be more human readable and not an inspection of an object?

Reference:
https://github.com/chef/chef/blob/12.0.3/lib/chef/node.rb#L323

**Comment by lamont-granquist** [comment]
yeah that should probably just be #to_s and that should get implemented to be human readable if its not.
