### ISSUE TITLE
Normalize chef-client and Reporting Outputs

### ISSUE THREAD

**Issue by sean-horn** [chef/chef#2868]
As a customer, I would like Chef to make the outputs of chef-client and the Reporting component more similar, to avoid confusion.
https://github.com/chef/omnibus-reporting/issues/113

**Comment by thommay** [comment]
@sean-horn did this get moved to JIRA?

**Comment by lamont-granquist** [comment]
This needs a lot more detail to be made actionable.  Which resources are different?  What kinds of changes need to be made?  What updates need to be made to the chef-client output, what changes need to be made on the reporting side, etc?

**Comment by thommay** [comment]
Closing due to lack of information.
