### ISSUE TITLE
Chef 12 Attribute Regression

### ISSUE THREAD

**Issue by jonlives** [chef/chef#2871]
## Summary
Chef 12 has introduced behaviour which alters the handling of attributes which contain arrays of hashes such that they no longer work as they did in Chef 11

## To Replicate

To replicate the observed regressing behaviour, the following spec should be added to *spec/unit/node_spec.rb* on **master**:

```ruby
      it "correctly fetches string and symbol attribute values from an array of hashes" do
        node.default['apache']['vhosts']     = [{'host' => 'test', 'port' => '666'}]
        expect(node.default['apache']['vhosts'].first['port']).to eql('666')
        expect(node.default['apache']['vhosts'].first[:port]).to eql('666')
        expect(node.default[:apache]['vhosts'].first['port']).to eql('666')
        expect(node.default[:apache]['vhosts'].first[:port]).to eql('666')
      end
```
The equivalent (working) behaviour in Chef 11 can be reproduced by adding the following spec to *spec/unit/node_spec.rb* on **11-stable**

```ruby
    it "correctly fetches string and symbol attribute values from an array of hashes" do
      node.default["apache"]["vhosts"] = [{'host' => 'test', 'port' => '666'}]
      node['apache']['vhosts'].first['port'].should == '666'
      node['apache']['vhosts'].first[:port].should == '666'
      node['apache'][:vhosts].first['port'].should == '666'
      node['apache'][:vhosts].first[:port].should == '666'
    end
```
## What I expected to Happen

I expected Chef 12 to behave as Chef 11 did, whereby the keys of the Hash inside the array ```node['apache']['vhosts’]``` should be accessible using either symbol or string values.

## What Actually Happened

Under Chef 12, accessing the ‘port’ key of the Hash inside the array ```node['apache']['vhosts’]``` using a symbol results in the value returned being nil, instead of the expected ‘666'

## The Cause

What I *have* identified so far is that the attribute value in question is a different object type in Chef 12 than it was in Chef 11.

In Chef 11, ```node.default["apache"]["vhosts”]``` was an **ImmutableArray** containing an **ImmutableMash**. This mash meant that of course symbols and strings could be used interchangeably to access Mash keys.

In Chef 12 however, ```node.default["apache"]["vhosts”]``` is now an **AttrArray** containing a plain old **Hash**. This now means that when a string key is requested using a symbol, it does not exist and returns nil.

I’m still digging into precisely what changed to cause this new behaviour (I suspect it’s something to do with the new attribute cache), but I wanted to file the issue here anyway in case anybody else is able to locate the cause or recognises the symptoms.

I can also confirm that this issue is not fixed by #2753.

**Comment by jonlives** [comment]
@lamont-granquist  / @danielsdeleo this is the attribute issue I mentioned last night we're seeing in Chef-client 12. Investigations continue as to what changed to cause this, but wanted to get the issue logged asap as per your request.

**Comment by lamont-granquist** [comment]
are you missing the 'node.default' accessor bit on your chef-11 rspec example?  that'd certainly cause a difference since `node[:foo]` will return an ImmutableMash/ImmutableArray while `node.default[:foo]` should be a VividMash/AttrArray (in both chef-11 and chef-12 i believe).

**Comment by lamont-granquist** [comment]
Yeah, when I backport your chef-12 spec directly to chef-11 without changing it, I get the same result:

```
     Failure/Error: expect(node.default['apache']['vhosts'].first[:port]).to eql('666')

       expected: "666"
            got: nil
```

Its also an AttrArray around a plain-old Hash.

**Comment by jonlives** [comment]
@lamont-granquist hmm I get the same. The odd thing is though in that case, it *does* work for us using chef-client 11.16.x, we only spotted the attribute going missing in 12.x.

**Comment by lamont-granquist** [comment]
Can you write more of the larger context?

**Comment by jonlives** [comment]
@lamont-granquist here's a test cookbook I've been using: https://gist.github.com/jonlives/dbdab7b17ab99e51fdff

Apologies for stupid github file naming rules. Running this under chef-client 11.16, the vhost created in /etc/httpd/conf.d/attr_test.conf should be "*:666".

In chef-client 12 however, the vhost ends up being "*:"

**Comment by lamont-granquist** [comment]
Your chef-11 rspec example also works fine in chef-12.  I get an ImmutableArray/Hash all the way through and the symbols work fine.

**Comment by jonlives** [comment]
Hmm that may have been a red herring if I wasn't writing my specs good. I can consistently reproduce the issue with the cookbook above though.

**Comment by lamont-granquist** [comment]
works on Chef 12.1.0.dev.0:

```
% chef-client -z -j dna.json
[2015-02-06T10:04:11-08:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 12.1.0.dev.0
resolving cookbooks for run list: ["test::default"]
Synchronizing Cookbooks:
  - test
Compiling Cookbooks...
Converging 1 resources
Recipe: test::default
  * template[/tmp/attr_test.conf] action create
    - create new file /tmp/attr_test.conf
    - update content in file /tmp/attr_test.conf from none to d69e55
    --- /tmp/attr_test.conf	2015-02-06 10:04:18.000000000 -0800
    +++ /var/folders/rs/wqwmj_1n59135dhhbvfdrlqh0001yj/T/chef-rendered-template20150206-68582-ah6y5v	2015-02-06 10:04:18.000000000 -0800
    @@ -1 +1,5 @@
    +<VirtualHost *:666>
    +  ServerName   atlas.trimix.foo.bar.com
    +</VirtualHost>
    +
    - change mode from '' to '0644'

Running handlers:
Running handlers complete
Chef Client finished, 1/1 resources updated in 6.186161 seconds
```

that is on my mac, not centos or ubuntu.

**Comment by lamont-granquist** [comment]
Any chance you're trying to upgrade chef-12 via `/opt/chef/embedded/bin/gem install ./chef-12.1.0.dev.0.gem` and getting trolled by appbundler and still running 12.0.x without the patch?

**Comment by jonlives** [comment]
I'm getting that behaviour on 12.0.3, with the patches from #2753 manually applied. Is there an RPM build of 12.1.0.dev.0 I could try out?

**Comment by lamont-granquist** [comment]
no

best bet is to wipe /opt/chef/embedded/apps/chef and git clone master into that.

**Comment by jonlives** [comment]
Lemme try that just now - there's a chance I might have borked applying the patches then.

**Comment by lamont-granquist** [comment]
and if you're manually applying patches into /opt/chef/embedded/lib/ruby/yadda/yadda thats the wrong place as well...

**Comment by jonlives** [comment]
Well now, this is kind of embarrassing. Not only did I write bad specs, it turns out I also evidently applied the patch incorrectly (tho I did put it in /opt/chef/embedded/apps/chef) because 12.1.0.dev.0 is indeed working correctly. I'm going to close this off now and go and do something entirely unrelated to computers. Thanks for your kind patience :p

**Comment by lamont-granquist** [comment]
lololololol =)
