### ISSUE TITLE
Disable redirect not possible 'enable_non_ssl' does not work

### ISSUE THREAD

**Issue by ostraaten** [chef/chef#2874]
In https://tickets.opscode.com/browse/CHEF-4029 it states that it possible to enable http and prevent redirect to https.

This is not working. For example settings like 
    nginx['non_ssl_port'] = 8080
    nginx['x_forwarded_proto'] = 'http'
    nginx['enable_non_ssl'] = true

Will keep redirect http on 8080 to https port 443. It does break configuration because at https port 443 there will be a redirect loop.

This is the case for latest Chef https://web-dl.packagecloud.io/chef/stable/packages/ubuntu/trusty/chef-server-core_12.0.3-1_amd64.deb

**Comment by lamont-granquist** [comment]
This repo is for the client, this issue needs to get refiled in the chef-server project http://github.com/chef/chef-server
