### ISSUE TITLE
Knife data bags from file should autocreate data bags

### ISSUE THREAD

**Issue by dblessing** [chef/chef#2884]
This is a re-report of https://tickets.opscode.com/browse/CHEF-1362. It seems this issue and related issues were closed as "no longer relevant" at some point but I'm not sure why.

Right now, `knife data bag from file <bag> <file/directory>` still throws an error if the data bag doesn't exist. This command would come in really handy for mass-creating data bags (i.e. if the data bags are stored in a git repo). Please support this.

**Comment by lamont-granquist** [comment]
You can workaround this with the ChefFS 'knife upload/knife download' commands which are better suited for bulk hacking:

```
knife upload /data_bags/<bag>/<item>
knife upload /data_bags/<bag>
knife upload /data_bags
```

**Comment by dblessing** [comment]
@lamont-granquist I can live with that. Thanks.
