### ISSUE TITLE
Error message: Unable to satisfy constraints on package

### ISSUE THREAD

**Issue by venumurthy** [chef/chef#2892]
The below error is ambiguous and actually isn't helping resolve an issue let alone even hinting it. Its just an issue of typo or wrong version number being pinned in an environment. 

[ec2-user@ip-172-31-163-152 ~]$ sudo chef-client
Starting Chef Client, version 12.0.3
resolving cookbooks for run list: ["learn_chef_httpd", "learn_chef_httpd::vhosts", "chef-client", "chef-client::delete_validation"]

================================================================================
Error Resolving Cookbooks for Run List:
================================================================================

Cookbook dependency resolution error:
-------------------------------------
Error message: Unable to satisfy constraints on package cron, which does not exist, due to solution constraint (chef-client >= 0.0.0). Solution constraints that may result in a constraint on cron: [(chef-client = 4.2.0) -> (cron >= 1.2.0)]
You might be able to resolve this issue with:
  1-) Removing cookbook versions that depend on deleted cookbooks.
  2-) Removing unused cookbook versions.
  3-) Pinning exact cookbook versions using environments.

Expanded Run List:
------------------
* learn_chef_httpd
* learn_chef_httpd::vhosts
* chef-client
* chef-client::delete_validation

Running handlers:
[2015-02-11T00:46:24-05:00] ERROR: Running exception handlers
Running handlers complete
[2015-02-11T00:46:24-05:00] ERROR: Exception handlers complete
[2015-02-11T00:46:24-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 1.73937474 seconds
[2015-02-11T00:46:24-05:00] ERROR: 412 "Precondition Failed"
[2015-02-11T00:46:24-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by lamont-granquist** [comment]
So the error message comes back from the server, so at best this is a server bug and is misclassified.

This is also a "hard" problem in computer science.  We are unlikely to take this work on.  We are also trying to phase out the server-side depsolver so the large effort would be eventually thrown away.
