### ISSUE TITLE
Nameserver changes don't get picked up by Chef

### ISSUE THREAD

**Issue by roman-yepishev-enoc** [chef/chef#2894]
This bug makes it impossible to do full Chef configuration of the node in case it was not previously configured with DNS enabled to resolve internal resources if these are later referenced in the recipes.

The use case is simple:
 1. Configure nameservers
 2. Fetch some content from a server which hostname can be resolved with nameserver configured previously.

Versions tested:
 * 11.16.2
 * 12.0.3

STR using Test Kitchen:
 1. On host: add '`54.175.219.8 randomhost.chef.io`' to /etc/hosts, effectively making randomhost.chef.io an alias for httpbin.org.
 2. Run dnsmasq
 3. Make sure randomhost.chef.io now resolves:
    ```
$ dig +short randomhost.chef.io @127.0.0.1
54.175.219.8
```
 4. Using centos-6.5 vagrant box, converge the following recipe:
   ```
file '/etc/resolv.conf' do
  content "nameserver 10.0.2.2"
end

remote_file '/tmp/user-agent'  do
  source 'http://randomhost.chef.io/user-agent'
end
```

**Expected results:**
Chef creates /tmp/user-agent with the content from http://httpbin.org/user-agent

**Actual results:**
```
[2015-02-11T16:46:06+00:00] WARN: remote_file[/tmp/user-agent] cannot be downloaded from http://randomhost.chef.io/user-agent: Error connecting to http://randomhost.chef.io/user-agent - getaddrinfo: Name or service not known
       
           ================================================================================
           Error executing action `create` on resource 'remote_file[/tmp/user-agent]'
           ================================================================================
           
           SocketError
           -----------
           Error connecting to http://randomhost.chef.io/user-agent - getaddrinfo: Name or service not known
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/resolver_bug/recipes/default.rb
           
            14: remote_file '/tmp/user-agent'  do
            15:   source 'http://randomhost.chef.io/user-agent'
            16: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/resolver_bug/recipes/default.rb:14:in `from_file'
           
           remote_file("/tmp/user-agent") do
             provider Chef::Provider::RemoteFile
             action "create"
             retries 0
             retry_delay 2
             guard_interpreter :default
             path "/tmp/user-agent"
             backup 5
             atomic_update true
             source ["http://randomhost.chef.io/user-agent"]
             use_etag true
             use_last_modified true
             cookbook_name "resolver_bug"
             recipe_name "default"
           end
```

Verify that file is accessible:
```
$ kitchen login
Last login: Wed Feb 11 16:45:57 2015 from 10.0.2.2
[vagrant@default-centos-65 ~]$ curl http://randomhost.chef.io/user-agent
{
  "user-agent": "curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.14.0.0 zlib/1.2.3 libidn/1.18 libssh2/1.4.2"
}
```

Verify that second converge works:
```
...
- update content in file /tmp/user-agent from e3b0c4 to 608598
  --- /tmp/user-agent	2015-02-11 16:46:05.995425159 +0000
  +++ /tmp/chef-rest20150211-2019-1xl9lb9	2015-02-11 16:50:12.501616626 +0000
  @@ -1 +1,4 @@
  +{
  +  "user-agent": "Chef Knife/11.16.2 (ruby-1.9.3-p547; ohai-7.4.0; x86_64-linux; +http://opscode.com)"
  +}
```

**Comment by stevendanna** [comment]
Ruby likely ins't calling res_init() (glibc library function: http://linux.die.net/man/3/res_init) and thus the first reading of /etc/resolv.conf exist for the lifetime of the process.  We should see if there is a Ruby interface to this system call (or maybe just use ffi to call it).

**Comment by lamont-granquist** [comment]
Are we sure this is ruby and not nscd?

**Comment by roman-yepishev-enoc** [comment]
nscd was not installed during my tests, so it did not affect the issue.
I also found http://projects.puppetlabs.com/issues/2776 which got linked from Bug #5095: Resolv should call res_init() - http://redmine.ruby-lang.org/issues/5095

**Comment by lamont-granquist** [comment]
Yeah, replicated.  For some reason ruby stats /etc/resolv.conf and then uselessly ignores that its changed.

The workaround would be to actually use nscd and then after updating /etc/resolv.conf to bounce nscd to pick up the changes.  This would have the side-effect of fixing everything else on the system which is running and will have cached the nameservers and fails to call res_init itself as well.  I'm actually with Uli Drepper that nscd is the right tool to fix this.

Of course ruby not doing that is still busted.  I feel very iffy about patching chef to do this.  And it isn't likely to be a very high priority for us internally to fix without a contributed PR.

**Comment by Tensibai** [comment]
Sounds like the kind of changes where you wish chef to stop running (like when chef update itself in omnibus-updater).

For this kind of changes, as I can't dig into any parts of a system, I would reboot the node to avoid side effects (as I would for any network related change or common library update for security fix).

**Comment by lamont-granquist** [comment]
That's why Uli suggested using nscd.  Much easier than rebooting the entire system.

https://bugzilla.redhat.com/show_bug.cgi?id=442172#c11

**Comment by Tensibai** [comment]
I do agree nscd is a solution, but it comes with pitfalls (ldap caching, overrides of DNS TTL) which I'm unsure everyone wish to deal with (indeed nscd can be tuned properly but this is highly dependent).

My first though of stopping the Chef run was a workaround after distribution of `/etc/resolv.conf`.
I'm assuming this happens early in the node life and that it's done early in the Chef run so the rest of actions (remote files, packages, daemons starts) will be done with the correct naming system in place on second run.

The second (reboot) comes after thinking about how I manage this kind of changes usually and the why I do this. 
There's few reason to reboot a Linux node, but name resolving sounds one to me.

Obviously I'm talking about an alternative to the use of nscd as I think nscd should not be mandatory.

**Comment by lamont-granquist** [comment]
nscd hasn't overrode DNS TTLs in getaddrinfo for well over a decade and since the GHOST attack wasn't a lot worse than it could have been we know that IPv6 has gotten nearly everyone to adopt getaddrinfo over gethostbyname.  it doesn't need to be tuned, it just supports TTLs correctly.

**Comment by lamont-granquist** [comment]
Looks like I'm even out of date now and gethostbyname has been cached since glibc 2.8 (2010-ish):

http://udrepper.livejournal.com/16362.html

**Comment by Tensibai** [comment]
I have to admit the DNS TTL never hit me (memory from others warning me about it), but the passwd and group cache have turned me mad for a while.
I didn't dig too much on nscd at this moment as it worked fine without it and without performances issues (but the boxes are far from being overloaded too).
Maybe the root cause was not nscd but the pam module in use, moved to pam_lsass since that. 

I'll retry this if I found time :)

**Comment by lamont-granquist** [comment]
passwd and group caching in nscd can be trivially disabled in config (and i always run it that way).

**Comment by lamont-granquist** [comment]
Closing this as its a bug in ruby.  If ruby is fixed, we'll pick it up when we ship the new ruby.

The workaround is to run nscd and bounce nscd.

If you don't do this, then chef and ruby is only part of your problem and other badly behaved programs that don't properly pick up /etc/resolv.conf changes will also be broken.  In general, as a best practice for System Engineering as a discipline, when you change /etc/resolv.conf you must take one of two actions -- either reboot your server, or else run nscd.  Any other approach risks leaving processes that have cached the old resolv.conf information.  This is not a problem with Chef and is a problem with managing a Linux/Unix operating system overall.

**Comment by mfischer-zd** [comment]
I've found a workaround that I like:

```
ruby_block 'reload resolv.conf' do
  block do
    require 'resolv'
    # What's this, you ask?  This bit of magic causes Ruby to substitute its
    # pure-Ruby resolver for the libc resolver.  The libc resolver is
    # initialized only once, but the Ruby one can be re-initialized.
    # This allows us to reload resolv.conf mid-run so we can resolve Consul
    # DNS names.
    require 'resolv-replace'
    Resolv::DefaultResolver.replace_resolvers [Resolv::DNS.new('/etc/resolv.conf')]
  end
end
```

**Comment by maokt** [comment]
My workaround was to call res_init in libc using ffi:

```
ruby_block 'res_init' do
    action :nothing
    block do
        require 'ffi'
        module libc
            extend FFI::Library
            ffi_lib FFI::CURRENT_PROCESS
            # res_init in GNU libc is called __res_init, so try both
            [ :res_init, :__res_init ].detect do |ff|
                begin
                    attach_function :res_init, ff, [], :int
                    true
                rescue FFI::NotFoundError
                    false
                end
            end
        end
        libc.res_init() if defined? libc.res_init
    end
end

```
