### ISSUE TITLE
bootstrap-latest.tar.gz is not compatible with Chef 12.x

### ISSUE THREAD

**Issue by gswallow** [chef/chef#2895]
Hi,

Creating a new instance using sparkleformation, I'm installing Chef and bootstrapping it like this:

curl -sL https://www.chef.io/chef/install.sh | sudo bash
chef-solo -c /etc/chef/solo.rb -j /etc/chef/chef-client-config.json -r http://s3.amazonaws.com/chef-solo/bootstrap-latest.tar.gz

chef-solo dies because the openssl cookbook, which is required by the chef-client::config recipe, does not contain a "name" in metadata.rb.

I downloaded the tarball and found these versions of the cookbooks missing "name"s in metadata.rb:

apache2 (1.3.0)
apt (1.5.0)
build-essential (1.2.0)
couchdb (1.0.4)
daemontools (1.0.0)
openssl (1.0.0)
rabbitmq (1.6.4)
ucspi-tcp (1.0.0)
xml (1.0.4)
zlib (1.0.0)

**Comment by lamont-granquist** [comment]
That isn't supported any more.  It sets up things like couchdb for chef-server 10.x which is dead and gone at this point.  Up to date Chef Server installation instructions are here:

https://docs.chef.io/install_server.html
