### ISSUE TITLE
Chef DK tools do not work in Git bash on Windows after installation in non-default directory

### ISSUE THREAD

**Issue by madhead** [chef/chef#2906]
### Version:
0.4.0-1 for Windows

### Environment:
Windows 7x64

### Scenario:
I've installed Chef DK to a non-default location (`C:\dev\opscode`, instead of `C:\opscode`) and I'm not able to use tools from `bin` in `bash` (the one which is shipped with Git). The reason is that in many files the paths in shebangs are hardcoded to `#!C:/dev/opscode/...`. `*.bat` files works ok.

### Steps to Reproduce:
Install Chef DK to a non-default location.

### Expected Result:
I expect the tools to work via bash.

### Actual Result:
The tools do not work when used from bash.

**Comment by danielsdeleo** [comment]
If you want to relocate the install, you'll have to stick to the windows toolchain (i.e., powershell). The reason for this is that shebang lines are generated at build time and cannot be written in a way that supports relocation, because shebangs must be absolute paths.
