### ISSUE TITLE
:powershell_script guards not working properly on non-powershell_script resources

### ISSUE THREAD

**Issue by japrom** [chef/chef#2909]
Hi,

It appears the powershell_script guards are not properly executed when guard_interpreter :powershell_script is set. They seem to only work on the powershell_script resource.

Here's a very trivial example
``` ruby
log "Powershell script guard in log" do
  guard_interpreter :powershell_script
  not_if "$false"
end

powershell_script "This works" do
  code "echo 'wheee!'"
  not_if "$false"
end
```
When executed, this is the output
```
PS C:\ > chef-client -z test.rb
<snip>
Starting Chef Client, version 12.0.3
<snip>
Converging 2 resources
Recipe: @recipe_files::C:/test.rb
  * log[Powershell script guard in log] action write (skipped due to not_if)
  * powershell_script[This works] action run
    - execute "powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -File
"D:/Users/jp/AppData/Local/Temp/2/chef-script20150213-1944-vxcktf.ps1"
```

As you can see... the log resource was skipped due to not_if, but the powershell_script ran, despite having the same exact guard. I expected the behavior/syntax on both resources to be exactly the same. Any ideas?

Thank you,
- James

**Comment by cordovinian** [comment]
Issue resolved with the fix from: https://github.com/chef/chef/issues/2683
