### ISSUE TITLE
OS chef upgrades over omnibus chef, breaking things

### ISSUE THREAD

**Issue by directionless** [chef/chef#2916]
When I install omnibus chef onto debian/ubuntu, I end up with a opscode distributed packaged called 'chef'. In this case, version 11.8.0-1.ubuntu.13.04 This runs into an interesting bug. 

The OS itself, distributes a chef package. Sometimes the OS's chef version is newer. When that happens, the OS upgrades the chef package. (For example, right now ubuntu distributes 11.8.2-2). When this happens, things start to break, one of the immediate ones, is the missing ruby-shadow.

At least for ubuntu/debian, I think there are a several of ways to fix this. 

On the tack of preventing the OS from upgrading it. You could name the package something else; or set an epoch in the version. You could also install an apt source for the omnibus chef, and ensure you're always newer. 

I think I probably favor the epoch route.

**Comment by directionless** [comment]
FWIW, I ended up with chef 11.8.0-1.ubuntu.13.04 by way of knife bootstrap, on a  https://manage.chef.io  server

**Comment by ranjib** [comment]
@directionless  you can tell dpkg to not install a specific package. using `apt-mark` [1]
[1]http://askubuntu.com/questions/18654/how-to-prevent-updating-of-a-specific-package

**Comment by directionless** [comment]
Yes, I can pin the package any number of ways. But I think this is a bug in the underlying chef omnibus packaging. Why make everyone work around it

**Comment by lamont-granquist** [comment]
We support apt repos via packagecloud.io now and if you install and apt_repository pointing to that then that repo will always be more up-to-date than the distro repo.
