### ISSUE TITLE
Gem_package could not resolve dependencies

### ISSUE THREAD

**Issue by cognoscibilis** [chef/chef#2917]
Environment:
* Chef 12.0.3 (chef-client -z mode)
* Ruby1.9.1

Installation of gem's falls with errors:
<code> ERROR: Failed to build gem native extension. </code>

Example recipe.rb:
```ruby
gem_package "sass"
gem_package "compass"
```
Example of recipe that works:
(ffi and rb-inotify are dependencies of compass)
```ruby
gem_package "ffi"
gem_package "rb-inotify"
gem_package "sass"
gem_package "compass"
```
Update: on ruby1.8 + rubygems there is no such problem

**Comment by lamont-granquist** [comment]
Not a chef issue.  You need to sort out how to to install the gems from the command line and install all the development gems that you need first (e.g. `gem_package 'ffi'` will certainly need `package "libffi-dev"` installed before it, and that i just one example).  And you need to look for help on how to do that in places like stackoverflow, mailing lists, irc, etc.  This issue tracker isn't for help on how to install random native gems on your system.
