### ISSUE TITLE
knife ssl fetch needs better cert validation logic and should not throw NoMethodError on nil

### ISSUE THREAD

**Issue by isuftin** [chef/chef#2919]
When trying to figure out an issue with my SSL cert not being verified even though I have the cert in a trusted cert directory, I am seeing this issue:

```
$ knife ssl fetch -VV https://chef.owicloud.org
INFO: Using configuration from /Users/isuftin/.chef/knife.rb
DEBUG: Checking SSL cert on https://chef.owicloud.org
WARNING: Certificates from chef.owicloud.org will be fetched and placed in your trusted_cert
directory (/Users/isuftin/.chef/trusted_certs).

Knife has no means to verify these are the correct certificates. You should
verify the authenticity of these certificates after downloading.

/opt/chefdk/embedded/apps/chef/lib/chef/knife/ssl_fetch.rb:92:in `cn_of': undefined method `[]' for nil:NilClass (NoMethodError)
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife/ssl_fetch.rb:118:in `write_cert'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife/ssl_fetch.rb:137:in `block in run'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife/ssl_fetch.rb:136:in `each'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife/ssl_fetch.rb:136:in `run'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:417:in `block in run_with_pretty_exceptions'
        from /opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:416:in `run_with_pretty_exceptions'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:213:in `run'
        from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
        from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
        from /usr/bin/knife:40:in `load'
        from /usr/bin/knife:40:in `<main>'
```

Chef version: 12.0.3

**Comment by ranjib** [comment]
looks like the ssl cert being [fetched](https://github.com/chef/chef/blob/master/lib/chef/knife/ssl_fetch.rb#L73) has malformed /empty data. Can you provide some information? what happens when you do:
```ruby
  require 'openssl'
  ctx = OpenSSL::SSL::SSLContext.new
  ctx.verify_mode = OpenSSL::SSL::VERIFY_NONE  
  conn = OpenSSL::SSL::SSLSocket.new(TCPSocket.new(host, port), ctx)
  conn.connect
  puts conn.peer_cert_chain
```

**Comment by isuftin** [comment]
@ranjib Thank you for the help. This turns out to be an issue with the perimeter firewall for our VPC. I am closing this at this time.

**Comment by ranjib** [comment]
@danielsdeleo we should add some validation logic?

**Comment by danielsdeleo** [comment]
@ranjib Yes, absolutely.

This is still a UX issue, even if `knife ssl fetch` can't possibly work because the certificate is malformed, it should not bail out with a `NoMethodError` on `nil`.

We need to do something to handle a failure in these lines: https://github.com/chef/chef/blob/9fc77cc03c9666dec7935e00e9bdfc3084c24419/lib/chef/knife/ssl_fetch.rb#L91-L92

@isuftin I'd really love to see your certificate and also know if SSL validation works in a browser for you when connecting to this system. I haven't gone far enough down the x509 rabbit hole to know the exact logic by which SSL is supposed to check your certificate (and I haven't used a cert with no CN before).

**Comment by isuftin** [comment]
@danielsdeleo It's a self signed cert so I do have to accept the security override in a browser the first time but it does work going forward. I'll see what I can do about getting you the actual certificate. I think the issue seems to be the perimeter layer between your/my box and the Chef server itself.  

I will work on getting the cert for inspection

**Comment by danielsdeleo** [comment]
@isuftin thanks. This should be totally safe as long as you don't hand out the private key.

**Comment by isuftin** [comment]
@danielsdeleo Sent you an email with the cert attached. Please acknowledge.

**Comment by danielsdeleo** [comment]
@isuftin thanks! I got it. I haven't had much free time to look at this issue recently, but I'll see if I can convert it to a text form that I can post here or in a gist. Thanks again.

**Comment by danielsdeleo** [comment]
Ok, I've added the data to this gist: https://gist.github.com/danielsdeleo/7187c873dd3459a00dd5 (still in .cer form).

**Comment by lantrix** [comment]
I have the same issue. Internally signed chef server certificate; works in browser with CA cert in trusted root store; but `knife ssl fetch` doesn't play ball.

```
Lexx:chef lantrix$ knife ssl fetch -VV
INFO: Using configuration from /Users/ted/.chef/knife.rb
DEBUG: Checking SSL cert on https://chefdev.seek.int/organizations/seekdev
WARNING: Certificates from chefdev.seek.int will be fetched and placed in your trusted_cert
directory (/Users/lantrix/.chef/trusted_certs).

Knife has no means to verify these are the correct certificates. You should
verify the authenticity of these certificates after downloading.

/opt/chefdk/embedded/apps/chef/lib/chef/knife/ssl_fetch.rb:92:in `cn_of': undefined method `[]' for nil:NilClass (NoMethodError)
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/ssl_fetch.rb:118:in `write_cert'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/ssl_fetch.rb:137:in `block in run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/ssl_fetch.rb:136:in `each'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife/ssl_fetch.rb:136:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:417:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:416:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:213:in `run'
	from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
	from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:40:in `load'
	from /opt/chefdk/bin/knife:40:in `<main>'
```

In my case it's not a self signed cert it's an Internal CA signed cert; 

```
Lexx:chef lantrix$ openssl s_client -connect chefdev.seek.int:443
CONNECTED(00000003)
depth=2 CN = Seek Root CA
verify error:num=19:self signed certificate in certificate chain
verify return:0
---
Certificate chain
 0 s:/C=AU/ST=Victoria/L=Melbourne/OU=DevOps
   i:/DC=int/DC=seek/CN=Seek Intermediate CA
 1 s:/DC=int/DC=seek/CN=Seek Intermediate CA
   i:/CN=Seek Root CA
 2 s:/CN=Seek Root CA
   i:/CN=Seek Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGZzCCBU+gAwIBAgIKOqau8QABAAALeTANBgkqhkiG9w0BAQsFADBKMRMwEQYK
CZImiZPyLGQBGRYDaW50MRQwEgYKCZImiZPyLGQBGRYEc2VlazEdMBsGA1UEAxMU
U2VlayBJbnRlcm1lZGlhdGUgQ0EwHhcNMTUwMzE4MDQwNzAzWhcNMTcwMzE3MDQw
NzAzWjBFMQswCQYDVQQGEwJBVTERMA8GA1UECBMIVmljdG9yaWExEjAQBgNVBAcT
CU1lbGJvdXJuZTEPMA0GA1UECxMGRGV2T3BzMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEA5OnYJCHzQbLhKAj8pGcn2//Nd4KdOP0eQUOjkSOldZL+TpTL
IV1mnV9BZFuR+fFKvyh85zeh7LSo/fMvmSsPEzGR7reNlw1OTN144zoYMAEkrk+H
wZG1pDsIKBqhu4xZOX1bAYxNSPEjAzinASBz5ENed7PHGXqcTgik3G1iUFcG7UM9
iaJp5Ti/7glQYEupU38xIfah2HMw8pzklA0RDR++l8lU9fnhmtI1p1cJ2mSIV4a9
fXzrkCuDbAFnK+97AyOhWkJui8nzK7HEJ/KYt+UMTuyGe8g03YlEV1OPAZeR4fi0
AfniultiLDiS2cOUxA58SPrEaQCrdTkvidInAQIDAQABo4IDUjCCA04wCwYDVR0P
BAQDAgWgMFoGA1UdEQRTMFGCEGNoZWZkZXYuc2Vlay5pbnSCPWludGVybmFsLWNo
ZWYtZGV2LTE1NDI2Nzc2NTYuYXAtc291dGhlYXN0LTIuZWxiLmFtYXpvbmF3cy5j
b20wHQYDVR0OBBYEFGM8XmNq6QrKcP67WY8PcK2YN/F+MB8GA1UdIwQYMBaAFEdd
3rCJ1L9UjtQoJR63U9V2rq5NMIIBLQYDVR0fBIIBJDCCASAwggEcoIIBGKCCARSG
gcZsZGFwOi8vL0NOPVNlZWslMjBJbnRlcm1lZGlhdGUlMjBDQSgxKSxDTj1WTS1B
VU1FTC1DQVNVQixDTj1DRFAsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049
U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz1zZWVrLERDPWludD9jZXJ0aWZp
Y2F0ZVJldm9jYXRpb25MaXN0P2Jhc2U/b2JqZWN0Q2xhc3M9Y1JMRGlzdHJpYnV0
aW9uUG9pbnSGSWh0dHA6Ly92bS1hdW1lbC1jYXN1Yi5zZWVrLmludC9DZXJ0RW5y
b2xsL1NlZWslMjBJbnRlcm1lZGlhdGUlMjBDQSgxKS5jcmwwggE4BggrBgEFBQcB
AQSCASowggEmMIG0BggrBgEFBQcwAoaBp2xkYXA6Ly8vQ049U2VlayUyMEludGVy
bWVkaWF0ZSUyMENBLENOPUFJQSxDTj1QdWJsaWMlMjBLZXklMjBTZXJ2aWNlcyxD
Tj1TZXJ2aWNlcyxDTj1Db25maWd1cmF0aW9uLERDPXNlZWssREM9aW50P2NBQ2Vy
dGlmaWNhdGU/YmFzZT9vYmplY3RDbGFzcz1jZXJ0aWZpY2F0aW9uQXV0aG9yaXR5
MG0GCCsGAQUFBzAChmFodHRwOi8vdm0tYXVtZWwtY2FzdWIuc2Vlay5pbnQvQ2Vy
dEVucm9sbC9WTS1BVU1FTC1DQVNVQi5zZWVrLmludF9TZWVrJTIwSW50ZXJtZWRp
YXRlJTIwQ0EoMSkuY3J0MCEGCSsGAQQBgjcUAgQUHhIAVwBlAGIAUwBlAHIAdgBl
AHIwEwYDVR0lBAwwCgYIKwYBBQUHAwEwDQYJKoZIhvcNAQELBQADggEBAFKscNpa
4Piz7kRNl/i3rF8y5kWwjc19fjDHT/2GezTo7US4yB/jESaUmBu1YTN7LsOUukHK
42Am7FkO1JOHQMLcgK/X2KfY4vihjWiclxTUoLva3v5ObSrhePxjq+WOvgC1HH5B
uMGpyA5fput6X1XbGtKtl+L4o6B/daqNGTm+80vJWiLin3wtvYK1F/zb4XeBdFaU
WzYZuaL0IhORzK3NHR/y/tImp/OIq5G5mcG+IoghSZ8TXnQtLSKJsj5dPtcKW6mT
cEn+/azLs7v0bKq6mvEWJvzGAeh1vb4syW+TcuA6wXRe+tLA3xC918Vw7DtN96il
wULqL/LZVxgf/yE=
-----END CERTIFICATE-----
subject=/C=AU/ST=Victoria/L=Melbourne/OU=DevOps
issuer=/DC=int/DC=seek/CN=Seek Intermediate CA
---
No client certificate CA names sent
---
SSL handshake has read 4127 bytes and written 432 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 8BE9C07239144EA4D0382E98B44D1F83602D73C6C633C7E280DC00B31EFF4C50
    Session-ID-ctx: 
    Master-Key: E2AAC600B3710D81BB3A75DA1FF2E9051C4199F873E751CC65B1817A7C1A40307C9B02EBFE6C68B7BD069B3583FC60C7
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 72 97 4a 8f 87 37 32 a8-6e 74 01 a8 fa 48 34 4d   r.J..72.nt...H4M
    0010 - 1b 35 05 be 9f 09 12 af-40 fa ae b3 8f 02 c7 56   .5......@......V
    0020 - 3b e3 90 da 36 cc dc f2-f5 fa 8d 7f c8 ca 61 73   ;...6.........as
    0030 - a4 1b ef d8 cb e1 1e 9f-7a 35 6a 6e e4 b0 6a be   ........z5jn..j.
    0040 - 2e 4e fa d4 a6 a8 75 13-da 1e d1 1d e8 5d 39 8d   .N....u......]9.
    0050 - ea 79 06 20 75 2e cd a0-81 7b ad a8 31 7b 88 e7   .y. u....{..1{..
    0060 - 55 fa b4 d0 1c a2 b5 e8-ff 41 a0 9b f7 62 ec b2   U........A...b..
    0070 - b8 cc 03 b6 34 79 45 fe-58 b3 63 b5 3e e5 df 2e   ....4yE.X.c.>...
    0080 - 30 36 8c d9 23 f8 10 9c-9d e1 3a 97 28 f6 d3 ce   06..#.....:.(...
    0090 - e4 7d ce 6a 99 f3 24 fc-e3 a6 e9 76 93 95 5c 33   .}.j..$....v..\3

    Start Time: 1427176649
    Timeout   : 300 (sec)
    Verify return code: 19 (self signed certificate in certificate chain)
```

The browser is totally happy (*CA cert in trusted root store*):
![screenshot 2015-03-24 16 59 02](https://cloud.githubusercontent.com/assets/117008/6796436/2f3fb054-d247-11e4-913f-9a4d8cbf29bd.png)

**Comment by isuftin** [comment]
In our case, it seemed to have ended up being an issue with attempting to fetch the SSL cert across a Sophos UTM perimeter firewall device in AWS. Are you crossing any perimeter devices in your pull?
__________________________     (╯°□°）╯︵ ┻━┻
 Ivan Suftin - Applications Developer - isuftin@usgs.gov
 Office: (608) 821-3825  - Cell : (608) 345-8963
 Center for Integrated Data Analytics - http://cida.usgs.gov/
 United States Geological Survey 
 8505 Research Way, Middleton, WI 53562

**Comment by lantrix** [comment]
We have a new transparent firewall in place recently; and it may be that. I'll have to see if I can connect to the chef server (in AWS) via another route and see if it works.

**Comment by huepf** [comment]
I have the exact same issue as lantrix.
lantrix, did you find the cause? Is it related to your firewall?

**Comment by danielsdeleo** [comment]
The issue is `knife ssl fetch` assumes it can use the `CN` from the cert as part of the filename when it writes it to disk. If you have a decrypting SSL proxy, it has its own cert which doesn't have a CN.

**Comment by lantrix** [comment]
@huepf I think so. We've dropped Chef for now in favour of DSC and custom automation; so I can't tell for sure. I'm still using Chef-Zero so this is a non issue now for me.

**Comment by xenolinguist** [comment]
Just encountered this issue with a customer who issued an internally-signed certificate to their Chef server without a CN. Their browsers didn't seem to mind, which I found weird, but knife had this same issue.

**Comment by ff-pspiess** [comment]
I too have this issue with a CA signed certificate:

[ec2-user@chef-automate-1 ~]$ openssl s_client -connect chef.firstfuelsoftware.net:443
CONNECTED(00000003)
depth=3 C = US, O = "The Go Daddy Group, Inc.", OU = Go Daddy Class 2 Certification Authority
verify return:1
depth=2 C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", CN = Go Daddy Root Certificate Authority - G2
verify return:1
depth=1 C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", OU = http://certs.godaddy.com/repository/, CN = Go Daddy Secure Certificate Authority - G2
verify return:1
depth=0 OU = Domain Control Validated, CN = *.firstfuelsoftware.net
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/CN=*.firstfuelsoftware.net
   i:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certs.godaddy.com/repository//CN=Go Daddy Secure Certificate Authority - G2
 1 s:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certs.godaddy.com/repository//CN=Go Daddy Secure Certificate Authority - G2
   i:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./CN=Go Daddy Root Certificate Authority - G2
 2 s:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./CN=Go Daddy Root Certificate Authority - G2
   i:/C=US/O=The Go Daddy Group, Inc./OU=Go Daddy Class 2 Certification Authority
 3 s:/C=US/O=The Go Daddy Group, Inc./OU=Go Daddy Class 2 Certification Authority
   i:/C=US/O=The Go Daddy Group, Inc./OU=Go Daddy Class 2 Certification Authority
