### ISSUE TITLE
Unable to disable ohai plugins in /etc/chef-server/chef-server.rb when running 'chef-server-ctl reconfigure'

### ISSUE THREAD

**Issue by kaezi** [chef/chef#2920]
Filing this as a bug under advisement of Adam Jacob @adamhjk 
**Issue**
When running `chef-server-ctl reconfigure` the full suite of ohai plugins get run. In my case, running this in an extremely large org, the passwd plugin will pull all 40k+ users down from AD which takes quite some time. This has only been tested in Chef 11

**Methods Attempted**
I've disabled plugins with client.rb on chef-client runs to success. However setting disabled plugins in `/etc/chef/client.rb` or `/etc/chef-server/chef-server.rb` yield no results when running with `chef-server-ctl reconfigure`.

**Workaround:**
Thanks to @jtimberman for this: 
omnibus-ctl uses /opt/opscode/embedded/cookbooks/solo.rb, ohai plugins can be disabled by editing that.

This of course means that plugins will likely need to be redisabled on server upgrades.

**Comment by lamont-granquist** [comment]
Yep, you've got the wrong repo though.   This is for client bugs only.  That is a bug in the embedded solo recipes and chef-server-ctl command that needs to go into http://github.com/chef/chef-server
