### ISSUE TITLE
knife upload ignores site-cookbooks when using --chef-repo-path

### ISSUE THREAD

**Issue by eheydrick** [chef/chef#2921]
### Version:

12.0.3
### Scenario:

I'm trying to upload a chef repo where cookbooks are stored in site-cookbooks. If I configure knife.rb to have `cookbook_path` pointed at my site-cookbooks directory it works. If I add `--chef-repo-path .` to the knife upload it cannot find the site-cookbooks directory. I would rather set the path to cookbooks on the command line than have to put it in knife.rb. 
### Steps to Reproduce:
1. Have a chef-repo with cookbooks in a site-cookbooks directory
2. Run `knife upload --chef-repo-path . /`
### Expected Result:

I'd expect knife to find cookbooks in site-cookbooks even when using --chef-repo-path. Or I'd expect a 
`-o path/to/cookbooks` flag to override the path to cookbooks. 
### Actual Result:

Everything but cookbooks were uploaded

**Comment by lamont-granquist** [comment]
using site-cookbooks is deprecated functionality.
