### ISSUE TITLE
warning: circular argument reference - data_bag  in chef/data_bag_item.rb:161

### ISSUE THREAD

**Issue by erwin** [chef/chef#2923]
for information

using ruby 2.2.0

/Users/yves/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/chef-12.0.3/lib/chef/data_bag_item.rb:161: warning: circular argument reference - data_bag

**Comment by rmoriz** [comment]
see #2707

**Comment by lamont-granquist** [comment]
will be fixed in 12.1.0

we also don't support anything other than omnibus installed chef/chefdk for production usage, or its your responsibility to track our released omnibus version of ruby.
