### ISSUE TITLE
route resource doesn't handle :delete action correctly

### ISSUE THREAD

**Issue by jimcm** [chef/chef#2927]
### Version:

/usr/bin/chef-client --version
Chef: 11.18.0.rc.1
### Environment:

Red Hat Enterprise Linux Server release 6.6 (Santiago)
### Scenario:

Using route resource to add routes, then delete one of those routes.
### Steps to Reproduce:

<b>Ran this recipe to add 2 routes to eth0</b>

```
route "10.0.1.10/32" do
  gateway "172.16.1.1"
  device "eth0"
  action :add
end
route "10.1.1.0/24" do
  gateway "172.16.1.1"
  device "eth0"
  action :add
end
```

<b>Ran chef-client, works as expected</b>
...snipped...
Running handlers:
Running handlers complete
Chef Client finished, 2/2 resources updated in 1.478233498 seconds
[root]# <b>netstat –rn</b>

<pre>
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
</i>10.0.1.10       172.16.1.1      255.255.255.255 UGH       0 0          0 eth0
192.168.22.16   0.0.0.0         255.255.255.240 U         0 0          0 eth1
172.16.1.0      0.0.0.0         255.255.255.0   U         0 0          0 eth0
10.1.1.0        172.16.1.1      255.255.255.0   UG        0 0          0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 eth1
0.0.0.0         172.16.1.1      0.0.0.0         UG        0 0          0 eth0
</pre>

[root]# <b>cat /etc/sysconfig/network-scripts/route-eth0</b>
10.0.1.10/32 via 172.16.1.1
10.1.1.0/24 via 172.16.1.1
[root] #

<b>Changed recipe to delete one of the routes</b>

```
route "10.0.1.10/32" do
  gateway "172.16.1.1"
  device "eth0"
  action :add
end
route "10.1.1.0/24" do
  gateway "172.16.1.1"
  device "eth0"
  action :delete
end
```

<b>Run client again. Routing table is updated correctly, 
(10.1.1.0/24 route deleted, 10.0.1.10/32 route still there)
but route-eth0 file now has only a single empty line !?</b>

...snipped...
Running handlers:
Running handlers complete
Chef Client finished, 2/2 resources updated in 1.886033576 seconds
[root]# <b>netstat -rn</b>

<pre> 
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
10.0.1.10       172.16.1.1      255.255.255.255 UGH       0 0          0 eth0
192.168.22.16   0.0.0.0         255.255.255.240 U         0 0          0 eth1
172.16.1.0      0.0.0.0         255.255.255.0   U         0 0          0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 eth1
0.0.0.0         172.16.1.1      0.0.0.0         UG        0 0          0 eth0
</pre>

[root]# <b>cat /etc/sysconfig/network-scripts/route-eth0</b>

[root]# <b>wc /etc/sysconfig/network-scripts/route-eth0</b>
1 0 1 /etc/sysconfig/network-scripts/route-eth0
[root]# 
### Expected Result:

I expected contents of /etc/sysconfig/network-scripts/route-eth0 file to be

10.0.1.10/32 via 172.16.1.1

as my recipe had a resource to add this route.
### Actual Result:

The file was empty

**Comment by juliandunn** [comment]
Yep, looks like a bug to me, since `generate_config` invokes [config_file_contents](https://github.com/chef/chef/blob/master/lib/chef/provider/route.rb#L183) with a `:delete` action, but that function doesn't implement `:delete` so the empty string is returned: https://github.com/chef/chef/blob/master/lib/chef/provider/route.rb#L217-L227

**Comment by lamont-granquist** [comment]
Should validate this is still a bug in 12.4.0 but I'll bet it still is
