### ISSUE TITLE
Windows Explicit Rights Should Be Maintained

### ISSUE THREAD

**Issue by sean-horn** [chef/chef#2930]
As a customer, I would like files and directories with windows rights to be capable of
modifying those rights, rather than only replacing them.

When assigning Windows rights to a file object, chef-client should maintain whatever explicit rights currently exist on that object.

From the docs at https://docs.chef.io/resource_file.html#windows-file-security we see

Some other important things to know when using the rights attribute:
- Only inherited rights remain. All existing explicit rights on the object are removed and replaced.

ZenDesk 2934

**Comment by lamont-granquist** [comment]
We have this issue on unix as well.  We only support applying full octal modes like `0777` and do not support operations like `ug-s` to strip setuid bits leaving the other perms.

Fixing this will involve deep changes to `Chef::FileAccessControl::[Unix,Windows]` to support not only comparing rights but diffing rights and applying the diffs.

**Comment by lamont-granquist** [comment]
https://tickets.opscode.com/browse/CHEF-1857

**Comment by adamedx** [comment]
The workaround here is to use something like icacls.exe with /grant or /remove to modify permissions -- I do this every now and then on the cli for desktop scenarios. Given the complexity of the Windows permission system (it already has inheritance in the mix, and precedence of deny aces over allow aces), I think this is a useful new feature that would be less likely to be used when building infrastructure where the outcomes need to be predictable. This is a good candidate for a contribution, and we could also solicit more customer feedback at https://feedback.chef.io.

Another possibility includes adding dsl support for obtaining the current security descriptor and modifying it before passing it to the `file` resource's `rights` property. Here's an option I've thought about: we already have infrastructure in chef-client for obtaining .net objects as Ruby objects. We could make a public API for that, in which case you could obtain the security descriptor has a ruby object. Then you'd just need a helper to turn it into something the file resource would like (along with your own modifications) to handle the use case in this issue (along with many others).

**Comment by adamedx** [comment]
Oh, it should be noted that PowerShell's `set-acl` does not seem to support modifying permissions directly -- I think you have to use `get-acl`, then change the acl, then use `set-acl`. @smurawski can correct me if I'm wrong here. That could also be a good workaround for this issue -- you could do something like this:

```ruby
powershell_script 'make sure i have access' do
not_if '(get-acl c:/mystuff).get-accessrules() | <something that verifies my ace is there'
code <<-EOH
$current = get-acl c:/mystuff
$current.AddAccessRule(<something to add my ace>)
set-acl path c:/mystuff -aclobject $current
EOH
end
```
