### ISSUE TITLE
org-user-add -a flag does not give billing-admin rights.

### ISSUE THREAD

**Issue by FearTheBadger** [chef/chef#2936]
I ran in to a case where I created a new organization but didn't associate a user at creating.  I then after the fact added a user with org-user-add setting the -a flag to make that user an admin.  org-user-add added the user and made them a normal admin, but did not give them billing-admin rights.  I could find no way to give any user the rights to view/modify billing-admins without deleting the org and re-creating.  I'm not sure if this is by design or if it is a bug.  Either way a method for adding a user to billing-admins when there is no one currently holding the role, would be much appreciated.

**Comment by lamont-granquist** [comment]
This repo is only for the chef-client.  Chef-server bugs need to go into http://github.com/chef/chef-server

**Comment by FearTheBadger** [comment]
sorry about that, I didn't realize I was in the wrong repo.  Thanks for the correction.
