### ISSUE TITLE
Knife cookbook list as json doesn't really list as json

### ISSUE THREAD

**Issue by petecheslock** [chef/chef#2938]
```
$ knife cookbook list -f json
[
  "7-zip                  1.0.2",
  "apt                    2.4.0",
  "ark                    0.9.0",
  "aws                    2.5.0"
]
```

Seems like `knife raw cookbooks` does return nicely details json per @danielsdeleo https://twitter.com/kallistec/status/568088807238549504.

But would make is easier to parse cookbooks via json if it rendered the value better.

**Comment by danielsdeleo** [comment]
Yep, this needs to omit the fancy text formatting when the user asks for json/yaml/etc

**Comment by stevendanna** [comment]
What do we want the expected response to look like?  Currently, here are is what -Fjson looks like for `knife cookbook list` with other options:

```
> knife cookbook list -f json --with-uri
{
  "test": {
    "0.1.0": "https://api.opscode.com/organizations/steve-ocs/cookbooks/test/0.1.0"
  },
  "chef-client": {
    "2.2.2": "https://api.opscode.com/organizations/steve-ocs/cookbooks/chef-client/2.2.2"
  },
[...SNIP...]
```

```
> knife cookbook list -f json --with-uri -a
{
  "test": {
    "0.1.0": "https://api.opscode.com/organizations/steve-ocs/cookbooks/test/0.1.0"
  },
  "chef-client": {
    "2.2.2": "https://api.opscode.com/organizations/steve-ocs/cookbooks/chef-client/2.2.2",
    "2.0.2": "https://api.opscode.com/organizations/steve-ocs/cookbooks/chef-client/2.0.2"
  },
...[SNIP]...
```

I think to match some of the other commands, this might make sense (not real output):

```
> knife cookbook list -f json
{
  "test": [ "0.1.0" ],
  "chef-client": ["2.2.2", "2.0.2"],
...[SNIP]...
}
```

It feels a bit odd to me that `knife cookbook list -fjson` and `knife raw /cookbooks` would still give different results if we went with the above format, but it would be a bit more in line with what the other `list` commands provide.
