### ISSUE TITLE
knife cookbook upload fails when user env:homedrive is a network share

### ISSUE THREAD

**Issue by smurawski** [chef/chef#2939]
The default knife.rb use ENV['HOME'] to determine where the .chef/checksums folder should be.  It appears that Ruby is concatenating HOMEDRIVE and HOMEPATH to get that location rather than using USERPROFILE.  If a users corporate HOMEDRIVE is a network share and not available, this causes knife cookbook upload to fail with an error that it cannot find that drive letter.

**Comment by scarolan** [comment]
\m/

**Comment by btm** [comment]
@smurawski my impression is that HOMEDRIVE\HOMEPATH is usually the same as USERPROFILE. But when it's not, are we going to break a bunch of people if we switch? Or should we fall back to USERPROFILE if we cannot access HOMEDRIVE\HOMEPATH?

**Comment by ksubrama** [comment]
https://github.com/chef/chef/pull/3088 should handle it in the cases where ENV['HOME'] isn't specified in knife.rb.  I'm separately working on the starter kit generators to make sure they don't include default values that reference ENV['HOME'] when we can derive sensible values inside the code.
