### ISSUE TITLE
Chef Deamon locks

### ISSUE THREAD

**Issue by santhoshjavapro** [chef/chef#2945]
Hi,
      I don't know whether its an issue, but I continuously face this problem when daemonizing chef-client, I have configured some 50+ nodes and daemonized chef-client to run for every 5mins in every server using the community chef book "chef-client". but very often my chef-client process stuck and does not continue for days/weeks until I manually kill the locked process.

When i grepped running chef process using "ps aux | grep chef" command

I got this

root       353  0.0  0.4 221743 38255 ?        Sl   Feb11   0:00 chef-client worker: ppid=765;start=13:31:42;                                                                                                    
root       764  0.0  0.4 215471 37587 ?        Sl    2014   0:24 /opt/chef/embedded/bin/ruby /usr/bin/chef-client -d -c /etc/chef/client.rb -L /var/log/chef/client.log -P /var/run/chef/client.pid -i 300 -s 200
root     14035  0.0  0.0 103239   876 pts/0    S+   17:22   0:00 grep chef

When I check my logs to see what happened, 

[2015-02-11T13:31:42+03:00] INFO: Forking chef instance to converge...
[2015-02-11T13:31:42+03:00] INFO: *** Chef 11.10.4 ***
[2015-02-11T13:31:42+03:00] INFO: Chef-client pid: 354
[2015-02-11T13:31:43+03:00] WARN: [inet6] no ip address on venet0
[2015-02-11T13:31:43+03:00] WARN: unable to detect ip6address

this is all I got it in logs for the particular process.(the chef-client before this particular process ran succesfully)

So someone explain me whats happening and why its locking very often? or best way to daemonize chef-client if possible

Note: chef-client cookbook is assigned in all nodes which also will be executed for every 5 mins
Platform : Centos 6.
Chef-client: 11.x

TIA

**Comment by lamont-granquist** [comment]
We did a bunch of work on this in Chef 12.0.0, it is know to be buggy in Chef 11.x and will likely remain that way.

**Comment by santhoshjavapro** [comment]
@lamont-granquist Thanks for answering, so u mean the only way to fix this is to upgrade to 12? Or any other workaround available?

**Comment by lamont-granquist** [comment]
Yes, upgrade to 12.

**Comment by santhoshjavapro** [comment]
Ya will try it, Thanks @lamont-granquist!

**Comment by santhoshjavapro** [comment]
Hi @lamont-granquist I updated my node to chef 12 and tried "chef-client" command and I got this error,

Starting Chef Client, version 12.0.3
[2015-02-20T00:32:40-05:00] ERROR: SSL Validation failure connecting to host: devops-integ.myproj.com - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

================================================================================
Chef encountered an error attempting to load the node data for "USMACHINE"
================================================================================

Unexpected Error:
-----------------
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

[2015-02-20T00:32:40-05:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 2.630475691 seconds
[2015-02-20T00:32:40-05:00] ERROR: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
[2015-02-20T00:32:40-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

We need to boostrap nodes again after updating client?

note: my chef server is running 11.x and now I updated 2 of my clients to 12 and then ran "chef-client" command. I believe its nt surely compatibilty problem.

TIA

**Comment by smurawski** [comment]
Here's a great post on dealing with untrusted certs with Chef 12 - http://jtimberman.housepub.org/blog/2014/12/11/chef-12-fix-untrusted-self-sign-certs/
