### ISSUE TITLE
setuid bit not set (sometimes)

### ISSUE THREAD

**Issue by minshallj** [chef/chef#2951]
to recreate:

1: start with a recipe that looks like
```ruby
file "try_it" do
        action :create
        content "Hey there"
        mode "4755"
        owner "chef"
        group "chef"
end
```
2: run it and inspect the file
```bash
ls -l try_it
-rwsr-xr-x 1 chef chef   9 Feb 19 19:35 try_it
```

3: then edit the recipe to look like this
```ruby
file "try_it" do
	action :create
	content "Hey there"
	mode "4755"
	owner "root"
	group "root"
end
```
4: run it and inspect the file
```bash
ls -l try_it
-rwxr-xr-x 1 root root   9 Feb 19 19:35 try_it
```

note the setuid bit is no longer set, on the next run of chef it will be set however.

**Comment by lamont-granquist** [comment]
This happens on Ubuntu and not Mac correct?

It is because setting the ownership on Ubuntu, even with chown from the command line, strips the setuid bit as a side effect.

**Comment by minshallj** [comment]
This was done in a cent os server, but I assume it holds true for all
Linux.
