### ISSUE TITLE
Wordpress cookbook is constantly asking for a deprecated cookbook

### ISSUE THREAD

**Issue by hectorj2f** [chef/chef#2960]
Hi guys,

I am not able to install a wordpress recipe by using ```knife``` to install a list of cookbooks:

apache2=3.0.1
apt=2.6.1
bluepill=2.3.1
build-essential
chef-sugar=2.5.0
chef_handler=1.1.6
database=4.0.2
iis=4.0.0
iptables=0.14.1
mysql=6.0.13
mysql2_chef_gem=1.0.1
nginx=2.7.4
ohai=2.0.1
openssl=2.0.2
php=1.5.0
php-fpm=0.6.10
postgresql=3.4.16
rbac=1.0.2
rsyslog=1.14.0
runit=1.5.16
smf=2.2.1
tar=0.6.0
windows=1.36.2
wordpress=2.3.0
xml=1.2.10
yum=3.5.3
yum-epel=0.6.0
yum-mysql-community=0.1.13
logrotate=1.8.0

$ knife cookbook site install <cookbook> <version>

When I run ```chef-solo -c solo.rb``` passing the data of my solo.json, I got the following error:

ERROR: Cookbook mysql-chef_gem not found. If you're loading mysql-chef_gem from another cookbook, make sure you configure the dependency in your metadata

Content of solo.json:

{
    "mysql": {
        "service_name": "mysql"
        "server_root_password": "iloverandompasswordsbutthiswilldo",
        "server_repl_password": "iloverandompasswordsbutthiswilldo",
        "server_debian_password": "iloverandompasswordsbutthiswilldo"
    },
    "run_list": [
        "recipe[elasticbox]"
    ]
}

NOTE: If I install my wordpress recipe using berkshelf, it seems surprising to me that it downloads ```mysql_chef_gem``` which is deprecated.

To be able to install my wordpress recipe, I had to downgrade many versions of several packages including the mysql package to avoid this issue.

Thanks.
Hector

**Comment by juliandunn** [comment]
Can you grep the metadata of all the cookbooks inside that tarball or whatever to see what is dependent upon mysql-chef_gem?

I doubt this is a Chef core problem.

**Comment by juliandunn** [comment]
I'm closing this since there hasn't been a response from the OP in >1mo.
