### ISSUE TITLE
sudo chef-server-ctl reconfigure

### ISSUE THREAD

**Issue by jigishmehta86** [chef/chef#2968]
Hi,

Can someone help me solve this issue?

---------------

Recipe: private-chef::postgresql
  * user[opscode-pgsql] action create
================================================================================
Error executing action `create` on resource 'user[opscode-pgsql]'
================================================================================

Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '8'
---- Begin output of ["usermod", "-d", "/var/opt/opscode/postgresql", "opscode-pgsql"] ----
STDOUT: 
STDERR: usermod: user opscode-pgsql is currently logged in
---- End output of ["usermod", "-d", "/var/opt/opscode/postgresql", "opscode-pgsql"] ----
Ran ["usermod", "-d", "/var/opt/opscode/postgresql", "opscode-pgsql"] returned 8

Resource Declaration:
---------------------
# In /opt/opscode/embedded/cookbooks/private-chef/recipes/postgresql.rb

 27: user node['private_chef']['postgresql']['username'] do
 28:   system true
 29:   shell node['private_chef']['postgresql']['shell']
 30:   home node['private_chef']['postgresql']['home']
 31: end
 32: 

Compiled Resource:
------------------
# Declared in /opt/opscode/embedded/cookbooks/private-chef/recipes/postgresql.rb:27:in `from_file'

user("opscode-pgsql") do
  action :create
  supports {:manage_home=>false, :non_unique=>false}
  retries 0
  retry_delay 2
  guard_interpreter :default
  username "opscode-pgsql"
  home "/var/opt/opscode/postgresql"
  shell "/bin/sh"
  system true
  cookbook_name :"private-chef"
  recipe_name "postgresql"
end

Running handlers:
[2015-02-23T18:10:13+00:00] ERROR: Running exception handlers
Running handlers complete

[2015-02-23T18:10:13+00:00] ERROR: Exception handlers complete
[2015-02-23T18:10:13+00:00] FATAL: Stacktrace dumped to /opt/opscode/embedded/cookbooks/cache/chef-stacktrace.out
Chef Client failed. 5 resources updated in 165.203813884 seconds
[2015-02-23T18:10:13+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: user[opscode-pgsql] (private-chef::postgresql line 27) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '8'
---- Begin output of ["usermod", "-d", "/var/opt/opscode/postgresql", "opscode-pgsql"] ----
STDOUT: 
STDERR: usermod: user opscode-pgsql is currently logged in
---- End output of ["usermod", "-d", "/var/opt/opscode/postgresql", "opscode-pgsql"] ----
Ran ["usermod", "-d", "/var/opt/opscode/postgresql", "opscode-pgsql"] returned 8

**Comment by mmzyk** [comment]
@jigishmehta86 You should open this issue agains the https://github.com/chef/chef-server repo, as this is a chef-server issue, not a chef client issue.

I will say that I've never seen this before, but you've got something going on with the opscode-pgsql user, as it's telling you in the error message:

STDERR: usermod: user opscode-pgsql is currently logged in

Perhaps remove that user and run reconfigure again to see if that fixes the issue. A reconfigure should put the user back. This is the user setup by the chef server for it to access the db.

I'm going to close this issue, but if the above doesn't fix it, please reopen agains the chef-server repo. Thanks.

**Comment by jigishmehta86** [comment]
cool. thanks

i can see the Chef web ui login portal. But when i use admin/p@ssw0rd1 credentials, it shows me a 'Some went wrong' page.

Can you suggest what can be wrong there ?

**Comment by mmzyk** [comment]
@jigishmehta86 You must be using open source chef 11 then, is that correct (based on the webui you're referencing)? I'd recommend going with Chef Server 12 - it's the latest and is fully open source. Although it does drop the webui that was used in open source Chef server 11 in favor of Chef Manage, our proprietary webui, which is free for use up to 25 nodes.

That said, to solve this issue you'll want to run chef-server-ctl tail to see the log output and see what error is being thrown. Other than that I can't offer any more specific guidance.

**Comment by jigishmehta86** [comment]
That's correct. I am using the open source chef 11. I will give the above suggestions a shot and see if it resolves my issues.

thanks @mmzyk
