### ISSUE TITLE
Chef webui login error

### ISSUE THREAD

**Issue by jigishmehta86** [chef/chef#2972]
i can see the Chef web ui login portal. But when i use admin/p@ssw0rd1 credentials, it shows me a 'Something went wrong' page.

Can someone suggest what can be wrong there ?

**Comment by smith** [comment]
If you're using Chef server 12 or Enterprise Chef 11, that username and password do not work and you'll have to create an initial account by signing up through the management console or using [`chef-server-ctl user-create`](https://docs.chef.io/ctl_chef_server.html#user-create).

Since you're using that password, my guess it that you may be using open source Chef server 11. I'd recommend using [Chef server 12](https://downloads.chef.io/chef-server/), but if you can't do that, you can try running `chef-server-ctl tail` to see what kind of errors are being logged.

I'm going to close this, since this repository is for the Chef client.

Issues for Open source Chef server 11 are tracked at [chef/omnibus-chef-server](https://github.com/chef/omnibus-chef-server), but the only updates that it receives are security updates, so if you're hitting a non-security-related bug, it probably won't be addressed in that version by Chef Software, Inc.

Issues for Chef server 12 (the current version) can be tracked at [chef/chef-server](https://github.com/chef/chef-server).

Hope that helps. Thanks!

**Comment by jigishmehta86** [comment]
@smith Thank you. I will give it a shot and see if issue gets resolved.

**Comment by jigishmehta86** [comment]
@smith i see these entries in logfile.

The log file if filled with connection disallowed node error.


------------------------------------------

the ffi-yajl and yajl-ruby gems have incompatible C libyajl libs and should not be loaded in the same Ruby VM
falling back to ffi which might work (or might not, no promises)
==> /var/log/opscode/rabbitmq/config <==
# svlogd configuration
S104857600
n10

==> /var/log/opscode/rabbitmq/current <==
2015-02-20_19:00:21.31499 =ERROR REPORT==== 20-Feb-2015::19:00:21 ===
2015-02-20_19:00:21.31500 ** Connection attempt from disallowed node 'rabbitmqctl1139@pte-nova-94934' ** 
2015-02-20_19:00:27.54958 
2015-02-20_19:00:27.54959               RabbitMQ 3.3.4. Copyright (C) 2007-2014 GoPivotal, Inc.
2015-02-20_19:00:27.54959   ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
2015-02-20_19:00:27.54959   ##  ##
2015-02-20_19:00:27.54960   ##########  Logs: /var/opt/opscode/rabbitmq/log/rabbit@localhost.log
2015-02-20_19:00:27.54960   ######  ##        /var/opt/opscode/rabbitmq/log/rabbit@localhost-sasl.log
2015-02-20_19:00:27.54960   ##########
2015-02-20_19:00:27.54960               Starting broker... completed with 0 plugins.
^C%                                                                                                                                [20:33] chef@pte-nova-94934 /home/chef # sudo cd /var/opt/opscode/rabbitmq    
sudo: cd: command not found
[20:33] chef@pte-nova-94934 /home/chef # sudo ls /var/opt/opscode/rabbitmq
db  etc  log
[20:33] chef@pte-nova-94934 /home/chef # sudo ls /var/opt/opscode/rabbitmq/log
rabbit@localhost.log  rabbit@localhost-sasl.log
[20:34] chef@pte-nova-94934 /home/chef # sudo vim /var/opt/opscode/rabbitmq/log/rabbit@localhost.log

config file(s) : (none)
cookie hash    : +L0j2p6UFRKpCdXzZbr+Dg==
log            : /var/opt/opscode/rabbitmq/log/rabbit@localhost.log
sasl log       : /var/opt/opscode/rabbitmq/log/rabbit@localhost-sasl.log
database dir   : /var/opt/opscode/rabbitmq/db/rabbit@localhost

=INFO REPORT==== 6-Feb-2015::15:05:21 ===
Limiting to approx 49900 file handles (44908 sockets)

=INFO REPORT==== 6-Feb-2015::15:05:21 ===
Memory limit set to 2388MB of 5970MB total.

=INFO REPORT==== 6-Feb-2015::15:05:21 ===
Disk free limit set to 50MB

=INFO REPORT==== 6-Feb-2015::15:05:21 ===
msg_store_transient: using rabbit_msg_store_ets_index to provide index

=INFO REPORT==== 6-Feb-2015::15:05:21 ===
msg_store_persistent: using rabbit_msg_store_ets_index to provide index

=WARNING REPORT==== 6-Feb-2015::15:05:21 ===
msg_store_persistent: rebuilding indices from scratch

=INFO REPORT==== 6-Feb-2015::15:05:21 ===
started TCP Listener on 127.0.0.1:5672

=INFO REPORT==== 6-Feb-2015::15:05:21 ===
Server startup complete; 0 plugins started.

=ERROR REPORT==== 6-Feb-2015::15:05:59 ===
** Connection attempt from disallowed node 'rabbitmqctl2578@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:06:34 ===
** Connection attempt from disallowed node 'rabbitmqctl3842@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:07:10 ===
** Connection attempt from disallowed node 'rabbitmqctl5046@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:07:46 ===
** Connection attempt from disallowed node 'rabbitmqctl6314@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:08:21 ===
** Connection attempt from disallowed node 'rabbitmqctl7452@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:08:57 ===
** Connection attempt from disallowed node 'rabbitmqctl8568@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:09:32 ===
** Connection attempt from disallowed node 'rabbitmqctl9712@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:11:16 ===
** Connection attempt from disallowed node 'rabbitmqctl13412@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:11:52 ===
** Connection attempt from disallowed node 'rabbitmqctl14680@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:12:27 ===
** Connection attempt from disallowed node 'rabbitmqctl15844@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:13:38 ===
** Connection attempt from disallowed node 'rabbitmqctl18203@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:14:14 ===
** Connection attempt from disallowed node 'rabbitmqctl19440@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:15:23 ===
** Connection attempt from disallowed node 'rabbitmqctl21607@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:15:59 ===
** Connection attempt from disallowed node 'rabbitmqctl22878@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:16:34 ===
** Connection attempt from disallowed node 'rabbitmqctl24225@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:17:10 ===
** Connection attempt from disallowed node 'rabbitmqctl25483@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:17:46 ===
** Connection attempt from disallowed node 'rabbitmqctl26720@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:18:22 ===
** Connection attempt from disallowed node 'rabbitmqctl28015@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:18:23 ===
** Connection attempt from disallowed node 'rabbitmqctl28015@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:18:59 ===
** Connection attempt from disallowed node 'rabbitmqctl29242@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:19:38 ===
** Connection attempt from disallowed node 'rabbitmqctl30555@pte-nova-94934' **

=INFO REPORT==== 6-Feb-2015::15:19:44 ===
Adding vhost '/chef'

=INFO REPORT==== 6-Feb-2015::15:19:45 ===
Adding vhost '/reindexer'

=INFO REPORT==== 6-Feb-2015::15:19:46 ===
Adding vhost '/jobs'

=INFO REPORT==== 6-Feb-2015::15:19:47 ===
Adding vhost '/analytics'

=INFO REPORT==== 6-Feb-2015::15:19:49 ===
Creating user 'chef'

=INFO REPORT==== 6-Feb-2015::15:19:50 ===
Creating user 'jobs'

=INFO REPORT==== 6-Feb-2015::15:19:51 ===
Creating user 'actions'

=INFO REPORT==== 6-Feb-2015::15:19:52 ===
Setting permissions for 'chef' in '/chef' to '.*', '.*', '.*'

=INFO REPORT==== 6-Feb-2015::15:19:53 ===
Setting permissions for 'chef' in '/reindexer' to '.*', '.*', '.*'

=INFO REPORT==== 6-Feb-2015::15:19:55 ===
Setting permissions for 'jobs' in '/jobs' to '.*', '.*', '.*'

=INFO REPORT==== 6-Feb-2015::15:19:56 ===
Setting permissions for 'chef' in '/analytics' to '.*', '.*', '.*'

=INFO REPORT==== 6-Feb-2015::15:19:57 ===
Setting permissions for 'actions' in '/analytics' to '.*', '.*', '.*'

=ERROR REPORT==== 6-Feb-2015::15:20:15 ===
** Connection attempt from disallowed node 'rabbitmqctl32677@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:21:59 ===
** Connection attempt from disallowed node 'rabbitmqctl3874@pte-nova-94934' **

=ERROR REPORT==== 6-Feb-2015::15:22:34 ===
** Connection attempt from disallowed node 'rabbitmqctl5161@pte-nova-94934' **

**Comment by mmzyk** [comment]
Something is very strange @jigishmehta86. Have you attempted to install analytics on this box? Analytics doesn't work with Open Source Chef 11. I'd highly recommend you move to the Chef 12 server. The Chef 12 server is free and open source as well, but with Chef 12 we made the entire server free, so there is no longer a distinction between Enterprise and Open Source as far as the server is concerned.
