### ISSUE TITLE
execute resource with the same name is being called out of order when executing multiple recipes

### ISSUE THREAD

**Issue by johusta** [chef/chef#2974]
Hi
  So I am not sure if we are coding something wrong. We have some very basic recipes that pull down a tar file and extract using the tar command. I have two recipes that I am running blast and bonnie.

The code that fails is
execute ("extract files") do
  cwd node ["blast"] ["unzip_dir"]
  command "tar -xzvf #{node['blast']['local_zipfile']}
  action: nothing
  end

Blast is first in the run list. During execution when it calls extract files it calls bonnie's "extract files" instead. Bonnie has the same resource statement as above but with the "bonnie" specific dir attributes instead. 

I did not think this would get shared with recipes unless I created a "definition" under the /definition directory within my cookbook?
Do I need to make each execute resource name unique to each recipe in cases where I am running multiple recipes in my run list?
I just lost my work connection but as soon as it come back I will attach some output from the chef-client run.

Thank You!

**Comment by ranjib** [comment]
it will be easier to debug with the output log. check if some other
resource is sending notification, thus altering the order. you should avoid
naming similar resources same, resource type + name should be unique in the
run list

regards
ranjib

**Comment by johusta** [comment]
Thanks for the quick response ranjib...here is the output up to the failure. If we need to rename we can go ahead and do that. I did not find anything in the docs that suggested it so just wanted to make sure as we have a  bunch of recipes like this......



resolving cookbooks for run list: ["chef-client::service", "blast::blast", "bonnie::bonnie"]
Synchronizing Cookbooks:
  - bonnie
  - blast
  - logrotate
  - chef-client
Compiling Cookbooks...
Converging 20 resources
Recipe: chef-client::init_service
  * log[Found chef-client in /usr/bin/chef-client] action write

  * directory[/var/run/chef] action create (up to date)
  * directory[/var/chef/cache] action create (up to date)
  * directory[/var/chef/backup] action create (up to date)
  * directory[/var/log/chef] action create (up to date)
  * directory[/etc/chef] action create (up to date)
  * cron[chef-client] action delete (up to date)
  * template[/etc/init.d/chef-client] action create (up to date)
  * template[/etc/sysconfig/chef-client] action create (up to date)
  * service[chef-client] action enable (up to date)
  * service[chef-client] action start (up to date)
  * template[/etc/logrotate.d/chef-client] action create (up to date)
Recipe: blast::blast
  * directory[/opt/thrashers] action create (up to date)
  * directory[/opt/thrashers/blast] action create
    - create new directory /opt/thrashers/blast
    - change mode from '' to '0755'
    - change owner from '' to 'root'
    - change group from '' to 'root'
    - restore selinux security context
  * remote_file[/opt/thrashers/blast/blast_s390x_8.10.tar.gz] action create
    - create new file /opt/thrashers/blast/blast_s390x_8.10.tar.gz
    - update content in file /opt/thrashers/blast/blast_s390x_8.10.tar.gz from none to 47329f
    (new content is binary, diff output suppressed)
    - change mode from '' to '0755'
    - change owner from '' to 'root'
    - change group from '' to 'root'
    - restore selinux security context
Recipe: bonnie::bonnie
  * execute[extract files] action run

    ================================================================================
    Error executing action `run` on resource 'execute[extract files]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of tar -xzvf /opt/thrashers/bonnie++/bonnie++-1.03e.tar.gz  ----
    STDOUT:
    STDERR: /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.0.1/lib/mixlib/shellout/unix.rb:147:in `chdir': No such file

**Comment by lamont-granquist** [comment]
If you name a resource with the same name then chef considers them the same thing and you get CHEF-3684 warning statements.  This is a valid thing to do in some cases when multiple recipes attempt to install the same `package "whatever"` resource.  However, if you have two `execute "extract files"` resources and have wildly different code blocks then Chef will consider those basically the same resource and you will get bad results.  Again this is what the CHEF-3694 warning is attempting to warn you about and those errors need to not be ignored.  You MUST rename those resources.  Either rename then and hard-code the different things:

```ruby
execute "extract bonnie files" do
....
end

execute "extract blast files" do
...
end
```

Or if you've got reusable code in an LWRP use interpolation to create a unique string:

```ruby
execute "extract #{new_resource.name} files" do
...
end
```

This is not a fixable bug and is just how Chef works internally.  The names on resources matter.  They must be unique GUIDs for things like notifications and subscribes.
