### ISSUE TITLE
unable to bootstrap a node. 

### ISSUE THREAD

**Issue by katmai** [chef/chef#2975]
hi guys, i am trying to bootstrap a node but i just can't get it working. i am trying to bootstrap a mirabox device running debian, from my ubuntu vm. i can ssh from the vm just fine into the device, i can ping it, i added the dns entries in /etc/hosts, i even did a real subdomain dns that resolves to the ip of the mirabox but still i can't bootstrap it.

katmai@chefserver:~/chef-repo$ knife bootstrap {{192.168.1.131}} --ssh-user {{root}} --ssh-password '{{nosoup4u}}' --sudo --use-sudo-password --node-name mirabox.512kbps.com --run-list 'recipe[learn_chef_apache2]' -VVV
INFO: Using configuration from /home/katmai/chef-repo/.chef/knife.rb
Connecting to {{192.168.1.131}}
DEBUG: Looking for bootstrap template in /opt/chefdk/embedded/apps/chef/lib/chef/knife/bootstrap
DEBUG: Found bootstrap template in /opt/chefdk/embedded/apps/chef/lib/chef/knife/bootstrap
DEBUG: Adding {{192.168.1.131}}
DEBUG: establishing connection to {{192.168.1.131}}:22
ERROR: Network Error: getaddrinfo: Name or service not known
Check your knife configuration and network settings
katmai@chefserver:~/chef-repo$

any ideas what i might be doing wrong? would be greatly appreciated.

**Comment by ranjib** [comment]
why curly braces?

knife bootstrap 192.168.1.131 --ssh-user root --ssh-password nosoup4u
--sudo --use-sudo-password --node-name mirabox.512kbps.com --run-list
'recipe[learn_chef_apache2]' -VVV

**Comment by katmai** [comment]
I swear i was thinking about that. I am just learning chef, and that's what it was in the tutorial.Didn't check the syntax output from knife :/ gosh i feel dumb. thanks a lot!
