### ISSUE TITLE
knife data_bag create should create the directory locally 

### ISSUE THREAD

**Issue by tspaulding295** [chef/chef#2978]
This is the code that creates the data_bag on the Chef Server.
https://github.com/chef/chef/blob/0819eafa6fd664815856fe0081dfcafabd59dcf6/lib/chef/knife/data_bag_create.rb#L52

Whilst creating the data_bag on the Chef Sever there is no additional step to create the directory on the local workstation.  This is input from customers based on the behavior of our other knife noun create commands. IE: Knife cookbook create

**Comment by charlesjohnson** [comment]
Does this work? "As a chef developer, I want to automatically create a matching data_bag object in my chef-repo (if one does not already exist) when I create a data_bag object on the chef server, so that I can be assured that no data_bag object is created on the server without also existing in a source code repository."

**Comment by smurawski** [comment]
This should be part of the knife subcommand cleanup - https://github.com/chef/chef/issues/3368

**Comment by lamont-granquist** [comment]
Don't think this should be part of the overall subcommand cleanup, I have strong doubts that will ever happen.

**Comment by snehaldwivedi** [comment]
@lamont-granquist & @tspaulding295  - knife data bag create DATA_BAG_NAME [DATA_BAG_ITEM] (options) does not create directory locally on your workstation https://docs.chef.io/workstation/knife_data_bag/ 
It is a new feature/enhancement on current knife create databag functionality so should we go ahead and implement the same? 
If yes then some more specifications will be needed ..  like how will other commands for databag work e.g knife data bag edit?
