### ISSUE TITLE
knife gives unhelpful error messages with invalid flag parameters

### ISSUE THREAD

**Issue by eropple** [chef/chef#2979]
When using command flags that accept only a discrete set of options, Chef returns an unhelpful message when you use one that doesn't exist. To wit:

``` bash
$ knife search node -i -F raw 'tags:foobar'
ERROR: ArgumentError: Unknown output format raw
```

This resulted in having to go comb the docs for the accepted values for `-F`; it seems to me that it would be significantly better for users for it to return something like this:

``` bash
$ knife search node -i -F raw 'tags:foobar'
ERROR: ArgumentError: --format/-F: invalid value 'raw'. Valid values: text, json, yaml, pp
```

Also annoying: it also outputs this error _after_ doing the search, which means that as a user I'm waiting for a few seconds for nothing.

**Comment by thommay** [comment]
Yup, this is annoying and we should fix it.
