### ISSUE TITLE
Add template location(ie. cookbook and recipe) as variables to template

### ISSUE THREAD

**Issue by andrenaumann** [chef/chef#2984]
Hi!

I usually add a comment to rendered templates indicating, that a file was rolled out by Chef..
```
# File rolled out by chef
```

This already prevents people from editing files and losing their additions during the next Chef run, but it would be great if I could use something like `#{cookbook_name}` and `#{recipe_name}` which are already present in recipes.

I could of course hand them over to the template using variables, but I find these so comfortable that I think, they should be available by default, so I could just add something like this to every template without having to do anything to prepare it:

```
# File rolled out by chef in <%= @cookbook_name %>::<%= @recipe_name %>
```

If I could do that, people would know where to look to change a file, instead of doing a chef run themselves or having to grep through all the templates in our Chef repository.

I know I can do it like this:

```
template "/path/to/file" do
  source "template.erb"

  variables({
    :cookbook_name => cookbook_name,
    :recipe_name => recipe_name
  })
end
```

but I wouldn't want to have to write that into each and every template block...

Kind regards,
Andre Naumann

**Comment by lamont-granquist** [comment]
Dup of #1259
