### ISSUE TITLE
[Question] Any advice on customize remote_file download process?

### ISSUE THREAD

**Issue by shuoli84** [chef/chef#2987]
Hi Chef devs, I am on boarding chef in our company. There is one thing really bothered me a lot, that is the "remote_file" resource. It downloads from remote url which really a big waste of time and bandwidth, and some sites also been blocked by GFW(China's great firewall, yay!!).

I created a project [peach](https://github.com/shuoli84/peach) to solve the problem for wget and curl, but not for chef yet. That's why I am seeking advice here, do you have any suggestion for the problem? Should I create a pull request or should I create a plugin? 

Integration is very simple: read the peach server config form /etc/peach, wrap the real download link as 
```
http://peachserver?file_url=[the real url]
``` 
Then everything settled. The first time peach met the url, it will download from source(with proxy support) and stream the result to the client, next time, it will serve directly from its cache. And It is far from mature yet.

**Comment by ranjib** [comment]
create a cookbook or ruby gem that offers peach based download as a
resource provider. you can use LWRP[1] to create custom resource/providers
easily.

[1]https://docs.chef.io/lwrp.html

**Comment by shuoli84** [comment]
@ranjib thanks for the quick reply. Quick question, Can I overwrite the remote_file or I create a new remote_file_peach? If it is the later one, then all the third party cookbooks are out of luck.

**Comment by andrenaumann** [comment]
If prefixing the URL with $peachserver is everything you need to do, you can always do something like this:

```
remote_file "/tmp/testfile" do
  source node["peachserver"] + "http://www.example.com/tempfiles/testfile"
  mode '0644'
  checksum "3a7dac00b1" # A SHA256 (or portion thereof) of the file.
end
```

and set peachserver to a default of "" in your recipe..
If needed, you can override the attribute with the peachserver to use or leave it empty without having to create yet another resource for downloading a file...

Alternatively: Configure a proxy in client.rb

**Comment by shuoli84** [comment]
@andrenaumann If I do prefixing in recipe, then all third party cookbooks are out of luck.

Configure a proxy can't help too much, since proxy can't cache https stuff.

If the ETag support required, then I can add the feature in peach.

**Comment by andrenaumann** [comment]
@shuoli84  I'm doing well, thank you :)     Just wanted to point out, that things like that can be had rather cheaply.. 

And in its current state, you'd be better off adding all those files to your recipe and roll them out with cookbook_file or remote_directory, because it doesn't do much more ;)

Don't let me discourage you from improving peach, once it can be configured from outside the source and updates files when the http source is updated and a few other things, it might be quite useful :)

**Comment by shuoli84** [comment]
Thanks guys, based on my investigation, seems "monkey patching" is the way to go. I monkey patched RemoteFile::HTTP::fetch, which gives what I need.

Thanks for the advice @andrenaumann. Sure I will improve peach, it saved me hours of time while try and dev cookbooks.
