### ISSUE TITLE
Add cookbook version numbers to chef-client output (CHEF-4446)

### ISSUE THREAD

**Issue by csandwith** [chef/chef#2989]
Re: https://tickets.opscode.com/browse/CHEF-4446

```
# chef-client --once
Starting Chef Client, version 11.6.0
resolving cookbooks for run list: ["users"]
Synchronizing Cookbooks:
  - users
Compiling Cookbooks...
Converging 0 resources
Chef Client finished, 0 resources updated
#
```

It would be awesome if the output of chef-client would tell us the version of a cookbook that it was installing.

Possible output style:

```
...
Synchronizing Cookbooks:
  - users [1.5.0]
...
```

This feature would have saved me hours of debugging.

(Note from Datamancer: This would have saved _me_ hours of debugging too. Since it should take a seasoned Chef dev approximately 2.3 seconds to implement, would you mind?)

**Comment by kungfujoe** [comment]
A Pull request has been created that resolves this ticket. It can be viewed here:
https://github.com/chef/chef/pull/3202
