### ISSUE TITLE
chef-sync broken since chef-server-core 12.0.4

### ISSUE THREAD

**Issue by jwestboston** [chef/chef#2993]
The chef-sync system (as a client) is broken when used in conjunction with chef-server-core 12.0.4 and 12.0.5.

This is being done on RHEL 6 (CentOS 6) .. as I'm still waiting for chef-server to work on CentOS 7.

I can post logs if needed, but just try a fresh setup and you will see it does not work.  The ec_sync_client process fails to run and logs ruby errors regarding bundle.

**Comment by stevendanna** [comment]
Closing this one as it has also been filed against server. Thanks!
