### ISSUE TITLE
OS X Chef-client installer package doesn't handle non-startup disks

### ISSUE THREAD

**Issue by nmcspadden** [chef/chef#3003]
### Version:
chef-client OS X 12.0.3

### Environment: 
OS X Yosemite 10.10.2 (will also apply to any OS X 10.7-10.10).

### Scenario:
The OS X chef-client installer (chef-12.0.3-1.pkg as of writing time) makes the assumption that it's only ever installing on the startup volume.  If you run the Chef client installer in the OS X Recovery environment, or the startup environment (such as by adding the Chef client installer to an OS X installation), the postflight script will fail.

### Steps to Reproduce:
1. Download the OS X chef client - 12.0.3-1.dmg, which contains "chef-12.0.3-1.pkg".
2. Download the Install OS X Yosemite.app installer from the Mac App Store.
2. Use [createOSXInstallPkg](https://github.com/munki/createOSXinstallPkg) to create a custom OS X installer for Yosemite:  
`sudo ./createOSXinstallPkg --source /Applications/Install\ OS\ X\ Yosemite.app  --pkg chef-12.0.3-1.pkg`
3. Install the new OS X installation package (on a VM, or test machine, or using NetBoot).

### Expected Result:
OS X should install successfully, and chef-client should be properly installed when the OS boots for the first time.

### Actual Result:
The installation will fail because of the postinstall script in the chef-12.0.3-1.pkg.  Specifically, it will fail here in the postinstall script:

    INSTALLER_DIR=/opt/chef
    CONFIG_DIR=/etc/chef

The package will try to install to /opt/chef and /etc/chef from the *currently booted OS*, which in the case of the OS X installer is actually the Recovery system, not the OS X installation.

To fix this, the target directories should be:

    INSTALLER_DIR="$3/opt/chef"
    CONFIG_DIR="$3/etc/chef"

When this script is then run by /usr/sbin/installer, $3 will correctly point to the volume that is being installed on - i.e. the target disk, which is receiving a new OS.

Some details on $3 in a package installation script can be found in [this legacy Apple package document](https://developer.apple.com/legacy/library/documentation/DeveloperTools/Conceptual/SoftwareDistribution4/Install_Operations/Install_Operations.html#//apple_ref/doc/uid/TP40004615-CH14-DontLinkElementID_9).

**Comment by nmcspadden** [comment]
Additionally:  
``PROGNAME=`basename $0` `` fails because `basename` doesn't exist in the OS recovery environment.
Thus, this line will also fail:  
`USAGE="usage: $0 [-v validation_key] ([-o organization] || [-u url])"`  

Additionally, the same issue occurs with PREFIX later on:  

    if is_smartos; then
        PREFIX="/opt/local"
    else
        PREFIX="/usr"
    fi

This should be:

    if is_smartos; then
        PREFIX="/opt/local"
    else
        PREFIX="$3/usr"
    fi

**Comment by lamont-granquist** [comment]
Are you expecting to actually be able to run out of a different path?  Because all of the shebang lines are going to be your next issue, then all the baked in rpaths in the binaries, and whatever other references there are to /opt/chef in the packages.

**Comment by nmcspadden** [comment]
No, those will work properly on the booted OS X system.  This issue is specifically only going to occur if installing in the OS X system installer environment - which is admittedly going to be a fairly edge case.

The point is that when the Chef client package is installing, it's going to run this postinstall script in the package, and the script is going to try do this, as an example:
`mkdir -p /etc/chef || error_exit "Cannot create ${CONFIG_DIR}!"`

If the chef client is being installed on a volume that is **not the current running boot volume**, then the script is going to create /etc/chef on the **boot** volume and not the **target** volume.  Which means, when the target volume boots, /etc/chef won't be present.  

The primary issue is that, in the OS X recovery environment / OS install environment, the target volume is actually /Volumes/Image Volume/ and not /.  Thus, "/etc/chef" really needs to be "/Volumes/Image\ Volume/etc/chef".

This happens with the symlinks below:
`ln -sf $INSTALLER_DIR/bin/chef-solo $PREFIX/bin`
If $INSTALLER_DIR is "/opt/chef" and $PREFIX is "/usr", this becomes:
`ln -sf /opt/chef/bin/chef-solo /usr/bin`

That will create a symlink on the **running** OS, not the target volume.

If this package is being installed on the non-booted OS, this postinstall script basically won't do what it's supposed to do.

By prefixing all the target volume paths with $3, it will prepend the correct target disk.  In addition, all the paths need to be properly quoted to avoid issues with the fact that OS X puts a space in the name during install:
`ln -sf $3/opt/chef/bin/chef-solo $3/usr/bin`
This becomes:
`ln -sf /Volumes/Image Volume//opt/chef/bin/chef-solo /Volumes/Image Volume/usr/bin`
which obviously breaks.

So again, this is a bit of an edge case - but it's an install situation that is possible on OS X that the postinstall script doesn't permit (and will break).

**Comment by lamont-granquist** [comment]
So those scripts are all over here:

https://github.com/chef/omnibus-chef/blob/master/package-scripts/chef/postinst

Those scripts run on every platform we install, though, so any patch to them needs to not be macosx specific and needs to be able to do the right thing on all of them.

**Comment by nmcspadden** [comment]
I was able to solve the problem a different way, by writing an AutoPkg recipe that creates the package I need.  Rather than have a postinstall script generate the symlinks, I put the symlinks directly into the package payload - which is less fragile and not dependent on a postinstall script that may break in certain OS X install environments.  I have that available here: 
https://github.com/autopkg/nmcspadden-recipes/blob/master/ChefClient/scripts/postinstall

**Comment by nmcspadden** [comment]
Sorry, last comment and I'll close the issue - but I have to wonder why, if you already have a mechanism that successfully generates OS X flat packages, which is OS X-dependent, you can't adopt more platform-specific fixes into the package.  I understand that you have a postinstallation script that works across all platforms, but since you're already generating an OS X package payload out of the Chef client contents, why not follow the guidelines for better packaging on OS X?

The postinstall script I'm using takes the risk out of the package installation, and becomes more versatile as a result - all files that are created are in the payload itself (with the exception of client.rb).  The postinstallation script doesn't do much in this case, but I left it in for posterity.

**Comment by lamont-granquist** [comment]
We could do that, would need to see the PR.  The reason why its not done is that nobody paid enough attention to it and there was already a solution which worked for every use case we were aware of.  I can pretty much guarantee that nobody here is an expert on OSX packaging.

**Comment by nmcspadden** [comment]
I took a look through the packaging process / build scripts, and did a test build myself (which works up until it requires the identity, which I obviously don't have).  It calls /usr/bin/pkgbuild and /usr/bin/productbuild (Apple's special package building mechanisms) during the build stage, but I can't find where in the scripts you linked that actually gets invoked.  Maybe I just don't know enough about the Jenkins setup, but I just can't identify at what stage that happens.

I'm not a Chef expert, but I'm very familiar with OS X packaging. My suggestion would still be to create the symlinks ahead of time and add them into the package payload, rather than relying on a postinstall script to do this.  As I said, I can't figure out where in the script the Packager::PKG handler is called, and where one can modify the contents of the pkgroot (located in /var/folders/) - but that would be the ideal solution.

Since I have a working solution with AutoPkg, it seems a lot of effort to fix something that's only broken in a fairly uncommon edge case that nearly all install processes will not experience.  (Although you still can't install the Chef package on any volume other than the boot volume).

**Comment by mikedodge04** [comment]
CC @sersut and @jtimberman

**Comment by adamedx** [comment]
@nmcspadden thanks for raising this. Are you ok closing at this point given the workaround you have available?

**Comment by nmcspadden** [comment]
Sorry for the delay on this response, but yes - this issue is no longer
particularly relevant to me, but I still would like to encourage safer Mac
packaging practices that work in more environments.

On Wed, Jul 22, 2015 at 10:26 AM, Adam Edwards <notifications@github.com>
wrote:

> @nmcspadden <https://github.com/nmcspadden> thanks for raising this. Are
> you ok closing at this point given the workaround you have available?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chef/chef/issues/3003#issuecomment-123798853>.
>



-- 
--
Nick McSpadden
nmcspadden@gmail.com
