### ISSUE TITLE
docker /etc/hosts, /etc/resolv.conf udpates => Chef-Apply does not work with template resources

### ISSUE THREAD

**Issue by epcim** [chef/chef#3005]
I would like to highliht ticket from JIRA. "Chef-Apply does not work with template resources". lly

The issue actually block some operations while using Chef on Docker. It basically fails to perform simple template operations at some situations.

Original JIRA ticket:
https://tickets.opscode.com/browse/CHEF-4002?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel

My comments and how it impact chef on docker w/examples:
https://github.com/docker/docker/issues/9295#issuecomment-71485104

**Comment by lamont-granquist** [comment]
chef-apply runs a single text file in isolation and has no cookbook structure so it cannot support template or file resources.  `chef-client -z` (aka 'local-mode' or 'chef-zero') should be used to support full cookbooks and use file and template resources.
