### ISSUE TITLE
package resource fails to install local package specified with source attribute

### ISSUE THREAD

**Issue by causton81** [chef/chef#3008]
Trying to install a local package with `package` resource and `source` attribute fails with `No candidate version available for ...`

Version 12.0.3 works fine. 12.1.0 does not.

**Comment by jdmundrawala** [comment]
What OS?

**Comment by causton81** [comment]
CentOS release 6.6 (Final)

On Tue, Mar 3, 2015 at 1:45 PM, Jay Mundrawala <notifications@github.com>
wrote:

> What OS?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chef/chef/issues/3008#issuecomment-77019466>.
>



-- 
-ca

**Comment by causton81** [comment]
The problem appears to be here:
https://github.com/chef/chef/blob/master/lib/chef/provider/package.rb#L57-L60

**Comment by lamont-granquist** [comment]
We're probably going to need the full stack trace, the -ldebug output and the RPM that you're trying to install and if a prior version of the RPM is installed or not.

**Comment by lamont-granquist** [comment]
Can't replicate this one either.  For apt_package I just get:

"apt package provider cannot handle source attribute. Use dpkg provider instead"

Changing to dpkg_package works fine:

```ruby
#!/usr/bin/env chef-apply

dpkg_package "chef" do
  source "/home/lamont/chef.deb"
end
```

**Comment by causton81** [comment]
I am installing an Oracle jdk7 rpm. If the package does not already exist
in yum metadata then you should see the issue.

**Comment by jaymzh** [comment]
@lamont-granquist yeah, it's because chef is in your apt metadata. If you do:

```
package 'balbal' do
  source "/home/lamont/chef.deb"
end
```

You'll repro this. I'm unclear how it broke though the old assertions seem to enforce the same thing.

**Comment by jaymzh** [comment]
Something like this seems to to suffice:

```
--- a/lib/chef/provider/package.rb
+++ b/lib/chef/provider/package.rb
@@ -56,7 +56,7 @@ class Chef
         end
 
         requirements.assert(:upgrade, :install) do |a|
-          a.assertion  { candidates_exist_for_all_uninstalled? }
+          a.assertion  { candidates_exist_for_all_uninstalled? || new_resource.source }
           a.failure_message(Chef::Exceptions::Package, "No candidate version available for #{packages_missing_candidates.join(", ")}")
           a.whyrun("Assuming a repository that offers #{packages_missing_candidates.join(", ")} would have been configured")
         end
```

I'm not entirely certain I'm not missing something though.
