### ISSUE TITLE
package resource no longer supports `action :nothing` in chef 12.1 release

### ISSUE THREAD

**Issue by martinb3** [chef/chef#3009]
https://github.com/chef/chef/pull/2692 appears to have broken support for `action :nothing` on a package resource. Any action other than `:install` or `:upgrade` appears to trigger an exception from https://github.com/chef/chef/blob/master/lib/chef/provider/package.rb#L369-L372.

According to [the docs](https://docs.chef.io/resource_common.html), the `:nothing` action is common and should be supported everywhere.

CC @lamont-granquist @jaymzh

**Comment by lamont-granquist** [comment]
I'm having trouble replicating it.  This works for me:

```ruby
#!/usr/bin/env chef-apply

package "libxslt-dev" do
  action  :nothing
end

log "foo" do
  notifies :install, "package[libxslt-dev]"
end
```

**Comment by jdmundrawala** [comment]
same here... tried on centos

**Comment by tyler-ball** [comment]
Ditto on osx - don't see this issue.  @martinb3 what system are you on?

**Comment by martinb3** [comment]
I'm actually seeing it when called through `chef_gem`. We have a cookbook that makes direct use of the 'rest-client' gem, and that's where I'm seeing it with Ubuntu 14.04:

```
# ensure rest-client gem is available
chef_gem 'rest-client' do
  action :nothing
end.run_action('install')
```

**Comment by martinb3** [comment]
It looks like changing the last line to `end.run_action(:install)` fixes it. Perhaps this is just an undocumented change from 12.0.x to 12.1.x?

**Comment by jaymzh** [comment]
I don't believe strings for actions has ever been explicitly supported, and probably worked by accident. I think Lamont's cleanup probably just more tightly enforced the requirements here.

**Comment by martinb3** [comment]
No worries. I'll go ahead and close this. It might be worth adding to the release notes that it does break backwards compatibility, even if it wasn't supported to begin with. Thanks all!

**Comment by lamont-granquist** [comment]
yeah, i'm surprised `'install'` ever worked, definitely not part of our documented API.

**Comment by btm** [comment]
we should check/raise the type passed to run_action.
