### ISSUE TITLE
Knife user creation doesn't work in Chef 12

### ISSUE THREAD

**Issue by luckymike** [chef/chef#3010]
```
knife user create foo --admin -p xxxxxxxxxxxxxxxx
```
Opens an editor with the following:
```
{
  "name": "foo",
  "public_key": null,
  "admin": true,
  "password": "xxxxxxxxxxxxxxxx"
}
```   
Saving gives this error:
```                                          
ERROR: The data in your request was invalid
Response: Field 'username' missing
```
Changing `name` to `username` then saving results in the same error.

**Comment by joerg** [comment]
Same here. I also tried setting "name" and "username"...

**Comment by btm** [comment]
Does this work for any version of Chef 12? That is, did 12.0.3 work, or just 11.x.x?

**Comment by stevendanna** [comment]
The short answer: You probably want to either (1) use chef-server-ctl user-create or (2) temporarily configure your knife client to such that the chef_server_url is the root of the chef server (no "organization/ORGNAME" in the URL) and the client is pivotal.

In Chef 11 Server: This command should work as expected.

In Chef 12 Server: Whether `knife user create` will work depends on the user making the request and the chef_server_url.  Chef 12 has the following user endpoints that expect POST:

- `POST /users`:

This endpoint creates a new user.  With `chef_server_url` set to the root of your Chef server, and using the pivotal user, this command should work without modification.

- `POST /organizations/ORGNAME/users`:

This endpoint force-associates an *existing* user with an organization (without the user accepting the invite).  This only works for the pivotal user.  The expected POST body is:

    { "username": "USERNAME" }

`knife user create` does not post the raw JSON that you enter into the editor.  Rather, it uses it to construct a valid Chef::User object where the name field is "name" and not "username".  In fact, it looks like it will probably ignore the username field altogether and will always pass the "name" field which isn't accepted by the organization-specific version of this endpoint.

**Comment by dcws** [comment]
This also doesn't work.  Then error morphs to "Field 'display name' missing.

**Comment by jblaine** [comment]
I can't see how this isn't a bug, somewhere, from many perspectives, regardless of the choice of fix path. Could someone with privs add the bug label to this issue, please?

**Comment by stevendanna** [comment]
@jblaine I doubt anyone disagrees with you.  I don't think the bug vs feature tags are used very reliably at the moment.  

@dcws Apologies on missing the display name issue.  On Chef 12 likely the only way to create a user right now is the user-create command.  Even when knife is fixed, you'll still need the super-user key to create users, which the user-create command uses underneath.

I'll assign this to myself to fix.

**Comment by stephenwrightii** [comment]
I'm also having the same problem.  Upgraded from chef 11 to chef 12.  I was working on process to backup our open source chef server and restore it to another server.  Everything is working except the users.  If i do a knife user show USERNAME.   It will not show the name of the user and if the user is an administrator the tag "admin:      false" is always returned.  It's never true.  This is causing a problem with the knife-backup gem.  The backing up of the users is not working as expected.

**Comment by joerocklin** [comment]
Just upgraded to ChefDK 0.6.0 hoping that it might somehow, magically, have been resolved, but it's still an issue - even trying to change the server URL (display_name field missing error instead of username).

**Comment by sdarwin** [comment]
I'm also getting this one:  "If i do a knife user show USERNAME. It will not show the name of the user and if the user is an administrator the tag "admin: false" is always returned. It's never true."

**Comment by spuder** [comment]
+1 This is a blocker for me as I can't find any workaround. 

```
chef --version
Chef Development Kit Version: 0.5.1
chef-client version: 12.3.0
berks version: 3.2.3
kitchen version: 1.4.0
```

**Comment by stevendanna** [comment]
@spuder This is being worked on here: https://github.com/chef/chef/pull/3438  

However, if you are on chef-server 12, then you should be able to create users with `chef-server-ctl user-create`.  Is that not working for you?

**Comment by spuder** [comment]
Yes, running `chef-server-ctl user-create` on the server appears to be a valid workaround.

**Comment by tylercloke** [comment]
Fix to `knife user` for Chef 12 is coming in this PR: https://github.com/chef/chef/pull/3438 

However, only the superuser has permission to create new users in Chef 12 (there is no concept of global admins in Chef 12 like there was in Open Source Chef 11), so `chef-server-ctl` is probably still going be the easiest way to create new users (at least for now), but once this fix is shipped, if you set up a knife config for the superuser, you can use `knife user` to create new users via knife (see `/etc/opscode/pivotal.rb` on a Chef 12 Server for an example of this, or just use `chef-server-ctl` for now).

Again, `chef-server-ctl user create` is gonna be your best option, at least until we make user creation permissions more configurable, but this branch should make things less confusing and actually works with Chef 12.

Hope this helps :)

**Comment by luckymike** [comment]
@tylercloke The entire reason to have `knife user`, IMO, is to allow individual org admins to create additional users within the org. Using the superuser is indeed redundant, and doesn't address this.

**Comment by tylercloke** [comment]
@luckymike Its a matter of permissions currently. User objects are global to the server, and are not specifically scoped to organizations, so by default, only the superuser has create access on Users, since "admins" are now scoped to orgs in CS12. However, as stated above, I agree `knife user` isn't that valuable against CS12 without more flexibility around User creation permissions. User creation and management is something I'm thinking about and would love to make easier for everyone :) I'll write up an RFC on how I think we could make User management and permissions better when I get a chance.

At least now, you will get a relevant error message about permissions instead of code that is completely broken against CS12, and is a base for future improvement.

**Comment by luckymike** [comment]
An Org admin has permissions to create Org users via the $$ console, correct? If so, this doesn't seem like a permissions issue, so much as exposing the correct, existing permissions.

**Comment by tylercloke** [comment]
Org admins cannot create users in Enterprise Chef / Chef Server 12. Only the superuser can in those versions of the server. Org admins can simply add and remove existing users from their org, but that all that does is restrict or grant user access to the org itself. It does not affect existence of the user as a whole.

**Comment by luckymike** [comment]
Ah, I see. Thanks for the clarification.

**Comment by tylercloke** [comment]
Fixed for newer versions of Chef Server 12 via this branch https://github.com/chef/chef/pull/3438 but still have to use the superuser. I recommend just using `chef-server-ctl user-create` for now to create new users in Chef Server 12. A few of us are thinking through an RFC to make user creation much less painful going forward and this is the first step on that path :)
