### ISSUE TITLE
Deprecate Chef::Mixin::Command

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef#3014]
We need to mark `Chef::Mixin::Command` with either `Chef::Log.deprecation` or `Chef::Mixin::Deprecation`.  While doing that, we need to remove all internal uses of it (but not remove it from `Provider` because that changes the public API).  Then we can remove the class entirely for 13.0.0

Source: https://github.com/chef/chef/pull/3012

**Comment by jdmundrawala** [comment]
I think we need to use Chef::Log.deprecation because we will need to continue mixing in Chef::Mixin::Command into Chef::Provider::Package to not break people. This would spew a warning in the include.

**Comment by tyler-ball** [comment]
@jdmundrawala agreed, and that will still have our tests fail if we use one of the methods internally, but won't fail on just the include.
