### ISSUE TITLE
knife search output with specific attribute is broken

### ISSUE THREAD

**Issue by ranjib** [chef/chef#3018]
```sh
knife search node '*:*' -a name
```

Stacktrace:
/home/ranjib/workspace/foss/chef/lib/chef/knife/search.rb:109:in `block in run': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/ranjib/workspace/foss/chef/lib/chef/search/query.rb:90:in `call'
	from /home/ranjib/workspace/foss/chef/lib/chef/search/query.rb:90:in `block in search'
	from /home/ranjib/workspace/foss/chef/lib/chef/search/query.rb:90:in `each'
	from /home/ranjib/workspace/foss/chef/lib/chef/search/query.rb:90:in `search'
	from /home/ranjib/workspace/foss/chef/lib/chef/knife/search.rb:105:in `run'
	from /home/ranjib/workspace/foss/chef/lib/chef/knife.rb:419:in `block in run_with_pretty_exceptions'
	from /home/ranjib/workspace/foss/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
	from /home/ranjib/workspace/foss/chef/lib/chef/knife.rb:418:in `run_with_pretty_exceptions'
	from /home/ranjib/workspace/foss/chef/lib/chef/knife.rb:214:in `run'
	from /home/ranjib/workspace/foss/chef/lib/chef/application/knife.rb:138:in `run'
	from /home/ranjib/workspace/foss/chef/bin/knife:25:in `<top (required)>'
	from /home/ranjib/workspace/foss/chef/.bundle/ruby/2.1.0/bin/knife:23:in `load'
	from /home/ranjib/workspace/foss/chef/.bundle/ruby/2.1.0/bin/knife:23:in `<main>'

**Comment by lamont-granquist** [comment]
fixed by #3019
