### ISSUE TITLE
Error while registering chef-client version 12.1.0 with enterprise chef server 12.

### ISSUE THREAD

**Issue by adheepadhi** [chef/chef#3020]
Hi,
Currently we are using enterprise chef server version 11(chef-11.1.4-1.el6.x86_64).
Now, our team are planning to upgrade the chef-client version from 11.12.4-1. to version 12.1.0.
 Initially when I was testing the latest chef-client I end up with the below error message.
So I went through few answers, it suggested me to update "lb['chef_max_version'] = 12" to  the private-chef.rb file on the chef server and to reconfigure the chef server and I did the same.
Even after doing the above changes and reconfiguring the chef server, I still see the same error message, while running chef-client. Kindly help me to solve this.

Error Message:
================================================================================
Chef encountered an error attempting to create the client "testing-NTT-chefclient-4March"
================================================================================

Invalid Request Data:
---------------------
The data in your request was invalid (HTTP 400).

Server Response:
----------------
{"error": "400 - Bad Request: Chef Client version between 10 and  11" required. Your version of Chef is 12.1.0."}

**Comment by adamedx** [comment]
@adheepadhi, did you find a way around this issue?

**Comment by adheepadhi** [comment]
@adamedx  Yes, we found the solution. nginx was not restarted automatically on the frontend chef server. so restarting the nginx made us to solve this. This case is only for chef 11.
