### ISSUE TITLE
support timeout property of service resource for all platform

### ISSUE THREAD

**Issue by StaymanHou** [chef/chef#3023]
chef server version: 11.1.6
chef client version: 11.18.0
OS: Ubuntu 12.04
cookbook involved: https://github.com/phlipper/chef-percona

We have a running Percona(Mysql) cluster. Create a new node and run chef-client. During the chef run, it notifies `:restart, service[:mysql]` when the mysql configuration file get updated. (reference: https://github.com/phlipper/chef-percona/blob/0666754756e9494ac2598d82a67fda6cf42aa8bd/recipes/configure_server.rb#L114) The action will cause the new node to join the cluster and download all the data. Since we have a big amount of data, this process always take 15~20 min. However chef-client will timeout in 10 min. I would like to have the ability to alter the timeout attribute.

I can see the timeout attribute is already supported for windows(https://github.com/chef/chef/blob/master/lib/chef/resource/service.rb#L161). Could anyone add the support for other platforms?

Thanks

**Comment by feoh** [comment]
+1.  We've had to skip the Chef service manager entirely and shell out to start mysql because of this.  It seems unreasonable to me that Chef should enforce a global 10 minute startup time limit on every service.

**Comment by bbc88ks** [comment]
+1. Could be useful to add timeout to all of the service providers

**Comment by arodwin** [comment]
+1.  Sensible request.

**Comment by damienjoldersma** [comment]
+1

**Comment by jdr0dn3y** [comment]
+1

**Comment by ynuyasha** [comment]
+1

**Comment by damienjoldersma** [comment]
Just hit this again today, is the right practice here to spawn off and detach a process to do the long running task? In this case, I can't restart my elasticsearch cluster in 10 min, it takes much longer.

**Comment by tfitch** [comment]
+1 this is affecting a customer adversely.

**Comment by srirammageswaran** [comment]
+1

**Comment by Ramesh7** [comment]
+1

**Comment by eduncan911** [comment]
+1 This is a 4 year old request...
