### ISSUE TITLE
knife arguments in Windows need protection if ampersand is in the string

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef#3026]
The problem is the `&` character is a special character. A knife argument with an ampersand in it must be protected or else the argument won't be interpreted correctly.

The typical way to protect the `&` character in a string is to surround the string with double quotes. This works when using knife in the command prompt but it does not work when using knife in Powershell.

It seems that, for some reason, when using knife in Powershell the double quotes get eaten by knife leaving the bare string available for interpretation resulting in the `&` being seen as a special character and ultimately not passing the correct argument value. The way to prevent this in Powershell is to use triple double quotes.

Do the following to see how knife is able to correctly get the protected argument.

Run the following in the command prompt.

```
C:\Users\vagrant>knife exec -E 'puts ARGV' "&s0meth1ng"
WARNING: No knife configuration file found
exec
-E
puts ARGV
&s0meth1ng
```

Run the following in Powershell.

```
PS C:\Users\vagrant> knife exec -E 'puts ARGV' """&s0meth1ng"""
WARNING: No knife configuration file found
exec
-E
puts ARGV
&s0meth1ng
```

**Comment by btm** [comment]
Here's the error you get when you put a single set of double-quotes around an ampersand in powershell in this example:
```
PS C:\ruby> knife exec -E 'puts ARGV' "&s0meth1ng"
exec
-E
puts ARGV
's0meth1ng' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by btm** [comment]
@jeremiahsnapp are there examples other than with "knife exec"?

I just wrote a small script to try to tell if this was a mixlib-cli or knife issue, and it doesn't appear to be a bug in mixlib-cli:

```
PS C:\ruby> ruby .\cli-amp.rb "&words" --something print_this "more&words" "do&dir"
ARGV: ["&words", "--something", "print_this", "more&words", "do&dir"]
something: print_this
```

```
require 'rubygems'
require 'mixlib/cli'

class MyCLI
  include Mixlib::CLI

  option :something,
    :short   => "-s words",
    :long    => "--something words"

end

cli = MyCLI.new
cli.parse_options

puts "ARGV: #{ARGV}"
puts "something: #{cli.config[:something]}"
```

**Comment by jeremiahsnapp** [comment]
That's interesting. Originally this was seen when setting the password on the command line when bootstrapping.

```
knife bootstrap windows winrm <IP_OR_FQDN> -x username -P """&s0meth1ng"""
```

**Comment by ksubrama** [comment]
I think this is related to the mixlib issue that I put on our backlog in ECOSYSTEM-45.  Mixlib parsing might be ok but the command invocation does some scary things like in https://github.com/chef/mixlib-shellout/blob/master/lib/mixlib/shellout/windows.rb#L257 where it checks if the command to be executed has & in it and schedules to run it under cmd if it does.  The execution of the command under cmd uses
```
ENV['COMSPEC'], "cmd /c \"#{command}\""
```
which seems reasonable at first glance but cmd /c uses different rules than otherwise when it comes to command parsing and escaping (it strips the first matching quote from the end instead of any nesting).  This means that the ps or win32 process on the other end gets to see the bare arguments and each of them have different escaping rules (PS escapes ' while Win32 escapes \).  There is also some weirdness in https://github.com/chef/mixlib-shellout/blob/master/lib/mixlib/shellout.rb#L172 where depending on whether you pass a single command line or an array, things get handled differently (and wonkily - a string is after all an array, so some codepaths do unexpected things).

I've been meaning to look into that and fully understand it.  Maybe now is a good time for it.

Also: http://blogs.msdn.com/b/twistylittlepassagesallalike/archive/2011/04/23/everyone-quotes-arguments-the-wrong-way.aspx
Fun times...

**Comment by ksubrama** [comment]
Abandon all hope ye who ventures here:

I should have taken @btm 's skepticism more seriously.  Here is my powershell debugging session after way too much confusion and despair:
```
C:\Users\ksubramanian> cat foo.rb
puts ARGV
C:\Users\ksubramanian> ruby .\foo.rb "foo"
foo
C:\Users\ksubramanian> ruby .\foo.rb foo
foo
C:\Users\ksubramanian> ruby .\foo.rb foo bar baz
foo
bar
baz
C:\Users\ksubramanian> ruby .\foo.rb foo bar b`"az
foo
bar
baz
C:\Users\ksubramanian> ruby .\foo.rb foo bar b\"az
>>
C:\Users\ksubramanian> ruby .\foo.rb foo bar b`\`"az
foo
bar
b"az
C:\Users\ksubramanian> ruby .\foo.rb foo bar 'baz qux'
foo
bar
baz qux
C:\Users\ksubramanian> ruby .\foo.rb foo bar '"baz qux"'
foo
bar
baz qux
C:\Users\ksubramanian> ruby .\foo.rb foo bar '"baz" "qux"'
foo
bar
baz
qux
C:\Users\ksubramanian> ruby .\foo.rb foo bar '`"baz`" `"qux`"'
foo
bar
`baz` `qux`
C:\Users\ksubramanian> ruby .\foo.rb foo bar "`"baz`" `"qux`""
foo
bar
baz
qux
C:\Users\ksubramanian> ruby .\foo.rb foo bar "`\`"baz qux`\`""
foo
bar
"baz qux"
C:\Users\ksubramanian> ruby .\foo.rb foo bar `\`"baz qux`\`"
foo
bar
"baz
qux"
C:\Users\ksubramanian> $x = "Foo bar"
C:\Users\ksubramanian> ruby .\foo.rb $x
Foo bar
C:\Users\ksubramanian> $x = 'Foo "bar'
C:\Users\ksubramanian> $x
Foo "bar
C:\Users\ksubramanian> ruby .\foo.rb $x
Foo bar
C:\Users\ksubramanian> $y = "$x"
C:\Users\ksubramanian> ruby .\foo.rb $x $y
Foo bar Foo
bar
C:\Users\ksubramanian> $y
Foo "bar
C:\Users\ksubramanian> echo $x $y
Foo "bar
Foo "bar
```

Lesson learned - passing arguments from powershell with anything other than ASCII characters is a nightmare.  According to https://connect.microsoft.com/PowerShell/feedback/details/376207/executing-commands-which-require-quotes-and-variables-is-practically-impossible the behavior you are seeing is "working as expected".  The general trend seems to be that powershell may or may not quote your arguments as it passes it through as a single concatenated line to the process being invoked.  Once invoked, the process does it's own command line parsing (and if it uses CommandLinetoArgvW which a lot of windows processes use), then it escapes backslashes and strips double-quotes using its own rules.  Hence the behavior you observe.

You can also sidestep the triple quoting by doing `&something instead.  If you wanted to properly escape a string with both spaces and special characters like & in it, perform the following:

Need to pass:  foo& bar
Quote for ruby: "foo& bar"
Escape for MS command line parser: \"foo& bar\"
Escape for powershell ruiner-of-all-good-things: `\`"foo`&` bar`\`"

```
C:\Users\ksubramanian> ruby .\foo.rb `\`"foo`&` bar`\`"
"foo& bar"
```

**Comment by ksubrama** [comment]
Note:  If whatever you pass needs to go through a shell_out, you need to re-escape everything one or two more times depending on whether it's going through PS or cmd on the other end.

**Comment by jeremiahsnapp** [comment]
Another solution is found in the following linked comment.

https://github.com/chef/chef/issues/1687#issuecomment-78323110

>If you have PS 3 or greater, you can use the --% operator to tell PowerShell not to parse the arguments.

>e.g.

```
knife --% exec -E 'puts ARGV' '&s0meth1ng'
```
