### ISSUE TITLE
"knife status" does not filter by environment with -E

### ISSUE THREAD

**Issue by glasschef** [chef/chef#3031]
The -E is essentially ignored when running the search for these nodes:

```
> knife status -E production -VV
...
DEBUG: Initiating GET to https://api.opscode.com/organizations/glassorg/search/node?q=*:*&sort=X_CHEF_id_CHEF_X%20asc&start=0&rows=1000
```

**Comment by juliandunn** [comment]
```
    -E, --environment ENVIRONMENT    Set the Chef environment (except for in searches, where this will be flagrantly ignored)
```

since status basically does a search, I'd argue this is documented and intended behavior.

**Comment by thommay** [comment]
I'd disagree; I think in the status case at least it would be easy and right to have -E do the right thing.

**Comment by glasschef** [comment]
Perhaps this should be tagged as "Enhancement", is there a downside to allowing the environment to be passed to the search query here?  It does seem very useful to be able to filter by environment, is there a better way of doing this?

**Comment by juliandunn** [comment]
There's no real downside, so yeah, I think it could be an enhancement.
