### ISSUE TITLE
Implement automated CLA-signing process

### ISSUE THREAD

**Issue by patcon** [chef/chef#3032]
Open Whisper Systems created a self-hosted service for tracking CLA signing via GitHub's issue status API:
https://github.com/WhisperSystems/CLAServer

You can see it at work here:
https://github.com/WhisperSystems/TextSecure/pulls

It's a really clever system that hooks in like Travis CI and notifies inline with a PR whether the submitting user has signed the CLA :)

**Comment by lamont-granquist** [comment]
We've already written something like that which we call currybot which is part of supermarket.

**Comment by patcon** [comment]
:+1: I've been MIA from Chef community for a bit :)
