### ISSUE TITLE
rubygems in omnibus chef 12.1.0 for windows is broken?

### ISSUE THREAD

**Issue by gswallow** [chef/chef#3033]
Hi,

Working with jaym and Cope on the #chef IRC channel, I was told that it's possible that Chef packaged a broken rubygems with Chef 12.1.0 omnibus for Windows.  The version of rubygems is 2.4.4.

This manifests itself in being unable to install sys-proctable-0.9.6 with the chef_gem resource (again, on Windows).  If I do this:

```ruby
chef_gem 'sys-proctable' do
  options '> 0.0.0'
  options '--platform universal-mingw32'
end
```

It works.

To fix it, jaym, Cope and I did this:

```
c:\opscode\chef\embedded\bin\gem -v (2.4.4)
c:\opscode\chef\embedded\bin\gem update --system
PATH=%PATH%;c:\opscode\chef\embedded\bin
c:\opscode\chef\embedded\bin\gem -v (2.4.6)
c:\opscode\chef\embedded\bin\gem install -q -v '0.9.6' --no-rdoc --no-ri sys-proctable (this worked)
```

**Comment by jdmundrawala** [comment]
Couldn't repro this... I think it has to do with gem not being in the path:
```
PS C:\Users\vagrant> $env:path = $env:Path + ";C:\opscode\chef\embedded\bin"
PS C:\Users\vagrant> gem install sys-proctable
Fetching: sys-proctable-0.9.6-universal-mingw32.gem (100%)
Successfully installed sys-proctable-0.9.6-universal-mingw32
Parsing documentation for sys-proctable-0.9.6-universal-mingw32
Installing ri documentation for sys-proctable-0.9.6-universal-mingw32
1 gem installed
PS C:\Users\vagrant> gem --version
2.4.4
PS C:\Users\vagrant>
```

**Comment by gswallow** [comment]
Here's everything I know. 

https://gist.github.com/gswallow/a937182d549334c8ce10

It could be that gem isn't in the path but I'm really trying to avoid installing a system wide ruby.  I have no need for one.

**Comment by lamont-granquist** [comment]
There were some edits that I had to do to the rubygems provider + specs as part of the multipackage stuff which could have broken this edge case.  Offhand I don't see how, though, since it looks like the gem install command that chef_gem issues looks like the gem install command which worked for you on the command line.  I also don't think the workaround of passing the `--platform` is the right solution and I definitely didn't take any code out which did that.

(and the multiple `options` arguments in your chef_gem example made me stumble, I think based on your gist you realize that doesn't work and you need to use version there?  and if adding version alone without the options fixes the problem that would at least make slightly better sense.)

**Comment by gswallow** [comment]
Yeah, the multiple options was a typo.  I included the --platform flag because my idea at the time was that it's possible the system's platform is x86-mingw32, while the available gem was for universal-mingw32.  So I overrode platform to make it install the universal gem.

**Comment by jdmundrawala** [comment]
Using `chef_gem sys-proctable` with the rubygems that we ship with chef is causing problems for sure. `C:/opscode/embedded/bin/gem install sys-proctable -q --no-rdoc --no-ri -v "0.9.6"` fails. Once I update to rubygems 2.4.6, it correctly installs.

@lamont-granquist I don't think there is any issue with your changes. If we bump rubygems in omnibus-chef to 2.4.6, this problem will go away.

**Comment by lamont-granquist** [comment]
okay :+1:

**Comment by jdmundrawala** [comment]
Further digging, we can't bump rubygems because of https://github.com/rubygems/rubygems/issues/1120 as it breaks our build.

**Comment by john-karp** [comment]
I'm running into this issue on Linux (RHEL6). So it's not Windows specific.

**Comment by CpuID** [comment]
Getting this on CentOS and Ubuntu in Docker, definitely multi OS.

**Comment by lamont-granquist** [comment]
We're going to be releasing 2.4.8 in chef-dk 0.8.0 and chef 12.5.0 which will (should?) fix this.
