### ISSUE TITLE
Create timeout option for `knife ssh`

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef#3036]
While testing `knife ssh` for #3035 I noticed a couple times that the command just hung if something disrupted the SSH traffic. I'm not sure what the root problem was but it seems like it would be nice to have some kind of timeout option for the knife ssh command.

**Comment by mreeves1** [comment]
+1 - This issue still bites me and makes knife ssh of limited use: https://tickets.opscode.com/browse/CHEF-1137 

I think placing `ConnectTimeout 10 ` in your .ssh/config file may help but perhaps only with the initial connection.

**Comment by rbowlby** [comment]
+1

**Comment by FlorentFlament** [comment]
+1

**Comment by erichter-zen** [comment]
+1

**Comment by chuckg** [comment]
+1 

@mreeves1 It does not appear to have any effect.

**Comment by taavituisk** [comment]
+1 A timeout is also useful if a chef run goes for too long.

**Comment by rmoriz** [comment]
especially useful, when you execute a command on a search that also returns one or more unavailable nodes (= hangs)…

**Comment by adrianpricei1** [comment]
+1 - would be a huge help when one or more nodes in your chef search is unresponsive.

**Comment by BarthV** [comment]
+1

**Comment by PHPCEO** [comment]
+1

**Comment by whitelancer** [comment]
+1!  Definitely something I've been struggling with in managing large quantities of servers.

**Comment by philippevidal80** [comment]
+1

**Comment by grizo** [comment]
+1

**Comment by jsirex** [comment]
Very interesting. Sometimes it is blocker. But looks like its ok to wait for 2 years and have nothing.
Good job!

**Comment by lamont-granquist** [comment]
This seems to have been added in e82138ddf51e6f45fc3d215866ccc48845b6e0c3 as `-t`
