### ISSUE TITLE
Knife Conatiner 

### ISSUE THREAD

**Issue by gaurav04** [chef/chef#3056]
When we use "chef/ubuntu-12.04" image to initialize or  build docker context  ,it build successfully.But,when we launch it then it stops after running ,and 'docker ps' command list nothing.
It may be because the image have no running services in it .SO is this the bug ??...But when i made the image ssh enabled so that ssh services keep running in it ,then it show me the running container

**Comment by btm** [comment]
knife-container issues are filed here: https://github.com/chef/knife-container/issues but has been deprecated in favor of https://github.com/chef/chef-provisioning-docker.
