### ISSUE TITLE
powershell_script doesn't allow for all flags to be specified

### ISSUE THREAD

**Issue by smurawski** [chef/chef#3057]
The powershell_script resource specifies -noprofile and -executionpolicy remotesigned.  Users should be able to specify an executionpolicy and allow profile scripts. 

From an earlier report in https://github.com/chef/chef/issues/1604 :

I feel like it should always append -NoLogo, -NonInteractive -InputFormat None, -File but that -NoProfile, -ExecutionPolicy RemoteSigned should both be able to be overridden.

Perhaps this should be changed to two different elements:

use_profile -- default false
execution_policy -- :remote_signed
And then build the flags internally.

**Comment by eric-tucker** [comment]
Is this ever going to be fixed?  I'm running into this issue now.

**Comment by jmccleery** [comment]
This is actually somewhat poorly executed right now. The flags property has a default value, but if you pass anything to it, it's just added before the default value instead of overriding it.

**Comment by DamonStamper** [comment]
+1 to allow powershell_script to load a profile.

A workaround is to dot source the profile.ps1 file as the first line of code in your powershell_script resource. Example, '.$profile.allusersallhosts'. Be sure to load the correct profile as PS has more than one. You could also set the execution policy at the start of every powershell_script resource (or inject that into your profile too). It would be tedious, but it would work.

**Comment by mdpdesign** [comment]
I'm running into the same problem, I'm trying to set the `flags` to override the `ExecutionPolicy` but can't do that.

Fixing this would be nice. Thanks!

**Comment by stuartpreston** [comment]
Repro'd on 14.3.37/Windows Server 2016/WMF 5.1

Agreed, currently if `flags` is supplied, it should be used in preference to the "default_interpreter_flags" but currently the defaults are appended.  See https://github.com/chef/chef/blob/master/lib/chef/provider/powershell_script.rb#L63-L65

**Comment by Nimesh-Msys** [comment]
This is fixed in [PR#8167](https://github.com/chef/chef/pull/8167/)
