### ISSUE TITLE
chef-client service fails to start on Debian 8 (jessie)

### ISSUE THREAD

**Issue by ve7cxz** [chef/chef#3063]
After install Chef 12 on a Debian 8 (jessie) server, it's not possible to start chef-client as a service:-

    root@canmore ~ # /etc/init.d/chef-client start
    Starting chef-client (via systemctl): chef-client.serviceFailed to start chef-client.service: Unit chef-client.service failed to load: No such file or directory
      failed!

It looks like there's no configuration for systemd, and that's why it's failing.

**Comment by btm** [comment]
@ve7cxz Where did /etc/init.d/chef-client come from? Are you using the chef-client cookbook?

**Comment by ve7cxz** [comment]
Sorry for the lack of details - yeah, it's from the chef-client cookbook.

I actually fixed it in the end with some modifications to the chef-client::service recipe and to the default attributes in the chef-client cookbook - I can open a pull request for them.

**Comment by btm** [comment]
https://github.com/opscode-cookbooks/chef-client/pull/289
