### ISSUE TITLE
group functional test hanging on FreeBSD 10

### ISSUE THREAD

**Issue by btm** [chef/chef#3068]
I've been researching the group functional test hanging on FreeBSD 10 in our new CI/CD infrastructure for the client (codename manhattan). 

After manual debugging, it is hanging while removing users here: https://github.com/chef/chef/blob/f400002d1a68b8ee672dea92ddfc6ff15624d9d2/spec/functional/resource/group_spec.rb#L174

This test is using the built in resource/provider for deleting users using pw as part of the group resource/provider tests, so I inserted a pause in the provider and tried manually deleting the user at that point, and it hung as well:

```
-bash-4.3$ sudo pw userdel Gordon
pwd_mkdb: warning, unknown root shell
pwd_mkdb: warning, unknown root shell
```

A bit of internet-ing brought me to an ansible bug where freebsd was hanging removing a user: https://github.com/ansible/ansible-modules-core/issues/243 which leads to a bug in FreeBSD: https://svnweb.freebsd.org/base?view=revision&revision=272192

Here's the specific bug/patch: for this issue: https://svnweb.freebsd.org/base?view=revision&revision=267970

This code will hang on FreeBSD 10-RELEASE, specifically the last user resource where we try to delete a user from a group (FreeBSD pw hangs dealing with the deleted user being in the group).
```
user "deleteme-1"
user "deleteme-2"

group "deleteme" do
  members [ "deleteme-1", "deleteme-2" ]
end

user "deleteme-1-delete" do
  username "deleteme-1"
  action :remove
end
```

I'm currently running ```sudo freebsd-update upgrade -r 10.1-RELEASE``` on our ci/cd box to verify the fix.

I'm undecided as to if we should add something in Chef to catch this case, or if we can get away with anyone running into this finding this github issue and then upgrading their system.

**Comment by btm** [comment]
My chef-apply script in my last comment to reproduce the bug now completes cleanly as well as the group functional test.

```
$ sudo /opt/chef/embedded/bin/ruby /opt/chef/embedded/bin/rspec spec/functional/resource/group_spec.rb 

[snip]
Finished in 1.3 seconds (files took 7.54 seconds to load)
18 examples, 0 failures
```

For the record for Chef Inc folks:

> Completing this upgrade requires removing old shared object files.
Please rebuild all installed 3rd party software (e.g., programs
installed from the ports tree) and then run "/usr/sbin/freebsd-update install"
again to finish installing updates.

Looked at portupgrade, it was a yak, ran ```sudo pkg upgrade``` and then freebsd-update install again.

```
-bash-4.3$ sudo /usr/sbin/freebsd-update install
Installing updates... done.
-bash-4.3$ 
```

/opt/chef has some debugging puts in it. I'm presuming the next build will install over the top of that and I'll kick it off now. I'm going to close this issue, but @martinisoft you should consider how you feel about the pw bug in 10.0-RELEASE hanging Chef.

**Comment by martinisoft** [comment]
@btm I definitely don't like that it is happening, but getting it to reliably happen would be a thing to help dig into it deeper with DTrace so we can see if there are any clues from that.

**Comment by btm** [comment]
@martinisoft well, we know why pw was hanging: https://svnweb.freebsd.org/base?view=revision&revision=267970

I think the question is, do enough people use FreeBSD 10.0-RELEASE with Chef that we need to work around that bug, e.g. detect that version of pw and raise an error, or can we just treat it as a known issue with the workaround/solution being upgrading to 10.1-RELEASE?

**Comment by martinisoft** [comment]
@btm Considering 10.0 is technically now "Legacy" as of the 10.1 release we could post it as a workaround/solution for now. There was a LOT of patches between 10.0 and 10.1 so upgrading is still a smart idea. I don't have any stats (or even how to collect those) on how many users of Chef run that platform in particular. My gut feeling is it is a small number.

**Comment by btm** [comment]
Yeah. It's probably enough that this is here. Google knows about this. I don't think it's worth a blog post or anything.

I hereby do declare if you're having this issue you should upgrade to 10.1
