### ISSUE TITLE
undefined method `verify' for Chef::Resource::Template

### ISSUE THREAD

**Issue by theredcat** [chef/chef#3070]
Hi,

It seems that the template::verify method that is described in the [docs](http://docs.chef.io/release/11-18/resource_template.html) doesn't exists at all.

This method is absent from the [rubydoc](http://www.rubydoc.info/gems/chef/Chef/Resource)

However, this option look pretty cool. Is the implementation in the roadmap?

**Comment by stevendanna** [comment]
@theredcat What version of chef-client are you using locally?

**Comment by btm** [comment]
It looks like https://github.com/chef/chef/pull/2581 was first released in Chef 12.1.0.

@jamescott did it mistakenly get added to the 11.18 release docs? http://docs.chef.io/release/11-18/resource_template.html

@theredcat The feature that's described on the docs is a DSL attribute to the file resource which the template resource inherits. https://github.com/chef/chef/blob/master/lib/chef/resource/file.rb#L121

**Comment by theredcat** [comment]
@stevendanna I'm using chef 11.18

@btm Thx for the information! I'll wait for the 12.1.1 to become stable
