### ISSUE TITLE
Chef 12 windows service provider assumes windows_service resource

### ISSUE THREAD

**Issue by joelwilson** [chef/chef#3071]
The changes made in be28ba90bd introduced support for running a windows service as a specific user but did not seem to take into account cases where the calling recipe used the `service` resource, which does not have the `run_as_user` or `run_as_password` methods, instead of the `windows_service` resource which does.

A good example of this - one which I ran into - is in the Chef Jenkins cookbook. The [slave_windows](https://github.com/opscode-cookbooks/jenkins/blob/master/libraries/slave_windows.rb) resource uses the standard `service` resource with an [XML config](https://github.com/opscode-cookbooks/jenkins/blob/master/libraries/slave_windows.rb#L131-L169) to set up the user to run as instead of using the updated `windows_service` resource, presumably because this feature didn't exist when the cookbook was written.

Here is the error that gets thrown:

```
================================================================================
Error executing action `start` on resource 'service[jenkins-slave]'
================================================================================

NoMethodError
-------------
undefined method `run_as_user' for Chef::Resource::Service

Compiled Resource:
------------------
# Declared in

service("jenkins-slave") do
action "nothing"
supports {:restart=>false, :reload=>false, :status=>false}
retries 0
retry_delay 2
default_guard_interpreter :default
service_name "jenkins-slave"
pattern "jenkins-slave"
only_if { #code block }
end


================================================================================
Error executing action `create` on resource 'jenkins_windows_slave[build-slave]'
================================================================================

NoMethodError
-------------
service[jenkins-slave] (dynamically defined) had an error: NoMethodError: undefined method `run_as_user' for Chef::Resource::Service

Resource Declaration:
---------------------
# In C:/chef/cache/cookbooks/xxx_jenkins/recipes/slave_windows.rb

53: jenkins_windows_slave node['jenkins']['node']['name'] do
54:   remote_fs node['jenkins']['node']['remote_fs'] # jenkins workspace items stored here
55:   group     node['jenkins']['node']['group']     # Group with access to remote_fs
56:   user      node['jenkins']['node']['user']      # user the service runs under (and remote_fs owner)
57:   password  node['jenkins']['node']['password']  # for user running the service
58:   labels    node['jenkins']['node']['labels']    # labels on Jenkins master
59:   action    :create
60: end

Compiled Resource:
------------------
# Declared in C:/chef/cache/cookbooks/xxx_jenkins/recipes/slave_windows.rb:53:in `from_file'

jenkins_windows_slave("build-slave") do
action [:create]
retries 0
retry_delay 2
default_guard_interpreter :default
declared_type :jenkins_windows_slave
cookbook_name "xxx_jenkins"
recipe_name "slave_windows"
remote_fs "C:\\\\jenkins"
group "Everyone"
user "jenkins"
password "password123"
labels ["builder", "windows"]
slave_name "build-slave"
usage_mode "normal"
in_demand_delay 0
idle_delay 1
description "Jenkins slave build-slave"
executors 1
service_name "jenkins-slave"
winsw_url "http://repo.jenkins-ci.org/releases/com/sun/winsw/winsw/1.16/winsw-1.16-bin.exe"
winsw_checksum "052f82c167fbe68a4025bcebc19fff5f11b43576a2ec62b0415432832fa2272d"
end
```

Stack trace:
```
Generated at 2015-03-12 20:54:39 +0000
Chef::Exceptions::RunFailedWrappingError: Found 1 errors, they are stored in the backtrace
1) NoMethodError -  jenkins_windows_slave[build-slave] (xxx_jenkins::slave_windows line 53) had an error: NoMethodError: service[jenkins-slave] (dynamically defined) had an error: NoMethodError: undefined method `run_as_user' for Chef::Resource::Service
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:959:in `method_missing'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/service/windows.rb:75:in `start_service'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/service.rb:90:in `block in action_start'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `call'
C:/opscode/chef/embedded/apps/chef/lib/chef/mixin/why_run.rb:52:in `add_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:180:in `converge_by'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider/service.rb:89:in `action_start'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:149:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'
C:/chef/cache/cookbooks/jenkins/libraries/slave_windows.rb:80:in `action_create'
C:/opscode/chef/embedded/apps/chef/lib/chef/provider.rb:145:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource.rb:561:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
C:/opscode/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:331:in `block in converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:326:in `catch'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:326:in `converge'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:345:in `converge_and_save'
C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:448:in `run'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:253:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:230:in `block in run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `loop'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `interval_run_chef_client'
C:/opscode/chef/embedded/apps/chef/lib/chef/application/client.rb:372:in `run_application'
C:/opscode/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
C:/opscode/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:64:in `load'
C:/opscode/chef/bin/chef-client:64:in `<main>'
```

The only workaround I can see is to go back to version 11.x.x. Is it cookbook maintainers' responsibility to use `windows_service` for Windows nodes instead of the `service` resource? If so, I can open an issue with the Jenkins cookbook.

**Comment by btm** [comment]
The thing is with https://www.chef.io/blog/2015/02/10/chef-12-provider-resolver/ we shouldn't need to specify windows_package in a resource to get that resource because the 'provides' line in the windows_service resource here: https://github.com/chef/chef/blob/master/lib/chef/resource/windows_service.rb#L28

**Comment by btm** [comment]
@joelwilson what version of Chef and the jenkins cookbook are you using?

**Comment by btm** [comment]
Ah, I see, the jenkins cookbook isn't using the DSL, it's directly loading a Chef::Resource::Service object.

https://github.com/opscode-cookbooks/jenkins/blob/master/libraries/slave_windows.rb#L197

**Comment by joelwilson** [comment]
@btm Chef 12.1.1 and Jenkins cookbook 2.2.2. The provider resolver is an interesting new feature which I hadn't seen, but I see you understand what I'm talking about though. I suppose the Jenkins cookbook is at fault then?

**Comment by btm** [comment]
@joelwilson we could patch the jenkins cookbook to call Chef::Resource::WindowsService.new instead, yeah. I'm wondering if @lamont-granquist has an opinion on how to make use of the resource resolver when creating a resource from within another provider.

**Comment by btm** [comment]
I'm going to close this because the cookbook is directly creating a service resource class, so it's on the cookbook to do the right thing since it's creating the class itself.

As I mentioned previously, this bug could be fixed in the jenkins cookbook by calling ```Chef::Resource::WindowsService.new``` instead, but this is probably the most robust option:
```
@service_resource = Chef::Resource.resource_for_node(:service, node).new(new_resource.service_name, run_context)
```

I was wondering if we should create a shortcut for that in the recipe DSL, but Chef::Provider::LWRPBase includes Chef::DSL::Recipe, so maybe the LWRP author can just do this and get the right service resource through Chef::DSL::Recipe.method_missing? I'm not quite set up to try that at the moment and I'm not that experienced with writing LWRPs.
```
service new_resource.service_name do
  only_if do
    wmi_property_from_query(:name, "select * from Win32_Service where name = '#{new_resource.service_name}'")
  end
end
```

**Comment by lamont-granquist** [comment]
Yep, `Chef::Resource.resource_for_node(:service, node)` is the correct stable API to use.

Mixing in LWRPBase will also allow just using the resource DSL directly via method_missing.

We do need a new API which can be mixed in to build resources which has some syntactic sugar and doesn't require method_missing.

**Comment by btm** [comment]
@someara or @jtimberman, any memory as to why we started doing things like ```Chef::Resource::Service.new(new_resource.service_name, run_context)``` instead of ```service new_resource.service_name do``` in LWRPs and HWRPs? Did the latter not work at some point and we got stuck on the first pattern?

I tested that there's no problem using ```execute``` in an LWRP provider in a simple test, but I wonder about edge cases.

**Comment by someara** [comment]
It's not a thing I do... @schisamo and @sethvargo may have insights

**Comment by lamont-granquist** [comment]
I think removing the Recipe DSL was done to remove method_missing and the confusing errors that it can produce.

We could really use a tighter API that did not rely on method_missing something like:

```ruby
build_resource(:service, "name") do
  action [ :enable, :start ]
end
```

**Comment by btm** [comment]
We do still include recipe DSL in LWRP providers in https://github.com/chef/chef/blob/master/lib/chef/provider/lwrp_base.rb#L75. I was thinking the same thing about adding to the DSL, but if you can just refer to the resource, e.g. ```service``` I'm not sure why we need to do anything else, we should just call those resources directly.

**Comment by lamont-granquist** [comment]
Yeah in LWRPs you should just use the recipe DSL.
