### ISSUE TITLE
Chef 12 'chef-server-ctl upgrade' fails on RHEL 5.11

### ISSUE THREAD

**Issue by ve7cxz** [chef/chef#3072]
I'm migrating from Chef 11 (11.1.3) to Chef 12 (12.0.5) on a RHEL 5.11 server, and running into an issue after running `chef-server-ctl upgrade`:-

    - configure service runit_service[rabbitmq]
    * link[/opt/opscode/service/rabbitmq] action create
      - create symlink at /opt/opscode/service/rabbitmq to /opt/opscode/sv/rabbitmq

At this point, it hangs. Running strace against the chef-client process shows it trying to stat `/opt/opscode/service/rabbitmq/supervise/ok`, which apparently doesn't exist:-

    stat("/opt/opscode/service/rabbitmq/supervise/ok", 0x7fffa031f450) = -1 ENOENT (No such file or directory)

I'm assuming this part of the `chef-server-ctl upgrade` is supposed to create it, but for some reason it isn't. I've attempted the upgrade twice now, and both times it has failed at the same point.

Exiting out of the upgrade leaves Chef 12 in a bad state, and it appears to then be impossible to continue the upgrade:-

    <...>
    Creating /tmp/chef11-server-data20150312-21492-nblrd0 as the location to save the open source Chef 11 server data
    Ensuring Chef 12 server is stopped
    warning: rabbitmq: unable to open supervise/ok: file does not exist
    Unable to stop the Chef 12 server, which is needed to complete the upgrade

The only way to get the upgrade process to work again is to uninstall the chef-server-core RPM and start again.

**Comment by ve7cxz** [comment]
Not sure if it's relevant, but I see lots of references to `private-chef-ctl`, whereas I'm following the instructions for the Open Source version.

**Comment by btm** [comment]
This looks like a [chef-server](https://github.com/chef/chef-server) issue, I've refiled it over there as https://github.com/chef/chef-server/issues/127.
