### ISSUE TITLE
Chef Client local mode (chef zero) search inconsistencies (NOT / AND NOT)

### ISSUE THREAD

**Issue by petecheslock** [chef/chef#3073]
This is with both Chef `12.0.0` and `12.1.1`

When talking to a real chef server (in that case hosted chef) - and running the following queries.  I get the following results (there are about 60 other nodes in this hosted chef account).

```
chef > search(:node, "role:api_server AND chef_environment:#{node.chef_environment} NOT tags:hidden", :filter_result => { 'ip' => ['ipaddress'] })
 => [{"ip"=>"1.1.1.1"}]
chef > search(:node, "role:api_server AND chef_environment:#{node.chef_environment} AND NOT tags:hidden", :filter_result => { 'ip' => ['ipaddress'] })
 => [{"ip"=>"1.1.1.1"}]
```
Works as I would expect

Also here i'm using filter results - but have confirmed the issue with both normal search and "partial" search.

On a test server - (using test-kichen with chef zero provisioner), and pre-populating node data, I see the following:

Node Data
```
cat /tmp/kitchen/nodes/api_server.json
{
  "id": "api_server",
  "chef_environment": "test",
  "run_list": [
    "role[api_server]"
  ],
  "automatic": {
    "ipaddress": "172.33.33.34",
    "hostname": "api-server",
    "roles": [
      "api_server"
    ]
  }
}
```
```
{
  "id": "sensu_master",
  "chef_environment": "test",
  "run_list": [
    "role[sensu_master]"
  ],
  "automatic": {
    "ipaddress": "172.33.33.50",
    "hostname": "sensu-master",
    "roles": [
      "sensu_master"
    ]
  }
}
```

Then running queries against:
```
pry(#<Chef::Recipe>)> search(:node, "role:api_server AND chef_environment:#{node.chef_environment} NOT tags:hidden", :filter_result => { 'ip' => ['ipaddress'] })
=> [{"ip"=>"172.33.33.34"},{"ip"=>"172.33.33.50"}]
pry(#<Chef::Recipe>)> search(:node, "role:api_server AND chef_environment:#{node.chef_environment} AND NOT tags:hidden", :filter_result => { 'ip' => ['ipaddress'] })
=> [{"ip"=>"172.33.33.34"}]
pry(#<Chef::Recipe>)> search(:node, "role:api_server AND chef_environment:#{node.chef_environment}", :filter_result => { 'ip' => ['ipaddress'] })
=> [{"ip"=>"172.33.33.34"}]
```

So in this case it seems to be the `AND` or `AND NOT` at the end.  This is easy for us to work around by using `AND NOT` in our cookbooks since that seems to work for both, but there might be a chef-zero or localmode bug.

**Comment by stevendanna** [comment]
> This is easy for us to work around by using AND NOT in our cookbooks since that seems to work for both, but there might be a chef-zero or localmode bug.

The problem with this is that AND NOT is incorrect lucene syntax and won't always work (I'd have to hunt down what types of queries/server versions it will break on, but we've definitely seen breakage in the past regarding AND NOT in the past).

**Comment by petecheslock** [comment]
Ugh - ok I'll hold off making the changes on my side then that might break.  Let me know if you want me to test anything in the meantime.

**Comment by christinedraper** [comment]
I'm having a similar problem via knife when using local mode or chef-zero. As an illustration, this search should always return 0 nodes.

```
$knife search node -q "name:appserver NOT name:appserver" -i
0 items found

$ knife search node -q "name:appserver NOT name:appserver" -i -z
5 items found
<snip - lists all nodes>
```
I tried using exclude ('-') as an alternative, but that doesnt work with a slightly different failure mode:
```
knife search node -q "name:appserver -name:appserver" -i -z
1 items found

appserver
```

**Comment by petecheslock** [comment]
Does anyone have any ideas on this?  It makes testing search with chef-zero very difficult.

**Comment by lamont-granquist** [comment]
This is misclassified and should go under the github.com/chef/chef-zero/issues/new repository.

The behavior of the server is correct chef-styled lucene syntax, the problem is that chef-zero does not properly replicate all of the silliness.

**Comment by petecheslock** [comment]
Thanks @lamont-granquist i'll get that moved over.
