### ISSUE TITLE
Bash resource fails when pam_mktemp is enabled

### ISSUE THREAD

**Issue by dantswain** [chef/chef#3074]
If pam_mktemp is enabled, temporary files are created under `/tmp/.private/<user>`, so chef puts its files there.  So, when running `sudo chef-client`, all of the bash scripts are placed in `/tmp/.private/root`.  However, if the script is to be executed as another user via the `user` attribute, the script fails with permission errors.

Example:

``` ruby
 bash 'bundle install' do
   user exec_user
   group exec_user
   cwd deploy_path
   code "bundle install --without test --path /home/#{exec_user}/.gem/"
 end
```

Fails with

``` bash
 STDERR: bash: /tmp/.private/root/chef-script20150313-15671-ftqqan: Permission denied
```

For us, the short term fix was to disable pam_mktemp.

**Comment by lamont-granquist** [comment]
This is a dup of a similar-ish bug on Mac OSX #3563

**Comment by lamont-granquist** [comment]
calling this a dup of #3563
