### ISSUE TITLE
chef-full.erb bootstrap template fails

### ISSUE THREAD

**Issue by mmarschall** [chef/chef#3084]
Running `knife bootstrap` using the chef-full.erb template results in the following errors:

```
Exception: NameError: undefined local variable or method `client_pem' for #<Chef::Knife::Core::BootstrapContext:0x007f96ae6f0558>
```
```
Exception: NameError: undefined local variable or method `trusted_certs' for #<Chef::Knife::Core::BootstrapContext:0x007f96ae6f0558>
```

Using `@chef_config[:client_pem]` instead of `client_pem` on line https://github.com/chef/chef/blob/master/lib/chef/knife/bootstrap/templates/chef-full.erb#L41 and https://github.com/chef/chef/blob/master/lib/chef/knife/bootstrap/templates/chef-full.erb#L43 fixes the first error.

I'm not sure how to fix lines https://github.com/chef/chef/blob/master/lib/chef/knife/bootstrap/templates/chef-full.erb#L62 and https://github.com/chef/chef/blob/master/lib/chef/knife/bootstrap/templates/chef-full.erb#L64 though... :-(

Any ideas?

**Comment by btm** [comment]
What version of Chef?  How is Chef installed? Are you using ChefDK? If so, what version?

ChefDK ships two versions of Chef, the "tools" and "library" version. I could see there being a disparity where https://github.com/chef/chef/pull/2030 is one but not the other.

**Comment by mmarschall** [comment]
I'm using Chef Development Kit Version: 0.3.5 on OS X

**Comment by btm** [comment]
@mmarschall If you're trying to stay on Chef 11, have you tried [0.3.6](https://opscode-omnibus-packages.s3.amazonaws.com/mac_os_x/10.8/x86_64/chefdk-0.3.6-1.dmg) or if you have no constraint upgrading your workstation tried [0.4.0](https://opscode-omnibus-packages.s3.amazonaws.com/mac_os_x/10.8/x86_64/chefdk-0.4.0-1.dmg)?

https://downloads.chef.io/chef-dk/mac/

**Comment by mmarschall** [comment]
I just tried with ChefDK 0.4.0-1 with same result:

```Exception: NameError: undefined local variable or method `client_pem' for #<Chef::Knife::Core::BootstrapContext:0x007fb3d466ea60>```

**Comment by btm** [comment]
Can you try with -V -V and share the output? Need to see the paths in the
stacktraces.

**Comment by mmarschall** [comment]
I don't get any stacktraces:

```
➜  chef-repo git:(master) ✗ knife bootstrap localhost -p 2222 -x user --verbose --bootstrap-template bootstrap/my-chef-full.erb --sudo -VV
INFO: Using configuration from /Users/mma/work/chef-repo/.chef/knife.rb
Connecting to localhost
DEBUG: Using the specified bootstrap template: bootstrap
ERROR: knife encountered an unexpected error
This may be a bug in the 'bootstrap' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NameError: undefined local variable or method `client_pem' for #<Chef::Knife::Core::BootstrapContext:0x007f8f158d1d18>
```
Only that one DEBUG message shows up... strange...

**Comment by btm** [comment]
Yeah, there's some code paths where that happens. Hmm, I'll try to reproduce it, I would expect more people to chime in if this was a simple repro though. Can you confirm output that might narrow it down?

* knife -v
* which knife

**Comment by btomasini** [comment]
I just encountered the same error when using `knife openstack server create` with a custom template.

```
btomasini@btomasini-lab:~$ chef --version
Chef Development Kit Version: 0.4.0
btomasini@btomasini-lab:~$ knife --version
Chef: 12.0.3
```

**Comment by mmarschall** [comment]
```
➜  chef-repo git:(master) ✗ which knife
/opt/chefdk/bin/knife
➜  chef-repo git:(master) ✗ knife --version
Chef: 12.0.3
➜  chef-repo git:(master) ✗ chef --version
Chef Development Kit Version: 0.4.0
```

**Comment by adamb0mb** [comment]
I'm seeing the error from `trusted_keys` too.

```
AdamP@machine ~/chef-repo>  knife bootstrap 10.0.0.1 -x root -N test.machine.office -E dev -t ~/chef-repo/.chef/bootstrap/chef-centos.erb  --run-list 'role[redis]' --secret-file=.chef/encrypted_data_bag_secret -VV
DEBUG: Looking for bootstrap template in /Users/AdamP/chef-repo/.chef/bootstrap
DEBUG: Found bootstrap template in /Users/AdamP/chef-repo/.chef/bootstrap
Connecting to 10.0.0.1
ERROR: knife encountered an unexpected error
This may be a bug in the 'bootstrap' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NameError: undefined local variable or method `trusted_certs' for #<Chef::Knife::Core::BootstrapContext:0x007fbb00ab3f98>
```

And, here are some info about my setup:
```
AdamP@Webmaster ~/chef-repo> which knife
/usr/bin/knife
AdamP@Webmaster ~/chef-repo> knife --version
Chef: 11.18.0.rc.1
AdamP@Webmaster ~/chef-repo> chef --version
Chef Development Kit Version: 0.3.5
```

**Comment by rbair23** [comment]
Same issue, same version numbers:

rbair$ chef --version
Chef Development Kit Version: 0.4.0
rbair$ knife --version
Chef: 12.0.3

**Comment by rbair23** [comment]
I should clarify, I was seeing the first error (`undefined local variable or method `client_pem'`) but not the second. Applying the fix specified by mmarschall solved my problem.

**Comment by lamont-granquist** [comment]
Pretty certain this was derp on my part that got fixed.
