### ISSUE TITLE
Functional test failures on Windows desktops

### ISSUE THREAD

**Issue by btm** [chef/chef#3106]
Compiling this for @mwrock, @fnichol. It'd be helpful to know the results of `bundle exec rspec -cb spec/functional/*` for other people on Windows. @jdmundrawala? @ksubrama?  

About a year ago I was tracking down a functional test failure in [CHEF-5193](https://tickets.opscode.com/browse/CHEF-5193) and I was seeing a bunch of test failures on my desktop that I wasn't seeing on a 2012vm. The output of those failures is here: https://gist.github.com/btm/802f31fba4cad8d38b4a

Today, in an admin powershell from `C:\Users\btm_000\documents\github\chef`, I get:

```
Finished in 16 minutes 37 seconds (files took 7.65 seconds to load)
3548 examples, 40 failures, 95 pending
```

I got the same errors in an admin powershell from `C:\ruby\chef` though:

```
Finished in 14 minutes 36 seconds (files took 7.28 seconds to load)
3548 examples, 40 failures, 95 pending
```

Most of the errors are repeating shared examples for file resources. Of course, the concern is that if these fail for other people it's going to make contribution harder because they're not starting from a point of all the tests passing.

**Comment by mwrock** [comment]
Took a look at this today. I pulled latest `master`, `bundle install`ed and then `bundle exec rspec -cb spec/functional/*`.

My results were:

```
Finished in 12 minutes 58 seconds (files took 9.37 seconds to load)
3552 examples, 33 failures, 91 pending
```

I am running Windows 10 build 10041. Looking at some of the failures it seems like the tests really need to run on a specific os version or even image since many errors were due to bad SIDs or pointer addresses.

**Comment by dbjorge** [comment]
#3266 tracks and #3267 addresses the SID issues in the securable_resource-based specs, which is about 1/3 of what I'm seeing on my Windows 8.1 desktop. Remaining failures are https://gist.github.com/dbjorge/432105bd9a3e3ae3fc8d, haven't looked deeply into any of them.

**Comment by stuartpreston** [comment]
This is so old I'm closing it.  We're down to 21 functional test failures on Windows 10, and 20 of those are probably due to a WinRM configuration that needs to be documented.  Tracking those in #7439 and #7440 instead.
```
Finished in 24 minutes 49 seconds (files took 36.29 seconds to load)
3745 examples, 21 failures, 66 pending
```
