### ISSUE TITLE
Installing AIX packages from source does not work

### ISSUE THREAD

**Issue by jdmundrawala** [chef/chef#3108]
Executing the following resource does not work on Chef 12.1.1
```ruby
package 'foo' do
  source '/tmp/cfengine-community-3.6.4.0-aix_6.x.bff'
end
```
Chef client gives back
```
  * package[foo] action install (up to date)
```
```
-bash-4.3$ lslpp -L | grep cfengine
-bash-4.3$
```

Investigating if this worked on Chef 12.0.3

**Comment by jdmundrawala** [comment]
This at least had the decency to crash in 12.0.3.

**Comment by juliandunn** [comment]
This only happens if you're silly enough to specify a `package_name` that is different than the thing actually provided by the BFF. (Like if you specified `package 'cfengine-community'` it would have been fine) So yeah, a bug, but pretty minor.
