### ISSUE TITLE
No version specified, and no candidate version available for

### ISSUE THREAD

**Issue by mrrllbb** [chef/chef#3113]
Recently I began to learn chef and followed the guide in the website learn.chef.io. I met a problem when I came to step 2. I just chef-apply the webserver.rb(in it: package 'apache2') and it got an error:* apt_package[apache2] action install
    * No version specified, and no candidate version available for apache2
    ================================================================================
    Error executing action `install` on resource 'apt_package[apache2]'
    ================================================================================
    
    Chef::Exceptions::Package
    -------------------------
    No version specified, and no candidate version available for apache2
    
    Resource Declaration:
    ---------------------
    # In webserver.rb
    
      1: package 'apache2'
      2: 
    
    Compiled Resource:
    ------------------
    # Declared in webserver.rb:1:in `run_chef_recipe'
    
    apt_package("apache2") do
      action :install
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      package_name "apache2"
      timeout 900
      declared_type :package
      cookbook_name "(chef-apply cookbook)"
      recipe_name "(chef-apply recipe)"
    end
    
[2015-03-20T17:22:21+08:00] FATAL: Stacktrace dumped to /home/mrrllbb/.chef/cache/chef-stacktrace.out
[2015-03-20T17:22:21+08:00] FATAL: Chef::Exceptions::Package: apt_package[apache2] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Chef::Exceptions::Package: No version specified, and no candidate version available for apache2

My OS is ubuntu.
Please help me and give me a solution. Thank you!

**Comment by nathenharvey** [comment]
@mrrllbb this repository is for the Chef framework.  It's better to use the Q&A section of https://learn.chef.io when you have questions there.

For this specific issue, it may be that your apt repos are not set-up properly or that there's simply no package named 'apache2' in the apt repos you are accessing.  The team at the Learn Chef site would probably want the following information to help you troubleshoot and move forward:

* Full stack of the chef-client run
* Are you using one of the provided VMs or one of your own?
* version of Chef you're running
* version of Ubuntu you're using

Good luck!

**Comment by jdmundrawala** [comment]
Given all the issues we've had with packages lately, I want to leave this open until we verify it is not a regression

**Comment by jdmundrawala** [comment]
Works fine

**Comment by Sevyls** [comment]
Sorry for reopening this, but I'm stuck at the same point as described.

* Ubuntu 14.04.2 LTS (my own VirtualBox VM)
* Chef Development Kit Version: 0.4.0

A suggested I updated my apt-get cache with "apt-get update", no change to the outcome.

````
michael@chef-node:~/chef-repo$ apt-cache search apache2 | egrep "^apache2"
apache2 - Apache HTTP Server
...
````

````
michael@chef-node:~/chef-repo$ sudo chef-apply webserver.rb 
sudo: Hostname chef-node kann nicht aufgelöst werden
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * apt_package[apache2] action install
    * No version specified, and no candidate version available for apache2
    ================================================================================
    Error executing action `install` on resource 'apt_package[apache2]'
    ================================================================================
    
    Chef::Exceptions::Package
    -------------------------
    No version specified, and no candidate version available for apache2
    
    Resource Declaration:
    ---------------------
    # In webserver.rb
    
      1: package 'apache2'
    
    Compiled Resource:
    ------------------
    # Declared in webserver.rb:1:in `run_chef_recipe'
    
    apt_package("apache2") do
      action :install
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      package_name "apache2"
      timeout 900
      declared_type :package
      cookbook_name "(chef-apply cookbook)"
      recipe_name "(chef-apply recipe)"
    end
    
[2015-04-22T17:20:36+02:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2015-04-22T17:20:36+02:00] FATAL: Chef::Exceptions::Package: apt_package[apache2] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Chef::Exceptions::Package: No version specified, and no candidate version available for apache2
````

The stacktrace:
````
Generated at 2015-04-22 17:20:36 +0200
Chef::Exceptions::Package: apt_package[apache2] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Chef::Exceptions::Package: No version specified, and no candidate version available for apache2
/opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:241:in `run'
/opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:322:in `block in run'
/opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:321:in `each'
/opt/chefdk/embedded/apps/chef/lib/chef/mixin/why_run.rb:321:in `run'
/opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:159:in `process_resource_requirements'
/opt/chefdk/embedded/apps/chef/lib/chef/provider.rb:135:in `run_action'
/opt/chefdk/embedded/apps/chef/lib/chef/resource.rb:582:in `run_action'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chefdk/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chefdk/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chefdk/embedded/apps/chef/lib/chef/application/apply.rb:150:in `run_chef_recipe'
/opt/chefdk/embedded/apps/chef/lib/chef/application/apply.rb:159:in `run_application'
/opt/chefdk/embedded/apps/chef/lib/chef/application/apply.rb:172:in `run'
/opt/chefdk/embedded/apps/chef/bin/chef-apply:25:in `<top (required)>'
/usr/bin/chef-apply:40:in `load'
/usr/bin/chef-apply:40:in `<main>'
````

**Comment by Sevyls** [comment]
even after i manually installed the package apache2 via ``apt-get install apache2``, the error output from chef stays the same.

**Comment by Sevyls** [comment]
my problem was the locale environment (de_AT.UTF8)

Workaround for this problem: https://github.com/chef/chef/issues/2695#issuecomment-68972171
