### ISSUE TITLE
make use_inline_resources the only way to write resources in Chef 13

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#3123]
should have done this for Chef 12

breaking change has to be done in a major version bump.

probably want to add some kind of dont_use_inline_resources for LWRPs that actually can't use it.

**Comment by tas50** [comment]
@lamont-granquist Can we close this now that custom resources turn use_inline_resources on by default?  Seems like that's the proper way to get users into the correct pattern.

**Comment by lamont-granquist** [comment]
Nope, adding the nags to foodcritic is actually in preparation for simply turning this on and making everything that inherits from LWRPBase have use_inline_resources by default.

**Comment by martinb3** [comment]
I think we also need to expose a way to turn this off, right? I don't see any way to currently disable `use_inline_resources`. (e.g. the `dont_use_inline_resources` that @lamont-granquist refers to above).

**Comment by lamont-granquist** [comment]
If you just define a method on a provider without using the 'action' syntax you will magically turn it off right now...

To really incorporate this better, we probably want to merge this into Chef::Provider#action though so that every method gets it.

But, I'm also not clear why anyone needs this functionality any more.  We have parent pointers on run_context's now and the root Chef.run_context and you can inject the run_context into declare_resource and build_resource to mess with your parent run_context's resource collection.

AFAIK the only reason for turning it off was to write (bad and broken) accumulators using resources.

**Comment by coderanger** [comment]
@lamont-granquist I will need it disabled in all Poise-based code as I have my own (better) replacement.

**Comment by lamont-granquist** [comment]
fair 'nuff then.

**Comment by coderanger** [comment]
But for my purposes it could be something like `override a method on the provider class`, rather than something exposed more directly.

**Comment by martinb3** [comment]
> you can inject the run_context into declare_resource and build_resource to mess with your parent run_context's resource collection.

I had assumed this was a workaround -- and not something we should be doing as a public API.

**Comment by lamont-granquist** [comment]
I think I may want to take a mulligan on create_if_missing but injecting the run_context is supported as far as I'm concerned.

**Comment by lamont-granquist** [comment]
so, i "took a mulligan on create_if_missing" and implemented this stuff:

https://coderanger.net/rewind/

its definitely intended that those APIs be used along with the `with_run_context` helper to be able to write definitions and resources that do not require anyone using dont_use_inline_resources.   those APIs are documented and fully intended to be used publicly.

**Comment by lamont-granquist** [comment]
resources written with `dont_use_inline_resources` are pretty fundamentally broken.  notifications are broken.  if they're relying on not having a sub-run_context then they're broken by definition when
called from use_inline_resources-style resources.  nobody who writes these kinds of resources does the extraction of their sub-resource collection updated state correctly via manual means (and it
wouldn't work if they did).

i vote we just put a bullet in this bad way of writing bad and fundamentally unfixable code.

we also have the tools via the bubble-up notifications and with_run_context helpers now there's nothing that can't be accomplished correctly by use_inline_resources styles of providers.

**Comment by lamont-granquist** [comment]
We should also bake constructing the notifying_block directly around the call to the action method -- so that `def action_install` would get a sub-resource collection in addition to `action :install`.  Kind of tired of people who don't know what they're doing setting off to write library providers and defeating the purpose of use_inline_resources by using `def action_install` and would like to make that mistake simply disappear so I can stop yelling at people in my head.

**Comment by coderanger** [comment]
Fixed via #6013, though maybe in some future land we'll want to make this apply even to the `def aciton_name` style, but that is a discussion for another day.
