### ISSUE TITLE
chef-server-ctl says user already exists when list-users shows otherwise

### ISSUE THREAD

**Issue by wjimenez5271** [chef/chef#3132]
Given the following command:
```
chef-server-ctl user-create will William Jimenez user@something.tld somepass
```
I get the response:
```
ERROR: Conflict
Response: User 'will' already exists
```
However:
```
# chef-server-ctl user-list
pivotal
wjimenez
```

Am I missing something obvious?

**Comment by stevendanna** [comment]
@wjimenez5271 Is it possible that the email address `user@something.tld` is already taken?

**Comment by stevendanna** [comment]
The following chef-server bug tracks the poor error message: https://github.com/chef/chef-server/issues/59  If that turns out not to be the case, please open a bug in the chef-server repo.
