### ISSUE TITLE
rpm package provider fails for URI sources

### ISSUE THREAD

**Issue by mfischer-zd** [chef/chef#3133]
rpm can install packages from URIs, but the current provider doesn't support this - it expects the RPM file to live on the local filesystem:

```
            unless ::File.exists?(@new_resource.source)
              @package_source_exists = false
              return
            end
```

**Comment by btm** [comment]
In general, we need to design something that adds support for remote_file on all the package resources that would support it. The windows_package resource in core doesn't support URLs but the one in the windows cookbook did. https://github.com/chef/chef/issues/2659
