### ISSUE TITLE
Amazon Linux: yum package resource fails with "ImportError: No module named yum"

### ISSUE THREAD

**Issue by knoxvilledba** [chef/chef#3143]
"Amazon Linux AMI 2014.09" servers starting failing upon attempting to install any package with chef-client. The failure looks like this for any "package" install you try:

Error executing action `install` on resource 'yum_package[tzdata]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /usr/bin/python /opt/chef/embedded/apps/chef/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
    STDOUT:
    STDERR: Traceback (most recent call last):
      File "/opt/chef/embedded/apps/chef/lib/chef/provider/package/yum-dump.py", line 36, in <module>
        import yum
    ImportError: No module named yum
    ---- End output of /usr/bin/python /opt/chef/embedded/apps/chef/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 ----
    Ran /usr/bin/python /opt/chef/embedded/apps/chef/lib/chef/provider/package/yum-dump.py --options --installed-provides --yum-lock-timeout 30 returned 1

    Resource Declaration:
    ---------------------
    # In /etc/chef/local-mode-cache/cache/cookbooks/timezone-ii/recipes/default.rb

     13: package value_for_platform_family(
     14:   'gentoo'  => 'timezone-data',

    Compiled Resource:
    ------------------
    # Declared in /etc/chef/local-mode-cache/cache/cookbooks/timezone-ii/recipes/default.rb:13:in `from_file'

    yum_package("tzdata") do
      action :install
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      package_name "tzdata"
      timeout 900
      flush_cache {:before=>false, :after=>false}
      declared_type :package
      cookbook_name "timezone-ii"
      recipe_name "default"
    end

After investigation, I found that the package which I update in my userdata "aws-cfn-bootstrap" was updated sometime in the last 24 hours, updating its dependencies to install python27. yum-dump.py seems to be calling /usr/bin/python, which is symlinked to python2.6 after the 2.7 install. /usr/bin/yum header was updated to "#!/usr/bin/python2.7". The problem seems to be that the 2.7 install breaks 2.6 interactivity with yum.

**Comment by stevendanna** [comment]
More info: https://forums.aws.amazon.com/thread.jspa?threadID=174341

**Comment by zts** [comment]
On IRC, switching your default python to 2.7 with `update-alternatives` was reported as resolving this issue.

    $ sudo alternatives --set python /usr/bin/python2.7

More details here: https://aws.amazon.com/amazon-linux-ami/2015.03-release-notes/

**Comment by zts** [comment]
^^ just to be clear, my comment above is a possible short-term advice for people who have been surprised by this update.  It would be nicer if chef-client were able to do the right thing without intervention.

**Comment by stevendanna** [comment]
@chef/client-core Any thoughts here?  We could include python and the required libraries in the chef-client omnibus package, but I'm not sure we really want to take that on as a dependency.  We could potentially check that the system has a sane-enough-for-us python installation and give a more sensible error message if it doesn't.

**Comment by danielsdeleo** [comment]
@stevendanna I think bringing our own python could possibly cause more problems than it's worth, if for example different versions of yum at some point need different versions of python across different OS versions and such. We should be able to rely on there being a python on the system that works with the yum that's on the system. Really all we should need here is some logic to find the right python command to use with whatever crazy stuff Amazon is doing and use it.

**Comment by stevendanna** [comment]
@danielsdeleo Would it be too ugly to try to identify the python that is being using by yum itself.  Perhaps grep out the shabang line?

**Comment by danielsdeleo** [comment]
That sounds like the most stable and general solution

**Comment by lamont-granquist** [comment]
also rewrite yum-dump.py in ruby and/or fix it so that its portable...

**Comment by danielsdeleo** [comment]
A year or two ago I looked for ruby libraries for yum and there was only one abandonware one which was only installable as an RPM. Maybe that's gotten better, or we could write our own?

**Comment by danielsdeleo** [comment]
That said, opening `$(which yum)`, reading the first line and removing `#!` and then using that as the path to the python binary seems like something we could implement easily w/ what we have and low risk.

**Comment by stevendanna** [comment]
@danielsdeleo +1, going to submit a PR today or tomorrow with that.  Only adjustment I was thinking of was some belt-and-suspenders protection against yum not being what we think it is, so perhaps reading the first 2 characters and making sure they are #! or something like that, to avoid reading in some large binary file.

**Comment by jaymzh** [comment]
:+1:  on checking which python yum is using.

**Comment by lamont-granquist** [comment]
Yeah works for me, make sure you really get a shebang
