### ISSUE TITLE
change InvalidCookbookVersion exception message

### ISSUE THREAD

**Issue by anjutiwari** [chef/chef#3146]
The version exception message is confusing.

when the version value in metadata.rb is 
version "x.y.z"

knife cookbook upload -o mycookbook
ERROR: Chef::Exceptions::InvalidCookbookVersion: 'x.y.z' does not match 'x.y.z' or 'x.y'

using negative version now :(-2.2.0)
ERROR: Chef::Exceptions::InvalidCookbookVersion: '-2.2.0' does not match 'x.y.z' or 'x.y'

so that's mean version "x.y.z" is a acceptable and valid version value as per the above exception message.

The exception message should change , which can clearly explain from the exception message that 
x,y and z are positive numbers.
example:- 
ERROR: Chef::Exceptions::InvalidCookbookVersion: 'x.y.z' .  Version numbers always follow a simple three-number version sequence. Example (version "1.6.0")

**Comment by nysthee** [comment]
I don't think that I quite understand what you mean with this. The example you're giving doesn't include a a negative number, so it shouldn't  output the given error?

**Comment by anjutiwari** [comment]
@nysthee 

using negative version now :(-2.2.0)
ERROR: Chef::Exceptions::InvalidCookbookVersion: '-2.2.0' does not match 'x.y.z' or 'x.y'

**Comment by nysthee** [comment]
I personally don't see this as an improvement. To me it's clear that semantic versioning http://semver.org/ is used as a standard.
