### ISSUE TITLE
chef-client 12.2.0 fails to start on CentOS 7

### ISSUE THREAD

**Issue by jayaich** [chef/chef#3158]
Our CentOS 7 servers automatically updated the chef-client (via omnibus_updater) to version 12.2.0 last night. We now find that we cannot start the client using 'systemctl start chef-client.service'. When we check the service status we see:
```
===============
[root@cent-4-026 opt]# systemctl status chef-client.service
chef-client.service - Chef Client daemon
   Loaded: loaded (/etc/systemd/system/chef-client.service; enabled)
   Active: failed (Result: exit-code) since Fri 2015-03-27 15:24:59 GMT; 30min ago
  Process: 10752 ExecStart=/usr/bin/chef-client -c $CONFIG -i $INTERVAL -s $SPLAY (code=exited, status=1/FAILURE)
 Main PID: 10752 (code=exited, status=1/FAILURE)

Mar 27 15:24:58 cent-4-026 chef-client[10752]: from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Mar 27 15:24:58 cent-4-026 chef-client[10752]: from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Mar 27 15:24:58 cent-4-026 chef-client[10752]: from /opt/chef/embedded/apps/chef/lib/chef.rb:25:in `<top (required)>'
Mar 27 15:24:58 cent-4-026 chef-client[10752]: from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Mar 27 15:24:58 cent-4-026 chef-client[10752]: from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Mar 27 15:24:58 cent-4-026 chef-client[10752]: from /opt/chef/embedded/apps/chef/bin/chef-client:23:in `<top (required)>'
Mar 27 15:24:58 cent-4-026 chef-client[10752]: from /usr/bin/chef-client:51:in `load'
Mar 27 15:24:58 cent-4-026 chef-client[10752]: from /usr/bin/chef-client:51:in `<main>'
Mar 27 15:24:59 cent-4-026 systemd[1]: chef-client.service: main process exited, code=exited, status=1/FAILURE
Mar 27 15:24:59 cent-4-026 systemd[1]: Unit chef-client.service entered failed state.
===============
```
I have downgraded the client to version 12.1.2 on one server, and that starts up fine.

**Comment by jdmundrawala** [comment]
can you get more of the stacktrace from journalctl?

I suspect it is the same issue as https://github.com/chef/chef/issues/3153

**Comment by jayaich** [comment]
I saw the bug report #3153 and tried applying the commit regarding 'all_homes'. Whilst this seems to have worked for our Debian systems, it made no difference on the CentOS 7 ones. The output from journalctl is below, and does indeed contain the same error message about HOME not being set. Very odd.

Mar 27 16:34:30 cent-4-025 systemd[1]: Starting Chef Client daemon...
-- Subject: Unit chef-client.service has begun with start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit chef-client.service has begun starting up.
Mar 27 16:34:30 cent-4-025 systemd[1]: Started Chef Client daemon.
-- Subject: Unit chef-client.service has finished start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit chef-client.service has finished starting up.
-- 
-- The start-up result is done.
Mar 27 16:34:31 cent-4-025 chef-client[16552]: /opt/chef/embedded/apps/chef/lib/chef/util/path_helper.rb:199:in `home': couldn't find HOME environment -- expanding `~' (ArgumentError)
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /opt/chef/embedded/apps/chef/lib/chef/util/path_helper.rb:199:in `all_homes'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /opt/chef/embedded/apps/chef/lib/chef/util/path_helper.rb:161:in `home'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:36:in `gather_plist_dirs'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:40:in `<class:Macosx>'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:27:in `<class:Service>'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:26:in `<class:Provider>'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:25:in `<class:Chef>'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:24:in `<top (required)>'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /opt/chef/embedded/apps/chef/lib/chef/providers.rb:93:in `<top (required)>'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /opt/chef/embedded/apps/chef/lib/chef.rb:25:in `<top (required)>'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /opt/chef/embedded/apps/chef/bin/chef-client:23:in `<top (required)>'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /usr/bin/chef-client:51:in `load'
Mar 27 16:34:31 cent-4-025 chef-client[16552]: from /usr/bin/chef-client:51:in `<main>'
Mar 27 16:34:31 cent-4-025 systemd[1]: chef-client.service: main process exited, code=exited, status=1/FAILURE
Mar 27 16:34:31 cent-4-025 systemd[1]: Unit chef-client.service entered failed state.

**Comment by jdmundrawala** [comment]
are you sure you correctly applied the patch?
I just tried on centos7 and it works fine

**Comment by jayaich** [comment]
No (sorry about that).
I applied the spec commit (7a6df30) , but not the actual change of 9b8f47c which modifies the path_helper.rb file.

Applied the commit and tested this on a CentOS 7 system and it worked fine.
Many thanks (and apologies).
