### ISSUE TITLE
[chef-client] failing on action start

### ISSUE THREAD

**Issue by mpkayeuk** [chef/chef#3159]
When bootstrapping a new node, during the initial client run chef-client is failing with:

================================================================================
myhost.mydomain.com     Error executing action `start` on resource 'service[chef-client]'
myhost.mydomain.com     ================================================================================
myhost.mydomain.com     
myhost.mydomain.com     Mixlib::ShellOut::ShellCommandFailed
myhost.mydomain.com     ------------------------------------
myhost.mydomain.com     Expected process to exit with [0], but received '1'
myhost.mydomain.com     ---- Begin output of /sbin/service chef-client start ----
myhost.mydomain.com     STDOUT: Starting chef-client: [FAILED]
myhost.mydomain.com     STDERR: /opt/chef/embedded/apps/chef/lib/chef/util/path_helper.rb:199:in `home': couldn't find HOME environment -- expanding `~' (ArgumentError)

**Comment by jdmundrawala** [comment]
Dup of https://github.com/chef/chef/issues/3153

**Comment by jdmundrawala** [comment]
This should be fixed in 12.2.1
