### ISSUE TITLE
Issues with version 12.2.0

### ISSUE THREAD

**Issue by nullck** [chef/chef#3163]
Hi, 
Please, I'm using amazon ec2 auto-scaling and my  script of user-data install chef  by using:

curl -sL http://opscode.com/chef/install.sh | bash

But today this resulted in this error:
"/opt/chef/embedded/apps/chef/lib/chef/util/path_helper.rb:199:in `home': couldn't find HOME environment -- expanding `~' (ArgumentError)"

this is my backlog:

Downloading Chef  for ubuntu...
downloading http://opscode.com/chef/metadata?v=&prerelease=false&nightlies=false&p=ubuntu&pv=14.04&m=x86_64
  to file /tmp/install.sh.6635/metadata.txt
trying wget...
url     http://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/13.04/x86_64/chef_12.2.0-1_amd64.deb
md5     86ca87ed4ee0053408e93e6b78b5923d
sha256  5bb49bef0ec52020304462f5c8718e7bea12a47ac1eb0375664b23e86fda7472
downloaded metadata file looks valid...
downloading http://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/13.04/x86_64/chef_12.2.0-1_amd64.deb
  to file /tmp/install.sh.6635/chef_12.2.0-1_amd64.deb

Thank you for installing Chef!
download: s3://scup-infra-chef/solo.rb to tmp/solo.rb
download: s3://scup-infra-chef/nodes/web.plataforma.qa.scup.net.br.json to tmp/node.json
download: s3://scup-infra-chef/cookbooks_master.tgz to tmp/cookbooks.tgz
/opt/chef/embedded/apps/chef/lib/chef/util/path_helper.rb:199:in `home': couldn't find HOME environment -- expanding `~' (ArgumentError)
        from /opt/chef/embedded/apps/chef/lib/chef/util/path_helper.rb:199:in `all_homes'
        from /opt/chef/embedded/apps/chef/lib/chef/util/path_helper.rb:161:in `home'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:36:in `gather_plist_dirs'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:40:in `<class:Macosx>'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:27:in `<class:Service>'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:26:in `<class:Provider>'
        from /opt/chef/embedded/apps/chef/lib/chef/provider/service/macosx.rb:25:in `<class:Chef>'

**Comment by jdmundrawala** [comment]
dup of https://github.com/chef/chef/issues/3153

**Comment by jdmundrawala** [comment]
This should be fixed in 12.2.1
