### ISSUE TITLE
Question: Font Icon for chef logo

### ISSUE THREAD

**Issue by mrchief** [chef/chef#3167]
Font-Awesome has a great collection of brand icons and I think chef icon will be a great addition. I was wondering if it'd Ok to take a shot at it (in other words, will there be any copyright or any other violations by doing so). 

I had something like this in mind:
![image](https://cloud.githubusercontent.com/assets/781818/6904592/e49f5038-d6ef-11e4-8f5f-0293371826c4.png)

**Comment by smith** [comment]
@mrchief I don't see any problem with that at all. For some higher-resolution SVG and AI images you might want to check out https://github.com/chef/chef-web-core/tree/master/lib/assets/images and https://app.box.com/s/8bciq01i8xi6ioa3wgd4. Official policy regarding our trademark and use of our logo can be found at https://www.chef.io/trademark-policy/.

Going to close this, but please let me know if you have any questions.

**Comment by mrchief** [comment]
Great! I went through the links and all logos have the text "CHEF" in them. Is it OK if I submit an icon without those words (just the logo as shown above)? With font icons, the text won't be legible anyway.

**Comment by smith** [comment]
Yeah I'm not a lawyer nor have I read through the trademark policy but you should be totally good. Pretty sure Font Awesome includes some kind of "all logos are trademarks of their respective owners language.

**Comment by mrchief** [comment]
Yeah it does. Cool, I'm going to work on this tonight. Do you think submitting a PR with the font icon files will be a good idea (hoping the community can benefit from it)?

**Comment by smith** [comment]
@mrchief go for it. That would be fantastic!
