### ISSUE TITLE
centos 7.1 image request

### ISSUE THREAD

**Issue by kramvan1** [chef/chef#3173]
With rhel decision to not make 7.0 a EUS/LTS, need to switch to 7.1.

Would like to see a 7.1 image like the one for 7.0 here:

'http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box'

**Comment by kramvan1** [comment]
Doc of rhel EUS/LTS: https://access.redhat.com/support/policy/updates/errata

**Comment by bdwyertech** [comment]
This would probably be better created in https://github.com/chef/bento

**Comment by kramvan1** [comment]
Moved to bento :https://github.com/chef/bento/issues/334
