### ISSUE TITLE
MacOSX Service provider - Running services are not restarted

### ISSUE THREAD

**Issue by joaogbcravo** [chef/chef#3175]
### Version:
12.2.1

### Environment: 
MacOSX
Any cookbook that uses the provider service/macosx.rb 
source: https://github.com/chef/chef/blob/master/lib/chef/provider/service/macosx.rb

### Scenario:
Restart services when they are running or stopped.
It just restart the service when it is stopped. However when it is running just stop it.

### Steps to Reproduce:
Use the provider service in some cookbook and run it in a MacOSX.
Example:
  service "SOME-SERVICE" do
    action :restart
  end

### Expected Result:
Expect to the service be restarted.

### Actual Result:
When the service is running, it is stopped but not started. Debug message:
[2015-04-01T14:41:25+01:00] DEBUG: service[thoughtworks.go-agent-1] already running, not starting
[2015-04-01T14:41:25+01:00] INFO: service[thoughtworks.go-agent-1] restarted

When the service is stopped, it is started correctly.

### Problem in source:
When start_service and stop_service methods are called it is checked if the attribute 'running' is 'true' or 'false' respectively. However this attribute is defined at the beginning of the service instance definition and not updated if it the service is stopped or started. 
When you restart the service when it is running, the flag is defined as "true" and the stop_service stops the service. However the start_service doesn't do nothing because the 'running' attribute is still 'true' (not updated).

### Proposed solution:
Remove in the start_service method (line 81 source code) the conditional:
 if @current_resource.running
     Chef::Log.debug("#{@new_resource} already running, not starting")

And to be consistent remove also in the stop_service method (line 93 source code) the conditional:
unless @current_resource.running
            Chef::Log.debug("#{@new_resource} not running, not stopping")

**Comment by lamont-granquist** [comment]
looks like fixed by #3051
