### ISSUE TITLE
Chef.Bootstrap.WindowsAzure LinuxChefClient 11.18.6.1 chef-install.sh not working with CentOS 7

### ISSUE THREAD

**Issue by mentlsve-acn** [chef/chef#3176]
### Environment: 
Cloud Provider: Azure
VM: CentOS-based 7.0 by OpenLogic
VM Extension: 
    Publisher: Chef.Bootstrap.WindowsAzure 
    Name: LinuxChefClient 
    Version: 11.18.6.1

### Scenario:
Node is not registering at chef server. Extension in Azure Portal remains in status NotReady.

### Steps to Reproduce:
1. Order compute instance with CentOS-based 7.0 by OpenLogic
2. Add the extension Chef Client.

### Expected Result:
Node registered at the chef server.

### Actual Result:
Installation fails. 

    less /var/log/azure/Chef.Bootstrap.WindowsAzure.LinuxChefClient/11.18.6.1/CommandExecution.log 
    2015/04/01 13:56:07 Downloading plugin manifest: Chef.Bootstrap.WindowsAzure.LinuxChefClient from http://rdfepirv2am2prdstr02.blob.core.windows.net/0fa68ca509a643f49117169ef78baf70/Chef.Bootstrap.WindowsAzure_LinuxChefClient_europewest_manifest.xml
    2015/04/01 13:56:07 Plugin server is: rdfepirv2am2prdstr02.blob.core.windows.net
    2015/04/01 13:56:07 Bundle URI = http://rdfepirv2am2prdstr02.blob.core.windows.net/0fa68ca509a643f49117169ef78baf70/Chef.Bootstrap.WindowsAzure__LinuxChefClient__11.18.6.1
    2015/04/01 13:56:08 Plugin bundlehttp://rdfepirv2am2prdstr02.blob.core.windows.net/0fa68ca509a643f49117169ef78baf70/Chef.Bootstrap.WindowsAzure__LinuxChefClient__11.18.6.1downloaded successfully length = 32153461
    2015/04/01 13:56:08 Extracted http://rdfepirv2am2prdstr02.blob.core.windows.net/0fa68ca509a643f49117169ef78baf70/Chef.Bootstrap.WindowsAzure__LinuxChefClient__11.18.6.1 to /var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-11.18.6.1
    2015/04/01 13:56:08 Found RuntimeSettings for Chef.Bootstrap.WindowsAzure.LinuxChefClient V 11.18.6.1
    2015/04/01 13:56:08 Spawned install.sh PID 9685
    2015/04/01 13:56:13 Process 9685 returned non-zero exit code (1)

An attempt to install it manually:

    cd /var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-11.18.6.1/bin/
    sudo ./install.sh

    We trust you have received the usual lecture from the local System
    Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

    [sudo] password for azureuser:
    /var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-11.18.6.1
    /var/lib/waagent/Chef.Bootstrap.WindowsAzure.LinuxChefClient-11.18.6.1/bin/chef-install.sh: line 62: lsb_release: command not found
    Unknown Distributor:

**Comment by adamedx** [comment]
This is addressed in a different repository: https://github.com/chef-partners/azure-chef-extension/issues/17.
