### ISSUE TITLE
run_list presence in role depends on order of .rb input file

### ISSUE THREAD

**Issue by js7558** [chef/chef#3179]
Sorry for any info or formatting mistakes, it's the first time I've submitted an issue against your project.   

### Version:

root@chef-workstation:~/chef-repo/roles# chef -v
Chef Development Kit Version: 0.4.0

### Environment: [Details about the environment such as the Operating System, cookbook details, etc...]

root@chef-workstation:~/chef-repo/roles# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

root@chef-workstation:~/chef-repo/roles# uname -a
Linux chef-workstation 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

### Scenario:
Following directions on a random tutorial I found at https://www.digitalocean.com/community/tutorials/how-to-use-roles-and-environments-in-chef-to-control-server-configurations trying to figure out the basics for Chef.  I'd followed the previous steps in the tutorial and they seem to work fine.   

The immediate issue I'm seeing is when creating the role from Ruby DSL.   It looks like the presence or absence of correct run_list: in the uploaded role depends on the order that I specify the inputs in.     

When I create a file web_server.rb as 

name "web_server"
description "A role to configure our front-line web servers"

default_attributes "nginx" => { "log_location" => "/var/log/nginx.log" }
override_attributes "nginx" => { "gzip" => "on" }
env_run_lists "production" => ["recipe[nginx::config_prod]"], "testing" => ["recipe[nginx::config_test]"], "_default" => []
run_list "recipe[apt]", "recipe[nginx]"

And then run  'knife role from file ./web_server.rb', and then dump it out with 'knife role show web_server', I get the correct and expected output, namely that run_list: is populated with the expected recipes:

root@chef-workstation:~/chef-repo/roles# knife role show  web_server
chef_type:           role
default_attributes:
  nginx:
    log_location: /var/log/nginx.log
description:         A role to configure our front-line web servers
env_run_lists:
  production: recipe[nginx::config_prod]
  testing:    recipe[nginx::config_test]
json_class:          Chef::Role
name:                web_server
override_attributes:
  nginx:
    gzip: on
run_list:
  recipe[apt]
  recipe[nginx]

However, when I change the ordering on the input file such that run_list is sequentially above env_run_lists, then I get a different output (inputs and outputs as follows):

root@chef-workstation:~/chef-repo/roles# cat web_server.rb
name "web_server"
description "A role to configure our front-line web servers"

default_attributes "nginx" => { "log_location" => "/var/log/nginx.log" }
override_attributes "nginx" => { "gzip" => "on" }
run_list "recipe[apt]", "recipe[nginx]"
env_run_lists "production" => ["recipe[nginx::config_prod]"], "testing" => ["recipe[nginx::config_test]"], "_default" => []

root@chef-workstation:~/chef-repo/roles# knife role from file ./web_server.rb
Updated Role web_server!
root@chef-workstation:~/chef-repo/roles# knife role show  web_server         
chef_type:           role
default_attributes:
  nginx:
    log_location: /var/log/nginx.log
description:         A role to configure our front-line web servers
env_run_lists:
  production: recipe[nginx::config_prod]
  testing:    recipe[nginx::config_test]
json_class:          Chef::Role
name:                web_server
override_attributes:
  nginx:
    gzip: on
run_list:

root@chef-workstation:~/chef-repo/roles# 

The run_list: is empty.   

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem?]
1. Create web_server.rb as noted above. Make sure that run_list: is above env_run_lists: in the file.
2. knife role from file web_server.rb 
3. knife role show web_server
4. Repeat 1-3, except for 1) make sure that run_list: is below env_run_lists: in the file.
5. Note output is different from 3).

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]
I'd expect either
   a) the order on the input file to not matter or 
   b) for the knife role from command to produce an error indicating that the ordering on the input file is not correct.

### Actual Result:
[What actually happens after the reproduction steps?]
As noted above, the order of the input file results in the same behavior when 'knife role from file' is run.  However, the outputs are different when running 'knife role show'.

**Comment by smurawski** [comment]
You are actually seeing the expected behavior.  As noted in the docs, "_default" is the same as run_list.  So, in the first case, _default was nil, then it was overriden with run_list.  In the second case, it had the run_list value and then was assigned nil by the env_run_lists _default.

https://docs.chef.io/roles.html
