### ISSUE TITLE
Exception handlers do not run if chef_run fails before @run_status is set

### ISSUE THREAD

**Issue by Igorshp** [chef/chef#3180]
Was digging around trying to figure out weird exception handler behaviour:

recipe does not exist on chef server - exception handler fire
role does not exist on chef server - exception handler does *NOT* fire

In the end I traced it to this line:
https://github.com/chef/chef/blob/master/lib/chef/client.rb#L438
and run_status is set here:
https://github.com/chef/chef/blob/master/lib/chef/client.rb#L244

This means that anything north of this line, does not fire a sensu handler:
https://github.com/chef/chef/blob/master/lib/chef/client.rb#L438

It feels like run_failed should always run regardless of run_status being populated fully (empty run_status instance appears to work just fine).

The goal is to get the exception handlers to fire in most (hopefully all) situations.

Any thoughts on how to best fix this?

**Comment by lamont-granquist** [comment]
seems to be fixed in 12.4.0
