### ISSUE TITLE
Using lazy attributes as name attribute

### ISSUE THREAD

**Issue by BackSlasher** [chef/chef#3191]
Consider this:
```ruby
node.default['my']['version']='5'
node.default['my']['package']=lazy { "best-#{node['my']['version']}" }

package node['my']['package']
```
While this should work, I get something like:
```text
Chef::Exceptions::Package
-------------------------
No candidate version available for ***#<Chef::DelayedEvaluator:0x000000059b1c98@/tmp/vagrant-chef-3/chef-solo-1/cookbooks/***/attributes/default.rb:57>

Resource Declaration:
---------------------
# In /tmp/vagrant-chef-3/chef-solo-1/cookbooks/***/recipes/default.rb

 31:   package pkg do
 32:     action :install
 33:   end
 34: end

Compiled Resource:
------------------
# Declared in /tmp/vagrant-chef-3/chef-solo-1/cookbooks/***/recipes/default.rb:31:in `block in from_file'

yum_package("#<Chef::DelayedEvaluator:0x000000059b1310@/tmp/vagrant-chef-3/chef-solo-1/cookbooks/***/attributes/default.rb:73>") do
  action [:install]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  package_name #<Chef::DelayedEvaluator:0x000000059b1310@/tmp/vagrant-chef-3/chef-solo-1/cookbooks/***/attributes/default.rb:73>
  timeout 900
  flush_cache {:before=>false, :after=>false}
  declared_type :package
  cookbook_name :***
  recipe_name "default"
end

```
I have several ideas:

1. Stay with current configuration, where lazy is only usable from inside the resource block
2. Modify the base resource class to check if the name attribute is a lazy block, and if so manually evaluate it
3. Add a `to_s` method to `DelayedEvaluator` where it evaluates itself. This seems the easiest, but might have side effects (being evaluated every time it's printed to some log, for instance)

If you can recommend a solution, I'll be happy to help

**Comment by lamont-granquist** [comment]
I don't think this makes any sense.

Resources need names as identifiers on the resource collection as targets for notifies and subscribes.  The solution to this should be to name the resource to a unique string, and then override the package_name with the lazy value which should work:

```ruby
yum_package "install the lazy package" do
  package_name lazy { "lazy_package_name" }
end
```

Trying to lazy up the actual name will cause a large amount of chaos on the resource collection.
