### ISSUE TITLE
Permission mismatch in the `script` provider on Mac OS X

### ISSUE THREAD

**Issue by carsomyr** [chef/chef#3194]
As you may know, Mac OS X creates longwinded temporary file pathnames of the form

```
/var/folders/59/z2lttptx1zd9_p8znf8j2lwr0000gn/T/chef-script20150405-72884-fk5dec
```

when running as an unprivileged user and

```
/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/chef-script20150405-73045-v4wykz
```

when running as root. Unfortunately, some of these intermediate directories may have permissions `700`, as in the case of `/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T`. This then causes the [`script` provider](https://github.com/chef/chef/blob/2e7ffaa/lib/chef/provider/script.rb#L56-65) to fail: A temp file can potentially be created with the root path scheme (assuming `sudo chef-client`), but the script is meant to be executed by an unprivileged user. Note that the `set_owner_and_group` method's permissions fixing will not mitigate the issue, since the intermediate directory has root owner permissions `700`, thus preventing the temporary script file from being accessed.

From what I can tell, the `script` provider needs to call `Tempfile.open` as the script user to cause Mac OS X to use the path scheme for that user.

**Comment by lamont-granquist** [comment]
Dup of #3563
