### ISSUE TITLE
Resources should support periodic execution options

### ISSUE THREAD

**Issue by docwhat** [chef/chef#3198]
`remote_file` can be turned into a pretty powerful DDoS system without much effort.

It would be nice, if `remote_file` had an attribute like `check_frequency` that could be set to something like `hourly`, `daily`, `weekly`, `every 2 days`, etc.

This would allow updates of things that need to be periodically updated, but where it doesn't have to be updated exactly now.

**Comment by lamont-granquist** [comment]
It already supports Etags and Last-Modified flags.

There is maybe a feature request here for baking into core chef a feature that would allow doing this and covering the apt periodic updates use case in a generic way for any resource.

**Comment by lamont-granquist** [comment]
Its also arguable that this should better go into a DSL library like chef-sugar.
