### ISSUE TITLE
install.sh should get client nightlies

### ISSUE THREAD

**Issue by btm** [chef/chef#3205]
This is technically an [omnitruck](https://github.com/chef/opscode-omnitruck) issue.

Currently Omnitruck and the [install.sh script](https://github.com/chef/opscode-omnitruck/blob/master/views/install.sh.erb) differentiate between stable, nightly, and "pre" releases. We've overloaded the version of the package similar to Rubygems for this functionality. I believe stable releases are numerical, pre-releases are alpha-numeric, and nightlies have a git sha in them. This is noted in the the [omnitruck readme](https://github.com/chef/opscode-omnitruck/blob/master/README.md#metadata-endpoint) as well.

In the near future, we're going to regularly produce builds, as often as every time something goes into master, or at least daily (providing something changed). We've discussed calling these "integration builds."

Currently you get unexpected results when you ask for a nightly (you get a really old build) but you get something newer if you ask for a pre-release nightly. We should simplify all this into just being stable releases and integration builds.

> Bryan McLellan: I had a talk with @schisamo and I'd like to change omnitruck for the chef-client to just have "releases" like you normally get, and "integration builds" which could be nightlies, or a prerelease or any other build that you publish that isn't a promoted release. anyone have feelings about this?
> Lamont Granquist: well, it already has both nightlies and prereleases
> Lamont Granquist: so can you get what you want out of what is already there?
> Bryan McLellan: it has nightlies, prereleases, and nightly prereleases, all based on voodoo in the version string, and currently install.sh/omnitruck/manhattan disagree about at least one of those definitions. so we want to make all of those be one thing.
> Lamont Granquist: okay, that sounds like something i'm +1 on
> Lamont Granquist: while you're at it, -p and -n are exclusive and won't serve up releases, so if there's a more recent actual release and you supply -p you won't see it, which is not what anyone wants
> Bryan McLellan: yeah the omnitruck readme is explicit about that, so it's probably a fix in omnitruck as well.
> Lamont Granquist: yeah, i had a branch that implemented that, but it broke about a thousand spec tests in the process

**Comment by schisamo** [comment]
We'll want to set up a second Omnitruck instance for serving up integration/nightly builds. This would allow us to have two distinct Omnitruck channels, one for current builds and one for stable builds. This would also map directly to how we handle the publishing to PackageCloud which has two distinct channels/repos:
https://packagecloud.io/chef/current
https://packagecloud.io/chef/stable

**Comment by btm** [comment]
In effect, I believe you're arguing that remove all Omnitruck functionality where it differentiates between types of builds by filename, and have the install.sh script / MSI links use a different URL for fetching different packages? That's a little different than just combining Omnitruck's current idea of pre-release versus nightly.

I think we'd want to have the stable instance return a 301 if ```nightlies``` or ```prerelease``` is true, for compatibility for anyone using the API. Or an 500 error at least. Something less confusing than ignoring it.

**Comment by lamont-granquist** [comment]
Two omnitruck instances sounds like a really bad idea to me.   We have the ability to support different projects already which are similar to channels with `-P chef-server` and `-P chefdk`.  The additional overhead of managing more instances seems unnecessary.

We can take the existing omnitruck instance and add more channels like 'chef-stable' and 'chef-current' or we can add another flag which switches between stable and current subdirs in the metadata bucket.  That way we don't have to increase the infrastructure footprint of omnitruck and the management overhead and add more URLs and increase the confusion and likelihood of operational mistakes.   The logic to implement 'channels' is already there in the 'project' logic, you just have to decide on what final shape you want the API to be.

**Comment by schisamo** [comment]
I don't care how we achieve 2 distinct channels in Omnitruck (multiple instances, multiple buckets etc.) but a couple of things to think about as you design the solution/api/architecture:

* As we move to a pure continuous delivery world we'll stop creating special ceremonial _stable_ builds (with special version numbers). Essentially any build is a candidate for being blessed as _stable_. In this world, we won't be able to use the package's version number to determine it's channel categorization. Many Chef Software, Inc. projects (Chef Server, Management console etc) are already beginning to experiment with using build versions like: `MAJOR.MINOR.PATCH+YYYYMMDDHHMMSS`. 
* Pre-releases (alphas, betas, RCs etc) will most likely become a thing of the past as we will have many end-users (including Chef Software, Inc.) dog fooding builds from the 'current' channel.
* We're about to move the publishing to Omnitruck from Jenkins to Artifactory. This will ensure all of our external consumption points (PackageCloud, Omnitruck etc.) are all published to at the same time and adhere to the same promotion logic. Publishing to Omnitruck will work in the same way publishing to PackageCloud currently works:
  * There is a 1:1 mapping between an Artifactory repo and an associated external channel (e.g. `omnibus-current-local -> PackageCloud chef/current`, `omnibus-stable-local -> PackageCloud chef/stable`) 
  * An Artifactory user plugin responds to Artifactory publish events and pushes (and yanks) artifacts to the external system appropriately.

**Comment by lamont-granquist** [comment]
So omnitruck already has the same kind of internal structure.  The opscode-omnibus-package-metadata bucket holds different subdirs which are like different channels when then have all the individual metadata json blobs.  The artifacts are stored separately in opscode-omnibus-packages.

Omnitruck wouldn't have a problem with having something like:

opscode-omnibus-package-metadata/chef-current/12.3.0+20150417120000.json pointing at s3://opscode-omnibus-packages/ubuntu/14.04/x86_64/chef-12.3.0+20150417120000.json and then to do a release to stable all you do is upload a new opscode-omnibus-package-metadata/chef-stable/12.3.0+20150417120000.json blob pointing at the same artifact.  Essentially the metadata blobs give you symlinks.

**Comment by btm** [comment]
@schisamo So do current builds get ```MAJOR.MINOR.PATCH+YYYYMMDDHHMMSS``` but stable channel builds will always be just a version? Is this how chef-trigger-release versus chef-trigger-anything_else currently works in manhattan?

If not:

If there's nothing in the version that differentiates between stable and current builds... when we want to promote a build to stable are we going to ask people to test whatever the latest build from current is (instead of an RC)?

It feels like it's going to be a little frustrating when someone has an issue and they tell support (or IRC, or whoever) that they're running chef-12.3.0+20150417120000, if that build had a small bug and we shortly after made another build chef-12.3.0+20150417122000 and that one was promoted to stable. You're going to want to tell someone to upgrade to the latest something, but people don't always want to upgrade to the very latest release.

**Comment by btm** [comment]
@schisamo I think the technical options for exposing two channels so someone can run "install.sh --give-me-the-edge" and get what they want are all in here, and we're probably shed-building past this point.

Once https://github.com/chef/chef-rfc/issues/115 gets accepted, someone from releng should open a PR against it to propose whatever versioning scheme you've come up with. I don't want to surprise the community with a significant change in how releases are versioned and treated.

**Comment by adamedx** [comment]
I vote for keeping things simple here and making it easy for us to just get started -- if a new omnitruck for "current" is easy to do, can we just go with that and iterate? Here's what I'd like to see:

* One convention for categorizing releases (e.g. "stable" vs "current") across all Chef Software releases ("products")
* One way for users to choose from those categories across release points (e.g. omnitruck vs. packagecloud)
* Start on a path that makes it easy for projects to use Delivery
* An easy was for us to just get started and take a baby step

I think having omnitruck support an explicit "current" and "stable" channel with different URI's / implementations will do that and would let us get up and running faster (existing omnitruck would just be stable, and we could experiment with a new one for current without disrupting stable). .

I could live with a single omnitruck and a query parameter for stable vs. current (the first two bullets), but I don't relish the idea of changing that public endpoint while we're this early in the game.

Worst case we learn that it's better for users to have one omnitruck, but in the short term I think tossing another one out there is pretty easy, right @schisamo?

@btm, I hear you on the version concerns, but again, I'd like to see people hit issues here and then we take action, which should be pretty fast. Also, it may be that versioning methodologies get "forced" on us initially as we move to using Delivery in more places.

We can always change things later folks. :smile:.

**Comment by btm** [comment]
@adamedx I'm not sure what you mean by vision, but my concern is that Chef Software decides how Chef Client is going to be versioned internally, ships it, and waits for people to have issues before starting a discussion with them. 

For example, just talking about versioning on https://github.com/chef/chef-rfc/pull/115 has already exposed that @jaymzh has encountered upgrade issues with our current versioning scheme with rpm packages.

Discussing it publicly both makes it more complete, and makes us good members of the community.

**Comment by adamedx** [comment]
@btm, maybe I'm not getting it, but is there a new versioning scheme being proposed for the current omnitruck? If we have a new omnitruck, versions aren't affected, right?

**Comment by jonlives** [comment]
I'd second the importance of having this discussion in the open so to speak to surface potential issues before they bite people.

On a more general note about the continuous delivery of releases, it bears remembering that although builds will indeed be delivered continuously and this is a good thing, they will often not be *consumed* that way. 

When doing CD inside a company for example, you're often going to be deploying the latest release into production at any one time. This does not map to the way people typically deploy chef releases - some people will be relatively bleeding edge, some people will still be trying to finish migrating to 12.x full stop (we're one of those cases), and you will often find a large delta between the chef-client versions people deploy in production. Often, a new release will only be consumed by a customer because it scratches a particular itch or adds a new feature.

When we're looking at how to implement this on the omnitruck side, my gut reaction is to favour separate stable and current channels simply to make it as easy as possible to DWIM. As a consumer of chef releases, I'd like to be able to go to the stable channel and see "ah yes, this is the most recent stable 12.1 release, and here's the latest stable 12.3 release I want to upgrade to.". 

As @schisamo said, we might not in future be able to use a version number to indicate stability, so that's mainly why it seems reasonable to me to have a channel where *only* builds blessed as stable exist. The actual build number doesn't matter, but I know that in that channel I will always find the latest stable 12.x.y.ZZZZZZ release. In the event that I *do* need a more current release that hasn't been marked as stable, I have the option of going to the "current" channel should I choose to.

Although debian stable & testing repos aren't exactly a model for continuous delivery, it's that sort of model I see as making the most practical distinction between whichever builds have been blessed as stable, and which are bleeding edge nightlies. That said, if there's a nice way to do this under one omnibus project then great, my main intent here is that we don't get too carried away with CD that we forget how said deliveries are typically going to be consumed.

**Comment by btm** [comment]
FWIW, you can currently get a nightly build from the Omnitruck API: http://www.chef.io/chef/download?p=windows&pv=2008r2&m=x86_64&v=latest&prerelease=true&nightlies=true

Right now, this gives you chef-client-12.4.0-dev.0+20150501082811.git.48.b060c84-1.msi, which was built by http://manhattan.ci.chef.co/job/chef-build/102/ (internal link) by the nightly trigger.

**Comment by btm** [comment]
I think this was mostly done in https://github.com/chef/opscode-omnitruck/pull/100, but the [install.sh](https://github.com/chef/opscode-omnitruck/blob/master/views/install.sh.erb) hasn't been updated to correspond yet and we haven't shipped those changes which have been merged.

**Comment by lamont-granquist** [comment]
That shipped yesterday.  Right now we do still differentiate between released versions and nightlies by their version number, and not by what channel they are in, but everything else works to get nightlies.

**Comment by btm** [comment]
@lamont-granquist how do the existing -n and -p flags work with what just shipped? We used to have to pass both -n and -p to get what we expected as a "nightly".

**Comment by lamont-granquist** [comment]
Use either one, and you get whatever the latest is...  Even if the latest is a release, so its "additive" rather than exclusive.

**Comment by lamont-granquist** [comment]
I think this is closable now at least in this repo.  The nightlies work fine in omnitruck/install.sh now.

The only remaining problem is that omnibus-chef needs to be pointed at "master" or else the actual nightly builds themselves will just rebuild release tags -- which is a bug against omnibus-chef.
