### ISSUE TITLE
knife cookbook upload returns ERROR: EOFError: end of file reached

### ISSUE THREAD

**Issue by ArjunHariharan** [chef/chef#3211]
After upgrading to chef-server 12, I started observing this failure while uploading cookbook smf.

```
knife cookbook upload smf
Uploading smf            [2.2.6]
	ERROR: EOFError: end of file reached
```

However, this works fine with chef-server 11
```
knife cookbook upload smf --force
Uploading smf            [2.2.6]
Uploaded 1 cookbook.
```

I tried purging all the cookbooks and uploading them again as suggested in a lot of blogs. Even that couldn't resolve this issue.

chef-client version - 11.18.6

**Comment by lamont-granquist** [comment]
At the very least we would need debug output from `knife cookbook upload smf -VV` to be able to have an idea of where the EOFError is coming from.  The logs from the server would also be useful.

**Comment by lamont-granquist** [comment]
Been a few months with no response, have to assume this was transient networking or something (EOFError is usually networking or bad TCP driver settings).
