### ISSUE TITLE
Failed to run verify-system-status when executing chef-server-ctl reconfigure

### ISSUE THREAD

**Issue by alulululu** [chef/chef#3219]
Failed to run [verify-system-status] when executing "chef-server-ctl reconfigure", but when calling " http://127.0.0.1:8000/_status" by firefox, it returns "{"status":"pong","upstreams":{"chef_solr":"pong","chef_sql":"pong"}}"

error log:
------------------------------------
Expected process to exit with [0], but received '22'
---- Begin output of curl -sf http://127.0.0.1:8000/_status ----
STDOUT: 
STDERR: 
---- End output of curl -sf http://127.0.0.1:8000/_status ----
Ran curl -sf http://127.0.0.1:8000/_status returned 22

**Comment by thommay** [comment]
Hi,
if you can still reproduce this issue, please open a new issue on chef-server at https://github.com/chef/chef-server/issues . Please can you include the version of chef-server that you're installing and what topology and so on.
Thanks!
