### ISSUE TITLE
SUSE Enterprise stops at 12.0.3

### ISSUE THREAD

**Issue by jaym** [chef/chef#3224]
The dropdown on the Chef Client downloads page stops at 12.0.3. SUSE Enterprise users are expected to use the Enterprise Linux builds, however this is confusing. We should either remove the SUSE Enterprise dropdown or make it an alias for Enterprise Linux

**Comment by coderanger** [comment]
For tracking https://github.com/chef/omnibus-chef/commit/129c4231b67d7c8caea2458063df159f82a811ee is the commit that caused builds to stop being published to `/full_client_list` (I think).

**Comment by adamedx** [comment]
The SUSE link has been removed, but in the future we should revisit adding the aliasing feature for users who aren't aware they can use the RHEL package.
