### ISSUE TITLE
Productize / Take ownership / Contribute to vsphere plugin

### ISSUE THREAD

**Issue by radiumx3** [chef/chef#3226]
Just a feature request that has been made some times ago and we would like to have a statement on this....

from https://tickets.opscode.com/browse/KNIFE-268

"As a FSA it would greatly enhance the sales cycle if we supported vsphere with knife in addition to our vcloud director support.
Currently a third party plugin (https://github.com/ezrapagel/knife-vsphere) that maintains decent support to perform vsphere related commands. Opscode, through Chirag's work, is maintaining a vcloud plugin. Problem is that most VMWare environments do not have vCloud due to expense and complexity of deployment.
However VMWare vSphere / vCenter is in pretty much every VMware shop, in addition vCloud requires vCenter/vSphere.
The third party plugin currently is not fully on feature parity with the vCloud plugin (bootstrap on Windows support for example). While knife plugins are community maintained, Opscode should consider becoming the gatekeeper / maintainer for this plugin"

**Comment by thommay** [comment]
@mattray is this a thing that's likely to happen?

**Comment by mattray** [comment]
Yes. Partner Engineering should eventually take responsibility for providing a more supported vSphere plugin as part of our VMware story. This is much like we're slowly taking responsibility for AWS, OpenStack and Azure. This doesn't mean we'll be taking sole responsibility of all VMware-related development, but Partner Engineering is supposed to be the ones who maintain vendor-to-vendor product integrations. 

I had a position "Partner Engineering SDE: VMware" specifically for this sort of work, it still hasn't been filled even though it is no longer posted.

**Comment by radiumx3** [comment]
Envoyé par Outlook pour Android




On Thu, Apr 16, 2015 at 3:06 AM -0700, "Matt Ray" <notifications@github.com> wrote:
Yes. Partner Engineering should eventually take responsibility for providing a more supported vSphere plugin as part of our VMware story. This is much like we're slowly taking responsibility for AWS, OpenStack and Azure. This doesn't mean we'll be taking sole responsibility of all VMware-related development, but Partner Engineering is supposed to be the ones who maintain vendor-to-vendor product integrations.

I had a position "Partner Engineering SDE: VMware" specifically for this sort of work, it still hasn't been filled even though it is no longer posted.

---

**Comment by lamont-granquist** [comment]
So, this isn't a chef-client bug, there's no code to commit to this repo.  Not debating the utility of the request, but this isn't the right channel.  A support request or some other customer engineering through a support contract would be a better way to get this prioritized.

**Comment by radiumx3** [comment]
Well there won't be any support contract with us if we're not even able to make our Proof on Concept on your product yet. I got your point tho'.
