### ISSUE TITLE
Aditional character on knife 12.2.1 using head

### ISSUE THREAD

**Issue by tiago-cruz-movile** [chef/chef#3229]
- knife 11.14:
```
[tiago.cruz@aeiou ~]$ sudo knife search dwarf -c /etc/chef/client.rb  | head -n 1
33 items found
[tiago.cruz@aeiou ~]$ knife -v
Chef: 11.14.2
```

- knife 12.0.0:
```
[tiago.cruz@mordor ~]$ sudo knife search dwarf -c /etc/chef/client.rb  | head -n 1
33 items found
[tiago.cruz@mordor ~]$ knife -v
Chef: 12.0.0
```

Now, using knife 12.2.1:
```
[tiago.cruz@moria ~]$ sudo knife search dwarf -c /etc/chef/client.rb  | head -n 1
33 items found

Node Name:   xxxxx.com
[tiago.cruz@moria ~]$ knife -v
Chef: 12.2.1
```
Can't you see? The `head -n 1` is not working any more on Chef 12.2.1 =)

Some strange invisible character or some like this are confusing the 'head' to get just the first line, and with this, breaking some scripts :+1:

**Comment by stevendanna** [comment]
@tiago-cruz-movile Might it be that the extra newline is being output on stderr?  What if you try:

    sudo knife search dwarf -c /etc/chef/client.rb 2>/dev/null | head -n 1

**Comment by tiago-cruz-movile** [comment]
Hello @stevendanna :)

Take a look:

``` 
tiagocruz@stark:~$ knife search dwarf  | head -n 1
33 items found

Node Name:   node1

tiagocruz@stark:~$ knife search dwarf 1>/dev/null | head -n 1
33 items found

tiagocruz@stark:~$ knife search dwarf 2>/dev/null | head -n 1
Node Name:   node1
``` 

Strange, is not?

**Comment by stevendanna** [comment]
@tiago-cruz-movile I think this was a purposeful change: https://github.com/chef/chef/commit/c2dfb56e730214266ae07a57a56e5889b1e6b85b

**Comment by thommay** [comment]
Yeah, this was done on purpose. We're going to close this bug.
