### ISSUE TITLE
template verify variable name mismatch

### ISSUE THREAD

**Issue by Tech356** [chef/chef#3232]
[RFC 27](https://github.com/chef/chef-rfc/blob/master/rfc027-file-content-verification.md) states

    The path to the temporary file with the proposed content will be available
    by using Ruby's sprinf formatting:

    "%{path}"

And the [documentation](https://docs.chef.io/resource_template.html) show an example

    template "/etc/nginx.conf" do
      verify "nginx -t -c %{path}"
    end

But the [code](https://github.com/chef/chef/blob/master/lib/chef/resource/file/verification.rb#L109) gives `file` instead of `path`

    def verify_command(path, opts)
        command = @command % {:file => path}
        interpreter = Chef::GuardInterpreter.for_resource(@parent_resource, command, @command_opts)
        interpreter.evaluate
    end

**Comment by stevendanna** [comment]
Thanks @Tech356.  Let's add :path and keep :file to avoid breaking anyone else who managed to figure out the right option.  Sorry about this.
