### ISSUE TITLE
two different behaviors for attribute and variable

### ISSUE THREAD

**Issue by chenzhiwei** [chef/chef#3237]
Chef attribute file
```
default['test']['attr'] = []
```

Chef recipe file
```
node.override!['test']['attr'] = ['5']

template '/tmp/test.txt' do
  source 'test.erb'
  variables(
    var: node['test']['attr'].to_s
  )
end

node.override!['test']['attr'] = ['6']
```

Chef template file
```
line_1 = <%= @var %>
line_2 = <%= node['test']['attr'].to_s %>
```

And line_1 and line_2 have the different value.

So, is this a Chef bug?

**Comment by stevendanna** [comment]
This is currently the expected behavior and is one of the reasons we introduced the lazy {} operator.  The argument to variables in your template block is evaluated at "compile time" as that resource is added to the resource collection.  The template itself is evaluated on converge time.

**Comment by chenzhiwei** [comment]
Thanks, I see.

I think I have no way to override resource variables in compile time, am I right?

And I am confused for the new attribute override method, like override and override! .

Through my testing, only force_override! will override the attribute, and other method will do something like deep merge.

I need to override an attribute which is in `override_attributes` section in environment, I know force_override! will work, but this method does not compatible with Chef 11. So, is there any other way to override environment.override_attributes in recipes?

**Comment by chenzhiwei** [comment]
Seems no one want to reply my second question, so close this issue. :(
