### ISSUE TITLE
Descendants tracker should use WeakRef

### ISSUE THREAD

**Issue by coderanger** [chef/chef#3239]
Right now it makes it impossible to have transient, anonymous provider classes easily. The tracker code should use WeakRefs and when accumulating descendants it should check if the ref is alive. Maybe offer an explicit `unregister!` call too.

**Comment by thommay** [comment]
Is this still an issue given all of the rewriting of providers?

**Comment by coderanger** [comment]
Given that DescendantsTracker is still included in Resource and Provider, yes this is still holding on to refs longer than it should.

**Comment by lamont-granquist** [comment]
Could use a PR to either remove DT and/or fix this.
