### ISSUE TITLE
Update chef/kitchen-tests to work with new provisioner

### ISSUE THREAD

**Issue by mcquin** [chef/chef#3241]
For reference: https://github.com/test-kitchen/test-kitchen/pull/484#issuecomment-94195354

\cc @chef/client-engineers

**Comment by lamont-granquist** [comment]
:+1:

**Comment by thommay** [comment]
This is reflected in ecosystem engineering's backlog, so let's continue to track it there!

**Comment by jaym** [comment]
this already happened
