### ISSUE TITLE
feature to check pgp signature of changes before applying them

### ISSUE THREAD

**Issue by ag4ve** [chef/chef#3243]
I'm not the best way to implement this. However, what I'd like is:
* setup pgp with a trustdb of people who should be able to update a server
* sign updates on the chef server
* check signatures before applying changes
* fail if there's no signature or the the person isn't trusted

Maybe this could be different for different paths or commands (a user could update /etc/ssh but not /etc/sudoers etc).

End result though is to not trust a central point for distributing possibly harmful changes to an environment.

**Comment by thommay** [comment]
Hi,
sorry to be so slow in responding! Feature requests such as this are best submitted to https://feedback.chef.io ; if you'd still like this please go ahead and create a new request there.
Thanks!
