### ISSUE TITLE
chef-client fails to start on sles 10 with floating point exception.

### ISSUE THREAD

**Issue by jagadeeshops** [chef/chef#3245]
This issue is already in jira and in the state confirmed. Url given below.
https://tickets.opscode.com/browse/CHEF-4892?page=com.googlecode.jira-suite-utilities:transitions-summary-tabpanel 
Actual issue: Installation goes well. If i try to start chef-client after installation it says Floating point exception and comes out.

Is there any workaround for us to make it work on sles 10?

**Comment by lamont-granquist** [comment]
There is no workaround and no plans to support SLES 10 with omnibus packages.  I suspect that we never will support it.

**Comment by jagadeeshops** [comment]
I got a workaround..Ruby is installed outside chef , installed the required gems for chef and pointed chef to the new ruby. I tested with a small recipe to create a file and it worked well. But not sure whether this setup will support all chef resources.
