### ISSUE TITLE
ifconfig resource does not respect 'target' option properly

### ISSUE THREAD

**Issue by rafaltrojniak** [chef/chef#3250]
It looks like 'target' properly is not respected in resource 'interface'.

While documentatoin says :
> target 	The IP address that will be assigned to the network interface. Default value: the name of the resource block. (See “Syntax” section above for more information.)

The code and behaviour looks like the variables are used separately. 

for example resource like :
````ruby
  ifconfig 'test-name' do
    device 'lo:1'
    target '1.2.3.4'
    mask '255.255.255.255'
    action [:add, :enable]
  end
````
will throw error :
````
           ================================================================================
           Error executing action `add` on resource 'ifconfig[test-name]'
           ================================================================================
           
           Chef::Exceptions::Exec
           ----------------------
           ifconfig lo:1 test-name netmask 255.255.255.255 returned 1, expected 0
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/XXX/recipes/default.rb
           
           147:   ifconfig 'test-name' do
           148:     device 'lo:1'
           149:     target '1.2.3.4'
           150:     mask '255.255.255.255'
           151:     action [:add, :enable]
           152:   end
           153: 
````

**Comment by juliandunn** [comment]
What platform are you on?

**Comment by rafaltrojniak** [comment]
Does it really changes anything at this particular problem ? I was testing that on centos-6.5, but the code is broken in the platform-shared part too.

Here is how I expected it to be implemented when digging  though the code: https://github.com/chef/chef/compare/master...rafaltrojniak:ifconfig_target?expand=1

**Comment by juliandunn** [comment]
I'm not familiar with this provider's code, but I see what you're saying. Actually, since the resource already [takes care of](https://github.com/chef/chef/blob/master/lib/chef/resource/ifconfig.rb#L33) setting `target` to `name` when `target` isn't specified, what's needed here is just to substitute `@new_resource.name` for `@new_resource.target`. Want to submit a patch?

**Comment by rafaltrojniak** [comment]
@juliandunn  Thanks for pointing that out, now I can see how this works when `target` is really used.

Apart from simple substitution, the detection logic seams weird too : https://github.com/chef/chef/blob/master/lib/chef/provider/ifconfig.rb#L70 (what does this 'inet_addr' really means ? is there 'inet6_addr' ?)

Really not sure how this supposed to be done, and I still have no CLAs signed.
I'm also not in hurry, so will leave this for someone with CLAs and more knowledge in code.

**Comment by juliandunn** [comment]
Yeah, I'm not sure either. Digging through the Git history it looks like this provider code [dates right back](https://github.com/chef/chef/commit/dbce25a9624c04ffafebb4cb581968f61ba637ea) to Chef's inception in 2009, so I'm not surprised it's wrong. My current Linux boxes don't have such an `inet_addr` field.

I'll minimally fix the problem you reported in this ticket, but it looks like this provider needs an overhaul generally.

**Comment by rafaltrojniak** [comment]
@juliandunn  Yes, the provider does quite weird things and needs to be cleaned up. But fixing that particular problem with target is enough for me now.
Maybe if I will someday sign CLA, that would be my first Pull request :P

**Comment by juliandunn** [comment]
@rafaltrojniak that would be great :grinning:
