### ISSUE TITLE
YUM package update as a group vs individual packages

### ISSUE THREAD

**Issue by tfitch** [chef/chef#3256]
Filing on behalf of a customer here.

This started out as possibly an issue with the OpenSSL cookbook, because it was failing to upgrade the openssl package when using the `openssl:upgrade` cookbook.  The error message is as follows

```
---- Begin output of ----
STDOUT: STDERR:
Transaction Check Error:
file /etc/pki/tls/certs/ca-bundle.crt from install of openssl-0.9.8e-32.el5_11.x86_64 conflicts with file from package openssl-0.9.8e-26.el5_9.1.i686
file /usr/share/man/man1/ca.1ssl.gz from install of openssl-0.9.8e-32.el5_11.x86_64 conflicts with file from package openssl-0.9.8e-26.el5_9.1.i686
file /usr/share/man/man1/req.1ssl.gz from install of openssl-0.9.8e-32.el5_11.x86_64 conflicts with file from package openssl-0.9.8e-26.el5_9.1.i686
file /usr/share/man/man1/x509.1ssl.gz from install of openssl-0.9.8e-32.el5_11.x86_64 conflicts with file from package openssl-0.9.8e-26.el5_9.1.i686

Error Summary

-------------

---- End output of ——

# Declared in /var/chef/cache/cookbooks/openssl/recipes/upgrade.rb:33:in `block in from_file'
package("openssl") do
action [:upgrade]
retries 0
retry_delay 2
guard_interpreter :default
package_name "openssl"
version "0.9.8e-32.el5_11"
timeout 900
cookbook_name "openssl"
recipe_name "upgrade"
end
```

The tricky part comes from manually doing a `yum update openssl` and getting no error.  But the chef-client is doing the updates one at a time, akin to running `yum update openssl-0.9.8e-26.el5_9.1.i686` which fails.

Unfortunately, I don’t have the archeology of the code traces handy, but I think the issue is actually with the package resource not the openssl cookbook. The cookbook is, by default, specifying a package family (not any specific version or architecture which would likely work in this case 
if the YUM package used only the family).

From what I could infer from the YUM package code, it looked as if the resource was querying the system to determine which packages were installed, capturing them in a list, and then iterating through the list to do the updates one at a time instead of as a family.

If so, this would result in the issue we're is seeing.

**Comment by lamont-granquist** [comment]
This is probably yet another incarnation of the yum arch bug which is fixed in master and should be released in 12.4.0

**Comment by lamont-granquist** [comment]
Hmm, no nevermind its not that bug.  This is sort of like the multipackage stuff, but with a single label inflating to multiple packages to install.  The cookbook can probably code around this by using a multipackage install and manually inflating the group itself.

**Comment by phundisk** [comment]
Yes it sounds like the multipackage would resolve the issue described above.

**Comment by timgriffiths** [comment]
Exactly how do i get around this problem with multipackage?

**Comment by lamont-granquist** [comment]
easiest way for now probably looks something like this (off the top of my head so probably has a bug or three):

```ruby
execute "install openssl" do
  command "yum -y install openssl"
  not_if "rpm -qa | egrep openssl"
end
```

the 'right' way to fix it involves resolving the group of packages to a single package via yum and then doing a multipackage install of that list.  i can't claim to know yum very well any more, so don't know what that is without a bunch of research.

**Comment by vinyar** [comment]
I was hitting this issue a few days ago actually. In my case, I was able to work around it by adding apt cookbook to the runlist, and enabling compile time update

```
    attributes:
      apt:
        compile_time_update: true
        compiletime: true
```

**Comment by marktheunissen** [comment]
@timgriffiths Try (for example):

```
multipackage [ "vim-common", "vim-minimal", "vim-enhanced" ] do
  action :upgrade
end
```

Using https://supermarket.chef.io/cookbooks/multipackage/versions/2.0.4

**Comment by lamont-granquist** [comment]
This is working for me right now on centos 7:

```
[2016-11-29T19:42:05+00:00] DEBUG: yum_package[openssl] checking yum info for openssl
[2016-11-29T19:42:05+00:00] DEBUG: yum_package[openssl] installed version: ["1.0.1e-42.el7"] candidate version: 1.0.1e-51.el7_2.7
[2016-11-29T19:42:05+00:00] DEBUG: yum_package[openssl] openssl is out of date, will upgrade to 1.0.1e-51.el7_2.7
[2016-11-29T19:42:05+00:00] INFO: yum_package[openssl] installing openssl-1.0.1e-51.el7_2.7 from updates repository
[2016-11-29T19:42:05+00:00] DEBUG: yum_package[openssl]: yum command: "yum -d0 -e0 -y install openssl-1.0.1e-51.el7_2.7"
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
[2016-11-29T19:42:07+00:00] INFO: yum_package[openssl] upgraded openssl to 1.0.1e-51.el7_2.7

    - upgrade package openssl from 1.0.1e-42.el7 to 1.0.1e-51.el7_2.7
```

**Comment by lamont-granquist** [comment]
Also appears to work on centos 6:

```
[2016-11-29T19:47:54+00:00] DEBUG: yum_package[openssl] checking yum info for openssl
[2016-11-29T19:47:54+00:00] DEBUG: yum_package[openssl] installed version: ["1.0.1e-48.el6"] candidate version: 1.0.1e-48.el6_8.3
[2016-11-29T19:47:54+00:00] DEBUG: yum_package[openssl] openssl is out of date, will upgrade to 1.0.1e-48.el6_8.3
[2016-11-29T19:47:54+00:00] INFO: yum_package[openssl] installing openssl-1.0.1e-48.el6_8.3 from updates repository
[2016-11-29T19:47:54+00:00] DEBUG: yum_package[openssl]: yum command: "yum -d0 -e0 -y install openssl-1.0.1e-48.el6_8.3"
[2016-11-29T19:47:58+00:00] INFO: yum_package[openssl] upgraded openssl to 1.0.1e-48.el6_8.3

    - upgrade package openssl from 1.0.1e-48.el6 to 1.0.1e-48.el6_8.3
```

based on the package versions this looks like it affects CentOS 5, but unfortunately my ability to run CentOS 5 bento boxes is busted right now due to virutalbox issues, which impedes researching this one.

**Comment by lamont-granquist** [comment]
This looks like its been fixed for some time now, I can't replicate on Chef 13.5.25
