### ISSUE TITLE
analytics should be removed as an option in chef-server-ctl install command

### ISSUE THREAD

**Issue by vinyar** [chef/chef#3273]
chef-server-ctl install
You must supply an addon name. Valid names include: chef-ha, chef-sync, **opscode-analytics**, opscode-manage, opscode-push-jobs-server, opscode-reporting.

Details: 
It will not work out of the box, as both analytics and chef server use postgresql on port 5432. Also, according to @jamesc there are performance penalties to having both on one the same box.

**Comment by stevendanna** [comment]
I've opened a chef-server bug for this here: https://github.com/chef/chef-server/issues/152
