### ISSUE TITLE
add-user-key argument error: wrong number of arguments

### ISSUE THREAD

**Issue by jdallen** [chef/chef#3274]
running chef-server-ctl add-user-key <user> <key path> leads to argument error:

/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/chef-12.0.3/lib/chef/http.rb:125:in `post': wrong number of arguments (0 for 2..3) (ArgumentError)

The problem seems to be in the post_rest method on line 43 in: 
/opt/opscode/embedded/service/omnibus-ctl/helpers/key_ctl_helper.rb

it needs to change from:
@chef_rest.post_rest
to:
@chef_rest.post_rest(url,body)

**Comment by merqlove** [comment]
Same here!

**Comment by mkmcdonald** [comment]
This is a one-line fix. Please take a look at this issue, Chef Software.

**Comment by thommay** [comment]
Hi, this is a chef-server issue; please can you file it at https://github.com/chef/chef-server/issues ?

**Comment by mkmcdonald** [comment]
Thanks, @thommay. I have done so.
