### ISSUE TITLE
Silent failure when attempting to delete directory with partition mounted to that point

### ISSUE THREAD

**Issue by sethfreeman** [chef/chef#3276]
I am installing tomcat 8 in the opt directory, deleting the /opt/tomcat directory if it exists, and creating a symlink from /opt/tomcat to the installation of tomcat.

The recipe looks like this:

directory "/opt/tomcat" do
  recursive true
  action :delete
  not_if { File.symlink?('/opt/tomcat') }
end

link "/opt/tomcat" do
  to "#{install_path}"
  owner 'tomcat'
  group 'tomcat'
end

The log indicates that the directory is being deleted, but it's not being deleted (see below).

There is a silent failure because that directory has a partition mounted to that point.

The actual error when running rm -rf on the command line is:

rm: cannot remove ‘/opt/tomcat/’: Device or resource busy

Chef should pick up this error the Chef run should fail based on that.

---
- directory[/opt/apache-tomcat-8.0.20] action create (up to date)
- directory[/opt/tomcat] action delete
  - delete existing directory /opt/tomcat
- link[/opt/tomcat] action create
  # 
  # Error executing action `create` on resource 'link[/opt/tomcat]'
  ## Errno::EISDIR
  
  Is a directory - /opt/tomcat

**Comment by zoeyang7633** [comment]
Hi, I am also having a similar issue which the directory was not deleted properly but there's no error. Is there any updates on this issue?

**Comment by snehaldwivedi** [comment]
Hi @sethfreeman, I have tried to reproduce this issue in the current chef version `chef- 21.6.467`, `OS- Ubuntu-20.04` but couldn't reproduce it. Following are the steps I followed to reproduce it.

```
directory "/opt/tomcat/apache-tomcat-8.5.69-deployer" do
   recursive true
   action :delete
   not_if { File.symlink?('/opt/tomcat/apache-tomcat-8.5.69-deployer') }
end

link "/opt/tomcat/apache-tomcat-8.5.69-deployer" do	
    to "/opt/tomcat/latest"
    owner 'tomcat'
    group 'tomcat'
end
```
**Output- 1st time:**

```
* directory[/opt/tomcat/apache-tomcat-8.5.69-deployer] action delete
   - delete existing directory /opt/tomcat/apache-tomcat-8.5.69-deployer
 * link[/opt/tomcat/apache-tomcat-8.5.69-deployer] action create
        - create symlink at /opt/tomcat/apache-tomcat-8.5.69-deployer to /opt/tomcat/latest
        - change owner from '' to 'tomcat'
        - change group from '' to 'tomcat'    
```
**2nd time**
```
 * directory[/opt/tomcat/apache-tomcat-8.5.69-deployer] action delete (skipped due to not_if)
       * link[/opt/tomcat/apache-tomcat-8.5.69-deployer] action create
```
       
It was deleting the existing directory and creating a symlink, as expected, and skipping the delete action if it's a symlink. Please check it on the latest chef version and if the issue still exists let us know.

**Comment by snehaldwivedi** [comment]
closing this as there is no response from the user and the issue was not replicated
