### ISSUE TITLE
Chef Client 11 -> 12 Regression In Initial Run of Daemonized chef-client

### ISSUE THREAD

**Issue by sean-horn** [chef/chef#3282]
Zendesk 4031

As a customer, I would like Chef Client 12.2.x to begin a daemonized run by running immediately or shortly after startup.

Currently, it waits the full interval + splay for the initial run.

This command

    chef-client -i 3666 -s 120 -l debug -L ./mylogfile.txt

Results in this debug log output, where the sleeping comes first

    # Logfile created on 2015-04-24 20:40:33 +0000 by logger.rb/44203
    [2015-04-24T20:40:33+00:00] INFO: Daemonizing..
    [2015-04-24T20:40:33+00:00] INFO: Forked, in 20380. Privileges: 0 0
    [2015-04-24T20:40:33+00:00] DEBUG: Sleeping for 3694 seconds

This looks like the possible location https://github.com/chef/chef/blob/12.2.1/lib/chef/application/client.rb#L377-L389

**Comment by diasjorge** [comment]
I'm experiencing the same after the update to 12.2.1 from 11.8

**Comment by lamont-granquist** [comment]
Closing as a dup of #3305 where i posted some commentary.
