### ISSUE TITLE
 Possible issue with chef-client > 12.0.3-1 - Related to Issue 3694

### ISSUE THREAD

**Issue by gyoza** [chef/chef#3290]
I started this post on the users cookbook page based off discussions on the chef irc channel but I felt like an issue should be created here as well, after this issue was created I was told to create one here..

In Short, any client (tested on RHEL type) > 12.0.3-1 gets into an infinite loop using the users_manage::sysadmins which then in turn consumes a whole lot of CPU until the process is killed.

The client is complaining about "cloned resources" and references issue 3694.

http://pastebin.com/p8Z1uaAm - log file of this action.

Here is a link to the user cookbook issue.
https://github.com/opscode-cookbooks/users/issues/94
here is a link to the chef-client issue. 
https://github.com/opscode-cookbooks/chef-client/issues/309

Attempted to update one of my systems to chef 12.1.0+ and I am getting the following error(s) when trying to run the client.

I am not trying to do anything tricky. Simply using a databag named users with an enguser group set in the user json.

-Cookbook-

```
include_recipe 'users'

users_manage "engusers" do
group_id 9001
action [ :remove, :create ]
end
```

Not really sure how to resolve this since the attribute names appear to be unique?

To note, 12.0.3 does not exhibit this problem.

**Comment by gyoza** [comment]
Anybody have any ideas?

**Comment by gyoza** [comment]
I am not the only one having this problem.

**Comment by lamont-granquist** [comment]
Was this ever fixed?  I have a feeling it was either fixed in core chef or was a cookbook issue and this hasn't cropped up again recently...

**Comment by tas50** [comment]
Closing this out since we didn't get a response on the request for a replication. If this is still a problem please file an new issue with details and we'll get back to you.
