### ISSUE TITLE
no_proxy behavior when set in client.rb vs environment

### ISSUE THREAD

**Issue by fdevaux** [chef/chef#3293]
client.rb supports setting no_proxy (as per https://docs.chef.io/config_rb_client.html)

However no_proxy set in client.rb behaves different from having it set as an environment variable (in the shell running chef-client). The client.rb version only supports a full hostname or IP whereas the environment variable supports a domain.

The document **does** mention this though ...
> A comma-separated list of URLs that do not need a proxy. Default value: nil.

However this is very confusing for the user.

For example, let's say I want no_proxy for all the hosts under internal.bigcorp.com, and one of the hosts is fileserver.internal.bigcorp.com. I test this with the remote_file platform resource.

If I have an environment variable `no_proxy=internal.bigcorp.com`, no proxy is being used, as expected. However if I have no environment variables and define the proxy settings in client.rb, the proxy will be used. If I update the no_proxy in client.rb to be `no_proxy fileserver.internal.bigcorp.com` the proxy is bypassed again.

**Comment by llaurent** [comment]
I've just upgraded to chef 12.2.1
In my client.rb I have  http_proxy, https_proxy and no_proxy defined and I also encounter the issue you're describing.

However it works as expected when I remove the http_proxy parameters...

**Comment by llaurent** [comment]
can also reproduce this behavior with irb (ruby 2.1.5p273)

**Comment by llaurent** [comment]
oh in the end it looks like ruby doesn't use https_proxy from env at all. so the workaround i was suggesting is wrong.

**Comment by sergiopatino** [comment]
any updates on this? we need to have no_proxy accept wild cards.

**Comment by acqant** [comment]
+1

**Comment by acqant** [comment]
network wild card would be great too!  10.*

**Comment by adamedx** [comment]
I agree we need a consistency in proxy configuration across all Chef tools -- this is very confusing for users.

**Comment by adamedx** [comment]
ccing @fnichol who is looking into proxy issues.

**Comment by jgrenoble** [comment]
+1, very confusing and causes some odd behavior.

**Comment by lamont-granquist** [comment]
tagging @jkeiser since he's currently in proxy-land.

**Comment by joshoohaah** [comment]
just had this issue pop up for me today as well.  Found out after investigation it was due to the `no_proxy` only taking in full hostname, and not doing wildcards.  This causes many issues when you are in a proxied environment..and you need your machine to talk to your chef server..but then also other boxes in that same environment.  we can't have/update the `no_proxy` for every single full hostname or IP address that a machine could potentially want to talk to on our environment.  It would be nice if either the client.rb could inherit the `no_proxy` from the environment variable and use it that way.

**Comment by jeremiahsnapp** [comment]
I assume this ruby feature request is relevant.

https://bugs.ruby-lang.org/issues/10251

**Comment by aktarali** [comment]
@adamedx Hi Bud, Hope you are well. I have hit this issue on a client site today. Have set the following on client.rb but its overridden by ENV variable set in /etc/profile it seems:
no_proxy "dpcom-dop0fd1d1.coronisite.local"

Have no_proxy on my /etc/profile for the chef-server too but keep seeing:
[2015-12-16T11:21:44+00:00] ERROR: 502 "Proxy Error ( A connection with the server cannot be established.  )"
[2015-12-16T11:21:44+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)


Cheers
Ali.

**Comment by petewest** [comment]
Net::HTTP already tries to discover proxy settings from the environment. By Chef implementing its own proxy discovery mechanism you end up having to conform to both standards (e.g.: Chef's fnmatch needs '*.local' and URI::Generic#find_proxy's regexp--and many other systems--need 'local') when implementing no_proxy lists. 

Chef's priority for checking ENV is NO_PROXY then no_proxy, whereas URI::Generic is the other way round so that introduces another layer of confusion.

Is there any advantage in Chef dealing with proxy settings instead of letting Net::HTTP do it?

**Comment by aktarali** [comment]
The weird thing is, no_proxy is set via /etc/profile and its still ignored.
It doesn't actually use it. So, I had to set it in /etc/chef/client.rb and
knife.rb to get it to recognise it.

What so damn annoying is, docker, chef, yum etc all have this problem. They
ignore system wide ENV var's!



On 5 January 2016 at 12:05, petewest <notifications@github.com> wrote:

> Net::HTTP already tries to discover proxy settings from the environment.
> By Chef implementing its own proxy discovery mechanism you end up having to
> conform to both standards (e.g.: Chef's fnmatch needs '*.local' and
> URI::Generic#find_proxy's regexp--and many other systems--need 'local')
> when implementing no_proxy lists.
>
> Chef's priority for checking ENV is NO_PROXY then no_proxy, whereas
> URI::Generic is the other way round so that introduces another layer of
> confusion.
>
> Is there any advantage in Chef dealing with proxy settings instead of
> letting Net::HTTP do it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chef/chef/issues/3293#issuecomment-168982582>.
>



-- 
Ali Aktar
Zircon Solutions LTD

**Comment by thenoid** [comment]
yeah little redonkulous that chef doesn't respect the system no_proxy variable/standard.  Please +1 this/fix it as it's currently causing issues with our environment.

**Comment by smith** [comment]
#4348 might fix this. Could you try it out for your use case or add specs that verify the expected behavior?

**Comment by joshoohaah** [comment]
the suggested fix #4348 will not handle the cases of `no_proxy` (as referenced as well by the comments/code changes in that bug-fix).

**Comment by charlesjohnson** [comment]
#4727 should allow for no_proxy wildcards.

**Comment by lamont-granquist** [comment]
looks like #4727 should have fixed this.

please open a new issue if that is incorrect.
