### ISSUE TITLE
Chef push cook book  SHA256 key

### ISSUE THREAD

**Issue by jai11** [chef/chef#3302]
I want to configure chef push on my client . For that I downloaded push-jobs cook book .
in that i have configured 
default['push_jobs']['package_url']      = 'https://opscode-private-chef.s3.amazonaws.com/el/6/x86_64/opscode-push-jobs-client-1.1.5-1.el6.x86_64.rpm'
default['push_jobs']['package_checksum'] = '08d1e8058e2ca1290f71f9c2ba6684cecfc2099d'

I have taken check sum from "http://downloads.chef.io/push-jobs-client/redhat/" 

but when i run (sudo chef-client -r "recipe[push-jobs]") on chef node it is giving me error as :-1: 

Checksum on resource (08d1e8) does not match checksum on content (f5e6be)

From where I can get SHA256 key as on site it is SHA1 ?

**Comment by manderson26** [comment]
You are correct, there is a mismatch between what we provide from the web page and what we require in the cookbook. I've added an issue to track this to the push-jobs cookbook, since this really is a cookbook problem.

**Comment by jai11** [comment]
Thanks ,
Can i get the link of issue

**Comment by jai11** [comment]
Thanks,

For time being can you please let me know what is the SHA256 for this rpm .

That will be of great help.
