### ISSUE TITLE
RuntimeError: File files/default/plugins/README does not exist for cookbook ohai

### ISSUE THREAD

**Issue by Matthew-Ellison** [chef/chef#3303]
### Version:
Using chef-solo 12.2 or 12.3

### Environment: [Details about the environment such as the Operating System, cookbook details, etc...]
ubuntu 14.04
chef-solo 12.3
application cookbook : nginx
wrapper cookbook : mycompany-nginx

### Scenario:
Using nginx wrapper cookbook to install nginx(nginx cookbook). This works with Test Kitchen(Vagrant driver and chef-solo provisioner).  When trying to use with Packer(amazon-ebs builder, chef-solo provisioner), I get the following 

```
amazon-ebs: [2015-04-27T12:22:41+00:00] ERROR: remote_directory[/etc/chef/ohai_plugins for cookbook ohai] (ohai::default line 33) had an error: RuntimeError: cookbook_file[/etc/chef/ohai_plugins/README] (dynamically defined) had an error: RuntimeError: File files/default/plugins/README does not exist for cookbook ohai
```

### Steps to Reproduce:
Install nginx 2.7.6 cookbook via a wrapper cookbook with Packer 0.7.5(amazon-ebs builder, chef-solo provisioner)

### Expected Result:
Expecting nginx to be installed, since it's working in Test Kitchen. 

### Actual Result:
I get the following error 
```
amazon-ebs: [2015-04-27T12:22:41+00:00] ERROR: remote_directory[/etc/chef/ohai_plugins for cookbook ohai] (ohai::default line 33) had an error: RuntimeError: cookbook_file[/etc/chef/ohai_plugins/README] (dynamically defined) had an error: RuntimeError: File files/default/plugins/README does not exist for cookbook ohai
```
Note the source  and destination dirs exist.

```
-rw-r--r-- 1 ubuntu ubuntu 49 Apr 29 15:08 /tmp/packer-chef-solo/cookbooks-1/ohai-2.0.1/files/default/plugins/README
```

```
drwxr-xr-x 2 root root 4096 Apr 29 15:08 /etc/chef/ohai_plugins
```

When I log into the packer node and run with chef-solo manually, I get the same error.

```
sudo chef-solo -l debug -c /tmp/packer-chef-solo/solo.rb -j /tmp/packer-chef-solo/node.json
```

```
$ cat /tmp/packer-chef-solo/solo.rb

cookbook_path 	["/tmp/packer-chef-solo/cookbooks-0","/tmp/packer-chef-solo/cookbooks-1"]

```

```
cat /tmp/packer-chef-solo/node.json
{
  "run_list": [
    "recipe[mycompnay-nginx::default]"
  ]
```

**Comment by Matthew-Ellison** [comment]
I added some puts to debug the  get_filename function in /opt/chef/embedded/apps/chef/lib/chef/cookbook/file_system_file_vendor.rb. I see  the ohai version number is omitted in the path to source file 

```
----------------------- /tmp/packer-chef-solo/cookbooks-0/ohai/files/default/plugins/README -------------------
----------------------- /tmp/packer-chef-solo/cookbooks-1/ohai/files/default/plugins/README -------------------
```

**Comment by Matthew-Ellison** [comment]
I ran kitchen converge in debug mode, and noticed it was consolidating the cookbooks(wrapper and application) in one directory.  I did this to my repo also , and now it's working.

**Comment by kareiva** [comment]
What about the case you have to store your wrapper and upstream cookbooks in separate repositories (i.e. upstream cookbook is managed by berkshelf)? I am also affected by this by using chef-solo alone.

**Comment by axsuul** [comment]
Another issue could be Berkshelf isn't loaded properly

**Comment by crmckenzie** [comment]
I'm sorry--what is the actual fix here? I'm having this issue and I don't know how to solve it.

**Comment by Matthew-Ellison** [comment]
This fix was to put all cookbooks into one directory. Although not a best practice.  The provisioners section of packer template.json file looked like this 

```
"provisioners": [{
    "type": "chef-solo",
    "cookbook_paths": ["/Users/username/cookbooks"],
    "run_list": [
      "recipe[apt::default]",
       "recipe[mycompany-nginx::default]"
    ]
  }],
```
It could very well be Berkshelf isn't loaded properly, and I'm curious if anyone can elaborate.

**Comment by crmckenzie** [comment]
Cookbooks are all in the same dir and it's still not working for me. :(

**Comment by crmckenzie** [comment]
It appears that the issue is that cookbook_file is unaware that the directory the cookbook is in contains a version. The code in [file_system_watcher](https://github.com/chef/chef/blob/master/lib/chef/cookbook/file_system_file_vendor.rb) does correctly identify berkshelf cookbook _root_ paths, but it does not correctly identify the cookbook path because the cookbook path is "name+version" and file_system_watcher expects "name."
