### ISSUE TITLE
Need Config/CLI options to move interval+splay sleep to end of client loop

### ISSUE THREAD

**Issue by swapnilborade** [chef/chef#3305]
Chef Client 12 does not Fork Chef instance to converge when running under daemon mode. It runs after specified interval of 1800 seconds but not as soon as we start service
With Chef Client 11. It runs as soon as we start chef-client service
We were having chef 11.4.4 on node. We did chef client 12 upgrade by installing omnibus package

We have chef-client running as daemon every 30 mins.

We are expecting chef-client to run as soon as we bootstrap node or start service but it seems that with chef 12 client it is not Forking chef instance to converge as soon as we start service. I have captured debug logs 

Below is example with Chef 12

Example:

```text
chef-client -d -c /etc/chef/client.rb -P /var/run/chef/client.pid -l debug -L /tmp/chef.log

# Logfile created on 2015-04-29 12:27:13 -0400 by logger.rb/44203
[2015-04-29T12:27:13-04:00] INFO: Daemonizing..
[2015-04-29T12:27:13-04:00] INFO: Forked, in 7978. Privileges: 0 0
[2015-04-29T12:27:13-04:00] DEBUG: Sleeping for 1800 seconds
```

I think we should be expecting  it to Fork chef instance to converge and should not wait for 1800 seconds

 issue seems to be at logic https://github.com/chef/chef/blob/12.2.1/lib/chef/application/client.rb#L384

It should run immediately for first time in daemonized mode

**Comment by swapnilborade** [comment]
Can you please confirm if this is bug on Line 384 or is it intended behavior
https://github.com/chef/chef/blob/12.2.1/lib/chef/application/client.rb#L384

Changing @signal = test_signal to @signal= IMMEDIATE_RUN_SIGNAL fixes issue

**Comment by swapnilborade** [comment]
Please ignore my earlier comment. Change suggested causes chef-client frequently  But issue seems to be at logic https://github.com/chef/chef/blob/12.2.1/lib/chef/application/client.rb#L384

It should run immediately for first time in demonized mode

**Comment by lamont-granquist** [comment]
That was changed deliberately since in other bootstrapping cases immediately launching a chef-client run when the daemon is configured can wind up with yum or dpkg locks getting held by the background chef-client and later commands in the kickstart/jumpstart/whatever bootstrapping script failing due to conflicts with the rapidly started chef-client run.

So, the behavior is deliberate and not a bug.  A config flag / command-line flag could be introduced to move the interval later.  Otherwise you should force the chef-client run that you're expecting to see first.

**Comment by diasjorge** [comment]
@lamont-granquist do you have any suggestion into how to force the first run? We've had a runit process doing the provisioning when the machine boots.

**Comment by elmic11111** [comment]
Ran into this same problem. I added a line to do --once for the initial run and then ran the Daemonizing command. I understand the concern about it interfering with the yum process possibility. My suggestion is that you have the default be that it waits the interval, and have a flag that can be set for people like me who would prefer it to run immediately and then follow the normal Daemonize process.

**Comment by swapnilborade** [comment]
Thanks . For time being, I have added it to RHEL Upstart and it works fine.
It makes sense to add Config/CLI option

**Comment by charlesjohnson** [comment]
"Otherwise you should force the chef-client run that you're expecting to see first." What's the flag to force this run?

**Comment by Es-Paul** [comment]
@charlesjohnson  There is no flag for this at the moment.
They are suggesting that we run the chef-client command manually once, to get our expected initial run (as per version 11.x) and then it daemonize it.

**Comment by pumpkineater** [comment]
@lamont-granquist  This affects chef-client service restarts too. I consider it a bug, and I'm surprised not more people have noticed the problems with this new (and broken) behavior. I would appreciate a solution to avoid ugly workarounds in various places.

**Comment by lamont-granquist** [comment]
I explained why its not a bug.

**Comment by charlesjohnson** [comment]
Understood that this is the current expected behavior, but also understood that the expected behavior is not the desired behavior for many users.

@lamont-granquist, what do we think should the way forward be in this case?

**Comment by lamont-granquist** [comment]
The updated subject line is correct, need an option so that users can configure it the way they need to.

**Comment by jeremiahsnapp** [comment]
I'd like to make sure that it is clearly understood that you can immediately start a manual chef-client run even though the chef-client service is waiting (sleeping) for the specified interval to pass.

In order for this to work the interval and splay must not be configured in the `client.rb` file. Instead they must be configured as options in the command that is run to start the chef-client service. This is the way the `chef-client` cookbook configures the chef-client service.

**Comment by charlesjohnson** [comment]
After re-reading the thread, I'm now confused.

I need another breakdown of desired behavior vs. actual behavior, if someone will indulge me.

**Comment by elmic11111** [comment]
For me the desire behavior is to be able to pass a flag that on start the chef client will damnonize, run immediately the flow the normal damenon time cycle.

**Comment by Es-Paul** [comment]
@charlesjohnson I updated my bootstrap scripts to accommodate the actual behavior so I don't need any changes.  This modified behavior simply caught me off guard.
What people want as the desired behavior is:
- Give the chef-client a command line flag to have it perform a chef run immediately, then daemonize (like Chef 11 did).

**Comment by Raboo** [comment]
I disagree. The default behavior should be that it runs on start., That it runs when a node reboots.. There should be an option for it to not run at start instead..
chef-client run at daemon start have been default behavior for a long time and there hasn't been any real or big problems. So why pretend there is one?
If you install chef from a package it kills the chef-client service anyway and it doesn't start the service automatically from what I've noticed (at least it does so with the .deb packages).. So why would there be apt/yum locks?

Even if there is yum locks.. If you were willing to wait 30 minutes for the first run, then you can wait until the first run fails cause of yum locks and then + 30 minutes.
So the people affected by yum locks needs to wait 31 minutes instead of 30..

Lets be realistic, without any poll or so I believe that most people would want and expect the old behavior as default.. Please make the old behavior default and give a settings/option to those 10 people with yum lock issues..

**Comment by charlesjohnson** [comment]
I'm with @Raboo here. When I start a daemon, I expect it to run immediately, not 30 minutes from now. 

This delayed behavior isn't intuitive, and it's not in keeping with a reasonable person's expectation of how the tool should work.

**Comment by Raboo** [comment]
I noticed one thing with chef 12..
```
[2015-09-25T10:16:12+02:00] INFO: Forking chef instance to converge...
[2015-09-25T10:16:12+02:00] WARN: Chef client 27066 is running, will wait for it to finish and then run.
```
Another proof that this isn't a problem since chef-client doesn't allow multiple chef workers to run simultaneously.

**Comment by charlesjohnson** [comment]
@Raboo Chef-client running over itself isn't the issue, it's other processes that might fail due to Chef-client keeping a yum lock, etc. As @lamont-granquist said above:
> That was changed deliberately since in other bootstrapping cases immediately launching a chef-client run when the daemon is configured can wind up with yum or dpkg locks getting held by the background chef-client and later commands in the kickstart/jumpstart/whatever bootstrapping script failing due to conflicts with the rapidly started chef-client run.

**Comment by wjordan** [comment]
Another workaround is to send the `USR1` signal to the daemonized chef-client process, which will trigger it to converge immediately. For example, modifying the command-line in the original issue to converge immediately on startup could be done by appending a command using the [kill](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/kill.html) utility:
```
# Start daemonized chef-client and converge immediately
chef-client -d -c /etc/chef/client.rb -P /var/run/chef/client.pid -l debug -L /tmp/chef.log && \
  kill -s USR1 $(cat /var/run/chef/client.pid)
```
Hope this helps!

**Comment by elmic11111** [comment]
I really don't know why this has been an issue for so long. It seems fairly basic to setup a flag to tell the system to wait the period before running the first time for bootstrap situations, and the default be to run immediately. I get that some people bootstrap and that the original behavior caused them issues, but breaking it for the rest of us isn't the right answer. Adding an option to handle bootstrap situations is.

**Comment by himagn** [comment]
Please add the flag. This behavioral change seems like a proverbial sledgehammer to kill a race condition fly.
