### ISSUE TITLE
'knife TYPE list some-non-option' should error

### ISSUE THREAD

**Issue by jblaine** [chef/chef#3310]
Chef 12.0.3 (ChefDK current, aka 0.40)

```
[@rcf-cm-master:/rcf-cm-master/htdocs/chef-misc] 1 $ knife user list noodle
admin
...
jblaine
...
$
```

The non-option argument 'noodle' should trigger a usage error.

**Comment by stevendanna** [comment]
This is true of all `knife TYPE list` commands. I've updated the bug title appropriately.
