### ISSUE TITLE
Knife fails to bootstrap remote running dropbear ssh daemon

### ISSUE THREAD

**Issue by JustinAiken** [chef/chef#3312]
Old Jira: [CHEF-3293](https://tickets.opscode.com/browse/CHEF-3293)

This still seems to be the case... I have a dropbear device that I can't get chef'd up w/ either chef-zero or chef-solo - it gives me the same error as reported in the old ticket.

**Comment by lamont-granquist** [comment]
We probably need more information on how to make net-ssh work with dropbear and/or net-ssh needs to get fixed to work with dropbear and we need to pick up the fixes.  We're unlikely to allocate the resources to test against a dropbear ssh daemon internally.
