### ISSUE TITLE
Error executing action `upgrade` on resource 'package[curl]'

### ISSUE THREAD

**Issue by KonstantinSlyshkov** [chef/chef#3313]
I'm using ubuntu 14.04 and docker 1.32  
The main idea I'm deploying chef via docker. The problem is, when I started up the project. Everything seems to be working fine. Then I've an error. 

Error executing action `upgrade` on resource 'package[curl]'
STDERR: Attempt to access disallowed key ' ' in a restricted hash at /usr/share/perl5/Debconf/Config.pm line 43, <DEBCONF_CONFIG> chunk 1.
------------------------------------
To me docker works fine, just a problem of chef, cannot cook following cookbooks and recepies. It's not the solely one error but they are interconnected.
I have access to repo's curl package. And it's can be uploaded as well. I was trying to google it but i guess it's not a problem with sources list. The following ubuntu repos sources.list:

deb http://ua.archive.ubuntu.com/ubuntu/ trusty main restricted
deb-src http://ua.archive.ubuntu.com/ubuntu/ trusty main restricted

deb http://ua.archive.ubuntu.com/ubuntu/ trusty-updates main restricted
deb-src http://ua.archive.ubuntu.com/ubuntu/ trusty-updates main restricted

deb http://ua.archive.ubuntu.com/ubuntu/ trusty universe
deb-src http://ua.archive.ubuntu.com/ubuntu/ trusty universe
deb http://ua.archive.ubuntu.com/ubuntu/ trusty-updates universe 
deb-src http://ua.archive.ubuntu.com/ubuntu/ trusty-updates universe

deb http://ua.archive.ubuntu.com/ubuntu/ trusty multiverse
deb-src http://ua.archive.ubuntu.com/ubuntu/ trusty multiverse
deb http://ua.archive.ubuntu.com/ubuntu/ trusty-updates multiverse
deb-src http://ua.archive.ubuntu.com/ubuntu/ trusty-updates multiverse

deb http://ua.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse
deb-src http://ua.archive.ubuntu.com/ubuntu/ trusty-backports main restricted universe multiverse

deb http://security.ubuntu.com/ubuntu trusty-security main restricted
deb-src http://security.ubuntu.com/ubuntu trusty-security main restricted
deb http://security.ubuntu.com/ubuntu trusty-security universe 
deb-src http://security.ubuntu.com/ubuntu trusty-security universe
deb http://security.ubuntu.com/ubuntu trusty-security multiverse
deb-src http://security.ubuntu.com/ubuntu trusty-security multiverse

deb http://extras.ubuntu.com/ubuntu trusty main
deb-src http://extras.ubuntu.com/ubuntu trusty main

---------------------------------
So any ideas what is happening, or just a thought where to look. would be grateful for any assistance.

**Comment by lamont-granquist** [comment]
That error message makes no sense at all (it a perl error, not ruby), so you're going to have to give a lot more context of the error message and the stack trace that you're getting from chef.

**Comment by KonstantinSlyshkov** [comment]
Hi there, I have resolved the problem. It would sound, kinda weird. Docker couldn't start at 3.18, 3.16 kernel(as well as any older then 13). At any version of docker starting from 1.3.0. Despite all the facts that docker "has no problem" with backward and further compatability(linux kernels). It is able to start only with 13.0.49.(I have absolutely no idea why). Oh, and actually all my programs independent from kernel too. I will post the reason why it was failing, if I'll found it. :)
