### ISSUE TITLE
Travis fails on Master

### ISSUE THREAD

**Issue by btm** [chef/chef#3323]
```rake spec``` only runs the functional and unit tests, which is what [is configured](https://github.com/chef/chef/blob/master/.travis.yml#L15) to happen for pull requests. However we run ```rake spec:all``` for branches on Travis, which includes the integration tests.

You can see the history of branch builds here: https://travis-ci.org/chef/chef/builds

It looks like the started failing after #3160 was merged @danielsdeleo, but that build didn't fail O_o: https://travis-ci.org/chef/chef/jobs/56784455

I don't understand right now why we aren't getting any notifications for this. I happened to notice the "build failing" badge in the [README.md](https://github.com/chef/chef/blob/master/README.md).

**Comment by danielsdeleo** [comment]
@btm I think the travis machines don't have IPv6 at all or it's not available to us in the container or something. Funny enough, the last 4 commits from the last time I did a `git pull` are @juliandunn disabling containers (i.e., the `sudo: false` thing in travis). Not clear whether he ultimately succeeded (guess not?). Anyway, we can reach out to travis and see if they can enable IPv6 in the containers, until then, it'd be nice if we can detect if IPv6 is not available and skip those tests.

**Comment by danielsdeleo** [comment]
As for the kitchen tests, I dunno what's up. Kitchen is failing to set up the EC2 instance. Maybe a Kitchen or kitchen-c2 issue? https://s3.amazonaws.com/archive.travis-ci.org/jobs/60869993/log.txt

**Comment by danielsdeleo** [comment]
Relevant log snippet (sorry for ansi spam)

```
[36m       Unable to fetch credentials: Expected(200) <=> Actual(404 Not Found)
[0m
[36m       Instance <i-a9d8055e> requested.[0m
[36m       EC2 instance <i-a9d8055e> created.[0m
[36m       Waited 0/300 for instance <i-a9d8055e> to become ready.[0m
[36m       Waited 5/300 for instance <i-a9d8055e> to become ready.[0m
[36m       Waited 10/300 for instance <i-a9d8055e> to become ready.[0m
[31m>>>>>> ------Exception-------[0m
[31m>>>>>> Class: Kitchen::ActionFailed[0m
[31m>>>>>> Message: Failed to complete #create action: [The instance ID 'i-a9d8055e' does not exist][0m
[31m>>>>>> ----------------------[0m
[31m>>>>>> Please see .kitchen/logs/kitchen.log for more details[0m
[31m>>>>>> Also try running `kitchen diagnose --all` for configuration
[0m
```

**Comment by juliandunn** [comment]
@danielsdeleo It didn't work to disable IPv6 in Travis so I reverted the change after discussing with @jdmundrawala. I think the failure is something else.
