### ISSUE TITLE
rpm upgrade of chef-full omnibus rpm package kills symlinks in /usr/bin OpenSuse / SLES

### ISSUE THREAD

**Issue by runningman84** [chef/chef#3330]
This issue is still breaking SuSE systems:
https://tickets.opscode.com/browse/CHEF-3022

If you upgrade a chef rpm on any SuSE system all chef symlinks in /usr/bin disappear.

**Comment by lamont-granquist** [comment]
Which version of chef were you upgrading from?   If you have a sufficiently old version of chef installed, the fact that you're upgrading to 12.3.0 won't matter if the old version you're upgrading is buggy.

**Comment by runningman84** [comment]
We were upgrading from chef 10.x, But I suppose that a newer chef rpm would have the same problem because you only check for redhat systems:
``
`if [ ! -f /etc/redhat-release -a ! -f /etc/fedora-release -a ! -f /etc/system-release ]; then
``
you should add /etc/SuSE-release like
``
`if [ ! -f /etc/redhat-release -a ! -f /etc/fedora-release -a ! -f /etc/system-release -a ! -f /etc/SuSE-release ]; then
``
in here:
https://github.com/chef/omnibus-chef/blob/master/package-scripts/chef/postrm

**Comment by lamont-granquist** [comment]
Heh, thanks for tracking down the bug.  Can you submit a PR to do exactly that, then we can give you credit?

That's a really old one then, surprised that no other SuSE user has ever reported it...
