### ISSUE TITLE
Unshare Specific Supermarket Cookbook Versions

### ISSUE THREAD

**Issue by sean-horn** [chef/chef#3334]
As a Supermarket user, I would like to be able to do the following to get rid of undesired versions of cookbooks I own.

    knife cookbook site unshare COOKBOOK VERSION

**Comment by sean-horn** [comment]
Also covered in https://github.com/chef/supermarket/issues/954

**Comment by lamont-granquist** [comment]
This probably has the same problem that yanking gems has.  If someone has their environment locked  in Berksfile.lock and regardless of how you feel about it the cookbook is working for them, and you then yank it, then you potentially break their production deployments (suddenly, at 3am on a friday night their local time, etc).

You might mark a cookbook so that it will not depsolve and be offered in the universe but it must still download to not break existing Berksfile.locks.

**Comment by flaccid** [comment]
The real use case is that the cookbook was uploaded incorrect in some way despite properly tagging and releasing it with the cookbook's github repo. We're not trying to reverse a release but rather fix the publishing of one that was done incorrectly. knife is a complete PITA here. It would be much nicer to trigger release in supermarket with your github cookbook or bring back UI upload of some kind.

**Comment by smurawski** [comment]
This functionality - depending on what supermarket offers, should really be packaged as a "chef" command in ChefDK.

**Comment by lamont-granquist** [comment]
I'd also argue that the packaging issue can be best addressed by bumping the patch number and pushing again.  You don't want to be ninja editing your artifacts.  Consider them read-only just like erlang variables.

**Comment by coderanger** [comment]
Immutable versions and being able to yank are orthogonal. I also disagree this should be in chef-dk as `knife cookbook site` is in core Chef and it would be odd to have the upload command and the yank command be totally different.

**Comment by nathenharvey** [comment]
I'm :+1: on allowing a user to remove a specific version of a cookbook from the Supermarket.

As it is, you can yank an entire cookbook which also has the potential to cause many issues.  Allowing the yanking of a specific version is, arguably, less likely to cause an issue than yanking the entire cookbook.

Today, you *can* yank a version, you just have to yank the entire cookbook and then subsequently upload only the versions you want.

On chef vs. knife, I definitely wouldn't recommend having share and remove be in separate tools.  We'd probably need to implement all of the `cookbook site` functionality into `chef` first and have a deprecation period for those commands in `knife`

**Comment by thommay** [comment]
I'm :-1: here, for the reasons that Lamont elucidated in https://github.com/chef/supermarket/issues/954#issuecomment-144823021 . You should roll forwards on cookbook versions, and then disallow broken ones from being solved to. But you should never remove. (The corollary to this is that we should cease allowing cookbooks to be removed from the supermarket, too)

**Comment by coderanger** [comment]
Broken is one thing, but stuff like accidentally putting passwords in a cookbook and then posting it we should offer a way to yank those artifacts. Rubygems and PyPI have the same policy. Once a version is uploaded you can't change it or upload new content there, but you can yank it.

**Comment by vinyar** [comment]
Bumping this as we have users running into this.
Chef allows `knife cookbook delete COOKBOOK VERSION (options)`

Expectation:
Supermarket should offer similar functionality - ability to delete a specific version of the cookbook

Here is a use case: 
Private supermarket that is kept in sync with supermarket.chef.io. Somehow during the sync, last version of every public cookbook is botched. Now your internal supermarket has no way of rolling forward short of nuking every corrupted cookbook to remove the last version.

**Comment by coderanger** [comment]
Not sure why you re-opened this. This isn't the Supermarket repo and has nothing to do with the feature being available in Supermarket.

**Comment by robbkidd** [comment]
Yep. Deleting a particular version of a cookbook from Supermarket is chef/supermarket#954 as Sean linked at the start of this issue. Still a debate. But better tracked there.

**Comment by vinyar** [comment]
my bad, I'll bump it in the appropriate spot 👍
