### ISSUE TITLE
Chef Server enters 100% cpu loop from GUI when cookbook from environment constraints does not exist

### ISSUE THREAD

**Issue by marcusn** [chef/chef#3338]
Produce:
  Add environment constraint cookbook x = 0.5.0 (where x version 0.5.0 does not exist)
  Add x to runlist on a node on that environment
  View runlist i UI

**Comment by smith** [comment]
Thanks for reporting this! Could you please reopen it on chef/chef-manage-issues, since it's specific to Chef Manage and not Chef client? Also, could you please specify the browser and OS version. I've been unable to reproduce this on Chrome/Mac.
