### ISSUE TITLE
windows_package resource keeps installing files

### ISSUE THREAD

**Issue by bigbam505** [chef/chef#3341]
I have a cookbook to install an msi file, pretty straight forward as below:

```

dd_agent_installer = ::File.join(Chef::Config[:file_cache_path], 'dd-agent.msi')

remote_file dd_agent_installer do
  source node['datadog']['installer']['url']
  checksum node['datadog']['installer']['checksum']
end

windows_package node['datadog']['installer']['name'] do
  action :install
  source dd_agent_installer
  version node['datadog']['installer']['version']
  installer_type :msi
end

```

I have this running on 12 nodes currently and 11 of them work as expected. The 12th node tries to  install the datadog agent every chef run.  I am not sure why this occurs however I have tried everything and still are not closer to solving the issue.  The application runs on the host fine, has a record in the uninstall program list and running the installer tries to repair the installation.  Not sure if anyone else is having this issue with windows_package on chef 12.2.1.

Also here are my attributes for the example above
```
default['datadog']['installer']['name'] = 'Datadog Agent'
default['datadog']['installer']['url'] = 'https://s3.amazonaws.com/ddagent-windows-stable/ddagent-cli-5.3.1.msi'
default['datadog']['installer']['version'] = '5.3.1.0'
default['datadog']['installer']['checksum'] = '543d3a726570cfccd84597c52ceed4ca795076cf65f2cee82625d7dabadf934d'
```

And here is a powershell query for the datadog agent

```
PS C:\> gwmi win32_product | ? { $_.Name -Like "Datadog Agent" }

IdentifyingNumber : {67A802D8-4E70-4F19-9931-4F6014286930}
Name              : Datadog Agent
Vendor            : Datadog Inc.
Version           : 5.3.1.0
Caption           : Datadog Agent

```

**Comment by jdmundrawala** [comment]
what if you don't specify version. I suspect it will crash: https://github.com/chef/chef/issues/3316 ?

**Comment by bigbam505** [comment]
Actually it ran the chef-client run and was successful without trying to install the msi again.  Not sure why this would be the case, and especially not sure why it was only this host.

**Comment by btm** [comment]
Are you using the windows cookbook?

**Comment by bigbam505** [comment]
No I am running chef 12.2.1 so the windows cookbook is not needed for the windows_package resource anymore.  I believe the cookbook is still used by other cookbooks so It might be on disk so not sure if it could still be used.

**Comment by bigbam505** [comment]
@btm Actually from what I have discovered one of my cookbooks pulled in the windows cookbook and is using it which is why this is working currently.  I realized this when I was running test-kitchen by itself without the windows cookbook.  The initial run would be successful and the second one would complain 
with something like:

```
No version specified, and no candidate version available for #{package name}
```

Hope this helps a little

**Comment by lamont-granquist** [comment]
@jaym do you know if this has been fixed or if its probably still an issue?

**Comment by jaym** [comment]
it was fixed in https://github.com/chef/chef/pull/3317
