### ISSUE TITLE
Data Bag Items must contain a Hash or Mash! Chef-Client 12, Windows Server 2012r2

### ISSUE THREAD

**Issue by Infectsoldier** [chef/chef#3347]
Hello. I am trying to use data_bag_item with Chef solo 12 and Vagrant on Windows Server 2012r2

I am getting the following error when provisioning a chef node:
"Data Bag Items must contain a Hash or Mash!"

I have verified that the data bag name domain.json exists and there is an id within the data bag with the same name. Also the data bag path is set correctly in the Vagrant file.

{
"id": "domain",
  "username": "user",
  "password": "pwd"
}

Issue on Chef client from 12.0.1 to 12.3 . Does not occur when downgrading to 11.18.0

**Comment by scopenco** [comment]
I have the same situation. on Chef 11 provision is ok.

**Comment by adamedx** [comment]
@scopenco, @Infectsoldier, can you configure vagrant to use local mode (i.e. chef-zero)? You should get expected behavior then.

**Comment by lamont-granquist** [comment]
chef solo doesn't support data bags, so you must have some cookbook like chef-solo-search which implements some kind of workaround which has broken with Chef 12.

chef solo is also deprecated, you should definitely be using chef-zero
