### ISSUE TITLE
Cron resource symbols for weekday are broken (regression)

### ISSUE THREAD

**Issue by mynamewastaken** [chef/chef#3351]
I tried to create a cron job:

```
cron 'clean_db_archive_logs' do
  minute '0'
  hour '6'
  weekday :tuesday
  user 'postgres'
  command '/var/lib/postgresql/backup.py'
end
```

and knife'd it up to our chef server. I ran chef-client and the run failed with the following error:

```
================================================================================
Error executing action `create` on resource 'cron[clean_db_archive_logs]'
================================================================================

Chef::Exceptions::Cron
----------------------
Error updating state of clean_db_archive_logs, exit: 1

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/<cb>/recipes/<recipe>

 42: cron 'clean_db_archive_logs' do
 43:   minute '0'
 44:   hour '6'
 45:   weekday :tuesday
 46:   user 'postgres'
 [..]
 49:   command '/var/lib/postgresql/backup.py'
 50: end

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/<cb>/recipes/<recipe>:42:in `from_file'

cron("clean_db_archive_logs") do
  action :create
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  minute "0"
  hour "6"
  day "*"
  month "*"
  weekday :tuesday
  command "/var/lib/postgresql/backup.py"
  user "postgres"
  [...]
  declared_type :cron
  cookbook_name "<cb>"
  recipe_name "<recipe>"
end
```

I then changed `weekday :tuesday` to `weekday '2'`, re-knife'd and re-ran chef-client (ver 12.0.3), which succeeded. It appears that the cron resource doesn't like mixed input for the times that a cron job will run.

**Comment by tas50** [comment]
@Vasu1105 Let's make sure that this issue is resolved in both the cron and cron_d resources.

**Comment by Vasu1105** [comment]
Sure @tas50 we will take care of it. Currently Antima from MSys is working on this. So I was trying to assign her this issue but I can't see her in our Assignees list. And it mistakenly got assigned to me. Informed this to @btm. And we will definitely will take care of cron_d too. Thank you.

**Comment by tas50** [comment]
@Vasu1105 You should probably take a look at the cron_d weekday property. It does validation using a native property instead of a crazy set_or_return mess like cron. You'd have to coerce the symbols to strings and then the validation should do the rest. It was something I meant to do for chef 16, but never got around to do doing it.
