### ISSUE TITLE
Provide Socks Proxy Ability for chef-client

### ISSUE THREAD

**Issue by sean-horn** [chef/chef#3352]
Zendesk 4180

As an enterprise customer, I would like the ability to send and receive chef-client proxy traffic through a SOCKS proxy, similarly to the existing chef-client HTTP proxy abilities.

**Comment by sean-horn** [comment]
The workflow while chef-client doesn't support SOCKS.

1. bootstrap the node by setting up an ssh tunnel and tricking chef-client to talk to it by changing the chef_server_url in client.rb to point to an ssh tunnel on localhost 
2. Once bootstrapped, revert the client.rb and make it point to our enterprise chef server 
3. Install the socksify gem with 'sudo /opt/chef/embedded/bin/gem install socksify' 
4. Run: 'sudo /opt/chef/embedded/bin/socksify_ruby <sockshost> <port> /usr/bin/chef-client'

socksify captures all tcp connections from chef-client and forwards them to our socks proxy.

**Comment by lamont-granquist** [comment]
Needs to get escalated through @adamedx if this is a priority and needs to get on a backlog somewhere.

**Comment by kovyrin** [comment]
This may be relevant: https://github.com/eligible/knife-bastion
