### ISSUE TITLE
why chef-client issue SIGHUP at start time

### ISSUE THREAD

**Issue by cheyang** [chef/chef#3353]
We are running "bash -c set -o pipefail;chef-client -l info|tee /tmp/chef-client.log" to do some configurations. We noticed that it issues SIGHUP at the chef-client start time, but not every time. I'm wondering why it issues SIGHUP sometimes. I'm sure we didn't do it in our recipes.

**Comment by cheyang** [comment]
Is it because the fork will issue SIGHUP?

**Comment by lamont-granquist** [comment]
Random guess would be that some child process gets a SIGHUP and it gets send to the whole process group.  You most likely need to create a new process group leader at some point if you want to prevent that (although I thought we did that inside of mixlib-shellout but my memory is fussy on that, and its possible that not everything that chef launches uses mixlib-shellout -- particularly until very recently we still had some stuff still calling popen4).

**Comment by lamont-granquist** [comment]
Not sure what to do with this one without more information.
