### ISSUE TITLE
eliminate discrepancy between old knife subcommands and ChefFS subcommands

### ISSUE THREAD

**Issue by thommay** [chef/chef#3368]
Some old functionality may need to be added to ChefFS to support this.
We should then rewrite all the old commands to use ChefFS.

**Comment by lamont-granquist** [comment]
Some functionality also likely needs to get dropped like a bad transmission...

Thinking specifically of the merging of multiple cookbooks in cookbook_paths with arrays.  That likely needs to go away--trying to make sense of that in the ChefFS world is likely madness and its been deprecated for years.

**Comment by tas50** [comment]
I'm going to close this one out at the point. It hasn't been a priority to fix this for the last 6 years and that's probably not going to change.
