### ISSUE TITLE
remote_file resource needs three forward slashes for local files (file:///) instead of two (file://) to function

### ISSUE THREAD

**Issue by vinyar** [chef/chef#3371]
__Example:__
This code will break (note two //):
```ruby
  remote_file "/etc/opscode/#{file_name}" do
    source "file://etc/staging/#{file_name}"
  end
```
The working code is (note three ///):
```ruby
  remote_file "/etc/opscode/#{file_name}" do
    source "file:///etc/staging/#{file_name}"
  end
```

Expected behavior:
Local URI should work with two forward slashes

**Comment by btm** [comment]
There are supposed to be three slashes. ```file://etc/staging/foo``` means "get me the staging/foo file on the host named etc" which isn't what you mean. The hostname can be omitted to infer the path is on the local machine.

These are both valid:
```
file://hostname/path/to/file
file:///path/to/file
```

http://tools.ietf.org/html/rfc1738#section-3.10

```
As a special case, <host> can be the string "localhost" or the empty
   string; this is interpreted as `the machine from which the URL is
   being interpreted
```

**Comment by btm** [comment]
Microsoft agrees on this syntax: http://blogs.msdn.com/b/ie/archive/2006/12/06/file-uris-in-windows.aspx

#1346 has historical related discussion on the topic in relation to Windows UNC paths.

**Comment by vinyar** [comment]
thanks. I'll keep the doc bug open and nuke this one.
