### ISSUE TITLE
Configuring the AutoStart options for the Windows service

### ISSUE THREAD

**Issue by glasschef** [chef/chef#3384]
It would be nice to be able to specify AutoStart or DelayedAutoStart here:

https://github.com/chef/chef/blob/master/lib/chef/application/windows_service_manager.rb#L122

**Comment by spuder** [comment]
Possibly related? 

https://github.com/chef/chef/issues/2814

**Comment by lamont-granquist** [comment]
Might be fixed by some of the PRs referenced off of #2814?

**Comment by thommay** [comment]
ping @chef/client-windows - did this get rolled up in the aforementioned bug, or is this still outstanding?

**Comment by ksubrama** [comment]
Yes - the :delayed_start boolean flag was added there.
