### ISSUE TITLE
Setting the directory owner to non-existing user does not fail

### ISSUE THREAD

**Issue by kohlerm** [chef/chef#3390]
See also 
https://github.com/kohlerm/chef_dir_owner

Creating a directory in a first run:

directory "/tmp/foo/bar" do
  #owner "foobar"
  recursive true
end

Then set the owner to a non-existent user

directory "/tmp/foo/bar" do
  owner "foobar"
  recursive true
end

-> works fine, also it should fail

Tested on Opensuse 13.2 (Chef: 12.0.3) and SLES 11 SP3 (Chef: 11.6.0)

**Comment by lamont-granquist** [comment]
You don't even have to create it first.  Owner is simply not validated.

**Comment by kohlerm** [comment]
As far as I remember it would fail, in case the directory did not exist, but I have to verify that.
