### ISSUE TITLE
cannot load such file -- ruby-wmi

### ISSUE THREAD

**Issue by aarsan** [chef/chef#3395]
I realize there was another ticket opened for this that has already been resolved but I am getting this error on a fresh Windows 2k12r2 install with the 12.3.0 client version. This is what I get when I try running chef-client -l info:

Compiling Cookbooks...

================================================================================
Recipe Compile Error in c:/chef/cache/cookbooks/windows/libraries/registry_helper.rb
================================================================================

LoadError
---------
cannot load such file -- ruby-wmi

Cookbook Trace:
---------------
  c:/chef/cache/cookbooks/windows/libraries/registry_helper.rb:27:in `<top (required)>'

Relevant File Content:
----------------------
c:/chef/cache/cookbooks/windows/libraries/registry_helper.rb:

 20:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 21:  # See the License for the specific language governing permissions and
 22:  # limitations under the License.
 23:  #
 24:
 25:  if RUBY_PLATFORM =~ /mswin|mingw32|windows/
 26:    require 'win32/registry'
 27>>   require 'ruby-wmi'
 28:  end
 29:
 30:  module Windows
 31:    module RegistryHelper
 32:
 33:      @@native_registry_constant = ENV['PROCESSOR_ARCHITEW6432'] == 'AMD64' ? 0x0100 : 0x0200
 34:
 35:      def get_hive_name(path)
 36:        Chef::Log.debug("Resolving registry shortcuts to full names")

Once I install ruby-wmi by hand, it's fine.

**Comment by jdmundrawala** [comment]
you probably have an old version of the windows cookbook

**Comment by aarsan** [comment]
I am using the Azure Chef Extension to bootstrap, which gets the latest version of the client. I'm not sure which step in this process the Windows cookbook is retrieved. I have no control over that. If that's the case, would this be an issue with the way Azure is deploying the client?

**Comment by aarsan** [comment]
Ok, I see that in the cookbook I was trying to run, it was locked to an older version of the windows cookbook. thanks.
