### ISSUE TITLE
Knife Bootstrap Improperly Detecting Existence of Chef Installation

### ISSUE THREAD

**Issue by sempervictus** [chef/chef#3408]
When bootstrapping a fresh Ubuntu 14.04 node with chef, the _exists_ function improperly returns true and the boostrap script believes there is a chef-client executable in place:

```
Connecting to 10.1.1.2
10.1.1.2 -----> Existing Chef installation detected
10.1.1.2 Starting first Chef Client run...
10.1.1.2 sh: 333: chef-client: not found
```

Initial attempts to replace the script with bashisms such as _if [[ ! -f ..._ all of which result in the bootstrap script either constantly believing that a chef client is available, or always downloading a new one. I haven't spent any time digging the history here past current open issues in GH, but i assume someone has already beaten their head against the wall with this.

**Comment by patcon** [comment]
Ditto on debian 7.8

**Comment by kristianm** [comment]
Got same error on Debian 8.1 with chef-12.4.0.rc.2. 
Works ok when using chef-12.3.0.

**Comment by ksubrama** [comment]
@mcquin ran into this internally and her issue was with the `if ! exists /usr/bin/chef-client` line at https://github.com/chef/chef/blob/master/lib/chef/knife/bootstrap/templates/chef-full.erb#L169 . She gets `exists: command not found`.

This is shell magic that I don't wield - so I'm going to follow the advice at https://github.com/chef/omnibus-chef/blob/master/package-scripts/chef/postinst#L8 and ping reviewers of #2877
@btm @lamont-granquist @thommay @juliandunn @danielsdeleo

**Comment by btm** [comment]
@mcquin what's your platform? what does `sh --version` return?

**Comment by lamont-granquist** [comment]
We're probably missing this:

https://github.com/chef/opscode-omnitruck/blob/master/views/install.sh.erb#L36-L44

**Comment by juliandunn** [comment]
@lamont-granquist no that's here: https://github.com/chef/chef/blob/master/lib/chef/knife/bootstrap/templates/chef-full.erb#L14-L21

**Comment by thommay** [comment]
@lamont-granquist the one in https://github.com/chef/chef/blob/master/lib/chef/knife/bootstrap/templates/chef-full.erb#L14-L22 is very slightly different, but i can't see why it'd cause this problem

**Comment by lamont-granquist** [comment]
Well you can use `if test -f "/usr/bin/chef-client"` and reverse the conditional.  You don't have to check through the path so that the `command -v` check is unnecessary and you can avoid the `if !` completely.

**Comment by lamont-granquist** [comment]
@thommay `&> /dev/null` is a bash-ism, that needs to be fixed to `>/dev/null 2>&1`
