### ISSUE TITLE
Replace knife cookbook site with knife supermarket

### ISSUE THREAD

**Issue by echohack** [chef/chef#3413]
See https://github.com/chef/knife-supermarket/issues/6

Knife cookbook site currently works off supermarket, but it's also a little strange that this is the name of the command. Shouldn't this command be "knife supermarket"?

**Comment by lamont-granquist** [comment]
Yes, knife supermarket should get pulled into core, and knife cookbook site and knife supermarket should work the same way.

**Comment by mwrock** [comment]
knife-supermarket gem is depricated and has moved to chef - https://github.com/chef-boneyard/knife-supermarket/pull/33
