### ISSUE TITLE
Behavior change in 12.4: nameless resources

### ISSUE THREAD

**Issue by coderanger** [chef/chef#3416]
As part of @jkeiser's new DSL work, the behavior of a resource with no name `file { ... }` has changed. I'm hesitant to call this a compat break because the old behavior was probably a bug for everyone except me. In the current release that code would result in a resource with name set to `nil`, in master that is a syntax error. This is because the old `method_missing` code uses `args[0]` as the name, which is `nil` if there are no args. The new code has real methods defined for each resource in the DSL and those require a name parameter.

I'm cool with fixing this on the Poise side of things if we can find a non-terrible way to do that, and if we agree the old `nil` behavior was a bug and not an API compat break to change it.

**Comment by coderanger** [comment]
A solution for this on the Chef side would be to make the DSL stub methods have a default value for the name parameter (probably `nil`) and then in `declare_resource` check that the name is something valid (not `nil` or `''`) and raise an exception if it isn't. Kind of roundabout though, and this will probably only benefit me (I override `declare_resource` in this case and it fills in a default name in some situations). An alternative would be for Poise to create overrides for every DSL stub method, which seems tricky and still gross.

**Comment by coderanger** [comment]
Another advantage of doing the error check in `declare_resource` is we could show a nicer error message, more like the runtime error display that shows the snippet of recipe code, rather than a standard `SyntaxError`. There is already a check in `ResourceBuilder` for `name.nil?` so that's a thing too.

**Comment by jkeiser** [comment]
You mean we allowed resource name to default to nil?  That seems like an
unintended compat change.

What I really want is to involve the resource in its own construction, I.e.
implement build_resource in the resource class and let it take whatever
arguments it wants.

**Comment by coderanger** [comment]
Yes, I use this in nested resources to allow for simpler syntax:

```ruby
application 'foo' do
  bundle_install do
    deployment true
  end
end
```

In that case `bundle_install` gets a default name, but this is now broken because the DSL stub method for it requires a name. I created #3417 with a potential fix on the Chef side to restore the old behavior.

**Comment by lamont-granquist** [comment]
this got fixed and merged
