### ISSUE TITLE
Issue in chef-server-ctl reconfigure

### ISSUE THREAD

**Issue by sridhar-ars** [chef/chef#3421]
Hi Guys,

I am trying to install chef server 12.0.3 in Rhel ec2 instance of type m3.medium. Facing few issues while doing chef-server-ctl reconfigure step.

   * execute[create_database_opscode-pgsql] action run

      ================================================================================
      Error executing action `run` on resource 'execute[create_database_opscode-pgsql]'
      ================================================================================

      Mixlib::ShellOut::ShellCommandFailed
      ------------------------------------
      Expected process to exit with [0], but received '1'
      ---- Begin output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
      STDOUT:
      STDERR: createdb: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
      ---- End output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
      Ran createdb --template template0 --encoding UTF-8 opscode-pgsql returned 1

      Resource Declaration:
      ---------------------
      # In /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/providers/pg_database.rb

       13:   execute "create_database_#{new_resource.database}" do
       14:     command createdb_command
       15:     user node['private_chef']['postgresql']['username']
       16:     not_if {database_exist?}
       17:     retries 30
       18:   end
       19: end

      Compiled Resource:
      ------------------
      # Declared in /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/providers/pg_database.rb:13:in `block in class_from_file'

      execute("create_database_opscode-pgsql") do
        action "run"
        retries 30
        retry_delay 2
        default_guard_interpreter :execute
        command "createdb --template template0 --encoding UTF-8 opscode-pgsql"
        backup 5
        returns 0
        user "opscode-pgsql"
        declared_type :execute
        cookbook_name "private-chef"
        not_if { #code block }
      end

    ================================================================================
    Error executing action `create` on resource 'private-chef_pg_database[opscode-pgsql]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    execute[create_database_opscode-pgsql] (/opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/providers/pg_database.rb line 13) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    ---- Begin output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
    STDOUT:
    STDERR: createdb: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
    ---- End output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
    Ran createdb --template template0 --encoding UTF-8 opscode-pgsql returned 1

    Resource Declaration:
    ---------------------
    # In /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/postgresql.rb

    127:   private_chef_pg_database "opscode-pgsql"
    128:   include_recipe "private-chef::erchef_database"

    Compiled Resource:
    ------------------
    # Declared in /opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/recipes/postgresql.rb:127:in `from_file'

    private_chef_pg_database("opscode-pgsql") do
      action :create
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :private_chef_pg_database
      cookbook_name "private-chef"
      recipe_name "postgresql"
      database "opscode-pgsql"
      template "template0"
      encoding "UTF-8"
    end

Running handlers:
[2015-05-24T22:43:30-04:00] ERROR: Running exception handlers
Running handlers complete
[2015-05-24T22:43:30-04:00] ERROR: Exception handlers complete
[2015-05-24T22:43:30-04:00] FATAL: Stacktrace dumped to /opt/opscode/embedded/cookbooks/cache/chef-stacktrace.out
Chef Client failed. 8 resources updated in 89.528052175 seconds
[2015-05-24T22:43:30-04:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: private-chef_pg_database[opscode-pgsql] (private-chef::postgresql line 127) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[create_database_opscode-pgsql] (/opt/opscode/embedded/cookbooks/cache/cookbooks/private-chef/providers/pg_database.rb line 13) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
STDOUT:
STDERR: createdb: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
---- End output of createdb --template template0 --encoding UTF-8 opscode-pgsql ----
Ran createdb --template template0 --encoding UTF-8 opscode-pgsql returned 1

Kindly advice me on this issue and steps to overcome the same.

Regards
Sridhar

**Comment by ranjib** [comment]
closing this. its being tracked on chef-server repo
