### ISSUE TITLE
Unstable environment change

### ISSUE THREAD

**Issue by asurak** [chef/chef#3422]
I have seen couple time that when issuing 

```
knife node environment set <node> <env>
```

I actually get

```
<node>:
  chef_environment: <env>
```

but if couple minutes later I try to see the environment of the node, it is not the new but the former one, although the command returns success. This mainly happens when I move more than 1 node in a short period of time. It means that I cannot rely on Chef Server actually moving the node to a new environment and need some logic on top to verify that the performed was actually done.

```
knife -v -> Chef: 12.0.3
chef-server 12.0.0
```

I have observed this issue also with chef-server 11.x and older knife. There is no one else communicating with the Chef Server and changing the environment at that time.

**Comment by ranjib** [comment]
@asurak can you describe how you are checking if the node is in the correct environment? `knife node show` will be always accurate, while knife search will give correct result with some delay

**Comment by thommay** [comment]
This generally only occurs when a chef-client run is happening at the same time you edit the node; when the client run completes it will save the node back, which can overwrite your changes. 
https://github.com/chef/chef-rfc/blob/master/rfc045-node_state_separation.md is designed to fix this class of problem.

**Comment by asurak** [comment]
Thank you @thommay . I think we have actually discussed that some time ago in Paris in person :)
I see that the RFC got accepted in March. Any idea when it might find its way into the GA?

**Comment by thommay** [comment]
Ah yes, we did! It needs some resources devoted to it, both in server and in client; I'd love to say this year but ...

**Comment by tas50** [comment]
I'm going to close this issue in favor of the RFC that was linked above. Implementing the RFC would have a lot of benefits, one being the fix to this issue.
