### ISSUE TITLE
Resource 'execute' hangs on Windows for some executable files

### ISSUE THREAD

**Issue by olivierlemasle** [chef/chef#3423]
I use Chef Solo 12.3.0.
I try to run the "ASP .NET MVC 4" installer on Windows 2008 R1 (64-bit), but the command never returns.

I'm not using the `windows` cookbook.
My recipe contains the following code:

```ruby
remote_file "#{Chef::Config[:file_cache_path]}/AspNetMVC4Setup.exe" do
  source 'http://download.microsoft.com/download/2/F/6/2F63CCD8-9288-4CC8-B58C-81D109F8F5A3/AspNetMVC4Setup.exe'
  checksum '66dbb6573ab653f8a722821155e9572db42226e8d187fd4a814f101d8bcba67e'
end
execute 'AspNetMVC4Setup.exe /q' do
  cwd Chef::Config[:file_cache_path]
end
```
The installation is ok, but the process hangs, and the end of the rest of the recipe is not executed (actually Chef freezes).

Logs end with:

```
==> web: [2015-05-25T05:59:55-07:00] DEBUG: Creating directory C:/var/chef/cache/remote_file
==> web: [2015-05-25T05:59:56-07:00] DEBUG: touching /var/chef/cache/AspNetMVC4Setup.exe to create it
==> web: 
==> web: [2015-05-25T05:59:56-07:00] INFO: remote_file[/var/chef/cache/AspNetMVC4Setup.exe] created file /var/chef/cache/AspNetMVC4Setup.exe
==> web: [2015-05-25T05:59:56-07:00] DEBUG: calculating checksum of C:/Users/vagrant/AppData/Local/Temp/chef-rest20150525-2268-icimbk to compare with 
==> web: [2015-05-25T05:59:56-07:00] INFO: remote_file[/var/chef/cache/AspNetMVC4Setup.exe] updated file contents /var/chef/cache/AspNetMVC4Setup.exe
==> web: [2015-05-25T05:59:58-07:00] DEBUG: selinux utilities can not be found. Skipping selinux permission fixup.
==> web: 
==> web: [2015-05-25T05:59:58-07:00] INFO: Processing execute[AspNetMVC4Setup.exe /q] action run (amysta::web line 29)
==> web: [2015-05-25T05:59:58-07:00] DEBUG: providers for generic execute resource enabled on node include: [Chef::Provider::Execute]
==> web: [2015-05-25T05:59:58-07:00] DEBUG: providers that refused resource execute[AspNetMVC4Setup.exe /q] were: []
==> web: [2015-05-25T05:59:58-07:00] DEBUG: providers that support resource execute[AspNetMVC4Setup.exe /q] include: [Chef::Provider::Execute]
==> web: [2015-05-25T05:59:58-07:00] DEBUG: providers that survived replacement include: [Chef::Provider::Execute]
```

But if I try manually (i.e. in a `cmd` console, with the same user account), the same command:

    AspNetMVC4Setup.exe /q

it returns (with exit code 0) in a few seconds.

Actually, my first attempt was to use the `windows` cookbook, with the code:

```ruby
windows_package 'Microsoft ASP.NET MVC 4' do
  source 'http://download.microsoft.com/download/2/F/6/2F63CCD8-9288-4CC8-B58C-81D109F8F5A3/AspNetMVC4Setup.exe'
  installer_type :custom
  options "/q"
end
```
It executed the command

    start "" /wait "\var\chef\cache\AspNetMVC4Setup.exe" /q & exit %%ERRORCODE%%

But there was exactly the same problem: it never returned when the command was passed by Chef; it returned in a few seconds when I tried manually in a `cmd` console.

Where is the difference?
Is there something to do with running a 32-bit Chef on a 64-bit Windows Server?

**Comment by olivierlemasle** [comment]
That's finally not a Chef issue.
The problem was encountered only when Chef was used with Vagrant (in fact, it was related to the powershell script Vagrant uses to elevate privileges for Chef). And there is no issue with Windows Server 2008 R2.

**Comment by sneal** [comment]
@olivierlemasle I'm tracking down a similar problem. Do you know what the issue was with Vagrant? I can reproduce it locally when running Chef directly on the guest and not through Vagrant.

**Comment by bsamek** [comment]
@sneal Did you ever figure out the problem? I'm having a similar issue running Chef with Packer to install Silverlight. No matter what approach I take (pure chef, chef calls batch script, chef runs powershell), Chef freezes if Silverlight installs successfully.

**Comment by olivierlemasle** [comment]
@sneal @bsamek FWIW, in my case, the issue was related to https://github.com/mitchellh/vagrant/blob/master/plugins/communicators/winrm/scripts/elevated_shell.ps1.erb
I can't remember the details (and I did not find the root cause anyway) but I did not reproduce the issue when using Chef directly.

**Comment by sneal** [comment]
@bsamek I'm not sure at this point, but one issue I had was running Chef via the Packer provisioner. The short answer is that Chef run via Packer is not run through a scheduled task (like Vagrant is), so some things won't install properly like Windows Updates. I had to resort to using the Packer PowerShell provisioner __running elevated__ to execute Chef.
