### ISSUE TITLE
chef-server-ctl org-create command

### ISSUE THREAD

**Issue by sdarwin** [chef/chef#3424]
a minor suggestion for the installation documentation found at https://docs.chef.io/install_server.html 

notice this line:
chef-server-ctl org-create chef Chef Software, Inc. --association_user stevedanno --filename /path/to/chef-validator.pem

should chef-validator.pem be modelled after ORGANIZATION-validator.pem?  It seemed necessary,  during testing. 

chef-validator.pem is ambiguous because it says "chef" which is expected everywhere, chef-client, chef-solo, chef-validator.    A clearer example:

chef-server-ctl org-create acme "Acme Corporation" --association_user stevedanno --filename /path/to/acme-validator.pem

and also change:
chef-server-ctl org-create short_name full_organization_name --association_user user_name --filename FILE_NAME
to 
chef-server-ctl org-create short_name full_organization_name --association_user user_name --filename ORGANIZATION-validator.pem

**Comment by thommay** [comment]
Thanks for your contribution, but please file this at https://github.com/chef/chef-docs/issues.
