### ISSUE TITLE
Chef::HTTP::StreamHandler debug output fills up log files

### ISSUE THREAD

**Issue by jwmint1** [chef/chef#3430]
We're updating some scripts from Chef10 to Chef11 and we see the following lines taking up >>90% of our log files:
[2015-05-26T12:33:35-07:00] DEBUG: Chef::HTTP::StreamHandler calling Chef::HTTP::ValidateContentLength::ContentLengthCounter#handle_chunk
[2015-05-26T12:33:35-07:00] DEBUG: Chef::HTTP::StreamHandler calling Chef::HTTP::Decompressor::NoopInflater#handle_chunk
This makes it significantly harder to debug our own code. I realize that this is debug output but it isn't really adding any value.  We'd appreciate it if these debug lines could be removed.
Additional:
- Related to Issue #3186.
- Our code provisions dynamically created instances, so file download is an essential component of our Chef runs.

**Comment by fletchowns** [comment]
I would love to see this logging removed! Or at least reduced to some summary lines after every x amount of chunks.

**Comment by midhunkrishna** [comment]
👍  Definitely required. This debug log is definitely useless in vast amounts. I need to actually search for this to understand what this is doing, not descriptive at all. I agree to @jwmint1.
