### ISSUE TITLE
Chef cron resource produces broken crontab entries for CentOS 6.6

### ISSUE THREAD

**Issue by VanTanev** [chef/chef#3445]
CentOS's crontab requires that each entry end with a newline character. 
However, when crontab entries are added for a new user, the last entry will not have a newline character.

The result is that the last crontab entry setup by Chef will not be parsed and executed

This can be fixed by manually editing the user's crontab and adding one blank line after the last crontab entry.
This will fix the problem, and subsequent runs of chef that add or delete entries will work as expected.

Based on: http://askubuntu.com/a/23337

### Version:
Chef: 12.3.0

### Environment:
CentOS release 6.6 (Final)

### Scenario:
Create crontab entries for a new user

### Steps to Reproduce:
```
user 'deploy' do
  comment 'Deploy user'
  home '/home/deploy'
  shell '/bin/bash'

  supports(:managed_home => true)
end

group 'deploy' do
  members ['deploy']
end

cron "[deploy-cron]first_cron" do
  user "deploy"
  hour "8-19"
  command "date > /tmp/first-crontab-entry 2>&1"
end

cron "[deploy-cron]second_cron" do
  user "deploy"
  hour "8-19"
  command "date > /tmp/second-crontab-entry 2>&1"
end
```

### Expected Result:
Have both crontab entries execute, creating the two files in `/tmp`

### Actual Result:
Crontab does not actually work.

**Comment by jblaine** [comment]
Yikes. This would have royally screwed us. Luckily we don't use the `cron` resource to install our chef-client crontab jobs.

**Comment by thommay** [comment]
I can't reproduce this. With your recipe above, on centos 6.6 and chef 12.3
```
[vagrant@default-centos-66 ~]$ sudo crontab -l -u deploy
# Chef Name: [deploy-cron]first_cron
* 8-19 * * * date > /tmp/first-crontab-entry 2>&1
# Chef Name: [deploy-cron]second_cron
* 8-19 * * * date > /tmp/second-crontab-entry 2>&1
```
results in:
```
[vagrant@default-centos-66 ~]$ ls -l /tmp/*tab*
-rw-r--r--. 1 deploy deploy 29 Jun  6 14:15 /tmp/first-crontab-entry
-rw-r--r--. 1 deploy deploy 29 Jun  6 14:15 /tmp/second-crontab-entry
[vagrant@default-centos-66 ~]$ cat /tmp/*cront*
Sat Jun  6 14:15:01 UTC 2015
Sat Jun  6 14:15:01 UTC 2015
```

**Comment by VanTanev** [comment]
I cannot reproduce it anymore either, and am thus closing the issue.

This was encountered in during slightly hectic time when we were rolling out a new deployment, and I _think_ I didn't imagine it, but rerunning our recipes on a clean machine does not exhibit the problem. 

A cursory glance at the code also suggests no reason the bug should've appeared. If we happen upon it again, I will try to recreate it properly before reopening the ticket.

Thank you for your time.
