### ISSUE TITLE
ConflictError: Unable to activate cheffish-1.2, because chef-zero-3.2.1 conflicts with chef-zero (~>4.2)

### ISSUE THREAD

**Issue by eliassal** [chef/chef#3452]
Hi, I followed instructions to setup "chef-provisioning-azure" which went fine, I got a copy of a very basic VM creation on Azure from the url 
http://stuartpreston.net/2015/02/chef-provisioning-with-microsoft-azure-part-1/#comment-595
the azure-provisioning-test.rb 
As I have a full chef ubuntu server, I tried the following statements

chef-client --local ./azure-provisioning-test.rb 
and
chef-apply ./azure-provisioning-test.rb
I get the following exceptions:

starting chef client, version 12.0.3
..Running Handlers
.....Error Running exception handlers
Error: Unable to activate cheffish-1.2, because chef-zero-3.2.1 conflicts with chef-zero (~> 4.2)
FATAL: Gem::ConflictError: Unable to activate cheffish-1.2, because chef-zero-3.2.1 conflicts with chef-zero (~>4.2)
How this can be resolved?
Thanks

**Comment by DarshanMurthy** [comment]
Hey could you solve the problem? Even I'm facing the same.

**Comment by lamont-granquist** [comment]
pretty sure this got solved awhile ago
