### ISSUE TITLE
Chef 12.3.0 and chef_gem install issues behind firewall

### ISSUE THREAD

**Issue by avsh** [chef/chef#3456]
My node doesn't have an internet access at all.

I'm trying to install gems from local file system but the setup fails due to gem binary wants to connect to rubygems.org

The command 
`/opt/chef/embedded/bin/gem install /var/chef/cache/gems/mail-2.6.3.gem -q --no-rdoc --no-ri -v "2.6.3"`
fails to run.

I run the command locally and it returned the warning

`WARNING:  Unable to pull data from 'https://rubygems.org/': no such name (https://rubygems.org/specs.4.8.gz)`

I assume it shouldn't try to connect to rubygems if `source` is in use.

**Comment by pburkholder** [comment]
Hi @avsh 

Use the attribute `clear_sources true` to remove rubygems.org from the sources list.

The old default behavior is it only add the 'source' to the list of available sources, and then use rubygems.org as the last one on the list.

The docs have only recently been updated, https://docs.chef.io/resource_gem_package.html,
and see also https://github.com/chef/chef/pull/2867

HTH,

Peter

**Comment by avsh** [comment]
Hi @pburkholder 

Thank you for the info. 

I've tried to use the ``clear_sources true`` as you advised but it fails.

Here is my code

```ruby
chef_gem 'mail' do
  compile_time true if respond_to?(:compile_time)
  source "#{::Chef::Config[:file_cache_path]}/gems/mail-2.6.3.gem"
  clear_sources true
end
```

and Chef failed because my squid didn't allow it to make outbound connection

```sh
192.168.35.199     Mixlib::ShellOut::ShellCommandFailed
192.168.35.199     ------------------------------------
192.168.35.199     Expected process to exit with [0], but received '1'
192.168.35.199     ---- Begin output of /opt/chef/embedded/bin/gem install /var/chef/cache/gems/mail-2.6.3.gem -q --no-rdoc --no-ri -v "2.6.3" ----
192.168.35.199     STDOUT:
192.168.35.199     STDERR: ERROR:  While executing gem ... (Net::HTTPServerException)
192.168.35.199         403 "Forbidden"
192.168.35.199     ---- End output of /opt/chef/embedded/bin/gem install /var/chef/cache/gems/mail-2.6.3.gem -q --no-rdoc --no-ri -v "2.6.3" ----
192.168.35.199     Ran /opt/chef/embedded/bin/gem install /var/chef/cache/gems/mail-2.6.3.gem -q --no-rdoc --no-ri -v "2.6.3" returned 1
```

**Comment by thommay** [comment]
So whilst `clear_sources` removes the sources line from the gem incantation, we also need to tell gems not to use any of the sources configured by default

**Comment by richardowen** [comment]
+1

This is stopping chef_gem from working if you don't have access to rubygems.org. If I execute this it works:

/opt/chef/embedded/bin/gem install path_to_gem -q --no-rdoc --no-ri -v "gem_version" --local

It is exactly the same command that chef_gem runs but with the addition of --local. Perhaps that should be added when source is specified?

**Comment by cixelsyd** [comment]
+1 I just hit this.  chef_gem needs to add "--local" to the command line when "source" is specified.

**Comment by cixelsyd** [comment]
Workaround is to add this:
options '--local'

to your chef_gem resource.  Note the inclusion of the dashes.

**Comment by lamont-granquist** [comment]
So basically:

if package_name looks like a filepath
and File.exist?(path) is true
we should add --local for the user so that it doesn't asplode.

**Comment by lamont-granquist** [comment]
Here's prior art on how we do the "looks like a filepath" thing for rpm_package and dpkg_package:

https://github.com/chef/chef/blob/master/lib/chef/mixin/get_source_from_package.rb

**Comment by lamont-granquist** [comment]
And actually gem_package is already trying to do that:

https://github.com/chef/chef/blob/master/lib/chef/provider/package/rubygems.rb#L24

So just make that work by adding --local

**Comment by loganmeetsworld** [comment]
We have decided to revert the change made in #4847 in order to put the domain in line with the way that rubygems has set it. If you want to have this behavior without a connection, you will have to append `--local` in the options.

**Comment by loganmeetsworld** [comment]
We have decided to revert the use of the `local` domain and use the default domain set by rubygems, `remote`. If the a user desires the behavior above without a connection, they must append `--local` as an option as it will not be the set default.

**Comment by moos3** [comment]
the --local breaks all dependancies. If your gem needs to go to rubygems to get additional packages, it will not go out and fetch them. This was a breaking change and should be reverted.

**Comment by vinyar** [comment]
So, the use case here is that we're installing one gem from local source, but want the rest to come from the internet. 

This might be a bug in the way `-b` switch operates, because that was the default. Shouldn't it look local first, then remote?

**Comment by bby-bishopclark** [comment]
options --local in chef_gem will likely not help:  the code checking for dependencies runs too early to be modified that way, if I understand https://serverfault.com/questions/868996/chef-13-and-inhibiting-bundler-network-requests#comment1119265_869604 right.

**Comment by lamont-granquist** [comment]
I think this is fixed in chef_gem now.  It is very old at any rate.

The gem metadata issue was hijacking this issue, and I no longer recommend gem metadata for anything.  It was mostly intended for poise and chef-sugar and those uses cases are no longer relevant and based on the issues surrounding it, nobody else should be using gem metadata (also maybe chef-vault, which also is planned on being incorporated into core chef).  The bugs in gem metadata are unlikely to ever get fixed.
