### ISSUE TITLE
Windows Bootstrap Fail

### ISSUE THREAD

**Issue by Infydevops** [chef/chef#3464]
Windows bootstrap fails with below error :
-------------------------------------------------------------------------------------------
knife bootstrap windows ssh IP_Address -r  'role[java]' -x Domain/user -i ~/.ssh/id_rsa

Bootstrapping Chef on IP_Address
WARNING: Failed to connect to <IP Address> -- Errno::ETIMEDOUT: A connection at
tempt failed because the connected party did not properly respond after a period
of time, or established connection failed because connected host has failed to
respond. - connect(2)
--------------------------------------------------------------------------------------------------------

**Comment by lamont-granquist** [comment]
This needs to be filed against the knife-windows project:  

https://github.com/chef/knife-windows/issues/new

It also will likely need more details.
