### ISSUE TITLE
ruby_blocks no longer fail if block returns false

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#3465]
I'm not sure when this changed, but this used to fail:

```
ruby_block 'test' do
  block do
    false
  end
end
```

As did:

```
ruby_block 'test' do
  block do
    # can't return from a Proc...
    next false
  end
end
```

But neither of those fail now... you can still raise/fail to force a failure, but that's not quite what you want - you want a way to express the resource failed now just throw a stackstrace in the middle of it.

**Comment by ranjib** [comment]
@jaymzh you have any idea which version it used to fail? i cant find any code path which could lead to failure in current git logs :0(

**Comment by jaymzh** [comment]
@ranjib Hmm. Try Chef 10 - we jumped straight from 10 to 12 in December, so we're still shaking out fun bugs introduced in 11 :)

**Comment by lamont-granquist** [comment]
What's the difference between the raise in the middle of the proc and having the resource fail and raise?  The current behavior seems less surprising to newbies (just because a ruby_block has a last statement that is false doesn't necessarily mean that i want my chef-client run to explode, whereas requiring me to raise keeps things very clear and unsurprising).  I suspect we had a bug on this and fixed it at some point.

**Comment by jaymzh** [comment]
How do you figure? `ruby_blocks` are ruby-blocks. Just like any other resource. If I return false from a LWRP or only_if, they fail, right?

**Comment by lamont-granquist** [comment]
`only_if { false }` doesn't really 'fail' though.  it doesn't do the action because that's what the boolean means.  LWRP actions also don't fail if they return false, the return value is ignored.

**Comment by danielsdeleo** [comment]
I can't reproduce the failure on a block implicitly returning false using chef-solo 10.34.6.

```ruby
ruby_block "wut" do
  block { false }
end
```

```
bundle exec chef-solo -c solo.rb -o wtf        
[2015-09-14T12:40:11-07:00] INFO: *** Chef 10.34.6 ***
[2015-09-14T12:40:14-07:00] WARN: Run List override has been provided.
[2015-09-14T12:40:14-07:00] WARN: Original Run List: []
[2015-09-14T12:40:14-07:00] WARN: Overridden Run List: [recipe[wtf]]
[2015-09-14T12:40:14-07:00] INFO: Run List is [recipe[wtf]]
[2015-09-14T12:40:14-07:00] INFO: Run List expands to [wtf]
[2015-09-14T12:40:14-07:00] INFO: Starting Chef Run for lorentz.local
[2015-09-14T12:40:14-07:00] INFO: Running start handlers
[2015-09-14T12:40:14-07:00] INFO: Start handlers complete.
[2015-09-14T12:40:14-07:00] INFO: Processing ruby_block[wut] action create (wtf::default line 7)
[2015-09-14T12:40:14-07:00] INFO: ruby_block[wut] called
[2015-09-14T12:40:14-07:00] INFO: Chef Run complete in 0.002567 seconds
[2015-09-14T12:40:14-07:00] INFO: Running report handlers
[2015-09-14T12:40:14-07:00] INFO: Report handlers complete
```

**Comment by danielsdeleo** [comment]
I _do_ get a LocalJumpError for an explicit `return`:

```
================================================================================
Error executing action `create` on resource 'ruby_block[wut]'
================================================================================

LocalJumpError
--------------
unexpected return

Cookbook Trace:
---------------
/private/tmp/fuuuuuu/wtf/recipes/default.rb:10:in `block (2 levels) in from_file'

Resource Declaration:
---------------------
# In /private/tmp/fuuuuuu/wtf/recipes/default.rb

  7: ruby_block "wut" do
  8:   #block { return false }
  9:   block do
 10:     return false
 11:   end
 12: end

```

But what kind of blocks allow explicit return and which do not are controlled by the upstream. The last time this changed that I know of was Ruby 1.9, which is now EOL, so there's no going back.
