### ISSUE TITLE
--with-orgs subcommand does not work with chef-server-ctl user-show

### ISSUE THREAD

**Issue by GoodMirek** [chef/chef#3466]
Following command works well:
$ sudo chef-server-ctl user-show --verbose
INFO: Using configuration from /etc/opscode/pivotal.rb
chefadmin: https://127.0.0.1/users/chefadmin
pivotal:   https://127.0.0.1/users/pivotal
wstation1: https://127.0.0.1/users/wstation1

At the same time the next command fails:
$ sudo chef-server-ctl user-show --verbose --with-orgs
INFO: Using configuration from /etc/opscode/pivotal.rb
INFO: HTTP Request Returned 404 Object Not Found: error
ERROR: The object you are looking for could not be found
Response: Could not find user organizations

Without --verbose parameter it fails as well:
$ sudo chef-server-ctl user-show --with-orgs
ERROR: The object you are looking for could not be found
Response: Could not find user organizations

$ uname -a
Linux ip-172-31-61-75 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ cat /proc/version
Linux version 3.13.0-48-generic (buildd@orlo) (gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1) ) #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015
$ dpkg --list chef-server-core
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name              Version       Architecture  Description
+++-=================-=============-=============-=======================================
ii  chef-server-core  12.0.8-1      amd64         The full stack of chef-server

Please let me know if any other information is necessary.

**Comment by thommay** [comment]
Please can you file this issue at https://github.com/chef/chef-server/issues ?
