### ISSUE TITLE
Multipackage issues with Yum

### ISSUE THREAD

**Issue by coderanger** [chef/chef#3476]
This is somewhat a stream of consciousness on what I think is a bug. The repro case should be doing a multi-package install with yum where the first package in the array is already up to date and the second is not, but the candidate version of the second package is the same as the first.

Walk through of what I think the problem is:

Take an example of `package ['one', 'two']` where `one` is already installed and `two` is not. `current_version_array` is set to `['1.2.3', nil]` reflecting that `one` is installed and `two` is not.

`Chef::Provider::Package#action_install` is what calls `install_package` for the specific implementation to override. It passes in `package_names_for_targets` and `versions_for_targets`. Both of these are already cleaned so packages that are up-to-date do not appear in them. So we call `install_package(['two'], ['1.2.3'])`. `1.2.3` is the candidate version in this case.

This gets passed down to `Chef::Provider::Package:Yum#install_remote_package`. Inside there we build the command string to pass to yum. It does this by looping over the given names and versions. The problem is when it tries to [skip packages that are already up to date](https://github.com/chef/chef/blob/master/lib/chef/provider/package/yum.rb#L1228). We already did this filtering in `package_names_for_targets` but it is using the array index from the filtered names/versions against the unfiltered `current_version_array`. So in this case `names[0] == 'two'` but `current_version_array[0] == '1.2.3'` which corresponds to `one`. In the case where `one` and `two` should be the same version (easy repro, any package and its `-devel`) this means that it skips `two` thinking it is already up to date.

The root issue is the frame shift, the index on the `names` (which comes from `package_names_for_targets` cannot be used with `current_version_array`. A probably fix is to just remove the check against the current version in the Yum provider as we already skipped packages that are up to date.

**Comment by coderanger** [comment]
Ping @chef/client-core (if it will let me).

**Comment by lamont-granquist** [comment]
diagnosis and proposed fix sounds correct.

**Comment by jaymzh** [comment]
Indeed. I'm traveling and can't take this on, but it sounds right

**Comment by lamont-granquist** [comment]
this is most likely because the provider does not use `use_multipackage_api`
