### ISSUE TITLE
audit mode is supposed to ban RSpec "should" syntax, but it doesn't

### ISSUE THREAD

**Issue by juliandunn** [chef/chef#3482]
As we discovered during an internal demo with @jtimberman, Audit Mode is [supposed to ban RSpec should syntax](https://github.com/chef/chef/blob/master/lib/chef/audit/runner.rb#L104) but weirdly it does not.

* Expected: `undefined method `should'`
* Actual: the control works

Sample case that Joshua showed:

```ruby
control_group "should" do
  control "should i?" do
    describe file('/etc/hosts') do
      it { should be_file }
    end
  end
end
```

**Comment by danielsdeleo** [comment]
Does that even apply to the implicit subject? AFAIK, the motivation for not supporting `should` is that it requires monkey patching `Object` (or even deeper), but the default receiver in that block is probably some RSpec class, so there's no monkey patching.

**Comment by juliandunn** [comment]
That question is beyond my RSpec powers. @jtimberman care to weigh in since you asked me to open this? :grin:

**Comment by danielsdeleo** [comment]
Confirmed in RSpec docs. https://www.relishapp.com/rspec/rspec-core/docs/subject/one-liner-syntax

> should was designed back when rspec-expectations only had a should-based syntax. However, it continues to be available and work even if the :should syntax is disabled (since that merely removes Object#should but this is RSpec::Core::ExampleGroup#should).

**Comment by danielsdeleo** [comment]
Closing based on the RSpec docs saying this kind of `should` is okay.
