### ISSUE TITLE
Allow nested libraries to be uploaded to a chef server

### ISSUE THREAD

**Issue by andrewelizondo** [chef/chef#3486]
In certain scenarios such as the [f5-bigip](https://github.com/target/f5-bigip-cookbook) cookbook, one would like to be able to separate out their library structure to allow cleaner code separation.

Currently we only support the files and templates directories having a nested file structure.

https://github.com/chef/chef/blob/master/lib%2Fchef%2Fcookbook_manifest.rb#L240-261

**Comment by lamont-granquist** [comment]
Closing this as a dup of RFC-040 and #3494
