### ISSUE TITLE
Chef download page is missing chef 12.3.0 for some versions of windows

### ISSUE THREAD

**Issue by Tech356** [chef/chef#3506]
I don't know if this is the right place for this or not but I don't know where else to report it. 

The chef client download page does not list version 12.3.0 for Windows version 7, 8, 2003r2, or 2008. 

https://www.chef.io/download-chef-client/

The alternate (or new?) download page has 12.3.0.

https://downloads.chef.io/chef-client/windows/#/

**Comment by jdmundrawala** [comment]
https://www.chef.io/download-chef-client/ has been replaced by https://downloads.chef.io/chef-client

**Comment by mmzyk** [comment]
@jdmundrawala If that's the case we should have a redirect in place, b/c otherwise that is really confusing, since nothing on download-chef-client indicates it's been replaced. Even then, we should just redirect.

**Comment by juliandunn** [comment]
@jaym can you ask the appropriate folks (is that @cwebberOps?) to make the redirect?

**Comment by cwebberOps** [comment]
@juliandunn I will open a ticket internally to fix it.
