### ISSUE TITLE
bridge options for ifconfig provider

### ISSUE THREAD

**Issue by pkuczynski** [chef/chef#3509]
Need to be able to define bridging configuration in Chef's ifconfig provider.

```
iface xenbr0 inet static
        address ...
        netmask ...
        network ...
        broadcast ..
        gateway ...
        bridge_ports eth0
```

Current implementation (http://docs.opscode.com/resource_ifconfig.html) doesn't take "bridge".

(Ref: https://tickets.opscode.com/browse/CHEF-5363)

**Comment by thommay** [comment]
Part of #3862 fix up.

**Comment by tas50** [comment]
bridge_ports is already there and I've added the bridge config to RHEL based systems in https://github.com/chef/chef/pull/10529
