### ISSUE TITLE
getting error while using cookbook microsoft_azure

### ISSUE THREAD

**Issue by vpgohil** [chef/chef#3511]
Hi,

I have downloaded cookbook microsoft_azure and tried to use it to create azure sql and I am getting below error at time of execution.

 Chef Client failed. 1 resources updated in 16.5670084 seconds
[2015-06-09T10:31:15+00:00] ERROR: Unable to activate azure-0.6.4, because mime-                     types-2.5 conflicts with mime-types (~> 1.0)

Tried to uninstall  mimetypes-2.5 but after this chef-client is not working. Please help me in solving this dependency issue.

please find below details.

chef -v
Chef Development Kit Version: 0.6.0
chef-client version: 12.3.0
berks version: 3.2.4
kitchen version: 1.4.0
 

followed instruction from https://supermarket.chef.io/cookbooks/microsoft_azure#readme

**Comment by vpgohil1986** [comment]
followed instruction from https://supermarket.chef.io/cookbooks/microsoft_azure#readme

**Comment by lamont-granquist** [comment]
This issue should probably be filed against the github repo of the cookbook

**Comment by juliandunn** [comment]
Please file an issue against the cookbook. https://github.com/chef-partners/azure-cookbook
