### ISSUE TITLE
Chef::User.list only queries org-specific users endpoint

### ISSUE THREAD

**Issue by stevendanna** [chef/chef#3513]
The `Chef::User.list` endpoint hits the org-specific user list endpoint:

https://github.com/chef/chef/blob/master/lib/chef/user.rb#L289

However, in multi-tenant server, it would also be useful to be able to use the root "users" endpoint.  For instance, this would be required to fully replicate the behavior of knife-opc's `knife opc user list` command for Chef Server administration.

One possibility is to add a `global_list` which will hit the root url.  On chef-server 11, global_list and list would be equivalent.

**Comment by snehaldwivedi** [comment]
@stevendanna can you please help me with the understanding what exactly you meant by `global_list`? 
As per the current code `knife user list`,  lists all admin and non admin users. Is there any other type of user we need to display through this command?

Also, in link line #L289 does not exists are you pointing it to https://github.com/chef/chef/blob/master/lib/chef/user.rb#L157?

**Comment by stevendanna** [comment]
> can you please help me with the understanding what exactly you meant by global_list?

Sure!  The chef-server has two API endpoints that can list users, `/users` and `/organizations/ORGNAME/users`. The former lists all users on the chef-server.  The latter lists all users associated to the given organization.  Currently, `Chef::User.list` uses a ServerAPI object that is based on the chef_server_url.  This is typically an org-specific URL and thus will be using the second API endpoint and only returning users associated with the organization the user has configured in their configuration file:

https://github.com/chef/chef/blob/928abf3e72ef9759551d80a23a4fc79730d2aa60/lib/chef/user.rb#L158

The idea of this ticket was to provide _some_ interface inside the Chef ruby codebase that could be used to call the `/users` endpoint.  One idea, outlined here, would be to add an option ot the Chef::User.list function that would then make an API call using the chef_server_root rather than the org-specific URL.  Another option might be to make a completely different class that represents this API.

Note that I am not up to speed on the many improvements that have been made to the code base since I wrote this ticket and thus the best course of action today may look very different.


> Also, in link line #L289 does not exists are you pointing it to https://github.com/chef/chef/blob/master/lib/chef/user.rb#L157?

Yes, the code changed a bit in the 5 years since I opened this issue. I should have used the perma-link :D

**Comment by snehaldwivedi** [comment]
@stevendanna I have tested with the merged opc code https://github.com/chef/chef/pull/10187,  Currently I we are using `chef_server_root` which is providing me list of both org-specific and non org-specific users. Like as follows, my list has two users org-specific and non org-specific.
```
$ bundle exec knife user list
zzz-32
zzz-33
```
```
$ bundle exec knife user show zzz-32 -l
display_name:  zzz 32
email:         zzz-32@mailinator.com
first_name:    zzz
last_name:     32
organizations:
username:      zzz-32
```
```
$ bundle exec knife user show zzz-33 -l
display_name:  zzz 32
email:         zzz-33@mailinator.com
first_name:    zzz
last_name:     32
organizations: 4thcoffee
username:      zzz-33
```
So I think its working as per the details mention in the cards. Please let me know if required any other details.

**Comment by stevendanna** [comment]
> Currently I we are using chef_server_root which is providing me list of both org-specific and non org-specific users. Like as follows, my list has two users org-specific and non org-specific.

I think using the chef_server_root produces the opposite problem and changes the semantics of the commnad.  _All_ users in Chef Server are global.  Those users can then be associated with 1 or more organizations.  For end-users, there are then 2 operations that they may want to complete:

1. List all users on the chef server
2. List all users associated with a given organization

In order to allow users to do each of these operations easily, we need to somehow provide a way to query each or the equivealent API endpoints.

**Comment by snehaldwivedi** [comment]
@stevendanna I have done some analysis on your suggestion. `chef_server_url` is path of organisation configured in `kife.rb` and if we use that it will only list the users of that specific organisation. In that case we will not be able to list all global users.

In my opinion we can use   `chef_server_root`, as it don't set any path for organisation. So if we run `knife user list` it will list all global users. We can add one option `-org-name NAME_OF_ORG` ,  if we specify org name like  `knife user list -org-name "4thcoffee"` its will list users that belongs to `4thcoffee` organisation.

Please let me know your opinion on this?

**Comment by stevendanna** [comment]
@snehaldwivedi I think that your solution is nice overall and if we were implementing this from scratch is a very reasonable behavior.  One potential problem this introduces however is that it represents a behavior change of the _existing_ `knife user list` command for users.  I would check in with the core chef team to see if they are OK with that behavior change.

**Comment by snehaldwivedi** [comment]
@stevendanna okay, please let me know once the discussion is done.

**Comment by tas50** [comment]
Is there any reason for us not to add a --global flag that would use the server_root and query out users at the server level instead of the org level?

**Comment by snehaldwivedi** [comment]
@tas50 this card was created to get all global user when we use  --global flag else it will show the org specific users. Please let me know if you require any more details added in PR

**Comment by btm** [comment]
If we did have top level a `-O organization` flag like was discussed in [rfc025](https://github.com/chef-boneyard/chef-rfc/blob/master/rfc025-multitenant-chef-client-support.md), and we could swap from `Chef::Knife.rest` to `Chef::Knife.root_rest` if that was set, then many we could hit all of these goals at once by also supporting (maybe it'd mostly just work) something like `knife user list --organization /`.
