### ISSUE TITLE
`knife user create` and `knife client create` should check file permissions 

### ISSUE THREAD

**Issue by stevendanna** [chef/chef#3514]
Both commands provide a `--file` option that allow the user to redirect the returned private key to a file.  If this file is not writable, the user/client will still be created but the private key will have been lost.

Checking that the file can be written before making the API request would solve this problem.  Here is an example from knife-opc:

https://github.com/chef/knife-opc/blob/92d9f1d9300b0f969bab812b3587e51d1a9543d2/lib/chef/knife/opc_user_create.rb#L57-L64

**Comment by VanWolf29** [comment]
I can take this one.
