### ISSUE TITLE
`knife user show` should have an option to include org membership

### ISSUE THREAD

**Issue by stevendanna** [chef/chef#3515]
knife-opc has a flag that will include the user's organization in the result of a `user show`.  It would be nice to have this same flag in `knife user show` or to create another command that this same information could be used:

https://github.com/chef/knife-opc/blob/master/lib/chef/knife/opc_user_show.rb#L32-L35

**Comment by snehaldwivedi** [comment]
already covered in [PR](https://github.com/chef/chef/pull/10380)
