### ISSUE TITLE
Resource and provider resolver fallback non-functional

### ISSUE THREAD

**Issue by coderanger** [chef/chef#3524]
The code used for the non-`provides()` lookup on resources and providers is non-functional as far as I can tell.

[The code looks like](https://github.com/chef/chef/blob/master/lib/chef/resource_resolver.rb#L143):

```ruby
@prioritized_handlers ||= super ||
```

but `super` returns an empty array, not `nil` so the fallback code never runs.

Ping @jkeiser and @thommay (I think this is probably a release blocker for RC2)

**Comment by coderanger** [comment]
Looking in to a fix now, but wanted to get this flagged ASAP.

**Comment by coderanger** [comment]
I can't actually figure out where legacy resources factor in to this system, maybe it doesn't matter that that code never runs?

**Comment by jkeiser** [comment]
@coderanger thanks!  This code is there to handle Resources that don't declare that they provide `x`, but do implement `provides`.  For example,

```ruby
def provides?(*args)
  true
end
```

Should provide everything.

**Comment by coderanger** [comment]
Yes, I get that but it doesn't work. `super` will never return nil and `[]` is a truthy value. Beyond that I don't see where non-`provides()` resources actually get looked up by the code in `Deprecated`.

**Comment by coderanger** [comment]
I think maybe you originally planned to use `enabled_handlers` for something, but because you changed `Resource#provides?` to be defined in terms of `ResourceResolver` that would no longer work anyway.

**Comment by jkeiser** [comment]
@coderanger `resources` is a full list of `Chef::Resource.descendants`, which is where I intended it to look up.  The fix is to check for `empty?` and go through the call. You're right about the recursion, though. Any resource that overrides `provides?` *and* calls `super` will recurse forever.

**Comment by coderanger** [comment]
That is one problem, but the more immediate issue is that resources which don't use `provides()` explicitly don't seem to be working anymore. You set things up in `Resource.resource_name` to call `provides()` automatically but that's only when setting a non-default name, and the `self.inherited` callback just does `child.resource_name`. No where in this path do resources actually get registered and it never uses the old `const_get` style directly for resources (though it does for providers).

**Comment by jkeiser** [comment]
I'm unclear what's not working, would you mind elaborating on the case that fails?  When I check out master, and run this recipe with chef-apply, it succeeds:

```ruby
class X < Chef::Resource
end

x 'hi' do
end
```

```
~/s/chef> bundle exec chef-apply x.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * x[hi] action nothing (skipped due to action :nothing)
```

**Comment by coderanger** [comment]
Okay, so I think I found the issue. Poise defines its own `#resource_name` and that is overwriting the registration behavior because registration with the DSL is a side-effect of calling `child.resource_name`. That seems really confusing, for something like that looks like an accessor to trigger a global registration. Can we move that logic to an explicit `register!` or something?

**Comment by jkeiser** [comment]
The reason it's written that way is to treat the default like a set--basically, when you set resource_name to a value, it will provide that value.  "When the resource_name becomes known, we provide that resource_name."

I could totally see it going a different way though--we could just do resource_name(convert_to_snake_case) in def self.inherited instead.  The only case that will affect is this:

```ruby
X = Class.new(Chef::Resource)
end
X.resource_name
x 'blah'
```

But I think it's reasonable for resource_name to just return `nil` in that case.

**Comment by coderanger** [comment]
So I was just pondering this while in the other room and yeah, I realized the reason this is failing in Halite too is that it uses anonymous classes and then defines `self.name` in the class body, but that's too late for the registration to work. Another issue with the code as written, I think it will try to register any class name by default, not just those under `Chef::Resource`. A `start_with?` check should take care of that.

Switch `resource_name` with no params to be side-effect-free sounds like a win to me, also makes the implementation easier on my side since I only need to deal with the upstream version if a value is being set.

**Comment by jkeiser** [comment]
@coderanger the patch in question is #3542

**Comment by coderanger** [comment]
This is not fixed, the line https://github.com/chef/chef/blob/master/lib/chef/resource_resolver.rb#L143 is still incorrect and represents two bugs:

1. The second part of the `||` can never fire.
2. The second part of the `||` can trivially cause infinite loops.

Basically we should remove that whole warning, I don't think there is any safe way to implement it and only looks like it works right now because it never gets called.

**Comment by coderanger** [comment]
(though this is a low-priority bug compared to the rest)
