### ISSUE TITLE
[knife] Assume a default key when no colon in QUERY

### ISSUE THREAD

**Issue by patcon** [chef/chef#3526]
The thought would be that this could be `name:` by default (or perhaps `fqdn:`?), but it could be set to something else in `knife.rb`

```
knife search example.com
knife ssh example.com "uname"
```

**Comment by patcon** [comment]
On further consideration, using the fqdn key and NOT providing a means to set another default key would seem to imply that the feature in #3527 could equally apply to `knife ssh` (though not `knife search`):

```
knife ssh patcon@example.com "uname"`
```

Again, this would align with user expectations of the `ssh` command

**Comment by lamont-granquist** [comment]
`knife search node "foo"` already goes through some magic to search name and fqdn and possibly a couple other fields by default.  that code could simply be reused for knife ssh.

**Comment by patcon** [comment]
thanks! found it: https://github.com/chef/chef/blob/b08c9010c387c762a6fa82fa9ae8c2a5e5c8594d/lib/chef/knife/search.rb#L161-L165

I'll mess around with it later

**Comment by patcon** [comment]
Hm. On consideration, "tags or role or fqdn or addresses" might be a little too general for a possibly destructive command, you think?

**Comment by lamont-granquist** [comment]
I never run a destructive ssh command without validating the targets it will hit with a non-destructive command.  And the knife ssh command is necessarily a chainsaw, anyone with access to it is trusted to not run 'knife ssh "sudo rm -rf / &"'

**Comment by patcon** [comment]
:) :+1: I'll look into tests then

**Comment by sawanoboly** [comment]
@lamont-granquist @patcon 

I agree that the QUERY has a default key when `:` was omited.

And, It will enough for in most use cases, I think.

- for node => use `name:`,`fqdn:`, or `ipaddress:` by default
- for other than the node (such as roles, users) => use `name:` by default

**Comment by patcon** [comment]
@sawanoboly Thanks for the feedback. @lamont-granquist said in the PR's inline comments that he preferred this share the same fuzziness as search, so I'm assuming that applies to all indexes. Correct me if I'm wrong though, @lamont-granquist

**Comment by lamont-granquist** [comment]
Yes, and not just share the same semantics, but no code duplication.  Extract a method, if there isn't one already, and use it both places consistently.

**Comment by lamont-granquist** [comment]
And dan is updating the knife search node fuzzifier method in #3913 for policyfiles now (which is precisely why the fuzzifier needs to exist only in one spot, not many)
