### ISSUE TITLE
registry_key resource is case sensitive in chef but not on windows

### ISSUE THREAD

**Issue by bigbam505** [chef/chef#3531]
If you use the `registry_key` resource on windows it can keep trying to run resources because of incorrect case.  For example, I was trying to set the chef-client service to run as delayed startup.  The code I had was this:

```ruby
 registry_key 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\chef-client' do
   action :create
   values [ {
      :name => 'DelayedAutoStart',
      :type => :dword,
      :data => 1
      } ]
end
```

However I noticed that this would keep creating the registry key on every chef run.  Upon further investigation I found that the windows service manager sets a key `DelayedAutostart` (notice the lowercase `s`).  If I change my code to the include the following it works fine.

```ruby 
not_if { registry_value_exists?('HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\chef-client', { name: 'DelayedAutoStart' }) }
```

Not sure if this has been addressed but I did not see any issues opened for this.  I ran into this with chef-client 12.2.1 and also chef-client 12.3.0 in test-kitchen

**Comment by Tech356** [comment]
Also reported here: https://tickets.opscode.com/browse/CHEF-5196

**Comment by jkerry** [comment]
Working on a fix on my fork.  I should be out of manual qa and get a pull request in shortly

**Comment by lamont-granquist** [comment]
#3539 is merged, so assuming this is fixed.
