### ISSUE TITLE
Windows: env LWRP with action :modify overwrites env variables

### ISSUE THREAD

**Issue by npiguet** [chef/chef#3540]
I've been trying to provision some windows VMs, and I'm trying to add a folder to the `PATH` environment variable. So far, this has not worked so well. In fact, it seems that chef completely ovewrites the environment variables even when I use `action :modify`

Here is the block I use:

``` ruby
env "Add java binaries to PATH" do
    action :modify
    key_name "PATH"
    value "#{java_home}\\bin"
end
```

Here is how PATH looks like before the block runs

```
PS C:\Windows\system32> $Env:PATH
C:\Windows\system32\WindowsPowerShell\v1.0\;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\opscode\chef\bin
```

and here is how it looks like after the block

```
> $Env:PATH
C:\Windows\system32\WindowsPowerShell\v1.0\;C:\softwares\extern\jvm\jdk1.8.0_45\bin
```

It seems that powershell always prepends itself to `PATH`, so that's why it's still there.

**Comment by npiguet** [comment]
As a workaround, I'm currently using
```ruby
unless ENV['PATH'].include?(java_home)
  env "Add java binaries to PATH" do
    action :create
    key_name "PATH"
    value "#{java_home}\\bin;#{ENV['PATH']}"
  end
end
```

**Comment by jdmundrawala** [comment]
there is a `windows_path` resource in the windows cookbook that you can use.
https://github.com/opscode-cookbooks/windows/blob/master/providers/path.rb#L25-L30 is how you'd do it if you didn't want to use the cookbook

**Comment by npiguet** [comment]
Thanks for that. But that sounds more like a workaround than the way it really should be, no?

**Comment by jdmundrawala** [comment]
It's either a bug in the code or the documentation. I feel like this one has come up before

**Comment by jdmundrawala** [comment]
Maybe we change the documentation and add the ability to specify prepend or append?
Thought?
cc @chef/client-windows

**Comment by npiguet** [comment]
That might be a good idea. The order does matter since I believe windows stops at the first match in `PATH`

**Comment by ksubrama** [comment]
I just grepped in the chef repo for "delim" and couldn't find any place where we set it.  Shouldn't we just set it to "," on linux and ";" on windows?

**Comment by MichaelPereira** [comment]
@npiguet @jaym I've created a PR to append values: #4703 Please let me know if you have any feedback

**Comment by tas50** [comment]
As an update the windows_path resource is built into Chef as of 13.4 so there's no need for the Windows cookbook at this point.

**Comment by btm** [comment]
@tas50 so we can close this now, as the user should set PATH using `windows_path` instead of `env`?

**Comment by tas50** [comment]
Yep this should be done with windows_path now which properly handles it on windows
