### ISSUE TITLE
Support truncate action on file resource

### ISSUE THREAD

**Issue by mattnelson** [chef/chef#3544]
Currently if you want to truncate a file you need to supply an empty content. It would be nice if the file resource supported this through an action.

``` ruby
file '/home/user/file' do
  content ''
end
```

``` ruby
file '/home/user/file' do
  action :truncate
end
```

**Comment by lamont-granquist** [comment]
This would be better served by a line-based file_edit resource that supported truncate as one of the ways that it managed the content of the file.

**Comment by ranjib** [comment]
the semantics (owner, group etc) is well suited for file resource.  But i find the first version is more appropriate (content ''), cause if the file is absent the action is similar to touch which is create without any content, while if its present and have some content then chef will actually truncate the file. ..

**Comment by lamont-granquist** [comment]
yeah this is not going to get implemented, the blank content approach can be considered the correct way to do this
