### ISSUE TITLE
file resource rights property should support SDDL for Windows

### ISSUE THREAD

**Issue by adamedx** [chef/chef#3545]
The `rights` property of file resources on Windows let's you set the security descriptor of an object. We should allow the user to specify an [SDDL](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379567%28v=vs.85%29.aspx) string since this is a common standard on Windows and would enable better integration of Chef with native Windows tools including PowerShell.

**Comment by adamedx** [comment]
Curious as to your thoughts @smurawski.

**Comment by stuartpreston** [comment]
I looked through all the other issues and customer feedback internally but didn't see this crop up as a problem for people or a requested enhancement. Closing this for now.
