### ISSUE TITLE
Ability to specify the format that erubis expects

### ISSUE THREAD

**Issue by damm** [chef/chef#3547]
Recently ran into a situation where some template I needed to process needed <%{ to start the line.

Anyway the erubis user guide mentions you can change the `:pattern =>` [user guide - tutorial - pattern](http://www.kuwata-lab.com/erubis/users-guide.02.html#tut-pattern)

Would be great if we could do this in the future; it's not something most users will want to do or need to.

https://github.com/chef/chef/blob/master/lib/chef/mixin/template.rb#L113

**Comment by lamont-granquist** [comment]
Probably not something we're going to prioritize without a user-submitted code to implement it.
