### ISSUE TITLE
Chef throws Win32APIFunctionNotImplemented when using Chef::ReservedNames::Win32::Version.new

### ISSUE THREAD

**Issue by TriskalJM** [chef/chef#3550]
I've got a recipe that fails on Windows XP Professional SP3. I'm checking the version of Windows using Chef's built-in functionality (not through some other cookbook), and it fails.

It appears that Chef is using a WinAPI function called GetProductionInfo that Windows XP doesn't implement.

Using Chef 11.12.0.rc.1

**Comment by juliandunn** [comment]
I'm sorry but Windows XP is not a [supported platform](https://docs.chef.io/supported_platforms.html). It is also [end-of-life](http://windows.microsoft.com/en-us/windows/end-support-help) as of April 8, 2014.
