### ISSUE TITLE
"directory" resource does not set "owner" that is not in /etc/passwd

### ISSUE THREAD

**Issue by gkugel** [chef/chef#3552]
When attempting to create a directory with an LDAP user as the owner, the ownership stays as "root"
During my tests I could only set ownership if the username is in /etc/passwd file:

  directory '/home/user1' do
      owner 'user1'
      group 'ldap-users'
      mode '0755'
      action :create
  end

If I run "sudo chown user1 /home/user1" after chef-client, the ownership is changed without any issues.

**Comment by stevendanna** [comment]
@gkugel Is the chef-client run where this is failing also the first time ldap is being configured?  If so, you might be hitting a problem with the fact that deep down in the stack (glibc), there is caching that occurs at the per-process level which means that configuration changes around nss aren't picked up by that process.

**Comment by lamont-granquist** [comment]
Yeah that most likely will not be solvable short of patching ruby itself and/or running nscd with user and group caching turned on.  I doubt there's a fixable chef-client bug here.

**Comment by gkugel** [comment]
Yep, looks like caching issue.  Restarting nscd seems to have helped.  Thank you!
