### ISSUE TITLE
--json-attribute option with run_list attribute not working.

### ISSUE THREAD

**Issue by Vasu1105** [chef/chef#3557]
Using chef 12.3.0

While trying -j option I have noticed that if I pass --json-attributes '{ "run_list": ["recipe[getting-started]"] }' while bootstrapping node it gets appended in first-boot.json, but it does not run the run list. I checked first-boot.json on node it looks like this  {"run_list":["recipe[getting-started]"],"run_list":[]}. And when I run the first-boot.json on command line I get following output 

sudo chef-client -j /etc/chef/first-boot.json 
Starting Chef Client, version 12.3.0
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Compiling Cookbooks...
[2015-06-19T11:53:09+00:00] WARN: Node vjenv4 has an empty run list.
Converging 0 resources

Running handlers:
Running handlers complete
Chef Client finished, 0/0 resources updated in 3.0463365 seconds
# 

It should merge the run_list from first boot attributes in run_list [ ],  but it creates another attribute with same name and which somehow causes in running blank run list.

**Comment by lamont-granquist** [comment]
those are for setting typical attributes.  while the run_list is implemented as an attribute, it is special one and you need to use -r to specify it.

**Comment by Vasu1105** [comment]
@lamont-granquist  thats correct that I can use -r for run_list but I feel we should handle such scenario or at lease prompt user not to add the run list through -j option.

**Comment by lamont-granquist** [comment]
Yeah it could raise or warn if it sees that attribute

**Comment by lamont-granquist** [comment]
probably not going to fix this.
