### ISSUE TITLE
`knife ssl check' may be reporting incorrect default certificate path

### ISSUE THREAD

**Issue by tpetchel** [chef/chef#3559]
While debugging an SSL issue, I ran `knife ssl check`. In the output, it states:

```
By default, the certificate is stored in the following location on the host
where your chef-server runs:

  /var/opt/chef-server/nginx/ca/SERVER_HOSTNAME.crt
```

But on my Chef server, the certificates are placed under `/var/opt/opscode/nginx/ca/SERVER_HOSTNAME.crt`.

Can someone please verify the default location and update the output as necessary? The [reference documentation](https://docs.chef.io/knife_ssl_check.html) shows the directory that I report above. 

Thanks!

**Comment by justanshulsharma** [comment]
@tpetchel certificates right location is
```
/var/opt/opscode/nginx/ca/SERVER_HOSTNAME.crt
```

**Comment by rmoriz** [comment]
isn't the chef-server omnibus install location `/opt/opscode`?

**Comment by jekriske** [comment]
Wasn't this already supposed to be fixed?
https://github.com/chef/chef/issues/2604

**Comment by lamont-granquist** [comment]
fixed.
