### ISSUE TITLE
API reversion: ProviderPriorityMap#priority

### ISSUE THREAD

**Issue by coderanger** [chef/chef#3561]
Looks like this method got removed in https://github.com/chef/chef/commit/9a09df111e614d3e66639740d796c0479ab9b63d#diff-0547a1dbce8a9b0e83b5285e9a0a31ec

Might have been accidental? It should just be an alias for `#set` given the current code. This was the only public API to declare provider priority ordering in 12.3 so I think removal would count as a disallowed API change.

Ping @jkeiser @thommay @lamont-granquist.

**Comment by coderanger** [comment]
Also it isn't clear to me how to use the current NodeMap code to set a priority array. The old code built the array in reverse so as long as your `priority()` call was after the classes were loaded (which is required anyway to have symbols for them) you were fine. I _think_ the intent is that you would use the new `override` filter flag for this, which is annoying both because you can only ever do this once (a wrapper couldn't easily re-order things once an override is in the array). Also because this flag would only work on 12.4+ so code declaring a priority array would need to check the Chef version carefully (less bad than the wrapper issue but annoying).

As it stands calling `Chef.provider_priority_map.set(:name, [Two, One])` would end up appending that to the end of the node map key array, `[One, Two, [Two, One]]` effectively. The provider resolver calls `.flatten(1).uniq` on this value, so the end result is `[One, Two]`, totally ignoring our requested priority. This also means my proposed fix is probably wrong :-) A hamfisted solution would be to make `#priority` work like `#set` _except_ it defaults to adding to the front of the list instead of the back. That seems like the most logical behavior for the use case of explicit priority orderings.

**Comment by coderanger** [comment]
Trying to trace through the `set_priority_array` code, and I'm not sure this is going to have the expected behaviors. There is a check for `if new_matcher[:value].is_a?(Array) != matcher[:value].is_a?(Array)` but in a priority map the value should always be an array. I can't tell if this matters or not, but we should maybe quickly write down the expected behaviors for some common cases.

**Comment by coderanger** [comment]
It seems like the effective behavior of `set_priority_array` given no filters et al is to just always prepend the value to the front of the array, which matches the 12.3 behavior but the code is sufficiently more complex that it doesn't seem intentional. There is some logic to alpha sort stuff, but it checks for `if new_matcher[:value].is_a?(Class)` which again should always be false since the value is an array.

**Comment by jkeiser** [comment]
Was fixed with #3562
