### ISSUE TITLE
Knife Bootstrap chef-vault-handler Docs

### ISSUE THREAD

**Issue by sean-horn** [chef/chef#3565]
As a customer, I would like to be able to reference further documentation with examples explaining usage of the following Chef Vault options available during bootstrap

What is this for?
How does it fit in with Chef Vault?
What would be an example of specifying multiple vaults in a single run?
What is the full usage flow for a simple use case? Can I just bootstrap a node and go on my way?

```
--bootstrap-vault-file VAULT_FILE
Use to specify the path to a JSON file that contains a list of vaults and items to be updated.

--bootstrap-vault-item VAULT_ITEM
Use to specify a single vault and item to update as vault:item.

--bootstrap-vault-json VAULT_JSON
Use to specify a JSON string that contains a list of vaults and items to be updated.
```

**Comment by legal90** [comment]
Usage examples are available here: https://docs.chef.io/install_bootstrap.html#use-bootstrap-vault-file

**Comment by tas50** [comment]
Closing this out based on the link to the docs site
