### ISSUE TITLE
Hosted chef fails to create databag if you press the enter key

### ISSUE THREAD

**Issue by spuder** [chef/chef#3567]
Create a databag in hosted chef. 

If you press the 'Create Data Bag' button with the mouse, then the databag will be created correctly. 
If you press the  'Create Data Bag' using the enter key on the keyboard, then the page will refresh, and fail to create the databag. 

Reproduced in both Chrome and Safari

![screenshot 2015-06-22 18 07 13](https://cloud.githubusercontent.com/assets/242382/8296105/87eb3d46-1909-11e5-83c2-94ad616b896d.png)

Here is a video showing it happening. 

https://youtu.be/DjR92IBB--k

**Comment by ranjib** [comment]
@spuder we use this repo and the issue tracker for chef-client only, can you please file this against chef-server or hosted chef related forum (support email i guess).

**Comment by mmzyk** [comment]
@spuder Thanks for this report. If you can open this against https://github.com/chef/chef-manage-issues that would be the right place. Chef Manage is the UI of Hosted Chef.

**Comment by spuder** [comment]
Thanks mmzyk, 

I opened a support ticket for this issue. Do you still want me to report it at chef-manage-issues?

**Comment by mmzyk** [comment]
@spuder You can. It's likely the support ticket will turn into a ticket there. If you open an issue you might comment on the support ticket about it as well.
