### ISSUE TITLE
failed (2: No such file or directory) - /opt/opscode-manage/embedded/service/opscode-manage/public/assets/locale/application_en-ed0cf4e74dffb77fe5988bd21bdb1519.js

### ISSUE THREAD

**Issue by yaniv-cb4** [chef/chef#3571]
failed (2: No such file or directory) is logged to /var/log/opscode/nginx/error.log.

2015/06/23 13:27:30 [error] 3005#0: *208 open() "/opt/opscode-manage/embedded/service/opscode-manage/public/assets/locale/application_en-ed0cf4e74dffb77fe5988bd21bdb1519.js" failed (2: No such file or directory), client: 192.168.1.156, server: deployment.c-b4.com, request: "GET /assets/locale/application_en-ed0cf4e74dffb77fe5988bd21bdb1519.js HTTP/1.1", host: "deployment.c-b4.com", referrer: "https://deployment.c-b4.com:8443/"

Version:
opscode-manage 1.17.0

Component                  Installed Version   Version GUID                                   Overridden From
----------------------------------------------------------------------------------------------------------------
berkshelf2                 2.0.18
bundler                    1.5.3
bzip2                      1.0.6               md5:00b516f4704d4a7cb50a1d97e6e8e15b
cacerts                    2014.08.20          md5:c9f4f7f4d6a5ef6633e893577a09865e           2015.04.22
chef-gem                   12.0.3              11.12.2
curl                       7.36.0              md5:643a7030b27449e76413d501d4b8eb57
gdbm                       1.9.1               md5:59f6e4c4193cb875964ffbe8aa384b58
libedit                    20120601-3.0        md5:e50f6a7afb4de00c81650f7b1a0f5aea
libffi                     3.2.1               md5:83b89587607e3eb65c70d361f13bab43
libiconv                   1.14                md5:e34509b1623cec449dfeb73d7ce9c6c6
liblzma                    5.0.5               md5:19d924e066b6fff0bc9d1981b4e53196
libtool                    2.4                 md5:b32b04148ecdd7344abc6fe8bd1bb021
libxml2                    2.9.1               md5:9c0cfef285d5c4a5c80d00904ddab380
libxslt                    1.1.28              md5:9667bf6f9310b957254fdcf6596600b7
libyaml                    0.1.6               md5:5fe00cda18ca5daeb43762b80c38e06e
makedepend                 1.0.5               md5:efb2d7c7e22840947863efaedc175747
ncurses                    5.9                 md5:8cb9c412e5f2d96bc6f459aa8c6282a1
nodejs                     0.10.10             md5:a47a9141567dd591eec486db05b09e1c
nokogiri                   1.6.3.1
omnibus-ctl                0.3.6               git:c514d1d4ecb24e30fdbd310b2dd038b2192b4fa7
openssl                    1.0.1m              md5:d143d1555d842a069cb7cc34ba745a06
opscode-manage             1.17.0              git:3330c1c266e4739ca91eb039226f499007feb262
opscode-manage-cookbooks   1.17.0
opscode-manage-ctl         1.17.0
pkg-config                 0.28                md5:aa3c86e67551adc3ac865160e34a2a0d
preparation                1.0.0
python                     2.7.9               md5:5eebcaa0030dc4061156d3429657fb83
redis                      2.8.21              md5:d059e2bf5315e2488ab679e09e55a9e7
ruby                       2.1.5               md5:df4c1b23f624a50513c7a78cb51a13dc           1.9.3-p550
rubygems                   1.8.24              md5:3a555b9d579f6a1a1e110628f5110c6b
runit                      2.1.1               md5:8fa53ea8f71d88da9503f62793336bc3
util-macros                1.18.0              md5:fd0ba21b3179703c071bbb4c3e5fb0f4
version-manifest           0.0.1
xproto                     7.0.25              md5:a47db46cb117805bd6947aa5928a7436
zlib                       1.2.8               md5:44d667c142d7cda120332623eab69f40
~

**Comment by ranjib** [comment]
@yaniv-cb4 we only track chef-client related issues here. please raise this against chef server or chef-manage related medium.
