### ISSUE TITLE
API break: RunContext attr_reader vs. attr_accessor

### ISSUE THREAD

**Issue by coderanger** [chef/chef#3585]
https://github.com/chef/chef/commit/87a8b49efbccb6934ff2bacb8f8df53d1caf5e46 changed a whole bunch of stuff from `attr_accessor` to `attr_reader`. The `Deprecated` module adds warnings on these, but it doesn't actually preserve the original behavior. Guessing this was just an oversight. Also it looks like the deprecation implementation was removed for `resource_collection=` some time between that commit and current master.

**Comment by coderanger** [comment]
Ping @jkeiser @thom @jdmundrawala.

**Comment by coderanger** [comment]
For a concrete example, https://github.com/poise/poise/blob/master/lib/poise/helpers/subcontext_block.rb#L32-L33 is now broken.

**Comment by coderanger** [comment]
Ack, didn't mean to close.

**Comment by coderanger** [comment]
Derp, this isn't actually in 12.4, just on master. Updating the name.

**Comment by jkeiser** [comment]
Phew! At least that explains why you didn't notice it :)
