### ISSUE TITLE
powershell_script no output for info and debug log levels

### ISSUE THREAD

**Issue by alexpop** [chef/chef#3596]
On a Linux node, if I have these two resources:

```ruby
execute "multi_line_script" do
  command <<-EOH
    whoami
    ls /etc
  EOH
  action :run
end

bash 'test1' do
  code '
    ls /tmp
  '
  action :run
end
```

they will print the STDOUT of the two bash scripts when chef-client uses 'info' or 'debug' log levels.

This is not the case for the 'powershell_script' resource. The following resource will have no output when chef-client uses 'info' or 'debug' log levels:

```ruby
powershell_script 'test' do
  code '
    ls c:\
  '
  action :run
end
```

**Comment by adamedx** [comment]
For triage: I think we should do this at medium priority and consider @alexpop's fix.

**Comment by dougireton** [comment]
I am struggling with this right now. PowerShell script output would really help with debugging.

**Comment by smurawski** [comment]
Closed with https://github.com/chef/chef/pull/4087
