### ISSUE TITLE
knife ssh and knife bootstrap should have option to disregard ~/.ssh/config settings

### ISSUE THREAD

**Issue by jeremiahsnapp** [chef/chef#3602]
Users are still asking for the ability to have `knife ssh` and `knife bootstrap` disregard their `~/.ssh/config` file.

An attempt at providing an option to disable the use of `~/.ssh/config` was submitted in the following PR but no action was taken on it.

https://github.com/chef/chef/pull/1003

**Comment by thommay** [comment]
I think #3857 solves most of the reasons people want to do this? If that's not the case, it would be great to have some use cases.
