### ISSUE TITLE
12.4 API breakage: Resource#action no longer casts to Array

### ISSUE THREAD

**Issue by coderanger** [chef/chef#3604]
In 12.3, setting `action(:foo)` on a resource [would upgrade it to `[:foo]` internally](https://github.com/chef/chef/blob/12.3.0/lib/chef/resource.rb#L165). This [was removed in 12.4](https://github.com/chef/chef/blob/12.4.0/lib/chef/resource.rb#L177-L181). This means code that uses the output value of `Resource#action` expecting an array is now broken. For example, [the runit cookbook](https://github.com/hw-cookbooks/runit/blob/v1.6.0/libraries/provider_runit_service.rb#L112).

In 12.3 the docstring comment does specifically state `@return [Array[Symbol]] the list of actions.` so I think we should consider this bound by API compat rules. Notably the same comment is also present on the 12.4 code despite now being incorrect.

This was changed in https://github.com/chef/chef/commit/236570dc9605ac312b44508b1c3a6a0e7c19b4dc.

Ping @jkeiser @thommay @jaym.

**Comment by coderanger** [comment]
Also while I'm staring at this code, the same change added `Resource#action=` which bypasses all validation.

**Comment by jkeiser** [comment]
Huh. I recall making that change specifically because I was seeing resource
actions that were not arrays. Happier with coercion though!

**Comment by coderanger** [comment]
You okay with removing the `action=` validation bypass? I don't think we should have a public API that ignores allowed_actions.

**Comment by jkeiser** [comment]
Yeah, totally.

**Comment by coderanger** [comment]
Roger, PR incoming.

**Comment by jkeiser** [comment]
Let's make sure and coerce the actions into either strings or symbols, too. I vote symbols.

**Comment by coderanger** [comment]
Yep, existing API mandates they be symbols. `arg = Array(arg).map(&:to_sym)`

**Comment by jaym** [comment]
is `allowed_actions` defined twice for a reason?

**Comment by coderanger** [comment]
@jaym You mean the `attr_accesor` and the `def`? That creates both `#allowed_actions` and `#allowed_actions=`, and then immediately overwrites the first one.

**Comment by coderanger** [comment]
I think @jkeiser has been trying to add the `foo=` form in everywhere that uses the "get or set based on argument" format because it makes code look more natural in a non-DSL context.

**Comment by jaym** [comment]
https://github.com/chef/chef/commit/236570dc9605ac312b44508b1c3a6a0e7c19b4dc#diff-135510b4e9e7ac268144bf6a7479a94dR776
https://github.com/chef/chef/commit/236570dc9605ac312b44508b1c3a6a0e7c19b4dc#diff-135510b4e9e7ac268144bf6a7479a94dR967

**Comment by coderanger** [comment]
@jaym instance method vs. class method.

**Comment by jaym** [comment]
ahh... context

**Comment by jkeiser** [comment]
Yep, I've been adding the setter for that reason.

**Comment by tyler-ball** [comment]
If I call `r = SomeResource.new` and then `r.action` I get back a single action.  Is this because the default_action is not an array?

**Comment by coderanger** [comment]
Yeah, working on that now.

**Comment by tyler-ball** [comment]
@coderanger just FYI I saw that same behavior in 12.3. and 12.4

**Comment by coderanger** [comment]
Yeah, I mentioned it over in the PR thread, we need to decide if we want to keep the old behavior the default (usually `:nothing`) is not in an array or call that a bug and have action always return an array in all circumstances like the docstring says it does. I tend towards the latter, but it is a break.

**Comment by jkeiser** [comment]
Please note that it is very possible I wrote that docstring, during 12.4 :)
I would prefer the latter too, but I think I backed off it out of caution.
Might be best to leave the behavior looking like 12.3 in the patch release,
but I could see arguments both ways.

**Comment by coderanger** [comment]
You added it in 12.1 https://github.com/chef/chef/commit/320aa0fe43158c8c89bfab7f1494271eb9da7cd0 so not quite Binding Covenant of the Ages, but still something.

**Comment by coderanger** [comment]
Paging @thommay as Core LT for a judgement call.

**Comment by thommay** [comment]
I'm leaning towards saying that it was a bug when we didn't return an array, so we should correct that and be accurate to the docs.

**Comment by martinb3** [comment]
:+1: Thanks for catching this. It broke some of our chefspec tests where we were checking for specific actions on a resource by passing an array of those actions -- and the action parameter was no longer an array.
