### ISSUE TITLE
I don't understand warning about resource_name in resource_matching_provider()

### ISSUE THREAD

**Issue by docwhat** [chef/chef#3614]
I'm getting the warning from [`resource_matching_provider()`](https://github.com/chef/chef/blob/dbb2e0c36d2585dc10eafd3c73f0af09ff0ff52a/lib/chef/platform/provider_mapping.rb#L198-L211) in Chef 12.4.0 and I don't understand it.

It says:

```
WARN: Class Chef::Provider::DiamondCollector does not declare 'resource_name :diamond
_collector'.
WARN: This will no longer work in Chef 13: you must use 'resource_name' to provide DSL.
```

But if I add `resource_name :diamond_collector` to `Chef::Provider::DiamondCollector` I get a `NoMethodError`.

I can add `resource_name :diamond_collector` to `Chef::Resource::DiamondCollector` and have, as per the [12.4.0 release notes](https://www.chef.io/blog/2015/06/24/chef-client-12-4-0-released/).  Specifically, I use this in the resource:

``` ruby
      if respond_to?(:resource_name)
        resource_name :diamond_collector
      else
        provides :diamond_collector
      end
```

For reference, here is the source of `resource_matching_provider()`:

``` ruby
        def resource_matching_provider(platform, version, resource_type)
          if resource_type.kind_of?(Chef::Resource)
            class_name = resource_type.class.name ? resource_type.class.name.split('::').last : 
              convert_to_class_name(resource_type.resource_name.to_s)

            begin
              result = Chef::Provider.const_get(class_name)
              Chef::Log.warn("Class Chef::Provider::#{class_name} does not declare 'resource_name #{convert_to_snake_case(class_name).to_sym.inspect}'.")
              Chef::Log.warn("This will no longer work in Chef 13: you must use 'resource_name' to provide DSL.")
            rescue NameError
            end
          end
          result
        end
```

I don't understand the `rescue NameError`... is it expecting a problem with `Chef::Provider.const_get(class_name)`? If so, why not check for existence instead of catching an error.  Error catching is slow and it makes the code confusing to read.

**Comment by martinb3** [comment]
I'd also like to understand this one. I'm supplying a `:resource_name` to a resource, and getting the same error. And like @docwhat, I can't use `:resource_name` on the provider without getting an error.

**Comment by lamont-granquist** [comment]
paging @jkeiser

**Comment by jkeiser** [comment]
Yeah, that should say you need to use `provides`, not `resource_name`. An if statement makes more sense than a rescue in this case too, I agree.

**Comment by docwhat** [comment]
I wish I understood what it was trying to do well enough to submit a pull request, @jkeiser.

**Comment by jkeiser** [comment]
Just replacing the word "resource_name" with "provides" in the message should be enough, I think. Your suggestion of using an if statement is good, too.

**Comment by docwhat** [comment]
Okay, submitted a pull request.  @jkeiser please review it carefully, since I don't understand why it returns `nil` by default. :-/
