### ISSUE TITLE
Chef 12.4.1

### ISSUE THREAD

**Issue by jaym** [chef/chef#3616]
The things that need to go into Chef 12.4.1
=================================

In Progress / Resolved
--------------------------------
- [x] https://github.com/chef/chef/pull/3599 *
- [x] https://github.com/chef/chef/pull/3586 *
- [x] https://github.com/chef/chef/pull/3611 *
- [x] https://github.com/chef/chef/pull/3603 *
- [x] https://github.com/chef/chef/pull/3605 *
- [x] #3589 *
- [x] #3587 skipping
- [x] #3620 *
- [x] #3629 *
- [x] #3623 *
- [x] #3627 *
- [x] #3630
- [x] #3638 *

Issues not yet worked on
------------------------------------
- [x] https://github.com/chef/chef/issues/3617

**Comment by ranjib** [comment]
resource_name changes ? are we calling it a bug or intended compat break?

**Comment by jaym** [comment]
I'm not sure what that is. Could you provide an example... things should be backwards compatible

**Comment by tyler-ball** [comment]
I think https://github.com/chef/chef/pull/3605 is going to change the behavior of resources so that `SomeResource.new.action` will be an array

**Comment by jaym** [comment]
@tyler-ball i believe that is how it was in 12.3

**Comment by jaym** [comment]
maybe not

**Comment by jaym** [comment]
cc @coderanger

**Comment by coderanger** [comment]
The main aim of #3605 is to restore the same behavior of 12.3 but we are changing one thing, defaults will now be an array.

**Comment by coderanger** [comment]
But the important fix was `action :foo && action == [:foo]`.

**Comment by ranjib** [comment]
consider a cookbook 'x-foo' having and lwrp file name 'bar'. Earlier resource_name would return :"x-foo_bar", in 12.4 this changed to :x_foo_bar

**Comment by jaym** [comment]
@ranjib we should probably fix that. Thoughts?
cc @chef/client-core

**Comment by jkeiser** [comment]
@jaym @ranjib how would you use a resource named x-foo_bar in a cookbook?  I'm curious, it sort of seems like something that just wouldn't work.

**Comment by ranjib** [comment]
We have an internal a library that implements the zap/authoritative/conf.d
style resource management using chef handler, which uses resource_name to
filter expected resources from resource collection against a directory,
then deletes the unwanted ones.

**Comment by danielsdeleo** [comment]
https://github.com/chef/chef/issues/3618 also :crying_cat_face:

**Comment by jeremiahsnapp** [comment]
@jaym Please add https://github.com/chef/chef/issues/3432 to the 12.4.1 list. It's a pretty big bug preventing users from properly running chef-client as a service on Windows and the fix doesn't look too complicated as I describe in the comment [here](https://github.com/chef/chef/issues/3432#issuecomment-116991259).

**Comment by jaym** [comment]
@jeremiahsnapp #3432 is not a regression we introduced in Chef 12.4.0. I don't think we should block on that.

**Comment by lamont-granquist** [comment]
regressions only for 12.4.1 please

**Comment by danielsdeleo** [comment]
I fixed #3618 but it needs backport. Run `git cherry-pick f0e9b2ffe7ec0904456b50ee26913cb42c0ca258 -m 1` I think.

**Comment by jaym** [comment]
Thanks @danielsdeleo 
I'm going to cherry pick everything when we're ready to ship

**Comment by b-dean** [comment]
None of the issues that were on here seemed to have anything to do with the problem I'm having with the omnibus including `cheffish` so I made issue chef/omnibus-chef#426

**Comment by jkeiser** [comment]
Adding #3638 (fix for #3634) to the roster.
