### ISSUE TITLE
Chef 12.4.0 changed the names of lwrp resources in some cases

### ISSUE THREAD

**Issue by jaym** [chef/chef#3617]
From @ranjib :
consider a cookbook 'x-foo' having and lwrp file name 'bar'. Earlier resource_name would return :"x-foo_bar", in 12.4 this changed to :x_foo_bar

**Comment by lamont-granquist** [comment]
this may have actually fixed a long standing bug

**Comment by jkeiser** [comment]
I'm not sure what to do here.  resource_name == the canonical DSL name seems right.  If we change chef_handler to use _ when searching for LWRPs, or let it use a direct LWRP lookup mechanism, will that help?

**Comment by ranjib** [comment]
i agree that the current behavior is right. hence i was not sure if its a bug. i workaround this by checking for both types, till we migrate.. just to be safe

**Comment by jkeiser** [comment]
@ranjib is it `chef_handler` that was causing the problem?  Basically, is there something we can update to make this easier for users?

**Comment by lamont-granquist** [comment]
Here's an old bug report which may be related:

https://tickets.opscode.com/browse/CHEF-5235

**Comment by jkeiser** [comment]
Yeah, that looks like an actual problem, there.  Now I'm more convinced this is a bugfix, and that sadly cookbooks will need to be updated.

**Comment by ranjib** [comment]
:-) i know, in fact i have decided to promote org_foo for cookbook naming scheme instead of org-foo. given name influence dsl, and methods cant have - etc, only use things in naming scheme that can be used as valid method names, class names etc.

**Comment by lamont-granquist** [comment]
also `:"org-foo"` symbol naming atrocities as well.

**Comment by lamont-granquist** [comment]
in retrospect `-` should not have been legal validation in an uploaded cookbook name, and unfortunately `build-essential` provides an example for new users that is totally wrong.

**Comment by ranjib** [comment]
@lamont-granquist there are many of those. I want to bring them underdown a single CI system, so that we can test them everytime core chef changes, we have to refactor them anyway (to use multi package and other new features).
@jaym if we all are on same page, then lets close this

**Comment by jaym** [comment]
Thanks @ranjib 
I think everyone agrees that the new behavior is what we want.
