### ISSUE TITLE
Can't specify both a version and a recipe in a nodes run_list

### ISSUE THREAD

**Issue by orclev** [chef/chef#3631]
### Version:
12.4.0

### Scenario:
I have a node that I want to run a specific recipe from a cookbook on, but I want to also constrain the version of the cookbook to run.

### Steps to Reproduce:
Add a entry to a nodes run list that specifies both a recipe and a cookbook version, E.G.

    -r "recipe[a_cookbook::cookbook_recipe@1.2.3]"

### Expected Result:
It runs the recipe from the specified version of the cookbook.

### Actual Result:
Generates an error:

    Chef::Exceptions::RecipeNotFound
    --------------------------------
    could not find recipe cookbook_recipe@1.2.3 for cookbook a_cookbook

### Other Info:
Looking at the source code it seems like internally Chef stores the run list as I'd expect with both a recipe and a version, so I'm not sure why the client seems to barf if you specify it in the same format in the run_list.

**Comment by lamont-granquist** [comment]
dup of #3620 #3618
