### ISSUE TITLE
Rails existing process detection fails and causes high CPU utlilization.

### ISSUE THREAD

**Issue by kkeane** [chef/chef#3644]
In Chef-server-coref 12.1.0, if the file /opt/opscode/embedded/service/oc_id/tmp/pids/server.pid exists but the corresponding process does not, rails will be caught in a restart loop, causing a high CPU utilization.

This situation happened to me if the underlying OS crashes and cannot clean up the old pid file.

**Comment by lamont-granquist** [comment]
This repo is only for the chef-client, that bug is against the chef-server/oc_id and needs to be refiled under the chef-server repo:

https://github.com/chef/chef-server/issues/new
