### ISSUE TITLE
Only run restorecon if SELinux is in enforcing mode

### ISSUE THREAD

**Issue by coderanger** [chef/chef#3648]
It would save some execution time to check if selinux is actually being used. Given how rarely it is actually wanted, we can save a few CPU cycles for most people.

**Comment by coderanger** [comment]
Could be done at the config level, make the default value of `enable_selinux_file_permission_fixup` depend on enforcement status.

**Comment by lamont-granquist** [comment]
That was the original way it was designed but it was removed in 26276a26

**Comment by Gazzonyx** [comment]
+1.  

I shouldn't have to set "Chef::Config[:enable_selinux_file_permission_fixup] = false" to unbreak the directory resource when recursively creating a directory where the top level folder doesn't yet exist.

@coderanger , thanks for the work around.

**Comment by nathwill** [comment]
as far as i can see, Chef definitely seems to be doing the right thing here already; i think the cause of the unexpected result is that the `selinuxenabled` utility included with libselinux considers selinux enabled if the selinux mount point has an selinuxfs and if the system has an selinux config file, which is true for all selinux states except "disabled".

```bash
[nathwill@wyrd ~]$ getenforce
Permissive
[nathwill@wyrd ~]$ selinuxenabled
[nathwill@wyrd ~]$ echo $?
0
[nathwill@wyrd ~]$ sudo setenforce 1
[sudo] password for nathwill: 
[nathwill@wyrd ~]$ getenforce
Enforcing
[nathwill@wyrd ~]$ selinuxenabled
[nathwill@wyrd ~]$ echo $?
0

... edit /etc/sysconfig/selinux to disable and reboot...

[nathwill@valhalla ~]$ getenforce
Disabled
[nathwill@valhalla ~]$ selinuxenabled 
[nathwill@valhalla ~]$ echo $?
1
```

one thing to note is that you can change from `permissive` to `enforcing` at runtime, but toggling to or from `disabled` requires a reboot, which gives the system a chance to autorelabel; so, the current logic around running restorecon seems correct (in the sense that following the upstream definition of 'enabled' is obviously the correct thing to do), and i'd guess we would *not* want to only run restorecon when selinux is enforcing, though it's nice that there's a config option to manually override in cases where it's known that selinux will forever remain disabled/permissive.
