### ISSUE TITLE
UI bug - should not be able to drag recipe to available roles list

### ISSUE THREAD

**Issue by ubergeekgirl** [chef/chef#3649]
person in training class suggested this is a UI bug to be able to drag the recipe apache into the available roles list. We found after save that it puts it into the right place, curious on others opinions. this was when swapping the recipe for the role(which now includes the recipe) https://s3.amazonaws.com/uploads.hipchat.com/7557/2341648/GOnAUAo6Dgmcb7t/upload.png

**Comment by coderanger** [comment]
I've refiled this over on the chef-manage-issues tracker. Thanks for the report!
