### ISSUE TITLE
Chef Shell with Chef Zero (local client mode) support/workflow

### ISSUE THREAD

**Issue by spkane** [chef/chef#3658]
Chef Shell does not seem to be able to talk to Chef Zero properly. Chef Shell can be run in solo mode, or against a server, but when the server is a Chef Zero instance, Chef Shell complains about missing client and validation PEM files. Since Chef Zero fakes all the auth and does not actually generate PEM files that can be properly pointed out, it seems that Chef Shell needs direct support for running against Chef Zero. This would be very useful for people using local client mode, who want to setup a Chef Shell testing environment that accurately reflects the workflow they are using.

**Comment by eiser82** [comment]
+1

**Comment by fretb** [comment]
+1
