### ISSUE TITLE
uninitialized constant StringIO (NameError)

### ISSUE THREAD

**Issue by daniel103** [chef/chef#3670]
### Scenario: 
require 'chef/cookbook/metadata' in a ruby script

### Steps to Reproduce:
Create a ruby script and in the require section add
require 'chef/cookbook/metadata'

### Expected Result:
I am able to use the Metadata class to parse metadata.rb files

### Actual Result:
Run time exception:

    /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': uninitialized constant    StringIO (NameError)
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/ffi-yajl-2.2.1/lib/ffi_yajl/ext.rb:42:in `<class:Encoder>'
    from /usr/local/share/gems/gems/ffi-yajl-2.2.1/lib/ffi_yajl/ext.rb:41:in `<module:FFI_Yajl>'
    from /usr/local/share/gems/gems/ffi-yajl-2.2.1/lib/ffi_yajl/ext.rb:30:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/ffi-yajl-2.2.1/lib/ffi_yajl.rb:45:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/chef-12.4.1/lib/chef/json_compat.rb:20:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/share/gems/gems/chef-12.4.1/lib/chef/cookbook/metadata.rb:28:in `<top (required)>'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:144:in `require'

**Comment by coderanger** [comment]
Looks like the actual issue is in ffi-yajl? /cc @lamont-granquist

**Comment by lamont-granquist** [comment]
Yep, looks like I'll be pushing out 2.2.2 later this afternoon...

**Comment by coderanger** [comment]
Upstream issue is fixed, closing this out.
