### ISSUE TITLE
[knife ssh] ERROR: fatal: No live threads left. Deadlock?

### ISSUE THREAD

**Issue by chrisduong** [chef/chef#3675]
Hi, 

When I run this command 

```bash
knife ssh 'name:*' 'sudo service zabbix-agent stop'
```
I've got this error

```
ERROR: fatal: No live threads left. Deadlock?
```
I don't know what causing it. Please help

**Comment by rschwiebert** [comment]
I am getting this too, but the same command works for a coworker who has the same environment as I do. It sounds like knife ssh is getting into a screwed up state locally, somehow.

**Comment by fletchowns** [comment]
I am seeing this as well after upgrading to chefdk 0.8.0.

I've found that it only seems to happen when my search string includes a node that is currently offline.

For example, I know this node is currently running:
```
[vagrant@vagrant ~]$ knife ssh --attribute fqdn 'name:app' 'uptime'
app.mydomain.com  18:40:32 up 125 days,  7:41,  1 user,  load average: 0.00, 0.02, 0.00
```

And I know this node is currently offline:
```
[vagrant@vagrant ~]$ knife ssh --attribute fqdn 'name:volume' 'uptime'
ERROR: fatal: No live threads left. Deadlock?
```

**Comment by rschwiebert** [comment]
I eventually found a comment elsewhere that solved the problem. I think the solution was to move the .chef_dk directory. Something cached there was causing this problem.

**Comment by fletchowns** [comment]
@rschwiebert what is the .chef_dk directory? I'm not seeing a folder with that name on my system.

**Comment by rschwiebert** [comment]
@fletchowns Apologies, I misremembered the name: for me, .chefdk (no underscore) was in my root directory.

**Comment by fletchowns** [comment]
Thanks @rschwiebert! That fixed it, I get the timeout error as expected now for the offline node.
```
[vagrant@vagrant ~]$ mv .chefdk .chefdk_bak
[vagrant@vagrant ~]$ knife ssh --attribute fqdn 'name:volume' 'uptime'
WARNING: Failed to connect to volume.mydomain.com -- Errno::ETIMEDOUT: Connection timed out - connect(2) for "volume.mydomain.com" port 22
```
I asked for help in IRC, same solution was suggested there:
> cheeseplus: I've always nuked my chefDK gems and cruft which anecdotally seems to help

**Comment by thommay** [comment]
OK, this looks like a chefDK gem issue, rather than a bug in chef, so I'm going to close this out.
