### ISSUE TITLE
Resource::Service#supports method ignored with systemd?

### ISSUE THREAD

**Issue by zuazo** [chef/chef#3678]
The `service#supports` method seems to be ignored at least in some cases.

For example, using Chef version `12.4.1` in Debian Jessie with this simple example:

``` ruby
service 'dovecot' do
  supports restart: true, status: true, reload: false
  action [:enable, :start]
end
```

The Chef Run fails with the following error:

```
STDERR: Failed to reload dovecot.service: Job type reload is not applicable for unit dovecot.service
```

But the **reload action is disabled** in the recipe.

We ran into this problem when trying to fix a bug in the [dovecot](https://github.com/onddo/dovecot-cookbook) cookbook (issue https://github.com/onddo/dovecot-cookbook/issues/15).

Another issue maybe related to this: [issue #2756: supports :status => false is ignored on RHEL platforms](https://github.com/chef/chef/issues/2756)

I know the service logic was refactored recently. Perhaps it is related.

Full log:

```
Recipe: dovecot::service


    ================================================================================
    Error executing action `reload` on resource 'service[dovecot]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '3'
    ---- Begin output of /bin/systemctl reload dovecot ----
    STDOUT: 
    STDERR: Failed to reload dovecot.service: Job type reload is not applicable for unit dovecot.service.
---- End output of /bin/systemctl reload dovecot ----
    Ran /bin/systemctl reload dovecot returned 3

    Resource Declaration:
    ---------------------
# In /tmp/kitchen/cookbooks/dovecot/recipes/service.rb

     22: service 'dovecot' do
     23:   supports restart: true, status: true, reload: false
     24:   action [:enable, :start]
     25: end

Compiled Resource:
    ------------------
    # Declared in /tmp/kitchen/cookbooks/dovecot/recipes/service.rb:22:in `from_file'

    service("dovecot") do
      action [:enable, :start]
      updated true
      supports {:restart=>true, :status=>true, :reload=>false}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "dovecot"
      enabled true

      pattern "dovecot"
      declared_type :service
      cookbook_name :dovecot
      recipe_name "service"
    end


Running handlers:

Running handlers complete


[2015-07-16T18:16:12+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
[2015-07-16T18:16:12+00:00] ERROR: service[dovecot] (dovecot::service line 22) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '3'
---- Begin output of /bin/systemctl reload dovecot ----
STDOUT: 
STDERR: Failed to reload dovecot.service: Job type reload is not applicable for unit dovecot.service.
---- End output of /bin/systemctl reload dovecot ----
Ran /bin/systemctl reload dovecot returned 3
[2015-07-16T18:16:12+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by kleini** [comment]
This problem makes deployment on systems using systemd really hard. This are currently Debian Wheezy, RedHat Enterprise Linux 7 and SUSE Linux Enterprise 12 for me.

**Comment by thommay** [comment]
related to #3836?

**Comment by nathwill** [comment]
this could actually be solved pretty cleanly by the systemd unit provider, systemctl provides some handy commands that map to the "supports" concept pretty well:

- try-restart: Restart one or more units if active
- reload-or-restart: Reload one or more units if possible, otherwise start or restart
- reload-or-try-restart: Reload one or more units if possible, otherwise restart if active

i just started a branch to add support for these actions to the systemd_unit resource, should hopefully have a PR ready in the next couple days.

**Comment by kleini** [comment]
Any news here? Stumbled again over a not working systemd provider on systemd based Linux systems where Chef tries to use the reload action although it is not supported by the service and the service resource is defined accordingly.

**Comment by RJSzynal** [comment]
So it's now 2019 and I just ran into the exact same thing nearly 4 years after it was reported. How do more people not run into this?
`  * service[mysql] action reload
    
    ================================================================================
    Error executing action `reload` on resource 'service[mysql]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '3'
    ---- Begin output of /usr/bin/systemctl --system reload mysql ----
    STDOUT: 
    STDERR: Failed to reload mysql.service: Job type reload is not applicable for unit mysqld.service.
    See system logs and 'systemctl status mysql.service' for details.
    ---- End output of /usr/bin/systemctl --system reload mysql ----
    Ran /usr/bin/systemctl --system reload mysql returned 3
    
    Resource Declaration:
    ---------------------
    # In /opt/kitchen/cache/cookbooks/app_db/recipes/install.rb
    
    252: service 'mysql' do
    253:   service_name    node['app_db']['service']
    254:   supports        restart: true, status: true, reload: false
    255:   action          :start
    256:   notifies        :run, 'ruby_block[wait for mysql]', :immediately
    257: end
    258: 
    
    Compiled Resource:
    ------------------
    # Declared in /opt/kitchen/cache/cookbooks/app_db/recipes/install.rb:252:in `from_file'
    
    service("mysql") do
      action [:start]
      updated true
      supports {:restart=>true, :status=>true, :reload=>false}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "mysql"
      enabled true
      running true
      masked false
      pattern "mysql"
      declared_type :service
      cookbook_name "app_db"
      recipe_name "install"
    end
    
    System Info:
    ------------
    chef_version=12.22.5
    platform=centos
    platform_version=7.5.1804
    ruby=ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
    program_name=chef-client worker: ppid=32;start=10:00:39;
    executable=/opt/chef/embedded/bin/chef-client`

**Comment by kleini** [comment]
https://code.open-xchange.com/#contentPanel;BhOg6voVu9;null;resources/ox_reload_detection.rb;content
