### ISSUE TITLE
Change hardcoded 1hr in knife status -h

### ISSUE THREAD

**Issue by jblaine** [chef/chef#3679]
This is a pre-screen for a feature that I am committing to implementing. I don't want to do work that is just going to get rejected, so I'd like to start the conversation here.

`knife status` has:

        -H, --hide-healthy               Hide nodes that have run chef in the last hour

It's poor.

# Why?

1. For one, the definition of "healthy" is overloaded here to be "a host that has run chef". It makes no check in the code to determine if the chef run was successful, so it has the capability to provide false positives for "health". Just because a node object was saved with `ohai_time` set doesn't mean the Chef run was successful. There are exception handlers like `lastrun` that intentionally save the node object on exception.
2. The 1 hour hardcoded time is totally arbitrary. Perhaps "healthy" to others means "nodes that have run chef in the last 4 hours" (or 30 minutes, or 3 days...).

# Option 1: Least disruptive
Add an optional argument of "MINS". Not specifying it will result in the previous behavior of checking for "healthy" hosts where "healthy" means ohai_time was in the last hour. This does not solve "Why: 1" above. It also is odd in that it is taking an optional argument. I don't believe I've seen any other Chef command allow for that.

        -H, --hide-healthy MINS         Hide nodes that have run chef in the last hour (or MINS)

# Option 2: Fully corrected
This removes "health" and "healthy" from wording so does not set expectations. It keeps the short option as '-H'. It also requires MINS. Commence option name bikeshedding... in 3... 2... 1...

        -H, --hide-by-time MINS         Hide nodes that have run chef in the last MINS minutes.

Thoughts?

**Comment by juliandunn** [comment]
I like option 2. You're right -- "healthy" is misleading. After all, the node could be checking in and still have the flu :grin:

**Comment by alanwthatcher** [comment]
I would love to see option 2 for sure.  I actually had the same exact thoughts when I saw this command after starting to use chef a few weeks ago!

**Comment by icberg7** [comment]
It also appears that the `-H` switch doesn't actually do anything, as does not exclude nodes that have updated recently; they're in there along with everything else.
(note that I've changed the server names)
```
[icberg7@vm1 ~]$ knife status -H | tail
103 hours ago, server10, redhat 6.6.
75 hours ago, server09, redhat 6.7.
8 hours ago, server08, redhat 6.7.
8 hours ago, server07, redhat 6.7.
5 hours ago, server06, redhat 6.6.
4 hours ago, server05, redhat 6.7.
28 minutes ago, server04, redhat 6.6.
23 minutes ago, server03, redhat 6.7.
20 minutes ago, server02, redhat 6.7.
2 minutes ago, server01, redhat 6.7.
```

I've seen this behavior with knife running under both chefdk-0.5.1 and chefdk-0.6.2

**Comment by jblaine** [comment]
@juliandunn et al, is there anyone else who should review this idea before I start writing the fix?

**Comment by juliandunn** [comment]
I'd just say to see if @chef/client-core has any feedback, otherwise go for it.

**Comment by danielsdeleo** [comment]
Seems reasonable to me.

**Comment by jblaine** [comment]
```
[@dev:~/src/chef/lib/chef/knife] 3679-knife-status 1 ± knife status
32 minutes ago, dev, centos 7.1.1503.
[@dev:~/src/chef/lib/chef/knife] 3679-knife-status ± knife status -H 33

[@dev:~/src/chef/lib/chef/knife] 3679-knife-status ± knife status --hide-by-mins 33

[@dev:~/src/chef/lib/chef/knife] 3679-knife-status ± knife status --hide-by-mins 30
32 minutes ago, dev, centos 7.1.1503.
[@dev:~/src/chef/lib/chef/knife] 3679-knife-status ±
```
The blank lines in the output courtesy of knife/core/ui.rb:msg() using `puts` without checking whether or not there is anything to put. It's rampant in Chef. Drives me nuts :)

**Comment by jblaine** [comment]
The blank lines fixed in 3778 :)
