### ISSUE TITLE
LWRP unable to find template it its own cookbook - instead looking in callers template folder

### ISSUE THREAD

**Issue by vinyar** [chef/chef#3681]
chef-client 12.0.1-1

I have a library cookbook with an LWRP where the provider constructs a template (FOO)
LWRP uses use_inline_resource.
Cookbook B calls the LWRP located in the library
Chef run fails because cookbook B does not have template FOO.

Expectation:
Library cookbook consumes templates in its own directory structure.
Cookbook consuming the LWRP should have no awareness of templates

Actual:
Chef run fails with generic can't find template error. The error is coming from Cookbook B.

Work around:
Placing the template file into the caller cookbook (Cookbook B) solves the issue.
This is not a good behavior because now every single cookbook that uses the LWRP has to contain a copy of the template.

Code:
```ruby
action :shutdown_for_realz do

  template shutdownManageServers_script do
    source 'shutdownManageServers.py.erb'
    mode '0644'
    variables(
    ...
      )
  end

  execute 'shutdown_for_realz' do
    command <<-EOH
      java -cp #{wlst_jar} weblogic.WLST #{shutdownManageServers_script} #{new_resource.domain_name}
    EOH
   # notifies :delete, "file[#{checkServerStatus_script}]", :immediately
   end

end

```
Seems like this might be a regression in 12.0.1
May be related to below:
https://tickets.opscode.com/browse/CHEF-5050
and discussion here: http://lists.opscode.com/sympa/arc/chef/2011-04/msg00111.html

**Comment by coderanger** [comment]
This is expected, add `cookbook 'A'` to the template resource in your provider code.

**Comment by vinyar** [comment]
@coderanger Hmm..  So this means that I can't use any LWRP that builds a template internally without modifying the source cookbook?

Also, what do you mean by `add cookbook 'A'` to the template resource in provider? Do you happen to have a code sample I could reference?

**Comment by coderanger** [comment]
First example I found, in the [`httpd` cookbook](https://github.com/chef-cookbooks/httpd/blob/f2fa39a4d6c2ea2dff9cb9d866ae28e05231735a/libraries/provider_httpd_service_rhel_sysvinit.rb#L14-L23). Note how the template resource inside the action has both the `source` and `cookbook` properties set.

**Comment by coderanger** [comment]
As for not being able to use LWRPs, if an LWRP was written incorrectly then yes, you may need to fix it.

**Comment by vinyar** [comment]
another reference: https://tickets.opscode.com/browse/CHEF-5052

I think the fix to this behavior will have to be done via RFC. Thanks @coderanger
