### ISSUE TITLE
chef-windows-service does not work unless run from opscode\chef\bin

### ISSUE THREAD

**Issue by jaym** [chef/chef#3688]
When `opscode\chef\bin` is not in the path, this breaks. See https://github.com/opscode-cookbooks/chef-client/issues/325

A simple solution here is to remove this from `embedded\bin` so that people can't even run it. Or we could detect the omnibus directory.

**Comment by btm** [comment]
https://github.com/chef/chef/issues/3952 looks like a dupe, but it's got a little more information. Closing in favor of that issue.
