### ISSUE TITLE
Chef::DataBagItem.save does not properly validate names with periods

### ISSUE THREAD

**Issue by vinyar** [chef/chef#3697]
BUG:
Databag item ID can not contain period " . " when created through `knife databag` commands or via `chef manage` UI.

However, they can be created from inside the recipe via code with `Chef::DataBagItem.new`; `raw_data` &  `.save`
Once the Databag Item is created via the recipe, the item can be edited via the GUI but can't be refreshed via `knife databag` command

Workaround:
This issue manifested itself when trying to save server names and state data in a data_bag. Since FQDN contains periods, we had to write gsub() code to convert dots ' . ' to underscores ' _ '.

**Comment by vinyar** [comment]
Related: https://github.com/chef/chef/blob/master/lib/chef/data_bag_item.rb#L38

**Comment by vinyar** [comment]
@kumar_charan for additional input

**Comment by lamont-granquist** [comment]
Better solution would probably be to add the validation to the `#save` method to prevent creating data bag items that have invalid keys.

**Comment by vinyar** [comment]
Neato. It's fixed  👍 
(after 5 years)

**Comment by lamont-granquist** [comment]
that broke the world, we cannot do that outside of a major breaking change.

we can try to fix some of the APIs to work with '.'s in the name, but generally we need to throw WARNs everywhere people do this because some usages can never be fixed (our use of solr uses '.' as a field separator which is a feature that will never be modified, so at some point everyone doing this runs out of runway and crashes into an unfixable bug).

**Comment by hrak** [comment]
This also broke chef vaults, since chef vault clients usually contain FQDN's

```
knife vault rotate keys myvault myitem --clean-unknown-clients -M client
WARN: Removing unknown client 'removed.node.example.com'
ERROR: Chef::Exceptions::InvalidDataBagItemID: Data Bag items must have an id matching /^[\-[:alnum:]_]+$/, you gave: "privateRegistry_key_removed.node.example.com"
```

This is with the latest Chef workstation 21.7.524

**Comment by marcparadise** [comment]
What makes the period invalid? 

Chef Server does accept periods in data bag/dbi names.

**Comment by sanga1794** [comment]
@marcparadise  We have already replaced error with deprecation warning but We can fix the other functionality too and make the knife command line work as it's working for recipe and allow user to pass "  . " period In databag_item names .. is this what is expected? I will go ahead and make the changes in that case.
