### ISSUE TITLE
Action Purge doesn't actually purge packages

### ISSUE THREAD

**Issue by tas50** [chef/chef#3699]
If a package is removed, but not purged and you use the action purge nothing happens:

Example:
package %w(popularity-contest whoopsie landscape-common command-not-found command-not-found-data) do
  action :purge
end

From the Chef run:

Recipe: core::packages
- apt_package[popularity-contest, whoopsie, landscape-common, command-not-found, command-not-found-data] action purge (up to date)

DPKG output:
dpkg -l | grep landscape
rc  landscape-client                 14.12-0ubuntu0.14.04                amd64        The Landscape administration system client
rc  landscape-common                 14.12-0ubuntu0.14.04                amd64        The Landscape administration system client - Common files

**Comment by lamont-granquist** [comment]
So, this is going to be kind of invasive to the existing provider code.  Right now you're either an installed_version or not.  The logic is boolean, not trinary.  Adding another state for removed-but-not-purged is going to be complicated and messy, particularly after the multipackage stuff.

The provider really /should/ work this way, but given the effort involved vs. the payoff, the priority of fixing this is pretty low.

Also, the apt provider is already a horrible mess and really needs cleanup before we start adding more features to it.  That and the yum-provider are my go-to examples of how accreting more and more open source PRs for features is not good software development.
