### ISSUE TITLE
Time sync - need clarification only

### ISSUE THREAD

**Issue by katmai** [chef/chef#3707]
Hi guys, so before going full production mode, i decided today to upgrade from 12.0.7 to 12.1. Everything went smooth except for 1 thing: 

So i upgraded / ran the opscode reconfigure / chef-server upgrade / cleanup then i rebooted the chef server.

After reboot, i noticed that all my 4 dev devices looked like they had the last check in about 5 days ago.

Trying to run manually the chef client on the nodes rendered:

```
Authentication Error:
---------------------
Failed to authenticate to the chef server (http 401).
The request failed because your clock has drifted by more than 15 minutes.
Syncing your clock to an NTP Time source should resolve the issue.
```

I ran the ntp and no corrections to time was made, the servers had no time issues.

Then i rebooted the dev machine and everything went back to normal.

Now my question is ... is this a normal behavior, like you have to reboot all nodes (i think not, seems silly) or am i missing something here? I didn't check the time / date on the chef server before the reboot, but i would like to get to the bottom of this as i want to get into production.

Any help would be greatly appreciated.
Thank you.

**Comment by juliandunn** [comment]
`ntpd` won't make corrections to the system clock if the drift is too large. It will just fail silently (unless you happen to inspect the logs). You need `ntpdate` for that. Chances are what happened is that when you rebooted your box, the OS ran an `ntpdate` and brought the clock into sync.

**Comment by indipopz** [comment]
I have successfully bootstraped my node. with a few changes i have pushed the cookbook to the server. but when i am running the cookbook on my node i am getting this error.


![screen shot 2016-09-23 at 3 09 01 pm](https://cloud.githubusercontent.com/assets/22254803/18781578/048c37ce-81a0-11e6-99d2-aa8ba66426b6.png)
