### ISSUE TITLE
OS X 10.11 - Chef Ruby reports wrong information about the host's OS/Kernel on

### ISSUE THREAD

**Issue by natewalck** [chef/chef#3708]
### Version:
Chef: 12.3.0

### Environment:
OS X 10.11 15A226f

### Scenario:
Get system version from ruby so we can gate functionality to specific versions of OS X

### Steps to Reproduce:
```
/opt/chef/embedded/bin/chef-shell
chef > RbConfig::CONFIG['host_os']
 => "darwin12.5.0"
chef >
```

### Expected Result:
Using System Ruby, it  looks like this:
```
/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/irb
irb(main):001:0> RbConfig::CONFIG['host_os']
=> "darwin15"
irb(main):002:0>
```
### Actual Result:
It shows a version of "darwin12.5.0" which is incorrect.

**Comment by natewalck** [comment]
It occured to me that Chef ruby was most likely compiled on a 10.8.5 machine (12.5 Darwin kernel).

This isn't actually what the machine is running, it is what it was compiled on.

**Comment by lamont-granquist** [comment]
Yeah expected behavior, use `=~ /^darwin/` or use ohai instead of RbConfig.
