### ISSUE TITLE
Redhat service provider action :disable ignores run level 1

### ISSUE THREAD

**Issue by cachamber** [chef/chef#3709]
When a redhat service calls the :disable action, chkconfig <service> off is called.  This only changes the service startup for run levels 2,3,4 and 5 - per the chkconfig man page.   This can cause services that run in run level 1 or 6 to be marked as updated every chef run when attempting to disable them.

While the resolution for this issue has been discussed in Pull Request #1120, this issue is focused on the disable action.  I was asked to create an issue to track the disable side of the solution.

**Comment by tas50** [comment]
I'm going to close this out at this point since systemd has eaten the world and make the legacy providers less important for modern setups.
