### ISSUE TITLE
Chef download RPM  for centos7.1

### ISSUE THREAD

**Issue by indraindu** [chef/chef#3712]
Hi,
    I have tried to install chef in centos7.1 image,but it fails and shows 404 error,but when i try that url it redirects,no such 404 error found and also i can see etc/chef. I installed in centos 7 platform ,in that platform version it takes 7(i.e., &pv=7),but in centos7.1 it takes as &pv=Derived from Red Hat Enterprise Linux 7.But i can found etc/chef/solo.rb file ,i cannot able to download rpm file in centos7.1 Following errors posted below:

 Redirecting to /bin/systemctl stop  iptables.service

 Failed to issue method call: Unit iptables.service not loaded.

 echocurl found: command not found

 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

I, [2015-07-19T23:57:18.718860 #22437]  INFO -- :                                   Dload  Upload   Total   Spent    Left  Speed

I, [2015-07-19T23:57:18.718928 #22437]  INFO -- : 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

I, [2015-07-19T23:57:19.185445 #22437]  INFO -- : 
100 18711  100 18711    0     0  40100      0 --:--:-- --:--:-- --:--:-- 40066
100 18711  100 18711    0     0  40091      0 --:--:-- --:--:-- --:--:-- 40066

I, [2015-07-19T23:57:19.189565 #22437]  INFO -- :  Downloading Chef 11.4.4 for el...

I, [2015-07-19T23:57:19.189639 #22437]  INFO -- : downloading http://opscode.com/chef/metadata?v=11.4.4&prerelease=false&nightlies=false&p=el&pv=Derived from Red Hat Enterprise Linux 7&m=x86_64

I, [2015-07-19T23:57:19.189710 #22437]  INFO -- :  to file /tmp/install.sh.979/metadata.txt

I, [2015-07-19T23:57:19.189779 #22437]  INFO -- :  trying curl...

I, [2015-07-19T23:57:19.615474 #22437]  INFO -- :  ERROR 404

I, [2015-07-19T23:57:19.615564 #22437]  INFO -- :  Omnitruck artifact does not exist for version 11.4.4 on platform el

I, [2015-07-19T23:57:19.615631 #22437]  INFO -- : 

I, [2015-07-19T23:57:19.615698 #22437]  INFO -- :  Either this means:

I, [2015-07-19T23:57:19.615764 #22437]  INFO -- :     - We do not support el

I, [2015-07-19T23:57:19.615830 #22437]  INFO -- :     - We do not have an artifact for 11.4.4

I, [2015-07-19T23:57:19.615895 #22437]  INFO -- :

I, [2015-07-19T23:57:19.615963 #22437]  INFO -- :  This is often the latter case due to running a prerelease or RC version of chef

I, [2015-07-19T23:57:19.616034 #22437]  INFO -- :  or a gem version which was only pushed to rubygems and not omnitruck.

I, [2015-07-19T23:57:19.616100 #22437]  INFO -- :

I, [2015-07-19T23:57:19.616171 #22437]  INFO -- :  You may be able to set your knife[:bootstrap_version] to the most recent stable

I, [2015-07-19T23:57:19.616239 #22437]  INFO -- : release of Chef to fix this problem (or the most recent stable major version number).

I, [2015-07-19T23:57:19.616306 #22437]  INFO -- :

I, [2015-07-19T23:57:19.616374 #22437]  INFO -- :  In order to test the version parameter, adventurous users may take the Metadata URL

I, [2015-07-19T23:57:19.616443 #22437]  INFO -- :  below and modify the '&v=<number>' parameter until you successfully get a URL that

I, [2015-07-19T23:57:19.616508 #22437]  INFO -- : does not 404 (e.g. via curl or wget).  You should be able to use '&v=11' or '&v=12'

I, [2015-07-19T23:57:19.616576 #22437]  INFO -- :  succesfully.

I, [2015-07-19T23:57:19.616650 #22437]  INFO -- :

I, [2015-07-19T23:57:19.616751 #22437]  INFO -- : If you cannot fix this problem by setting the bootstrap_version, it probably means

I, [2015-07-19T23:57:19.616823 #22437]  INFO -- :  that el is not supported.

I, [2015-07-19T23:57:19.616892 #22437]  INFO -- :

I, [2015-07-19T23:57:19.616963 #22437]  INFO -- : Metadata URL: http://opscode.com/chef/metadata?v=11.4.4&prerelease=false&nightlies=false&p=el&pv=Derived from Red Hat Enterprise Linux 7&m=x86_64

I, [2015-07-19T23:57:20.681222 #22437]  INFO -- :  Copying embedded executables to /usr/bin

I, [2015-07-19T23:57:21.723432 #22437]  INFO -- :  cp: error reading â€˜/proc/sysrq-triggerâ€™: Input/output error

I, [2015-07-19T23:57:21.723518 #22437]  INFO -- :  cp: failed to extend â€˜/usr/bin/proc/sysrq-triggerâ€™: Input/output error

Thamks&regards,
Indra

**Comment by juliandunn** [comment]
What command are you actually running to get this?

**Comment by indraindu** [comment]
In my /etc/redhat-release  file ,i ve Derived from Hat Enterprise Linux 7&m=x86_64 when i changed to CentOs Linux release 7.1.1503(Core).It works for me.why such change we need?
Thanks & regards,
indra

**Comment by juliandunn** [comment]
I have no idea, but CentOS doesn't ship that way -- someone must have modified the /etc/redhat-release file on your system.

**Comment by dermarens** [comment]
I had the same problem using their cloud images from http://cloud.centos.org/centos/7/images/ which were released on the same day as the fix for this problem https://git.centos.org/blob/rpms!centos-release.git/f3a9a7fb3d640e80ed979be291330537a174d6b9/SPECS!centos-release.spec which probably didn't make it into the images.

Maybe they updated the images some time ago, maybe they didn't. I didn't redownload/check them but simply modified our already shrunk cloud image which was much easier.

See https://github.com/chef/opscode-omnitruck/pull/86 for more infos.
