### ISSUE TITLE
Bootstrapping using chef-full.erb and csh as login shell fails

### ISSUE THREAD

**Issue by decrazyo** [chef/chef#3718]
### Version:

Chef Development Kit Version: 0.6.2
chef-client version: 12.4.1
berks version: 3.2.4
kitchen version: 1.4.0
### Environment:

Workstation: OS X 10.9.5
Client: RHEL 6.4
### Scenario:

I'm attempting to bootstrap chef onto a RHEL 6.4 system using knife and the default chef-full template.
The login shell on this system, and all systems in my environment, is c shell.
The syntax of the script produced by chef-full.erb is incompatible with c shell and bootstrapping fails.
### Steps to Reproduce:

Provision a RHEL 6.4 system.
Change the default login shell to c shell.
bootstrap the system from a workstation using knife as follows.
knife bootstrap <client> --ssh-user <user> --ssh-password <pass> --node-name <name> --sudo --use-sudo-password
### Expected Result:

chef-client should be installed and the node added to the chef server as normal.
### Actual Result:

c shell is unable to launch bourne shell to do the dirty work because it chokes on the newlines in the bootstrap script. STDERR follows.

XXX.XXX.XXX.XXX Unmatched '.
XXX.XXX.XXX.XXX TMPDIR: Undefined variable.
XXX.XXX.XXX.XXX tmp=/tmp: Command not found.
XXX.XXX.XXX.XXX else: endif not found.
### Possible Fix:

As a quick workaround I escaped all newlines in chef-full.erb including those inserted by the ERB code and the bootstrapping process worked perfectly.

**Comment by juliandunn** [comment]
Yeah, I suspect that's a problem. We would take a PR. The file is here: https://github.com/chef/chef/blob/master/lib/chef/knife/bootstrap/templates/chef-full.erb

**Comment by lamont-granquist** [comment]
Yeah, so the workaround here is not to change the default login shell for your provisioning user.

If this is a problem on FreeBSD generally (which IIRC has csh for the root user shell), then we can bump the priority up, but right now its not very high priority.

**Comment by dheeraj86mathur** [comment]
I am using csh and getting exact same issue at time of bootstrap ? can you confirm what exactly is the solution ?

**Comment by lamont-granquist** [comment]
We are not going to have the bandwidth to address this.  We'd accept a user driven PR, but offhand I'm not even certain what the correct way to go about fixing it would be, and don't even have the bandwidth to investigate.

**Comment by lamont-granquist** [comment]
actually #8885 may fix this
