### ISSUE TITLE
Docker recepie

### ISSUE THREAD

**Issue by adyanthaya17** [chef/chef#3722]
Hi, I wanted to know where I could find the docker recepies for my chef cookbook.

**Comment by coderanger** [comment]
Not entirely sure what you mean, but Chef is not integrated with Docker in any specific way that I can imagine you would be referring to. If you are looking for help with Chef you can ask questions in the IRC channel or mailing list.

**Comment by adyanthaya17** [comment]
Chef has cookbooks containing recepies. I wanted to add the docker recepie to it.

**Comment by coderanger** [comment]
I think maybe you are looking for a cookbook to install Docker? You can find a list on the Supermarket cookbook sharing site: https://supermarket.chef.io/cookbooks?utf8=%E2%9C%93&q=docker&platforms[]=

These are not directly part of Chef itself, they are community maintained add-ons if you will.

**Comment by ranjib** [comment]
@adyanthaya17 chef is the framework using which recipes/cookbooks are written. cookbooks itself are not part of chef, they are distributed via community cookbook repo (supermarket) or from github.
there are more than one docker cookbooks available, just google chef docker . this is the first hit: https://github.com/bflad/chef-docker
if you dont know how to use community cookbooks ask in mailing list, read some basic tutorials. this issue tracker is strictly for the chef framework, in particular the client codebase.

**Comment by adyanthaya17** [comment]
I did clone the https://github.com/bflad/chef-docker but when I try to upload the cookbook it gives me an error:

root@chef-server:/home/oss/chef-repo/cookbooks# knife cookbook upload chef-docker
/home/oss/chef-repo/cookbooks/chef-sugar-master/lib/chef/sugar/version.rb:19: warning: already initialized constant Chef::Sugar::VERSION
/home/oss/chef-repo/cookbooks/chef-sugar/lib/chef/sugar/version.rb:19: warning: previous definition of VERSION was here
ERROR: Could not find cookbook chef-docker in your cookbook path, skipping it
ERROR: Failed to upload 1 cookbook.

**Comment by coderanger** [comment]
This is an issue tracker for bug reports and patches for Chef itself. If you are looking for help to learn Chef please check out https://learn.chef.io/

**Comment by ranjib** [comment]
@adyanthaya17 as mentioned twice, seek help  on mailing list/irc channels
