### ISSUE TITLE
`backward` notifiers feature

### ISSUE THREAD

**Issue by melezhik** [chef/chef#3723]
Hi Opscode guys! I want to share an idea.
What if chef resources were able to notify another resources to get converged in `backward` way. I mean let we have a resource A gets converged and then notifying resource B to get converged, so first A and then B - this default direction and what if I need first converge B ( before A ) and then A?

Just an _abstract_ example:
```
file '/foo/bar/baz' do
   action: nothing
end 

# this execute will run every time, despite :creates modifier  

 execute 'echo' do
  :creates '/foo/bar/baz'
  :notifies :remove , 'file[/foo/bar/baz]', :immediately, :before => true 
end
 ```

**Comment by lamont-granquist** [comment]
What you're suggesting I guess isn't really a notification.   Notifications fire after the resource and only if the resource changed the state of the system.  What you are suggesting is more like a precondition where you always want to fire a resource before the resource you are executing.  But you can always do that simply by including the resource prior to the current resource.  If you just change your `action :nothing` there to `action :remove` then it accomplishes what you are trying to do.

This might result in repeated resources in the resource collection and CHEF-3694 issues, but there is currently a proposal to eliminate resource cloning which would better allow duplicated resources.

For more complicated code wrapping the resources up in an LWRP or in a recipe and using include_recipe can assure that they run first.

So, I'm not seeing what practical problem this solves that can't be solve better via other means, and don't understand why there's the need to complicate the landscape with more features.

**Comment by melezhik** [comment]
Thanks for feedback @lamont-granquist , the example I gave here is not very understandable, let me try another one: I need restart some service but _only if_ some other precondition happens. Whatever you call it ( I may assume that I chose not proper terminology in the beginning ) , this is how people tends to think  - do something , but only if something before this is  successfully executed. The accent here is on the main action , not on the precondition, like one may write an pseudo code for this:

          Restart tomcat service only_if war file is downloaded successfully 

Here we have got 2 resources tomcat service and remote file.  I know it might be expressed in standard chef workflow - first remote file and then notifying service tomcat to restart . Mine syntax is more compact and closer to what a man would think - do something  only if something before this is done. 

To continue think about it, what if I need add some other preconditions, like checking consistently of downloaded war file ? So I would have this:

          Restart tomcat service only_if war file is downloaded successfully and it is a valid java archive


In case of any of preconditions fails I expect chef raise an exception, so tomcat won't restart. 


I do not want talk here about chef inner implementation, yes I understand it might impact a current design , it just an idea how one may write chef recipes in more effective way.

**Comment by lamont-granquist** [comment]
That sounds like subscribes.  Use a service resource to subscribe to a remote_file resource to download a war file.  You can setup a chain of subscribes from the service resource to a ruby_block or execute resource that validates the file to the remote_file as well.

**Comment by melezhik** [comment]
Yeah, subscribes are fine, really.

But I what I really need is to specify _precondition resources calls_ on the side of "dependent" resource, not on the side of "precondition" resources.  

Main idea is to _invert_ notifications syntax, when one focuses more on _"main"_ resource converge rather than on preconditions needs executed before this ... Do you understand me? It's just about convenience, and this is really how people, not programs tends to think: 

**"This is main part, I need to focus on it, and yeah there are also some  supplemental parts, I will tell you about them right away, but let's focus on main part first  ... "**

Let me give you another more realistic examples, _based_ on official chef doc for notifiers / subscribes. 

Imagine, we need _unconditionally_ restart nagios every time, but before this we need to verify that configuration is not broken ( whatever/whoever could broke it   ). Here we go:

```

# this is the _main_ part
# we focus on unconditional nagios restart

service 'nagios3' do
  supports :restart => true, :reload => true
  action :restart
  # here we also  define some preconditions chain
  notify :run, 'execute[test-nagios-config]', :before
  notify :run, 'execute[yet-another-test-nagios-config]', :before
end

# this is the preconditions chain
execute 'test-nagios-config' do
  command 'nagios3 --verify-config'
  action :nothing
end

execute 'yet-another-test-nagios-config' do
  command 'nagios3 --verify-config --yet-another-way'
  action :nothing
end

```

**Comment by melezhik** [comment]
And yes, whatever you call it not notifiers, subscribes or preconditions - the idea is what I described in  previous comment. Initially I thought that notifies will be good for it, but if we need other _implementation_  we can change  the topic of the issue  :)

**Comment by coderanger** [comment]
As stated before, the way to do this is just put the code in the order you want it to run, just like any other code you've written before.

**Comment by lamont-granquist** [comment]
Yep, just run the execute block to verify nagios config.  If its busted then an exception will get thrown out of the shell command and out of the execute resource and will stop the chef-client run -- because you really need to halt ASAP at that point.  Then if its not busted, force the nagios restart with the service resource.

Just let execution order solve the problem, and then there's not a lot of need for `action :nothing` resources that are always going to run, which is just confusing.

Gonna close this, I don't think its something that is widely wanted.

**Comment by melezhik** [comment]
Guys, thanks for feedback. I still feel that you probably missing my point. This is not like chef currently is not sufficient for me, I have been using chef for years and it is great , but I try to tell about how it can be improved. Classic way with resources list that are executed in order is ok, but it lacks of agility sometimes. 

That's fine. You may close this issue.
