### ISSUE TITLE
Chef Solo - Missing Data Bag results in a misleading error

### ISSUE THREAD

**Issue by emiller42** [chef/chef#3727]
Hello!

Ran into this in some local development.  Steps are somewhat simple:

1)  Reference a local data bag item in a cookbook.
2)  Make sure that data bag item does not exist locally.
3)  Attempt a kitchen converge using the cookbook

When Chef Solo attempts to access the local data bag, It throws a Validation Exception stating "Data Bag Items must contain a Hash or Mash!".

While technically correct, this error masks the real issue which is that the data bag item doesn't exist at all.  

Ideally, Chef would throw an accurate message indicating that the data bag item is not found when this is the case.  Instead of attempting to load it and passing what I can only assume is nil through self.from_hash().

**Comment by lamont-granquist** [comment]
Yeah Chef Solo doesn't support data bags, you should really use Chef Zero which does.

The error message does suck, but its unlikely we'll allocate the resources to fix that one.  Generally we're trying to push people away from using Chef Solo and to using Chef Zero because of issues like this.

**Comment by emiller42** [comment]
Didn't realize this was still open.  Closing it out, as Chef Zero was indeed the way to go.
