### ISSUE TITLE
service idempotency not correct in AIX

### ISSUE THREAD

**Issue by alanwthatcher** [chef/chef#3730]
When using an LWRP like the following on AIX with Chef 12:

```ruby
service "xntpd" do
 supports :restart => true
 action [ :start ]
end
```

The recipe will always report it is starting the service, even when the service is already running.  Idempotency seems to not be functioning properly.

**Comment by juliandunn** [comment]
Does it only affect this particular service, `xntpd`? How about other ones?

**Comment by alanwthatcher** [comment]
I have tried so far on xntpd and sshd service, with the same result.  I did see in the code where it calls the function that uses "lssrc -s" to check if running.  And, I've confirmed that it should see both of those services as active.

**Comment by alanwthatcher** [comment]
This appears to be an issue with shell_out possibly, specifically the "is_resource_group?" in the provider/service/aix.rb file.  I say this because I did was able to get the services recognized as active if I removed the is_resource_group? check.  Also, interestingly, I noticed that the output of lssrc commands is being displayed on the terminal as chef-client is being run.  Below is an output of what I see from a normal chef-client run without the modified code.  You can see the output of "lssrc -g", which is to determine if the service is actually a service group, and the output of the "startsrc -s " command.

~~~~~~~~~~~~~~~
* service[xntpd] action start0513-086 The xntpd Group is not on file. 
0513-029 The xntpd Subsystem is already active. 
Multiple instances are not supported. 

    - start service service[xntpd] 
  * service[sshd] action start0513-086 The sshd Group is not on file. 
0513-029 The sshd Subsystem is already active. 
Multiple instances are not supported. 

    - start service service[sshd] 
~~~~~~~~~~~~~~~

**Comment by alanwthatcher** [comment]
I have been able to "patch" the problem to an extent on my test system.  This isn't the correct way however, because the problem seems to stem from the shell_out! not handling the output of "lssrc -g" command when the service_name is not, in fact, a group.  Whenever I rely on just "lssrc -g #{@new_resource.service_name}" to try and determine if the resource is a service group, the code executes the rescue block in my code (below).  When actually executed from the command line the output is:

~~~~~~~~~~~~
# lssrc -g xntpd 
0513-086 The xntpd Group is not on file.
~~~~~~~~~~~~

Here is the replacement function that I currently have working.  As I'm fairly new to Chef and Ruby, this may not be the most elegant way, but so far it is what I have come up with.  The actual fix, I think, will have to be in the shell_out command.

~~~~~~~~~~~~
        def is_resource_group? 
         Chef::Log.debug "Determining if #{@new_resource} is a resource group" 
         begin 
          group = shell_out!("lssrc -a|grep #{@new_resource.service_name}").stdout 
          Chef::Log.debug ("#{group}") 
          if group.split(' ')[1] == "#{@new_resource.service_name}" 
            Chef::Log.debug "#{@new_resource.service_name} is a resource group" 
            @is_resource_group = true 
          else 
            Chef::Log.debug "#{@new_resource.service_name} is not a resource group" 
            @is_resource_group = false 
          end 

           # ShellOut sometimes throws different types of Exceptions than ShellCommandFailed. 
           # Temporarily catching different types of exceptions here until we get Shellout fixed. 
           # TODO: Remove the line before one we get the ShellOut fix. 
         rescue Mixlib::ShellOut::ShellCommandFailed, SystemCallError 
            Chef::Log.debug "#{@new_resource.service_name} service group status is undertermined, defaulting to false" 
           @status_load_success = false 
           @is_resource_group = false 
           nil 
         end 
        end 
~~~~~~~~~~~~

**Comment by juliandunn** [comment]
@alanwthatcher What version of the Chef Client are you using? Some of that code looks like it dates from pre-12.4.0, which is when I made a few changes to the service group parsing mechanism to solve [unreliability issues](https://github.com/chef/chef/pull/3327).

**Comment by alanwthatcher** [comment]
Chef version:
~~~~~~
 # chef-client --version
Chef: 12.4.1
~~~~~~~

When "lssrc -g " is called for a non-service group name, the shell_out fails.  That is why I switched it for the "lssrc -a | grep".  I added the rescue block for testing.  In the original code logic, this caused it to default back to the service not being started, and therefore always issuing the startsrc command.

**Comment by juliandunn** [comment]
I'm firing up an LPAR to see if I can repro this but... apparently IBM Power Development Platform has a backlog on reservations for several days so it's going to take a while :frowning:

**Comment by alanwthatcher** [comment]
I will try and look more into it this week. Debug level of logs didn't
produce any informative messages, except when I modified the function call
to log a message that confirmed that the shell_out bombed. When I tried
spit out the contents of the variable holding the shell_out output, it was
just blank.

The problem must reside down at that level, I am just trying to work
backwards, but am new to Ruby. So.

Let me know any way I might be able to assist. Thanks for your efforts!

**Comment by juliandunn** [comment]
Yeah, if you can figure out a repro case just outside of Chef with only mixlib-shellout and the original `lssrc -g` call to see what's happening, that'd be splendid.

**Comment by alanwthatcher** [comment]
To be honest, I don't know how to go about doing that.  If you can point me toward an example, I would be more than happy to make it happen.

**Comment by juliandunn** [comment]
You can do this right within a `pry` session on the LPAR like so:

```
$ /opt/chef/embedded/bin/pry
[1] pry(main)> require 'mixlib/shellout'
=> true
[2] pry(main)> s = Mixlib::ShellOut.shell_out!("lssrc -g ... ")
=> <something>
```

and then seeing what exception is being thrown and/or inspecting the `s` object to see what it looks like. Thanks Alan!

**Comment by alanwthatcher** [comment]
Ok.  So here is what I ended up with.  I couldn't run the commands as you have above on either aix or linux.  So I searched around a bit, and the best I could come up with so far is what I am pasting below.

I started with just using the command "hostname" (cmd variable, line 3 for output), to get an idea of what the output should look like.  The next command is for a subsystem group that does exist (cmd2, line 5).  And the third for the subsystem group that does not exist (cmd3, line 7).

There were no errors raised during my testing.  The things I see of note are the output about "less" not being installed, which it is not.  And that the command for the subsystem group that does not exist (cmd3) exits with a status of 1, but the output is in stdin, and not stderr. I forced a bad command with the same method on a linux system and confirmed that stderr is where the output went on that system.  So I am not sure if that could be part of the cause?

I am going to continue to poke around.  Best way to learn.

~~~~~~~~~~~~~~~~~~~~~~~
/ # /opt/chef/embedded/bin/pry
[1] pry(main)> require 'mixlib/shellout'
which: 0652-141 There is no less in /usr/bin /etc /usr/sbin /usr/ucb /usr/bin/X11 /sbin /usr/local/bin.
=> true
[2] pry(main)> cmd = Mixlib::ShellOut.new("hostname")
=> <Mixlib::ShellOut#2288063720: command: 'hostname' process_status: nil stdout: '' stderr: '' child_pid: nil environment: {} timeout: 600 user:  group:  working_dir:  >
[3] pry(main)> cmd.run_command
=> <Mixlib::ShellOut#2288063720: command: 'hostname' process_status: #<Process::Status: pid 15597692 exit 0> stdout: 'savdclvbox01aix1.nfcutest.net' stderr: '' child_pid: 15597692 environment: {} timeout: 600 user:  group:  working_dir:  >
[4] pry(main)> cmd2 = Mixlib::ShellOut.new("lssrc -g ras")
=> <Mixlib::ShellOut#2285387240: command: 'lssrc -g ras' process_status: nil stdout: '' stderr: '' child_pid: nil environment: {} timeout: 600 user:  group:  working_dir:  >
[5] pry(main)> cmd2.run_command
=> <Mixlib::ShellOut#2285387240: command: 'lssrc -g ras' process_status: #<Process::Status: pid 15597694 exit 0> stdout: 'Subsystem         Group            PID          Status
 syslogd          ras              4653206      active' stderr: '' child_pid: 15597694 environment: {} timeout: 600 user:  group:  working_dir:  >
[6] pry(main)> cmd3 = Mixlib::ShellOut.new("lssrc -g xntpd")
=> <Mixlib::ShellOut#2284014100: command: 'lssrc -g xntpd' process_status: nil stdout: '' stderr: '' child_pid: nil environment: {} timeout: 600 user:  group:  working_dir:  >
[7] pry(main)> cmd3.run_command
=> <Mixlib::ShellOut#2284014100: command: 'lssrc -g xntpd' process_status: #<Process::Status: pid 16777456 exit 1> stdout: '0513-086 The xntpd Group is not on file.' stderr: '' child_pid: 16777456 environment: {} timeout: 600 user:  group:  working_dir:  >
[8] pry(main)>
~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by alanwthatcher** [comment]
While I couldn't produce an actual error in the pry session, I did tinker with the actual command being executed in service/aix.rb and it does seem that any command that exits with exit code 1 (maybe others, not sure) does seem to cause the same kind of behavior.

**Comment by alanwthatcher** [comment]
Thanks.  I made the change locally and it works great.  I also learned something about shell_out vs shell_out!.
