### ISSUE TITLE
Wrong IP address reported in OpenVZ containers

### ISSUE THREAD

**Issue by ameir** [chef/chef#3731]
I have never been able to get the correct IP address reported on OpenVZ containers.  I instead always get 127.0.0.2 as the IP.

Here's a screenshot from the management console:
http://take.ms/8q2bA # note that the last one is VMWare, not OpenVZ.

The partial `ifconfig` output from a container is below.
```
venet0    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:127.0.0.2  P-t-P:127.0.0.2  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
          RX packets:3282819 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3515429 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:4235147025 (4.2 GB)  TX bytes:4100779262 (4.1 GB)

venet0:0  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:x.x.x.184  P-t-P:x.x.x.184  Bcast:x.x.x.184  Mask:255.255.255.255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
```

I suggest that if multiple IPs are returned, Ohai/Chef keep the first one that *doesn't* start in "127".  It may be worth noting that `hostname -i` returns the correct IP.

**Comment by lamont-granquist** [comment]
This most likely needs to be refiled as an ohai bug in http://github.com/chef/ohai/issues/new
