### ISSUE TITLE
Better error message when user tries to write to a badly-declared property

### ISSUE THREAD

**Issue by jkeiser** [chef/chef#3734]
```ruby
class Foo < Chef::Resource::LWRPBase
  resource_name :foo
  attribute :myhash, default: {}
  attribute :mylist, default: []
end
foo 'x' do
  mylist << 'hi'
  myhash[:a] = 10
end
```

Emits this error:

`ERROR: can't modify frozen Array`

We should put something explaining the situation, if we can.

We might want to warn on property declaration in the case of empty array and empty hash anyway, as they are super common.

**Comment by martinb3** [comment]
I'll attempt this one :)

**Comment by coderanger** [comment]
More specifically, it would be cool to put a `rescue` in the Property getter code that catches RuntimeError and looks the string `"can't modify frozen"` in the message value. If present, rewrite the message to include some more info, then reraise.

**Comment by danielsdeleo** [comment]
@martinb3 let me know if you need help navigating the error inspector stuff

**Comment by martinb3** [comment]
@danielsdeleo thanks! I looked over what's currently in there, and it doesn't look too bad.

**Comment by coderanger** [comment]
I don't think this needs to touch the error inspector code, we can scope it inside the Property code more directly.

**Comment by jkeiser** [comment]
I like that solution @coderanger, much more likely to be accurate!

**Comment by jkeiser** [comment]
oh wait, no, it can't work because the error happens *after* you get the property (when you decide how to use it).

**Comment by coderanger** [comment]
Oh right, ignore me!

**Comment by martinb3** [comment]
It might also be a useful/interesting/helpful error message for cookbook authors for other cases of frozen variables, if any exist.

**Comment by danielsdeleo** [comment]
@martinb3 the one that I know about is `ENV` vars:

```
[2] pry(main)> ENV['PATH'].downcase!
RuntimeError: can't modify frozen String
from (pry):2:in `downcase!'
```

**Comment by martinb3** [comment]
Just noticing there's a related [warning already in place](https://github.com/chef/chef/blob/master/lib/chef/resource.rb#L811-L813).

e.g.
```
       Synchronizing Cookbooks:
         - foo (0.1.0)
       Compiling Cookbooks...
       [2015-08-06T13:55:15+00:00] WARN: Property #<Class:0x000000052b7ac8>.myhash has an array or hash default ({}). This means that if one resource modifies or appends to it, all other resources of the same type will also see the changes. Either freeze the constant with `.freeze` to prevent appending, or use lazy { {} }.
       [2015-08-06T13:55:15+00:00] WARN: Property #<Class:0x000000052b7ac8>.mylist has an array or hash default ([]). This means that if one resource modifies or appends to it, all other resources of the same type will also see the changes. Either freeze the constant with `.freeze` to prevent appending, or use lazy { [] }.
```

**Comment by martinb3** [comment]
Created PR for this one. I haven't ever touched this part of the chef code, so any feedback is welcome! :)
