### ISSUE TITLE
Provide a way to override chef-client loggers.

### ISSUE THREAD

**Issue by docwhat** [chef/chef#3735]
Due to the way the `Chef::Application.configure_logging()` [resets `Chef::Log`](https://github.com/chef/chef/blob/master/lib/chef/application.rb#L137), it is impossible to add aditional loggers to `Chef::Log.loggers`.

My use case is that I would like my server nodes to use [`logstash-logger`](https://github.com/dwbutler/logstash-logger) to log all warnings, errors and fatals.  While I could use `loc_location` in `client.rb` the problem is that I want to send the meta information as JSON _without_ the timestamp and severity string that gets added to messages.

This would also make the WinEvt and Syslog loggers much simpler to understand and not require `Mixlib::Unformatter` (which smells bad).

You could rewrite the `loc_location` stuff to use the default ruby file logger (sort of like `MonoLogger` but simpler) when given a string (or IO object) and include a different way to add additional custom loggers.

**Comment by lamont-granquist** [comment]
@jaym could you look at this?

**Comment by docwhat** [comment]
My PR #3736 actually didn't fix this problem.  It is *sort of* on the right track, but it would have to be much more complicated because `:log_location` is set by default in many places.

I have a feeling that a lot of the logging has to be simplified.  Right now it takes looking through 6+ different files across 2 different projects to understand what's going on.

**Comment by lamont-granquist** [comment]
:+1:  on simplifying the logging, it is definitely overly complicated.
