### ISSUE TITLE
registry_key resource is not idempotent

### ISSUE THREAD

**Issue by Roviluca** [chef/chef#3742]
hello,

to have a chef resource not idempotent make me really sad.
Can you make the resource idempotent or at least a method to check if the resource is in the desired state so i can us it inside (only | not)_if?

something similar (or very easily better) to:

    def registry_in_desired_state?(key, name, value)
        registry = registry_get_values(
          key,
          :machine
        )

        for element in registry do
          if element[:name] == name
              if element[:data] == value
                return true
               end
          end
        end
        return false
      end

thank you

**Comment by tylergohl** [comment]
I noticed something potentially similar, but I think in my case Chef was trying to enforce case sensitivity on the windows registry, when it is not case sensitive.  So if you have a registry entry for `server` and a chef resource that is trying to create `Server` - chef will continually attempt to run that resource and update it.

**Comment by jkerry** [comment]
I had a pull request merged recently to fix the case sensitivity issue.

**Comment by lamont-granquist** [comment]
We definitely need a better, repeatable bug report since it is certainly intended that the registry_key resource is idempotent.  We can't fix "its not idempotent, sad" without a replication case and will most likely just close this ticket as unactionable.

**Comment by Roviluca** [comment]
I think Tylergohl identified the issue in a better way so, since jkerry said that he pushed the fix, i'll check again when i have the new version installed.
