### ISSUE TITLE
ifconfig resource does not work with bootproto DHCP (or does not work at all)

### ISSUE THREAD

**Issue by kkeane** [chef/chef#3745]
Configuration: CentOS 6, chef-client 12.4.1

It seems to not be possible to use the ifconfig resource to generate a DHCP network configuration. The documentation is also contradictory - among the examples, there are two that show identical resource configurations, yet claim two different generated configuration files.

It also generates ifcfg files with an incorrect name.

The specific issue I found:

Using the following resource:

ifconfig "eth1" do
  device "eth1"
  onboot "yes"
  bootproto "dhcp"
end

Expected result (on CentOS 6):

It should generate a file /etc/sysconfig/network-scripts/ifcfg-eth1 with (at least) the following content:

DEVICE="eth1"
BOOTPROTO=dhcp
NM_CONTROLLED=no
ONBOOT=yes
TYPE=Ethernet
IPV4_FAILURE_FATAL=yes

Preferably, the hardware address and, for CentOS 7, also a UUID should be included.

Actual result:

The file name misses the device name suffix (i.e., it is called ifcfg- instead of ifcfg-eth1) and contains an IP address.

ONBOOT=yes
BOOTPROTO=dhcp
IPADDR=eth1

It appears that there are architectural issues with this resource; a non-breaking fix may be difficult. My recommendation is to deprecate this resource (and provide either a new resource, or a cookbook)

Architectural issues:
- The resource seems to assume that the name is an IP address. It should be a device name (or an arbitrary resource name) instead.
- The relationship between specifying an IP address in the resource name, and through the inet_addr attribute is not clear.
- The relationship between device and target is not clear.
- Interfaces can have either multiple IP addresses, or may not have any IP address at all (such as with DHCP).
- Many essential configuration options are apparently not supported. For instance, you cannot specify a default gateway or DNS Servers.
- No support for IPv6.
- No support for bridging, vlans etc.

**Comment by kkeane** [comment]
As a workaround, it appears that there is a third-party cookbook on the supermarket: network_interfaces_v2 . I have not yet tested it.

**Comment by lamont-granquist** [comment]
The ifconfig provider is somewhat unloved.
