### ISSUE TITLE
Chef-client bootstrapping fails on Windows XP (32-bit)

### ISSUE THREAD

**Issue by aditya-wate** [chef/chef#3753]
While bootstrapping a Windows XP node on VirtualBox from an Ubuntu workstation, it fails at the first run of chef-client. Could you please confirm if Win XP is supported by Chef.

**```ruby version -> ruby 1.9.3p551 (2014-11-13) [i386-mingw32]```**
**```gem version -> 2.4.8```**

PF the logs below:

--
C:\Documents and Settings\IEUser\My Documents\rubygems-2.4.8\rubygems-2.4.8>chef
-client
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/ffi-1.9.8-x86-mingw32/lib/ffi/
library.rb:261:in `attach_function': Function 'Wow64DisableWow64FsRedirection' n
ot found in [kernel32.dll] (FFI::NotFoundError)
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/win32-eventlog-0.
6.1/lib/win32/windows/functions.rb:42:in `<module:Functions>'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/win32-eventlog-0.
6.1/lib/win32/windows/functions.rb:4:in `<module:Windows>'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/win32-eventlog-0.
6.1/lib/win32/windows/functions.rb:3:in `<top (required)>'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/win32-eventlog-0.
6.1/lib/win32/eventlog.rb:3:in `require_relative'
        from C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/win32-eventlog-0.
6.1/lib/win32/eventlog.rb:3:in `<top (required)>'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.0.0/rubygems/core_ext
/kernel_require.rb:54:in `require'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.0.0/rubygems/core_ext
/kernel_require.rb:54:in `require'
        from C:/opscode/chef/embedded/apps/chef/lib/chef/event_loggers/windows_e
ventlog.rb:30:in `<top (required)>'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.0.0/rubygems/core_ext
/kernel_require.rb:54:in `require'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.0.0/rubygems/core_ext
/kernel_require.rb:54:in `require'
        from C:/opscode/chef/embedded/apps/chef/lib/chef/client.rb:41:in `<top (
required)>'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.0.0/rubygems/core_ext
/kernel_require.rb:54:in `require'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.0.0/rubygems/core_ext
/kernel_require.rb:54:in `require'
        from C:/opscode/chef/embedded/apps/chef/lib/chef/handler.rb:18:in `<top
(required)>'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.0.0/rubygems/core_ext
/kernel_require.rb:54:in `require'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.0.0/rubygems/core_ext
/kernel_require.rb:54:in `require'
        from C:/opscode/chef/embedded/apps/chef/lib/chef.rb:32:in `<top (require
d)>'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.0.0/rubygems/core_ext
/kernel_require.rb:54:in `require'
        from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.0.0/rubygems/core_ext
/kernel_require.rb:54:in `require'
        from C:/opscode/chef/embedded/apps/chef/bin/chef-client:23:in `<top (req
uired)>'
        from C:/opscode/chef/bin/chef-client:63:in `load'
        from C:/opscode/chef/bin/chef-client:63:in `<main>'

--

Thanks
Aditya
![screen shot 2015-08-04 at 10 30 46 am](https://cloud.githubusercontent.com/assets/8527583/9063100/f31b31a6-3a93-11e5-86dc-5204cceee8d2.png)

**Comment by adamedx** [comment]
@aditya-wate, Windows XP is no longer offered for mainstream support by the OS vendor, and it is also not listed as a supported platform by Chef. See the following document for supported platforms, which lists the Windows versions below: https://github.com/chef/chef-rfc/blob/master/rfc021-platform-support-policy.md:

Windows	7, 8, 8.1, 2008, 2008R2, 2012, 2012R2

Can you try this on a later version of Windows? Things should work fine if you use a supported platform.

**Comment by aditya-wate** [comment]
@adamedx : Thanks for the confirmation. I presumed so. Actually I already have bootstrapped Windows 7, but we also wanted an XP machine. I also read the documentation but wanted to be sure, since sometimes there's a fix is in progress but not mentioned in the doc.
