### ISSUE TITLE
Chef randomly returning Net::SSH::HostKeyMismatch after Vagrant and VirtualBox update

### ISSUE THREAD

**Issue by dfduarte** [chef/chef#3755]
Hello there!

Recently, I've updated my Vagrant to 1.7.4, and my Virtualbox to 5.0 version in order to fix a boring bug on Virtualbox in my Ubuntu. 

However, now, randomly Chef returns a SSH key mismatch error, when I do a new bootstrap with some virtual machines. As follow:

Doing old-style registration with the validation key at /home/xxxxxx/chef-repo/.chef/xxxxxxx-validator.pem...
Delete your validation key in order to use your user credentials instead

<i>
Connecting to vm1
ERROR: Net::SSH::HostKeyMismatch: fingerprint b6:b9:3a:f7:ab:e6:a5:00:10:01:f5:f7:79:ec:75:00 does not match for "vm1,172.16.1.2"
Doing old-style registration with the validation key at /homexxxxxxxx/chef-repo/.chef/xxxxxx-validator.pem...
Delete your validation key in order to use your user credentials instead

Connecting to vm2
ERROR: Net::SSH::HostKeyMismatch: fingerprint 01:b5:2b:df:a8:69:82:6d:36:f8:80:4f:ab:3d:88:cc does not match for "vm2,172.16.1.3"
</i>
I don't know if any chef update has broke something, but, thats it. My Chef-DK version, is:

<b>A workaround to this problem, its removing the vm hosts from ~/.ssh/know_hosts, but it's very tricky to do every time I have to destroy  these machines.

Chef Development Kit Version: 0.6.2
chef-client version: 12.3.0
berks version: 3.2.4
kitchen version: 1.4.0

**Comment by lamont-granquist** [comment]
That's expected behavior, this is just how ssh host keys work.  You probably need to use StrictHostKeyChecking=no in your `~/.ssh/config` file inside of some Host section that matches your virts.

**Comment by spuder** [comment]
To remove the offending key from your ~/.ssh/config file use `ssh-keygen -R`

`ssh-keygen -R 192.0.2.0`

Or bootstrap with the `--no-host-key-verify` option (not recommended since less secure)

`knife bootstrap 192.0.2.0 --no-host-key-verify`
