### ISSUE TITLE
Console output is way too much

### ISSUE THREAD

**Issue by kayssun** [chef/chef#3756]
I am not sure if I did not see some configuration option, but since Vagrant 1.7.4, chef produces a lot of debug output between the normal, configurable log messages. Every template gets dumped to stdout and it is hard to find the actual log messages.

Example:
```
==> luebbe_b2c: [2015-08-06T13:38:10+00:00] INFO: cookbook_file[/root/.config/fish/local.fish] owner changed to 0
==> luebbe_b2c: [2015-08-06T13:38:10+00:00] INFO: cookbook_file[/root/.config/fish/local.fish] group changed to 0
==> luebbe_b2c: [2015-08-06T13:38:10+00:00] INFO: cookbook_file[/root/.config/fish/local.fish] mode changed to 750
==> luebbe_b2c:     
==> luebbe_b2c: - change mode from '' to '0750'
==> luebbe_b2c:     
==> luebbe_b2c: - change owner from '' to 'root'
==> luebbe_b2c:     
==> luebbe_b2c: - change group from '' to 'root'
```

The first three lines are correct, the next lines are always shown, even when I decrease log verbosity.

I guess this is more likely something in chef than vagrant and I would really like to help but I could not locate the problem yet.

**Comment by dfduarte** [comment]
Tip:

Try to go to your knife.rb file, and add the following line:

log_level                :info

If this line already exists, but it have something like :debug, change it to :info and try again.

**Comment by kayssun** [comment]
I am not using knife but librarian.

If I set this in my Vagrantfile: 

```
node.vm.provision 'chef_solo' do |chef|
      chef.log_level = :warn
end
```

the three first "INFO:" messages disappear, but this is not what I want since everything else is still printed to the terminal.

**Comment by lamont-granquist** [comment]
We haven't changed anything in how the logging works, this is almost certainly a vagrant issue.
