### ISSUE TITLE
ChefFSDataStore.exists_dir? is slow on large repositories

### ISSUE THREAD

**Issue by tpodom** [chef/chef#3761]
@jkeiser I was able to trace the additional slowness during `depsolve` to the `exists_dir?` check.

If the cookbook repository is large then the `exists_dir?` operation is slow because it iterates the entire cookbook file system.  In the example repository https://github.com/tpodom/slow-repo the `exists_dir?` takes 0.36 seconds to execute.  Since this method is executed during the `depsolve` process it results in walking the entire file system multiple times.

The scenario that is slow is when `exists_dir?` is called on a cookbook directory because it calls `list` on the cookbooks root.  `list` then walks all of the cookbooks but each cookbook in turn calls its own `children` to check `can_upload?`.

There are two potential improvements I can think of.  One is to modify `eixsts_dir?` to instead check the single path.  Another potential improvement would be to rewrite `ChefRepositoryFileSystemCookbookDir::can_upload?` to have it exit early if it finds any child since it's just checking size > 0.

**Comment by lamont-granquist** [comment]
@jkeiser is this the same as the perf bug as the one you fixed in 12.5.0, or is this another one?

**Comment by erkki** [comment]
This is def another one, seeing (and currently debugging) this as well on 12.9.41. What's (essentially, at the end) a (per cookbook) Dir.exists? takes about 60s on a not so large collection of cookbooks.

**Comment by vsingh-msys** [comment]
@lamont-granquist I came across the same situation while working on `chefignore` file lookup per instance get created multiple times for `ChefRepositoryFileSystemCookbookDir` class per cookbook in `children` traversal, so we can also improve that as well.
