### ISSUE TITLE
[bug] in Chef::Platform.find_provider 12.4.1

### ISSUE THREAD

**Issue by dennybaa** [chef/chef#3765]
Hello,

there seems to be a bug in platform detection mechanism. Invocation of the code bellow
```ruby
Chef::Platform.find_provider('ubuntu', '14.04', :service)
```

throws an exception - *Chef::Exceptions::ProviderNotFound: Cannot find a provider for...*

PS. Checked on 12.3.0, works correct.

 \- Denis

**Comment by lamont-granquist** [comment]
Chef::Resource#provider_for_action is the public interface you should be using in Chef 12.

**Comment by dennybaa** [comment]
@lamont-granquist Thanks for an idea! I've thought that the `find_provider` is also okay since it was (mb. is) used in mysql cookbook, which seems to be well done.

**Comment by lamont-granquist** [comment]
It doesn't any more...

**Comment by lamont-granquist** [comment]
Closing this, pretty sure we broke this interface in 12.0 with the introduction of the ProviderResolver.
