### ISSUE TITLE
PostgreSQL relation "users" not found while running Chef 12 on RHEL 6

### ISSUE THREAD

**Issue by shashank-sriva** [chef/chef#3766]
While trying to run chef-server-ctl reconfigure on an RHEL6.5 server, received below error.
==========================================
[2015-08-11T07:53:19+09:00] ERROR: Exception handlers complete
Chef Client failed. 32 resources updated in 177.750828388 seconds
[2015-08-11T07:53:19+09:00] FATAL: Stacktrace dumped to /opt/opscode/embedded/cookbooks/cache/chef-stacktrace.out
[2015-08-11T07:53:20+09:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[bootstrap-platform] (private-chef::bootstrap line 45) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml ----
STDOUT:
STDERR: /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/adapters/postgres.rb:211:in `async_exec': PG::UndefinedTable: ERROR:  relation "users" does not exist (Sequel::DatabaseError)
LINE 1: INSERT INTO "users" ("username", "email", "public_key", "ser...
                    ^
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/adapters/postgres.rb:211:in `block in execute_query'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/database/logging.rb:28:in `log_yield'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/adapters/postgres.rb:211:in `execute_query'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/adapters/postgres.rb:198:in `block in execute'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/adapters/postgres.rb:177:in `check_disconnect_errors'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/adapters/postgres.rb:198:in `execute'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/adapters/postgres.rb:312:in `block (2 levels) in execute'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/database/connecting.rb:230:in `block in synchronize'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/connection_pool/threaded.rb:101:in `hold'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/database/connecting.rb:230:in `synchronize'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/adapters/postgres.rb:312:in `block in execute'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/adapters/postgres.rb:467:in `check_database_errors'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/adapters/postgres.rb:310:in `execute'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/dataset/actions.rb:744:in `execute'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/adapters/postgres.rb:581:in `fetch_rows'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/dataset/actions.rb:803:in `returning_fetch_rows'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/dataset/actions.rb:297:in `insert'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/adapters/shared/postgres.rb:879:in `insert'
        from /opt/opscode/embedded/service/gem/ruby/2.1.0/gems/sequel-3.34.1/lib/sequel/adapters/shared/postgres.rb:881:in `insert'
        from ./bin/bootstrap-platform:83:in `bootstrap'
        from ./bin/bootstrap-platform:120:in `<main>'
---- End output of /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml ----
Ran /opt/opscode/embedded/bin/bundle exec ./bin/bootstrap-platform ./bootstrapper-config/config.rb ./bootstrapper-config/pivotal.yml returned 1

**Comment by EssentialMix** [comment]
I had same issue. Looks like something was not created from first kick: chef-server-ctl reconfigure
For resolving this just run: chef-server-ctl cleanse
It will cleanup everything, after that run again: chef-server-ctl reconfigure
Works for me now.

**Comment by shashank-sriva** [comment]
Wow!! Thanks EssentialMix :)) I will try it & let you know :)) Thank you so
much :))

On Fri, Aug 28, 2015 at 11:28 PM, EssentialMix <notifications@github.com>
wrote:

> I had same issue. Looks like something was not created from first kick:
> chef-server-ctl reconfigure
> For resolving this just run: chef-server-ctl cleanse
> It will cleanup everything, after that run again: chef-server-ctl
> reconfigure
> Works for me now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chef/chef/issues/3766#issuecomment-135846823>.
>



-- 
*Warm Regards,*
*Shashank Srivastava,*
Linux Administrator, HCL Technologies Ltd. Noida SEZ,
M.C.P., M.C.T.S. (.NET 2.0 Windows Application Development)
http://softybits.blogspot.com
http://mymusicrevu.blogspot.com

**Comment by thommay** [comment]
Hi, this is a chef-server bug, which has its own repository. If you're still having a problem, please open a new ticket at https://github.com/chef/chef-server/issues/new .
Thanks!
