### ISSUE TITLE
chef-client breaking change to recipe list in node object

### ISSUE THREAD

**Issue by theckman** [chef/chef#3767]
There appears to be a breaking change between `12.1.1` and `12.4.1` in how the recipe list is posted back to the chef server.

In `12.1.1`, the recipes posted back are both expanded and unexpanded. In other words, if you have the recipe `int-service::default` in your run list, the recipe list will have `int-service` and `int-service::default`.

In `12.4.1`, the unexpanded version (`int-service`) is no longer posted back. As such, if you had a search like: `recipes:int-service` the node will no longer be returned in the search results.

This looks to be a breaking change in `chef-client`. Should this change be made for a minor release version (i.e., `12.1` to `12.4`) or should it be a change introduced in `13.x`?

**Comment by ranjib** [comment]
@danielsdeleo @lamont-granquist @thommay  are we considering this as bug, or as intended.

**Comment by adamhjk** [comment]
smells like us fixing a bug that caused unintended consequences to me. @danielsdeleo @thommay ?

**Comment by jeffbyrnes** [comment]
I believe this refers to chef/chef#2312.

**Comment by Tyrael** [comment]
just got bitten by this, surprised that it is known for this long and nothing was done to fix/articulate this change.

**Comment by lamont-granquist** [comment]
the prior behavior is that you randomly might or might not get one or the other, so reverting is most likely the solution that nobody wants.

either `foo::deafult` should always become `foo` or else both `foo::default` and `foo` should always appear.
