### ISSUE TITLE
chef-server behind nginx proxy returns the wrong URL for bookshelf API

### ISSUE THREAD

**Issue by vladuemilian** [chef/chef#3773]
I have chef-server installed behind front-end machine with nginx which redirects the requests for a specify domain to the chef-server machine. So, for `chef.mydomain.com`, all requests will be redirected to `172.26.100.100` which holds the chef-server.

From my workstation (which is not in the same private network), I want to manage my environment. Everything works fine with `knife`, except `knife cookbook upload` command.

It seems that chef-server is giving me the wrong URL for bookshelf API, instead of `https://chef.mydomain.com/organizations/myorg/...` it gives `https://172.26.100.100/organizations/myorg/...` which cannot be resolved.

In documentation I found that `bookshelf['external_url']` will change that URL. I put it in `chef-server.rb` configuration file, but after i did a `chef-server-ctl reconfigure` the output is the same.

Chef-server version: `12.0.3`

Output of `knife cookbook upload -a -VV`

```
...
...
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating PUT to https://172.26.100.100/organizations/myorg/sandboxes/a7785ecca3d8a4334be4ac5c846c3fba

```

This is my `chef-server.rb`

```
nginx['enable_non_ssl']=true
nginx['non_ssl_port']=80

server_name = "chef.mydomain.com"
api_fqdn server_name

nginx['url'] = "https://#{server_name}"
nginx['server_name'] = server_name
nginx['ssl_certificate'] = "/var/opt/opscode/nginx/ca/chef.mydomain.com.crt"
nginx['ssl_certificate_key'] = "/var/opt/opscode/nginx/ca/chef.mydomain.com.key"
lb['fqdn'] = server_name
lb['api_fqdn'] = server_name
lb['bookshelf'] = server_name
bookshelf['vip'] = "https://#{server_name}/"
bookshelf['external_url'] = "https://chef.mydomain.com"
bookshelf['url'] = "https://#{server_name}/"
```

How can I change the URL from `172.26.100.100` to `chef.mydomain.com`? Why `bookshelf['external_url']` not changing it like is written in documentation? I did something wrong?

**Comment by thommay** [comment]
This has been previously filed as chef/chef-server#473, which will be looked at by the server team in due course. Please don't file multiple identical bugs against different repositories.
