### ISSUE TITLE
Installation fails on RHEL 6.6

### ISSUE THREAD

**Issue by scriptmonkey** [chef/chef#3781]
When I issue:
 rpm -Uvh --test /tmp/chef-server-core-12.1.2-1.el6.x86_64.rpm

I receive the following error:
installing package chef-server-core-12.1.2-1.el6.x86_64 needs 212MB on the /opt filesystem

I have over a Gig available on the /opt filesystem.  I did test the creation if a 1GB file, so the space is available and writable.  Hopefully, it is something simple.

**Comment by scriptmonkey** [comment]
This is totally my fault.

I see on this link:
https://docs.chef.io/chef_system_requirements.html

That /opt needs 5GB.  

Would it be possible to alter the error message to provide the proper space?
Thanks!

**Comment by coderanger** [comment]
This error message comes from RPM, not Chef. 99% certain we have no control over it.

**Comment by scriptmonkey** [comment]
I see.  I appreciate your input.   I apologize for not looking at the requirements.
