### ISSUE TITLE
`berk upload` fails due to syntax error

### ISSUE THREAD

**Issue by noradaiko** [chef/chef#3782]
What is this file?
https://github.com/chef/chef/blob/master/spec/data/cookbooks/borken/recipes/default.rb

It causes a syntax error and I can't upload cookbooks with berkshelf.

**Comment by lamont-granquist** [comment]
you need to not have your cookbook path pointing at that directory, those are internal cookbooks for the chef-client's unit testing framework, some of which need to be deliberately broken to test behavior of the code when a cookbook is broken

**Comment by noradaiko** [comment]
Thanks.

It occurs only if gems are installed with `bundle install --path vendor/bundle` in my case.
So I stripped the path option and the error has gone.
