### ISSUE TITLE
chef-server-ctl doesn't understand shell quoting

### ISSUE THREAD

**Issue by Martin-S-Weber** [chef/chef#3784]
``chef-server-ctl user-create username First Last first.last@example.org "failure to deal with shell quotes" --filename first.last.chef.pem``

or

``chef-server-ctl user-create username First Last first.last@example.org "'failure to deal with shell quotes'" --filename first.last.chef.pem``

lead to:

``FATAL: Wrong number of arguments
USAGE: knife opc user create USERNAME FIRST_NAME [MIDDLE_NAME] LAST_NAME EMAIL PASSWORD``

**Comment by lamont-granquist** [comment]
This needs to be reported in the chef-server repo, this repo is for the client.  

http://github.com/chef/chef-server/issues/new
