### ISSUE TITLE
require 'chef' fails on Windows 8.1 with Ruby 2.2

### ISSUE THREAD

**Issue by WaffleSouffle** [chef/chef#3785]
irb
    irb(main):001:0> require 'chef'
    NameError: uninitialized constant Process::Constants::FFI
            from c:/ruby/Ruby22-x64/lib/ruby/gems/2.2.0/gems/win32-process-0.7.5/lib/win32/process/constants.rb:4:in `<module:Constants>'
            from c:/ruby/Ruby22-x64/lib/ruby/gems/2.2.0/gems/win32-process-0.7.5/lib/win32/process/constants.rb:3:in `<top (required)>'
            from c:/ruby/Ruby22-x64/lib/ruby/gems/2.2.0/gems/win32-process-0.7.5/lib/win32/process.rb:2:in `require_relative'
            from c:/ruby/Ruby22-x64/lib/ruby/gems/2.2.0/gems/win32-process-0.7.5/lib/win32/process.rb:2:in `<top (required)>'
            from c:/ruby/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
            from c:/ruby/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
            from c:/ruby/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mixlib-shellout-2.1.0-universal-mingw32/lib/mixlib/shellout/windows.rb:21:in `<top (required)>'
            from c:/ruby/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
            from c:/ruby/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
            from c:/ruby/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mixlib-shellout-2.1.0-universal-mingw32/lib/mixlib/shellout.rb:32:in `<class:ShellOut>'
            from c:/ruby/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mixlib-shellout-2.1.0-universal-mingw32/lib/mixlib/shellout.rb:26:in `<module:Mixlib>'
            from c:/ruby/Ruby22-x64/lib/ruby/gems/2.2.0/gems/mixlib-shellout-2.1.0-universal-mingw32/lib/mixlib/shellout.rb:24:in `<top (required)>'
            from c:/ruby/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
            from c:/ruby/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
            from c:/ruby/Ruby22-x64/lib/ruby/gems/2.2.0/gems/chef-config-12.4.1/lib/chef-config/config.rb:28:in `<top (required)>'
            from c:/ruby/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
            from c:/ruby/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
            from c:/ruby/Ruby22-x64/lib/ruby/gems/2.2.0/gems/chef-12.4.1-universal-mingw32/lib/chef/config.rb:30:in `<top (required)>'
            from c:/ruby/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
            from c:/ruby/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
            from c:/ruby/Ruby22-x64/lib/ruby/gems/2.2.0/gems/chef-12.4.1-universal-mingw32/lib/chef.rb:24:in `<top (required)>'
            from c:/ruby/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
            from c:/ruby/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
            from c:/ruby/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
            from (irb):1
            from c:/ruby/Ruby22-x64/bin/irb:11:in `<main>'irb(main):002:0> exit

    ruby --version
    ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mingw32]

    gem list
    *** LOCAL GEMS ***

    addressable (2.3.8)
    akami (1.3.1)
    archive-tar-minitar (0.5.2)
    berkshelf (3.3.0)
    berkshelf-api-client (1.3.0)
    bigdecimal (1.2.6)
    buff-config (1.0.1)
    buff-extensions (1.0.0)
    buff-ignore (1.1.1)
    buff-ruby_engine (0.1.0)
    buff-shell_out (0.2.0)
    builder (3.2.2)
    bundler (1.10.6)
    celluloid (0.16.0)
    celluloid-io (0.16.2)
    chef (12.4.1 universal-mingw32, 12.4.0)
    chef-config (12.4.1, 12.4.0)
    chef-dk (0.6.2)
    chef-provisioning (1.1.1)
    chef-zero (4.2.3)
    cheffish (1.3.0, 1.2)
    chefspec (4.3.0)
    cleanroom (1.0.0)
    coderay (1.1.0)
    cookbook-omnifetch (0.2.1)
    debase (0.1.4)
    debase-ruby_core_source (0.7.9)
    debugger-ruby_core_source (1.3.8)
    dep-selector-libgecode (1.0.2)
    dep_selector (1.0.3)
    diff-lcs (1.2.5)
    docile (1.1.5)
    erubis (2.7.0)
    faraday (0.9.1)
    fauxhai (2.3.0)
    ffi (1.9.10 ruby x64-mingw32)
    ffi-yajl (2.2.0)
    gem-path (0.6.1)
    gssapi (1.0.3)
    gyoku (1.3.1)
    hashie (2.1.2)
    highline (1.7.2)
    hitimes (1.2.2)
    httpclient (2.6.0.1)
    httpi (0.9.7)
    inifile (2.0.2)
    io-console (0.4.3)
    ipaddress (0.8.0)
    json (1.8.3, 1.8.1)
    kitchen (0.0.3)
    libyajl2 (1.2.0)
    little-plugger (1.1.3)
    logging (1.8.2)
    method_source (0.8.2)
    mime-types (2.6.1)
    mini_portile (0.6.2)
    minitar (0.5.4)
    minitest (5.4.3)
    mixlib-authentication (1.3.0)
    mixlib-cli (1.5.0)
    mixlib-config (2.2.1)
    mixlib-log (1.6.0)
    mixlib-shellout (2.1.0 ruby universal-mingw32)
    multi_json (1.11.2)
    multipart-post (2.0.0)
    net-http-persistent (2.9.4)
    net-scp (1.2.1)
    net-ssh (2.9.2)
    net-ssh-gateway (1.2.0)
    net-ssh-multi (1.2.1)
    net-telnet (0.1.1)
    nio4r (1.1.1)
    nokogiri (1.6.6.2 x64-mingw32)
    nori (1.1.5)
    octokit (3.8.0)
    ohai (8.5.0)
    paint (1.0.0)
    plist (3.1.0)
    power_assert (0.2.2)
    pry (0.10.1 ruby x64-mingw32)
    psych (2.0.8)
    rack (1.6.4, 1.5.5)
    rake (10.4.2)
    rbx-require-relative (0.0.9)
    rdoc (4.2.0)
    retryable (2.0.1)
    ridley (4.2.0)
    rspec (3.3.0)
    rspec-core (3.3.1)
    rspec-expectations (3.3.0)
    rspec-its (1.2.0)
    rspec-mocks (3.3.1)
    rspec-support (3.3.0)
    rspec_junit_formatter (0.2.3)
    ruby-debug-ide (0.4.32)
    ruby_core_source (0.1.5)
    rubygems-update (2.4.8)
    rubyntlm (0.1.1)
    safe_yaml (1.0.4)
    savon (0.9.5)
    sawyer (0.6.0)
    semverse (1.2.1)
    serverspec (2.19.0)
    sfl (2.2)
    simplecov (0.10.0)
    simplecov-html (0.10.0)
    slop (3.6.0)
    solve (1.2.1)
    specinfra (2.36.15)
    syslog-logger (1.6.8)
    systemu (2.6.5)
    test-kitchen (1.4.2)
    test-unit (3.0.8)
    thor (0.19.1)
    timers (4.0.1)
    uuidtools (2.1.5)
    varia_model (0.4.0)
    wasabi (1.0.0)
    win32-api (1.5.3 universal-mingw32)
    win32-dir (0.5.0)
    win32-event (0.6.1)
    win32-eventlog (0.6.3)
    win32-ipc (0.6.5, 0.6.4)
    win32-mmap (0.4.1)
    win32-mutex (0.4.2)
    win32-process (0.8.0, 0.7.5)
    win32-service (0.8.6)
    win32console (1.3.2)
    windows-api (0.4.4)
    windows-pr (1.2.4)
    winrm (1.2.0)
    wmi-lite (1.0.0)

**Comment by WaffleSouffle** [comment]
Works in 2.1.6

    irb(main):001:0> require 'chef'
    DL is deprecated, please use Fiddle
    true
    exit

    ruby --version
    ruby 2.1.6p336 (2015-04-13 revision 50298) [x64-mingw32]

    gem list

    addressable (2.3.8)
    akami (1.3.1)
    berkshelf (3.3.0)
    berkshelf-api-client (1.3.0)
    bigdecimal (1.2.7, 1.2.4)
    binding.repl (3.0.0)
    buff-config (1.0.1)
    buff-extensions (1.0.0)
    buff-ignore (1.1.1)
    buff-ruby_engine (0.1.0)
    buff-shell_out (0.2.0)
    builder (3.2.2)
    bundler (1.10.6)
    cd (1.0.0)
    celluloid (0.16.0)
    celluloid-io (0.16.2)
    chef (12.4.1 universal-mingw32)
    chef-config (12.4.1)
    chef-dk (0.6.2)
    chef-provisioning (1.1.1)
    chef-zero (4.2.3)
    cheffish (1.3.1)
    chefspec (4.3.0)
    chunky_png (1.3.4)
    cleanroom (1.0.0)
    clipboard (1.0.6)
    code (0.9.0)
    coderay (1.1.0)
    compass (1.0.3)
    compass-core (1.0.3)
    compass-import-once (1.0.5)
    cookbook-omnifetch (0.2.1)
    debugging (1.1.0)
    dep-selector-libgecode (1.0.2)
    dep_selector (1.0.3)
    diff-lcs (1.2.5)
    erubis (2.7.0)
    every_day_irb (2.0.0)
    fancy_irb (1.0.0)
    faraday (0.9.1)
    fauxhai (2.3.0)
    ffi (1.9.8 x64-mingw32)
    ffi-yajl (2.2.2)
    gssapi (1.0.3)
    gyoku (1.3.1)
    hashie (2.1.2)
    highline (1.7.3)
    hirb (0.7.3)
    hitimes (1.2.2)
    httpclient (2.6.0.1)
    httpi (0.9.7)
    inifile (2.0.2)
    instance (0.2.0)
    interactive_editor (0.0.10)
    io-console (0.4.3, 0.4.2)
    ipaddress (0.8.0)
    json (1.8.3, 1.8.2, 1.8.1)
    kitchen (0.0.3)
    libyajl2 (1.2.0)
    little-plugger (1.1.3)
    logging (1.8.2)
    method_locator (0.0.4)
    method_source (0.8.2)
    methodfinder (2.0.0)
    mime-types (2.6.1)
    mini_portile (0.6.2)
    minitar (0.5.4)
    minitest (5.6.0, 4.7.5)
    mixlib-authentication (1.3.0)
    mixlib-cli (1.5.0)
    mixlib-config (2.2.1)
    mixlib-log (1.6.0)
    mixlib-shellout (2.1.0 universal-mingw32)
    multi_json (1.11.0)
    multipart-post (2.0.0)
    net-http-persistent (2.9.4)
    net-scp (1.2.1)
    net-ssh (2.9.2)
    net-ssh-gateway (1.2.0)
    net-ssh-multi (1.2.1)
    net-telnet (0.1.1)
    nio4r (1.1.1)
    nokogiri (1.6.6.2 x64-mingw32)
    nori (1.1.5)
    octokit (3.8.0)
    ohai (8.5.1)
    ori (0.1.0)
    os (0.9.6)
    paint (1.0.0)
    plist (3.1.0)
    power_assert (0.2.3)
    pry (0.10.1 x64-mingw32)
    psych (2.0.13, 2.0.5)
    rack (1.6.4)
    rake (10.4.2, 10.1.0)
    rb-fsevent (0.9.4)
    rb-inotify (0.9.5)
    rdoc (4.2.0, 4.1.0)
    retryable (2.0.1)
    ridley (4.2.0)
    rspec (3.3.0)
    rspec-core (3.3.2)
    rspec-expectations (3.3.1)
    rspec-its (1.2.0)
    rspec-mocks (3.3.2)
    rspec-support (3.3.0)
    rspec_junit_formatter (0.2.3)
    ruby_engine (1.0.1)
    ruby_info (1.0.1)
    ruby_version (1.0.1)
    rubygems-update (2.4.8, 2.4.6)
    rubyntlm (0.1.1)
    safe_yaml (1.0.4)
    sass (3.4.13)
    savon (0.9.5)
    sawyer (0.6.0)
    semverse (1.2.1)
    serverspec (2.21.0)
    sfl (2.2)
    slop (3.6.0)
    solve (1.2.1)
    specinfra (2.40.2)
    spoon (0.0.4)
    syslog-logger (1.6.8)
    systemu (2.6.5)
    test-kitchen (1.4.2)
    test-unit (3.0.9, 2.1.6.0, 2.1.5.0)
    thor (0.19.1)
    timers (4.0.1)
    unicode-display_width (0.2.0)
    uuidtools (2.1.5)
    varia_model (0.4.0)
    wasabi (1.0.0)
    win32-api (1.5.3 universal-mingw32)
    win32-dir (0.5.0)
    win32-event (0.6.1)
    win32-eventlog (0.6.3)
    win32-ipc (0.6.5)
    win32-mmap (0.4.1)
    win32-mutex (0.4.2)
    win32-process (0.7.5)
    win32-service (0.8.6)
    win32console (1.3.2)
    windows-api (0.4.4)
    windows-pr (1.2.4)
    winrm (1.2.0)
    wirb (2.0.0)
    wmi-lite (1.0.0)

**Comment by lamont-granquist** [comment]
We don't support chef running out of gems on windows and don't support it running on 2.2.2 yet.
