### ISSUE TITLE
Resource "package", attribute "package_name" doesnt work as expected

### ISSUE THREAD

**Issue by philicious** [chef/chef#3786]
According to http://docs.chef.io/release/11-16/resource_package.html and http://docs.chef.io/release/11-16/resource_apt_package.html

you should be able to specify an array for package_name, however I get an error
```
 Chef::Exceptions::ValidationFailed
  ----------------------------------
  Option package_name must be a kind of [String]!  You passed ["python-openssl", "libnl-3-200", "libnl-route-3-200", "python-dbus", "python-apt", "python-newt", "python-gudev", "python-dmidecode", "python-libxml2"].
```
Recipe
```
package 'install-spacewalk-deps' do
  package_name %w(python-openssl libnl-3-200 libnl-route-3-200 python-dbus
                  python-apt python-newt python-gudev python-dmidecode python-libxml2)
end
```

```
chef-client -v
Chef: 11.16.4
```
This is working fine with chef-client 12.x

**Comment by coderanger** [comment]
Multi-package installs were added in 12.1.0.

**Comment by philicious** [comment]
then the docs need updates because they clearly say arrays are supported for 11.x
http://docs.chef.io/release/11-16/resource_package.html
http://docs.chef.io/release/11-16/resource_apt_package.html
