### ISSUE TITLE
updated_by_last_action? not working in chef-12.4.0

### ISSUE THREAD

**Issue by shubhamitc** [chef/chef#3789]
I have faced the issue of updated_by_last_action? to return false all the time.
Log 
-----------------------------------------------------------------------------
`Recipe: mysql_db_config::default`
  `* directory[/tmp] action create`
   ` - change mode from '0755' to '03357'`
`  * remote_file[/var/chef/cache/app_name.tar.gz] action create`
`    - create new file /var/chef/cache/app_name.tar.gz`
 `   - update content in file /var/chef/cache/app_name.tar.gz from none to 69dcc8`
`    (new content is binary, diff output suppressed)`
 ` * log[<remote_file[/var/chef/cache/app_name.tar.gz] @name: "/var/chef/cache/app_name.tar.gz" \@noop: nil @before: nil @params: {} @provider: Chef::Provider::RemoteFile @allowed_actions: [:nothing, :create, :delete, :touch, :create_if_missing] @action: [:create] @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: "/var/chef/cache/cookbooks/mysql_db_config/recipes/default.rb:34:in `from_file'" `@guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @sensitive: false` `@path: "/var/chef/cache/app_name.tar.gz" @backup: 5 @atomic_update: true @force_unlink: false` `@manage_symlink_source: nil @diff: nil @verifications: [] @source:` `["http://oak.cs.ucla.edu/cs144/projects/tomcat/cs144.war"] @use_etag: true @use_last_modified: true` `@ftp_active_mode: false @headers: {} @declared_type: :remote_file @cookbook_name:` `"mysql_db_config" @recipe_name: "default">] action write`

Recipe
-------
`tar_downloaded=remote_file "#{Chef::Config[:file_cache_path]}/app_name.tar.gz" do`
`	source "http://oak.cs.ucla.edu/cs144/projects/tomcat/cs144.war"`
 ` action :create`
`  # notifies :run, "bash[client_log_push]"`
`end`
`log tar_downloaded.inspect`

Based on the value of tar_downloaded various actions are configured. Any help!
`if (t.updated_by_last_action?)`
    `do_something()`
`end`

Machine
----
chef-client --version
Chef: 12.4.1

lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.5 (Final)
Release:	6.5
Codename:	Final

**Comment by coderanger** [comment]
That flag is only set (and only ever has been set) after the action has run. Most likely you are checking it immediately afterwards at compile time. You probably want to use a ruby_block resource and an `:immediately` notification instead.

**Comment by shubhamitc** [comment]
Hi ,

I m getting the same with lwrp ,
\#/lib/providers/tomcat.rb

`use_inline_resources`

action :download do
	t = remote_file "#{Chef::Config[:file_cache_path]}/#{new_resource.application_context}" do
			# source "#{new_resource.name}"
			source "http://oak.cs.ucla.edu/cs144/projects/tomcat/cs144.war"
			path "#{Chef::Config[:file_cache_path]}/#{new_resource.application_context}"
			mode 0755
			owner node.default[:tomcat][:user]
  			group node.default[:tomcat][:group] 
  			backup false
			action [:create]
	end
	ruby_block 'check_status' do 
		block do 
			Chef::Log.info t.updated_by_last_action?
		end
	end
	log "PROCESS STARTS  #{new_resource.name} :  #{t.inspect } #{t.updated_by_last_action?.class}"
	new_resource.updated_by_last_action( true )
end`

**Comment by coderanger** [comment]
The log within the `ruby_block` should work as expected, the `log` resource below it will not.
