### ISSUE TITLE
Difference between Chef 11 and 12 in how the client uses 'splay' and 'interval' (Ubuntu 14.04)  

### ISSUE THREAD

**Issue by klutarevich** [chef/chef#3791]
I'm transitioning from Chef 11 to Chef 12.4.1 on some of my Ubuntu 14.04 machines and I noticed a difference in behavior when starting chef-client without --once option (i.e. use 'splay' and 'interval'). When chef-client 11 starts it first waits for 'splay' seconds, runs the recipes from runlist and then waits for 'interval' seconds. When I run chef-client 12.4.1 it first waits for 'interval' (long) seconds instead of waiting for 'splay' (short) and it looks as if chef-client simply hangs. Was this change intentional or it's a bug?

**Comment by lamont-granquist** [comment]
Extremely intentional.

There is an open issue #3305 to make this configurable
