### ISSUE TITLE
Mount provider should skip the existence check of device, if fstype is fuse with subtype.

### ISSUE THREAD

**Issue by mapi** [chef/chef#3801]
### Version:

Chef 12.4.1
### Environment:

Debian 8.1 on Google Compute Engine
### Scenario:

use `mount` provider for mount fuse filesytem.
### Steps to Reproduce:

``` ruby
mount "/mnt/my-bucket" do
  fstype "fuse.gcsfuse"
  device "my-bucket"
  options "rw,user"
  action [:mount, :enable]
end
```
### Expected Result:

can mount filesystem.
### Actual Result:

raise `Chef::Exceptions::Mount`

```
================================================================================
Error executing action `mount` on resource 'mount[/mnt/my-bucket]'
================================================================================

Chef::Exceptions::Mount
-----------------------
Device my-bucket does not exist
```
### NOTE

``` ruby
mount "/mnt/my-bucket" do
  fstype "fuse"
  device "gcsfuse#my-bucket"
  options "rw,user"
  action [:mount, :enable]
end
```

may be works.
but this is deprecated(via `man mount(8)`) and gcsfuse will not support deprecated idiom.
so mount provider should skip device check, if fstype is `fuse.#{subtype}`

**Comment by sanga1794** [comment]
@mapi, while analysing the issue i found issue you have created: https://github.com/GoogleCloudPlatform/gcsfuse/issues/116.
So is your issue resolved by using above one, Or still you are facing this issue?

**Comment by sanga1794** [comment]
@mapi for time being we closing the issue, please reopen it if you are still facing the issue, Thanks!!
