### ISSUE TITLE
/var/chef completely wiped by running chef-solo with default configs

### ISSUE THREAD

**Issue by gionn** [chef/chef#3802]
https://github.com/chef/chef/blob/master/lib/chef/application/solo.rb#L212

It isn't sufficient to just rm_r cookbooks_path?

Is it really a feature? It just destroyed my environments, data_bags, backups, etc under /var/chef 

/cc @vtolstov

**Comment by lamont-granquist** [comment]
Yeah I ripped that line out of the "port" of this code from chef-solo to chef-client/local-mode.  It actually wiped out my entire chef git checkout when it wasn't stubbed correctly and ran an rm -rf on the directory that I ran rspec from.

I would be :+1: on a PR to remove that line and make it entirely the responsibility of the "caller" (the script that invokes chef-solo/client).

**Comment by ranjib** [comment]
yup, i've been bitten by this as well. @gionn you want to work on it? else i can send a PR

**Comment by vtolstov** [comment]
cookbooks path is not enough, because databags may have old data.
May be add new option to cleanup chef work dir or something like this?

**Comment by gionn** [comment]
@vtolstov This feature is useful when using recipe_url (cookbooks.tar.gz served via https), so cleaning data_bags folder is out of scope, since something else should put them in the right place (and so it can freely empty such folder).

For me cleaning `Chef::Config[:cookbook_path]` is enough.

As a side note, I just saw:
```
Mixlib::ShellOut.new("tar zxvf #{tarball_path} -C #{recipes_path}").run_command
```

Why impose with `-z` that the archive should be gzipped? Tar is smart enough to do the right thing without any particular option (enabling us to switch to bz2 or xz at any time).

If is good for all, I will make a PR for both.

Thanks.

**Comment by lamont-granquist** [comment]
The '-z' probably predates tar being smart enough to just DTRT if you leave it off.  I still have more than a decade of reflex (might be more than 20 years of reflex, can't recall now) of automatically including that flag to tar--its a hard habit to break...

**Comment by vtolstov** [comment]
@gionn in case of not removing data_bags for example may bring problems, when some recipe use * from some databag. May be create two step unpack? first get root dirs from archive, and if dir present in tar, remove it from disk?

**Comment by lamont-granquist** [comment]
We should rip out the rm_rf completely in Chef 13.0 and make it the responsibility of the 'caller' to do the correct thing for their environment.
