### ISSUE TITLE
route: resource doesn't specify 'dev' in route-ethX config file

### ISSUE THREAD

**Issue by murphy-slaw** [chef/chef#3823]
On Redhat based systems, the Route provider writes config files in /etc/sysconfig/network-scripts/route-ethX, but it doesn't specify a device. On CentOS 6 at least, if you don't specify a device, the static route will be bound to eth0.

I have the following route resource:

route '10.96.32.0/19' do
  gateway '10.100.50.1'
  device 'eth1'
end

The corresponding line in route-eth1 is

10.96.32.0/19 via 10.100.50.1

when it should be

10.96.32.0/19 via 10.100.50.1 dev eth1

So the route gets created bound to eth0.

On top of this, the route provider doesn't check device when checking to see if a route exists. So when chef runs, it doesn't fix the route because it already sees it existing (even though it's bound to eth0 instead of eth1).

The first time that Chef runs with a new route resource, the route WILL be created correctly. It only gets messed up when the system is rebooted and the network scripts bring up the route on the wrong device.

**Comment by smurawski** [comment]
Tagging with https://github.com/chef/chef/issues/3862.  We should fix this as part of the route provider overhall.

**Comment by tas50** [comment]
Tagging this for sustaining to see if we can replicate it. @thommay did a good chunk of work cleaning this up.
