### ISSUE TITLE
Upgrading from chef-client 11.16.4 to 12.4.1 does not upgrade chef-client service.

### ISSUE THREAD

**Issue by vinyar** [chef/chef#3824]
**OS:**
Windows2012r2

**Scenario:**
Chef client 11.16.4 is installed
Chef client is configured to run as a service via chef-client cookbook.
Chef client 12.4.1 is installed on top of existing chef-client installation. Service option is not selected.

**Error:**
Chef client 12.4.1 is installed.
chef-client service is now broken because it still points to 11.16.4 gem.
`"C:\opscode\chef\embedded\bin\ruby" "C:\opscode\chef\embedded\lib\ruby\gems\1.9.1\gems\chef-11.16.4-x86-mingw32\lib\chef\application\windows_service.rb"  -c C:\chef\client.rb -L C:\chef\client.log"`

**Expectation:**
Either one of the two behaviors below will satisfy expected behavior
-  chef-client installer detects that service was configured and remaps the startup parameter to use new gem.
-  chef-client installer detects that service was installed, but not selected on upgrade and uninstalls old service as a result.

@gallopinto , @tutocr

**Comment by vinyar** [comment]
related:
https://github.com/chef/chef/issues/3826
https://github.com/chef/chef/issues/3825

**Comment by vinyar** [comment]
Looks like installing chef-client 12 w/o updating service also breaks omnibus_updater cookbook:
https://github.com/hw-cookbooks/omnibus_updater/issues/32

**Comment by gallopinto** [comment]
We're having this issue. It will be difficult to update all of the Chef client installations.

**Comment by smurawski** [comment]
Created epic https://github.com/chef/chef/issues/4042 to track this

**Comment by stuartpreston** [comment]
Closing this in favour of #4042
