### ISSUE TITLE
Uninstalling chef-client does not remove chef service delayed start 

### ISSUE THREAD

**Issue by vinyar** [chef/chef#3826]
**OS:**
Windows 2012r2

**Scenario:**
Chef client 11.16.4 is installed
Chef client is configured to run as a service via chef-client cookbook.
Recipe is ran to set chef-client service to `delayed start`
Chef client 12.4.1 is installed on top of existing chef-client installation. Service option is not selected.
Chef client 12.4.1 is uninstalled.
_BUG_: chef-client service is left behind in the services.msc
chef-client 12.4.1 is reinstalled with service option selected.
chef-client service is installed and set to `delayed start` without changes.

**Error:**
- chef-client service is left behind in the services.msc after newer version of chef client is uninstalled.
- when chef-client service is re-installed, it's set to `delayed start` by default (left over from previous install and not cleaned up by uninstall).

**Expectation:**
When chef client is uninstalled, the configuration of service should be removed.
When chef client is reinstalled/repaired delayed start / stopped should be reset to default.

@gallopinto , @tutocr

**Comment by vinyar** [comment]
related:
https://github.com/chef/chef/issues/3826
https://github.com/chef/chef/issues/3825

**Comment by smurawski** [comment]
Since the chef-client cookbook does not install the service via the MSI, uninstalling the MSI does not know to remove the service.  We'll have to fix the chef-service-manager.  /cc @chef/client-windows

**Comment by smurawski** [comment]
Created epic https://github.com/chef/chef/issues/4042 to track this

**Comment by stuartpreston** [comment]
Closing this out, as per discussion in https://github.com/chef/chef/issues/3825
