### ISSUE TITLE
remote_directory: add  `preserve_mode true` property

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#3833]
If you have secret files you want to chmod 600 in your remote_directory but you want the default to be 644 for the rest of the files there's no way to specify that.  It would be nice to have `preserve_mode true` added to remote_directory so that .ssh priv keys could be copied out, and a subsequent file resource could repair their modes to 600 and then on a subsequent run the file mode would get preserved and the resources wouldn't thrash.

**Comment by lamont-granquist** [comment]
link to @jkeiser's original ticket: https://tickets.opscode.com/browse/CHEF-2691

**Comment by justjake** [comment]
BUMP! This is rather annoying.

**Comment by tfitch** [comment]
This oldie by goodie is causing problems for me today.  So there is still some desire to see this new `preserve_mode` attribute to the `remote_directory` resource.  Thanks!

**Comment by lamont-granquist** [comment]
maybe `preserve_mode [ <array of file paths> ]` would be even better, then enforcement could happen on most of the files remote_directory manages, but exceptions could be made, rather than just turning off enforcement for everything.
