### ISSUE TITLE
systemd provider helper platform_has_systemd_unit? broken in 12.4.1, pending 11.18.0 release

### ISSUE THREAD

**Issue by fujin** [chef/chef#3835]
https://github.com/chef/chef/blob/11.18.0.r/lib/chef/platform/service_helpers.rb#L118-L138
https://github.com/chef/chef/blob/master/lib/chef/platform/service_helpers.rb#L118-L139

```
[aj@endpoint1df988a3]~% sudo cat /var/chef/cache/chef-stacktrace.out
Generated at 2015-08-28 07:29:31 +0000
NoMethodError: service[cloud-config.service] (pantheon::cloud_init line 15) had an error: NoMethodError: undefined method `+' for false:FalseClass
/opt/chef/embedded/apps/chef/lib/chef/platform/service_helpers.rb:134:in `platform_has_systemd_unit?'
/opt/chef/embedded/apps/chef/lib/chef/platform/service_helpers.rb:98:in `config_for_service'
/opt/chef/embedded/apps/chef/lib/chef/provider/service/redhat.rb:36:in `supports?'
/opt/chef/embedded/apps/chef/lib/chef/provider_resolver.rb:79:in `block in supported_handlers'
/opt/chef/embedded/apps/chef/lib/chef/provider_resolver.rb:79:in `select'
/opt/chef/embedded/apps/chef/lib/chef/provider_resolver.rb:79:in `supported_handlers'
/opt/chef/embedded/apps/chef/lib/chef/provider_resolver.rb:91:in `prioritized_handlers'
/opt/chef/embedded/apps/chef/lib/chef/provider_resolver.rb:116:in `maybe_dynamic_provider_resolution'
/opt/chef/embedded/apps/chef/lib/chef/provider_resolver.rb:61:in `resolve'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:1205:in `provider_for_action'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:584:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:49:in `run_action'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `each'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:81:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/runner.rb:80:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:654:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:649:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:649:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:688:in `converge_and_save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:269:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:270:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:258:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:224:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:39:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:212:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:280:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:269:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:269:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/solo.rb:247:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-solo:25:in `<top (required)>'
/bin/chef-solo:55:in `load'
/bin/chef-solo:55:in `<main>'%
```

Looks like `extract_systemd_services(command)` is returning false due to a mixlib command error and blowing up the method which calls it.

The whole design of this is very questionable. `systemctl --all` and `systemctl list-unit-files` are basically unusable with more than a few thousand units and should not be used for this purpose.

**Comment by lamont-granquist** [comment]
That design was just due to google telling me that was the way to solve that problem, and a lot of pulling my hair out.  I'm definitely not a systemd expert, so I wouldn't be surprised if there's a better design, but I have no idea what it would be.

**Comment by nathwill** [comment]
systemctl list-unit-files takes a pattern as an argument, which may help:

```bash
[nathwill@wyrdish ~]$ systemctl list-unit-files multi-user.target
UNIT FILE         STATE 
multi-user.target static

1 unit files listed.
[nathwill@wyrdish ~]$ echo $?
0
[nathwill@wyrdish ~]$ systemctl list-unit-files nonexistent.target
UNIT FILE STATE

0 unit files listed.
[nathwill@wyrdish ~]$ echo $?
0
```

i'm not sure how much more efficient it's internal scan is, but i'd guess it's significantly so. It might be simplest to just check for file existence in the systemd system-mode unit load path (`/etc/systemd/system`, `/run/systemd/system`, `/usr/lib/systemd/system`) since this seems to be a service-unit specific implementation, and service units are file-based.

it's also almost certainly preferable to always use systemctl to manage services on systemd-based platforms, regardless of whether a particular service is described via a unit file or a sysv script; systemctl handles the compatibility, so if `/proc/1/comm` is `systemd`, that's probably all you actually need to know to add systemd to the service provider list.

**Comment by nathwill** [comment]
@lamont-granquist @fujin ok, took at stab at this in #3836, interested in your feedback.

@fujin with your 1000's of service units, would the new `has_systemd_service_unit?` method of checking the load path for the file existence work for how you're managing those units? i'm pretty sure it's technically possible to create a service unit via dbus and have it not exist on the file system, but i'm not aware of any cases where that's actually been done...

**Comment by fujin** [comment]
@nathwill will test and provide feedback. Thanks for the ridiculously fast turn around :). 1000's of service units was me being polite. We are quite potentially the largest systemd installation on the planet with >400,000 units, typically 5~6 per customer with hundreds of thousands of customers.

we'd discussed internally checking the load path for file extensions and I think this is probably one of the only ways we'll be able to do it, aside from sitting on DBus directly doing calls/replies.

**Comment by fujin** [comment]
@lamont-granquist sorry mate, that wasn't a dig at ya. :) I find systemd stuff in general is super hard to find how to do the right thing, and sorry I didn't find this sooner.

**Comment by nathwill** [comment]
@fujin off-topic, but i'd love your feedback on https://github.com/nathwill/chef-systemd if y'all are using it, and if not, info on what we could do to make it more attractive for use. it sounds like you're our primary target user :)

**Comment by lamont-granquist** [comment]
Oh, I didn't take it as a dig.  I just wanted to be clear that I'm not attached to the code at all and not horribly surprised that it doesn't scale at all.  I knew it was Minimum Viable Product when I wrote it.

**Comment by stevendanna** [comment]
> we'd discussed internally checking the load path for file extensions and I think this is probably one of the only ways we'll be able to do it, aside from sitting on DBus directly doing calls/replies.

@fujin Do we think this would be viable?  I was originally looking to this route but then some saw comments that the issue with `systemctl --all` is actually dbus locking up; however, I haven't looked into the performance there myself.

**Comment by fujin** [comment]
@stevendanna we've used the approach in other situations (from a golang binary) to monitor dbus call/recv/message performance; I don't think it would be impossible, but it's kind of a moving target. I think potentially it can deal with slowdowns of the bus a little better by retrying or blocking until the response is recieved, instead of just failing+bubbling the error through `platform_has_systemd_unit?`; hard to say though.

**Comment by stevendanna** [comment]
Aside from the performance issues, it looks like @ranjib's fix here:

https://github.com/chef/chef/pull/3935

Is the likely cause of the original stack-trace.

**Comment by thommay** [comment]
We've now merged all the PRs associated with this, so let's close this out and create new bugs if need be. Thanks, all!
