### ISSUE TITLE
chef-shell in solo-mode does not load cookbooks at startup (CHEF-3831)

### ISSUE THREAD

**Issue by ghost** [chef/chef#3842]
This major issue reported over two years ago is still broken. The ticket was marked 'fixed' and closed, but was never fixed. Please see https://tickets.opscode.com/browse/CHEF-3831?page=com.atlassian.streams.streams-jira-plugin:activity-stream-issue-tab

Because of this bug the chef shell doesn't work as advertised (https://docs.chef.io/chef_shell.html) in solo mode. If you have decided not to fix this, please make a note in the documentation that the shell only works in client mode.

Tested, still broken on 11.18.12.

Thanks!

**Comment by stevendanna** [comment]
I've update the title to make it clear that the behavior is in solo-mode.  client-mode and standalone-mode work as expected as far as I can see. The most proximate cause is likely this:

https://github.com/chef/chef/blob/master/lib/chef/shell/shell_session.rb#L177

Which should probably look more like:

```
rl = Chef::RunList::RunListExpansionFromDisk.new(@node.environment, @node.run_list.to_a)
rl.expand
@run_context.load(Chef::RunList::RunListExpansionFromDisk.new(@node.environment, rl))
```

However, there might be some work to do to to make sure that `@node.run_list` and `@node.environment` is correct at that point in the run.

**Comment by sczizzo** [comment]
Any chance this will ever be fixed, or should I give up and move to a workflow based on Chef Zero? Currently experiencing this exact issue with a recent ChefDK installation:
```
Chef Development Kit Version: 0.14.13
chef-client version: 12.7.2
berks version: 4.3.2
kitchen version: 1.8.0
```
Agree with OP that this behavior does not seem expected given the documentation, which says "Cookbooks will be loaded in the same way that chef-solo loads them"

**Comment by coderanger** [comment]
@sczizzo We're finally following up on migrating `chef-solo` to be local mode in disguise so the point should now be moot.
