### ISSUE TITLE
powershell_script documented to run by default with -ExecutionPolicy RemoteSigned, whereas as of 12.x, runs with -ExecutionPolicy Unrestricted

### ISSUE THREAD

**Issue by timor-raiman** [chef/chef#3844]
From https://docs.chef.io/resource_powershell_script.html:

> flags  
> 
> Ruby Type: String
> 
> A string that is passed to the Windows PowerShell command. Default value: -NoLogo, -NonInteractive, -NoProfile, -ExecutionPolicy RemoteSigned, -InputFormat None, -File.

This conflicts

https://github.com/chef/chef/blob/master/lib/chef/provider/powershell_script.rb#L114

**Comment by lamont-granquist** [comment]
Pretty sure that is intentional and this is just a doc bug @jamescott

**Comment by stuartpreston** [comment]
Closing this doc issue now, docs PR raised in https://github.com/chef/chef-web-docs/pull/1498
