### ISSUE TITLE
reboot resource, delay_mins is in seconds; incorrect command line syntax?

### ISSUE THREAD

**Issue by jamescott** [chef/chef#3845]
The docs have been updated---https://github.com/chef/chef-docs/issues/618---to clarify the current behavior as I understand it, but the syntax at the link below should be verified:

https://github.com/chef/chef/blob/c91b3371036de811c9b2ba0e26f287e676dfd96f/lib/chef/platform/rebooter.rb#L35

This TechNet article indicates there may be a bug in the code:

https://technet.microsoft.com/en-us/library/Bb491003.aspx

@jaym @mmzyk @gswallow

**Comment by smurawski** [comment]
This will be fixed with the release of 12.5.0.  I've filed https://github.com/chef/chef-web-docs/issues/670 to update the documentation to match that.

**Comment by btm** [comment]
Fixed by https://github.com/chef/chef-web-docs-2016/issues/670
