### ISSUE TITLE
knife cookbook upload does not respect port in chef_server_url

### ISSUE THREAD

**Issue by dan-bolsun** [chef/chef#3846]
Hi,

Currently I testing chef server on virtual machine and do some DNAT to access it. Server is configured due to guide and nginx listens on default 443 port. On my host system port 444 is used.
So knife.rb looks like this:
...
chef_server_url          "https://my.chef.server.com:444/organizations/testorg"
...

After server and workstation setup some commands runs well. `knife ssl fetch`, `knife ssl check` and even `knife data bag from file ...`. But when I try to upload some cookbooks with `knife cookbook upload my_cookbook -V` fails and INFO loglines look like:

INFO: Uploading chef-repo/cookbooks/my_cookbook/resources/manage.rb (checksum hex = ...) to https://my.chef.server.com:443/...
...

As you may see `knife cookbook upload ...` is sending cookbook to 443 port instead of 444 listed in knife.rb.

`knife cookbook upload -v' output:
Chef: 12.4.1

**Comment by stevendanna** [comment]
This is likely a chef-server configuration problem.  The chef-server generates upload links that the client is supposed to be able to just follow.

**Comment by dan-bolsun** [comment]
Okay, thank you. I just need to run it on 443 port without any redirects

**Comment by stevendanna** [comment]
@dan-bolsun It should be possible to change the listen port but isn't currently because of this bug:

https://github.com/chef/chef-server/issues/50

Going to close this issue out in favor of the chef-server one above.  Apologies for the trouble this bug has caused you.

**Comment by dan-bolsun** [comment]
Not a problem. And thank you for quick response!
