### ISSUE TITLE
Fix knife ssh

### ISSUE THREAD

**Issue by thommay** [chef/chef#3852]
Because it's slightly scary right now.

**Comment by thommay** [comment]
#2935

**Comment by thommay** [comment]
#3169

**Comment by coderanger** [comment]
Good timing, can throw #3857 on here too.

**Comment by thommay** [comment]
Maybe #3602 too

**Comment by rmoriz** [comment]
how about #3036?

**Comment by vsingh-msys** [comment]
Seems all of the above mentioned issues/PRs are merged/closed
