### ISSUE TITLE
Fix network providers

### ISSUE THREAD

**Issue by thommay** [chef/chef#3862]
Bring the `ifconfig` and `route` into the second decade of the 21st century. Possibly `ifconfig` should be renamed to `interface`.

- Route resource should support IPV6
- ifconfig resource to support the new Network Manager keyfile format

**Comment by tas50** [comment]
I'm going to close this one out at this point. ifconfig in particular needs to get replaced with the modern systemd equiv, but that outside the scope of this issue.
