### ISSUE TITLE
AIX multipackage with source

### ISSUE THREAD

**Issue by alanwthatcher** [chef/chef#3863]
I have a requirement to install multiple packages from a single source directory to support a particular client.  However, when I provide the package_name as an array, and also the source (as required for AIX), I get an error 

```
    Chef::Exceptions::InvalidResourceSpecification
    ----------------------------------------------
    You may not specify both multipackage and source
```

Which comes from chef/provider/package:

```
      def check_resource_semantics!
        if new_resource.package_name.is_a?(Array) && new_resource.source != nil
          raise Chef::Exceptions::InvalidResourceSpecification, "You may not specify both multipackage and source"
        end
      end
```

I would rather not create multiple stanzas (either through a loop or the hard way).  I can work around the problem by using an execute block, but that seems non chef-like to me.  Is this expected behavior that I need to work around?  Thanks!

**Comment by lamont-granquist** [comment]
The only providers that support arrays are yum and deb package.

**Comment by alanwthatcher** [comment]
Ok. I didn't notice that. I thought I saw on the bff_package page that it
could be an array. I guess I was mistaken. I'll have to check it out
tomorrow. Thanks.
