### ISSUE TITLE
knife vsphere vm snapshot problem - can not find folders

### ISSUE THREAD

**Issue by lioryantov** [chef/chef#3885]
Hi,

I am using knife vsphere plugin , and I trying to list all exist snapshots on particular machine without success.
The command I used: 
knife vsphere vm snapshot LiorVM -f "/vm/Lior VM's/" --list -VV
The result:
INFO: Using configuration from /root/chef-repo/.chef/knife.rb
DEBUG: value for config item vsphere_host: lab-admin-vc1.domain.com
DEBUG: value for config item vsphere_path: /sdk
DEBUG: value for config item vsphere_port: 443
DEBUG: value for config item vsphere_nossl: 
DEBUG: value for config item vsphere_user: lioryantov
DEBUG: value for config item vsphere_pass: ***********
DEBUG: value for config item vsphere_insecure: true
DEBUG: value for config item proxy_host: 
DEBUG: value for config item proxy_port: 
DEBUG: value for config item folder: /vm/Lior VM's/
DEBUG: value for config item vsphere_dc: Domain-Lab
no such folder /vm/Lior VM's/ while looking for vm

Although when I running command "knife vsphere folder list" I received correct directory topology.
Folder: vm
   Folder: Lior VM's
What is the problem there, what I am doing wrong in my query ?
Many Thanks,
Lior

**Comment by thommay** [comment]
Hi,
knife-vsphere is not part of core chef. Please report your issue at https://github.com/chef-partners/knife-vsphere/issues/new and you'll be able to get some assistance there.
