### ISSUE TITLE
knife cookbook site share doesn't work

### ISSUE THREAD

**Issue by daften** [chef/chef#3888]
I'm getting the error when trying to release a new version for the aegir3 cookbook (https://github.com/daften/cookbook-aegir3):

```
ERROR: knife encountered an unexpected error
This may be a bug in the 'cookbook site share' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NameError: undefined local variable or method `method_name' for Chef::Cookbook::Metadata:Class
```

**Comment by thmttch** [comment]
+1 same here. `-VV` is useless, and shows the same errors as above with no additional details or warnings.

This is for https://supermarket.chef.io/cookbooks/anaconda hosted at https://github.com/thmttch/chef-continuum-anaconda.

ChefDk and OS are:

  ```bash
  $> chef -v
  Chef Development Kit Version: 0.8.1
  chef-client version: 12.4.4
  berks version: 3.3.0
  kitchen version: 1.4.2

  $> uname -a
  Darwin sfo 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
  ```

**Comment by levkov** [comment]
Same issue:
knife supermarket share build-essential "Other" -VV
INFO: Using configuration from /root/chef-repo/.chef/knife.rb
INFO: Validating ruby files
DEBUG: Ruby file /root/chef-repo/cookbooks/build-essential/libraries/xcode_command_line_tools.rb is unchanged, skipping syntax check
DEBUG: Ruby file /root/chef-repo/cookbooks/build-essential/libraries/matchers.rb is unchanged, skipping syntax check
DEBUG: Ruby file /root/chef-repo/cookbooks/build-essential/libraries/timing.rb is unchanged, skipping syntax check
DEBUG: Ruby file /root/chef-repo/cookbooks/build-essential/attributes/default.rb is unchanged, skipping syntax check
DEBUG: Ruby file /root/chef-repo/cookbooks/build-essential/recipes/_freebsd.rb is unchanged, skipping syntax check
DEBUG: Ruby file /root/chef-repo/cookbooks/build-essential/recipes/_rhel.rb is unchanged, skipping syntax check
DEBUG: Ruby file /root/chef-repo/cookbooks/build-essential/recipes/_solaris2.rb is unchanged, skipping syntax check
DEBUG: Ruby file /root/chef-repo/cookbooks/build-essential/recipes/_mac_os_x.rb is unchanged, skipping syntax check
DEBUG: Ruby file /root/chef-repo/cookbooks/build-essential/recipes/_debian.rb is unchanged, skipping syntax check
DEBUG: Ruby file /root/chef-repo/cookbooks/build-essential/recipes/_fedora.rb is unchanged, skipping syntax check
DEBUG: Ruby file /root/chef-repo/cookbooks/build-essential/recipes/_smartos.rb is unchanged, skipping syntax check
DEBUG: Ruby file /root/chef-repo/cookbooks/build-essential/recipes/_suse.rb is unchanged, skipping syntax check
DEBUG: Ruby file /root/chef-repo/cookbooks/build-essential/recipes/default.rb is unchanged, skipping syntax check
DEBUG: Ruby file /root/chef-repo/cookbooks/build-essential/recipes/_omnios.rb is unchanged, skipping syntax check
INFO: Validating templates
INFO: Syntax OK
DEBUG: Staging at /tmp/chef-build-essential-build20151029-2541-1q3unvu
DEBUG: Staging /root/chef-repo/cookbooks/build-essential/recipes/_freebsd.rb to /tmp/chef-build-essential-build20151029-2541-1q3unvu/build-essential/recipes/_freebsd.rb
DEBUG: Staging /root/chef-repo/cookbooks/build-essential/recipes/_rhel.rb to /tmp/chef-build-essential-build20151029-2541-1q3unvu/build-essential/recipes/_rhel.rb
DEBUG: Staging /root/chef-repo/cookbooks/build-essential/recipes/_solaris2.rb to /tmp/chef-build-essential-build20151029-2541-1q3unvu/build-essential/recipes/_solaris2.rb
DEBUG: Staging /root/chef-repo/cookbooks/build-essential/recipes/_mac_os_x.rb to /tmp/chef-build-essential-build20151029-2541-1q3unvu/build-essential/recipes/_mac_os_x.rb
DEBUG: Staging /root/chef-repo/cookbooks/build-essential/recipes/_debian.rb to /tmp/chef-build-essential-build20151029-2541-1q3unvu/build-essential/recipes/_debian.rb
DEBUG: Staging /root/chef-repo/cookbooks/build-essential/recipes/_fedora.rb to /tmp/chef-build-essential-build20151029-2541-1q3unvu/build-essential/recipes/_fedora.rb
DEBUG: Staging /root/chef-repo/cookbooks/build-essential/recipes/_smartos.rb to /tmp/chef-build-essential-build20151029-2541-1q3unvu/build-essential/recipes/_smartos.rb
DEBUG: Staging /root/chef-repo/cookbooks/build-essential/recipes/_suse.rb to /tmp/chef-build-essential-build20151029-2541-1q3unvu/build-essential/recipes/_suse.rb
DEBUG: Staging /root/chef-repo/cookbooks/build-essential/recipes/default.rb to /tmp/chef-build-essential-build20151029-2541-1q3unvu/build-essential/recipes/default.rb
DEBUG: Staging /root/chef-repo/cookbooks/build-essential/recipes/_omnios.rb to /tmp/chef-build-essential-build20151029-2541-1q3unvu/build-essential/recipes/_omnios.rb
DEBUG: Staging /root/chef-repo/cookbooks/build-essential/libraries/xcode_command_line_tools.rb to /tmp/chef-build-essential-build20151029-2541-1q3unvu/build-essential/libraries/xcode_command_line_tools.rb
DEBUG: Staging /root/chef-repo/cookbooks/build-essential/libraries/matchers.rb to /tmp/chef-build-essential-build20151029-2541-1q3unvu/build-essential/libraries/matchers.rb
DEBUG: Staging /root/chef-repo/cookbooks/build-essential/libraries/timing.rb to /tmp/chef-build-essential-build20151029-2541-1q3unvu/build-essential/libraries/timing.rb
DEBUG: Staging /root/chef-repo/cookbooks/build-essential/attributes/default.rb to /tmp/chef-build-essential-build20151029-2541-1q3unvu/build-essential/attributes/default.rb
DEBUG: Staging /root/chef-repo/cookbooks/build-essential/README.md to /tmp/chef-build-essential-build20151029-2541-1q3unvu/build-essential/README.md
DEBUG: Staging /root/chef-repo/cookbooks/build-essential/CHANGELOG.md to /tmp/chef-build-essential-build20151029-2541-1q3unvu/build-essential/CHANGELOG.md
DEBUG: Staging /root/chef-repo/cookbooks/build-essential/metadata.json to /tmp/chef-build-essential-build20151029-2541-1q3unvu/build-essential/metadata.json
DEBUG: Generating metadata
ERROR: knife encountered an unexpected error
This may be a bug in the 'supermarket share' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NameError: undefined local variable or method `method_name' for Chef::Cookbook::Metadata:Class

**Comment by levkov** [comment]
Chef Development Kit Version: 0.9.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2

**Comment by vdel26** [comment]
+1 I'm having the exact same issue here. My local Chef environment:

```
Chef Development Kit Version: 0.8.1
chef-client version: 12.4.3
berks version: 4.0.1
kitchen version: 1.4.2
```

**Comment by btm** [comment]
I can't reproduce this on ChefDK 0.8.1 or ChefDK 0.9.0. I tried using the metadata.rb from some of the cookbooks linked to but it didn't matter.

Can someone who is able to reproduce this share the metadata.* files from the temporary directory that is created?

**Comment by alexpop** [comment]
Here are repro commands by uploading the `windows` cookbook to a local supermarket:

```bash
[12:17:24 /tmp/cookbooks3]$ knife cookbook site download windows
Downloading windows from Supermarket at version 1.38.3 to /private/tmp/cookbooks3/windows-1.38.3.tar.gz
Cookbook saved: /private/tmp/cookbooks3/windows-1.38.3.tar.gz
[12:17:32 /tmp/cookbooks3]$ tar -xzf windows-1.38.3.tar.gz
[12:17:51 /tmp/cookbooks3]$ knife supermarket share windows -o .
ERROR: knife encountered an unexpected error
This may be a bug in the 'supermarket share' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NameError: undefined local variable or method `method_name' for Chef::Cookbook::Metadata:Class
[12:18:03 /tmp/cookbooks3]$
```
^ Same error with other cookbooks like: `push-jobs`, `mysql`, `yum-epel`

Same commands work fine for the yum cookbook:
```bash
[12:18:03 /tmp/cookbooks3]$ knife cookbook site download yum
Downloading yum from Supermarket at version 3.8.2 to /private/tmp/cookbooks3/yum-3.8.2.tar.gz
Cookbook saved: /private/tmp/cookbooks3/yum-3.8.2.tar.gz
[12:18:36 /tmp/cookbooks3]$ tar -xzf yum-3.8.2.tar.gz
[12:19:13 /tmp/cookbooks3]$ knife supermarket share yum -o .
Making tarball yum.tgz
Upload complete!
[12:19:47 /tmp/cookbooks3]$
```

Setup:
```bash
[12:19:47 /tmp/cookbooks3]$ chef -v
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2
[12:23:31 /tmp/cookbooks3]$ chef gem list knife-supermarket

*** LOCAL GEMS ***

knife-supermarket (0.2.1)
```

**Comment by alexpop** [comment]
The bug has to do with cookbook dependencies. 
If the cookbook only contains a metadata.json and it has dependencies, you'll get the reported error. 
From my previous example, I removed the `chef_handler` dependency from the `windows` cookbook and share succeeded:

```bash
[12:47:51 /tmp/cookbooks3]$ knife supermarket share windows -o .
Making tarball windows.tgz
Upload complete!
```

**Comment by lamont-granquist** [comment]
So what is the workflow being encountered here where knife cookbook site share needs to work with a cookbook that has had its metadata.rb stripped out?  What steps generated the metadata.json and stripped the metadata.rb?

**Comment by alexpop** [comment]
The workflow I've seen was like this:
*Hey, this stuff works, supermarket is awesome, download, download, download. Hey, we need to review and store these cookbooks in our version control now. Hey, we need to push these cookbooks and consume them from our private supermarket now.*

**Comment by DPD-30** [comment]
Seeing same issue here.  Any package that has been uploaded to public supermarket without a metadata.rb is not able to be pushed to a private supermarket with knife supermarket share if it has a dependancy.  Berkshelf packages cookbooks without the metadata.rb as I belive the stove tool does also.

**Comment by daften** [comment]
I have a metadata.rb and no metadata.json file in my cookbook.

**Comment by trinitronx** [comment]
I ran into this while trying to share a cookbook with only `metadata.rb`, however it was managed by [Berkshelf][1], and was first:

 - installed from GitHub source with `berks install`
 - Uploaded to hosted Chef with `berks upload`
 - Vendored into a Chef Repo (e.g: `~/src/pub/chef-repo/cookbooks`) with `berks vendor cookbooks/`
 - Shared to Supermarket with `knife cookbook site share my-cookbook "Applications"  -o cookbooks`

Due to the back & forth from Chef Server with `berks upload` & `berks vendor`, the `metadata.rb` gets converted into `metadata.json`.  Thus, `knife cookbook site share my-cookbook "Applications" -o cookbooks -VV` returned an error:

    INFO: Using configuration from /home/trinitronx/.chef/knife.rb
    DEBUG: No chefignore file found at /home/trinitronx/src/pub/chef-repo/chefignore no files will be ignored
    DEBUG: No chefignore file found at cookbooks/site-cookbooks/chefignore no files will be ignored
    INFO: Validating ruby files
    INFO: Validating templates
    INFO: Syntax OK
    DEBUG: Staging at /tmp/chef-my-cookbook-build20160118-18240-mu1l3x
    DEBUG: Staging /home/trinitronx/src/pub/chef-repo/cookbooks/my-cookbook/recipes/default.rb to /tmp/chef-my-cookbook-build20160118-18240-mu1l3x/my-cookbook/recipes/default.rb
    DEBUG: Staging /home/trinitronx/src/pub/chef-repo/cookbooks/my-cookbook/attributes/default.rb to /tmp/chef-my-cookbook-build20160118-18240-mu1l3x/my-cookbook/attributes/default.rb
    DEBUG: Staging /home/trinitronx/src/pub/chef-repo/cookbooks/my-cookbook/chefignore to /tmp/chef-my-cookbook-build20160118-18240-mu1l3x/my-cookbook/chefignore
    DEBUG: Staging /home/trinitronx/src/pub/chef-repo/cookbooks/my-cookbook/README.md to /tmp/chef-my-cookbook-build20160118-18240-mu1l3x/my-cookbook/README.md
    DEBUG: Staging /home/trinitronx/src/pub/chef-repo/cookbooks/my-cookbook/Rakefile to /tmp/chef-my-cookbook-build20160118-18240-mu1l3x/my-cookbook/Rakefile
    DEBUG: Staging /home/trinitronx/src/pub/chef-repo/cookbooks/my-cookbook/metadata.json to /tmp/chef-my-cookbook-build20160118-18240-mu1l3x/my-cookbook/metadata.json
    DEBUG: Staging /home/trinitronx/src/pub/chef-repo/cookbooks/my-cookbook/Gemfile to /tmp/chef-my-cookbook-build20160118-18240-mu1l3x/my-cookbook/Gemfile
    DEBUG: Generating metadata
    ERROR: knife encountered an unexpected error
    This may be a bug in the 'cookbook site share' knife command or plugin
    Please collect the output of this command with the `-VV` option before filing a bug report.
    Exception: NameError: undefined local variable or method `method_name' for Chef::Cookbook::Metadata:Class
    
After manually applying @andy-dufour's patch above to my ChefDK install at: `/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/cookbook/metadata.rb`, I re-ran `knife cookbook site share my-cookbook "Applications" -o cookbooks` and it worked!

So, this patch worked for me: https://github.com/chef/chef/commit/3d769be3383f7f73c3ee6ed7bce75e40f2ae56c6
[1]: http://berkshelf.com/

**Comment by andy-dufour** [comment]
Awesome! if anyone needs to manually patch that commit will likely work, and it's super simple.

We're discussing a more complete patch here: https://github.com/chef/chef/pull/4428

**Comment by daften** [comment]
This patch did work, following up in the PR. 
Thanks everybody for the input :)

**Comment by dfduarte** [comment]
The patch above doesn't works for me =(, too bad...

I got the output of -VV, and its almost the same.

```
DEBUG: Generating metadata
/Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/cookbook/metadata.rb:626:in `block (2 levels) in validate_json': undefined local variable or method `method_name' for Chef::Cookbook::Metadata:Class (NameError)
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/cookbook/metadata.rb:625:in `each'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/cookbook/metadata.rb:625:in `block in validate_json'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/cookbook/metadata.rb:623:in `each'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/cookbook/metadata.rb:623:in `validate_json'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/knife/cookbook_metadata.rb:96:in `validate_metadata_json'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/knife/cookbook_metadata.rb:69:in `block in generate_metadata'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/knife/cookbook_metadata.rb:64:in `each'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/knife/cookbook_metadata.rb:64:in `generate_metadata'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/knife/cookbook_metadata.rb:59:in `run'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/cookbook_site_streaming_uploader.rb:62:in `create_build_dir'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/knife/cookbook_site_share.rb:72:in `run'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/knife-supermarket-0.2.4/lib/chef/knife/supermarket_share.rb:54:in `run'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/knife.rb:416:in `block in run_with_pretty_exceptions'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/knife.rb:415:in `run_with_pretty_exceptions'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/knife.rb:214:in `run'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/application/knife.rb:148:in `run'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/bin/knife:25:in `<top (required)>'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/bin/knife:23:in `load'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/bin/knife:23:in `<main>'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/dduarte/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

I've updated to the latest Chef-DK version (and knife-supermarket plugin), but the problem stills happening. Is there a another solution for that?

**Comment by dfduarte** [comment]
Nevermind guys, it works! Thanks @andy-dufour.

The problem here was: I use a MacOS Captain here, and for some reason, Chef-DK copies itself for 2 different folders. In my case, I has the same metadata file in:

/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/cookbook/metadata.rb
/Users/xxxxxxx/.rvm/gems/ruby-2.2.1/gems/chef-12.7.2/lib/chef/cookbook/metadata.rb

I think it's some problem with the way I've installed Chef for the first time (that time, I didn't use cask)

**Comment by sadaf2605** [comment]
Having same error with:

> chef -v
> Chef Development Kit Version: 0.19.6
> chef-client version: 12.15.19
> delivery version: master (802e801d920ea6b6d48db735aa7c6e7a6194bea4)
> berks version: 5.1.0
> kitchen version: 1.13.2
>

**Comment by btm** [comment]
@sadaf2605 what does your stacktrace look like that comes from `knife cookbook site share CKBK -V -V` ?

**Comment by lamont-granquist** [comment]
I'm working on this in a branch right now
