### ISSUE TITLE
knife status: ArgumentError: comparison of Hash with Hash failed

### ISSUE THREAD

**Issue by bwann** [chef/chef#3899]
Whenever I try "knife status", I get an "ERROR: ArgumentError: comparison of Hash with Hash failed". I'm not sure what exactly lead up to it breaking, it used to work for me. I don't seem to have any weird node data, I can run a "knife show" for each of my nodes and they all look sane.

Verbose error: https://gist.github.com/bwann/32ecbc64b3ab83e7cca8

client/knife verson:  Chef: 12.4.1
Chef server version: 12.4.1

**Comment by bwann** [comment]
Looks like a node with no ohai time did this. Dumping variables n1 and n2 in the all_nodes.sort function, knife status died on this node

n1: {"name"=>"simple02", "ipaddress"=>{}, "ohai_time"=>{}, "ec2"=>nil, "run_list"=>[], "platform"=>{}, "platform_version"=>{}, "chef_environment"=>"_default"}

n2: {"name"=>"canary20", "ipaddress"=>"192.168.170.18", "ohai_time"=>1442697742.9531252, "ec2"=>nil, "run_list"=>["recipe[site-init]", "role[canary_role]"], "platform"=>"raspbian", "platform_version"=>"7.8", "chef_environment"=>"_default"}
ERROR: ArgumentError: comparison of Hash with Hash failed

When I deleted the "simple02" node and client from the server, knife status started working again.

**Comment by tas50** [comment]
I'm going to close this one out since it's been 6 years and we don't really have the information to fully debug the issue at this point.
