### ISSUE TITLE
'chef generate recipe' doesn't use cookbook name in metadata.rb file

### ISSUE THREAD

**Issue by mwiczynski-cartera** [chef/chef#3902]
### Version:
Chef Development Kit Version: 0.6.2
chef-client version: 12.3.0
berks version: 3.2.4
kitchen version: 1.4.0

### Environment: 
mac osx 10.10.4

### Scenario:
Add a recipe using chef generate recipe. Breaks when git repo(cookbook dir) name is not same as cookbook name.  I want to name my git repo differently than the cookbook name.

### Steps to Reproduce:
chef generate cookbook foo
mv foo cookbook-foo
cd cookbook-foo
chef generate recipe bar

### Expected Result:
rspec and kitchen to run successfully.

### Actual Result:
I only included rspec output.  kitchen has similar problem finding cookbook.
```
================================================================================
Error Resolving Cookbooks for Run List:
================================================================================

Missing Cookbooks:
------------------
No such cookbook: cookbook-foo

Expanded Run List:
------------------
* cookbook-foo::bar

F.

Failures:

  1) cookbook-foo::bar When all attributes are default, on an unspecified platfo
rm converges successfully                                                      
     Failure/Error: runner.converge(described_recipe)
     Net::HTTPServerException:
       412 "Precondition Failed "
     # ./spec/unit/recipes/bar_spec.rb:13:in `block (3 levels) in <top (required
)>'                                                                            
     # ./spec/unit/recipes/bar_spec.rb:17:in `block (3 levels) in <top (required
)>'                                                                            

Finished in 3.37 seconds (files took 3.72 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/unit/recipes/bar_spec.rb:16 # cookbook-foo::bar When all attributes
 are default, on an unspecified platform converges successfully                
```

**Comment by lamont-granquist** [comment]
This is the repo for chef-client, needs to be refiled under http://github.com/chef/chef-dk/issues/new

**Comment by mwiczynski-cartera** [comment]
Thanks for pointing me to correct repo.  It isn't listed as a choice here: https://docs.chef.io/community_contributions.html#issues-and-bug-reports

**Comment by lamont-granquist** [comment]
Thanks for pointing out how you got steered in the wrong direction, I'll work on fixing that.
