### ISSUE TITLE
Stdout from sensitive execute resource displays with chef-client -l debug

### ISSUE THREAD

**Issue by structurefall** [chef/chef#3903]
I have a sensitive execute block in one of my cookbooks. Normally, running chef-client suppresses the output from this block, as it should, however if I run it with `-l debug`, stdout goes straight to my terminal:

```
# chef-client -l debug
Starting Chef Client, version 12.4.1
resolving cookbooks for run list: 
```

...

```
  * execute[my-execute-block] action run
```

<em>(tons of stuff that we shouldn't be able to see)</em>

<pre>    - execute sensitive resource
  * execute[next-thing] action run</pre>

This is undesirable ಠ_ಠ

I noted <a href="https://github.com/chef/chef/issues/3813">this issue</a>, which is similar, but in this case the execution was successful, and debug mode was the variation.

**Comment by tas50** [comment]
I don't think this is actually the case in modern Chef Infra Clients. If someone is still having this issue with 17+ please file a new issue and we can track down what happens there.
