### ISSUE TITLE
chef push job client for AIX

### ISSUE THREAD

**Issue by ensean** [chef/chef#3905]
Hi, we know that chef push job client currently supports Linux/Windows, when will it support AIX ?

**Comment by lamont-granquist** [comment]
Wrong repo, see https://github.com/chef/chef-push

This is also meant as a bugtracker, and if you've got a support inquiry that's better handled through zendesk:   https://getchef.zendesk.com/hc/en-us or the feedback site: https://feedback.chef.io/
