### ISSUE TITLE
resource common functionality  not working under chef-client 11.64

### ISSUE THREAD

**Issue by nitheeshp** [chef/chef#3906]
I am trying to hide sensitive information on execute resource  when chef-client  runs and i am using chef-client version 11.6.4  . But it is working only above chef-client version 12 and above . But as per release document  chef-client version 11.6.4 is supporting  - http://docs.chef.io/release/11-16/resource_common.html

execute 'mysql login' do
   command  'mysql -h localhost -u root -psomepassword'
  sensitive true 
end

**Comment by coderanger** [comment]
Support for hiding execute output was only added in 12.0.

**Comment by nitheeshp** [comment]
But this releases document says it is supporting in  11.64
http://docs.chef.io/release/11-16/resource_common.html
