### ISSUE TITLE
chef-apply cannot process include undefined method `unreachable_cookbook?' for nil:NilClass

### ISSUE THREAD

**Issue by h4ck3rm1k3** [chef/chef#3914]
see http://stackoverflow.com/questions/30031076/fatal-nomethoderror-undefined-method-unreachable-cookbook-for-nilnilclass/32549316#32549316

Chef apply does not instantiate the cookbook_compiler variable in the run context object via the load method (https://github.com/chef/chef/blob/master/lib/chef/run_context.rb#L157). Therefore the compiler object on this line https://github.com/chef/chef/blob/master/lib/chef/run_context.rb#L469 is nil. It seems to me that the compiler will need to initialized.

**Comment by ranjib** [comment]
chef-apply is designed to executed single file recipe. its not supposed to support whole cookbooks (i.e dependencies, segments like template/files etc).

**Comment by h4ck3rm1k3** [comment]
This is not an acceptable outcome, your code is obviously not checking for conditions and the error message is confusing. Please at least make it robust.

**Comment by ranjib** [comment]
@h4ck3rm1k3 if you mean that chef-apply should give a more readable error, then thats definitely something we should fix. I can change the title of this ticket to 'chef-apply should throw better error message when include_recipe is used.' Currently this ticket reads like theres an error in chef-apply code.
