### ISSUE TITLE
chef-client run should honor original exception in all fork/nofork use cases. (windows/linux)

### ISSUE THREAD

**Issue by carpnick** [chef/chef#3916]
### Summary

When [Chef-client runs](https://github.com/chef/chef/blob/master/lib/chef/application.rb#L207) Linux nodes go into a [fork](https://github.com/chef/chef/blob/master/lib/chef/application.rb#L256), all exceptions are caught and exit code is changed based on errors.  Then the [handling code](https://github.com/chef/chef/blob/master/lib/chef/application.rb#L285) throws an exception if error is found.

The [no-fork use case](https://github.com/chef/chef/blob/master/lib/chef/application.rb#L245), default on windows and on linux can be changed with --no-fork option,  allows exceptions to bubble up.
### Scenario
- When executing a chef-client run, we would like to know the exact exit code from recipe/resource.  In our chef runs we are exiting with specific exit codes to determine what to do next.  We are using exit codes as control flow.  We would like to use the default chef-client behavior.
### Questions and behaviors
- Should we just use the --no-fork option for this use case?  Is this being deprecated anytime soon?  Any other differences in behaviors we should be worried about?
- Should the fork case honor "SystemExit" exceptions, and let those control the exit code?
  -  This also would entail changing the  handling code
- Why is the forked use case performing a new exception type, and not honoring the original chef-client exception?  When doing a search on [the exception](https://github.com/chef/chef/search?utf8=%E2%9C%93&q=ChildConvergeError) this is the only spot it is used.

**Comment by lamont-granquist** [comment]
You don't get the ruby Exception back from the operating system, so we can't throw the same Exception that the child threw.  I'm not sure how to inject an exitstatus into an exception that gets raised, if you can figure that out you could submit a PR to do that.  The alternative would be to stop raising and just call exit with the child exitstatus.  That could also use a PR so people could discuss it.

**Comment by carpnick** [comment]
Referencing PR- https://github.com/chef/chef/issues/3916

**Comment by smurawski** [comment]
@Carpnick I've got some updates inbound to that pr on this. Gimme a day or so.

**Comment by carpnick** [comment]
@smurawski Thanks.  I saw the note in the PR that you noticed the same thing I did.  Was just referencing this issue to your PR, since this issue basically goes away with the exit code refactor you are currently working through.
