### ISSUE TITLE
Fix knife bootstrap

### ISSUE THREAD

**Issue by thommay** [chef/chef#3920]
at least:
use `mixlib-install` for both windows and unix
don't write a big ass command into syslog and ps and blurgh
get some real debugging and logging

**Comment by thommay** [comment]
#3662 is affected by this.

**Comment by thommay** [comment]
#3872 and #3871 are part of this

**Comment by lamont-granquist** [comment]
Per #3872 the way that we should fix this via using scp to copy up the file should also follow the pattern of:

1.  create a tmpdir in /tmp
2.  enforce mode 600 on the tmpdir
3.  copy a file to the tmpdir
4.  fix the uploaded files perms
5.  mv the uploaded file into place

That should get it right no matter what the umask is set to on the target machine, without having to worry about getting umask over ssh right all the time (particularly with scp, using net-ssh, which might work, or might be buggy--while i can prove that the above algorithm only has a race which might expose a readable empty tmpdir)

**Comment by thommay** [comment]
#3887 too!

**Comment by CodingSpiderFox** [comment]
This quite an old issue, why hasn't it been resolved? What's the status?

**Comment by btm** [comment]
The first half of this was fixed in Chef 15 in https://github.com/chef/chef/issues/3871#issuecomment-527626952. The second half will be fixed in Chef 16 in #8465 

It's taken a long time mostly because there's a lot of breaking changes that have to be worked out on annual major releases.

**Comment by lamont-granquist** [comment]
Updating bootstrap to use mixlib-install is now being tracked in #8468

This issue is probably too wide to be useful and is at least 50-75% done.
