### ISSUE TITLE
Cookbook Metadata Level Up Epic

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#3924]
- we need to implement chef_version
- we need to support multiple version dependencies in cookbooks
- we need to support 'supports' better, and multiple versions.

there's probably common code/implementation that we need under 'depends'/'chef_version'/'supports' for handling multiple version constraints.  the chef-server team believes the servers can handle that and no code changes are needed there.   we need to implement chef_version per the RFC that got approved for that.

**Comment by lamont-granquist** [comment]
#2457 is incorporated in this

**Comment by lamont-granquist** [comment]
https://tickets.opscode.com/browse/CHEF-4727 is incorporated in this

**Comment by lamont-granquist** [comment]
https://github.com/chef/chef-rfc/blob/master/rfc037-chef-ohai-version-metadata.md is incorporated in this

**Comment by coderanger** [comment]
If we are adding metadata, I would also love to see a generic hash mechanism available like Rubygems has with `spec.metadata`. Would allow experimenting more in the future without stop-the-world level changes.

**Comment by lamont-granquist** [comment]
The whole metadata now is kind of that way.  The server doesn't reject anything.  And Chef 12 client (and knife, and chef-dk) now ignores metadata that it doesn't know about (IIRC I actually made it warn when it finds metadata it doesn't understand).  We can add anything and maintain backcompat.

**Comment by tas50** [comment]
Closing this out since all we have left at this point is the multiple versions part
