### ISSUE TITLE
homebrew_package fails too early if homebrew is installed but homebrew_user has been removed

### ISSUE THREAD

**Issue by spkane** [chef/chef#3925]
There is a bit of a chicken and egg problem here, that should fail more gracefully. 

A run-list that creates an OS X user, and then installs homebrew for that user, works as expected.

However, if you later remove the user (like during testing), everything breaks badly (unless you also uninstall homebrew), even though the user would be re-created before it is actually needed by homebrew or any package installs.

This seems to happen because Chef detects that homebrew is installed and has a homebrew_owner defined, and then can't find that user, and fails. It might be better, if this only generated a warning and continued. That way if this user is recreated before the first package call, things should still work fine.

If you get to the first package and the user still doesn't exist, this seems like a better time to have a fatal error.

**Comment by lamont-granquist** [comment]
Could use actual output of the stack trace of the error.  The logical place I'd look for that error is in the provider code, and if its there it wouldn't cause the behavior you're seeing, which means I couldn't guess where its blowing up.

**Comment by spkane** [comment]
After looking at this a bit closer. The issue is actually in the Homebrew cookbook, and not the actual provider. I'll close this and open a bug there.
