### ISSUE TITLE
Knife Bootstrap API does not respect `:environment` config variable

### ISSUE THREAD

**Issue by evan2645** [chef/chef#3927]
When consuming Knife Bootstrap via its API, the `:environment` config variable is not considered during the rendering of the bootstrap template. This results in the node being bootstrapped in the `_default` environment, despite being explicitly configured otherwise.

Knife's Bootstrap Context uses a hash of Knife's config values, plus chef config values, to build the bootstrap template. When invoking Knife by CLI, the `:environment` config variable is transposed into `Chef::Config`, but this is not the case when using the API. Bootstrap Context looks at `Chef::Config` only, and ignores any value of `:environment` that has been explicitly passed to it in the Knife config hash.

Instead, we should prefer the value in the Knife config, and absent one, fall back to looking in `Chef::Config`. I have pushed a proposed fix, here: https://github.com/chef/chef/pull/3864

The Chef repo was failing its tests when I branched from it. I have verified that my tests are passing. I'm not sure whether I should rebase it, open a new one, etc...

**Comment by lamont-granquist** [comment]
Subtask of #3946 epic

**Comment by evan2645** [comment]
Closed via https://github.com/chef/chef/pull/4105/commits/3bdfa8f65cf19563e35d2bad3f7fcf9263ac7881
