### ISSUE TITLE
Environment attribute with duplicate key overwrites values with no warning

### ISSUE THREAD

**Issue by tfitch** [chef/chef#3933]
So I have an environment file I call `dupe-env.rb` with the contents

```
name 'dupe-env'
description 'The duplicate attribute test  environment'
default_attributes 'tfitch' => {
  'kdc' => '1.example.com',
  'kdc' => '2.example.com'
}
```

I do a `knife environment from file dupe-env.rb` and it will happily create (or update) the new environment on my Chef server.

But when I do a `knife environment show dupe-env` the output is this

```
chef_type:           environment
cookbook_versions:
default_attributes:
  tfitch:
    kdc: 2.example.com
description:         The duplicate attribute test  environment
json_class:          Chef::Environment
name:                dupe-env
override_attributes:
```

The two `kdc` values are squashed down to one.  Now this makes sense, there's a namespace collision, so the last one in the file wins.  BUT - there's no warning to the user that their data is being squashed.  I think when `knife` parses the environment file (either Ruby or json) and it notices duplicates keys, it should give a user a heads up of `Hey, I'm overriding the value of kdc attribute because it appears more than once in the attribute definition.`

Something like that to help out the users, so they're not wondering where all their data went.  (The example a customer first showed me for this problem had seven kdc values being "consolidated" down to one and they were confused.)

**Comment by coderanger** [comment]
This isn't something Chef can control or detect, it is how Ruby parses source code. The same is true in JSON too, if you have `{"x": 1, "x": 2}` most libraries will give you `{"x" => 1}` when parsed. Chef is, in these cases, reliant on the parser behaviors of the higher-level tools.

**Comment by tfitch** [comment]
Well there's a lot of parsing and object mapping happening in here that makes me think this *might* be possible.  https://github.com/chef/chef/blob/master/lib/chef/json_compat.rb

It's bad UX the way it currently is, so I'll ask the engineering team about it on Monday.

**Comment by coderanger** [comment]
You were using the Ruby DSL format, so I was only mentioning JSON for comparison. With JSON formats we might be able to hook into something low level in the library we use, but with the Ruby format there is 100% no way to know that anything has happened. We just get a Ruby Hash object and how it was parsed is lost by then.

**Comment by tfitch** [comment]
Well, if it can be handled when the environment is defined in JSON, that'd be better than not handling it at all.

On the Ruby side, seems like it'll have to handled with an update to the docs to remind people about how Ruby handles Hash keys with repeated key names.

**Comment by danielsdeleo** [comment]
I suppose it would be possible to make a linter type thing, but by the time the code is evaluated, we won't be able to do anything. For example, running `ruby -w -rpp -e 'pp({"a" => 1, "a" => 2})'` is basically the same thing as described in the bug report, and it doesn't cause a ruby warning.
