### ISSUE TITLE
Excessive package size on Windows for 12.4.2

### ISSUE THREAD

**Issue by adamedx** [chef/chef#3943]
From a mailing list post:

> Looks like the 12.4.2 (128MB) windows client install is a bit larger than 12.4.1 (74MB). 

This is not desired behavior and should be corrected in the next release.

**Comment by burnzy** [comment]
Also it looks like the x86 version is the only one available for download. Currently, can't see the 64-bit package for 12.4.2.

**Comment by adamedx** [comment]
To clarify, there is actually no x86 vs. x64 package at the moment, there is only one package for all versions of Windows. So if you see a 12.4.2 for Windows, that's the right package: https://downloads.chef.io/chef-client/windows/.

I think what's confusing is that the package has "x86" in the name. That does indicate that the package is composed of binaries that will result in x86 (32-bit) processes running, but 32-bit processes are perfectly legal on 64-bit Windows (up until recently, Windows still shipped both 32-bit and 64-bit browsers on x64 Windows for instance). 

So for the moment the key issue we are tracking here is package size.

**Comment by adamedx** [comment]
This has been resolved in Chef Client release 12.4.3: http://lists.opscode.com/sympa/arc/chef/2015-09/msg00189.html
