### ISSUE TITLE
add --policy-name and --policy-group options to chef-client

### ISSUE THREAD

**Issue by jtimberman** [chef/chef#3947]
The current implementation of policies is that `/etc/chef/client.rb` must be modified to use them. It would be nice, in the spirit of the `-r` and `-o`, to have `--policy-name` and `--policy-group` options that allow setting `node.policy_name` and `node.policy_group` (as implemented in 01be9b1e91e515eb76de43a1e448e5476bd56574).

Use of these options would need to work alongside `-n` (named run list).

**Comment by lamont-granquist** [comment]
help wanted?
