### ISSUE TITLE
Windows chef-client silently ignores client.rb with UTF-16 encoding

### ISSUE THREAD

**Issue by tbriggs-curse** [chef/chef#3949]
While writing a bootstrap script for chef in powershell on windows, I encountered an issue where chef-client silently ignores all settings in the client.rb file (with no errors even in debug) if the file is UTF-16 encoded (which is the default encoding for powershell's 'Out-File').

I've reproduced this on Chef versions 12.4.1 and 12.4.2 on Windows, though it may affect other versions and platforms.

To reproduce, write a client.rb file in powershell as follows:

    PS C:\chef> @"
      raise 'foo'
    "@ | Out-File C:\chef\client.rb

Then `chef-client -c c:\chef\client.rb`, chef will not raise the exception or show any warning message on its failure to load the file.

Running `C:\opscode\chef\embedded\bin\file.exe C:\chef\client.rb` describes the file as 'Little-endian UTF-16'

Running:

    PS C:\chef> @"
      raise 'foo'
    "@ | Out-File -Encoding UTF8 C:\chef\client.rb

Then `chef-client -c c:\chef\client.rb` will correctly raise 'foo', and 'file.exe' describes the file as 'UTF-8'.

Chef should warn the user when it cannot load its configuration due to encoding errors, or be able to load UTF-16 configuration.

**Comment by lamont-granquist** [comment]
Your example is both a good example and indicates it is likely not very fixable.  The workaround is to use a magic comment at the start of the file to indicate that the file is UTF-16:

```ruby
# Encoding: UTF-16
raise 'foo'
```

Then ruby will know its UTF-16 and open it correctly.
