### ISSUE TITLE
Chef resources no longer respect the ordering of `default` and `name_attribute`

### ISSUE THREAD

**Issue by jkeiser** [chef/chef#3950]
Consider the following recipe:

```ruby
class Blah < Chef::Resource::LWRPBase
  attribute :x, default: 'default!', name_attribute: true
  attribute :y, name_attribute: true, default: 'default!'
end

b = Blah.new('name!')
puts b.x.inspect
puts b.y.inspect
```

In 12.4.1, this prints:

```
"default!"
"name!"
```

In master, this prints:
```
"default!"
"default!"
```

12.4.1 used to honor whichever attribute happened to come first. 12.5 (master) no longer does. We can either

1. Honor the old ordering behavior and keep backwards compatibility in all cases.
2. Raise an error if you use both, hurting backwards compatibility in all cases where both are specified.
3. Pick `name_attribute` over `default`, sometimes hurting backwards compatibility when both are specified.
4. Pick `default` over `name_attribute`, sometimes hurting backwards compatibility when both are specified.

I may whip up (1) to see if it can be accomodated (it probably can). But damn if it doesn't seem weird :)

cc @coderanger @jaymzh @lamont-granquist

**Comment by coderanger** [comment]
I think #2 is the most correct of those and should definitely be on the table for Chef 13, I would probably vote for #3 if we want to keep compat for the most part as that is probably what you meant to have happen? I'm also pretty okay calling this a bug, as the fix (remove the default) will work even on older Chef so doing #3 for 12.5 (with a deprecation warning) and #2 for 12.6 or 13.0 seems like a decent plan to me.

**Comment by jkeiser** [comment]
Yeah, #3 was a conscious choice, but ... backcompat is king, so if it's not completely stupid code (and it might be), #1 in 12.5 and #2 in 13.0 might be the best thing.

**Comment by coderanger** [comment]
Yeah, though even with 1, I would still put up a deprecation warning of some kind. "Pick one or the other because this shouldn't be a thing".

**Comment by coderanger** [comment]
Added on #3705 to track for fixing this again in Chef 13.

**Comment by jaymzh** [comment]
should you want me to test this, happy to once there's a nightly with it

**Comment by jaymzh** [comment]
This doesn't seem to be fixed....

chef-12.5.0+20150924083009-1.el6.x86_64

gets the same error.

**Comment by jkeiser** [comment]
@jaymzh can you elaborate? On my build, the recipe at the very top here prints "default!" "name!" which is what 12.4.1 did.

**Comment by jkeiser** [comment]
By "my build" I mean I installed the same nightly on OS/X just now and tried that.

**Comment by jkeiser** [comment]
@jaymzh ah, found the line you mention from #3897. The line you pasted was this:

`attribute :foo, kind_of => String, :default => nil, :name_attribute => true`

That does *indeed* do something different from 12.4.3. Filing a new bug, since this particular one is actually fixed.
