### ISSUE TITLE
Unable to install chef-server on docker container 

### ISSUE THREAD

**Issue by spurti** [chef/chef#3960]
I am unable to install chef-server (chef-server-core_12.0.8-1_amd64.deb) over a docker container (ubuntu 14.04 x86_64).
When running chef-server-ctl reconfigure it fails with following error:
 ================================================================================
    Error executing action `run` on resource 'execute[/opt/opscode/bin/private-chef-ctl start rabbitmq]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /opt/opscode/bin/private-chef-ctl start rabbitmq ----
    STDOUT: warning: rabbitmq: unable to open supervise/ok: file does not exist
    STDERR:
    ---- End output of /opt/opscode/bin/private-chef-ctl start rabbitmq ----
    Ran /opt/opscode/bin/private-chef-ctl start rabbitmq returned 1

**Comment by ranjib** [comment]
@spurti this is chef client related issue tracker, please file a bug against the chef server repo.

i think you wont be able to do this easily in docker,,, chef server omnibus components assumes a full blown base system (docker wont have a process supervisor or init like thing,, and i think the failure is related to that). there might be some workaround.. but im not sure,, also if you want to use it for development purposes use chef-zero ,, goiardi too can be easily run inside docker
