### ISSUE TITLE
Chef resources with `default: nil` honor the default even if you also specify `name_attribute: true`

### ISSUE THREAD

**Issue by jkeiser** [chef/chef#3964]
```ruby
class Blah < Chef::Resource::LWRPBase
  attribute :x, default: nil, name_attribute: true
end

b = Blah.new('name!')
puts b.x.inspect
```

In 12.4.3, this prints:

```
"name!"
```

In master (12.5), this prints:

```
nil
```

The root cause is that `default: nil` is simply ignored by Chef 12.4.3, so it will treat an explicit `default: nil` the same as if you never specified it at all. Thus, if you specify both `default: nil` and `name_attribute: true` _in that order_, 12.5's behavior will change your default to `nil`, where before it was the name of the attribute.

Changing this is distasteful--if you say `default: nil`, it seems like we should treat it as if you *meant* what you said. My belief in the statement "backcompat is king" is being sorely challenged here.

This is branched from #3951.

@jaymzh @coderanger @lamont-granquist

**Comment by jaymzh** [comment]
I *did* mean what I said. The DEFAULT is nil... but I also specified something, so it's not nill.

It's a silly thing to have in there, for sure, but also... if I actually SPECIFY a value, then the default shouldn't have any effect at all.

**Comment by jkeiser** [comment]
@jaymzh `nil` isn't nothing, though :) "I want my default to be `nil`" is a positive statement.

You made two positive statements about the default value for that attribute, and Chef picked the first one :)

**Comment by jkeiser** [comment]
`nil` is a special value used by a *lot* of resources to signify something real for a resource attribute.

I'm going to fix this for 12.5, but I'll make an RFC to deprecate the behavior along with the other `nil` changes that have gone through.

**Comment by jkeiser** [comment]
(Actually, it probably goes straight hand in hand with @coderanger's bug to throw a hard error when multiple statements about your default value happen.)

**Comment by jaymzh** [comment]
I don't understand. Defaults are the value you want if no value was specified.

So if I didn't specify the attribute, it'd be nil. If I do specify the attribute, it's what I specify.

I specified it.

Therefore it's not the default.

What's the confusion?

**Comment by jaymzh** [comment]
Or to put it another way, unless I do "myresource do" in which case there is no nameattribute and therefore I specified nothing, should `default` every come into play. But I DID specify a name of the resource when I did `myresource 'this is a fucking name' do`, then I expect the value of that attribute to overide the default... and get a value of 'this is a fucking name' ... because I specified.... so defaults no longer matter... Yes, of course nil is a thing, but that's not the point, `default` stops coming into play once I'm actually **specifying the attribute's value**

**Comment by jkeiser** [comment]
@jaymzh The way I read it:

- `attribute :x, default: 10` means "I want x to be 10 if the user doesn't specify it."
- `attribute :x, default: nil` means "I want x to be `nil` if the user doesn't specify it."
- `attribute :x, name_attribute: true` means "I want x to equal `name` if the user doesn't specify it."
- `attribute :x, default: 10, name_attribute: true` is ambiguous: if the user doesn't specify x, should x equal `name` or 10? The user said both.
- `attribute :x, default: nil, name_attribute: true` is just as ambiguous: if the user doesn't specify x, should x equal `name` or `nil`? The user said both.

This is philosophy though, and moot in Chef 13 due to the fact that you won't be allowed to say `default` and `name_attribute` together. In Chef 12, I've already submitted a patch :)

**Comment by jkeiser** [comment]
@jaymzh IMO, one of the best ways to think about it is to treat `name_attribute: true` as exactly equivalent to `default: lazy { name }`.

**Comment by jaymzh** [comment]
@jkeiser I see how you got there. Because that's what the code does under the hood (mostly).

But from a user perspective, it seems more like you're telling it that the user can specify this at this location... (the name of the resource), not that it's a default.

**Comment by jaymzh** [comment]
Anyway - I'm nuking that stupidity from our codebase now. Even if you think about it the way I think about it it's a "danging/useless" setting.  Now that I've preserved some backcompat, I'm moving forward with testing the rest of 12.5. ;)

**Comment by jaymzh** [comment]
On this note... could your warning actually tellus which resource did this:

[2015-09-24T17:41:58-07:00] WARN: Cannot specify keys default, name_attribute together on property name--only the first one (default) will be obeyed. Please pick one. at /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.0.current.0/lib/chef/mixin/from_file.rb:42:in `class_eval'


doesn't provide any indication of what resource is doing this. :(

**Comment by jkeiser** [comment]
@jaymzh hmm, I guess it's time to stop guessing how far back in the stack trace the "callsite" is and start getting smarter about it.  It requires a search back through `caller()` but it's doable--I was just trying to wait on it :)

**Comment by jkeiser** [comment]
@jaymzh regarding your interpretation, I can see where that comes from. The thing that makes me see it as a default is this:

```
e = execute '/usr/bin/bash' do
end
e = execute 'Run bash' do
  command '/usr/bin/bash'
end
```

Whatever it is, it's not a simple alias because the values can diverge--if you look at the two examples together, the rule *looks* like "if `command` is not set, its value is `name`."
