### ISSUE TITLE
Warning "Ambiguous resource precedence" during chef-client run

### ISSUE THREAD

**Issue by spurti** [chef/chef#3974]
During my chef-client run, I see below warnings:

Ambiguous resource precedence: [Chef::Resource::Package, Chef::Resource::YumPackage], please use Chef.set_resource_priority_array to provide determinism
How could this be resolved ?

I have tried adding these lines to my library:

Chef.set_resource_priority_array(:package, [ Chef::Resource::YumPackage ], os: 'redhat')
Chef.set_resource_priority_array(:package, [ Chef::Resource::AptPackage ], os: 'ubuntu')

module Ambiguity
  module Resolver
  end
end
and include in the recipes as Chef::Recipe.send(:include, Ambiguity::Resolver)

chef-client version is chef-12.4.0

**Comment by lamont-granquist** [comment]
You'd have to provide more context about what you are doing, and/or try 12.4.3 and see if they go away.

**Comment by spurti** [comment]
While using "package" resource in my recipe I am facing these warnings. Recipe is meant to run both on ubuntu and rhel.

**Comment by lamont-granquist** [comment]
Try 12.4.3?

**Comment by thommay** [comment]
We believe these warnings were resolved by 12.4.3
