### ISSUE TITLE
Chef config always in C:\chef when using windows MSI

### ISSUE THREAD

**Issue by lbn-chef-team** [chef/chef#3980]
Hello,

When we set the chef folder in MSI (as default c:\opscode\chef), the config folder is forced to be C:\chef. This is an inconveniant when using MSI because we have to make the changes after install.

The config folder could be moved from c:\Chef to <MSI_install_folder>\chef\config (as default C:\opscode\chef\config) for exemple?

the interest is to have only one folder defined for chef-client in all case.
It is pretty much the same as #3952 with the choice of target folder.

Best Regards,

lbn team,

**Comment by stuartpreston** [comment]
I'm closing this due to age. We should keep configuration and the application installation folders separate so that the application can be upgraded separately.  That is the status-quo today.
