### ISSUE TITLE
node.force_override not setting the attributes correctly

### ISSUE THREAD

**Issue by jmauro** [chef/chef#3982]
Hi everyone,

I have the following code into a cookbook attribute file:
```
force_override[:location][:datacenter] = datacenter
force_override[:location][:country]    = country
force_override[:location][:continent]  = continent
```
This was working with chef 11.18.4
Since we have upgraded to chef 12.4.1, this doesn't work anymore we have to first initialize the namespace to set the attribute right:
```
default[:location] = {}
force_override[:location][:datacenter] = datacenter
force_override[:location][:country]    = country
force_override[:location][:continent]  = continent
```
Is that a bug or a wanted feature?

Regards,
JM

**Comment by lamont-granquist** [comment]
I can't replicate this.

cookbooks/test/attributes/default.rb:

```ruby
force_override[:foo][:bar] = "baz"
force_override[:fizz][:buzz] = "qux"
```

cookbooks/test/recipes/default.rb:

```ruby
puts "foo via strings:"
pp node['foo']
puts "foo via symbols:"
pp node[:foo]
puts "fizz via strings:"
pp node['fizz']
puts "fizz via symbols:"
pp node[:fizz]
```

Those all render correctly:

```
% chef-client -z -j dna.json
Starting Chef Client, version 12.4.1
resolving cookbooks for run list: ["test::default"]
Synchronizing Cookbooks:
  - test
  - multipackage
Compiling Cookbooks...
LIBRARY FILE: Chef::RunContext
foo via strings:
{"bar"=>"baz"}
foo via symbols:
{"bar"=>"baz"}
fizz via strings:
{"buzz"=>"qux"}
fizz via symbols:
{"buzz"=>"qux"}
Converging 0 resources

Running handlers:
Running handlers complete
Chef Client finished, 0/0 resources updated in 5.260798 seconds
```

**Comment by lamont-granquist** [comment]
Wouldn't be surprised if this is just fixed by #3721

**Comment by jmauro** [comment]
Ok I have forgotten to say that I am calling those attribute into another
cookbook attribute file which has the originale cookbook as a dependency,
don't know if that changes anything...

I will try to add more context tomorrow if I can.
Le 29 sept. 2015 01:29, "Lamont Granquist" <notifications@github.com> a
écrit :

**Comment by thommay** [comment]
Since we can't replicate this, and there's a massive refactor of attributes going on, I'm going to close this

**Comment by sun77** [comment]
Hello, 

I'm sorry to reopen this issue but do you have news about the massive refactor of attributes ? 

I have the same issue as Jeremy  : 

An attributes is defined in a recipe A : 

```
node.default[:disk] = {
...
...
}
```

In a recipe B, I need to use it : 
```
node['disk'].select do |dev, conf|
...
...
end
```
But the node['disk'] attribute is nil.

I've tried to debugged with node.debug_value in the recipe B : 
```
pp node.debug_value('disk')
pp node['disk']
```
And : 

pp node.debug_value('disk') : 
```
[["set_unless_enabled?", false],
 ["default",
  {"/dev/sda"=>
    {"options"=>"fstabkey:label disklabel:msdos bootable:1",
     "volume"=>
      [{:type=>"primary",
        :mountpoint=>"/mnt/sysimage",
        :size=>"75GB",
        :filesystem=>"ntfs",
        :mount_options=>"defaults",
        :fs_options=>"createopts=\"-L SYSTEM -f \""},
       {:type=>"primary",
        :mountpoint=>"/mnt/sysimage/d",
        :size=>"50GB-",
        :filesystem=>"ntfs",
        :mount_options=>"defaults",
        :fs_options=>"createopts=\"-L DATA -f\""}]}}],
 ["env_default", :not_present],
 ["role_default", :not_present],
 ["force_default", :not_present],
 ["normal", :not_present],
 ["override", :not_present],
 ["role_override", :not_present],
 ["env_override", :not_present],
 ["force_override", :not_present],
 ["automatic", :not_present]]
```
pp node['disk'] : 
```
nil
```

Are you aware of this kind of issue ? 

Regards, 
Anthony

**Comment by lamont-granquist** [comment]
node.default[:disk] is a symbol while node['disk'] is a string.  that is supposed to work, but was buggy in 12.0.x/12.1.x.  if you're on those versions you need to upgrade.   if you are running chef 12.5.1 and can repro then you can open a new ticket.

**Comment by snkutlu** [comment]
Hi

I am running 12.5.1. Have a similar issue with node.role_default. node.debug_value shows correctly but node['...'] gives nil. 

Same for 12.4.3 as well..

Regards
-Suleyman

**Comment by sun77** [comment]
Hello, 

Yes sorry, I forgot to mention that I have this issue with botch chef 12.4.1 and 12.5.1.

I will open a new issue if needed.

Regards, 
Anthony
