### ISSUE TITLE
Fix package resource/providers

### ISSUE THREAD

**Issue by thommay** [chef/chef#3996]
There's a concern that the package provider is getting very hard to reason about.
we should is to document what the `candidate_version` API is/should_be, then we should tidy up the various providers to use `super` in their candidate_version calls.

we should also ensure that providers properly support arrays of packages, and if they do not then they should advertise that fact.

**Comment by thommay** [comment]
Supporting #3984 and #3938 would be part of this work.

**Comment by lamont-granquist** [comment]
The other thing is that candidate_version maybe should have common logic in the superclass and have some other hook which does the unique fetching of the candidate_version (and probably the unique version string comparison).

**Comment by tas50** [comment]
Closing this issue out as too generic. If we have actionable issues with the package resources at this point we should create issues for those specific items. Issues like this are hard to ever close and aren't helping for tracking the problems.
