### ISSUE TITLE
knife exec works but eventually reports an error when parameter is passed to an .rb script  (Chef 12.1)

### ISSUE THREAD

**Issue by klutarevich** [chef/chef#4001]
When I run "knife exec" with .rb file and a parameter it works (runs some_script.rb and treats "blah" as ARGV[2]) but then returns an error as if it considered "blah" to be the next script to run.
> knife exec some_script.rb "blah" --config C:\chef\client.rb
> ERROR: "blah" not found in current directory or script_path, giving up.

**Comment by thommay** [comment]
This looks like the expected behaviour - knife exec is expecting a list of scripts to be passed in and is executing them one by one.
