### ISSUE TITLE
cannot make a symlink of a directory. 

### ISSUE THREAD

**Issue by hattori** [chef/chef#4008]
Hi there,

I'm stuck on making a symlink of a directory.
I got this error 'Is a directory' when I make a symlink of a directory as the following command in my recipe.

link "/usr/local/foo" do
  to "/usr/local/bar"
end

/usr/local/foo is a directory and exists.
/usr/local/bar doesn't exist yet.
I want to make a symlink so that it would be /usr/local/bar -> /usr/local/foo as a result of 'ls -l' command.

Cheers

**Comment by coderanger** [comment]
This tracker is for bug reports, not for user support. To answer your specific question, you have the path and the `to` in your recipe code backwards, reverse them. Please ask future support questions on the IRC channel, mailing list, or other user support systems.
