### ISSUE TITLE
Recent chef-client solaris sparc packages use sun4v instead of sparc as the architecture.

### ISSUE THREAD

**Issue by MarkGibbons** [chef/chef#4018]
Using sun4v for solaris sparc packages, packages.s3.amazonaws.com/solaris2/5.10/sun4v/chef-12.4.3-1.sun4v.solaris,  is misleading and requires renaming the package for automated use. I have sun4u, sun4us, sun4v, i86pc solaris servers but I think the right architecture names to use would be sparc and i386. The chef-client sun4v package runs on and seems to be intended for all sparc servers.  It looks like the architecture is being picked up from the uname -m command output.  The appropriate command on Solaris would be uname -p to pick up the instruction set architecture.

From the uname man page.
  The arch -k and uname -m commands return equivalent  values;
     however,  the use of either of these commands by third party
     programs is discouraged, as is the use of the  arch  command
     in  general.  To  determine  the  machine's  Instruction Set
     Architecture (ISA or processor type), use uname with the  -p
     option.

Thanks,
  Mark

**Comment by thommay** [comment]
@chef/engineering-services @chef/omnibus-maintainers thoughts on this?

**Comment by schisamo** [comment]
@scotthain is the SME on this.

**Comment by scotthain** [comment]
I'm +1 on this change. @MarkGibbons is correct. I'm not sure if this belongs in Ohai or Omnibus, however...

**Comment by lamont-granquist** [comment]
Changing ohai would probably be a breaking change.  Should probably change omnibus (possibly add a `uname -p` as node[:isa] or whatever if its not already there somewhere, but shouldn't change node[:arch])

**Comment by scotthain** [comment]
That was my thought as well, I wanted to make sure - thanks @lamont-granquist

**Comment by schisamo** [comment]
So just to clarify (and be very specific). The current Solaris packages have `sun4u`/`sun4v` in the name but properly sets the value returned by `uname -p` in the package metadata:
https://github.com/chef/omnibus/blob/f549df66638183b07aa636f687dbabab82a1bb5f/lib/omnibus/packagers/solaris.rb#L91

**Comment by schisamo** [comment]
I also wanted to add the various `uname` output for our future selves:

From a Solaris 10 sparc machine:
```
-bash-3.2$ uname -m
sun4v
-bash-3.2$ uname -p
sparc
```
From a Solaris 10 i386 machine:
```
-bash-3.2$ uname -m
i86pc
-bash-3.2$ uname -p
i386
```

**Comment by lamont-granquist** [comment]
Hmm, so this really needs to go in omnibus-chef, fix doesn't go here.  I'll leave it open, but someone should pick this up as a PR against omnibus itself and link here and close this issue...

**Comment by schisamo** [comment]
@lamont-granquist I'm working on a PR in chef/omnibus right now (will be done this evening). I'll reference this PR from my fix PR.

**Comment by lamont-granquist** [comment]
:+1:
