### ISSUE TITLE
knife bootstrap against OSX 10.10.5 node giving error at first chef-client run (post chef omnibus install)

### ISSUE THREAD

**Issue by chico-san** [chef/chef#4019]
Recent attempt to knife bootstrap a OSX node (10.10.5) giving me an error when bash script is trying to execute "chef-client" for the first time, after omnibus installer successfully installs chef-client.  It installed latest 12.4.3-1.

Changing chef-client to 12.3.0 fixed the issue, so something's not right with the latest 12.4 release at least not for OSX:
# 

Connecting to unity_mac_node.foo.bar
Password: 
unity_mac_node.foo.bar Installing Chef Client...
unity_mac_node.foo.bar   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
unity_mac_node.foo.bar                                  Dload  Upload   Total   Spent    Left  Speed
100 18736  100 18736    0     0  20058      0 --:--:-- --:--:-- --:--:-- 20059
unity_mac_node.foo.bar Downloading Chef 12 for mac_os_x...
unity_mac_node.foo.bar downloading https://www.opscode.com/chef/metadata?v=12&prerelease=false&nightlies=false&p=mac_os_x&pv=10.10&m=x86_64
unity_mac_node.foo.bar   to file /tmp/install.sh.883/metadata.txt
unity_mac_node.foo.bar trying curl...
unity_mac_node.foo.bar url  https://opscode-omnibus-packages.s3.amazonaws.com/mac_os_x/10.10/x86_64/chef-12.4.3-1.dmg
unity_mac_node.foo.bar md5  e0caf8a0bd8b4140191fdfe7946da27c
unity_mac_node.foo.bar sha256   32d290cb5648ea600d976717fa32fc1e213e4452f10dc7b481f4e9aa7200293c
unity_mac_node.foo.bar downloaded metadata file looks valid...
unity_mac_node.foo.bar downloading https://opscode-omnibus-packages.s3.amazonaws.com/mac_os_x/10.10/x86_64/chef-12.4.3-1.dmg
unity_mac_node.foo.bar   to file /tmp/install.sh.883/chef-12.4.3-1.dmg
unity_mac_node.foo.bar trying curl...
unity_mac_node.foo.bar Comparing checksum with shasum...
unity_mac_node.foo.bar Installing Chef 12
unity_mac_node.foo.bar installing dmg file...
unity_mac_node.foo.bar Checksumming Protective Master Boot Record (MBR : 0)…
unity_mac_node.foo.bar Protective Master Boot Record (MBR :: verified   CRC32 $A63E199D
unity_mac_node.foo.bar Checksumming GPT Header (Primary GPT Header : 1)…
unity_mac_node.foo.bar  GPT Header (Primary GPT Header : 1): verified   CRC32 $1D64EDE0
unity_mac_node.foo.bar Checksumming GPT Partition Data (Primary GPT Table : 2)…
unity_mac_node.foo.bar GPT Partition Data (Primary GPT Tabl: verified   CRC32 $443CB9AF
unity_mac_node.foo.bar Checksumming  (Apple_Free : 3)…
unity_mac_node.foo.bar                     (Apple_Free : 3): verified   CRC32 $00000000
unity_mac_node.foo.bar Checksumming disk image (Apple_HFS : 4)…
unity_mac_node.foo.bar ..............................................................................
unity_mac_node.foo.bar           disk image (Apple_HFS : 4): verified   CRC32 $85A4C8ED
unity_mac_node.foo.bar Checksumming  (Apple_Free : 5)…
unity_mac_node.foo.bar                     (Apple_Free : 5): verified   CRC32 $00000000
unity_mac_node.foo.bar Checksumming GPT Partition Data (Backup GPT Table : 6)…
unity_mac_node.foo.bar GPT Partition Data (Backup GPT Table: verified   CRC32 $443CB9AF
unity_mac_node.foo.bar Checksumming GPT Header (Backup GPT Header : 7)…
unity_mac_node.foo.bar   GPT Header (Backup GPT Header : 7): verified   CRC32 $82A9B24E
unity_mac_node.foo.bar verified   CRC32 $38C25161
unity_mac_node.foo.bar /dev/disk3           GUID_partition_scheme  
unity_mac_node.foo.bar /dev/disk3s1         Apple_HFS                       /Volumes/chef_software
unity_mac_node.foo.bar installer: Package name is Chef Client
unity_mac_node.foo.bar installer: Upgrading at base path /
unity_mac_node.foo.bar installer: The upgrade was successful.
unity_mac_node.foo.bar "disk3" unmounted.
unity_mac_node.foo.bar "disk3" ejected.
unity_mac_node.foo.bar Starting first Chef Client run...
unity_mac_node.foo.bar bash: line 100: chef-client: command not found

**Comment by scarz** [comment]
Having absolutely the same problem:
1. Mac OS X version: 10.10.5
2. Chef-client version: 12.4.3

Picking "12.3.0" version for a bootstrap works just fine. Later upgrade to 12.4.3 also works good, the problem happens only on boostrap

**Comment by lamont-granquist** [comment]
Because of 10.11.x not having a writable /usr we now setup symlinks in /usr/local/bin/chef-client.  On package install /usr/local/bin is created if it does not already exist.  Most likely the PATH is not being setup correctly (and even if the installer tried to setup the PATH it can't modify its parent's settings).

The upgrade probably works because the symlinks in /usr/bin are setup by the 12.3.0 install and then not removed correctly (possibly another bug there, but mostly a cosmetic one).

**Comment by lamont-granquist** [comment]
chef-full itself should /probably/ enforce that /usr/local/bin and /usr/bin MUST be on its own PATH -- proabably just by appending those two to its PATH.

**Comment by thommay** [comment]
We did a great big pile of work to make sure this works. If that's not the case with modern versions of chef please open a new ticket.
