### ISSUE TITLE
OpenIndiana/OpenSolaris: user resource is sad on password change

### ISSUE THREAD

**Issue by bwann** [chef/chef#4020]
When specifying a user resource for OpenIndiana with a new password hash, it dies on a usermod error.

root@heroin: ~# chef-client -v
Chef: 12.0.1

Full debug output: https://gist.github.com/bwann/b31e6e786fb05c0497e2

```
root_password = '$6$THOaxLbY$frFXO5VFo3JTstuffstuffstuffsuffOyIBUJHIF95bBknrUMbxLu1VPlGyY/'

user 'root' do
  uid 0
  gid 0
  home '/root'
  shell root_shell
  password root_password
end
```

Results in:

```
STDERR: UX: usermod: ERROR: project $6$THOaxLbY$frFXO5VFo3JTstuffstuffstuffsuffOyIBUJHIF95bBknrUMbxLu1VPlGyY/ does not exist.  Choose another.
UX: usermod: $6$THOaxLbY$frFXO5VFo3JTstuffstuffstuffsuffOyIBUJHIF95bBknrUMbxLu1VPlGyY/ name too long.
UX: usermod: $6$THOaxLbY$frFXO5VFo3JTstuffstuffstuffsuffOyIBUJHIF95bBknrUMbxLu1VPlGyY/ name should be all lower case or numeric.
```

**Comment by lamont-granquist** [comment]
chef-client 12.0.1 is really old and pretty horribly buggy.  I don't know that we fixed anything in the user provider on solaris-ish boxes, but for numerous reasons you should really upgrade and see if you can repro.  Chef 12.x was fairly unusable until 12.2.x and the 12.0.x's were filled with regressions from 12.0.0

**Comment by bwann** [comment]
Upgraded to 12.4.3 and hitting the same problem. What's odd is that I see in CHEF-1707 it looks like this was reported and fixed before (in 11.5?), but I don't see a user provider at all for openindiana in 12.4, only mount and package:

root@heroin:/opt/chef/embedded/lib# /usr/gnu/bin/grep -i openindian -R *
ruby/gems/2.1.0/gems/ohai-8.5.1/lib/ohai/plugins/solaris2/platform.rb:        when /^\s*(OpenIndiana).*oi_(\d+).*$/
ruby/gems/2.1.0/gems/ohai-8.5.1/lib/ohai/plugins/solaris2/platform.rb:          platform "openindiana"
ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/provider/package/ips.rb:        provides :package, platform: %w(openindiana opensolaris omnios solaris2)
ruby/gems/2.1.0/gems/chef-12.4.3/lib/chef/provider/mount/solaris.rb:        provides :mount, platform: %w(openindiana opensolaris nexentacore omnios solaris2 smartos)

**Comment by thommay** [comment]
@bwann this /might/ be as easy a fix as adding `openindiana` to `/opt/chef/embedded/apps/chef/lib/chef/provider/user/solaris.rb` line 27:
```
        provides :user, platform: %w(omnios solaris2 openindiana)
```
If you have a box you could try that on, we can get a patch worked up.

**Comment by lamont-granquist** [comment]
and should that really be:  `%w(openindiana opensolaris nexentacore omnios solaris2 smartos)`?

if i recall correctly one of those at least is netbsd userspace over the solaris kernel which would not want to be using the solaris userspace tools, but i forget which.

**Comment by lamont-granquist** [comment]
illumos is another one

**Comment by thommay** [comment]
@lamont-granquist nexenta is debian-ish, smartos i'm not sure of. but the others ought to be right.

**Comment by lamont-granquist** [comment]
So, patch this to:

```
provides :user, platform:  %w(openindiana opensolaris illumos omnios solaris2 smartos)
```

**Comment by lamont-granquist** [comment]
I suspect all these also need to have their group provider modified to be Chef::Provider::Group::Usermod as well?
