### ISSUE TITLE
Creating an admin user - errors out

### ISSUE THREAD

**Issue by usowmyas** [chef/chef#4022]
[root@ip-172-31-14-160 ~]# chef-server-ctl user-create wem_admin admin wem ************@****.com mypassword --filename /tmp/admin.pem results in following error : 
FATAL: Wrong number of arguments

USAGE: knife opc user create USERNAME FIRST_NAME [MIDDLE_NAME] LAST_NAME EMAIL PASSWORD
    -s, --server-url URL             Chef Server URL
        --chef-zero-host HOST        Host to start chef-zero on
        --chef-zero-port PORT        Port (or port range) to start chef-zero on.  Port ranges like 1000,1010 or 8889-9999 will try all given ports until one works.
    -k, --key KEY                    API Client Key
        --[no-]color                 Use colored output, defaults to false on Windows, true otherwise
    -c, --config CONFIG              The configuration file to use
        --defaults                   Accept default values for all questions
    -d, --disable-editing            Do not open EDITOR, just accept the data as is
    -e, --editor EDITOR              Set the editor to use for interactive commands
    -E, --environment ENVIRONMENT    Set the Chef environment (except for in searches, where this will be flagrantly ignored)
    -f, --filename FILENAME          Write private key to FILENAME rather than STDOUT
    -F, --format FORMAT              Which format to use for output
        --[no-]listen                Whether a local mode (-z) server binds to a port
    -z, --local-mode                 Point knife commands at local repository instead of server
    -u, --user USER                  API Client Username
    -o, --orgname ORGNAME            Associate new user to an organization matching ORGNAME
        --print-after                Show the data after a destructive operation
    -V, --verbose                    More verbose output. Use twice for max verbosity
    -v, --version                    Show chef version
    -y, --yes                        Say yes to all prompts for confirmation
    -h, --help                       Show this message

**Comment by thommay** [comment]
Hi, this is the bug tracker for the chef-client. To report an issue with chef-server, please file it at https://github.com/chef/chef-server/issues . In this instance, I'm not sure that '_' is an allowed character in a username.
