### ISSUE TITLE
knife bootstrap with --bootstrap-version should install that version when chef is found already installed

### ISSUE THREAD

**Issue by jblaine** [chef/chef#4041]
I propose that explicitly indicating a chef version to install via the --bootstrap-version argument should install that version of chef when it finds an existing chef installed already during the bootstrap.

**Comment by lamont-granquist** [comment]
related to the #3920 epic to fix all the knife bootstrap shittiness.

**Comment by tas50** [comment]
@jblaine I'm fairly certain we fixed this with our bootstrap rewrite so I'm going to close this out. Thanks for filing the issue.
