### ISSUE TITLE
Fix Windows Service Management / Upgrade Story

### ISSUE THREAD

**Issue by smurawski** [chef/chef#4042]
As it stands, the Windows service can be installed in several ways, only one of which flags the MSI to know the service exists (to properly upgrade/uninstall).

We need to handle:
- One
  - Install chef-client
  - Use chef-client cookbook to create the service
  - Uninstall chef-client (service should be removed)
- Two
  - Install chef-client 
  - Use chef-client cookbook to create the service
  - Upgrade chef-client  (service should use most recent client)
- Three
  - Install chef-client with service
  - Uninstall chef-client (service should be uninstalled)

We should look at moving the upgrade/install process to use chef-ingredient.

**Comment by vinyar** [comment]
Having a solid in-place upgrade process for chef-client (on windows and in general) would be a massive win!

**Comment by stuartpreston** [comment]
It's 2018 and Chef Client installs as a scheduled task OR as a service and the chef_client_updater can upgrade both of those things.  I'm closing this for now - feel free to reopen if there's something else we should be doing here.
