### ISSUE TITLE
remote_file resource does not allow credentials to be passed in ftp source attribute

### ISSUE THREAD

**Issue by adeconsulting** [chef/chef#4044]
I'm attempting to bootstrap an Ubuntu 12.04 LTS node using Chef 11.10.4.  The remote_file resource is failing because it does not support credentials in the ftp source attribute.  For example, it fails with the error:

"ftp://myuser:my\\$pass_01@192.168.30.15/test.tgz" is not a valid `source` parameter for remote_file. `source` must be an absolute URI or an array of URIs.

**Comment by coderanger** [comment]
Guessing this issue is something related to your specific usage:

```
>> URI.parse("ftp://myuser:my\$pass_01@192.168.30.15/test.tgz").absolute?
=> true
```

Please check that your escape sequences are correct.

**Comment by adeconsulting** [comment]
ok, I will check into that.  Thanks.

**Comment by lamont-granquist** [comment]
Yeah, we just use that API which delegates to URI::FTP under the covers, which certainly does support user and password.   You can use this to build valid URI strings with pry:
```
[1] pry(main)> require 'uri'
=> false
[7] pry(main)> URI::FTP.build(userinfo: "myuser:my\$pass_01", host: "192.168.30.15", path: 'test.tgz').to_s
=> "ftp://myuser:my$pass_01@192.168.30.15/test.tgz"
```

**Comment by coderanger** [comment]
Going to close this as I don't see anything in the code that would be an issue.
