### ISSUE TITLE
Resources: Symbol usage changes sometime > 12.4.3?

### ISSUE THREAD

**Issue by vancluever** [chef/chef#4047]
Hi!

Consider the following resource, consuming a LWRP from https://github.com/gofullstack/backup-cookbook:

```
backup_model :backup_job do
  description 'Backup job desc here'
  definition IO.read("#{Chef::Config[:file_cache_path]}/backup_model.rb")
end
```

(The backup job is written to the cache from a template)

This is functional on systems running Chef 12.4.3.

On some recent kitchen tests using an unpinned Chef (12.5.1), we are now getting the following:

```
Chef::Exceptions::ValidationFailed: Option name must be a kind of [Symbol]!  You passed "backup_job".
```

Even more so, moving the attribute to its `name_attribute`, aptly named `name`, apparently does not correct the issue.

Pinning kitchen to use `require_chef_omnibus: 12.4.3` does fix it, however.

Has something changed with the behaviour surrounding attribute validation?

**Comment by coderanger** [comment]
Names are internally coerced to strings by the DSL. If we ever formally supported using symbols there, I'm unaware of it, nor does it make logical sense. Make your resources names be strings and it should be fine. Also don't use #name for custom properties, that's a part of the resource API and you shouldn't override it unless you have a Very Good Reason™.

**Comment by vancluever** [comment]
Thanks Noah, yeah this is what I suspected. This is the first time I've ever seen a cookbook take a symbol for something like this.

Going to close this now, and work on forking/refactoring this cookbook so that this isn't an issue.

Thanks again!

--Chris

**Comment by ranjib** [comment]
for posterity, package providers that support multi-package, can take array as name :-)
