### ISSUE TITLE
could not parse svn info

### ISSUE THREAD

**Issue by puneetloya** [chef/chef#4050]
```
            subversion("svn qalib") do
             action [:sync]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             destination “/xyz/abc“
             enable_checkout true
             revision "HEAD"
             remote "origin"
             checkout_branch "deploy"
             svn_arguments "--no-auth-cache"
             svn_info_args "--no-auth-cache"
             declared_type :subversion
             cookbook_name “test-agent"
             recipe_name "default"
             repository “valid_url”
             svn_username “abc”
             svn_password “xyz”
             user "root"
           end
```

```
RuntimeError: Could not parse `svn info` data: 
       /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/subversion.rb:181:in `extract_revision_info'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/subversion.rb:135:in `revision_int'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/subversion.rb:110:in `checkout_command'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/subversion.rb:65:in `block in action_checkout'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/mixin/why_run.rb:52:in `call'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/mixin/why_run.rb:52:in `add_action'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:175:in `converge_by'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/subversion.rb:64:in `action_checkout'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider/subversion.rb:98:in `action_sync'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/provider.rb:144:in `run_action'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource.rb:585:in `run_action'
       /chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:49:in `run_action'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block (2 levels) in converge'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `each'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block in converge'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/runner.rb:80:in `converge'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:653:in `block in converge'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:648:in `catch'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:648:in `converge'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:687:in `converge_and_save'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/client.rb:269:in `run'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:270:in `block in fork_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:224:in `block in run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:212:in `run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:408:in `block in interval_run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:398:in `loop'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:398:in `interval_run_chef_client'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:388:in `run_application'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:60:in `run'
         /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/chef-client:26:in `<top (required)>'
         /opt/chef/bin/chef-client:54:in `load'
         /opt/chef/bin/chef-client:54:in `<main>'
```

Important
1) /xyz directory was existing but /xyz/abc was not
2) The same recipe works on Chef 12.4.3 and fails with 12.5.1

**Comment by BarthV** [comment]
:+1: same issue here.
I'm trying to see what's wrong.

**Comment by BarthV** [comment]
since 01419e6c445b7e92912d6f501f7e22926472e4d8 : 
subversion is shelling out to svn command with a "cwd" set to the target directory
* https://github.com/chef/chef/blob/12.5.1/lib/chef/provider/subversion.rb#L133

This is nice but if you give a not existint cwd it wil fail badly : 
```
  * subversion[test-svn] action sync[2015-10-16T16:15:41+02:00] INFO: Processing subversion[test-svn] action sync ((chef-apply cookbook)::(chef-apply recipe) line 1)

[2015-10-16T16:15:41+02:00] DEBUG: Providers for generic subversion resource enabled on node include: [Chef::Provider::Subversion]
[2015-10-16T16:15:41+02:00] DEBUG: Provider for action sync on resource subversion[test-svn] is Chef::Provider::Subversion

/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/mixlib-shellout-2.2.1/lib/mixlib/shellout/unix.rb:183:in `chdir': No such file or directory @ dir_chdir - /tmp/test-svn (Errno::ENOENT)
```

This is due to a wrong cwd definition : 
* https://github.com/chef/chef/blob/12.5.1/lib/chef/provider/subversion.rb#L163-L165

Maybe consider using basename(dir) instead of dir , or maybe something more complex to handle that case ?

Thanks !

**Comment by davemenninger** [comment]
:+1:   same issue here

**Comment by MichaelKueller** [comment]
I have the same issue

**Comment by ckamps** [comment]
Confirmed that the workaround of creating the destination directory in advance of using the subversion resource is successful.

**Comment by BarthV** [comment]
:up: 
Please fix this regression :angel:

**Comment by gtaggart** [comment]
In my case, my SVN repository did not have a "HEAD" revision.  Once I specified a numeric revision, mine worked.

**Comment by klutarevich** [comment]
I can reproduce this issue consistently when the Chef client (12.9.x) running 'subversion' :sync action is installed as a service on Windows. On the other hand when I run chef client from the console the same script works consistently all the time. I think it's due to the fact that Windows services can't use stdin/stdout the same way regular apps do.

**Comment by jchowdhary** [comment]
I am working on Chef Client 12.9.41 and still getting the same error.. I am consistently getting the same error when running in chef client from console too, infact i even tried by first creating the directory where checkout will happen ..but still the same issue..Can you pls. update what is the way forward on this subversion resource other than workout by using SVN commands from 'execute' resource..
Pls. see my code snippet and error
    RuntimeError
    ------------
    Could not parse `svn info` data:

    Resource Declaration:
    ---------------------
    # In C:/Users/Joy/.chef/local-mode-cache/cache/cookbooks/hello/recipes/svn.rb

      1: subversion "abc" do
      2:   repository "valid url"
      3:   revision 'HEAD'
      4:   #destination "#{Chef::Config[:file_cache_path]}/antitheft"
      5:   destination 'C:/fromsvnchef'
      6:   svn_username "abc"
      7:   svn_password "abcd"
      8:   action :checkout
      9:   retries 2
     10:   retry_delay 2
     11: end

    Compiled Resource:
    ------------------
    # Declared in C:/Users/Joy/.chef/local-mode-cache/cache/cookbooks/hello/recipes/svn.rb:1:in `from_file'

    subversion("abc") do
      action [:checkout]
      retries 2
      retry_delay 2
      default_guard_interpreter :default
      destination "C:/fromsvnchef"
      enable_checkout true
      revision "HEAD"
      remote "origin"
      checkout_branch "deploy"
      svn_arguments "--no-auth-cache"
      svn_info_args "--no-auth-cache"
      declared_type :subversion
      cookbook_name "lamp-stack"
      recipe_name "svn"
      repository "valid url"
      svn_username "abc"
      svn_password "abcd"
    end

**Comment by homerakshay** [comment]
@jchowdhary @puneetloya : Are you guys still facing this issue? If yes, i could probably help. Let me know.. Will paste a detailed way of getting a fix as how i have done for my svn code via chef. 

Thank you. 
Regards, 
Akshay

**Comment by jchowdhary** [comment]
@homerakshay :+1:    Though i worked out with the alternate solution, it would be good if you can provide the solution with svn info command.Really appreciate

**Comment by homerakshay** [comment]
@jchowdhary What approach did you follow to get this working? If you could shed some light on it, i can help..

**Comment by avinihal05** [comment]
I am getting the same error.
Pls. see my code snippet and error

23.22.97.98 C:\Users\Administrator>chef-client -c c:/chef/client.rb -j c:/che
f/first-boot.json
23.22.97.98 [2017-04-26T03:08:37-07:00] INFO: *** Chef 12.19.36 ***
23.22.97.98 [2017-04-26T03:08:37-07:00] INFO: Platform: x64-mingw32
23.22.97.98 [2017-04-26T03:08:37-07:00] INFO: Chef-client pid: 3548
23.22.97.98 [2017-04-26T03:08:47-07:00] INFO: Setting the run_list to ["recipe[pcrco_backup_windows]"] from CLI options
23.22.97.98 [2017-04-26T03:08:47-07:00] INFO: Run List is [recipe[pcrco_backup_windows]]
23.22.97.98 [2017-04-26T03:08:47-07:00] INFO: Run List expands to [pcrco_backup_windows]
23.22.97.98 [2017-04-26T03:08:47-07:00] INFO: Starting Chef Run for windows23219798
23.22.97.98 [2017-04-26T03:08:47-07:00] INFO: Running start handlers
23.22.97.98 [2017-04-26T03:08:47-07:00] INFO: Start handlers complete.
23.22.97.98 [2017-04-26T03:08:47-07:00] INFO: HTTP Request Returned 404 Not Found:
23.22.97.98 [2017-04-26T03:08:47-07:00] INFO: Error while reporting run start to Data Collector. URL: https://54.243.108.240/organizations/pcrco/data-coll
ector Exception: 404 -- 404 "Not Found"  (This is normal if you do not have Chef Automate)
23.22.97.98 [2017-04-26T03:08:47-07:00] INFO: Loading cookbooks [pcrco_backup_windows@0.0.1]
23.22.97.98 [2017-04-26T03:08:47-07:00] INFO: Processing subversion[PCRCo_Web] action sync (pcrco_backup_windows::default line 14)
23.22.97.98
23.22.97.98
23.22.97.98 
23.22.97.98 Error executing action 'sync' on resource 'subversion[PCRCo_Web]'
23.22.97.98 
23.22.97.98
23.22.97.98 RuntimeError
23.22.97.98 ------------
23.22.97.98 Could not parse `svn info` data:
23.22.97.98
23.22.97.98 Resource Declaration:
23.22.97.98 ---------------------
23.22.97.98 # In c:/chef/cache/cookbooks/pcrco_backup_windows/recipes/default.rb
23.22.97.98
23.22.97.98  14: subversion "PCRCo_Web" do
23.22.97.98  15:   repository "https://23.22.97.98:8443/svn/PCRCo_Web/trunk"
23.22.97.98  16:   revision "HEAD"
23.22.97.98  17:   destination app_directory
23.22.97.98  18:   svn_username "xyz"
23.22.97.98  19:   svn_password "xyz"
23.22.97.98  20:   action :sync
23.22.97.98  21: end
23.22.97.98  22:
23.22.97.98
23.22.97.98 Compiled Resource:
23.22.97.98 ------------------
23.22.97.98  Declared in c:/chef/cache/cookbooks/pcrco_backup_windows/recipes/default.rb:14:in 'from_file'
23.22.97.98
23.22.97.98 subversion("PCRCo_Web") do
23.22.97.98   action [:sync]
23.22.97.98   retries 0
23.22.97.98   retry_delay 2
23.22.97.98   default_guard_interpreter :default
23.22.97.98   destination "C:/BackupChef/20170426030847"
23.22.97.98   enable_checkout true
23.22.97.98   revision "HEAD"
23.22.97.98   remote "origin"
23.22.97.98   checkout_branch "deploy"
23.22.97.98   svn_arguments "--no-auth-cache"
23.22.97.98   svn_info_args "--no-auth-cache"
23.22.97.98   declared_type :subversion
23.22.97.98   cookbook_name "pcrco_backup_windows"
23.22.97.98   recipe_name "default"
23.22.97.98   repository "https://23.22.97.98:8443/svn/PCRCo_Web/trunk"
23.22.97.98   svn_username "xyz"
23.22.97.98   svn_password "xyz"
23.22.97.98 end
23.22.97.98
23.22.97.98 Platform:
23.22.97.98 ---------
23.22.97.98 x64-mingw32
23.22.97.98
23.22.97.98
23.22.97.98 [2017-04-26T03:08:47-07:00] INFO: Running queued delayed notifications before re-raising exception
23.22.97.98 [2017-04-26T03:08:47-07:00] ERROR: Running exception handlers
23.22.97.98 [2017-04-26T03:08:47-07:00] ERROR: Exception handlers complete
23.22.97.98 [2017-04-26T03:08:47-07:00] INFO: Sending resource update report(run-id: 3415351f-e15f-4552-b0c6-f4463fc2a5df)
23.22.97.98 [2017-04-26T03:08:48-07:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
23.22.97.98 [2017-04-26T03:08:48-07:00] FATAL: Please provide the contents of
 the stacktrace.out file if you file a bug report
23.22.97.98 [2017-04-26T03:08:48-07:00] FATAL: RuntimeError: subversion[PCRCo_Web](pcrco_backup_windows::default line 14) had an error: RuntimeError: Could not parse `svn info` data:
ERROR: Failed to execute command on 23.22.97.98 return code 1
PS C:\chef-repo>

**Comment by TimListon** [comment]
Getting the error when the initial repo has not been checked out yet.  If I do a manual check out and then do a chef-client run the code executes successfully.

```  ================================================================================
    Error executing action `sync` on resource 'subversion[Subpoena]'
    ================================================================================

    RuntimeError
    ------------
    Could not parse `svn info` data:

    Resource Declaration:
    ---------------------
    # In c:/chef/cache/cookbooks/edc_websites/recipes/Subpoena.rb

     49: subversion "#{site_ID}" do
     50:        repository repo
     51:        revision 'HEAD'
     52:        destination "#{node['edc_websites']['doc_root']}\\#{site[0]}"
     53:        svn_username '{redacted}'
     54:        svn_password '{redacted}'
     55:        svn_arguments "--trust-server-cert-failures=unknown-ca"
     56: end
     57:

    Compiled Resource:
    ------------------
    # Declared in c:/chef/cache/cookbooks/edc_websites/recipes/Subpoena.rb:49:in `from_file'

    subversion("Subpoena") do
      action [:sync]
      default_guard_interpreter :default
      destination "W:\\DATA\\dev.subpoena.edcgov.us"
      enable_checkout true
      revision "HEAD"
      remote "origin"
      checkout_branch "deploy"
      svn_arguments "--trust-server-cert-failures=unknown-ca"
      svn_info_args "--no-auth-cache"
      declared_type :subversion
      cookbook_name "edc_websites"
      recipe_name "Subpoena"
      repository "https://svn.co.el-dorado.ca.us/svn/IT/District%20Attorney/Subpoena/trunk"
      svn_username "{redacted}"
      svn_password "{redacted"
    end

    System Info:
    ------------
    chef_version=13.2.20
    platform=windows
    platform_version=10.0.14393
    ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-client
    executable=C:/opscode/chef/bin/chef-client

[2017-09-06T12:17:54-07:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2017-09-06T12:17:54-07:00] ERROR: Running exception handlers
Running handlers complete
[2017-09-06T12:17:54-07:00] ERROR: Exception handlers complete
Chef Client failed. 3 resources updated in 16 seconds
[2017-09-06T12:17:54-07:00] INFO: Sending resource update report (run-id: 04589a8e-93f5-4ed1-84a0-d2da54dd0d01)
[2017-09-06T12:17:54-07:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2017-09-06T12:17:54-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-09-06T12:17:54-07:00] FATAL: RuntimeError: subversion[Subpoena] (edc_websites::Subpoena line 49) had an error: RuntimeError: Could not parse `svn info` data:
```

[chef-stacktrace.out.txt](https://github.com/chef/chef/files/1282845/chef-stacktrace.out.txt)

**Comment by mattbushell** [comment]
I also have the same problem as TimListon, an initial checkout does not work, one has to manually checkout initially. Creating the destination directory did not fix it.
