### ISSUE TITLE
Chef12 alternative to InlineResources::ClassMethods#recipe_eval_with_update_check ?

### ISSUE THREAD

**Issue by jperville** [chef/chef#4053]
The `InlineResources::ClassMethods#recipe_eval_with_update_check` method seems to have disappeared at some point between chef 12.4.3 and chef 12.5.1.

Since the method is quite useful (especially when implementing a LWRP that wraps other internal resources, we want the LWRP to be updated when any of the internal resources is updated), are there any plans to bring it back? Is there an alternative that would work other than copy/pasting the code from chef 12.4 into my application cookbook?

**Comment by coderanger** [comment]
This isn't really the place for support requests, but you can switch to using Poise's `notifying_block` helper instead.

**Comment by lamont-granquist** [comment]
That's sufficiently deep into the internals of chef recipe parsing that I think its fair to say that was an internal undocumented API that broke between minor version releases.  So most likely we don't want to bring that exact method back.

We can discuss bringing in a documented first-class API which will fulfill the requirements, but this ticket could use a bit more explanation of the use case and hash out some alternatives.

**Comment by jperville** [comment]
Here is my use case: I have a wrapper cookbook for docker, which has a feature to merge environment variables obtained from different sources into an "env-file" (a file containing key=value pairs). In the past, the docker_container resource would only accept one such file, so I really needed all environment variables to go in one place. It is also convenient to explicitly dump all environment variables that will be exported into a container in a single place.

The content of the env-file is built by recipe-eval'ing arbitrary recipes provided by the wrapper cookbook user in the `env_imports` attribute. For example, when I declared

```ruby
my_docker_container do
   repo 'myrepo/myapp'
   ...
   env_imports %w[feature1 feature2]
end
```

My wrapper resource will `recipe_eval_with_update_check` all recipes whose names are given in `node['feature1']['export-recipe']` and in `node['feature2']['export-recipe']`. Most of the times, these resources only set node attributes (usually environment variables or volume definitions for the docker container), they do not touch chef resources directly.

If I used `recipe_eval` to implement this feature instead of `recipe_eval_with_update_check` then my wrapper resource would always be updated, triggering eventual notifications (especially container redeploys), which I do not want.

If `recipe_eval_with_update_check` is to go, what are the alternatives to converge arbitrary resources from within an LWRP without setting the modified flag when nothing has been modified in the sub context?

**Comment by lamont-granquist** [comment]
It looks like you've got an accumulator pattern, but you seem to have made it a bit overly complicated which is painting you into a corner.

I'd really suggest not doing any of what you're doing with node attributes to start with and to try using definitions.  I've got some example cookbooks which use definitions to do accumulator patterns here:

https://github.com/lamont-cookbooks/multipackage
https://github.com/lamont-cookbooks/sk_sysctl
https://github.com/lamont-cookbooks/sk_ssh_known_hosts

The conditional execution of recipe code that you're doing is causing me to really stumble, though, and I'm not sure exactly why you went that direction or what you'd lose by re-engineering to not do that.

Generally what I'd say though is that you need to get those recipes into a run_list either explicitly or via a normal include_recipe wrapped in a conditional.

The recipes can then use a definition to accumulate the key=value pairs into a single resource which will do the work.   The definition should probably be creating the my_docker_container resource (if it does not already exist on the resource collection) and then it should be accumulating an "env_imports" property containing a hash.

Then once you've compile-time parsed all of the definitions the resource will be fully built, when it is encountered at converge time it will only fire once.  That approach gets rid of the whole mess of trying to include_recipe into a sub-resource collection.

I don't know what else you're trying to do by the way that you're driving essentially doing an include_recipe off of a resource though, and I ran out of caffeine this morning and need to head out to the coffee shop, so I might be missing something else driving you to this approach...

**Comment by jperville** [comment]
Thanks @lamont-granquist . The affected cookbook is a legacy one. After reading your message I now have a few ideas to experiment which should eliminate the need for recipe_evaling from within LWRP. Will let know how I solve the issue after refactoring my LWRP to not use recipe_eval anymore.

**Comment by lamont-granquist** [comment]
notifying_block has been added to core chef now:

https://github.com/chef/chef/pull/4818
