### ISSUE TITLE
v12.5 breaks windows script resources that have an absolute path interpreter

### ISSUE THREAD

**Issue by mwrock** [chef/chef#4057]
The vast majority of script resources such as `batch` or `powershell` do not explicitly pass a interpreter. Internally these resources by default will pass `cmd` or `powershell`. Under these common scenarios the recent changes to the `base_path` of `batch` and `powershell` work fine.

However it is possible for a recipe to pass an absolute path to the `interpreter` attribute. In this case joining the base_path like we do [here](https://github.com/chef/chef/blob/master/lib/chef/provider/batch.rb#L34) breaks the recipe with an error looking like:
```
Expected process to exit with [0], but received '1'
---- Begin output of "C:\Windows\system32\C:\windows\sysnative\cmd.exe" /c "C:/Users/ADMINI~1/AppData/Local/Temp/chef-script20151008-5236-tkbbs4.bat" ----
STDOUT:
STDERR: The filename, directory name, or volume label syntax is incorrect.
---- End output of "C:\Windows\system32\C:\windows\sysnative\cmd.exe" /c "C:/Users/ADMINI~1/AppData/Local/Temp/chef-script20151008-5236-tkbbs4.bat" ----
Ran "C:\Windows\system32\C:\windows\sysnative\cmd.exe" /c "C:/Users/ADMINI~1/AppData/Local/Temp/chef-script20151008-5236-tkbbs4.bat" returned 1
```

[This happened](https://github.com/chocolatey/chocolatey-cookbook/issues/54) in the [chocolatey-cookbook](https://github.com/chocolatey/chocolatey-cookbook) since it uses a `batch` resource and passesd `C:\windows\sysnative\cmd.exe` as the interpreter on 64 bit systems. It needs to do this for the resource that installs chocolatey since it may also need to install .net 4 if it is not already installed.

We should detect if an absolute path is being used as the interpreter and if so, leave the interpreter path as is.

**Comment by adamedx** [comment]
Interesting -- I think we should make this attribute ignore any attempts to set it (with a warning) -- I don't see any scenario under which changing the interpreter is a good idea. That would let you get the `powershell_script` resources to actually execute `bash` for instance...

**Comment by mwrock** [comment]
Yeah I'd agree. I wonder though if we would want to provide a flag that would point the interpreter to sysnative on 64 bit. Maybe not since 64bit chef will render this a moot point. I suppose in the meantime recipes would just need t shellout in a `ruby_block` if they needed to do that.

**Comment by chefsalim** [comment]
Also, there is a card open (ECO-41) to update the docs that this property is not supported.  Since we have to override the path to support 64-bit scenarios, it would break any scenario where a custom interpreter was passed in.

**Comment by adamedx** [comment]
No need for sysnative @mwrock  -- `batch` and `powershell_script` always use 64-bit if you don't specify an arch:
https://docs.chef.io/resource_powershell_script.html

> architecture	
> Ruby Type: Symbol
>
> The architecture of the process under which a script is executed. If a value is not provided, the chef-client defaults to the correct value for the architecture, as determined by Ohai. An exception is raised when anything other than :i386 is specified for a 32-bit process. Possible values: :i386 (for 32-bit processes) and :x86_64 (for 64-bit processes).

**Comment by adamedx** [comment]
@mwrock fyi, here's where 64-bit gets forced without using sysnative:

https://github.com/chef/chef/blob/master/lib/chef/provider/windows_script.rb#L46-L62

**Comment by mwrock** [comment]
Ah cool missed that. I'm closing this since absolute path interpreters are an extreme edge case and anti pattern.
