### ISSUE TITLE
Could not parse `svn info` data with Chef 12.5.1

### ISSUE THREAD

**Issue by ostraaten** [chef/chef#4058]
Today my recipe started failing. I noticed that now 12.5.1 is used. When I use Chef client version 12.4.1 in my Vagrant the recipe runs fine again. 

==> default: Error executing action `checkout` on resource 'subversion[TestRepos]'
==> default: ================================================================================
==> default: 
==> default: 
==> default: RuntimeError
==> default: ------------
==> default: Could not parse `svn info` data: 
==> default: 
==> default: 
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef/f48c6cb837fd2b74caf10959687287b1/cookbooks/uwv-subversion/recipes/cache_credentials.rb
==> default: 
==> default: 
==> default:   4:   subversion "TestRepos" do
==> default:   5:     repository "https://devops.ok/svn"
==> default: 
==> default:   6:     svn_arguments "--depth immediates --config-dir #{h}/.subversion"
==> default:   7:     svn_info_args "--config-dir #{h}/.subversion"
==> default:   8:     revision "HEAD"
==> default: 
==> default:   9:     destination "#{h}/magweg"
==> default:  10:     group u
==> default:  11:     user u
==> default:  12:     svn_username '"myuser"'
==> default:  13:     svn_password '"mypass"'
==> default: 
==> default:  14:     action :checkout
==> default: 
==> default:  17:   end
==> default:  18: 
==> default: 
==> default:

**Comment by BarthV** [comment]
:+1: 
same bug here. Trying to find out the reason

**Comment by BarthV** [comment]
dups #4050

**Comment by lamont-granquist** [comment]
closing as dup of #4050 then
