### ISSUE TITLE
Chef 12.5.0 resources need action_helper/action_class with Recipe DSL and converge_by

### ISSUE THREAD

**Issue by glenjamin** [chef/chef#4067]
Is there any way to use `converge_by` in the new custom resources?

I've switched a library cookbook over to using them, and everything is much nicer - but having to switch back to an LWRP to allow `converge_by` is a bit annoying.

**Comment by glenjamin** [comment]
I created this little mixin to make the custom resource behave a bit more like an LWRP in this regard:

```ruby
  module ConvergeBy
    include Chef::Mixin::WhyRun

    def converge_by(descriptions, &block)
      converge_actions.add_action(descriptions, &block)
      updated_by_last_action(true)
    end

    protected

    def converge_actions
      @converge_actions ||= ConvergeActions.new(self, run_context, action)
    end
  end
```

It seems to work, but there's a strong chance I overlooked something important

**Comment by lamont-granquist** [comment]
What is the error when you try to use converge_by and are you using converge_by within an action block or in a method outside of an action block?  It should work within an action block because the DSL is mixed into the action.  But outside of that you are in the Chef::Resource context and it won't work.

**Comment by lamont-granquist** [comment]
The binding/context/lexical scope of Chef 12.5 resources is a bit confusing to say the least.  If you open up a method directly on the resource there is a new_resource that doesn't throw a syntax error but it doesn't seem to be the new_resource of the action/provider scope and its properties seem to be reset to the default.

**Comment by glenjamin** [comment]
The error is basically, "that method doesn't exist".

It does work inside the action block, but I'd factored all the real work of the action out into helper methods which sat on the resource - and then didn't have access to the resource DSL or `converge_by`.

Here's a full example of what I ended up doing: https://github.com/glenjamin/github-cookbook/blob/47bafaaf2fee18b3f3b152fae6332abc80b4a902/resources/org.rb#L22

**Comment by lamont-granquist** [comment]
So if we just wrap the method calls with the action class context all the Chef::Provider::LWRPBase stuff comes with it, then we should not need to extract the mixin.

**Comment by lamont-granquist** [comment]
trying to define methods on the resource is the wrong approach, the action_class helper can be used here:

```ruby
[...define the resource...]

action_class do
  include MyModule

  def something_else
  end
end

action :doit do
  use_method_from_mymodule()
  something_else()
end
```
