### ISSUE TITLE
chef/tasks/rspec.rb requires bundler

### ISSUE THREAD

**Issue by josb** [chef/chef#4072]
```rake spec``` gives
```
rake aborted!
NameError: uninitialized constant Bundler
/Users/josb/git/chef/tasks/rspec.rb:32:in `block (2 levels) in <top (required)>'
/Users/josb/git/chef/tasks/rspec.rb:31:in `chdir'
/Users/josb/git/chef/tasks/rspec.rb:31:in `block in <top (required)>'
Tasks: TOP => spec => component_specs
(See full trace by running task with --trace)
```
Fix is to add ```require 'bundler'``` at the top of chef/tasks/rspec.rb.

**Comment by lamont-granquist** [comment]
Generally we always run with `bundle exec`, but if you want to submit a PR we can whack merge on it.  Not a thing we're likely to ever pick up so I'm just closing this as an issue.

**Comment by josb** [comment]
Fair enough, thanks Lamont.
