### ISSUE TITLE
Bootstrapping windows with ChefDK 0.9.0 breaks on missing -E switch

### ISSUE THREAD

**Issue by vinyar** [chef/chef#4073]
Bug:
Bootstrapping a windows box (possibly all boxes) now errors out with `missing argument: -E (OptionPa=
rser::MissingArgument)`

Expectation: Bootstrapping a node without passing an environment should default to `_default` environment.

chef-vm-node03.redmond.corp.microsoft.com  echo.
chef-vm-node03.redmond.corp.microsoft.com  echo.file_cache_path   "c:/chef/=
cache"
chef-vm-node03.redmond.corp.microsoft.com  echo.file_backup_path  "c:/chef/=
backup"
chef-vm-node03.redmond.corp.microsoft.com  echo.cache_options     ({:path =
=3D> "c:/chef/cache/checksums", :skip_expires =3D> true})
chef-vm-node03.redmond.corp.microsoft.com  echo.
chef-vm-node03.redmond.corp.microsoft.com  echo.# Using default node name (=
fqdn)
chef-vm-node03.redmond.corp.microsoft.com  echo.trusted_certs_dir "C:/chef/=
trusted_certs"
chef-vm-node03.redmond.corp.microsoft.com ) 1>C:\chef\client.rb
chef-vm-node03.redmond.corp.microsoft.com
chef-vm-node03.redmond.corp.microsoft.com C:\Users\svcfchef>(echo.{"run_lis=
t":[]}) 1>C:\chef\first-boot.json
chef-vm-node03.redmond.corp.microsoft.com Starting chef to bootstrap the no=
de...
chef-vm-node03.redmond.corp.microsoft.com
chef-vm-node03.redmond.corp.microsoft.com C:\Users\svcfchef>SET "PATH=3DC:\=
Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v=1.0\;C:\opscode
\chef\bin\;C:\ruby\bin;C:\opscode\chef\bin;C:\opscode\chef\embedded\bin"
chef-vm-node03.redmond.corp.microsoft.com
chef-vm-node03.redmond.corp.microsoft.com C:\Users\svcfchef>chef-client -c =
c:/chef/client.rb -j c:/chef/first-boot.json -E
chef-vm-node03.redmond.corp.microsoft.com C:/opscode/chef/embedded/lib/ruby=
/gems/2.0.0/gem
s/mixlib-cli-1.5.0/lib/mixlib/cli.rb:191:in `parse_options
chef-vm-node03.redmond.corp.microsoft.com ': missing argument: -E (OptionPa=
rser::MissingArgument)
chef-vm-node03.redmond.corp.microsoft.com       from C:/opscode/chef/embedd=
ed/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application.rb:86:in `c=
onfigure_chef'
chef-vm-node03.redmond.corp.microsoft.com       from C:/opscode/chef/embedd=
ed/lib/ruby/gem
s/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application.rb:48:in `r=
econfigure'
chef-vm-node03.redmond.corp.microsoft.com       from C:/opscode/chef/embedd=
ed/lib/ruby/gem
s/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application/client.rb:2=
79:in `reconfigure'
chef-vm-node03.redmond.corp.microsoft.com       from C:/opscode/chef/embedd=
ed/lib/ruby/gems/2.0.0/gems/chef-12.5.1-universal-mingw32/lib/chef/application.rb:58:in `r=
un'
chef-vm-node03.redmond.corp.microsoft.com       from C:/opscode/chef/embedd=
ed/lib/ruby/gem
s/2.0.0/gems/chef-12.5.1-universal-mingw32/bin/chef-client:26:in `<top (req=
uired)>'
chef-vm-node03.redmond.corp.microsoft.com       from C:/opscode/chef/bin/ch=
ef-client:65:in`load'
chef-vm-node03.redmond.corp.microsoft.com       from C:/opscode/chef/bin/ch=
ef-client:65:in`<main>'
ERROR: Failed to execute command on chef-vm-node03.redmond.corp.microsoft.c=
om return code 1

D:\muleadm>knife bootstrap windows winrm chef-vm-node03.redmond.corp.microsoft.com --winrm-user <username>

@peterclift @tonyctchow for more info

**Comment by lamont-granquist** [comment]
Better submitted to https://github.com/chef/knife-windows/issues/new first.
