### ISSUE TITLE
User Agent in Chef Client 12.4.1 and above is "Chef Knife"

### ISSUE THREAD

**Issue by bdangit** [chef/chef#4074]
Anyone experiencing this?  When we upgraded a bunch of our nodes to 12.4.1 and above, we noticed from our Chef Server logs that the user agent is now Chef Knife.

I can see from this code that its hardcoded as Chef Client, but something must be overriding it.
https://github.com/chef/chef/blob/943bcdeb5ec0911ff0a0d2d9841d7060b3b6f963/lib/chef/http/http_request.rb#L43-L44

Before: 
```ruby
Chef Client/11.16.4 (ruby-1.9.3-p547; ohai-7.4.0; x86_64-linux; +http://opscode.com)
```

After:
```ruby
Chef Knife/12.4.3 (ruby-2.1.6-p336; ohai-8.5.1; x86_64-linux; +http://opscode.com)
```

~~What is also strange is that http://opscode.com should have been http://chef.io.~~ This change for chef.io is only a chef-client 12.5.1-ism.  Everything about User agent changing is applicable.

**Comment by chilicheech** [comment]
Yep, I noticed this as well. Something must be overriding it because it's not using the default: https://github.com/chef/chef/blob/943bcdeb5ec0911ff0a0d2d9841d7060b3b6f963/lib/chef/http/http_request.rb#L70

**Comment by lamont-granquist** [comment]
`require 'chef/knife'` is coming in via cheffish:

```
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/knife.rb:36:in `<class:Knife>': WTF? (RuntimeError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/knife.rb:34:in `<class:Chef>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/knife.rb:33:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/cheffish-1.5.0/lib/cheffish.rb:231:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/resources.rb:87:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef.rb:26:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/lib/chef/application/apply.rb:20:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.4.4/bin/chef-apply:23:in `<top (required)>'
	from /opt/chefdk/bin/chef-apply:54:in `load'
	from /opt/chefdk/bin/chef-apply:54:in `<main>'
```

**Comment by svanharmelen** [comment]
@jkeiser just noticed this too and it's actually breaking some of our internal tooling which checks if calls are coming from a Chef Client of from a user (using Knife or the WebUI). So having this fixed in the next release would be awesome! Thx!

**Comment by svanharmelen** [comment]
@jkeiser @lamont-granquist ping... It's been a few months, would be really great if this could be fixed in the next Chef client release. Thanks!

**Comment by jkeiser** [comment]
We should probably be setting this in the knife application class rather than a require.

**Comment by lamont-granquist** [comment]
So at least in 12.6.0 if you don't use cheffish resources, the requires for cheffish won't fire and knife won't get slurped in.  Still a bug in cheffish, imo.

@jkeiser why does cheffish have to pull in 'chef/knife', its not knife so that seems wrong...   smells like some common code needs to get extracted into something that can be included into both, or that the require in cheffish is just too broad...

**Comment by bancek** [comment]
You can change the user agent by adding this line to your recipe:

```
Chef::HTTP::HTTPRequest.user_agent = "Chef Client/11.16.4 (ruby-1.9.3-p547; ohai-7.4.0; x86_64-linux; +http://opscode.com)"
```
