### ISSUE TITLE
Chef-Server crashing when invalid cookbook version is uploaded

### ISSUE THREAD

**Issue by franznemeth** [chef/chef#4076]
I accidentally ran into a way to crash the chef server.

When you upload a cookbook with berkshelf/knife which has a version number similar to 0.3.2999999999 the chef server is no longer able to serve cookbooks to its clients.
~/chef-repo/cookbooks/cookbook# knife cookbook show cookbook
cookbook   0.3.29 0.3.-1294967297

It seems that somewhere along the way the chef-server runs into an integer overflow which makes it impossible for clients to start a chef run.
This happens on all clients, not only the ones that have this particular cookbook in their run_list.

```
client:~/ # chef-client
Starting Chef Client, version 12.5.1
resolving cookbooks for run list: ["cookbook"]

================================================================================
Error Resolving Cookbooks for Run List:
================================================================================

Unknown Server Error:
---------------------
The server had a fatal error attempting to load the node data.

Server Response:
----------------
internal service error
```

How to reproduce:
  - create a cookbook with the version 0.3.2999999999
  - include that cookbook into the runlist of a node

**Comment by lamont-granquist** [comment]
chef server issues need to be filed against http://github.com/chef/chef-server/issues/new this repo is for client issues only.

you should include the version of the server when you report it over there since the size of the cookbook version numbers were increased at some point fairly recently (within the past year).
