### ISSUE TITLE
knife upload cookbook issue when there are multiple versions of cookbooks

### ISSUE THREAD

**Issue by avinashkolluru** [chef/chef#4077]
I have 2 different versions of cookbook on my local machine (~/.berkshelf/cookbooks).
When i use the 'knife upload cookbook' command to upload the cookbooks to chef-server looks like the files from both the versions are merged and uploaded as a single cookbook(tagged with the latest version)

To be specific - I had docker-1.0.17 and docker-2.1.2. There were a few library files that have been removed in version 2.1.2 but on the chef server contained all the library files even from 1.0.17

**Comment by coderanger** [comment]
You can't use knife to upload the Berkshelf internal data structures. Use `berks upload` for that.

**Comment by avinashkolluru** [comment]
@coderanger Is there a way to bypass the ssl check in berks upload.
I'm trying to upload to a local development server which has a self signed cert.

```
E, [2015-10-21T09:53:21.840556 #51708] ERROR -- : Ridley::Errors::ClientError: SSL_connect returned=1 errno=0 state=error: certificate verify failed
E, [2015-10-21T09:53:21.840653 #51708] ERROR -- : /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/responses.rb:29:in `value'
```

**Comment by avinashkolluru** [comment]
@coderanger 
Ignore.... found the --ssl-verify option which berks supports. 
Thanks
