### ISSUE TITLE
nil output when empty? is called on non-empty chef search result

### ISSUE THREAD

**Issue by szymonpk** [chef/chef#4083]
I've looked in past issues, didn't found anything similar.

chef-server 12.1.2 (self-hosted)
chef-client 12.4.1

```ruby
xmpp_servers = search(:node, 'recipes:xmpp_server\\:\\:default')
Chef::Log.info xmpp_servers.class
Chef::Log.info xmpp_servers.empty?
Chef::Log.info xmpp_servers
```
Output I'm getting:

```
[2015-10-21T11:51:49+00:00] INFO: Array
[2015-10-21T11:51:49+00:00] INFO: nil
[2015-10-21T11:51:49+00:00] INFO: [<non-empty array, too long to paste>]
```

According to [docs](http://docs.ruby-lang.org/en/2.0.0/Array.html#method-i-empty-3F), empty? should return true, false or die horribly.

**Comment by lamont-granquist** [comment]
Problem here isn't with `empty?` its with Chef::Log.info when passed a "false"

coercion to a string should fix the output:

```ruby
Chef::Log.info xmpp_servers.empty?.to_s
Chef::Log.info "#{xmpp_servers.empty?}"
```

as will using a different API"

```ruby
pp xmpp_servers.empty?
```

And just doing this prints out 'nil'

```
Chef::Log.info false
```

**Comment by lamont-granquist** [comment]
This is a bug/feature of ruby's `logger` class:

% pry
[1] pry(main)> require 'logger'
=> true
[3] pry(main)> logger = Logger.new(STDOUT)
[...]
[4] pry(main)> logger.info false
I, [2015-10-21T14:08:46.305408 #23975]  INFO -- : nil
```

**Comment by lamont-granquist** [comment]
So there's a work around which I'd argue is the actually the correct thing to do.  We are very unlikely to reimplement the logger class just to work around this bug.  We're also unlikely to prioritize this towards fixing the upstream issue in ruby (if it can be fixed without a breaking API change there).  The cost of either of those yak shaves vs the benefits of fixing this edge condition are so out of proportion that I can guarantee its not actionable as an issue in this repo.  If a bug is cut against ruby upstream and we pull that bugfix in, then it'll get fixed here.

**Comment by szymonpk** [comment]
@lamont-granquist thx for fast response and explanation!
