### ISSUE TITLE
unable to drive file/dir permissions of git checkouts

### ISSUE THREAD

**Issue by glensc** [chef/chef#4084]
chef-client runs are supposed to be idempotent, however git checkout depends largely what was the umask when the chef-client was ran:

```
# umask 007
# chef-client
# ls -l cdn/ajax/
drwxrwx--- 41 root root 4,0K okt   21 16:39 libs/
-rw-rw---- 1 root root 815 okt   21 17:14 cdn/ajax/libs/jquery/package.json
```

```
# rm -rf cdn
# umask 077
# chef-client
# ls -l cdn/ajax/
total 4
drwx------ 41 root root 4096 okt   21 17:14 libs/
-rw------- 1 root root 815 okt   21 17:14 cdn/ajax/libs/jquery/package.json
```
and there seems to be no attribute to set file or dir permissions, nor umask:
https://docs.chef.io/resource_git.html

umask would be more appropriate as git is able to track file "rwx" state (but seems apparently u-g-o separately (i.e +x is applied to all three, after umask masking))

ps: the recipe was simply:
```ruby
git node['cdn-js']['dir'] do
    repository node['cdn-js']['git_repository']
    revision node['cdn-js']['git_revision']
    action :sync
end
```

**Comment by lamont-granquist** [comment]
what if you call directory afterwards:

```
git node['cdn-js']['dir'] do
    repository node['cdn-js']['git_repository']
    revision node['cdn-js']['git_revision']
    action :sync
end

directory node['cdn-js']['dir'] do
  owner 'root'
  group 'root'
  recursive true
end
```

It looks like the directory resource does not support files_group/files_owner/files_mode though like remote_directory does--i suspect there's some very old ticket about that either in github or the old jira instance.

  recursive true
end
```

**Comment by glensc** [comment]
that is dirty hack and not suitable for production solution. there's race condition when files are not accessible between git checkout and directory resource finishing.

also it does not solve files permission problem that were checked out )(i'll update problem report to include sample of files too). and doing one permission for all files is also wrong, some files have +x bit the others don't.

**Comment by glensc** [comment]
so, it definately needs to be umask, not to do it wrong and later attempt to fix consequences.

for a second i got a :bulb: that maybe git itself can have umask via its config. but sadly no
https://www.kernel.org/pub/software/scm/git/docs/git-config.html

and anyway, imho the solution needs to be a more global than git (subversion, ..?), i.e resources that execute some external command and may create more than one file

**Comment by lamont-granquist** [comment]
So then there's `Chef::Config[:umask]` and this is probably a dup of #3741

**Comment by lamont-granquist** [comment]
The one other comment I've got is that git checkouts themselves are not atomic, so anything accessing the directory will potentially see a half-checked-out directory.  The 'production' approach to this would be to checkout to a directory which was not live, and then flip a symlink in order to make the whole thing live atomically.  You can then do the git resources, fix the perms, mangle anything else you like, and then atomically flip the symlink (and possibly stop the service before and start the service after if that's what you need).  The deploy_revision resource is one example of how to automate this (although its kind of a bad, overlycomplicated rails-centric example).

**Comment by glensc** [comment]
well, i plan to have "deploy_revision" point to branch "master", so where do i symlink to? probably should just use some date value generated from recipe.

i'll go for `Chef::Config[:umask]` for now, even it will enforce this recipe's taste to everything, which may cause another set of issues.

#3741 mentioned something about subscribing to events, can i get example how  to do the umask trick exactly at converge stage (set before git converge and reset after git converge finished)?

**Comment by glensc** [comment]
with symlink approach, must think also
  - how to purge old checkouts
  - each checkout is full checkout, maybe could use shared local repo and `--git-dir`

**Comment by lamont-granquist** [comment]
`deploy_revision` creates a structure that looks like this:

```
% ls -l /srv/secchi 
total 12
lrwxrwxrwx 1 root root   61 Mar 31  2015 current -> /srv/secchi/releases/d8038195f66ef9d50d70b46b2255761be79c8fa7/
drwxr-xr-x 5 root root 4096 Mar 31  2015 releases/
drwxr-xr-x 5 root root 4096 Oct 20 13:42 shared/
```

The 'master' tag is resolved to its gitsha and checked out to `releases/<gitsha>` then the current symlink is flipped.  The releases directory looks like:

```
% ls -l /srv/secchi/releases 
total 12
drwxr-xr-x 16 root root 4096 Oct  7  2014 0912357517e77294c06d12570c3afc5692cbba86/
drwxr-xr-x 16 root root 4096 Sep  4  2014 7c63fb19a6c18ffaaf486c7cd8dbc669f5425f74/
drwxr-xr-x 15 root root 4096 Mar 31  2015 d8038195f66ef9d50d70b46b2255761be79c8fa7/
```

The `deploy_revision` resource will purge old checkouts and has a default policy of keeping 5 which can be tweaked by setting the `keep_releases` property to a different value.

**Comment by lamont-granquist** [comment]
And right now having two ruby_blocks before and after which use `File#umask()` is the only way to get exactly what you want.

**Comment by glensc** [comment]
ah, [deploy_revision](https://docs.chef.io/resource_deploy.html) is resource!

**Comment by glensc** [comment]
ps: the "current" symlink does not need to be absolute at all!

**Comment by glensc** [comment]
can you make example for that `File#umask()` use in `deploy_resource`?

**Comment by lamont-granquist** [comment]
```ruby
ruby_block "set umask" do
  block
    File#umask(0022)
  end
end

git "whatever" do
  [...stuff...]
end

ruby_block "set umask" do
  block
    File#umask(0077)
  end
end
```

it gets more complicated if you want to save and restore due to contexts and bindings.   this might work:

```ruby

saved_umask = "it doesnt matter what this is, i just need this variable in my binding"

ruby_block "set umask" do
  block
    saved_umask = File#umask(0022)
  end
end

git "whatever" do
  [...stuff...]
end

ruby_block "set umask" do
  block
    File#umask(saved_umask)
  end
end
```

Ruby variable scoping can be horrible, that compiles in my brain, not entirely certain ruby will agree with me...

**Comment by glensc** [comment]
ah, i see. you did mean separate blocks, as i looked none of the callbacks (`after_restart`, `before_migrate`, `before_restart`, `before_symlink`, `restart_command`) fit wrapping around `git` command run.

**Comment by glensc** [comment]
neat. this seems to be it!

```ruby
# setup and keep cdn-js updated

directory node['cdn-js']['dir'] do
	owner 'root'
	group 'root'
	mode '0755'
	action :create
end

# create umask variable to define scope
umask = nil

ruby_block "set umask" do
	block do
		umask = File.umask(0022)
	end
end

deploy_revision node['cdn-js']['dir'] do
	repo node['cdn-js']['git_repository']
	revision node['cdn-js']['git_revision']
	# setup credentials to access git over ssh
	ssh_wrapper node['sshwrapper']

	rollback_on_error true

	# disable these, defaults are ugly
	# http://stackoverflow.com/a/12569090/2314626
	purge_before_symlink([])
	create_dirs_before_symlink([])
	symlink_before_migrate({})
	symlinks({})
end

ruby_block "restore umask" do
	block do
		File.umask(umask)
	end
end
```

**Comment by lamont-granquist** [comment]
yeah that should work, although `umask` worries me a bit since if we ever define a `umask` resource or a `umask` method on the DSL it'll collide with that (and it might get into your cookbooks via some cookbook you use using chef-sugar which might pick up such a method).  `temp_umask` would be a bit better to avoid future problems.

**Comment by lamont-granquist** [comment]
Closing this since there's workarounds and its now a dup of #3741
