### ISSUE TITLE
knife missing subcommands after rehash

### ISSUE THREAD

**Issue by alexpop** [chef/chef#4089]
After installing chef-dk 0.9.0, I executed `knife rehash` to speed up knife.
Later on, I've noticed `knife upload` and `knife download` not being recognized anymore. So, I executed the following commands to identify all default missing subcommands after `rehash`

```
[07:50:21 /tmp]$ knife > rehash.txt
[07:50:32 /tmp]$ rm ~/.chef/plugin_manifest.json
[07:50:41 /tmp]$ knife > norehash.txt
[07:50:46 /tmp]$ diff rehash.txt norehash.txt
142a143,151
> knife delete [PATTERN1 ... PATTERNn]
> knife deps PATTERN1 [PATTERNn]
> knife diff PATTERNS
> knife download PATTERNS
> knife edit [PATTERN1 ... PATTERNn]
> knife list [-dfR1p] [PATTERN1 ... PATTERNn]
> knife show [PATTERN1 ... PATTERNn]
> knife upload PATTERNS
> knife xargs [COMMAND]
```

**Comment by stevendanna** [comment]
The issue appears to be that the chef_fs commands all inherit from lib/chef/chef_fs/knife.rb which has it's own `inherited` method defined.  This method calls super and thus ends up at the top of the stack when we use `caller` to determine where the subcommand came from.  This leads to a situation where all of these files are in the manifest, but the reported file for loading them is incorrect.
