### ISSUE TITLE
ReplaceOrAdd Warning

### ISSUE THREAD

**Issue by damacus** [chef/chef#4092]
Hey, 

Just started getting this error. Is this a core Chef::Provider problem?

WARN: Class Chef::Provider::ReplaceOrAdd does not declare 'provides :replace_or_add'.

[2015-10-22T10:59:05+00:00] WARN: This will no longer work in Chef 13: you must use 'provides' to use the resource's DSL.

**Comment by lamont-granquist** [comment]
replace_or_add isn't a core chef provider, so no this is not a core chef issue, it is in some cookbook that you are using.
