### ISSUE TITLE
cannot write to drive root on windows unless elevated

### ISSUE THREAD

**Issue by mwrock** [chef/chef#4094]
Moving https://github.com/chef/chef-dk/issues/576 to here.

If you try to write a file or directory resource to c:\, a permissions error is thrown unless in an admin shell even if the user has the propper perms.

**Comment by btm** [comment]
On my Windows 10 desktop this seems to be working as expected for me. I wonder about the 'even if the user has proper permissions' as I don't think it's normal to be able to write to the root of the drive without being elevated:

in chef-shell in an elevated command prompt:
```
def writable?(path)
  ::File.exists?(path) && Chef::ReservedNames::Win32::File.file_access_check(path, Chef::ReservedNames::Win32::API::Security::FILE_GENERIC_WRITE)
end

chef (12.16.42)> writable?('C:')
 => true
chef (12.16.42)> writable?('C:/')
 => true
chef (12.16.42)> writable?('C:\\')
 => true

chef (12.16.42)> writable?('C:/WINDOWS')
 => true
```

creating a file succeeds:
```
C:\>echo test > test_file

C:\>
```

In a non-elevated command prompt:
```
chef (12.16.42)> writable?('C:')
 => true
chef (12.16.42)> writable?('C:/')
 => false
chef (12.16.42)> writable?('C:\\')
 => false

chef (12.16.42)> writable?('C:/WINDOWS')
 => false
```

creating a file fails:
```
C:\>echo test > test_file
Access is denied.

C:\>

```

Interestingly when not elevated vim lets me create a file without error but it doesn't show up.

**Comment by btm** [comment]
1) Running `knife cookbook create foo` from the root of the drive creates a cookbook in my chef-repo.
2) Running `chef generate cookbook foo2` seems to try to generate a cookbook in the root of my drive.

Changing my config to have my cookbook_path be `c:/` and then running #1 again does succeed. 

Ah, so, we indeed to do not have permissions to create files at the root of the drive. We do have permission to create subdirectories though. Changing FILE_GENERIC_WRITE to FILE_ADD_SUBDIRECTORY returns true for a non-elevated shell:

```
def add_directory?(path)
  ::File.exists?(path) && Chef::ReservedNames::Win32::File.file_access_check(path, Chef::ReservedNames::Win32::API::Security::FILE_ADD_SUBDIRECTORY)
end
chef (12.16.42)> add_directory?('c:')
 => true
chef (12.16.42)> add_directory?('c:/')
 => true
chef (12.16.42)> add_directory?('c:\\')
 => true
```

So what we need in this case is to be more specific about which rights we are interested in.
