### ISSUE TITLE
package resource should honor version without release

### ISSUE THREAD

**Issue by someara** [chef/chef#4103]
This is non-intuitive.

Yum from the command line works with

```
 yum install docker-engine-1.7.1
```

Chef forces you to investigate an enabled package repository and then specify an exact release

``` ruby
package 'docker-engine' do
  version '1.7.1-1.el6'
end
```

^ The problem with that, is that it might not be the latest revision available to a repository, which is probably not what you want on RHELish systems.

Googling 'Did you specify both version and release?' yields chaos and confusion.
Example of chaos and confusion - https://github.com/someara/chef-docker/issues/93

**Comment by pkang** [comment]
+1.

Would love it if we could get this enhancement. Like @someara mentioned, it's completely unintuitive given yum command line works without having to specify release portion of package.

**Comment by phspagiari** [comment]
:+1:

**Comment by joshuawscott** [comment]
👍

**Comment by hatt** [comment]
How is this not standard behaviour? The underlying package management supports it and every other "major" configuration management system has supported this for a long time.

**Comment by someara** [comment]
Lack of this feature basically makes the version property useless if you're not managing your own repository mirrors.

Upstream repositories (for some reason) often yank releases when new ones come out.
This is causing all sorts of chaos in the mysql cookbook

https://github.com/chef-cookbooks/mysql/issues/443

**Comment by someara** [comment]
This applies to apt_package as well

**Comment by someara** [comment]
https://github.com/chef-cookbooks/docker/issues/781

**Comment by lamont-granquist** [comment]
#6540 fixes this
