### ISSUE TITLE
Firewall Cookbook--undefined method `provides' for Chef::Provider

### ISSUE THREAD

**Issue by Mr-Howard-Roark** [chef/chef#4107]
I am getting the below error, and cannot figure out how to fix it despite finding similar errors posted on the interwebs.  Weirdly, I get the error regardless of the version of the Firewall cookbook I use (ie <2.0 and >2.0 give the same error).  Any thoughts on how to approach this problem would be appreciated.

Chef Version:
    Chef Development Kit Version: 0.8.1
    chef-client version: 12.4.4

Error:
=========================================                            
uvo1cltmcfslkk0zr9g.vm.cld.sr Recipe Compile Error in /var/chef/cache
uvo1cltmcfslkk0zr9g.vm.cld.sr =======================================
=========================================                            
uvo1cltmcfslkk0zr9g.vm.cld.sr                                        
uvo1cltmcfslkk0zr9g.vm.cld.sr NoMethodError                          
uvo1cltmcfslkk0zr9g.vm.cld.sr undefined method `provides' for Chef::Provider::FirewallFirewalld:Class

**Comment by lamont-granquist** [comment]
That looks like you're using Chef 11, not Chef 12.4.4 -- or else that class is not inheriting from Chef::Provider.

**Comment by Mr-Howard-Roark** [comment]
Thanks for your reply.  I am using Chef 12.4.4--please see below.  I suppose if the FirewallFirewalld class is not inheriting from Chef::Provider, then there's no workaround?  It seems like a previous version must have worked properly in the past.
  
$chef --version                                                      
Chef Development Kit Version: 0.8.1                                  
chef-client version: 12.4.4                                          
berks version: 3.3.0                                                 
kitchen version: 1.4.2                                               
$

**Comment by lamont-granquist** [comment]
That provider inherits from Chef::Provider::LWRPBase which inherits from Chef::Provider:

https://github.com/chef-cookbooks/firewall/blob/e408c1c40f9a82171d89572808d29ff8b1881581/libraries/provider_firewall_firewalld.rb#L19

Are you launching a virt using something like test-kitchen which is using an image which has Chef 11, and/or can you dump the full stacktrace.out in here?  Because that error message looks like you're using Chef 11, even if Chef 12 is what is installed in your workstation.

**Comment by Mr-Howard-Roark** [comment]
Ohhh whoops--ya I am bootstrapping a node, which apparently is installing a chef-client of version 11.16.2.  Thanks for your replies! 

-Mike
