### ISSUE TITLE
SELinux does not update /etc/selinux/config

### ISSUE THREAD

**Issue by lbornov2** [chef/chef#4113]
When using the official SELinux cookbook (managed by Chef - https://supermarket.chef.io/cookbooks/selinux/versions/0.9.0), 

including the recipe

selinux_state "SELinux Permissive" do
  action :permissive
end

Does NOT update the /etc/selinux/config.  Presumably, according to the SELinux docs, these are the the startup values (https://wiki.gentoo.org/wiki/SELinux/Tutorials/Permissive_versus_enforcing).  Therefore, a would will wipe out the chef configurations, and use the ones in /etc/selinux/config

**Comment by lamont-granquist** [comment]
Is this not an issue that should go against the selinux cookbook itself?

**Comment by lbornov2** [comment]
@lamont-granquist , my bad, thought selinux cookbook was managed by chef.  Actually owned by https://github.com/skottler/selinux.  Closing.

**Comment by lamont-granquist** [comment]
(FWIW, even if its owned by chef, this is the wrong repo, this is client-only -- all cookbooks need to have issues cut against their own repos under chef-cookbook/whatever on github...)
