### ISSUE TITLE
Remove the use of method_missing to populate the params hash of definitions

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#4117]
This may go under the heading of definitions needing a complete rethink.

But fundamentally definitions are pretty simple and just a method created on the DSL.  But under the covers, it uses method_missing to populate its params hash:

https://github.com/chef/chef/blob/8d32fdd4377476a9f7dc36a864ccdaa17c32b3a1/lib/chef/resource_definition.rb#L57-L62

This is awful when you accidentally find that you've wound up with a method named `#timeout` polluting your namespace (because of some awful legacy ruby code) and now method_missing never fires when you try to pass a 'timeout' option to a definition:

https://github.com/lamont-cookbooks/multipackage/issues/6

The definitions block needs to be parsed by a real object which has methods on it corresponding to the parameters that the definition wants.  But currently definitions do not declare the parameters that they want to receive.

What we probably want to do is leverage properties and have a definitions v2 API that makes users specify their interface for the definition with properties and then does proper parsing and input validation of the properties.

Since fundamentally a definition is just a method on the DSL it make make more sense to just write some useful mixins or base classes so that people can write methods-on-the-DSL-which-take-blocks-and-use-properties-for-validation.  Don't even call them definitions to avoid the stink associated with that name.

Ideally you just open up a class and do something like:

``` ruby
class Multipackage < Chef::DSL::Extension
  provides :multipackage

  property :package_name, [String, Array], :name_property => true
  property :timeout, [String, Integer]

  code do
    [...stuff...]
  end
end
```

**Comment by coderanger** [comment]
How is this not a resource?

**Comment by lamont-granquist** [comment]
it'll still run at compile-time and doesn't have any actions, and can't be notified or subscribed, its just a method with strong typing to its block arguments.

**Comment by lamont-granquist** [comment]
this'll also be RFC'd, this is a TODO for me, and I'm going to play around with this in a cookbook for awhile and validate that something like i just wrote really does work...

**Comment by lamont-granquist** [comment]
So this could work as a resource but it needs an after_created block to force it to compile time like chef_gem, and then we'd need hooks to be able to break out of the use_inline_resources sub-resource collection and manipulate either the parent or the root resource collection.

**Comment by lamont-granquist** [comment]
nobody should use definitions
