### ISSUE TITLE
Chef 12 opscode-reporting bootstrap is failing behind a proxy

### ISSUE THREAD

**Issue by nkaravias** [chef/chef#4121]
On a fresh Chef 12 server (12.2.0-1 on OEL 6.5 x64) I've installed the opscode-reporting package and I'm trying to configure it. The host that's running the Chef server only has access to the net via a web proxy and $no_proxy is properly set to 127.0.0.1,localhost on the environment and on /opt/opscode-reporting/embedded/cookbooks/solo.rb.

Running opscode-reporting-ctl reconfigure seems to break because it cant connect to chef zero. For the duration of the converge (for opscode-reporting-ctl reconfigure) I was able to see that chef-zero is indeed up and listening on localhost:8889. However the client is not able to connect to it (my guess is because it's ignoring $no_proxy and my proxy server is blocking it). Any ideas?

Here's a snippet of the output of `opscode-reporting-ctl reconfigure`
```
- configure service runit_service[opscode-reporting]
Recipe: opscode-reporting::oc-reporting-pedant
  * template[/etc/opscode-reporting/pedant_config.rb] action create (up to date)
Recipe: opscode-reporting::default
  * file[/etc/opscode-reporting/opscode-reporting-running.json] action create (up to date)
[2015-10-29T13:25:53-07:00] ERROR: Timeout connecting to http://127.0.0.1:8889/nodes/den00qcw.local.com, retry 1/5
http://127.0.0.1:8889/nodes/den00qcw.local.com, retry 2/5
http://127.0.0.1:8889/nodes/den00qcw.local.com, retry 3/5
http://127.0.0.1:8889/nodes/den00qcw.local.com, retry 4/5
http://127.0.0.1:8889/nodes/den00qcw.local.com, retry 5/5
^Running handlers:
[2015-10-29T14:22:01-07:00] ERROR: Running exception handlers
Running handlers complete

[2015-10-29T14:22:01-07:00] ERROR: Exception handlers complete
[2015-10-29T14:22:01-07:00] FATAL: Stacktrace dumped to /opt/opscode-reporting/embedded/cookbooks/cache/chef-stacktrace.out
Chef Client failed. 5 resources updated in 2677.812041135 seconds
[2015-10-29T14:22:01-07:00] ERROR: Timeout connecting to http://127.0.0.1:8889/nodes/den00qcw.local.com, giving up
```

**Comment by lamont-granquist** [comment]
This is the repo for the chef-client project, probably needs to get refiled against either:

https://github.com/chef/chef-reporting/issues/new

or if that is private, then against chef-server itself:

https://github.com/chef/chef-server/issues/new
