### ISSUE TITLE
yum downgrade install method not respected for local package

### ISSUE THREAD

**Issue by Sauraus** [chef/chef#4123]
If you specify the `source` attribute on a yum package chef-client will default to `localinstall` as the installation method because it's hardcoded here: https://github.com/chef/chef/blob/master/lib/chef/provider/package/yum.rb#L1255-L1260

**Comment by lamont-granquist** [comment]
What should the correct behavior be?

**Comment by Sauraus** [comment]
IMHO it should allow downgrade with a local package, why should this only be supported for remote package installs?

**Comment by lamont-granquist** [comment]
yeah, i haven't admin'd a CentOS box in over 4 years, just need to understand what commands to issue, that code is very useful...

**Comment by lamont-granquist** [comment]
#6540 fixes this now
