### ISSUE TITLE
git submodules are not downloaded with git resource

### ISSUE THREAD

**Issue by puneetloya** [chef/chef#4126]
_From @puneetloya on October 29, 2015 1:29_

git tests_dir do
  repository node['xyz']['repo']
  revision node['xyz']['branch']
  enable_submodules true
  action :sync
end

It is downloading the main parent repository but not the submodules. I am getting only the .gitmodules file and nothing else. Am I missing something very basic?

_Copied from original issue: jssjr/git#83_

**Comment by puneetloya** [comment]
_From @someara on October 29, 2015 16:15_

Hello! The "git" resource ships in Core Chef, not this cookbook. Can you please file this at github.com/chef/chef ?

**Comment by lamont-granquist** [comment]
Could use more information - version of chef-client, debug output from when the resource runs, etc.

**Comment by joshburt** [comment]
I believe I understand the problem here.  I'm working on a re-write of the git HWRP and have included the fix in that code base.

A stand-alone version of the git HWRP is here:  https://github.com/joshburt/jgit

Once the work is complete, I'll create pull requests for the enhancements.  If you'd like to review the changes before-hand they are here:
https://github.com/joshburt/jgit/blob/master/libraries/provider_jgit.rb#L190
https://github.com/joshburt/jgit/blob/master/libraries/provider_jgit.rb#L207

**Problem Description**
We are currently preping the submodules like this:
`git submodule sync`
and we should be doing this:
`git submodule init`

Additionally passing `--recursive` to clone commands has the same affect and has been added to my code base.  Updates were made with respect to this: https://git-scm.com/book/en/v2/Git-Tools-Submodules

Timeline:
The code base is complete.  Tests are being updated now.  Once tests are updated I'll submit the pull request and comment back here.

Thanks!

**Comment by joshburt** [comment]
I originally thought this was an issue.  I reviewed the code and the documentation, and then tested it.  I no longer believe this is an issue with Chef.


So, first a recap of how we are handling submodules within the git HWRP.  The below logic is derived from https://github.com/chef/chef/blob/master/lib/chef/provider/git.rb#L169

On action sync, or checkout we run these git commands:
```
git submodule sync
git submodule update --init --recursive
```


From the official documentation: https://git-scm.com/docs/git-submodule

> 
> init
> Initialize the submodules recorded in the index (which were added and committed elsewhere) by copying submodule names and urls from .gitmodules to .git/config. Optional <path> arguments limit which submodules will be initialized. It will also copy the value of submodule.$name.update into .git/config. The key used in .git/config is submodule.$name.url. This command does not alter existing information in .git/config. You can then customize the submodule clone URLs in .git/config for your local setup and proceed to git submodule update; you can also just use git submodule update --init without the explicit init step if you do not intend to customize any submodule locations.
> 
> sync
> Synchronizes submodules' remote URL configuration setting to the value specified in .gitmodules. It will only affect those submodules which already have a URL entry in .git/config (that is the case when they are initialized or freshly added). This is useful when submodule URLs change upstream and you need to update your local repositories accordingly.
> 	"git submodule sync" synchronizes all submodules while "git submodule sync -- A" synchronizes submodule "A" only.
> 	If --recursive is specified, this command will recurse into the registered submodules, and sync any nested submodules within.
> 



**Summary**
	Based off the git documentation we should NOT need to perform a 'git submodule init', as I originally though.  Based on the init documentation that would only be required if we intended to customize the submodule locations (which we don't support).


**The Test**
To test this I created a git repository consisting of a number of submodules:  https://github.com/joshburt/git_tester

Platform: Windows Server 2012R2
Git Version: 2.7.2 32-bit
Chef-Client Version: 12.6.0-1

I then created a cookbook with a single recipe in it that performed the following:
```
git 'git_tester' do
  repository 'https://github.com/joshburt/git_tester.git'
  enable_submodules true
  action :sync
end
```

Relevant output:
```
[2016-05-24T14:48:36-06:00] INFO: Processing git[git_tester] action sync (git_tester::default line 7)                                                                                                     
[2016-05-24T14:48:37-06:00] INFO: git[git_tester] cloning repo https://github.com/joshburt/git_tester.git to git_tester                                                                                   
[2016-05-24T14:48:37-06:00] INFO: git[git_tester] checked out branch: HEAD onto: deploy reference: 075daa97178f61ec69d97bd7257efc49190478c9                                                               
[2016-05-24T14:48:37-06:00] INFO: git[git_tester] synchronizing git submodules                                                                                                                            
[2016-05-24T14:48:38-06:00] INFO: git[git_tester] enabling git submodules                                                                                                                                 
```
Works as expected.  Submodules are checkout.

**Final Thoughts**
I have a theory on what was occurring when this was initially reported, but would need confirmation.

If one makes changes to what is checkout, the working 'deploy' branch might not represent what is expected. (e.g. If you remove everything other than the .git folder and re-run nothing will change.  There would need to be a revision change to trigger any logic to fire and update what is checkout on the filesystem).

Unless the original submitter can provide more information I believe was should be closed.
Thanks,
