### ISSUE TITLE
UX on knife server delete prompt is misleading

### ISSUE THREAD

**Issue by vinyar** [chef/chef#4128]
Original bug here:
https://github.com/chef/knife-azure/issues/242

Relevant code:
This code [here1](https://github.com/chef/knife-azure/blob/master/lib/chef/knife/azure_server_delete.rb#L126) is actually calling the confirm method from the core knife ui [here2](https://github.com/chef/chef/blob/master/lib/chef/knife/core/ui.rb#L267-L272).

Here1 - https://github.com/chef/knife-azure/blob/master/lib/chef/knife/azure_server_delete.rb#L126
Here2 - https://github.com/chef/chef/blob/master/lib/chef/knife/core/ui.rb#L267-L272

--------@ricardolupo original bug:
The prompt for `knife azure server delete` should allow upper and lower case [y|Y] or allow the literal string being requested.

`Do you really want to delete this server? (Y/N) Y
I have no idea what to do with 'Y'
Just say Y or N, please.
Do you really want to delete this server? (Y/N) y`

**Comment by cheeseplus** [comment]
This should be working as expected now.
