### ISSUE TITLE
Yum installs on Fedora 22 broken

### ISSUE THREAD

**Issue by tas50** [chef/chef#4129]
The yum provider with the dnf shim fails on Fedora 22 with an error in the yum-dump.py script.  Complete error here:

https://gist.github.com/tas50/51436655202c7b895948

**Comment by tas50** [comment]
Fixed here https://github.com/chef/chef/pull/4142

**Comment by brianhays** [comment]
Looks like the issue can be closed. :smile: The fix (#4142) was merged :rocket:
