### ISSUE TITLE
knife bootstrap fails without run list

### ISSUE THREAD

**Issue by btm** [chef/chef#4131]
When bootstrapping without a run list (I was testing bootstrapping and didn't need a run) knife fails with an exception:

```
ERROR: knife encountered an unexpected error
This may be a bug in the 'ec2 server create' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `empty?' for nil:NilClass
```

It looks like #policyfile_and_run_list_given? added in #3958 fails on `!config[:run_list].empty?` because `config[:run_list]` isn't set at all.

Backtrace. Ugh. We need to not swallow the backtrace in knife.
```
ERROR: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/bootstrap.rb:425:in `policyfile_and_run_list_given?'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/bootstrap.rb:381:in `validate_options!'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/bootstrap.rb:328:in `run'
/Users/btm/.chefdk/gem/ruby/2.1.0/gems/knife-ec2-0.12.0/lib/chef/knife/ec2_server_create.rb:529:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:405:in `block in run_with_pretty_exceptions'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:404:in `run_with_pretty_exceptions'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:203:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/knife.rb:142:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/knife:25:in `<top (required)>'
/usr/local/bin/knife:54:in `load'
/usr/local/bin/knife:54:in `<main>'
```

/cc @danielsdeleo

**Comment by danielsdeleo** [comment]
should be a pretty easy fix.

As for the stack trace bit, I think there's a general agreement that stack traces are scary for users who aren't expecting them, and the error message did a good job of telling you how to gather the relevant data.

**Comment by btm** [comment]
I'm not sure how the error message did a good job of anything other than reminding me to go add code to print the stacktrace in the usual spot. I'm missing something. -V -V output doesn't help because there's limited debugging output in knife/knife-ec2/knife-windows. The stacktrace makes it immediately obvious. I'm going to submit a PR to save the stacktrace somewhere, which will be a lot easier than describing to someone how to add it back.

**Comment by btm** [comment]
backtrace patch: #4137
