### ISSUE TITLE
Subversion - shell unfriendly parameters

### ISSUE THREAD

**Issue by JCotton1123** [chef/chef#4132]
The subversion resource doesn't appear to escape or enclose in quotes its parameters when the generated command is passed to the shell. See https://github.com/chef/chef/blob/master/lib/chef/provider/subversion.rb#L193 for example.

Example where the password contains a parenthesis:

```
 ---- Begin output of svn info https://XXX.sourcerepo.com/XXX/web --no-auth-cache --username XXXX --password [hidden_password]  -rHEAD ----
       STDOUT:
       STDERR: sh: 1: Syntax error: ")" unexpected
```

When I find some time I'll try to create a fix and issue a PR.

**Comment by tas50** [comment]
I'm going to close this out as a wont-fix for now. The subversion resources aren't a priority for the team and that most likely will not change. If someone in the community wants to take up improving this resource we'd gladly accept a PR, but the team won't be resolving this issue.
