### ISSUE TITLE
Chef-client re-register does not work against CS12.1.0 and newer

### ISSUE THREAD

**Issue by andy-dufour** [chef/chef#4139]
If you take a registered client and remove its client.pem, in chef server 11 the node would re-register as long as the validator key was still present on the node and the validator had update access on the client.

Since CS12.1.0 you get the following error message:
'Since Server API v1, all keys must be updated via the keys endpoint.'

Potential fix here:

https://github.com/chef/chef/tree/ad/reregistration-keysapi

**Comment by coderanger** [comment]
You probably want to close this and re-open it as a pull-request.

**Comment by jaymzh** [comment]
There will be a pull request. I requested an issue, however, for tracking in the meantime.

**Comment by tylercloke** [comment]
Yeah `lib/chef/api_client/registration.rb` accidentally got updated to use API V1 which won't work for that code. This should fix you:

https://github.com/chef/chef/pull/4238

**Comment by lamont-granquist** [comment]
looks fixed by #4238
