### ISSUE TITLE
(feature request) include pry-byebug with chef-dk

### ISSUE THREAD

**Issue by vinyar** [chef/chef#4144]
Original bug here: https://github.com/chef/chef-dk/issues/579

Since Pry is already included, in my opinion byebug should be included as well. 

In my experience, anyone who starts using pry, never goes back, but due to lack of experience in both ruby and debugging, most chef users end up littering their cookbooks with endless `require 'pry';binding.pry` statements.

**Comment by vinyar** [comment]
https://github.com/chef/chef/pull/4146

**Comment by lamont-granquist** [comment]
yeah wrong place, a PR against omnibus-chef to include it in both chef and chef-dk would get my approval.
