### ISSUE TITLE
Windows plugin disabling not working

### ISSUE THREAD

**Issue by dscowan** [chef/chef#4148]
Chef 12.5.1

In client.rb I have tried

Ohai::Config[:disabled_plugins] = [	"gce" ]

Which gives a warning that the new style should be used, but I see no "Skipped gce plugin" in the debug output

I have also tried

ohai.disabled_plugins = [:gce]
ohai.disabled_plugins = ["gce"]
Ohai::Config[:disabled_plugins] = [	:gce ]

None of which seem to actually disable the plugin

**Comment by tas50** [comment]
Give :GCE a try.

-Tim

**Comment by dscowan** [comment]
That worked.  I had no idea it was case sensitive

ohai.disabled_plugins = [:GCE, :NetworkListeners, :NetworkRoutes, :Azure]

works fine
