### ISSUE TITLE
Look for client.rb in .chef

### ISSUE THREAD

**Issue by georeith** [chef/chef#4150]
With chef-provisioning you often want to use your workstation as a provisioning node.

I and I'm sure many others put shared data into knife.rb under source control and then gitignore and load in a knife.local.rb  and a client.pem file which the team member supplies. By the time a user has configured this they have done all the necessary steps to also setup their client.rb (in this case anyway) but they can only use one in this location with a verbose command line option that differs per workstation and install location.

Considering .chef is earmarked for configuration can we not extend the lookup for client.rb to .chef?

**Comment by coderanger** [comment]
Local-mode should automatically load the `knife.rb` instead of `client.rb` following the normal workstation loading code I think.

https://github.com/chef/chef/blob/92ba97d8af84822ebcda4f928cd82b001148c5b5/lib/chef/application/client.rb#L346-L350 is the specific code to handle it.

**Comment by georeith** [comment]
@coderanger Local-mode forces you to use chef zero no? Should be able to use a workstation as a provisioning node on a chef-server

**Comment by georeith** [comment]
@coderanger Nevermind as long as `chef_zero.enabled` is set to false it correctly works. Thanks for the info.
