### ISSUE TITLE
Suppress databag warning about unencrypted databag

### ISSUE THREAD

**Issue by spuder** [chef/chef#4154]
Anytime you run a command to fetch from a databag, it throws the following warning. 

> knife : Unencrypted data bag detected, ignoring any provided secret options.

This alert is more noisy when scripting in powershell

``` powershell
knife : Unencrypted data bag detected, ignoring any provided secret options.
At line:12 char:19
+ $databagrelease = knife data bag show foo bar -c c:\chef\client.rb | Sele ...
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unencrypted dat...secret options.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

It would be nice if `chef data bag show foo bar` had the option to suppress this warning.  

The affected line of code is here: 

https://github.com/chef/chef/blob/master/lib/chef/knife/data_bag_show.rb#L43-L56

Maybe change `ui.info` to `ui.warn` ?

**Comment by spuder** [comment]
As a side note, I'm not using encrypted databags, so I'm not sure why that alert is given. This might actually be a bug. 


```ruby
          if encrypted && secret
            # Users do not need to pass --encrypt to read data, we simply try to use the provided secret
            ui.info("Encrypted data bag detected, decrypting with provided secret.")
            raw = Chef::EncryptedDataBagItem.load(@name_args[0],
                                                  @name_args[1],
                                                  secret)
```

**Comment by rileyrileyrose** [comment]
I'd like to help with this, if it's not been assigned yet.

**Comment by coderanger** [comment]
@rileyrileyrose We don't really assign stuff per se. Just put up a pull request and someone will take a look :-) If you've got any questions about getting started with Chef development feel free to drop me a line on #chef IRC, Hangops Slack, or Discourse.

**Comment by rileyrileyrose** [comment]
@coderanger Thanks!

**Comment by PatrickWalker** [comment]
@spuder you mention it would nice to have the option to suppress. Would you see this being a CLI argument passed in? I think making it warn as per your last suggestion should be enough, is the concern that someone is supplying a secret file under the false idea that the databag is encrypted?

**Comment by spuder** [comment]
Our use case is we have a powershell wrapper that we hand to developers. It runs chef and shows if the build artifact was changed with pretty output. We would like a way to disable the ugly warning.

**Comment by bkdspanning** [comment]
+1

Even showing an unencrypted data bag item gets a warning:

> $ knife data bag show thinger thing -Fj
WARNING: Unencrypted data bag detected, ignoring any provided secret options.

You can add verbosity with an argument, it would be nice to either turn off verbosity or set the level.  It looks like the code uses log levels, so maybe it could be something like `--log-level info`?

**Comment by matthiasr** [comment]
I don't see how _raising_ the log level of the message helps here. Now I need to suppress all warnings to get rid of this (informational) message?

**Comment by matthiasr** [comment]
Even worse, it seems it is impossible to lower the log level of `knife`? As far as I can discern, no flag means "warn" (so before #4524 would _not_ have shown this message), `-V` means "info", `-V -V" means debug? This is not explicitly stated in [the documentation](https://docs.chef.io/debug.html#knife), can someone confirm this?

A `log_level` statement in `knife.rb` seems to be completely ignored (on Knife 12.13.30).
