### ISSUE TITLE
Support for SystemD "mask"/"unmask" commands

### ISSUE THREAD

**Issue by Azrael808** [chef/chef#4155]
This was a bug in the old Jira instance:

https://tickets.opscode.com/browse/CHEF-3369

I'm wondering if this is something that's on the roadmap for Chef?

**Comment by ranjib** [comment]
Chef-systemd cookbook allows this. You want to give it a spin?

**Comment by Azrael808** [comment]
Thanks @ranjib - looks like that cookbook _will_ eventually support it, but not right now:

https://github.com/nathwill/chef-systemd/issues/64

I've subscribed to that issue, but in the meantime I'll be looking how the systemd cookbook can help me in other ways!
