### ISSUE TITLE
Chef server installation in RHEL 5 without root access.

### ISSUE THREAD

**Issue by ManishMehra** [chef/chef#4163]
Hi Team

Why does chef need root access? Is there a possible way to install chef in RHEL5 server without having root privileges? 

Thanks

**Comment by thommay** [comment]
Hi, this is the repository for the chef client, not the server. Also, this is a bug tracker, not a help system. I'd recommend that you post a question to our mailing list at https://discourse.chef.io.
Thanks

**Comment by stevendanna** [comment]
A brief answer for @ManishMehra:

Chef Server requires root privileges for a few items:

- Installing the package 
- Listening on privileged ports (80, 443)
- Installing ourselves into the system's init system so starts on boot
- Tuning sysctls around shared memory limits

Without modification, it is not currently possible to install chef-server without root privileges.  Happy to discuss this use case more in a chef-server issue or the mailing list.

**Comment by ManishMehra** [comment]
Thanks for the clarification @stevendanna.  Sure @thommay. I will keep that in mind.
