### ISSUE TITLE
Implement a progress bar/summary option for knife ssh

### ISSUE THREAD

**Issue by TheSerapher** [chef/chef#4170]
We are running quite a few SSH commands where we only worry about shell exit codes and how far we are into the process. For that matter, it would be great to have the option to redirect output of the command into a file, show a progress bar while running and at the end a simple summary of nodes exit codes and potential list of failed nodes. I have not seen an option to do this yet.

Not sure if this was requested before as an enhancement, just noticed it would be great while running my knife ssh session. Could also be used as copy/paste content for possible tickets that are resolved by this ;-)

**Comment by coderanger** [comment]
I think this might be out of scope for `knife ssh`. It is designed to be relatively simplistic, this kind of UI work might be better off in a more dedicated SSH scripting tool like Fabric or Capistrano. That said, it wouldn't hurt too much to add, the complexity cost seems manageable either way.

**Comment by TheSerapher** [comment]
Possibly right, but since as an admin I use mostly `knife ssh` for my tasks, it would not be too bad to have it directly built into the tool as an option. To be honest, most of the time the output is a sensory overload when running it across a lot of nodes, and even though one could minimise it by adding a output redirect into the SSH command and only make a summary there, it would still be neater to have a proper copy & paste-able output from the tool itself.

Thanks for looking into this, it's really just a nice to have. If complexity exceed the usability, too bad.

**Comment by michael-peck** [comment]
I completely agree with TheSerapher, it would be a nice-to-have. In my ideal world there would be a progress bar and also a current-status/current-recipe type of indication so if things freeze or just take a long time it's clear where things are stuck.

Can't fault you in the least for wanting to keep knife the simple tool it is, but if it doesn't compromise that objective a progress thing would be very handy... and would be useful when demonstrating chef to clients and product owners.
