### ISSUE TITLE
Email bug 

### ISSUE THREAD

**Issue by MarioColuzzi** [chef/chef#4171]
An email account with third or fourth domain level is not accepted in Chef setup

Example, by issuing the following command setup:

**chef-server-ctl user-create mariocoluzzi mario coluzzi  chef_admin mario.coluzzi@aaa.bbb.ccc.uk password --filename /chef_rep**

got the following: **ERROR: Conflict**

Only when I have a second level domain email, setup exit without error

**Comment by coderanger** [comment]
Are you sure it isn't that you either already have a user with the email or a user with the username?

**Comment by coderanger** [comment]
Also this repo is for Chef, please file Chef Server bug reports over at https://github.com/chef/chef-server/.

**Comment by MarioColuzzi** [comment]
Running handlers:
Running handlers complete
Chef Client finished, 410/478 resources updated in 175.986088 seconds
Chef Server Reconfigured!
[root@chef tmp]# chef-server-ctl user-create chef_admin chef_admin mario.coluzzi@aaa.bbb.ccc.uk password --filename /chef_rep
FATAL: Wrong number of arguments
USAGE: knife opc user create USERNAME FIRST_NAME [MIDDLE_NAME] LAST_NAME EMAIL PASSWORD
    -s, --server-url URL             Chef Server URL
        --chef-zero-host HOST        Host to start chef-zero on
        --chef-zero-port PORT        Port (or port range) to start chef-zero on.  Port ranges like 1000,1010 or 8889-9999 will try all given p                              orts until one works.
    -k, --key KEY                    API Client Key
        --[no-]color                 Use colored output, defaults to false on Windows, true otherwise
    -c, --config CONFIG              The configuration file to use
        --defaults                   Accept default values for all questions
    -d, --disable-editing            Do not open EDITOR, just accept the data as is
    -e, --editor EDITOR              Set the editor to use for interactive commands
    -E, --environment ENVIRONMENT    Set the Chef environment (except for in searches, where this will be flagrantly ignored)
    -f, --filename FILENAME          Write private key to FILENAME rather than STDOUT
    -F, --format FORMAT              Which format to use for output
        --[no-]listen                Whether a local mode (-z) server binds to a port
    -z, --local-mode                 Point knife commands at local repository instead of server
    -u, --user USER                  API Client Username
    -o, --orgname ORGNAME            Associate new user to an organization matching ORGNAME
        --print-after                Show the data after a destructive operation
    -V, --verbose                    More verbose output. Use twice for max verbosity
    -v, --version                    Show chef version
    -y, --yes                        Say yes to all prompts for confirmation
    -h, --help                       Show this message
[root@chef tmp]# chef-server-ctl user-create chef_admin chef_admin chef_admin mario.coluzzi@aaa.bbb.ccc.uk password --filename /chef_rep
ERROR: Errno::EISDIR: Is a directory @ rb_sysopen - /chef_rep
[root@chef tmp]# chef-server-ctl user-create chef_admin chef_admin chef_admin mario.coluzzi@aaa.bbb.ccc.uk password --filename /chef_rep/Credent                              ials
ERROR: Conflict
Response: User 'chef_admin' already exists
[root@chef tmp]# chef-server-ctl user-create mario_admin mario_admin mario_admin mario.coluzzi@aaa.bbb.ccc.uk password --filename /chef_rep/Cred                              entials
ERROR: Conflict
Response: User 'mario_admin' already exists
[root@chef tmp]# chef-server-ctl user-create mariocoluzzi mario coluzzi mario.coluzzi@aaa.bbb.ccc.uk password --filename /chef_rep/MarioColuzzi.pem                           ERROR: Conflict
Response: User 'mariocoluzzi' already exists
[root@chef tmp]# chef-server-ctl user-create mariocoluzzi mario coluzzi mario.coluzzi@aaa.bbb.ccc.uk password --filename /chef_rep/MarioColuzzi.pem
FATAL: File /chef_rep/MarioColuzzi.pem is not writable.  Check permissions.
chmod 775 -R /chef_rep
[root@chef tmp]# chef-server-ctl user-create mariocoluzzi mario coluzzi mario.coluzzi@aaa.bbb.ccc.uk password --filename /chef_rep/MarioColuzzi.pem
ERROR: Conflict
Response: User 'mariocoluzzi' already exists
[root@chef tmp]# chef-server-ctl org-create passport "Mario Coluzzi local chef" --association_user mariocoluzzi --filename  /chef_rep/ORGANIZATION-validator.pem
ERROR: The data in your request was invalid
Response: Field 'name' invalid
[root@chef tmp]# chef-server-ctl org-create passport "Mario Coluzzi local chef" --association_user mariocoluzzi --filename  /chef_rep/ORGANIZATION-validator.pem
ERROR: The object you are looking for could not be found
Response: Could not find user mariocoluzzi
[root@chef tmp]# chef-server-ctl user-create mariocoluzzi mario coluzzi mario.coluzzi@aaa.bbb.ccc.uk password --filename MarioColuzzi.pem
ERROR: Conflict
Response: User 'mariocoluzzi' already exists
[root@chef tmp]# chef-server-ctl user-create mariocoluzzi mario coluzzi mario.coluzzi@aaa.bbb.ccc.uk password --filename /chef_rep/MarioColuzzi.pem
ERROR: Conflict
Response: User 'mariocoluzzi' already exists
[root@chef tmp]# chef-server-ctl user-create mariocoluzzi mario coluzzi mario.coluzzi@aaa.bbb.ccc.uk password --filename /chef_rep/MarioColuzzi.pem
ERROR: Conflict
Response: User 'mariocoluzzi' already exists
[root@chef tmp]# chef-server-ctl user-create user_name first_name last_name email password --filename /chef_rep/MarioColuzzi.pem
ERROR: The data in your request was invalid
Response: email must be valid
[root@chef tmp]# chef-server-ctl user-create stevedanno Steve Danno steved@chef.io abc123 --filename /chef_rep/MarioColuzzi.pem
[root@chef tmp]# chef-server-ctl user-create mariocoluzzi Mario Coluzzi mario.coluzzi@aaa.bbb.ccc.uk password --filename /chef_rep/MarioColuzzi.pem
ERROR: Conflict
Response: User 'mariocoluzzi' already exists
[root@chef tmp]# chef-server-ctl user-create mariocoluzzi Mario Coluzzi mario.coluzzi@passport.org password --filename /chef_rep/MarioColuzzi.pem
[root@chef tmp]# chef-server-ctl org-create passport "Mario Coluzzi local chef" --association_user mariocoluzzi --filename  /chef_rep/ORGANIZATION-validator.pem
ERROR: Conflict
Response: Organization already exists
[root@chef tmp]# chef-server-ctl org-create passport "Mario Coluzzi local chef" --association_user mariocoluzzi --filename  /chef_rep/ORGANIZATION-validator.pem
ERROR: Conflict
Response: Organization already exists
[root@chef tmp]# chef-server-ctl
I don't know that command.
[root@chef tmp]# chef-server-ctl org-create passport "Mario Coluzzi local chef" --association_user mariocoluzzi --filename  /chef_rep/ORGANIZATION-validator.pem
[root@chef tmp]# chef-server-ctl org-delete passport
Do you want to delete the organization passport? (Y/N) y
full_name: Mario Coluzzi local chef
guid:      d686db66a09b9454423c5b9874e283de
name:      passport
[root@chef tmp]# chef-server-ctl org-create passport "Mario Coluzzi local chef" --association_user mariocoluzzi --filename  /chef_rep/ORGANIZATION-validator.pem
[root@chef tmp]# chef-server-ctl install opscode-manage
Starting Chef Client, version 12.5.0.current.0
resolving cookbooks for run list: ["private-chef::add_ons_wrapper"]
Synchronizing Cookbooks:
  - private-chef (0.1.0)

**Comment by coderanger** [comment]
As stated in the errors, you are trying to create objects which already exist. Additionally, as I said, you filed this in the wrong place.
