### ISSUE TITLE
chef-server-ctl install . . . offline

### ISSUE THREAD

**Issue by MarioColuzzi** [chef/chef#4172]
Not all computers are allowed to access internet, as you may know.

**chef-server-ctl install opscode-manage**

Does not work in machines in DMZ

This is a *feature* rather than a bug **but it can be considered as such if not fixed**.

How to dump repository locally?

**Comment by coderanger** [comment]
As stated in the other issue, please don't file Chef Server bug reports here.

**Comment by coderanger** [comment]
But to answer your question, you can download the deb or rpm for all addons directly from https://packagecloud.io/chef/stable and transfer them to the machine yourself.

**Comment by MarioColuzzi** [comment]
Thanks!

**Comment by smith** [comment]
Look under "Use Local Packages" on https://docs.chef.io/install_server.html
