### ISSUE TITLE
AIX 7.1 + chef-client 12.5.1 Showing 404s in chef-client STDOUT/STDERR

### ISSUE THREAD

**Issue by sean-horn** [chef/chef#4181]
AIX 7.1 with chefDK 0.10 is showing output like the following during bootstrapping, while the same version linux client does not. The 404s are the usual flags for "There is no node on the chef server for this node/client name" and "Could not communicate with a Reporting service" . The chef-client runs appear to be succeeding.

```
knife bootstrap p135n52.example.com.com -x root -P passwd 
-N p135n52.example.com.com '-r recipe[aix-base-setup],recipe[ebs]' -y -V 
I get 404 Object Not Found error on startup. I would like to find out what i am doing wrong to get this error. 

See -V output below. Also included -VV output with attachment bug1.out. 
OS AIX 7.1, chefdk 10.0. chef client 12.5.1 


INFO: Using configuration from /chef-repo/.chef/knife.rb 
INFO: HTTP Request Returned 404 Object Not Found: error 
INFO: HTTP Request Returned 404 Object Not Found: error 
Creating new client for p135n52.example.com.com 
Creating new node for p135n52.example.com.com 
INFO: HTTP Request Returned 404 Object Not Found: error 
Connecting to p135n52.example.com.com 
p135n52.example.com.com -----> Existing Chef installation detected 
p135n52.example.com.com Starting the first Chef Client run... 
p135n52.example.com.com Starting Chef Client, version 12.5.1
```

**Comment by lamont-granquist** [comment]
It looks like you're using the validatorless bootstrapping and you're passing -V to it so you're getting the INFO messages output  by the HTTP code when it hits the 404 on the client and node which triggers the creation of the client+node.  AIX has nothing to do with this, and on the Linux box you're either using a validation client or not passing -V.  The output is maybe a little unclean, but you did pass -V and the 404s won't appear without that -- and fixing that would be so messy and involve hacking around in the guts of Chef::HTTP and this is so cosmetic that the priority of this is below low, so just closing.
