### ISSUE TITLE
Running chef-client -z (local mode) from / breaks system configuration (e.g. sudo)

### ISSUE THREAD

**Issue by adammeghji** [chef/chef#4186]
I've noticed that running chef-client in local mode via "-z" from the / root directory has side effects which break things across the system, i.e. the ability to sudo.  I'm provisioning machines via AWS user-data.sh, which happens to run as root in /.

Here is the command being run via user-data in /:
`sh -c "cd / && chef-client -z --recipe-url /etc/chef/cookbooks.tgz -j /etc/chef/first-boot.json"`

In the sudo example, I can't tell what's being changed on the system which affects sudo specifically, but I get this error:
```
ubuntu@ip-10-150-146-12:~$ sudo ls
sudo: unable to stat /etc/sudoers: No such file or directory
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin
ubuntu@ip-10-150-146-12:~$
```

Running from any other directory avoids this side effect, and my system remains intact.  For example:
`sh -c "cd /etc/chef && chef-client -z --recipe-url /etc/chef/cookbooks.tgz -j /etc/chef/first-boot.json"`

Hopefully this is sufficient to help track this down :)  Super obscure error, but glad I have a workaround.

**Comment by lamont-granquist** [comment]
somehow your /etc/sudoers file got deleted, but chef-client -z doesn't touch that on its own accord.

most likely its something in your recipe code in the chef-client run which is doing it.

**Comment by adammeghji** [comment]
@lamont-granquist oddly enough, /etc/sudoers is untouched, and /etc/sudoers.d/ is also untouched.  Something else is being mutated in the system, but I'm not smart enough to figure out what (despite 4+ hours of wracking my brain and looking around).

This happens immediately upon running chef-client -z, before any of the cookbooks have actually run.

I will try to put together a reproduceable scenario, which should involve spinning up a new box, installing chef-client, cd /, and running chef-client -z.  @zts confirmed this is a bug in IRC when discussing yesterday.

**Comment by lamont-granquist** [comment]
So ohai might have a bug.  It shouldn't mutate any system state, but sometimes strange code in plugins sneaks through code review.  The only other possibility I can think of would be something truly bizzare in the way local mode sets up its own cache directory.

**Comment by adammeghji** [comment]
I'm also using recipe-url to fetch cookbooks, which get extracted into the cwd, could something else be modifying permissions or mangling anything in subdirectories beyond ./cookbooks, i.e. modifying "." or "./etc"?

**Comment by lamont-granquist** [comment]
Hmmm, there was that awful FileUtils.rm_rf, but I think I ripped that out of the chef-client code you'd be running under zero and that it was only under chef-solo.  That is some funky code though.

**Comment by lamont-granquist** [comment]
(i fixed your first example where i assume you meant to 'cd /' instead of 'cd /etc/chef')

**Comment by thommay** [comment]
@adammeghji how are you getting on with putting together a reproduction?

**Comment by adammeghji** [comment]
@lamont-granquist thanks :)
@thommay I've been engulfed in some other stuff, so haven't had time to reproduce this in a sandbox.

**Comment by adammeghji** [comment]
@thommay in attempting to create a reproduceable scenario, I was able to get some additional info re: what's happening here.  Looks like my cookbooks.tgz file actually has `.` in it, and `--recipe-url` is extracting into `cwd`, and thus overwriting `.`:
```
ubuntu@kungfu:/tmp/t$ tar -tvf cookbooks.tgz
drwx------ 1000/1000         0 2015-11-24 17:37 .
drwxrwxr-x 1000/1000         0 2015-11-24 17:37 cookbooks
```

Thus, `/.` is being overwritten with `drwx------` instead of `drwxr-xr-x`, and everything goes to hell after that.

I'm generating the cookbooks.tgz via Berkshelf's `berks package`.  I'll take it up with those folks.

Thanks for all the help everyone!  Sorry for the false alarm.

**Comment by lamont-granquist** [comment]
yeah that makes sense, and we extract the tarball in . because we expect to have ./cookbooks and such which only makes sense, so if . is in the tarball and you're in / and it fiddles with the perms then you're gonna have a bad day...

does not seem like there's any useful way to change the chef/chef codebase to make this any better...
