### ISSUE TITLE
ArgumentError: invalid byte sequence in UTF-8 when using knife diff on binary files

### ISSUE THREAD

**Issue by matschaffer** [chef/chef#4189]
### Version:

11.18.12
### Scenario:

Diff cookbooks that may contain binary files
### Steps to Reproduce:

`knife diff cookbooks/a_cookbook_containing_a_binary`

Using OS X `.DS_Store` files seem especially likely to cause the error
### Expected Result:

Some sort of non-crash diff report (e.g., "Binary files X and Y differ")
### Actual Result:

`ERROR: ArgumentError: invalid byte sequence in UTF-8`
### Notes

The problematic code seems to still be [here in `Chef::ChefFS::CommandLine.diff_text`](https://github.com/chef/chef/blob/master/lib/chef/chef_fs/command_line.rb#L263) in master.

`new_value` and `old_value` come in as strings with specific encodings (ASCII-8BIT in the case of binary files). The values then get written out to files, then read back in [here in `Chef::Util::Diff#udiff`](https://github.com/chef/chef/blob/master/lib/chef/util/diff.rb#L92) but without and encoding option. `IO.readlines` then appears to default to UTF-8.

**Comment by lamont-granquist** [comment]
Part of the breaking changes to Chef 12.0 were numerous encoding relating fixes, along with the upgrade to ruby-2.x which fixed other encoding inconsistencies.

**Comment by lamont-granquist** [comment]
Closing this, reopen if its still broken on 12.

**Comment by matschaffer** [comment]
Sorry should have updated the version. I originally noticed it on 11 but it's also broken on 12 and on master.

**Comment by matschaffer** [comment]
@lamont-granquist Just reconfirmed now, same exact error on 12.5.1. 244f7a5e6312 had a different failure though I suspect this is just blocking the ArgumentError since it's due to an undefined abstract method since the code I linked to in the description (using `IO.readlines` with no encoding option) is still present. 

```
/Users/mat/.rvm/gems/ruby-2.2.3/bundler/gems/chef-244f7a5e6312/lib/chef/chef_fs/file_system/base_fs_object.rb:99:in `child': undefined method `make_child_entry' for #<Chef::ChefFS::FileSystem::CookbookSubdir:0x007fb60199ecd8> (NoMethodError)
	from /Users/mat/.rvm/gems/ruby-2.2.3/bundler/gems/chef-244f7a5e6312/lib/chef/chef_fs/file_system.rb:234:in `block in child_pairs'
	from /Users/mat/.rvm/gems/ruby-2.2.3/bundler/gems/chef-244f7a5e6312/lib/chef/chef_fs/file_system.rb:232:in `each'
	from /Users/mat/.rvm/gems/ruby-2.2.3/bundler/gems/chef-244f7a5e6312/lib/chef/chef_fs/file_system.rb:232:in `child_pairs'
	from /Users/mat/.rvm/gems/ruby-2.2.3/bundler/gems/chef-244f7a5e6312/lib/chef/chef_fs/command_line.rb:145:in `diff_entries'
	from /Users/mat/.rvm/gems/ruby-2.2.3/bundler/gems/chef-244f7a5e6312/lib/chef/chef_fs/command_line.rb:146:in `block in diff_entries'
	from /Users/mat/.rvm/gems/ruby-2.2.3/bundler/gems/chef-244f7a5e6312/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `call'
	from /Users/mat/.rvm/gems/ruby-2.2.3/bundler/gems/chef-244f7a5e6312/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:267:in `process_input'
	from /Users/mat/.rvm/gems/ruby-2.2.3/bundler/gems/chef-244f7a5e6312/lib/chef/chef_fs/parallelizer/parallel_enumerable.rb:257:in `process_one'
	from /Users/mat/.rvm/gems/ruby-2.2.3/bundler/gems/chef-244f7a5e6312/lib/chef/chef_fs/parallelizer.rb:93:in `call'
	from /Users/mat/.rvm/gems/ruby-2.2.3/bundler/gems/chef-244f7a5e6312/lib/chef/chef_fs/parallelizer.rb:93:in `worker_loop'
	from /Users/mat/.rvm/gems/ruby-2.2.3/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
	from /Users/mat/.rvm/gems/ruby-2.2.3/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

**Comment by matschaffer** [comment]
#4180 appears to be the same issue as this one.

**Comment by matschaffer** [comment]
If it helps (or anyone else who finds this) I used this monkey patch on my chef 11 project to at least see which file was causing the problem:

```ruby
class << Chef::ChefFS::CommandLine
  alias diff_text_without_cookbook_status_encoding_rescue diff_text

  def diff_text(old_path, new_path, old_value, new_value)
    diff_text_without_cookbook_status_encoding_rescue(old_path, new_path, old_value, new_value)
  rescue ArgumentError => e
    "!!! Unable to diff #{old_path} and #{new_path} due to #{e}"
  end
end
```

**Comment by lamont-granquist** [comment]
Yeah so ChefFS extracted that udiff() method to bypass all the output formatting, but it dropped the important check to make sure that the files weren't binary.  Either that needs to get put into udiff or the calling method in ChefFS needs to handle that case explicitly.

**Comment by alexandredrumond** [comment]
Arquive´s name with especial caracter is a problem because Chef generate erro. Verify all arquives inside folder cookbooks, including folder "file".
