### ISSUE TITLE
Avoid end users access to the Chef cookbooks in node cache directory

### ISSUE THREAD

**Issue by chefgs** [chef/chef#4191]
We have got a situation in which, we need to avoid system end users accessing Chef cookbooks in cache directory. what is the best way to handle this?

1. Can we delete the cookbook from cache path, at the end of cookbook execution?
2. Is it possible to encrypt/decrypt cookbook while executing Chef client?

Please provide a suggestion
&
Is it possible to include the probable solution, as a enhancement to upcoming Chef release?

**Comment by coderanger** [comment]
This was already answered on StackOverflow: http://stackoverflow.com/q/33669880/78722

Do not spam the team just because you don't like the answer.
