### ISSUE TITLE
knife user create fails with local mode

### ISSUE THREAD

**Issue by equick** [chef/chef#4197]
Hi,

I'm using chefdk-0.10.0-1.el7.x86_64 and trying to create users in localmode for testing [chef-vault](https://github.com/Nordstrom/chef-vault).

In Chef12 the syntax is:
```
knife user create USERNAME DISPLAY_NAME FIRST_NAME LAST_NAME EMAIL PASSWORD (options)
```

So I run this with the -z option:
```
bash-4.3$ knife user create quick quick Edward Quick quick@noreply.com secret -z
ERROR: The data in your request was invalid
Response: Must specify "name" in JSON
```

I tried changing username to name but I still got the same response.
```
{
  "username": "quick",
  "display_name": "quick",
  "first_name": "Edward",
  "last_name": "Quick",
  "email": "quick@noreply.com",
  "password": "secret",
  "create_key": true
}
```

This issue sounds similar to [issue 3010](https://github.com/chef/chef/issues/3010) but in my case it's trying to create users in local mode.

Am I doing something wrong here, or is this a bug?

Thanks,
Ed

**Comment by lamont-granquist** [comment]
you're probably better off just creating the json manually yourself, the backing store for chef-zero is just the filesystem.

**Comment by lamont-granquist** [comment]
It seems that the solution to this on chef-server is to use `chef-server-ctl user-create` which means that knife and chef-server are just broken for this command with chef-12 server.  It looks like localmode is just being faithful to this brokenness.  There's nothing to fix in knife right now.  There's also nothing to fix in chef-zero/local-mode right now.  So I think this would have been better submitted as a bug against the server:  http://github.com/chef/chef-server/issues/new.

**Comment by equick** [comment]
Thanks, that's exactly what I did in the end and submitted a [PR](https://github.com/test-kitchen/test-kitchen/pull/880) for test-kitchen but I still think this should work with knife user create -z

**Comment by equick** [comment]
Ok thanks lamont-granquist, I will leave this for now as I have a workaround.
