### ISSUE TITLE
(windows) powershell_script should not inherit from $profile

### ISSUE THREAD

**Issue by vinyar** [chef/chef#4199]
If $profile has syntax errors, powershell_script resource will fail.

__Example:__
$profile has invalid syntax that's missing a bracket

__Proposed solution:__
Pass -NoProfile to  `powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy RemoteSigned -InputFormat None...`

__Details:__
powershell_script errors out with:

$profile content:
```
PS C:\Users\vagrant> type $profile
new-alias n "C:\Program Files (x86)\Notepad++\notepad++.exe" -force
new-alias s "C:\Program Files\Sublime Text 2\sublime_text.exe" -force
new-alias k knife -force
new-alias chef chef-client -force
remove-item alias:cd ; set-alias cd pushd -force
"chef shell-init powershell | Invoke-Expression" >> $PROFILE
```

powershell_script throws the same error as powershell on the server directly.
```ruby
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [[WinRM::Transport::FileTransporter] Upload failed (exitcode: 0), but stderr present
Invoke-Expression : At line:1 char:2
+ [2015-11-23T13:50:18-08:00] WARN: *****************************************
+  ~
Missing type name after '['.
At C:\Users\vagrant\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps
1:7 char:30
+ chef shell-init powershell | Invoke-Expression
+                              ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : MissingTypename,Microsoft.PowerShell.Commands.InvokeExpressionCommand
```

**Comment by lamont-granquist** [comment]
chef/mixin/powershell_out probably needs this as well?

**Comment by thommay** [comment]
ping @chef/client-windows

**Comment by mwrock** [comment]
`-noprofile` was added as one of the default flags in March: https://github.com/chef/chef/commit/48984933cca0d9d31cd667478f050f45029b08d5

**Comment by mwrock** [comment]
@vinyar which chef client version are you seeing this with?

**Comment by vinyar** [comment]
I'll double check why we were not seeing it.

**Comment by vinyar** [comment]
I verified that both powershell_out and powershell_script use -noprofile. 
Unfortunately, I no longer have access to test environment. I'll keep an eye out, and reopen if I hit this agian.
