### ISSUE TITLE
 incorrect output for custom resource in chef 12.5.1

### ISSUE THREAD

**Issue by pwlae** [chef/chef#4201]
Hi.
If I run my resource like single resource (Not in loop)
For example:
```
openstack_client 'create identity service' do
  option variables
  command 'service create identity'
  command_argument(
    description: '"OpenStack Identity"',
    name: 'keystone'
  )
end
```
Chef output correct:
* openstack_client[create identity service] action run (up to date)

But if I call my resource in array
For example:
```
%w(
  admin
  user
).each do |role|
  openstack_client "create #{role} role" do
    option variables
    command "role create #{role}"
  end
end
```
Output looks like:
  *      (up to date)
  *      (up to date)

All tests I doing on kitchen
```
$ /opt/chefdk/embedded/bin/chef --version
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2
```

**Comment by lamont-granquist** [comment]
this is a test-kitchen bug in how it handles output, not a core chef bug
