### ISSUE TITLE
Inaccurate documentation about ports required for push-jobs

### ISSUE THREAD

**Issue by tonyflint** [chef/chef#4205]
Both of these pages:
https://docs.chef.io/push_jobs.html
https://docs.chef.io/server_firewalls_and_ports.html

Mention this regarding what ports must be open between the push-jobs clients and server:

`TCP protocol ports 10000 and 10003 must be open. These are the heartbeat and command ports respectively.`

However, after doing a tcpdump from a push-jobs client, I see TCP traffic on ports 10000 and 10002 (not 10003). Is 10002 required in addition to, or instead of, 10003?

**Comment by thommay** [comment]
@tonyflint please can you file this bug on the chef/chef-web-docs project?

**Comment by lamont-granquist** [comment]
Needs to get cut against http://chef/chef-web-docs/issues/new, this is just for reporting bugs against the client.

**Comment by lamont-granquist** [comment]
jinx!
