### ISSUE TITLE
Bootstrap/Chef-Client broken on CentOS 7 with Chef 12.5.1

### ISSUE THREAD

**Issue by darkn3rd** [chef/chef#4209]
Running through tutorials from learn.chef.io with webapp tutorial on RHEL. trying a simple bootstrap, and it seems to fail on CentOS 7.  I did not have the same issue when using Ubuntu 14.04 Trusty Tahr.

Doing this from a Cent OS 7 workstation with ChefDK 0.10 installed (`chefdk-0.10.0-1.el7.x86_64.rpm`) against a Chef Server 12.3.

```bash
$ knife bootstrap ${ADDRESS} --sudo --ssh-user ${USER} --node-name ${NODE_NAME} --run-list ${RUN_LIST}
Creating new client for node
Creating new node for node
Connecting to node
node -----> Existing Chef installation detected
node mkdir: cannot create directory ‘/etc/chef’: File exists
node sh: line 178: /etc/chef/client.pem: Not a directory
node chmod: cannot access ‘/etc/chef/client.pem’: Not a directory
node mkdir: cannot create directory ‘/etc/chef’: Not a directory
node sh: line 213: /etc/chef/trusted_certs/chefserver.crt: Not a directory
node sh: line 241: /etc/chef/client.rb: Not a directory
node sh: line 250: /etc/chef/first-boot.json: Not a directory
node Starting the first Chef Client run...
node /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/config_fetcher.rb:50:in `realpath': Not a directory @ realpath_rec - /etc/chef/client.rb (Errno::ENOTDIR)
node 	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/config_fetcher.rb:50:in `realpath'
node 	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/config_fetcher.rb:50:in `config_missing?'
node 	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:95:in `load_config_file'
node 	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:346:in `load_config_file'
node 	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:87:in `configure_chef'
node 	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:48:in `reconfigure'
node 	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:279:in `reconfigure'
node 	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:58:in `run'
node 	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/chef-client:26:in `<top (required)>'
node 	from /bin/chef-client:54:in `load'
node 	from /bin/chef-client:54:in `<main>'
```

The node actually does get registered on the Chef Server, only if the validator is not configured, at least with my initial testing.  When I try to do an chef-client run on the target node, it the similar error:

```bash
# chef-client
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/config_fetcher.rb:50:in `realpath': Not a directory @ realpath_rec - /etc/chef/client.rb (Errno::ENOTDIR)
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/config_fetcher.rb:50:in `realpath'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/config_fetcher.rb:50:in `config_missing?'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:95:in `load_config_file'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:346:in `load_config_file'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:87:in `configure_chef'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:48:in `reconfigure'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/client.rb:279:in `reconfigure'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application.rb:58:in `run'
	from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/chef-client:26:in `<top (required)>'
	from /bin/chef-client:54:in `load'
	from /bin/chef-client:54:in `<main>'

```

**Comment by lamont-granquist** [comment]
So the node you're trying to bootstrap has a normal file in '/etc/chef' that is not a directory:

```
node mkdir: cannot create directory ‘/etc/chef’: File exists
node mkdir: cannot create directory ‘/etc/chef’: Not a directory
```

We could certainly give a better error message here.  We could delete this automatically, but that makes me a little nervous since I don't quite know how this happened or what that file is and if we should be deleting it or not.  The solution for you would just be to manually delete that /etc/chef file and if that file is somehow baked into an image to remove it from the base image.

**Comment by darkn3rd** [comment]
On the node itself, I did an initial installation, `rpm -Uvh chef-12.5.1-1.el7.x86_64.rpm`, and the installer does not create the initial `/etc/chef` directory.  I think earlier versions created the directory.  So when I started, the node I am trying to bootstrap has no initial `/etc/chef` at all.   Upon failure, I repeated the process.  Noticing that it registered the node on the chef server, I ran `chef-client` on the node.

**Comment by lamont-granquist** [comment]
You don't have a directory, though, you've clearly got a file or some other non-directory there.  We also never created /etc/chef out of any of our RPMs that we distribute with Omnibus.   We've also certainly never created anything other than a directory there.  If you can't figure out how that got there, I'd actually consider the possibility that file system corruption flipped some bits and trashed that directory entry, really what you've got there is a weird situation that should never have occurred.

**Comment by darkn3rd** [comment]
Sorry, for delay, had to track down the vagrant image I was using at the time.  You're spot on, there was an actual `/etc/chef` file, and when deleted everything if fine.  I am thinking this is too much of an outlier case to warrant any attention.

**Comment by thommay** [comment]
Thanks for confirming this. I'm gonna close this bug.
