### ISSUE TITLE
Creating a key "json_class" in a DataBag leads to error

### ISSUE THREAD

**Issue by joerg** [chef/chef#4212]
I don't know if this actually is part of #3518, if so, feel free to close this issue.

When creating or editing any DataBag Item and adding a key "json_class" in the raw_data part an error is spilled out: `ERROR: Chef::Exceptions::JSON::ParseError: Unsupported `json_class` type 'I AM A STUPID TEXT'`

Steps to reproduce:
* Call `EDITOR=emacs knife data bag edit <data_bag> <item>`
* Fill in something like this (only the json_class in raw_data matters)
```
{
  "name": "data_bag_item_rcrs_chef_reporting_joerg_test_delete_me",
  "json_class": "Chef::DataBagItem",
  "chef_type": "data_bag_item",
  "data_bag": "rcrs_chef_reporting",
  "raw_data": {
    "id": "joerg_test_delete_me",
    "just_a_test": "is valid",
    "json_class": "this is a bug"
  }
}
```
* Output is like `ERROR: Chef::Exceptions::JSON::ParseError: Unsupported `json_class` type 'this is a bug'`

We stumbled upon this because we created a handler that saves all run data in DataBags. Those DataBags are valid and can be viewed with `knife raw` and also with ridley, but `knife data bag` fails.

**Comment by lamont-granquist** [comment]
This is in fact a dup of #3518 and just another manifestation of why json_class sucks very badly.
