### ISSUE TITLE
knife download environments incomplete

### ISSUE THREAD

**Issue by sdarwin** [chef/chef#4213]
Chef: 12.5.1

knife download environments, creates files formatted as:

```
{
  "name": "staging"
}
```

alternatively, a command such as "knife environment show staging --format=json > environments/staging.json" generates:

```
{
  "name": "staging",
  "description": "",
  "cookbook_versions": {

  },
  "json_class": "Chef::Environment",
  "chef_type": "environment",
  "default_attributes": {

  },
  "override_attributes": {

  }
}
```

The latter format is more complete, and in fact test-kitchen + chef-solo requires those additional attributes in an environment, it crashes otherwise.

"knife download environments" should probably download the same data as "knife environment show", right?

**Comment by thommay** [comment]
Right, we should totally verify which bits of this kitchen/solo/zero actually need and make `knife download environment` do the right thing here.

**Comment by lamont-granquist** [comment]
If the problem here is that ChefFS is suppressing empty hashes on download and is not actually reflecting the state of the 'document' on the server, that should definitely get fixed there.

If its accurately reflecting the server, it might be a bit muddier as to what to do about this...

**Comment by smurawski** [comment]
This should be part of https://github.com/chef/chef/issues/3368

**Comment by lamont-granquist** [comment]
I'm not actually positive its part of that epic....   it might just be a core bug in ChefFS...
