### ISSUE TITLE
Subversion resource does not respect http_proxy settings

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef#4214]
http://subversion.apache.org/faq.html#proxy

Unlike most Linux utilities which respect `ENV['http_proxy']` (and associated variables) the subversion binary does not.  It requires proxy settings to be added to the subversion servers configuration file.  On my machine this is located at `~/.subversion/servers`.  It requires adding the keys `http-proxy-host` and `http-proxy-port` under the `[global]` group.

If `Chef::Config[:http_proxy]` is set we need to push this down to the subversion configuration when a subversion resource is invoked.

**Comment by thommay** [comment]
can we do `----config-option servers:global:http-proxy-port <port>` as a short term fix?

**Comment by tyler-ball** [comment]
@thommay where are you reading about that??  That is much better than modifying a file!  That should just be our fix if it works.

I had no idea you could specify config on the command line - I'm not familiar with subversion and just used the first link when I googled `subversion http proxy`.

**Comment by thommay** [comment]
yeah it's gnarly but do `svn co --help` and it's in there, and then you can figure out what the key is based on what you wrote above.

**Comment by thommay** [comment]
(actually forget short term fix; if we don't have to poke around in `.subversion/servers` then we shouldn't

**Comment by tanahlayang** [comment]
Hi pals,
Did we think that not all users need this proxy argument extension, (My Environment doesn't need it)?
I think the params *svn_arguments* has useful enough if someone *want override the svn configs*

The issue now,
If these arguments has forced in source code to add in chef subversion resource, How I want to disable it? cause as I said not everyone need these http-proxy

thanks

**Comment by tas50** [comment]
It's not realistic for us to update the config on the fly in order to work around subversion. Instead we should make sure we get this into the documentation so that users understand what they need to do to use proxy servers with subversion.
