### ISSUE TITLE
500 errors in resolving cookbook for runlist - bad argument in call to erlang in chef_depsolver_worker

### ISSUE THREAD

**Issue by umang1912** [chef/chef#4222]
Hi,
Our staging chef server is throwing these errors when running chef-client on the nodes. Restarting services on chef-server didnt help.
client.log on the node -  
> ERROR: Server returned error 500 for https://chef_server_ip/organizations/qubole/environments/staging/cookbook_versions, retrying 1/5 in 3s 

crash.log - 
> =SUPERVISOR REPORT====
     Supervisor: {local,pooler_chef_depsolver_member_sup}
     Context:    child_terminated
     Reason:     {badarg,[{erlang,binary_to_term,[<<131,104,2,100,0,2,111,107,108,0,0,0,4,104,2,109,0,0,0,8,119,101,98,115,108,97,118,101,104,3,97,0,98,2,165,221,160,97,1,104,2,109,0,0,0,12,99,104,101,102,95,104,97,110,100,108,101,114,104,3,97,1,97,1,97,8,104,2,109,0,0,0,16,113,100,115,95,115,101,110,115,117,95,99,108,105,101,110,116,104,3,97,1,97,0,97,0,104,2,109,0,0,0,4,99,114,111,110,104,3,97,1,97,6,97,1>>],[]},{chef_depsolver_worker,handle_call,3,[{file,"src/chef_depsolver_worker.erl"},{line,178}]},{gen_server,try_handle_call,4,[{file,"gen_server.erl"},{line,607}]},{gen_server,handle_msg,5,[{file,"gen_server.erl"},{line,639}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,237}]}]}
     Offender:   [{pid,<0.2334.0>},{name,chef_depsolver_worker},{mfargs,{chef_depsolver_worker,start_link,undefined}},{restart_type,temporary},{shutdown,brutal_kill},{child_type,worker}]

erchef.log - 
> [error] Supervisor pooler_chef_depsolver_member_sup had child chef_depsolver_worker started with {chef_depsolver_worker,start_link,undefined} at <0.2275.0> exit with reason bad argument in call to erlang:binary_to_term(<<131,104,2,100,0,2,111,107,108,0,0,0,4,104,2,109,0,0,0,8,119,101,98,115,108,97,118,101,104,3,97,...>>) in chef_depsolver_worker:handle_call/3 line 178 in context child_terminated

Haven't seen this issue before, and unable to fix it now. Can anyone help?

**Comment by thommay** [comment]
please can you file this on https://github.com/chef/chef-server/issues, where you're much more likely to find someone who can help.

**Comment by umang1912** [comment]
Thanks. I've file it there - https://github.com/chef/chef-server/issues/648. Closing this one.
