### ISSUE TITLE
Cannot add user(active directory) to organization

### ISSUE THREAD

**Issue by sasideveloper** [chef/chef#4223]
Hi,

I tried integration of chef server with active directory. I am not able to add user to organization. Please find the error log below.

chef-server-ctl org-user-add org_name user_name
ERROR: The object you are looking for could not be found
Response: Could not find user user_name

Is it mandatory that every domain user should have one local user in chef? can some one guide how to   start using ldap users..

**Comment by thommay** [comment]
Please file this bug against chef-server rather than chef. Also, we would recommend that support questions be asked at https://discourse.chef.io rather than here. Thanks!
