### ISSUE TITLE
dsc_resource has a fixed 10 minute timout which causes long running dsc resources to fail

### ISSUE THREAD

**Issue by keyrage** [chef/chef#4232]
Using DSC resources with Chef-client 12.5.1 and WMF 5 "Production Preview" will timeout and fail if the resource takes longer than 10 minutes to complete a change. This is especially problematic when using the xSQLServerSetup DSC resource.
Unlike dsc_script there is no property within the dsc_resource that allows the timeout value to be modified.

**Comment by jaym** [comment]
Yep, looks like an oversight. Thanks for the report
