### ISSUE TITLE
knife is relying on environment variable PWD

### ISSUE THREAD

**Issue by kzw** [chef/chef#4233]
The following behavior of knife is unacceptable when called from other interpreters.  My usage is in trying to come up with some mock for knife output when it is executed from python script.  But the behavior is similar when it is called from ruby.

Here is the problem demostrated in ruby.  Python case is similar and discussed briefly at the bottom
```
irb(main):014:0> Dir.pwd
=> "/private/tmp"
irb(main):015:0>
irb(main):015:0> Dir.chdir('/Users/kzwin/chef-repo') { system('pwd') }
/Users/kzwin/chef-repo
=> true
Dir.chdir('/Users/kzwin/chef-repo') { system('knife role -z list') }

=> true
ENV['PWD'] = '/Users/kzwin/chef-repo'
Dir.chdir('/Users/kzwin/chef-repo') { system('knife role -z list') }
roles1
role2
myrole
.
.
.
```

In python, I would like to to use `subprocess.call` or `subprocess.Popen`.  This API has the ability to set the `cwd` of the command to process.  Setting this `cwd` option to anything does not seem to have any affect on `knife`.  Only setting environment variable `PWD` does the trick.

Can someone explain this behavior?  And possibly make it do the right thing?

**Comment by coderanger** [comment]
I'm guessing this is the culprit https://github.com/chef/chef/blob/8d32fdd4377476a9f7dc36a864ccdaa17c32b3a1/chef-config/lib/chef-config/workstation_config_loader.rb#L128-L134

Looks like it only uses `$PWD` if set. Not sure why it wouldn't always use the actual `Dir.pwd`. Ping @danielsdeleo @jkeiser.

**Comment by danielsdeleo** [comment]
This is intentional. When you are relying on the path-based directory lookup, and you symlink a directory inside of that path, `Dir.pwd` reads the "real" path instead of the symlinked thing, which breaks the lookup. Eg., you have:

* `~/my-chef-workspace/my-org` which is a real directory
* `~/my-chef-workspace/my-org/.chef/knife.rb` which is the config you want to use
* `~/my-chef-workspace/my-org/chef-repo` which is a symlink to somewhere else

If you `cd ~/my-chef-workspace/my-org/chef-repo` and run `knife whatever`, it should use the config `~/my-chef-workspace/my-org/.chef/knife.rb` The only way knife can do this is by inspecting `PWD`.

**Comment by coderanger** [comment]
It is also worth noting that knife exists primary for humans, it isn't a scripting tool in general. You can use libraries like PyChef to interact with the Chef API directly.

**Comment by kzw** [comment]
Where can I find the algorithm to discover knife.rb location? 

PyChef looks nice but as chef api changes will pyChef automatically keep up?  My original goal was to come up with a mock of `knife sucommand whatever` output from the real server with `knife subcommand -z whaever`.

**Comment by coderanger** [comment]
Automatically, no. It keeps up with changes when I (or someone else) fixes it, just like any other software :P

**Comment by danielsdeleo** [comment]
The code link that @coderanger posted is for the class that finds and loads your config file. This is probably the most useful method to read: https://github.com/chef/chef/blob/8d32fdd4377476a9f7dc36a864ccdaa17c32b3a1/chef-config/lib/chef-config/workstation_config_loader.rb#L101-L124

Also, as @coderanger hinted, if you unset `PWD` then the process' `cwd` will be respected, so you could just do that.
