### ISSUE TITLE
Chef 12.5 custom resources property collapse with built-in resources

### ISSUE THREAD

**Issue by maoueh** [chef/chef#4250]
Using Chef custom resources syntax introduced in Chef 12.5 series (ChefDK 0.10.0 Windows 7, x64, cookbook depends on `compat_resource ~> 12.5`). 

Assuming the following resource:

```ruby
# resources/custom.rb (cookbook simple)
property :name, String, name_property: true
property :revision, String

git '/tmp/repo' do
  repository 'git@url.com:project.git'
  revision revision
  action :sync
end

# recipes/default.rb
simple_custom 'test' do
  revision 'branch'
end
```

This will result in the following `git` resource:

```ruby
git '/tmp/repo' do
  repository 'git@url.com:project.git'
  revision 'HEAD'
  action :sync
end
```

Changing property `revision` to `revision_` make it work correctly. It seems that due to how custom resource scope is evaluated collapse with built-in properties somehow. It's unclear for me which one does not resolve correctly: the right-hand side or the left-hand side. I would guess the later but it's unclear.

My current workaround is to use `new_resource.revision`. If this is unfixable due to being a Ruby limitation, the documentation should have a note about this.

**Comment by coderanger** [comment]
Indeed this isn't fixable AFAIK (ping @jkeiser) since `#revision` will always look at local real methods before scope promotion to the provider.

**Comment by lamont-granquist** [comment]
this is kind of the same as #4006, but it appears to be even worse...

+1 on ping @jkeiser 

i'm starting to consider that actions should not be evaluated in the context of the resource and the user should be forced to type new_resource.revision in all cases...  the overlapping of namespaces is really pretty messy...

**Comment by jkeiser** [comment]
Yep. sub-resources can't access properties of the parent with the same name. `new_resource.revision` is correct.

**Comment by lamont-granquist** [comment]
closed by #4269

**Comment by maoueh** [comment]
I think I might have hit another scoping problem, but seems highly more weird now. Currently tested with Chef 12.5.1 but I will try later with latest Chef to see if it's a problem or not. Assume this:

```
# Resource
resource_name 'my_resource'

property :name, name_property: true

action :execute do
  cookbook_file '/tmp/#{name}/custom.conf' do
    source "#{name}/custom.conf"
  end
end

# Recipe
my_resource 'mp3'
```

The run will fail looking for the actual cookbook file. Instead of looking for `mp3/custom.conf`, it instead searches for `/tmp/mp3/custom.conf/custom.conf`. It seems that within the `cookbook_file`, the `name` property resolves to the actual `cookbook_file` resource instead of my own `name` property.

I search a bit the issue tracker and did not find any evidence of this. Shall I create a new issue for this?

P.S Extract from printed Chef run log:

```
       [2016-02-21T20:22:09+00:00] ERROR: my_resource [mp3] (test_cookbook::something line 2) had an error: Chef::Exceptions::FileNotFound: cookbook_file[/tmp/mp3/custom.conf] (/tmp/kitchen/cookbooks/test_cookbook/resources/my_resource.rb line 4) had an error: Chef::Exceptions::FileNotFound: Cookbook 'test_cookbook' (1.0.0) does not contain a file at any of these locations:
         files/centos-6.6//tmp/mp3/custom.conf/custom.conf
         files/centos//tmp/mp3/custom.conf/custom.conf
         files/default//tmp/mp3/custom.conf/custom.conf
         files//tmp/mp3/custom.conf/custom.conf
```

**Comment by lamont-granquist** [comment]
That's the same scoping bug.  In 12.7.2 you should hit the warning that was added telling you to add new_resource if that wasn't intended.

**Comment by maoueh** [comment]
Ok thanks for the fast reply, seems like I'm hit from every sides :) Sorry for the hassle!

**Comment by lamont-granquist** [comment]
Yeah the scopes are annoying, I'd kind of suggest always writing `new_resource.whatever` out longhand.

I sort of wonder if we could fix params[:whatever] so it wasn't so awful and scope that to the provider/action and encourage using that...

**Comment by maoueh** [comment]
Yup I agree, if scoping is so easy to break, in some instances in very unexpected ways, a long non-collapsing way should be always used.

Ideas:

`properties.<prop>` where `properties` could be scoped to `action` and `helper` (something I saw you suggesting in another issue).

Or it could be just `property` but I understand however that it could still be slightly confusing as `property` is also used to define the actual `property`. 

In this optic, it could be also `params.<prop>` but frankly, I don't very like `params`, but it's subjective of course.

```
resource 'any' do
  name properties.name
end
```
```
resource 'any' do
  name property.name
end
```
```
resource 'any' do
  name params.name
end
```

**Comment by lamont-granquist** [comment]
yeah, i think the `property` confusion is most likely going to preclude that choice, even if technically i think you could do it because one is defined on the class and one on the instance.
