### ISSUE TITLE
Chef12.5.1 - custom resource template lookup issue

### ISSUE THREAD

**Issue by AlessioMartorelli** [chef/chef#4253]

**Comment by coderanger** [comment]
You seem to have pressed submit a bit too early.

**Comment by AlessioMartorelli** [comment]
Sorry coderanger, accidentally pressed enter while editing the message. I've updated the description, would you mind opening it again?

**Comment by coderanger** [comment]
@AlessioMartorelli This tracker is for bug reports about Chef itself, you can get usage and authoring help from places like the mailing list or IRC channel.

**Comment by coderanger** [comment]
(also I answered you on IRC but you had already left I think)
