### ISSUE TITLE
package resource should raise when package_name.length != version.length != arch.length

### ISSUE THREAD

**Issue by jsmartt** [chef/chef#4266]
This snippet fails on at least the standard centos-7.1 boxes I use with kitchen:

``` ruby
package 'glibc' do
  arch ['x86_64', 'i686']
end
```

I get the following error:

```
Converging 1 resources
Recipe: test2::yum

    * No candidate version available for glibc
    ================================================================================
    Error executing action `install` on resource 'yum_package[glibc]'
    ================================================================================

    Chef::Exceptions::Package
    -------------------------
    No candidate version available for glibc

    Resource Declaration:
    ---------------------
    # In /tmp/kitchen/cache/cookbooks/test2/recipes/yum.rb

      7: package 'glibc' do
      8:   arch ['x86_64', 'i686']
      9: end
     10:

    Compiled Resource:
    ------------------
    # Declared in /tmp/kitchen/cache/cookbooks/test2/recipes/yum.rb:7:in `from_file'

    yum_package("glibc") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      package_name "glibc"
      flush_cache {:before=>false, :after=>false}
      declared_type :package
      cookbook_name "test2"
      recipe_name "yum"
      arch ["x86_64", "i686"]
    end


Running handlers:
[2015-12-09T23:57:16+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-12-09T23:57:16+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 03 seconds
[2015-12-09T23:57:16+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
[2015-12-09T23:57:16+00:00] ERROR: yum_package[glibc] (test2::yum line 7) had an error: Chef::Exceptions::Package: No candidate version available for glibc
```

however, the following works:

``` ruby
package 'glibc' do
  arch 'x86_64'
end

package 'glibc' do
  arch 'i686'
end
```

So I know there is a package available. It doesn't seem to handle an array of architectures as shown in the documentation [here](https://docs.chef.io/resource_yum.html).

**Comment by lamont-granquist** [comment]
i'm leaning towards either that being the correct syntax or it should use (i think) `package [ 'glibc.i686', 'glibc.x86_64' ]` to leverage the arch-in-the-name and multipackage functionality that is already in there.

fixing the code to match the docs to potentially install the cross product of all the existing multipackage stuff plus possibly-array-of-arch handling sounds just messy as hell.  the base problem here is that you need to have two different candidates and install them both, inflating one package to two, and creating two candidate_versions where the package_name_array only has one item.  the resultant code will not be readable or debuggable by humans...

@thommay do you concur doc bug?

**Comment by thommay** [comment]
Yeah I think so; I can't imagine any way you could sensibly handle an array of arches without wild craziness.

**Comment by lamont-granquist** [comment]
So any references to the Array option for the arch property on the yum_package resource should be dropped out of the docs.

**Comment by thommay** [comment]
@jamescott would you mind taking a look at this please?

**Comment by lamont-granquist** [comment]
This is not the intended use for arch-as-an-array, it should look like this and should be an extension of multipackage and the length of the name and arch properties should match:

```
package [ "glibc", "glibc" ] do
  arch [ "x86_64", "i686" ]
end
```

**Comment by lamont-granquist** [comment]
note that the DNF provider at least will make this somewhat easier:  `package [ "glibc.x86_64", "glibc.x86_64" ]`.  IDK if yum_package will support that syntax until we shred the existing nightmare and port the dnf_package approach back to yum_package.
