### ISSUE TITLE
extend apt_package provider with 'build-dep' and 'source' actions

### ISSUE THREAD

**Issue by nickbroon** [chef/chef#4267]
This enhancement would be very useful for using Chef to create package build environments.
See the apt-get man page for details of these actions.

**Comment by lamont-granquist** [comment]
This should probably be in a custom resource in a cookbook that provides primitives geared around building packages.  The core package resource should really stay focused on installing packages for use.

**Comment by thommay** [comment]
Hi,
our feeling is that this is much better implemented as separate resources in a cookbook; it's a rather niche use case in the context of a configuration management system and the edge cases around `source`, especially, could get very hairy.
Thanks for your submission.
