### ISSUE TITLE
Chef 12.6.0 prerelease will not build on AIX due to ruby-prof gem

### ISSUE THREAD

**Issue by scotthain** [chef/chef#4275]
Building native extensions fails on AIX platforms due to a bug. https://github.com/ruby-prof/ruby-prof/pull/177 has a fix.

Stack trace:
https://gist.github.com/scotthain/b3f407511645aa4f5fd2

**Comment by scotthain** [comment]
A workaround could easily be to add a new section in the https://github.com/chef/chef/blob/master/Gemfile#L20 `ruby_prof` and then exclude that in https://github.com/chef/omnibus-software/blob/master/config/software/chef.rb#L62 when on the AIX platform.

**Comment by lamont-granquist** [comment]
not so useful to have this as an issue lying around since its not really actionable.
