### ISSUE TITLE
Duplicated paragraph

### ISSUE THREAD

**Issue by alexandrusavin** [chef/chef#4281]
There is a duplicated paragraph on this [page](https://docs.chef.io/chef_client_security.html) in "knife ssl fetch" section

**Comment by btm** [comment]
Oh, hmm, by paragraph I think you mean a whole section. Could you file a bug over at https://github.com/chef/chef-web-docs/issues instead please?

**Comment by alexandrusavin** [comment]
Yep! Here it is: https://github.com/chef/chef-web-docs/issues/775
