### ISSUE TITLE
Make name_property imply identity

### ISSUE THREAD

**Issue by jkeiser** [chef/chef#4282]
It is weird that this doesn't imply identity:

```
class X < Chef::Resource
  property :path, name_property: true
end
```

`name_attribute` doesn't do this, because an old resource written this way:

```
class X < Chef::Resource::LWRPBase
  attribute :path, name_attribute: true
end
```

Will _not_ be set as the identity attribute.

We can fix this by making `name_property` differ from `name_attribute` in this respect.

However, it should be a default, and this should work:

`property :path, name_property: true, identity: false`

**Comment by tyler-ball** [comment]
We have a test build of 12.7 ready - do we need to hold off on releasing next week to get this fix in?
