### ISSUE TITLE
Make identity_property work with later property decls

### ISSUE THREAD

**Issue by jkeiser** [chef/chef#4283]
This should create an identity property:

```
identity_property :x
property :x, String
```

It does not, currently.

**Comment by tyler-ball** [comment]
We have a test build of 12.7 ready - do we need to hold off on releasing next week to get this fix in?

**Comment by lamont-granquist** [comment]
nope

**Comment by tas50** [comment]
I'm going to close this out at this point as this is a very low priority fix considering the usage of identity_property in general.
