### ISSUE TITLE
knife ssl check fails for chef server running in azure

### ISSUE THREAD

**Issue by ashii007** [chef/chef#4301]
I am following the chef lab for azure at http://tryazuremarketplace.com/chef/lab

Exercise 2, Step 4. When I run 'knife ssl check' command. It failed. stack trace is as follows: 

```
Ashishs-MBP:chef-repo ashishkumar$ knife -v
Chef: 12.5.1
Ashishs-MBP:chef-repo ashishkumar$ sudo knife ssl check -VV
INFO: Using configuration from /Users/ashishkumar/azurecheflab/chef-repo/.chef/knife.rb
DEBUG: Checking SSL cert on https://chefsrv-8oob2k2d.cloudapp.net/organizations/azurechef
Connecting to host chefsrv-8oob2k2d.cloudapp.net:443
/opt/chef/embedded/lib/ruby/2.1.0/openssl/ssl.rb:214:in `verify_wildcard': undefined method `length' for nil:NilClass (NoMethodError)
    from /opt/chef/embedded/lib/ruby/2.1.0/openssl/ssl.rb:196:in `verify_hostname'
    from /opt/chef/embedded/lib/ruby/2.1.0/openssl/ssl.rb:161:in `block in verify_certificate_identity'
    from /opt/chef/embedded/lib/ruby/2.1.0/openssl/ssl.rb:159:in `each'
    from /opt/chef/embedded/lib/ruby/2.1.0/openssl/ssl.rb:159:in `verify_certificate_identity'
    from /opt/chef/embedded/lib/ruby/2.1.0/openssl/ssl.rb:231:in `post_connection_check'
    from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/ssl_check.rb:138:in `verify_cert_host'
    from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/ssl_check.rb:246:in `run'
    from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:405:in `block in run_with_pretty_exceptions'
    from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
    from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:404:in `run_with_pretty_exceptions'
    from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:203:in `run'
    from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/knife.rb:142:in `run'
    from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/knife:25:in `<top (required)>'
    from /usr/local/bin/knife:54:in `load'
    from /usr/local/bin/knife:54:in `<main>'
```

**Comment by juliandunn** [comment]
First of all you don't need `sudo` for that check... but also are you sure your Chef server is actually up and running properly? Can you perform other operations against it? What happens when you open https://your-chef-server/ in your browser?

**Comment by korishev** [comment]
I'm having the same error, at the same point in the same lab.  I can indeed verify that the chef server is working, and that it is using a self-signed cert.  Going to `https://<server>.cloudapp.net` redirects to `https://<server>.cloudapp.net/organizations/azurechef` and shows the management interface (I'm logged in).

Prior to this error, the lab has us run `knife ssl fetch`, with the typical warning, and this result:
```
Adding certificate for .cloudapp.net in /Users/mnelson/chef-repo/.chef/trusted_certs/_cloudapp_net.crt
```
When I check the cert it downloaded though, it looks like the CN field isn't quite right.

```
➜  trusted_certs  openssl x509 -noout -text -in _cloudapp_net.crt
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 0 (0x0)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=YouCorp, OU=Operations, CN=.cloudapp.net
        Validity
            Not Before: Nov 17 19:01:39 2015 GMT
            Not After : Nov 14 19:01:39 2025 GMT
        Subject: C=US, O=YouCorp, OU=Operations, CN=.cloudapp.net
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
```

It would seem to me that the Chef server isn't generating the cert with the right host name.  The CN should be either *.cloudapp.net for a wildcard, or <server>.cloudapp.net for a specific host, but this is neither.  Could this be where openssl's verify_identity/verify_hostname may be getting tripped up?

Is there a way I can regenerate the SSL Cert and force the hostname?

**Comment by juliandunn** [comment]
Hmm. Maybe this is a problem just with the Azure marketplace server image? Pinging @ryancragun for advice.

**Comment by korishev** [comment]
I rolled my own SSL Cert from my personal CA and installed the cert and key into /etc/ssl/[certs|private],  added `nginx['ssl_certificate']` and `nginx['ssl_certificate_key']` to `/etc/opscode/chef-server.rb` pointing at the new files.
I then ran `sudo chef-server-ctl reconfigure` as a workaround.  Everything seems happy now.  I agree, this is likely just a bit of Azure strangeness.

**Comment by jgmio** [comment]
I'm following the [Azure-marketplace tutorial](https://docs.chef.io/azure_portal.html#azure-marketplace) and I also get an error during the certificate check.

Also, before I got `knife ssl fetch` to run I had to edit the ".chef/knife.rb" file to point to the right `chef_server_url`. While the success message mentions an .cloudapp.net url, I actually have an .cloudapp.azure.com url.

The outcome of `knife ssl check` now advises to connect using the hostname .cloudapp.net. Does chef have anything to create the right certificate?

**Comment by sernapallyanurag** [comment]
I am facing same ssl error and I am unable to access my nginx directory. Can you please specify the steps followed to copy these certificate files into the required directory.

**Comment by thommay** [comment]
@jamescott hey, this looks like something we can only fix by documenting that long hostnames will break the chef server. Would the best thing to do be to update https://docs.chef.io/azure_portal.html#azure-marketplace ?

**Comment by jgmio** [comment]
Maybe it's not my place, but why create a script or something that eases the installation process / learning curve?

I'm on Azure but I assume other services also create such long URL's (and thus breaking compatibility)

**Comment by tas50** [comment]
Closing this out as a documentation issue.
