### ISSUE TITLE
 knife upload doesnt work because  method 'make_child_entry' is missing

### ISSUE THREAD

**Issue by rajgouravjain** [chef/chef#4304]
### Version:
in rpm  chefdk-0.9.0-1.el6.x86_6 at gem : chef-12.5.1

[What you are trying to achieve and you can't?]

I am trying to upload resources from chef_repo_path to chef server. 

### Steps to Reproduce:
I am trying to upload resources from my chef_repo_path to chef server using command: 

knife upload / -c /root/.chef/knife-jenkins.rb -VV
### Expected Result:

It should not return a failure message. 

### Actual Result:

Command succeeds but returns failure message with error. : 

=========================================
ERROR: knife encountered an unexpected error
This may be a bug in the 'upload' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `make_child_entry' for #<Chef::ChefFS::FileSystem::CookbookSubdir:0x0000000415d958>
=========================================

Verbose output is available in attachment :
 
[ErrorDuringKnifeUpload.txt](https://github.com/chef/chef/files/61224/ErrorDuringKnifeUpload.txt)
 
========================================

**Comment by lamont-granquist** [comment]
dup of #4070
