### ISSUE TITLE
docs.chef.io doesn't match "knife --help"

### ISSUE THREAD

**Issue by ricksebak** [chef/chef#4305]
https://docs.chef.io/knife_cookbook.html#upload suggests that "knife cookbook upload something -d" is a synonym of "knife cookbook upload something --include-dependencies". These things aren't synonyms of each other. "knife cookbook upload --help" shows that -d is a synomym for --disable-editing.

**Comment by btm** [comment]
Hi,

Thanks for filing a bug, but please file doc bugs over here: https://github.com/chef/chef-web-docs/issues
