### ISSUE TITLE
Subclassing CookBook provider problem

### ISSUE THREAD

**Issue by zdenko-s** [chef/chef#4310]
When overriding method `load_current_resource` I call parent class implementation at the end
>      def load_current_resource
>        @current_resource = Chef::Resource::CookbookFileSubclass.new(@new_resource.name)
>        super
>      end
Problem is that method `load_current_resource` of `CookbookFile` does not check is any subclass already created instance of `@new_resource` but blindly creates new instance.

>def load_current_resource
>        @current_resource = Chef::Resource::CookbookFileSubclass.new(@new_resource.name)
>        super
>      end
If we check same method at `File` provider, we see correct implementation:
>def load_current_resource
>        # Let children resources override constructing the @current_resource
>        @current_resource ||= Chef::Resource::File.new(new_resource.name)
>end
Fix:
Modify `@current_resource = Chef::Resource::CookbookFile.new(@new_resource.name)` to `@current_resource ||= Chef::Resource::CookbookFile.new(@new_resource.name)`

**Comment by lamont-granquist** [comment]
You should not subclass cookbook_file.  You should use composition and use cookbook_file.

Either rewrite what you're doing as a Cusom Resource or LWRP, or subclass from LWRPBase and use the Recipe DSL, or directly mixin the recipe DSL yourself, or mixin build_resource and use that alone, or just build a sub-resource yourself.  In the latter case:

```
          cf = Chef::Resource::CookbookFile.new("/tmp/myfile", run_context)
          cf.source("myfile.erb")
          cf.cookbook(cookbook_name)
          cf.run_action(:create)
          new_resource.updated_by_last_action(true) if cf.updated_by_last_action?
```

**Comment by zdenko-s** [comment]
Composition or inheritance?
OO school says: "Ask yourself, IS or HAS?". My resource IS cookbook file with additional processing. Maybe template? Really does not matter since both of them are implemented wrong way.
Coming from C++, where I would create virtual method 'getResource' which will create/return resource. It is up to the subclass developer to decide does it override and creates different resource or leaves to parent class to implement it.
