### ISSUE TITLE
Add cookbook metadata to conditionally turn lazy_load on/off per-cookbook

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#4317]
The Chef 12 default behavior of eager loading all cookbook files mostly makes sense.  However, it would be good to be able to lazy load files conditionally per-cookbook.  This would make the file-distribution-via-cookbooks more possible again without twiddling global bits that might break other cookbooks.

**Comment by coderanger** [comment]
:+1: though my user case will probably evaporate eventually when we get gem deps in place. We should also think about how to override it as an admin even per-cookbook, if that should be a thing.

**Comment by lamont-granquist** [comment]
Still a thing although without anyone being impacted by this, I don't think we'll ever get around to it.
