### ISSUE TITLE
knife bootstrap fails without run list II

### ISSUE THREAD

**Issue by c0mrade** [chef/chef#4332]
This issue might be related to the same issue that this PR addressed:
https://github.com/chef/chef/pull/4149

Where fix assumes there is a run list in a configuration hash. I was trying to use [google knife](https://github.com/chef/knife-google) to bootstrap nodes from google cloud engine. I've opened [this issue](https://github.com/chef/knife-google/issues/86) at their repo.

I ran it and debug it locally to see where the problem is, and this is the problem actually, not their gem :

```
ERROR: Network 'undefined method `empty?' for nil:NilClass'
ERROR: Network '/Library/Ruby/Gems/2.0.0/gems/chef-12.5.1/lib/chef/knife/bootstrap.rb:425:in `policyfile_and_run_list_given?'
/Library/Ruby/Gems/2.0.0/gems/chef-12.5.1/lib/chef/knife/bootstrap.rb:381:in `validate_options!'
/Library/Ruby/Gems/2.0.0/gems/chef-12.5.1/lib/chef/knife/bootstrap.rb:328:in `run'
/Library/Ruby/Gems/2.0.0/gems/knife-google-2.0.0/lib/chef/knife/google_server_create.rb:641:in `run'
/Library/Ruby/Gems/2.0.0/gems/chef-12.5.1/lib/chef/knife.rb:405:in `block in run_with_pretty_exceptions'
/Library/Ruby/Gems/2.0.0/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/Library/Ruby/Gems/2.0.0/gems/chef-12.5.1/lib/chef/knife.rb:404:in `run_with_pretty_exceptions'
/Library/Ruby/Gems/2.0.0/gems/chef-12.5.1/lib/chef/knife.rb:203:in `run'
/Library/Ruby/Gems/2.0.0/gems/chef-12.5.1/lib/chef/application/knife.rb:142:in `run'
/Library/Ruby/Gems/2.0.0/gems/chef-12.5.1/bin/knife:25:in `<top (required)>'
/usr/local/bin/knife:23:in `load'
/usr/local/bin/knife:23:in `<main>''
```

The issue points to this line https://github.com/chef/chef/blob/12.5.1/lib/chef/knife/bootstrap.rb#L425 and so when I change this line to :

```
(config[:run_list] && !config[:run_list].empty?) && !!config[:policy_name]
```

Actually now that I look at it, it's fixed in a master branch so this might be a duplicate issue

**Comment by btm** [comment]
Have you tried master to see if #4149 fixed the issue?

**Comment by c0mrade** [comment]
@btm yes master does fix the issue
