### ISSUE TITLE
Discussion: enable mixlib-shellout's login mode for execute/script resources

### ISSUE THREAD

**Issue by coderanger** [chef/chef#4338]
So this came up again today and I hadn't seen a discussion on it before. Should we enable the `login` flag? Mostly I care about fixing `$HOME` when a user is set, and then `$PATH` munging that gets turned on seems counterproductive but we should probably do something.

**Comment by webframp** [comment]
Amazingly, I just bumped into this today as well chef-client 12.6 on Windows. Hackish and incomplete, but this got the job done for me: https://github.com/chef/chef/compare/master...webframp:execute-credentials

**Comment by coderanger** [comment]
I put up my own version of this in https://github.com/poise/poise/commit/aaf2e538e3dab0fa96f29a2919014f699614f6e0 along with setting the user's default group if possible.

/cc @chef/client-core

**Comment by lamont-granquist** [comment]
we definitely meant to get that kind of functionality exposed in the resources.

**Comment by webframp** [comment]
I assumed it was just an oversight, since the mixlib-shellout behavior is there. 

As to the correct way to implement it, I have no attachment to the code I started working on and would just like to see it supported on the appropriate providers

**Comment by coderanger** [comment]
I think the two things we need to change before enabling this more globally would be to change the `$PATH` fixes to be an append instead of an overwrite, and add setting at least `$HOME` and `$USER` to the Windows backend too. Also the code in `ShellOut#gid` needs a guard to work on Windows, right now that will throw a nil-NoMethodError.

**Comment by lamont-granquist** [comment]
calling this one a dup of #3563
