### ISSUE TITLE
knife ssh fails with --ssh-password if ~/.ssh/id_rsa does not exist

### ISSUE THREAD

**Issue by jblaine** [chef/chef#4342]
Affects at least knife 12.5.1

Using `knife ssh` in "password, not key" mode fails (though it shows only a warning):

```
% knife ssh 'netgroups:mtc' 'ls /' --ssh-user jblaine --ssh-password
Enter your password:
WARNING: Failed to connect to hosthere.our.org -- Errno::ENOENT: No such file or directory @ rb_sysopen - /afs/rcf/user/jblaine/.ssh/id_rsa

...20 other hosts with same output here...
```

**Comment by cramaechi** [comment]
If `--no-host-key-verify` isn't given on the command line and a password is eventually used to ssh connect to the host, I believe we should disable host key verification manually by setting `config[:host_key_verify]` to false as soon as a password is given via command line, user prompt, or knife.rb. It bears mentioning that host key verification is enabled by default.

<img width="709" alt="screen shot 2018-01-25 at 9 17 06 am" src="https://user-images.githubusercontent.com/24444174/35396134-b937188c-01b1-11e8-9840-8283fb29dbb3.png">
