### ISSUE TITLE
Parameterize bootstrap client.rb log_location

### ISSUE THREAD

**Issue by bcandido** [chef/chef#4346]
In order simplify log_location attribute into client.rb file, its a good idea make it simpler to change in bootstrap time with a parameter into knife.rb file  (maybe), since it is practically the only attribute that is not parametrized.

https://github.com/chef/chef/blob/master/lib/chef/knife/core/bootstrap_context.rb#L66

Change client.rb in bootstrap time could be much easier than create your own bootstrap template in order only to change log_location

**Comment by manoj-vasishta** [comment]
i'll take this one

**Comment by lamont-granquist** [comment]
https://github.com/chef/chef-rfc/blob/master/rfc071-knife-bootstrap-client-config.md closes this i think
