### ISSUE TITLE
Notify multiple packages

### ISSUE THREAD

**Issue by derekjc** [chef/chef#4349]
I'm trying to notify a resource that contains multiple packages as below

```
package ["chef", "chef-zero"] do
    action :nothing
end

log 'call a notification' do
  notifies :install, 'package[chef, chef-zero]', :immediately
end
```

The above recipe is in line with documentation at https://docs.chef.io/resource_yum.html (Multiple Packages). Output of a local run is below. Kindly let me know if this is a bug or a user error?

```
Starting Chef Client, version 11.12.8
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Compiling Cookbooks...
[2015-12-30T23:18:57+05:30] WARN: Node derek-laptop has an empty run list.
Converging 2 resources

Running handlers:
[2015-12-30T23:18:57+05:30] ERROR: Running exception handlers
Running handlers complete

[2015-12-30T23:18:57+05:30] ERROR: Exception handlers complete
[2015-12-30T23:18:57+05:30] FATAL: Stacktrace dumped to /home/derek/.chef/local-mode-cache/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 0.67967665 seconds
[2015-12-30T23:18:57+05:30] ERROR: resource log[call a notification] is configured to notify resource package[chef, chef-zero] with action install, but package[chef, chef-zero] cannot be found in the resource collection. log[call a notification] is defined in /home/derek/abc.rb:5:in `from_file'

[2015-12-30T23:18:57+05:30] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
derek@derek-laptop:~$ cat abc.rb 
package ["chef", "chef-zero"] do
    action :nothing
end

log 'call a notification' do
  notifies :install, 'package[chef, chef-zero]', :immediately
end
```

**Comment by StephenKing** [comment]
You show the output of Chef 11.12.8 here. I think multipackage support was [added with Chef 12.1](https://github.com/chef/chef/blob/master/CHANGELOG.md#1210). But I assume you're also the author of this [question on serverfault.com](http://serverfault.com/questions/745990/chef-notify-multiple-packages) where you show the output of version 12.6 and myself was also able to reproduce the issue with 12.5.1.

**Comment by StephenKing** [comment]
Is there maybe some weird quoting issue involved that the multipackage resource cannot be found in the resource collection?

    chef (12.5.1)> recipe_mode
    chef:recipe (12.5.1)> package ["chef", "chef-zero"] do
    chef:recipe >     action :nothing
    chef:recipe ?> end

    chef:recipe (12.5.1)> resources
    ["package[[\"chef\", \"chef-zero\"]]"]
     => ["package[[\"chef\", \"chef-zero\"]]"]

I would e.g. expect that the following works

    chef:recipe (12.5.1)> resources(resources.first)
    ["package[[\"chef\", \"chef-zero\"]]"]
    Chef::Exceptions::ResourceNotFound: Cannot find a resource matching package[["chef"] (did you define it first?)

**Comment by derekjc** [comment]
Thanks Stephen. I filed this issue as the feature does not work as expected or as per the docs. Wonder if this worked in 12.1 and then got messed up somewhere.

**Comment by derekjc** [comment]
Same behavior on version 12.1

    chef > recipe_mode
    chef:recipe > package ['test', 'test2']
     => <apt_package[test, test2] @name: "test, test2" @noop: nil @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :install, :upgrade, :remove, :purge, :reconfig] @action: :install @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: "(irb#1):1:in `irb_binding'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @sensitive: false @candidate_version: nil @options: nil @package_name: ["test", "test2"] @resource_name: :apt_package @response_file: nil @response_file_variables: {} @source: nil @version: nil @timeout: 900 @default_release: nil @declared_type: :package @cookbook_name: nil @recipe_name: nil> 
    chef:recipe > package 'one item'
     => <apt_package[one item] @name: "one item" @noop: nil @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :install, :upgrade, :remove, :purge, :reconfig] @action: :install @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: "(irb#1):2:in `irb_binding'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @sensitive: false @candidate_version: nil @options: nil @package_name: "one item" @resource_name: :apt_package @response_file: nil @response_file_variables: {} @source: nil @version: nil @timeout: 900 @default_release: nil @declared_type: :package @cookbook_name: nil @recipe_name: nil> 
    chef:recipe > resources
    ["package[[\"test\", \"test2\"]]", "package[one item]"]
     => ["package[[\"test\", \"test2\"]]", "package[one item]"] 


    chef:recipe > resources('package[one item]')
    <apt_package[one item] @name: "one item" @noop: nil @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :install, :upgrade, :remove, :purge, :reconfig] @action: :install @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: "(irb#1):2:in `irb_binding'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @sensitive: false @candidate_version: nil @options: nil @package_name: "one item" @resource_name: :apt_package @response_file: nil @response_file_variables: {} @source: nil @version: nil @timeout: 900 @default_release: nil @declared_type: :package @cookbook_name: nil @recipe_name: nil>
     => <apt_package[one item] @name: "one item" @noop: nil @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :install, :upgrade, :remove, :purge, :reconfig] @action: :install @updated: false @updated_by_last_action: false @supports: {} @ignore_failure: false @retries: 0 @retry_delay: 2 @source_line: "(irb#1):2:in `irb_binding'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @sensitive: false @candidate_version: nil @options: nil @package_name: "one item" @resource_name: :apt_package @response_file: nil @response_file_variables: {} @source: nil @version: nil @timeout: 900 @default_release: nil @declared_type: :package @cookbook_name: nil @recipe_name: nil>


    chef:recipe > resources("package[[\"test\",\"test2\"]]")
    Chef::Exceptions::ResourceNotFound: Cannot find a resource matching package[["test"] (did you define it first?)
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/resource_collection/resource_set.rb:63:in `lookup'
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/resource_collection/resource_set.rb:156:in `block in find_resource_by_string'
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/resource_collection/resource_set.rb:155:in `each'
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/resource_collection/resource_set.rb:155:in `find_resource_by_string'
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/resource_collection/resource_set.rb:87:in `block in find'
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/resource_collection/resource_set.rb:82:in `each'
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/resource_collection/resource_set.rb:82:in `find'
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/recipe.rb:88:in `resources'
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/shell/ext.rb:552:in `resources'
	    from (irb#1):21

    chef:recipe > resources('package[test,test2]')
    Chef::Exceptions::ResourceNotFound: Cannot find a resource matching package[test] (did you define it first?)
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/resource_collection/resource_set.rb:63:in `lookup'
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/resource_collection/resource_set.rb:156:in `block in find_resource_by_string'
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/resource_collection/resource_set.rb:155:in `each'
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/resource_collection/resource_set.rb:155:in `find_resource_by_string'
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/resource_collection/resource_set.rb:87:in `block in find'
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/resource_collection/resource_set.rb:82:in `each'
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/resource_collection/resource_set.rb:82:in `find'
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/recipe.rb:88:in `resources'
	    from /home/derek/.rvm/gems/ruby-2.2.1/gems/chef-12.1.0/lib/chef/shell/ext.rb:552:in `resources'
	    from (irb#1):22

**Comment by derekjc** [comment]
The only way it works for me is when I define individual package resources separately and then define a multi package resource containing those individual packages.

@jaymzh There must be something I'm missing?

**Comment by jaymzh** [comment]
Yea, if you want to notify you have to give it a string name:

```
package 'my awesome list' do
  package_name ['foo', 'bar']
end
```

so you can notify it. You can't notify an array. We made a note to document this, but dunno if it happened or not.

**Comment by lamont-granquist** [comment]
So I think we could still make this work, but its going to take some changes to the plumbing of the resource_set.  I sort of intended to make it work, but never quite took it over the line and made sure that it did work.  Problem is that the key in the resource_set is `"package[[\"strace\", \"lsof\"]]"` and not `"package[strace, lsof]"`

**Comment by lamont-granquist** [comment]
^ its likely considerably worse than that, I was recently mildly horrified to find that we have a multi-resource notification syntax that looks exactly like the multipackage syntax:

https://github.com/chef/chef/blob/de209e6ee12939f641ec0ed002c2d3506abaafe7/lib/chef/resource_collection/resource_set.rb#L27-L29

**Comment by lamont-granquist** [comment]
9 year old feature dating back to the first commit ever to the resource_collection:

https://github.com/chef/chef/blob/3dd77b260393bae93bb27677e3f8a45f407981c1/lib/chef/resource_collection.rb#L129-L136
