### ISSUE TITLE
chef-server-core on Ubuntu 15.10

### ISSUE THREAD

**Issue by Fjodor42** [chef/chef#4352]
Hiya,

sudo chef-server-ctl reconfigure as per https://learn.chef.io/install-and-manage-your-own-chef-server/linux/install-chef-server/install-chef-server-using-your-hardware/ fails on Ubuntu Wily.

It would seem that chef-private expects /usr/lib/systemd, which, on Wily, is actually placed at /lib/systemd.

Removing /usr/lib/systemd and symlinking it instead to /lib/systemd seems to be going OK - it's generating the dhparams.pem file as I'm writing this.

I don't know this repo well enough to find the relevant recipe/cookbook, but it shoud be straightforward to check if /lib/systemd exists && /usr/lib/systemd does not, and symlink the latter to the former in that case.

Best regards,

F

**Comment by lamont-granquist** [comment]
This repo is for bug against the chef-client, not against the chef-server, this should get refiled against http://github.com/chef/chef-server/issues/new.

**Comment by Fjodor42** [comment]
Thank you - will do
