### ISSUE TITLE
Can the chef-apply retrieves own node object from a chef-server ?

### ISSUE THREAD

**Issue by sawanoboly** [chef/chef#4356]
Hi, I'd like to use node object which saved on the chef-server by the chef-apply.

I know,  download an object by `knife download` before running the chef-apply will resolve this issue. But, I hope to using client.rb to retrieve own node object from server by the chef-apply.

**Comment by lamont-granquist** [comment]
i'm pretty :-1: on turning chef-apply into chef-client.

this sounds like what you want to do is run chef-client with an override run list and to shortcut cookbook synchronization and pick up a cookbook out of a local directory.

and the next path down this road that i can see is going to be adding data bags and search and other client features to chef-apply, and that is just not what chef-apply is for, and chef-client already does all that correctly...

**Comment by coderanger** [comment]
Also :-1: for the same reasons as @lamont-granquist

**Comment by sawanoboly** [comment]
I just need node object.

I know that it's too much bother to do use all resources by chef-apply.
When we need data_bags, existing recipes and other several resources , everyone use chef-client obviously.

**Comment by sawanoboly** [comment]
@lamont-granquist @coderanger 

For example, there is node which was bootstraped with mynode. But it has another real hostname such as myhost.local.

When I'd like to run simple batch by chef-apply for such as test, check on node.

In this case chef-apply uses `myhost.local` instead of `mynode` because chef-apply doesn't load any configuration.

I know how to resolve this difference as below.

1. chef-shell -z -S SERVER_URL
2. put  via `> node.to_json` to node.json
3. chef-apply -j  node.json

or

1. echo '{ "name" : "mynode"}' > node.json
2. chef-apply -j  node.json

My purpose is to be omit this operations.

**Comment by coderanger** [comment]
@sawanoboly The point is that you shouldn't use chef-apply for this at all. You probably want to use chef-client with an override run list.

**Comment by sawanoboly** [comment]
I see. That's reasonable. Thanks.
