### ISSUE TITLE
Ruby 2.3.0 Thread.exclusive deprication warning

### ISSUE THREAD

**Issue by bewatts** [chef/chef#4359]
After upgrading to Ruby 2.3.0, we get the following warning: 

```
Thread.exclusive is deprecated, use Mutex
/Users/pivotal/.gem/ruby/2.3.0/gems/chef-12.6.0/lib/chef/dsl/declare_resource.rb:91:in `build_resource'
/Users/pivotal/.gem/ruby/2.3.0/gems/chef-12.6.0/lib/chef/dsl/declare_resource.rb:62:in `declare_resource'
...
```

Problem comes from: https://github.com/chef/chef/blob/master/lib/chef/dsl/declare_resource.rb#L91

Background: 
https://bugs.ruby-lang.org/issues/11904

Other Fixes to this problem: 
https://github.com/middleman/middleman-livereload/pull/85/files

**Comment by lamont-granquist** [comment]
keep in mind that until omnibus and/or chef-dk ships with 2.3 that we don't support 2.3

we'll have to fix this, but its not a high priority for us right now and the fastest way to fix it would be via opening a PR
