### ISSUE TITLE
Deploy code that's not in SCM

### ISSUE THREAD

**Issue by ameir** [chef/chef#4362]
The `deploy` resource is so close to what I need, except that it appears to require git or svn.  In my environment, I use Jenkins to pull code from git, compile and/or do other magic, and push a tarball to S3.  That tarball is the production-ready code, without the .git directory.

Currently, I'm using `aws_s3_file` to pull the tarball, and an `execute` block to untar it and manage directories, etc.  It works, but it's not as clean as I'd like it to be (hence me wanting to use this resource).

Are there workarounds to working with a local file instead of an SCM repo?

I'd be happy to work on supporting this in whatever spare time I can scrape up, and use the file's hash instead of the SCM commit/revision for the directory name.

I'm also aware of https://github.com/RiotGamesCookbooks/artifact-cookbook, but it does not appear to be maintained.

**Comment by zhelyan** [comment]
+1

**Comment by ameir** [comment]
Closing since updates to `deploy` are not being considered at this time, per #4810.
