### ISSUE TITLE
knife node edit does not save policy_name and policy_group

### ISSUE THREAD

**Issue by scopenco** [chef/chef#4364]
Hello,

```
$ knife -v
Chef: 12.6.0
```

before `knife node edit SERVER`  i see on chef server json 
```json
{
  "name": "SERVER",
  "policy_name": "mypolicy",
  "policy_group": "staging",
  "run_list": [
  "recipe[env-reports::bukanew]"
]
,
  "normal": {
    "policy_name": "reports",
    "policy_group": "staging",
    "tags": [

    ],
```

after `knfe node edit SERVER` i see json on Chef Server:
```json
{
  "name": "SERVER",
  "chef_environment": "_default",
  "run_list": [
  "recipe[env-reports::bukanew]"
]
,
  "normal": {
    "policy_name": "reports",
    "policy_group": "staging",
    "tags": [

    ],
```

knife forсe set chef_environment but should set policy attributes.

**Comment by danielsdeleo** [comment]
What version of Chef Server do you have?

**Comment by scopenco** [comment]
```
# rpm -q chef-server-core
chef-server-core-12.3.1-1.el6.x86_64
```

**Comment by danielsdeleo** [comment]
Okay, I just ran:

```
> knife node edit NODE
```

And I got this message:

```
Node not updated, skipping node save
```

(This is a bug for sure)

Is that what you're seeing, or is there something else?

**Comment by scopenco** [comment]
run `knife node edit NODE` then change some attribute, then save and node will be updated but policy will change to environment

**Comment by danielsdeleo** [comment]
Okay, I see we're doing slightly different things, I suspect that these behaviors have the same root cause, but will confirm when I dive into the code.
