### ISSUE TITLE
Chef v11.18.14 not available for download

### ISSUE THREAD

**Issue by kierenevans** [chef/chef#4366]
Ohai,

Despite https://github.com/chef/chef/pull/3654 releasing 11.18.14 as a security release in July, it is not yet available to download via the downloads page ( https://downloads.chef.io/chef-client/redhat/ ) or the installer script.

We have yet to invest the time to upgrade to v12, so would be grateful for a package upload.

Thanks,
Kieren

**Comment by coderanger** [comment]
I'm not certain that release actually happened. There is a tag in the Chef repo, but I can't find anything in the Omnibus repos for it. Maybe it was built as a one-off? /cc @btm @jaym @thommay

**Comment by thommay** [comment]
I think the right answer here is to probably just do a release tomorrow when the next OpenSSL vuln comes out, and forget that .14 ever happened. Apologies for any confusion.

**Comment by josegonzalez** [comment]
Did you happen to create a release? The gem is no longer available either, and we have yet to investigate moving to chef 12...

**Comment by josegonzalez** [comment]
Friendly :bump:

**Comment by kierenevans** [comment]
@thommay Did the new 11.18.x release happen?
