### ISSUE TITLE
windows_package shouldn't auto-detect product version for .exe installers

### ISSUE THREAD

**Issue by docwhat** [chef/chef#4372]
What happened:

I tried to upgrade a Windows 2012R2 box From Chef 12.5.1 to 12.6.  This caused
java to be attempted to be installed even when already installed.  Java's
installer crashes with an unhelpful error (1603) when this happens.

What I expected:

The "is it already installed?" logic should continue to work.

Details:

I'm using the `java` cookbook, which uses the `windows` cookbook.

The java cookbook is using the `windows_package` resource to install the JDK
executable installer.  I have no idea what kind of installer it is (e.g. inno,
nsis, wise, etc.) but I suspect it is custom.

The `windows` cookbook detects Chef 12.6 and uses the new providers from there.

Unfortunately, the new provider tries to detect the version to-be-installed
from the `.exe`.  This doesn't work with Java's JDK installer because it uses a
different versioning scheme (e.g. The file has product_version '7.0.790.15' but
the uninstall entry has version '1.7.0.790')

I have tried overriding the `version` attribute with `nil` but that doesn't
seem to work.

I feel that it is either a mistake to auto-gather the product version or it
should be off by default and can be turned on in some way.

Debug log from chef run:

```
DEBUG: windows_package[Java SE Development Kit 7 Update 79 (64-bit)] checking package version
DEBUG: Checking if windows_package[Java SE Development Kit 7 Update 79 (64-bit)] version '7.0.790.15' is already installed. ["1.7.0.790"] is currently installed
DEBUG: windows_package[Java SE Development Kit 7 Update 79 (64-bit)] Java SE Development Kit 7 Update 79 (64-bit) ["1.7.0.790"] needs updating to 7.0.790.15
DEBUG: windows_package[Java SE Development Kit 7 Update 79 (64-bit)] installing  package 'c:\chef\cache\jdk-7u79-windows-x64.exe'
```

Resource declaration and compiled resource from error:

```
Resource Declaration:
---------------------
# In C:/chef/cache/cookbooks/java/recipes/windows.rb

 76: windows_package node['java']['windows']['package_name'] do
 77:   source cache_file_path
 78:   checksum node['java']['windows']['checksum']
 79:   action :install
 80:   installer_type :custom
 81:   options "/s #{additional_options}"
 82: end

Compiled Resource:
------------------
# Declared in C:/chef/cache/cookbooks/java/recipes/windows.rb:76:in `from_file'

windows_package("Java SE Development Kit 7 Update 79 (64-bit)") do
  provider Chef::Provider::Package::Windows
  action [:install]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :windows_package
  cookbook_name "java"
  recipe_name "windows"
  source "C:\\chef\\cache/jdk-7u79-windows-x64.exe"
  options "/s /v\"/qn INSTALLDIR=\\\"C:\\Program Files\\Java7\\\"\""
  installer_type :custom
  version "7.0.790.15"
  package_name "Java SE Development Kit 7 Update 79 (64-bit)"
  checksum "80b1452c808691dc63945926c52156c8afe7ebcfa3747093fd296f0a3f1cfbcc"
  success_codes [0, 42, 127]
end
```

**Comment by coderanger** [comment]
Ping @chef/client-windows

**Comment by mwrock** [comment]
I think @docwhat is correct here. One thing the auto detection was trying to solve was the "multiple package" scenario. There are scenarios where one wants to install multiple versions of the same package and it would be nice to auto detect the versions if possible. However as can be seen in the above java example, the embedded version is simply not reliable for use in this manner. It is better for package resource consumers to explicitly state the expected version for those scenarios.

**Comment by docwhat** [comment]
How about adding a way to "turn on" using the package version for those installers that *do* have a sane product version?

Example:

```
windows_package 'foobar.exe' do
  ...
  version :use_package
end
```

Just make sure you reject any symbols that *aren't* `:use_package`.

You can extend this to the other providers as well, with (for example) the `.msi` provider having `:use_package` by default.

**Comment by mwrock** [comment]
I just no longer see the value of the auto detection (bummer - spent nearly a day to get the ffi stuff all lined up right :)) and I think keeping it just convolutes the code. But if anyone thinks it makes sense, I'm totally open.

**Comment by docwhat** [comment]
It's always hard to nuke clever code.  My English writing teacher used to say when you write a paper, find your favorite paragraph and remove it.  It applies to coding, too. *sigh*

**Comment by mwrock** [comment]
:)
