### ISSUE TITLE
Dynamic nodes

### ISSUE THREAD

**Issue by Fodoj** [chef/chef#4391]
The problem I can see for Chef (or actually other similar tools like Puppet) in cloud environment is the lack of dynamic node registration\de-registration. Basically if machine is gone, then chef server has no idea it's gone and we have a stale node than with no means to do anything about it.

I was thinking lately that something like Consul or other service discovery tool would be great to be a core feature of Chef - so unhealthy nodes are removed automatically, for example.

I wonder if there was a discussion about this already - I couldn't find one, so may be I am thinking in a wrong direction. But basically I have a feeling that SCM like chef currently is not really ready for environment when dozens of nodes constantly come and go. 

What are your thoughts\plans on this issue?

**Comment by lamont-granquist** [comment]
This is a bug tracker, questions like that would be better asked on IRC or proposed as an RFC on the http://github.com/chef/chef-rfc repo
