### ISSUE TITLE
Data bags item no longer support "name" key

### ISSUE THREAD

**Issue by arr-dev** [chef/chef#4392]
Chef version: 12.6.0

Data bags no longer support `name` key. 
This worked on version 12.4.3 
~~and seems to be caused by this commit d99e306a41b1402209d320cb7119b12a3bbb962f,  specifically this change https://github.com/chef/chef/commit/d99e306a41b1402209d320cb7119b12a3bbb962f#diff-143e680ed6057de0f7066c7b539a7d28R131~~
edit, not true, see thommay's comment

This is a sample of data bag that worked in 12.4.3 and doesn't work with 12.6.0

```
{
  "id": "app_staging",
  "name": "app_staging",
  "environment_name": "staging",
...
}
```

With 12.4.3, `data_bag_item("deploy_setup", "app_staging")['name']` returned `app_staging`, 
but now it returns `nil`

**Comment by thommay** [comment]
hi @arr-dev,
that commit isn't in 12.6, so there must be something else going on. I'm surprised that this ever worked, but I'll need to look further.

**Comment by coderanger** [comment]
The code in `knife data bag from file` seems to handle this correctly, maybe something in ChefFS?

**Comment by arr-dev** [comment]
@thommay you are right, it's not caused by this.
btw, I am using `chef-solo` if that has anything to do with it.
I've tried from irb, with `Chef::DataBagItem.load` and it behaves the same.

**Comment by thommay** [comment]
@arr-dev "it behaves the same" - it displays the bug, or it works?

**Comment by arr-dev** [comment]
Sorry, should have been clearer, it works on 12.4 and doesn't work on 12.6.

**Comment by lamont-granquist** [comment]
I have no idea what broke, but I replicated it...

works:

```ruby
Starting Chef Client, version 12.4.3
resolving cookbooks for run list: ["test"]
Synchronizing Cookbooks:
  - test
Compiling Cookbooks...
OBJECT:
{"data_bag_item('foo', 'bar')"=>
  {"id"=>"bar",
   "name"=>"bar",
   "test"=>"junk",
   "chef_type"=>"data_bag_item",
   "data_bag"=>"foo"}}
NAME:
"bar"
Converging 0 resources

Running handlers:
Running handlers complete
Chef Client finished, 0/0 resources updated in 2.429475 seconds
```

fails:

```
Starting Chef Client, version 12.6.0
resolving cookbooks for run list: ["test"]
Synchronizing Cookbooks:
  - test (0.0.1)
Compiling Cookbooks...
OBJECT:
{"data_bag_item('foo', 'bar')"=>
  {"id"=>"bar",
   "test"=>"junk",
   "chef_type"=>"data_bag_item",
   "data_bag"=>"foo"}}
NAME:
nil
Converging 0 resources

Running handlers:
Running handlers complete
Chef Client finished, 0/0 resources updated in 03 seconds
```

**Comment by e100** [comment]
I have a similar problem using chef-client.

Encrypted data bag with a "name" attribute stored in Chef server.

With chef-client 12.6.0 it works fine.
With 12.7.2 accessing name from within a recipe returns nil

**Comment by lamont-granquist** [comment]
@e100 this bug clearly broke in 12.6.0 not 12.7.2, do you have a different bug to report or did you get a version wrong?

**Comment by e100** [comment]
I got the versions right, this might be a different but related bug.

Using the following code with chef-client:
```
bag = data_bag_item("encrypted","item")
puts "OBJECT:"
puts bag.inspect
puts "ID:"
puts bag["id"].inspect
puts "NAME:"
puts bag["name"].inspect
```


In 12.6.0 it works as expected:
```
OBJECT:
#<Chef::EncryptedDataBagItem...Redacted>
ID:
"item"
NAME:
"item"
```
In 12.7.2 "name" is always nil:
```
OBJECT:
#<Chef::EncryptedDataBagItem...Redacted>
ID:
"item"
NAME:
nil
```

**Comment by chefsalim** [comment]
Not sure what is going on in 12.6.0...however this does also repro for me with the latest chef, and commenting out the name deletion that was added in the above mention commit causes the script to work as expected.

    def self.from_hash(h)
      h.delete("chef_type")
      h.delete("json_class")
#     h.delete("name")
