### ISSUE TITLE
Fix API for Service Resource "priority" property

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#4394]
To do start and stop in the same rc level you would have to do this:

``` ruby
 {2 => [:start, ''], 2 => [:stop, '']}
```

But that is a duplicated key and all that you'll get is stop in runlevel 2 out of that.

Data structure probably needs to be changed to something more like:

```
[
  {
    run_level: 2,
    action:  :start,
    priority:  80,
  },
  {
    run_level: 2,
    action:  :stop,
    priority:  20,
  },
]
```

Will probably be a breaking change (although maybe we could switch on getting Array vs Hash)

**Comment by lamont-granquist** [comment]
discovered via #4393

**Comment by lamont-granquist** [comment]
I think we can do this in a minor rev by introducing an Array form like above and then just coercing the Hash form into the Array form.  The Hash form will still be broken if there's duplicated keys, but its actually somewhat uncommon to setup start and stop in the same level (although for '50' it would conventionally be the same on both sides, but the integer form of this argument already gets that correct).

**Comment by Shubhrmcf07** [comment]
Is this resolved? If not, I would like to take it up.

**Comment by lamont-granquist** [comment]
still buggy.  feel free.

**Comment by Shubhrmcf07** [comment]
Can I know a bit more?
