### ISSUE TITLE
Windows securable resources should support SIDs

### ISSUE THREAD

**Issue by smurawski** [chef/chef#4397]
We should support supplying the SID for users and groups for user resource, group resource, and any windows securables.

**Comment by drmmarsunited** [comment]
Hey folks!

Just wondering if this is going to get prioritized soon.  I've just started a new project with Chef that deals with multiple base language versions of Windows, so the ability to target rights via SID is the way I would like to go.

Thanks for all your awesome efforts!

**Comment by eedwardsdisco** [comment]
+1

Windows DSC supports using SIDs, would be nice to have parity since due to issues with dsc_resource and dsc_script I'm forced to use the directory resource.

**Comment by jugatsu** [comment]
https://github.com/chef/chef/issues/5981

**Comment by ISHBAR** [comment]
Checking in on this, (I'm open to other options out there), currently trying to set permissions for some ohai plugins

e.g. `rights :full_control, 'Administrators'` and getting 

`Chef::Exceptions::Win32APIError: No mapping between account names and security IDs was done.`

This is whenever 'Administrators' / Authenticated Users is in another language, i.e. 
_Usuários autenticados_. This would be a lot more universal with SIDs instead.
