### ISSUE TITLE
incorrect cookbook README is shown at supermarket site 

### ISSUE THREAD

**Issue by melezhik** [chef/chef#4404]
Hi guys!

I have just uploaded a several versions of sparrow cookbook at supermarket. Everything fine. But cookbook's README file is substituted by one placed at https://github.com/melezhik/sparrow/blob/master/README.md which is wrong, because cookbook's real REAME file is shipped by coobook and has another content. Thanks in advance for your help. 

https://supermarket.chef.io/cookbooks/sparrow

If it helps sparrow cookbooks source code is here - https://github.com/melezhik/sparrow-cookbook with README at  https://github.com/melezhik/sparrow-cookbook/blob/master/README.md

**Comment by melezhik** [comment]
Hi ! Any news here?

**Comment by thommay** [comment]
Hi, this is for bugs in the chef-client. I'd recommend you file this issue with supermarket, at https://github.com/chef/supermarket .

**Comment by melezhik** [comment]
Thanks @thommay  will do this

**Comment by melezhik** [comment]
FYI - https://github.com/chef/supermarket/issues/1204
