### ISSUE TITLE
Normal attributes creation during first chef-client

### ISSUE THREAD

**Issue by n4rk0o** [chef/chef#4437]
I need to use normal attributes in a cookbook during the first chef-client (node creation).
The cookbook is using the node attributes to interact with Chef (data_bag usage).

I created a json with normal attributes with a run_list:

{
 "my_normal_attribute": "123456",
  "run_list": [ 
    "recipe[my_lib::default]"
  ]
}

So, the recipe "my_lib::defaut" interract with Chef and need to load the attribute "my_normal" from Chef::Node.load(@node) class.

Unfortunately, with chef-client -j "my_json_file" I got an error and the attributes are never created.
I think that chef will compile the cookbook and execute it before the normal attribute creation. So I need to  that normal attribute must be created before any cookbook compilation an run.

PS: Sorry for my english :smile: 

Regards

**Comment by lamont-granquist** [comment]
Normal attributes are loaded before anything else, so chef already behaves the way that you want it to behave.  I can't determine from your description what you are doing incorrectly.

**Comment by n4rk0o** [comment]
The library created is inside a cookbook named "libraries". This librarie have a definition named "get_normal_attrib_value" who get the normal attributes.

I call this definition inside another cookbook to compare the value of a specific attribute with the normal attribute.

The problem is that when I run the first chef-client with a json file, it should create normal attributes and add the cookbook "libraries" on the top and another cookbooks next.

The normal attributes are never added to the chef Node and my library can't load the normal attributes because they don't exist yet.

You said that the normal attributes are created before any cookbook compilation. The library that I created load the Node attributes during the call of the definition "get_normal_attrib_value" and the normal attributes are "nil" value.

At the end of the library I use:
Chef::Recipe.send(:include, my_module::my_sub_module)

Maybe I forgot something but I don't know what :disappointed: 

Regards

**Comment by lamont-granquist** [comment]
Since you've included your module in Chef::Recipe you should be able to access node objects via just `node["my_normal_attribute"]`.

I'm not sure why you included `Chef::Node.load(@node)`, but if your library is doing something like that, just delete it.
