### ISSUE TITLE
Chef nightlies confusing hash with a block

### ISSUE THREAD

**Issue by tas50** [chef/chef#4440]
I ran into this chunk of code that runs fine in 12.6.0 that is now failing on a nightly of ChefDK / chef-client in Travis:

```text
================================================================================
Recipe Compile Error in /tmp/d20160119-2256-ez7lg1/cookbooks/aws/recipes/ec2_hints.rb
================================================================================
RuntimeError
------------
Property content of file[/etc/chef/ohai/hints/ec2.json] cannot be passed a block! If you meant to create a resource named content instead, you'll need to first rename the property.
Cookbook Trace:
---------------
  /tmp/d20160119-2256-ez7lg1/cookbooks/aws/recipes/ec2_hints.rb:26:in `block in from_file'
  /tmp/d20160119-2256-ez7lg1/cookbooks/aws/recipes/ec2_hints.rb:25:in `from_file'
Relevant File Content:
----------------------
/tmp/d20160119-2256-ez7lg1/cookbooks/aws/recipes/ec2_hints.rb:
 19:  
 20:  directory '/etc/chef/ohai/hints' do
 21:    recursive true
 22:    action :create
 23:  end.run_action(:create)
 24:  
 25:  file '/etc/chef/ohai/hints/ec2.json' do
 26>>   content {}
 27:    action :create
 28:  end.run_action(:create)
 29:  
 30:  ohai 'reload' do
 31:    action :reload
 32:  end.run_action(:reload)
 33:  
F
================================================================================
Recipe Compile Error in /tmp/d20160119-2256-ez7lg1/cookbooks/aws/recipes/ec2_hints.rb
================================================================================
RuntimeError
------------
Property content of file[/etc/chef/ohai/hints/ec2.json] cannot be passed a block! If you meant to create a resource named content instead, you'll need to first rename the property.
Cookbook Trace:
---------------
  /tmp/d20160119-2256-ez7lg1/cookbooks/aws/recipes/ec2_hints.rb:26:in `block in from_file'
  /tmp/d20160119-2256-ez7lg1/cookbooks/aws/recipes/ec2_hints.rb:25:in `from_file'
Relevant File Content:
----------------------
/tmp/d20160119-2256-ez7lg1/cookbooks/aws/recipes/ec2_hints.rb:
 19:  
 20:  directory '/etc/chef/ohai/hints' do
 21:    recursive true
 22:    action :create
 23:  end.run_action(:create)
 24:  
 25:  file '/etc/chef/ohai/hints/ec2.json' do
 26>>   content {}
 27:    action :create
 28:  end.run_action(:create)
 29:  
 30:  ohai 'reload' do
 31:    action :reload
 32:  end.run_action(:reload)
 33:  
F
================================================================================
Recipe Compile Error in /tmp/d20160119-2256-ez7lg1/cookbooks/aws/recipes/ec2_hints.rb
================================================================================
RuntimeError
------------
Property content of file[/etc/chef/ohai/hints/ec2.json] cannot be passed a block! If you meant to create a resource named content instead, you'll need to first rename the property.
Cookbook Trace:
---------------
  /tmp/d20160119-2256-ez7lg1/cookbooks/aws/recipes/ec2_hints.rb:26:in `block in from_file'
  /tmp/d20160119-2256-ez7lg1/cookbooks/aws/recipes/ec2_hints.rb:25:in `from_file'
Relevant File Content:
----------------------
/tmp/d20160119-2256-ez7lg1/cookbooks/aws/recipes/ec2_hints.rb:
```

**Comment by coderanger** [comment]
That's a Ruby syntax thing. The code in the cookbook is incorrect. The way to pass an empty hash to a method is either `content({})` or `content Hash.new`.

**Comment by coderanger** [comment]
(to be clear, it was only working by accident before)

**Comment by tas50** [comment]
The code has been fixed already. I was just calling attention to a behavior change in our nightlies.

**Comment by coderanger** [comment]
@jkeiser ^^

I think that was the intention though, it's a correctness fix not a compat break.

**Comment by lamont-granquist** [comment]
Yeah, the only thing that worries me here is if we potentially broke properties that really do take a block, but assuming we didn't, then this is just correct behavior.

I'm a bit worried this could turn into another rathole where "we broke cookbooks that worked yesterday" but this example is a pretty good one of how perverse a "working" cookbook can be.  The content property of the file resource only takes a String.  Whoever tried to pass in a Hash was having a pretty large brainfart of some sort on that day.  The fact that ruby translated that into a block, and then we silently accepted it and then it "worked" is just a chain of 'happy' accidents that let this cookbook compile.

Its unfortunate that this kind of code breaks, but at some point we have to be able to break bad ruby/chef code without violating semver since that isn't part of our public API.

**Comment by coderanger** [comment]
@lamont-granquist There is no way to take a block with Chef's implementation of `property()`. It requires custom extensions where you can also override that error :)

**Comment by lamont-granquist** [comment]
Yeah, I was worried that we broke passing blocks, but I see now that we never accepted blocks in properties and you have to use `proc {}` to pass a property a callback, and it has always been this way for properties.

I also see that via some kind of magic we didn't break /attributes/ in the process and that the callbacks for the deploy resource still take blocks fine.

So I think we can close this...   @jkeiser is noodling over making properties take blocks correctly...
