### ISSUE TITLE
homebrew package provider doesn't support multipackage

### ISSUE THREAD

**Issue by tas50** [chef/chef#4441]
The homebrew provider should support arrays of packages as we support in our other providers

**Comment by lamont-granquist** [comment]
i'm burned out on writing multipackage providers and package providers in general.  the next thing i touch on package providers will likely be pulling DNF into core and multipackaging that.  if anyone wants to tackle this, they should look at the chocolatey or zypper providers for inspiration (and not the yum/apt providers which need cleanup...).
