### ISSUE TITLE
(windows) powershell_out! not raising errors

### ISSUE THREAD

**Issue by nhudacin** [chef/chef#4443]
Hello, 

Looking at the comments for [powershell_out!](https://github.com/chef/chef/blob/master/lib/chef/mixin/powershell_out.rb) on line 41 at the time of this writing, it says `# (raises exceptions on errors)` which I don't believe is happening. 

I have some powershell code here that has been "silently failing". I know how to fix my powershell code, it's obviously wrong.. BUT because there was no exception, it was not obvious what the issue was while troubleshooting. 

If I run shell_out! the command will raise the appropriate exception of course for a totally different reason as powershell syntax is not valid in a windows shell.

``` ruby
## This will change the server's authentication mode to mixed (if not already) and set the sa_pwd
      def set_server_login_mode
        begin
          cmd_str = <<-EOH
            # Required parameters
            $instance = '#{instance}'
            $sa_pwd = '#{new_resource.sa_pwd}'

            try {
                # Make sure the sql server powershell modules are available on the path
                if (-not $env:PSModulePath.Replace('\','/').Split(';') -contains 'C:/Program Files (x86)/Microsoft SQL Server/110/Tools/PowerShell/Modules/') {
                    $env:PSModulePath = [System.Environment]::GetEnvironmentVariable('PSModulePath',"Machine")
                }

                # If the sqlps module is not available in this session, import it
                if ((Get-Module -ListAvailable | Where-Object { $_.Name -eq 'sqlps' }).Count -eq 0) {
                    $currentLocation = (Get-Location).Path
                    Import-Module "sqlps" -DisableNameChecking
                    Set-Location $currentLocation
                }

                # If $instance = MSSQLSERVER change it to computername
                if ($instance -eq 'MSSQLSERVER') { $instance = $env:COMPUTERNAME }
                else { $instance = "$env:COMPUTERNAME\$instance" }

                # Connect to the instance using SMO
                $server = New-Object ('Microsoft.SqlServer.Management.Smo.Server') $instance

                # If not mixed, set it
                if ($server.Settings.LoginMode -ne 'Mixed') {
                    $server.Settings.LoginMode = [Microsoft.SqlServer.Management.SMO.ServerLoginMode]::Mixed
                    $server.Alter()

                    # Services need to be restarted
                    Restart-Service MSSQLSERVER -Force

                    # Need to enable and set the sa pwd
                    Invoke-Sqlcmd -Query 'ALTER LOGIN sa ENABLE;' -Database 'master'
                    Invoke-Sqlcmd -Query "ALTER LOGIN sa WITH PASSWORD= '$sa_pwd';" -Database 'master'
                }
            }
            catch { throw }
          EOH

          Chef::Log.info(cmd_str)
          cmd = powershell_out!(cmd_str)

          Chef::Log.info(cmd.stdout)
          Chef::Log.info(cmd.stderr)
        rescue Mixlib::ShellOut::ShellCommandFailed
          raise
        end
        Chef::Log.info("#{instance} login mode changed successfully!")
      end
```

Here's the output from test-kitchen (no failures, no info lines reported)... 

```
-----> Converging <prod-windows>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <prod-windows>
       Starting Chef Client, version 12.4.1
       [2016-01-21T09:07:36-06:00] WARN: Child with name 'dna.json' found in multiple directories: C:/Users/ENGINE~1/AppData/Local/Temp/kitchen/dna.json and C:/Users/ENGINE~1/AppDat
a/Local/Temp/kitchen/dna.json
       resolving cookbooks for run list: ["integration::standard_prod_instance"]
       Synchronizing Cookbooks:
         - dotnet
         - windows
         - seven_zip
         - chef_handler
         - integration
         - sqlserver
       Compiling Cookbooks...
       Converging 2 resources
       Recipe: dotnet::dotnet-3.5
        (up to date)
       Recipe: integration::standard_prod_instance
         * sqlserver_instance[MSSQLSERVER] action configure[2016-01-21T09:07:38-06:00] WARN: Should have run the server login mode
       [2016-01-21T09:07:38-06:00] WARN: Just to prove this is working
        (up to date)

       Running handlers:
       Running handlers complete
       Chef Client finished, 0/2 resources updated in 18.750515 seconds
       Finished converging <prod-windows> (1m4.97s).
-----> Kitchen is finished. (1m18.97s)
```

When I RDP into the box and run chef-client in debug mode (screen shot because the text output is NOT showing up nicely in the issue!): 

![image](https://cloud.githubusercontent.com/assets/6682884/12485326/e734adde-c023-11e5-9ad1-af42dab5a473.png)

**Comment by nhudacin** [comment]
This is related to the way PowerShell exits when hitting the [_ParserError_](https://octopus.com/blog/powershell-exit-codes). I understand the reason for not determining the exit code on the error stream per the article, though I do not agree. 

Regardless, I'm not sure if there's a way to check for a ParserError and raise an exception in Chef.  I'm pretty sure this will have to be fixed in my script(s).

**Comment by smurawski** [comment]
Do you need the output in your chef run? `powershell_script` does a syntax validation and will error on parse failures.

**Comment by nhudacin** [comment]
True. If I use powershell_script, does that add to the resource collection? I'm trying to get it so that a SQL Server instance is the managed Chef resource and not the 12 other items I need in order to get the instance installed and configured. 

In this example, the powershell script is only setting the authentication mode. This will happen exactly once during the setup and I won't need to manage it going forward.

**Comment by smurawski** [comment]
@nhudacin If it's in a recipe, it'd be part of the resource collection.  If it's in an LWRP or a custom resource, then it'd be in a sub-context.

I don't quite get how you would do it otherwise... if it's part of a recipe that's in a run list, it's going to get executed or checked every time it runs unless you have the proper guards in place.  Resources just give you a formal way to guard the execution so that it only happens when necessary.  Whether that's a conditional inclusion of a recipe (like `include_recipe 'sql_server::setup' only_if need_sql_server?`) or in a custom resource, you'll need to have some logic determine if you need to run the script again.

**Comment by nhudacin** [comment]
And that's what I'm trying to avoid.. This is just a configuration script to run after a sql server instance install. I only want to run it once after the sql server install is completed.... Think of it as an extension to the base sql server install. 

That powershell script is only being run once currently (after I fixed the syntax issue) and I don't ever want it to run again. 

My concern with changing that script from powershell_out! to powershell_script was that it would get added to the node's resource collection and I don't want that to happen. Lol then again, I could just be using Chef incorrectly (wouldn't be the first time) ;)

**Comment by smurawski** [comment]
@nhudacin to get the effect of "run once after an install" you could use a `powershell_script` resource with an action of `:nothing:` then use a notification from the resources that do the install of the sql server to run it only after the install.  It'd never run unless the sql install ran, which I think meets your requirements.
