### ISSUE TITLE
knife ap-northeast-2 support

### ISSUE THREAD

**Issue by gyoza** [chef/chef#4452]
Am I missing something or does knife not support ap-northeast-2 yet? I do not see any tickets referencing it. 

$ knife -v
Chef: 12.5.1

**Comment by lamont-granquist** [comment]
so, knife doesn't talk to ec2 at all, so this is misfiled and should go under http://github.com/chef/knife-ec2, but also that support comes from the underlying fog-ec2 library where 'ap-northeast-2' is listed here:

https://github.com/fog/fog-aws/blob/bcfa68c0eadff299b760f0d74ea3007d4298c127/lib/fog/aws.rb#L227
