### ISSUE TITLE
remote_file should use Content-MD5 header if available

### ISSUE THREAD

**Issue by docwhat** [chef/chef#4456]
If a URL has the `Content-MD5` header when a `HEAD` request is sent, it should be used by `remote_file` if the `checksum` attribute isn't set.

[rfc2616 Content-MD5 docs](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.15)

Example of a `HEAD` request:

```
$ curl -I http://download.sysinternals.com/files/bginfo.zip
HTTP/1.1 200 OK
Accept-Ranges: bytes
Content-MD5: QmsDlpevg1tt+YZI8Rz5KA==
Content-Type: application/x-zip-compressed
Date: Mon, 25 Jan 2016 16:58:38 GMT
Etag: 0x8D31CA686B02A28
Last-Modified: Thu, 14 Jan 2016 05:49:53 GMT
Server: ECAcc (lga/134E)
X-Cache: HIT
x-ms-blob-type: BlockBlob
x-ms-lease-status: unlocked
x-ms-meta-CbModifiedTime: Thu, 01 Aug 2013 20:25:53 GMT
x-ms-request-id: 098550c5-0001-002e-2d91-57e753000000
x-ms-version: 2009-09-19
Content-Length: 984141
Connection: Keep-Alive
```

**Comment by lamont-granquist** [comment]
should this just go into http middleware for everything, similar to the content length validation?

**Comment by docwhat** [comment]
Sounds reasonable.  Once upon a time (2000-ish?) there was some CMS software that implemented this incorrectly.  But hopefully nobody does any more.
