### ISSUE TITLE
"package" resource class should support '-force' whenever underlying package manager implementation does.

### ISSUE THREAD

**Issue by DarwinJS** [chef/chef#4462]
Although I am using chocolatey as an example - my intent is to indicate this as a valid need for all package managers natively supported by chef (that also support some type of force to override any built in idempotence or for which idempotence has been implemented within the chef provider code).  (I understand via Matt Wrock that Chocolatey is planned to be natively supported).

I would like to be able to do checks on _sub-parts_ of a package and trigger a re-install of the package if any of those parts are found to be broken.

Using chocolatey as an example, I currenly must resort to calling the package manager as an executable resource to work around the fact I cannot set "force" as an attribute on a chocolatey resource item.

Here is the work around:

```
execute 'install_googlechrome' do
  command 'choco install googlechrome -force -confirm'
  not_if {::File.exist?("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe") && registry_key_exists?('HKEY_LOCAL_MACHINE\\SOFTWARE\\Classes\\CLSID\\{5C65F4B0-3651-4514-B207-D10CB699B14B}\\LocalServer32') && registry_value_exists?('HKEY_LOCAL_MACHINE\\SOFTWARE\\Classes\\CLSID\\{5C65F4B0-3651-4514-B207-D10CB699B14B}\\LocalServer32', { name: '', type: :string, data: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\47.0.2526.111\\delegate_execute.exe'})}
end
```

Here is what native resource support would look like if it exists (new stuff surround by "**"):

```
chocolatey 'googlechrome' do
  **installoption: force**
  action :nothing
end
```

I would then setup my checks to notify the above resource.

**Comment by coderanger** [comment]
The package resource has an `options` property which gets passed as CLI arguments to most providers. Is that insufficient?

**Comment by DarwinJS** [comment]
I know for the *current* community implementation of the Chocolatey provider, the ruby code is not dropping through to the chocolatey code because it does it's own "package installed" check and then returns true - so if I pass force in options - it never get's to the actual chocolatey code because the ruby implementation layer pre-empts running chocolatey when it does it's own check.

In this request I am asking that [a] the future chocolatey implementation would support '-force', [b] that it be taken as a design principle that Chef provided *package providers should rely on the provider code for idempotency check where they already exist and not code it into the ruby implementation when new ones are added, [c] that Chef created *package providers should not impede any existing -force parameters for underlying provider code and that [d] the current providers are audited for what they *actually* do in regard to a,b and c - not to wait for someone who has interest and time in each individual *package provider to push through a similar Issue.

So I am hoping this request would trigger a review of the current state of the providers and audit them for this functionality and for consistency.

My request is for the "architecture" stuff that pure, user story driven agile isn't really very good at ;) (in this case "consistent implementation design audit of things in the same class") 

The audit for consistency aspect of this request is made more important by the chef documentation assertion "While it is possible to use each of these specific resources, it is recommended to use the package resource as often as possible." made here: https://docs.chef.io/resource_package.html
D.

**Comment by lamont-granquist** [comment]
So if you bypass the idempotency checks then your package resource will not be idempotent and will force reinstall on every run.  At some point you're going to have to include your own idempotency checks and you might as well:

```ruby
unless ::File.exist?("C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe") && registry_key_exists?('HKEY_LOCAL_MACHINE\\SOFTWARE\\Classes\\CLSID\\{5C65F4B0-3651-4514-B207-D10CB699B14B}\\LocalServer32') && registry_value_exists?('HKEY_LOCAL_MACHINE\\SOFTWARE\\Classes\\CLSID\\{5C65F4B0-3651-4514-B207-D10CB699B14B}\\LocalServer32', { name: '', type: :string, data: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\47.0.2526.111\\delegate_execute.exe'})
  chocolatey_package "googlechrome" do
    action [ :uninstall, :install ]
  end
end
```

Adding force is maybe a little bit more elegant, but you can't get around the need to write that awful manual idempotency check.   However, we need to multipackage the rest of the package providers (homebrew already has an outstanding issue for this), we need a multipackage DNF provider in core, we need to cleanup the implementation of the yum and apt providers, and there's probably a ton of other bugs which this will get triaged down below.  I don't see this happening any time soon other than with user contributed code.

**Comment by DarwinJS** [comment]
@lamont-granquist - I did include my own checks in the guard.

What I am driving to is drift management that says **"hey, if these couple of key resources are missing, why mess around - slam the whole package on there because other stuff could be broken too"**

Idempotence at the "package manager says it's all good" level a little too optimistic for me.

It's an opportunistic approach to drift management stolen from Windows Installer.  But Windows Installer would reinstall an entire "Feature" - an internal subdivision of the package that was sometimes smaller than the entire package.

I don't plan to implement it on everything, but want the flexibility to do so.

I have a quick question about your excellent code snippet.  I am new to chef and have been seeing some content on the web indicating that enclosing ruby if logic is not equivalent to guards and can lead to problems in some circumstances.  Can you help me understand if there is any advantage to my structure as a guard versus your structure as an if statement?

Thanks,
D.

**Comment by lamont-granquist** [comment]
The biggest difference is that the resources aren't going to get created at all on the resource collection so you can't ever notify them.  If you include a guard then the guard also guards against notifications though, which might not be what you want in that circumstance either.  I find it very 50/50, but there's an FC rule that suggests everyone should use guards in that circumstance.

And as far as I can tell that code snippet solves the problem you are trying to solve.  I understand that problem extremely well (in a prior life I did configuration management at the scale of 30,000 servers with CFEngine 2, before puppet existed) and don't really need it explained to me.  Its also expensive to do, and requires a definition inside of the package manager that can be verified by the package manager, and some cooperation between CM software like Chef and the package manager in case post-installation tweaking needs to happen to files/perms/keys.  And the priority of doing any of that is beyond low right now.  All of the rest of the issues with package resources compete with your request, all of the rest of the bugs in chef-client compete with it, all the bugs in test-kitchen and our other open source software compete with it, and all the rest of our business priorities compete with it.  And I just gave you a workaround which accomplishes the best we can do right now without much better designed support from chocolatey itself.

**Comment by DarwinJS** [comment]
Thanks for your comments @lamont-granquist.  I'm not really driving for this to be a high priority - more just interested to get a first base level of functionality on the wish list.

As a side note there is a preference on my part for favoring a provider's underlying "-force" (if one exists) versus uninstall followed by install.

The reason is that if I have authored the underling package, I can make the internals of the package efficient for a forced reinstall - so potentially a lot lower overhead than a full uninstall and reinstall.

Thanks.

**Comment by lamont-granquist** [comment]
This is asking to fundamentally break the idempotency model in Chef resources.

This is a case where using an execute resource to run every time is the correct solution for the end user.  Please use that solution.

We could add a "force" option consistently across all package providers to bypass idempotency checks -- but the priority of this is low enough that I'm certainly not implementing it in the next year or two, and we need to clean up the existing Chef::Provider::Package nightmare before plugging any new functionality on top of that.  So closing this.

**Comment by DarwinJS** [comment]
@lamont-granquist - yes I am using an execute resource and actually have it checking key resources within the package so that if they go sideways it can be fixed.

A universal force would be nice as then these health checks could use standard chef resources rather than also have to ensure the package manager is installed and other things that the standard resource sometimes have built-in.

Thanks.
