### ISSUE TITLE
Bug in chef making knife supermarket share

### ISSUE THREAD

**Issue by jcalonsoh** [chef/chef#4485]
### Version:
client: chef 12.5.1, plugin: gem knife-supermarket -v 0.2.1, server: supermarket-2.1.0~alpha.0-1.el6.x86_64

### Environment: 
cookbooks metadata.json

### Scenario:
knife supermarket share build-essential 

### Steps to Reproduce:
when supermarket-server have not suggested cookbook in its repo inside metadata.json of the cookbook that its being uploaded

### Expected Result:
knife supermarket share build-essential
Making tarball build-essential.tgz
Upload complete!

### Actual Result:
knife supermarket share build-essential -VVV
ERROR: knife encountered an unexpected error
This may be a bug in the 'supermarket share' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NameError: undefined local variable or method `method_name' for Chef::Cookbook::Metadata:Class

### Comment:
https://github.com/chef/chef/blob/852e9141fc03fd4eba021818fead406cad368183/lib/chef/cookbook/metadata.rb
methods:
validate_version_constraint 
I think its not working properly

**Comment by lamont-granquist** [comment]
dup of #3888
