### ISSUE TITLE
Debian service provider always updates action :enable due to an error in get_priority

### ISSUE THREAD

**Issue by axos88** [chef/chef#4486]
It seems like the debian service provider's get_priority function is broken.

For the case when 0,1,6 runlevels are at priority 20, action stop, and 2,3,4,5 are at priority 80, action start, it should simplify and yield a priority of fixnum 80, yet it doesn't.

Also may want to change line https://github.com/chef/chef/blob/master/lib/chef/provider/service/debian.rb#L125 to be able to compare hash and fixnum priority definitions in a way that the comparison between 
`{"0"=>[:stop, "10"], "1"=>[:stop, "10"], "2"=>[:start, "90"], "3"=>[:start, "90"], "4"=>[:start, "90"], "5"=>[:start, "90"], "6"=>[:stop, "10"]}` and `90` to yield true.

I may or may not have time to submit an actual PR to fix this (I just spent waay more time on tracking this down than should have), so feel free to hijack it if you can dedicate the time needed.

**Comment by tas50** [comment]
I'm going to close this out since we've refactored  bit of this code and systemd has eaten the world and made legacy init systems less important to track down at this point.
