### ISSUE TITLE
What do we do about scope confusion in 12.5-style resources?

### ISSUE THREAD

**Issue by coderanger** [chef/chef#4525]
An example from a user on IRC:

``` ruby
  property :quantity, kind_of: Fixnum, default: 0

  action :create do
    do_stuff()
  end

  def do_stuff
    puts new_resource.quantity # FAIL! no such method called `new_resource'

    service 'blah' do # FAIL! cannot find resource called `service'
      action :nothing
    end
  end
```

This keeps coming up, we need to do something about it but I have no idea what.

**Comment by coderanger** [comment]
Ping @jkeiser @lamont-granquist @thommay

**Comment by lamont-granquist** [comment]
have to do this for now at least:

```ruby
action_class.class_eval do
  def do_stuff
  end
end
```

instead of having the DSL in the context of the resource and proxying methods like action (which seems to be what we're doing?) could we invert that and open it up in the action_class context and proxy back to the resource?

**Comment by coderanger** [comment]
In 12.6 you can at least cut that down to

``ruby
action_class do
  def do_stuff
  end
end
```

But that is super non-obvious or as Adam would say "not delightful".

**Comment by lamont-granquist** [comment]
So pulling the DSL and the rest of the action_class/provider namespace into the resource seems like a bad idea.  We've already got so many namespace collisions going on.  We probably need less, and I think more is going to be even more confusing...

**Comment by lamont-granquist** [comment]
could change the syntax:

```ruby
 property :quantity, kind_of: Fixnum, default: 0

  action :create do
    do_stuff()
  end

  helper :do_stuff do
    puts new_resource.quantity # FAIL! no such method called `new_resource'

    service 'blah' do # FAIL! cannot find resource called `service'
      action :nothing
    end
  end
```

That would avoid having to deal with users typing `def do_stuff` but I suspect users want to be able to type `def do_stuff`.

Intercepting `def` is likely problematic...

I think there's three choices for the receiver of the `def`:

1. the resource class
2. the action class
3. some kind of builder class

I don't like the idea of fixing the first option by polluting the namespace.

**Comment by coderanger** [comment]
Rails has a pretty clear concept of "helper methods" but they also have a clearer dividing line between different execution contexts (controller vs. template) split up by being in different files. How do we make it clear to users that the stuff inside an action block is a different context?

**Comment by b-dean** [comment]
I would be fine with 

```ruby
action_class do
  include SomeMixin::HelperMethods

  def do_stuff
  end
end
```

... if it were documented. The [Custom Resource documentation](https://docs.chef.io/custom_resources.html) should mention this, if for no other reason than to let people know they can use whyrun mode with their inline resources (which are most of the examples in the custom resource docs):

```ruby
action_class do
  def whyrun_supported?
    true
  end
end
```

**Comment by tas50** [comment]
action_class has been defined via documentation and we cleared up the confusion of new_resource.foo vs. foo, which isn't mentioned here, but that was another scope issue. I think we're good to close this out at this point.
