### ISSUE TITLE
DSC Failure incorrectly reported as WARN

### ISSUE THREAD

**Issue by webtonize** [chef/chef#4534]
I'm all new to Chef and such, so it could be something I still have to learn about, but I feel i ran in to something unusual with Chef this weekend.

I intentionally setup a dsc_script resource to fail, but the webinterface just reported everything went fine and there are no errors to report. The log on the chef-client gives a warning

the resource:
dsc_script 'MustThrowError' do
code <<-EOH
WindowsFeature InstallIISConsole
{
Name = "MustThrowError"
Ensure = "Present"
}
EOH
end

And the chef-client log:

[2016-02-01T18:05:15+01:00] WARN: Received error while testing configuration:
PowerShell DSC resource MSFT_RoleResource failed to execute Test-TargetResourc e functionality with error message: The requested feature MustThrowError is not found on the target machine. + CategoryInfo : InvalidOperation: (:slightly_smiling: [], CimException + FullyQualifiedErrorId : ProviderOperationExecutionFailure + PSComputerName : . The SendConfigurationApply function did not succeed. + CategoryInfo : NotSpecified: (root/Microsoft/...gurationManager :String) [], CimException + FullyQualifiedErrorId : MI RESULT 1 + PSComputerName : .

Is there some kind of configuration change I need to make to the server or client here to get this "warning", which to me seems pretty fatal enough to get some higher classification, show up in the Web UI and command-line tools?

**Comment by lamont-granquist** [comment]
This looks more like a bug where a warn should be a fatal, rather than getting the warn to show up in the server

**Comment by btm** [comment]
Fixed by https://github.com/chef/chef/pull/5377.
