### ISSUE TITLE
Request to Add Sleep Argument for Knife SSH

### ISSUE THREAD

**Issue by pescetto** [chef/chef#4543]
Hello,

Sometimes when running Knife SSH commands across multiple nodes, we have to have time between when one node executes the command and the next (i.e. a rolling restart). 

I'm not sure if this option exists for the "knife ssh" command, but it would be nice to add an argument "-s <time_in_seconds>" so that it 1. Doesn't execute the commands concurrently and 2. waits X amount of seconds in between issuing the command to each node.

Hopefully this makes sense. I don't have a lot of time to work on this now, but this feature would be very valuable. Please let me know if there's an existing way to do this or if I need to clarify anything.

Thank you.

**Comment by lamont-granquist** [comment]
`knife ssh -C 1 'do something; sleep 5'`?

**Comment by pescetto** [comment]
Ahhh, thanks! That'll do.
