### ISSUE TITLE
Chef 12.7.0 (64 bit windows) client install fails if chef is already installed

### ISSUE THREAD

**Issue by spuder** [chef/chef#4544]
Chef's blog asks for people to test the new 64 Bit windows chef-client

https://www.chef.io/blog/2016/02/08/update-on-native-64-bit-windows-chef-client/?utm_content=buffer70eba&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

Running as administrator on a Windows 2012 R2 Installation gives this error:

```
Installing chef from C:\Users\sowen\AppData\Local\Temp\2\chef-client-12.7.0%2B20160208210034-1-x64.msi
msiexec was not successful. Received exit code 1603
At line:246 char:9
+         throw "msiexec was not successful. Received exit code $($p.ExitCode)"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (msiexec was not... exit code 1603:String) [], RuntimeException
    + FullyQualifiedErrorId : msiexec was not successful. Received exit code 1603
```

![screenshot 2016-02-09 10 02 39](https://cloud.githubusercontent.com/assets/242382/12923821/6922dd4e-cf14-11e5-8e6c-a15533c2a796.png)

If you try and run the MSI manually, it exits with an undefined error. 

![screenshot 2016-02-09 10 05 26](https://cloud.githubusercontent.com/assets/242382/12923879/aeaf059a-cf14-11e5-9168-2a50df2bc900.png)

Enabling MSI logging produces this log: 

    msiexec /i .\chef-client-12.7.0%2B20160208210034-1-x64.msi /l*v MyLog.txt

http://pastebin.com/Q53W7WHq

**Comment by btm** [comment]
Do you have the chef-client currently installed? Is it listed in add/remove programs?
Do you have `c:\opscode\chef` already? is it empty?

**Comment by spuder** [comment]
Yes both those conditions are true. I'm testing on a server with chef 12.5 already installed.

**Comment by btm** [comment]
It took forever to find this again to link it. Relevant to 1603 errors: https://github.com/chef/omnitruck/issues/135

@spuder Ideally you would zip or tar up C:\opscode in a way that would preserve all permissions first so we could reproduce the issue. perhaps just rename it, then try the install again and see if it succeeds. I think something left behind in those folders prevents the MSI from running sometimes. I was able to reproduce it at first, but then when I blew away c:\opscode it started working fine and I couldn't reproduce it again.

**Comment by spuder** [comment]
Renaming c:\opscode to c:\opscode-old does not fix the problem. chef 12.7.0 still fails to install. 
Don't delete c:\opscode because then you can't uninstall the old version of chef. 

I have been able to provision multiple new windows VM's with chef 12.7.0 just fine. You just can't upgrade an existing install. 

    knife bootstrap windows winrm 203.0.113.0 -N foobar --prerelease --bootstrap-version 12.7.0-1 -V

**Comment by chefsalim** [comment]
I'm unable to repro this with upgrade from 12.5.1 -> 12.7.0.  

Can you confirm output of 'chef-client -v', and whether manually uninstalling the 12.5 client via Add/Remove Programs and then installing 12.7.0 succeeds?  Thanks!

**Comment by spuder** [comment]
Strange, I decided to give the 2012R2 VM a reboot, and now I can no longer reproduce. 

The VM just upgraded from 12.5.1 to 12.7.0 no problems. Windows must have been in a weird state. Thanks for the assistance. 

    . { iwr -useb https://omnitruck.chef.io/install.ps1 } | iex; install -channel current -project chef

**Comment by btm** [comment]
Thanks @spuder. if it happens again let us know, I'd be great to nail down what that state is so we can avoid it or throw a decent error.
