### ISSUE TITLE
Chef 12.2.1 - boostrap fails with Exception: NameError: uninitialized constant Chef::Mixin::Command

### ISSUE THREAD

**Issue by kamal079** [chef/chef#4546]
> $ knife --version
Chef: 12.2.1

_DEBUG: Looking for bootstrap template in /opt/chef/embedded/apps/chef/lib/chef/knife/bootstrap/templates
DEBUG: Found bootstrap template in /opt/chef/embedded/apps/chef/lib/chef/knife/bootstrap/templates
ERROR: knife encountered an unexpected error_

Adding ``` require 'chef/mixin/command' ``` to the client_builder.rb in ```/opt/chef/embedded/apps/chef/lib/chef/knife/bootstrap``` helped me get past the error.  Has anyone encountered an issue before or am I missing something?

**Comment by lamont-granquist** [comment]
12.2.1 is pretty old by now, does the same problem happen if you upgrade to 12.6 (or very shortly 12.7)?

**Comment by kamal079** [comment]
Ok, I tried 12.6.0, but it errored with the same reason. 

> knife --version
Chef: 12.6.0

```
DEBUG: Looking for bootstrap template in /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/knife/bootstrap/templates
DEBUG: Found bootstrap template in /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/knife/bootstrap/templates
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/mixin/deprecation.rb:51:in `const_missing': uninitialized constant Chef::Mixin::Command (NameError)
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/knife/ssh.rb:533:in `run'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/knife/bootstrap.rb:392:in `run'
```

**Comment by lamont-granquist** [comment]
if you comment out `extend Chef::Mixin::Command` on line 533 of /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/knife/ssh.rb does it work?

**Comment by kamal079** [comment]
yes, it does. I commented out the line ``` extend Chef::Mixin::Command ``` in ssh.rb
