### ISSUE TITLE
chef-server-ctl reconfigure fails on postgresql

### ISSUE THREAD

**Issue by vallabram1** [chef/chef#4553]
STDERR: createdb: could not connect to database template1: could not connect to server: No such file or directory
Is the server running locally and accepting
connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

how to fix this  error  to setup chef server on my ubuntu server.

**Comment by lamont-granquist** [comment]
This repo is for client-issues.  This server issue needs to get refiled under http://github.com/chef/chef-server/issues/new
