### ISSUE TITLE
property in custom resource overwrites resource

### ISSUE THREAD

**Issue by franznemeth** [chef/chef#4554]
Hello!

I have a problem writing a custom resource. If a property has the same name as a resource (e.g. user) the property overwrites the user resource.

```
property :user, String, default: 'testuser'

action :create
  application_user = new_resource.user
  user application_user do
    action :create
  end
end
```

Is this purposefully?

Regards
Franz Nemeth

**Comment by lamont-granquist** [comment]
Its a consequence of having the namespaces merged together.  Duplicate of #4006.
