### ISSUE TITLE
Chef Omnibus is not supported in Linux Alpine

### ISSUE THREAD

**Issue by thedrow** [chef/chef#4558]
This prevents me from running test kitchen to test Linux Alpine provisioning.

**Comment by coderanger** [comment]
Not sure what this bug is about. If you mean that we don't build `apk` packages, that should be filed over in the Omnibus project as it would have to support it first. Unfortunately I don't think we'll want to commit to testing on Musl, as that's a lot of work for relatively little benefit.

**Comment by thedrow** [comment]
I mean that it's not possible to run test-kitchen on Alpine because of this.
See https://github.com/portertech/kitchen-docker/pull/190#issuecomment-182338070

**Comment by coderanger** [comment]
That is 1) not related to Chef and 2) only an issue with that specific driver not all of Test Kitchen.

**Comment by thedrow** [comment]
It is related to Chef because the problem is that the Omnibus installer does not support installation in Alpine Linux.

**Comment by coderanger** [comment]
@thedrow I just chatted with some of the other maintainers and we agreed that Chef itself isn't going to support specific Alpine builds. We welcome you to contribute as a maintainer for the platform, and in doing that we would recommend you add support for both Musl and `apk` builds to OMnibus itself, but you could support it another way if you prefer.
