### ISSUE TITLE
nohup command in my bash resource

### ISSUE THREAD

**Issue by saurav2104** [chef/chef#4560]
The nohup command in my bash resource under `code` directs the output into STDOUT and STDERR instead of directing it to nohup.out.

` >nohup.out
  nohup ./example.sh & `
Normally if I run the sh file (without using any chef resource) it would STOUT and STDERR are redirected to nohup.out. But with chef resource (execute or bash) its gets printed and client fails.

**Comment by lamont-granquist** [comment]
this might work better:

```ruby
bash "whatever" do
  code <<-EOH
    nohup ./example.sh </dev/null >/tmp/nohup.out 2>&1 &
  EOH
end
```

mixlib-shellout, and therefore chef, shouldn't be able to grab a file descriptor away from the subprocess that the bash subprocess is launching, so I suspect you've got an error in your bash syntax someplace.

**Comment by saurav2104** [comment]
@lamont-granquist 
You are correct. I changed my bash syntax and it worked.
Thanks.
