### ISSUE TITLE
Provide a third notification timer :before

### ISSUE THREAD

**Issue by fsimmend** [chef/chef#4561]
`:immediately` and `:delayed` are not enough. 
----------------

There are so many situations, when we do not want to use either of both notification timers. The standard usecase is the orchestration of service and multiple configuration resources. If there is more than one configuration resource, that needs the services to be restarted in case of a change, we do not want the service to be restarted multiple times in a single chef run. We can of course use the delayed timer but then we cannot place another resource that depends on that configuration to be active in the same chef run. Alternatively, we could do the trick and notify a ruby_block resource that modifies the service resource to run a restart action instead of start. That’s what we currently do but it feels wrong and is nothing but intuitive. 

I would suggest, that a third timer should be introduced, that simply allows to add the action right before the resource default action takes place. In this case we would see a service[restart] and immediately after a service[start](noop).
In case its the first run, a second common problem would be addressed too. The common start, restart problem using a package resource and a subscribes notification from the service to the package.

**Comment by thommay** [comment]
We have an RFC for this already: https://github.com/chef/chef-rfc/blob/master/rfc058-before.md

**Comment by thommay** [comment]
(ie, we agree, and thank you for filing the report. But we need someone to implement it!)

**Comment by coderanger** [comment]
I think this is actually shipping today as part of 12.7, so you don't have long to wait.
