### ISSUE TITLE
Resource for PowerShellGet

### ISSUE THREAD

**Issue by chlsmith** [chef/chef#4562]
It would be really nice to have an included directive in the "dsc_resource" resource to have it pull down modules from a URL and extract them to the right locations.  As it is, I've been doing these steps previous to running my dsc_resource work, but it would be much easier if it was just a directive inside of dsc_resource.

**Comment by lamont-granquist** [comment]
needs triage from @chef/client-windows for milestone and priority

**Comment by smurawski** [comment]
This should not be built into dsc_resource, but we could use a powershellget resource that wraps the PowerShellGet module.  There is one in progress for the powershell cookbook which should be near release now that PowerShell 5 has re-RTM'd.

**Comment by btm** [comment]
We're working on powershell package support in https://github.com/chef/chef/pull/5315.

**Comment by btm** [comment]
https://github.com/chef/chef/pull/5315 has been merged and is included in 12.17.5+ in current.
