### ISSUE TITLE
remote_directory command for transferring files of size > 500 MB

### ISSUE THREAD

**Issue by saurav2104** [chef/chef#4572]
Hi
I am trying to transfer some files from my workstation to my client. I am using the following resource.

``` ruby
remote_directory '/scratch/ofsaebas/conf' do
  source 'conf'
  owner 'ofsaebas'
  group 'dba'
  mode '0755'
  action :create
end
```

When I do `knife cookbook upload` . the command works for directory of lesser size (say 1 MB ?) but I get the following error when the file size is 500 MB or more.

```
Uploading learnChef      [0.2.0]
ERROR: NoMemoryError: failed to allocate memory
```

I just want to copy the directory (size: 500 MB) from my workstation to some node.

**Comment by coderanger** [comment]
Perhaps try `knife cookbook upload`, I'm not sure how smart ChefFS is about using streaming requests for everything, though I remember some recent patch activity around something like that.

**Comment by saurav2104** [comment]
I had made a typing error. I am using `knife cookbook upload my_cookbook_name`

**Comment by lamont-granquist** [comment]
so while that looks like a bug, a better approach is to toss a tarball up into s3 somewhere and then download that with remote_file and extract with an execute resource.  a 500MB directory structure as a remote_directory is most likely not going to make you happy and this is likely just the first issue with it.

**Comment by saurav2104** [comment]
Thanks. I will try that.

**Comment by jospeechmorph** [comment]
We are currently experiencing the exact same issue. When using the "knife cookbook upload my_cookbook_name" syntax, in the console output we get ERROR: NoMemoryError: failed to allocate memory but only if the .zip file we are trying to copy is greater than 500mb. 

Is there any ETA on getting this bug fixed? If not can someone help by more explicitly explaining what you would need to do to try the upload to S3 and download it from there to the deployment machine. I am an IT person not a dev so this is a bit above my head.

**Comment by thommay** [comment]
This bug won't get fixed. You absolutely should never put files that size in a cookbook. If you need to download a file, use `remote_file` against a URL (any url) where that file is stored.
