### ISSUE TITLE
chef-client fails with Errno::ENOENT on log file in local mode.

### ISSUE THREAD

**Issue by kbaltrinic** [chef/chef#4576]
I just upgraded from chef-client 12.0.3 to 12.7.2 on my local ubuntu desktop where I use chef to manage the box w/o a server.  To do this I run the following command (from within a script):

```
TT=`date +%Y-%m-%d--%H:%M:%S`
sudo chef-client -z -c ./config.rb -o "$1" -l info -L ./logs/chef-run.$TT.log
```

This had been working fine in 12.0.3.  In 12.7.2 the chef run fails and writes the following to the log file, i.e. `chef-run.<date-stamp>.log` above.

```
[2016-02-14T22:03:31-05:00] INFO: Started chef-zero at chefzero://localhost:8889 with repository at ~/chef
  One version per cookbook
  cookbooks at /home/ken/chef/cookbooks
  cookbook_artifacts at /home/ken/chef/cookbook_artifacts
  data_bags at /home/ken/chef/data_bags
  environments at /home/ken/chef/environments
  roles at /home/ken/chef/roles
  clients at /home/ken/chef/clients
  nodes at /home/ken/chef/nodes
  users at /home/ken/chef/users
  acls at /home/ken/chef/acls
  containers at /home/ken/chef/containers
  groups at /home/ken/chef/groups
  policies at /home/ken/chef/policies
  policy_groups at /home/ken/chef/policy_groups

[2016-02-14T22:03:33-05:00] FATAL: Errno::ENOENT: No such file or directory - ./logs/chef-run.2016-02-14--22:03:30.log
```

Pretty funny that it writes `No such file or directory - ./logs/chef-run.2016-02-14--22:03:30.log` _to the log file_ `./logs/chef-run.2016-02-14--22:03:30.log`

I found that changing my script to the following works:

```
TT=`date +%Y-%m-%d--%H:%M:%S`
sudo chef-client -z -c ./config.rb -o "$1" -l info -L $(pwd)/logs/chef-run.$TT.log
```

Seems its an issue with resolving the relative path.

**Comment by lamont-granquist** [comment]
thing this is a dup of another local mode / chef zero bug we've got in dealing with '.' and '~' and things.

**Comment by lamont-granquist** [comment]
If this still is a problem it likely just needs File.expand_path added somewhere.

**Comment by tas50** [comment]
Confirmed this isn't an issue anymore in Chef 15
