### ISSUE TITLE
powershell_script does not have PSCredential capability

### ISSUE THREAD

**Issue by ChrisAWalker** [chef/chef#4589]
I would like the ability to run a powershell_script resource as a different user (some operations require a domain account).  This capability already exists within the dsc_resource capability.  This is an example:

powershell_script 'get cluster node' do
  code 'new-cluster'
  property :pscredential, PSCredential
  not_if 'get-clusternode'
end

**Comment by spuder** [comment]
The common work around for this is to use a windows scheduled task. 

http://spuder.github.io/chef/chef-powershell-local-administrator/

**Comment by adamedx** [comment]
This has actually been fixed since at least Chef Client 12.5.1: https://github.com/chef/chef/pull/3772. If you haven't tried it, please do so in the most recent Chef Client release.
