### ISSUE TITLE
'cluster' chef helper does not work

### ISSUE THREAD

**Issue by ChrisAWalker** [chef/chef#4597]
## Description

Within my recipe, I run this code:

```
require 'chef/win32/version'
thisnode = Chef::ReservedNames::Win32::Version.new

if thisnode.cluster?
  puts "this is a cluster - YES"
else
  puts "This is not a cluster - NO"
end

if thisnode.windows_server_2012_r2?
  puts "this is windows 2012r2!!!!!!"
else
  puts "this is NOT windows 2012r2<<<<<<"
end
```

The node IS a cluster and is operating normally.  My chef run correctly identifies the node's OS version (windows_server_2012_r2); however, it does not identify it as a cluster (responds with 'This is not a cluster - NO').

https://docs.chef.io/dsl_recipe.html
## Chef Version

Chef Version 12.6.0
## Platform Version

Windows Server 2012r2 full GUI (not Core, but will eventually be run as Core)
## Replication Case

Very simple - create cluster node with the correct OS version, then run this basic recipe.  It incorrectly handles the cluster helper.  There is _no_ error.  The helper is not properly identifying the capability.
## Stacktrace

No stacktrace.out is available from this output.

**Comment by thommay** [comment]
@chef/client-windows lamont and I are looking at this one very blankly

**Comment by ChrisAWalker** [comment]
@thommay - I'm going to look at this again later today.  We are now running 12.7.2.  I'm going to see if I can reproduce it again...

**Comment by ChrisAWalker** [comment]
BTW - what is the criteria that Chef is looking for to state it is a cluster?

**Comment by ChrisAWalker** [comment]
I ran this code on a fully functional cluster again today, here is the output, including a quick service query:

```
I ran this again on a cluster, and it still does not detect that the server is a cluster.

C:\Users\ADMINI~1\AppData\Local\Temp\kitchen>c:\opscode\chef\embedded\bin\chef-solo -j C:\Users\ADMINI~1\AppDa
ta\Local\Temp\kitchen\dna.json -c C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\client.rb
Starting Chef Client, version 12.7.2
[2016-03-30T16:39:22-05:00] INFO: *** Chef 12.7.2 ***
[2016-03-30T16:39:22-05:00] INFO: Chef-client pid: 3760
[2016-03-30T16:39:28-05:00] INFO: Setting the run_list to ["recipe[stores_hvs::cluster]"] from CLI options
[2016-03-30T16:39:28-05:00] INFO: Run List is [recipe[stores_hvs::cluster]]
[2016-03-30T16:39:28-05:00] INFO: Run List expands to [stores_hvs::cluster]
[2016-03-30T16:39:28-05:00] INFO: Starting Chef Run for T9400hvs1001
[2016-03-30T16:39:28-05:00] INFO: Running start handlers
[2016-03-30T16:39:28-05:00] INFO: Start handlers complete.
Compiling Cookbooks...
This is not a cluster - NO
This is windows 2012r2!!!!
Converging 0 resources
[2016-03-30T16:39:28-05:00] INFO: Chef Run complete in 0.499992 seconds
[2016-03-30T16:39:28-05:00] INFO: Skipping removal of unused files from the cache

Running handlers:
[2016-03-30T16:39:28-05:00] INFO: Running report handlers
Running handlers complete
[2016-03-30T16:39:28-05:00] INFO: Report handlers complete

Deprecated features used!
  The on_platforms option to node_map has been deprecated at 1 location:
    - C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cookbooks/powershell/libraries/powershell_module_resource.r
b:25:in `<class:PowershellModule>'
  Cannot specify both default and name_property together on property path of resource yum_globalconfig. Only o
ne (name_property) will be obeyed. In Chef 13, this will become an error. Please remove one or the other from
the property. at 1 location:
    - C:\Users\ADMINI~1\AppData\Local\Temp\kitchen\cookbooks\yum\resources\globalconfig.rb:76:in `class_from_f
ile'

Chef Client finished, 0/0 resources updated in 11 seconds

C:\Users\ADMINI~1\AppData\Local\Temp\kitchen>services.msc

C:\Users\ADMINI~1\AppData\Local\Temp\kitchen>sc query clussvc

SERVICE_NAME: clussvc
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_PRESHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

C:\Users\ADMINI~1\AppData\Local\Temp\kitchen>
```

**Comment by mwrock** [comment]
Chef basically uses win32 APIs to pull the same info that this powershell command pulls:
```
Get-WmiObject -Class Win32_OperatingSystem -Property OperatingSystemSKU
```
Now this just shows an integer. For example on my win10 box I get:
```
__GENUS            : 2
__CLASS            : Win32_OperatingSystem
__SUPERCLASS       :
__DYNASTY          :
__RELPATH          : Win32_OperatingSystem=@
__PROPERTY_COUNT   : 1
__DERIVATION       : {}
__SERVER           :
__NAMESPACE        :
__PATH             :
OperatingSystemSKU : 4
PSComputerName     :
```
So you need to cross reference the SKU (4 here) with the list on https://msdn.microsoft.com/en-us/library/ms724358(v=vs.85).aspx. My 4 matches up to `PRODUCT_ENTERPRISE`.

If the SKU label on that web page contains "cluster" chef identifies the node as a cluster. There are two cluster SKUs:
`PRODUCT_CLUSTER_SERVER (0x00000012)` - HPC
`PRODUCT_CLUSTER_SERVER_V (0x00000040)` - Hyper-V

Now it looks like there is a bug in chef that does not acknowledge the Hyper-V cluster. So it would be interesting if you are a Hyper-V cluster which would be easy to fix or if you are something else entirely in which case there are more questions.

**Comment by ChrisAWalker** [comment]
Yes, this is a full Windows Standard Edition, Hyper-V, Failover Cluster.  When running the same SKU, I get the following:

```
PS C:\Windows\system32> gwmi -class Win32_OperatingSystem -Property OperatingSystemSKU


__GENUS            : 2
__CLASS            : Win32_OperatingSystem
__SUPERCLASS       :
__DYNASTY          :
__RELPATH          : Win32_OperatingSystem=@
__PROPERTY_COUNT   : 1
__DERIVATION       : {}
__SERVER           :
__NAMESPACE        :
__PATH             :
OperatingSystemSKU : 7
PSComputerName     :



PS C:\Windows\system32> start cmd
PS C:\Windows\system32> cmd
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>sc query clussvc

SERVICE_NAME: clussvc
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, ACCEPTS_PRESHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0

C:\Windows\system32>

**Comment by mwrock** [comment]
Interesting. `OperatingSystemSKU` 7 is `PRODUCT_STANDARD_SERVER`

**Comment by burnzy** [comment]
Not sure if this has been mentioned in another issue or not. But the same problem exists for the 'core' helper. For windows server 2012 anyway, the core? helper returns false even on core installations. 

The link that @mwrock mentioned (https://msdn.microsoft.com/en-us/library/ms724358(v=vs.85).aspx)  has a note that may be the reason for this:

> PRODUCT_*_SERVER_CORE values are not returned in Windows Server 2012. For example, the base server edition, Server Datacenter, is used to build the two different installation options: "full server" and "core server". With Windows Server 2012, GetProductInfo will return PRODUCT_DATACENTER regardless of the option used during product installation.

**Comment by stuartpreston** [comment]
I'm closing this one due to age and the fact there's nothing obvious to do. We currently in Chef honor the value from the OperatingSystemSKU as @mwrock mentioned. If anyone has new information or thoughts on an alternative cluster detection method on Windows please open a new issue.
