### ISSUE TITLE
Proxy config for bootstrapping should support different proxy than client.d settings

### ISSUE THREAD

**Issue by sbstnbr** [chef/chef#4604]
## Description

When I run chef-client on a new node, the requests crashes: "Chef encountered an error attempting to create the client "node_dev_205"
- I can send large ping from chef client to chef server
- I can send large POSTs from chef client to chef server
- I tried disabling TCP Offload Engines (TOE)
## Chef Version

12.7.2
## Platform Version

Red Hat Enterprise Linux Server release 6.4
## Replication Case
1. Bootstrap the new node from a workstation: chef-client install OK but connection to chef-server KO.
2. Run chef-client on node: same error
## Client Output

Chef encountered an error attempting to create the client "node_dev_205"
## Authentication Error:

Received an EOF on transport socket.  This almost always indicates a network
error external to chef-client.  Some causes include:
- Blocking ICMP Dest Unreachable (breaking Path MTU Discovery)
- IPsec or VPN tunnelling / TCP Encapsulation MTU issues
- Jumbo frames configured only on one side (breaking Path MTU)
- Jumbo frames configured on a LAN that does not support them
- Proxies or Load Balancers breaking large POSTs
- Broken TCP offload in network drivers/hardware
## Stacktrace

https://gist.github.com/sbstnbr/907cf87f86d50eedb062

**Comment by lamont-granquist** [comment]
Does /var/chef/cache/chef-stacktrace.out confirm its throwing EOFError?

**Comment by sbstnbr** [comment]
@lamont-granquist Yes, it seems so: https://gist.github.com/sbstnbr/078dd9c064a801472d06

**Comment by lamont-granquist** [comment]
Well, its good to see my new error message is working correctly.  However, we still haven't seen an EOFError due to anything other than /some/ kind of weird networking issue.  That error message really carries all the information that we've been able to distill so far...

You could post some packet dumps from tcpdump and wireshark -- if you can capture the connection attempt both on the client side and the server side it'll probably show that there's a packet being sent by one side and never being seen on the other side...

**Comment by sbstnbr** [comment]
When I connect to my chef-server via wget, I get the following error:

```
wget server-url
--2016-02-22 15:55:09--  server-url
Resolving server-url... XX
Connecting to server-url|XX|:443... connected.
ERROR: cannot verify server-url’s certificate, issued by “/C=US/O=YouCorp/OU=Operations/CN=XX”:
  Self-signed certificate encountered.
To connect to server-url insecurely, use ‘--no-check-certificate’.
```

Can it be linked to my issue ?

**Comment by sbstnbr** [comment]
@lamont-granquist I actually found the issue: the proxy settings.

Both my chef server and my node are behind a proxy.

When I boostrapped my node, I added `--bootstrap-proxy 10.104.204.2:8080` for it to be able to connect to the internet to perform the 1st step of the bootstrap which is the download of chef-client. This worked. 
But it also set http_proxy and https_proxy variables in` /etc/chef/client.rb` which are then used for the node to contact the chef-server. And this failed because my proxy does not allow servers to communicate between each other. I fixed it by deleting the two variables.

So:
- on one side I need the node to use the proxy to install chef-client
- but on the other I don't want the node to use it to contact chef-server

What would you suggest?

**Comment by lamont-granquist** [comment]
I'm not sure, the client.d dir stuff in https://github.com/chef/chef/pull/4529/files might help as long as it allows for client.d to drop a config which is separate from the proxy used to bootstrap the chef-client.  That may happen almost by accident and not design though.  Certainly a use case we should support but not a use case that I recall seeing come up before.

**Comment by ankushgupta** [comment]
this is occurs due to the lasted version of chefdk i.e 2
Try to use to chefdk1.5
