### ISSUE TITLE
allow custom resource properties to be marked as sensitive

### ISSUE THREAD

**Issue by bleything** [chef/chef#4613]
## Description

It would be super cool if there was a way to tell a custom resource to suppress the output of specific property changes without needing to mark the entire resource as sensitive. Currently if you use `converge_if_changed :property_name` chef-client will emit the old and new values of the property. This happens even if the contents of that block are sensitive resources. The only alternative is to mark the entire resource as sensitive, which may not be desirable.

My specific use case is a resource that manages application users. The resource manages a lot of things about the users, so I use `converge_if_changed :property_name` a lot. The only one I care about suppressing is the password. Everything else I'd prefer to see the old and new values in the chef-client output.

I imagine this as a flag to the property declaration, like `property :x, sensitive: true`. I think that if that option existed then implementing this would only require a small change to `Chef::Provider#converge_if_changed`.
## Chef Version

12.7.2
## Platform Version

Ubuntu 14.04 LTS
## Replication Case

**resources/my_cool_user.rb**

``` ruby
resource_name :my_cool_user

property :username, String, name_property: true
property :password, String

action :manage do
  converge_if_changed :password do
    file "/tmp/#{username}.passwd" do
      sensitive true
      content password
    end
  end
end
```

**recipes/default.rb**

``` ruby
my_cool_user "normal" do
  password "cats"
end

my_cool_user "sensitive" do
  sensitive true
  password "dogs"
end
```
## Client Output

Output has been trimmed and empty/irrelevant lines removed:

```
* my_cool_user[normal] action manage
- create normal
-   set password to "cats"
* file[/tmp/normal.passwd] action create
- create new file /tmp/normal.passwd
- update content in file /tmp/normal.passwd from none to d93660
- suppressed sensitive resource

* my_cool_user[sensitive] action manage
- create sensitive
-   set password to (suppressed sensitive property)
* file[/tmp/sensitive.passwd] action create
- create new file /tmp/sensitive.passwd
- update content in file /tmp/sensitive.passwd from none to 23bcd2
- suppressed sensitive resource
```

The relevant lines are the `-    set password to...` lines. You can see that in the "normal" user the password is emitted even though the resource in the block is marked as sensitive.

**Comment by bleything** [comment]
fwiw, I started working on a PR for this but got pretty lost in the source. I'm happy to figure it out and do the work, but I want to make sure it's something y'all want first.

**Comment by coderanger** [comment]
This smells more like an RFC than a Github issue.

**Comment by bleything** [comment]
Ah, maybe? I asked where to file feature requests in the hangops #chef channel and was told here. Happy to move it, just let me know to where.

**Comment by coderanger** [comment]
I defer to @thommay and @jkeiser as the most involved parties :) :+1: for the actual feature. Probably so clearly the right thing to do that an RFC is overkill.

**Comment by thommay** [comment]
Nah, this isn't a big enough change to warrant an RFC - it's just extending current functionality into a new area. I'm definitely :+1: on this.

**Comment by lamont-granquist** [comment]
:+1:

**Comment by yruss972** [comment]
+1

**Comment by koldrid** [comment]
Was this not covered in https://github.com/chef/chef/pull/5185?

**Comment by koldrid** [comment]
aaaannnndddd I just noticed the date

**Comment by thommay** [comment]
@koldrid you're correct, thanks.
