### ISSUE TITLE
Chef::DataBagItem.to_hash is modifying Chef::DataBagItem.raw_data

### ISSUE THREAD

**Issue by rb1whitney** [chef/chef#4614]
## Description

Chef::DataBagItem.to_hash to modifying raw_data and causing corruption of data bags to upload to chef server

## Chef Version

We have been experiencing issue with 12.06 but more many versions below this as well.

## Platform Version

Red Hat Enterprise Linux Server release 6.7

## Replication Case

to_hash has a bug and it has been corrupting my data bags. When I use to_hash to compare if a data bag is identical to what is on the server. The chef code modifies the raw_data being compared and causes chef_type and data_bag to be added to my raw_data. The above code is modifying self.raw_data since the object is a pointer and not a copy. 

https://github.com/chef/chef/blame/master/lib/chef/data_bag_item.rb
def to_hash
      result = self.raw_data
      result["chef_type"] = "data_bag_item"
      result["data_bag"] = self.data_bag
      result
end

If you try to Chef::DataBagItem.save with the data_bag item, it will upload this content to Chef Server. For an encrypted data bag, Chef thinks the data is un-encrypted as a result.

knife data bag show test_environment datasource:
Unencrypted data bag detected, ignoring any provided secret options.
chef_type: data_bag_item
data_bag:  test_environment
id:        datasource
password:
  cipher:         aes-256-cbc
  encrypted_data: ...
  
  hmac:           ...
  
  iv:             ...
  
  version:        2
url:
  cipher:         aes-256-cbc
  encrypted_data: ...
  
  hmac:           ...
  
  iv:             ...
  
  version:        2
username:
  cipher:         aes-256-cbc
  encrypted_data: ...
  
  hmac:           ...
  
  iv:             ...
  
  version:        2
## Client Output

None

## Stacktrace

Code to test:
puts "Before: #{local_bag_item.to_json}"
local_bag_item.to_hash
puts "After: #{local_bag_item.to_json}"

Before running to_hash, json output: 

{"name":"test_environment_datasource","json_class":"Chef::DataBagItem","chef_type":"data_bag_item","data_bag":"test_environment","raw_data":{"id":"...","password":{"encrypted_data":"...","hmac":"...","iv":"...","version":2,"cipher":"aes-256-cbc"},"username":{"encrypted_data":"...","hmac":"...","iv":"...","version":2,"cipher":"aes-256-cbc"}}}

After we run to_hash, I ran to_json. Shows that to_.hash is appending "chef_type":"data_bag_item","data_bag":"test_environment" at back of hash and uploading this json will cause those extra values to append to server:  {"name":"test_environment_datasource","json_class":"Chef::DataBagItem","chef_type":"data_bag_item","data_bag":"test_environment","raw_data":{"id":"datasource","password":{"encrypted_data":"...","hmac":"....","iv":"....","version":2,"cipher":"aes-256-cbc"},"username":{"encrypted_data":"....","hmac":"...","iv":"...","version":2,"cipher":"aes-256-cbc"},"chef_type":"data_bag_item","data_bag":"test_environment"}}

This causes issue when you query Chef directly:

knife raw data/test_environment/datasource:
{
  "id": "some_data",
  "username": {
    "encrypted_data": "....",
    "hmac": "...",
    "iv": "...",
    "version": 2,
    "cipher": "aes-256-cbc"
  },
  "password": {
    "encrypted_data": "...",
    "hmac": "...",
    "iv": "...",
    "version": 2,
    "cipher": "aes-256-cbc"
  },
  "chef_type": "data_bag_item",
  "data_bag": "test_environment"
}

**Comment by lamont-granquist** [comment]
Yep that is terrible, and likely buggy all over the codebase.

**Comment by coderanger** [comment]
https://github.com/chef/chef/issues/4628 is likely related to this.

**Comment by thommay** [comment]
Should be fixed by #4631
