### ISSUE TITLE
CHEF-1621 "recursive" attribute on "directory" resource

### ISSUE THREAD

**Issue by sdarwin** [chef/chef#4615]
When you set "recursive true" on a directory resource, chef will create the intermediate directories if they are missing.  But it won't "manage" them, in the sense that those permissions could be modified later and chef won't notice.   There is a sort of one-time decision, as to what the permissions of missing intermediate directories should be.   As Rush has said, "If you choose not to decide, you still have made a choice."   And you are deciding that root is the best choice to be the owner of those directories.     But shouldn't it rather be the user/group/mode of the directory resource?

In other words, when creating /a/b/c/d/e recursively, and /a/b previously exist, then chef will create c/d/e .  In the future, as long as /a/b/c/d exists, chef only cares about e.
What are the most expected permissions for the missing c/d/e, the first time chef generates those?
If a directory is missing, and chef is creating it because the recursive attribute is set to true, why not set it to the user/group/mode that was specified?  
To counter some arguments:
1.  you might end up changing the permissions of /var and /etc.    No. /var and /etc are already in place.
2.  you don't know "permissions_root", as in CHEF-1621.   Doesn't matter.  Just create the _missing_ dirs.
3.  It is chef's job to "manage" the dirs, to be idempotent.   Well, this method does not really change that. does it?   the intermediate dirs are not currently being managed.
Not sure if I am missing some cases though.   but doesn't this make sense?

**Comment by lamont-granquist** [comment]
If you just want to patch it so that when c/d/e is created it gets the owner/group/perm set there's no real reason not to do that, i guess.

If you care about those dirs, though, you probably want to create explicit dir resources to actually manage them though.

**Comment by sdarwin** [comment]
Thank you for the answer.  Yes, definitely in this scenario if you really care about those dirs, you have to create explicit dir resources.  but hopefully this is addressing a very common and convenient case of using the recursive parameter to quickly create dirs.

**Comment by coderanger** [comment]
My understanding is that we wanted to match the behavior of `mkdir -p` with respect to default umask et al.

**Comment by jaymzh** [comment]
OK, so I had to read through your description like 5 times to understand the change you are proposing. To be clear you are NOT proposing:

* Managing intermediate directories on an ongoing basis. I.e. the fact that someone can change them and they will not be converged stays as-is.
* Managing any directories that already existed (except for the leaf directory)

You ARE proposing:

* If you have to create an intermediate directory, use permissions from the resource instead of relying on the `umask`

If that's correct, I support that, I think it's reasonable, and I'd support such a PR.

However, managing the directories won't work for ... lots of reasons like not knowing which ones to manage or setting bad permissions on / or /usr or whatever.

**Comment by coderanger** [comment]
Any patch would need a careful examination of its security properties as far as common use cases go.

**Comment by sdarwin** [comment]
jaymzh - agreed.

**Comment by sdarwin** [comment]
coderanger:  "My understanding is that we wanted to match the behavior of mkdir -p"

That is very interesting.

mkdir -p -m 700 a/b/c/d
results in:
drwxrwxr-x 3 vagrant vagrant 4096 Feb 24 12:14 a
drwxrwxr-x 3 vagrant vagrant 4096 Feb 24 12:14 b
drwxrwxr-x 3 vagrant vagrant 4096 Feb 24 12:14 c
drwx------ 2 vagrant vagrant 4096 Feb 24 12:14 d

I am glad to defer to the wisdom of mkdir -p, in terms of umask, if that is preferred.  The main concern was actually owner/group, that it not be root, but rather the specified user.    It was the owner/group that prompted me to open this ticket.    
To solve the ambiguity of the mode, which could either be the specified mode of the resource OR the system umask, how about adding an optional "umask" parameter to the dir resource?
If the umask is not specified, then it defaults to the system default, and you get mkdir -p functionality mentioned above.
If the umask is specified, then the intermediate directories mode will depend on the value. 
Regardless, the owner/group is defined by the chef resource.

**Comment by lamont-granquist** [comment]
We should not engineer a umask property only for the directory resource.  #3741 already covers adding a umask property to Chef::Resource and mentions that File#umask and the Chef::Config[:umask] attribute are already there to workaround umask issues.

**Comment by lamont-granquist** [comment]
And IMO either the user/group/mode gets applied to recursive-created dirs consistently or the existing behavior is preserved.  Splitting the difference will be surprising/confusing.

**Comment by lamont-granquist** [comment]
So:

- #3741 covers adding a umask attribute to Chef::Resource
- we will not split the difference
- we want to preserve mkdir -p semantics
- the always-correct way to control the perms and ownership of recursively created directories is to be explicit and to use another directory resource for them (and this is not a 'workaround' this is being explicit about possibly confusing intentions).

Closing this as either a dup of #3741 or a wontfix of the other concerns.
