### ISSUE TITLE
Client 12.7.2 gives Chef::Exceptions::ValidationFailed error during EncryptedDataBagItem.load that used to work on chef-client 12.5.1

### ISSUE THREAD

**Issue by kinnairdclan** [chef/chef#4628]
## Description

I'm bootstrapping a node with a cookbook that worked fine with chef-client as of November, with chef-client 12.5.1, unfortunately the following code:

`#Configure PostgreSQL cluster -- create pertinent databases, users, and groups based on uploaded, decrypted shell here-document.`
`here_doc_name = Chef::EncryptedDataBagItem.load("database_configs", "tlcworx_#{node["tlcworx_db"]["environment"]}")["filename"]`
`here_doc_content = Chef::EncryptedDataBagItem.load("database_configs", "tlcworx_#{node["tlcworx_db"]["environment"]}")["content"]`
`open("#{node["tlcworx_db"]["tmp_dir"]}/#{here_doc_name}", 'w') { |f| f.puts here_doc_content }`

Has rendered up the following error that halts the bootstrap:

`Chef::Exceptions::ValidationFailed: Option data_bag's value {"encrypted_data"=>"PffgOkpIpdoEJO8khrUOUQwqv2/vqrtzOf1U/z/a5xD4KqSH2/CkD1zHndzW\nwJL1\n", "iv"=>"d/kiiPRQWQoKBTU5WF8NPw==\n", "version"=>1, "cipher"=>"aes-256-cbc"} does not match regular expression /^[\-[:alnum:]_]+$/`

Obviously, I'm supplying the same `--secret-file` as I did back then via knife CLI argument. Running `knife data bag edit database_configs tlcworx_uat --secret-file /path/to/secret.pem` decrypts the cookbook content appropriately, and doesn't error out. Again, this is only upon bootstrap when a server's chef-client is communicating with the remote chef-server.

I can avoid this error by running with the chef-client version I previously used with this cookbook, namely `knife bootstrap --bootstrap-version 12.5.1 [...]`

[Posting on SO](https://stackoverflow.com/questions/35616044/chefexceptionsvalidationfailed-error-during-encrypteddatabagitem-load-due-to), I was led to another reported instance of this problem at the Hangops Slack with the most recent chef-client.

## Chef Version

12.7.2 (chef-client)

## Platform Version

Debian 8.3

## Client Output

https://gist.github.com/kinnairdclan/2dab8f7cbdf64f4cd428
## Stacktrace

https://gist.github.com/kinnairdclan/333df44b22a8dfbb112c

**Comment by lamont-granquist** [comment]
very likely a dup of #4614
