### ISSUE TITLE
Service silently fails to reload service if not listed in supports.

### ISSUE THREAD

**Issue by fuel-wlightning** [chef/chef#4632]
## Description

When reloading a service that doesn't support reloading, chef appears to be reloading the service, and fails silently.
## Chef Version

chef-client version: 12.7.2
berks version: 4.2.0
kitchen version: 1.5.0
## Platform Version

CentOS 6.6 (init.d based script)
## Replication Case

*Utilize any init.d script (I used nginx) on RedHat.
`
  template "/etc/nginx/conf.d/05_https_edge.conf" do
    source "nginx_05_https_edge.conf.erb"
    mode "0644"
    owner "root"
    group "root"
    notifies :reload, 'service[nginx]'
  end

  service "nginx" do
    action [ :enable, :start ]
  end
`
## Client Output

```
     * service[nginx] action reload
       - reload service service[nginx]
```
## Stacktrace

No stacktrace.
## Code at issue

https://github.com/chef/chef/blob/12.7.2/lib/chef/provider/service/init.rb#L89

There is an if and elsif, need to catch the else with a warning or debug info.

**Comment by coderanger** [comment]
:+1: we should have an `else` in that dispatch to warn at a minimum, possibly raise `UnsupportedAction`?

**Comment by cmur2** [comment]
This just happened to me and took a while to troubleshoot since from the Chef output it's not clear that the action was never really executed.

**Comment by lexelby** [comment]
Just tripped over this as well.
