### ISSUE TITLE
knife.rb and activation e-mail's link don't obey the API_FQDN on AWS

### ISSUE THREAD

**Issue by dfduarte** [chef/chef#4637]
## Description

Knife.rb and activation e-mail's link don't obey the API_FQDN on AWS. When configuring a new Chef-Server on AWS, the activation e-mail for new users and the starter kit's knife.rb uses the internal hostname from AWS machine, and don't get neither the machine hostname and the named passed on api_fqdn.

## Chef Version

12.6

## Platform Version

Amazon Linux 2015.09.

## Replication Case

0- Configure machine and hostname and requirements.
1- Install directly from RPM, or using Chef's cookbook.
2- Configure chef-server.rb accordling the Supermarket manual and config_rb_server manual, as api configuration for Supermarket, as usual, and api_fqdn for hostnames.
3- Create a new organization and get the Starter kit. Notice that knife.rb points to wrong host
4- Create a new user, and notice that activation link stills pointing to wrong place.

**Comment by lamont-granquist** [comment]
by "API_FQDN on AWS" do you mean the api_fqdn configured in the chef-server.rb?

and the starter kit and the activation link are rendered by the server so that would make this a server bug...

**Comment by dfduarte** [comment]
By "API_FQDN on AWS" do you mean the api_fqdn configured in the chef-server.rb?
**Yes, that's right!**

and the starter kit and the activation link are rendered by the server so that would make this a server bug...

**I think so, because these files are rendered by Chef-Server itself. So, based on your affirmative, I have to write up a new issue ticket somewhere else, or here it's the right place?**

**Comment by lamont-granquist** [comment]
http://github.com/chef/chef-server/issues/new is the correct place to file that bug, this is only for client code.
