### ISSUE TITLE
New chef-client (12.8.0) broken 

### ISSUE THREAD

**Issue by gopisaba** [chef/chef#4639]
## Description

The new current chef-client is not working with the resource windows_package. 

## Chef Version

12.8.0

## Platform Version

Windows 2008 and Windows 2012

## Replication Case

I am using chef-zero in my environment. I am installing chef-client with the powershell script

`. { iwr -useb http://omnitruck.chef.io/install.ps1 } | iex; install -channel current -project chef`

After the new chef-client (12.8.0) release the windows package recipes end up with the error messages. After I revert back to the stable version (12.7.2) it is all good. 

I could replicate the issue in my test environment with simple windows package cookbook.

## Client Output

 Chef::Exceptions::NoWindowsPackageSource
    ----------------------------------------
    Source for package 7zip must be specified in the resource's source property for package to be installed because the
package_name property is used to test for the package installation state for this package type.

    Resource Declaration:
    ---------------------
    # In C:/Users/Administrator/.chef/local-mode-cache/cache/cookbooks/test/recipes/default.rb

      1: windows_package '7zip' do
      2:   source 'http://www.7-zip.org/a/7z938-x64.msi'
      3: end

    Compiled Resource:
    ------------------
    # Declared in C:/Users/Administrator/.chef/local-mode-cache/cache/cookbooks/test/recipes/default.rb:1:in `from_file'

    windows_package("7zip") do
      package_name "7zip"
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :windows_package
      cookbook_name "test"
      recipe_name "default"
      source "http://www.7-zip.org/a/7z938-x64.msi"
    end

## Stacktrace

Generated at 2016-02-29 02:16:20 -0800
Chef::Exceptions::NoWindowsPackageSource: windows_package[7zip] (test::default line 1) had an error: Chef::Exceptions::NoWindowsPackageSource: Source for package 7zip must be specified in the resource's source property for package to be installed because the package_name property is used to test for the package installation state for this package type.
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/mixin/why_run.rb:240:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/mixin/why_run.rb:321:in `block in run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/mixin/why_run.rb:320:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/mixin/why_run.rb:320:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/provider.rb:154:in `process_resource_requirements'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/provider.rb:132:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/resource.rb:596:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/runner.rb:73:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/runner.rb:105:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/runner.rb:105:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/runner.rb:105:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/runner.rb:104:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/client.rb:668:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/client.rb:663:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/client.rb:663:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/client.rb:702:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/client.rb:280:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/application.rb:252:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/application.rb:228:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/application.rb:211:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/application/client.rb:445:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/application/client.rb:435:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/application/client.rb:435:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/application/client.rb:424:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/lib/chef/application.rb:58:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.8.0-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:60:in `load'
C:/opscode/chef/bin/chef-client:60:in `<main>'

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by spuder** [comment]
+1 I can reproduce this. 

Also tried the following variants with the same error


>    Source for package http://www.7-zip.org/a/7z938-x64.msi must be specified in the resource's source property for package to be installed because the package_name property is used to test for the package installation state for this package type.

```ruby
windows_package 'http://www.7-zip.org/a/7z938-x64.msi' do
  package_name '7zip'
  installer_type :msi
  source 'http://www.7-zip.org/a/7z938-x64.msi'
  action :install
end
```

Also tried installing a windows package from local disk. Got the same error

```ruby
remote_file 'c:/7zip.msi' do
  source 'http://www.7-zip.org/a/7z938-x64.msi'
end


windows_package 'c:/7zip.msi' do
  package_name '7zip'
  installer_type :msi
  source 'c:/7zip.msi'
  action :install
end

```

**Comment by spuder** [comment]
@mwrock could you take a peak at this? I suspect this commit caused the regression. 

https://github.com/chef/chef/commit/50fe971657133e5774c2d05c0bc3850ae27455b0#diff-e6fe4e3a8256efbb46017e16c2c41db4

**Comment by mwrock** [comment]
Ugh. Yes that is indeed a regression for MSI's caused by the "fix" for another regresion for EXE's. 

`new_resource.source unless msi?` should be `new_resource.source || msi?`

Will be adding a test to catch this.
