### ISSUE TITLE
Knife data bag create does not respect -s option

### ISSUE THREAD

**Issue by nlam79** [chef/chef#4647]
## Description

Using knife data bag create with the -s or --server-url option does not work.  However, using -s for knife roles/cookbooks/environments is okay. 
## Chef Version

12.5.1 and 12.7.2
## Platform Version

Ubuntu 14.04
## Replication Case

-Create a chef 12 server
-Create a new org and admin user
-Create a knife.rb to access this chef server using the admin user.
-Run "knife cookbook list -c knife.rb" to test initial access is ok.
-Run "knife data bag create -c knife.rb -s https://chef12-server/organizations/test-org
Result: data bag should be created under the chef12 server / org specified by -s.  Instead it is created under the chef-server-url specified by knife.rb.
## Client Output

N/A
## Stacktrace

N/A

**Comment by sbbowers** [comment]
This problem is related to:

```
$ knife --help
Usage: knife sub-command (options)
    -s, --server-url URL             Chef Server URL
...
```
vs

```
$ knife data bag create --help
knife data bag create BAG [ITEM] (options)
        --server-url URL             Chef Server URL
...
    -s, --secret                     The secret key to use to encrypt data bag item values. Can also be defaulted in your config with the key 'secret'.
        --secret-file SECRET_FILE    A file containing the secret key to use to encrypt data bag item values. Can also be defaulted in your config with the key 'secret_file'.
```

The `knife data bag *` sub-commands over-write the short form parameter that is a global parameter:
https://github.com/chef/chef/blob/master/lib/chef/knife/data_bag_secret_options.rb#L38

A temporary work around is to use the --server-url form for everything.

**Comment by vsingh-msys** [comment]
Added deprecation warning in #8909  if someone uses `-s` for data bag. will remove `-s` for data bag in the future major release after that `-s` will work for `--server-url` only.
