### ISSUE TITLE
Proposal: Don't disable the shell for locked users

### ISSUE THREAD

**Issue by legal90** [chef/chef#4648]
Actually, I suggest to roll back the PR #4465, because it breaks the backward compatibility and introduces an unexpected behavior for such action as user account lock.

I've explained the concerns in the comment here: https://github.com/chef/chef/pull/4465#issuecomment-190165530
Quote:
> In our case on RHEL 6 we've managed а user and performed `lock` action expecting that it will be literally locked (`usermode -L`), but nothing more:

> ```ruby
user 'beaver' do
  # ...
  action :lock
end
```

> But now this user has a shell set to `/bin/false`, which causes failures to start the beaver daemon. Its init script contains the following line: `su - $user -c kill -TERM $pid`, so now it's failed because of disabled shell.

> We strongly suggest do not break the behavior of user account lock, at least for `useradd` provider, and left only `-L` option here. 
In case if operator wants this user account to be restricted to login via SSH private key, he should manage `AllowUsers` option of ssh deamon and/or just disable the shell explicitly:

> ```ruby
user 'my_user' do
  # ...
  shell `/bin/false`
  action :lock
end
```

Following the man page of `usermod`, locking the user account means only setting the `-L` option, so it's not about changing the shell or something else.

сс: @artursitarski @lamont-granquist @thommay

**Comment by thommay** [comment]
I agree we should roll back #4465 . How about we add a `disable` action to both lock the user and change the shell, and leave the `lock` action as is?

**Comment by legal90** [comment]
Thanks!

> How about we add a disable action to both lock the user and change the shell, and leave the lock action as is?

I'm OK with that. It will be useful for cases like mentioned in the top message of #4465

**Comment by jblaine** [comment]
+1 rollback

**Comment by jkeiser** [comment]
Merged! Closing this.
