### ISSUE TITLE
knife user create doesn't actually allow users to be created (w/o pivotal)

### ISSUE THREAD

**Issue by vinyar** [chef/chef#4656]
## Description

knife provides a command `knife user create` however it will fail even for org admins because afaik the only way to create users is with `chef-server-ctl user-create` command
## Chef Version

Going back at least a few chefdk versions

```
$ chef -v
Chef Development Kit Version: 0.11.2
chef-client version: 12.7.2
berks version: 4.2.0
kitchen version: 1.5.0
```
## Replication Case

```
knife user create knife_user_test knife_user_test knife_test knife_create knife@usercreate.test test123
ERROR: You authenticated successfully to https://api.opscode.com/organizations/i_watch_dora_the_exlorer as alexv_trash01 but you are not authorized for this action
Response:  missing create permission
```
## Expected outcome

Perhaps one of the following would be a valid solution
- update the help file to reflect that command needs special key
- remove knife user create command

**Comment by vinyar** [comment]
Created a brand new org for testing, and the user creating fails with:

```
ERROR: Failed to authenticate to https://api.opscode.com/organizations/ad_demo as alexv with key /Users/alexvinyar/.chef/alexv.pem
Response:  Invalid signature for user or client 'alexv'
```

**Comment by coderanger** [comment]
This should probably be discussed in a broader context. Most of the user-related commands in knife (also `knife configure`) have been non-functional. The new `server-admins` group exists to try and fix some of that, but only covers `knife user edit` right now I think?

**Comment by lamont-granquist** [comment]
This command has only ever worked on open source chef server and never on private/hosted/enterprise/chef server 12.

Also a dup of numerous other reports.  Probably wrong repo to report this in since there's no Server API to hit in order to modify this command to work.

**Comment by mmzyk** [comment]
Assuming a user is part of the server admins group on the server, this command should know work, as of the release of Chef server 12.4.1, which was back in Feb. This should be verified, but once it is, this can be closed. (Note that if a user is NOT part of the server admins group, this command will always fail, due to how permissions work on Chef server 12+).

Relevant docs here: https://docs.chef.io/knife_user.html (also links to docs on server admins)

**Comment by roberto-mardeni** [comment]
knife user commands are useless at least from the standpoint of the hosted chef, for anybody that needs it, you should do the following:

- Register the account at https://manage.chef.io/signup
- Activate the account via the email received
- Invite to the organization needed
- Accept the invitation
- Add the account to whatever security groups needed

**Comment by nikhil2611** [comment]
Pivotal users is used by the chef-server-ctl command and knife on the chef-server itself. If you are using the command from a workstation they’d need to make sure their user is added as a server-admin to be able to manage users and orgs outside of the org they may be a member of.
