### ISSUE TITLE
Line endings and file resources

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#4662]
## Description

The way we handle line endings is mildly terrible and inconsistent and confusing.  When we upload cookbooks we use 'binmode' so we get no conversion of line endings.  When we download cookbooks [MOST of the file resources will use binmode](https://github.com/chef/chef/blob/20e5d3309e075feefbe01d67b408f207786bd3a5/lib/chef/file_content_management/tempfile.rb#L54-L57) so that users will get whatever they uploaded.  However [the template resource will do line ending conversion](https://github.com/chef/chef/blob/20e5d3309e075feefbe01d67b408f207786bd3a5/lib/chef/mixin/template.rb#L166-L180) so will behave like binmode is false.
## Chef Version

11.8.0-ish through 12.7.2
## Issues
- Sometimes users push files to Windows hosts which are then consumed ultimately on Linux hosts (the windows host may be the TFTP server or whatever for $REASONS).
- Sometimes users push files to Linux hosts which are then consumed ultimately on Windows hosts.
- When we weren't using binmode on file resources people would push binaries through cookbook_file or remote_file resources which would then be mangled by binmode settings.
- Users that aren't using the template resource get the line ending of whatever was uploaded -- so you can't edit Windows cookbook_file resources on Linux hosts and vice-versa
- Does anyone want to edit on Linux, push to Linux via chef but to deploy with Windows line endings?  (and vice versa)
## Proposal One
-  Add a binmode flag on all the file resources.
-  Most file resources will default to binmode false, while template resources will default to binmode true.  This is necessary for backcompat and is in many ways arguably 'correct'.
-  The 'binmode true' flag on cookbook_file/etc resources will mean the line endings will convert to agree with the target O/S
-  The 'binmode' on the template resource will need to work around erubis converting everything to windows line ending.  

This has at least one issue that the ability to edit on linux, push to linux, but consume windows line endings becomes a lot more difficult.  You could still save the file as windows on the linux workstation and upload it and then use 'binmode true' though.  But its not 'delightful'.
## Proposal Two
-  Add a `line_ending` property (note: awkward) that is quadruple valued:
- `nil` means no conversion (binmode = true, and this would be the default for cookbook_file, etc)
- `:target` means to convert to the target host (binmode = false, and this would be the default for template resource)
- `:windows` means to convert to windows, even if you're on a linux host
- `:unix` means to convert to unix endings, even if we're running on windows

The benefit of this is its much more clearly descriptive, and would allow writing a file resource which would deploy windows line endings to a linux host -- without having to both set binmode to true _and_ to make damn certain to upload the file to the chef server with windows line endings.
## Note

We treat files and templates differently by default right now.  I'm not sure we should fix this, however.  When someone wants to deploy a binary they will _never_ use a template and will _always_ use a cookbook_file.  They will _never_ want line ending conversion.  The default for cookbook_file gets this use case correct.

On the other hand templates are _never_ going to be binaries, and by default you almost always want the line endings to match the target host -- otherwise if someone edits the /etc/resolv.conf on a windows host and uploads it you blow it out with windows line endings, which is what you never want.

Of course cookbook_files that are text files are treated like binaries by default, while cookbook_files are still more often text files than binaries[*].  I guess I could see the argument that both cookbook_files and template files should be considered text files by default and should get the target O/S line endings by default -- but that requires everyone pushing out a binary cookbook_file to have a flag day and drop 'binmode true' onto their resources.

The way I proposed solving this in https://tickets.opscode.com/browse/CHEF-4746 was to inspect the file and determine if it looked like a binary or not and then set binmode based on if the first X thousand bytes of the file looked binary or text.

Either way if we pick proposal #1 or #2 we'd need to think this issue through as well.  There are three sub-options here:
1.  Templates default to text files, cookbook_files default to binaries (this would not be a breaking change, and i'd assumed we'd do one of the proposals above and implement it with this first)
2.  Templates and cookbook_files default to text files, all binaries need to be denoted as such on the resource (this would be hella breaking change)
3.  Magical binary detection nirvana with the option to override in the edge case we guess wrong (this might not be a breaking change except in edge conditions)

[*] binaries are always cookbook_files, cookbook_files are predominantly text files

**Comment by lamont-granquist** [comment]
`newline` might be a better name for the property in proposal two than `line_ending` since its shorter, doesn't have the underscore and matches the title of https://en.wikipedia.org/wiki/Newline (which is what pops up when i type `line ending` into google)

**Comment by lamont-granquist** [comment]
supersedes #1718 and #2466

**Comment by stiller-leser** [comment]
I'd love to have an update to this. This makes it impossible for us to use chef on windows since we are compiling the cookbooks before using them in Vagrant. It's sad to see statements like "We’re declining to move forward with changes to CRLF handling at this time. By closing this idea, we’re releasing the votes attached to it for use on other product ideas." as found [here](https://feedback.chef.io/forums/301644-chef-product-feedback/suggestions/10862298-knife-upload-to-remove-crlf) . Also I vote for your second proposal. Seems like this would be the best way to handle it.

**Comment by lamont-granquist** [comment]
update is that i haven't had time to work on it and other stuff is taking priority...

**Comment by stiller-leser** [comment]
Thanks for the feedback. Do you happen to have pointers as to where or at which steps one might have to look?

**Comment by thommay** [comment]
This absolutely needs to be an RFC.

**Comment by epu** [comment]
Story description doesn't mention windows-native developers (I used to develop chef cookbooks on windows and use windows machines for the cookbook deployment pipelines) which sounds similar to @stiller-leser environment. I like the readability of proposal 2 (developer sets intended mode by name).
