### ISSUE TITLE
The "amazon" platform should be moved from the "rhel" to the "fedora" platform_family

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#4665]
## Description

The "amazon" platform isn't a recompiled-rhel version and never should have been there.  At the same time it uses RPMs and is based on fedora at its core.

This is a major breaking change for 13.

**Comment by tas50** [comment]
Amazon Linux is really it's own thing at this point.  Originally it was sorta RHEL 5, but not really.  We should just give it the amazon platform_family and be done with it for 13.

**Comment by lamont-granquist** [comment]
Because if you add a new platform_family you have to add it to everywhere the others are, ie.:

```
./lib/chef/dsl/platform_introspection.rb:        #     [:fedora, :rhel] => "value for all known redhat variants"
./lib/chef/provider/ifconfig/redhat.rb:        provides :ifconfig, platform_family: %w{fedora rhel}
./lib/chef/provider/package/yum.rb:        provides :package, platform_family: %w{rhel fedora}
./lib/chef/provider/service/insserv.rb:        provides :service, platform_family: %w{debian rhel fedora suse} do |node|
./lib/chef/provider/service/redhat.rb:        provides :service, platform_family: %w{rhel fedora suse} do |node|
./lib/chef/provider/service.rb:        Chef.set_provider_priority_array :service, [ Systemd, Insserv, Redhat ], platform_family: %w{rhel fedora suse}
./lib/chef/resource/yum_package.rb:      provides :package, os: "linux", platform_family: %w{rhel fedora}
./spec/functional/resource/group_spec.rb:    when "debian", "fedora", "rhel", "suse", "gentoo", "slackware", "arch"
./spec/functional/resource/group_spec.rb:    when "debian", "fedora", "rhel", "suse", "gentoo", "slackware", "arch"
./spec/functional/resource/user/useradd_spec.rb:        if %w{rhel fedora wrlinux}.include?(OHAI_SYSTEM["platform_family"])
./spec/functional/resource/user/useradd_spec.rb:          if %w{rhel fedora}.include?(OHAI_SYSTEM["platform_family"])
./spec/support/shared/unit/platform_introspector.rb:      [:rhel, :fedora] => "redhatty value",
./spec/unit/dsl/platform_introspection_spec.rb:      [:rhel, "fedora"] => "redhatty value",
```

If we move from "rhel" to "fedora" none of that code needs to change.  And that is just the code internal to this repo.

**Comment by luckymike** [comment]
Please WARN really loudly about this in subsequent versions of 12.x & maybe even begin supporting it in both families ahead of time (if that is possible) so folks can migrate ahead of time.

**Comment by lamont-granquist** [comment]
a nodes platform_family is single valued, it cannot be both.  i don't know how to warn on this usefully.  platform_family is checked half a million times in a chef-client run due to the resource and provider resolver code, throwing WARNs on access like that will obliterate the logs with noise.  trying to target only recipe is code is a) very hard and b) also prone to false positives since you want to identify a conditional taken on platform_family where "rhel" and "fedora" are not treated the same.

we accept a PR to add a warning, but unless someone steps up i think this is just going to have to be a breaking change for 13.0 that will need to be caught by testing.

**Comment by luckymike** [comment]
Hmm. I figured that the platform_family was single valued and I see your concern about a million WARNS.

Given that, from a cookbook maintainer standpoint, I'm :+1: on @tas50's suggestion of an amazon platform family. I'd note that a lot of cookbooks already have `if node[:platform] == "amazon"` conditions set inside `if node[:platform_family] == "rhel"` blocks. That's likely to continue with a switch to fedora.

Adding the Amazon family would allow cookbook maintainers to update existing conditionals ahead of time. It would also provide more consistent behavior for cookbooks that aren't updated, as neither the rhel nor fedora conditions would be met. 

I realize that adding the family is more work, but it's more accurate and better solution for users in the long run.

**Comment by lamont-granquist** [comment]
chef/ohai#971
