### ISSUE TITLE
resources() inside provider gets wrong resource collection

### ISSUE THREAD

**Issue by coderanger** [chef/chef#4669]
When calling `resources('type[name]') inside 12.5-style fused resources you end up calling it on the`new_resource` object via the automatic scope manipulation, which means it is querying the run context the resource was defined in, not the context created inside the action.

``` ruby
action :run do
  ruby_block 'test' do
    block { }
  end

  run_context.resource_collection.resources('ruby_block[test]') # Is the above resource defined in the action.
  resources('ruby_block[test]') # Raises an exception because it is looking at the outer context.
end
```

/cc @jkeiser @lamont-granquist

**Comment by lamont-granquist** [comment]
nearly a feature, but probably not...

**Comment by Poohblah** [comment]
Does https://github.com/chef/chef/issues/4017 fix or address this issue in any way?

**Comment by lamont-granquist** [comment]
I wouldn't expect it to.  This one is unique to the way 12.5 custom resources mash-up all the contexts and is more related to #4672 and all the rest of the scope issues with 12.5 resources...

**Comment by lamont-granquist** [comment]
http://serverfault.com/questions/729013/chef-12-5-custom-resources-accessing-resources-in-recipes/773057#773057

the accepted answer on that SO question now uses this bug as a feature.

some days i really hate stackoverflow...

**Comment by lamont-granquist** [comment]
actually @coderanger i'm before coffee this morning -- but i think with the recursive searching added everywhere that we can still fix this and preserve backcompat with that SO answer -- it just becomes a bit useless extra code.  we'll lower the target run_context down a level into the proper sub-resource collection, but then the resources line will still bubble up and find the resource...    and we fix the bug they have where they'll be able to call their provider from another provider and still find the resource in the outer run context...   do you concur?

**Comment by lamont-granquist** [comment]
at some point we must have fixed this because the code no longer raises.  maybe way back with the whole find_resource/edit_resource/with_run_context changes it got fixed as part of that...
