### ISSUE TITLE
Knife exit codes and messaging are inconsistent

### ISSUE THREAD

**Issue by tas50** [chef/chef#4671]
## Description

We're not very consistent with exit codes and error messaging in knife.  Some things just exit and show the usage banner while others show a warning about what the user failed to input. Some things exit with 1 while some exit with 0 even though they failed.  Others like knife help incorrectly exit with 1, which seems super odd. A simple method to toss up the usage banner, throw up a passed in failure message, and exit with 1 would really help keep this consistent everywhere.
## Chef Version

12.7.2
## Platform Version

Any
## Replication Case

Run some random knife plugins with bogus options and check stdout and the return code

**Comment by lamont-granquist** [comment]
#2981 related

**Comment by lamont-granquist** [comment]
#2293 related

**Comment by lamont-granquist** [comment]
#4268 related

**Comment by lamont-granquist** [comment]
I think this is too open ended of an issue to be useful.  This would be better treated by cutting tickets against the individual issues or by doing an audit and opening a single multiple-issue-big-checklist issue.  As an issue to track that we don't have the time to do the audit it isn't useful.
