### ISSUE TITLE
Fatal error when log dir not present seems kind of lame

### ISSUE THREAD

**Issue by jblaine** [chef/chef#4680]
## Description

chef-client fails to run if even the leaf log directory specified in `client.rb` does not exist (for example, `/var/log` exists but `/var/log/chef` does not exist)

This seems poor.

## Chef Version

12.6.0

## Platform Version

Don't think it matters, but RHEL 7

## Replication Case

1. Set `log_location "/var/log/chef/client.log"` in `/etc/chef/client.rb`
2. `sudo rm -rf /var/log/chef`
3. Run `chef-client`

## Client Output
```
[root@dalmore1 ~]# rm -rf /var/log/chef
[root@dalmore1 ~]# chef-client
[2016-03-09T09:41:22-05:00] FATAL: Failed to open or create log file at /var/log/chef/client.log: Errno::ENOENT (No such file or directory @ rb_sysopen - /var/log/chef/client.log)
[2016-03-09T09:41:22-05:00] FATAL: Aborting due to invalid 'log_location' configuration
[root@dalmore1 ~]#
```

**Comment by thommay** [comment]
I'd say this was entirely correct behaviour.

**Comment by coderanger** [comment]
:+1: current behavior is correct IMO.

**Comment by jblaine** [comment]
I guess it's subjective. IMO, the class of tools like CM tools should be resilient in the face of non-critical issues.

**Comment by thommay** [comment]
Not being able to do what the operator tells you to do is a critical issue.

**Comment by coderanger** [comment]
Beyond that, being unable to record logs of "I downloaded some code from a server and ran it as root" seems pretty critical to me.
