### ISSUE TITLE
chef-server-ctl  commands hangs 

### ISSUE THREAD

**Issue by melezhik** [chef/chef#4687]
## Description

chef-server-ctl  install opscode-manage
chef-server-ctl opscode-manage-ctl reconfigure
chef-server-ctl reconfigure 

And so on

Whatever command I run using chef-server-ctl  , it hangs.

I mean all I see at my console is "Chef Client started" and nothing happens then, for dozens of minutes. A weird thing though that if run "ps aux | grep chef-client" I can see a chef client running and doing it's job. If then I press CTRL+C and stopping chef-server-ctl  script _then_ I start to get output from running chef client and finally have "Chef Client finished" at my console telling me that chef client get it's job done.

So whatever command I run using chef-server-ctl and those running chef-client under the hood I need to "alive" chef-server-ctl script hitting CTRL+C

## Chef Version

chef-server-core-12.2.0-1.el6.x86_64.rpm

## Platform Version

Red Hat Enterprise Linux Server release 6.7 (Santiago)
Kernel \r on an \m

## Replication Case

See description

## Client Output

See description

## PS

This issue is based on https://discourse.chef.io/t/chef-server-ctl-install-opscode-manage-takes-too-much-time/7946

**Comment by thommay** [comment]
Hi,
please file chef-server issues in the chef-server repository, https://github.com/chef/chef-server/issues .

**Comment by melezhik** [comment]
https://github.com/chef/chef-server/issues/773
