### ISSUE TITLE
The MSI update detroying existing gem installations

### ISSUE THREAD

**Issue by lbn-aaio-team** [chef/chef#4688]
Hello Chef team :)

Here an issue we've encountred during update with the last v12.8.1 MSI package of chef-client.

## Description
When running chef-client MSI for updating, the gems that was installed before are not present anymore.

## Chef Version
12.7.2 update to 12.8.1

## Platform Version
Windows Server 2012 R2 

## Replication Case
- Install chef client with MSI 12.7.2
- Install a gem from a recipe:  chef_gem 'chef_handler_foreman'
- insert this line in your client.rb: require 'chef_handler_foreman' (be sure you install the gem before)
- run "chef-client" => it should works^^
Then:
- run the install of chef client with MSI 12.8.1
- run "chef-client"  => it fails with message "FATAL : Configuration error LoadError: cannot load such file -- chef_handler_foreman"

N.B, When comment the "require" line in client.rb, the chef-client running success and apply the install of the gem "chef_handler_foreman". This confirm that the gem has been detroy during update: 
[2016-03-10T15:13:18+01:00] INFO: chef_gem[chef_handler_foreman] installed chef_handler_foreman at
    - install version  of package chef_handler_foreman

## Client Output
PS C:\Users\Administrator> chef-client
[2016-03-10T14:19:32+01:00] FATAL: Configuration error LoadError: cannot load such file -- chef_handler_foreman
[2016-03-10T14:19:32+01:00] FATAL:   C:/chef/client.rb:12:in `from_string'
[2016-03-10T14:19:32+01:00] FATAL: Aborting due to error in 'C:/chef/client.rb'

## Stacktrace
no stack trace created during chef-client.

Best Regards;

LinkByNet devops team

**Comment by lamont-granquist** [comment]
not sure what changed, but this is also an often-asked-for-feature since old gems often fail to work across upgrades.

**Comment by lamont-granquist** [comment]
I don't think we can actually fix this.  If we bump the ruby version from 2.0.x to 2.1.x or 2.2.x then the gem paths change (/opt/chef/embedded/lib/ruby/gems/2.0.0 contains the ruby 'ABI' version) and this will always break so we can fundamentally never guarantee that this will ever work.

**Comment by thommay** [comment]
Fundamentally, any gems that you require in your chef run should be installed by your chef run, and appropriate steps taken to lazy load them at the right time. For newer versions of Chef, see the `gem` metadata flag ( https://docs.chef.io/config_rb_metadata.html ).
