### ISSUE TITLE
group provider on suse Linux adds user multiple times

### ISSUE THREAD

**Issue by mawinter69** [chef/chef#4689]
## Description

When modifying existing groups on Suse SLES11 without append the groups are not properly updated. The list of users is appended without removing any users, also if a user is already included is not considered. There was an old issue (https://tickets.opscode.com/browse/CHEF-3651) that claimed to have fixed it but actually it was not fixed.

## Chef Version

Any version, this bug is still in the master branch available

## Platform Version

SUSE SLES11 any SP and earlier, probably also in opensuse < 12.3

## Replication Case

group "cheftest" do
  members ["chef1","chef2"]
end

group "cheftest" do
  members ["chef1","chef2","chef3"]
end

The result in /etc/group should be
cheftest:!:2001:chef1,chef2,chef3
but is
cheftest:!:2001:chef1,chef2,chef1,chef2,chef3

With every change to members and subsequent chef run the group becomes bigger and bigger until the OS runs into an error and treats the group as empty.

The problem is in the file lib/chef/provider/group/suse.rb
in the method set_members 

## Fix
The correct implementation of this method would be

```
def set_members(members)
  to_delete =  @current_resource.members - members
  to_delete.each do |member|
    shell_out!("groupmod -R #{member} #{@new_resource.group_name}")
  end

  to_add = members -  @current_resource.members
  to_add.each do |member|
    shell_out!("groupmod -A #{member} #{@new_resource.group_name}")
  end
end
```

**Comment by lamont-granquist** [comment]
^ PR with that fix would be appreciated
