### ISSUE TITLE
knife bootstrap not working with a user which has sudo access.

### ISSUE THREAD

**Issue by saurav2104** [chef/chef#4695]
## Description

From my workstation under chef-repo , I am trying to bootstrap a Linux node by passing the following command `knife bootstrap my_machine -x test -P test123 --sudo --use-sudo-password`
The I get the error:

_'Doing old-style registration with the validation key at D:/chef-repo/.chef/oss-validator.pem...
_Delete your validation key in order to use your user credentials instead

Connecting to my_machine
my_machine Password:
my_machine Sorry, user test is not allowed to execute '/bin/sh -c'_
_
## Chef Version

Chef: 12.7.2

## Platform Version

Oracle Linux

## Replication Case

Done in desciption

## Client Output

Same as in the description

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by thommay** [comment]
Pretty sure the error tells you every thing you need - your sudo access doesn't permit the bootstrapper to run '/bin/sh -c'.
Try this with 
```
sudo /bin/sh -c "echo foo"
```

**Comment by saurav2104** [comment]
The output of given command:
`-bash-4.1$ sudo /bin/sh -c "echo foo"`
`foo`
`-bash-4.1$`
