### ISSUE TITLE
Missing cookbook dep results in misleading error

### ISSUE THREAD

**Issue by ianrossi** [chef/chef#4698]
## Description
Described originally here: https://tickets.opscode.com/browse/CHEF-4694
I can't login to the old site to post comments.

If there is a cookbook pinned in the cookbook_versions section of an environment and that same cookbook does not exist on the Chef Server, then the run fails but with the output below that indicates a 504 error for the API endpoint. A better error would be helpful here, like `Cookbook [NAME] does not exist on the Chef Server.`

Even better, a nice feature of the `knife environment from file ...` command would be to fail if there are cookbook constraints for cookbooks that don't exist on the Chef Server. Much like when you do a `knife cookbook upload [COOKBOOK]` and a dependency of `[COOKBOOK]` is either not on the Chef Server or not being uploaded.

This resulted from a cookbook name typo in the environment file. When uploaded, there was no indication of a problem. A lot of time was spent troubleshooting this and a more helpful error would be great. Thanks for Chef!!!

## Chef Version
Chef 12.7.3
Chef 12.5.1

Chef Server 11

## Platform Version
RHEL 6.5

## Replication Case
Upload an environment file to Chef Server that includes a version constraint in cookbook_versions for a cookbook that doesn't exist on the Chef Server.

## Client Output
Here is the relevant output from the client.log:
```
[2016-03-11T14:55:20-05:00] ERROR: Server returned error 504 for https://internal-chef.fortis.bose.com/environments/marge-efe-003/cookbook_versions, retrying 1/5 in 4s
[2016-03-11T15:00:24-05:00] ERROR: Server returned error 504 for https://internal-chef.fortis.bose.com/environments/marge-efe-003/cookbook_versions, retrying 2/5 in 6s
```

**Comment by coderanger** [comment]
This shouldn't happen with any recent Chef Server. 504 is a gateway timeout, meaning the solver didn't fail fast on an unknown artifact name.

**Comment by coderanger** [comment]
Client improvement isn't impossible, but I think we can probably rely on the server error messages given they would have quickly pointed to the issue.

**Comment by lamont-granquist** [comment]
Best the client can do here is return some kind of "solver timeout" error for a 504 on cookbook_versions.  This should really be refiled under http://github.com/chef/chef-server/issues/new

**Comment by Poohblah** [comment]
I ran into a very similar issue (504 gateway timeouts) a while ago and I was able to solve this issue by increasing the nginx gateway timeout on my chef server. For instance, I added the following line to `/etc/opscode/chef-server.rb`:

```
nginx['proxy_connect_timeout'] = '60s'
```

60 seconds is probably a bit high (1 second was the default, I believe), but I haven't had any problems with backends consuming too many resources either.
