### ISSUE TITLE
Chef client 12.7 & 12.8 errors out on pip install warnings

### ISSUE THREAD

**Issue by luckymike** [chef/chef#4702]
## Description

Chef client converge is incorrectly failing on pip warnings, even though the pip process exits with a 0 and succeeds. 

## Chef Version

chef-client 12.8 & 12.7

## Platform Version

Ubuntu 12.04

## Replication Case

You can run the [graphite cookbook](https://github.com/hw-cookbooks/graphite) test suite for ubuntu-12.

## Client Output

Note that running locally produces the same messages but the install is successful and it exits with a 0.

https://gist.github.com/luckymike/56d9ffb7be5ebb8030de

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by coderanger** [comment]
This would be a bug in the `python_pip` resource, except that cookbook (`python`) is deprecated and should be replaced with `poise-python`.

**Comment by luckymike** [comment]
@coderanger I believe you about updating to `poise-python` :) but can you provide a little info on the bug? It's strange to me that it presented in Chef 12.7, since the `python` cookbook has worked without issue since its last update in January 2014.

Did Chef previously miss the bug, and now does not? It seems like there's an actual behavioral change here. It would be nice to understand what it is in case it rears itself with other cookbooks, since nothing in the errors outwardly pointed to the `python` cookbook.

Thanks for the quick reply.

**Comment by coderanger** [comment]
If I had to guess it is something related to env vars, but "deprecated" means I don't run tests anymore and won't fix it regardless.

**Comment by luckymike** [comment]
@coderanger I just updated the graphite cookbook to use `poise-python` and the `python_package` resource in place of `python` and `python_pip` respectively. This worked fine as a drop-in replacement on 12.6. It fails with the exact same error on 12.7 & 12.8.

**Comment by luckymike** [comment]
Here's my branch with `poise-python` in place of `python`. Please re-open.

**Comment by luckymike** [comment]
Oops. Edited to include the branch link.
