### ISSUE TITLE
Chef client 12.7 & 12.8 errors out on pip install warnings (2nd attempt!)

### ISSUE THREAD

**Issue by luckymike** [chef/chef#4705]
## Description

Chef client converge is incorrectly failing on stdout/stderr messages, even though the shell process exits with a 0 and succeeds. Observed on pip specifically.

This is a dupe of #4702 which was closed without investigation, it appears. Please do not close this without first investigating. My best guess is that chef-client may be mishandling exit statuses where the process logs to stderr.

## Chef Version

chef-client 12.8 & 12.7

## Platform Version

Ubuntu 12.04

## Replication Case

You can run the [graphite cookbook(https://github.com/hw-cookbooks/graphite) integration test suite for ubuntu-12. 

The current `graphite` release uses the deprecated—but heretofore fully functional—`python` cookbook. I have created a branch that successfully replaced `python` with `poise-python` in a [branch](https://github.com/hw-cookbooks/graphite/tree/update/replace-python-cookbook), where you can also run the integration tests to see that changing the python cookbook does not alter the behavior.

## Client Output

https://gist.github.com/luckymike/56d9ffb7be5ebb8030de

Note that running locally produces the same messages but the install is successful and it exits with a 0.

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by luckymike** [comment]
Debug suggests the behavior difference is in the STDERR handling:

With 12.6:
```
       [2016-03-13T19:03:03+00:00] DEBUG: [python_package[uwsgi]] Running python command: /usr/bin/python2.7 -m pip.__main__ install uwsgi\=\=2.0.12
       The directory '/home/vagrant/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please ch
eck the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
       The directory '/home/vagrant/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the
 permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
       Collecting uwsgi==2.0.12
       /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made,
 but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
         SNIMissingWarning
       /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
         InsecurePlatformWarning
         Downloading uwsgi-2.0.12.tar.gz (784kB)
       Installing collected packages: uwsgi
         Running setup.py install for uwsgi: started
           Running setup.py install for uwsgi: finished with status 'done'
       Successfully installed uwsgi-2.0.12
```
With 12.7 & 12.8:
```
[2016-03-13T19:13:09+00:00] DEBUG: [python_package[uwsgi]] Running python command: /usr/bin/python2.7 -m pip.__main__ install uwsgi\=\=2.0.12
       The directory '/home/vagrant/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
       The directory '/home/vagrant/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
       Collecting uwsgi==2.0.12
       /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
         SNIMissingWarning
       /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
         InsecurePlatformWarning
         Downloading uwsgi-2.0.12.tar.gz (784kB)
       Installing collected packages: uwsgi
         Running setup.py install for uwsgi: started
           Running setup.py install for uwsgi: finished with status 'error'
```

**Comment by coderanger** [comment]
If this is still failing with `python_package` it would more likely be a bug in my cookbook, not in Chef itself. Every time you have posted output you are cutting off to what you think is important. Please don't do that, include the _full_ output.

**Comment by luckymike** [comment]
All you had to do was ask :)

I'm currently generating logs and stacktrace.out for both 12.8 and 12.7 failures using both the `python_package` and `python_pip` resources. I will post gists to all of them as soon as they're ready.

In the meantime, I have to ask why you believe that this is a bug in your code? 

It behaves the same way with both the old and new pip/python providers, and it has worked flawlessly prior to the 12.7 chef release. I'm happy to help troubleshoot by trying reasonable suggestions, but it helps to know that those are founded on more than a hunch.

**Comment by coderanger** [comment]
Because all my tests are passing against all versions of Chef, which likely points at something in your environment that my pip scripting isn't accounting for.

**Comment by luckymike** [comment]
I'm on the last converge to generate logs... 

Do your tests include a uwsgi or other install that generates a log to STDERR?
Have you tried the graphite tests? They use a "stock" ubuntu 12 opscode basebox. I've reproduced this on 2 different systems using test kitchen. As far as environments go, I'd argue that's pretty standard.

**Comment by luckymike** [comment]
Here are gists of the client log and stacktrace for both 12.7 & 12.8 using the current graphite cookbook release (the deprecated python providers) and a new branch of the graphite cookbook with the current poise-python providers. They are labelled with the version and release/poise as appropriate.

Hope these help!

https://gist.github.com/luckymike/2036c9dd861a82450c86

**Comment by coderanger** [comment]
So as the debug logs show, the failure is with linking against OpenSSL. This is probably related to `-L/opt/chef/embedded/lib`, which I shouldn't be passing in to the compile. I don't think I test any package with C extensions in general because the test already take ~6 hours for every run so adding more stuff is going to be tough until Test Kitchen's concurrent mode is made workable. The likely fix is to remove some environment variables that Chef is setting for compiler flags. If you dump environment variables from inside the Chef run, I would bet we started setting `$LD_FLAGS` or similar.

**Comment by luckymike** [comment]
Here's what I see for the ENV in the Chef run on 12.7:
```
MAIL: /var/mail/vagrant
SSH_CLIENT: 10.0.2.2 58097 22
USER: root
LANGUAGE: en_US:
SHLVL: 1
HOME: /home/vagrant
SSH_TTY: /dev/pts/0
LC_CTYPE: en_US.UTF-8
LOGNAME: root
_: /bin/sh
TERM: xterm
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/chef/embedded/bin:/opt/chef/embedded/bin
LANG: en_US.UTF-8
SSH_AUTH_SOCK: /tmp/ssh-aNSPcT1637/agent.1637
SHELL: /bin/bash
PWD: /home/vagrant
SSH_CONNECTION: 10.0.2.2 58097 10.0.2.15 22
USERNAME: root
SUDO_COMMAND: /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level warn --force-formatter --no-color --json-
attributes /tmp/kitchen/dna.json --chef-zero-port 8889
SUDO_USER: vagrant
SUDO_UID: 900
SUDO_GID: 900
```
and here's 12.6:
```
MAIL: /var/mail/vagrant
SSH_CLIENT: 10.0.2.2 58147 22
USER: root
LANGUAGE: en_US:
SHLVL: 1
HOME: /home/vagrant
SSH_TTY: /dev/pts/0
LC_CTYPE: en_US.UTF-8
LOGNAME: root
_: /bin/sh
TERM: xterm
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/chef/embedded/bin:/opt/chef/embedded/bin
LANG: en_US.UTF-8
SSH_AUTH_SOCK: /tmp/ssh-bCbSji1243/agent.1243
SHELL: /bin/bash
PWD: /home/vagrant
SSH_CONNECTION: 10.0.2.2 58147 10.0.2.15 22
USERNAME: root
SUDO_COMMAND: /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level warn --force-formatter --no-color --json-
attributes /tmp/kitchen/dna.json --chef-zero-port 8889
SUDO_USER: vagrant
SUDO_UID: 900
SUDO_GID: 900
```
The only differences are the SSH ports and AUTH_SOCK:
```
diff 12.7-env.txt 12.6-env.txt 
2c2
< SSH_CLIENT: 10.0.2.2 58097 22
---
> SSH_CLIENT: 10.0.2.2 58147 22
14c14
< SSH_AUTH_SOCK: /tmp/ssh-aNSPcT1637/agent.1637
---
> SSH_AUTH_SOCK: /tmp/ssh-bCbSji1243/agent.1243
17c17
< SSH_CONNECTION: 10.0.2.2 58097 10.0.2.15 22
---
> SSH_CONNECTION: 10.0.2.2 58147 10.0.2.15 22
```
I also did 12.8, same story: 
```
MAIL: /var/mail/vagrant
SSH_CLIENT: 10.0.2.2 58453 22
USER: root
LANGUAGE: en_US:
SHLVL: 1
HOME: /home/vagrant
SSH_TTY: /dev/pts/0
LC_CTYPE: en_US.UTF-8
LOGNAME: root
_: /bin/sh
TERM: xterm
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/chef/embedded/bin:/opt/chef/embedded/bin
LANG: en_US.UTF-8
SSH_AUTH_SOCK: /tmp/ssh-WKyTcn1266/agent.1266
SHELL: /bin/bash
PWD: /home/vagrant
SSH_CONNECTION: 10.0.2.2 58453 10.0.2.15 22
USERNAME: root
SUDO_COMMAND: /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level warn --force-formatter --no-color --json-attributes /tmp/kitchen/dna.json --chef-zero-port 8889
SUDO_USER: vagrant
SUDO_UID: 900
SUDO_GID: 900
Converging 59 
```
This should be easily reproducible if you download the graphite cookbook and run the ubuntu-12 test suite (there's only one). The converge takes all of 5 minutes, so it's fairly easy to experiment with different ideas.

This looks like a regression in chef-client. I've provided the steps to reproduce, and if someone else can clearly demonstrate a successful converge of those recipes with 12.7 & 12.8, I'm open to learning that the problem is elsewhere and helping to test a solution. In the meantime I can't take time to exercise more guesswork for the sake of proving myself wrong.

I hope this issues gets some more eyes this week.

**Comment by lamont-granquist** [comment]
@luckymike I don't see where "Chef client converge is incorrectly failing on stdout/stderr messages, even though the shell process exits with a 0 and succeeds" when every error message you've got pretty clearly indicates "Expected process to exit with [0], but received '1'"

I also don't see how this is a core chef problem.

The python_pip resource should not be using `-L/opt/chef/embedded/lib` or `-I/opt/chef/embedded/include` or anything similar that passes `-L` or `-I` flags into /opt/chef into the native build.   Since the resource is building stuff to install into the O/S python instance that's inappropriate, and the result is that libraries like openssl that are included twice can wind up with a 'diamond' dependency problem -- the core python binary and libs will be linked against core openssl in the distro, while what you are building is linked against openssl in omnibus -- and the result is that when both are linked into the same process it'll explode with linker errors like this.

I don't see the bug to fix here in core chef.

Its possible that this 'broke' with upgraded openssl libs in omnibus as well, but it is not a 'regression' since this approach is always broken on /some/ distros (either distros with openssl that are older than the version in omnibus or newer -- and switching the ominbus versions around will just push around which distros are broken).

**Comment by coderanger** [comment]
What he said, I don't see how this is anything other than a bug in my code.

**Comment by luckymike** [comment]
@lamont-granquist Well, I was questioning that "Expected process to exit with [0], but received '1'" because running the process manually produces the exact same output but the process exits with a 0 and everything is copacetic, but that obviously would not account for the embedded libraries as you've explained. That makes sense, thank you.

@coderanger Would you like me to open an issue against poise-python.

**Comment by coderanger** [comment]
@luckymike I made one, thanky :)
