### ISSUE TITLE
Issues with checksum mismatch on Chef-clients Version 12 and higher

### ISSUE THREAD

**Issue by satinrichu** [chef/chef#4746]
## Description
 We have upgraded chef-client on one of cluster hosts and running into checksum mismatch errors, while other nodes dont seem to have any issues and all cookbooks and recipres work like sweet. Please advise what is issue with new chef-clients and fi for same.
Briefly describe the issue

## Chef Version
12.4.3
Tell us which version of chef-client you are using (see below for Server+ChefDK bugs).
$ chef-shell --version
Chef: 12.4.1
## Platform Version
Linux
Tell us which Operating System distribution and version chef-client is running on.
Windows and Linux
## Replication Case
Checksum error on all nodes which has Version 12 or more
Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

## Stacktrace
 Error executing action `create_if_missing` on resource 'remote_file[/var/chef/cache/
: Chef::Exceptions::ChecksumMismatch: Checksum on resource (9565dd) does not match checksum on content (fd06b4)

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY
Ok
This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc NA.

* [Server issues](https://github.com/chef/chef-server/issues/new) NA
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new) NA
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google) NA

**Comment by lamont-granquist** [comment]
You're not giving enough information to debug the problem.

Its likely that chef-client 12.x is now validating checksums instead of just using it to check idempotency and you need to update the checksums in your cookbook, but its impossible to tell from the information that you've described.  We'd need substantially more complete chef-client runs, including the cookbooks and recipes that were trying to be converged along with the complete contents of the stacktrace.out file.
