### ISSUE TITLE
knife bootstrap gives policy-... errors when it shouldn't

### ISSUE THREAD

**Issue by daften** [chef/chef#4756]
## Description

When issuing knife bootstrap with the latest knife from chefdk (0.12.0), I get an unexpected error. This is purely a knife error, if I need to post in ChefDK for some reason, please let me know.

## Chef Version

ChefDK 0.12.0 for Mac OS X 10.11

## Platform Version

Max Os X 10.11.4 en chefDK 0.12.0

## Replication Case

Try to bootstrap a server with the knife.rb file from attachment (as knife.txt)
[knife.txt](https://github.com/chef/chef/files/190216/knife.txt)

bootstrap command:
knife bootstrap FQDN -N FQDN --ssh-user chef_user --sudo --environment staging --run-list 'recipe[chef-client::cron],role[...]'

## Client Output

INFO: Using configuration from .../chef-repo/.chef/knife.rb
ERROR: --policy-name and --policy-group must be specified together

**Comment by daften** [comment]
After debugging some more, it seems :policy_group=>"local" is set as an option. I don't understand how this happened though :s

**Comment by daften** [comment]
It also seems it has to do with my local setup, since reverting to previous versions of chefdk (until 0.11.0) doesn't fix it. Anybody that can help out?

**Comment by daften** [comment]
Apparently, knife-zero is the culprit. After issuing knife zero diagnose, i noticed it was  Zero Bootstrap Config that put policy_group local there. Probably a fault in knife-zero.

**Comment by lamont-granquist** [comment]
yeah its a knife-zero bug #4758
