### ISSUE TITLE
Discussion: Verification command output

### ISSUE THREAD

**Issue by coderanger** [chef/chef#4793]
Filing this as a ticket because I don't see a straightforward implementation. Right now when we run a verification command and it fails all the user sees is something like this:

``````
   Error executing action `create` on resource 'monit_check[nginx]'
    ================================================================================

    Chef::Exceptions::ValidationFailed
    ----------------------------------
    file[/etc/monit/conf.d/nginx.conf] (/var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit_config.rb line 90) had an error: Chef::Exceptions::ValidationFailed: Proposed content for /etc/monit/conf.d/nginx.conf failed verification #<Chef::Resource::File::Verification:0x00000003dc3ae0>

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/poise/files/halite_gem/poise/helpers/notifying_block.rb:69:in `notifying_block'
    /var/chef/cache/cookbooks/poise-monit/files/halite_gem/poise_monit/resources/monit_config.rb:72:in `action_create'```
``````

Notably we don't show the actual verification command if there was one (easy to fix, I can handle that) and we don't show the command output. Most tools with a syntax check option (`nginx -t`, `monit -t`) will print some debugging message indicating what the error is, which would be valuable to bubble up the chain. This is difficult though, because we are re-using the resource guard system and that doesn't expose command output as part of its API. A possible work-around is that good cookbooks shouldn't use the command form of `verify` and should instead use a block with `shell_out!` more directly, and raise the exception themselves. That's a bit weird though. What say we all.

**Comment by coderanger** [comment]
Ping @chef/client-core for thought :)

**Comment by lamont-granquist** [comment]
Yeah definitely :+1: on showing the verification command.

The command output would also be very good, although 'sensitive' resources should probably have that suppressed as well.  If its difficult to disentangle that code, i'd be happy with only showing the verification command for now, and having a TODO to add the output.

**Comment by coderanger** [comment]
Yeah, showing the command would at least hint people that it isn't my code doing the wrong thing. I think that's an easy first step :) The output is the dicey bit. We would either need to not use the guard APIs, or extend those APIs to expose command output somehow (probably not possible given how they work internally).

**Comment by lamont-granquist** [comment]
in #8249 phil mentions he'd like to be able to get at the file contents in addition to the output.

**Comment by tas50** [comment]
The first component of this we did fix. You can now see the actual command that would be run, but we should really fix chef runs to show the output of the command. It would be really useful for debugging cookbook runs.

**Comment by jaymzh** [comment]
Yeah it doesn't help if you have a complicated template that generates a file, and then the verifier output of your 20 line template is: `Unexpected ] on line 115`

We *really* need to preserve the actual *file*.

Literally **EVERY** time we've hit a verifier fail, someone's asked me "well, how can I see what the generated file was?" and then we copy-paste the template block change the path to `/tmp` and drop the verifier, run chef again, take the rendered file, go look at line 115, see what was wrong, then go look at the template source and go "oh I see how that can happen."

Unless you're building fragile templates with line-for-line content that have to be updated every single time the software consuming the rendered file adds a new field the verifier output will almost never be useful without the rendered file.
