### ISSUE TITLE
windows_service does not support :reload

### ISSUE THREAD

**Issue by spuder** [chef/chef#4796]
## Description

Using `windows_service` [as documented here](https://docs.chef.io/resource_windows_service.html), with :reload throws error:

>   #Chef::Provider::Service::Windows:0x36eee00 does not support :reload

Using any other resource "enable", "configure_startup" ect.. works without problem. 

Looking at the source, it seems that the 'reload' method is not defined. 

https://github.com/chef/chef/blob/master/lib/chef/provider/service/windows.rb
## Chef Version

12.8.1
## Platform Version

Windows 2012 R2
## Replication Case

``` ruby
windows_service 'SomeService' do
  run_as_user 'foobar'
  run_as_password 'correct-horse-battery-staple'
  action :reload
end
```
## Client Output

```
* windows_service[AspireService] action reload
           * #<Chef::Provider::Service::Windows:0x36eee00> does not support :reload
           ================================================================================
           Error executing action `reload` on resource 'windows_service[AspireService]'
           ================================================================================

           Chef::Exceptions::UnsupportedAction
           -----------------------------------
           #<Chef::Provider::Service::Windows:0x36eee00> does not support :reload

           Resource Declaration:
           ---------------------
           # In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/nd-aspire/recipes/default.rb

           122: windows_service 'SomeService' do
           123:   
           124:   run_as_user 'foobar'
           125:   run_as_password 'correct-horse-battery-staple'
           126:   action :reload
           127: end
```

**Comment by coderanger** [comment]
Does Windows even have this? I don't think windows has anything generic like SIGHUP for behavior like this.

**Comment by spuder** [comment]
Doubt it. The closest thing would probably be `sc.exe config` 

http://ss64.com/nt/sc.html

**Comment by coderanger** [comment]
Seems like this should be a doc update then :-)

**Comment by thommay** [comment]
Agreed, this is a documentation update @jamescott

**Comment by lamont-granquist** [comment]
This looks like the error message is 100% accurate -- "does not support reload"

**Comment by spuder** [comment]
There is a `reload_command` attribute documented. I think the resource *should* support reload, but only if the user has defined a `reload_command` attribute.

**Comment by stuartpreston** [comment]
PR opened against the docs (https://github.com/chef/chef-web-docs/pull/1503) - closing this now.
