### ISSUE TITLE
Documentation don't include how to setup mail server during deployment of Chef server

### ISSUE THREAD

**Issue by theWoodman** [chef/chef#4807]
## Description

In all documentation i could find I have not be able to note any documentation on how to setup or configure the Chef server for a specific SMTP relay. 

Nor:
https://learn.chef.io/
or 
https://docs.chef.io/install_server.html#standalone

## Chef Version

12.4.1

## Platform Version

Ubuntu 14.04.3

## Replication Case

Follow the steps in guide here: https://docs.chef.io/install_server.html#standalone
like: 
1. have VM
2. download chef server package
3. deploy server package with dpkg -i
4. install chef manage
5. Log in as new admin account
6. add new user to new org

## Client Output

No mails is sent when e.g. adding new users.

## Stacktrace

[none]

**Comment by lamont-granquist** [comment]
this is definitely a chef-server bug so is misfiled here and needs to go under https://github.com/chef/chef-server/issues/new
