### ISSUE TITLE
chef client - error during  Knife configure -i 

### ISSUE THREAD

**Issue by get2arun** [chef/chef#4814]
## Description

I face the issue when running "**knife configure -i**" in Chef client. In addition to the error, I see the warning message like below. Any clue to resolve this error. I am using Chef client _chef-12.8.1-1.el7.x86_64_ and running on redhat 7 machine. I use the Chef server chef-server-11.1.7-1.el6.x86_64. 
## Chef Version

chef-12.8.1-1.el7.x86_64
## Platform Version

Redhat 7.1 in chef client
## Replication Case

step 1. Setup open source Chef server in Redhat 6.7
Step 2. Login to Chef worksatation(redhat 7.1 in my case) and Copy the keys(.pem) files from Chef server to Chef workstation path /root/.chef/ 
Step 3. install and chef client and execute the "knife configure -i"
## client Output

**Error is below.**
[root@SERVER_NAME .chef]# knife configure -i
WARNING: No knife configuration file found
Where should I put the config file? [/root/.chef/knife.rb]
Please enter the chef server URL: [https://SERVER_NAME.com:443] https://SERVER_NAME.com:443
Please enter a name for the new user: [Userid] chef_user_account_in_chef_server
Please enter the existing admin name: [admin] admin
Please enter the location of the existing admin's private key: [/etc/chef-server/admin.pem] /root/.chef/admin.pem
Please enter the validation clientname: [chef-validator]
Please enter the location of the validation key: [/etc/chef-server/chef-validator.pem] /root/.chef/chef-validator.pem
Please enter the path to a chef repository (or leave blank):
Creating initial API user...
Please enter a password for the new user:
**WARNING: IF YOU ARE USING CHEF SERVER 12+, PLEASE FOLLOW THE INSTRUCTIONS UNDER knife user create --help.**
You only passed a single argument to knife user create.
For backwards compatibility, when only a single argument is passed,
knife user create assumes you want Open Source 11 Server user creation.
knife user create for Open Source 11 Server is being deprecated.
Open Source 11 Server user commands now live under the knife osc_user namespace.
For backwards compatibility, we will forward this request to knife osc_user create.
**If you are using an Open Source 11 Server, please use that command to avoid this warning.
FATAL: Cannot find subcommand for: 'osc_user configure -i'**
Available subcommands: (for details, knife SUB-COMMAND --help)

*\* BOOTSTRAP COMMANDS **
knife bootstrap [SSH_USER@]FQDN (options)
(...output truncated)

Do I need to downsize the chef-client to some version of 11 to work with Chef server 11.x. Please advice.

**Comment by lamont-granquist** [comment]
@tylercloke can you take a look at this one?  seems to be that knife osc_user configure does not exist or something...

**Comment by saigosan** [comment]
I hit this same problem today, using latest chef client version - 12.11.18-1.el7.x86_64.rpm on  CentOS 7.2.1511

**Comment by ldormoy** [comment]
Any solution for this? I ran into the exact same problem

chef dk:       2.4.17
chef server: 12.19.36
OS:              Ubuntu 16.04

**Comment by marcparadise** [comment]
This is still occurring in  Chef 16+, but the error is slightly different because of the removed support for deprecated form of `knife user create`: 

```
Please enter a password for the new user:  
USAGE: knife user create USERNAME DISPLAY_NAME FIRST_NAME LAST_NAME EMAIL PASSWORD (options)
    -f, --file FILE                  Write the private key to a file if the server generated one.
    -k, --prevent-keygen             API V1 (Chef Infra Server 12.1+) only. Prevent server from generating a default key pair for you. Cannot be passed with --user-key.
        --user-key FILENAME          Set the initial default key for the user from a file on disk (cannot pass with --prevent-keygen).
FATAL: You must specify a display name
```

**Comment by tas50** [comment]
We fixed this in 17!
