### ISSUE TITLE
cookbook name not taken into account in local mode or chef-zero

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#4816]
## Description

In local mode, the directory name is used as the name of the cookbook, not the `name` in metadata.rb

So if you have a cookbook called `foo`, but the dir name is `foo_test` and inside of `foo` you do `include_recipe 'foo::some_recipe'` it'll complain that:

```
Cookbook foo not found. If you're loading foo from another cookbook, make sure you configure the dependency in your metadata
```

Frankly, I was a proponent of adding a Foodcritic rule that required to be the same but @lamont-granquist  (I think) chimed in that having them able to be separate is super important. I ended up using this to test something and it turns out not to work.
## Chef Version

12.8.1
## Platform Version

CentOS 7
## Replication Case

See above.
## Client Output

See above.

**Comment by lamont-granquist** [comment]
are you missing the `name "foo"` inside the metadata.rb of that cookbook though?

**Comment by jaymzh** [comment]
No - that's the thing I set...  :)

**Comment by lamont-granquist** [comment]
yep, dat be broken
