### ISSUE TITLE
cookbook show definitions throws exception.

### ISSUE THREAD

**Issue by chinni505** [chef/chef#4821]
## Description

while ran below command i am seeing below issues.

fyi:
chinnapas-MacBook-Air:cookbooks chinni$ knife cookbook show iptables 0.14.0 definitions
ERROR: The object you are looking for could not be found
Response: Cannot find a cookbook named iptables with version 0.14.0
chinnapas-MacBook-Air:cookbooks chinni$ knife cookbook show iptables 2.2.0 definitions
ERROR: knife encountered an unexpected error
This may be a bug in the 'cookbook show' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `manifest' for #<Hash:0x007fd6f93a6ad8>

## Chef Version
12.8.1

debug output:

chinnapas-MacBook-Air:cookbooks chinni$ knife cookbook show iptables 2.2.0 definitions -VV
INFO: Using configuration from /Users/chinni/Desktop/chef/chef-repo/.chef/knife.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as chinni505
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://api.chef.io/organizations/chinops/cookbooks/iptables/2.2.0
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-Ops-Server-API-Version: 1
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.1;
DEBUG: X-OPS-USERID: chinni505
DEBUG: X-OPS-TIMESTAMP: 2016-04-12T04:37:52Z
DEBUG: X-OPS-CONTENT-HASH: 2jmj7l5rSw0yVb/vlWAYkK/YBwk=
DEBUG: X-OPS-AUTHORIZATION-1: oeJL50Qu66etXz5zjZ9AhMGXFiSBwuMZwA8gwZJPw/MzJnqh+2+S9+IXN2+u
DEBUG: X-OPS-AUTHORIZATION-2: MyXYEg46xz4cuvdqTQviLHiBvikRMxUt0ydMuj9pcDGDZWwGoaD5vjKrS1eZ
DEBUG: X-OPS-AUTHORIZATION-3: 0EsIssWLoZz5igzO+SaRtNK/fn40U42Sn2BOF+SlYLP01ggxROZbcSg5s5Tf
DEBUG: X-OPS-AUTHORIZATION-4: 1flcGUEiNB6zmV8dQ7ewE+fm4E6NR5Qado2rAgZgID11QiCW2XeEJxyRCV8Z
DEBUG: X-OPS-AUTHORIZATION-5: cepfix3kU22j4vUTDqx3Y0H8PvrrADQMbsAG99WlhIa41++JkEVDrhjrA2C9
DEBUG: X-OPS-AUTHORIZATION-6: E7H6uWZC+nUnqFsYmOaFLXo0hUniewKBM8r6KUy0sA==
DEBUG: HOST: api.chef.io:443
DEBUG: X-REMOTE-REQUEST-ID: 4c751557-78b8-4f7f-9a4e-20cb3838e5bb
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: content-encoding: gzip
DEBUG: content-type: application/json
DEBUG: date: Tue, 12 Apr 2016 04:37:53 GMT
DEBUG: server: openresty/1.9.3.1
DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=12.4.2+20160205150224
DEBUG: x-ops-server-api-version: {"min_version":"0","max_version":"1","request_version":"1","response_version":"1"}
DEBUG: content-length: 3616
DEBUG: connection: Close
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife/cookbook_show.rb:81:in `run': undefined method `manifest' for #<Hash:0x007f878c8af618> (NoMethodError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/knife.rb:219:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/lib/chef/application/knife.rb:148:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/embedded/bin/knife:22:in `load'
	from /opt/chefdk/embedded/bin/knife:22:in `<main>'

**Comment by lamont-granquist** [comment]
not a valid command so this boils down to needing a better error message

**Comment by tomkadwill** [comment]
I'm new to Chef, can I have a go at this? Is there a deadline for this bug fix?

**Comment by klausyoum** [comment]
Dear @lamont-granquist,

I also found the error message even though my command looks like valid. Could you tell me my missed point or something wrong? If this is a bug, I hope this bug is fixed in near future.

chef$ chef -v
Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.3.0
kitchen version: 1.6.0


chef$ knife cookbook show my_cookbook 0.1.1 files
ERROR: knife encountered an unexpected error
This may be a bug in the 'cookbook show' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `manifest' for #<Hash:0x00000003cc57d8>

Regardschefadmin@ip-172-31-21-87:~/products/chef-demo$ chef -v
Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.3.0
kitchen version: 1.6.0

Thanks.

**Comment by andibachmann** [comment]
Hello @lamont-granquist 

I experience the same error message as @chinni505 (same stack trace, with almost similar tools, i.e. only last version digits differ) . 
You said: 
>  not a valid command so this boils down to needing a better error message

How can I help to provide a better error message?

regards
andi

**Comment by asychev** [comment]
Same for me:

$ knife cookbook show base 0.3.22 files
ERROR: knife encountered an unexpected error
This may be a bug in the 'cookbook show' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `manifest' for #<Hash:0x007f812f211a30>

-VV:

/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/knife/cookbook_show.rb:81:in `run': undefined method `manifest' for #<Hash:0x007fe687178d18> (NoMethodError)
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/knife.rb:219:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/knife.rb:148:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/bin/knife:25:in `<top (required)>'
        from /usr/local/bin/knife:51:in `load'
        from /usr/local/bin/knife:51:in `<main>'

Chef Development Kit Version: 0.14.25
chef-client version: 12.10.24
berks version: 4.3.3
kitchen version: 1.8.0

$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

**Comment by thommay** [comment]
fixed in Chef 12.11.18 by #4936, please upgrade. ( https://discourse.chef.io/t/pre-release-chef-dk-0-15-9-announcement/8664 )
