### ISSUE TITLE
12.5 Custom Resource actions using definitions do not behave as expected

### ISSUE THREAD

**Issue by veetow** [chef/chef#4825]
## Description

12.5 Custom Resource actions using definitions do not behave as expected.

## Chef Version

12.4.0

## Platform Version

CentOS 6.6

## Replication Case

Given a custom resource like so:
```
property :log_path

action :install do
  logrotate_app 'my_logs' do
    cookbook 'logrotate'
    path [::File.join(log_path, '*.log')]
    # ...
  end
end
```

`log_path` will evaluate as `nil`.

Prepending `new_resource` to `log_path` will result in an exception:

```
 ================================================================================
 Error executing action `install` on resource 'with_definition[test]'
 ================================================================================
 
 NoMethodError
 -------------
 undefined method `log_path' for []:Array
 
 Cookbook Trace:
 ---------------
 ...
 /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:122:in `instance_eval'
 /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:122:in `compile_and_converge_action'
 
```

The only workaround that I've found is to instantiate a temporary variable with the value of the property and pass that into the definition, i.e.:

```
property :log_path

action :install do
  my_log_path = log_path.dup

  logrotate_app 'my_logs' do
    cookbook 'logrotate'
    path [::File.join(my_log_path, '*.log')]
    # ...
  end
end
```

That works as expected.

**Comment by coderanger** [comment]
This is expected. Definitions don't do the automatic `enclosing_provider` scope promotion that resources do. I would put this under "don't use definitions", but that's just me.

**Comment by veetow** [comment]
I would counter that without full knowledge of the goings on "behind the scenes" (it was sorta the point of the new custom resources to make writing them simpler), it is _entirely_ unexpected.

Also, plenty of existing community cookbooks use definitions, especially `logrotate_app`, so it's hardly valid to say not to use them.

**Comment by coderanger** [comment]
@veetow Definitions have been in a weird gray area for a long time. Not technically deprecated, but also very clearly second-class citizens compared to resources. They should be best thought of as top-level macros, not building blocks that can be used inside other building blocks.

**Comment by stevendanna** [comment]
`logrotate_app` definitely needs to be changed into being a resource.  It is my hope to do that this weekend as I also have some PRs that are piling up all of which require me to modernize the test setup of the logrotate cookbook.  

Hopefully, for logrotate_app specifically we can clear this problem up on the cookbook side.

Can we put a warning in place for when someone uses a definition in a resource like this?

**Comment by veetow** [comment]
@coderanger, I understand and don't disagree overall, but as I mentioned, there are many definitions out there in the community, and there's no obvious deterrent from using one of them in a custom resource.

@stevendanna that's great news re: `logrotate_app`.

**Comment by lamont-granquist** [comment]
Does this even work inside of old-school providers?

**Comment by coderanger** [comment]
I don't think so, there is also no special handling for `new_resource` so you had to do the same thing there too.

**Comment by lamont-granquist** [comment]
verified with an old school provider.

this is just ruby scope issues and is another reason why definitions are discouraged.  assigning to a local variable is the correct ruby way to get the state into your binding.  so the workaround is actually the appropriate fix and/or just don't use definitions.
