### ISSUE TITLE
Do not set a default distribution on apt_repository resource

### ISSUE THREAD

**Issue by eherot** [chef/chef#4828]
## Description

Having this as a default is not a good idea because some Apt repos do not use a distribution and having this here makes it impossible to use them. Also, it is a different behavior than the existing apt cookbook, which causes it to break backwards compatibility.

## Chef Version

12.9.38

## Platform Version

Ubuntu/Debian (any)

## Replication Case

Apt repositories that do not use a distro (e.g. [Elastic Beats](https://www.elastic.co/guide/en/beats/libbeat/current/setup-repositories.html)

## Client Output

```
       STDERR: W: Failed to fetch https://packages.elastic.co/beats/apt/dists/trusty/stable/binary-amd64/Packages  HttpError404

       W: Failed to fetch https://packages.elastic.co/beats/apt/dists/trusty/main/binary-amd64/Packages  HttpError404

       E: Some index files failed to download. They have been ignored, or old ones used instead.
       ---- End output of apt-get -q update ----
       Ran apt-get -q update returned 100; ignore_failure is set, continuing

             ================================================================================
             Error executing action `update` on resource 'apt_update[beats]'
             ================================================================================

             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             execute[apt-get -q update] (/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.9.38/lib/chef/provider/apt_update.rb line 75) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
```

**Comment by coderanger** [comment]
Why does it make it impossible? You can always set your own value for it, the codename is the a default for that property.

**Comment by eherot** [comment]
Because the correct value in this case is no value at all. Here's the "correct" output file:
```
deb     "https://packages.elastic.co/beats/apt" stable main
```
Setting the value to `''` does work but it feels like a bit of a kludge.

**Comment by lamont-granquist** [comment]
#4832 fixes this although does not change the default.
