### ISSUE TITLE
Could not establish a secure connection to the server

### ISSUE THREAD

**Issue by coolshare** [chef/chef#4836]
## Description
 I run "client list" I got

```
$ knife client list
ERROR: SSL Validation failure connecting to host: chefserver.example.com - SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
ERROR: Could not establish a secure connection to the server.
Use knife ssl check to troubleshoot your SSL configuration.
If your Chef Server uses a self-signed certificate, you can use
knife ssl fetch to make knife trust the server's certificates.

Original Exception: OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
```

But the odd thing is that both "check" and "fetch" return normally

```
mqian@chefwork:~/chef-repo$ knife ssl check
Connecting to host chefserver:443
Successfully verified certificates from `chefserver'

mqian@chefwork:~/chef-repo$ knife ssl fetch
WARNING: Certificates from chefserver will be fetched and placed in your trusted_cert
directory (/home/mqian/chef-repo/.chef/trusted_certs).

Knife has no means to verify these are the correct certificates. You should
verify the authenticity of these certificates after downloading.

Adding certificate for chefserver in /home/mqian/chef-repo/.chef/trusted_certs/chefserver.crt
```

## Chef Version

Tell us which version of chef-client you are using (see below for Server+ChefDK bugs).
 Chef Version: 12.3.0
## Platform Version

Tell us which Operating System distribution and version chef-client is running on.
Ubuntu 14.04 desktop

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by lamont-granquist** [comment]
are you using the omnibus packages for 12.3.0 or are you using RVM, and which version of the openssl libraries are you linking against?

see http://stackoverflow.com/questions/25814210/opensslsslsslerror-ssl-connect-syscall-returned-5-errno-0-state-sslv3-read

**Comment by thommay** [comment]
Hey, just to make sure: in the output from `knife ssl check` you have `chefserver`, but in `knife client list` you have `chefserver.example.com`; is this just you redacting your urls by hand, or are they actually different?

**Comment by coolshare** [comment]
I actually have both chefserver and chefserver.example.com in both server and client's hosts



Regards

Mark

**Comment by btm** [comment]
What is in your client.rb for `chef_server_url`?

**Comment by coolshare** [comment]
Since I was installing workstation so I don't have a client.rb.

I only have ~/chef-repo/.chef/knife.rb:


log_level                :info
log_location             STDOUT
node_name                'admin'
client_key               '~/chef-repo/.chef/admin.pem'
validation_client_name   'hds-validator'
validation_key           '~/chef-repo/.chef/hds.pem'
chef_server_url          'https://chefserver/organizations/hds'
syntax_check_cache_path  '~/chef-repo/.chef/syntax_check_cache'
cookbook_path [ '~/chef-repo/cookbooks' ]



Regards 



Mark 






Date: Wed, 20 Apr 2016 10:17:45 -0700

**Comment by btm** [comment]
Yeah, I meant knife.rb

Have you tried changing your `chef_server_url` to `https://chefserver.example.org/organizations/hds`?

**Comment by coolshare** [comment]
Yes, I did but the same result. Does chef use its own proxy setting for reconfigure?
I could ping, telnet, and wget with no problem...



Regards 



Mark 






Date: Wed, 20 Apr 2016 10:24:14 -0700

**Comment by lamont-granquist** [comment]
If you (re-)install the omnibus package for 12.3.0 and attempt to replicate does it still fail?

```
% curl https://omnitruck.chef.io/stable/install.sh | sudo bash -s -- -v 12.3.0
% /opt/chef/bin/knife client list
```

**Comment by thommay** [comment]
can you also run
```
/opt/chef/embedded/bin/openssl s_client -connect chefserver:443 -showcerts
```
```
/opt/chef/embedded/bin/openssl s_client -connect chefserver.example.org:443 -showcerts
```

and send the output to thom@chef.io (or suitably expurgate them and post them here)

**Comment by thommay** [comment]
Hi,
I'm going to close this issue for lack of response. Should you feel this isn't correct, please reopen the ticket with the information we requested.
Thanks for using Chef!
