### ISSUE TITLE
Last check-in time ahead by 7 hours

### ISSUE THREAD

**Issue by chef09210** [chef/chef#4848]
## Description

Last check-in time on Chef Server for recently converged Node displays as 'In 7 hours' instead of when it actually checked in.

## Chef Version

12.9.38.1

## Platform Version

Windows 7 Enterprise 64-bit

## Replication Case

Initiate a chef-client run on a node
Check the Chef Manage UI for last check in time

## Client Output

https://gist.github.com/chef09210/c7b5394f3acb29e89b58ef4497d57b83

## Stacktrace

https://gist.github.com/chef09210/c7b5394f3acb29e89b58ef4497d57b83

**Comment by coderanger** [comment]
Usually means the server has the right time but the wrong timezone.

**Comment by coderanger** [comment]
(or just the wrong time, but that's easier to notice)

**Comment by lamont-granquist** [comment]
Yeah in chef this is saved as the epoch time so there's no bug in the chef/chef or chef/ohai codebase, so at a minimum this is filed incorrectly.  Probably needs to go under https://github.com/chef/chef-server/issues/new unless manage has a public github issue tracker?

**Comment by smurawski** [comment]
Or given that manage is a premium feature, file a Zendesk ticket with support.

**Comment by chef09210** [comment]
You're right it was an issue with the timezone on the node
