### ISSUE TITLE
knife ssh search doesn' t find nodes

### ISSUE THREAD

**Issue by gliptak** [chef/chef#4853]
## Description

```knife ssh search``` doesn' t find nodes shown in ```knife search node```

I read http://serverfault.com/questions/346418/knife-ssh-doesnt-find-my-nodes (from 2012) and validated that I have FQDN  in ```knife node show``` and the machine (names) are in DNS.

## Chef Version

```
chef --version
Chef Development Kit Version: 0.12.0
chef-client version: 12.8.1
berks version: 4.3.0
kitchen version: 1.6.0
```
## Platform Version

```
cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)
```

## Replication Case

```
knife search node "name:*" 
3 items found
...
```
```
knife ssh search "name:*" "uptime"
FATAL: No nodes returned from search!
```

**Comment by thommay** [comment]
Hi,
the correct command is `knife ssh "name:*" "uptime"` . You're currently executing a search for `search` and, probably not surprisingly, not getting any results.
Thanks for the report.

**Comment by gliptak** [comment]
@thommay Thank you for pointing out my typo

**Comment by gliptak** [comment]
Could the search term be included in the error message (this would likely make it easier to spot this ...)? Thanks
