### ISSUE TITLE
Chef-Client run with empty runlist takes 7+ minutes on Windows 7 Enterprise

### ISSUE THREAD

**Issue by chef09210** [chef/chef#4854]
## Description

When initiating a chef-client run on a Windows 7 Enterprise 64-bit node with an empty runlist, the process takes an inordinate amount of time, from 7-11+ minutes

## Chef Version

12.9.38.1 x64

## Platform Version

Windows 7 Enterprise 64-bit

## Replication Case

Install chef-client on Windows 7 Enterprise 64-bit node
Run 'chef-client -l debug' in a Powershell window

## Client Output

https://gist.github.com/chef09210/1b444b56ac5fef36a3801837631ff4ff

Note:
[2016-04-20T17:02:07-07:00] DEBUG: Plugin C ran 'gcc -v' and returned 0
[2016-04-20T17:07:51-07:00] DEBUG: Plugin C ran '/lib/libc.so.6' and returned 1
[2016-04-20T17:13:36-07:00] DEBUG: Plugin C ran '/lib64/libc.so.6' and returned 1

Takes 5 and then 6 minutes between plugin runs.

**Comment by lamont-granquist** [comment]
dup of ohai#798
