### ISSUE TITLE
Knife Delete Node Causes Errors On Next Run

### ISSUE THREAD

**Issue by rossedman** [chef/chef#4861]
## Description

If I remove a node through knife and then try to provision a node with the same name I am provided an error about being unauthorized to create that node again. If I delete the node through Chef Manage this problem does not occur. This could not be a bug at all but more of a misunderstanding in how this works. 

## Chef Version

Chef Client: 12.8.1

## Platform Version

Centos 7.2

## Replication Case

1. Bootstrap a node and connect it to chef server. 
2. Use `knife node delete node_name`
3. On next node bootstrap `Your validation client is not authorized to create the client for this node (HTTP 403).` now happens on every node.

## Client Output

Output [Here](https://gist.github.com/rossedman/3d51369d771eeff86181fa312b4c4b7d)

## Stacktrace

Output [Here](https://gist.github.com/rossedman/7a81af6161737b48a4f2dde0af9098a4)

**Comment by thommay** [comment]
you need to delete the client as well as the node, with `knife client delete node_name`.

**Comment by rossedman** [comment]
@thommay I did that as well. Still caused all nodes after to fail.
