### ISSUE TITLE
knife cookbook site install broken on windows

### ISSUE THREAD

**Issue by willoucom** [chef/chef#4862]
## Description

On windows, the command knife cookbook site install "package" return an error with tar

The error seems to occur because the tar.exe installed doesn't support the option --force-local

## Chef Version

Irrelevant, client-side issue

## Platform Version

Windows 10
knife --version : Chef: 12.8.1

## Replication Case

Download latest chef-dk for windows (chefdk-0.12.0-1-x86.msi), install it.

Run : knife cookbook site install "package"

## Client Output

$ knife cookbook site install docker
[snip]
Uncompressing docker version 2.6.8.
ERROR: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of tar zxvf "D:/Chef/chef-repo/cookbooks/docker.tar.gz" --force-local ----
STDOUT:
STDERR: tar: Option --force-local is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
---- End output of tar zxvf "D:/Chef/chef-repo/cookbooks/docker.tar.gz" --force-local ----
Ran tar zxvf "D:/Chef/chef-repo/cookbooks/docker.tar.gz" --force-local returned 1

## Quickfix and Workaround

You can bypass this error by commenting a single line in : 
/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.8.1-universal-mingw32/lib/chef/knife/cookbook_site_install.rb

Comment the line 147 : 
            extract_command << " --force-local"

Retry the command : 
knife cookbook site install docker

Installing docker to D:/Chef/chef-repo/cookbooks
Checking out the master branch.
Pristine copy branch (chef-vendor-docker) exists, switching to it.
Downloading docker from Supermarket at version 2.6.8 to D:/Chef/chef-repo/cookbooks/docker.tar.gz
Cookbook saved: D:/Chef/chef-repo/cookbooks/docker.tar.gz
Removing pre-existing version.
Uncompressing docker version 2.6.8.
Removing downloaded tarball
43 files updated, committing changes

**Comment by willoucom** [comment]
I have done some test and research, and it seems this issue occured after PR #3968 

From my humble point of view, quoting the path should have solved the initial issue.

I have made more testing and the same issue occurs using tar.exe from git for windows or tar.exe from chef-dk.

**Comment by EagleIJoe** [comment]
I believe the fixed missed a "not" as it should negate the Windows plattform request?

**Comment by smurawski** [comment]
@EagleIJoe The PR added logic to check the version of tar.  ChefDK on Windows includes the bsdtar variant, which does not support --force-local, but someone may have the GNU Utils version on their path at a higher precedence than the tar with ChefDK.  The GNU Utils tar does support --force-local, so the logic checks if it is the GNU or bsd version.
