### ISSUE TITLE
knife ssh asks for identity file passphrase for every node returned from query

### ISSUE THREAD

**Issue by jblaine** [chef/chef#4881]
## Description

When using an SSH identity file that has a passphrase on it, and that key is not loaded into an in-memory agent like `ssh-agent` ... using `knife ssh 'os:linux' 'echo foo' -i ~/.ssh/whatever --ssh-user jblaine` will cause knife to ask for the passphrase to `~/.ssh/whatever` for _every node returned by the search._

This behavior does not mimic the (correct) existing functionality of _password-based_ SSH where the password is asked for _once_ if not specified on the command-line.

Example output:
```
Enter passphrase for /home/jblaine/.ssh/whatever: Enter passphrase for /home/jblaine/.ssh/whatever: Enter passphrase for /home/jblaine/.ssh/whatever: Enter passphrase for /home/jblaine/.ssh/whatever: Enter passphrase for /home/jblaine/.ssh/whatever: Enter passphrase for /home/jblaine/.ssh/whatever: Enter passphrase for /home/jblaine/.ssh/whatever: Enter passphrase for /home/jblaine/.ssh/whatever: Enter passphrase for /home/jblaine/.ssh/whatever:
...
```

## Chef Version

12.8.1, but pretty sure all versions of Chef

## Platform Version

N/A, but RHEL 7

## Replication Case

1. Run `knife ssh` with a search query that returns more than 1 host that is configured for key-based SSH authentication.
2. Do not have the identity's key stored in memory (`ssh-agent` or similar)

## Client Output

Above

## Stacktrace
N/A

**Comment by thommay** [comment]
I'd say this is correct behaviour. If you want an ssh-agent, you should use one. It's not safe or sensible for us to implement one, and arguably we shouldn't store the password either.

**Comment by jblaine** [comment]
Hi Tom and Lamont,

I'm not seeing where you got the idea that I'm suggesting Chef implement an `ssh-agent` nor the idea that you should store the password in any way differently than you do already for `--ssh-password` (that is, in memory for the duration of the command).

**Comment by coderanger** [comment]
I agree with @thommay on this one. We store the password as an implementation detail but this behavior seems fine. I think the prompt comes from deep in net-ssh so we don't have access to fix this super-easily. We could probably do it by re-using some bit of the SSH connection objects from one to the next, but given the amount of work for minimal benefit I would say :-1: on any changes.

**Comment by coderanger** [comment]
Specifically the prompt is from https://github.com/net-ssh/net-ssh/blob/d539101da49dcfb535c70a2f36ecfe49516b6a4a/lib/net/ssh/key_factory.rb

**Comment by thommay** [comment]
my point is that you're essentially asking us to do something that another, well tested, mature product already does. You should use that thing.

**Comment by lamont-granquist** [comment]
@jblaine do you have a use case where you cannot use ssh-agent?

**Comment by jblaine** [comment]
@lamont-granquist No.

I disagree with the reasoning to not consider doing anything here. The `expect` command is equally as well-tested and a more mature product that you could have told people to use for feeding passwords to SSH. Instead, the special no-argument invocation of `--ssh-password` was implemented.

That you're more familiar with `ssh-agent` from daily usage than `expect` doesn't negate my point, if you ask me.

But ... in cases like this there's usually no good to come by me further elaborating on my views about consistency, least surprise, taking a step back, etc.

**Comment by curiositycasualty** [comment]
For anyone else who winds up here: I found that when loading the private key via specifying it in `knife.rb` or via chef in some other way, it would prompt for the key password and ignore a running `ssh-agent`.

However, when I delegated all the key stuff, (removing `ssh_identity_file` from my `knife.rb` file and instead specifying it in my `~/.ssh/config`), I no longer has `knife ssh` prompting me for the keys passphrase.
