### ISSUE TITLE
Default bootstrap template doesn't work under CSH

### ISSUE THREAD

**Issue by coderanger** [chef/chef#4885]
This manifests as:

```
Unmatched '.
TMPDIR: Undefined variable.
tmp=/tmp: Command not found.
else: endif not found.
```

Though the specific message might change over time. The root of the issue seems to be that CSH and it's kin don't grok multi-line string literals. Maybe we should tweak the bootstrap code to bypass the user's shell and always use `/bin/sh` directly?

**Comment by lamont-granquist** [comment]
That is what the bootstrap code used to do, it was probably lost with the recent refactoring.  Since i used tcsh for 20-ish years before switching to zsh, I think we should fix this.

**Comment by jsonstro** [comment]
Help? This is a major pain for our workflow. Any chance to see a fix on this moved through the stack?

**Comment by lamont-granquist** [comment]
#8885 probably fixes this.
