### ISSUE TITLE
yum package provider needs refactor

### ISSUE THREAD

**Issue by btm** [chef/chef#4905]
## Description

The yum package provider needs to be refactored. It is nearly 3x longer than the next nearest package provider in lines. A number of existing bugs in this provider would be significantly easier to fix after this work is complete.

From internal FLOW tickets:
- Refactor the package provider into multiple classes/files.
- Refactor the package provider tests into multiple classes/files to match
- Evaluate replacing the custom dependency management code with shelling out to yum

**Comment by lamont-granquist** [comment]
#4901 will address the first point.

**Comment by lamont-granquist** [comment]
happening #6540

**Comment by jagan495** [comment]
Thank you lamont-granquist . In which chef client version it will work
