### ISSUE TITLE
remote_file drops default HTTP port from GET request

### ISSUE THREAD

**Issue by quulah** [chef/chef#4915]
## Description

I'm using remote_file to download a file from a HTTP source. The source contains the default port in the URL. Example: http://10.1.2.3:80/file. The server at the other end (in which I have no control over) requires the GET to come with the port included. If it's not there it responds with a 403 Forbidden error.

It seems that the as_uri(source) method used by Chef::Provider::RemoteFile::Content drops the port.

as_uri() is just URI.parse().

## Chef Version
```
$ chef-client --version
Chef: 12.5.0.current.0
```
## Platform Version

CentOS 7

## Replication Case

```
irb(main):001:0> require 'uri'
=> true
irb(main):002:0> source = 'http://10.1.2.3:80/file'
=> "http://10.1.2.3:80/file"
irb(main):003:0> URI.parse(source)
=> #<URI::HTTP:0x00000001670358 URL:http://10.1.2.3/file>
```

Then have a server that doesn't like requests without the port.

## Client Output

The file itself is not relevant here.

```
[2016-05-10T10:23:39+00:00] DEBUG: Initiating GET to http://10.1.2.3/file.rpm
...
    remote_file("/var/chef/cache/file.rpm") do
      provider Chef::Provider::RemoteFile
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      path "/var/chef/cache/file.rpm"
      backup 5
      atomic_update true
      source ["http://10.1.2.3:80/file.rpm"]
      use_etag true
      use_last_modified true
      declared_type :remote_file
      cookbook_name "test"
      recipe_name "download"
      owner "root"
      group "root"
      mode "0644"
      not_if { #code block }
    end
[2016-05-10T10:23:39+00:00] INFO: Running queued delayed notifications before re-raising exception
[2016-05-10T10:23:39+00:00] DEBUG: Re-raising exception: Net::HTTPServerException - remote_file[/var/chef/cache/file.rpm] (test::download line 31) had an error: Net::HTTPServerException: 403 "Forbidden"
```

**Comment by quulah** [comment]
Testing with curl from the command line results in the same error. If I add the port, everything is fine. Without it the server responds with 403. It's picky.

I found this: [CHEF-5355](https://github.com/chef/chef/pull/1471), but the Host header itself should be fine without the port. And it is just the IP with both remote_file and a curl test from the command line.

**Comment by thommay** [comment]
The quick answer is that the target server is broken. That said, can you do `curl -v http://...` for both the url with the port and the one with out it?

**Comment by lamont-granquist** [comment]
I don't understand how this doesn't conflict with CHEF-5355, and if curl doesn't work against this IP address I'm fairly hesistant to change remote_file.  If remote_file's header property can be used to set the Host header to work around this issue(?) the I really wouldn't see any need for code changes (and I'd be more inclined to take code changes that allowed overriding the Host header).

**Comment by quulah** [comment]
I'll try and remember to run the curl -v tomorrow. But I guess it won't reveal anything special.

I don't think it's an issue with the headers, it's with the URL in the GET itself. Curl sends the Host header similarly, with just the IP. So modifying the Host header won't work.

I assumed, and would like that whenever I use remote_file the URL used is the source specified and not something modified (the :80 dropped). Even if this case is due to a silly server.

**Comment by lamont-granquist** [comment]
I think that is just coming from Net::HTTP which also makes me somewhat disinclined to fix it...

**Comment by quulah** [comment]
$ curl -v http://10.1.2.3:80/file.rpm
```
> GET http://10.1.2.3:80/file.rpm HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.1.2.3
> Accept: */*
> Proxy-Connection: Keep-Alive

< HTTP/1.1 200 OK
< Date: Mon, 16 May 2016 06:27:56 GMT
< Server: Apache/2.4.7 (Ubuntu)
< Content-Length: 30646421
< Accept-Ranges: bytes
< Last-Modified: Mon, 02 May 2016 08:49:25 GMT
< Content-Type: binary/octet-stream
< Via: 1.1 http-proxy-in-between
<
```

$ curl -v http://10.1.2.3/file.rpm
```
> GET http://10.1.2.3/file.rpm HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.1.2.3
> Accept: */*
> Proxy-Connection: Keep-Alive

< HTTP/1.1 403 Forbidden
< Date: Mon, 16 May 2016 06:27:59 GMT
< Server: Apache/2.4.7 (Ubuntu)
< Content-Length: 358
< Content-Type: text/html; charset=iso-8859-1
<
```

There's a proxy in between too, but I don't think it matters here. And the 403 response seems to come from the real destination.

Any way, I get your hesitance to change things. Indeed, it seems to be a problem / feature of the Net::HTTP library. As you can see in the initial report, it's the URI.parse() that drops the port.

I already created a workaround using an execute block. I'd rather use remote_file though.

If this were going to be changed in Chef, I think the as_uri() would have to be change to be something more than just the URI.parse(). And that probably is used in multiple places. :)

**Comment by thommay** [comment]
I think we're going to say that this is a won't fix - we're pretty sure that Net::HTTP is behaving to spec, and this is the first time anyone's reported this, so the cost/benefit is not good.
Sorry we can't give you an answer you'd like more.
