### ISSUE TITLE
Command line arguments passed to chef-client do not override values set in /etc/chef/client.d/client.rb

### ISSUE THREAD

**Issue by poliva83** [chef/chef#4918]
## Description

chef-client now traverses `/etc/chef/client.d/` and loads all the configuration set up in this folder. However you can not override values set in these configuration files using command line arguments. This seems wrong as you are able to override values set only in `/etc/chef/client.rb`.
## Chef Version

Chef: 12.9.41
## Platform Version

Ubuntu 14.04.4 LTS
## Replication Case
- 1. Create a configuration file in /etc/chef/client.d/client.rb

```
cat /etc/chef/client.d/client.rb

# Created by cloud-init v. 0.7.7 on Mon, 09 May 2016 19:48:18 +0000
log_level              :info
ssl_verify_mode        :verify_none
log_location           "/var/log/chef/client.log"
validation_client_name "mandolin-validator"
validation_key         "/etc/chef/validation.pem"
client_key             "/etc/chef/client.pem"
chef_server_url        "https://fake.chef.url/organizations/mandolin"
environment            "admin-poliva-Mandolin-orion"
node_name              "poliva-node.poliva.fake"
json_attribs           "/etc/chef/firstboot.json"
file_cache_path        "/var/cache/chef"
file_backup_path       "/var/backups/chef"
pid_file               "/var/run/chef/client.pid"
Chef::Log::Formatter.show_time = true
```
- 2. Create  `/etc/chef/firstboot.json`

```
cat /etc/chef/firstboot.json

{"run_list": ["recipe[bb_bescloud_admin::ssh]"], "bb_bescloud_admin": {"admin_files": {"base_src_url": "http://fake.fake.fake/~Mandolin/bescloud_files/"}}}
```
- 3. Create  `/root/test.json`

```
cat /root/test.json

{"run_list": ["recipe[bb_bescloud_admin::postfix]"], "bb_bescloud_admin": {"admin_files": {"base_src_url": "http://fake.fake.fake/~Mandolin/bescloud_files/"}}}
```
- 4. Run chef-client loading `/root/test.json` with -j flag (will have run_list `[bb_bescloud_admin::ssh]` when you expect `[bb_bescloud_admin::postfix]`)

```
chef-client -j /root/test.json
Starting Chef Client, version 12.9.41
resolving cookbooks for run list: ["bb_bescloud_admin::ssh"]
```
- 5. Remove `json_attribs           "/etc/chef/firstboot.json"` line from `/etc/chef/client.d/client.rb`

```
cat /etc/chef/client.d/client.rb

# Created by cloud-init v. 0.7.7 on Mon, 09 May 2016 19:48:18 +0000
log_level              :info
ssl_verify_mode        :verify_none
log_location           "/var/log/chef/client.log"
validation_client_name "mandolin-validator"
validation_key         "/etc/chef/validation.pem"
client_key             "/etc/chef/client.pem"
chef_server_url        "https://fake.chef.url/organizations/mandolin"
environment            "admin-poliva-Mandolin-orion"
node_name              "poliva-node.poliva.fake"
file_cache_path        "/var/cache/chef"
file_backup_path       "/var/backups/chef"
pid_file               "/var/run/chef/client.pid"
Chef::Log::Formatter.show_time = true
```
- 6. Run chef-client loading `/root/test.json` with -j flag again (This time run_list is `[bb_bescloud_admin::postfix]`)

```
chef-client -j test.json

Starting Chef Client, version 12.9.41
resolving cookbooks for run list: ["bb_bescloud_admin::postfix"]
```

**Comment by lamont-granquist** [comment]
Hmmm, yeah, that's a mess of responsibilities...

Chef::Application#load_config_file is responsible for loading the config file and doing all the merging of attributes.  The Chef::Application::Client#load_config_file method calls the superclass (loads the default client.rb) which then does the attribute merging, then the subclass goes and loads up the client.d directory after the merge already happened.   That is clearly wrong.

**Comment by lamont-granquist** [comment]
Needs to be replicated to see if this behavior is still present.

If it is, it needs to be folded into some larger work on sorting out what is going wrong with cli + config merging with knife.
