### ISSUE TITLE
Sporadic blue screens on Windows caused by csrss.exe being terminated

### ISSUE THREAD

**Issue by jjustice6** [chef/chef#4920]
## Description

Running Chef on Windows sporadically results in a blue screen stating that csrss.exe has been killed by ruby.exe. These machines do not continue to produce this blue screen every time Chef runs, having gone for days or weeks since producing the blue screen initially without doing it again. 
Nor was this blue screen produced by an unique run (such as the first run of a new cookbook release), by all appearances the Chef run should simply have confirmed that everything was converged and exited.

Terminating the csrss.exe process on Windows is a guaranteed way to create a blue screen, so this should not be happening ever.
## Chef Version

chef-client 12.9.38
## Platform Version

Windows 2008 R2 SP1
## Replication Case

We are unable to replicate this. However, we have observed this on 3 different machines in the past two weeks, and we have kernel mode crash dumps for those 3 machines. They all indicate that csrss.exe was killed by ruby.exe at a time corresponding to a Chef run.
## Client Output

The client.log file contains nothing indicating that there is a crash. It is simply incomplete.
## Stacktrace

No stacktrace.out file is produced as a result of this problem.

**Comment by jjustice6** [comment]
Still haven't been able to reproduce this, but attaching the Windows debugger to the running process stepping through it trying to identify potential problems with TerminateProcess reveals that it consistently follows the pattern of calling NtTerminateProcess 4 times in the chef-client run. 

The first two are terminations of legitimate handles (both of which are preceded by NtOpenProcess calls resulting in the creation of the handle), the third one is on null, with no handles open in the process (as seen via `!handle 0 f Process` in the debugger), and the fourth one is on ffffffffffffffff, which is apparently a special Windows thing for killing yourself.

I'm concerned about that third instance, in which TerminateProcess is called on null. There are no process handles open at that point, and there were no new NtOpenProcess calls after the second call to NtTerminateProcess. I have no idea what this corresponds to in the Chef code, but perhaps if it's erroneous then it's also erroneously attempting to terminate csrss.exe on rare occasion?

**Comment by lamont-granquist** [comment]
so on the unix side there's code in mixlib-shellout which does kill -9 to processes which are timing out.

i believe we added similar code on the windows side, but i have no clue how it was implemented.

recently i think we made timeouts in ohai much more aggressive to reduce long hangs from timeouts.

the aggressive ohai timeouts might have uncovered a mixlib-shellout windows process termination bug?

**Comment by btm** [comment]
https://github.com/chef/ohai/pull/788 was first released in Ohai 8.14.0.

It looks like Chef 12.8.1 included Ohai 8.12.1 and 12.9.38 has 8.14.0, so the timeouts in ohai closing a process seem like likely culprit.

**Comment by jjustice6** [comment]
It occurs to me that this:
```
Get-WmiObject -Query "select * from Win32_Process where ParentProcessID=0"
```
results in two processes being returned:
PID 0, System Idle Process, and PID 4, System.
If you then call it again with ParentProcessID=4, you see smss.exe; which is another important Windows process.

Killing that process results in a blue screen, but the crash dump doesn't indicate csrss.exe so we're still at a loss for the root cause here. Still, it's probably worth considering validating against calling `kill_process_tree` with a PID of 0 regardless.

Perhaps mixlib_shellout should check the names of the processes it kills against the names of windows processes that shouldn't be killed?

**Comment by johnbellone** [comment]
@btm The past few days @jjustice6 spent good deal of time getting us ready to roll back the Windows client to 12.8.1 - what's the current thoughts about a fix going forward?

**Comment by smurawski** [comment]
@johnbellone I spent a good bit of yesterday trying to replicate the conditions where something might get passed incorrectly to that `kill_process_tree` and haven't been able to replicate the problem.

I am working on a PR for mixlib-shellout that will validate against a list of processes that should not get killed (and I'll link it in this issue when I push it - probably later today).  However, as we don't have a replication case, it's hard to say that'll resolve the issue.  

If you are still seeing  it - would you be able to change the log_level to debug?  That should get what commands are being executed by ohai in the log.  While it may not get exactly what is causing the problem, we can see what is leading up to it.

**Comment by smurawski** [comment]
I submitted https://github.com/chef/mixlib-shellout/pull/127 to deal with the possible `kill_process_tree` issue.  I still have some more investigating to do though.

**Comment by niels1004** [comment]
Sounds like the WMI query does not filter on CreationDate of the process. Quoting the description of ParentProcessId from [https://msdn.microsoft.com/en-us/library/aa394372(v=vs.85).aspx](url) (emphasis mine):

> Unique identifier of the process that creates a process. Process identifier numbers are reused, so they only identify a process for the lifetime of that process. It is possible that the process identified by ParentProcessId is terminated, so ParentProcessId may not refer to a running process. **It is also possible that ParentProcessId incorrectly refers to a process that reuses a process identifier. You can use the CreationDate property to determine whether the specified parent was created after the process represented by this Win32_Process instance was created.**

Hope this helps.

**Comment by btm** [comment]
@smurawski it doesn't look like we've had a release of mixlib-shellout since https://github.com/chef/mixlib-shellout/pull/127. Is the next step here to release that, get it in Chef, and try to reproduce the issue?

**Comment by btm** [comment]
https://github.com/chef/mixlib-shellout/pull/127 was included in mixlib-shellout v2.2.7, released on 8/22/16.

mixlib-shellout v2.2.7 was first included in chef v12.14.32. Chef 12.14.89 was [released](https://discourse.chef.io/t/chef-12-14-89-released/9487) to stable on 9/22/16.

If you experience this issue on any earlier version of Chef, please upgrade to the latest version and see if it resolves.

Otherwise, please let us know if you experience this issue on a recent version of Chef.

**Comment by Raghunathareddyp** [comment]
I also noticed the same issue on few windows servers, did any one find the root cause for this issue.
Dump analysis says csrss.exe critical process terminated by ruby.exe

**Comment by jjustice6** [comment]
I don't think we or Chef ever found a _true_ root cause, but we haven't experienced it since updating to or past the version of chef-client 12.14 that @btm mentions. What version are you encountering this on?
