### ISSUE TITLE
Should we freeze Ohai data?

### ISSUE THREAD

**Issue by coderanger** [chef/chef#4930]
A fun "bug report" from a user this evening ended up in that someone was calling `node['os'].capitalize!` instead of the non `!` version. As you might expect, this breaks a lot of things. Maybe we should consider freezing all Ohai data when we load it into the node object? This is not common given that this is the first I've heard of it in 6 years but still it would be relatively easy and maybe reduce memory usage? What say we all @chef/client-core.

**Comment by coderanger** [comment]
At least re: memory usage, it looks like calling freeze on a string re-allocs it to exactly the needed length. Given the number of small strings we have in there, I wouldn't be surprised it that was a decent bit of savings.

**Comment by jaymzh** [comment]
How did that happen? `node['os']` isn't a writer - that should have failed with the "please use node.default" error, right?

Would such a freeze affect only the 'automatic' precedence? Or the whole node for entries that happened to come from ohai? I've definitely, in attribute files, overwritten ohai data to work around wonky bugs in ohai, chef, cookbooks, etc. Certainly in specs I do it regularly. I can see some very strange things coming out of this.

**Comment by lamont-granquist** [comment]
https://github.com/chef/chef/blob/master/spec/unit/node/attribute_spec.rb#L464-L473

**Comment by btm** [comment]
I agree "I can see some very strange things coming out of this."

```
chef:attributes (12.7.2)> node.default[:hostname]
 => {}
chef:attributes (12.7.2)> node.env_default[:hostname]
 => {}
chef:attributes (12.7.2)> node.role_default[:hostname]
 => {}
chef:attributes (12.7.2)> node.force_default[:hostname]
 => {}
chef:attributes (12.7.2)> node.normal[:hostname]
 => {}
chef:attributes (12.7.2)> node.override[:hostname]
 => {}
chef:attributes (12.7.2)> node.role_override[:hostname]
 => {}
chef:attributes (12.7.2)> node.env_override[:hostname]
 => {}
chef:attributes (12.7.2)> node.force_override[:hostname]
 => {}
chef:attributes (12.7.2)> node.automatic[:hostname]
 => "btm-desktop"
chef:attributes (12.7.2)> node[:hostname]
 => "btm-desktop"

chef:attributes (12.7.2)> node[:hostname].capitalize!
 => "Btm-desktop"

chef:attributes (12.7.2)> node.default[:hostname]
 => {}
chef:attributes (12.7.2)> node.env_default[:hostname]
 => {}
chef:attributes (12.7.2)> node.role_default[:hostname]
 => {}
chef:attributes (12.7.2)> node.force_default[:hostname]
 => {}
chef:attributes (12.7.2)> node.normal[:hostname]
 => {}
chef:attributes (12.7.2)> node.override[:hostname]
 => {}
chef:attributes (12.7.2)> node.role_override[:hostname]
 => {}
chef:attributes (12.7.2)> node.env_override[:hostname]
 => {}
chef:attributes (12.7.2)> node.force_override[:hostname]
 => {}
chef:attributes (12.7.2)> node.automatic[:hostname]
 => "btm-desktop"
chef:attributes (12.7.2)> node[:hostname]
 => "Btm-desktop"
```

```
chef:attributes > node.automatic[:hostname].capitalize!
 => "Btm-desktop"

chef:attributes (12.7.2)> node.default[:hostname]
 => {}
chef:attributes (12.7.2)> node.env_default[:hostname]
 => {}
chef:attributes (12.7.2)> node.role_default[:hostname]
 => {}
chef:attributes (12.7.2)> node.force_default[:hostname]
 => {}
chef:attributes (12.7.2)> node.normal[:hostname]
 => {}
chef:attributes (12.7.2)> node.override[:hostname]
 => {}
chef:attributes (12.7.2)> node.role_override[:hostname]
 => {}
chef:attributes (12.7.2)> node.env_override[:hostname]
 => {}
chef:attributes (12.7.2)> node.force_override[:hostname]
 => {}
chef:attributes (12.7.2)> node.automatic[:hostname]
 => "Btm-desktop"
chef:attributes (12.7.2)> node[:hostname]
 => "Btm-desktop"
```

**Comment by lamont-granquist** [comment]
so what about `node.default[:whatever].capitalize!` and `node.automatic[:whatever].capitalize!`

and there'll be a perf hit if we don't freeze all the strings, since we'll need to dup and freeze everything.  that'll hit phil fairly hard (although if the existing code stops cheating here, it'll make my node attributes code look good in comparison).

**Comment by btm** [comment]
attributes: there be dragons.

`node.automatic[:hostname].capitalize!` was shown in my second code block in my last comment.

```
chef:attributes (12.7.2)> node.default[:test] = "foo"
 => "foo"
chef:attributes (12.7.2)> node[:test]
 => "foo"
chef:attributes (12.7.2)> node.default[:test].capitalize!
 => "Foo"
chef:attributes (12.7.2)> node[:test]
 => "foo"
chef:attributes (12.7.2)> node.default[:test]
 => "Foo"
```

**Comment by lamont-granquist** [comment]
yeah, i mean i'm sure the current behavior is to mutate them and that they're unfrozen, but what should the future behavior be?

**Comment by jaymzh** [comment]
So wait, what is it that `node[:hostname].capitalize!` is capitalizing if not node.automatic[:hostname] ? Is it the string from the cached computed value that's getting munged? I'm confused.

Anyway with regards to what **should** happen, I think if you write with writers, it should write. node.automatic, node.default, etc. If I know what I'm doing and go `node.automatic[:os] = "fiddlybits"` I mean ya know, I better really know what I'm doing, but it should work. But `node[:os] = "poodlytood"` isn't a writer and that shouldn't work at all.

**Comment by lamont-granquist** [comment]
So what is going on though is that you're getting an object (String) and then you're calling mutator methods on the unfrozen string.

`node.automatic[:os]` and `node[:os]` both are pointers to the same String.

In order to fix this we need to freeze the `node[:os]` string, but to have the semantics work out so that `node.automatic[:os].capitalize!` is still "i know what i'm doing" then you have to dup.freeze the string when you compute the immutable merged array.

I can do that, but I'm certain after looking at the ruby-prof traces of what you (phil) do, that you really won't like the performance hit.

Kind of want to do that, just to be evil and light a fire under rewriting all the node attributes with decorators, but I think I should go down the road of pulling that branch into master in more easily digestible pieces into the Chef::Decorator stuff i started with the lazy candidate_version code....

**Comment by jaymzh** [comment]
@lamont-granquist that's not true. @btm 's past shows that's not true.

```
chef:attributes (12.7.2)> node.automatic[:hostname]
 => "btm-desktop"
chef:attributes (12.7.2)> node[:hostname]
 => "Btm-desktop"
```

how the fuck are those different in his paste?

**Comment by lamont-granquist** [comment]
wut?

**Comment by lamont-granquist** [comment]
hrm, well it makes sense if its already dup'ing the string to create the immutable merged view, in which case i may be incorrect and all we have to do is freeze the result, which would be much cheaper.

**Comment by jaymzh** [comment]
right, that was my thought.

**Comment by coderanger** [comment]
I was mostly thinking we would recursively freeze everything returned by Ohai before we load it in to `node.automatic`. That would leave all other attribute levels unfrozen, but if we are dup'ing things in the attribute merge that might not help. Also: why are dup'ing those strings?

**Comment by lamont-granquist** [comment]
well i'm assuming it _should_ work this way (and setting aside the automatic/ohai issue for now):

```ruby
node.normal["foo"] = "bar"
node.override["foo"] = "baz"
node["foo"] << "buzz"  # this should be a frozen string
node.override["foo"] << "buzz"  # this should mutate to "bazbuzz"
```

in order to do that i think you need to dup and freeze when you do the attribute merge, because you need two different "baz" strings -- one mutable, one frozen.

**Comment by lamont-granquist** [comment]
and for ohai stuff, we can freeze it, but we need to make sure that re-running plugins still works.

**Comment by coderanger** [comment]
Freezing the merged view is a different issue and would be a more substantial compat break, though we already block array and hash mutation calls so maybe not a big deal. For Ohai I think we can freeze at all layers because I can't think of a case where mutating Ohai data should be allowed. Re-running plugins should be be fine because we can totally re-init `node.automatic` I think a la FP data types. Maybe we don't freeze the hashes and arrays, just strings for now?

**Comment by jaymzh** [comment]
by all layers, do you mean all precedents are all layers of the hash? Cause certainly overwriting ohai data from the run by writing to default can be very useful.

**Comment by coderanger** [comment]
@jaymzh Not sure what you mean, writing to `node.default` would not currently override Ohai data.

**Comment by coderanger** [comment]
Fixed by https://github.com/chef/ohai/issues/972

Freezing the actual hashes and arrays is probably not worth the trouble.
