### ISSUE TITLE
Analytics Rules documentation example for array:contains() is incorrect

### ISSUE THREAD

**Issue by chef09210** [chef/chef#4937]
## Description

Analytics Rules documentation for array:contains() has 

> For example:
> 
> array:contains(organization_name = 'ponyville')

However the syntax is listed as 

> array:contains(field, valueToFind)

https://docs.chef.io/analytics_rules.html#array-contains

**Comment by coderanger** [comment]
As mentioned in the template, this repo is for Chef bugs only.
