### ISSUE TITLE
Analytics alert details are not displayed properly for run_converge rules

### ISSUE THREAD

**Issue by chef09210** [chef/chef#4938]
## Description

When a Chef Analytics rule is setup to run on run_converge, the details presented in the UI are not being filled in properly

Run ID:
Node Name:
Start Time: 11:04 pm - 16 May 2016
End Time:  11:04 pm - 16 May 2016

Total Resource Count:
Updated Resource Count:
Run List: {{ model.alertable.run_list | stringifyArray}}
Tags: {{ model.alertable.tags | stringifyArray}}

Only Start/End Time are displayed.

## Chef Version

12.9.41

## Platform Version

Windows 2012R2

## Replication Case

Create a simple rule

rules 'test'
rule on run_converge
when
true
then
alert:info("Run succeeded")
end
end

Initiate a chef-client run on the node

Check Analytics Alerts tab

Expand the Details for the alert

**Comment by coderanger** [comment]
Please stop, like I said for the last one, this is for Chef bugs only. You can file issues with Chef Analytics by emailing Chef Support or talking to your TAM.
