### ISSUE TITLE
Automatically set atomic_updates to false in Chef::Provider::File when updating /etc/resolv.conf or /etc/hosts on a docker guest?

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#4949]
These give EBUSY errors on docker.

Fixing them in cookbooks is a bit of a whack-a-mole.

The worst things that I can think of happening is:

- docker detection code fails to detect docker, so the updates fail, in which case manually setting atomic_updates to false works, and the user isn't much worse off than they are now.

- docker no longer requires these settings, in which case its still going to work, outside of the edge condition where you happen to run the server out of disk space right when you're doing this (but its docker, so immutable infrastructure magically makes this problem go away #amirite?)

It does mean that to fix bugs in the docker detection code you need to upgrade chef and not just upgrade a cookbook.  This doesn't feel like docker is going to mess with this that much though.

**Comment by coderanger** [comment]
On one hand, this is an annoyingly specific special case to throw in there, on the other hand it will come up more and more :-/

**Comment by lamont-granquist** [comment]
Reference issues:

https://github.com/docker/docker/issues/9295
https://github.com/chef-cookbooks/chef_hostname/pull/3/files
https://github.com/chef-cookbooks/resolver/pull/22
https://github.com/customink-webops/hostsfile/issues/77

It would be a fairly small bit of code to make the whole problem go away.

**Comment by thommay** [comment]
yeah, let's just do it. it's the right thing for our customers.
