### ISSUE TITLE
Chocolatey package incorrectly identifies latest version of package.

### ISSUE THREAD

**Issue by artisticcheese** [chef/chef#4968]
Please see issue created on wrong recipe here
https://github.com/chocolatey/chocolatey-cookbook/issues/86#issuecomment-221428759

**Comment by ferventcoder** [comment]
It looks like this issue stems from calling choco `list -ar` which has no guaranteed ordering of resources. I'm also concerned that `--all-versions` should not be used, not every type of nuget odata source supports it, but every source supports 

* Latest version through a query
* Calling for a specific version

I'd suggest possibly some rework in chocolatey.rb to eliminate the use of `-a` to allow for more support with custom hosts.

cc @mwrock @lamont-granquist

**Comment by mwrock** [comment]
I just spent some time looking into this.

It looks like i added it to prevent bogus versions and then made an incorrect assumption on the ordering.

The ordering problem is easy to fix alone and I also think we can avoid the -a and just bubble errors from choco for bogus versions.

One thing that may be useful to know but not a consolation regarding the original issue filed at https://github.com/chocolatey/chocolatey-cookbook/issues/86 is that while the resource informs the console that the package has been upgraded to an old version. It's lying. Its really just calling `choco upgrade -y` on the package with no version constraint. Only if the resource has an explicit `version` property will we pin on the upgrade.

Clearly we should be reporting the correct version.
