### ISSUE TITLE
User deletion encountered "logged in" error even when using force

### ISSUE THREAD

**Issue by orarnon** [chef/chef#4995]
## Description

Using the User resource and force with "true", still gets an error that the user is logged in.
There's an ssh-agent running for this user. However, from what I understand, force should take care of it.
Even if all processes are killed before running chef, still gets:
warning: can't remove /var/mail/webistrano: No such file or directory

## Chef Version

12.5.1

## Platform Version

Ubuntu 12.04

## Replication Case

Create any user and run the following to delete:

user 'user' do
  action :remove
  force true
  comment 'Webistrano users'
  gid 'user'
  home '/home/user'
  shell '/bin/bash'
  supports :manage_home => true
end

## Client Output

================================================================================
    Error executing action `remove` on resource 'user[webistrano]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '12'
    ---- Begin output of ["userdel", "-r", "-f", "webistrano"] ----
    STDOUT:
    STDERR: userdel: user webistrano is currently logged in
    userdel: warning: can't remove /var/mail/webistrano: No such file or directory
    ---- End output of ["userdel", "-r", "-f", "webistrano"] ----
    Ran ["userdel", "-r", "-f", "webistrano"] returned 12

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/sonic-phpapp/recipes/code_deploy.rb

     20: user 'webistrano' do
     21:   action :remove
     22:   force true
     23:   comment 'Webistrano users'
     24:   gid 'webistrano'
     25:   home '/home/webistrano'
     26:   shell '/bin/bash'
     27:   supports :manage_home => true
     28: end
     29:

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by thommay** [comment]
I don't think this is a bug in chef, but is standard unix behaviour. You've requested `userdel` remove the user even though it's still logged in, which it's done. But the exit code of 12 means it can't remove the user's home directory, and that's because there's still a process running that's logged in and using that directory. Force definitely won't (and shouldn't - that would be horribly confusing) kill processes; it's simply exposing userdel's option.
