### ISSUE TITLE
Use of node.default_unless mutates other attributes

### ISSUE THREAD

**Issue by simon-baatz** [chef/chef#5005]
## Description

In specific situations, calling `node.default_unless` may change the value returned by `node[...]` of a _different_ attribute.

```ruby
raise "Before _unless: a/r1/g/u is #{node['a']['r1']['g']['u']}!" unless node['a']['r1']['g']['u'].is_a?(String)

node.default_unless['a']['r1']['g']['r'] = 'r'

raise "After _unless: a/r1/g/u is #{node['a']['r1']['g']['u']}!" unless node['a']['r1']['g']['u'].is_a?(String)
```

This code will raise the following exception in the situation described below:

```
       RuntimeError
       ------------
       After _unless: a/r1/g/u is {}!
```

Before the call to `default_unless` the node access returned a string, after the call it becomes an empty immutable mash.

## Chef Version

Chef Client, version 12.10.24

## Platform Version

CentOS 7.2

## Replication Case

Create an empty cookbook using `chef generate cookbook unless`. Change the default recipe to:

```ruby
raise "Before _unless: a/r1/g/u is #{node['a']['r1']['g']['u']}!" unless node['a']['r1']['g']['u'].is_a?(String)

node.default_unless['a']['r1']['g']['r'] = 'r'

raise "After _unless: a/r1/g/u is #{node['a']['r1']['g']['u']}!" unless node['a']['r1']['g']['u'].is_a?(String)
```

Create a JSON environment `env/kitchen.json` for use with kitchen

```json
{
    "name": "kitchen",
    "description": "kitchen example",
    "cookbook_versions": {
    },
    "chef_type": "environment",
    "default_attributes": {
        "a" : {
            "r1" : {
                "g" : {
                    "u" : "u1"
                }
            }
        }
    }
}
```

Adapt the `.kitchen.yml` file to use the environment:

```yaml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  environments_path: env
  client_rb:
    environment: kitchen

platforms:
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[unless::default]
    attributes:
```

Run `kitchen converge`

## Client Output

```
...       
       RuntimeError
       ------------
       After _unless: a/r1/g/u is {}!
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/unless/recipes/default.rb:10:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/unless/recipes/default.rb:
       
         3:  # Recipe:: default
         4:  #
         5:  # Copyright (c) 2016 The Authors, All Rights Reserved.
         6:  raise "Before _unless: a/r1/g/u is #{node['a']['r1']['g']['u']}!" unless node['a']['r1']['g']['u'].is_a?(String)
         7:  
         8:  node.default_unless['a']['r1']['g']['r'] = 'r'
         9:  
        10>> raise "After _unless: a/r1/g/u is #{node['a']['r1']['g']['u']}!" unless node['a']['r1']['g']['u'].is_a?(String)
        11:  
       
       Platform:
       ---------
       x86_64-linux
...
```

**Comment by thommay** [comment]
@lamont-granquist this looks right up your alley.

**Comment by lamont-granquist** [comment]
yeah related to #3721, suspect its due to the global state default_unless sets up, which would be eliminated by using a decorator to implement that.

this is actually the first part of #3721 that i want to pull into master when i get back from vacay in order to start taking the node attribute rewrite into master in smaller bites.

**Comment by lamont-granquist** [comment]
I tried replicating this with attributes files and I think it fails because of attribute precedence levels, while its necessary to set env_default to exhibit the bug.  Added a spec to #5029 which is red on current master and shows that #5029 fixes the issue (not even sure I understand this bug but its gone there).
