### ISSUE TITLE
Chef 12.5+ Template resource subscription actions broken for wrapped/layered cookbooks

### ISSUE THREAD

**Issue by swstraus** [chef/chef#5020]
## Description
Starting in Chef 12.5, Subscription actions based on template changes in a layered/wrapped cookbook are not executing.

## Chef Version

12.11.18

## Platform Version

CentOS 6

## Replication Case

In my organization we use a custom tomcat cookbook to build out tomcat instances.  There are many proprietary customizations that get applied to these instances, so a generic wrapper was created and custom attributes are applied at that layer so that many different subsystems can utilize it.

I have created 3 stripped down cookbooks with only the relevant code included to reproduce this issue.  In order to skip the installation of tomcat and to simplify the example, these cookbooks will be restarting the cron daemon instead of tomcat and using a placeholder file called server.xml which we will use to trigger the restart action.

I only noticed this issue recently when our newer amazon ami's started including the latest chef client by default.  Prior to that we were only using chef 12.4.0.

The cookbooks are:

[base_test](https://github.com/swstraus/base_test) - Provider Cookbook that simulates a tomcat installation and associated configuration
[base_wrapper](https://github.com/swstraus/base_wrapper) -  Cookbook that depends on base_test and applies additional customizations.  For this test, it merely just wraps the install to simulate the issue being reported.
[test_recipe_cookbook2](https://github.com/swstraus/test_recipe_cookbook2) - Application cookbook that installs a tomcat configuration into /data/servers/testy_tomcat_1.  This depends/includes base_wrapper, which in turn depends/includes base_test.

The issue is that prior to Chef 12.5, when a change occurred to a file, in this case server.xml, a subscription to that resource would result in an restart to the tomcat if that resource changed.  After 12.5, that action no longer takes place.

####To reproduce:

1. install [Chef-client 12.4.3](https://packages.chef.io/stable/el/6/chef-12.4.3-1.el6.x86_64.rpm)
2. clone the above 3 cookbooks into your cookbook repo on a CentOS 6 host
3. run chef-client -z -o test_recipe_cookbook2.  
4. run step 3 again to verify idempotency (0 resources updated)
5. echo "extra text" >> /data/servers/testy_tomcat_1/conf/server.xml
6. run chef-client -z -o test_recipe_cookbook2.
7. Notice that the crond service will be restarted after the template for server.xml is updated.
8. Install [Chef-client 12.11.18](https://packages.chef.io/stable/el/6/chef-12.11.18-1.el6.x86_64.rpm) or any version 12.5 or newer and rerun steps 3-6.
9. After upgrading, you will notice that the template for server.xml is updated, but the restart action no longer takes place.

## Client Output

####Chef 12.4.3 (restart happens)

[root@crouton-vaa01 chef-repo]# chef-client -z -o test_recipe_cookbook2
[2016-06-10T13:56:23-04:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 12.4.3
[2016-06-10T13:56:24-04:00] WARN: Run List override has been provided.
[2016-06-10T13:56:24-04:00] WARN: Original Run List: []
[2016-06-10T13:56:24-04:00] WARN: Overridden Run List: [recipe[test_recipe_cookbook2]]
resolving cookbooks for run list: ["test_recipe_cookbook2"]
Synchronizing Cookbooks:
  - base_wrapper
  - test_recipe_cookbook2
  - base_test
Compiling Cookbooks...
Converging 2 resources
Recipe: base_wrapper::default
  * base_test_instance[testy_tomcat_1] action create
    * directory[/data/servers] action create (up to date)
    * directory[/data/servers/testy_tomcat_1] action create (up to date)
    * directory[/data/servers/testy_tomcat_1/lib] action create (up to date)
    * directory[/data/servers/testy_tomcat_1/logs] action create (up to date)
    * directory[/data/servers/testy_tomcat_1/temp] action create (up to date)
    * directory[/data/servers/testy_tomcat_1/webapps] action create (up to date)
    * directory[/data/servers/testy_tomcat_1/work] action create (up to date)
    * directory[/data/servers/testy_tomcat_1/etc] action create (up to date)
    * directory[/data/servers/testy_tomcat_1/conf] action create (up to date)
    * directory[/data/servers/testy_tomcat_1/properties] action create (up to date)
    * template[/data/servers/testy_tomcat_1/conf/server.xml] action create
      - update content in file /data/servers/testy_tomcat_1/conf/server.xml from bf872c to 8d5d54
      --- /data/servers/testy_tomcat_1/conf/server.xml	2016-06-10 13:55:52.332584752 -0400
      +++ /tmp/chef-rendered-template20160610-2650-1ib7k9m	2016-06-10 13:56:24.294352947 -0400
      @@ -1,3 +1,2 @@
      -fjkadslfjasl;Placeholder text
      -extra text
      +Placeholder text
    * service[crond] action enable (up to date)
    * service[crond] action restart
      - restart service service[crond]
  
  * service[crond] action enable (up to date)
[2016-06-10T13:56:24-04:00] WARN: Skipping final node save because override_runlist was given

Running handlers:
Running handlers complete
Chef Client finished, 3/15 resources updated in 0.889854752 seconds

####Chef 12.11.18 (restart does not happen)

[root@crouton-vaa01 chef-repo]# chef-client -z -o test_recipe_cookbook2
[2016-06-10T13:54:38-04:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 12.11.18
[2016-06-10T13:54:40-04:00] WARN: Run List override has been provided.
[2016-06-10T13:54:40-04:00] WARN: Original Run List: []
[2016-06-10T13:54:40-04:00] WARN: Overridden Run List: [recipe[test_recipe_cookbook2]]
resolving cookbooks for run list: ["test_recipe_cookbook2"]
Synchronizing Cookbooks:
  - base_wrapper (0.1.0)
  - test_recipe_cookbook2 (0.1.1)
  - base_test (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 2 resources
Recipe: base_wrapper::default
  * base_test_instance[testy_tomcat_1] action create
    * directory[/data/servers] action create (up to date)
    * directory[/data/servers/testy_tomcat_1] action create (up to date)
    * directory[/data/servers/testy_tomcat_1/lib] action create (up to date)
    * directory[/data/servers/testy_tomcat_1/logs] action create (up to date)
    * directory[/data/servers/testy_tomcat_1/temp] action create (up to date)
    * directory[/data/servers/testy_tomcat_1/webapps] action create (up to date)
    * directory[/data/servers/testy_tomcat_1/work] action create (up to date)
    * directory[/data/servers/testy_tomcat_1/etc] action create (up to date)
    * directory[/data/servers/testy_tomcat_1/conf] action create (up to date)
    * directory[/data/servers/testy_tomcat_1/properties] action create (up to date)
    * template[/data/servers/testy_tomcat_1/conf/server.xml] action create
      - update content in file /data/servers/testy_tomcat_1/conf/server.xml from 12c607 to 8d5d54
      --- /data/servers/testy_tomcat_1/conf/server.xml	2016-06-10 13:54:32.004167192 -0400
      +++ /data/servers/testy_tomcat_1/conf/.chef-server.xml20160610-2285-1if2xle	2016-06-10 13:54:40.249107433 -0400
      @@ -1,2 +1,2 @@
      -fjkaslfdjal;Placeholder text
      +Placeholder text
    * service[crond] action enable (up to date)
  
  * service[crond] action enable (up to date)
[2016-06-10T13:54:40-04:00] WARN: Skipping final node save because override_runlist was given

Running handlers:
Running handlers complete
Chef Client finished, 2/14 resources updated in 01 seconds

**Comment by coderanger** [comment]
Could you maybe create a slightly more minmal repro case? Or otherwise explain more concisely what you are trying to do? This is still a ton of both code and output to look at with little indication of what your goal is.

**Comment by swstraus** [comment]
I thought this code was pretty minimal and stripped down.  You should see what I started with :).

The gist is this  with 12.4 and below, restarts were triggered.  With 12.5 and above, restarts are no longer triggered. I have removed the debug from above and removed mention of one cookbook.

**Comment by coderanger** [comment]
I _think_ you are describing that resources inside a provider's action method are no longer visible to subscriptions from an enclosing run context. Meaning if you have:

```
class MyResource < Chef::Resource
  action :run do
    template '/foo'
  end
end

my_resource 'foo'
other_resource 'bar' do
  subscribes :whatever, 'template[/foo]'
end
```

it no longer triggers the notification. Is that a reasonable summary?

**Comment by coderanger** [comment]
If so, that's expected and correct :) You should alter the notification to be from `my_resource[foo]`. We now enforced the encapsulation a lot more strongly when working with custom resources. The stuff inside them are like private methods/variables, you can't touch them from the outside.

**Comment by coderanger** [comment]
No, you would subscribe to `base_test_instance[whatever]`. You can no longer look inside the internals of another resource, which should never have worked but we've gotten progressively better at implementing this.

**Comment by swstraus** [comment]
So, in this case the fix was

```
subscribes :restart, "base_test_instance[#{instanceName}]"
```
The resource is dynamic.

Thanks for the guidance.
