### ISSUE TITLE
Service resource does not handle dependent services on Windows

### ISSUE THREAD

**Issue by jeffreycoe** [chef/chef#5023]
## Description

When attempting to stop a Windows service that has dependent services, the Windows service provider errors out with a message stating the service cannot be stopped since one of its dependents is still started.

Could the service resource have an attribute to apply the action on the service's dependents?

## Chef Version

12.11.18

## Platform Version

Windows Server 2012 R2

## Replication Case

Run a recipe that attempts to stop a Windows service with dependents using the service resource 

## Client Output

[2016-06-12T19:21:51-04:00] DEBUG: SystemCallError: windows_service\[MSSQLSERVER\] (test-recipe::stop-services line 30) had an error: SystemCallError: A stop control has been sent to a service that other running services are dependent on. - ControlService: A stop control has been sent to a service that other running services are dependent on.

## Stacktrace

C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/win32-service-0.8.7/lib/win32/windows/helper.rb:36:in 'raise_windows_error'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/win32-service-0.8.7/lib/win32/service.rb:1551:in 'send_signal'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/win32-service-0.8.7/lib/win32/service.rb:760:in 'stop'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18-universal-mingw32/lib/chef/provider/service/windows.rb:133:in 'block in stop_service'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18-universal-mingw32/lib/chef/provider/service/windows.rb:288:in 'block in spawn_command_thread'

**Comment by smurawski** [comment]
I think this is the behavior that we want.  While it would be convenient to force all the dependent services to stop, there isn't necessarily a hard link between a service and dependent services.  This could easily lead to scenarios where (using your example of sql server) you stop sql server and that also shuts down sql agent (which by default is a manual start service).  Later in your recipe, you start sql server, but sql agent is never restarted.  If you are explicit about the services you expect to be stopped, it's more transparent as to what services are being affected.

You can work around that by using a `powershell_script` resource with `stop-service mssqlserver -force` if you really need that behavior, but you have the same potential downside that starting one service back up does not necessarily start back up any of the dependent services.
