### ISSUE TITLE
Reboot resource on linux needs to fork the shutdown process

### ISSUE THREAD

**Issue by smurawski** [chef/chef#5026]
When using the `reboot` resource on centos or ubuntu, `shutdown -r` with some time period and reason is executed and blocks until the time period runs out.  Then chef-client races to finish against the shutdown in progress.

This can break testing scenarios that require a reboot via test-kitchen as the new exit codes aren't returned consistently (depending on who wins the race).

**Comment by smurawski** [comment]
This is compared to windows, where the shutdown command requests a reboot and returns right away, allowing the client run to finish.

**Comment by lamont-granquist** [comment]
the reboot handler itself runs very late though doesn't it so there shouldn't be any resources running so having a delay of several seconds should give chef-client time to clean up and finish -- and in the event it does not then nothing was going to happen anyway in the chef-client run?

**Comment by lamont-granquist** [comment]
oh, i see the reboot resource fails to fork off the `shutdown -r`...

**Comment by daxgames** [comment]
+1 - for a fix

**Comment by aaronlippold** [comment]
This needs to be resolved it will cause many downstream effects when we are building software stacks on CI/CD pipelines that required hardened images built on demand.
