### ISSUE TITLE
dsc_script does not show verbose output

### ISSUE THREAD

**Issue by adbertram** [chef/chef#5044]
## Description

When using the dsc_script resource, the verbose output from the LCM does not show up when invoking chef-client
## Chef Version

12.11.18
## Platform Version

Windows Server 2012 R2/WMFv5
## Replication Case

knife winrm $NodeFqdn -m chef-client -x $UserName -P $Password --verbose

@smurawski

**Comment by avishnyakov** [comment]
Same-same here. Can't get verbose logs from chef and chef_solo under vagrant.
Chef client 12.15.19, Windows Server 2012 R2/WMFv5

**Comment by avishnyakov** [comment]
Any updates / comments on this item? @smurawski

**Comment by mwrock** [comment]
this is still a known issue @avishnyakov

**Comment by avishnyakov** [comment]
Alright, no worries. 

What might be a work around to get verbose trace from DSC run under dsc_script, then? It's a bit dark with little visibility on what, how and then been run.

**Comment by stuartpreston** [comment]
Closing this old issue. `dsc_script` was updated for WMF5 in https://github.com/chef/chef/pull/6383 so please retest against using a recent Chef Client if this is still an issue for you.
