### ISSUE TITLE
Group provider fails on AIX when the group already exists

### ISSUE THREAD

**Issue by jjustice6** [chef/chef#5054]
## Description

Attempting to create a group on AIX results in an error if the group already exists:
`group[chef] had an error: Chef::Exceptions::Exec: chgroup 'id=15848' foobar returned 17, expected 0`

The larger error message indicates the group resource invocation looks fine: 
## Chef Version

Chef: 12.9.41
## Platform Version

AIX 7.1.0.0
## Replication Case

Attempt to create a group with a specified ID that already exists on the system, matching the ID that already exists.
## Client Output

```
      Resource Declaration:
      ---------------------

       93:           group group_name do
       94:             gid group_id
       95:             system true
       96:           end
       97:         end

      Compiled Resource:
      ------------------

      group("foobar") do
        action [:create]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        group_name "foobar"
        gid "15848"
        declared_type :group
        cookbook_name "our-cookbook"
        system true
      end
```

**Comment by juliandunn** [comment]
I can't reproduce this using AIX 7.2 and Chef Client 12.13.37. Can you provide more information or a clean repro case?

Here is what I tried:

* Create a group on the system, use the recipe as follows to `chef-apply` it:

```ruby
group "foobar" do
  action [:create]
  gid "15848"
  system true
end
```

Chef successfully says the resource is up to date.

* Create a group on the system with a different group ID from the above, then try to `chef-apply` it:

Chef successfully says 

```
  * group[foobar] action create
    - alter group foobar
    - change gid 15849 to 15848
```

**Comment by coderanger** [comment]
@juliandunn Any chance it matters if there are procs running with that group? I know some user stuffs yell if that users has any processes.

**Comment by juliandunn** [comment]
@coderanger nope, still no repro. Started a shell with a user that has the `foobar` GID, tried both Chef and `chgroup` and it happily works.

**Comment by fwwasol** [comment]
Hello,
I have the same issue on a AIX 7.1 (7100-03-03-1415) system:

```
chgroup 'id=203' some_group returned 17, expected 0

 Resource Declaration:
 ---------------------
 # In /home/ext-asp-fwa/chef-solo/local-mode-cache/cache/cookbooks/lmt_aixsaphost/recipes/default.rb

  22: group 'some_group' do
  23:   gid '203'
  24:   system true
  25:   ignore_failure true
  26: end
  27:
```

when I execute the command in shell the following message is shown:

`Error changing "id" to "203" : Account exists.`

**Comment by lamont-granquist** [comment]
There isn't enough information here to debug and replication failed.

We'd need to see the full stacktrace.out ideally along with the `-l trace` output from around the failing user resource.
