### ISSUE TITLE
long chef run fails with Connection reset by peer - recvfrom(2)

### ISSUE THREAD

**Issue by lioramilbaum** [chef/chef#5056]
## Description

One of the resources in my recipe is a command which runs for few minutes. When issuing the recipe run (using knife ssh or knife ec2 server create) it fails with an error:
"ERROR: Errno::ECONNRESET: Connection reset by peer - recvfrom(2)"

When I issue the same recipe run with chef-client in a debug mode, it doesn't fail.

Briefly describe the issue

## Chef Version

chef.io

Tell us which version of chef-client you are using (see below for Server+ChefDK bugs).

12.11.18

## Platform Version

Tell us which Operating System distribution and version chef-client is running on.

RedHat 7.0

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by lamont-granquist** [comment]
its possible you have a firewall in between the host you're running 'knife ssh/knife bootstrap' on and the target host.  if ssh is not configured to use keepalives then when the connection goes idle while the resources is running the firewall may send a TCP RST on the idle connection and tear it down.  that would be really either a configuration issue for your network engineers or a configuration issue around ssh/sshd.  the added output from `-l debug` would probably keep the ssh connection alive.

**Comment by lioramilbaum** [comment]
Following your comment, I've investigated the ssh/sshd configuration. When I manually update the newly created ec2 instance with the settings:
ClientAliveInterval 60
ClientAliveCountMax 1000

And restart the sshd service, than I can run my recipe successfully with no debug info.

I've developed a recipe which configures the sshd service and restarts it. BUT, the settings doesn't take affect for the connection I am already running. 
Is there a way to implement a ssh reconnection with chef?

**Comment by lamont-granquist** [comment]
I don't think so.  Doubt you can use chef to manage the boostrapping connection.  You can fork/patch the AMI that you're using on EC2 to set the sshd_config settings.  You may be able to set up TCP keepalives on your workstation to get around this problem.  The best solution would be to get the network engineers responsible for the firewall in between you can EC2 to be more liberal about allowing idle connections.

On linux something like this might work:

```
  # echo 60 > /proc/sys/net/ipv4/tcp_keepalive_time
  # echo 60 > /proc/sys/net/ipv4/tcp_keepalive_intvl
  # echo 20 > /proc/sys/net/ipv4/tcp_keepalive_probes
```

(see http://tldp.org/HOWTO/TCP-Keepalive-HOWTO/usingkeepalive.html)

**Comment by lioramilbaum** [comment]
Well, I did find a solution with chef how to bootstrap the connection.  I invoke the knife command twice. The first one is for the connection bootstrap which restarts the sshd and the second one is for my recipes. The second knife call is invoked in a different ssh connection and therefor the settings works.

Thanks for leading me to the right solution.
