### ISSUE TITLE
powershell script ask for a server reboot while manual doesn't

### ISSUE THREAD

**Issue by basilboonk** [chef/chef#5057]
## Description

I have Windows server where i am trying to install .NET using powershell_script function in Chef.

`import-module servermanager 
add-windowsfeature NET-Framework-Core`

When I try manually the above commands manually on the windows server, it doesn't ask for a reboot. While I try it using Chef cookbook, it requires a reboot,

`powershell_script 'Install .Net' do
    code <<-EOH
        import-module servermanager
        add-windowsfeature NET-Framework-Core
        EOH
end`

Can we install this package without a server reboot using Chef ?
## Chef Version

Chef: 12.7.2
## Platform Version

Windows Server 2012 R2 Standard

PS C:> $PSVersionTable

Name                           Value

---

PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34209
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2
## Client Output
- powershell_script[Install .Net] action run
  [execute] WARNING: You must restart this server to finish the installation p
  rocess.
  
  ```
        Success Restart Needed Exit Code      Feature Result
  
        ------- -------------- ---------      --------------
  
        True    Yes            SuccessRest... {.NET Framework 3.5 (include
  ```
  
  s .NET 2.0...
  - execute "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLog
    o -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:
    /Users/AppData/Local/Temp/chef-script20160624-21664-1sl7ook.ps1"

Where as manual installation doesn't need a reboot. Attached the image for the same,
![manual-run](https://cloud.githubusercontent.com/assets/20127561/16337854/334a4350-3a36-11e6-9349-e1698d5e5ba6.jpg)

**Comment by thommay** [comment]
@chef/client-windows please take a look, this seems weird

**Comment by mwrock** [comment]
There are several things that can impact the need for a restart. Is that `powershell_script` the only, or at least the first, resource in your converge. On a clean vm if I run JUST that `powershell_script` then a restart is not required.

You might want to use the `-LogPath` parameter of `Add-WindowsFeature` and that might provide clues as to why a restart is needed.

**Comment by smurawski** [comment]
@mwrock  is correct here.. there are a number of things that can influence whether a restart is required or not.  Previous installations, user context (how and as what user is Chef running), and patch status of the machine all impact whether a reboot in required when enabling a windows feature.  This is not something we can really change about the `powershell_script` resource.
