### ISSUE TITLE
knife environment create treats -d and --description differently

### ISSUE THREAD

**Issue by tpetchel** [chef/chef#5064]
## Description

Passing the `-d` flag to `knife environment create` does not try to bring up `EDITOR`, but passing `--description` does. I would expect both flags to behave identically.

https://docs.chef.io/knife_environment.html#create

## Chef Version

```
Chef Development Kit Version: 0.15.15
chef-client version: 12.11.18
delivery version: 0.0.23 (bf89a6b776b55b89a46bbd57fcaa615c143a09a0)
berks version: 4.3.5
kitchen version: 1.10.0
```

## Platform Version

Windows Server 2012 R2

## Replication Case

```
C:\Users\Administrator\delivery-demo\delivery-base [master ≡]> knife environment create acceptance-mammalia-diprotodontia-awesome_customers_delivery-master --description "The acceptance environment"
ERROR: RuntimeError: Please set EDITOR environment variable
C:\Users\Administrator\delivery-demo\delivery-base [master ≡]> knife environment create acceptance-mammalia-diprotodontia-awesome_customers_delivery-master -d "The acceptance environment"
Created acceptance-mammalia-diprotodontia-awesome_customers_delivery-master
```

## Client Output

N/A

## Stacktrace

N/A

**Comment by thommay** [comment]
This is a doc bug, `--description` doesn't have a short option. I have a change that needs delivering that fixes this.
