### ISSUE TITLE
chef-solo - Tuto : Error Resolving Cookbooks for Run List

### ISSUE THREAD

**Issue by MantaRayDeeJay** [chef/chef#5067]
## Description

I'm trying to follow the chef-solo tuto available at http://gettingstartedwithchef.com/first-steps-with-chef.html
But when I type "chef-solo -c solo.rb -j web.json", I have the following error message

## Chef Version

Starting Chef Client, version 12.11.18

## Platform Version

vagrant@precise64 (Ubuntu precise 64 via a virtual box vagrant VM)

## Replication Case

Please see the following link, I have posted on StackOverflow
http://stackoverflow.com/questions/38082226/chef-solo-tuto-error-resolving-cookbooks-for-run-list

## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.
[chef-stacktrace.zip](https://github.com/chef/chef/files/338752/chef-stacktrace.zip)

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by coderanger** [comment]
As stated in the template, this is for bugs only, not user support. I've fixed the tags on your StackOverflow post (in the future make sure you use the `chef` tag) so it should now be seen by our usual SO volunteers.

**Comment by MantaRayDeeJay** [comment]
Thanks for your tip. I will do it next time
