### ISSUE TITLE
Value of default_unless node attribute reset each run

### ISSUE THREAD

**Issue by tpetchel** [chef/chef#5069]
## Description

We have a Learn Chef tutorial that uses `default_unless` to set MySQL passwords. When you run the cookbook on a node, `chef-client` fails the second time because the node attribute for the MySQL password changes.

A user reported the issue here: https://learn.chef.io/manage-a-web-app/rhel/run-your-web-application-on-a-node/#comment-2755482616

I'm hoping someone can help me figure out if this is a Chef bug or I'm doing something wrong.

Here's a slimmer repro case:

In my default attributes file, I have:

```
def random_password
  require 'securerandom'
  SecureRandom.base64
end

default_unless['root_password'] = random_password
```

Then in a recipe:

```
pp "The root password is #{node['root_password']}."
```

Note how the node attribute's value changes. First run:

```
$ chef-client --local-mode --runlist 'recipe[default_unless_test]'
[2016-06-29T10:11:07-04:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 12.11.18
resolving cookbooks for run list: ["default_unless_test"]
Synchronizing Cookbooks:
  - default_unless_test (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
"The root password is Q4Ylh/hT3+UQ2imLz8QgUw==."
Converging 0 resources

Running handlers:
Running handlers complete
Chef Client finished, 0/0 resources updated in 02 seconds
```

Second run:

```
$ chef-client --local-mode --runlist 'recipe[default_unless_test]'
[2016-06-29T10:11:26-04:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 12.11.18
resolving cookbooks for run list: ["default_unless_test"]
Synchronizing Cookbooks:
  - default_unless_test (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
"The root password is wQu0l8PPDuEn3X0BnJr+tA==."
Converging 0 resources

Running handlers:
Running handlers complete
Chef Client finished, 0/0 resources updated in 02 seconds
```

The same thing happens when you run the cookbook on a bootstrapped node.

## Chef Version

```
$ chef-client --version
Chef: 12.11.18
```

## Platform Version

Mac OS X (repro case), first seen on CentOS 7.2.

## Replication Case

Clone https://github.com/tpetchel/default_unless_test and run `chef-client --local-mode --runlist 'recipe[default_unless_test]'`.

## Client Output

See above.

## Stacktrace

N/A

**Comment by lamont-granquist** [comment]
default and override levels are always wiped at the start of every chef run.  you have to use `node.normal_unless` to get persistence.

note that this is amazingly insecure.  every other node node on the chef server can query the node object and see the password, so basically you're blasting your password out publicly to every server -- if any of them get hacked the secrets are visible.

this is kind of bad pattern to be teaching people, since its always wrong from a security perspective.

**Comment by tpetchel** [comment]
Just wanted to say thanks for pointing that out. I got a few more opinions, and understand what to do now to improve things. It'll be more in the spirit of this article: http://atomic-penguin.github.io/blog/2013/06/07/HOWTO-test-kitchen-and-encrypted-data-bags/.
