### ISSUE TITLE
Ability to increase concurrency during a knife ssh run

### ISSUE THREAD

**Issue by RyanJarv** [chef/chef#5070]
Often I use knife ssh for deploying changes to large clusters, usually I want to do a few nodes slowly and then start going through the rest faster. If I wanted to do this with knife ssh right now I would have to run the command with -C 1, interrupt the command when everything is going well and rerun it with a higher concurrency which means it will run on all the nodes again.

It would be awesome if there was a way to increase the number of concurrent hosts in the middle of a run, possibly through another form of -C like '-C 1:60:10' which would mean run on one host at first and increase concurrency every 60 seconds up to 10 total. Being able to increase the concurrency with a keybinding would also be useful.

**Comment by coderanger** [comment]
This seems out of scope for `knife ssh`. When you reach this point I would recommend using more dedicated remote execution tools :)

**Comment by RyanJarv** [comment]
I mostly use knife ssh because of the ability to use search query's, any idea where to look for something that would integrate with chef search similarly?

**Comment by coderanger** [comment]
Fabric and SaltStack's command runners both have Chef integrations via PyChef. You can also look at tools like RunDeck, Chef Push Jobs, and MCollective which all have Chef integrations.

**Comment by RyanJarv** [comment]
Ok thanks will take a look at those.

**Comment by lamont-granquist** [comment]
Yeah i think if we had code we might consider just whacking merge, but without code we'll probably never prioritize this as an issue.

Closing this not as a 'no' but as a 'no time'.
