### ISSUE TITLE
Default location for zero mode

### ISSUE THREAD

**Issue by Tensibai** [chef/chef#5078]
## Description

Chef-solo default to zero mode from 12.11.18 (ref #4919).
Issue linked to Berkshelf [#1483](https://github.com/berkshelf/berkshelf/issues/1483)  and Chef client's #4186

The location to untar the tarball is current directory and not solo default of `/var/chef/cookbooks` and it can overwrite owner and modes of parents directory. 

## Chef Version

Since 12.11.18 with chef-solo mode (not harmfull when using legacy mode as the cookbook path is defaulted to `/var/chef/cookbooks`)

## Platform Version

Any

## Replication Case

Create a tarball with berks package, see berkshelf issue [#1483](https://github.com/berkshelf/berkshelf/issues/1483)

## Client Output

Working directory inherit tarball `.` permissions, creating side effects on target system when tarball user, group and permissions are restricted.

## (Debatable) Propositions:

1. Use tar parameters to drop user and modes from tarball (safest for target node IMHO) ([Here if I read properly](https://github.com/chef/chef/blob/7e3a0aa1ed3559dd599b95cfb90599e2aeedbe6f/lib/chef/application/client.rb#L337):
     ```
     --no-same-owner
           extract files as yourself (default for ordinary users)

     --no-same-permissions
           apply the user's umask when extracting permissions from the archive (default for ordinary users)
     ```
    Adding those two parameters at end of line should do.

2. Exclude `.` from extraction:
[Here again](https://github.com/chef/chef/blob/7e3a0aa1ed3559dd599b95cfb90599e2aeedbe6f/lib/chef/application/client.rb#L337)

    with `--exclude '.'` at end of line

3. Make chef-zero use a defined default path (/var/chef/repo for example) instead of current directory if run as root without configuration:

I assume this should be done [here](https://github.com/chef/chef/blob/master/chef-config/lib/chef-config/config.rb#L128-L142)

##In my point of view
 - 1. is the best option as it prevents chef from modifying permissions by a corrupted tarball,drawbak is that I didn't ensure which versions of tar allow those parameters.
 - 2. is the safe one but we still write the tarball anywhere on the target system which could be abused (but if the tarball is compromised, it could do a lot from the recipes within anyway).
 - 3. Is probably the most conservative one but also the more complex to implement and the most subject to break someone use case soemwhere in my opinion.

## Workarounds:

1. Run chef-solo with `--legacy` command line option to get the previous behavior (using `/var/chef/cookbooks` as target)
2. Create `§etc§chef/client.rb` file with content:
`chef_repo_path '/var/chef/repo'`
3. (Highly discouraged) Monkey patch chef to avoid this behavior

## Conclusion

Even if fixing the untar of the recipes tarball won't guarantee there won't be malicious code executed, it makes harder to corrupt a system than a simple tar file with malicious relative path.

Root cause is within berkshelf `Archive::Tar::Minitar` call [here](https://github.com/berkshelf/berkshelf/blob/master/lib/berkshelf/packager.rb#L45), sadly the issue is there for more than one year now and I'm unsure whether it should be a double fix (Archive and berkshelf) or only berkshelf (probabaly using `./*` instead of `.` would do the trick). 

P.S: I'll try to bake some PR for each behavior.

**Comment by thommay** [comment]
Hi,
I'd expect this to be fixed in 12.12 due to #5059 ; please can you try the prerelease (https://discourse.chef.io/t/pre-announcement-chef-client-v12-12-13-release/8835) ?
Thanks,
-Thom

**Comment by Tensibai** [comment]
@thomascate  "bug" is still present, when running as root with no config the repo_path is set to current working directory.

I think the root is the block of code here: https://github.com/chef/chef/blob/master/chef-config/lib/chef-config/config.rb#L128-L142

Log output with the warning log entry from line 135 (prefixed by >>> here):

```
[2016-07-04T14:19:58+00:00] WARN: *****************************************
[2016-07-04T14:19:58+00:00] WARN: Did not find config file: /etc/chef/solo.rb, using command line options.
[2016-07-04T14:19:58+00:00] WARN: *****************************************
>>> [2016-07-04T14:19:58+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /usr/local/src.
[2016-07-04T14:19:58+00:00] WARN: *****************************************
[2016-07-04T14:19:58+00:00] WARN: Did not find config file: /etc/chef/client.rb, using command line options.
[2016-07-04T14:19:58+00:00] WARN: *****************************************
Starting Chef Client, version 12.12.13
[....]
```

The issue you linked to fix the subsequent runs as the cookbooks directory exists in cache location (when a runlist exists), but not for first run.

I'll be happy to help digging on the best direction on the 3 above, I'm too lazy to prepare 3 PR for each case. 

Moreover, as the tarball is extracted before any other event, someone could bake a tarball to change perms on other files without even the need to write a cookbook, I know this is relatively low (as if you can give chef a tarball you can have a cookbook within doing the same change), but I'm uncomfortable to leave it as is now I know it :/

**Comment by thommay** [comment]
Thanks for digging in to this. I think the fact it always returns `Dir.pwd` is actually the bug, and I see no reason not to just fix that. Would you like to put together a PR for that? 
There's a longer fix - moving chef to using mixlib-archive, and then ignoring permissions in this instance.

**Comment by Tensibai** [comment]
I agree to the longer fix, I'm unsure I'm able to write it that said. for the quick fix (returning cwd instead of Dir.pwd, I'll try to write it before leaving work now)

**Comment by Tensibai** [comment]
@thommay Looking at mixlib-archive I can't get how it would/could ignore permissions, seems it set the entry permission to destination without control over this behavior (per [line 38](https://github.com/chef/mixlib-archive/blob/master/lib/mixlib/archive/tar.rb#L38)).

Did I miss something there, or do you mean mixlib-archive should be improved too for this use case ?

**Comment by thommay** [comment]
@Tensibai https://github.com/chef/mixlib-archive/pull/2 so no, you didn't miss anything :)
