### ISSUE TITLE
knife needs to enforce chef_type when `from file` sub-command is used

### ISSUE THREAD

**Issue by haidangwa** [chef/chef#5086]
## Description

With `knife environment from file` or `knife role from file`, the chef_type specification is not enforced. I can easily upload an environments JSON as a role by doing this: `knife role from file Dev.json`, when Dev.json is really an environments file.
## Chef Version

chefdk 0.15.15, but I believe this bug goes way back
## Platform Version

Redhat and Mac
## Replication Case

`knife role from file Dev.json`, when Dev.json is really an environments file.

There needs to be some validation that the JSON is being uploaded as the right type by enforcing chef_type in the JSON.

**Comment by lamont-granquist** [comment]
closing in favor of #8829
