### ISSUE TITLE
knife-cookbook-site-share and knife-supermarket producing 404 errors

### ISSUE THREAD

**Issue by loganmeetsworld** [chef/chef#5088]
## Description

When I use the command `knife cookbook site share -o <location> <cookbook-name> -k <key-location> -VV` or the same command with `knife supermarket share`, I get the error: 
`FATAL: Unable to reach Supermarket: 404 "Not Found". Increase log verbosity (-VV) for more information.`

## Chef Version

chef -v: 
`Chef Development Kit Version: 0.15.16
chef-client version: 12.12.14
delivery version: master (444effdf9c81908795e88157f01cd667a6c43b5f)
berks version: 4.3.5
kitchen version: 1.10.0`

## Platform Version

Mac 10.11.5

## Replication Case

1. Uninstall knife supermarket: `gem uninstall knife-supermarket`
2. Install appbundle-updater: `chef gem install appbundle-updater`
3. Install chef v12.12.13: `sudo chef exec appbundle-updater chefdk chef v12.12.13`
4. Run  `knife cookbook site share -o <location> <cookbook-name> -k <key-location> -VV`
5. In terraformed supermarket knife.rb, point supermarket-site to the public ip of the terraform supermarket. 

## Stacktrace

Short: 
`FATAL: Unable to reach Supermarket: 404 "Not Found". Increase log verbosity (-VV) for more information.`

All output: 
`DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://supermarket.chef.io/api/v1/cookbooks/dino
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-REMOTE-REQUEST-ID: 8f85fe7f-e416-4093-b160-a52f8476834b
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 404 Not Found
DEBUG: cache-control: no-cache
DEBUG: content-encoding: gzip
DEBUG: content-type: application/json; charset=utf-8
DEBUG: date: Wed, 06 Jul 2016 20:26:14 GMT
DEBUG: server: nginx/1.8.1
DEBUG: status: 404 Not Found
DEBUG: x-content-type-options: nosniff
DEBUG: x-frame-options: SAMEORIGIN
DEBUG: x-request-id: 6669e6f7-0eec-4de1-a101-3aa94fe3ded9
DEBUG: x-runtime: 0.007463
DEBUG: x-xss-protection: 1; mode=block
DEBUG: content-length: 87
DEBUG: connection: Close
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: ---- HTTP Response Body ----
DEBUG: �VJ-*�/��M-.NLO-V��V
J-�/-JNUH�O-V��/QH��,.�S�Ձ�N�OIU�R���w��sQ��?H
DEBUG: ---- End HTTP Response Body -----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
INFO: HTTP Request Returned 404 Not Found:
FATAL: Unable to reach Supermarket: 404 "Not Found". Increase log verbosity (-VV) for more information.
DEBUG:
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
/Users/loganmcdonald/.chefdk/gem/ruby/2.1.0/gems/chef-12.12.14/lib/chef/http.rb:146:in `request'
/Users/loganmcdonald/.chefdk/gem/ruby/2.1.0/gems/chef-12.12.14/lib/chef/http.rb:111:in `get'
/Users/loganmcdonald/.chefdk/gem/ruby/2.1.0/gems/chef-12.12.14/lib/chef/knife/cookbook_site_share.rb:117:in `get_category'
/Users/loganmcdonald/.chefdk/gem/ruby/2.1.0/gems/chef-12.12.14/lib/chef/knife/cookbook_site_share.rb:69:in `run'
/Users/loganmcdonald/.chefdk/gem/ruby/2.1.0/gems/chef-12.12.14/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
/Users/loganmcdonald/.chefdk/gem/ruby/2.1.0/gems/chef-12.12.14/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/Users/loganmcdonald/.chefdk/gem/ruby/2.1.0/gems/chef-12.12.14/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
/Users/loganmcdonald/.chefdk/gem/ruby/2.1.0/gems/chef-12.12.14/lib/chef/knife.rb:219:in `run'
/Users/loganmcdonald/.chefdk/gem/ruby/2.1.0/gems/chef-12.12.14/lib/chef/application/knife.rb:148:in `run'
/Users/loganmcdonald/.chefdk/gem/ruby/2.1.0/gems/chef-12.12.14/bin/knife:25:in `<top (required)>'
/opt/chefdk/bin/knife:52:in `load'
/opt/chefdk/bin/knife:52:in `<main>'`

**Comment by nellshamrell** [comment]
I am also seeing this issue after upgrading to 12.12.14 (which contains the aliased knife supermarket commands) and uninstalling the now defunct knife supermarket gem.

**Comment by loganmeetsworld** [comment]
Also seeing the same issue on 12.12.13.

**Comment by thommay** [comment]
OK, I think this is an ancient bug that you've just stumbled upon :)
When a cookbook doesn't exist - which `dino` doesn't - you should specify the category of the cookbook, by running `knife supermarket share dino Other`. When you don't specify the category, you're supposed to get a helpful error message: https://github.com/chef/chef/blob/v12.11.27/lib/chef/knife/cookbook_site_share.rb#L111-L112 ; but we throw an exception and so never get there.

**Comment by JTabel** [comment]
I am stumbling upon this as well, but with a slightly different case. I am using a private supermarket within our company and I have the supermarket url configured in my knife.rb. However, upon sharing a cookbook, I get the 404 error with the same output. I does not show the URL of our private chef server in the verbose output, but instead tries to use the upstream chef supermarket, which obviously does not have the cookbook. Also trying to pass the supermarket-site as a parameter does not change this behaviour. Running chef 12.12.3.

**Comment by thommay** [comment]
@JTabel that doesn't sound like the same bug. Please open a new bug, with the verbose log output from `knife -VV supermarket share ...`

**Comment by JTabel** [comment]
Sure, will do.

**Comment by aershov1978** [comment]
Supermarket URL is hardcoded in chef-12.12.15/lib/chef/knife/cookbook_site_share.rb:
`def get_category(cookbook_name)
        begin
          data = noauth_rest.get("https://supermarket.chef.io/api/v1/cookbooks/#{@name_args[0]}")
          if !data["category"] && data["error_code"]
            ui.fatal("Received an error from Supermarket: #{data["error_code"]}. On the first time you upload it, you are required to specify the category you want to share this cookbook to.")
            exit(1)
          else`
