### ISSUE TITLE
Overridden `name_attribute` not matching a condition triggers `does not match` warning, even if it's overriden by a proper value in body.

### ISSUE THREAD

**Issue by chr4** [chef/chef#5090]
## Description
False positive warning (I assume) if a `name_attribute` attributes has a `regex` condition (I assume this is also true for other conditions), but it's overriden in the body with an attribute matching the condition. See example in "Replication Case". As the actual value used by the provider matches the `regex` condition, I think this could be a false positive, or is there a simple solution I cant' think of?

## Chef Version
12.12.13

## Platform Version
Ubuntu Xenial 16.04 LTS

## Replication Case
I've encountered this issue using the [iptables-ng cookbook](https://github.com/chr4-cookbooks/iptables-ng).

The `iptables_ng_chain` ressource has a `named_attribute` with a `regex` condition:

iptables-ng/ressources/chain.rb:
```ruby
attribute :chain,  kind_of: String, name_attribute: true, regex: /^\S{1,29}$/
```

Because `chef-client` complains when specifying multiple resources with the same name, the `name_attribute` is concatinated using other attributes. The `chain` attribute then sets the actual attribute that's going to be used:

iptables-ng/providers/chain.rb:
```ruby
iptables_ng_chain "#{new_resource.chain}:#{new_resource.table}:#{new_resource.name}" do
  chain  new_resource.chain
  [...]
end
```

## Client Output
```
  Default value "FORWARD:filter:10-forward-drop-invalid" is invalid for property chain of resource iptables_ng_chain. In Chef 13 this will become an error: Option chain's value FORWARD:filter:10-forward-drop-invalid does not match regular expression /^\S{1,29}$/. at 1 location:
    - /var/chef/cache/cookbooks/iptables-ng/providers/rule.rb:42:in `block in edit_rule'
```

**Comment by lamont-granquist** [comment]
Fixing this might be a little bit tortured because we'll have to delay validation of the name being passed to the name property until the end of the block when we're certain we haven't set the name property explicitly.

**Comment by jkeiser** [comment]
I'm a little surprised actually, because I wouldn't expect `chain`'s default value to be evaluated until it was used. Can you show a little more of the stack and show exactly which line it failed on? Thanks!

**Comment by jkeiser** [comment]
Oh, right. It doesn't have a stack.

The only diagnostic I can think of, is perhaps could you try and replace the `iptables_ng_chain` lines in the `edit_rule` function with this:

```
x = "#{new_resource.chain}:#{new_resource.table}:#{new_resource.name}"
c = iptables_ng_chain x
x = new_resource.chain
c.chain x
x = new_resource.table
c.table x
c.action :create_if_missing
c.not_if { exec_action == :delete }
```

And tell me what line triggers the warning at that point? There are just so many `chain`s it's hard to keep up :)

**Comment by jkeiser** [comment]
I suspect the stack might not have been telling us the whole truth in this case.  A short repro does not repro this issue:

```ruby
class X < Chef::Resource
  resource_name :xyz
  property :blah, name_property: true, regex: /a/
end
xyz "b" do
  blah "a"
end
xyz "c" do
  puts blah
end
```

The above recipe fails on line 9 with `Default value "c" is invalid for property blah of resource xyz.` and does *not* fail on line 6.

Not to say something isn't wrong with your case--clearly something is wrong somewhere--but I'm not sure it's the problem we have been chasing. Getting the diagnostics from previous comment will help :)

**Comment by jkeiser** [comment]
@lamont-granquist I removed "Accepted Minor" until we get to the bottom of this.

**Comment by chr4** [comment]
Thanks for your response!
I've changed `providers/rule.rb` as [you proposed](https://github.com/chef/chef/issues/5090#issuecomment-237455685) with the following results (`rule.rb:43` being `c = iptables_ng_chain x` (line 2 in your snipped):

```
  Default value "INPUT:filter:50-nginx" is invalid for property chain of resource iptables_ng_chain. In Chef 13 this will become an error: Option chain's value INPUT:filter:50-nginx does not match regular expression /^[\w-]{1,29}$/. at 1 location:
    - /var/chef/cache/cookbooks/iptables-ng/providers/rule.rb:43:in `block in edit_rule'
  Cloning resource attributes for iptables_ng_chain[INPUT:filter:50-nginx] from prior resource (CHEF-3694)
Previous iptables_ng_chain[INPUT:filter:50-nginx]: /var/chef/cache/cookbooks/iptables-ng/providers/rule.rb:43:in `block in edit_rule'
Current  iptables_ng_chain[INPUT:filter:50-nginx]: /var/chef/cache/cookbooks/iptables-ng/providers/rule.rb:43:in `block in edit_rule' at 1 location:
    - /var/chef/cache/cookbooks/iptables-ng/providers/rule.rb:43:in `block in edit_rule'
```

This is how `iptables_ng_rule` is called:
```ruby
iptables_ng_rule '50-nginx' do
  rule ['-i eth1 --protocol tcp --dport 80  --match state --state NEW --jump ACCEPT',
        '-i eth1 --protocol tcp --dport 443 --match state --state NEW --jump ACCEPT']
end
```

Is this of any help? Let me know if there's more that I can provide.

**Comment by lamont-granquist** [comment]
yeah the correct fix for your code is to fix the CHEF-3694 resource cloning warning message.  that produces correct code, and is literally the best practice for coding what you're trying to do.

the interaction with resource cloning and the property evaluation here is mildly awful, but the solution is we need to remove resource cloning -- the property code isn't buggy, this just goes onto the huge stack of reasons why resource cloning is bad.
