### ISSUE TITLE
Knife supermarket share does not take into account a custom supermarket URL

### ISSUE THREAD

**Issue by JTabel** [chef/chef#5092]
## Description

When I tried uploading a new version of a cookbook to our private supermarket, I got `FATAL: Unable to reach Supermarket: 404 "Not Found". Increase log verbosity (-VV) for more information.`

## Chef Version

`chef -v
Chef Development Kit Version: 0.11.2
chef-client version: 12.12.13
berks version: 4.3.5
kitchen version: 1.10.2`

## Platform Version

OSX 10.11.5 (my local machine) as well as Ubuntu 14.04 (build server)

## Replication Case

When using a private supermarket, try uploading a cookbook to it. You can either have the supermarket url configured in knife.rb or call knife supermarket share with --supermarket-site or -m. Both result in the same error message.

## Stacktrace

`INFO: Using configuration from /Users/juliantabel/workspace/chef/.chef/knife.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://supermarket.chef.io/api/v1/cookbooks/xing_bamboo
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-REMOTE-REQUEST-ID: ca101a01-f86b-4e06-9764-714e10614e87
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 404 Not Found
DEBUG: cache-control: no-cache
DEBUG: content-encoding: gzip
DEBUG: content-type: application/json; charset=utf-8
DEBUG: date: Thu, 07 Jul 2016 13:32:19 GMT
DEBUG: server: nginx/1.8.1
DEBUG: status: 404 Not Found
DEBUG: x-content-type-options: nosniff
DEBUG: x-frame-options: SAMEORIGIN
DEBUG: x-request-id: fc3f270c-782a-48a1-985a-eee806ae39e6
DEBUG: x-runtime: 0.006163
DEBUG: x-xss-protection: 1; mode=block
DEBUG: content-length: 87
DEBUG: connection: Close
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: ---- HTTP Response Body ----
DEBUG: �VJ-*�/��M-.NLO-V��V
J-�/-JNUH�O-V��/QH��,.�S�Ձ�N�OIU�R���w��sQ��?H
DEBUG: ---- End HTTP Response Body -----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
INFO: HTTP Request Returned 404 Not Found:
FATAL: Unable to reach Supermarket: 404 "Not Found". Increase log verbosity (-VV) for more information.
DEBUG:
/Users/juliantabel/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'
/Users/juliantabel/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-12.12.13/lib/chef/http.rb:146:in `request'
/Users/juliantabel/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-12.12.13/lib/chef/http.rb:111:in `get'
/Users/juliantabel/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-12.12.13/lib/chef/knife/cookbook_site_share.rb:117:in `get_category'
/Users/juliantabel/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-12.12.13/lib/chef/knife/cookbook_site_share.rb:69:in `run'
/Users/juliantabel/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-12.12.13/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
/Users/juliantabel/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-12.12.13/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/Users/juliantabel/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-12.12.13/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
/Users/juliantabel/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-12.12.13/lib/chef/knife.rb:219:in `run'
/Users/juliantabel/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-12.12.13/lib/chef/application/knife.rb:148:in `run'
/Users/juliantabel/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/chef-12.12.13/bin/knife:25:in `<top (required)>'
/Users/juliantabel/.rbenv/versions/2.3.0/bin/knife:23:in `load'
/Users/juliantabel/.rbenv/versions/2.3.0/bin/knife:23:in `<main>

**Comment by lamont-granquist** [comment]
dup of #5088

**Comment by JTabel** [comment]
@lamont-granquist I wrote a reply in #5088 and I was told this was a different problem and I should open another issue ...

**Comment by thommay** [comment]
yeah, it's not a dup. but it is fixed, regardless.
