### ISSUE TITLE
Audit mode 'bout to be broken

### ISSUE THREAD

**Issue by tyler-ball** [chef/chef#5095]
## Description

Rspec 3.5.1 changes a private API we are leveraging which is going to throw a NoMethodError when trying to call.

We call [`Rspec.world.register`](https://github.com/chef/chef/blob/686113531d23f30e9973d659c456ae33eb9cff1f/lib/chef/audit/runner.rb#L168) but they changed the API to [`Rspec.world.record`](https://github.com/rspec/rspec-core/commit/8e564dca9e5962bb6b41865af3fa49f2c3cbe5dd#diff-3831ad1cf9ec21d559640a066a9d3bc8).

As long as we keep `rspec-core` pinned to 3.4.4 we avoid this.

## Chef Version

All since audit mode was added.

## Platform Version
All

## Replication Case

Run `rake dependencies` to update `rspec-core`. Hopefully we have a test that fails. If not, we need to write one.

**Comment by tyler-ball** [comment]
We discovered this in the ChefDK, so [pinned it there](https://github.com/chef/chef-dk/pull/932).

**Comment by mwrock** [comment]
:+1:

**Comment by thommay** [comment]
It's pinned in chef now too.
