### ISSUE TITLE
Chef-zero: remote_directory resource fails if sub-folder/file contains spaces

### ISSUE THREAD

**Issue by erikng** [chef/chef#5105]
## Description

When using the remote_directory resource, if any folder/file contains spaces, chef-client errors out

## Chef Version

Chef Client OS X, version 12.11.18

## Platform Version

OS X, 10.11.5

## Replication Case

Create a cookbook with the following:
recipes/default.rb
```
remote_directory '/Users/Shared/test' do
  owner 'system'
  group 'wheel'
  mode '0755'
  recursive true
  source 'rootfolder'
  action :create
end
```

file structure
`files/default/rootfolder/folder with spaces/file` 
or
`files/default/rootfolder/folder/file with spaces` 

## Client Output

```Unexpected Error:
URI::InvalidURIError: bad URI(is not URI?): chefzero://localhost:8889/file_store/repo/cookbooks/remote_directory_test/files/default/rootfolder/folder with spaces/chef-12.11.18-1.dmg```

## Stacktrace

```
Generated at 2016-07-12 16:31:37 -0700
URI::InvalidURIError: bad URI(is not URI?): chefzero://localhost:8889/file_stor$
/opt/chef/embedded/lib/ruby/2.1.0/uri/common.rb:176:in `split'
/opt/chef/embedded/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
/opt/chef/embedded/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/http.rb:251:$
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/http.rb:194:$
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/cookbook/syn$
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/cookbook/syn$
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/cookbook/syn$
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/util/threade$
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/util/threade$
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/util/threade$
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/util/threade$
```

**Comment by lamont-granquist** [comment]
Replicated on 12.12.21, note that this is a chef-zero bug and that chef-client against hosted works fine with a file-with-spaces.

```
% chef-client -z -r 'test::default'
Starting Chef Client, version 12.12.21
resolving cookbooks for run list: ["test::default"]
Synchronizing Cookbooks:

  ================================================================================
  Error Syncing Cookbooks:
  ================================================================================

  Unexpected Error:
  -----------------
  URI::InvalidURIError: bad URI(is not URI?): chefzero://localhost:8889/file_store/repo/cookbooks/test/files/folder/test file

  Platform:
  ---------
  x86_64-darwin15


  Running handlers:
[2016-07-13T11:25:41-05:00] ERROR: Running exception handlers
  Running handlers complete
[2016-07-13T11:25:41-05:00] ERROR: Exception handlers complete
  Chef Client failed. 0 resources updated in 06 seconds
[2016-07-13T11:25:41-05:00] FATAL: Stacktrace dumped to /Users/lamont/zero/local-mode-cache/cache/chef-stacktrace.out
[2016-07-13T11:25:41-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-07-13T11:25:41-05:00] ERROR: bad URI(is not URI?): chefzero://localhost:8889/file_store/repo/cookbooks/test/files/folder/test file
[2016-07-13T11:25:41-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by thommay** [comment]
Yeah, @cheeseplus and @jkeiser were poking something similar looking earlier that was solo specific

**Comment by thommay** [comment]
This was just fixed in chef-zero, should be in the next release.

**Comment by erikng** [comment]
@thommay should this be fixed as of 12.13.13? I ran `curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -c current` on a test machine and the issue is still present.

**Comment by lamont-granquist** [comment]
works in 12.13.14:

```
Starting Chef Client, version 12.13.14
resolving cookbooks for run list: ["test::default"]
Synchronizing Cookbooks:
  - test (0.0.1)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: test::default
  * remote_directory[/tmp/foo] action create
    - create new directory /tmp/foo
  Recipe: <Dynamically Defined Resource>
    * cookbook_file[/tmp/foo/file with spaces] action create
      - create new file /tmp/foo/file with spaces
      - update content in file /tmp/foo/file with spaces from none to e3b0c4
      (no diff)
      - change mode from '' to '0644'


Running handlers:
Running handlers complete
Chef Client finished, 2/2 resources updated in 04 seconds
```

**Comment by erikng** [comment]
How long does it take omnitruck to post the latest build?

https://omnitruck.chef.io/current/chef/metadata?v=12.13.14&p=mac_os_x&pv=10.11&m=x86_64 is not pulling in data.

**Comment by lamont-granquist** [comment]
Within 24 hours, or if its broken, however long it takes to fix it...
