### ISSUE TITLE
Nokogiri not in chef client 12.12.x packages

### ISSUE THREAD

**Issue by jakemig** [chef/chef#5116]
## Description

Starting with version 12.7.0, nokogiri was included in chef client installations as per https://github.com/chef/chef/pull/4435. The latest installs, however, do not include this gem despite a reference to updating it in 12.12.13 (https://github.com/chef/chef/pull/5042). Is the nokogiri gem no longer supposed to be bundled or is this an error?

## Chef Version

12.12.13 & 12.12.15

## Platform Version

Tested on both Ubuntu and Windows.

## Replication Case

Install the chef 12.12.15 .deb file.
```
$ ls /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/nokogiri*
ls: cannot access /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/nokogiri*: No such file or directory
```

## Client Output

N/A

## Stacktrace

```
LoadError: cannot load such file -- nokogiri
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from (irb):1
        from /opt/chef/embedded/bin/irb:11:in `<main>'
```

**Comment by coderanger** [comment]
Ping @lamont-granquist I think we oops'd >_<

**Comment by lamont-granquist** [comment]
Paging @mwrock or @btm maybe?

Its supposed to still be there and its in the Gemfile.lock and it's been trolling me because now appbundle-updater wants to install it everywhere when it didn't before, so I find it highly puzzling that it could have been missed...

**Comment by petecheslock** [comment]
Any idea when the next release is going to be with the fixed chef client package with nokogiri included?

**Comment by mwrock** [comment]
Should be Wednesday next week. Hoping to announce a RC tomorrow.

**Comment by petecheslock** [comment]
Cool thanks @mwrock!
