### ISSUE TITLE
ArgumentError: invalid byte sequence in UTF-8 on windows

### ISSUE THREAD

**Issue by tsmith-sdm** [chef/chef#5120]
## Description

 Chef::EncryptedDataBagItem.load fails with a ArgumentError: invalid byte sequence in UTF-8 on windows

## Chef Version

Chef Development Kit Version: 0.14.25
chef-client version: 12.10.24
berks version: 4.3.3
kitchen version: 1.8.0

## Platform Version

ChefDK is running on Windows 8.1 Pro with Powershell 4.0
chef-client is running on Windows Server 2012 R2 Standard

## Replication Case
Run ChefDK
> openssl rand -base64 512 | tr -d '\r\n' > secret_key
> knife data bag create −−secret-file secret_key credentials test

Tested JSON editing with Sublime3, TextPad and notepad. Tried as default ANSI and Save As UTF-8 in both Sublime3 and TextPad.

{
  "id": "test",
  "username": "test",
  "password": "123456"
}

Then on the client side

test = Chef::EncryptedDataBagItem.load("credentials", "test")

## Stacktrace

Generated at 2016-07-18 06:56:33 -0700
ArgumentError: invalid byte sequence in UTF-8
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/encrypted_data_bag_item.rb:147:in `strip'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/encrypted_data_bag_item.rb:147:in `load_secret'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/encrypted_data_bag_item.rb:124:in `load'
c:/chef/cache/cookbooks/sdm-cookbook-fit-server/recipes/default.rb:13:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/mixin/from_file.rb:30:in `from_file'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/cookbook_version.rb:233:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/run_context.rb:354:in `load_recipe'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:140:in `block in compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:138:in `compile_recipes'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/run_context/cookbook_compiler.rb:75:in `compile'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/run_context.rb:176:in `load'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/client.rb:510:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/client.rb:280:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application.rb:268:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application.rb:244:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application.rb:227:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application/client.rb:456:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application/client.rb:443:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application/client.rb:442:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application/client.rb:442:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application/client.rb:426:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/lib/chef/application.rb:59:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.12.15-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:63:in `load'
C:/opscode/chef/bin/chef-client:63:in `<main>'
ArgumentError: invalid byte sequence in UTF-8

**Comment by tsmith-sdm** [comment]
Didn't scroll up far enough to see the real error

Recipe Compile Error in c:/chef/cache/cookbooks/sdm-cookbook-fit-server/recipes/
default.rb
================================================================================


ArgumentError
-------------
invalid byte sequence in UTF-8

Cookbook Trace:
---------------
  c:/chef/cache/cookbooks/sdm-cookbook-fit-server/recipes/default.rb:13:in `from
_file'

**Comment by tsmith-sdm** [comment]
It appears that the following PowerShell command does not create a UTF-8 file

openssl rand -base64 512 | tr -d '\r\n' > secret_key

opening the secret_key file and saving as UTF-8 fixes the problem

**Comment by lamont-granquist** [comment]
your windows box is probably not set to UTF-8 which is why your powershell isn't creating UTF-8 files?  and chef-client falls back to guessing that the file is UTF-8 and explodes when its not.  but since the file only contains a random jumble of characters and has no metadata associated with what the encoding is, there's no way chef-client can know the encoding without some kind of guessing.  and this problem infects everything including community cookbooks, where chef HAS to guess UTF-8 as the base encoding.  really we should standardize that cookbooks MUST be UTF-8 encoded and that anything else is invalid, just like strings in JSON.

anyway, i don't see a chef-client bug here and beating on your system settings is likely the right answer.
