### ISSUE TITLE
validation_client_name not escaped properly when using knife bootstrap

### ISSUE THREAD

**Issue by RyanJarv** [chef/chef#5130]
When you have a single quote in the validation_client_name of knife.rb it doesn't get escaped properly when running knife bootstrap.

In my case I had literally set the validation_client_name to "A path that doesn't exist" because of another bug I was running into with some code thinking nil/false was a file, need to dig into that and submit another report for that though.

Chef: 12.11.18

Client: OSx
Server: Ubuntu

```
➜  example mkdir .chef
➜  example git:(master) ✗ cat <<EOH
heredoc> validation_client_name "A path that doesn't exist"
heredoc> EOH
validation_client_name "A path that doesn't exist"
➜  example git:(master) ✗ knife bootstrap ubuntu@1.1.1.1 -z -i ~/.ssh/privatekey.pem    
Doing old-style registration with the validation key at ...
Delete your validation key in order to use your user credentials instead

Connecting to 52.40.10.128
52.40.10.128 bash: -c: line 196: unexpected EOF while looking for matching `"'
52.40.10.128 bash: -c: line 199: syntax error: unexpected end of file
➜  example git:(master) ✗ 
```

**Comment by cramaechi** [comment]
We could just escape the single quote in the logic behind `knife bootstrap`, but I believe `validation_client_name` should be properly escaped when `knife.rb` is loaded in, as indicated by the red arrow in the following screenshot:

`chef/chef-config/lib/chef-config/workstation_config_loader.rb `
<img width="823" alt="screen shot 2018-01-15 at 1 58 36 pm" src="https://user-images.githubusercontent.com/24444174/34959579-bfc26af6-f9fc-11e7-9e3f-54f83151741d.png">

Please share your thoughts.

**Comment by tas50** [comment]
@RyanJarv In Chef Infra Client 15 we entirely rewrote how bootstrap works for Windows. I'm going to close this out at this point. If you're still seeing this sort of behavior in Chef Infra Client 15 please open it back up so we can dig in further.
