### ISSUE TITLE
Tutorial requires a fix: "Manage a basic ubuntu web application"

### ISSUE THREAD

**Issue by dpasqualin** [chef/chef#5134]
## Description

The firewall cookbook in [Manage a basic ubuntu web application / Configure the firewall](https://learn.chef.io/manage-a-web-app/ubuntu/configure-the-firewall/) needs update. 

Step 1 suggests to install version 2.4.0, but this version shows a  `Chef::Exceptions::ImmutableAttributeModification` when running `kitchen converge`. The reason why is described [here](http://stackoverflow.com/questions/18471361/using-modified-opsworks-deploy-cookbook-immutable-object-error), and the solution is to suggest a newer version, 2.5.2 for instance.

## Chef Version

12.12.15

## Platform Version

Ubuntu 14.04.4 LTS (on vagrant).

## Replication Case

To replicate just follow the tutorial.

## Stacktrace

`
================================================================================
       Error executing action 'restart' on resource 'firewall[default]'
       ================================================================================
       
       Chef::Exceptions::ImmutableAttributeModification
       ------------------------------------------------
       Node attributes are read-only when you do not specify which precedence level to set. To set an attribute use code like `node.default["key"] = "value"'
`

**Comment by coderanger** [comment]
Hi there. Thanks for the report, but this is the issue tracker for Chef itself. I don't think we have a public issue tracker for Learn Chef, but I'll make sure this gets passed along. Thanks again!

**Comment by tpetchel** [comment]
@dpasqualin  - just wanted to acknowledge the report. I'll take a look as soon as I can! Thanks for letting us know.

**Comment by dpasqualin** [comment]
@coderanger and @tpetchel, thank you, it's nice to help :)
