### ISSUE TITLE
Remove iconv from the ruby build

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#5140]
It hasn't been needed since 1.8.7, and it needs to die with chef 12.

https://github.com/chef/omnibus-software/blob/92d13d4dc24edf5f28ed872e502fd9e6fb3a9b15/config/software/ruby.rb#L38-L42

**Comment by coderanger** [comment]
The comment mentions nokogiri, is that no longer correct?

**Comment by lamont-granquist** [comment]
that was what came up, but there's no guarantee its the only c ext that accidentally links to libiconv if its there

**Comment by coderanger** [comment]
I mean that we are still planning to distribute nokogiri as part of the Chef installers, so even if Ruby doesn't need it, ...

**Comment by lamont-granquist** [comment]
i don't think its required for nokogiri, i think it just gets promiscuously picked up by libxml2/libxslt if its there...

**Comment by coderanger** [comment]
👍 Just need to check back when we kill it and make sure it's not coming in from the OS.

**Comment by lamont-granquist** [comment]
there's the omnibus health_check alarms that go off if we accidentally link to anything that isn't in the whitelist, which better not let us do that..

**Comment by lamont-granquist** [comment]
#5993
