### ISSUE TITLE
Creating a user with pw beginning with - returns an error

### ISSUE THREAD

**Issue by flybd5** [chef/chef#5142]
## Description

chef-server-ctrl create-user doesn't allow passwords that begin with a dash "-"

## Chef Version

12

## Platform Version

Ubunto 14.04 64 bit

## Replication Case

Try to create a new user with a password that begins with a dash. Placing a backslash before the slash works.

## Client Output

Error: invalid option: -rest-of-password
USAGE: knife opc user create USERNAME FIRST_NAME [MIDDLE_NAME] LAST_NAME EMAIL 
...etc...

**Comment by thommay** [comment]
This is the issue tracker for the chef client, not the chef server. 

Please can you file this issue at https://github.com/chef/chef-server/issues/new .
