### ISSUE TITLE
Error while bootstrapping windows node

### ISSUE THREAD

**Issue by samsonkolge** [chef/chef#5149]
## Description

Error while bootstrapping windows node via winrm method

## Chef Version

$ chef -v
Chef Development Kit Version: 0.14.25
chef-client version: 12.10.24
berks version: 4.3.3
kitchen version: 1.8.0

## Platform Version
Windows 8.1

## Replication Case

$ chef gem list | grep windows
knife-windows (1.4.1)
windows-api (0.4.4)
windows-pr (1.2.4)

Please fire the below command to replicate the issue:

chef exec knife bootstrap windows winrm -N 192.168.33.93 -r 'role[production]' -x Administrator -P 'XXXXXXXX' -p 5985 -VV

## Client Output

INFO: Using configuration from C:/Users/kolge/learn-chef/chef-repo/.chef/knife.rb
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key ca_trust_file and found value
DEBUG: Looking for key winrm_user and found value Administrator
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_transport and found value plaintext
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_password and found value XXXXXXX
DEBUG: Looking for key winrm_port and found value 5985
DEBUG: Looking for key session_timeout and found value 30
DEBUG: Looking for key session_timeout and found value 30
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_transport and found value plaintext
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_transport and found value plaintext
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key ca_trust_file and found value
DEBUG: Looking for key ssl_peer_fingerprint and found value
DEBUG: Looking for key ca_trust_file and found value
C:/Users/kolge/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-windows-1.4.1/lib/chef/knife/winrm_knife_base.rb:69:in `resolve_target_nodes': undefined method `split' for nil:NilClass (NoMethodError)
        from C:/Users/kolge/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-windows-1.4.1/lib/chef/knife/winrm_knife_base.rb:62:in `configure_session'
        from C:/Users/kolge/AppData/Local/chefdk/gem/ruby/2.1.0/gems/knife-windows-1.4.1/lib/chef/knife/bootstrap_windows_winrm.rb:51:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24-universal-mingw32/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24-universal-mingw32/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24-universal-mingw32/lib/chef/knife.rb:219:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24-universal-mingw32/lib/chef/application/knife.rb:148:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24-universal-mingw32/bin/knife:25:in `<top (required)>'
        from C:/opscode/chefdk/bin/knife:61:in `load'
        from C:/opscode/chefdk/bin/knife:61:in `<main>'

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

## Stacktrace

NA

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by brownc** [comment]
Just walked into the same problem, so any clues and hints would be gratefully received.  Only difference in my case is trying to bootstrap Windows 10, and WinRM is enabled/validated by 'knife wsman test'

**Comment by lamont-granquist** [comment]
you need to pass the address as the argument:

you have:

```
chef exec knife bootstrap windows winrm -N 192.168.33.93 -r 'role[production]' -x Administrator -P 'XXXXXXXX' -p 5985 -VV
```

you need:

```
chef exec knife bootstrap windows winrm 192.168.33.93 -N 192.168.33.93 -r 'role[production]' -x Administrator -P 'XXXXXXXX' -p 5985 -VV
```

although you're probably mixed up the node name argument and the server to login to -- you probably want to give it a more useful node name than its IP address...

**Comment by lamont-granquist** [comment]
knife-windows could have a more useful error message here when the host argument is missing, but this is the wrong repo to file that ticket...

http://github.com/chef/knife-windows/issues/new
