### ISSUE TITLE
User can bypass ACL on knife bootstrap

### ISSUE THREAD

**Issue by NerdsvilleCEO** [chef/chef#5153]
Hello,
  It appears that if I attempt to grant a role which has been disallowed to be added by a specific group at time of bootstrap, I can. Is there any way that we can validate whether they have permissions to grant a role to a node at this time? It seems that there are validation rules which prevent adding a role to a node which has already been provisioned. 

This would be really useful for the security of using roles with ACL's and vault

Please advise

**Comment by coderanger** [comment]
ACLs do not control run lists in that way. More to the point, nothing in a run list can be used for security-sensitive purposes as nodes retain write access to their own run list for now.

**Comment by coderanger** [comment]
(and yes, that means Chef-Vault's search query mode is insecure and should not be used in most cases)
