### ISSUE TITLE
SSH Authentication Bug of Command `Knife`

### ISSUE THREAD

**Issue by croath** [chef/chef#5156]
## Description

Command `knife` responses authentication failure while following the tutorial at https://learn.chef.io/manage-a-node/ubuntu/bootstrap-your-node/

While using the command in the tutorial:

```
knife bootstrap ADDRESS --ssh-user USER --ssh-password 'PASSWORD' --sudo --use-sudo-password --node-name node1 --run-list 'recipe[learn_chef_apache2]'
```

It always failed when my password is a simple blank space ` `. (I'm sure there's no typo or misspelling because I've tried many and many times. And at the same time SSH just worked fine.) Everything worked fine after I changed my password to another one.
## Chef Version

Chef: 12.12.15
## Platform Version

The target node is a Ubuntu 15.10 Desktop 4.2.0-16-generic running in a virtual box locally.
I ran the `knife` command on an OS X El Capitan 10.11.6 (15G31)
## Replication Case

Just change your ubuntu login password to a single space ` `, and run the command on a Macbook:

```
knife bootstrap YOUR_IP --ssh-user YOUR_USERNAME --ssh-password ' ' --sudo --use-sudo-password --node-name node1 --run-list 'recipe[learn_chef_apache2]'
```
## Client Output

```
Creating new client for node1
Creating new node for node1
Connecting to 172.16.3.150
croath@172.16.3.150's password:
croath@172.16.3.150's password:
ERROR: Net::SSH::AuthenticationFailed: Authentication failed for user croath@172.16.3.150@172.16.3.150
```
## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.
### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.
- [Server issues](https://github.com/chef/chef-server/issues/new)
- [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
- Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by liuxiaopiao** [comment]
Met the same problem

**Comment by haninabubaker** [comment]
Same problem here!

**Comment by agill17** [comment]
Ran into the same type of error when running chef-client on aws ec2 instances from Workstation -- knife ssh "name:node_name" "sudo chef-client" -i ~/.ssh/key.pem --ssh-user ubuntu

**Comment by JLATORRE89** [comment]
Same issue using -P instead of -i on a fresh install. The bootstrap command worked one time and failed each additional time on a Windows Workstation.

Command output:
from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:182:in `new_session'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:488:in `next_session'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:138:in `session'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session_actions.rb:36:in `block (2 levels) in sessions'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-
2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
ERROR: Net::SSH::AuthenticationFailed: Authentication failed for user u1@xx.xxx.xxx.xxx@xxx.xxx.xxx.xxx

**Comment by PranjalGohain** [comment]
Is there any fix on this yet ?

**Comment by croath** [comment]
@PranjalGohain After 2 years, no.
