### ISSUE TITLE
Fips check fails on Mac and throws an error

### ISSUE THREAD

**Issue by jkugler** [chef/chef#5161]
## Description

When running rspec tests on OS X, I am running in to this error on Chef 12.12.15

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /proc/sys/crypto/fips_enabled

I've traced the issue to this code: https://github.com/chef/chef/blame/master/chef-config/lib/chef-config/fips.rb#L48 which was introduced in v12.10.33

The code is this:

      fips_path = "/proc/sys/crypto/fips_enabled"
      File.exist?(fips_path) && File.read(fips_path).chomp != "0"

On a Mac system, that path does not exist, so File.exist? should fail, but somehow it's returning true, which then means File.read is invoked and it fails, returning the ENOENT error. 

## Chef Version

12.12.15

## Platform Version

OS X 10.10.5

## Replication Case

I have not yet been able to replicate this on the command line.  I will work on that.

## Client Output

     Errno::ENOENT:
       No such file or directory @ rb_sysopen - /proc/sys/crypto/fips_enabled

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chef-config-12.12.15/lib/chef-config/fips.rb:48:in `read'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chef-config-12.12.15/lib/chef-config/fips.rb:48:in `fips?'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chef-config-12.12.15/lib/chef-config/config.rb:530:in `block in <class:Config>'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/mixlib-config-2.2.1/lib/mixlib/config/configurable.rb:48:in `call'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/mixlib-config-2.2.1/lib/mixlib/config/configurable.rb:48:in `get'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/mixlib-config-2.2.1/lib/mixlib/config.rb:423:in `internal_get'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/mixlib-config-2.2.1/lib/mixlib/config.rb:444:in `internal_get_or_set'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/mixlib-config-2.2.1/lib/mixlib/config.rb:456:in `block in define_attr_accessor_methods'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chef-config-12.12.15/lib/chef-config/config.rb:545:in `block in <class:Config>'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/mixlib-config-2.2.1/lib/mixlib/config/configurable.rb:48:in `call'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/mixlib-config-2.2.1/lib/mixlib/config/configurable.rb:48:in `get'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/mixlib-config-2.2.1/lib/mixlib/config.rb:423:in `internal_get'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/mixlib-config-2.2.1/lib/mixlib/config.rb:69:in `[]'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chef-12.12.15/lib/chef/http/auth_credentials.rb:47:in `signature_headers'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chef-12.12.15/lib/chef/http/authenticator.rb:102:in `authentication_headers'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chef-12.12.15/lib/chef/http/authenticator.rb:51:in `handle_request'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chef-12.12.15/lib/chef/http.rb:265:in `block in apply_request_middleware'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chef-12.12.15/lib/chef/http.rb:263:in `each'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chef-12.12.15/lib/chef/http.rb:263:in `inject'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chef-12.12.15/lib/chef/http.rb:263:in `apply_request_middleware'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chef-12.12.15/lib/chef/http.rb:142:in `request'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chef-12.12.15/lib/chef/http.rb:111:in `get'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chef-12.12.15/lib/chef/node.rb:585:in `load'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chef-12.12.15/lib/chef/node.rb:569:in `find_or_create'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chef-12.12.15/lib/chef/policy_builder/dynamic.rb:72:in `load_node'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chef-12.12.15/lib/chef/client.rb:467:in `load_node'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chefspec-4.7.0/lib/chefspec/solo_runner.rb:375:in `client'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chefspec-4.7.0/lib/chefspec/solo_runner.rb:142:in `node'
     # /Users/502552966/.rvm/gems/ruby-2.2.1/gems/chefspec-4.7.0/lib/chefspec/server_runner.rb:41:in `initialize'
     # ./spec/unit/recipes/master_spec.rb:5:in `new'
     # ./spec/unit/recipes/master_spec.rb:5:in `block (2 levels) in <top (required)>'
     # ./spec/unit/recipes/master_spec.rb:11:in `block (2 levels) in <top (required)>'
     # ./spec/unit/recipes/master_spec.rb:140:in `block (3 levels) in <top (required)>'

**Comment by thommay** [comment]
I think what you're seeing is that `File.exist?` has been mocked in a test. Pretty sure this isn't a bug in chef.

**Comment by jkugler** [comment]
ARRGH! You're right. Didn't know how it could be.  What I was working on isn't 100% my code, so I missed the mock. Thank you.
