### ISSUE TITLE
yum_package ignores the  .arch on package names

### ISSUE THREAD

**Issue by joaompinto** [chef/chef#5163]
## Description

The yum_package resource does not check for the package architecture (.arch) when validating if a given package is installed.
## Chef Version

chef-12.12.15
## Platform Version

RHEL7
## Replication Case

The following recipe, should install the .i686 packages:

yum_package ['ntp', 'libstdc++.i686', 'libstdc++-devel.i686', 'compat-libstdc++-33.i686', 'ksh'] do
  action    :install
end
## Client Output

...
[2016-08-03T12:21:03+01:00] INFO: Storing updated cookbooks/sysconfig/recipes/base_packages.rb in the cache.
[2016-08-03T12:21:03+01:00] INFO: Processing yum_package[ntp, libstdc++.i686, libstdc++-devel.i686, compat-libstdc++-33.i686, ksh] action install (sysconfig::base_packages line 1)
[2016-08-03T12:21:05+01:00] INFO: yum_package[ntp, libstdc++.i686, libstdc++-devel.i686, compat-libstdc++-33.i686, ksh] installing libstdc++-4.8.5-4.el7 from uln_latest repository libstdc++-devel-4.8.5-4.el7 from uln_latest repository compat-libstdc++-33-3.2.3-72.el7 from uln_latest repository
[2016-08-03T12:21:05+01:00] INFO: yum_package[ntp, libstdc++.i686, libstdc++-devel.i686, compat-libstdc++-33.i686, ksh] installed ["libstdc++", "libstdc++-devel", "compat-libstdc++-33"] at ["4.8.5-4.el7", "4.8.5-4.el7", "3.2.3-72.el7"]
...

[root@build ~]# rpm -qi  libstdc++.i686
package libstdc++.i686 is not installed
[root@build ~]# yum list libstdc++
Loaded plugins: langpacks, ulninfo
Installed Packages
libstdc++.x86_64                                                           4.8.5-4.el7                                                           @anaconda/7.2
Available Packages
libstdc++.i686                                                             4.8.5-4.el7                                                           uln_latest   
## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.
### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.
- [Server issues](https://github.com/chef/chef-server/issues/new)
- [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
- Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by thommay** [comment]
probably the same as #5112 in the end.

**Comment by tmoy61** [comment]
I ran into a similar (related?) issue today.  We have the same package installed for different architectures on the same system.  We're trying to remove one of them with...

yum_package 'foo.i386' do
  action :remove
end

This fails, but reports success.

Rerunning with debug logging shows what's happening:

[2016-08-25T11:56:48-04:00] DEBUG: Parsed out arch i386, new package name is foo
[2016-08-25T11:56:48-04:00] DEBUG: yum_package[foo.i386] checking yum info for foo.i386
[2016-08-25T11:56:48-04:00] DEBUG: yum_package[foo.i386] installed version: ["0.5.8.1-38.el5"] candidate version: (none)
[2016-08-25T11:56:48-04:00] DEBUG: yum_package[foo.i386]: yum command: "yum -d0 -e0 -y remove foo.i386.i386"
No Match for argument: foo.i386.i386
[2016-08-25T11:56:49-04:00] INFO: yum_package[foo.i386] removed

    - remove package foo.i386

So it looks to me like it pulls the architecture off then adds it back twice.  A bug, correct?

**Comment by thommay** [comment]
@tmoy61 yep, but a different one. can you open a new issue?

**Comment by tmoy61** [comment]
I moved my issue to ...
https://github.com/chef/chef/issues/5254

**Comment by dschlenk** [comment]
Can confirm this affects rhel/centos 6.x as well

**Comment by jsmartt** [comment]
@thommay , @lamont-granquist, are ther any updates on this or related issues (#3476, #4266, #5112, #5254)? Basically, it doesn't look possible to update a packages with multiple architectures at once, which is a pretty big problem, for instance if you have both the 32-bit and 64-bit openssl packages and need those updated...

[Here's a gist](https://gist.github.com/jsmartt/010c73edac388560e82ad14d7dc78f8c) that explains the issues in more detail and shows some bugs with the package resource. At this point, I don't see a valid workaround using this resource.

**Comment by lamont-granquist** [comment]
i fixed it all in the dnf_provider, my long term plan is to declare bankruptcy on the yum_package code and specs and rewrite it, but i need the dnf provider to become more battle tested.  so no, there's no updates on this.  i'd consider patches to the current code, but i'm unlikely to do any work on it myself.

**Comment by jsmartt** [comment]
I keep hearing mention of this dnf provider, but the only place I can find it is in the code (eg, [here](https://github.com/chef/chef/blob/v12.18.31/lib/chef/provider/package/dnf.rb)). I can't find it in the docs, and every way I've tried to use it results in an `Errno::EPIPE Broken pipe` error. I've tried each of the following resource definitions, but each result in that same error:

```ruby
dnf_package 'libstdc++'

dnf_package 'libstdc++' do
  version '4.8.5-11.el7'
end

dnf_package ['libstdc++.x86_64', 'libstdc++.i686'] do
  version '4.8.5-11.el7'
end

dnf_package 'libstdc++' do
  arch ['x86_64', 'i686']
  version '4.8.5-11.el7'
end

dnf_package ['libstdc++', 'libstdc++'] do
  arch ['x86_64', 'i686']
  version '4.8.5-11.el7'
end
```

What gives? And if that's Chef's provided workaround or recommended replacement, there really needs to be some docs saying how to use it.

**Comment by lamont-granquist** [comment]
do you have dnf installed on your system?

and docs haven't caught up, and i don't recommend it as a workaround/replacement, and its experimental at this point.  the fact that you're getting an EPIPE is a pretty good indication that replacing the yum_package code with similar code to dnf_package would be disruptive.

there's currently a parallel effort to look at fixing the yum_package provider in the existing codebase since the dnf_package code is likely 3-6 months away from being ported to the yum_package provider.

**Comment by jsmartt** [comment]
I do have dnf installed. And OK, thanks; a fix for yum_package would be much appreciated.

**Comment by lamont-granquist** [comment]
is it dnf 0.6 on centos/rhel7 from epel?  or is it dnf 2.0?

**Comment by lamont-granquist** [comment]
right now it only works on dnf 1.1.x on fedora 24, and is known to fail with dnf 0.6.x and 2.0 -- i'm working on 2.0 fixes right now while 0.6 i'm probably going to hard code it not to work with that

**Comment by jsmartt** [comment]
Ah. Yeah, it was dnf 0.6 from CentOS EPEL

**Comment by lamont-granquist** [comment]
yeah i tried and gave up on that one.  i have a task i need to do to make dnf_package fail better in that situation.

there's dnf 2.x for rhel-7 that phil mentions here:

https://github.com/chef/chef/pull/4894#issuecomment-277054648

i'm working on that today.
