### ISSUE TITLE
The 'user' resource needs support for password maxage, minage and account expiration.

### ISSUE THREAD

**Issue by joaompinto** [chef/chef#5164]
## Description

On Linux systems the minage, maxage and account expiration are standard user attributes.
## Chef Version

Chef 12.12.15
## Platform Version

RHEL7
## Replication Case

Feature request
## Client Output

Feature request
## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

**Comment by webchi** [comment]
Yes, we need it =)

**Comment by dantidote** [comment]
We need this too.
