### ISSUE TITLE
package resource execution fails - update wasn't executed

### ISSUE THREAD

**Issue by lioramilbaum** [chef/chef#5167]
## Description

When executing the first package resource execution, an update should be executed. For instance:
apt-get update
apt-get install <some package>

package resouce should take care of the update step

## Chef Version

12.12.5

Tell us which version of chef-client you are using (see below for Server+ChefDK bugs).

Chef Development Kit Version: 0.16.28
chef-client version: 12.12.15
delivery version: master (921828facad8a8bbbd767368bfc72f19bd30e7bd)
berks version: 4.3.5
kitchen version: 1.10.2

Tell us which Operating System distribution and version chef-client is running on.

Ubuntu 12.04

## Replication Case

A recipe which includes only one resource on a fresh instance

package "<package name>"

## Client Output

Fails cause 'apt-get update' was not executed

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by coderanger** [comment]
Unfortunately this isn't really doable, `apt-get update` is a relatively heavy-weight operation so this would be too slow. Check out the new `apt_update` resource for this task.
