### ISSUE TITLE
Windows arch detection during bootstrap is incorrect for 32-bit

### ISSUE THREAD

**Issue by glasschef** [chef/chef#5178]
## Description

Windows arch detection during bootstrap checks for `X86` when it's actually `x86` (in 32-bit Windows 7, at least) so it falls back to 64-bit install, which can't install:

https://github.com/chef/knife-windows/blob/710bceb8c7c17cdde8f6f59591add920ce1d9d33/lib/chef/knife/bootstrap_windows_base.rb#L438

## Chef Version

12.12.15 

## Platform Version

Windows 7 32-bit

## Replication Case

Attempt a vanilla bootstrap of 32bit Windows with chef-client 12.12.15

## Client Output

```
DEBUG: 10.211.192.138[552B1929-8A47-4272-A6D8-A933EA4BC9EF] => :run_command[echo %PROCESSOR_ARCHITECTURE%]
10.211.192.138 x86

...

10.211.192.138 powershell.exe -ExecutionPolicy Unrestricted -NoProfile -NonInteractive -File  C:\chef\wget.ps1 "https://www.chef.io/chef/download?p=windows&pv=2008r2&m=x86_64&DownloadContext=PowerShell&v=12" "C:\Users\clhadmin\AppData\Local\Temp\chef-client-latest.msi"

```
## Stacktrace

```
10.211.192.155 C:\Users\clhadmin>msiexec /qn /log "C:\Users\clhadmin\AppData\Local\Temp\chef-client-msi5504.log" /i "C:\Users\clhadmin\AppData\Local\Temp\chef-client-latest.msi"
10.211.192.155 T h i s   i n s t a l l a t i o n   p a c k a g e   i s   n o t   s u p p o r t e d   b y   t h i s   p r o c e s s o r   t y p e .   C o n t a c t   y o u r   p r o d u c t   v e n d o r .
10.211.192.155
```

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by lamont-granquist** [comment]
shouldn't this issue get cut against knife-windows?

**Comment by glasschef** [comment]
@lamont-granquist Whoops, wrong repo!  Closing this after filing one here: https://github.com/chef/knife-windows/issues/382
