### ISSUE TITLE
Chef 12.13.30 - "log writing failed. closed stream" when running chef-client with -L flag

### ISSUE THREAD

**Issue by petecheslock** [chef/chef#5195]
## Description

In our bootstrap process - we run a command like the following
```
chef-client  -j /etc/chef/first_run.json -L /var/log/chef-client/first-boot.log
```

When nodes start for the first time they will run that command and you can inspect the output of the bootstrap run by reviewing that log.  When upgrading from Chef 12.10 to 12.13 we've started to get the following reported to STDOUT.
```
log writing failed. closed stream
log writing failed. closed stream
log writing failed. closed stream
log writing failed. closed stream
```

The log file in /var/log/chef-client/first-boot.log DOES get created with the following, but nothing is written to it

```
# Logfile created on 2016-08-12 14:44:44 +0000 by logger.rb/53938
```

## Chef Version

chef-client 12.13.30

## Platform Version

Ubuntu 14.04

## Replication Case

Install chef-client 12.13.30 - run the following (with or w/o passing a json of node attrs
```
chef-client -L <path to log file>
```

## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

## Stacktrace
```
chef-client -j /etc/chef/first_run.json -L /var/log/chef-client/first-boot-test.log
log writing failed. closed stream
log writing failed. closed stream
log writing failed. closed stream
log writing failed. closed stream
```

I know i could solve this with: 
```
chef-client  -j /etc/chef/first_run.json > /var/log/chef-client/first-boot.log 2>&1
```
But it seems like some sort of change/regression made its way in so just letting y'all know.  This might be an issue for people use use in the `-L` flag in their service init scripts.

**Comment by thommay** [comment]
tracking this at https://github.com/chef/mixlib-log/issues/17 ; thanks Pete.

**Comment by thommay** [comment]
A fixed ohai has been released, and we'll be releasing a new omnibus package tomorrow.
