### ISSUE TITLE
Upstart service provider considers actual state instead of goal state

### ISSUE THREAD

**Issue by evan2645** [chef/chef#5204]
## Description

The upstart status command returns two pieces of state information: the goal state and the current state. The upstart service provider, when checking the status of a service, uses the current state. This poses a problem as upstart can (and often does) act as a supervision daemon.

Under various configuration, upstart can make many attempts to flexibly boot a service when its goal state is `start`. During this time, the current state might be something other than `running`. In this condition, Chef will recognize the service as _not_ running, and attempt to issue a start command. This command, of course, fails as upstart has already 'started' the job.

Recommended solution: use the goal state as the current state in the upstart provider in order to avoid fighting with process supervision. I am happy to push a fix for this, but want to know that it is an acceptable direction before working on it.
## Chef Version

`12.5.1`, but behavior is present in master
## Platform Version

Ubuntu 14.04
## Replication Case
1. Drop upstart job config with respawn unlimited, post-stop sleep configured, exec /bin/false
2. Configure chef service for the job
3. Start the service immediately
4. Notify delayed restart of the service
## Client Output

```
ec2-54-149-139-182.us-west-2.compute.amazonaws.com ================================================================================[0m
ec2-54-149-139-182.us-west-2.compute.amazonaws.com [31mError executing action `restart` on resource 'service[topology-manager]'[0m
ec2-54-149-139-182.us-west-2.compute.amazonaws.com ================================================================================[0m
ec2-54-149-139-182.us-west-2.compute.amazonaws.com 
ec2-54-149-139-182.us-west-2.compute.amazonaws.com [0mMixlib::ShellOut::ShellCommandFailed[0m
ec2-54-149-139-182.us-west-2.compute.amazonaws.com ------------------------------------[0m
ec2-54-149-139-182.us-west-2.compute.amazonaws.com Expected process to exit with [0], but received '1'
ec2-54-149-139-182.us-west-2.compute.amazonaws.com [0m---- Begin output of /sbin/start topology-manager ----
ec2-54-149-139-182.us-west-2.compute.amazonaws.com [0mSTDOUT: 
ec2-54-149-139-182.us-west-2.compute.amazonaws.com [0mSTDERR: start: Job is already running: topology-manager
ec2-54-149-139-182.us-west-2.compute.amazonaws.com [0m---- End output of /sbin/start topology-manager ----
ec2-54-149-139-182.us-west-2.compute.amazonaws.com [0mRan /sbin/start topology-manager returned 1[0m
```

**Comment by evan2645** [comment]
Regarding the existing behavior: anyone using upstart service provider with a configuration which provides supervision will be exposed to chef run failure. The current workaround is to provide a custom `status_command`, which is ultimately platform-specific and painful.

Changing the default behavior to use the goal state instead of the current state will mean that those hacks can be removed. The only case I can think of in which this change will impact existing deployments is if a user's upstart supervisory configuration was inadequate, and he/she is instead relying on chef-client's service start command on every run to keep the service alive.

**Comment by thommay** [comment]
This seems like a reasonable change for most users, and we'd happily take a PR for it.

**Comment by evan2645** [comment]
@thommay pushed #5249 for this

**Comment by tas50** [comment]
Closing this out based on the merged PR
