### ISSUE TITLE
WmiLite::WmiException during the chef-client run

### ISSUE THREAD

**Issue by AmbareeshV** [chef/chef#5221]
## Description

I was trying to start the tectiassh service using service resource in windows and getting the below error

FATAL: WmiLite::WmiException: An error occurred connecting to the WMI service for namespace 'root/cimv2'. The namespace may not be valid, access may not be allowed to the WMI service, or the WMI service may not be available.
(in OLE method `ConnectServer': )
    OLE error code:8007045B in SWbemLocator
      A system shutdown is in progress. 
    HRESULT error code:0x80020009
      Exception occurred.

## Chef Version

 11.18.12

## Platform Version

Windows server 2012 R2

## Client Output

FATAL: WmiLite::WmiException: An error occurred connecting to the WMI service for namespace 'root/cimv2'. The namespace may not be valid, access may not be allowed to the WMI service, or the WMI service may not be available.
(in OLE method `ConnectServer': )
    OLE error code:8007045B in SWbemLocator
      A system shutdown is in progress. 
    HRESULT error code:0x80020009
      Exception occurred.

**Comment by thommay** [comment]
We strongly recommend for Windows support that you use Chef 12. We're very unlikely to do any further releases of Chef 11 besides for major security problems, and Chef 12 has received a huge quantity of work to improve it on Windows. IF this problem still occurs with the latest release of Chef 12, please feel free to reopen the ticket.
