### ISSUE TITLE
Installing yum packages from 3rd party repo disables ability to install deps

### ISSUE THREAD

**Issue by tas50** [chef/chef#5228]
## Description

When installing yum packages from 3rd party repo chef disables additional repos which kills the ability to install any deps that come from the core OS repos.
## Chef Version

12.13
## Platform Version

CentOS 7.2
## Replication Case

Add nginx.org repo
Make sure you don't have the openssl package already (docker image doesn't)
Install nginx
## Client Output

```
 * yum_package[nginx] action install

    ================================================================================
    Error executing action `install` on resource 'yum_package[nginx]'
    ================================================================================

    Chef::Exceptions::Exec
    ----------------------
    yum -d0 -e0 -y --disablerepo=* --enablerepo=nginx install nginx-1.10.1-1.el7.ngx returned 1:
    STDOUT:  You could try using --skip-broken to work around the problem
     You could try running: rpm -Va --nofiles --nodigest

    STDERR: Error: Package: 1:nginx-1.10.1-1.el7.ngx.x86_64 (nginx)
               Requires: openssl >= 1.0.1

    Cookbook Trace:
    ---------------
    /opt/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'

    Resource Declaration:
    ---------------------
    # In /opt/kitchen/cache/cookbooks/chef_nginx/recipes/package.rb

     41: package node['nginx']['package_name'] do
     42:   options package_install_opts
     43:   notifies :reload, 'ohai[reload_nginx]', :immediately
     44:   not_if 'which nginx'
     45: end
     46: 

    Compiled Resource:
    ------------------
    # Declared in /opt/kitchen/cache/cookbooks/chef_nginx/recipes/package.rb:41:in `from_file'

    yum_package("nginx") do
      package_name "nginx"
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "chef_nginx"
      recipe_name "package"
      options "--disablerepo=* --enablerepo=nginx"
      flush_cache {:before=>false, :after=>false}
      not_if "which nginx"
    end

    Platform:
    ---------
    x86_64-linux

Running handlers:
[2016-08-18T18:52:56+00:00] ERROR: Running exception handlers
Running handlers complete
[2016-08-18T18:52:56+00:00] ERROR: Exception handlers complete
Chef Client failed. 10 resources updated in 07 seconds
[2016-08-18T18:52:56+00:00] FATAL: Stacktrace dumped to /opt/kitchen/cache/chef-stacktrace.out
[2016-08-18T18:52:56+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-08-18T18:52:56+00:00] ERROR: yum_package[nginx] (chef_nginx::package line 41) had an error: Chef::Exceptions::Exec: yum -d0 -e0 -y --disablerepo=* --enablerepo=nginx install nginx-1.10.1-1.el7.ngx returned 1:
STDOUT:  You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
STDERR: Error: Package: 1:nginx-1.10.1-1.el7.ngx.x86_64 (nginx)
           Requires: openssl >= 1.0.1
```

**Comment by lamont-granquist** [comment]
pretty sure this is a dup

**Comment by lamont-granquist** [comment]
#2728 dup or related?

**Comment by irinatag** [comment]
chef: 12.4.1
OS: rhel 7.1

Same error when using a cookbook to install Docker 1.11 on rhel 7.1 machine in Openstack (works fine in test-kitchen with Vagrant):

 `* docker_installation_package[default] action create
           * yum_package[docker-engine] action install

             ================================================================================
             Error executing action `install` on resource 'yum_package[docker-engine]'
             ================================================================================

             Chef::Exceptions::Exec
             ----------------------
             yum -d0 -e0 -y install docker-engine-1.11.1-1.el7.centos returned 1:
             STDOUT:  You could try using --skip-broken to work around the problem
       You could try running: rpm -Va --nofiles --nodigest

             STDERR: Error: Package: docker-engine-1.11.1-1.el7.centos.x86_64 (docker)
                 Requires: libsystemd.so.0(LIBSYSTEMD_209)(64bit)
             Error: Package: docker-engine-1.11.1-1.el7.centos.x86_64 (docker)
                 Requires: libdevmapper.so.1.02(DM_1_02_97)(64bit)
             Error: Package: docker-engine-1.11.1-1.el7.centos.x86_64 (docker)
                 Requires: libltdl.so.7()(64bit)
             Error: Package: docker-engine-1.11.1-1.el7.centos.x86_64 (docker)
                 Requires: libsystemd.so.0()(64bit)

             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/provider.rb:133:in `compile_and_converge_action'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
             /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/docker/libraries/docker_installation_package.rb

       17:       package package_name do
       18:         version package_version
       19:         options package_options
       20:         action :install
       21:       end
       22:     end

             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/docker/libraries/docker_installation_package.rb:17:in `block in <class:DockerInstallationPackage>'

             yum_package("docker-engine") do
        action [:install]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        package_name "docker-engine"
        version "1.11.1-1.el7.centos"
        flush_cache {:before=>false, :after=>false}
        declared_type :package
        cookbook_name "gapDocker"
             end


           ================================================================================
           Error executing action `create` on resource 'docker_installation_package[default]'
           ================================================================================

           Chef::Exceptions::Exec
           ----------------------
           yum_package[docker-engine] (/tmp/kitchen/cache/cookbooks/docker/libraries/docker_installation_package.rb line 17) had an error: Chef::Exceptions::Exec: yum -d0 -e0 -y install docker-engine-1.11.1-1.el7.centos returned 1:
           STDOUT:  You could try using --skip-broken to work around the problem
            You could try running: rpm -Va --nofiles --nodigest

           STDERR: Error: Package: docker-engine-1.11.1-1.el7.centos.x86_64 (docker)
               Requires: libsystemd.so.0(LIBSYSTEMD_209)(64bit)
           Error: Package: docker-engine-1.11.1-1.el7.centos.x86_64 (docker)
               Requires: libdevmapper.so.1.02(DM_1_02_97)(64bit)
           Error: Package: docker-engine-1.11.1-1.el7.centos.x86_64 (docker)
               Requires: libltdl.so.7()(64bit)
           Error: Package: docker-engine-1.11.1-1.el7.centos.x86_64 (docker)
               Requires: libsystemd.so.0()(64bit)
`

**Comment by lamont-granquist** [comment]
@tas50 this was a cookbook bug of some sort -- your resource explicitly was doing a disable all:  `options "--disablerepo=* --enablerepo=nginx"`
