### ISSUE TITLE
Chocolatey - checksum requirement

### ISSUE THREAD

**Issue by ferventcoder** [chef/chef#5246]
Just a heads up, 0.10.0 was recently released and requires checksums for HTTP packages, of which some packages on the community repository to fail currently.

Just something to be aware of as you may receive some reports on this - https://github.com/chocolatey/choco/issues/910

cc @lamont-granquist @mwrock @smurawski

**Comment by ferventcoder** [comment]
I added all of the different options you have when you run into this issue here: https://github.com/chocolatey/choco/issues/112#issue-58511395

The first option is consumer-based. Did you know you could pass the checksums yourself?

**Comment by mwrock** [comment]
Thanks @ferventcoder! I'm closing this since I don't think there is any action we need to take on this now and acknowledging we are aware of the situation.
