### ISSUE TITLE
chef-client should use system CA store

### ISSUE THREAD

**Issue by zdzichu** [chef/chef#5251]
## Description

Currently chef-client ignores system-wide CA store. For example, when adding company CA certificate as trusted, one has to add it twice:
- first into system store (dropping into `/etc/pki/ca-trust/source/anchors/` and then invoking `/usr/bin/update-ca-trust`; on some distributions it's `/usr/local/share/ca-certificates/` and `update-ca-certificates` or `trust anchor CA.crt`); this makes the CA trusted by most frameworks, including Java
- second into `node['chef_client']['conf_dir'] / 'trusted_certs'` directory; this works only for chef-client

Using multiple location for the same data is cumbersome and error prone, system administrator can easily forget about private directories for each application. That's why system CA database is consolidated on Linux.
Windows platform also have system CA store, which should be used by chef-client, too.

More informations:
https://fedoraproject.org/wiki/Features/SharedSystemCertificates
https://p11-glue.freedesktop.org/sharing-trust-policy.html

## Chef Version

12.4.3

## Platform Version

RHEL 7.

## Replication Case

1. Use remote_file resource pointing to HTTPS server with certificate signed by private CA
2. Make CA.crt trusted systemd-wide (see Description)
3. Run chef-client and observe OpenSSL error about untrusted certificate.

Workaround
1. Put CA.crt in /etc/chef/trusted_certs/

**Comment by lamont-granquist** [comment]
Then we're exposed to bugs caused by ancient system CA stores on old distros that we support like RHEL5.

We made a decision a long time ago to ship our own.

**Comment by zdzichu** [comment]
Seriously?
If there's a bug in RHEL5, it need to be reported and fixed anyway.

**Comment by coderanger** [comment]
If you want to read the long explanation of why this isn't possible, check out https://github.com/kennethreitz/requests/issues/2966 (yes I know that's for a different project, most of the same issues apply).

**Comment by svucich** [comment]
Having to configure SSL for multiple services working around chef is extremely cumbersome - And to not use the System stores in windows also drives me mental... Especially as the documentation literally only works for the chef-client.
I have to say, there has been discussions internally at my work about how poor the documentation and also implementation of this. Regardless of how many bugs there are with the windows system ca store, getting all of the services working with SSL is also a tire fire that is putting of many of our devs... SSL implementation should not be as disjointed as it is in chef...
