### ISSUE TITLE
windows_package does not perform remote windows install on Windows 2008 R2 Server

### ISSUE THREAD

**Issue by samsonkolge** [chef/chef#5252]
## Description

When I try to install Powershell using windows_package referring to a local file, it does not work and gives the below error:

           ================================================================================
           Error executing action `install` on resource 'windows_package[.NET 4.5]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '-2146762749'
           ---- Begin output of start "" /wait "c:\users\vagrant\dotnet45.exe"   /Passive /NoRestart & exit %%%%ERRORLEVEL%%%% ----
           STDOUT:
           STDERR:
           ---- End output of start "" /wait "c:\users\vagrant\dotnet45.exe"   /Passive /NoRestart & exit %%%%ERRORLEVEL%%%% ----
           Ran start "" /wait "c:\users\vagrant\dotnet45.exe"   /Passive /NoRestart & exit %%%%ERRORLEVEL%%%% returned -2146762749

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/m1-2.0/recipes/install_ps.rb

            34: windows_package '.NET 4.5' do
            35:   source "C:\\Users\\vagrant\\dotNet45.exe"
            36:   installer_type :custom
            37:   options '/Passive /NoRestart'
            38:   action :install
            39:   #timeout 5000
            40:   # notifies :run, 'execute[.NET Framework]', :immediately
            41: end
            42:

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/m1-2.0/recipes/install_ps.rb:34:in `from_file'

           windows_package(".NET 4.5") do
             package_name ".NET 4.5"
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :windows_package
             cookbook_name "m1-2.0"
             recipe_name "install_ps"
             source "c:\\users\\vagrant\\dotnet45.exe"
             installer_type :custom
             options "/Passive /NoRestart"
             returns [0]
           end

           Platform:
           ---------
           x64-mingw32

       Running handlers:
       [2016-08-25T02:58:27-07:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-08-25T02:58:27-07:00] ERROR: Exception handlers complete
       Chef Client failed. 2 resources updated in 02 minutes 14 seconds
       [2016-08-25T02:58:27-07:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2016-08-25T02:58:27-07:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-08-25T02:58:27-07:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: windows_package[.NET 4.5] (m1-2.0::install_ps line 34) had an error: Mixlib::Sected process to exit with [0], but received '-2146762749'
       ---- Begin output of start "" /wait "c:\users\vagrant\dotnet45.exe"   /Passive /NoRestart & exit %%%%ERRORLEVEL%%%% ----
       STDOUT:
       STDERR:
       ---- End output of start "" /wait "c:\users\vagrant\dotnet45.exe"   /Passive /NoRestart & exit %%%%ERRORLEVEL%%%% ----
       Ran start "" /wait "c:\users\vagrant\dotnet45.exe"   /Passive /NoRestart & exit %%%%ERRORLEVEL%%%% returned -2146762749
>>>>>> Converge failed on instance <default-windows-2008-r2>.
>>>>>> Please see .kitchen/logs/default-windows-2008-r2.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: WinRM exited (1) for command: [
$env:PATH = [System.Environment]::GetEnvironmentVariable("PATH","Machine")

& $env:systemdrive\opscode\chef\bin\chef-client.bat --local-mode --config $env:TEMP\kitchen\client.rb --log_level auto --force-formatter --no-color --json-atton --chef-zero-port 8889]
>>>>>> ----------------------

## Chef Version

Kitchen version 1.8.0
$ chef -v
Chef Development Kit Version: 0.14.25
chef-client version: 12.10.24
berks version: 4.3.3
kitchen version: 1.8.0

## Platform Version

Running kitchen on Windows 2008 R2 Server

## Replication Case
Recipe is as under:

```
cookbook_file "C:\\Users\\vagrant\\dotNet45.exe" do
   source 'dotNetFx45_Full_setup.exe'
   action :create_if_missing
end

cookbook_file "C:\\Users\\vagrant\\Win7.msu" do
   source 'Win7.msu'
   action :create_if_missing
end

powershell_script 'Install .NET 4.5...' do
  code <<-EOH
    # $location = "C:\\Windows\\Temp"
    # $exe = "dotNet45.exe"
    # $args = "/q", "/norestart"
    # Start-Process -FilePath "$location\\$exe" -ArgumentList $args -Wait -PassThru
    # Start-Sleep 300
    # echo "Exit status"
    wmic process call create "cmd.exe /c C:\\Windows\\Temp\\dotNet45.exe /q /norestart"
  EOH
end
```

Further even the below does not work:

```
windows_package '.NET 4.5' do
  source "C:\\Users\\vagrant\\dotNet45.exe"
  installer_type :custom
  options '/Passive /NoRestart'
  action :install
  #timeout 5000
  # notifies :run, 'execute[.NET Framework]', :immediately
end

windows_package '.NET Framework' do
  source "C:\\Users\\vagrant\\Win7.msu"
  installer_type :custom
  options '/quiet /norestart'
  action :nothing
end
```

**Comment by btm** [comment]
Have you tried using an offline installer? https://msdn.microsoft.com/en-us/library/ee942965(v=vs.110).aspx

**Comment by smurawski** [comment]
@samsonkolge You cannot install windows update packages over WinRM (which is how kitchen is running Chef) without using `elevated: true` in the transport (which will run chef via a scheduled task rather than directly in the winrm context.
