### ISSUE TITLE
Cannot add mount to Windows 2012 R2 Server

### ISSUE THREAD

**Issue by sconicelli** [chef/chef#5255]
## Description

I am attempting to mount a network share on Windows 2012 R2 Server however it seems the mount is never really being mounted to the OS.  I am logging directly on to the node and then executing "chef-client" from PowerShell as an administrator.

When I run chef-client, it finishes successfully however nothing is mounted... My "puts" expression is showing the value of `"#{node['mount_repo']['windevice']}"` however is seems the device is not being interpreted within the "mount" block. (see code below).

Any help would be greatly appreciated... 

Thanks,
Steve
## Chef Version

Chef client version is 12.12.15
## Platform Version

Operating system is Windows 2012 R2 (x86_64)
Chef client version is 12.12.15
## Replication Case

My `default.rb` recipe's code is as follows:

```
if platform?("windows")
    puts "Mounting #{node['mount_repo']['windevice']} to #{node['mount_repo']['windir']}..."
    mount node['mount_repo']['windir'] do
      device "#{node['mount_repo']['windevice']}"
      username "#{node['mount_repo']['winuser']}"
      password "#{node['mount_repo']['winpasswd']}"

      action :mount
        end
else
    mount node['mount_repo']['nixdir'] do
      action :mount
      device "#{node['mount_repo']['nixdevice']}"
        end
end
```

When I run the chef-client, the "puts" command is showing the value of  `#{node['mount_repo']['windevice']}` however it seems it is not being interpreted within the "mount" block.
## Client Output

```
PS C:\Windows\system32> chef-client
Starting Chef Client, version 12.12.15
resolving cookbooks for run list: ["mount_repo"]
Synchronizing Cookbooks:
  - mount_repo (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Mounting \\123.456.789.10\stage to W:...
Converging 1 resources
Recipe: mount_repo::default
  * mount[W:] action mount
    - mount  to W:

Running handlers:
Running handlers complete
Chef Client finished, 1/1 resources updated in 18 seconds
```
## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.
### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.
- [Server issues](https://github.com/chef/chef-server/issues/new)
- [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
- Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by btm** [comment]
@sconicelli can you still produce this? can you share a log file from a `chef-client -l debug` run?

**Comment by stuartpreston** [comment]
Closing this as unanswered. Retested on Windows 2016 and Chef Client 14.3.37 and the mount resource seems to work normally.

```
C:\Users\Administrator>type repro.rb
mount 'W:' do
  device '\\\\172.27.16.136\\opscode'
  username 'Administrator'
  password 'P2ssw0rd'
  domain ENV['COMPUTERNAME']
  action :mount
end

C:\Users\Administrator>chef-apply repro.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * mount[W:] 
    - mount  to W:

C:\Users\Administrator>net use
New connections will be remembered.


Status       Local     Remote                    Network

-------------------------------------------------------------------------------
OK           W:        \\172.27.16.136\opscode   Microsoft Windows Network
The command completed successfully.
```
