### ISSUE TITLE
Gem windows-pr should be installed by chef-client on windows.

### ISSUE THREAD

**Issue by 375gnu** [chef/chef#5275]
## Description

Gem `windows-pr' should be installed by chef-client. I see it bundled with 11.6.0.

## Chef Version

12.13.37

## Platform Version

Windows Server 2008 R2

## Replication Case

Just try to use `windows' cookbook with this client version.

**Comment by thommay** [comment]
Hi,
thanks for your feature request. I don't think we should add a gem dependency to chef, but we should definitely open a request on the windows cookbook to do so. It would be helpful if you could do so with examples of what fails if it's not installed.
Thanks!
