### ISSUE TITLE
yum_repository action :delete doesn't seem to work

### ISSUE THREAD

**Issue by tas50** [chef/chef#5282]
We have an alias in the provider for backwards compatibility. At some point we changed the action from delete to remove. There's a lot of deletes floating around. In the cookbook the backwards compat seems to work, but it's not working in core chef.

https://github.com/chef/chef/blob/master/lib/chef/provider/yum_repository.rb#L110

Chef::Exceptions::ValidationFailed
----------------------------------
Option action must be equal to one of: nothing, create, remove, make_cache, add!  You passed :delete.

**Comment by lamont-granquist** [comment]
resource just needs to have those two added to allowed_actions

**Comment by tas50** [comment]
I'll get a PR in for that

**Comment by tas50** [comment]
Fixed in #5320

**Comment by tas50** [comment]
This is fixed in master
