### ISSUE TITLE
Removing a windows registry key requires data to be passed

### ISSUE THREAD

**Issue by tas50** [chef/chef#5283]
When running the following resource on Chef 12.13.37 you get an error that you must provide a data key, which seems really odd since you're deleting a key not adding it.

``` ruby
  registry_key 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Run' do
    values [{
      name: new_resource.name,
      type: :string
    }]
    action :delete
  end
```

```
           ArgumentError
           -------------
           Missing data key in RegistryKey values hash

```

**Comment by lamont-granquist** [comment]
probably easy to fix with a making the exception (hopefully in define_resource_requirements) conditional on the action.

**Comment by tas50** [comment]
Our docs actually document this bug btw

**Comment by lamont-granquist** [comment]
i kind of feel like this may be a dup of an already existing bug.

**Comment by lamont-granquist** [comment]
i might be thinking of the value_exists? / data_exists? confusion one though.

**Comment by lamont-granquist** [comment]
paging @chef/client-windows on this one as well

**Comment by mwrock** [comment]
yeah definitely seems like we should only raise when adding and not deleting.

**Comment by ksubrama** [comment]
:+1: to the above

**Comment by Aliasgar16** [comment]
The fix for this issue can be tracked [here](https://github.com/chef/chef/pull/5359).

**Comment by btm** [comment]
Fixed by https://github.com/chef/chef/pull/5359.
