### ISSUE TITLE
remote_file on windows errors before trying all sources

### ISSUE THREAD

**Issue by drrk** [chef/chef#5286]
## Description

When using a remote_file resource, with multiple sources if a source fails with a timeout the next source is not tried, but instead a FATAL error is raised.  This is different behavior to that of Linux that correctly moves onto the next source given.

## Chef Version

12.13.37

## Platform Version

Windows Server 2012r2

## Replication Case

See https://gist.github.com/drrk/b1a0478ba9134541c47b5c5fcbb0bf51

## Client Output

See https://gist.github.com/drrk/e48600c2b460cdad8e8c2766d420e4d6

**Comment by Contreraznt** [comment]
Contreraz@live.com,victorhsaliascontreraz@gmail.com are me account for the only thing that comes with a good news to me and contreraz@live.com is the only way to get it done in my phone is a two-part interview with the big boys.

**Comment by Contreraznt** [comment]
Contreraz@live.com hasn't been able to work with you on in my account access denied please grant me account access.

**Comment by lamont-granquist** [comment]
i don't know why windows would be special in this regard.  smells more like it may be a generic bug against the remote_file provider where it needs to catch Errno::ETIMEDOUT and move on.

**Comment by NimishaS** [comment]
@drrk , fix for this issue: https://github.com/chef/chef/pull/5358. This will work in case a source url times out.

For, `http://192.168.0.9/test_file` I was getting `EOFError` and not `Timeout Error`. Details of the error can be found here: https://gist.github.com/NimishaS/815ea1df9a9f14e0fdf0124213b88dfa

**Comment by rhass** [comment]
The fix will be in the next Chef release.

**Comment by Contreraznt** [comment]
Contreraz@live.com hasn't been able to get to login and victorhsaliascontreraz@gmail.com is the only way to get it done with the big boys and contreraz@live.com is a two-part interview with the first of its kind in my phone
