### ISSUE TITLE
Chef Client 12.13.37 changes apt_repository semantics

### ISSUE THREAD

**Issue by tokenrain** [chef/chef#5304]
## Description

We recently updated some of our chef clients to 12.13.37 and incurred some breakage which we tracked down to the apt_repository resource which is now part of core chef client but which has slightly different in semantics to the widely used apt cookbook.

The resource that is now part of core chef has the following in lib/chef/resource/apt_repository.rb:

property :distribution, [ String, nil, false ], default: lazy { node["lsb"]["codename"] }, nillable: true, coerce: proc { |x| x ? x : nil }

This is different from the apt cookbook which has:

attribute :distribution, kind_of: String

The resource from the core chef cookbook is not being overridden so that any calls to the apt_repository resource which used to have a nil distribution now results in distribution being set to node['lsb']['codename'] which changes the snippet in /etc/apt/sources.list and breaks apt.

Not that I like it but there are some 3rd party repos that do not have a distribution

## Chef Version

Chef Client 12.13.37

## Platform Version

Ubuntu 12.04 and 14.04

## Replication Case

Given the below resource definition you will get two different /etc/apt/sources.list.d/neo4j.list files depending on if chef-client has apt_repository built in (12.13.37) or nor (say 12.8.1)

  apt_repository 'neo4j' do
    uri "http://debian.neo4j.org/repo"
    components ['stable/']
    key 'http://debian.neo4j.org/neotechnology.gpg.key'
    action :add
  end

## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by coderanger** [comment]
Yes, to address the rare cases where the default is undesired you can set `distribution nil`. Is that not working correctly?

**Comment by tokenrain** [comment]
I just wanted to point this out - If this was known then great -  setting it manually does work - it is just that I do not control some of the cookbooks that are affected so I am going to have to mod some community cookbooks and issue some pull requests. Oh well. Thanks

**Comment by coderanger** [comment]
If you still have the cookbook loaded, it should take priority over the core resource. Because of this we generally don't promise compat when pulling resources in to core, they generally get a tune up before we want to put an API promise back on them :)
