### ISSUE TITLE
User manage_home not working in chef-client 12.14.60

### ISSUE THREAD

**Issue by bradenwright** [chef/chef#5318]
## Description
User home has been working fine, 12.13.37 works.

```
  user username do
    comment comment
    gid     new_resource.gid
    home    new_resource.home
    supports :manage_home => true
    shell   shell
  end
```

## Chef Version
12.14.60

## Platform Version
Ubuntu 14.04

## Client Output
When I log onto the box you can see its has not been created:
```
root@default-ubuntu-1404-1471838078:~# ls -l /home/
total 1
drwxr-xr-x 3 ubuntu ubuntu 6 Sep 13 04:56 ubuntu
root@default-ubuntu-1404-1471838078:~# cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
libuuid:x:100:101::/var/lib/libuuid:
syslog:x:101:104::/home/syslog:/bin/false
messagebus:x:102:106::/var/run/dbus:/bin/false
landscape:x:103:109::/var/lib/landscape:/bin/false
sshd:x:104:65534::/var/run/sshd:/usr/sbin/nologin
pollinate:x:105:1::/var/cache/pollinate:/bin/false
ubuntu:x:1000:1000:Ubuntu:/home/ubuntu:/bin/bash
ntp:x:106:111::/home/ntp:/bin/false
bwright:x:1001:110::/home/bwright:
root@default-ubuntu-1404-1471838078:~# ls -l /home/
total 1
drwxr-xr-x 3 ubuntu ubuntu 6 Sep 13 04:56 ubuntu
root@default-ubuntu-1404-1471838078:~# 
```

**Comment by lamont-granquist** [comment]
you're using `supports { :manage_home => true }` not `manage_home true` try using the latter.

**Comment by lamont-granquist** [comment]
you should also be seeing this error message:

https://github.com/chef/chef/blob/7de537bfb14fb5869cedd7008fafa414d2ad06e7/lib/chef/resource/user/linux_user.rb#L39

**Comment by coderanger** [comment]
@lamont-granquist I think the bigger issue is that the default changed again.

**Comment by lamont-granquist** [comment]
the default didn't change though its always been false, and that didn't get modified

**Comment by lamont-granquist** [comment]
it looks like `supports { :manage_home => true }` used to be a synonym for `manage_home true` which "broke"

we can go back to that behavior i guess, but its pretty terrible behavior, and we'll definitely break everyone with Chef 13.

**Comment by coderanger** [comment]
https://github.com/chef/chef/pull/5122#discussion-diff-71311061 is the last discussion on this that I remembered.

**Comment by lamont-granquist** [comment]
the whole thing is terribly confusing, and dates back to the fact that in chef 0.6.x it looks like we started down the road of making one useradd provider class that would use `supports[:manage_home]` to implement different behavior on different distros.  we later went to using subclasses that implement solaris and aix versions of the provider instead (which is better although still mildly awful).  but the supports api is vestigial design at this point.

**Comment by lamont-granquist** [comment]
and when you think about the meaning of settings supports[:manage_home] to false on a linux box where the adduser script has supported manage_home for as long as chef has existed and on every linux distro that chef supports....   well, its just cargo cults all the way down....

**Comment by lamont-granquist** [comment]
#5322 should most likely change the behavior back.

**Comment by bradenwright** [comment]
I hear you/agree.  The syntax even seemed weird/not chef like.  I'll update my code so Chef 13 won't break it.

Also someone may want to consider updating doc page... I mean it's accurate (it shows both ways) but does have an example under "supports" property of ":manage_home => false"

Thanks for the quick reply

**Comment by bradenwright** [comment]
As mentioned fixed the issue with:

```
user username do
    comment comment
    gid new_resource.gid
    home new_resource.home
    manage_home true
    shell shell
  end
```

**Comment by t0m** [comment]
This also broke us on amazon linux, we were using `supports { :manage_home => true }` instead of `manage_home` as well. The suggested fix worked.

**Comment by pkleanthous** [comment]
Guys it's an easy Fix ,although it took me time to find this thread.
Can you please update the documentation ? https://docs.chef.io/resource_user.html

**Comment by pmahoney** [comment]
The fix is not so simple if using the `users` cookbook. Latest (3.0.0) `users` cookbook uses this now unsupported syntax: [users/providers/manage.rb:91](https://github.com/chef-cookbooks/users/blob/v3.0.0/providers/manage.rb#L91).

**Comment by lamont-granquist** [comment]
its still an easy fix to the users cookbook:  https://github.com/chef-cookbooks/users/pull/353

**Comment by pmahoney** [comment]
@lamont-granquist it's a breaking change in a minor version bump. Is this normal Chef behavior?

**Comment by lamont-granquist** [comment]
we're probably going to revert it in #5322

**Comment by dcampano** [comment]
I was also bit by this and while it is an easy fix it was an aggravation to track down why my cookbook was working fine previously.

**Comment by lamont-granquist** [comment]
12.14.77 reverted this.

note that `supports: { manage_home: true }` is still deprecated and must be replaced with `manage_home: true` or else you'll break in Chef 13
