### ISSUE TITLE
CHANGELOG.md doesn't mention addition of yum_repository

### ISSUE THREAD

**Issue by mfischer-zd** [chef/chef#5321]
## Description

CHANGELOG.md doesn't mention addition of yum_repository

## Chef Version

12.14

## Details

A `yum_repository` resource provider was added during the release of Chef 14.  Not only is this not backward compatible with the third-party cookbook upon which many of us have relied for years (see, e.g., #5317, #5282), but it wasn't documented in the release notes or the CHANGELOG or in the Chef resource documentation (see https://github.com/chef/chef-web-docs/issues/117).

**Comment by lamont-granquist** [comment]
its there under "Create and delete yum repositories #5187 (thommay)" the title of the PR was changed sometime after the last time the changelog was generated

**Comment by lamont-granquist** [comment]
since @tas50 has already addressed the issue with the :delete resource being missing and the next time the changelog is regenerated it'll pick up the changed title of the PR, i don't think there's anything actionable here.

**Comment by mfischer-zd** [comment]
Please reopen until a product manager can assess, thanks.

**Comment by tas50** [comment]
I updated the text of the PR but the original changelog had already been merged. The change not making it into the release notes was a bit of miscommunication on my part prior to the release. The changelog text and the release notes are updated in #5323. The property and action behavior has been corrected in #5320, which we'll be releasing shortly
