### ISSUE TITLE
not_if 'which ruby' does not work because chef-client contaminates ENV['PATH']

### ISSUE THREAD

**Issue by Hinaser** [chef/chef#5331]
## Description

I encountered an issue when installing ruby from source.

```bash
bash 'install_ruby' do
  user 'root'
  cwd '/tmp'

  not_if 'which ruby'

  code <<-EOC
    tar xzf /usr/local/src/ruby-2.3.1.tar.gz -C ./
    (cd ruby-2.3.1} && ./configure --disable-install-rdoc && make && make install)
    gem install bundler --no-ri --no-rdoc
  EOC
end
```

I intended to run this recipe when ruby is not installed.
When ruby is installed, this script will not execute.

But this recipe won't work as intended because of unexpected behavior of `not_if` instruction.
It is expected that when `'which ruby'` returns 1, meaning ruby is not found on system, bash resource tries to install ruby from source, but it never does.

If the target application is other than ruby, it works.

### The reason

This happens because `PATH` environment variable is contaminated by chef-client.
For detail, while chef-client is running, `PATH` would be like this:
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/chef/embedded/bin:/opt/chef/embedded/bin`

It is also strange that `/opt/chef/embedded/bin`  duplicates.
I doubt that code around initializing the `PATH` environment variable has some defect.

### How to confirm chef actually contaminates PATH?

It is easy. Create the recipe like described below and run chef-client in local-mode.

```bash
# Please confirm that you are on OS which has chef-DK or chef-client installed
# If you haven't installed chef-DK, install by the command below
#
# wget https://omnitruck.chef.io/install.sh -O - | sudo bash -s -- -P chefdk -c stable -v 0.16.28
#
cd /tmp

# Create recipe
cat << EOF > reproduce_bug.rb
  bash 'reproduce_dirty_path_bug' do
    user 'root'
    cwd '/tmp'

    code <<-EOC
      echo \$PATH > dirty_path.txt
      which ruby > should_be_empty.txt
    EOC
  end
EOF

# Run recipe
sudo chef-client --local-mode reproduce_bug.rb

# Check the result
cat dirty_path.txt
```

For my test environment, the contents of both `dirty_path.txt` and `should_be_empty.txt` are like this:
```
# cat dirty-path.txt
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/chefdk/embedded/bin:/opt/chefdk/embedded/bin
```
```
# cat should_be_empty.txt
/opt/chefdk/embedded/bin/ruby
```

## Chef Version

```
vagrant@host1:~$ chef --version
Chef Development Kit Version: 0.16.28
chef-client version: 12.12.15
delivery version: master (921828facad8a8bbbd767368bfc72f19bd30e7bd)
berks version: 4.3.5
kitchen version: 1.10.2
```

## Platform Version

Debian 8.5 Jessie 64bit on VirtualBox created by Vagrant

```bash
vagrant@host1:~$ uname -a
Linux host1 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
```

## Replication Case

```bash
# Please confirm that you are on OS which has chef-DK or chef-client installed
# If you haven't installed chef-DK, install by the command below
#
# wget https://omnitruck.chef.io/install.sh -O - | sudo bash -s -- -P chefdk -c stable -v 0.16.28
#
cd /tmp

# Make sure ruby is not already installed
which ruby

# Create recipe
cat << EOF > reproduce_bug_in_installing_ruby.rb
  bash 'reproduce_bug_in_installing_ruby' do
    user 'root'
    cwd '/tmp'

    not_if 'which ruby'

    code <<-EOC
      echo "If Ruby is not installed, you should see this message"   >> /tmp/would_not_be_created.txt
    EOC
  end
EOF

# Run recipe
sudo chef-client --local-mode reproduce_bug_in_installing_ruby.rb
```

## Client Output

The output result from the above `sudo chef-client --local-mode reproduce_bug_in_installing_ruby.rb` command is:
The output by `chef-client` command is:
```bash
[2016-09-16T15:49:13+09:00] WARN: No config file found or specified on command line, using command line options.
[2016-09-16T15:49:13+09:00] WARN: No cookbooks directory found at or above current directory.  Assuming /tmp.
Starting Chef Client, version 12.12.15
resolving cookbooks for run list: []
Synchronizing Cookbooks:
Installing Cookbook Gems:
Compiling Cookbooks...
[2016-09-16T15:49:15+09:00] WARN: Node host1 has an empty run list.
Converging 1 resources
Recipe: @recipe_files::/tmp/reproduce_bug_in_installing_ruby.rb
  * bash[reproduce_bug_in_installing_ruby] action run (skipped due to not_if)

Running handlers:
Running handlers complete
Chef Client finished, 0/1 resources updated in 01 seconds
```

The above result tells that bash resource 'install_ruby' was skipped even though ruby was not installed on system.

**Comment by coderanger** [comment]
Obligatory-but-maybe-unhelpful "here is a thing that solves this" https://github.com/poise/poise-ruby-build/

**Comment by coderanger** [comment]
Also there is a really low chance we're going to change this at this point. It's been argued back and forth how much we should standardize the runtime environment and having some tools always available on the path is just really useful. Solves more problems than it creates :-/

**Comment by Hinaser** [comment]
Hi @coderanger 
Thanks for comments.

Before I posted this issue, I searched all issues on this chef repository but I could never reach the same issue. Maybe because I looked only issue titles?

Yes, this issue may affect very limited people, so importance might be low.
But at least we should hit the pile for everyone struggling the same issue here.

And I don't understand that we definitely need $PATH to be modified because scripts under chef's embedded directory can be accessed by fullpath or using any other chef specific environment variables.

**Comment by lamont-granquist** [comment]
this is a dup of #4724

there's a bit of back-and-forth-flailing in that ticket but i think my conclusion is essentially correct here: 

https://github.com/chef/chef/issues/4724#issuecomment-212519849

we need to have a shell_out API for internal use within chef-client (when we internally shell_out to `apt-get install` or whatever in package providers) where we do things like forcing an English locale so that unix utilities don't try to speak German to us, and we also need path_sanity for those use cases.   because we're a configuration management system we have to assume that the base configuration of the system is insane (which it often is -- locale settings by default on upstart under ubuntu were particularly laughably bad).  but then there's the problem of "okay you really set latin-1 on your system and really expect your services to start in latin-1 and we shouldn't override that intention" which is what shell_out_with_systems_locale is all about.   we need to fix that a bit better so that API becomes shell_out_external or something (or really it should probably be how shell_out() behaves and nearly every single use of shell_out that we have in the codebase should be changed to shell_out_internal() which will behave like shell_out() behaves now).  it should be hopefully fairly obvious that we need to do that in a major breaking change.

**Comment by lamont-granquist** [comment]
yeah think i'm going to close this -- its still here so anyone who google searches it can find all this text and get led to the still-open issue around it.

**Comment by Hinaser** [comment]
Hi @lamont-granquist 

It's OK.  I hope this conversation would be useful to someone.
