### ISSUE TITLE
Segmentation fault with chef-client 12.14.60 on Windows 2012R2

### ISSUE THREAD

**Issue by rlaveycal** [chef/chef#5333]
## Description

I have a custom resource that creates a Windows share using win32ole (pull request is [here](https://github.com/chef-cookbooks/windows/pull/282)). It does the following

```
require 'win32ole'
wmi = WIN32OLE.connect("winmgmts://")
share = wmi.get("Win32_Share")
r = share.create('c:\', 'my_share', 0, 16777216, 'test', nil, nil)
```

which results in
```
[BUG] Segmentation fault
ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]
-- Control frame information -----------------------------------------------
c:0041 p:---- s:0171 e:000170 CFUNC  :method_missing
c:0040 p:0102 s:0160 e:000159 METHOD C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/ctn-infrastructure/providers/share.rb:145
```

It's the call to create() that cause the fault.

It works with chef-client 12.13.37

## Chef Version

12.14.60

## Platform Version

Windows 2012R2

## Replication Case

Put the above script in a block and execute, or use the referenced pull request

## Client Output

https://gist.github.com/rlaveycal/7d0593864aeb5826054ba11353fd9d44

**Comment by lamont-granquist** [comment]
this looks like a bug with win32ole on ruby 2.3.1?  i'm not sure there's anything we'll be able to do about that here, since we can't roll back the ruby version (and we RFC'd this process understanding that we might break a few people in a minor update, but we had to move on from ruby 2.1 since its dropping off support).  that bug should probably get addressed in the win32ole repo.

**Comment by rlaveycal** [comment]
It's definitely a chef client issue.
 * execute code in irb : Works
 * execute code in ruby_block : Works
 * execute code in LWRP : Seg fault

I'll strip my LWRP down tomorrow and see if I can isolate a trigger.

**Comment by rlaveycal** [comment]
You're right - this is a win32ole bug on x64. The issue is with the 3rd to last string parameter (which is the share's description). If this is `''` then you get the fault. Set to `nil` or any other value and it works

For reference this causes the issue:
```
\opscode\chef\embedded\bin\ruby -rwin32ole -e 'wmi = WIN32OLE.connect("winmgmts://"); share = wmi.get("Win32_Share"); puts share.create("c:\\test2", "test", 0, 16777216, "", nil, nil)'
```

I've closed this issue and I'll raise a bug on Ruby.

**Comment by kamaradclimber** [comment]
I have exactly the same kind of segmentation fault on method_missing.

```
WIN32OLE.new('Schedule.Service').tap(&:connect).NewTask(0).tap do |task|
  task.RegistrationInfo.Author = 'Chef'
  task.Principal.tap do |principal|
    principal.UserId = new_resource.user
    principal.GroupId = new_resource.group
  end
end
```

it fails when new_resource.group is empty `''`
