### ISSUE TITLE
Enhancement: Provide a way to notify resource if defined

### ISSUE THREAD

**Issue by mfischer-zd** [chef/chef#5336]
It should be possible for a resource to notify a resource if and only the resource to be notified exists.  (Put differently, it should be possible to make a run not fail at runtime with an uncaught exception if the notified resource has not been defined at compile time.)

An example would be a cleanup recipe that removes a conf.d file, and notifies the daemon that might use the conf.d file to reload.  If the daemon is no longer being managed by Chef, it's not fatal that the daemon's service is no longer declared.

**Comment by coderanger** [comment]
The easiest way to handle this would be to use `find_resource` to declare the target if it hasn't been already.

**Comment by mfischer-zd** [comment]
A DSL enhancement would be preferable, e.g.:

```
resource 'foo' do
   notifies :action, 'some[resource]', :if_exists, :immediately
end
```

**Comment by coderanger** [comment]
DSL changes are the biggest hammer we have, and generally only used for something either very common or that doesn't increase the API surface. Given that this hasn't come up enough for someone to ask for it, I don't think that's a good fix.

```ruby
recipe = self
ruby_block 'whatever' do
  block do
    recipe.find_resource(:service, 'name') do
      action :nothing
      provider :noop
    end
end
```

That should be all you need in your recipe :)

**Comment by mfischer-zd** [comment]
Let's ask the community; this is not a decision you get to make by yourself.

**Comment by lamont-granquist** [comment]
I'm not finding the example compelling either:

```
service "thing" do
  action :nothing
end

file "/etc/thing.d/thing.conf" do
  action :remove
  notifies :stop, 'service[thing]', :before
end
```

either wrap it in a resource to avoid 3694 errors, or rename the service resource.

**Comment by mfischer-zd** [comment]
@lamont-granquist What if the service is defined elsewhere?   Doesn't your example redefine its behavior as a side effect?

**Comment by coderanger** [comment]
@mfischer-zd The example I gave uses `find_resource` to only define it if it isn't already defined.

**Comment by lamont-granquist** [comment]
it doesn't really hurt to define the service twice.  even with resource cloning and 3694 errors that simple of a resource clone is unlikely to cause issues other than spitting out the WARN that everyone ignores.  and its easy to work around:

```
service "thing-being-removed" do
  service_name "thing"
  action :nothing
end

file "/etc/thing.d/thing.conf" do
  action :remove
  notifies :stop, 'service[thing-being-removed]', :before
end
```

or whatever naming tactic you like to avoid the 3694 collision.

plus wrap that in a custom resource or use_inline_resources-style LWRP and the sub-resource collection makes the name unique (resources only have to be uniquely named within their own resource collection to avoid 3694 issues).

**Comment by mfischer-zd** [comment]
I agree that this is a viable workaround, @lamont-granquist, but I still fail to see how this is a better user experience than adding a simple `:if_exists` argument.  

Let's solicit user and customer feedback before making a decision.  Thanks.

**Comment by nathenharvey** [comment]
@mfischer-zd let me offer you some other ways to raise the visibility of this request so that it can have broader discussion within the community and the product team within Chef.

1.  Write it up as a [public RFC](https://github.com/chef/chef-rfc).
2.  Share the request on the [Chef feedback site](https://feedback.chef.io/) - this is reviewed by Chef Software, Inc.'s product management team.
3.  Mention this ticket (and/or your RFC, and/or you post on the feedback site) and solicit input on the [discussion forum](https://discourse.chef.io/).

**Comment by thommay** [comment]
Hi,
as @nathenharvey suggests, there are better venues for providing feature requests to Chef. It's extremely unlikely, given our backlog, that this will be prioritised through this channel, and so I'm going to close out this ticket.
I strongly encourage you to raise this via feedback.chef.io and interact with our product team there.
Thanks,
-Thom
