### ISSUE TITLE
deb package of bad quality on install

### ISSUE THREAD

**Issue by trivalik** [chef/chef#5343]
Ubuntu Software Center is hold the deb package of bad quality on install.
This was occured for install of chef server version 12.8.0.
The Ubuntu Version was as fresh installed 14.04.5
I believe the root cause is that mail address is missing behind "Maintainer:"
like here described https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Maintainer
![untitled](https://cloud.githubusercontent.com/assets/3148279/18626671/be0e328a-7e56-11e6-9a1e-f2769f4edf89.png)

**Comment by thommay** [comment]
Hi,
this is the issue tracker for the chef client, not the server. Please could you resubmit this issue at https://github.com/chef/chef-server/issues , and we'd be happy to discuss it further there.
