### ISSUE TITLE
Knife supermarket don't upload "test" directory

### ISSUE THREAD

**Issue by dfduarte** [chef/chef#5354]
## Description

Knife supermarket don't upload "test" directory

## Chef Version

Latest from DK 0.17.17. (For some reason, I've could been able to check the chef version using chef -v on MacOS, and it just throws a error)

## Platform Version

MacOS 10.11 El Captain

## Replication Case

1- Create and craft a cookbook
2- upload it using knife supermarket share <cookbook> -m <supermarket-url-to-privatespmk>
3- Download it using berks or manually
4- Test and spec dirs missing.

This affects some operations with Berkshelf (like running berkshelf under fresh Berksfile from a recently downloaded cookbook, if this cookbook have some fixtures, for example).

I know this is something done by design by Chef (and it's from the cookbook dev pattern, but it's something good to have available sometimes)

Opening here due to recommendation from the DK team. Initial ticket: https://github.com/chef/chef-dk/issues/1019

## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

**Comment by coderanger** [comment]
As mentioned on the other ticket, this is expected behavior. Non-cookbook files are not part of the release artifact.

**Comment by dfduarte** [comment]
Cool, I figured that, but I just wanted to confirm, because this is not mentioned on Supermarket/Knife documentation. Thank you so much, man!
