### ISSUE TITLE
systemd_unit provider verify property in underlying file resource breaks name-sensitive units

### ISSUE THREAD

**Issue by nathwill** [chef/chef#5362]
## Description

after merging of https://github.com/chef/chef/pull/5210, systemd_unit resource can no longer create valid units where systemd considers the unit file name to be an important (and prescribed) part of the unit definition (i.e. automount, mount, probably device units as well).

because the verify command is executed on the temporary path, this causes `systemd-analyze verify %{path}` to fail (as shown below). see also https://github.com/chef/chef/issues/5324.

example output where `systemd-analyze verify` blows up due to file name:

```
[root@default-fedora-24 ~]# systemd-analyze verify /etc/systemd/system/chef-proc-sys-fs-binfmt_misc.automount 
chef-proc-sys-fs-binfmt_misc.automount: Where= setting doesn't match unit name. Refusing.
chef-proc-sys-fs-binfmt_misc.automount: Failed to create chef-proc-sys-fs-binfmt_misc.automount/start: Unit chef-proc-sys-fs-binfmt_misc.automount is not loaded properly: Invalid argument.
```

## Chef Version

12.14+

## Platform Version

all systemd-based platforms

## Replication Case

try to converge a recipe that creates a mount unit, such as:

```ruby
systemd_unit("tmp.mount") do
  content ({
    "Mount"=>{
      "What"=>"tmpfs", 
      "Where"=>"/tmp", 
      "Type"=>"tmpfs", 
      "Options"=>"mode=1777,strictatime"
    },
    "Unit"=>{
       "Description"=>"temp dir", 
       "Documentation"=>"man:hier(7)", 
       "Conflicts"=>"umount.target", 
       "Before"=>"local-fs.target umount.target", 
       "DefaultDependencies"=>"no", 
       "ConditionPathIsSymbolicLink"=>"!/tmp"
    }
  })
  action [:create]
end
```

## Client Output

```
            ================================================================================
             Error executing action `create` on resource 'systemd_unit[tmp.mount]'
             ================================================================================
             
             Chef::Exceptions::ValidationFailed
             ----------------------------------
             file[/etc/systemd/system/tmp.mount] (dynamically defined) had an error: Chef::Exceptions::ValidationFailed: Proposed content for /etc/systemd/system/tmp.mount failed verification #<Chef::Resource::File::Verification:0x00000002cbcb20>
             
             Resource Declaration:
             ---------------------
             # In /tmp/kitchen/cache/cookbooks/systemd/libraries/resource_factory.rb
             
       48:               systemd_unit "#{new_resource.name}.#{unit_type}" do
       49:                 triggers_reload new_resource.triggers_reload
       50:                 content property_hash(
       51:                   Systemd.const_get(unit_type.to_s.camelcase.to_sym)::OPTIONS
       52:                 )
       53:                 action actn
       54:               end
       55:             end
             
             Compiled Resource:
             ------------------
             # Declared in /tmp/kitchen/cache/cookbooks/systemd/libraries/resource_factory.rb:48:in `block (2 levels) in build_resource'
             
             systemd_unit("tmp.mount") do
        action [:create]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        declared_type :systemd_unit
        cookbook_name "setup"
        triggers_reload true
        content {"Mount"=>{"What"=>"tmpfs", "Where"=>"/tmp", "Type"=>"tmpfs", "Options"=>"mode=1777,strictatime"}, "Unit"=>{"Description"=>"temp dir", "Documentation"=>"man:hier(7)", "Conflicts"=>"umount.target", "Before"=>"local-fs.target umount.target", "DefaultDependencies"=>"no", "ConditionPathIsSymbolicLink"=>"!/tmp"}}
             end
```

**Comment by nathwill** [comment]
at this point i think it's reasonable to revert #5210 while considering alternative approaches to add the desired functionality.

**Comment by lamont-granquist** [comment]
did you check with 12.14.77 and after https://github.com/chef/chef/pull/5327 was merged?

**Comment by nathwill** [comment]
yes, i did. the fix in #5327 only affected file extensions, this bug is for units with prescribed names, where a temp file (prefixed with chef-) just flat out won't ever validate; for mount, automount (+other?) units, the file name in its entirety is prescribed (i.e. an automount unit for '/home/myuser' *must* be named home-myuser.automount to be valid).

**Comment by lamont-granquist** [comment]
```
Mount units must be named after the mount point directories they control. Example: the mount point /home/lennart must be configured in a unit file home-lennart.mount.
```

well that is somewhat abusively terrible of systemd.

@mwrock @stevendanna okay i've hit the "yeah, lets revert it" point unless someone can think of something more cleverer

although i think that #5327 is still a useful improvement to have so probably don't need to revert that one.

**Comment by nathwill** [comment]
the only thing i can think of here is creating/registering a custom verifier that copies the temp-path to the systemd run-path ('/run/systemd/system/new_resource.name') and performs the validation there before removing it, but that's quite a bit more involved... i'll try to play around with it soon, as i do really like the idea of verifying the units since we basically take free-form unit content in the content property.

**Comment by nathwill** [comment]
> well that is somewhat abusively terrible of systemd.

yes, given that the units also have the 'Where' and 'What' properties, it seems... odd... to be so finicky about naming, but whatcha gonna do :/

**Comment by lamont-granquist** [comment]
i, for one, welcome our new systemd overlords...

**Comment by nathwill** [comment]
haha, indeed. and just to be clear, my definition of "soon" for me trying to put together a custom verifier is more like "sometime in the next month", so i still think the immediate action should be to revert, unless somebody's got another fast-and-fancy fix in mind.

**Comment by mwrock** [comment]
I'm sadly in favor of reverting. reopened https://github.com/chef/chef/pull/5326

**Comment by stevendanna** [comment]
@mwrock @lamont-granquist I think revert makes sense for now.  A custom verifier in ruby might be a nice solution but we can't leave it broken until then and taking a peak at the systemd code I don't see any fast way around the filename check (at least none that we would be comfortable committing :D)

**Comment by thommay** [comment]
Closing this ticket since we've reverted the code.
