### ISSUE TITLE
'knife download cookbooks' corrupting certificate files

### ISSUE THREAD

**Issue by gifkinsj** [chef/chef#5363]
## Description

I'm running Chef DK on Windows 7 and I'm experiencing an issue when using "knife download cookbooks" versus "knife cookbook download <cookbook name>". The problematic cookbook in question contains x509 certificate. When using "knife download cookbooks", the correct version of the cookbook is downloaded (i.e latest), however the certificate seems to get corrupted. When I use "knife cookbook download <cookbook name>", the cookbook downloads correctly and the certificate is as expected.. Furthermore chef-client downloads the cookbook correctly.
## Chef Version

Chef DK 0.17.17 and 
Chef Server 12.2.0 
## Platform Version

ChefDK - Windows 7.
Chef Server - CentOS 7.
## Replication Case
1. Have a cookbook contain an x509 certificate, on the Chef Server repo
2. Issue "knife download cookbooks", see relevant cookbook files update
3. Issue "knife download cookbooks" again, the certificate file will show as updated (the MD5 sum remains the same however)

Also the byte size of the file will not be the same as the source file, however if you use "knife cookbook download x", the byte size will be correct and file won't be corrupt (md5 is also correct).
## Client Output

https://gist.github.com/gifkinsj/12f64b50acf7861aeca9fb8ae97142ec 
## Stacktrace

No stack trace created

**Comment by lamont-granquist** [comment]
probably be useful to know how the encoding / localization on the window box was setup...   i'm fearfully ignorant of such things on windows though so i can't tell you how to do that, but on unix I'd as you for the output of `set | egrep -a "^(LANG|LC)"`

**Comment by gifkinsj** [comment]
The Windows implementation of charsets (or code pages) is interesting: http://ss64.com/nt/chcp.html

When setting the code page to 65001 (or UTF-8), I still have the same issue when downloading.

Interestingly the "knife cookbook download" works without a problem, perhaps that command enforces the char set?

**Comment by thommay** [comment]
When you say "corrupt", is the file visibly changed? Can you check that line endings are the same in both cases?

**Comment by lamont-granquist** [comment]
yeah UTF-8 should work, so that makes an encoding issue less likely.     ^^^ i kinda like thom's line of thought that it might be line ending issues...

**Comment by Aliasgar16** [comment]
Fix for this can be tracked [here](https://github.com/chef/chef/pull/5494).
