### ISSUE TITLE
Typo that breaks "make_cache" in new integrated yum_repository code

### ISSUE THREAD

**Issue by 85matthew** [chef/chef#5364]
## Description

With older version of chef-client, was previously using the public yum repo to do installs similar to:

yum_repository 'package_name' do
  description 'package description'
  baseurl 'http://path.com'
  action [:create, :makecache ]
end

With the new chef-client version (and integrated yum_repository) "makecache" is no longer a valid option: Above code throws:

 Chef::Exceptions::ValidationFailed
    ----------------------------------
    Option action must be equal to one of: nothing, create, remove, make_cache, add, delete!  You passed :make cache.

Would be nice to support ":makecache" and ":make_cache" with depreciation warning but I have already updated recipes to test ":make_cache"

Found typo in provider that is still set to ":makecache" when all other resources (and above in provider) support :make_cache  

## Chef Version

Chef: 12.14.77

## Platform Version

Centos7

## Replication Case

Run any:

yum_repository with action [:makecache or :make_cache ]

## Client Output

When run with older ":makecache"

Chef::Exceptions::ValidationFailed
    ----------------------------------
    Option action must be equal to one of: nothing, create, remove, make_cache, add, delete!  You passed :make cache.

When updated to run with new ":make_cache"

 NoMethodError
    -------------
    undefined method `action_make_cache' for #<Chef::Provider::YumRepository:0x00000003c575a8>
    Did you mean?  action_makecache

## Stacktrace

N/A

## Fix- 

Propose longer term support both [:makecache ] and [:make_cache] with depreciation warning.

ASAP fix- Line 97 on below link.

Change 
from- (action :makecache do)
to - (action :make_cache do)

https://github.com/chef/chef/blob/master/lib/chef/provider/yum_repository.rb

**Comment by tas50** [comment]
@85matthew I fixed this one here https://github.com/chef/chef/pull/5348

Sorry you're running into this

**Comment by 85matthew** [comment]
Got it. thanks for the quick response! 

Any idea when a new chef-client version/build will be published?

**Comment by tas50** [comment]
@85matthew Today if we don't hit and road blocks

**Comment by 85matthew** [comment]
thanks!
