### ISSUE TITLE
The process encountered Chinese will produce garbled

### ISSUE THREAD

**Issue by shanyaoshiguang** [chef/chef#5370]
## Description
I specify the client start java process in the chef server,When I execute chef-client in client,When the parameters in the process of transfer Chinese when there will be garbled,But if I'm going to start with admin's identity, everything goes well.

## Chef Version
chef-server version 11.0.11
chef-client version 11.10.4

## Platform Version
OS == CentOS Linux 2.6.32
Tell us which Operating System distribution and version chef-client is running on.

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

execute "run" do
  user "admin"
  cwd "/export/App/pay.center.company.test/pay_center/bin"
  command "source /etc/profile;/export/App/pay.center.company.test/pay_center/bin/start.sh"
end
## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by thommay** [comment]
Unfortunately with such old versions of chef it's hard to tell if this is a bug that has been subsequently fixed. If you can upgrade to chef 12 and try there then we're more likely to be able to help you.
I'm going to close this ticket, but feel free to reopen it if you can try and confirm with a more recent version of chef.
