### ISSUE TITLE
Getting error while registering node to chef server - OpenSSL::X509::CertificateError: nested asn1 error

### ISSUE THREAD

**Issue by ankurvaish88** [chef/chef#5376]
Hi Folks , 

I am trying to setup chef-server & client on my personnel VM just (for studying purpose) and hence using etc/hosts entries as local dns /hostnames of chef-server and client . My server is ready and also accessible via GUI , but getting certificate error while registering client to node via following command - 

chef-client -S https://localhost.localdomain -K /etc/chef/trusted_certs/chef-validator.pem

chef-server url - https://localhost.localdomain 
validator key - chef-validator.pem (simple copied from chef-server) 
Location of chef-server's cert on client machine - /root/.chef/trusted_certs/localhost.localdomain.crt  (copied from chef-server) 

chef-client -v
Chef: 12.14.60

*Output of stacktrace.out file - *

```
Generated at 2016-09-23 11:48:41 +0530
OpenSSL::X509::CertificateError: nested asn1 error
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http/ssl_policies.rb:82:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http/ssl_policies.rb:82:in `new'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http/ssl_policies.rb:82:in `block in set_custom_certs'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http/ssl_policies.rb:81:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http/ssl_policies.rb:81:in `set_custom_certs'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http/ssl_policies.rb:48:in `apply'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http/ssl_policies.rb:35:in `apply_to'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http/basic_client.rb:153:in `configure_ssl'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http/basic_client.rb:117:in `build_http_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http/basic_client.rb:51:in `http_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http/basic_client.rb:70:in `request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http.rb:341:in `block in send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http.rb:373:in `block in retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http.rb:371:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http.rb:371:in `retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http.rb:335:in `send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http.rb:148:in `request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/http.rb:131:in `post'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/api_client/registration.rb:96:in `create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/api_client/registration.rb:87:in `create_or_update'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/api_client/registration.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/client.rb:620:in `register'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/client.rb:266:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/application.rb:302:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/application.rb:290:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/application.rb:290:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/application.rb:255:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/application.rb:243:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.14.60/bin/chef-client:26:in `<top (required)>'
"/var/chef/cache/chef-stacktrace.out" [noeol] 40L, 4016C    
```

Kindly let me  know what I am doing wrong and if possible how to disable SSL check on my chef-client as I need this setup only for self learning purpose . 

Thanks . 
Ankur Vaish

**Comment by lamont-granquist** [comment]
you probably need to run through `knife ssl check`

https://docs.chef.io/knife_ssl_check.html
http://www.thegeekstuff.com/2016/06/knife-ssl-check-fetch/
http://jtimberman.housepub.org/blog/2014/12/11/chef-12-fix-untrusted-self-sign-certs/

"nested asn1 error" likely means you created the self-signed client cert incorrectly would be my guess.

**Comment by ankurvaish88** [comment]
Hi , Thanks for your response . 

knife ssl check command is returning me a positive output . 

[root@chef-client ~]# knife ssl check
Connecting to host localhost.localdomain:443
Successfully verified certificates from `localhost.localdomain'

but below command returning me error (registering my client with chef-server) -:

[root@chef-client ~]# chef-client -S https://localhost.localdomain -k /etc/chef/trusted_certs/chef-validator.pem
[2016-09-26T14:19:33+05:30] INFO: Forking chef instance to converge...
Starting Chef Client, version 12.14.60
[2016-09-26T14:19:33+05:30] INFO: *** Chef 12.14.60 ***
[2016-09-26T14:19:33+05:30] INFO: Platform: x86_64-linux
[2016-09-26T14:19:33+05:30] INFO: Chef-client pid: 2432

================================================================================
Chef encountered an error attempting to load the node data for "chef-client"
================================================================================

Unexpected Error:
-----------------
OpenSSL::X509::CertificateError: nested asn1 error



Due to which I am unable to register my client . 

Thanks .

**Comment by thommay** [comment]
Does `knife ssl fetch` help the situation? 
Can you do `openssl x509 -in /root/.chef/trusted_certs/localhost.localdomain.crt -noout -text` to make sure the cert is parseable?

**Comment by thommay** [comment]
Hi,
since we've not heard further, we'll be closing this ticket. If you have further information, please feel free to reopen and update.
Thanks!

**Comment by badsector3** [comment]
Hi. I have the same issue. If I use knife to bootstrap a node everything is fine but if I try to bootstrap  node using cmd I am getting the error:
OpenSSL::X509::CertificateError: nested asn1 error

The nginx cert on chef-server was generated as following:
sudo openssl req -subj '/CN=blabla.net/' -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout cert.key -out cert.crt

I tried the suggested command:
openssl x509 -in /etc/chef/trusted_certs/cert.crt -noout -text
Output:
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 0 (0x0)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, O=YouCorp, OU=Operations, CN=blabla.net
        Validity

            Not Before: Apr 10 13:44:07 2017 GMT
            Not After : Apr  8 13:44:07 2027 GMT
        Subject: C=US, O=YouCorp, OU=Operations, CN=blabla.net
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
etc.....

Looks to be fine for me. 
chef-server-core     12.14.0-1
Chef Client, version 12.19.36
Any ideas?

**Comment by badsector3** [comment]
I just signed the SSL cert with GoDaddy. I still have the same issue running the auto-register getting:
DEBUG: Re-raising exception: OpenSSL::X509::CertificateError - nested asn1 error

I can register the node with knife without issue. Any ideas?

**Comment by wojtek-fliposports** [comment]
This problem is not related with certificates by them self but a possible file is not correct CRT file. Make sure that in `/etc/chef/trusted_certs` there are only correct CRT files and remove/move PEM files and others

**Comment by badsector3** [comment]
Thanks wojtek-fliposports. Sorted
