### ISSUE TITLE
user resoure appends a slash at the end of home folder unnecessarily

### ISSUE THREAD

**Issue by kzw** [chef/chef#5388]
## Description

Our usage of user resource for 'home' folder leaves out the trailing `/` but chef automagically adds at the end.  This causes `green` events with every chef client run because our recipe tries to make home folder without trailing slash but chef silently adds a slash at the end; on the next run, chef thinks we have change the home folder and hence the green.
## Chef Version

This has been with us for more than 2 years.  I worked around earlier by adding `/` at the end.  But I recently refactored this code and asked myself why am I adding `/` at the end and removed that slash.  Now my chef client runs are green all the time even for no changes to our chef repo
## Platform Version

ubuntu 12.04
## Replication Case

Deploy 'user' resoure without `/` at the end of home folder and run chef-client more than once.

I looked for some RFC somewhere on `/etc/passwd` format thinking maybe you are following the some standard and did not find it.  I also checked a machine (centos) that is not managed by chef and all folders normally do not have `/` at the end.

This bug is annoying.

**Comment by thommay** [comment]
Can you tell us what version of chef you're using?

**Comment by lamont-granquist** [comment]
So, I certainly have at least one user resource on ubuntu 14.04 which is not getting a trailling slash added:

```
lamont:x:2001:2001:Lamont Granquist:/home/lamont:/bin/zsh
```

and the only thing i can see in the code that might be doing something like this is `Pathname.new(new_resource.user).cleanpath` but I just checked that manually in pry and its not adding slashes, and I think that's only used for an idempotency check as well.

so this would be an annoying bug, but I don't see it (at least not in >= 12.14.x)

**Comment by phene** [comment]
I think this behavior may be triggering [my issue](https://github.com/chef/chef/issues/5444).

**Comment by kzw** [comment]
This problem started on version before 12.3 and I can see it's still happening on 12.5.1 and I believe on 12.9.38

**Comment by phene** [comment]
I [have confirmed](https://github.com/chef/chef/issues/5444#issuecomment-253345620) that this issue is triggering #5444.

**Comment by thommay** [comment]
This should have been fixed by #5452; please can you try an up to date version of chef and confirm. If that's not the case, please feel free to reopen this ticket.
