### ISSUE TITLE
Resource logging is inappropriate if raising exceptions?

### ISSUE THREAD

**Issue by JPvRiel** [chef/chef#5389]
## Description

Using resource logging doesn't play well when intending to raise an exception, related to docs at https://docs.chef.io/resource_log.html. It starts off suggesting to use the log resource first (by first, I interpret this as recommended). The docs do not (at least not clearly that I've seen) explain if it's inappropriate to use the resource log method if you also intend raising an exception (handled or not).

It seems ```Chef::Log.fatal('string')``` should be used instead of the log resource if needing to abort a chef client run with an exception.

Either using the log resource should work in conjunction with needing to raise exceptions, or the docs should warn against it in this scenario.

## Chef Version

Chef Development Kit Version: 0.16.28
chef-client version: 12.12.15

## Platform Version

Ubuntu 16.04 LTS

## Replication Case

Create a simple test.rb recipe
```
log 'message' do
  message('This is fatal!')
  level :fatal
end
raise
```

## Client Output

The exception triggers and exits before the "logging" resource outputs the message?
```
...
       Starting Chef Client, version 12.14.60
...
     Recipe Compile Error in /tmp/kitchen/cache/cookbooks/test/recipes/test.rb
...
      Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/test/recipes/test.rb:
       
         1:  log 'message' do
         2:    message('This is fatal!')
         3:    level :fatal
         4:  end
         5>> raise
         6:  
...
       Running handlers:
       [2016-09-27T23:21:45+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-09-27T23:21:45+00:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 00 seconds
       [2016-09-27T23:21:45+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-09-27T23:21:45+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-09-27T23:21:45+00:00] ERROR: 
       [2016-09-27T23:21:45+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

As the output above shows, the log message was not collected from the log resource before exiting.

## Stacktrace

N/A, above should suffice.

**Comment by coderanger** [comment]
This is due to how Chef works as a two-pass system. You can find more information in https://coderanger.net/two-pass/. `fatal` is just a log level like any other and doesn't actually have any special handling as far as aborting the run. What you probably want instead is the `Chef::Application.fatal!` method. This will both log at the fatal level and raise an exception to end the converge.

**Comment by JPvRiel** [comment]
@coderanger, thanks agree that the misconception may stem from new Chef users not knowing the finer points of compile versus converge steps. I submitted the issue because, in my view, the official documentation is not very clear about which piece of logging to use when and how it ties back to the two-pass system. 

From a guess, ```Chef::Log``` is suited to compile time logging and immediately writing out log messages whereas  ```log 'message' do ...``` is not and if you intentially raise your own exception, you may never see the log message output.

**Comment by coderanger** [comment]
@JPvRiel The issue isn't the logging, it's that Chef's two-pass system takes a while to get used to. Any Ruby code outside of a `ruby_block` happens at compile time, the `log` resources log output happens at converge time. You could also have done this:

```ruby
log 'message' do
  message('This is fatal!')
  level :fatal
end
ruby_block 'killlllll' do
  block do
    raise
  end
end
```
