### ISSUE TITLE
user resource

### ISSUE THREAD

**Issue by cgerke** [chef/chef#5392]
The default behaviour in Mac OS X when creating a user is to give it an interactive login shell '/bin/bash'

Would it not make sense for the chef resource to also do this? By default then, the property is set with a custom string to set a custom shell.

For a non-interactive login shell, the requirement would then be that the system property is set to true.

Would you accept a PR for this?

**Comment by thommay** [comment]
As with the previous ticket, I think this might be a behaviour change that we couldn't accept in chef 12. Ping @mikedodge04 @jaymzh @chef/client-os-x
