### ISSUE TITLE
There is no -M option for useradd on Solaris

### ISSUE THREAD

**Issue by jjustice6** [chef/chef#5403]
## Description

The user resource sets -M as an option on Solaris in some cases.

https://github.com/chef/chef/blob/master/lib/chef/provider/user/solaris.rb#L85  
https://github.com/chef/chef/blob/master/lib/chef/provider/user/useradd.rb#L144

## Chef Version

12.14.17 up

## Platform Version

Solaris 5.11

## Replication Case

```
sundev21 # useradd --help
UX: useradd: ERROR: Invalid syntax.
usage:  useradd [-u uid [-o] | -g group | -G group[[,group]...] |-d dir | -b base_dir |
                -s shell | -c comment | -m [-k skel_dir] | -f inactive |
                -e expire | -A authorization[[,authorization]...] |
                -P profile[[,profile]...] | -R role[[,role]...] |
                -K key=value | -p project[[,project]...] |
                [-S [files | ldap]] login
        useradd -D [-g group | -b base_dir | -f inactive | -e expire
                -A authorization [[,authorization]...] |
                -P profile [[,profile]...] | -R role [[,role]...] |
                -K key=value ... -p project] | [-s shell] | [-k skel_dir]
```
## Client Output

Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '2'

which isn't particularly helpful, but taking the command and running it yourself you can see that the presence of -M is the problem.

**Comment by jjustice6** [comment]
This may tie in to #5371

**Comment by coderanger** [comment]
Does anyone with more solaris knowledge than me grok if there is any way that `-m` would be defaulted on like with Linux? If not, should be easy to remove.

**Comment by lamont-granquist** [comment]
you have to be reasonably careful because of the tight coupling to the AIX class through the base class.

it looks like solaris defaults to `-M`-like behavior and that you have to add `-m` in order to manage_home.

**Comment by coderanger** [comment]
@lamont-granquist Fortunately my fix for the `-r` thing disconnected this in particular from the base class :)

**Comment by lamont-granquist** [comment]
👍

**Comment by jjustice6** [comment]
Agreed with Lamont, it appears that Solaris decided that since they were making `-M` style behavior the default that they simply axed the flag altogether.

**Comment by lamont-granquist** [comment]
More likely the other way around, I doubt Solaris ever had the flag, and it was Linux who decided to allow a configuration option to swap the default, and then needed to add -M to set it back...

Pretty certain Solaris useradd came first and Linux copied it...
