### ISSUE TITLE
bash resource "flags" option not inherited by guards when using guard_interpreter

### ISSUE THREAD

**Issue by causton81** [chef/chef#5416]
## Description

bash resource guards with `guard_interpreter :bash` do not inherit `flags` option. See https://github.com/chef/chef/blob/master/lib/chef/resource/execute.rb#L162-L168

On a fresh `vagrant up` I am installing pyenv such that pyenv is initialized by ~/.profile. I need to set `flags '-l'` so that ~/.profile gets loaded with new pyenv config during that first converge.

It's pretty dirty to use pyenv this way and I should probably just use the python community cookbook to setup the system python, but I thought I'd bring it up since it's confusing to have the `code` part find and run a command that's not supposed to run, then have that command fail for the exact reason that the guard protects against. I used the old trick of 

```
not_if "bash -l -c 'some-command' &>/tmp/guard.out"
```

to diagnose it.
## Chef Version

12.14.89
## Platform Version

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.11 (wheezy)
Release:    7.11
Codename:   wheezy

**Comment by rmoriz** [comment]
related: https://github.com/chef/chef-rfc/blob/master/rfc011-resource-guard.md

**Comment by lamont-granquist** [comment]
Okay so it sounds like flags should inherit through the same mechanism used by powershell_script.

This is probably a breaking change for someone though who has flags which will break their guards.

**Comment by sanga1794** [comment]
Hi, 
We've tried with latest chef but issue is not being reproduced at our end.

```
bash 'bash-test' do
	guard_interpreter :bash
	code "mkdir test"
	flags '-l'
	not_if '[[ 1 < 1 ]]'
end
```

recipe o/p

```
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * bash[bash-test] action run
    - execute "bash" -l "/tmp/chef-script20200401-6443-1447mcq"
```
@lamont-granquist  Please suggest if we need to do anything here?

**Comment by dheerajd-msys** [comment]
Hi @causton81 Please check ^

**Comment by dheerajd-msys** [comment]
@causton81  Closing this issue as it is not reproducible from our end with the latest chef.
Please let us know if there is anything.
