### ISSUE TITLE
remove config[:ssh_password_ng] from knife ssh

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#5425]
config[:ssh_password] should be changed to work like config[:ssh_password_ng] and the latter should be dropped

Chef 13 breaking change.

**Comment by lamont-granquist** [comment]
kind of looks like we should have fixed all the knife plugins here and this will need to slip to Chef-14 because ain't got no time right now to do that...

**Comment by lamont-granquist** [comment]
This may actually be more like "wipe out all the connection stuff in knife ssh / knife bootstrap" due to train.

But knife ssh needs to use the trainified style connection stuff (and should really use train, but we should at least sort out the options)

**Comment by tas50** [comment]
In Chef 15 we renamed ssh-password to connection-password. We should update connection-password to prompt for the password like ssh-password-ng does if no option is provided. Then we can use the knife option deprecation framework to point users to use connection-password instead. This is technically breaking, but it's a security issue and we should just fix it.
