### ISSUE TITLE
Accumulator Patterns as Resources are still Somewhat Unsatisfying

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#5438]
This is the current correct way to write a delayed accumulator as a resource pattern:

```ruby
provides :email_alias
resource_name :email_alias

property :address, String, name: true, identity: true
property :recipients, Array

default_action :create

action :create do
  with_run_context :root do
    nr = new_resource   # break out of the closure over the first call
    edit_resource(:template, "/tmp/aliases") do
      source 'aliases.erb'
      variables[:aliases] ||= {}
      variables[:aliases][nr.address] ||= []
      variables[:aliases][nr.address] += nr.recipients
      action :nothing
    end
  end
  log "force delayed notification" do
    notifies :create, "template[/tmp/aliases]", :delayed
  end
end
```

Two issues here:

1.  the scoping issue is fucking horribly confusing, the first time the resource is created the new_resource is frozen to the email_alias resource that first created it and subsequent calls pick up that resource out of the binding, and not the resource that is currently executing (and this isn't due to a 3694 error, it also has nothing to do with the custom resources scope confusion and happens with LWRPs as well).  And to be clear the binding closure here is not in the edit_resource block that is being created directly but that block is instance_eval'd against the template resource and the template resource has the binding of when it was first created which has a new_resource from the first invocation.

2.  the create-it-with-action-nothing-and-force-a-delayed-notification-via-a-log-resource pattern is mildly awful.  ideally there would be a way to do that when you create the resource so that it sends itself a delayed notification when its first created.... `delayed_action :create`?

**Comment by lamont-granquist** [comment]
The way this is documented with find_resource works better because the block is only passed to the resource when its created, but is slightly less satisfying due to the need to assign the resource to a variable and manipulate it:

```ruby
provides :email_alias
resource_name :email_alias

property :address, String, name: true, identity: true
property :recipients, Array

default_action :create

action :create do
  r = with_run_context :root do
    find_resource(:template, "/tmp/aliases") do
      source 'aliases.erb'
      variables[:aliases] = {}
      action :nothing
    end
  end
  r.variables[:aliases][address] ||= []
  r.variables[:aliases][address] += recipients
  log "force delayed notification" do
    notifies :create, "template[/tmp/aliases]", :delayed
  end
end
```

**Comment by thommay** [comment]
It feels like all this should get sugared into an `accumulated_resource` or something. But yes, agree that we should have a way to trigger a delayed notification automatically.

**Comment by lamont-granquist** [comment]
yeah, someone already went down that road, since its an accumulator pattern from 4 years ago i suspect it has broken use cases inside use_inline_resources-style resources (so all of them now):

https://supermarket.chef.io/cookbooks/accumulator

**Comment by lamont-granquist** [comment]
fixed these issues as much as is possible:

#5441 
#5443 
#5446 

we may need a higher level API to wrap around this, but i want to play with these implementations some more

**Comment by lamont-granquist** [comment]
for my own sake here's the updated way of writing them:

```
provides :email_alias
resource_name :email_alias

property :address, String, name: true, identity: true
property :recipients, Array

default_action :create

action :create do
  with_run_context :root do
    edit_resource(:template, "/tmp/aliases") do |nr|
      source 'aliases.erb'
      variables[:aliases] ||= {}
      variables[:aliases][nr.address] ||= []
      variables[:aliases][nr.address] += nr.recipients
      action :nothing
      delayed_action :create
    end
  end
end
```
