### ISSUE TITLE
Solaris package remove with a source can be broken

### ISSUE THREAD

**Issue by coderanger** [chef/chef#5440]
The current `Chef::Provider::Package::Solaris` (i.e. not IPS) has some funky code so that when you use a `source` property, [it automatically fetches the version of the package from the source](https://github.com/chef/chef/blob/6f2315803b046d07eaef641cb2c427327c32e265/lib/chef/provider/package/solaris.rb#L59). This is correct for install and upgrade actions, but when removing, generally you want to remove the version on the system (if any), not the version in the source. Basically unless I'm mistaken, that block of code linked above needs `if @new_resource.source && (action == :install || action == :upgrade)` I think.

/cc @chef/client-solaris

**Comment by coderanger** [comment]
Also even with that fix, the following code would do weird stuff:

```ruby
solaris_package 'whatever' do
  action [:install, :remove]
end
```

I'm mostly okay with that, but it's still odd.

**Comment by lamont-granquist** [comment]
does the mixin need fixing?

https://github.com/chef/chef/blob/6f2315803b046d07eaef641cb2c427327c32e265/lib/chef/provider/package/solaris.rb#L28

**Comment by coderanger** [comment]
I don't think so, that's just for handling resource names that look like paths as syntactic sugar.

**Comment by coderanger** [comment]
Might also be some other related errors where `-d` is being used incorrectly. Will try to get more info from work peoples but the general feel is that pre-IPS solaris packaging isn't worth much effort. Chef itself is the last thing to upgrade to IPS :) We just worked around this with a `bash` resource for the purposes of the upgrade process.

**Comment by lamont-granquist** [comment]
still kind of feels like this should be common-code to dpkg-ish local-source-style providers?

**Comment by coderanger** [comment]
I think the difference is that `pkgadd` doesn't install directly from the source, it just adds it as a "temp repo" or something? So you have to both specify the source and then make sure it's actually what you are installing. I'm mostly reverse engineering my knowledge of this from the existing code though.
