### ISSUE TITLE
ohai mount size bug with duplicate mount points

### ISSUE THREAD

**Issue by vncntvandriessche** [chef/chef#5442]
## Description

If a filesystem is mounted multiple times (cfr. with Docker):

```bash
root@git-004:~# mount | grep vda2
/dev/vda2 on / type ext4 (rw,relatime,data=ordered,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group)
/dev/vda2 on /var/lib/docker/299151.299151/aufs type ext4 (rw,relatime,data=ordered,jqfmt=vfsv0,usrjquota=aquota.user,grpjquota=aquota.group)
```

only the first of those duplicate mount points will get usage stats: [ohai/filesystem.rb#L86](https://github.com/chef/ohai/blob/80c91e74ac403959d54c9f15b1aa7a3c4fc4bd8b/lib/ohai/plugins/linux/filesystem.rb#L86)
(in master):  [filesystem.rb#L92](https://github.com/chef/ohai/blob/master/lib/ohai/plugins/linux/filesystem.rb#L92)

```ruby
node.filesystem.select do |k,v|
  v["mount"] == "/" && v["kb_size"]
end.values.first["kb_size"]
```
and other attributes will get mixed.

## Chef Version

12.12.15

## Platform Version

Description:    Debian GNU/Linux 8.2 (jessie)

## Replication Case

Set up an instance managed with chef
Install docker-daemon using chef
Start a container: `docker run --name some-mariadb -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mariadb`
Run chef with a recipe containing:

```ruby
node.filesystem.select do |k,v|
  v["mount"] == "/" && v["kb_size"]
end.values.first["kb_size"]
```

### Example chai output

```json
{
  "/dev/vda2": {
    "kb_size": "82341228",
    "kb_used": "50379892",
    "kb_available": "28392816",
    "percent_used": "64%",
    "mount": "/var/lib/docker/299151.299151/aufs",
    "total_inodes": "5222400",
    "inodes_used": "799398",
    "inodes_available": "4423002",
    "inodes_percent_used": "16%",
    "fs_type": "ext4",
    "mount_options": [
      "rw",
      "relatime",
      "data=ordered",
      "jqfmt=vfsv0",
      "usrjquota=aquota.user",
      "grpjquota=aquota.group"
    ]
  },

<................>

  "vda2": {
    "fs_type": "ext4",
    "uuid": "cc42b060-4483-4413-8d84-c16b197fa3ce"
  },
  "rootfs": {
    "mount": "/",
    "fs_type": "rootfs",
    "mount_options": [
      "rw"
    ]
  }
}
```

### NOTE: CHEF CLIENT BUGS ONLY

We install chef using the omnibus installer, according to [this issue](https://github.com/chef/ohai/issues/880) at `ohai` this should be fixed using the `filesystem2` plugin.
Any thoughts on getting this bundled into the omnibus-installer by default?

**Comment by thommay** [comment]
The filesystem2 plugin is included - you need to do `node.filesystem2` rather than `node.filesystem`.  When we release chef13 we'll be able to remove the filesystem plugin and replace it with filesystem2 but until then we can't.
I'm going to close this since this is an ohai issue rather than a chef one.

**Comment by vncntvandriessche** [comment]
@thommay Thank you so much for this clear answer, we'll implement it as you have suggested.

Sorry to have bothered you for a non-issue ;)
