### ISSUE TITLE
Release chef-config 12.15.19

### ISSUE THREAD

**Issue by jonathanmorley** [chef/chef#5449]
## Description

I am getting the following error when I have a gem dependency on chef

```
ERROR:  Could not find a valid gem 'chef-config' (= 12.15.19) in any repository
```

**Comment by coderanger** [comment]
This probably means the 12.15 release is in progress, it will be fixed shortly. It's hard to do every single push simultaneously.

**Comment by jonathanmorley** [comment]
That would make sense, but 12.15.19 was released 5 days ago according to the changelog

**Comment by coderanger** [comment]
It was built 5 days ago, the release to stable channel/rubygems/etc is a separate step that happens after a lot of testing.
