### ISSUE TITLE
Using a Template Resource in an Accumulator using `with_run_context :root` gets the cookbook_name wrong sometimes

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#5454]
Seems we're picking up the cookbook_name from the root run_context sometimes and looking for the template source in the calling cookbook, not the cookbook_name the resource was in.

Workaround looks something like this (from the ssh_known_hosts cookbook):

```
  r = with_run_context :root do
    # XXX: remove log resource once delayed_actions lands in compat_resource
    find_resource(:log, 'force delayed notification') do
      notifies :create, 'template[update ssh known hosts file]', :delayed
    end
    find_resource(:template, 'update ssh known hosts file') do
      source "ssh_known_hosts.erb"
      path node['ssh_known_hosts']['file']
      owner new_resource.owner
      group new_resource.group
      mode new_resource.mode
      action :nothing
      backup false
      variables(entries: [])
    end
  end

  # messing with the run_context appears to cause issues with the cookbook_name
  r.cookbook_name = "ssh_known_hosts"
```

**Comment by awolde** [comment]
Whats the eta on this, I landed on this after a lot of googling. I have it like this in a custom resource  cookbook I'm writing.

```
action :create do
  r = with_run_context :root do 
    edit_resource(:template, 'update config file' ) do
      source "#{process}.erb"
      path cfg_file
      mode '0644'
      variables( here: )
    end
  end
r.cookbook_name = "new_custom_resource"
end
```

Errors out saying `undefined method cookbook_name=' for ["calling_cookbook"]:Array`
If I comment `r.cookbook_name` section, the same problem where it cannot find the template files in the calling cookbook.

**Comment by coderanger** [comment]
@awolde Put `self.cookbook_name = "new_custom_resource"` inside the edit_resource block.

**Comment by awolde** [comment]
putting in `cookbook = 'new_custom_resource'` inside the edit_resource block worked.

**Comment by lamont-granquist** [comment]
wonder if this isn't another scoping issue like in #5438
