### ISSUE TITLE
ssh: ed25519 support

### ISSUE THREAD

**Issue by rmoriz** [chef/chef#5461]
Chef relies on an old `net-ssh` version that does not support `ed25519` keys.

https://wiki.archlinux.org/index.php/SSH_keys#Ed25519

**Comment by lamont-granquist** [comment]
We're using net-ssh 3.2.0 which is the last stable release.  4.0.0 is still "4.0.0.beta3"

When 4.0.0 stable drops then you should submit a PR to bump the constraint.
