### ISSUE TITLE
chef-solo logs error and cancels recipe run when creating directory on remote node

### ISSUE THREAD

**Issue by gwhorley** [chef/chef#5470]
## Description
When I try to provision a Windows VM through Vagrant using the `:chef_solo` provider, an error is thrown after the Chef client starts and chef-zero attempts to create a directory on the VM:
```
==> windows2k12: [2016-10-18T22:49:14-07:00] INFO: HTTP Request Returned 500 Internal Server Error: error
==> windows2k12: 
==> windows2k12: ================================================================================
==> windows2k12: Chef encountered an error attempting to load the node data for "vagrant-ea2b491d"
==> windows2k12: ================================================================================
==> windows2k12: 
==> windows2k12: Unknown Server Error:
==> windows2k12: ---------------------
==> windows2k12: The server had a fatal error attempting to load the node data.
==> windows2k12: 
==> windows2k12: Server Response:
==> windows2k12: ----------------
==> windows2k12: Exception raised! ERROR: #<Errno::EINVAL: Invalid argument @ dir_s_mkdir - C:/"absolute_path_of_local_directory_where_vagrant_is_run"C:/vagrant-chef/nodes>
```

## Chef Version

12.15.19

## Platform Version

Tried on Windows Server 2008 R2 and Windows Server 2012 R2 VMs

## Replication Case

I have never tried to run chef-zero or chef-solo commands manually, so my steps will involve the latest version of `vagrant` as well as the latest version of vagrant plugins `vagrant-omnibus` `vagrant-berkshelf` and `vagrant-vsphere`.

1. Create Vagrantfile that has configuration for one windows VM that is created through `:vsphere` provider
1. Add `config.berkshelf.enabled = true` 
1. Add block for `config.vm.provision :chef_solo do |chef|` that contains one recipe in `chef.run_list`
1. Create Berksfile in same directory as Vagrantfile that contains `source http://url_to_public_supermarket` and `cookbook name_of_cookbook_in_run_list`
1. Run `vagrant up`

## Client Output

https://gist.github.com/gwhorley/8c5e3c96389b19d81d89a372af4758e5

## Stacktrace

https://gist.github.com/gwhorley/8c5e3c96389b19d81d89a372af4758e5

**Comment by thommay** [comment]
This doesn't look like a chef bug: `C:/"absolute_path_of_local_directory_where_vagrant_is_run"C:/vagrant-chef/node` looks like a vagrant configuration problem. 
Feel free to reopen if that's not the case.
