### ISSUE TITLE
Not able to upload cookbook

### ISSUE THREAD

**Issue by scshitole** [chef/chef#5484]
## Description

Briefly describe the issue
Not able to upload cookbook from Work station
## Chef Version 12.15

Tell us which version of chef-client you are using (see below for Server+ChefDK bugs).
## Platform Version

Tell us which Operating System distribution and version chef-client is running on.
## Replication Case

SJC-ML-SHITOLE:f5-learn shitole$ knife cookbook upload  f5-learn
ERROR: Could not find cookbook f5-learn in your cookbook path, skipping it
Uploaded 0 cookbook.
SJC-ML-SHITOLE:f5-learn shitole$ 
SJC-ML-SHITOLE:f5-learn shitole$ 
SJC-ML-SHITOLE:f5-learn shitole$ 
SJC-ML-SHITOLE:f5-learn shitole$ pwd
/Users/shitole/chef-repo/cookbooks/f5-learn
SJC-ML-SHITOLE:f5-learn shitole$ ls
Berksfile   Vagrantfile chefignore  files       metadata.json   recipes     test
README.md   attributes  definations libraries   metadata.rb spec
SJC-ML-SHITOLE:f5-learn shitole$ cd ..
SJC-ML-SHITOLE:cookbooks shitole$ ls
chefignore      dummy           f5-bigip        f5-bigip-0.5.2.tar.gz   f5-learn        learn_chef_apache2  starter
SJC-ML-SHITOLE:cookbooks shitole$ 

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.
## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

SJC-ML-SHITOLE:f5-learn shitole$ knife cookbook upload  f5-learn
ERROR: Could not find cookbook f5-learn in your cookbook path, skipping it
Uploaded 0 cookbook.
SJC-ML-SHITOLE:f5-learn shitole$ 
SJC-ML-SHITOLE:f5-learn shitole$ 
SJC-ML-SHITOLE:f5-learn shitole$ 
SJC-ML-SHITOLE:f5-learn shitole$ pwd
/Users/shitole/chef-repo/cookbooks/f5-learn
SJC-ML-SHITOLE:f5-learn shitole$ ls
Berksfile   Vagrantfile chefignore  files       metadata.json   recipes     test
README.md   attributes  definations libraries   metadata.rb spec
SJC-ML-SHITOLE:f5-learn shitole$ cd ..
SJC-ML-SHITOLE:cookbooks shitole$ ls
chefignore      dummy           f5-bigip        f5-bigip-0.5.2.tar.gz   f5-learn        learn_chef_apache2  starter
SJC-ML-SHITOLE:cookbooks shitole$ 

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.
## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.
### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.
- [Server issues](https://github.com/chef/chef-server/issues/new)
- [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
- Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by tduffield** [comment]
What happens if you run the `knife cookbook upload` command from the `chef-repo` directory?

**Comment by thommay** [comment]
Hi,
this looks like a local problem rather than a chef bug, and we'll be closing this issue. 
For problems like this, we strongly recommend asking our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).
