### ISSUE TITLE
Knife failing with OpenSSL error on Windows

### ISSUE THREAD

**Issue by JHBoricua** [chef/chef#5507]
## Description
 Resubmitting issue because previous submission was incorrectly dismissed as a "How do I..." question.

Knife commands are failing with the following error on a clean install of the latest Chef Development kit for Windows:

ERROR: OpenSSL::OpenSSLError: This version of OpenSSL does not support FIPS mode

## Chef Version

Chef Development Kit Version: 0.19.6
chef-client version: 12.15.19
delivery version: master (802e801d920ea6b6d48db735aa7c6e7a6194bea4)
berks version: 5.1.0
kitchen version: 1.13.2

## Platform Version

Microsoft Windows 10 workstation with chef-client 12.15.19 installed from chefdk-0.19.6-1-x86.msi package.

## Replication Case

1. Install Chef DK on windows 10 workstation with default options.
2. launch Chef DK.
4. cd to chef-repo directory.
5. perform ANY knife command

## Client Output
Examples:
PS G:\chef-repo> knife ssl fetch
ERROR: OpenSSL::OpenSSLError: This version of OpenSSL does not support FIPS mode

PS G:\chef-repo> knife ssl check
ERROR: OpenSSL::OpenSSLError: This version of OpenSSL does not support FIPS mode

PS G:\chef-repo> knife cookbook list
ERROR: OpenSSL::OpenSSLError: This version of OpenSSL does not support FIPS mode

Chef-client debug output:

PS G:\chef-repo> chef-client -l debug
[2016-11-02T11:22:32-05:00] WARN: *****************************************
[2016-11-02T11:22:32-05:00] WARN: Did not find config file: C:/chef/client.rb, using command line options.
[2016-11-02T11:22:32-05:00] WARN: *****************************************
C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-config-12.15.19/lib/chef-config/config.rb:1041:in `fips_mode=': This version of OpenSSL does not support FIPS mode (OpenSSL::OpenSSLError)
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-config-12.15.19/lib/chef-config/config.rb:1041:in `enable_fips_mode'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-config-12.15.19/lib/chef-config/config.rb:538:in `init_openssl'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:89:in `configure_chef'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:49:in `reconfigure'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application/client.rb:313:in `reconfigure'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/lib/chef/application.rb:58:in `run'
        from C:/opscode/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.15.19-universal-mingw32/bin/chef-client:26:in `<top (required)>'
        from C:/opscode/chefdk/modules/chef/../../bin/chef-client:68:in `load'
        from C:/opscode/chefdk/modules/chef/../../bin/chef-client:68:in `<main>'

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by thommay** [comment]
Hi,
this doesn't look like a chef bug, which is why I asked you to post to discourse. FIPS mode is not enabled by default on any platform, but requires configuration to enable it.
Is your Windows 10 install provided by your IT department? Does it have the registry key `System\CurrentControlSet\Control\Lsa\FIPSAlgorithmPolicy` , and if so, does that registry include Enabled=1?

**Comment by JHBoricua** [comment]
The key exists and it is enabled on my system.

**Comment by tpetchel** [comment]
@JHBoricua, can you try appending the `--no-fips` flag to your `knife` command?

https://docs.chef.io/knife_common_options.html

**Comment by JHBoricua** [comment]
That seems to work and I got my list of recipes. Is that mandatory on windows workstations using the development kit?

**Comment by tpetchel** [comment]
No, it's not a standard requirement for Windows. You need it only because you have FIPS mode enabled.

If you're interested in trying this out, can you add the line `fips false` to your `knife.rb` file and see if you can run `knife` commands without the `--no-fips` flag? 

https://docs.chef.io/config_rb_knife.html

**Comment by tpetchel** [comment]
Closing since this is not tracking a bug or feature request. @JHBoricua, I'm happy to chat more on the Disqus thread if you have additional questions. Or reach out to the community using the link posted in #5506.
