### ISSUE TITLE
Upstart provider only supports the start and stop states

### ISSUE THREAD

**Issue by RyanJarv** [chef/chef#5513]
## Description

The regex to check for states in the Upstart provider only looks for start and stop.

https://github.com/chef/chef/blob/9d09f9e23db45eaf71bc9421507a25fccac1293b/lib/chef/provider/service/upstart.rb#L36

If the service is in any other state it will raise the following error:

        NoMethodError
        -------------
        undefined method `[]' for nil:NilClass

at

https://github.com/chef/chef/blob/9d09f9e23db45eaf71bc9421507a25fccac1293b/lib/chef/provider/service/upstart.rb#L253

## Chef Version

chef-client: 12.15.19

## Platform Version

Ubuntu 14.04

## Replication Case

https://github.com/RyanJarv/chef_upstart_bug

**Comment by RyanJarv** [comment]
Don't know much about upstart and not sure how often this is actually an issue may be fine just to document it and raise an error with a better description.

**Comment by navkumar2245** [comment]
can i work on this issue if it is not fixed yet?

**Comment by tas50** [comment]
@navkumar2245 You're more than welcome to work on this issue. Since Ubuntu 14.04 is just about EOL at this point this won't be something we'll tackle internally at Chef.
