### ISSUE TITLE
Node assignment of node objects should deep-dup in convert_value

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#5520]
Potentially breaking edge conditions that need fixing in Chef 16:

- ~~#to_hash should deep-dup strings and other data:  https://github.com/chef/chef/blob/master/spec/unit/node/attribute_spec.rb#L462-L470~~ (Done)
- assignment should always deep-dup via convert_value, even assigning node objects to node objects to avoid duplication in the tree:    discussion in https://github.com/chef/chef/pull/5378#issuecomment-249382290 and i've come around to the view that we should be consistent in duping objects on assignment.

**Comment by lamont-granquist** [comment]
This is a good example of stuff that needs to change in a major release but is nearly impossible to submit a deprecation warning about.

**Comment by lamont-granquist** [comment]
first half done by #5896

**Comment by sandstrom** [comment]
Thanks for a great piece of software! 🏅 

Another issue (that I'm sure you've heard before) is that `nil` isn't treated as a value. Basically, when `nil` values are used inheritance doesn't work as expected. Using `false` is a workaround, but personally I think it would be great if `nil` worked too.

I think this is the relevant line (but not sure):
https://github.com/chef/chef/blob/97f5d8d8/lib/chef/mixin/deep_merge.rb#L125

**Comment by lamont-granquist** [comment]
good time to remind me.

that mixin is no longer used by the attributes code, and i think the code that needs to get removed is here:

https://github.com/chef/chef/blob/97f5d8d882d027aa2662c5b015c09184f4c564a7/lib/chef/node/attribute.rb#L595-L597

**Comment by lamont-granquist** [comment]
or not...  that blows up horribly...

**Comment by lamont-granquist** [comment]
#7892 fixes the nil behavior for Chef-15.

**Comment by sandstrom** [comment]
@lamont-granquist Awesome! 🎉 🇸🇪

**Comment by lamont-granquist** [comment]
looks like strings are deep-dup'd now by `#to_hash`

```
[10] pry(main)> n.default["foo"]["bar"].object_id
=> 70281180379760
[11] pry(main)> n.to_hash["foo"]["bar"].object_id
=> 70281310416320
```

But it looks like object assignment of node objects does not dup:

```
[12] pry(main)> n.default["quux"] = n.default["foo"]
=> {"bar"=>"baz"}
[14] pry(main)> n.default["foo"]["bar"].object_id
=> 70281180379760
[15] pry(main)> n.default["quux"]["bar"].object_id
=> 70281180379760
[16] pry(main)> n.default["quux"].object_id
=> 70281180380680
[17] pry(main)> n.default["foo"].object_id
=> 70281180380680
```

And this means assignment is wonky with spooky action at a distance after assignment:

```
[18] pry(main)> n.default["foo"]["fizz"] = "buzz"
=> "buzz"
[19] pry(main)> n["quux"]
=> {"bar"=>"baz", "fizz"=>"buzz"}
```

Of course if you round trip it though (through the chef-server) then the identical object will be lost and behavior will be different the second time through.

Still needs fixing on 15.4.54

**Comment by lamont-granquist** [comment]
This probably should get done, but TBH we haven't seen this issue come up with customers.  My assigning critical priority to this was mostly around anything node attributes being critical in my brain, but this is such an edge condition of an edge condition I think it may be better marked as low.
