### ISSUE TITLE
Output from `client.rb` doesn't get logged to the log file.

### ISSUE THREAD

**Issue by zfjagann** [chef/chef#5526]
## Description

Output from `client.rb` doesn't get logged to the log file.

Clearly this isn't an easy fix, since the `client.rb` file contains details about what log file you'd like chef to log to.

What I'd like to do is setup a logger before `client.rb` is executed, and encourage people to use this logger for meaningful messages originating in `client.rb`.
The logger will be responsible for writing any messages to stdout as per the current behavior, as well as saving them.
Once the `client.rb` file is executed and the actual chef logger initialized, the saved log messages can be written to the log file normally.

## Chef Version

```
$ chef --version
Chef Development Kit Version: 0.17.17
chef-client version: 12.13.37
delivery version: master (f68e5c5804cd7d8a76c69b926fbb261e1070751b)
berks version: 4.3.5
kitchen version: 1.11.1
```

## Platform Version

Arch linux, centos7

## Replication Case

```
$ cat client.rb
cookbook_path ['/home/zeal/dev/pub/chef-pub/cookbooks']

puts 'Inside client.rb'
$ cat cookbooks/sample/recipes/default.rb
log 'Inside chef' do
  level :warn
end
$ cat run_list.json
{
  "run_list": [
    "recipe[sample]"
  ]
}
```

Run chef with: `chef-client -z -j run_list.json -c client.rb --logfile chef.log -F null`

## Client Output

```
$ chef-client -z -j run_list.json -c client.rb --logfile chef.log -F null
Inside client.rb
```

```
$ cat chef.log
# Logfile created on 2016-11-07 15:10:15 -0800 by logger.rb/44203
[2016-11-07T15:10:17-08:00] WARN: Inside chef
# Logfile created on 2016-11-07 15:10:15 -0800 by logger.rb/44203
```

**Comment by jaymzh** [comment]
I like this idea ( @zfjagann  and I discussed it before he wrote it up ) - the question I have is, does this require an RFC before he takes a whack at doing it? The border is fuzzy to me. CC @thommay  and @lamont-granquist

**Comment by coderanger** [comment]
This seems broad enough that an RFC would be called for. Not sure if this is a thing we should encourage though, feels off putting for reasons I can't really quantify. Feels very foot-gun-y but that alone isn't a reason to not do it.

**Comment by lamont-granquist** [comment]
It seems reasonably fine as long as you're aware of the sharp edges.  I wonder if it would be possible to have a callback fire any time the logger was set via either the CLI or in config or anywhere else in the codebase to reinitialize the class?  Probably too much of a stretch goal, but it would make the code flow a little better.  If you get down to fighting with when the CLI options are parsed vs when the config file is parsed thats more when I'd throw the brakes on the idea -- right now I've had insufficient caffeine to recall if existing parse order supports this use case or not.

**Comment by zfjagann** [comment]
[Created an RFC](https://github.com/chef/chef-rfc/pull/237)
