### ISSUE TITLE
Unable to run command 'chef-server-ctl install chef-manage' while installing chefserver 'chef-server-core-12.5.0-1.el7.x86_64.rpm'

### ISSUE THREAD

**Issue by lovetobeamit** [chef/chef#5535]
I downloaded Chef server for RHEL7 and installing it by following steps as mentioned in  https://docs.chef.io/release/server_12-5/install_server.html
My RPM name is:  chef-server-core-12.5.0-1.el7.x86_64.rpm
When I run the command:  chef-server-ctl install chef-manage

I am getting error:  STDERR: yum-dump Repository Error: failure: repodata/repomd.xml from chef-stable: [Errno 256] No more mirrors to try.
https://packagecloud.io/chef/stable/el/7/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

I think the URL mentioned above is inactive URL. Please suggest the workaround.

**Comment by thommay** [comment]
Hi,
this tracker is for issues in the chef-client. For bugs in chef-server, please use https://github.com/chef/chef-server/issues ; in this case however this problem is fixed in more recent releases of the chef-server and I'd strongly advise you to upgrade.
I'll be closing this issue now.
Thanks!
