### ISSUE TITLE
Bootstrapping from within Node error 

### ISSUE THREAD

**Issue by dbclkclk** [chef/chef#5537]
## Description
Bootstrapping node without knife. Bootstrapping is happening directly on node. 

## Chef Version
     sudo chef-client -v 
     Chef: 12.15.19

## Platform Version
     Mac OSX Sierra 

## Replication Case

* Download validator key and place withing `/etc/chef` directory
* create client.rb within `/etc/chef` directory
* run `chef-client` from the command line

### I removed the pem verbose key from the debug log below

> [2016-11-11T16:49:24-04:00] DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
> [2016-11-11T16:49:24-04:00] DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
> [2016-11-11T16:49:24-04:00] DEBUG: Initiating POST to https://api.chef.io/organizations/techstack/clients
> [2016-11-11T16:49:24-04:00] DEBUG: ---- HTTP Request Header Data: ----
> [2016-11-11T16:49:24-04:00] DEBUG: Content-Type: application/json
> [2016-11-11T16:49:24-04:00] DEBUG: Accept: application/json
> [2016-11-11T16:49:24-04:00] DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
> [2016-11-11T16:49:24-04:00] DEBUG: X-Ops-Server-API-Version: 0
> [2016-11-11T16:49:24-04:00] DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.1;
> [2016-11-11T16:49:24-04:00] DEBUG: X-OPS-USERID: techstack
> [2016-11-11T16:49:24-04:00] DEBUG: X-OPS-TIMESTAMP: 2016-11-11T20:49:24Z
> [2016-11-11T16:49:24-04:00] DEBUG: X-OPS-CONTENT-HASH: 5mIxeW9Zm2qjZPzKwXOCkN4P1C4=
> [2016-11-11T16:49:24-04:00] DEBUG: X-OPS-AUTHORIZATION-1: AUL7/zIRHiAVXraB3dqP0oG/67n/MkY4LUJGNR+iEtGb2xfxoxaBxIdHYDU5
> [2016-11-11T16:49:24-04:00] DEBUG: X-OPS-AUTHORIZATION-2: kDlNOT+uNnULemSnAOTBb4kwWf2Kaz3+P90SMsiOrS5NiatR3afYlyNRgafe
> [2016-11-11T16:49:24-04:00] DEBUG: X-OPS-AUTHORIZATION-3: MehtV1BTuUr9WZuKo4R9/YiKrphwoSsLSK1iLBetfWlJCeFRoF+ov22NzORh
> [2016-11-11T16:49:24-04:00] DEBUG: X-OPS-AUTHORIZATION-4: B2irtcI3rcGLeyz2meT2RfFK6v2q9xZmXL9ymU4Y4jsZXUtnDB40cwEsXgka
> [2016-11-11T16:49:24-04:00] DEBUG: X-OPS-AUTHORIZATION-5: LvHm+bjHbwrulDKuDytuU7LwLZGGYPDSVMWTnEbkf3oZUQJLdWB/B6oWNVXW
> [2016-11-11T16:49:24-04:00] DEBUG: X-OPS-AUTHORIZATION-6: icG54lhDhyptGDs2ryhRDVGmc/Srx8Ew7X0qJYToLA==
> [2016-11-11T16:49:24-04:00] DEBUG: HOST: api.chef.io:443
> [2016-11-11T16:49:24-04:00] DEBUG: X-REMOTE-REQUEST-ID: 3df2b364-f9cf-45aa-8d74-835e607d8399
> [2016-11-11T16:49:24-04:00] DEBUG: Content-Length: 505
> [2016-11-11T16:49:24-04:00] DEBUG: ---- End HTTP Request Header Data ----
> [2016-11-11T16:49:25-04:00] DEBUG: ---- HTTP Status and Header Data: ----
> [2016-11-11T16:49:25-04:00] DEBUG: HTTP 1.1 401 Unauthorized
> [2016-11-11T16:49:25-04:00] DEBUG: date: Fri, 11 Nov 2016 20:49:25 GMT
> [2016-11-11T16:49:25-04:00] DEBUG: server: openresty/1.9.7.2
> [2016-11-11T16:49:25-04:00] DEBUG: www-authenticate: X-Ops-Sign version="1.0" version="1.1"
> [2016-11-11T16:49:25-04:00] DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=12.8.0+20160829163122
> [2016-11-11T16:49:25-04:00] DEBUG: x-ops-server-api-version: {"min_version":"0","max_version":"1","request_version":"0","response_version":"0"}
> [2016-11-11T16:49:25-04:00] DEBUG: content-length: 107
> [2016-11-11T16:49:25-04:00] DEBUG: connection: Close
> [2016-11-11T16:49:25-04:00] DEBUG: ---- End HTTP Status/Header Data ----
> [2016-11-11T16:49:25-04:00] DEBUG: ---- HTTP Response Body ----
> [2016-11-11T16:49:25-04:00] DEBUG: {"error":["Failed to authenticate as 'techstack'. Ensure that your node_name and client key are correct."]}
> [2016-11-11T16:49:25-04:00] DEBUG: ---- End HTTP Response Body -----
> [2016-11-11T16:49:25-04:00] DEBUG: ---- HTTP Request Body ----
> [2016-11-11T16:49:25-04:00] DEBUG: {"name":"dean","admin":false,"public_key":"-----BEGIN PUBLIC KEY-----\nblah blah blha blah\n-----END PUBLIC KEY-----\n"}
> [2016-11-11T16:49:25-04:00] DEBUG: ---- End HTTP Request Body ----
> [2016-11-11T16:49:25-04:00] DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
> [2016-11-11T16:49:25-04:00] DEBUG: Content-Length validated correctly.
> [2016-11-11T16:49:25-04:00] DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
> [2016-11-11T16:49:25-04:00] DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
> [2016-11-11T16:49:25-04:00] DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
> [2016-11-11T16:49:25-04:00] DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
> [2016-11-11T16:49:25-04:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
> [2016-11-11T16:49:25-04:00] DEBUG: Expected JSON response, but got content-type ''
> [2016-11-11T16:49:25-04:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
> [2016-11-11T16:49:25-04:00] INFO: HTTP Request Returned 401 Unauthorized: error
> 
> ================================================================================
> Chef encountered an error attempting to create the client "dean"
> ================================================================================
> 
> Authentication Error:
> ---------------------
> Failed to authenticate to the chef server (http 401).
> 
> Server Response:
> ----------------
> Failed to authenticate as 'techstack'. Ensure that your node_name and client key are correct.
> 
> Relevant Config Settings:
> -------------------------
> chef_server_url         "https://api.chef.io/organizations/techstack"
> validation_client_name  "techstack"
> validation_key          "/etc/chef/techstack-validator.pem"
> 
> If these settings are correct, your validation_key may be invalid.

     

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
