### ISSUE TITLE
Change in Chef::Node::ImmutableArray syntax between 12.15.19 and 12.16.42

### ISSUE THREAD

**Issue by pwalz** [chef/chef#5538]
## Description

There seems to have been a change in how Chef::Node::ImmutableArrays behave between chef-client 12.15.19 and 12.16.42 - basically, using Ruby's `array_name[start_index, number_of_elements]` syntax to retrieve a portion of the array no longer works properly. I get an `ArgumentError` stating `wrong number of arguments (given 2, expected 1)`.

Can you shed any light on whether I'm doing something wrong or whether this was an unintended change with 12.16.42?

## Chef Version

12.16.42

## Platform Version

Ubuntu 16.04, although the problem is not specific to a platform or version

## Replication Case

I've uploaded a test cookbook that demonstrates the problem I'm seeing. It has a test-kitchen config that exercises the cookbook under both 12.15.19 and 12.16.42: https://github.com/pwalz/broken_arrays

Here's a stripped-down example - assume `node['server_list']` is an array with at least one element:

```
server_list = node['server_list']
new_server_list = server_list[0, server_list.length]
```

No, it doesn't accomplish anything useful, other than trigger an error under 12.16.42. The example cookbook uses this syntax in a more productive way.

## Client Output

See https://gist.github.com/pwalz/c63ebf80db8b15082812f77613005f57

## Stacktrace

``` ================================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/broken_arrays/recipes/default.rb
       ================================================================================
       
       ArgumentError
       -------------
       wrong number of arguments (given 2, expected 1)
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/broken_arrays/recipes/default.rb:8:in `randomize_list'
         /tmp/kitchen/cache/cookbooks/broken_arrays/recipes/default.rb:25:in `from_file'
       
       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/broken_arrays/recipes/default.rb:
       
         1:  def randomize_list(server_list)
         2:    num_servers = server_list.length
         3:  
         4:    # Pick a "random" server to be listed first.
         5:    # Needs to be deterministic so we're not constantly rearranging the resulting list.
         6:    start = node['macaddress'].split(":")[5].hex.to_i.modulo(num_servers)
         7:  
         8>>   new_server_list = server_list[start, num_servers - start] + server_list[0, start]
         9:    pp "new_server_list:", new_server_list
        10:  end
        11:  
        12:  puts "\n######################################################################\n"
        13:  puts "Explicit single-element array - always works\n"
        14:  
        15:  randomize_list( %w( server1 ) )
        16:  
        17:  puts "\n######################################################################\n"
       
       Platform:
       ---------
       x86_64-linux
```

(It's also in the client output gist referenced above.)

**Comment by lamont-granquist** [comment]
Thanks for the repro case, fix is about to get merged in #5541
