### ISSUE TITLE
knife help environment shows wrong example

### ISSUE THREAD

**Issue by cakuzo** [chef/chef#5558]
## Description

`knife help environment` shows following example
> Examples
>        To add an environment using data contained in a JSON file:
>           $ knife environment create devops from file "path to JSON file"

[knife-environment.1](https://github.com/chef/chef/blob/db57131ad383076391b9df32d5e9989cfb312d58/distro/common/man/man1/knife-environment.1#L375)

should be
`knife environment from file "path to JSON file"`

## Chef Version
chef-12.14.77-1.el7.x86_64

## Platform Version

RHEL7

## Replication Case

`knife help environment`

search for the following string

`/environment create devops from file`

**Comment by btm** [comment]
Closed by #5684
