### ISSUE TITLE
Backups created by chef-server-ctl backup command cannot be restored after version 12.9.1-1.

### ISSUE THREAD

**Issue by chengepaul** [chef/chef#5566]
## Description

Backups created by chef-server-ctl backup command cannot be restored after version 12.9.1-1.

## Chef Version
Backup and restore do not work with the latest versions.

12.11.1-1 
12.11.0-1  
12.10.0-1  

## Platform Version
Ubuntu 14.04

Tell us which Operating System distribution and version chef-client is running on.
~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.4 LTS"

Chef-server-core - standalone version

## Replication Case
1. install chef-server-core with version 12.11.1-1
2. chef-server-ctl reconfigure
3. chef-server-ctl backup -y
4. chef-server-ctl restore -c chef-backup.tgz

## Stacktrace

Expanding tarball: /var/opt/chef-backup/chef-backup-2016-11-11-01-06-52.tgz
Restoring Chef Server from backup
Cleaning up any old files
    *******************************************************************
    * * * * * * * * * * *       STOP AND READ       * * * * * * * * * *
    *******************************************************************
    This command will delete *all* local configuration, log, and
    variable data associated with Chef Server.

    You have 60 seconds to hit CTRL-C before configuration,
    logs, and local data for this application are permanently
    deleted.
    *******************************************************************

ok: down: bookshelf: 0s, normally up
ok: down: nginx: 0s, normally up
ok: down: oc_bifrost: 1s, normally up
ok: down: oc_id: 0s, normally up
ok: down: opscode-chef-mover: 1s, normally up
ok: down: opscode-erchef: 0s, normally up
ok: down: opscode-expander: 1s, normally up
ok: down: opscode-solr4: 0s, normally up
ok: down: postgresql: 0s, normally up
ok: down: rabbitmq: 1s, normally up
ok: down: redis_lb: 0s, normally up
bookshelf disabled, not stopping
nginx disabled, not stopping
oc_bifrost disabled, not stopping
oc_id disabled, not stopping
opscode-chef-mover disabled, not stopping
opscode-erchef disabled, not stopping
opscode-expander disabled, not stopping
opscode-solr4 disabled, not stopping
postgresql disabled, not stopping
rabbitmq disabled, not stopping
redis_lb disabled, not stopping
Terminating processes running under application users. This will take a few seconds.
Your config files have been backed up to /root/opscode-cleanse-2016-11-11T01:10.
[ERROR] no implicit conversion of nil into String

**Comment by thommay** [comment]
Hi,
this repository is for the chef client, not the chef server. Please file this bug at https://github.com/chef/chef-server/issues/new .
Thanks
