### ISSUE TITLE
Incorrect warning for Guard blocks increases noise on logs with invalid WARNs with users cookbook

### ISSUE THREAD

**Issue by petecheslock** [chef/chef#5574]
## Description

Using the users cookbook to add users the following commit spams logs with WARNs (these are not warns unless core functionality in chef has changed. 
https://docs.chef.io/resource_common.html#only-if-examples
https://github.com/chef-cookbooks/users/blob/master/providers/manage.rb#L104
https://github.com/chef-cookbooks/users/blob/master/providers/manage.rb#L114

## Chef Version

Chef-client > 12.14.27

## Platform Version

Ubuntu

## Replication Case

Use that latest users cookbook to create a user with SSH key
you will see the following

## Client Output

```
  * directory[/home/USER/.ssh] action create[2016-11-23T14:12:09+00:00] WARN: only_if block for directory[/home/USER/.ssh] returned "<SSH KEY OUTPUT>", did you mean to run a command? If so use 'only_if "<SSH KEY OUTPUT>"' in your code.
 (up to date)
    * template[/home/USER/.ssh/authorized_keys] action create[2016-11-23T14:12:09+00:00] WARN: only_if block for template[/home/USER/.ssh/authorized_keys] returned
"<SSH KEY OUTPUT>", did you mean to run a command? If so use 'only_if "<SSH KEY OUTPUT>"' in your code
.
```

### NOTE: CHEF CLIENT BUGS ONLY

This issue was added with this commit https://github.com/chef/chef/commit/bea83309ccedfe48be5ebac979bb531100f31883

/cc @coderanger

**Comment by coderanger** [comment]
Yep, this should be fixed in the cookbook :)

**Comment by coderanger** [comment]
It's not an error, it's a warning. As the commit says, it's to catch a common class of user errors when they don't understand the difference between `not_if 'foo'` and `not_if { 'foo' }`. It's pretty easy to change the user cookbook to do:

```ruby
only_if { !!(u['ssh_keys'] || u['ssh_private_key'] || u['ssh_public_key']) }
```

**Comment by petecheslock** [comment]
Ah i see what you're saying.   Thanks @coderanger

**Comment by spuder** [comment]
I'm a little confused by this example. Are you saying to get rid of this warning I need to change all my cookbooks from

    only_if { node['foo']['bar'] }

to

    only_if { !!(node['foo']['bar']) }

**Comment by coderanger** [comment]
If the value is a string, yes.

**Comment by spuder** [comment]
I've found Rubocop doesn't like !!()

http://www.rubydoc.info/github/bbatsov/rubocop/Rubocop/Cop/Style/DoubleNegation

Either use this syntax

    only_if { !(node['foo']['bar']).nil? }

or add to the .rubocop.yml

```
Style/DoubleNegation:
  Enabled: false
```

**Comment by shortdudey123** [comment]
`only_if { !(node['foo']['bar']).nil? }` will only work part of the time:

```
[1] pry(main)> false.nil?
=> false
[2] pry(main)> !(false).nil?
=> true
[3] pry(main)> !!(false)
=> false
[4] pry(main)> 
```
