### ISSUE TITLE
Use of wildcards in package versions results in package always installing

### ISSUE THREAD

**Issue by gene1wood** [chef/chef#5578]
## Description

Use of wildcards in package versions results in package always installing

## Chef Version

12.6.0-1

## Platform Version

Ubuntu 14.04

## Replication Case

Create a recipe that uses the apt version wildcard feature. In this example we're indicating to install the newest version of `git` in the `1.9` major+minor version.

```
apt_package 'git' do
  version '1:1.9\*'
end

```

## Client Output

Because the package resource determines if the current package version matches the requested package version by doing a string comparison, comparisons of the current version and the targeted version containing a wildcard will always show a mistmatch and always trigger an installation, even when the current version is the newest version matching the wildcard. The installation doesn't install anything because the version is correct but chef believe that the resource has changed.

* https://github.com/chef/chef/blob/1991cf97660a38e704eb4cd9609ed6ea84a35442/lib/chef/provider/package.rb#L319
* https://github.com/chef/chef/blob/1991cf97660a38e704eb4cd9609ed6ea84a35442/lib/chef/provider/package.rb#L168

```
Recipe: example::test
  * apt_package[git] action install
    - install version 1:1.9\* of package git
```

## Possible Solutions

The `apt` provider could override these string comparison methods in `package` and instead

* detect for the presense of a wildcard in the targeted version
* if present run a simulated `apt-get` run to expand the wildcard ( `apt-get --simulate install git="1:1.9*"` )
* determine what the wildcard expanded version number is
* do a string comparison of the current and target versions

or

* detect for the presense of a wildcard in the targeted version
* if present run some other apt command which does the version comparison which accounts for wildcards and returns the comparison results

or

* use some apt binding to have apt do the comparison. This is the method [ansible uses](https://github.com/ansible/ansible-modules-core/blob/109c68980424146121d79e4bc91cec475894645a/packaging/os/apt.py#L291)

**Comment by gene1wood** [comment]
[Here's some mention of the wildcard feature](https://www.debian.org/doc/manuals/apt-howto/ch-apt-get.en.html#s-pin)

**Comment by lamont-granquist** [comment]
yeah it would be best to do version comparisons using apt's code.

the yum provider is an example of how porting algorithms like that into ruby ends badly.

**Comment by dragon788** [comment]
There are tests for serverspec and InSpec to avoid wildcards by using cmp or a `should be >` on a left anchored version, and they support the Debian-style epoch versions as well. It's a shame we can't do loose versions in Chef that way yet.

**Comment by lamont-granquist** [comment]
The dnf provider does, the yum provider rewrite will.

**Comment by lamont-granquist** [comment]
Think I'm going to close this since its too vague right now and the support has to go in each individual package provider, and they're not all finished this issue will never be done.  There's other issues opened specifically on yum+apt somewhere which are more appropriate.
