### ISSUE TITLE
Invalid warnings from resource guard clauses

### ISSUE THREAD

**Issue by emiller42** [chef/chef#5581]
## Description

A pattern we use for conditional resource evaluation is to test if a particular attribute is populated.  

Example:
```
execute 'ls' do
  only_if { node['foo']['bar'] }
end
```

Where `default['foo']['bar'] = nil`.  The intention being that the resource should only execute if the attribute has been overridden to any value.  This relies on the common Ruby convention that a nil value is 'falsey' while a non-nil value is 'truthy'.  

Additional warnings added in #5233 incorrectly trigger when this pattern is used.  

```
* execute[ls] action run[2016-11-25T11:16:59+00:00] WARN: only_if block for execute[ls] returned "something", did you mean to run a command? If so use 'only_if "something"' in your code.
```

Ideally, this validation would distinguish between `only_if { node['foo']['bar'] }` and `only_if { "something" }` with only the latter triggering a warning.  

## Chef Version

Chef v12.16.42

## Platform Version

N/A 

## Replication Case

```
node.default['foo']['bar'] = 'something'

execute 'ls' do
  only_if { node['foo']['bar'] }
end
```

## Client Output

```
* execute[ls] action run[2016-11-25T11:16:59+00:00] WARN: only_if block for execute[ls] returned "something", did you mean to run a command? If so use 'only_if "something"' in your code.
```

## Stacktrace

N/A

**Comment by coderanger** [comment]
Unfortunately the suggestion isn't possible as Ruby doesn't work that way. You can silence the warning by returning a boolean from your block instead of a string:

```ruby
only_if { !!node['foo']['bar'] }
```

**Comment by shortdudey123** [comment]
I think you should be able to do this instead as well
```
not_if { node['foo']['bar'].nil? }
```

**Comment by coderanger** [comment]
That would work with `nil` but not `false`.

**Comment by emiller42** [comment]
I know how to work around the defect, but that doesn't really address the fact that this is a defect.  The warning introduced in #5233 triggers in circumstances outside of the intended case. ( `only_if { "string" }` )

This puts the onus on users to either ignore invalid WARNs in their logs, (bad) or change their code to eliminate them. (Also bad)  In the latter case, it further introduces a subtle trap, which we already saw happen in the workaround proposed by @shortdudey123

**Comment by coderanger** [comment]
@emiller42 Unfortunately there is no way to know from just seeing the return value if it was a literal or a node attribute (or something else). That's just not how Ruby works. It is a warning on purpose, it's something that should be fixed but not inherently fatal. Basically your comment of:

>  This relies on the common Ruby convention that a nil value is 'falsey' while a non-nil value is 'truthy'.

is something we can no longer fully support for these blocks, return actual booleans when you mean to have booleans. If you have a suggested implementation for only catching literal strings, I'm happy to hear it.

**Comment by emiller42** [comment]
>  If you have a suggested implementation for only catching literal strings, I'm happy to hear it.

Yes, don't do it.

Guard clauses expect a block argument which can be tested conditionally.  `{ "some_string" }` fits that specification.  The validation being applied here is attempting to lint the block in a place where it is impossible to lint the block.  It can't be done without false positives.  It's inherently defective. 

This is a linting problem.  Implement it in Foodcritic where it can be done accurately.

**Comment by coderanger** [comment]
Unfortunately not everyone uses Foodcritic, and given that fixing the warning takes two keystrokes and prevents a fairly common misuse of Chef ...

I'm sorry for the frustration, but it does seem like a net win overall to me given how easy it is to silence the warning.

**Comment by emiller42** [comment]
> Unfortunately not everyone uses Foodcritic

The same argument could be leveraged against everything Foodcritic validates.  

> given that fixing the warning takes two keystrokes

I now have to audit a couple hundred internal cookbooks to see where those two keystrokes need to be applied, simply to avoid monitoring noise caused by a defect.

**Comment by rmoriz** [comment]
Just to let you know that `!!` throws a cookstyle error…

Chef Development Kit Version: 1.2.22

```

➜  resources git:(master) ✗ chef exec cookstyle acme_persistence.rb  -D
Inspecting 1 file
C

Offenses:

acme_persistence.rb:118:17: C: Style/DoubleNegation: Avoid the use of double negation (!!).
      only_if { !!item['cert'] }
                ^
acme_persistence.rb:129:17: C: Style/DoubleNegation: Avoid the use of double negation (!!).
      only_if { !!item['fullchain'] }
                ^
acme_persistence.rb:140:17: C: Style/DoubleNegation: Avoid the use of double negation (!!).
      only_if { !!item['chain'] }
                ^

1 file inspected, 3 offenses detected
```

**Comment by lamont-granquist** [comment]
```ruby
if node['foo']['bar']
  execute 'ls' do
end
```

if that works for you instead, then the next release of FC will turn off the rule that tried to force you to write that as an `only_if`
