### ISSUE TITLE
chef-client doesn't properly reset the ruby environment

### ISSUE THREAD

**Issue by bcurnow** [chef/chef#5589]
## Description

It appears that in Chef version 12.0.0, a fix was implemented for https://github.com/chef/chef/issues/2548. The fix was to use some ruby code to clear out the GEM_HOME and GEM_PATH environment variables:

`ENV["GEM_HOME"] = ENV["GEM_PATH"] = nil unless ENV["APPBUNDLER_ALLOW_RVM"] == "true"`

However, if the Gem/Gem::Specification class is initialized before the environment variables are reset then the fact that they are nil doesn't matter.

However, adding `Gem.clear_paths` after the ENV reset will cause the Gem/Gem::Specification classes to re-read the environment on the next command and will result in a working chef-client run. Seems like this is the logic next step for the original fix introduced.

A script that simply unsets GEM_HOME and GEM_PATH resolves this issue as does `rvm system` since there is no system ruby and therefore that rvm command simply unsets the variables.

## Chef Version

12.16.42

## Platform Version

CentOS 6.8

## Replication Case

* Bootstrap node with 12.16.42
* Install rvm::system (using https://github.com/martinisoft/chef-rvm version 0.9.4)
* Logout
* Log back in
* sudo to root (`sudo su -`)
* run `/opt/chef/bin/chef-client`

## Client Output

```
       /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'addressable' (= 2.4.0) among 17 total gem(s) (Gem::MissingSpecError)
       Checked in 'GEM_PATH=/usr/local/rvm/gems/ruby-2.3.1:/usr/local/rvm/gems/ruby-2.3.1@global', execute `gem env` for more information
       	from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/dependency.rb:320:in `to_spec'
       	from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
       	from /opt/chef/bin/chef-client:4:in `<main>'
```
## Stacktrace

See output above.

**Comment by lamont-granquist** [comment]
already fixed in https://github.com/chef/appbundler/pull/24 appbundler seems to need a gem release
