### ISSUE TITLE
reboot! does not work well with Tomcat

### ISSUE THREAD

**Issue by Xoph** [chef/chef#5594]
## Description

I have Tomcat 8 installed. When Tomcat is installed, it is added at the beginning of the PATH environment variable, so the 'shutdown...' command-line in the reboot! method of the rebooter.rb module uses shutdown.bat in C:\Program Files\Tomcat-8\bin\ instead of the built-in Windows shutdown command.

My recipes update the version of Java installed, and therefore set the JRE_HOME environment variable, so using the reboot resource returns an error because the 'shutdown...' command-line is still using the old value of the JRE_HOME environment variable (which references a location that no longer exists) when running the reboot.

Synopsis: If the PATH environment variable contains a location with a shutdown.exe or shutdown.bat file that is evaluated before C:\Windows\System32, that file will be used and it can cause an issue.

Solution: Use a full path depending on OS architecture.

Additional funkiness comes into play with this issue as well, because shutdown.bat for Tomcat does not support /c so a message cannot be specified to the user.

## Chef Version

12.13.37

## Platform Version

Windows Server 2012 R2

## Replication Case

1. Create a file C:\Temp\shutdown.bat that contains the text 'exit 1'.
2. Add C:\Temp\ as the first item in the list in the PATH environment variable.
3. Create a recipe that uses the reboot resource.
4. Run Chef for the recipe and see it fail.

## Client Output

Chef Client finished, 50/105 resources updated in 10 minutes 19 seconds
  3/3 controls succeeded
[2016-11-29T13:31:01-05:00] WARN: Rebooting server at a recipe's request. Details: {:delay_mins=>1, :reason=>"Rebooting
the server!.", :tim
estamp=>2016-11-29 13:26:06 -0500, :requested_by=>"Reboot the server at the end of the run"}

Running handlers:
[2016-11-29T13:31:01-05:00] ERROR: Running exception handlers
Running handlers complete
[2016-11-29T13:31:01-05:00] ERROR: Exception handlers complete
Chef Client failed. 50 resources updated in 10 minutes 19 seconds
  3 controls succeeded
[2016-11-29T13:31:01-05:00] FATAL: Stacktrace dumped to c:/support/radiologyservicetools/installautomation/local-mode-ca
che/cache/chef-stacktrace.out
[2016-11-29T13:31:01-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-11-29T13:31:01-05:00] FATAL: Chef::Exceptions::RunFailedWrappingError: Found 1 errors, they are stored in the back
trace

## Stacktrace

Generated at 2016-11-29 13:31:01 -0500
Chef::Exceptions::RunFailedWrappingError: Found 1 errors, they are stored in the backtrace
1) Chef::Exceptions::RebootFailed -  Expected process to exit with [0], but received '1'
---- Begin output of shutdown /r /t 60 /c "Rebooting the server to finalize the installation of Server Environment Setup as part of the Universal Viewer installation." ----
STDOUT: The JRE_HOME environment variable is not defined correctly

This environment variable is needed to run this program
STDERR: 
---- End output of shutdown /r /t 60 /c "Rebooting the server to finalize the installation of Server Environment Setup as part of the Universal Viewer installation." ----
Ran shutdown /r /t 60 /c "Rebooting the server to finalize the installation of Server Environment Setup as part of the Universal Viewer installation." returned 1
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37-universal-mingw32/lib/chef/platform/rebooter.rb:49:in `rescue in reboot!'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37-universal-mingw32/lib/chef/platform/rebooter.rb:45:in `reboot!'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37-universal-mingw32/lib/chef/platform/rebooter.rb:59:in `reboot_if_needed!'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37-universal-mingw32/lib/chef/client.rb:305:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37-universal-mingw32/lib/chef/application.rb:284:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37-universal-mingw32/lib/chef/application.rb:260:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37-universal-mingw32/lib/chef/application.rb:243:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37-universal-mingw32/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37-universal-mingw32/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37-universal-mingw32/lib/chef/application/client.rb:450:in `loop'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37-universal-mingw32/lib/chef/application/client.rb:450:in `interval_run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37-universal-mingw32/lib/chef/application/client.rb:434:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37-universal-mingw32/lib/chef/application.rb:60:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:64:in `load'
C:/opscode/chef/bin/chef-client:64:in `<main>'

**Comment by btm** [comment]
we could use `ENV['SYSTEMROOT']` here like we did in https://github.com/chef/chef/pull/5564

**Comment by Xoph** [comment]
Note that there is already a pull request going with the fix, and it uses the SYSTEMROOT environment variable. I'm just not sure why it's failing the build. If we solve that, it's ready to go.
