### ISSUE TITLE
Action :umount for mount resource is an obtuse anachronism

### ISSUE THREAD

**Issue by jblaine** [chef/chef#5595]
## Description

The `:umount` action for the `mount` resource to unmount a filesystem is a direct name duplication of the UNIX/Linux userland command. While that's cool and all, `:unmount` should be allowed as well because it makes sense in the scope of the resource to name the action based on what action will take place.

## Chef Version

12.6.0 though I see no open issues or open+closed PRs about this, so think it affects all Chef client versions.

## Platform Version

N/A but Linux

## Replication Case

Try to use `:unmount` as an action to the `mount` resource. It fails and wants the UNIX/Linux-command naming of `:umount`

## Client Output

NA

## Stacktrace

NA

**Comment by thommay** [comment]
Agreed. We'd love a PR to add `unmount` as an action.
