### ISSUE TITLE
add support for zfs to mount provider

### ISSUE THREAD

**Issue by ttr** [chef/chef#5597]
## Description

Mounting zfs throws "Device <zfs path> does not exist"

## Chef Version

Chef Client, version 12.15.19

## Platform Version

Devuan 1.0 (debian jessie fork)

## Replication Case

define mount using zfs partition:
` mount "/usr/local/dockerstorage/es" do
  device XENzfs/XEN/dockerstorage/es
  fstype 'zfs'
  options path[3] || 'noatime,rw
end'

At simplest (IMO) is to add zfs into https://github.com/chef/chef/blob/master/lib/chef/provider/mount/mount.rb#L196

**Comment by thommay** [comment]
@ttr do you fancy making a pull request to fix this?
