### ISSUE TITLE
chef-client 12.16 automatic data collector connections fail when using a chef-server URL including an organization

### ISSUE THREAD

**Issue by tcp100** [chef/chef#5608]
## Description
Chef Client 12.16 added the feature to automatically forward an Automate Data Collector via the Chef Server with zero configuration.  It attempts to use the chef server URL as specified in client.rb, so no additional configuration is needed.  However if the Chef server URL contains an organization, i.e. <https://chef.server.com/organizations/myorg>, the chef server will try to redirect the post, resulting in a client failure.

This can be worked-around by adding the data_collector.server_url = "https://chef.server.com/data-collector/v0/" directly to client.rb, but believe this violates the intent of the enhancement added to client v 12.16 - that data collection can be enabled with zero config.

Concern is that this has caused clients to spontaneously start failing, and since it fails before even getting into ohai or cookbook execution, changes can't be reverted via policy.  Our solution was to stop rollout of 12.16 - then via client 12.12, add a key-value pair for data_collector.server_url via chef-client cookbook, and then re-launch rollout of 12.16 across the enterprise..

## Chef Version

chef-client 12.16

## Platform Version

RHEL 6

## Replication Case

Enable Automate data collection on the chef server.

Bootstrap a node with the chef-server URL specifying an organization, I.E.:

knife bootstrap 10.11.12.13 --ssh-user bob --sudo --identity-file
~/.ssh/bob-key.pem --node-name mynode.org.com --run-list role
[myorg-generic-dev] --server-url https://chef.org.com/organizations/myorg

## Client Output

10.11.12.13 Chef Client failed. 0 resources updated in 24 seconds
10.11.12.13 [2016-11-30T18:28:06+00:00] ERROR: POST request was redirected
from
https://chef.org.com/organizations/myorg/data-collector to
https://chef.org.com/data-collector/v0/. Only GET and HEAD support
redirects.
10.11.12.13 [2016-11-30T18:28:06+00:00] FATAL:
Chef::Exceptions::ChildConvergeError: Chef run process exited
unsuccessfully (exit code 1)

## Stacktrace

N/A

**Comment by thommay** [comment]
cc @danielsdeleo @adamleff @srenatus

**Comment by adamleff** [comment]
Pinged internal team that worked on this.

**Comment by danielsdeleo** [comment]
The main problem here is the Chef Server sending a redirect. Can you share your `chef-server.rb`, and also look in the nginx logs to see if there's any additional info about why it's sending this redirect? On the client-side, _maybe_ we could have Chef Client rescue this error and disable the data collector, but I'm not sure if that's what we really want.

**Comment by tcp100** [comment]
Hmm.. Our `chef-server.rb` is pretty vanilla.. As below:

I was curious that the redirect was happening as well, but thought that it was since the data collector appeared to work from the base url of the chef server, vs the one with /organizations/<org> attached.

We wouldn't want the data collector to be disabled, optimally I'd think the chef-client could determine the proper base url to use for the collector.

```
api_fqdn "chef.prod.sys.dom"
ldap['host'] = 'ad01.prod.sys.dom'
ldap['port'] = 389
ldap['ssl_enabled'] = false
ldap['base_dn'] = 'dc=prod,dc=sys,dc=dom'
ldap['bind_dn'] = 'CN=chef-svc,OU=service,OU=accounts,OU=prod,DC=prod,DC=sys,DC=dom'
ldap['login_attribute'] = 'sAMAccountName'
ldap['bind_password'] = 'bindpassword'
license['nodes'] = 1200

oc_id['applications'] = {
  'supermarket' => {
    'redirect_uri' => 'https://supermarket.prod.sys.dom/auth/chef_oauth2/callback'
  }
}

data_collector['root_url'] = 'https://automate.prod.sys.dom/data-collector/v0'
data_collector['token'] = '93a49a4f2482c64126f7b6015e6b0f30284287ee4054ff8807fb63d9cbd1c506'

```

The only thing I see in the nginx logs is that it's sending a 301 when trying to hit the data collector with the relative `/organizations/<org>` in the chef_server_url, bug no reasoning as to why:

`10.11.12.13 - - [30/Nov/2016:12:03:10 +0000]  "POST /organizations/infrastructure/data-collector HTTP/1.1" 301 "0.016" 178 "-" "Chef Client/12.16.42 (ruby-2.3.1-p112; ohai-8.21.0; x86_64-linux; +https://chef.io)" "10.110.23.24:443" "301" "0.001" "12.16.42" "algorithm=sha1;version=1.1;" "SDdEa-aDEMO01.dev.sys.dom" "2016-11-30T12:03:10Z" "SF2UluZ9+uyf9J5OImhCOcsdrag=" 96766
`

I don't see anything else pertaining to this request in the other nginx logs (error) or in the erchef logs themselves.  We don't have anything else in front of the chef server.

**Comment by srenatus** [comment]
@tcp100 Thanks for sharing your config. Its problem is the missing trailing slash here:

```
data_collector['root_url'] = 'https://automate.prod.sys.dom/data-collector/v0'
```

Without the slash, Automate's nginx will try to be clever and redirect you to `data-collector/v0/` -- breaking your POST. 💥 
 
This has been fixed yesterday (making Automate accept stuff on the root_url without the trailing slash), but for getting unstuck, please try again with adding it to your `data_collector['root_url']`.

**Comment by danielsdeleo** [comment]
Closing this since the proper fix has been merged (in Automate, which is private so I can't link to the change) and there is a workaround for now. If anyone is of the opinion that the data collector should disable itself when encountering invalid redirects, please file a new issue (or create a PR) and we can talk about it.

**Comment by adamleff** [comment]
@danielsdeleo there is a `data_collector.raise_on_failure` config parameter that we initially honored for this. If it was false, and we failed to send the run_start message, we'd disable. We should probably continue to honor that even with the automagic config, no?
