### ISSUE TITLE
dsc_resource scriptblock property type support

### ISSUE THREAD

**Issue by eedwardsdisco** [chef/chef#5629]
## Description

PowerShell ScriptBlocks appear unsupported in dsc_resource as a `property :soandso` value

## Chef Version

12.16.42

## Platform Version

2012r2 x64 12.16.42

## Replication Case

```
dsc_resource "disable-#{profile_name}-profile" do
  resource :script
  module_name 'PSDesiredStateConfiguration'
  property :getscript, "{@{ Result = -not ((Get-NetFirewallProfile -Name '#{profile_name}').Enabled) }}"
  property :setscript, "{Set-NetFirewallProfile -Name '#{profile_name}' -Enabled False -Verbose}"
  property :testscript, "{-not ((Get-NetFirewallProfile -Name '#{profile_name}').Enabled)}"
end
```

## Client Output

Chef::Exceptions::PowershellCmdletException: Powershell Cmdlet failed: Invoke-DscResource : PowerShell DSC resource MSFT_ScriptResource  failed to 
       execute Test-TargetResource functionality with error message: Failure to get a 
       valid result from the execution of TestScript. The Test script should return 
       True or False. 
       At line:1 char:73
       + ... ge);exit 1};Invoke-DscResource -Method test -Name script -Property @{ ...
       +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationMan 
          ager:String) [Invoke-DscResource], CimException
           + FullyQualifiedErrorId : ProviderOperationExecutionFailure,Microsoft.Powe 
          rShell.DesiredStateConfiguration.Commands.InvokeDscResourceMethodCommand

## cont.

Trying to use the https://msdn.microsoft.com/en-us/powershell/dsc/scriptresource 'script' resource which takes ScriptBlock parameters.

I don't see ScriptBlock as a supported type in `chef/mixin/powershell_type_coercions`, and I can't seem to get this to work, so I'm puzzled as to how to figure this out without ScriptBlock support.

**Comment by eedwardsdisco** [comment]
I got this to work by dropping the `{}`'s around my script blocks.

So, appears that the strings are getting wrapped into scriptblocks during the ps call?

This wasn't obvious from the [documentation on dsc_resource](https://docs.chef.io/release/devkit/resource_dsc_resource.html).

Perhaps an example that shows how to use `resource :script` would be useful.

**Comment by usrme** [comment]
@eedwardsdisco Confirming that this is a problem on a Windows Server 2016 endpoint as well. Thanks for providing a solution, and I concur with having an example of this in the documentation. In fact, more examples of real practical usage of DSC with Chef are needed. Maybe something up @smurawski 's alley?
