### ISSUE TITLE
Clarify effect of json-attributes

### ISSUE THREAD

**Issue by axos88** [chef/chef#5637]
https://docs.chef.io/ctl_chef_client.html

It seems that attributes given in the --json-attributes will effetively have the 'normal' level. Please docuement this, I would've expected it to be on the highest level.

**Comment by coderanger** [comment]
To quote from the linked page:

> In certain situations this option may be used to update normal attributes.

Is there something else you would like to see added?

**Comment by coderanger** [comment]
(also `All attributes are normal attributes` is further down in the section, in bold)

**Comment by shortdudey123** [comment]
@coderanger dang, beat me to the punch!

The `All attributes are normal attributes` section explains this

**Comment by axos88** [comment]
sorry, can't read.
