### ISSUE TITLE
dsc_script does not accept a flag of type Chef::Util::Powershell::PSCredential when used with command

### ISSUE THREAD

**Issue by tehsuk** [chef/chef#5640]
## Description

'Invalid argument type' error is returned when the dsc_script resource is used with the 'command' property & a 'flags' property that contains a Chef::Util::Powershell::PSCredential type.

/lib/chef/util/powershell/cmdlet.rb is what is disallowing this.

There are 2 workarounds I'm aware of, both of which aren't very desirable for how I'm using chef/dsc:

- Don't use a .ps1 as a command.  I prefer to keep my DSC resources in external .ps1 files that I keep in \files\default in my cookbook for portability reasons (I use these in other environments not currently being managed by chef).
- Pass the userid/password as strings to flags.  For now I'm storing creds encrypted in a vault & decrypting them in my recipe, setting PSDscAllowPlainTextPassword = $true in configuration data, but this isn't secure & the password ends up appearing in the logs if dsc_script fails & in the temp mof files.

## Chef Version

Chef 12.16.42

## Platform Version

Tested on Server 2012R2 & Server 2016

## Replication Case

Sample recipe:
```
creds_pso = ps_credential('domain\user', 'password')
dsc_script 'doathing' do
 command "C:\dscscripts\doathing.ps1"
 flags ({:cred => creds_pso})
 configuration_data <<-EOH
  @{
   AllNodes = @(
    @{
    NodeName = "localhost";
    PSDscAllowDomainUser = $true
    })
   }
   EOH
end
```
doathing.ps1:
```
Configuration doathing {
 param (
  [System.Management.Automation.PSCredential] $cred
 )
 Import-DscResource -ModuleName PSDesiredStateConfiguration
 
 Node $AllNodes.Nodename {
  Group AddDomainUserToLocalGroup {
   GroupName = 'AGroup'
   MembersToInclude = 'domain\anotheruser'
   Credential = $cred
  }
 } 
}
```
## Client Output
```
[2016-12-09T15:01:41-05:00] INFO: Processing dsc_script[doathing] action run (mycookbook::default line 37)
[2016-12-09T15:01:41-05:00] ERROR: DSC operation failed: Invalid argument type `Chef::Util::Powershell::PSCredential` specified for PowerShell switch `:admincreds`. Arguments to PowerShell must be of type `String`, `Numeric`, `Float`, `FalseClass`, or `TrueClass`
```
## Stacktrace

attached
[chef-stacktrace.zip](https://github.com/chef/chef/files/643147/chef-stacktrace.zip)

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by mwrock** [comment]
You will want to use the ps_credential helper to embed a ps credential: https://docs.chef.io/resource_dsc_script.html#ps-credential-helper

Please reopen if that does not work for you!

**Comment by tehsuk** [comment]
I'm using the ps_credential helper, its the first line of the sample recipe I posted.

I haven't tested embedding a variable created by a ps_credential object into the 'code' property, as I prefer keeping my DSC in external PS1 files.
