### ISSUE TITLE
chef_group throwing OpenSSL::SSL::SSLError

### ISSUE THREAD

**Issue by pariminaresh** [chef/chef#5642]
## Description

I'm using ACL resources chef_group, chef_acl to create groups and assign ACL entries on the server side objects.

It is working fine with the private chef server but failing when try to run against enterprise server and throwing error as ERROR: chef_group[admin_test] had an error: OpenSSL::SSL::SSLError. I believe this is not related to knife ssl check OR fetch.Since knife acl commands are working fine from the same node.

## Chef Version

chef-client version: 12.15.19

## Platform Version

ubuntu-14.04

## Replication Case

 - Create a chef_group resource(The pasted below the one I defined) to create a group on the server.
 - Run against private chef server - working fine for me
 - Run against enterprise chef server - failing with SSL error

  Below is the peace of code, Im running:
  ------->
  hash = {:chef_server_url=>"chef.ec.com", :options=>{:client_name=>'admins',     :signing_key_filename=>'/tmp/admins.pem',:api_version=>"2"}}

  chef_group "Create_group" do
      name "test_group"
     chef_server hash
  end
<------- 

## Client Output

chef_group[admin_cn] action create[2016-12-09T19:07:52+00:00] ERROR: SSL Validation failure connecting to host: giscinchef.corporate.ge.com - SSL_connect returned=1 errno=0 state=error: certificate verify failed
       
           
           ================================================================================
           Error executing action `create` on resource 'chef_group[admin_cn]'
           ================================================================================
           
           OpenSSL::SSL::SSLError
           ----------------------
           SSL Error connecting to https://giscinchef.corporate.ge.com/organizations/test-bm/groups/admin_cn - SSL_connect returned=1 errno=0 state=error: certificate verify failed

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by lamont-granquist** [comment]
The chef_group resource is actually a cheffish resource which would technically go here:  https://github.com/chef/cheffish/issues

If knife is working correctly it may be a dup of https://github.com/chef/cheffish/issues/105 where cheffish has its own chefserver api object that seems to have been forked off some time ago and needs to go away.

**Comment by lamont-granquist** [comment]
closing as probably a dup of chef/cheffish#105
