### ISSUE TITLE
Ubuntu 16.04 Cron resource updates on every run

### ISSUE THREAD

**Issue by corycburke** [chef/chef#5643]
## Description

On Ubuntu 16.04, every time chef-client is run, cron resources report that they have updated (or will update in the case of why-run mode).

## Chef Version

Chef-Client 12.7.2

## Platform Version

Ubuntu 16.04

## Replication Case

Create a cron job using the cron resource built into Chef on Ubuntu 16.04. Run chef-client once so that the cron job is created. Immediately after creating the cron job, run chef-client -W, chef-client indicates that the cron job would be updated.

**Comment by lamont-granquist** [comment]
12.7.2 is very old at this point, and we'll probably require the properties being passed to the cron resource.   a small github repo with TK config to replicate the case would be useful.

**Comment by thommay** [comment]
Hi,
we're going to need a lot more information to be able to reproduce and fix this. For now, we'll be closing this ticket, but feel free to reopen it with further information.
