### ISSUE TITLE
dsc_script - can't pass a variable created by ps_credential to flags

### ISSUE THREAD

**Issue by tehsuk** [chef/chef#5644]
## Description

See #5640 

Copy of that issue below:

'Invalid argument type' error is returned when the dsc_script resource is used with the 'command' property & a 'flags' property that contains a Chef::Util::Powershell::PSCredential type.

/lib/chef/util/powershell/cmdlet.rb is what is disallowing this.

There are 2 workarounds I'm aware of, both of which aren't very desirable for how I'm using chef/dsc:

- Don't use a .ps1 as a command.  I prefer to keep my DSC resources in external .ps1 files that I keep in \files\default in my cookbook for portability reasons (I use these in other environments not currently being managed by chef).
- Pass the userid/password as strings to flags.  For now I'm storing creds encrypted in a vault & decrypting them in my recipe, setting PSDscAllowPlainTextPassword = $true in configuration data, but this isn't secure & the password ends up appearing in the logs if dsc_script fails & in the temp mof files.

## Chef Version

Chef 12.16.42

## Platform Version

Tested on Server 2012R2 & Server 2016

## Replication Case

Sample recipe:
```
creds_pso = ps_credential('domain\user', 'password')
dsc_script 'doathing' do
 command "C:\dscscripts\doathing.ps1"
 flags ({:cred => creds_pso})
 configuration_data <<-EOH
  @{
   AllNodes = @(
    @{
    NodeName = "localhost";
    PSDscAllowDomainUser = $true
    })
   }
   EOH
end
```
doathing.ps1:
```
Configuration doathing {
 param (
  [System.Management.Automation.PSCredential] $cred
 )
 Import-DscResource -ModuleName PSDesiredStateConfiguration
 
 Node $AllNodes.Nodename {
  Group AddDomainUserToLocalGroup {
   GroupName = 'AGroup'
   MembersToInclude = 'domain\anotheruser'
   Credential = $cred
  }
 } 
}
```
## Client Output
```
[2016-12-09T15:01:41-05:00] INFO: Processing dsc_script[doathing] action run (mycookbook::default line 37)
[2016-12-09T15:01:41-05:00] ERROR: DSC operation failed: Invalid argument type `Chef::Util::Powershell::PSCredential` specified for PowerShell switch `:admincreds`. Arguments to PowerShell must be of type `String`, `Numeric`, `Float`, `FalseClass`, or `TrueClass`
```
## Stacktrace

attached
[chef-stacktrace.zip](https://github.com/chef/chef/files/643147/chef-stacktrace.zip)

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by thommay** [comment]
Can you describe what you think the API should look like here? Should it just be as simple as allowing a ps_creds object to be passed in to flags and some magic expansion happens, or is there something we could do better?
I'll note in passing that adding the sensitive property to your resources should alleviate some of the concerns you have around logging.

**Comment by tehsuk** [comment]
I'm looking for dsc_script to be able to accept a flag of type Chef::Util::Powershell::PSCredential when used with command, the same way that dsc_script supports using a ps_credential variable in a code block (see https://github.com/chef/chef/pull/3772 for an example).

https://github.com/chef/chef/blob/master/lib/chef/util/powershell/cmdlet.rb lines 128-140 show that you support Numeric, Float, FalseClass, TrueClass, and Strings as flags.  I'd like to see Chef::Util::Powershell::PSCredential added.

Based on https://docs.chef.io/resource_common.html the sensitive property only works with 3 chef resources: execute, file, and template.

**Comment by tas50** [comment]
I'm going to close this issue out at this point. Sensitive works on all resources and passing objects into the resource like this isn't something the team would be building. If someone in the community wants to propose extending the resource with additional auth options that's something we'd be interested in, but not something we'd be building outselves.
