### ISSUE TITLE
Implement SSLPolicy - A mechanism to handle certificates globally

### ISSUE THREAD

**Issue by afiune** [chef/chef#5652]
## Description

We have introduced a new feature to `berkshelf` with the following PR https://github.com/berkshelf/berkshelf/pull/1640 - This new functionality implements a new class called `SSLPolicy` that will manage the certificate store for any cookbook upload and/or download.

This issue is about moving this new functionality to `chef-config` so that not only **berkshelf** can take advantage of it, but also **knife** and other components. Additionally it will allow us to deal with bug-fixes on a single point and not on many places.

cc/ @danielsdeleo

**Comment by vinyar** [comment]
Great idea, because setting {ssl = false} is getting old.

**Comment by vinyar** [comment]
Closing bug since PR has been merged.

**Comment by thommay** [comment]
It hasn't been implemented in Chef, which is the purpose of this ticket.

**Comment by vinyar** [comment]
just curious if it's in

**Comment by lamont-granquist** [comment]
I don't think we need this.

Berkshelf 7 ripped out ridley entirely and uses Chef::HTTP which should just work (and the new class should probably be ripped out of berkshelf now).

What we need to do is sort out #8600 where we have three different cert stores within ruby and inconsistent usage of APIs which may or may not be aware of different ones of them, so users effectively have to beat on all three locations until it works and there's no documentation around it.
