### ISSUE TITLE
Knife - add support for encrypted private keys on a workstation

### ISSUE THREAD

**Issue by axos88** [chef/chef#5655]
## Description

We would prefer if our private keys would stay encrypted on our hard drives on our workstations (which are usually laptops - ergo subject to bad things :)), and we would be able to:

  1. Provide the decryption key on knife startup.
  2. Use a tool such as ssh-agent to "retrieve" the key. (I know, it doesn't work that way, but the effect is the same)

IMHO Solution 1 would be easier to do as a quickfix, by adding one/two new option(s) to knife:

```knife[:client_key_password] = STDIN.getpass("Password for client key decryption:")```

knife would then provide this password when it needs access to the private key, or it would deccrypt the key to memory, and use the decrypted version. So if there was support for ```knife[:client_key]``` not to point to  file, but contain an actual openssh key would also work, because then the knife.rb could contain the decryption logic. 

## Chef Version

12.15.19

## Platform Version

N/A

**Comment by coderanger** [comment]
Hi there, we don't use GitHub issues to track this kind of feature request as there are an almost infinite number of potential features and very non-infinite time to work on them. Chef Software operates https://feedback.chef.io/ if you would like to provide them input on their roadmap as a company. On the open-source side, if you would like to agree to implement this feature I would recommend writing up a [Chef RFC](https://github.com/chef/chef-rfc) and presenting it at the next developer meeting. As I mentioned on StackOverflow, I would personally like to see this exist, but it's not on my near-term list and I've not heard and particular murmurs from the other Chef devs about it in a long time.

**Comment by axos88** [comment]
https://feedback.chef.io/forums/301644-chef-product-feedback/suggestions/17460199-add-support-for-encrypted-private-keys-on-a-workst
