### ISSUE TITLE
Is the client_name really necessary?

### ISSUE THREAD

**Issue by axos88** [chef/chef#5656]
## Description

It should be possible to remove the client_name parameter entirely.
Since we are using RSA keys for authentication, it should be safe to assume they are unique. This means that the key in use actually does identify the user (a technique used by github, gitlab, etc as well).

Of course this is no small task, the signing protocol needs to be adjusted probably to remove the requiredness of the client_name in the signed body.

This would make knife configuration distribution easier

## Chef Version

12.15

## Platform Version

N/A

**Comment by coderanger** [comment]
Without some kind of ID we would need to check every single public key in the system to know which the signature matches. If you mean we could use the public key itself as the client and node name, then sure but it would make debugging much less pleasant.

**Comment by coderanger** [comment]
As mentioned on #5655, we don't really use GitHub issues for tracking these kinds of questions. If you are interested in improving the authentication protocol, an RFC would also be the place to start.

As for the comparison to GitHub and Gitlab, the SSH protocol does in fact include the user name for this purpose as you can see in [RFC 4252](https://tools.ietf.org/html/rfc4252#page-9) otherwise it would be computationally infeasible for the same reasons as here.

**Comment by axos88** [comment]
https://feedback.chef.io/forums/301644-chef-product-feedback/suggestions/17460205-remove-client-names-the-rsa-key-should-identify-t

**Comment by axos88** [comment]
@coderanger, come on, you can easily build a hash from pubkey to clientname on the server side to look up the client name. :)

Pretty sure github has more users than most chef deployments, and they do just fine.

**Comment by axos88** [comment]
on github the username is always git@

**Comment by axos88** [comment]
just try issuing: ```ssh git@github.com```, it will tell your github username.

**Comment by coderanger** [comment]
The name that GitHub cares about isn't the ssh protocol name, it's the pub key blob in the authentication negotiation, it's included before an auth method is agreed on and maps back to a user in GitHub's database.  



Original Quoted context has been removed as per policy
