### ISSUE TITLE
No man page for knife vault

### ISSUE THREAD

**Issue by ricksebak** [chef/chef#5658]
## Description

There is no man page for knife vault.

## Chef Version

Chef Development Kit Version: 1.0.3

## Platform Version

Ubuntu 16.04

## Replication Case

When you run `knife help upload` or `knife help search` or similar for pretty much any knife sub-command, you get the man page for the sub-command. When you run `knife help vault`, you do not get any man page.

## Client Output

```
knife help vault
ERROR: No help found for 'vault'
```

## Stacktrace

There is no stacktrace.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by thommay** [comment]
Thanks for the report. Chef vault is a separate project; please open a bug at https://github.com/chef/chef-vault/issues/new
