### ISSUE TITLE
Service provider breaks on RHEL/CentOS 7.3

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#5660]
## Description

RHEL 7.3/CentOS 7.3 moves chkconfig from 1.3.x to 1.7.x which has drastically different expectations: instead of `on` and `off`, it wants `enable` and `disable`:

```
$ chkconfig --help
getopt: unrecognized option '--help'
Usage: /usr/sbin/chkconfig [--root=path] enable|disable|is-enabled <sysv script name>
```
This leads Chef to break on any `:enable` or `:disable` rule.

## Chef Version
chef-12.13.37-1.el7.x86_64

## Platform Version

RHEL 7.3

## Replication Case

Upgrade... try to `:enable` a service

## Client Output

```
[2016-12-18T18:06:09-08:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: service[mysvc] (fb_hardware::default line 240) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /sbin/chkconfig mysvc on ----
STDOUT: 
STDERR: Usage: /sbin/chkconfig [--root=path] enable|disable|is-enabled <sysv script name>
---- End output of /sbin/chkconfig 2x_refresh on ----
Ran /sbin/chkconfig mysvc on returned 1
```

## Stacktrace

Not relevant.

**Comment by thommay** [comment]
so 1.3 only supports `on` or `off`, and 1.7 only supports `enable` and `disable`? this is gonna be heaps of fun.
Reading further, can we just do `systemctl enable foo` or `systemctl disable foo`, even for things that have init scripts? I believe that systemctl does the right thing and just proxies to chkconfig in that case...

**Comment by stevendanna** [comment]
> Reading further, can we just do systemctl enable foo or systemctl disable foo, even for things that have init scripts? I believe that systemctl does the right thing and just proxies to chkconfig in that case...

I believe, it depends on the verison of systemd and how the distro has integrated it.  Systemd used to have direct support for chkconfig.  After systemd@0f0467e63b0e0688ae9edb1512c1a2637d62ddb4 (systemd v221) it is up to the distributions to provide a helper script `systemd-sysv-install` which handles enable, disable, etc.

**Comment by lnykryn** [comment]
There must be something else going on. There was no such changes in chkconfig in 7.3 (although we did a rebase) and on my machine it works just fine. 

enable|disable|is-enabled <sysv script name> would match the interface for the systemd-sysv-install mentioned above, But our implementation in chkconfig does not handle the --root parameter.

https://git.fedorahosted.org/cgit/chkconfig.git/tree/chkconfig.c#n47

**Comment by jaymzh** [comment]
Yeah... this is probably related to our backport of systemd and some weird combination of other stuff that hit us only in 7.3. I'm going to close this and if I find there's something chef can/should do I'll open up a follow up.

**Comment by jaymzh** [comment]
OK, cause others are likely to run into this...

As of RHEL 7.3, `/usr/lib/systemd/systemd-sysv-install` is a symlink to `../../..//sbin/chkconfig`.

If you are backporting newer systemd per the Facebook repo (https://github.com/facebookincubator/rpm-backports) or the resulting Redhat copr repo (https://copr.fedorainfracloud.org/coprs/jsynacek/systemd-backports-for-centos-7/) then you've probably been dropping off `/usr/lib/systemd/systemd-sysv-install` - probably with Chef.

Once you upgrade to 7.3, Chef will of course write through this symlink, overwriting chkconfig and the world comes falling down. :)
