### ISSUE TITLE
Solaris IPS packages still fail to install due to dependency conflicts.

### ISSUE THREAD

**Issue by stlng** [chef/chef#5665]
## Description
Related to [#5456](https://github.com/chef/chef/issues/5456), [#5457](https://github.com/chef/chef/issues/5457) & [chef/omnibus#723](https://github.com/chef/omnibus/pull/723)

Solaris Chef client Omnibus IPS packages are being built on Solaris 11.3 SRU 9.3.  This adds pkg dependencies to the IPS package manifest that don't exist on earlier Solaris 11 revisions.

## Chef Version
[12.17.44](https://packages.chef.io/files/stable/chef/12.17.44/solaris2/5.11/chef-12.17.44-1.sparc.p5p) 

## Platform Version

Solaris 11.3 SRU 6.5 and Solaris 11.2 SRU 4.6 (tested - other revs of Solaris 11 too)

## Replication Case

On Solaris 11.3 SRU 4.6
```
 # pkg install -v -g ./chef-12.17.44-1.sparc.p5p pkg://Omnibus/developer/versioning/chef
Creating Plan (Solver setup): -
pkg install: No matching version of developer/versioning/chef can be installed:
  Reject:  pkg://Omnibus/developer/versioning/chef@12.17.44-1
  Reason:  No version matching 'require' dependency shell/ksh93@93.21.1.20120801,5.11-0.175.3.9.0.3.0 can be installed
    ----------------------------------------
    Reject:  pkg://solaris/shell/ksh93@93.21.1.20120801-0.175.3.9.0.3.0
    Reason:  This version is excluded by installed incorporation consolidation/userland/userland-incorporation@0.5.11-0.175.3.6.0.4.0
    ----------------------------------------
```
On Solaris 11.2 SRU 4.6

```
# pkg install -v -g ./chef-12.17.44-1.sparc.p5p pkg://Omnibus/developer/versioning/chef
Creating Plan (Solver setup): \
pkg install: No matching version of developer/versioning/chef can be installed:
  Reject:  pkg://Omnibus/developer/versioning/chef@12.17.44,5.11-1:20161207T094031Z
  Reason:  All versions matching 'require' dependency pkg:/shell/bash@4.1.17,5.11-0.175.3.0.0.30.0 are rejected
    Reject:  pkg://solaris/shell/bash@4.1.17,5.11-0.175.3.0.0.30.0:20150821T172401Z
    Reason:  This version is excluded by installed incorporation pkg://solaris/consolidation/userland/userland-incorporation@0.5.11,5.11-0.175.2.4.0.6.0:20141105T220831Z
```
## Comments

If the package manifest is edited (and the package regenerated) to remove dependency versions, the client installs and runs with no obvious issues on Solaris 11.3 SRU 4.6.

To install on Solaris 11.2. 'pkg:/system/library/security/crypto' requires removing from the manifest dependency list as this package is not available. Once installed chef-client still fails to run, due to missing symbols (which were only added in Solaris 11.3):

```
Solaris 11.2 # chef-client -v
ld.so.1: ruby: fatal: relocation error: file /opt/chef/embedded/lib/libruby.so.2: symbol pthread_setname_np: referenced symbol not found
Killed
```

[Named threads added to Solaris 11.3](https://blogs.oracle.com/observatory/entry/named_threads)

This could be addressed by re-compiling the embedded Ruby on Solaris 11.2

Ref: Current chef-client package dependencies
`
$pkg contents -mg ./chef-12.17.44-1.sparc.p5p chef | grep ^depend
depend fmri=pkg:/shell/bash@4.1.17-0.175.3.0.0.30.0 type=require
depend fmri=pkg:/shell/ksh93@93.21.1.20120801-0.175.3.9.0.3.0 type=require
depend fmri=pkg:/system/core-os@0.5.11-0.175.3.9.0.4.0 type=require
depend fmri=pkg:/system/library/gcc/gcc-c-runtime@4.8.2-0.175.3.0.0.30.0 type=require
depend fmri=pkg:/system/library/math@0.5.11-0.175.3.8.0.3.0 type=require
depend fmri=pkg:/system/library/security/crypto@0.5.11-0.175.3.9.0.4.0 type=require
depend fmri=pkg:/system/library@0.5.11-0.175.3.9.0.4.0 type=require
depend fmri=pkg:/system/linker@0.5.11-0.175.3.9.0.4.0 type=require
`

**Comment by lamont-granquist** [comment]
tagging @scotthain

**Comment by scotthain** [comment]
https://github.com/chef/omnibus/pull/740 should address the dependency versioning, we're looking at the crypto and pthreads issues to see if we can verify on our testers.

**Comment by jaymalasinha** [comment]
https://github.com/chef/omnibus/pull/745  has the version fixes.
It require pkg change-facet facet.version-lock.*=false command to be run prior to the installing the updated package

**Comment by MarkGibbons** [comment]
A small caution about using "pkg change-facet facet.version-lock.*=false", this sequence

pkg change-facet facet.version-lock.*=false
pkg install chef     (tested using 12.21.31)
pkg update

creates a broken and unusable version of the pkg command.  Installing fixes while pkg is broken is not fun. Personally I'm not going to turn off facet locks that are part of the entire distribution.  Patching the os first lets the chef install work.  Turning off facet locks looks like it lets incompatible versions of modules be installed.

Mark
