### ISSUE TITLE
powershell_package resource always triggers pending reboot

### ISSUE THREAD

**Issue by jugatsu** [chef/chef#5672]
## Description

Running powershell_package resource always triggers windows pending reboot.

Steps to reproduce:

```ruby
powershell_package 'xActiveDirectory' do
  action :install
end

reboot 'reboot' do
  action :reboot_now
  only_if { reboot_pending? }
end
```

You will get the endless reboot :)

Actualy this is the _packageManagement_ module issue https://github.com/OneGet/oneget/issues/179

**I've been created this issue to address the problem to chef community.**

As a temporary workaround (Until WMF 5.1 will be released.) - ugrade to PackageManagement 1.1.1.0 where this issue was fixed.

```ruby
# https://github.com/OneGet/oneget/issues/179
powershell_package ['PackageManagement','xActiveDirectory'] do
  action :install
end
```

**Comment by lamont-granquist** [comment]
closing as this doesn't appear to be a chef client bug
