### ISSUE TITLE
data_bag_item raw_data should be converted to a mash before accessed

### ISSUE THREAD

**Issue by axos88** [chef/chef#5686]
## Description

https://github.com/chef/chef/blob/85c9830b3396451af209625ef2263013855ff776/lib/chef/data_bag_item.rb#L81

If a hash is given as the new data, and it contains a key with an :id symbol, validate_id raises an error, as it is passed a nil value.

Since raw_data should be a mash anyways, the setter should convert the value to a mash before retrieving values from it, and setting it as the internal value.

## Chef Version

12.16.42

## Platform Version

n/a

## Replication Case

See above

## Client Output

```
==> default: Chef::Exceptions::InvalidDataBagItemID
==> default: --------------------------------------
==> default: Data Bag items must have an id matching /^[\.\-[:alnum:]_]+$/, you gave: nil
==
```

**Comment by lamont-granquist** [comment]
👍  data bag items should be a mash in chef 13
