### ISSUE TITLE
is chef-client supoort   cpu powerpc32 or arm32？

### ISSUE THREAD

**Issue by zhaoxiaoke** [chef/chef#5689]
I saw chef support deb is only support x86. but my devices cpu is powerpc32

**Comment by coderanger** [comment]
We do not provide installers for those platforms but I know it works on ARM (a bunch of us have compiled stuff for RasPis) and I have no reason to think PPC32 wouldn't work just fine. You'll just have to manage the installation yourself and we don't really have any guidance on this.

**Comment by zhaoxiaoke** [comment]
ok. but  i have another question:
when i install chef_12.17.44-1_amd64.deb from chef.io web. i find this path "opt/chef/embedded/lib" include many so file ,like:

**Comment by zhaoxiaoke** [comment]
debian@945562e636c6:/data/share/code/chef-debpackages/client-opt/chef/embedded/lib$ ls
cmake               libexslt.la         libffi.so          libltdl.a         liblzma.so        libssl.a         libxml2.so.2.9.4   libyaml-0.so.2.0.4  libz.so.1.2.8
config_guess        libexslt.so         libffi.so.6        libltdl.la        liblzma.so.5      libssl.so        libxslt.a          libyaml.a           pkgconfig
engines             libexslt.so.0       libffi.so.6.0.4    libltdl.so        liblzma.so.5.2.2  libssl.so.1.0.0  libxslt.la         libyaml.la          ruby
libcrypto.a         libexslt.so.0.8.17  libiconv.la        libltdl.so.7      libruby-static.a  libxml2.a        libxslt.so         libyaml.so          xml2Conf.sh
libcrypto.so        libffi-3.2.1        libiconv.so        libltdl.so.7.3.0  libruby.so        libxml2.la       libxslt.so.1       libz.a              xsltConf.sh
libcrypto.so.1.0.0  libffi.a            libiconv.so.2      liblzma.a         libruby.so.2.3    libxml2.so       libxslt.so.1.1.29  libz.so
libexslt.a          libffi.la           libiconv.so.2.5.1  liblzma.la        libruby.so.2.3.0  libxml2.so.2     libyaml-0.so.2     libz.so.1

**Comment by zhaoxiaoke** [comment]
i think this so should ues the host, why chef includes these so?

**Comment by coderanger** [comment]
As I said, we do not provide installers for those platforms. You'll have to either build packages yourself or install things as gems the old fashioned way. In either case, you'll be on your own for the most part so I wouldn't recommend doing this unless you're very familiar with Ruby package management or plan to hire someone that is an expert.

**Comment by zhaoxiaoke** [comment]
ok .thank you very much!

**Comment by zhaoxiaoke** [comment]
We do not provide installers for those platforms but I know it works on ARM (a bunch of us have compiled stuff for RasPis) and I have no reason to think PPC32 wouldn't work just fine. You'll just have to manage the installation yourself and we don't really have any guidance on this.
--hi coderanger ，can  i have the installers for  RasPis on ARM?  it is free or commercial payment?

**Comment by zhaoxiaoke** [comment]
hi coderanger, can help with the above problem?  thank you very much!
