### ISSUE TITLE
Documentation on arguments of event_handlers

### ISSUE THREAD

**Issue by axos88** [chef/chef#5690]
## Description

The arguments of the blocks in 
```
Chef.event_handler do
  on :run_completed do |???|
    ....
  end
end
```

seem to be different from event to event (such as the exception in case of failure), but I am unable to find the documentation on what they actually are.

Also it seems impossible to access the run_status from the run_completed and run_failed events to be able to extract things such as the number of updated resources.

## Chef Version

12.17

**Comment by coderanger** [comment]
https://github.com/chef/chef/blob/master/lib/chef/event_dispatch/base.rb is the master record for all events. Life is a tad more complex if you need to support really old versions for certain events (you need to use the argspec from that version of Chef, not the latest) but you can probably ignore that.

As for the run status object, you get it as an argument on `run_started` not `run_completed`. That's a wonky API design and we should probably fix it but for now, it is what it is.

**Comment by axos88** [comment]
So it should be possible to "save" the run_status from the run_started event, and evaluate its value on the run_completed / run_failed?
