### ISSUE TITLE
Valid package return codes fail recipe

### ISSUE THREAD

**Issue by metalseargolid** [chef/chef#5694]
## Description

When a Chocolatey package succeeds with a return code other than 0 which is marked as a success (e.g. 3010 for pending reboot), the package result is returned to the chef run, which fails because it was expecting a return code of 0. As long as the package returns with what Chocolatey perceives as a success, I would expect the resource convergence to succeed as well.

I see two clear avenues towards resolution (not to say there aren't other or better ways):

1. Run `choco.exe` with `--ignore-package-codes`. I am able to work around this by specifying the option as part of the resource block, but would expect this to succeed by default. This flag tells Chocolatey not to return the package success code through to the shell, but 0 for success and 1 for failure. Note that this flag exists in 0.9.10+.

2. Introspect the Chocolatey package return codes and allow those codes on convergence completion as a success. However, this seems less feasible to perform from a Chef resource than the first item.

## Chef Version

ChefDK 1.0.3

## Platform Version

Windows Server 2012R2, Windows 10

## Replication Case

When I use the `chocolatey_package` resource

```ruby
chocolatey_package 'vagrant' do
    version '1.9.1'
    action :upgrade
end
```

The package returns 3010 upon completion (notifying that a reboot is necessary), which is to be expected. However, this seems to fail the converge step.
## Client Output

> STDERR:
           ---- End output of C:\ProgramData\chocolatey/bin/choco.exe upgrade -y -version 1.9.1 --allow-empty-checksums vagrant ----
           Ran C:\ProgramData\chocolatey/bin/choco.exe upgrade -y -version 1.9.1 --allow-empty-checksums vagrant returned 3010

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

**Comment by mwrock** [comment]
There is a PR #5688 currently in progress for this issue.

**Comment by metalseargolid** [comment]
Fair enough, didn't see that one when I searched. Being able to specify successful error codes is fine even if it's not automatic.

**Comment by cheeseplus** [comment]
Closing as https://github.com/chef/chef/pull/5688 has been merged.
