### ISSUE TITLE
Chef hangs when running npm script command

### ISSUE THREAD

**Issue by zrisher** [chef/chef#5699]
## Description

When using the `execute` or `batch` resource to run a script from an npm package, chef will hang if the script doesn't exist or if it runs a js file with `console.log()` in it.

## Chef Version

12.2.1

## Platform Version

Windows 2012 R2

### Setup
Install Chef 12.2.1 on a Windows 2012 R2 box.
Install the latest x64 version of nodejs+npm from https://nodejs.org/en/download/.
Run powershell as Administrator and start `chef-shell`:

```
recipe_mode
execute "1" do
  "call npm install -g git+https://git@github.com/zrisher/chef-npm-example.git"
end
run_chef
```
This should succeed and install the package at `C:\Users\Administrator\AppData\Roaming\npm\node_modules\chef-npm-example`

### Works with native Windows shell
Create a batch file with the following contents at `C:\Users\Administrator\Desktop\test.bat`:
```
cd C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\chef-npm-example
echo before
call npm run-script some_script
echo after
```

Run `call C:\Users\Administrator\Desktop\test.bat` from cmd and it will successfully output:
```
before
Index.js Test
after
```

### Fails with Chef
Now run `chef-shell` again, defining a batch with the same contents:
```
recipe_mode
batch "1" do
  code <<-EOC
    cd C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\chef-npm-example
    echo before
    call npm run-script some_script
    echo after
EOC
end
tracing on
run_chef
```

This will output `before`, `Index.js Test`, and then loop without end through `mixlib/shellout/windows.rb`. See [here](https://github.com/felixrieseberg/windows-build-tools/issues/45#issuecomment-270037772) for an in-depth description of the loop logic, but basically it means the called process isn't exiting. 

### Related cases 
If we amend `package.json` in `C:\Users\Administrator\AppData\Roaming\npm\node_modules\chef-npm-example` and empty the script definition: `"some_script": "node ./lib/index.js"` -> `"some_script": ""` we encounter the same behavior - chef hangs, but the native Windows shell gets to `after` and exits (telling us the script is missing).

If instead we amend `lib/index.js` by commenting out the `console.log('Index.js Test')` line, both native shell and Chef succeed. You can even place basic operations in `index.js` like `const a = 1;`. But if any `console.log()` exists, the chef process will hang.

## Primary Issue
I understand that the functionality of `npm` is beyond the scope of this project. However, I don't understand why this works when run from `cmd` or a batch file, but not when run via Chef's `execute` or `batch` resources. If you guys can help me figure that part out, I'll know how `npm`'s behavior needs to change and can go from there.

**Comment by zrisher** [comment]
Possible related: https://github.com/npm/npm/issues/2938

**Comment by zrisher** [comment]
It would also be nice to know if this is still a problem with the latest Chef 12. I'm stuck on 12.2.1 due to using AWS OpsWorks.

**Comment by tas50** [comment]
@zrisher I'm going to close this out at this point since this is against Chef 12 and we're on 17 now. If we have a test case for this against a currently supported release we can move forward, but without that this isn't something we will be tracking down.
