### ISSUE TITLE
knfie upload - too short control escape

### ISSUE THREAD

**Issue by ceneo** [chef/chef#5702]
## Description

In the Chef::Cookbook::SyntaxCheck class there is a method called remove_uninteresting_ruby_files() that filters out cookbooks' files we don't want to treat as ruby files, and further, don't want to validate it's syntax.

```
def remove_uninteresting_ruby_files(file_list)
  file_list.reject { |f| f =~ %r{#{cookbook_path}/(files|templates)/} }
end
```

Sometimes when we want to upload cookbooks to a chef server using **knfie upload**, this method generates error:

`too short control escape (ArgumentError)`

This depends on directory, where the cookbooks are stored.

If directory path contains special characters for regexp (control escape characters), the error appears.

For example, in path:
**C:\\AGENT-HOME\\xml-data\\build-dir\\76808194-76906499\\artifact\\cookbooks/java'**

**\\xml-data** is handled as
\xnn - Matches an ASCII character, where nn is a two-digit hexadecimal character code.

**\\cookbooks** is handled as
\cX - Matches an ASCII control character, where X is the letter of the control character. For example, \cC is CTRL-C.

To eliminate this bug, I suggest to "normalize" cookbook_path using `Chef::Util::PathHelper.escape_glob_dir()` method.

escape_glob_dir() is used many times in SyntaxCheck class.

## Chef Version

Chef Development Kit Version: 0.9.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2

## Platform Version

Windows 2012r2

**Comment by thommay** [comment]
Fixed in #5704
