### ISSUE TITLE
Wrong link in documentation for Chef Automate (trivial)

### ISSUE THREAD

**Issue by mrincodi** [chef/chef#5714]
## Description

Wrong link in documentation for Chef Automate

## Chef Version

Any

## Platform Version

Any

## Replication Case

Go to
https://learn.chef.io/automate/install/install-chef-automate/#step5

At the end of the section, it reads:
"After you connect, you may find it easier to continue this tutorial by opening this page in its own Google Chrome window from your RDP connection. You can find a bookmark in the Learn Chef folder."

The link is https://learn.chef.io/tutorials/#chef-automate
but this link just brings the browser to https://learn.chef.io/tutorials, not to any internal anchor.

Please correct the link so it points to 
https://learn.chef.io/automate/install/install-chef-automate/#step6

## Client Output

None
## Stacktrace

None

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by lamont-granquist** [comment]
filed under the wrong repo, this is only for the client.

learn chef is here:  https://github.com/chef/chef-web-learn but unfortunately appear to be marked private.

@tpetchel if you're reading this should be a bug against that repo

**Comment by mrincodi** [comment]
Thanks, lamont-granquist, for your reply.

Yes, https://github.com/chef/chef-web-learn is private. I cannot open bugs for it. I think this is important to fix.

In any case, it should be made clear to the reader how to open bugs regarding documentation, and give access.

Thanks.


P. S.: I have another bug to report (of course I am aware this is not the place for it, but there's nowhere else): In 
https://learn.chef.io/automate/deploy-cookbook/create-the-project/#step4
you ask the user to edit the file .delivery\config.json in Windows. It should be suggested to use WordPad for this.
