### ISSUE TITLE
Remove Xcode Command Line Tools dependency for macOS

### ISSUE THREAD

**Issue by erikng** [chef/chef#5719]
## Description

As chef is currently designed, it requires the Xcode Command Line Tools to be installed prior to running chef. While chef does somewhat function, a user is presented a dialog box asking to install the Xcode command line tools.

This becomes problematic as you now need a way to dynamically 
pre-install the CLI tools (which change per major operating system and delta update) prior to running chef.

## Chef Version

Chef 12.17.44

## Platform Version

macOS Sierra 10.12.2 but this impacts 10.9-10.11.5 as well.

## Replication Case

Install chef on macOS.
Run chef-client in normal or local mode.

## Client Output

While I am including the client output, this is for an un-configured node. This more than likely is irrelevant.

https://gist.github.com/erikng/19e653faca79a940eb4ba789434ccd05

<img width="1019" alt="screen shot 2017-01-12 at 8 44 43 am" src="https://cloud.githubusercontent.com/assets/5685016/21898948/66a77612-d8a3-11e6-9888-31d3c1c8fc74.png">

**Comment by erikng** [comment]
For some additional context, it culprit in this case is more than likely

```
[2017-01-12T08:40:52-08:00] DEBUG: Plugin C: ran 'gcc -v' and returned 1
[2017-01-12T08:40:52-08:00] DEBUG: Plugin C 'gcc -v' failed. Skipping data.
```

However there could be more triggers than just this.

**Comment by natewalck** [comment]
Looks like ohai is triggering this: https://github.com/chef/ohai/blob/master/lib/ohai/plugins/c.rb

Perhaps we could bypass this if on Darwin? (Or only if gcc exists?)

This is a decently annoying hurdle for chef to work on macOS and I think it would be a positive change to get this working without CLI tools being required (especially since most macOS boxes are indeed client machines).

**Comment by erikng** [comment]
The problem is gcc exists on the machine, however the frameworks for GCC to work only come from the CLI tools.

**Comment by natewalck** [comment]
So then I think not running this on Darwin would be pretty sane...until someone needs it for compiling stuff on build machines. 

Perhaps we could only run this if said framework was present? That would be pretty sane and prevent it from running on non-build machines.

**Comment by erikng** [comment]
I think it would be easier to not run this on Darwin. We have no idea what frameworks are needed and they could change at any point.

**Comment by natewalck** [comment]
@erikng But that now makes this a breaking change for anyone who depends upon gcc version on their build machine stack. Not doing it at all is the right thing from a client point of view, but it is definitely the wrong thing if your major focus is automated iOS builds.

**Comment by lamont-granquist** [comment]
this needs to get migrated over to the ohai repo - http://github.com/chef/ohai/issues/new
