### ISSUE TITLE
windows_package is reinstalling on every run

### ISSUE THREAD

**Issue by Cylindric** [chef/chef#5721]
I am using Chef to manage a whole bunch of servers, and am having some trouble with windows_package. It seems to be installing the packages on every run.

This is happening on Windows Server 2012R2 servers, running chef-client 12.15.19.

My recipe is a simple one, in this case it just installs 7-zip from an MSI, but I am seeing the same thing with NSClient++

```
windows_package '7-Zip' do
    source "http://chefdeploy.local/chefdeploy/7zip/7z1604-x64.msi"
    action :install
    options "/qn"
end
```

Here's the pertinent output from a run (and [everything](https://gist.github.com/Cylindric/724e11343a7a873d8f4aa7c24d46c83d):

```
Recipe: my-7zip::default
  * windows_package[7-Zip] action install[2017-01-13T09:07:14+00:00] INFO: Processing windows_package[7-Zip] action install (my-7zip::default line 7)

  Recipe: <Dynamically Defined Resource>
    * remote_file[c:\chef\cache\package\7z1604-x64.msi] action create[2017-01-13T09:07:14+00:00] INFO: Processing remote_file[c:\chef\cache\package\7z1604-x64.msi] action create (dynamically defined)
 (up to date)
     (up to date)
```

That looks to me like it is up to date and shouldn't do anything, but I see an install dialog very briefly pop up on the server every time the client runs, and my Windows event logs also show an EventId 1033:

> Windows Installer installed the product. Product Name: 7-Zip 16.04 (x64 edition). Product Version: 16.04.00.0. Product Language: 1033. Manufacturer: Igor Pavlov. Installation success or error status: 0.

I have tried pinning the version in the recipe to `version "16.04.00.0"`, but that made no difference.

**Comment by Cylindric** [comment]
Interestingly, I get that EventLog entry 6 times every time the agent runs.

If I add a manual guard to the recipe, it works as expected:
```
powershell_script 'check-7zip-status' do
    code "$true"
    flags '-NoProfile -NoLogo -NonInteractive -ExecutionPolicy Bypass'
    guard_interpreter :powershell_script
    only_if 'If ((Get-WmiObject -Class Win32_Product | Where-Object { $_.Name -eq "7-Zip 16.04 (x64 edition)"}) -eq $null) { Return $True } Return $False'
    notifies :install, 'package[7-Zip]', :immediate
end

package '7-Zip' do
    source "http://chefdeploy.gator.local/chefdeploy/7zip/7z1604-x64.msi"
    action :nothing
    options "/qn"
end
```

**Comment by jugatsu** [comment]
```ruby
windows_package '7-Zip 9.20 (x64 edition)' do
    source "http://chefdeploy.local/chefdeploy/7zip/7z1604-x64.msi"
    action :install
    options "/qn"
end
```
Checkout DisplayName from HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Uninstall or Wow6432Node

https://docs.chef.io/resource_windows_package.html

Also try to use checksum to prevent downloading package every time.

**Comment by jugatsu** [comment]
The key is to use DisplayName in 'name'
```ruby
windows_package 'name' do
  checksum                   String
  installer_type             Symbol
  notifies                   # see description
  options                    String
  provider                   Chef::Provider::Package::Windows
  remote_file_attributes     Hash
  returns                    Integer, Array of integers
  source                     String # defaults to 'name' if not specified
  subscribes                 # see description
  timeout                    String, Integer
  action                     Symbol # defaults to :install if not specified
end
```

**Comment by Cylindric** [comment]
Okay, I have tried with the following, and I still get the (very quick) popup dialog come and go, and the EventLog still has "Windows Installer installed the product. Product Name: 7-Zip 16.04 (x64 edition). Product Version: 16.04.00.0. Product Language: 1033. Manufacturer: Igor Pavlov. Installation success or error status: 0." in it.

```
package '7-Zip 16.04 (x64 edition)' do
    source "http://chefdeploy.local/chefdeploy/7zip/7z1604-x64.msi"
    action :install
    options "/qn"
end
```

The name is that as shown when running ohai on the server.

I am running a single-recipe run of `chef-client -o "recipe[7zip]"`, so it's definitely this recipe.

**Comment by jugatsu** [comment]
Can you run chef-client with -l debug and paste output to gist?

**Comment by Cylindric** [comment]
I've put it up here: https://gist.github.com/Cylindric/19b353efd4bee7c6b755466d9b8ae2d9

It's weird, it certainly seems to be correctly determining that it doesn't need to be installed, and yet my event logs show something that looks like it is, and it is popping up on the screen.
windows_package[7-Zip 16.04 (x64 edition)] fetched source file to c:\chef\cache\package\7z1604-x64.msi

```
windows_package[7-Zip 16.04 (x64 edition)] getting product code for package at c:\chef\cache\package\7z1604-x64.msi
windows_package[7-Zip 16.04 (x64 edition)] checking package status and version for {23170F69-40C1-2702-1604-000001000000}
windows_package[7-Zip 16.04 (x64 edition)] getting product version for package at c:\chef\cache\package\7z1604-x64.msi
windows_package[7-Zip 16.04 (x64 edition)] getting product version for package at c:\chef\cache\package\7z1604-x64.msi
Checking if windows_package[7-Zip 16.04 (x64 edition)] version '16.04.00.0' is already installed. 16.04.00.0 is currently installed
windows_package[7-Zip 16.04 (x64 edition)] 7-Zip 16.04 (x64 edition) 16.04.00.0 satisifies 16.04.00.0 requirement
windows_package[7-Zip 16.04 (x64 edition)] is already installed - nothing to do

```

I also have 6 Event Log entries with EventID 1033 from MsiInstaller at 08:39:27

**Comment by jugatsu** [comment]
I think pop-up

> windows_package[7-Zip 16.04 (x64 edition)] fetched source file to c:\chef\cache\package\7z1604-x64.msi

means that it actually fetching MSI from http://chefdeploy.local/chefdeploy/7zip/7z1604-x64.msi because you didn't provide checksum to windows_package resource.
```ruby
[2017-01-17T08:39:27+00:00] INFO: Processing remote_file[c:\chef\cache\package\7z1604-x64.msi] action create (dynamically defined)
[2017-01-17T08:39:27+00:00] DEBUG: remote_file[c:\chef\cache\package\7z1604-x64.msi] checksumming file at c:\chef\cache\package\7z1604-x64.msi.
[2017-01-17T08:39:27+00:00] DEBUG: remote_file[c:\chef\cache\package\7z1604-x64.msi] checking for changes
```

**Comment by Cylindric** [comment]
That's interesting, I didn't expect to see any sort of dialog during downloads. Also, I thought it would detect the file from the cache headers. I'll have to check my IIS settings to make sure it's setting them correctly I guess.

**Comment by Cylindric** [comment]
I was basing that assumption off this:

> The use_conditional_get attribute is the default behavior of the chef-client. If the remote file is located on a server that supports ETag and/or If-Modified-Since headers, the chef-client will use a conditional GET to determine if the file has been updated. If the file has been updated, the chef-client will re-download the file.

And the log output of

```
---- HTTP Request Header Data: ----
if-modified-since: Tue, 01 Nov 2016 16:22:06 GMT
if-none-match: "754272f25734d21:0"
Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
---- End HTTP Request Header Data ----
---- HTTP Status and Header Data: ----
HTTP 1.1 304 Not Modified
accept-ranges: bytes
etag: "754272f25734d21:0"
server: Microsoft-IIS/8.5
x-powered-by: ASP.NET
date: Tue, 17 Jan 2017 08:39:27 GMT
connection: close
---- End HTTP Status/Header Data ----

```

**Comment by jugatsu** [comment]
Just add checksum to windows_package resource like this
```ruby
windows_package '7-Zip 16.04 (x64 edition)' do
    source "http://chefdeploy.local/chefdeploy/7zip/7z1604-x64.msi"
    checksum 'HERE_IS_CHECKSUM'
    action :install
    options "/qn"
end
```

To calculate checksum use (linux example)
```ruby
sha256sum LOCAL_PATH/7z1604-x64.msi
```

**Comment by Cylindric** [comment]
Cool, I can do that. Do you know if there are any plans to make it work like the remote_file? It seems to imply it is using that in the background, so I don't see why it can't use the same methods.

**Comment by jugatsu** [comment]
Are you sure that it was downloaded each time? Can you check with tcpdump or IIS logs? Because of that request
```ruby
---- HTTP Request Header Data: ----
if-modified-since: Tue, 01 Nov 2016 16:22:06 GMT
if-none-match: "754272f25734d21:0"
Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
---- End HTTP Request Header Data ----
---- HTTP Status and Header Data: ----
HTTP 1.1 304 Not Modified
accept-ranges: bytes
etag: "754272f25734d21:0"
server: Microsoft-IIS/8.5
x-powered-by: ASP.NET
date: Tue, 17 Jan 2017 08:39:27 GMT
connection: close
---- End HTTP Status/Header Data ----
```
it should't.

Othewise i consider that it's a bug and you should make seperate issue.

**Comment by Cylindric** [comment]
Okay, I enabled PacketBeat for that server so I get all the packet logs. 

It is definitely not fetching the zip each time, I'm only seeing a small conditional GET, as we'd expect from the debug logs, so that's working fine.

I also updated the client to 12.17.44 just to be sure it's not something old.

I'm still seeing popups for a fraction of a second every time Chef runs, and 6 MSI events in the logs, but Process Monitor doesn't show any modified files. All very odd.

For now I'll just use the checksum to prevent the flickering - it can be dangerous if it grabs or changes focus while entering stuff from a console session - but it is weird.

**Comment by rneu31** [comment]
#5745 may be relevant.

**Comment by btm** [comment]
@Cylindric Are you running the 64bit or 32bit version of Chef?

**Comment by btm** [comment]
The fact that the file is being downloaded every time appears to be a previously filed bug over here: https://github.com/chef/chef/issues/4916

The pop up you're seeing might not be an install but rather from the Windows Installer opening up the MSI to retrieve the product code.

**Comment by tduffield** [comment]
So the Windows Event you're seeing is a side-effect of how the MSI Installer and Chef work together. In order to get certain information about the application you wish to install (or that is already installed) we need [unpackage the MSI just enough to grab the Product Code and Version](https://github.com/chef/chef/blob/master/lib/chef/provider/package/windows/msi.rb#L48-L51). This action appears to trigger the 1033 event you're seeing in your Windows Events. The install, as indicated by the Chef Logs, is not happening on every run.

**Comment by dheerajd-msys** [comment]
I have verified on `Windows Server 2012R2 servers, running chef-client 12.19.36` that running the `windows_package` multiple times doesn't install the package again.
```
[2017-03-30T10:03:42+00:00] DEBUG: windows_package[7-Zip 16.04 (x64 edition)] is already installed - nothing to do
     (up to date)
[2017-03-30T10:03:42+00:00] DEBUG: Exiting
```
Also it does not modify the Timestamp of installer on every run if already downloaded.
I have verified it with timestamp of local path of the installer where it was downloaded on my VM and checked from `Registry Editor` and `Install Date` remains same if already installed.

Please refer http://www.itninja.com/blog/view/the-complete-guide-to-msi-switches-for-silent-software-installation the line `In a silent installation, everything that happens after you initiate the installer occurs without interactively prompting the user. Some dialog boxes might pop up, but they'll disappear on their own` satisfies the popups we see during the chef-run.

Please close this issue if information is helpful.
