### ISSUE TITLE
chef-server-ctl user-create misleading error message

### ISSUE THREAD

**Issue by ricksebak** [chef/chef#5733]
## Description

Using chef-server-ctl, if you try to create a user, and that user has the same email address as another already-existing user, you will get an error saying that the user you are trying to create already exists. This is misleading because the user you are trying to create doesn't already exist, you just need to use a unique email address for the new user.

## Chef Version

chef-server-core-12.11.1-1.el7.x86_64

## Platform Version

RHEL 7

## Replication Case

```
[root@ip-10-177-178-11 ec2-user]# chef-server-ctl user-list
john_robison
pivotal
[root@ip-10-177-178-11 ec2-user]# chef-server-ctl user-show john_robison | grep email
email:        john.robison@cloudreach.com
[root@ip-10-177-178-11 ec2-user]# chef-server-ctl user-create other_user Other User john.robison@cloudreach.com somepassword
ERROR: Conflict
Response: User 'other_user' already exists
```

## Client Output

See above

## Stacktrace

No stacktrace

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* [Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by thommay** [comment]
Hi,
Thanks for your bug report, but this repository is for chef client issues only. Please report chef server issues to https://github.com/chef/chef-server/issues/new .
I'll be closing this ticket now.
Thanks,
-Thom
