### ISSUE TITLE
--force-formatter not working in daemon mode

### ISSUE THREAD

**Issue by railsmith** [chef/chef#5738]
## Description

Running the chef-client with `--force-formatter` option in daemon mode still gives logger output instead of formatter output.

    chef-client -d -i 60 -l info -L /var/log/chef/client.log --force-formatter

## Chef Version

12.14

## Platform Version

Redhat 6

## Replication Case

Run the chef-client in daemon mode with --force-formatter option.

    chef-client -d -i 60 -l info -L /var/log/chef/client.log --force-formatter

Expected output - Chef should use the default formatter instead of logger output.

**Comment by lamont-granquist** [comment]
`-l info` is going to give info message output which is not the default for the formatter.  you probably want `-l warn` or `-l auto` or just leave that option off.

**Comment by railsmith** [comment]
It seems formatter does not get activated unless the chef-client is run from a tty and [Chef daemon](https://github.com/chef/chef/blob/db57131ad383076391b9df32d5e9989cfb312d58/lib/chef/daemon.rb) does not log anything to STDOUT which means I cannot do `>> /var/log/chef/client.log` either.

**Comment by lamont-granquist** [comment]
validated that this fails for some reason, going to need to be fixed as part of #2514 in Chef 13

**Comment by railsmith** [comment]
Is there a workaround I can try for Chef 12 now? I just need to capture the `live_stream` of the execute resource to a log file in the chef events handler. Should I hook on to `stream_output` event handler? Our client has bought enterprise Chef license and its critical for us to log everything as much as we can which will help them to debug their business operations.

**Comment by coderanger** [comment]
@railsmith The formatter output is only intended for humans and would be very difficult to parse/search in an automated way. If they have a premium features license you want to be using the DataCollector system which is enabled automatically with Chef Automate I think.

**Comment by railsmith** [comment]
I have done the following workaround for now.

     chef-client -d -i 60 -l info -L /var/log/chef/client.log -F doc --force-formatter

and capturing the `live_stream` in the chef-client event handlers

     Chef.event_handler do
         on :stream_output do |stream, output, options|
         end
      end

**Comment by tas50** [comment]
I'm assigning this to the sustaining team to see if this is still an issue after our most recent logging cleanup.

**Comment by lamont-granquist** [comment]
labelled as "Critical" just to get the replication done soon because I want to work on fixing this stuff soon.

**Comment by lamont-granquist** [comment]
(this is one that i'll proably wind up working so only the replication is critical)

**Comment by lamont-granquist** [comment]
should be addressed as part of #9126
