### ISSUE TITLE
Successful `knife environment from file` spits output to stderr instead of stdout

### ISSUE THREAD

**Issue by poliva83** [chef/chef#5739]
## Description

Noticed after upgrading workstations to use chefdk 1.1.16 that some scripts were breaking. Turns out its related to `knife environment from file` returning output to stderr instead of stdout. Confirmed it happens with `knife role from file` as well.

## Chef Version
chef (12.17.44) [on workstation that installed chefdk (1.1.16)]

```
chef@ws:~$ head /opt/chefdk/version-manifest.txt
chefdk 1.1.16
```

## Platform Version

Ubuntu 14.04

## Replication Case
```
irb(main):001:0> require 'mixlib/shellout'
irb(main):002:0> x = Mixlib::ShellOut.new('/usr/bin/knife environment from file /opt/gitchefsync/staging/mand-common_global_chef_env/chef-repo/bbdba/environments/bbdba-chan-cassandra-deb-orion.json --yes', {})
=> <Mixlib::ShellOut#15463280: command: '/usr/bin/knife environment from file /opt/gitchefsync/staging/mand-common_global_chef_env/chef-repo/bbdba/environments/bbdba-chan-cassandra-deb-orion.json --yes' process_status: nil stdout: '' stderr: '' child_pid: nil environment: {} timeout: 600 user:  group:  working_dir:  >
irb(main):003:0> x.run_command
=> <Mixlib::ShellOut#15463280: command: '/usr/bin/knife environment from file /opt/gitchefsync/staging/mand-common_global_chef_env/chef-repo/bbdba/environments/bbdba-chan-cassandra-deb-orion.json --yes' process_status: #<Process::Status: pid 21984 exit 0> stdout: '' stderr: 'Updated Environment bbdba-chan-cassandra-deb-orion' child_pid: 21984 environment: {} timeout: 600 user:  group:  working_dir:  >
```

**Comment by poliva83** [comment]
Note that `knife cookbook upload -a` also sends output to stderr on a success. However interestingly successful deletion of cookbook via `knife cookbook delete` prints only to stdout.

**Comment by roccomuscaritolo-okta** [comment]
I noticed the same thing today. Very strange choice.

**Comment by snehaldwivedi** [comment]
@lamont-granquist @marcparadise In ui.rb (https://github.com/chef/chef/blob/master/knife/lib/chef/knife/core/ui.rb#L99) & https://github.com/chef/chef/blob/master/knife/lib/chef/knife/core/ui.rb#L121 stderr is being used to spit output for all logs. In many knife operations output is getting rendered in stderr, so if I make a change to handle this one scenario it's breaking existing behaviors at many places. Please confirm if I should move forward to do it?
