### ISSUE TITLE
SSH issues between Chef and Kitchen

### ISSUE THREAD

**Issue by coderanger** [chef/chef#5740]
Filing this over here because I think it was a Chef change that busted things.

The error looks like:

```
IOError: closed stream
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/buffered_io.rb:102:in `send'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/buffered_io.rb:102:in `send_pending'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/session.rb:271:in `block in ev_do_handle_events'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/session.rb:270:in `each'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/session.rb:270:in `ev_do_handle_events'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/event_loop.rb:110:in `ev_select_and_postprocess'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/event_loop.rb:29:in `process'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/session.rb:216:in `process'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/session.rb:178:in `block in loop'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/session.rb:178:in `loop'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-ssh-4.0.1/lib/net/ssh/connection/session.rb:178:in `loop'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:802:in `loop'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:730:in `close_channel'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/kitchen-sync-2.1.1/lib/kitchen/transport/sftp.rb:54:in `close'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/test-kitchen-2ce46e6e369e/lib/kitchen/transport/ssh.rb:98:in `cleanup!'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/test-kitchen-2ce46e6e369e/lib/kitchen/instance.rb:285:in `cleanup!'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/test-kitchen-2ce46e6e369e/lib/kitchen/command.rb:205:in `run_action_in_thread'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/test-kitchen-2ce46e6e369e/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
  /Users/coderanger/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/logging-2.1.0/lib/logging/diagnostic_context.rb:450:in `block in create_with_logging_context'
```

Specifically the trigger seems to require testing multiple instances (it crashes when trying to connect to the second instance) via `kitchen test`, and requires either a lot of output or time so a no-op test case won't trigger it. Still trying to nail down specifics on the trigger but I do have a lot of repro cases. Only happening with Chef master currently, but I haven't tested the 12.18 pre-release, also happens with both release and master of kitchen.

**Comment by tduffield** [comment]
This might be a result of the recent upgrade of net-ssh, which happened on both chef and test-kitchen.

**Comment by coderanger** [comment]
Yeah, seems likely. Do you know if that change was in 12.18's release candidate?

**Comment by tduffield** [comment]
@coderanger let me get back to you on that. I think we miscommunicated the version of chef we intend to release as 12.18.

**Comment by tduffield** [comment]
Okay. So, a couple of things to clarify.

1. I said net-ssh was upgraded on master, I was incorrect. The PR to update net-ssh to 4.0.1 is #5735 (which has yet to be merged). The major version difference between chef and test-kitchen could be the source of your issue. 
2. As the net-ssh stuff has yet to be merged, it will not be in our pre-release version. That being said, we miscommunicated our pre-release version in the announcement yesterday (which we are now correcting).

**Comment by coderanger** [comment]
@tduffield Which version should I test for the pre-release?

**Comment by tduffield** [comment]
@coderanger 12.18.31

**Comment by coderanger** [comment]
Okay, no repro on 12.18.31 so not a blocker for the release, but still something WTF-y is happening :)

Going to try and narrow down when it happened.

**Comment by lamont-granquist** [comment]
this looks like a t-k / net-ssh 4.0.x bug, i don't think its a chef/chef issue.  kind of smells like it might be a net-ssh 4.x bug...

**Comment by coderanger** [comment]
Yep, the specific commit that triggers the bug is https://github.com/chef/chef/commit/31b5aabd2c2ff37b0eba63033971087f1c6db000 so almost certainly a net-ssh major version compat issue.

**Comment by lamont-granquist** [comment]
what happens if you install the gems in the bundle to support ed25519 keys?

see comment here:

https://github.com/test-kitchen/test-kitchen/issues/1075#issuecomment-259272666

the problem may be that we bumped net-ssh to 4.x in t-k but didn't include:

```
  s.add_dependency "rbnacl-libsodium", "~> 1.0.0"
  s.add_dependency "rbnacl", "~> 4.0.0"
  s.add_dependency "bcrypt_pbkdf", "~> 1.0.0"
```

**Comment by coderanger** [comment]
@lamont-granquist I'm running it all under bundler so it would get those gems from Chef regardless. I think the issue is that previously the chef gem was forcing net-ssh to 3.x so we didn't notice the 4.x compat issues. The fact that it only happens on the second connection makes me think its a global state issue somewhere.

**Comment by lamont-granquist** [comment]
fds are global state.    mismanagement of fds in net-ssh/net-sftp?

**Comment by coderanger** [comment]
Going to move this over to the TK repo since I don't think Chef did anything wrong, just happened to be a chef commit that exposed the problem.
