### ISSUE TITLE
environments - allow only listed cookbooks

### ISSUE THREAD

**Issue by axos88** [chef/chef#5741]
## Description

It seems impossible to currently restrict - say the production environment - to only the cookbooks listed.
Any cookbooks that are unlisted are currently permitted without version restriction.

It would be great if we could do that, and be sure that all our cookbooks have the correct version restrictions

## Chef Version

12.17

**Comment by atheiman** [comment]
I dont know of a way to prevent including cookbooks not listed in an environment, however you can pin all versions in an environment using a Berksfile.lock and `berks apply` from the Berkshelf gem:

```
$ berks apply --help
Usage:
  berks apply ENVIRONMENT

Options:
  -f, [--envfile=ENVFILE]                # Path to a JSON environment file to update.
  -b, [--lockfile=PATH]                  # Path to a Berksfile.lock to operate off of.
                                         # Default: Berksfile.lock
      [--ssl-verify], [--no-ssl-verify]  # Disable/Enable SSL verification when locking cookbooks.
  -c, [--config=PATH]                    # Path to Berkshelf configuration to use.
  -F, [--format=FORMAT]                  # Output format to use.
                                         # Default: human
  -q, [--quiet], [--no-quiet]            # Silence all informational output.
  -d, [--debug], [--no-debug]            # Output debug information
```

**Comment by cheeseplus** [comment]
This is mostly an issue of workflow - if you want tighter locks I'd check out [Policyfiles](http://hedge-ops.com/policyfiles/) or something like the Environment Cookbook pattern. Doing this would require significant changes to chef-server and is very unlikely to happen given the existence of workflows that solve for this problem.
