### ISSUE TITLE
apt_package should support local installation of deb packages providing a less horrible interface than apt itself

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#5760]
see #5685

the typical way that ubuntu/debian admins install a local package on the command line and get depsolving is to either:

- `apt-get install -f ./package.deb` and have that fail
- `apt-get -yf install` when the former fails

or to:

- copy the deb to /var/cache/apt/archives/ 
- `apt-get install package`

see https://unix.stackexchange.com/questions/159094/how-to-install-a-deb-file-by-dpkg-i-or-by-apt

we should fix it so that users can just:

```ruby
apt_packge ./package.deb
```

and have it work the same way that yum supports `localinstall` of rpms transparently.

**Comment by coderanger** [comment]
I've always done this through https://launchpad.net/gdebi not `apt`.

**Comment by lamont-granquist** [comment]
that would get messy to have apt_package depend on that though.

**Comment by jugatsu** [comment]
How about dpkg -i for local installs? Example from ansible apt module below
https://github.com/ansible/ansible-modules-core/blob/devel/packaging/os/apt.py#L588

**Comment by coderanger** [comment]
@jugatsu That doesn't install deps and is already available via `dpkg_package`.

**Comment by renchap** [comment]
Starting with Debian Stretch `apt install ./package.deb` now works as expected and install the package dependencies.
The `apt_package` resource does not allow `source` to be defined, so you can not use this feature.

The provider should be changed so you can do something like:

```ruby
apt_package "mypackage" do
  action :install
  source "/var/cache/mypackage.deb"
end
```

It should work out of the box (with a recent `apt`) once the check in the current provider is removed.
