### ISSUE TITLE
Knife cookbook upload ignores chef-server port number specified in knife.rb

### ISSUE THREAD

**Issue by matalo33** [chef/chef#5761]
## Description

As a result of various 'security' requirements on my current chef deployment I have to tunnel knife traffic from my knife client machine to chef server. I have this value set in my knife.rb:

`server: "https://localhost:8890/organizations/my-org"`

This works fine, up until using **knife cookbook upload**

```
$ knife cookbook upload --verbose <cookbook>
INFO: Using configuration from /Users/matalo33/.chef/knife.rb
Uploading <cookbook> [<version>]
INFO: Validating ruby files
INFO: Validating templates
INFO: Syntax OK
INFO: Saving <cookbook>
INFO: Uploading files
ERROR: Connection refused connecting to https://localhost/bookshelf/organization-<hash>/checksum-<hash>?AWSAccessKeyId=<aws-key>&Expires=1485434250&Signature=<sig>, retry 1/5
```

**knife cookbook upload** drops the port 8890 specified in my config and tried to use port 443. If I set up a new tunnel forwarding port 443, without changing any knife config, the upload is successful.

## Chef Version

12.12.15

## Platform Version

macOS Sierra 10.12.2

## Replication Case

- Specify a custom port number in **server:** in knife.rb
- For testing this can be a locally forwarded port through SSH
- `ssh -L 8890:<chef-server>:443 user@host`
- Observe that knife functions as expected
- Try **knife cookbook upload** and notice it disregards the port in knife.rb and connects directly via port 443

**Comment by coderanger** [comment]
Unfortunately this isn't something Chef really supports. This isn't an issue in Chef itself, but with the protocol from Chef Server. The URL file uploads is sent _from_ the server not read from the confit file. As such there can be only a single canonical name use there. You can change it by setting the bookshelf URL and VIP setting in your Chef Server config.

**Comment by andreazorzetto** [comment]
Interesting to know. But doesn't explain why the error that I get back from knife is not in the attempt to get to the actual chef server URL but to the localhost URL (that I configured in the knife.rb) only missing the port:

ERROR: Connection refused connecting to https://**127.0.0.1**/organizations/orgname/env/c054828f422965664e2b30df1b866aaf, retry 1/5
ERROR: Connection refused connecting to https://**127.0.0.1**/organizations/orgname/env/c054828f422965664e2b30df1b866aaf, retry 2/5
...
...

If what you say is correct I should see something like this instead:

ERROR: Connection refused connecting to https://**server_url**/organizations/orgname/...

**Comment by chandtailor1** [comment]
I've had the same issue with "knife cookbook upload" - all other knife commands follow the chef server url specified in the knife.rb config file but "knife cookbook upload" doesn't follow this configuration.

I agree with @andreazorzetto in that it doesn't make sense for the chef server to give you the URL to upload the cookbook. This is a local command pushing cookbooks to the server rather than the server pulling from your remote machine.
