### ISSUE TITLE
Issue with chef user resource 

### ISSUE THREAD

**Issue by shubhamitc** [chef/chef#5767]
## Description

Chef-client is not working properly for User resource when used as an object of Chef::Resource::User class.

## Chef Version

Chefc-client above > chef13

## Platform Version

Centos 6.xx
## Replication Case

I am running the following in loop with different values of username. 
```
user= Chef::Resource::User.new('username', run_context)
				user.password 'hash'
				user.supports :manage_home => true
				user.home '/home/username'
				user.shell '/bin/bash'
              			user.action [:create, :modify]
 				user.run_action :create
				
```
## Client Output

```

 ================================================================================
      Error executing action `create` on resource 'user_resource_abstract_base_class[root]'
      ================================================================================
      
      NotImplementedError
      -------------------
      NotImplementedError
      
      Cookbook Trace:
      ---------------
      /var/chef/cache/cookbooks/config_common/recipes/user_groups.rb:55:in `block (4 levels) in from_file'
      /var/chef/cache/cookbooks/config_common/recipes/user_groups.rb:28:in `foreach'
      /var/chef/cache/cookbooks/config_common/recipes/user_groups.rb:28:in `block (3 levels) in from_file'
      /var/chef/cache/cookbooks/config_common/recipes/user_groups.rb:27:in `each'
      /var/chef/cache/cookbooks/config_common/recipes/user_groups.rb:27:in `block (2 levels) in from_file'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
      /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
      
      Compiled Resource:
      ------------------
      # Declared in 
      
      user_resource_abstract_base_class("root") do
        action [:create, :modify]
        supports {:manage_home=>true}
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        username "root"
        home "/root"
        shell "/bin/bash"
        password "$6$VcvJ7Na8/.tYT2a8$I4kaEiEU/dHlfo5zyWad/.I/NT7dmF7xElYbyGv8UEKYx3DcAAUS4abwPHHzJieaDGvlxF.OqlA//R9O.xTDU0"
        iterations 27855
      end
      
      Platform:
      ---------
      x86_64-linux
      
    
    ================================================================================
    Error executing action `run` on resource 'ruby_block[Create user and groups]'
    ================================================================================
    
    NotImplementedError
    -------------------
    user_resource_abstract_base_class[root] (dynamically defined) had an error: NotImplementedError: NotImplementedError
    
    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/config_common/recipes/user_groups.rb:55:in `block (4 levels) in from_file'
    /var/chef/cache/cookbooks/config_common/recipes/user_groups.rb:28:in `foreach'
    /var/chef/cache/cookbooks/config_common/recipes/user_groups.rb:28:in `block (3 levels) in from_file'
    /var/chef/cache/cookbooks/config_common/recipes/user_groups.rb:27:in `each'
    /var/chef/cache/cookbooks/config_common/recipes/user_groups.rb:27:in `block (2 levels) in from_file'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'




```

**Comment by thommay** [comment]
This looks like you're doing something you really shouldn't. Can you explain why you'd ever want to instantiate objects of `Chef::Resource::User` manually, especially since it looks a lot like you're just doing:
```
users.each do |u|
  user u
end
```
inside a ruby block rather than in the recipe.

**Comment by lamont-granquist** [comment]
yeah that's broken 100% deliberately. 

you can also use:

```ruby
declare_resource(:users, 'foo') do
  supports manage_home:  true
end
```

although i don't see why you'd need to do that.

**Comment by shortdudey123** [comment]
FWIW, `supports manage_home:  true` is deprecated and should be `manage_home:  true`

**Comment by lamont-granquist** [comment]
fixed.  i clearly need much more caffeine this morning...

**Comment by shubhamitc** [comment]
My user database is in GIT and we are trying to process it from there. Git sync will be performed on converge phrase, so will not be able to enumerate user array or hash as the file will be present on server. To make sure, user creating activity is performed after the git fetch/checkout is completed, i need to run this block of code inside ruby_block. 

I was not aware of @lamont-granquist 's declare_resource approach. Let me check it out.

**Comment by lamont-granquist** [comment]
```
i need to run this block of code inside ruby_block.
```

you probably don't, but you don't show exactly what you're doing, so i can only guess.   you should probably use a git resource that notifies a user resource.  if you need variables to be set for the username or whatever then you should pre-declare those in normal recipe code outside of the scope of the ruby_block you're using.

**Comment by shubhamitc** [comment]
In that case I will have to notify all the users resources. 
Idea here is to store the user/password data in GIT and be able to create and delete user from git itself so we can have an inbuilt audit. To achieve that we need to first download the file using git sync resource and then read all the lines from file to create users + groups. 
If you have any other alternatives I am very open to those suggestions.
Shubham

**Comment by lamont-granquist** [comment]
you can move your logic to a resource and force the git resource to run at compile time:

resources/default.rb:
```ruby
action :doit do
  git "stuff" do
    [ ... sync the git repo ... ]
  end.run_action(:sync)

  users = [ ... slurp into an array ... ]

  users.each do |user|
    user user.username do
      [ ... etc ... ]
    end
  end
end
```

by moving the git resource to compile time, you can avoid the ruby_block and can construct normal ruby variables and do typical looping constructs around creating users.

since the git resource might depend on prior recipes being completed, it most likely makes sense to move the logic into a resource so that the code still runs at converge time of the outer run context.

**Comment by tas50** [comment]
I'm going to close this out since it's been over a year and we haven't heard back with more information.
