### ISSUE TITLE
Please update Ohai to 8.23.0

### ISSUE THREAD

**Issue by erikng** [chef/chef#5775]
## Description

As of https://github.com/chef/ohai/commit/0d293ff3fa6af456f389a40b75e2c000ce0474bb, Ohai no longer requires Xcode Command Line tools to be installed on macOS.

Updating ohai in this repository would allow me to test these fixes in an official package.

## Chef Version

12.19.3 still contains the old Ohai version.

https://downloads.chef.io/chef/current/12.19.3

**Comment by coderanger** [comment]
This will happen as we prep for the 12.19 release over the next two weeks.

**Comment by tas50** [comment]
I kicked my PR with the update to see if I can get travis to pass

**Comment by erikng** [comment]
Thanks for the updates.

**Comment by lamont-granquist** [comment]
better tracked in #5757

**Comment by tas50** [comment]
This has been done on master
