### ISSUE TITLE
user resource "manage_home" doesn't create home directory for an existing user in CentOS 6

### ISSUE THREAD

**Issue by schredder** [chef/chef#5779]
## Description

The `user` resource's `manage_home` won't create the home directory for an existing user.

## Chef Version

chef-client 12.16.42

## Platform Version

CentOS 6.8 x86_64

## Replication Case

I'm using `kitchen` with `bento/centos-6.8` and VirtualBox.

To set up a contrived example, run a recipe that creates a user:
```
user 'foo' do
  action :create
end
```
...This should create the user, but not the home directory.

Then update the resource to ...
```
user 'foo' do
  action :create
  manage_home true
end
```
...and run `chef-client` to converge again. You should see that the `user` resource *does not* update, and a home directory still does not exist, despite that the `manage_home` property, according to the docs, [will create the home directory if it doesn't exist](https://docs.chef.io/resource_user.html#properties).

Compare that to a `chef-client` run that creates user `foo` with `manage_home true` set when the user doesn't already exist. The home directory is created as expected.

### Expected behavior

I would expect adding `manage_home true` to modify an existing user.
`CREATE_HOME` is set to `yes` in `/etc/login.defs` in `bento/centos-6.8` by default.

**Comment by shortdudey123** [comment]
It looks like for existing users, chef will not change the user with the action is `create` unless the new resource's home property is set and that is does not match the current users home. i.e. you need to add the `home` property

This is just based on reading the chef code base and i have not tested it to verify that works.

**Comment by schredder** [comment]
I modified my test so that the second chef-client run's recipe declares this:
```
user 'foo' do
  action :create
  home '/tmp/foo'
  manage_home true
end
```

`chef-client` will alter the user's `home` property (and report the updated resource), but the home directory (`/tmp/foo` in this case) still doesn't get created.

**Comment by shortdudey123** [comment]
Reading the chef make again makes me think that it should work, so i will let someone else chime in

**Comment by coderanger** [comment]
Unless something has changed we don't actually do the home dir creation, that's handled by the underlying useradd or whatever command. The `manage_home` option just corresponds to arguments passed to that command. As such, if they user already exists, no useradd is run, so nothing happens.

**Comment by shortdudey123** [comment]
The [`elsif`](https://github.com/chef/chef/blob/master/lib/chef/provider/user.rb#L131-L136) block get run though.  This should return true assuming that the users home dir is not the home being passed to the resource:

`return true if !@new_resource.home.nil? && Pathname.new(@new_resource.home).cleanpath != Pathname.new(@current_resource.home).cleanpath`

**Comment by coderanger** [comment]
Yes but on Linux that `manage_user` method ends up calling `usermod -m`:

> -m, --move-home
>  Move the content of the user's home directory to the new location.
>  This option is only valid in combination with the -d (or --home) option. 

As I said, the only thing that would actually create a homedir is the `useradd -m`, we don't have any code implementing that process.

**Comment by shortdudey123** [comment]
ah 👍

**Comment by ketan** [comment]
Is this a regression?

I was able to have chef create a home directory using chef `12.13.37`. However chef `13.2.20` seems to cause this to break.

To reproduce:

* create the files below in a directory.
* `docker build . -t foo --build-arg BUILD_NUMBER=0.17.17`
* `docker build . -t foo --build-arg BUILD_NUMBER=2.0.26`

With version of 0.17.17, the chef run completes, with 2.0.26, it fails.

```Dockerfile
# Dockerfile
FROM centos:6

COPY default.rb /default.rb
ARG BUILD_NUMBER

RUN rpm -ivh https://packages.chef.io/files/stable/chefdk/${BUILD_NUMBER}/el/6/chefdk-${BUILD_NUMBER}-1.el6.x86_64.rpm && \
    chef-solo --version && \
    chef-apply /default.rb
```

```ruby
# default.rb

user 'bob' do
  home '/bob'
  shell '/bin/bash'
end

ruby_block "assert home dir exists" do
  block do
    raise "Home dir does not exist" unless ::File.exist?('/bob')
  end
end
```

**Comment by coderanger** [comment]
@ketan You need to specify `manage_home true` on the user resource.

I'm closing this out as I don't think we're going to change this any time soon, scripting the actual homedir creation ourselves feels like it would get off in to the weeds too fast.

**Comment by jaymzh** [comment]
@coderanger the regression here is that when `manage_home` is **not** set to true we now pass in `-M`, but we didn't before. That means we no longer look a login.defs by default (per the docs), we explicitly tell useradd NOT to creat the homedir. It changed here:

https://github.com/chef/chef/commit/f769d7eba17b3f5aa9e0561126bd9f6801c1bac2#diff-96815653a34461853b36e515b424b39fR144

That's both in contradiction to the docs and to what I think most people would expect.

**Comment by jaymzh** [comment]
CC @lamont-granquist  who made that change.

**Comment by coderanger** [comment]
@jaymzh I think that was intentional, what is in the resource is now authoritative. Unless Lamont disagrees I still don’t see a bug here.

**Comment by jaymzh** [comment]
The docs say that unless specified, `login.defs` will be used. Which used to be true, but is no longer true. So changing that mid-12 is a regression. If you want to change that 12->13, so be it, update the docs and fix 12.

**Comment by jaymzh** [comment]
Quoting from https://docs.chef.io/resource_user.html

```
With the :create action, a user’s home directory is created based on HOME_DIR. If the home directory is missing, it is created unless CREATE_HOME in /etc/login.defs is set to no. When created, a skeleton set of files and sub-directories is also created in the home directory.
```

Which is actually even MORE wrong now that I read it again. It says that file always takes precedence, but it doesn't. It takes precedence only if the user didn't ask Chef to override it. So the docs are super wrong either way... and this was definitely a breaking change to make mid-major version.

**Comment by coderanger** [comment]
I apologize for the incorrect docs, we'll get those fixed up on Monday. As for the compat break, we do our best but sometimes they happen given human fallibility. I'll happily accept a patch, but at this time the open-source side of the Chef project is only proactively maintaining security fixes for Chef 12, and as this reversion has been in place for over a year now (that commit shipped in Chef 12.14) it might actually do more harm than good to correct it at this point, though I happily defer to the wisdom of @thommay and @lamont-granquist on that.

**Comment by lamont-granquist** [comment]
I believe this came down to a difference in the way the provider behaved without any explicit setting of `manage_home` in the resource where ubuntu and centos differed in their default behavior so that Chef differed in its behavior.  I think that commit fixed it by asserting that the debian way was the way of truth and that it broke centos by design.  That is now authoritative and the docs should just get updated.

And if we change it back now we wind up causing regressions in everyone who has been using it since 12.14.x which is ~14 months.

That was also done in the depths of Chef-12 going on for 2.5 years or whatever with no breaking changes being "allowed" so we started to sneak in breaking changes anyway.  Sort of apologies, but also this is why we need yearly breaking change releases at a minimum.

**Comment by lamont-granquist** [comment]
(also i think these were two separate issues -- the original issue in the OP is still legit -- although i agree that the priority was so low that we were never likely to fix it so agree with @coderanger's decision to just close it -- although if anyone really wants to scratch an itch and fix it we wouldn't necessarily say 'no' to the PR, although it would need to not be overly messy+hacky and would need to cleanly implement the behavior and get all the edge cases correctly).

**Comment by jaymzh** [comment]
That's fine, but please dont' close this until the docs reflect reality.

**Comment by cdbattags** [comment]
Any updates on this?

**Comment by yangpeng-chn** [comment]
Experienced same issue with `Chef Infra Client: 15.0.298`.

**Comment by jqassar** [comment]
Yes, this is still happening with current chef-infra.
