### ISSUE TITLE
pacman_package won't install multiple packages

### ISSUE THREAD

**Issue by zfjagann** [chef/chef#5780]
## Description

`pacman_package` fails if you give it an array in `package_name`

## Chef Version

```
$ chef --version
Chef Development Kit Version: 1.1.16
chef-client version: 12.17.44
delivery version: master (83358fb62c0f711c70ad5a81030a6cae4017f103)
berks version: 5.2.0
kitchen version: 1.14.2
```

## Platform Version

Arch Linux

## Replication Case

```
pacman_package 'tools' do
  package_name ['tmux', 'git', 'hg']
  action :upgrade
end
```

## Client Output

    ================================================================================
    Error executing action `upgrade` on resource 'package[x11 utils]'
    ================================================================================

    TypeError
    ---------
    no implicit conversion of Array into String

    Resource Declaration:
    ---------------------
    # In /etc/chef/local-mode-cache/cache/cookbooks/base/recipes/x11.rb

     51: package 'x11 utils' do
     52:   package_name x_packages + fonts
     53:   action :upgrade
     54: end
     55:

    Compiled Resource:
    ------------------
    # Declared in /etc/chef/local-mode-cache/cache/cookbooks/base/recipes/x11.rb:51:in `from_file'

    package("x11 utils") do
      package_name ["xorg-server", "xorg-xinit", "xorg-xrandr", "arandr", "pulseaudio", "alsa-utils", "ttf-arphic-ukai", "ttf-arphic-uming", "ttf-baekmuk", "ttf-bitstream-vera", "ttf-cheapskate", "ttf-dejavu", "ttf-freebanglafont", "ttf-freefont", "ttf-hannom", "ttf-indic-otf", "ttf-junicode", "ttf-khmer", "ttf-linux-libertine", "ttf-mph-2b-damase", "ttf-sazanami", "ttf-tibetan-machine", "ttf-ubraille", "ttf-anonymous-pro", "ttf-droid","ttf-fira-mono", "ttf-fira-sans", "ttf-gentium", "ttf-hanazono", "ttf-inconsolata", "ttf-ionicons", "ttf-liberation", "ttf-linux-libertine-g", "ttf-symbola", "ttf-ubuntu-font-family"]
      action [:upgrade]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "base"
      recipe_name "x11"
    end

[full output](https://gist.github.com/zfjagann/c6a011d0e7a328fbafabcd594c726031)

## Stacktrace

[full output, including stacktrace](https://gist.github.com/zfjagann/c6a011d0e7a328fbafabcd594c726031)

**Comment by lamont-granquist** [comment]
the mutipackage feature has never been implemented on it.  fixing yum and dnf and gem_package along with multipackage homebrew are all higher priorities.

**Comment by zfjagann** [comment]
@lamont-granquist: that's fine, I just wanted to raise it as an issue. I'll take a stab at a PR for this when I find some free time. :)
