### ISSUE TITLE
knife bootstrap and knife ssh:  "could not settle on host_key algorithm"

### ISSUE THREAD

**Issue by djcode** [chef/chef#5813]
## Description

It appears that the version of net-ssh that Chef uses contains this bug: https://github.com/net-ssh/net-ssh/issues/314

## Chef Version

Chef: 12.18.31

## Platform Version

Mac OS X Sierra

## Replication Case

Add the lines:
```
Host *
  HostKeyAlgorithms +ssh-dss
```
to ~/.ssh/config and then try to knife bootstrap a machine with a DSA key.

## Client Output
```
WARNING: Failed to connect to <hostname> -- Net::SSH::Exception: could not settle on host_key algorithm
```

**Comment by lamont-granquist** [comment]
this is not terribly useful for tracking -- this bug gets fixed when we pull in the upstream net-ssh -- there's no code for us to fix here.
