### ISSUE TITLE
We should update the default data bag encryption version for Chef 13

### ISSUE THREAD

**Issue by coderanger** [chef/chef#5819]
Adding this so we don't forget. Unless someone has a really good reason we should bump the encryption version to 3 (it is currently 1) for Chef 13 because it's been long enough.

**Comment by thommay** [comment]
Annoyingly our docs say 0,1,2 and the code says 1,2,3; so we should fix that too.
https://docs.chef.io/data_bags.html#encryption-versions

**Comment by lamont-granquist** [comment]
should also make sure that mixlib-auth is using 1.3 by default, and consider dropping support for 1.0 and 1.1 (although probably not 1.2 since 1.3 only came out end of last year).

i don't have the history of that in my brain so don't know how disruptive any of that would be.
