### ISSUE TITLE
Use a real KDF for data bag encryption secrets

### ISSUE THREAD

**Issue by coderanger** [chef/chef#5820]
Currently we use a single round of SHA256 for deriving the actual AES key. This is okay, but it would be better to use a real-er key derivation function some day like PBKDF2 or if we want to be really fancy, Argon2. This would require a new encryptor version most likely so it will probably take a while to get this in.

**Comment by coderanger** [comment]
Just for the sake of prioritization I can't think of an attack where this would matter so probably can put it off until such time as we're making a v4 encryption for another reason and just slide it in for extra crypto points.

**Comment by tas50** [comment]
I'm going to close this out at this point since the future of secrets management in Chef Infra Client is not encrypted data bags.
