### ISSUE TITLE
Edit resource editing attributes not asked to. 

### ISSUE THREAD

**Issue by damacus** [chef/chef#5828]
## Description

When using two differently named custom_resources, the resource that is run second overwrites all attributes of the first, even if not asked to.  

See example here: 
https://gist.github.com/josqu4red/cbd422e9c875197b83d03112be53d4e2

## Chef Version

Latest

## Platform Version

Tell us which Operating System distribution and version chef-client is running on. Ubuntu, RHEL.

## Replication Case / Client Output

https://gist.github.com/josqu4red/cbd422e9c875197b83d03112be53d4e2

## Other

Tracking this bug at Samba Cookbook https://github.com/sous-chefs/samba/issues/56

**Comment by lamont-granquist** [comment]
reasonably certain this isn't a chef bug.

**Comment by damacus** [comment]
For future reference, resources that want to use the accumulator pattern must use: 
```ruby
action :nothing
delayed_action :create
```

rather than just `delayed_action :create`
