### ISSUE TITLE
Validation key is not reached

### ISSUE THREAD

**Issue by jeusdi** [chef/chef#5829]
## Description

Validation key is not reached...

## Chef Version

Chef Client, version 12.18.31

## Platform Version

Windows 10

## Replication Case

I'm trying to use `chef_client` as provisioner. Currently, I'm getting this message:

    ==> default: ================================================================================
    ==> default: Chef encountered an error attempting to create the client "vagrant-3ccfff14"
    ==> default: ================================================================================
    ==> default:
    ==> default: Authentication Error:
    ==> default: ---------------------
    ==> default: Failed to authenticate to the chef server (http 401).
    ==> default:
    ==> default: Server Response:
    ==> default: ----------------
    ==> default: Invalid signature for user or client 'living-digital-validator'
    ==> default:
    ==> default: Relevant Config Settings:
    ==> default: -------------------------
    ==> default: chef_server_url         "https://api.chef.io/..."
    ==> default: validation_client_name  "living-digital-validator"
    ==> default: validation_key          "/tmp/vagrant-chef/validation.pem"
    ==> default:
    ==> default: If these settings are correct, your validation_key may be invalid.
    ==> default:
    ==> default: Platform:
    ==> default: ---------
    ==> default: x86_64-linux
    ==> default:

It's trying to pick `validation_key` as `"/tmp/vagrant-chef/validation.pem"` instead of picking `living.pem` file I've set on `Vagrantfile`:

    config.vm.provision "chef_client" do |chef|
        chef.add_recipe 'custom_recipe'
        chef.chef_server_url = 'https://api.chef.io/...'
        chef.validation_key_path = 'living.pem'
        chef.validation_client_name = 'living-digital-validator'
    end

I'm using an account I've just created on Chef Server as cloud (Chef Manage).

Why is it picking a `pem` instead of I've set on `Vagranfile`?

I've created a `knife.rb` file this content:

    current_dir = File.dirname(__FILE__)
    log_level                :info
    log_location             STDOUT
    node_name                "living"
    client_key               "#{current_dir}/living.pem"
    chef_server_url          "https://api.chef.io/..."
    cookbook_path            ["#{current_dir}/../cookbooks"]

and then I've performed `knife ssl check`:

    Connecting to host api.chef.io:443
    Successfully verified certificates from `api.chef.io'

## Client Output

==> default: Running provisioner: chef_client...
==> default: Detected Chef (latest) is already installed
==> default: Creating folder to hold client key...
==> default: Uploading chef client validation key...
==> default: Generating chef JSON and uploading...
==> default: Running chef-client...
==> default: [2017-02-21T12:01:26+00:00] INFO: Forking chef instance to converge...
==> default: Starting Chef Client, version 12.18.31
==> default: [2017-02-21T12:01:26+00:00] INFO: *** Chef 12.18.31 ***
==> default: [2017-02-21T12:01:26+00:00] INFO: Platform: x86_64-linux
==> default: [2017-02-21T12:01:26+00:00] INFO: Chef-client pid: 9967
==> default: Creating a new client identity for vagrant-3ccfff14 using the validator key.
==> default: [2017-02-21T12:01:27+00:00] INFO: Client key client.pem is not present - registering
==> default: [2017-02-21T12:01:28+00:00] INFO: HTTP Request Returned 401 Unauthorized: error
==> default:
==> default: ================================================================================
==> default: Chef encountered an error attempting to create the client "vagrant-3ccfff14"
==> default: ================================================================================
==> default:
==> default: Authentication Error:
==> default: ---------------------
==> default: Failed to authenticate to the chef server (http 401).
==> default:
==> default: Server Response:
==> default: ----------------
==> default: Invalid signature for user or client 'living-digital-validator'
==> default:
==> default: Relevant Config Settings:
==> default: -------------------------
==> default: chef_server_url         "https://api.chef.io/organizations/living-digital"
==> default: validation_client_name  "living-digital-validator"
==> default: validation_key          "/tmp/vagrant-chef/validation.pem"
==> default:
==> default: If these settings are correct, your validation_key may be invalid.
==> default:
==> default: Platform:
==> default: ---------
==> default: x86_64-linux
==> default:
==> default:
==> default: Running handlers:
==> default: [2017-02-21T12:01:28+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2017-02-21T12:01:28+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 02 seconds
==> default: [2017-02-21T12:01:28+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2017-02-21T12:01:28+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2017-02-21T12:01:28+00:00] ERROR: 401 "Unauthorized"
==> default: [2017-02-21T12:01:28+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

## Stacktrace

It's empty

**Comment by cheeseplus** [comment]
This is how the Vagrant provisioner of Chef works and not chef-client itself. It will always rename the key on the guest https://github.com/mitchellh/vagrant/blob/9c299a2a357fcf87f356bb9d56e18a037a53d138/plugins/provisioners/chef/provisioner/chef_client.rb#L131-L133 so if you are getting an error it's most likely the validation key itself is bad/old/incorrect.

**Comment by cheeseplus** [comment]
Closing this as noted, it's an issue with how Vagrant works.
