### ISSUE TITLE
use `chef generate cookbook` instead of this command, but there is no such command

### ISSUE THREAD

**Issue by non7top** [chef/chef#5841]
## Description

```
# knife cookbook create phpapp
WARN: This command is being deprecated in favor of `chef generate cookbook` and will soon return an error.
Please use `chef generate cookbook` instead of this command.
 at /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.33/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'

# chef generate cookbook
-bash: chef: command not found
```

## Chef Version

Chef: 12.19.33

## Platform Version

CentOS release 6.8

**Comment by coderanger** [comment]
From your path you installed the `chef-client` installer that is meant for servers. You want the ChefDK installer instead, which is designed for workstations.

**Comment by tduffield** [comment]
https://downloads.chef.io/chefdk

**Comment by non7top** [comment]
Thanks, that is quite unobvious, considering none of the packages provides /usr/bin/chef

# yum whatprovides /usr/bin/chef
No Matches found

Do you have a hint about where I should report bugs for chef yum repositories?

**Comment by coderanger** [comment]
@non7top You probably didn't install via yum, since we don't really advertise that.

**Comment by tduffield** [comment]
@non7top if you wish to install the packages via Yum, make sure you're following the instructions here: https://docs.chef.io/packages.html.

If you did that, and its still the case that the yum whatprovides doesn't return, I will pass that along.

**Comment by non7top** [comment]
This is a link to the repo that I install the packages from.
https://packages.chef.io/stable-yum/el/6/$basearch

The reason why that repo does not provide /usr/bin/chef is because no package actually provides that, which is a bad packaging practice.

```
# rpm -qf `which chef`
file /usr/bin/chef is not owned by any package
```

I mean I added the repo, then ran `yum install chef` and surprisingly there was no 'chef' executable installed. Well that's fine, I then tried to install it by searching for that with `yum whatprovides /usr/bin/chef` which didn't help as well. The result is frustration.
