### ISSUE TITLE
Chef doesn't have access to a file created by itself, under the ownership of SYSTEM?

### ISSUE THREAD

**Issue by axos88** [chef/chef#5844]
## Description

Seems like chef is unable to converge the following resource AFTER it was already created (by itself on a prior run). Chef runs under the localsystem account.

```
	template file_path do
		source '.....'
		variables({
                  foo: bar
		})

		inherits false
		owner 'SYSTEM'
		rights :full_control, 'SYSTEM'
	end
```

## Chef Version

12.18.31

## Platform Version

Windows 2012R2

## Replication Case

Run a cookbook with above resource twice.

## Client Output

```
==> default:     Errno::EACCES
==> default:     -------------
==> default:     template[....] (C:/chef/cache/cookbooks/.... line ...) had an error: Errno::EACCES: Permission denied @ rb_sysopen - .....
==> default:     
```

**Comment by smurawski** [comment]
@axos88 Thanks for the report!

I did some testing and I can replicate the result.  From a bit of reading, it appears that the LocalSystem account uses either the `Builtin\Administrators` group token or the System token when accessing resources.  

By changing your example (and adding `:read` rights for the `Administrators` group) to 

```
template file_path do
		source '.....'
		variables({
                  foo: bar
		})

		inherits false
		owner 'SYSTEM'
		template file_path do
		source '.....'
		variables({
                  foo: bar
		})

		inherits false
		owner 'SYSTEM'
		rights :full_control, 'SYSTEM'
	        rights :read, 'Administrators'
	end
```

the chef-client run will be able to re-converge successfully.

**Comment by axos88** [comment]
@smurawski Please reopen.

This is a workaround, not a fix. 
And in case of a a jmx password file, it is not good enough, as the file may ONLY be readable by the user that starts the JVM. If any other users have read access (such as the Administrators in this case), it will bork with a fatal error, that the password file is not secure enough.

There must be a way to ensure that a file is only readable by the system user. It seems ridicolous that chef would be unable to read a file that it created itself, and is owned by the same user it is running under.
