### ISSUE TITLE
differing `knife search` results for `recipe:cookbook_name` and `recipe:cookbook_name\:\:default`

### ISSUE THREAD

**Issue by shoekstra** [chef/chef#5845]
When using knife search I receive different results for `recipe:mycookbook` and `recipe:mycookbook\:\:default` because some colleagues use `recipe[mycookbook::default]` in run lists and others use `recipe[mycookbook::default]`.

```
$ knife search node 'recipe:mycookbook'
19 items found

$ knife search node 'recipe:mycookbook\:\:default'
7 items found
```

As `recipe[mycookbook]` is short for `recipe[mycookbook::default]`, would it make sense to return the same results?

Using `recipe:mycookbook*` as my search does return the correct result (although don't feel this is the best solution):

```
$ knife search node 'recipe:mycookbook*'
26 items found
```

I also tried using `cookbook` and `cookbooks` but those returns different results too:

```
$ knife search node 'cookbook:mycookbook'
0 items found

$ knife search node 'cookbooks:mycookbook'
24 items found
```

**Comment by lamont-granquist** [comment]
pretty certain that is fixed by this commit:  https://github.com/chef/chef/pull/5833/commits/d8a2bc810381f58eeb4ecd4db7ff104038f8f97c

**Comment by shoekstra** [comment]
I'll close this for now then, thanks.
