### ISSUE TITLE
`group` resource not idempotent on Windows (12.19.36)

### ISSUE THREAD

**Issue by shoekstra** [chef/chef#5857]
## Description

Chef tries to create a group that already exists.

## Chef Version

Chef-client 12.19.36

## Platform Version

Discovered this on Windows 2012 R2, haven't tested others.

## Replication Case

I was creating a wrapper cookbook for the [sensu cookbook](https://github.com/sensu/sensu-chef) - to ensure [zap](https://github.com/nvwls/zap) does not delete the user and group created by the RPM I have this in my wrapper cookbook:

```
include_recipe 'sensu::default'

user node['sensu']['user']
group node['sensu']['group']
```

## Client Output

```
       ...
         * windows_user[sensu] action create[2017-03-02T23:18:28+01:00] INFO: Processing windows_user[sensu] action create (sensu::_windows line 22)
       [2017-03-02T23:18:28+01:00] INFO: windows_user[sensu] created
       
           - create user sensu
         * group[sensu] action manage[2017-03-02T23:18:28+01:00] INFO: Processing group[sensu] action manage (sensu::_windows line 27)
        (up to date)
       ...
         * windows_user[sensu] action create[2017-03-02T23:19:09+01:00] INFO: Processing windows_user[sensu] action create (sensu_wrapper::default line 13)
        (up to date)
         * group[sensu] action create[2017-03-02T23:19:09+01:00] INFO: Processing group[sensu] action create (sensu_wrapper::default line 14)
       
           
           ================================================================================
           Error executing action `create` on resource 'group[sensu]'
           ================================================================================
           
           ArgumentError
           -------------
           The account already exists.
           ---- Begin Win32 API output ----
           System Error Code: 2224
           System Error Message: The account already exists.
           ---- End Win32 API output ----
           
           Resource Declaration:
           ---------------------
           # In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/sensu_wrapper/recipes/default.rb
           
            14: group node['sensu']['group']
            15: 
```

**Comment by coderanger** [comment]
Windows doesn't allow users and groups with the same name.

**Comment by shoekstra** [comment]
I tried to manually create a group and could not so what you say is possible, but I've just noticed the first instance says `up to date`, the second one fails?

[This](https://github.com/sensu/sensu-chef/blob/develop/recipes/_windows.rb#L27-L30) still runs without error.  I can imagine this cookbook is fairly popular and if this was the cause of the problem it would've been picked up before.

I worked around this by doing the below in the wrapper and now my CI builds pass:

```
unless node['os'] == 'windows'
  user node['sensu']['user']
  group node['sensu']['group']
end
```

**Comment by shoekstra** [comment]
Is it possible that the first time Chef encounters this group resource it caches that the group doesn't exist and the second time uses the cached response instead of looking again?

Maybe a cloned resource only runs [`load_current_resource`](https://github.com/chef/chef/blob/master/lib/chef/provider/group/windows.rb#L36-L53) once?

**Comment by coderanger** [comment]
The "already exists" is because a user with that name exists and Windows sees those as being the same thing.

**Comment by shoekstra** [comment]
I'm still not 100% convinced I'm afraid - it seems when the resource does not appear twice in the chef run it works fine, when it does appear twice the chef run breaks.

Work around for me is to have that `unless` block in the `sensu-wrapper::default` recipe so that the only time the `user` and `group` resources appear is in the `sensu::_windows` recipe.

**Comment by smurawski** [comment]
@shoekstra, @coderanger  is correct.  You cannot have a user and group with the same name on a Windows system.  At the end of the day, both are Win32_Account(s) and the need to have unique names (which is why you have a default Administrator account and Administrators group).

Chef is doing the correct thing here in erroring, because it'll never be able to converge the system to a state where you have a user and group with the same name.
