### ISSUE TITLE
Cannot symlink /opt/javacode/shared/config/database.yml to /opt/javacode/releases/20170309121203/config/database.yml before migrate: No such file or directory @ rb_file_s_symlink - (/opt/javacode/shared/config/database.yml, /opt/javacode/releases/20170309121203/config/database.yml)

### ISSUE THREAD

**Issue by shivamec082** [chef/chef#5885]
## Description

I have a cookbook to deploy the code to chef server but facing issue.

## Chef Version

i am using chef server version 12.13
## Platform Version

i am using ubuntu 16.04

## Replication Case
 This my code

 deploy 'javacode' do
      repo 'https://github.com/shivamec082/javacode.git'
      user 'ubuntu'
     deploy_to '/opt/javacode'
   
      action :deploy
    before_migrate do
   
          link "/opt/javacode/shared/config/database.yml" do
           to " /opt/javacode/releases/20170309115633/config/database.yml"
   
     end
      end
   end
   cookbook_file"/usr/share/GitHub/www/index.html" do

## Client Output

Starting Chef Client, version 12.18.31
resolving cookbooks for run list: ["GitHub"]
Synchronizing Cookbooks:
  - GitHub (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 2 resources
Recipe: GitHub::default
  * deploy[javacode] action deploy (up to date)
  - force ownership of /opt/javacode to :ubuntu
  - deploy from repo to /opt/javacode/releases
  - force ownership of /opt/javacode to :ubuntu
  * link[/opt/javacode/shared/config/database.yml] action create
    - create symlink at /opt/javacode/shared/config/database.yml to  /opt/javacode/releases/20170309115633/config/database.yml
  - evaluate block and run any associated actions
  ================================================================================
  Error executing action `deploy` on resource 'deploy[javacode]'
  ================================================================================

  Chef::Exceptions::FileNotFound
  ------------------------------
  Cannot symlink /opt/javacode/shared/config/database.yml to /opt/javacode/releases/20170309120525/config/database.yml before migrate: No such file or directory @ rb_file_s_symlink - (/opt/javacode/shared/config/database.yml, /opt/javacode/releases/20170309120525/config/database.yml)

  Resource Declaration:
  ---------------------
  # In /var/chef/cache/cookbooks/GitHub/recipes/default.rb

   10: deploy 'javacode' do
   11:   repo 'https://github.com/shivamec082/javacode.git'
   12:   user 'ubuntu'
   13:   deploy_to '/opt/javacode'
   14:
   15:   action :deploy
   16: before_migrate do
   17:
   18:       link "/opt/javacode/shared/config/database.yml" do
   19:        to " /opt/javacode/releases/20170309115633/config/database.yml"
   20:
   21:      end
   22:   end
   23: end
   24: cookbook_file"/usr/share/GitHub/www/index.html" do

  Compiled Resource:
  ------------------
  # Declared in /var/chef/cache/cookbooks/GitHub/recipes/default.rb:10:in `from_file'

  deploy("javacode") do
    action [:deploy]
    retries 0
    retry_delay 2
    default_guard_interpreter :default
    deploy_to "/opt/javacode"
    repository_cache "cached-copy"
    purge_before_symlink ["log", "tmp/pids", "public/system"]
    create_dirs_before_symlink ["tmp", "public", "config"]
    symlink_before_migrate {"config/database.yml"=>"config/database.yml"}
    symlinks {"system"=>"public/system", "pids"=>"tmp/pids", "log"=>"log"}
    revision "HEAD"
    remote "origin"
    scm_provider Chef::Provider::Git
    keep_releases 5
    enable_checkout true
    checkout_branch "deploy"
    declared_type :deploy
    cookbook_name "GitHub"
    recipe_name "default"
    repo "https://github.com/shivamec082/javacode.git"
    user "ubuntu"
    before_migrate #<Proc:0x00000005c46490@/var/chef/cache/cookbooks/GitHub/recipes/default.rb:16>
    shared_path "/opt/javacode/shared"
    destination "/opt/javacode/shared/cached-copy"
    current_path "/opt/javacode/current"
  end

  Platform:
  ---------
  x86_64-linux

Running handlers:
[2017-03-09T12:05:26+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-03-09T12:05:26+00:00] ERROR: Exception handlers complete
Chef Client failed. 1 resources updated in 01 seconds
[2017-03-09T12:05:26+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-03-09T12:05:26+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-03-09T12:05:26+00:00] ERROR: deploy[javacode] (GitHub::default line 10) had an error: Chef::Exceptions::FileNotFound: Cannot symlink /opt/javacode/shared/config/database.yml to /opt/javacode/releases/20170309120525/config/database.yml before migrate: No such file or directory @ rb_file_s_symlink - (/opt/javacode/shared/config/database.yml, /opt/javacode/releases/20170309120525/config/database.yml)
[2017-03-09T12:05:26+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

## Stacktrace
Chef::Exceptions::FileNotFound: deploy[javacode] (GitHub::default line 10) had an error: Chef::Exceptions::FileNotFound: Cannot symlink /opt/javacode/shared/config/database.yml to /opt/javacode/releases/20170309122205/config/database.yml before migrate: No such file or directory @ rb_file_s_symlink - (/opt/javacode/shared/config/database.yml, /opt/javacode/releases/20170309122205/config/database.yml)
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:310:in `rescue in block (2 levels) in run_symlinks_before_migrate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:307:in `block (2 levels) in run_symlinks_before_migrate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:306:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:306:in `block in run_symlinks_before_migrate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider.rb:176:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:305:in `run_symlinks_before_migrate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:191:in `migrate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:160:in `deploy'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:109:in `block in action_deploy'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:440:in `with_rollback_on_error'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:108:in `action_deploy'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/resource.rb:622:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:670:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:665:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:665:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:704:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:284:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:295:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:283:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:283:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:248:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:57:in `load'
/usr/bin/chef-client:57:in `<main>'

>>>> Caused by Errno::ENOENT: No such file or directory @ rb_file_s_symlink - (/opt/javacode/shared/config/database.yml, /opt/javacode/releases/20170309122205/config/database.yml)
/opt/chef/embedded/lib/ruby/2.3.0/fileutils.rb:358:in `symlink'
/opt/chef/embedded/lib/ruby/2.3.0/fileutils.rb:358:in `block in ln_s'
/opt/chef/embedded/lib/ruby/2.3.0/fileutils.rb:1587:in `fu_each_src_dest0'
/opt/chef/embedded/lib/ruby/2.3.0/fileutils.rb:356:in `ln_s'
/opt/chef/embedded/lib/ruby/2.3.0/fileutils.rb:379:in `ln_sf'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:308:in `block (2 levels) in run_symlinks_before_migrate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:306:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:306:in `block in run_symlinks_before_migrate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider.rb:176:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:305:in `run_symlinks_before_migrate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:191:in `migrate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:160:in `deploy'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:109:in `block in action_deploy'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:440:in `with_rollback_on_error'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider/deploy.rb:108:in `action_deploy'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/provider.rb:145:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/resource.rb:622:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/runner.rb:69:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/runner.rb:97:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/runner.rb:97:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/runner.rb:97:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/2.3.0/forwardable.rb:189:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/runner.rb:96:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:670:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:665:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:665:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:704:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/client.rb:284:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:295:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:283:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:283:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:248:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:57:in `load'

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* Requests for new or alternative functionality should be made to [feedback.chef.io](https://feedback.chef.io/forums/301644-chef-product-feedback/category/110832-chef-client)
* [Chef Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by lamont-granquist** [comment]
you need directory resources for /opt/javacode/shared and /opt/javacode/shared/config to create those.

**Comment by shivamec082** [comment]
Hi,



I am totally new on this. I tried to create a directory structure using below code.

But getting unknown method error. Can you please assist me on directory resources for those directory.





directory '/opt/javacode/shared/config do
  owner 'root'
  group 'root'
  mode '0755'
  action :create
end

________________________________

**Comment by lamont-granquist** [comment]
this is the usual idiom to use:

```ruby
%w{ /opt/javacode/shared  /opt/javacode/shared/config }.each do |dir|
  directory dir do
    owner 'root'
    group 'root'
    mode '0755'
    action :create
  end
end
```

note that this issue is heading into territory better handled by asking questions on slack, stackoverflow or the chef mailing list/discourse -- we don't normally do user support on github issues, this is to file and fix bugs.
