### ISSUE TITLE
Missing output from systemd-analyze makes troubleshooting impossibly hard

### ISSUE THREAD

**Issue by axelrtgs** [chef/chef#5931]
## Description

Missing output from systemd-analyze makes troubleshooting impossibly hard

## Chef Version

chef-client 12.19.36

## Platform Version

Ubuntu 16.04

## Replication Case

create a systemd unit with invalid data, systemd-analyze will fail but chef will only indicate failure with no help of where, the systemd-analyze output would be very helpful for troubleshooting issues as it contains the exact errors.

## Client Output

ERROR: systemd_unit[app.service] (WebApps::app line 85) had an error: Chef::Exceptions::ValidationFailed: file[/etc/systemd/user/app.service] (dynamically defined) had an error: Chef::Exceptions::ValidationFailed: Proposed content for /etc/systemd/user/app.service failed verification #<Chef::Resource::File::Verification:0x00000004f19fb0>

**Comment by stresler** [comment]
This is exactly what I hit. I don't think this is a "Help Wanted" but a feature request. 

The systemd-analyze output is available it is just not making it into the chef output. My use case I described in the PR conversation here: https://github.com/chef/chef/pull/5765#issuecomment-288579727

Where it was indicated this should be a new issue.
