### ISSUE TITLE
Cloud instance resize

### ISSUE THREAD

**Issue by sumeetisp** [chef/chef#5939]
## Description

Is there any way we can resize/modify (like increase/decrease CPU or RAM) a cloud instance using chef(knife ec2) on any of the cloud providers?

**Comment by cheeseplus** [comment]
There isn't and knife-ec2 isn't really meant to be a complete suite for managing EC2 instances. Lots of provisioning tooling avoids this because of the nature of the process which has to stop the instance, resize it, and the start it again but I'd look at the AWS CLI and CloudFormation.
