### ISSUE TITLE
remote_file does not consider certificates stored under /etc/chef/trusted_certificates

### ISSUE THREAD

**Issue by carguel** [chef/chef#5944]
## Description

When using remote_file to download a file from a HTTPs server with a custom CA signed certificate, the CA Certificate stored under /etc/chef/trusted_certificates is not considered.
Therefore the download failed with the following error message:

```
remote_file[/var/chef/cache/ssha-0.0.3.gem] (common::_ldap_gems line 19) had an error: OpenSSL::SSL::SSLError: SSL Error connecting to https://srv.local:8443/packages-repo/gems/ssha-0.0.3.gem - SSL_connect returned=1 errno=0 state=error: certificate verify failed
```
Currently, it seems that to allow this verification to be successful, the CA certificate shall be included in /opt/chef/embedded/ssl/certs/cacert.pem 

## Chef Version
12.19.36

## Platform Version

RHEL 7

**Comment by capnregex** [comment]
Hit this myself this week..

**Comment by kapilchouhan99** [comment]
Hi @carguel could you please check it on latest version?
If you are still facing the same issue, please provide us steps to reproduce this issue and trace output.
Thank you!!!

**Comment by tas50** [comment]
@kapilchouhan99 This might be helpful: https://www.reddit.com/r/chef_opscode/comments/jvbzvp/windows_including_custom_certs_in_chefs_embedded/

**Comment by kimbernator** [comment]
@tas50 I appreciate you putting some momentum into this! Would definitely be helpful to have this fixed.
