### ISSUE TITLE
class_eval no longer work in Chef 13 builds

### ISSUE THREAD

**Issue by tas50** [chef/chef#5945]
For Chef 12.5-12.6 we needed to do do action_class.class_eval to avoid method missing errors. So we had rolled that out to a lot of cookbooks so we could get compatibility back to 12.5.1.  With the latest Chef 13 builds this is throwing an error now, which is resolved by removing class_eval. Unfortunately this breaks out compatibility with Chef 12.5-12.6. If we have to go 12.7+ I guess that's what we have to do, but ideally we could retain compat all the way back to the start of custom resources.

```
================================================================================
Recipe Compile Error in /opt/kitchen/cache/cookbooks/ohai/resources/hint.rb
================================================================================
NoMethodError
-------------
undefined method `class_eval' for nil:NilClass
Cookbook Trace:
---------------
  /opt/kitchen/cache/cookbooks/ohai/resources/hint.rb:5:in `class_from_file'
```

**Comment by lamont-granquist** [comment]
moving the helpers to the end of the file after the declaration of the action works around the bug.

action_class looks like it was designed to return nil if no action had been declared, and only construct the action_class if the action_class method was passed a block.  in 12.x something else must have been getting called that had the side effect of always creating the action_class and we removed that code.

fixing the bug might be as simple as always constructing the action_class when the helper method is called

**Comment by tas50** [comment]
Foodcritic rule time. Thanks for the info on this one. I'll make sure we do it right from now on

**Comment by lamont-granquist** [comment]
no, still working on fixing it, but its just a more tangled web of autovivifying accessors than was first apparent

**Comment by lamont-granquist** [comment]
#5946
