### ISSUE TITLE
knife bootstrap fails on ssh connection with Errno::ECONNRESET

### ISSUE THREAD

**Issue by mynamewastaken** [chef/chef#5950]
## Description

`knife bootstrap` fails with `ERROR: Errno::ECONNRESET: Connection reset by peer - recvfrom(2)` after I enter my credentials when trying to bootstrap a node. I'm trying to bootstrap from a Fedora 25 node to a Centos 7 node. Firewall is disabled on both nodes, and selinux was temporarily set to permissive during testing on remote Centos 7 node.

I can manually ssh to this node without problems. I can also do a `net-ssh::Start` in an `irb` session to connect as well, so I think this is an issue with `knife bootstrap`.

In the ssh logs on the bootstrap node side, I see an error about 'Bad packet length 292028.' I can consistently trigger that error log message with the `knife bootstrap` attempts.

## Chef Version

This happens with my initial chefdk version 1.2.22 as well as the version below which I upgraded to, to try and fix the issue:

```chef -v
Chef Development Kit Version: 1.3.23
chef-client version: 12.19.36
delivery version: master (efc4cb152d4f423b8dec781ba4d00f032c4881e0)
berks version: 5.6.3
kitchen version: 1.16.0
```

## Platform Version

Fedora 25 on Chef workstation (chefdk 1.3.23), Centos 7 on remote node.

## Replication Case

`knife bootstrap root@$host -N $host.$domain -y` This instantly fails with ECONNRESET

## Client Output

[gist for `knife bootstrap` output.](https://gist.github.com/mynamewastaken/6d538044714e06c8809a7c7fc33f0374)
[logs for sshd on the bootstrap node.](https://gist.github.com/mynamewastaken/0cf3ec86b320eaf0049a30a96f68c9dd)

**Comment by mynamewastaken** [comment]
Could this be an issue with ssh command length being exceeded? http://www.theeggeadventure.com/wikimedia/index.php/Ssh_argument_length

**Comment by tas50** [comment]
In Chef Infra Client 15 we rewrote the knife bootstrap functionality to use train. This radically changed how we bootstrap and more than likely resolves this. If you're still seeing the issue with Chef Infra Client 15 please feel free to open this backup.
