### ISSUE TITLE
powershell_script guard should default the user and password fields to the script resource

### ISSUE THREAD

**Issue by keyrage** [chef/chef#5951]
## Description

The error

"Mixlib::ShellOut::InvalidCommandOption: You must supply both a username and password when supplying a user in windows'
Occurs when a user and password are defined in a powershell_script resource and in which a guard is set. Removing the guard from the resource removes the error.

## Chef Version

Occurs in 12.19.36 (Haven't tried older clients)

## Platform Version
Tested on Windows Server 2012 R2

## Replication Case

	powershell_script 'SQL setup' do
		code <<-EOH
			$SQL_Server_ISO_Drive_Letter = (gwmi -Class Win32_LogicalDisk | Where-Object {$_.VolumeName -eq "SQLServer"}).DeviceID
			cd $SQL_Server_ISO_Drive_Letter\\
			$SQL_Install_Cmd=.\\setup.exe #{setup_args}
			$SQL_Install_Cmd>$env:TEMP\\sqlinstall.log
		EOH
		timeout 7200
		action :run
		guard_interpreter :powershell_script
		not_if "if (get-service -name \"#{defaultinstance}\"){$true}else{$false}"
		sensitive false
		user 'azure'
		password 'P2ssw0rd'
	end

## Client Output

Mixlib::ShellOut::InvalidCommandOption
 --------------------------------------
powershell_script[SQL setup] (C:/Users/azure/AppData/Local/Temp/kitchen/cache/cookbooks/poal_sqlserver/resources/sql2012.rb line 138) had an error: Mixlib::ShellOut::InvalidCommandOption: powershell_script[Guard resource] (dynamically defined) had an error: Mixlib::ShellOut::InvalidCommandOption: You must supply both a username and password when supplying a user in windows

**Comment by keyrage** [comment]
If I pass the user, password and domain variables as arguments after the guard then everything works as expected.
not_if "if (get-service -name \"#{defaultinstance}\"){$true}else{$false}", :user => 'azure', :password => 'P2ssw0rd', :domain => ''

**Comment by keyrage** [comment]
I'd argue the best approach is for the guard to NOT use the credentials in the script resource but explicitly require them to be passed as arguments in the guard property. Rationale for that is  that there may be times where the guard script does not require alternate credentials or even vice versa. This approaches allows the most versatility rather than imposing a strict one to one relationship.

**Comment by jvogt** [comment]
I wrote a monkey patch to solve this for anything inheriting windows_script (ie: powershell_script and batch)

https://gist.github.com/jvogt/481b0478afb05ee819b57e7be9c06615

Just include this in your cookbook's `libraries` directory.

**Comment by jvogt** [comment]
BTW, the resource attributes passed to the guard are supplied by an instance variable `@class_inherited_attributes`.

Various resources depending on the `execute` resource use `Chef::Resource::Execute.set_guard_inherited_attributes` to add attributes to `@class_inherited_attributes`

The inheritance path from `powershell_script` down to `execute` is:

```powershell_script -> windows_script -> script -> execute```

According to the documentation, the `execute` resource should accept user/password/domain.  

So possibly `lib/chef/resource/execute.rb` would be the most logical place to add `:password` and `:domain` to `@class_inherited_attributes` _(instead of powershell_script, as I did in my monkey patch)_

Just thinking out loud, if anyone from chef can give feedback, I'd be happy to submit a PR.

**Comment by jvogt** [comment]
@keyrage I'm sorry I didn't see your proposed solution, I think I agree with you except that at this point it would be a breaking change for anyone (presumably non-windows) using alternate credentials for their executes, who's guards are already running with the alternate credential.

**Comment by smastrorocco** [comment]
Hitting this issue on v13.8.5

Any fix in?
