### ISSUE TITLE
powershell_script's default guard_interpreter should be :powershell_script

### ISSUE THREAD

**Issue by Happycoil** [chef/chef#5953]
## Description

`powershell_script`'s default `guard_interpreter` should be `:powershell_script`. The vast majority of PowerShell script guards are also written in PowerShell, so having to add `guard_interpreter :powershell_script` to every single `powershell_script` resource seems unnecessary and confusing.

The default used to be `:powershell_script`, but was changed here: https://github.com/chef/chef/commit/a3aba411ccdf1a0a5f236ed3ce2a678a1892e29b#diff-fbc7a88e488de87fe1086188141990e8, was this intentional?

## Chef Version

12.4.0.rc1 and up

## Platform Version

Any windows version

**Comment by lamont-granquist** [comment]
doesn't look remotely intentional as far as i can tell.

PR to revert that change would be fine.
