### ISSUE TITLE
Chef 11.10 does not support success with exit status 1 for Upstart jobs

### ISSUE THREAD

**Issue by gdelprete-tl** [chef/chef#5955]
## Description

Chef 11.10 does not recognize 1 as a success exit status when it starts jobs with Upstart, which is issued when the job is already running. Therefore, the chef run aborts thinking there has been an error.

## Chef Version

Our Opsworks setup is to use chef-client in local mode, version 11.10.

## Platform Version

Amazon Linux AMI 2016.03

**Comment by coderanger** [comment]
As I mentioned in your StackOverflow question, 11.x is quite old and no longer under any semblance of support. Please try to reproduce this with a more recent release.

**Comment by lamont-granquist** [comment]
Chef-11 bugfixing ended a long time ago.
