### ISSUE TITLE
Knife search node should have a case insensitive option

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#5969]
At the very least we need to support adding case insensitivity as an option:

https://feedback.chef.io/forums/301644-chef-product-feedback/suggestions/17347648-provide-a-mechanism-to-disable-case-sensitivity-on

The fuzzifier (which I may move around in the code):

https://github.com/chef/chef/blob/388e33923ca50688e0aea546a6fdd815d2ef05ab/lib/chef/knife/search.rb#L154-L158

Could be extended so that knife search node would use case-insensitivity by default.

Knife ssh already should use the same fuzzifier as knife search node and we should fix that.

**Comment by ashwin-msys** [comment]
@lamont-granquist, This will require a change in chef-server code. We will need to dig deep into the search implementation. Should we proceed with the change?
