### ISSUE TITLE
verifications running before :before notifications executed cause unnecessary failures

### ISSUE THREAD

**Issue by nathwill** [chef/chef#5970]
## Description

verifiers are being run run before `:before` notification actions are executed on the target resource, so a resource that would pass verification if the before notification was run before the notifying resource was verified will unnecessarily fail.

## Chef Version

12.19.36

## Platform Version

CentOS 7.3

## Replication Case

in this (contrived) example, systemd has a dependency on the service unit existing before the corresponding socket unit can be created. if the before-notification was executed before the verification, this would work.

```
systemd_unit 'true.socket' do
  content({
    'Unit' => {
      'Description' => 'Truth Listen Socket'
    },
    'Socket' => {
      'ListenStream' => "0.0.0.0:9001"
    },
    'Install' => {
      'WantedBy' => 'sockets.target'
    }
  })
  action [:create, :enable, :start]
  notifies :create, 'systemd_unit[true.service]', :before
end

systemd_unit 'true.service' do
  content({
    'Unit' => {
      'Description' => 'Truth Service',
      'After' => 'network.target'
    },
    'Service' => {
      'StandardOutput' => 'null',
      'StandardError' => 'syslog',
      'ExecStart' => "/usr/bin/true",
      'Restart' => 'on-failure'
    },
    'Install' => {
      'WantedBy' => 'multi-user.target'
    }
  })
  action :create
end
```

## Client Output

[converge failure](https://gist.github.com/nathwill/7f45d374404fcc34fa9cba6007dd663e)

## Stacktrace

[stacktrace](https://gist.github.com/nathwill/6c14ab0c11c194d0f8afd654505df1fe)

**Comment by coderanger** [comment]
Why are you using a before notification for creating a unit?

**Comment by coderanger** [comment]
before notifications are pretty much exclusively built for the "I need to stop this service during upgrades or config changes and start it again after" use case, so this would only apply is the service resource had a verifier?

**Comment by nathwill** [comment]
@coderanger oh i'm not. like i said, it's a contrived example... it came up in #5909 and seemed like an oversight to me, so figured i'd raise the issue for discussion separately (there may be cases where you want to run a resource before a resource in a community cookbook where you've got less control of ordering).

> before notifications are pretty much exclusively built for the "I need to stop this service during upgrades or config changes and start it again after"

ah. makes sense. obvious answer is "order matters", which is fine, but i wasn't sure if before notification was intended to be more like puppet's before ordering, in which case verifier's triggering first seems like a hindrance.

**Comment by coderanger** [comment]
Yeah, that's why I mentioned it, very much not for more arbitrary ordering tricks :) For that you still need to put them in the order you want them to run.

**Comment by nathwill** [comment]
👍
