### ISSUE TITLE
Deprecate Chef::Search::Query positional parameters

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#5975]
I think we can throw a deprecation warning in hashify_args once the user hits the positional arg mangling:

https://github.com/chef/chef/blob/d648136085c4061eaefa04ad823c49a14282a749/lib/chef/search/query.rb#L107

**Comment by tas50** [comment]
We should get a cookstyle warning for this one.

**Comment by tas50** [comment]
The cookstyle issue for this is https://github.com/chef/cookstyle/issues/144

**Comment by lamont-granquist** [comment]
yeah this got done in cookstyle instead
