### ISSUE TITLE
properly deprecate Chef::Resource's `state_attrs` and `identity_attr` methods

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#5980]
killing the word `attributes` as applied to resources with fire.

**Comment by lamont-granquist** [comment]
Also:

- deprecate `:name_attribute`
- deprecate `attribute` itself as an alias for `:property` in Resource::LWRPBase

**Comment by tas50** [comment]
I think we have a long way to go before we can kill attributes (long long way), but we should figure out what to do with the state_attrs and identity_attr mess. I'm not sure if anyone (including us) is using this correctly.
