### ISSUE TITLE
WMI Access Denied on Windows, have to restart Windows Management Instrumentation Daily to get it to work

### ISSUE THREAD

**Issue by jeremysmitherman** [chef/chef#5996]
## Description

Getting `OLE error code:80041003 in SWbemObjectSet
  Access denied
HRESULT error code:0x80020009`

When running chef-client on some Windows Server 2012r2 nodes

## Chef Version

12.8

## Platform Version

Windows Server 2012r2

## Replication Case

Run chef-client.

## Client Output

https://gist.github.com/jeremysmitherman/06632ceaa300bafa20fb3882b916ba79

## Stacktrace

No stacktrace.out generated

**Comment by smurawski** [comment]
Are there any other services/programs on the box that have WMI plugins?  I've seen this type of behavior where some WMI provider consumes a bunch of resources and makes WMI non-responsive.

Could you share the results of [WMIDiag](http://go.microsoft.com/fwlink/?linkid=84435)? (A tool to troubleshoot WMI problems - example: https://blogs.technet.microsoft.com/askperf/2007/06/22/basic-wmi-testing/)

**Comment by stuartpreston** [comment]
Closing this due to age.  If more information becomes available, we encourage you to join our [Community Slack](https://community-slack.chef.io) and post in the #windows channel. Thanks!
