### ISSUE TITLE
Zypper package resource doesn't respect options

### ISSUE THREAD

**Issue by scotthain** [chef/chef#6011]
## Description

For example, using:
```
package 'rpm-build' do
  options '--force-resolution'
end
```

will end up with the invocation of:
`zypper --non-interactive --no-gpg-checks install --auto-agree-with-licenses rpm-build=4.11.2-15.1`
rather than the expected:
`zypper --non-interactive --no-gpg-checks install --auto-agree-with-licenses --force-resolution rpm-build=4.11.2-15.1`

## Chef Version

12.9.38 +

## Platform Version

sles 12.1 (EC2 ami to be specific)

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* Requests for new or alternative functionality should be made to [feedback.chef.io](https://feedback.chef.io/forums/301644-chef-product-feedback/category/110832-chef-client)
* [Chef Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by lamont-granquist** [comment]
yeah both the shell_out calls need `new_resource.options` added to it, not sure if i took that out or if its simply never supported it.

should consider if the options flag should overwrite stuff like --no-gpg-check or not.
