### ISSUE TITLE
Chef server upgrade (11 -> 12) workflow breaks installation on Ubuntu

### ISSUE THREAD

**Issue by saveriomiroddi** [chef/chef#6016]
## Description

The official chef server upgrade (11 -> 12) workflow breaks the installation on Ubuntu, by ultimately causing the chef-server-ctl symlink (and potentially other core ones) to be missing.

## Chef Version

Upgrade from latest 11.1.7 (open source) to 12.14.0-1.

## Platform Version

Ubuntu 14.04.5 server.

## Replication Case

The official workflow to upgrade v11 (open source) to v12 is to:

1. upgrade to the latest v11
2. install the chef-server-core package
3. remove the v11 package

There is no problem with 1. and 2. - (meta)data has been properly upgraded; the problem lies in step 3.

This is an extraction of step 3's output:

    The Chef 11 server package (chef-server) is still present on the system and can now be safely removed.

This statement (within the context) is wrong and actually harmful - after removing the package (`aptitude remove chef-server`), the `/usr/bin/chef-server-ctl` symlink was missing (and potentially other ones), therefore, the installation was broken. Of course, I don't mean "radically" broken, but the `/usr/bin` symlinks are still an expected part of a correct installation.

I'm not familiar with the deb packages specifications, but I suspect that since the symlink is common between the two packages, if this is not correctly specified in the package(s) metadata, removal of the v11 package will remove files (symlinks in this case) which are shared with the v12 one.

## Client Output

The issue is not relevant to the upgrade itself, which is correct:

      Converging 302 resources
      * link[/usr/bin/private-chef-ctl] action create (up to date)
      * link[/usr/bin/chef-server-ctl] action create (up to date)

The only thing that should be modified, at least as stop gap, is to change or entirely remove this message:

    The Chef 11 server package (chef-server) is still present on the system and can now be safely removed.

which will cause the user to break the installation.

**Comment by shortdudey123** [comment]
This repo is for chef-client
Since this issue is chef-server related, please create an issue at https://github.com/chef/chef-server/issues/new instead

**Comment by saveriomiroddi** [comment]
Apologies; I've copied to https://github.com/chef/chef-server/issues/1216; I assume this issue can be closed and/or deleted.
