### ISSUE TITLE
Windows client defaulting to FIPS mode

### ISSUE THREAD

**Issue by jblaine** [chef/chef#6026]
## Description

The Windows client appears to be defaulting to FIPS mode on.

## Chef Version

12.19.36

## Platform Version

Windows Server 2012R2 64-bit

## Replication Case

1. Install Chef Client for Windows Server 2012R2 x86_64
2. Ensure there is nothing mentioning FIPS in `C:\chef\client.rb` or `C:\chef\client.d\*` (`findstr /I fips C:\chef\client.rb`)
2. Run: `C:\opscode\chef\bin\chef-client`

As a side note, the fips-enabled-by-default situation causes an openssl exception if you happen to be running the x86 chef client on an x86_64 box and chef-client _won't even run_. In the case here, where the x86_64 client is being run on an x86_64 box, FIPS mode is attempted and works, but should _not be the default_ as far as I can tell.

## Client Output

```
...
OpenSSL FIPS 140 mode enabled
...
```

**Comment by thommay** [comment]
per #5507 does the `System\CurrentControlSet\Control\Lsa\FIPSAlgorithmPolicy` registry key exist, and if it does, is `Enabled=1` in there? We definitely don't default to FIPS mode on, and we run extensive tests to ensure that the chef client runs correctly.

**Comment by jblaine** [comment]
Thanks. Yes, it turns out that key is set to 1. Off to find out who did this. Closing.
