### ISSUE TITLE
Windows_Package %%%%ERRORLEVEL%%%% on EXE Installs

### ISSUE THREAD

**Issue by Bowmaster** [chef/chef#6027]
Hello - I was having a consistent issue when trying to install EXE packages in chef using the Windows_Package with the :Custom installer_type.  All installs are reporting back as failed.  What I noticed is that the command is attempting to run in this format:

start "" /wait "C:\Installer.exe" /Q & exit %%%%ERRORLEVEL%%%%

What stands out to me is the use of the 4 %'s on each side of ERRORLEVEL.  This is not going to return a straight 0 which is what is desired to determine success.

We're running test kitchen with Chef 12.14.77 on a Server 2016 VM.

I believe the file in question is here, on line 64:  https://github.com/chef/chef/blob/master/lib/chef/provider/package/windows/exe.rb . Note the hardcoded 4 %'s on each side vs the standard %ERRORLEVEL% usage in batch.

I've been able to run this same cmd manually with %ERRORLEVEL% and it does complete successfully so I know the install cmd is valid.

For reference, here's a picture of the cmd being ran on the node:
![errorlevel](https://cloud.githubusercontent.com/assets/13702629/24725680/cb0d3036-1a1d-11e7-84f9-1f7d6d187ecc.png)

And here's my kitchen output as well:

-----> Starting Kitchen (v1.15.0)
-----> Converging <default-ourcompany-server2016>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.6.4...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-ourcompany-server2016>
       Starting Chef Client, version 12.14.77
       resolving cookbooks for run list: ["ms_sql::default"]
       Synchronizing Cookbooks:
         - ms_sql (0.1.0)
         - windows (3.0.4)
         - ohai (5.0.2)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 2 resources
       Recipe: ms_sql::default
         * template[C:/Windows/Temp/SQL_Configuration.ini] action create (up to date)
         * windows_package[SQL] action install

           ================================================================================
           Error executing action `install` on resource 'windows_package[SQL]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '-2022834173'
           ---- Begin output of start "" /wait "c:\kitchen-vagrant-files\sql 2016 x64\setup.exe"   /ConfigurationFile=C:/Windows/Temp/SQL_Configuration.ini & exit %%%%ERRORLEVEL%%%% ----
           STDOUT:
           STDERR:
           ---- End output of start "" /wait "c:\kitchen-vagrant-files\sql 2016 x64\setup.exe"   /ConfigurationFile=C:/Windows/Temp/SQL_Configuration.ini & exit %%%%ERRORLEVEL%%%% ----
           Ran start "" /wait "c:\kitchen-vagrant-files\sql 2016 x64\setup.exe"   /ConfigurationFile=C:/Windows/Temp/SQL_Configuration.ini & exit %%%%ERRORLEVEL%%%% returned -2022834173

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/ms_sql/recipes/default.rb

            22: windows_package 'SQL' do
            23:   action :install
            24:   source 'C:/Kitchen-Vagrant-Files/SQL 2016 x64/setup.exe'
            25:   options '/ConfigurationFile=C:/Windows/Temp/SQL_Configuration.ini'
            26:   installer_type :custom
            27: end
            28: =begin

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/ms_sql/recipes/default.rb:22:in `from_file'

           windows_package("SQL") do
             package_name "SQL"
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :windows_package
             cookbook_name "ms_sql"
             recipe_name "default"
             source "c:\\kitchen-vagrant-files\\sql 2016 x64\\setup.exe"
             options "/ConfigurationFile=C:/Windows/Temp/SQL_Configuration.ini"
             installer_type :custom
             returns [0]
           end

           Platform:
           ---------
           x64-mingw32

       Running handlers:
       [2017-04-05T15:23:06-05:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-04-05T15:23:06-05:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 11 seconds
       [2017-04-05T15:23:06-05:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2017-04-05T15:23:06-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-04-05T15:23:06-05:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: windows_package[SQL] (ms_sql::default line 22) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '-2022834173'
       ---- Begin output of start "" /wait "c:\kitchen-vagrant-files\sql 2016 x64\setup.exe"   /ConfigurationFile=C:/Windows/Temp/SQL_Configuration.ini & exit %%%%ERRORLEVEL%%%% ----
       STDOUT:
       STDERR:
       ---- End output of start "" /wait "c:\kitchen-vagrant-files\sql 2016 x64\setup.exe"   /ConfigurationFile=C:/Windows/Temp/SQL_Configuration.ini & exit %%%%ERRORLEVEL%%%% ----
       Ran start "" /wait "c:\kitchen-vagrant-files\sql 2016 x64\setup.exe"   /ConfigurationFile=C:/Windows/Temp/SQL_Configuration.ini & exit %%%%ERRORLEVEL%%%% returned -2022834173
 ------Exception-------
 Class: Kitchen::ActionFailed
 Message: 1 actions failed.
     Converge failed on instance <default-ourcompany-server2016>.  Please see .kitchen/logs/default-ourcompany-server2016.log for more details
 ----------------------
 Please see .kitchen/logs/kitchen.log for more details
 Also try running `kitchen diagnose --all` for configuration

**Comment by jugatsu** [comment]
You should use elavated shell in TK. This is not chef-client bug.

**Comment by smurawski** [comment]
As noted by @jugatsu, you cannot install sql server over WinRM without some sort of delegation in place (which is unsupported in test-kitchen).  You can use the `elevated: true` setting on the transport in test-kitchen to get around that.
