### ISSUE TITLE
Implement `after_resource` that leverages `load_current_value`

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#6036]
The `current_value_does_not_exist!` API sets the `current_resource` to nil which seems bad.  The purpose of this is to have better checking around the object-does-not-exist-yet case.  So for example in the file resource now we build a current_resource but expect the mode, owner, group, etc to be 'nil' when the file simply doesn't exist yet.  It would seem to be better to build a default resource and then set a property like `exist` to false, and then have a `current_resource.exist?` helper to handle this case.  Right now I suspect that there are going to be lingering bugs in the resource reporter and data collector code (and possibly server-side in automate, etc) if anyone starts really using this feature and setting current_resource to nil.  I suspect that most people are not doing this.   The fact that it is hidden under the load_current_value and converge_if_changed api suggests that we can change this without changing the shape of the API.

I'd also like to work on creating an after_resource to solve all the horrible new_resource mutation issues we have where we're abusing the desired state with the final state and then trying to pass that into the resource_reporter/data_collector.  We really need to simply call a function to load an `after_resource` and let reporting diff `current_resource` and `after_resource` and then we can leave the `new_resource` alone.  In order to do that, though, we can't use `load_current_resource` because that function updates the current_resource as a side effect, we need to have a function which can load either the current_resource or the after_resource depending on how it is called.  The `load_current_value` function does that (and apparently even will optionally call itself with the resource as an argument).

#5974, #5980 are related, #5992 could probably use being looked at as well.

**Comment by lamont-granquist** [comment]
It looks like load_current_value is also creating the current_resource by `new_resource.dup` and that should be changed to `new_resource.class.new` to get a new object rather than dup'ing the user desired state intent.

**Comment by lamont-granquist** [comment]
so just changing `new_resource.dup` to `new_resource.class.new` will bypass the implicit copying of all the new_resource state to the current_resource.  this might be a breaking change.  but it seems this would only be useful in the case of the name and the name_property which is where we seem to do it all the time in load_current_resource.  if we just made load_current_value set those two properties off of the new_resource then that would accomplish the task.

unfortunately it'll still be breaking, and there's literally no way to write a deprecation warning for load_current_value.  we'd have to go down the road of writing a decorator around the current_resource as its being built in load_current_value and intercept calls which might be reading values before they were explicitly set.

**Comment by lamont-granquist** [comment]
or could hang the state off the property i guess:  "mark all the properties as ‘dirty’ and then as they’re written to mark them ‘clean’ and on access if you hit a ‘dirty’ property you throw a warning — marking the name + name_property as ‘clean’ to start with."

**Comment by lamont-granquist** [comment]
so @coderanger, the use-case that gives me pause is something like `atomic_update` on the file resource.

right now, via cloning magic, if the user sets `atomic_update false` then that is on the new_resource and we dup it to both the current_resource and would dup it to the after_resource.   then that would presumably get shovelled off to reporting / data collecting / whatevers...

if we don't dup the new_resource then the current_resource + after_resource sent to reporting would have the default `atomic_update true`.  that's misleading if we report the whole resource.  if we only report the diffs in properties, then it disappears and becomes less misleading -- but it becomes impossible to search for "file resources which ran and had atomic_update to false".

**Comment by coderanger** [comment]
@lamont-granquist I think for stuff like that we need to use the `desired_state` flags so DataCollector and friends know not to look at it. There is no semantic meaning for the before or after values of that property since it isn't state, it's configuration.

**Comment by lamont-granquist** [comment]
but should data collector look at it?  just because its not "desired_state" doesn't mean that we don't want to do reporting on the fact that a resource ran with those flags...

the other solution would seem to be feeding the new_resource into the data collector to pull off "non-desired_state" from there and pull off "desired_state" from current+after.

**Comment by coderanger** [comment]
Yep, I think the "other solution" is 100% how it should work :) Use `new_resource` for config (i.e. `desired_state: false`) and current/after for `desired_state: true`.

**Comment by lamont-granquist** [comment]
https://github.com/chef-cookbooks/windows/issues/490#issuecomment-322306855 is another custom resources issue.

we frequently use nil on properties on current_resource to indicate '$thing hasn't been created yet' but `current_resource.property.nil?` will then fail if the property is required on the new_resource.
