### ISSUE TITLE
Unable to Create UTF-8 File from Template Under Windows

### ISSUE THREAD

**Issue by bhazard** [chef/chef#6037]
## Description

I am using Chef to create a UDL file on Windows 12. The file must be encoded as UTF-8, but I can't get Chef to produce anything other than ANSI.

On the workstation, the ERB template file is UTF-8 encoded, but the template file that ends up on the target nodes is ANSI when it lands in the chef cache -- so it seems the encoding is being lost during the file transfer to the target node. Both workstation and target node's ruby defaults to UTF-8 during the chef-client run, although I expect that because the source ERB template is ANSI on the target, the final file is being created as ANSI as well.  Chef Server is hosted at AWS (as a service).

The recipe is pretty straightforward:

    log "Encoding is #{Encoding.default_external}"

    template 'C:/file.udl' do
      rights :full_control, 'Everyone'
      action :create
      source 'file.udl.erb'
    end

And the template (again UTF-8 encoded at the source but not after being transferred to the target node):

    [oledb]
    ; Everything after this line is an OLE DB initstring
    Provider=SQLOLEDB.1;Password=MyPassword;Persist Security Info=True;User ID=MyUsername;Initial Catalog=MyCat;Data Source=MyServer

The resultant ANSI file can't be read by OLE and is confirmed to be ANSI.  Seems like a bug during losing the encoding during the file transfer, but I could imagine also that setting the encoding on the target template file could be valuable (so a feature?).

## Chef Version

12.19.36

## Platform Version

Chefdk on workstation is 1.2.22; verified under Windows Server 2012 on the target; workstation is Mac OSX 10.11.6

**Comment by coderanger** [comment]
To copy over my question from SO, does the file look correct via `knife cookbook show`?

**Comment by bhazard** [comment]
Not sure if I understand ... are you asking about the encoding of the template via `knife cookbook show`?  It "looks" fine, but I don't know how to see an encoding that way?  Or are there other options that would help clarify?

**Comment by coderanger** [comment]
There is no encoding there to check, but confirm that the bytestream returned when downloading the hasn't been mojibake'd. This seems unlikely, but you said the bytes were incorrect in the node cache we we need to work out which side is mishandling the data.

**Comment by jugatsu** [comment]
@bhazard can you reproduce this issue in test-kitchen wirh `chef_zero` provisioner?

**Comment by bhazard** [comment]
I can repro w/ chef_zero and kitchen, but the issue is not quite the same (could be difference on my end).  Let me take a closer look at the files produced ... will be a day or so though.

**Comment by stuartpreston** [comment]
I just happened to spot this as I was looking through the issues list, I don't know if it helps but from my testing in the past, a valid UDL file needs to be UTF-16LE with BOM.  There's probably a better way of achieving this than my code, which I've passed along for amusement:

```
secrets = data_bag_item('secrets', node.chef_environment)

# Deploy file.udl in %programdata% (typically c:\ProgramData\)
template "#{ENV['PROGRAMDATA']}\\file.udl" do
  source 'file.udl.erb'
  action :create
  variables(password: secrets['sql-user-password'])
end

# Convert connection file to the correct encoding
ruby_block 'convert connection file to UTF-16LE with BOM' do
  block do
    existing_file = ::File.read("#{ENV['PROGRAMDATA']}\\file.udl")
    new_file = File.open("#{ENV['PROGRAMDATA']}\\file.udl", 'w:UTF-16LE')
    new_file << "\xFF\xFE".force_encoding('utf-16le') + existing_file.force_encoding('utf-8').encode('utf-16le')
  end
end
```

**Comment by bhazard** [comment]
@stuartpreston - thx for the reply and workaround, and you're right about the UDL file format -- it needs to be UTF-16 with BOM, not UTF-8.  I should not have believed notepad.  Chef should be able to take a UTF-16 with BOM file over though, yes?

**Comment by xiaohui-zhangxh** [comment]
this is my solution by hacking Chef::Mixin::Template::TemplateContext
```
require 'chef/mixin/template'
unless Chef::Mixin::Template::TemplateContext.public_methods.include?(:_origin_render_template)
  class Chef::Mixin::Template::TemplateContext
    alias_method :_origin_render_template, :_render_template
    def _render_template(template, context)
      encoding = context[:__encoding__] && context[:__encoding__].upcase
      if template && encoding && template.encoding.name != encoding
        Chef::Log.info("Encoding template to #{encoding}")
        template.force_encoding encoding
      end
      _origin_render_template(template, context)
    end
  end
end

template '/usr/local/sbin/autopostgresqlbackup' do
  source 'autopostgresqlbackup'
  mode 750
  variables(
    __encoding__: 'utf-8',
    backup_dir: node['autopostgresqlbackup']['backup_dir'],
  )
end
```

**Comment by lamont-granquist** [comment]
I can't determine the bug here from reading through this.  AFAIK if you give us a UTF-16 w/BOM as a template then we should deploy that, and the error was on the editor side.

If the template or file resources mangle a UTF-16 w/BOM somewhere between cookbook upload and deployment that would be a bug, but it needs to be resubmitted as one with a bit clearer bug report.
