### ISSUE TITLE
fails to load libs 

### ISSUE THREAD

**Issue by revanthreddy36** [chef/chef#6043]
## Description

I am using chef-client 13 in my kitchen environment and it seems like the run is failing due to some libraries. 

## Chef Version

13.0.113

## Platform Version

centos 6.7 

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Client Output

 LoadError
       ---------
       cannot load such file -- chef/mixin/command
       
       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/rvm/libraries/chef_rvm_string_cache.rb:22:in `<top (required)>'
       

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* Requests for new or alternative functionality should be made to [feedback.chef.io](https://feedback.chef.io/forums/301644-chef-product-feedback/category/110832-chef-client)
* [Chef Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by coderanger** [comment]
That class has been removed in Chef 13. You'll need to wait until the `rvm` cookbook is fixed for Chef 13 or upgrade it yourself locally. From a quick glance at the code I thing it can be pretty easily fixed to use the shellout API.

**Comment by revanthreddy36** [comment]
@coderanger Thank you. i ll use 12.19.36 until the rvm cookbook is updated.
