### ISSUE TITLE
Assertion functionality is missing?

### ISSUE THREAD

**Issue by lioramilbaum** [chef/chef#6056]
## Description

I need to verify java 8 is installed. Only check it. I do not want chef to install it if doesn't exist or different version installed. If the assertion fails, stop the chef run.

**Comment by coderanger** [comment]
Assertion of what?

**Comment by lioramilbaum** [comment]
if java 8 is installed than go ahead. if not, stop.

**Comment by coderanger** [comment]
I think you have the wrong repository, closing this out. Perhaps you meant this issue for something specific to your company?

**Comment by lioramilbaum** [comment]
Not really. I was looking for the same functionality as the assert module in Ansible. Never mind, I will find a solution for it.

**Comment by coderanger** [comment]
You'll have to be a lot more specific. If you're trying to install Java using Chef there are a number of community cookbooks available on supermarket.chef.io, though most people use the eponymous `java` cookbook.
