### ISSUE TITLE
Chef appears to uninstall itself

### ISSUE THREAD

**Issue by mal** [chef/chef#6058]
**Dislcaimer:** I appreciate that this may not be a direct Chef bug that you can solve from this repo, but it seemed prudent to ensure that the Chef team is at aware of this if not already. I had a search but didn't turn up much, so hopefully I'm not duping anything.

---

## Description

Chef appears to uninstall itself. All the binaries but for `chef-zero` no longer exist on the server.

## Chef Version

`11.12` - I know it's old, but good chance this affects more than just this version.

## Platform Version

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

## Replication Case

**cookbooks/testcase/metadata.rb**
```rb
name             'testcase'
maintainer       'mal'
maintainer_email 'mal.graty@idioplatform.com'
version          '1.0.0'

depends 'apt'
```
**cookbooks/testcase/recipes/default.rb**
```rb
package 'libruby2.3'
```

**launch command** -- add your own valid SSH Key arg
```sh
knife ec2 server create -I ami-dc40e1ca -N chef-test -f m1.small -r 'recipe[testcase]' -x ubuntu --bootstrap-version 11.12
```

**Once launched:**
1. `ssh` into the server
2. Force `unattended-upgrades` to run: `sudo unattended-upgrade -d`

**Observed:**

1. You will see unattended-upgrades recognise Chef and upgrade it to `12.3.0` from the ubuntu repository.
    - This appears to complete successfully but by design or otherwise, most binaries do not appear to be present.
2. This will also uninstall the normal version of Chef in `/opt`
3. A service file `/etc/init.d/chef-client` will be added

**Notes:**

Running `unattended-upgrades` without installing `libruby2.3` does not cause a problem, however this appears to be more accidental than anything:

```
root@ip-10-185-221-79:~# dpkg -l chef
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                            Version                      Architecture                 Description
+++-===============================================-============================-============================-===================================================================================================
ii  chef                                            11.12.8-2                    amd64                        The full stack of chef
root@ip-10-185-221-79:~# sudo unattended-upgrade -d
Initial blacklisted packages: 
Initial whitelisted packages: 
Starting unattended upgrades script
Allowed origins are: ['o=Ubuntu,a=xenial', 'o=Ubuntu,a=xenial-security']
Checking: chef ([<Origin component:'universe' archive:'xenial' origin:'Ubuntu' label:'Ubuntu' site:'us-east-1.ec2.archive.ubuntu.com' isTrusted:True>])
pkg 'libruby2.3' not in allowed origin
sanity check failed
pkgs that look like they should be upgraded: 
Fetched 0 B in 0s (0 B/s)                                                                                                                                                                                          
fetch.run() result: 0
blacklist: []
whitelist: []
Packages that will be upgraded: 
InstCount=0 DelCount=0 BrokenCount=0
Extracting content from '/var/log/unattended-upgrades/unattended-upgrades-dpkg.log' since '2017-04-12 12:39:25'
```

The absense of the `libruby2.3` package is the reason the upgrade doesn't take place by default. Installing it causes subsequent runs of `unattended-upgrades` trigger the issue described above.

**Comment by mal** [comment]
Solving this in the meantime by excluding `chef` from unattended upgrades, posting here in case it can help anyone else caught out by this (it's designed for `ubuntu` YMMV with other distros):

```rb
file '/etc/apt/apt.conf.d/50unattended-upgrades' do
  content IO.read(path).sub('Package-Blacklist {', "\\0\n      \"chef\";")
  not_if "grep '\\bchef\\b' #{path}"
end
```

**Comment by cheeseplus** [comment]
Thanks for the note here. We are very aware which is why we build our own packages and recommend using these https://downloads.chef.io/. The distro packages are often outdated and don't follow how we build the software and as such we don't recommend using distro packages.

**Comment by coderanger** [comment]
Going to close this out as it sounds like there isn't a bug per se, the distro packages just don't include everything our normal packages do, which is expected.

**Comment by mal** [comment]
Yup, we've always followed that practice on our servers. I decided to post this because we've never experienced `unattended-upgrades` updating the manually installed `deb` (which we get from https://downloads.chef.io/) before.

We've not altered anything in terms of Chef version, OS or anything else that would obviously affect this so I'm left thinking that something else in the eco-system must have changed to enable the upgrade to take place.

Happy for this to stay closed but it does appear to be different from just the run of the mill - don't use distro packages.
