### ISSUE TITLE
windows_task does not have a :change action

### ISSUE THREAD

**Issue by spuder** [chef/chef#6059]
In chef 13, the windows_task was ported from the windows cookbook. 

The port does not include a `:change` action. This will cause any cookbook that attempts to modify a windows scheduled task to fail. 

```
           * windows_task[modify sched task start time] action change
             
             ================================================================================
             Error executing action `change` on resource 'windows_task[modify sched task start time]'
             ================================================================================
             
             NoMethodError
             -------------
             undefined method `action_change' for #<Chef::Provider::WindowsTask:0x00000005285d70>
             Did you mean?  action_enable
                     action_create
             
             Resource Declaration:
             ---------------------
             # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/ad-join/resources/domain_join.rb
             
       72:     windows_task 'modify sched task start time' do
       73:       task_name 'chef ad-join' # http://bit.ly/1WDZ1kn
       74:       start_day '06/09/2016'
       75:       start_time '01:00'
       76:       only_if { node['kernel']['cs_info']['domain_role'].to_i == 0 || node['kernel']['cs_info']['domain_role'].to_i == 2 }
       77:       action :change
       78:     end
       79: 
```

See related issue https://github.com/NetDocuments/ad-join-cookbook/issues/23

**Comment by NimishaS** [comment]
@spuder , `:change` action has been removed because `:create` action can also be used to modify an existing task if there's any change in the properties. Hence `:change` was a redundant action.
e.g. If I run the following recipe once:
```
windows_task 'chef-client' do  
  command 'chef-client'
  run_level :highest
  frequency :hourly
  frequency_modifier 2
end
```
It creates task for running `chef-client` after every 2 hrs.

Now if I modify the same recipe as:
```
windows_task 'chef-client' do  
  command 'chef-client'
  run_level :highest
  frequency :hourly
  frequency_modifier 5
end
```
This overwrites the existing task only and runs `chef-client` after every 5 hrs. 

Please refer the conversation here: https://github.com/chef-cookbooks/windows/issues/366#issuecomment-286731505

**Comment by tas50** [comment]
I think what we'll potentially want to do here is alias change to create so we don't break legacy cookbooks. We can then introduce a foodcritic rule to move people over to the new action.

**Comment by spuder** [comment]
Workarounds

```ruby
windows_task 'foo' do
      action :change if Chef::VERSION.split('.')[0] = 12 
end
```

or 
```ruby
windows_task 'foo' do
      action :change if Gem::Requirement.create('= 12').satisfied_by(Gem::Version.create(Chef::VERSION))
end

**Comment by spuder** [comment]
There are other incompatibilities between windows_task from the windows cookbook and windows_task from core. I have not yet been able to identify which properties are causing the problem. 

```
      * windows_task[modify sched task start time] action create

             ================================================================================
             Error executing action `create` on resource 'windows_task[modify sched task start time]'
             ================================================================================

             NoMethodError
             -------------
             undefined method `tr' for nil:NilClass

             Resource Declaration:
             ---------------------
             # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/ad-join/resources/domain_join.rb

       72:     windows_task 'modify sched task start time' do
       73:       task_name 'chef ad-join' # http://bit.ly/1WDZ1kn
       74:       start_day '06/09/2016'
       75:       start_time '01:00'
       76:       only_if { node['kernel']['cs_info']['domain_role'].to_i == 0 || node['kernel']['cs_info']['domain_role'].to_i == 2 }
       77:       # action :change if Chef::VERSION.split('.')[0] = 12 # issue #23
       78:       # action :change if Gem::Requirement.create('= 12').satisfied_by?(Gem::Version.create(Chef::VERSION))
       79:       action :create
       80:     end
       81:

             Compiled Resource:
             ------------------
             # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/ad-join/resources/domain_join.rb:72:in `block in class_from_file'

             windows_task("modify sched task start time") do
        action [:create]
        default_guard_interpreter :default
        task_name "chef ad-join"
        declared_type :windows_task
        cookbook_name "nd-ad-join"
        execution_time_limit "PT72H"
        start_day "06/09/2016"
        start_time "01:00"
        only_if { #code block }
             end

             System Info:
             ------------
             chef_version=13.0.118
             platform=windows
             platform_version=6.3.9600
             ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
             program_name=C:/opscode/chef/bin/chef-client
             executable=C:/opscode/chef/bin/chef-client
```

**Comment by spuder** [comment]
The [windows_task documentation](https://docs.chef.io/resource_windows_task.html) indicates that 'change' will only take affect if the 'user' or 'command' attribute has changed. 

> creates a task (or updates existing if user or command has changed)

**Comment by NimishaS** [comment]
@spuder, the issue which I fixed was https://github.com/chef-cookbooks/windows/issues/366. The title of the issue says `Task only looks at command and user for idempotency check`. Ideally it should check for other properties too. The core `windows_task` has been modified to attain that.
Please let me know if I can help you with anything.

**Comment by btm** [comment]
@harikesh-kolekar was this fixed by https://github.com/chef/chef/pull/6193 ?

**Comment by NimishaS** [comment]
@btm, https://github.com/chef/chef/pull/6193 fixes a separate issue related to `command` option.

Since `create` action has replaced `change` action and has been documented too: https://docs.chef.io/resource_windows_task.html, this issue can be closed.

**Comment by btm** [comment]
@NimishaS I poked around and it looks like `task_need_update?` has a confusing set of `&&` and `||`s that could be interpreted to mean that `new_resource.command` has to be set for an update. I think `task_need_update?` will return true if any of the properties listed have changed though.

If that is true, we still need to update https://docs.chef.io/resource_windows_task.html where it says:

> creates a task (or updates existing if user or command has changed)

**Comment by NimishaS** [comment]
@btm, Initially there was an issue and  `new_resource.command` had to be set during an update. It's fixed in #6193.
Yes, https://docs.chef.io/resource_windows_task.html needs update as you mentioned. We'll create a card for that.

**Comment by NimishaS** [comment]
@btm, the description of `create` action has been updated: https://docs.chef.io/resource_windows_task.html#actions. Please close this issue.

**Comment by btm** [comment]
@tas50 do you still want to alias `:change` to `:create`? I don't know off the top of my head if that'd be a compatible change.

**Comment by tas50** [comment]
@btm I'll have to check and see if it's a compatible change, but if so we should definitely do it for backwards compatibility.

**Comment by spuder** [comment]
I would still like an alias for `:change`
My work around is

```ruby
windows_task foo do
    action :change if Gem::Requirement.create('~> 12').satisfied_by?(Gem::Version.create(Chef::VERSION))
end
```
