### ISSUE TITLE
run_status start time and end time are in different time zones

### ISSUE THREAD

**Issue by Poohblah** [chef/chef#6065]
When using the chef-handler-mail 3rd-party gem to e-mail output of a failed chef run, I noticed that the reported start time and end time are in different time zones:

```
Results of Failed Chef run on ***.***.***

Start time: 2017-04-14 17:12:59 UTC
End time: 2017-04-14 11:13:41 -0600
...
```

It looks to me like the [template](https://github.com/kisoku/chef-handler-mail/blob/master/lib/chef/handler/mail.erb) and [reporter](https://github.com/kisoku/chef-handler-mail/blob/master/lib/chef/handler/mail.rb) for this handler are just grabbing the [`run_status` object directly from chef core](https://github.com/chef/chef/blob/master/lib/chef/run_status.rb) and implicitly calling `.to_s` on the start and end times.

We are currently using chef-client 12.17.44 and version 0.1.2 of the chef-handler-mail gem.

I should also point out that the time zone of the system is not changing during the course of the chef run - the time zone is set at kickstart time, before chef is even installed/bootstrapped; moreover, this happens repeatedly after many converges, so even if chef is setting the time zone, we shouldn't see this behavior.

**Comment by lamont-granquist** [comment]
That is a but in the chef-handler-mail app, it needs to call `time.getutc.to_s`.

And the timezone has to be changing during first-run somehow since all that Chef is doing is calling `Time.now` and does not do any timezone handling.
