### ISSUE TITLE
Subtle change in the user resource in Chef 13?

### ISSUE THREAD

**Issue by martinb3** [chef/chef#6069]
## Description

I have a recipe which adds and then removes a user; before Chef 13, the ChefSpec check for actions `:create` and `:delete` were passing. After upgrading to Chef 13, ChefSpec says no :create action exists.

## Chef Version

Using 'chef' gem version 12.19.36, the test case below passes. When using 13.0.118, the test case below fails.

## Replication Case

Recipe:
```
user 'deleteme'
user 'deleteme' do
  action :remove
end
```

ChefSpec:
```
        it 'creates user deleteme' do
          expect(chef_run).to create_user('deleteme')
        end

        it 'deletes user deleteme' do
          expect(chef_run).to remove_user('deleteme')
        end
```

## Error message

```
     Failure/Error: expect(chef_run).to create_user('deleteme')
       expected "linux_user[deleteme]" actions [:remove] to include :create
     # ./test/unit/spec/user_spec.rb:23:in `block (5 levels) in <top (required)>'
```

This doesn't happen in Chef 12.x and I can't find anything in the changelog that would indicate such a big behavioral difference.

Thanks in advance!

**Comment by coderanger** [comment]
The issue is probably related to the removal of resource cloning, if you use different resource names for the two I would imagine it would work.

**Comment by martinb3** [comment]
I'm blind -- that makes sense. Nevermind! :)

**Comment by martinb3** [comment]
I had assumed resource cloning was going to be an runtime error once the functionality was removed -- for my own edification, is it now just a silent bug?

**Comment by coderanger** [comment]
It's not a bug per se, you just get two unrelated resource objects in the collection. When you use the "by name" APIs it returns the most recent one so that's all chefspec sees but there are two in there.
