### ISSUE TITLE
Getting error while registering node to chef server - OpenSSL::X509::CertificateError: nested asn1 error 

### ISSUE THREAD

**Issue by badsector3** [chef/chef#6072]
## Description

Getting error while registering node to chef server - OpenSSL::X509::CertificateError: nested asn1 error 
This is the same issue as https://github.com/chef/chef/issues/5376

I cannot auto-register node but works fine with knife.
SSL signed by godaddy (works as secure connection can be seen in browser) but still the same issue.
 
## Chef Version

chef-node  12.19.36
chef-manage                      2.5.1-1     
chef-server-core                 12.14.0-1

## Platform Version

Ubuntu 16.04 
chef-node  12.19.36

## Replication Case

I installed the chef-client as following:
curl -L https://www.opscode.com/chef/install.sh | bash /dev/stdin -v 12.19.36-1
mkdir /etc/chef
and uploaded following:
client.rb, first-boot.json and trusted_certs where are the *.pem and crt. 
client.rb/first-boot.json copy after successful knife bootstrap
*.crt from workstation after 'knife ssl fetch/check' 
*.pem from chef-server

## Client Output

`
[2017-04-18T20:42:36+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
[2017-04-18T20:42:36+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::APIVersions#handle_request
[2017-04-18T20:42:36+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
[2017-04-18T20:42:36+00:00] DEBUG: Initiating POST to https://...............
[2017-04-18T20:42:36+00:00] DEBUG: ---- HTTP Request Header Data: ----
[2017-04-18T20:42:36+00:00] DEBUG: Content-Type: application/json
[2017-04-18T20:42:36+00:00] DEBUG: Accept: application/json
[2017-04-18T20:42:36+00:00] DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
[2017-04-18T20:42:36+00:00] DEBUG: X-Ops-Server-API-Version: 0
[2017-04-18T20:42:36+00:00] DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.1;
[2017-04-18T20:42:36+00:00] DEBUG: X-OPS-USERID: chef-validator
[2017-04-18T20:42:36+00:00] DEBUG: X-OPS-TIMESTAMP: 2017-04-18T20:42:36Z
[2017-04-18T20:42:36+00:00] DEBUG: X-OPS-CONTENT-HASH: bSbsMxJ6qpX5wsmiQbdCJ7fcQsQ=
[2017-04-18T20:42:36+00:00] DEBUG: X-OPS-AUTHORIZATION-1: okarTPR3+k/xwWq61O9TEIz8TVUdPtR9DFCWuv0O+I97FjqaGj/QJzL+zsmX
[2017-04-18T20:42:36+00:00] DEBUG: X-OPS-AUTHORIZATION-2: HklfXYUh9U/UW89iIL60txQe5k1h5KxjTyBjb8pJxEm+M2I7nTdQxgCZqc3D
[2017-04-18T20:42:36+00:00] DEBUG: X-OPS-AUTHORIZATION-3: P6xG715GEpsCXIgWnW7UKayYnG97Cf5HsT07Oq6IlUuBKeCuBplfhdsfu2xb
[2017-04-18T20:42:36+00:00] DEBUG: X-OPS-AUTHORIZATION-4: Gkq2ULsdaW7oNHzJnY5ask7Fg0wVqFkSQfE3egDiMbcRbMw2Wgnc17SzhXyJ
[2017-04-18T20:42:36+00:00] DEBUG: X-OPS-AUTHORIZATION-5: 55HQ5qou/mW/Txse8ZCXdxCyAw2KKgD+o2lizo5hhour8Tpr4xyYSdiMj5WP
[2017-04-18T20:42:36+00:00] DEBUG: X-OPS-AUTHORIZATION-6: 9a+yadDgq3MLHdbKdgRwjJYX6SbH3fMz9haCrO/fSQ==
[2017-04-18T20:42:36+00:00] DEBUG: HOST: ...............:443
[2017-04-18T20:42:36+00:00] DEBUG: X-REMOTE-REQUEST-ID: fc35068e-56ed-4b73-8ec2-8615a24754a9
[2017-04-18T20:42:36+00:00] DEBUG: Content-Length: 508
[2017-04-18T20:42:36+00:00] DEBUG: ---- End HTTP Request Header Data ----

================================================================================
Chef encountered an error attempting to create the client "bastion"
================================================================================

Platform:
---------
x86_64-linux

[2017-04-18T20:42:36+00:00] DEBUG: Re-raising exception: OpenSSL::X509::CertificateError - nested asn1 error
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:82:in `initialize'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:82:in `new'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:82:in `block in set_custom_certs'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:81:in `each'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:81:in `set_custom_certs'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:48:in `apply'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:35:in `apply_to'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/basic_client.rb:153:in `configure_ssl'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/basic_client.rb:117:in `build_http_client'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/basic_client.rb:51:in `http_client'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/basic_client.rb:70:in `request'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:340:in `block in send_http_request'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:372:in `block in retrying_http_errors'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:370:in `loop'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:370:in `retrying_http_errors'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:333:in `send_http_request'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:148:in `request'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:131:in `post'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/api_client/registration.rb:96:in `create'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/api_client/registration.rb:87:in `create_or_update'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/api_client/registration.rb:58:in `run'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:621:in `register'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:267:in `run'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:295:in `block in fork_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:248:in `block in run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/local_mode.rb:44:in `with_server_connectivity'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:236:in `run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `loop'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `interval_run_chef_client'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:434:in `run_application'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:59:in `run'
  /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/bin/chef-client:26:in `<top (required)>'
  /usr/bin/chef-client:57:in `load'
  /usr/bin/chef-client:57:in `<main>'

Running handlers:
[2017-04-18T20:42:36+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-04-18T20:42:36+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 01 seconds
[2017-04-18T20:42:36+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-04-18T20:42:36+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-04-18T20:42:36+00:00] DEBUG: OpenSSL::X509::CertificateError: nested asn1 error
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:82:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:82:in `new'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:82:in `block in set_custom_certs'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:81:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:81:in `set_custom_certs'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:48:in `apply'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:35:in `apply_to'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/basic_client.rb:153:in `configure_ssl'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/basic_client.rb:117:in `build_http_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/basic_client.rb:51:in `http_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/basic_client.rb:70:in `request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:340:in `block in send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:372:in `block in retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:370:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:370:in `retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:333:in `send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:148:in `request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:131:in `post'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/api_client/registration.rb:96:in `create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/api_client/registration.rb:87:in `create_or_update'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/api_client/registration.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:621:in `register'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:267:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:295:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:248:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:57:in `load'
/usr/bin/chef-client:57:in `<main>'
[2017-04-18T20:42:36+00:00] ERROR: nested asn1 error
[2017-04-18T20:42:36+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
`

## Stacktrace
`
Generated at 2017-04-18 20:42:36 +0000
OpenSSL::X509::CertificateError: nested asn1 error
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:82:in `initialize'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:82:in `new'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:82:in `block in set_custom_certs'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:81:in `each'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:81:in `set_custom_certs'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:48:in `apply'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/ssl_policies.rb:35:in `apply_to'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/basic_client.rb:153:in `configure_ssl'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/basic_client.rb:117:in `build_http_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/basic_client.rb:51:in `http_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http/basic_client.rb:70:in `request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:340:in `block in send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:372:in `block in retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:370:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:370:in `retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:333:in `send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:148:in `request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:131:in `post'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/api_client/registration.rb:96:in `create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/api_client/registration.rb:87:in `create_or_update'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/api_client/registration.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:621:in `register'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:267:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:295:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:248:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:57:in `load'
/usr/bin/chef-client:57:in `<main>'`

**Comment by badsector3** [comment]
Is the auto-register possible? Anybody?

**Comment by wojtek-fliposports** [comment]
This problem is not related with certificates by them self but a possible file is not correct CRT file. Make sure that in `/etc/chef/trusted_certs` there are only correct CRT files and remove/move PEM files and others

**Comment by thommay** [comment]
Closing as a dup of #5376
