### ISSUE TITLE
Service provider for rpcbind detected as Upstart on Debian 8

### ISSUE THREAD

**Issue by gsreynolds** [chef/chef#6076]
## Description

Service resource detects provider as Chef::Provider::Service::Upstart for NFS service rpcbind on Debian 8. Issue is related to but not specific to or caused by (https://github.com/atomic-penguin/cookbook-nfs/issues/76). The NFS cookbook previously had service provider overrides based on platform (https://github.com/atomic-penguin/cookbook-nfs/commit/7b8b8c483119a52b3d3971dc29b8c01322a858c7). These were removed in v2.3.0 of the cookbook, deferring to the Chef provider helpers.

Unfortunately, this has exposed an issue with the helpers. The issue appears to be that because /etc/init/rpcbind.conf exists (https://packages.debian.org/jessie/amd64/rpcbind/filelist), Chef is incorrectly detecting the init provider as Upstart instead of Insserv. Removing the file results in the correct behaviour.

## Chef Version

Issue present on chef_version=13.0.118

## Platform Version

Debian 8.6

## Replication Case

Either run the nfs::default recipe (v2.3.1)

or

Install nfs-common package. 
Attempt to restart the rpcbind service using a recipe.
```
service 'rpcbind' do 
  action :restart
end
```
## Client Output & Stacktrace

Default behaviour & stacktrace reproduced in chef-shell
https://gist.github.com/gsreynolds/540a66658c99ec20358b04d40c4b8caf#file-1-upstart-detected

Same behaviour in chef-client using nfs::default
https://gist.github.com/gsreynolds/540a66658c99ec20358b04d40c4b8caf#file-2-chef-client-nfs-default

`rm /etc/init/rpcbind.conf` causes Chef to correctly identify provider and restart the service successfully:
https://gist.github.com/gsreynolds/540a66658c99ec20358b04d40c4b8caf#file-3-insserv-detected

Thanks in advance!

**Comment by thommay** [comment]
Is upstart running on the system at all, or is it all insserv?

**Comment by gsreynolds** [comment]
No Upstart installed or running on the system, stock Debian 8 with systemd. Reproducible in both the debian:8 docker image and chef/bento Debian 8.6 vagrant box, with only the addition of the nfs-common package (specifically it's rpcbind dependency)

Restarting the service by manually specifying the systemd provider works correctly, but this is using init.d behind the scenes

```
chef (13.0.118)> recipe_mode
chef:recipe (13.0.118)> service 'rpcbind' do
chef:recipe > provider Chef::Provider::Service::Systemd
chef:recipe ?> action :restart
chef:recipe ?> end
 => <service[rpcbind] @name: "rpcbind" @before: nil @params: {} @provider: Chef::Provider::Service::Systemd @allowed_actions: [:nothing, :enable, :disable, :start, :stop, :restart, :reload, :mask, :unmask] @action: [:restart] @updated: false @updated_by_last_action: false @source_line: "(irb#1):1:in `irb_binding'" @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @service_name: "rpcbind" @enabled: nil @running: nil @masked: nil @options: nil @parameters: nil @pattern: "rpcbind" @start_command: nil @stop_command: nil @status_command: nil @restart_command: nil @reload_command: nil @init_command: nil @priority: nil @timeout: nil @run_levels: nil @user: nil @declared_type: :service @cookbook_name: nil @recipe_name: nil>
chef:recipe (13.0.118)> run_chef
[2017-04-20T13:00:04+00:00] INFO: Processing service[rpcbind] action restart ((irb#1) line 1)
Failed to get unit file state for rpcbind.service: No such file or directory
Failed to get unit file state for rpcbind.service: No such file or directory
[2017-04-20T13:00:04+00:00] INFO: service[rpcbind] restarted
 => true
```

```
systemctl status rpcbind
● rpcbind.service - LSB: RPC portmapper replacement
   Loaded: loaded (/etc/init.d/rpcbind)
  Drop-In: /run/systemd/generator/rpcbind.service.d
           └─50-rpcbind-$portmap.conf
   Active: active (running) since Thu 2017-04-20 13:00:04 UTC; 10s ago
  Process: 2194 ExecStop=/etc/init.d/rpcbind stop (code=exited, status=0/SUCCESS)
  Process: 2200 ExecStart=/etc/init.d/rpcbind start (code=exited, status=0/SUCCESS)
   CGroup: /system.slice/rpcbind.service
           └─2207 /sbin/rpcbind -w

Apr 20 13:00:04 5c4f075da872 systemd[1]: Starting LSB: RPC portmapper replacement...
Apr 20 13:00:04 5c4f075da872 rpcbind[2200]: Starting rpcbind daemon....
Apr 20 13:00:04 5c4f075da872 systemd[1]: Started LSB: RPC portmapper replacement.
```

**Comment by lamont-granquist** [comment]
well this is where the magic is supposed to happen:

https://github.com/chef/chef/blob/master/lib/chef/provider/service.rb#L247

**Comment by gsreynolds** [comment]
In case anyone comes across the same issue, I'm currently working around it just using edit_resource:

```ruby
%w(idmap portmap lock).each do |srv|
  edit_resource(:service, srv) do
    provider Chef::Provider::Service::Systemd
  end
end
```
