### ISSUE TITLE
value_for_platform_family broken when version provided?

### ISSUE THREAD

**Issue by rmoriz** [chef/chef#6085]
## Description

Running on centos 6.2:

```ruby
default['erlang']['install_method'] = value_for_platform_family(
  'rhel'   => { '~> 6.0' => 'esl' },
  'debian' => { '~> 7.0' => 'esl' },
  'default' => 'package'
)
```
After [reading the docs](https://docs.chef.io/dsl_recipe.html#value-for-platform-family) I expected `node['erlang']['install_method']` to be `esl` but actually it's `{"~> 6.0"=>"esl"}` (Chef::Node::ImmutableMash)

## Chef Version

Chef Client, version 13.1.5

**Comment by coderanger** [comment]
The docs are incorrect in this case, that API never supported version queries (but `value_for_platform` does). This is because other than a few special cases (`rhel` and `mac_os_x` mostly) there is no consistency in platform versions between family members.
