### ISSUE TITLE
'powershell_script' Process not Elevated when running under alternative credentials

### ISSUE THREAD

**Issue by username-is-already-taken2** [chef/chef#6086]
## Description
When using the resource ['powershell_script'](https://docs.chef.io/resource_powershell_script.html) and providing an alternative user details. The chef client is spawning a process as that user that is not elevated and I'm being prompt by UAC when executing my code block.

The user context that I am providing in the resource is an administrator, if I execute the same 'powershell_script' resource block without the user credentials then my powershell code is run elevated and I don't have a uac prompt

I would also like to add that the chef-client is successfully launching the process in the context of my provided user credentials, this is a great feature.  Thanks very much. 👍 

## Chef Version
```
C:\chef>chef-client --version
Chef: 12.19.36
```
## Platform Version
```
Windows 2012 R2 - [Version 6.3.9600]
```
## Replication Case
Here is a striped down example, if it hangs when testing it could be that its waiting at a UAC prompt.  I observed the prompt as I was logged on to the console when testing.

```
powershell_script 'runas_example' do
  code <<-EOH
    Start-Process -Verb runas cmd.exe -ArgumentList '/c time /t'
  EOH
  user 'another_administrator'
  password 'another_password'
end
```

**Comment by username-is-already-taken2** [comment]
I worked with @smurawski on the windows slack channel to confirm the issue

**Comment by smurawski** [comment]
Root issue - https://github.com/chef/mixlib-shellout/issues/142

**Comment by dheerajd-msys** [comment]
@username-is-already-taken2, There is a workaround for this issue that when chef-client is run as a service then `powershell_script` doesn't prompt UAC for alternate user.

Verified on :
Platform    : Windows 2012 R2
Chef-client : 13.0.118

**Comment by smurawski** [comment]
@dheerajd-msys `powershell_script` with alternate credentials from what the service is running as?

**Comment by dheerajd-msys** [comment]
@smurawski, @username-is-already-taken2 Please ignore the service part.
Initially I was trying to run `chef-apply` on my local machine which is not registered as a node on any chef-server and I was able to reproduce this issue.

Today I bootstrapped a node and then ran this recipe using `chef-apply`:
```
powershell_script 'runas_example' do
  code <<-EOH
    Start-Process -Verb runas cmd.exe -ArgumentList '/c time /t'
  EOH
  user 'another_administrator'
  password 'another_password'
end
```
It doesn't prompt for UAC.
I am wondering if it's related to `SeAssignPrimaryTokenPrivilege` user right. Please check the note here: https://discourse.chef.io/t/pre-release-announcement-chef-client-12-19/10452
It says: 
```
When Chef is running as a service, this feature requires that the user that Chef runs as has 
'SeAssignPrimaryTokenPrivilege' (aka 'SE_ASSIGNPRIMARYTOKEN_NAME') user right. By default only
 LocalSystem and NetworkService have this right when running as a service. This is necessary even if the 
user is an Administrator.
```

**Comment by smurawski** [comment]
@dheerajd-msys running chef-apply in your interactive user context is not the same as running via the service or task scheduler.  In my testing (noted in the chef/mixlib-shellout#142 ), I've assigned that right to a user, as well as testing with the system account which has that right be default.

**Comment by dheerajd-msys** [comment]
@smurawski Does it mean that you still get UAC prompt upon running the `powershell_script` after assigning `SeAssignPrimaryTokenPrivilege`?

**Comment by smurawski** [comment]
@dheerajd-msys I mean that the process that is launched with alternate credentials (which cannot be accomplished without `SeAssignPrimaryTokenPrivilege` right in a non-interactive context) is not elevated regardless of the elevation context of the starting process.

This isn't something about `powershell_script`, it is related to how the process is being launched via mixlib-shellout.

**Comment by NimishaS** [comment]
I tried running `Start-Process -Verb runas cmd.exe -ArgumentList '/c time /t'` directly from powershell console while I was logged in with a user added in `Administrator` group. I got a UAC prompt.
This seems like a default behavior of Windows and not related to `powershell_script` or `mixlib-shellout`.

**Comment by username-is-already-taken2** [comment]
Hi there @NimishaS 

Thanks for your reply.

Logging into a windows machine as someone who is a member of the administrators group doesn't mean by default that your powershell console is elevated when you start it.

When you did your test did you notice the word "administrator" in the console title?  if not then it's just a standard user.

This is an example of 2 console started within the same session.....

![image](https://user-images.githubusercontent.com/13700297/27689520-58ebbfb2-5cd6-11e7-97e1-8f28fe19d87e.png)

the administrator one works yet the standard one doesn't.  It comes down to the console being launched with elevated permissions. This will then allow elevated processes to spawned without uac

Best Regards

Gary

**Comment by NimishaS** [comment]
Thanks Gary, my bad. Yeah I didn't run my powershell console as Administrator.

**Comment by NimishaS** [comment]
@username-is-already-taken2 , we are adding an option in `mixlib-shellout` to launch a process with elevated privileges. We'll be adding a similar option in `powershell_script` resource too.

**Comment by NimishaS** [comment]
@username-is-already-taken2 , this issue will be fixed once https://github.com/chef/chef/pull/6271 is merged and released.

You'll be able to pass `elevated` option in the recipe:
```
powershell_script 'runas_example' do
  code <<-EOH
    Start-Process -Verb runas cmd.exe -ArgumentList '/c time /t'
  EOH
  user 'another_administrator'
  password 'another_password'
  elevated true
end
```

**Note**: The user who will be running Chef requires `Replace a process level token` permission to run a command which requires elevated privileges. So you'll need to add that right.

**Comment by username-is-already-taken2** [comment]
Thank you @NimishaS  I really appreciate you following this through.

**Comment by username-is-already-taken2** [comment]
@NimishaS what happens now it's merged with master? Do we wait for the next chef-client build cycle?  I think once its in and I can test, I could look to create a PR to updated the powershell resource in the docs section.

**Comment by NimishaS** [comment]
@username-is-already-taken2 , we need to wait for chef-client's release. @btm will be able to comment about this.

**Comment by btm** [comment]
@username-is-aleady-taken2 there is a build in current that contains this code that you can try. I think it is a couple of weeks until the next scheduled release.

https://downloads.chef.io/chef/current/13.3.18
