### ISSUE TITLE
Disable local mode's localhost socket by default in Chef 14

### ISSUE THREAD

**Issue by danielsdeleo** [chef/chef#6088]
## Description

At some point in the Chef 12 cycle, I added the "socketless" mode for Chef Zero/local mode. It's used for all internal requests within local mode, but local mode still had to listen on port 8889 to support Chef Provisioning stuff when SSHing to a remote machine with a tunnel back to the workstation. Provisioning should not be the dominant use case and there are some security concerns to opening a port to Chef Zero, even on localhost. For now, users can pass `--no-listen` to use only the internal socketless interface, but this should be the default. As a breaking change, it's best to wait for a major version, and we missed the boat on 13.0, so 14.0 it is.

## Chef Version

Applies to whenever socketless mode was added.

## Platform Version

Anything running local mode.

## Replication Case

The security issue is if a malicious actor with an unprivileged account on the system connects to the local mode socket and does stuff like uploading a rootkit cookbook or whatever.

The config setting is here: https://github.com/chef/chef/blob/71863634ac50dbfb2601de536828b779517066ae/chef-config/lib/chef-config/config.rb#L387

**Comment by lamont-granquist** [comment]
closed by #6174

**Comment by coderanger** [comment]
I only fixed `chef-solo`, we still need to change it for `chef-client -z`.

**Comment by coderanger** [comment]
(though I'm also pretty okay with calling this a security fix and thus an allowed compat break before 14.0, especially since almost no one knows about the listen mode being a thing and they can always turn it back on manually).

**Comment by lamont-granquist** [comment]
ah, 'k

i'd suggest retconning it and pretending it shipped in 13.0

**Comment by coderanger** [comment]
Yeah, my plan is to flip the default and put a deprecation warning if they use the CLI arg to turn it back on, and then rip it out for 14.
