### ISSUE TITLE
Cookbook gem installs don't log in Chef 13

### ISSUE THREAD

**Issue by tas50** [chef/chef#6089]
## Description

When you define a gem to install in a cookbook metadata it doesn't actually log that the installation is occurring during the run

## Chef Version

13

## Platform Version

Ubuntu 16.04

## Client Output

This cookbook includes gem 'aws-sdk', '~> 2' in the metadata and does in fact install the gem, but it logs nothing

```
       Preparing to unpack .../chef_13.0.118-1_amd64.deb ...
       Unpacking chef (13.0.118-1) ...
       Setting up chef (13.0.118-1) ...
       Thank you for installing Chef!
       Transferring files to <instance-monitoring-ubuntu-1404>
       Starting Chef Client, version 13.0.118
       Creating a new client identity for instance-monitoring-ubuntu-1404 using the validator key.
       resolving cookbooks for run list: ["aws_test::instance_monitoring"]
       Synchronizing Cookbooks:
         - aws_test (0.0.1)
         - aws (5.0.1)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 2 resources
       Recipe: aws_test::instance_monitoring
         * aws_instance_monitoring[enable detailed monitoring] action enable
```

**Comment by lamont-granquist** [comment]
closing this as we're more likely to deprecate this feature than fix it (also this is likely a logger/formatter issue that we've already addressed or we're tracking somewhere else)
