### ISSUE TITLE
Add a flag to core chef resource properties to eventually ban overriding them

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#6099]
`property :retries, String` on a resource should explode in the same place as where we check for overriding methods with properties.

we probably need to include a flag on the property so that it can be marked non-overridable by child classes.  then we should mark `:retries`, `:retry_delay`, `:sensitive`, etc with this flag.  in 13.1 it should spit out a deprecation that warns that it will be a raise and then in 14.0 it should raise.

**Comment by lamont-granquist** [comment]
we deliberately subclass and the override properties in the subclass in some cases in core chef, and its useful to do so, so we can't just globally ban overriding properties -- even though technically you're at least slightly violating the inheritance is-a relationship every time you do this.

**Comment by lamont-granquist** [comment]
and at least some cookbooks have implemented their own `:sensitive` so that would break existing cookbooks so needs to be done as a deprecation.

**Comment by lamont-granquist** [comment]
in looking at this i just haven't been seeing this come up as a huge issue.  i think we've addressed the 98% use case in addressing breakages due to methods being overridden.  dropping the priority on this.

**Comment by tas50** [comment]
I was reading this over this week and thought it was probably a good one to close.

**Comment by lamont-granquist** [comment]
yeah this just hasn't been an issue, lets open it again if someone ever has issues with it.
