### ISSUE TITLE
SLES 11: issue with GLIBC_2.12' not found

### ISSUE THREAD

**Issue by samsonkolge** [chef/chef#6109]
## Description

Kitchen create on sles11 gives the below error:

       Transferring files to <default-suse-sles11sp3>
       /opt/chef/embedded/bin/ruby: /lib64/libpthread.so.0: version `GLIBC_2.12' not found (required by /opt/chef/embedded/lib/libruby.so.2.4)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-suse-sles11sp3>.  Please see .kitchen/logs/default-suse-sles11sp3.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

## Chef Version

$ chef -v
Chef Development Kit Version: 1.2.22
chef-client version: 12.18.31
delivery version: master (0b746cafed65a9ea1a79de3cc546e7922de9187c)
berks version: 5.6.4
kitchen version: 1.16.0

## Platform Version

I am trying to create environment on windows 8.1

## Replication Case
Below is my .kitchen.yml file
$ cat .kitchen.yml
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: suse/sles11sp3

suites:
  - name: default
    run_list:
      - recipe[sles11::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:

**Comment by lamont-granquist** [comment]
prolly dup of #5774 and https://github.com/test-kitchen/kitchen-vagrant/issues/293 and kitchen caching
