### ISSUE TITLE
RedHat service provider does not set rc.d symlinks correctly

### ISSUE THREAD

**Issue by cbroglie** [chef/chef#6113]
## Description

The RedHat provider executes `/sbin/chkconfig <service> on` instead of `/sbin/chkconfig --add <service>`. This results in only the S* symlinks being created, so the service is not stopped when entering run levels which it should not be running.

Here is an example of the behavior (my service is called messaging-worker):
```shell
[vagrant@localhost ~]$ sudo /sbin/chkconfig --del messaging-worker
[vagrant@localhost ~]$ ls /etc/rc[0-6].d/*worker
ls: cannot access /etc/rc[0-6].d/*worker: No such file or directory
[vagrant@localhost ~]$ sudo /sbin/chkconfig messaging-worker on
[vagrant@localhost ~]$ ls /etc/rc[0-6].d/*worker
/etc/rc2.d/S71messaging-worker  /etc/rc4.d/S71messaging-worker
/etc/rc3.d/S71messaging-worker  /etc/rc5.d/S71messaging-worker
[vagrant@localhost ~]$ sudo /sbin/chkconfig --add messaging-worker
[vagrant@localhost ~]$ ls /etc/rc[0-6].d/*worker
/etc/rc0.d/K15messaging-worker  /etc/rc3.d/S71messaging-worker  /etc/rc6.d/K15messaging-worker
/etc/rc1.d/K15messaging-worker  /etc/rc4.d/S71messaging-worker
/etc/rc2.d/S71messaging-worker  /etc/rc5.d/S71messaging-worker
[vagrant@localhost ~]$
```

The relevant code is [here](https://github.com/chef/chef/blob/e9e9fe8711248fc9748fd3b633b7418eb8cd0ed1/lib/chef/provider/service/redhat.rb#L112). Looking through the source I found that it could be made to work if the `run_levels` property were set correctly, but that appears to be buggy (it threw an exception for me, stack trace below). Additionally, this would require specifying the run levels in chef, instead of pulling them from the init.d script itself.

## Chef Version

13.0

## Platform Version

CentOS 6.9

## Replication Case

The necessary config (assuming the init.d script is in place) is just:

```ruby
service 'messaging-worker' do
  action :enable
end
```

And the relevant header bits of the init.d script:
```shell
#!/bin/bash
#
# chkconfig: 2345 71 15
# description: messaging-worker service daemon
```

This results in the S symlinks being set for run levels 2-5, but no K symlinks for 0, 1, or 6, meaning the service is not stopped on shutdown or reboot:

```shell
[vagrant@localhost ~]$ ls /etc/rc[0-6].d/*worker
/etc/rc2.d/S71messaging-worker  /etc/rc4.d/S71messaging-worker
/etc/rc3.d/S71messaging-worker  /etc/rc5.d/S71messaging-worker
[vagrant@localhost ~]$
```

I did also try to set the `run_levels` property to work around this, but it generated an exception (see below). Here is the config I tried:
 
```ruby
service 'messaging-worker' do
  action :enable
  run_levels [2,3,4,5]
end
```

## Client Output

https://gist.github.com/cbroglie/d398354c685b819c12a3701834a77ecc

## Stacktrace

https://gist.github.com/cbroglie/b0a06a2e4efb595d073435e06ba7965e

**Comment by lamont-granquist** [comment]
dup of #1120?
