### ISSUE TITLE
Kill vendor branching in cookbook site install

### ISSUE THREAD

**Issue by coderanger** [chef/chef#6115]
Or just kill `knife cookbook site` in general, but at a minimum we should get rid of the the vendor branching entirely.

**Comment by lamont-granquist** [comment]
adding to the 13.1 milestone (which will most likely all become the 13.1 milestone or later) in order to get deprecations in.

**Comment by lamont-granquist** [comment]
so we need the deprecations for this put in otherwise we wind up dropping in deprecation warnings next february before we drop it in april or whatever

**Comment by tas50** [comment]
This was nuked
