### ISSUE TITLE
Unable to use zypper_package resource on SLES 11 SP4

### ISSUE THREAD

**Issue by rosario-mattera** [chef/chef#6121]
## Description

When I try to use the zypper_package resource to install a rpm package on SLES 11 SP4 I get several errors.
If I try to install manually using zypper with the same options revelead in the log, I have no problems. Could you please support?

## Chef Version

Chef-Client 13.0.123

## Platform Version

SLES 11 SP4

## Replication Case

When I try to use the zypper_package resource to install a rpm package on SLES 11 SP4 I get several errors.

Compiled Resource:
# Declared in /var/chef/cache/cookbooks/networker/recipes/default.rb:51:in `from_file'

zypper_package("networker") do
  package_name "networker"
  action [:install]
  default_guard_interpreter :default
  declared_type :zypper_package
  cookbook_name "networker"
  recipe_name "default"
  source "/var/chef/cache/lgtoclnt-9.1.0.4-1.x86_64.rpm"
end
 

## Client Output

```
#<Mixlib::ShellOut::ShellCommandFailed: zypper_package[networker] (networker::default line 51) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '3' ---- Begin output of ["zypper", "--non-interactive", "install", "--auto-agree-with-licenses"] ---- STDOUT: install (in) [options] <capability|rpm_file_uri> ... Install packages with specified capabilities or RPM files with specified location. A capability is NAME[.ARCH][OP<VERSION>], where OP is one of <, <=, =, >=, >. Command options: --from <alias|#|URI> Select packages from the specified repository. -r, --repo <alias|#|URI> Load only the specified repository. -t, --type <type> Type of package (package, patch, pattern, product, srcpackage). Default: package. -n, --name Select packages by plain name, not by capability. -C, --capability Select packages by capability. -f, --force Install even if the item is already installed (reinstall), downgraded or changes vendor or architecture. --oldpackage Allow to replace a newer item with an older one. Handy if you are doing a rollback. Unlike --force it will not enforce a reinstall. -l, --auto-agree-with-licenses Automatically say 'yes' to third party license confirmation prompt. See 'man zypper' for more details. --debug-solver Create solver test case for debugging. --no-recommends Do not install recommended packages, only required. --recommends Install also recommended packages in addition to the required. -R, --no-force-resolution Do not force the solver to find solution, let it ask. --force-resolution Force the solver to find a solution (even an aggressive one). -D, --dry-run Test the installation, do not actually install. --download Set the download-install mode. Available modes: only, in-advance, in-heaps, as-needed -d, --download-only Only download the packages, do not install. STDERR: Too few arguments. At least one package name is required. ---- End output of ["zypper", "--non-interactive", "install", "--auto-agree-with-licenses"] ---- Ran ["zypper", "--non-interactive", "install", "--auto-agree-with-licenses"] returned 3> had an error:
zypper_package[networker] (networker::default line 51) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '3' ---- Begin output of ["zypper", "--non-interactive", "install", "--auto-agree-with-licenses"] ---- STDOUT: install (in) [options] <capability|rpm_file_uri> ... Install packages with specified capabilities or RPM files with specified location. A capability is NAME[.ARCH][OP<VERSION>], where OP is one of <, <=, =, >=, >. Command options: --from <alias|#|URI> Select packages from the specified repository. -r, --repo <alias|#|URI> Load only the specified repository. -t, --type <type> Type of package (package, patch, pattern, product, srcpackage). Default: package. -n, --name Select packages by plain name, not by capability. -C, --capability Select packages by capability. -f, --force Install even if the item is already installed (reinstall), downgraded or changes vendor or architecture. --oldpackage Allow to replace a newer item with an older one. Handy if you are doing a rollback. Unlike --force it will not enforce a reinstall. -l, --auto-agree-with-licenses Automatically say 'yes' to third party license confirmation prompt. See 'man zypper' for more details. --debug-solver Create solver test case for debugging. --no-recommends Do not install recommended packages, only required. --recommends Install also recommended packages in addition to the required. -R, --no-force-resolution Do not force the solver to find solution, let it ask. --force-resolution Force the solver to find a solution (even an aggressive one). -D, --dry-run Test the installation, do not actually install. --download Set the download-install mode. Available modes: only, in-advance, in-heaps, as-needed -d, --download-only Only download the packages, do not install. STDERR: Too few arguments. At least one package name is required. ---- End output of ["zypper", "--non-interactive", "install", "--auto-agree-with-licenses"] ---- Ran ["zypper", "--non-interactive", "install", "--auto-agree-with-licenses"] returned 3
```

## Stacktrace
`/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:289:in `invalid!'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/mixlib-shellout-2.2.7/lib/mixlib/shellout.rb:276:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/mixin/shell_out.rb:120:in `shell_out!'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/mixin/shell_out.rb:76:in `shell_out_compact!'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/mixin/shell_out.rb:95:in `shell_out_compact_timeout!'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/provider/package/zypper.rb:143:in `zypper_package'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/provider/package/zypper.rb:106:in `install_package'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/provider/package.rb:102:in `block (3 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/provider/package.rb:258:in `multipackage_api_adapter'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/provider/package.rb:101:in `block (2 levels) in <class:Package>'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/mixin/why_run.rb:52:in `add_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/provider.rb:202:in `converge_by'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/provider/package.rb:100:in `block in <class:Package>'
(eval):2:in `block in action_install'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/provider.rb:211:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/provider.rb:211:in `compile_and_converge_action'
(eval):2:in `action_install'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/provider.rb:171:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/resource.rb:591:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/runner.rb:70:in `run_action'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/runner.rb:98:in `each'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/runner.rb:98:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/runner.rb:97:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/client.rb:715:in `block in converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/client.rb:710:in `catch'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/client.rb:710:in `converge'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/client.rb:749:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/client.rb:286:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application.rb:291:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application.rb:279:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application.rb:279:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application.rb:244:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application.rb:232:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/chef-13.0.123/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:58:in `load'
/usr/bin/chef-client:58:in `<main>'`

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* Requests for new or alternative functionality should be made to [feedback.chef.io](https://feedback.chef.io/forums/301644-chef-product-feedback/category/110832-chef-client)
* [Chef Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by tas50** [comment]
SLES 11 is now EOL so we won't be resolving this issue. You'll want to upgrade to a currently supported SLES release.
