### ISSUE TITLE
dsc_resource should support SxS module versions.

### ISSUE THREAD

**Issue by MichaelStankiewicz** [chef/chef#6124]
## Description

When attempting to process a DSC resource using the dsc_resource resource, an exception is thrown during the Chef converge if multiple versions of the module exist on the managed node.

## Chef Version

Chef client version 12.19.36-1 x64

## Platform Version

Windows Server 2012R2 with WMF v5.1.

## Replication Case

Install multiple versions of a DSC resource on a managed node.  Then create a dsc_resource block in a recipe that leverages that resource.  Apply the recipe to the node and execute a converge routine.

NOTE: The invoke-dscresource does support a -ModuleName parameter which accepts a 'ModuleInfo Object'.  With this, you can supply both the module name, along with the version, to overcome this issue.  The issue at hand is that the dsc_resource needs to be adapted to support this functionality.

## Client Output

The chef-client run will return the following: 'Resource %DSC_Resource_Name% was not found.'  However if you manually attempt to invoke the resource on the managed node using the Invoke-DscResource cmdlet, you see that the reason for the failure is due to multiple modules existing with the same version, and the Invoke-DscResource can't distinguish between which one to use since the dsc_resource doesn't support a 'version' parameter.

**Comment by smurawski** [comment]
@MichaelStankiewicz as a workaround you can use the `ps_module_spec` helper from the `dsc_contrib` cookbook.  https://github.com/smurawski/dsc_contrib/blob/master/README.md#ps_module_spec  

https://supermarket.chef.io/cookbooks/dsc_contrib

**Comment by MichaelStankiewicz** [comment]
Thanks, @smurawski.  I'll be giving that a go for sure.

**Comment by btm** [comment]
12.18.46+ added support for specifying a `module_version` in https://github.com/chef/chef/pull/5701/. This is documented on the docs site: https://docs.chef.io/resource_dsc_resource.html#properties.

How is this different than that feature?

**Comment by MichaelStankiewicz** [comment]
@btm I wasn't aware this was integrated into 12.9.  I'll give it a go and use it going forward.

**Comment by btm** [comment]
@MichaelStankiewicz thanks! Given this has sat open I thought I might be missing something. I'm going to close this issue as fixed by #5701, let me know if you find otherwise though.

**Comment by MichaelStankiewicz** [comment]
@btm So I've confirmed that this works, however I think the documentation can use a minor update.  If you specify the module_version parameter, you MUST also specify the module_name parameter as well.  However the documentation as currently worded, implies that if module_name is not supplied, the module name will be inferred, implying that the property is not mandatory when in fact it is (at least when a module_version is also specified).

Per the [current documentation](https://docs.chef.io/resource_dsc_resource.html#properties):

> module_name
> Ruby Type: String
> 
> The name of the module from which a DSC resource originates. If this property is not specified, it will be inferred.

**Comment by btm** [comment]
@MichaelStankiewicz thanks. Would you please open an issue against https://github.com/chef/chef-web-docs/issues for the documentation change? The docs team will do the work but your help finding the right language will help them make sure the right change is made.

**Comment by MichaelStankiewicz** [comment]
Done.  [#892 ](https://github.com/chef/chef-web-docs/issues/892)opened.
