### ISSUE TITLE
bundle install fails for chef package due to missing file

### ISSUE THREAD

**Issue by pvandervelde** [chef/chef#6126]
I'm trying to run bundle install to get my chef related gems installed. It works for all gems except the chef gem itself.

My gem file looks like this:

    source 'https://rubygems.org' do
      gem 'chef', '13.0.118'
    end

The command line is:

    bundle install --gemfile="c:\myproject\Gemfile" --path "c:\myproject\gems" --binstubs="c:\myproject\gems\bin" --no-cache

And the output is:

    Fetching gem metadata from https://rubygems.org/.........
    Fetching version metadata from https://rubygems.org/..
    Resolving dependencies...
    Installing public_suffix 2.0.5
    Installing builder 3.2.3
    Using bundler 1.12.5
    Installing fuzzyurl 0.9.0
    Installing mixlib-config 2.2.4
    Installing ffi 1.9.18
    Installing wmi-lite 1.0.0
    Installing libyajl2 1.2.0 with native extensions
    Installing hashie 3.5.5
    Installing mixlib-log 1.7.1
    Installing rack 2.0.1
    Installing uuidtools 2.1.5
    Installing diff-lcs 1.3
    Installing erubis 2.7.0
    Installing highline 1.7.8
    Installing iniparse 1.4.2
    Installing iso8601 0.9.1
    Installing mixlib-cli 1.7.0
    Installing net-ssh 4.1.0
    Installing ipaddress 0.8.3
    Installing plist 3.3.0
    Installing systemu 2.6.5
    Installing proxifier 1.0.3
    Installing rspec-support 3.5.0
    Installing multi_json 1.12.1
    Installing net-telnet 0.1.1
    Installing sfl 2.3
    Installing syslog-logger 1.6.8
    Installing win32-api 1.5.3
    Installing addressable 2.5.1
    Installing win32-process 0.8.3
    Installing win32-dir 0.5.1
    Installing win32-ipc 0.7.0
    Installing win32-eventlog 0.6.3
    Installing win32-mmap 0.4.2
    Installing ffi-win32-extensions 1.0.3
    Installing ffi-yajl 2.3.0 with native extensions
    Installing mixlib-archive 0.4.1
    Installing mixlib-authentication 1.4.1
    Installing net-sftp 2.1.2
    Installing net-ssh-gateway 2.0.0
    Installing net-scp 1.2.1
    Installing rspec-core 3.5.4
    Installing rspec-expectations 3.5.0
    Installing rspec-mocks 3.5.0
    Installing windows-api 0.4.4
    Installing mixlib-shellout 2.2.7
    Installing win32-event 0.6.3
    Installing win32-mutex 0.4.3
    Installing win32-service 0.8.10
    Installing chef-zero 13.0.0
    Installing net-ssh-multi 1.2.1
    Installing specinfra 2.67.9
    Installing rspec_junit_formatter 0.2.3
    Installing rspec-its 1.2.0
    Installing rspec 3.5.0
    Installing chef-config 13.0.118
    Installing serverspec 2.38.0
    Installing ohai 13.0.1
    Installing chef 13.0.118 with native extensions

    Errno::ENOENT: No such file or directory @ rb_sysopen - c:/myproject/gems/ruby/2.3.0/gems/chef-13.0.118-universal-mingw32/spec/functional/assets/yumrepo/repodata/4ac40fa3c6728c1401318e2e20a997436624e83dcf7a5f952b851ef422637773-filelists.sqlite.bz2
    An error occurred while installing chef (13.0.118), and Bundler cannot continue.
    Make sure that `gem install chef -v '13.0.118'` succeeds before bundling.

The error is correct, that file does not exist if I install with bundler but if I run gem install chef with the following command line it works just fine and all files are there.

gem install --install-dir c:\myproject\gems chef -v 13.0.118

My global gem list is

    *** LOCAL GEMS ***

    bigdecimal (default: 1.2.8)
    bundler (1.14.6)
    io-console (default: 0.4.5)
    json (default: 1.8.3)
    psych (default: 2.1.0)
    rake (12.0.0)
    rdoc (default: 4.2.1)

And my OS is Windows 10.

Any ideas why this is not working the way I would expect it to? Am I missing additional gems / tools?

This was reported as bundler/bundler#5625 but was deemed more likely a chef packaging issue than a bundler issue.

**Comment by coderanger** [comment]
We pretty actively recommend using our installers, especially on non-Linux platforms. Is there a reason you can't use the normal installers?

**Comment by pvandervelde** [comment]
I could but we're working on removing as much software from our build servers as we can. Having to install Chef means we have multiple ruby run times etc.. That's all software we'd rather not have to install and maintain. We don't actually run chef on the build machines themselves, we just need the code so that the build scripts can execute chefspec. We only run chef on the images we're building by installing chef solo and then using that to execute the cookbooks.

**Comment by lamont-granquist** [comment]
Closing this as we don't have the bandwidth to support custom gem installs.  We'd accept patches, but we clearly don't have any time to investigate the problem.
