### ISSUE TITLE
Unable to detect ip address in Chef 13 when using knife ssh

### ISSUE THREAD

**Issue by benthorner** [chef/chef#6127]
## Description

Chef 13 chef-client no longer detects no ip address when using knife ssh. The issue appears to be caused by the network plugin being unable to run 'ip addr' in a non-login shell (PATH does not contain /sbin).

## Chef Version

Chef Client 13.0.118 (also broken in 13.0.113)

## Platform Version

Red Hat Enterprise Linux Server release 6.7 (Santiago)

## Replication Case

   knife ssh 'name:XXXXXX' 'sudo chef-client -r ""'

## Client Output

   knife ssh 'name:XXXXXX' 'sudo chef-client -r ""'
   XXXXXXX knife sudo password: 
   Enter your password: 
   XXXXXXX Starting Chef Client, version 13.0.118
   XXXXXXX [2017-05-06T09:26:39+01:00] WARN: Plugin Network: unable to detect ipaddress

Debug output...

   XXXXXXX [2017-05-06T09:31:45+01:00] DEBUG: Plugin Network: ran 'ip addr' and failed #<Errno::ENOENT: No such file or directory - ip>
   XXXXXXX [2017-05-06T09:31:45+01:00] DEBUG: Plugin Network threw #<Ohai::Exceptions::Exec: No such file or directory - ip>

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

**Comment by akitada** [comment]
This issue has been fixed in master. https://github.com/chef/ohai/issues/990

**Comment by benthorner** [comment]
Ah, I didn't find that when I was looking. Thanks :-)
