### ISSUE TITLE
chef 13 and updated_by_last_action?

### ISSUE THREAD

**Issue by pantocrator27** [chef/chef#6130]
## Description

I have read a lot about Chef 13 deprecating `updated_by_last_action?` but cannot find any documentation about what has replaced this functionality

## Chef Version

13

## Platform Version

All

**Comment by coderanger** [comment]
It is almost never needed these days. It's not really deprecated so much as if you aren't so advanced as to be reading the Chef code to start with, you shouldn't know it exists. When building custom resources with the `action :foo do` syntax and simpler resources under the hood, that is handled automatically.

**Comment by pantocrator27** [comment]
my use case for why I use it is the following ... behind a proxy, I use the `rubygems` cookbook to configure my rubygem sources to a private rubygem repository and want to force it to be run first prior to other resources.  so I:

```
gemrc_global = gemrc 'global' do
  values(
    sources: [
      node['my-cookbook-name']['url'],
    ]
  )

  action :nothing
end
gemrc_global.run_action(:create)

# reload gemrc file for rest of the Chef run
Gem.configuration = Gem::ConfigFile.new [] if gemrc_global.updated_by_last_action?
```

The above currently exists in a recipe.  Are you suggesting I build a custom resource around a custom resource to achieve this functionality?

**Comment by coderanger** [comment]
I assume you're trying to use that to configure where Chef installs gems from for stuff like gem deps and `chef_gem`? If so you can just put that in the `client.rb` config:

```ruby
rubygems_url 'https://whatever'
```

Otherwise yes, fix that to be a normal resource.

**Comment by pantocrator27** [comment]
@coderanger I did not know that `rubygems_url` for `client.rb`.  I will give it a go!
