### ISSUE TITLE
Chef With Internally Hosted RubyGems Server

### ISSUE THREAD

**Issue by pantocrator27** [chef/chef#6133]
## Description

I work behind a firewall in which we have an internally hosted RubyGems server that is served on https and signed with a private certificate.  

For Chef 12, I have a RubyGems cookbook that wraps https://github.com/chef-cookbooks/rubygems and in my `client.rb` file specify `ssl_ca_path`.  However it appears that the mechanism to install the gems does not obey the `ssl_ca_path` directive.  I originally set my `/opt/chef/embedded/etc/gemrc` file to turn off SSL verification until I figured out I could append my custom certificate to `/opt/chef/embedded/ssl/certs/cacert.pem` and re-enabled SSL verification.  

For Chef 13, it appears that instead of having a wrapper cookbook to set `/opt/chef/embedded/etc/gemrc`, I could set `rubygems_url` in `client.rb`.  However in attempting to also set `ssl_ca_path` I still get SSL verification errors.  

I would have the expectation that setting `ssl_ca_path` in `client.rb` could be used for performing the gem install using the Chef gem resources with SSL verification errors.  

## Chef Version

12 & 13

## Platform Version

Mac OS X, CentOS, RHEL, Ubuntu, Debian & Fedora that I have tested.   

## Replication Case

1. Stand up a private RubyGems server that serves traffic over HTTPS and signed with a self-signed certificate.
2. Using the OS's native mechanism which is `ca-certificates` for RHEL, CentOS & Ubuntu, use it to install your sign signed certificate to your OS's certificate bundle.  If on RHEL & CentOS, you may also have to install `openssl-perl` and run `c_rehash` from the `/etc/ssl/certs` directory.  
3. If on Chef 12, use the https://github.com/chef-cookbooks/rubygems to configure Chef to use your private RubyGems server
4. If on Chef 13, set `rubygems_url` in `client.rb` to point to your RubyGems server.  
5. Execute a cookbook that attempts to install a gem against your private RubyGems server.  

## Client Output

`SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed`

**Comment by coderanger** [comment]
So unfortunately rubygems and bundler don't use the system trust root (which would be our omnibus setup in this case), they each have their TLS CA system. Compounding this is the fact that there is no CLI option to modify the CA paths, so you have to do it via a gemrc file. What you can do at least is set up a gemrc file somewhere and use the `GEMRC` environment variable to point at that file. This should definitely be improved, I'll see if I can work with the Rubygems folks on it.

**Comment by coderanger** [comment]
Also because they use OpenSSL, both should respect `$SSL_CA_FILE`, though exporting that inside Chef might do some funky stuff.

**Comment by pantocrator27** [comment]
Thanks @coderanger, I figured this to be the case based on behavior I have seen.  As stated it would be nice for all things that are bundled into Chef to at least use the same cert bundle and be configurable via `ssl_ca_path`.

**Comment by coderanger** [comment]
In an optimal world it would be hooked in to our `trusted_certs/` folder automatically, but that might take a while :)

**Comment by pantocrator27** [comment]
Just for completeness when I was digging around yesterday, I did submit https://github.com/chef-cookbooks/rubygems/issues/16.  It would be an alternate way to handle the issue.

**Comment by coderanger** [comment]
Closing this out as there is nothing specific we can do about it at this time.
