### ISSUE TITLE
remote_directory doesn't obey file specificity

### ISSUE THREAD

**Issue by shatil** [chef/chef#6136]
## Description
https://docs.chef.io/resource_remote_directory.html says:
> The remote_directory resource will obey file specificity.

This is not true, because `chef-client` also requires:
> The directory that is copied from the cookbook should be located under `COOKBOOK_NAME/files/default/REMOTE_DIRECTORY`.

Please fix Chef so it behaves like `cookbook_file` does, rather than requiring a hardcoded path that may not apply to every circumstance.

## Chef Version
chef_version=13.0.118

## Platform Version
platform=centos
platform_version=6.9
ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
program_name=chef-solo worker: ppid=16572;start=19:40:45;
executable=/opt/chef/bin/chef-solo

## Replication Case
Create a `files/monit.d` directory in your cookbook, then declare:

```ruby
remote_directory '/etc/monit.d' do
    files_group 'root'
    files_mode '0600'
    files_owner 'root'
    notifies :restart, 'service[monit]', :delayed
    recursive true
    source 'monit.d'
end
```

## Client Output

```
==> default: ================================================================================
==> default:
==> default: Error executing action `create` on resource 'remote_directory[/etc/monit.d]'
==> default:
==> default: ================================================================================
==> default:
==> default:
==> default:
==> default:
==> default: Chef::Exceptions::FileNotFound
==> default:
==> default: ------------------------------
==> default:
==> default: cookbook my_cookbook has no directory files/default/monit.d
```

**Comment by lamont-granquist** [comment]
pretty much a dup of #2837

**Comment by lamont-granquist** [comment]
closing as dup
