### ISSUE TITLE
Chef recepe create Windows_Task throw Error "SystemCallError: Invalid access to memory location. - CreateProcessW"

### ISSUE THREAD

**Issue by vanessazou** [chef/chef#6148]
## Description
We have chef running on 100 machines every 30mins and constantly see random instance failed on "SystemCallError: Invalid access to memory location. - CreateProcessW" error. Totally random no easy way to replicate this issue locally.

The recipe is to create a windows scheduled job:
windows_task 'Schedule_Job' do
action :create
task_name 'Schedule_Job'
command 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe C:\scripts\Schedule_Job.ps1'
frequency :hourly
end

Error:
windows_task[Schedule_Job] (server::Schedule_Job line 28) had an error: SystemCallError: Invalid access to memory location. - CreateProcessW

I have googled how to fix this issue. But the following links ended up in no solution.
https://github.com/chef/mixlib-shellout/issues/111
https://bugs.ruby-lang.org/issues/11515

Could anyone help me or give me some insight why this happens?

Thank you
Vanessa

## Chef Version
chef: 12.6.0

## Platform Version
Widows 10

## Replication Case
Could not replicate easily, the issue randomly happens. Might need 100 instances running chef every 30 mins to get the issue fired.

## Client Output
[2017-05-12T13:47:10-04:00] INFO: Processing windows_task[Schedule_Job] action create (server::Schedule_Job line 28)
[2017-05-12T13:47:10-04:00] INFO: Running queued delayed notifications before re-raising exception
[2017-05-12T13:47:10-04:00] ERROR: Running exception handlers
[2017-05-12T13:47:10-04:00] ERROR: Exception handlers complete
[2017-05-12T13:47:10-04:00] INFO: Sending resource update report (run-id: 704d2c67-36db-4222-a4d9-14d4ee33bcd8)
[2017-05-12T13:47:10-04:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
[2017-05-12T13:47:10-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-05-12T13:47:10-04:00] FATAL: SystemCallError: windows_task[Schedule_Job](server::Schedule_Job line 28) had an error: SystemCallError: Invalid access to memory location. - CreateProcessW
[2017-05-12T13:47:24-04:00] INFO: Child process exited (pid: 12572)

**Comment by tas50** [comment]
@vanessazou As a first step in troubleshooting can you try upgrading to a more recent chef-client release. 12.6 is quite old at this point.

**Comment by vanessazou** [comment]
I would like to. But before upgrading, we have to do lots of research and test to make sure our dev and prod environment comfortable with the new version. That's the main reason we still running on the 12.6 for stability.

So unless, this is upgrading is the only solution for this issue, I prefer to just get any suggestion and solution on this 12.6 version,.

And here is the chef-stacktrace.out.
#chef-stacktrace.out
Generated at 2017-05-12 13:47:10 -0400
SystemCallError: windows_task[Schedule_Job] (server::Schedule_Jobline 28) had an error: SystemCallError: Invalid access to memory location. - CreateProcessW
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.2.5-universal-mingw32/lib/mixlib/shellout/windows/core_ext.rb:347:in `create'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.2.5-universal-mingw32/lib/mixlib/shellout/windows.rb:80:in `run_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/mixlib-shellout-2.2.5-universal-mingw32/lib/mixlib/shellout.rb:259:in `run_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/mixin/shell_out.rb:97:in `shell_out_command'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/mixin/shell_out.rb:50:in `shell_out'
C:/chef/cache/cookbooks/windows/providers/task.rb:238:in `load_task_hash'
C:/chef/cache/cookbooks/windows/providers/task.rb:159:in `load_current_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/provider.rb:127:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/resource.rb:596:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/runner.rb:74:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/runner.rb:106:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/runner.rb:106:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/runner.rb:106:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/runner.rb:105:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/client.rb:658:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/client.rb:653:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/client.rb:653:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/client.rb:692:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/client.rb:271:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/application.rb:243:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/application.rb:220:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/application.rb:203:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/application/client.rb:386:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/lib/chef/application.rb:58:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.0.0/gems/chef-12.6.0-universal-mingw32/bin/chef-client:26:in `<top (required)>'
C:/opscode/chef/bin/chef-client:64:in `load'
C:/opscode/chef/bin/chef-client:64:in `<main>'

**Comment by lamont-granquist** [comment]
dup of #5415, needs to get replicated on ruby 2.4.x, we don't have the resources to dig into what looks like a ruby-on-windows-on-ruby-2.0.0 bug without a replication case showing that it is a current issue.
