### ISSUE TITLE
yum_package: doesn't detect package installation failure for files not ending in ".rpm"

### ISSUE THREAD

**Issue by eschro-illumio** [chef/chef#6150]
## Description

When `yum_package` is provided with local filename, it uses `localinstall`.
But, if that filename doesn't end in ".rpm", the `yum` command will ignore the file and return an exit code of `0`.

It seems like this is really a quirk of `yum` rather than `chef-client`, so maybe extra validation in the `yum` package provider is needed?

## Chef Version

chef-client 12.16.42

The `v12.16.42` tag must have rolled off, but it looks like that [`localinstall` sentry still exists](https://github.com/chef/chef/blob/ab621a6151c309f7b9787c8c7134453ae6e04e36/lib/chef/provider/package/yum.rb#L121)

## Platform Version

centos 6

## Replication Case

1. Save a file to the local filesystem. Make sure it doesn't end in `.rpm`
2. Try to install it

```
remote_file 'good-tree-rpm' do
  source 'http://mirrors.us.kernel.org/centos/6/os/x86_64/Packages/tree-1.5.3-3.el6.x86_64.rpm'
  path ::File.join(Chef::Config['file_cache_path'], 'tree.rpm')
end

package 'tree-gets-installed' do
  source ::File.join(Chef::Config['file_cache_path'], 'tree.rpm')
end

execute 'validate-tree-is-installed' do
  command 'rpm -qa |grep tree'
end

remote_file 'bad-epel-rpm' do # for the sake of a contrived example
  source 'http://mirrors.us.kernel.org/fedora-epel/6/x86_64/epel-release-6-8.noarch.rpm'
  path ::File.join(Chef::Config['file_cache_path'], 'foo')
end

package 'epel-release-wont-get-installed' do
  source ::File.join(Chef::Config['file_cache_path'], 'foo')
end

execute 'validate-epel-release-install' do
  command 'rpm -qa |grep epel-release'
end # this will fail
```

## Client Output

The `yum localinstall` reports things are A-OK, but here's a shell-equivalent to demonstrate what's happening behind the curtain:

```
[root@ip-172-29-1-211 chef]# sudo yum localinstall /tmp/kitchen/cache/ven
Loaded plugins: fastestmirror, presto
Setting up Local Package Process
Skipping: /tmp/kitchen/cache/ven, filename does not end in .rpm.
Nothing to do
[root@ip-172-29-1-211 chef]# echo $?
0
```

**Comment by coderanger** [comment]
Literally just hardcoded in to yum https://github.com/rpm-software-management/yum/blob/master/cli.py#L1391-L1394

Nice.

**Comment by hfinucane** [comment]
Why does chef use localinstall? install seems to at least return an rc of 1, and it works just fine with local files ...

**Comment by coderanger** [comment]
@hfinucane Just legacy historical crud, we used to support versions of yum where that wasn't the case. With EL5 being dead as of a few months ago, we can probably just change it.

**Comment by lamont-granquist** [comment]
this'll probably get addressed when i wipe out the existing yum provider and replace it with one patterned after the dnf provider.  leaving it open for tracking.

**Comment by lamont-granquist** [comment]
Neither `yum install` or `yum localinstal` work here, with slightly different behavior but both fail:

```
# yum -y localinstall /tmp/foo
Loaded plugins: fastestmirror
Skipping: /tmp/foo, filename does not end in .rpm.
Nothing to do
```

```
# yum -y install /tmp/foo
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.web-ster.com
 * extras: centos.s.uw.edu
 * updates: mirror.sfo12.us.leaseweb.net
```

if we don't have a yum command we can issue to do the work, this can't be fixed.

**Comment by hfinucane** [comment]
The ask was not to coerce yum into working, the ask was to not have it fail silently-
```
$ wget http://mirrors.us.kernel.org/fedora-epel/6/x86_64/epel-release-6-8.noarch.rpm -O epel
$ sudo yum localinstall ./epel ; echo $?
Loaded plugins: fastestmirror
Setting up Local Package Process
Skipping: ./epel, filename does not end in .rpm.
Nothing to do
0
$ sudo yum install ./epel ; echo $?
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.cisp.com
 * extras: mirrors.kernel.org
 * updates: mirror.teklinks.com
No package ./epel available.
Error: Nothing to do
1
$ sudo yum install ./epel.rpm -y # so `yum install` will work fine for local paths
Loaded plugins: fastestmirror
Setting up Install Process
Examining ./epel.rpm: epel-release-6-8.noarch
Marking ./epel.rpm to be installed
Loading mirror speeds from cached hostfile
 * base: mirror.cisp.com
 * extras: mirrors.kernel.org
 * updates: mirror.teklinks.com
Resolving Dependencies
--> Running transaction check
---> Package epel-release.noarch 0:6-8 will be installed
--> Finished Dependency Resolution
...
```
