### ISSUE TITLE
chef-client 13 should have plist gem 3.3.0

### ISSUE THREAD

**Issue by erikng** [chef/chef#6151]
## Description

In my testing of chef-client 13.0.118 I have noticed deprecation warnings.

These are fixed by replacing plist-3.2.0 with plist-3.3.0

## Chef Version

13.0.118

## Platform Version

macOS

## Replication Case

Attempt to install a dynamic launch daemon or dynamic profile.

## Client Output

```    * osx_profile[com..profile.chef.browsers.chrome] action install/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/plist-3.2.0/lib/plist/generator.rb:97: warning: constant ::Fixnum is deprecated
/opt/chef/embedded/lib/ruby/gems/2.4.0/gems/plist-3.2.0/lib/plist/generator.rb:162: warning: constant ::Fixnum is deprecated

      - install profile com..profile.chef.browsers.chrome```

**Comment by tas50** [comment]
We actually pulled in 3.3 2 days ago. It'll ship in the 13.1 release.

**Comment by erikng** [comment]
Sweet. Thanks tas.
