### ISSUE TITLE
Chef fails to run "execute" resource with command "nohup gulp serve &"

### ISSUE THREAD

**Issue by hitorchi** [chef/chef#6155]
## Description

It seems running the following resource fails to start up the gulp server on my target VM.

```
execute 'run_UI' do
    cwd node['hygieia']['ui']['home']
    user node['hygieia']['user']['name']
    group node['hygieia']['user']['group']
    command "nohup gulp serve &" 
    action :run
end
```

I am running the command `kitchen converge` to create a VM with a Hygieia server installed and running (a DevOps dashboard that depends on "gulp" for the UI) within my main machine. The code above is the lone resource in one of my recipes to start up the UI. I am also using test kitchen and berksfile.

**Link to Hygieia:**
[Hygieia's Github Page](https://github.com/capitalone/Hygieia)

I know this is the fault of Chef failing to run the command `nohup gulp serve &` properly because if I log into the VM and run the command myself, it works properly starting the gulp server, so the gulp project that comes from Hygieia and the gulp application installed from npm are alright. 

However, if I were to replace the command field above with say "gulp serve", then the gulp server will successfully run, but then Chef will hang permanently on my main machine unless I do CTRL-C as gulp runs constantly in the foreground of the VM instead of in the background as I wanted, so that isn't an ideal situation either as I don't wish to have to manually interfere.

## Chef Version

Chef Development Kit Version 1.2.22 
**[Note: I have updated to Version 1.3.43 to try to fix the issue, but the result is the same]**

## Platform Version

Ubuntu 14.04 for the VM, Mac OSX 10.11.6 for the main machine

## Replication Case

1. Configure test kitchen as well as berksfile and write recipes to install Hygieia's dependencies and install Hygieia itself, as well as recipes to run Hygieia's API collectors, API layer and UI layer. 

2. Run `kitchen converge` on my main machine to create the VM 

3. Installing dependencies, installing Hygieia, running the API collectors, running the API layer all succeed but the UI layer fails to run due to `nohup gulp serve &` failing to run

## Client Output

The output seems normal, even though gulp can't be found in my processes when running `ps -aux | grep gulp`.

```
-----> Converging <default-ubuntu-1404>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 5.6.0...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-ubuntu-1404>
       Starting Chef Client, version 13.0.118
       resolving cookbooks for run list: ["kobo-hygieia::collectors"]
       Synchronizing Cookbooks:
         - kobo-hygieia (0.1.3)
         - git (6.0.0)
         - mongodb3 (5.3.0)
         - build-essential (8.0.2)
         - dmg (4.0.0)
         - yum-epel (2.1.1)
         - java (1.49.0)
         - nodejs (3.0.0)
         - yum (5.0.1)
         - windows (3.0.5)
         - runit (1.7.8)
         - mingw (2.0.1)
         - user (0.7.0)
         - seven_zip (2.0.2)
         - ark (3.1.0)
         - ohai (5.1.0)
         - maven (5.0.0)
         - homebrew (4.1.0)
         - apt (6.1.0)
         - compat_resource (12.19.0)
         - packagecloud (0.3.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       /tmp/kitchen/cache/cookbooks/packagecloud/resources/repo.rb:10: warning: constant ::Fixnum is deprecated
       Converging 1 resources
       Recipe: kobo-hygieia::collectors
         * execute[run_UI] action run
           - execute nohup gulp serve & 
       Running handlers:
       Running handlers complete
       Chef Client finished, 1/1 resources updated in 01 seconds
       Finished converging <default-ubuntu-1404> (0m4.64s).
```

**Comment by lamont-granquist** [comment]
does using a bash resource instead of an execute resource fix this?

**Comment by hitorchi** [comment]
@lamont-granquist Unfortunately, it seems to give the same reason where gulp still fails to run on my VM.

**Comment by hitorchi** [comment]
One solution is to wrap gulp in another command, specifically "forever" from npm.

I'll close this issue and include a link to the stackoverflow link:
[Using Forever](http://stackoverflow.com/questions/28543171/run-gulp-script-with-forever)
