### ISSUE TITLE
delete_resource broken for "package" resources

### ISSUE THREAD

**Issue by GUI** [chef/chef#6158]
## Description

Calling `delete_resource!` on `package` resources results in `Chef::Exceptions::ResourceNotFound` errors. This seems to be due to the resource having 2 different names inside chef. For example, under OpenSuse, the resource is named "package" in one context, but shows up as "zypper_package" in other contexts. Under CentOS its "package" or "yum_package". This may also impact other operating systems where the `package` resource maps to a more specific implementations.

## Chef Version

Tested against 12.20.3 and 13.0.118

## Platform Version

OpenSuse Leap 42.2 and CentOS 7.3

## Replication Case

Here's a Vagrantfile that demonstrates the issue with a simple recipe that defines a package and then calls `delete_resource!` on that package. This example uses Chef 12.20.3 and OpenSuse Leap 42.2, but the same thing happens with Chef 13 or under CentOS.
 
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "bento/opensuse-leap-42.2"
  config.vm.provision :chef_apply do |chef|
    chef.version = "12.20.3"

    chef.recipe = <<-RECIPE
      package "bzip2"
      delete_resource!(:package, "bzip2")
    RECIPE
  end
end
```

## Client Output

```
[2017-05-16T03:51:30+00:00] INFO: Run List is []
[2017-05-16T03:51:30+00:00] INFO: Run List expands to []
[2017-05-16T03:51:30+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2017-05-16T03:51:30+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-05-16T03:51:30+00:00] FATAL: Chef::Exceptions::ResourceNotFound: Cannot find a resource matching package[bzip2] (did you define it first?)
```

## Stacktrace

```
Chef::Exceptions::ResourceNotFound: Cannot find a resource matching package[bzip2] (did you define it first?)
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/resource_collection/resource_list.rb:75:in `delete'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/resource_collection.rb:63:in `delete'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/dsl/declare_resource.rb:74:in `delete_resource!'
/tmp/vagrant-chef-apply/recipe-5879a54cb012f9ddeb72911bfefb7efd.rb:2:in `run_chef_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/apply.rb:192:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/apply.rb:192:in `run_chef_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/apply.rb:204:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/apply.rb:216:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/bin/chef-apply:25:in `<top (required)>'
/bin/chef-apply:57:in `load'
/bin/chef-apply:57:in `<main>'
```

If you change the `delete_resource!(:package, "bzip2")` line to `delete_resource!(:zypper_package, "bzip2")`, then it gets slightly further (line 64 of [ResourceCollection#delete](https://github.com/chef/chef/blob/v12.20.3/lib/chef/resource_collection.rb#L62-L65) instead of line 63), but still fails:

```
Chef::Exceptions::ResourceNotFound: Cannot find a resource matching zypper_package[bzip2] (did you define it first?)
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/resource_collection/resource_set.rb:67:in `delete'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/resource_collection.rb:64:in `delete'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/dsl/declare_resource.rb:74:in `delete_resource!'
/tmp/vagrant-chef-apply/recipe-248e26f76440794751686af30019a620.rb:2:in `run_chef_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/apply.rb:192:in `instance_eval'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/apply.rb:192:in `run_chef_recipe'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/apply.rb:204:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/apply.rb:216:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/bin/chef-apply:25:in `<top (required)>'
/usr/bin/chef-apply:57:in `load'
/usr/bin/chef-apply:57:in `<main>'
```

So the issue seems to be that in the `ResourceList` collection, the package is only known by the name `zypper_package[bzip2]`, but in the `ResourceSet` collection, the package is only known by the name `package[bzip2]`. But the delete operation expects for the resource to exist under both collections with the same name, which is why this fails.

You can sort of see what's happening behind the scenes with this workaround of replacing the `delete_resource!` call with 2 explicit delete calls using the different names (which seems to work, but obviously isn't ideal):

```
run_context.resource_collection.send(:resource_list).delete("zypper_package[bzip2]")
run_context.resource_collection.send(:resource_set).delete("package[bzip2]")
```

**Comment by GUI** [comment]
One additional note is that `find_resource!` and `edit_resource!` seem to work as expected with `package` resources, so this issue seems isolated to `delete_resource!`.

If anyone else is running into this, another potential workaround is to use `edit_resource!` to set the resource action to "nothing". While not entirely the same as removing the resource, it might serve as a workaround, depending on your needs:

```
edit_resource!(:package, "bzip2") do
  action :nothing
end
```

**Comment by lamont-granquist** [comment]
that's more of a resource collection bug than an delete_resource bug

**Comment by taharah** [comment]
I just ran into this same issue with the user resource.

**Comment by artem-sidorenko** [comment]
following patch fixes that for me:
```diff
diff --git a/lib/chef/resource_collection.rb b/lib/chef/resource_collection.rb
index e450f4f19..df0e6ddff 100644
--- a/lib/chef/resource_collection.rb
+++ b/lib/chef/resource_collection.rb
@@ -60,8 +60,9 @@ class Chef
     end
 
     def delete(key)
-      resource_list.delete(key)
-      resource_set.delete(key)
+      res = resource_set.delete(key)
+      resource_list.delete(res.to_s)
+      res
     end
 
     # @deprecated
```

@tas50 @lamont-granquist I would be happy to provide a PR with a fix if you can tell me if this direction is right

**Comment by artem-sidorenko** [comment]
if somebody is interested on the workaround, you can monkeypatch that method, create `libraries/delete_resource_patch.rb` in your cookbook with following content:

```ruby
class Chef
  class ResourceCollection
    def delete(key)
      res = resource_set.delete(key)
      resource_list.delete(res.to_s)
      res
    end
  end
end
```

**Comment by lamont-granquist** [comment]
PR: yes, please.  I keep forgetting this bug is a thing.

**Comment by artem-sidorenko** [comment]
@lamont-granquist here you are: https://github.com/chef/chef/pull/8570
