### ISSUE TITLE
Chef 'execute' resource does not honor supplementary groups during execution of command.

### ISSUE THREAD

**Issue by brent-at-gm** [chef/chef#6162]
## Description

The execute resource does not seem to honor supplementary groups during execution of the command.  This causes permission issues when executing a command as a user that should have the appropriate privileges through the supplementary group. This same behavior has been recorded as an issue in 2014 "https://github.com/chef/chef/issues/2342".

## Chef Version

chef-client --version
Chef: 12.17.44

## Platform Version

Oracle Linux Server release 7.2

## Replication Case

```
group 'group1' do
  gid 20000
end

user 'user1' do
  comment 'user1 comment'
  uid 20000
  gid 20000
  home '/home/user1'
  shell '/bin/bash'
end

group 'group2' do
  gid 20001
end

user 'user2' do
  comment 'user2 comment'
  uid 20001
  gid 20001
  home '/home/user2'
  shell '/bin/bash'
end

group 'group1' do
  members 'user2'
  append true
  action :modify
end

directory '/var/tmp/testdir' do
  owner 'user1'
  group 'group1'
  mode '0770'
  recursive true
  action :create
end

execute 'touch a file in directory' do
  command 'touch /var/tmp/testdir/testfile'
  user 'user2'
  group 'group2'
end
```

## Client Output

STDERR: touch: cannot touch ‘/var/tmp/testdir/testfile’: Permission denied
       ---- End output of touch /var/tmp/testdir/testfile ----
       Ran touch /var/tmp/testdir/testfile returned 1

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

## Shell Output

[user2@host1 ~]$ touch /var/tmp/testdir/testfile

Executes with no issue outside of chef-client locally in the shell.

**Comment by jeunito** [comment]
@brent-at-gm This boils down to mixlib which is a separate library (but still a chef library) and uses [Process under the hood](https://github.com/chef/mixlib-shellout/blob/master/lib/mixlib/shellout/unix.rb#L338). My guess is that it doesn't let you do this but I haven't verified this myself.

**Comment by jeunito** [comment]
@brent-at-gm I have verified that it is indeed like that: 
```ruby
2.4.0 :016 > c = Mixlib::ShellOut.new("touch /test", {:user => "user2", :group => "user2"})
 => <Mixlib::ShellOut#18517320: command: 'touch /test' process_status: nil stdout: '' stderr: '' child_pid: nil environment: {} timeout: 600 user: user2 group: user2 working_dir:  >
2.4.0 :018 > c.run_command
 => <Mixlib::ShellOut#18517320: command: 'touch /test' process_status: #<Process::Status: pid 14358 exit 1> stdout: '' stderr: 'touch: cannot touch '/test': Permission denied' child_pid: 14358 environment: {} timeout: 600 user: user2 group: user2 working_dir:  >
```

**Comment by brodygov** [comment]
Another workaround that may be useful:

You can use the `sg` command (like `su`, but for group IDs) to switch to the secondary group id.

```
command 'sg group1 -c "touch /var/tmp/testdir/testfile"'
```

This also changes the primary group, which may be undesirable. Running `id` without `sg`:

```
uid=20001(user2) gid=20001(group2) groups=20001(group2)
```

And with `sg group1 ...`:

```
uid=20001(user2) gid=20000(group1) groups=20000(group1),20001(group2)
```

**Comment by lamont-granquist** [comment]
This is probably a dup of #7690 where the execute resource needs to use the mixlib-shellout login flag.

**Comment by lamont-granquist** [comment]
calling this one a dup of #3563 and #4338
