### ISSUE TITLE
Chef Client 13.1.31 - Custom Resource - Required Property skipping validation and returning empty hash and nil error on template

### ISSUE THREAD

**Issue by rshade** [chef/chef#6190]
## Description
haproxy cookbook has a custom resource, it has a required property for default_backend, if you do not set it, you do not get required property missing error. It just creates an empty hash. "frontend"=>{"http-in"=>{"default_backend"=>""}}}

Chef::Mixin::Template::TemplateError
             ------------------------------------
             undefined method `each' for nil:NilClass

       Template Context:
             -----------------
             on line #92
       90:   default_backend <%= f['default_backend'] %>
       91: <% end -%>
       92: <% f['bind'].each do |binding| -%>
       93:   bind <%= binding %>
       94: <% end -%>
       System Info:
             ------------
             chef_version=13.1.31
             platform=centos
             platform_version=7.3.1611
             ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
             program_name=chef-client worker: ppid=5366;start=17:44:44;
             executable=/opt/chef/bin/chef-client

## Chef Version
13.1.31

## Platform Version

CentOS 7.3

## Replication Case
you can use the haproxy cookbook here: https://github.com/sous-chefs/haproxy/pull/226/files
and run: 
`chef exec kitchen converge config-ssl-redirect`

## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* Requests for new or alternative functionality should be made to [feedback.chef.io](https://feedback.chef.io/forums/301644-chef-product-feedback/category/110832-chef-client)
* [Chef Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by rshade** [comment]
chef_version=13.0.118

**Comment by rshade** [comment]
I tested 12.19. and 12.16.42 and same result

**Comment by coderanger** [comment]
You've got a variable name collision on `new_resource`, I don't understand why that code is working at all. It should explode with a methodmissing.

**Comment by coderanger** [comment]
Workshop'd this a bit in Slack, the behavior on the Chef side is correct. The required prop error is getting raised (I think) but because we run delayed notifications on the way out during a failure, and because this resource is leaving partial data in the accumulator during an exception, it gets sad. The solution is to not leave partial data in the accumulator during an exception.

**Comment by lamont-granquist** [comment]
dup of #4596 ?

**Comment by lamont-granquist** [comment]
oh i see, its not.  

so probably a dup of the other issue surrounding aborting a delayed notification when things blow up, instead of always running them (IDK where that bug is offhand)

**Comment by coderanger** [comment]
The bug is in the cookbook code, going to close this out as correct, if undesirable, behavior. This really shows how hard it is to write good accumulator patterns.
