### ISSUE TITLE
`windows_task` should have a frequency option of `none`

### ISSUE THREAD

**Issue by joshoohaah** [chef/chef#6200]
## Description

Currently you have to specify a frequency for a scheduled task.  There are occasionally a need to have a scheduled task with 'no frequency'.  ( I know...I sound like a crazy person with this request).
But i have come across this need a few times where i need this type of functionality...and the chef run just needed to call `run` on the scheduled task.  But i could not use `windows_task` to create the task.

## Chef Version
13

## Platform Version
Windows 2012 R2

**Comment by NAshwini** [comment]
-- To create task we have only two option one by GUI and another is through 'schtasks' command & for creation of task we use 'schtasks' command.
-- But '***schtasks /CREATE***' command does not give any option for '***:none***' or ***"" (blank value)*** or ***no value*** under ***'/SC'*** option. it just gives below values
 ( _schedule => Specifies the schedule frequency._
    _Valid schedule types: MINUTE, HOURLY, DAILY, WEEKLY,_
    _MONTHLY, ONCE, ONSTART, ONLOGON, ONIDLE, ONEVENT_ )
-- Hence we cannot add ':none' option to frequency in 'windows_task' resource.
-- We can use an workaround i.e Create the task and set frequency ':once' & set starttime as a past time. The task will exist and you can run it at will. I tried it below example and it worked.
example: `if current time is 3.55 PM then we can set past time as 03:50`
```
windows_task 'test task_none' do
  command "echo test"
  cwd "c:/windows"
  start_time "03:50"
  frequency :once
  execution_time_limit "100"
end
```

got some reference:
https://serverfault.com/questions/568055/schtasks-create-task-with-no-schedule-that-runs-on-demand

**Comment by joshoohaah** [comment]
@NAshwini, you can create a scheduled task with no trigger by using schtasks to import a scheduled task template and set its triggers to being empty.
I have done this before using chef...just not being able to use the `windows_task` resource.  Here is an example below.

here is a snippet of a ruby recipe that deploys a scheduled task with no trigger:
https://gist.github.com/joshoohaah/4c2cdd936312d36f87263948ee5f7773

Here is the scheduled task template file with triggers off:
https://gist.github.com/joshoohaah/bcfb563d02462e98a0d94e4510cb235a

The key there is `<Triggers />` in the xml template for the scheduled task

**Comment by NAshwini** [comment]
Thank you @joshoohaah, Thats interesting..
will look into it & get back to you.
