### ISSUE TITLE
No documentation for coerce method in custom resources

### ISSUE THREAD

**Issue by Poohblah** [chef/chef#6212]
Custom resources support the `coerce` method, which to my best understanding is mainly used to convert properties of resources from one type to another at resource declaration time. [Here is one example of its use in the wild.](https://github.com/chef-cookbooks/docker/blob/master/libraries/docker_container.rb#L91).  However, [the custom resources documentation](https://docs.chef.io/custom_resources.html) does not mention the `coerce` method at all.

**Comment by coderanger** [comment]
Already tracked at https://github.com/chef/chef-web-docs/issues/717
