### ISSUE TITLE
Windows_Package should handle trailing spaces in package names

### ISSUE THREAD

**Issue by rlaveycal** [chef/chef#6217]
## Description

PostgreSQL 9.6.3.1 on Windows installs itself with a DisplayName of "PostgreSQL 9.6 " (note the trailing space). If the package resource has the name "PostgreSQL 9.6" then the two don't match and Chef will re-install the package on every run.

It would be nice if https://github.com/chef/chef/blob/master/lib/chef/provider/package/windows/registry_uninstall_entry.rb#L43 stripped spaces before doing the comparison

## Chef Version

12.13.37

## Platform Version

Windows 2012R2

## Replication Case

Create a recipe with this resource (and download the PostgreSQL 9.6.3 installer)
```
package 'PostgreSQL 9.6' do
  source "postgresql-9.6.3-1-windows-x64.exe"
  installer_type :custom
  options '--mode unattended '\
          '--unattendedmodeui none '\
          "--servicename Postgres "\
          "--datadir d:\\PGSqlData "\
          "--superpassword password "
  action :install
end
```

**Comment by lamont-granquist** [comment]
fastest way to get this fixed would be to just submit a PR since you tracked down the line in the source

**Comment by sriyanfernando** [comment]
i would like to work on that issue.

**Comment by perlun** [comment]
@lamont-granquist @rlaveycal There we go, #6280 fixes this.
