### ISSUE TITLE
http_request does not support the :patch action

### ISSUE THREAD

**Issue by atsansone** [chef/chef#6235]
## Description

If you want to create an HTTP request using the `:patch` action, it is not currently possible. See [http_request documentation](https://docs.chef.io/resource_http_request.html).

## Chef Version

All versions after which `http_request` was implemented. 

## Platform Version

This occurs on any platform, any version.

## Replication Case

Try to create an `http_request` to a REST API that uses the `:patch` action. The option is unavailable.

## Client Output

There is no output because you cannot use the `:patch` action.

    http_request 'posting data' do
      action :patch
      url 'http://example.com/check_in'
      message ({:some => 'data'}.to_json)
      headers({'AUTHORIZATION' => "Basic #{
        Base64.encode64('username:password')}",
        'Content-Type' => 'application/data'
      })
    end

**Comment by lamont-granquist** [comment]
dup of #6131 which we just need to get time to merge
