### ISSUE TITLE
Link resource doesn't work with action :delete when "to" is missing and target is a file.

### ISSUE THREAD

**Issue by timurb** [chef/chef#6238]
## Description

When I use `link` resource with `:delete` action and don't specify `to` parameter
and a target file for some reason is plain file and not a link and not absent
chef run crashes with inconcise error.

If a target file is a link or absent Chef run passes fine.
If a target file is a file and I specify `to` parameter Chef produces error which is easy to understand and that's ok. I'd expect this edge case to produce the same error.

## Chef Version

I was able to reproduce it for all Chef 11,12 and 13 (last stable for 13).

## Platform Version

Ubuntu 12.04

## Replication Case

```
link '/foo' do
  action :delete
end
```

Save the above recipe to `link.rb` and run:
```
touch /foo
chef-apply link.rb
```

The same error was seen for chef-client run.

## Client Output

The run producer exception of `no implicit conversion of nil into String`
Full stack trace https://gist.github.com/timurb/bb402d54e9f1d5577bb44ce12901e04a

**Comment by jaymzh** [comment]
Came here to report the same thing. :)
