### ISSUE TITLE
undefined method `map' for #<String:0x00000003dce0a8>

### ISSUE THREAD

**Issue by siddhu07** [chef/chef#6254]
## Description

while doing
knife cookbook upload <name>, it give 

ERROR: knife encountered an unexpected error
This may be a bug in the 'cookbook upload' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `map' for #<String:0x00000003dce0a8>

## Chef Version
Chef Development Kit Version: 1.5.0

## Platform Version
RHEL 8

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

## Stacktrace

INFO: Using configuration from /home/ec2-user/.chef/knife.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as ec2-user
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::APIVersions#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-Ops-Server-API-Version: 1
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.1;
DEBUG: X-OPS-USERID: ec2-user
DEBUG: X-OPS-TIMESTAMP: 2017-07-05T05:03:41Z
DEBUG: X-OPS-CONTENT-HASH: 2jmj7l5rSw0yVb/vlWAYkK/YBwk=
DEBUG: X-OPS-AUTHORIZATION-1: YOu37qxhzd2TBttO69PSeU+NPaGHaDP8XAjSst+VXC9latk7p4hDg6W9GLSc
DEBUG: X-OPS-AUTHORIZATION-2: ZPWfc0uhSIbU+Sv5MAWb9DIoYBzACHQkqgB4ZbPQXjUZ0ZSfQUZLVA6973Z5
DEBUG: X-OPS-AUTHORIZATION-3: 0xYbAoHtdyzoxjAI0VJAshR/WyeB6iYjYse9jA9bUKgGkkUEydouk1t4QybI
DEBUG: X-OPS-AUTHORIZATION-4: 7EAHzDmeZbXyZOQCRBLO7sh+iJJPp/ejzdjUfN+sV1Vpkz8nRqn96i1GN0UH
DEBUG: X-OPS-AUTHORIZATION-5: anIISl/1oXr53jLzsEPsiCChXUVa/vcn1oIjyjE3J/Fx61z/YCXLBi/tIOeD
DEBUG: X-OPS-AUTHORIZATION-6: FFSB12FkkZAFOABhMw3Y5Yq9ilakLlqmuhCPKVRB7w==
DEBUG: HOST: sid-cassandra-chef-nalljf7vhf0a5j1q.us-east-1.opsworks-cm.io:443
DEBUG: X-REMOTE-REQUEST-ID: 8a80e9ed-ee2c-45ea-8515-19e81e76e69d
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: server: openresty
DEBUG: date: Wed, 05 Jul 2017 05:03:41 GMT
DEBUG: content-type: text/html
DEBUG: last-modified: Tue, 16 May 2017 01:35:16 GMT
DEBUG: transfer-encoding: chunked
DEBUG: connection: close
DEBUG: etag: W/"591a5754-303"
DEBUG: content-encoding: gzip
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: HTTP server did not include a Content-Length header in response, cannot identify truncated downloads.
DEBUG: Chef::HTTP calling Chef::HTTP::APIVersions#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Expected JSON response, but got content-type 'text/html'
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/knife/cookbook_upload.rb:104:in `run': undefined method `map' for #<String:0x000000031c6ee0> (NoMethodError)
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/knife.rb:442:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/knife.rb:219:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/lib/chef/application/knife.rb:156:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.2/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/bin/knife:57:in `load'
	from /opt/chefdk/bin/knife:57:in `<main>'

**Comment by lamont-granquist** [comment]
```
  # Get a list of cookbooks and their versions from the server
        # to check for the existence of a cookbook's dependencies.
        @server_side_cookbooks = Chef::CookbookVersion.list_all_versions
        justify_width = @server_side_cookbooks.map { |name| name.size }.max.to_i + 2
```

```
    def self.list_all_versions
      chef_server_rest.get("cookbooks?num_versions=all")
    end
```

that looks like the server responded with a 200 and some text, rather than json, and the text was returned as a string.

**Comment by cheeseplus** [comment]
Closing due to lack of response and the fact this is most likely a chef-server configuration problem.
