### ISSUE TITLE
Deprecation warning may result in printing sensitive information to the log.

### ISSUE THREAD

**Issue by acranox** [chef/chef#6263]
## Description

A chef-client 13 deprecation warning results in printing sensitive information to the log.
Using the file resource, w/ 'sensitive true' will prevent the file content from being printed to the log, but a deprecation warning may print the file content at the end of the chef-client run.

## Chef Version

12.19.36

## Platform Version

RHEL 7

## Replication Case

inside loop, with some values are expected to be empty, I'm using the file resource, where the content is an attribute that was defined earlier:
```
node['foobar'].each do |key, value|
  file "/path/#{value['filename']} do
    content node['secret_key'][key]
    sensitive true
  end
end
```

## Client Output

```
  An attempt was made to change content from "REDACTED SECRET KEY" to nil by calling content(nil). In Chef 12, this does a get rather than a set. In Chef 13, this will change to set the value to nil. at 1 location:
    - /var/chef/cache/cookbooks/foobar/recipes/test.rb:75:in `block (2 levels) in from_file'
   See https://docs.chef.io/deprecations_custom_resource_cleanups.html for further details.
```

## Stacktrace

N/A

**Comment by tas50** [comment]
Closing this at this point since we've removed this deprecation code.
