### ISSUE TITLE
`cron` resources should support setting timezone

### ISSUE THREAD

**Issue by GuyPaddock** [chef/chef#6269]
## Description
We have a nightly job we want to run every night at 2 AM Eastern time. Unfortunately, the default time zone for cron is UTC unless otherwise defined in the file.

Chef `cron` resources do not support providing the time zone to use, so this means that every time we go into or out of Daylight Saving Time, we have to modify the resource and re-deploy to our servers to ensure it stays at 2 AM instead of moving to 1 AM or 3 AM.
 
## Chef Version
Chef 11

## Platform Version
Amazon OpsWorks with chef-zero

## Replication Case
Not applicable -- this is a feature request

## Client Output
Not applicable -- this is a feature request

## Stacktrace
Not applicable -- this is a feature request

**Comment by coderanger** [comment]
Are there any cron daemon implementations that support this?

**Comment by coderanger** [comment]
A quick survey of cron daemons says "no", so this isn't something we would support. I recommend implementing it in your recipe code using the Ruby `Time` class and `tzinfo` gem to do the timezone math for you.

**Comment by coderanger** [comment]
I had thought that cron daemons on most distros don't support this (Ubuntu 16.10 specifically says it doesn't) but then https://linux.die.net/man/5/crontab makes it sound like maybe some do? Do you know which platforms actually support this feature?

**Comment by GuyPaddock** [comment]
Hmm, you may be correct. I was under the impression that this was more widespread.

I did stumble across this, which indicates that Cron only supports once timezone once defined:
https://serverfault.com/questions/848829/how-to-use-timezone-with-cron-tab

**Comment by GuyPaddock** [comment]
This, though, seems to indicate that is not the case:
https://serverfault.com/questions/374284/crontab-schedule-in-different-timezones

**Comment by coderanger** [comment]
It looks like was a feature in vixiecron, but I don't think many distros are still using that. Probably the safest bet is to use the `tzdata` gem and do the math in your recipe code.

**Comment by GuyPaddock** [comment]
@coderanger we thought about doing that, but then it would only take effect if we redeploy after a timezone DST switch.

**Comment by GuyPaddock** [comment]
Also looks like we aren't the first to request this feature -- the original request was against Chef 10: https://tickets.opscode.com/browse/CHEF-3614

Granted, judging from the issue queue, seems like it's a rare request.

**Comment by GuyPaddock** [comment]
I suppose another approach is to use resources to write out the `crontab` instead of using native `cron` resources.

**Comment by coderanger** [comment]
Yeah, a `template` resource and `/etc/cron.d` might work better (assuming your cron daemon supports this at all).

**Comment by lamont-granquist** [comment]
the `cron` resource is somewhat discouraged.  if you're on a recent enough crond to support TZ files you should have an /etc/cron.d directory and you really should drop files/templates there.  i think there's even a cron_d resource in some cookbook, but fundamentally it's just managing /etc/cron.d templates and most of these approaches just overly complicated the problem in the name of creating an abstraction layer that has bugs and needs maintenance.  just managing crons with a template makes more sense.

**Comment by lamont-granquist** [comment]
so that's not a 'no' that's a 'PRs accepted', but we're unlikely to ever do the work to patch support into it.
