### ISSUE TITLE
JSON Environment Files Allow Periods in Names

### ISSUE THREAD

**Issue by geoffbeal** [chef/chef#6276]
## Description

First, I'm new to Chef and have about 2hours experience with the Chef Server.  So maybe I'm at fault here, but I think I've stumbled on a validation bug.

what I did:

1.  I created a Number of Environment JSON files.  Each Environment is based on a DNS Zone and contained Periods.  I named the files similar to:

environments/dev.ca1.domain.com.json

Here is a snippit from the JSON file sanitized a bit:

--------
{
    "name": "dev.ca1.domain.com",
    "description": "dev.ca1.domain.com environment",
    "chef_type": "environment",
    "json_class": "Chef::Environment",
    "default_attributes": {    },
    "override_attributes": {   },
    "cookbook_versions": { },
}
-------

2.  I used "knife upload environments" to upload this and several other environments to the chef server.

3.  I started running into weird behavior where the Chef Server GUI wouldn't display environments, but "knife environment list" would.

4.  I attempted to delete the role(s) and was given the error message:
ERROR: Chef::Exceptions::ValidationFailed: Option name's value dev.ca1.domain.com does not match regular expression /^[\-[:alnum:]_]+$/

After reading the Documentation closer, and seeing the  RegEX error, I guess Periods are not allowed in names.

It's my fault for not reading the documentation closer, but I also think the bug is that the JSON files data should have been validated before allowing it to upload.  If not a Bug then I'd like to make a Feature Request :)

## Chef Version

Tell us which version of chef-client you are using (see below for Server+ChefDK bugs).

Server Side:
[00:10:56 root@chef001 etc]$ rpm -qa | grep chef
chef-manage-2.5.3-1.el7.x86_64
chef-server-core-12.15.6-1.el7.x86_64

Client Side:
gbeal@gbeal-wsm01:~/src/chef-repo/environments$ knife --version
Chef: 12.19.36

## Platform Version

Tell us which Operating System distribution and version chef-client is running on.

Server Side
[00:11:05 root@chef001 etc]$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 

Client Side:
MacOS Sierra 10.12.5 (16F73)

## Replication Case

1. Create JSON Environment Files with Periods in the File Name, and "Name" parameter in the config.

2. cd to your chef-repo home.

3.  Run "knife upload environments"

My output:
------
gbeal@gbeal-wsm01:~/src/chef-repo$ knife upload environments
Created environments/qa2.ca3.domain.com
Created environments/perfeng.ca1.domain.com
Created environments/qa1.ca3.domain.com
......
[Several Environments]
gbeal@gbeal-wsm01:~/src/chef-repo$ knife environment list
_default
dev.ca1.domain.com
dev.ca3.domain.com
perfeng.ca1.domain.com
......
[again, several environments]
gbeal@gbeal-wsm01:~/src/chef-repo$ knife environment delete dev.ca1.domain.com
Do you really want to delete dev.ca1.domain.com? (Y/N) Y
ERROR: Chef::Exceptions::ValidationFailed: Option name's value dev.ca1.domain.com does not match regular expression /^[\-[:alnum:]_]+$/
-------

I tried several variations of trying to escape the periods, etc with the same result.

Hopefully this is sufficient to recreate what I did.  Fortunately for me this is a new install and I can trash the data and start over.  

## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* Requests for new or alternative functionality should be made to [feedback.chef.io](https://feedback.chef.io/forums/301644-chef-product-feedback/category/110832-chef-client)
* [Chef Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by coderanger** [comment]
Sounds like it's probably a mismatch between the ChefFS and non-ChefFS code. @thommay thoughts?

**Comment by thommay** [comment]
Almost certainly, unfortunately.

**Comment by geoffbeal** [comment]
I've since cleansed and re-created the environments without the periods, so this isn't blocking or anything.  I just figured I'd create a bug report to, hopefully, eventually get resolved and prevent someone else doing what I did.

If there is something I can do to help test let me know, but it sounds like you guys have a good idea what's going on.  

And sorry about the formatting of my various outputs.  No idea why it's bold/strikeout in places.

**Comment by Tech356** [comment]
This problem still exists on `chef-server-core-12.17.33`. I encountered it with roles.

**Comment by ClaesGIS** [comment]
We have encountered this problem as well. Would it be possible modify or delete the environments without triggering the error?

**Comment by ClaesGIS** [comment]
Use this at your own discretion. I take no responsibility for anything that happens to your environment. I recommend running backup before attempting this.
`chef-server-ctl backup`

**How I resolved my problem**
1. Log onto the chefserver
2. Change user to opscode-pgsql 
`su - opscode-pgsql`
3. Access the database
`psql -d opscode_chef`
4. List the current environements
`select name from environments;`
5. Take the result from the query above and delete those entries
`delete from environments where name in ('something.with.dots.in.it01','something.with.dots.in.it02');`
6. You might need to restart chef server. I didn't have to.
`chef-server-ctl restart`
