### ISSUE TITLE
gpg/keyserver and apt_repository

### ISSUE THREAD

**Issue by rmoriz** [chef/chef#6294]
## Problem ##

`apt_repository` supports different ways to provide a gpg key/key id for a repository. A common way is to provide the key id and a public key server to fetch the key.

However it turns out that many public key servers and even key server pools like `sks-keyservers.net` are not very reliable, rate limited or sometimes unreachable. This usually breaks a chef-run and causes a lot of "false" positives in monitoring.

I might be wrong but it also looks to me that it's currently not idempotent, e.g. it fetches the key on each converge, at least on chef 12. 

## Suggestion for fix ## 

I suggest to implement the following:

1. implement a default retry option for key fetching which is unrelated to the `retries`. (Most public cookbooks don't use `retries`)

2. allow to specify an array of key-servers that will be iterated on error.

3. Backport https://github.com/chef/chef/commit/c90401fa936353550b7658a2a9f4908cf6d27a40 to chef12 client (fixes idempotency)

### Related / Real world example of the issue ###

https://github.com/chef-cookbooks/chef-apt-docker/pull/5

**Comment by coderanger** [comment]
We use `apt-key` to do the actual install so not sure how far down the rabbit hole we want to go vs. declaring this an upstream issue :-/ `retries` should work already as that's a core feature of all Chef resources so you might want to solve it using that and wrappers or `edit_resource`.

If it isn't idempotent we should definitely fix that though, https://github.com/chef/chef/blob/master/lib/chef/provider/apt_repository.rb#L200-L203 is the relevant code.

**Comment by rmoriz** [comment]
So maybe the broken idempotency caused the increase in timeouts due to rate-limiting?

**Comment by rmoriz** [comment]
Can we get a backport of c90401f to chef12?

**Comment by e100** [comment]
A backport would be nice, we still have some cookbooks that need updated before moving to Chef 13.

**Comment by cheeseplus** [comment]
Chef 12 is maintenance only at this point and releases are cut (almost*) exclusively for security fixes so a backport is very unlikely to happen.

**Comment by majormoses** [comment]
In chef 12 I it comes from the cookbook so it would need to be done there.

**Comment by rmoriz** [comment]
@majormoses Chef 12.9 included `apt_repository` which before was provided by the `apt` cookbook.

**Comment by rmoriz** [comment]
I'm closing this issues as Chef 14 is released and everyone should at least have upgraded to chef 13 in the meantime. (If you don't have, ask me for consultancy services ;)
