### ISSUE TITLE
DeepMerge ends up creating attribute values when it shouldn't

### ISSUE THREAD

**Issue by twk3** [chef/chef#6302]
## Description

When deep merge is run against a node attribute collection, where the destination is missing a key that the source has declared and set to `nil`, the act of checking for the existence of the key in the destination will cause it to be populated with an empty vividmash, causing the end result to be the empty mash instead of nil.

Here is where VividMash default to an empty mash when being referenced using `[]`

https://github.com/chef/chef/blob/59c6bd77abb071423daea0b62c4d97a54e0aa26a/lib/chef/node/attribute_collections.rb#L168

And here is where deep_merge checks for the key using `[]` rather than `key?`:
https://github.com/chef/chef/blob/2e92c709459dffef54f9d671e10ec9a949a94962/lib/chef/mixin/deep_merge.rb#L67

## Chef Version

Chef 12 and 13

## Replication Case

Can be seen in normal attribute easily, but would repro in default and override during the `apply_role_attributes ` method instead of `consume_attributes`

```
node.normal['cookbook']['predefined-attribute1'] = nil
node.normal['cookbook']['predefined-attribute2'] = nil
node.consume_attributes({ 'cookbook' => { 'fresh-attribute' => nil, 'predefined-attribute2' => nil } }) 
puts node['cookbook']['fresh-attribute'].inspect
# Result is `{}`. Expecting `nil`
puts node['cookbook']['predefined-attribute1'].inspect
# Result is `nil`. Expecting `nil`
puts node['cookbook']['predefined-attribute2'].inspect
# Result is `nil`. Expecting `nil`
```

**Comment by lamont-granquist** [comment]
PR would be most appreciated.  higher level functionalish tests of node attribute merging could get dropped somewhere vaguely appropriate in spec/unit/node_spec.rb which would be sufficient testing
