### ISSUE TITLE
CHANGELOG.md is missing information for most v13.3 versions

### ISSUE THREAD

**Issue by acoulton** [chef/chef#6309]
The CHANGELOG.md appears to be missing versions. The first two stanzas in the file are currently for v13.3.33 and v13.3.27 (which as far as I can tell aren't actually "released" even though they are tagged as releases?).

However, the next entry is v12.19.33 - there is no changelog at all listed for v13.2.20 which is the current actual release on downloads.chef.io. Nor indeed is there any changelog for *any* of the v13 releases prior to v13.3.27

It's actually quite unclear - from the changelog or from anywhere else that I've been able to find - trying to work out what Chef versions have actually been officially released, and what changes they introduce.

**Comment by tas50** [comment]
We've switched changelog generators and fixed the issue going forward, but we do have issues with the current changelog. I'll see what I can do to generate a better changelog for the previoius 13.X releases.

**Comment by acoulton** [comment]
Great, thanks @tas50

**Comment by tas50** [comment]
I've backfilled the latest Chef 12 releases here. 
https://github.com/chef/chef/blob/master/CHANGELOG.md

Chef 13+ is going to take a bit longer, but this gets us closer

**Comment by tas50** [comment]
13.0 releases have been added

**Comment by lamont-granquist** [comment]
looks fixed for now
