### ISSUE TITLE
Information from guards (not_if, only_if)

### ISSUE THREAD

**Issue by D33M** [chef/chef#6322]
## Description

Currently Chef displays generic information about why resource wasn't run, according to guards (`(skipped due to not_if)`). It would be nice if we could briefly describe this behaviour, without looking into cookbooks.

## Chef Version

```
Chef Development Kit Version: 2.0.26
chef-client version: 13.2.20
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 6.2.0
kitchen version: 1.16.0
inspec version: 1.30.0
```

## Suggessted mechanism

It would be nice if guards were a little more expanded:
```
execute 'Hello' do
   command     'rm -rf /'
    not_if [
       {File::exist?('/please_dont'), :information => 'Since you are begging, it will be skipped'},
       {user_is_my_friend && user_paid, :information => 'You're my dude!'},
       {node['hostname'] == 'my.computer', :information => 'I won't give myself more work...'}
    ]
end
```

This way it would display descriptive information *why* it was skipped (without looking inside code and wondering, which part made it `true`):

```
* execute [Hello] action run  (skipped due to not_if: 'Since you are begging, it will be skipped')
```

**Comment by coderanger** [comment]
Unfortunately that isn't valid Ruby code, the required gymnastics to work this into the DSL probably wouldn't be worth it.

**Comment by D33M** [comment]
Yeah, I do know, it isn't valid, I just wanted to show some example how it would like - just to show what I have in mind. Syntax can be of course quite different.
