### ISSUE TITLE
changelog not listing 12.21.4 changes...

### ISSUE THREAD

**Issue by gaelik** [chef/chef#6336]
## Description

We are currently deploying 12.21.3. We would like to know what changed in that release and how it impacts us

## Chef Version

12.21.3

## Platform Version

All platforms 

## Replication Case

Just point a browser to the changelog file... https://github.com/chef/chef/blob/master/CHANGELOG.md

**Comment by coderanger** [comment]
We're working on it, there's been a lot of issues with getting our changelog management scripts to deal with multiple active branches. In the short term you can look at the release notes file or the announcement on the mailing list.

Closing this out as it is known and tracked elsewhere.
