### ISSUE TITLE
Chef 13.3.42 universal-mingw32 missing from Rubygems.org

### ISSUE THREAD

**Issue by Annih** [chef/chef#6338]
Hello,

Chef 13.3.42 seems to be the latest release of chef-client (August 11, 2017), official packages for all platforms exist on https://downloads.chef.io/chef
But there is no gem for *universal-mingw32* platform on rubygems.org :cry: 

Any plan to release it soon?

Thanks :)

**Comment by coderanger** [comment]
I've poked some peoples, but I'm not actually certain why we publish that binary gem at all, I don't think we still ship any binary components in the Chef gem itself. Also FWIW we heavily recommend against installing Chef as a gem, please use the omnibus-style installers as you linked to.

**Comment by Annih** [comment]
Wow! Coming from a contributor like you this answer is ... interesting...

In general - not talking about the windows one - the chef gem is useful in at least the following cases:
* Gem development depending on chef/knife
* Cookbook testing (Maybe you heard about ChefSpec?)

And for the windows gem, for people like me using a Windows environment - for dev and/or testing purpose - the `universal-mingw32` gem has specific dependencies as defined in https://github.com/chef/chef/blob/master/chef-universal-mingw32.gemspec very useful when you need to install and load all your dependencies (e.g. bundler env.).

Anyway, thanks for poking people, I'm not in hurry but it would help me to work with latest version without hacking my bundle everywhere :)

**Comment by lamont-granquist** [comment]
shipped it manually, we're looking into why our autopublishing is still busted.

**Comment by coderanger** [comment]
@Annih ChefSpec is included with the ChefDK installer, which is the recommended way to test cookbooks.

**Comment by Annih** [comment]
@lamont-granquist thank you for this quick resolution :)

@coderanger I personally don't like the ChefDK, but I agree this it is the recommended way to test cookbooks.
In another hand ChefSpec is still a ruby gem which depend on the Chef ruby gem, so to bundle the ChefDK at some point you need to resolve the dependencies, etc.

I understand the goal of the ChefDK to hide all this logic, but again I don't like it. Most of the people I know who used the ChefDK, didn't understand their ruby environment at all.
IMHO ruby is kind of great to implement a system like Chef, and this language and its ecosystem already have ways to do packages and handles dependencies, no need to reinvent everything, (ruby + bundler are great :/). 
However I recognize all the great work done to build the ChefDK, and also admit that it helps people to start developing with Chef.

Chef is a great piece of Ruby, and thanks to that craftman's work, the ruby's ecosystem has been greatly enriched. My opinion on the ChefDK, doesn't change anything :)
