### ISSUE TITLE
Using $ in a filename breaks when combined with selinux

### ISSUE THREAD

**Issue by deltamualpha** [chef/chef#6346]
## Description

I have a `remote_directory` call that contains, within its tree, a file called `PropertyLoader$args.class`. When chef attempts to create this file, it fails with the following error message (paths elided for clarity):

```
---- Begin output of /sbin/restorecon -R "/path/to/PropertyLoader$args.class" ----
STDOUT:
STDERR: /sbin/restorecon:  lstat(/path/to/PropertyLoader.class) failed:  No such file or directory
---- End output of /sbin/restorecon -R "/path/to/PropertyLoader$args.class" ----
Ran /sbin/restorecon -R "/path/to/PropertyLoader$args.class" returned 255
```

`restorecon` points to this being an issue in the selinux handling of the file.

## Chef Version

```
$ chef-client -v
Chef: 13.3.42
```

## Platform Version

CentOS 7.3.1611

## Replication Case

I believe a minimal case would be a recipe that tries to create a file with a character that the shell would expand as a variable with SELinux turned on.

## Client Output

See above.

## Stacktrace

<https://gist.github.com/deltamualpha/47401fd0790bf1f564f0e26a313b83f9>

**Comment by coderanger** [comment]
Report from Slack, we must have missed a string-y shell out that needs to be array-y.

**Comment by lamont-granquist** [comment]
yeah that's buried in file provider helpers somewhere, its not directly in the provider code if i recall

**Comment by deltamualpha** [comment]
Would you accept https://github.com/deltamualpha/chef/tree/selinux-shellout-fix if I opened a PR with it (and it was properly smushed down to avoid the merge commit)?

**Comment by thommay** [comment]
Yes please @deltamualpha
