### ISSUE TITLE
chef chokes on git version string on apple.

### ISSUE THREAD

**Issue by kzw** [chef/chef#6350]
## Description

When running git resource on macbook with git provided by Apple, chef dies with the following exception
`Malformed version number string Git-81)`

## Chef Version

12.15

## Platform Version

Mac OS 10.12

## Replication Case

Run chef recipe using git resource.

## Client Output

```
===============================================================================
    Error executing action `sync` on resource 'git[/Users/redacted/arcanist/libphutil]'
    ================================================================================

    ArgumentError
    -------------
    Malformed version number string Git-81)

    Resource Declaration:
    ---------------------
    # In /Users/redacted/repo/chef/solo/cache/cookbooks/bread-local/recipes/default.rb

     19:   git File.join(arc_root, repo) do
     20:     repository File.join(github_root, repo)
     21:     revision version
     22:     depth 1
     23:   end
     24: end

    Compiled Resource:
    ------------------
    # Declared in /Users/redacted/repo/chef/solo/cache/cookbooks/bread-local/recipes/default.rb:19:in `block in from_file'
```
## Stacktrace

Please see above

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* Requests for new or alternative functionality should be made to [feedback.chef.io](https://feedback.chef.io/forums/301644-chef-product-feedback/category/110832-chef-client)
* [Chef Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by thommay** [comment]
For reference:
```
[17:01] ~/work/chef % /usr/bin/git --version 
git version 2.13.3 (Apple Git-91)
[17:01] ~/work/chef % /usr/local/bin/git --version
git version 2.14.1
```

**Comment by kzw** [comment]
Yes.  A work around would be to disable apple git.  But chef should be smarter about these version strings.  I feel that this should just a be small change in git resource code.

**Comment by thommay** [comment]
We'd welcome a pull request to fix this. The code in question is here:

https://github.com/chef/chef/blob/462ce499783771dd54d3cba576e6165643a25b11/lib/chef/provider/git.rb#L106-L108

**Comment by tas50** [comment]
Closing this out since it's been merged to master
