### ISSUE TITLE
DNF provider doesn't handle `:upgrade` as expected

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#6352]
## Description

DNF provider will downgrade if we have a newer package installed than the repo.

i.e.:

* Install foo-2.3-2
* yum/dnf repo's latest version is foo-2.1-1
* `package 'foo' { action :upgrade }` will downgrade you to 2.1

In the yum provider this wasn't true.

## Chef Version

12.21.4

## Platform Version

CentOS 7.3

## Replication Case

See above

**Comment by lamont-granquist** [comment]
confirmed.

it looks like a bug in the superclass from this line:

https://github.com/chef/chef/blob/master/lib/chef/provider/package.rb#L328

called from this block:

https://github.com/chef/chef/blob/master/lib/chef/provider/package.rb#L442-L456

we probably have this bug spread all over the package providers.  there needs to be hook here to do version comparison and subclasses should implement it.

**Comment by jaymzh** [comment]
Oddly, Package::Yum doesn't have this bug

**Comment by lamont-granquist** [comment]
there's probably some hack inside the yum provider to work around it.

**Comment by jonlives** [comment]
Confirming, I suspect this is the method in question: https://github.com/chef/chef/blob/master/lib/chef/provider/package/yum.rb#L159

Looks like it was added earlier this year as part of work to support multipackage_api. I'll take a look at getting a more generic fix into the superclass here.
