### ISSUE TITLE
Support multiple keys for apt_repository to match yum_repository

### ISSUE THREAD

**Issue by gsreynolds** [chef/chef#6369]
## Description

For `apt_repository` resource the key property does not accept an array of keys. The `yum_repository` resource does. 

https://github.com/chef/chef/blob/4f2bac9506f9e93dd33e0a94d61c016f6aeacbb1/lib/chef/resource/yum_repository.rb#L39
https://github.com/chef/chef/blob/4f2bac9506f9e93dd33e0a94d61c016f6aeacbb1/lib/chef/resource/apt_repository.rb#L36

For deb packages which require two keys to be installed to authenticate, it's not currently supported to install both in a single `apt_repository` resource. 

Current workaround: 
https://github.com/sous-chefs/rundeck/blob/247c4282b2be2c4fb0efcd814dde907a32a4b8ed/recipes/server_install.rb#L54-L73

Related: https://github.com/sous-chefs/rundeck/pull/178

## Chef Version

13.3.42

## Platform Version

Ubuntu 16.04, any debian based distro

## Replication Case

Install rundeck package from [bintray apt repo](https://dl.bintray.com/rundeck/rundeck-deb)
Need to install *both* bintray key `379CE192D401AB61` from keyserver.ubuntu.com and rundeck build key from `http://rundeck.org/keys/BUILD-GPG-KEY-Rundeck.org.key` to install the package without allowing unauthenticated packages

## Client Output

apt-get install execute in `apt_package` fails with
`E: There were unauthenticated packages and -y was used without --allow-unauthenticated`

**Comment by thommay** [comment]
We'd be very happy to take a PR for this.
As you say, 
https://github.com/chef/chef/blob/master/lib/chef/resource/apt_repository.rb#L36
would need updating to take an Array (you'd probably want to coerce a String in to an array, too)
and then update
https://github.com/chef/chef/blob/4f2bac9506f9e93dd33e0a94d61c016f6aeacbb1/lib/chef/provider/apt_repository.rb#L43-L48
to loop through the Array of keys.
