### ISSUE TITLE
windows_package does not perform remote install of exe on Windows 2012 R2

### ISSUE THREAD

**Issue by akramkm** [chef/chef#6371]
windows_package does not perform remote windows install on Windows of a exe  on windows 2012 R2

Error Message:
10.1.9.7 [2017-08-30T15:19:32+00:00] FATAL: Mixlib::ShellOut::CommandTimeout: windows_package[dyna] (dyna::agent-windows line 21) had an error: Mixlib::ShellOut::CommandTimeout: command timed out:
10.1.9.7 ---- Begin output of start "" /wait "c:\dyna.exe"   /q /n & exit %%%%ERRORLEVEL%%%% ----
10.1.9.7 STDOUT:
10.1.9.7 STDERR:
10.1.9.7 ---- End output of start "" /wait "c:\dyna.exe"   /q /n & exit %%%%ERRORLEVEL%%%% ----
10.1.9.7
10.1.9.7 ProcessId: 5108
10.1.9.7 app_name: C:\Windows\system32\cmd.exe
10.1.9.7 command_line: cmd /c "start "" /wait "c:\dyna.exe"   /q /n & exit %%%%ERRORLEVEL%%%%"
10.1.9.7 timeout: 600
ERROR: Failed to execute command on 10.1.9.7 return code 1

This is below configuration of my chef environment:
Chef Development Kit Version: 1.4.3
chef-client version: 12.19.36
delivery version: master (41b94ffb5efd33723cf72a89bf4d273c8151c9dc)
berks version: 5.6.4
kitchen version: 1.16.0
inspec version: 1.25.1

I have installed winrm-elevated -v 1.1.0 gem as well 

Below is the command I am trying to execute
knife winrm --winrm-shell elevated name:client2012 -a ipaddress -x admin -P password@123 --config C:\Users\admin\starter_kit\chef-repo\.chef\knife.rb chef-client

could you please advice

**Comment by btm** [comment]
@akramkm the error message here was `Mixlib::ShellOut::CommandTimeout`. When running this installer manually did it take around 10 minutes or more? The default timeout is 600 seconds. You can set a longer timeout using the `timeout` property of the `windows_package` resource.

https://docs.chef.io/resource_windows_package.html#properties

**Comment by stuartpreston** [comment]
Closing this issue due to age.

@akramkm Feel free to drop by our [Chef Community Slack](https://community-slack.chef.io) to discuss this issue if you still encounter it.
