### ISSUE TITLE
knife bootstrap winrm with json option injects escape characters into json string that are not removed

### ISSUE THREAD

**Issue by dscowan** [chef/chef#6373]
## Description

Briefly describe the issue
windows bootstrap winrm escapes parenthesis with multiple caret characters in the json argument.  This is not unescaped.  This causes specifically problems with the java cookbook not being idempotent because the attribute is different from what is stored in the windows registry.  Long story short a json attribue of 

Java 8 Update 66 (64-bit)

Gets turned into 

Java 8 Update 66 ^^^(64-bit^^^)

I found the line that does this

https://github.com/chef/knife-windows/blob/master/lib/chef/knife/core/windows_bootstrap_context.rb#L327

## Chef Version
12.21.4

Tell us which version of chef-client you are using (see below for Server+ChefDK bugs).

## Platform Version
12.21.4
Tell us which Operating System distribution and version chef-client is running on.
Windows 12.21.4

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.
knife bootstrap windows winrm -E testing -r role[test] -j {"java":{"windows":{"package_name":"Java Update 133 (64-bit)}}}

## Client Output

The relevant output of the chef-client run or a link to a gist of the entire run, if there is one.

test003F C:\Users\Administrator>(echo.{"java":{"jdk_version":"8","java_home":"c:/java/jdk1.8.0_66","windows":{"package_name":"Java 8 Update 66 ^^^(64-bit^^^)"}},"run_list":["role[test]"]} ) 1>C:\chef\first-boot.json 
....
test003F [2017-08-31T12:24:58-04:00] INFO: Processing windows_package[Java 8 Update 66 ^^^(64-bit^^^)] action install (java::windows line 101)

test003F [2017-08-31T12:24:58-04:00] INFO: Installing windows_package[Java 8 Update 66 ^^^(64-bit^^^)] version latest

test003F [2017-08-31T12:24:58-04:00] INFO: Starting installation...this could take awhile.

test003F [2017-08-31T12:26:22-04:00] INFO: windows_package[Java 8 Update 66 ^^^(64-bit^^^)] sending write action to log[jdk-version-changed] (immediate)

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it.

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* Requests for new or alternative functionality should be made to [feedback.chef.io](https://feedback.chef.io/forums/301644-chef-product-feedback/category/110832-chef-client)
* [Chef Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by tas50** [comment]
@RyanJarv In Chef Infra Client 15 we entirely rewrote how bootstrap works. I'm going to close this out at this point. If you're still seeing this sort of behavior in Chef Infra Client 15 please open it back up so we can dig in further.
