### ISSUE TITLE
Problem with ACLs when a user and a client has the same name

### ISSUE THREAD

**Issue by System25** [chef/chef#6378]
## Description

If you have in the system a user that has a name (for example: "charles_xavier") and you have a client with the same name ("charles_xavier"), when you try to add that user to the ACL of a node there is an error. I suppose that the cause if that the system doesn't now if the actor that you are trying to add to the ACL is the user or the client.

I think that it would be better if there were a way to specify whether the actor is a client or a user.

## Chef Version

12.0.6

## Platform Version

CentOS 6.

## Replication Case

Create a file called "acltest.txt" with the following content:
```
{
  "create": {
    "actors": [
      "pivotal",
      "charles_xavier"
    ],
    "groups": [
      "clients",
      "users",
      "admins"
    ]
  }
}
```

Then execute the following commands:

```
chef-server-ctl  user-create charles_xavier Charles Xavier charles_xavier@xmen.com mypass
knife client create charles_xavier
knife node create mytestnode
knife raw /organizations/default/nodes/mytestnode/_acl/create -m PUT -i acltest.txt
```

The error message is:
```
ERROR: Server responded with error 400 "Bad Request"
ERROR: Error Body: {"error":["Invalid/missing actor in request body"]}
```

**Comment by thommay** [comment]
Hi, this is the bug tracker for the chef-client. For chef-server bugs, like this one, please file an issue at https://github.com/chef/chef-server/issues/new . I'll be closing this issue now.

**Comment by System25** [comment]
Ok. Issue created: https://github.com/chef/chef/issues/6378
