### ISSUE TITLE
policy_name/policy_group not found in attributes

### ISSUE THREAD

**Issue by scopenco** [chef/chef#6390]
## Description

I'm trying to use search in chef recipe like this
```
servers = search(:node, ‘some_attr:true’,
  filter_result: { name: [‘name’],
                   policy_name: [‘policy_name’],
                   policy_group: [‘policy_group’],
                    }
                )
```
and servers return me result with empty policy_name/policy_group. I understand that policy_name/policy_group are node data but why then name is returning? If i'm not mistaken it's node data too.

How can I get policy_name/policy_group using `filter_result`?

## Chef Version

```
$ chef-client -v
Chef: 12.20.3
```

chef server 12.16.2

## Platform Version

CentOS Linux release 7.3.1611 (Core)

**Comment by tas50** [comment]
I'm fairly positive we fixed this in a later version of Chef Client. I'm going to close this out at this point, but if you see this on a Chef Infra Client 15 release please open it back up so we can dig into the codebase and make this work.
