### ISSUE TITLE
dnf_helper.py in Dnf provider fails to run due to SIGCHLD hander

### ISSUE THREAD

**Issue by nemith** [chef/chef#6393]
## Description

When the Dnf provider runs the python helper script `dnf_helper.py` it exits right after the call the base.fill_sack().  Removing the SIGCHLD handler fixes the problem. 

https://github.com/chef/chef/blob/0764bf5de8f21de13fb8e25373af5667b7c22771/lib/chef/provider/package/dnf/dnf_helper.py#L75

Found on Fedora 26

## Chef Version

12.19.36

## Platform Version

Fedora 26 x86_64

## Replication Case

compile time recipe exposed this for me.
 50:  if node.linux? # ~FC019, ~FC023
 51:    # The Linux plugins require dmidecode
 52:    package 'dmidecode' do
 53:      action :nothing
 54>>   end.run_action(:upgrade)
 55:  end

## Client Output

https://gist.github.com/nemith/cc6e53e5713cc7c147cc7e1c6197263e

**Comment by nemith** [comment]
Also why is the signal handler exit with an exit code of 0 and not a non-zero value?

**Comment by lamont-granquist** [comment]
it probably should exit -1 or something, but the only thing that talks to it is the dnf package provider which doesn't care.

**Comment by lamont-granquist** [comment]
so offhand this morning i don't understand what the SIGCHLD handler has to do with the EOFError the chef run spits out.

**Comment by nemith** [comment]
I am guessing the dnf package is starting a child process during the fill_sack() call.  The child process ends and a SIGCHLD is sent to the dnf_helper python process, it is caught in the signal handler and the exits without any output.  

I have no idea why SIGCHLD is being handled at all here, it makes no sense to exit on that call in any use case that I can think of.

Since my rule is forced to run at compile time i am getting the EOFError.  If it was properly running at runtime i am sure the error would be more appropriate.

This showed up after a system upgrade or something else that caused dnf to start a child process.  I am not sure exactly the trigger.

**Comment by lamont-granquist** [comment]
oh the default is to ignore it, right...
