### ISSUE TITLE
windows_package incorrectly tries to install an older version of a package.

### ISSUE THREAD

**Issue by rdean716** [chef/chef#6396]
## Description

When a newer version of an MSI package is installed, the windows_package resource attempts to install the older package version.  From what I can gather (i could be wrong) from the documentation this should not be the expected behavior.

## Chef Version

Chef: 12.18.31

## Platform Version

Windows Server 2012 R2

## Replication Case

As defined in our recipe:

```ruby
package 'RSA Authentication Agent' do
  source rsaauth_package
  action :install
  options "/L*V #{log_file}"
end
```

When the package source is the 7.2.1.93 version of the package AND 7.3.2.76 is the currently installed version the package resource determines that the agent needs updating - which Windows Installer Blocks with 1638 because another version of the product is already installed - resulting in a failed chef-client run.

Adding an array of version does not stop the resource from attempting the installation

Adding an array of return codes does stop this from terminating the chef run, but causes the package to attempt to install each time.

## Client Output

- truncated client output:
```
INFO: Processing windows_package[rsaauth] action install (win_baseline::rsaauth line 18)
INFO: Running queued delayed notifications before re-raising exception
ERROR: Running exception handlers
ERROR: Exception handlers complete
INFO: Sending resource update report (run-id: 5e73df2f-d116-4e9b-9983-56658048ac80)
FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
FATAL: Mixlib::ShellOut::ShellCommandFailed: windows_package[rsaauth] (win_baseline::rsaauth line 18) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1638'
---- Begin output of msiexec /qn /i "c:\chef\cache\rsaauth_7.2.1.93.msi"  /L*V C:\chef\cache/msi_logs\rsaauth.log ----
STDOUT: A n o t h e r   v e r s i o n   o f   t h i s   p r o d u c t   i s   a l r e a d y   i n s t a l l e d .     I n s t a l l a t i o n   o f   t h i s   v e r s i o n   c a n n o t   c o n t i n u e .     T o   c o n f i g u r e   o r   r e m o v e   t h e   e x i s t i n g   v e r s i o n   o f   t h i s   p r o d u c t ,   u s e   A d d / R e m o v e   P r o g r a m s   o n   t h e   C o n t r o l   P a n e l .
STDERR: 
---- End output of msiexec /qn /i "c:\chef\cache\rsaauth_7.2.1.93.msi"  /L*V C:\chef\cache/msi_logs\rsaauth.log ----
Ran msiexec /qn /i "c:\chef\cache\rsaauth_7.2.1.93.msi"  /L*V C:\chef\cache/msi_logs\rsaauth.log returned 1638
---- End output of msiexec /qn /i "c:\chef\cache\rsaauth_7.2.1.93.msi"  /L*V C:\chef\cache/msi_logs\rsaauth.log ----
Ran msiexec /qn /i "c:\chef\cache\rsaauth_7.2.1.93.msi"  /L*V C:\chef\cache/msi_logs\rsaauth.log returned 1638
```

- truncated debug output:

```
DEBUG: windows_package[RSA Authentication Agent] getting product code for package at c:\chef\cache\rsaauth_7.2.1.93.msi
DEBUG: windows_package[RSA Authentication Agent] checking package status and version for {1CBBF615-E223-45A3-BE98-4B67EC6846DA}
DEBUG: Checking if windows_package[RSA Authentication Agent] version '["7.2.1.93", "7.3.2.76"]' is already installed. 7.3.2.76 is currently installed
DEBUG: windows_package[RSA Authentication Agent] RSA Authentication Agent 7.3.2.76 needs updating to ["7.2.1.93", "7.3.2.76"]
DEBUG: windows_package[RSA Authentication Agent] installing MSI package 'c:\chef\cache\rsaauth_7.2.1.93.msi'
A n o t h e r   v e r s i o n   o f   t h i s   p r o d u c t   i s   a l r e a d y   i n s t a l l e d .     I n s t a
l l a t i o n   o f   t h i s   v e r s i o n   c a n n o t   c o n t i n u e .     T o   c o n f i g u r e   o r   r e
m o v e   t h e   e x i s t i n g   v e r s i o n   o f   t h i s   p r o d u c t ,   u s e   A d d / R e m o v e   P r
o g r a m s   o n   t h e   C o n t r o l   P a n e l .
```

## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* Requests for new or alternative functionality should be made to [feedback.chef.io](https://feedback.chef.io/forums/301644-chef-product-feedback/category/110832-chef-client)
* [Chef Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by lamont-granquist** [comment]
related to  #6352

**Comment by btm** [comment]
@jonlives do we believe that https://github.com/chef/chef/pull/6428 in Chef 13.5.8+ may have fixed this? should we re-test?
