### ISSUE TITLE
chef-server-ctl backup brings down the chef server

### ISSUE THREAD

**Issue by rudymccomb** [chef/chef#6398]
## Description

`chef-server-ctl backup` seems to bring down the Chef Server, nowhere in the docs does it say that backing the above command will bring down the Chef Server for a time.
[https://imgur.com/a/5ivBC](url)

I've also filed bug here https://github.com/chef/chef-server/issues/1391 just in case i filed in the wrong location

## Chef Version

Chef 12.15.6

## Platform Version

Ubuntu 16.04LTS

## Replication Case

You should be able to replicate this by running `chef-server-ctl backup` on any Chef Sever 12.5+, I haven't tested this below 12.5.

## Client Output

[https://imgur.com/a/5ivBC](url)

## Stacktrace

N/A as there is no error

### NOTE: CHEF CLIENT BUGS ONLY

* Requests for new or alternative functionality should be made to [feedback.chef.io](https://feedback.chef.io/forums/301644-chef-product-feedback/category/110832-chef-client)
* [Chef Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by thommay** [comment]
Thanks, but the chef server repository was the right location. I'll close this bug now.
