### ISSUE TITLE
windows_task: tasks will not run on battery power

### ISSUE THREAD

**Issue by spuder** [chef/chef#6403]
Scheduled tasks by default will not run if on battery power. This includes test kitchen vms. 

<img width="647" alt="screenshot 2017-09-13 21 17 46" src="https://user-images.githubusercontent.com/242382/30410805-7e2807ba-98ca-11e7-8dc9-7dabc364b338.png">

This should not be the default, or at least it should be configurable. If you are on a laptop, you will spend hours of fun debugging why chef works when your laptop is plugged in, but not when on battery power. (Even if your workstation is a mac)

## How

There are 3 main ways to make a windows scheduled task. 

- Schedtask.exe
- [New-ScheduledJobOption](https://docs.microsoft.com/en-us/powershell/module/psscheduledjob/new-scheduledjoboption?view=powershell-5.1)
- XML

SchedTask.exe is not able to modify the power/battery settings. You must either use the powershell module, or import the task as xml. 

    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>

### Possible config options
```ruby
windows_task 'foo' do
  conditions :start_only_ac_power, false, :stop_on_battery, false 
end
```
```ruby
windows_task 'foo' do
  start_only_ac_power false
  stop_on_battery false
end
```

**Comment by jaymzh** [comment]
Hey @tas50 - what's the status of this? It looks like `windows_task` (now?) uses XML... I think one could just add a property that sets DisallowStartIfOnBatteries in the XML?

This has bitten our client team pretty hard. :/

**Comment by spuder** [comment]
It looks like the XML is only when updating an existing task, chef still uses the commands for creation. 

https://github.com/chef/chef/blob/master/lib/chef/provider/windows_task.rb

**Comment by jaymzh** [comment]
@spuder - `def action_create` seems to use XML to me. Am I missing something?

**Comment by tas50** [comment]
We're currently working on rewriting the whole thing to use the win32-taskscheduler gem, which is XML based under the hood. This will allow for all the fancy (and basic) things like running on battery and real priorities.

The WIP PR is https://github.com/chef/chef/pull/6815

**Comment by tas50** [comment]
Now that we landed the rewrite of windows task to no longer uses the CLI we should figure out if we can get this fixed up. The default for the resource should definitely be to run on battery power.
