### ISSUE TITLE
ChefSpec Summary Output Not Displaying Verbs

### ISSUE THREAD

**Issue by adamscharf** [chef/chef#6412]
## Description

After running chefspec, the summary output for tests are no longer displaying the verbs. Is this a recent change to the coding standard and I need to update my tests or a bug with ChefSpec?

e.g.,

### Tests
```ruby
expect(chef_run).to create_directory('/opt/my-folder').with(
  owner: 'root',
  group: 'root',
  mode: '0755',
  )
end

it do
  expect(chef_run).to install_package('unzip')
end
```
### Expected Output
```bash
  should create directory "/opt/my-folder"
  should install package "unzip"
```
### Actual Output
```bash
  should  directory "/opt/my-folder"
  should  package "unzip"
```

## Chef Version

```bash
▶ chef --version
Chef Development Kit Version: 2.1.11
chef-client version: 13.2.20
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.0
kitchen version: 1.17.0
inspec version: 1.33.1
```

## Platform Version

macOS Sierra - Version 10.12.6 (16G29)

## Replication Case

Write any test and omit the manual description. The assumed description doesn't include the verbs.

**Comment by thommay** [comment]
Hi, thanks for reporting an issue, but this issue tracker is for the chef client. For chefspec bugs, please make a report at https://github.com/chefspec/chefspec/issues/new. I'll be closing this report now.

**Comment by adamscharf** [comment]
Oh, ok. Sorry about that!
