### ISSUE TITLE
Unremovable node with name starting with '-'

### ISSUE THREAD

**Issue by raphaunix** [chef/chef#6415]
Well, somehow we created a node and client with the following name **"-r"**
**Example hosts:**
```
freebsd1.example.com
freebsd2.example.com
freebsd3.example.com
-r
centos1.example.com
centos2.example.com
```
When I try to remove it the knife executable understands as a parameter even when I use double or single quotes and outputs the **USAGE** of the knife, the commands I've tried:
```
knife node delete -r
knife node delete "-r"
knife node delete '-r'
knife client delete -r
knife client delete "-r"
knife client delete '-r'
```
How can I remove this node/client from chef server?
Thanks

**Comment by coderanger** [comment]
`knife raw -m DELETE /nodes/-r` and similar for clients.

**Comment by coderanger** [comment]
And in the future this is not the right place to ask for user support, this is for bug reports only. You can use the mailing list or Slack channels to ask for help.
