### ISSUE TITLE
ERROR: IOError: closed stream on knife ssh when an instance terminates

### ISSUE THREAD

**Issue by popsikle** [chef/chef#6418]
## Description
When running knife ssh on a large fleet of servers if any of them shut down the whole knife ssh run is terminated.  Can not re-open the older bug, https://tickets.opscode.com/browse/CHEF-3810

## Chef Version
12.x

## Platform Version
OSX, 12.X

## Replication Case
run knife ssh 'name:*' 'sudo chef-client' while terminating an ec2 instance

## Client Output
ERROR: IOError: closed stream

## Stacktrace
N/A

**Comment by stuszynski** [comment]
Had the same issue.

**Comment by r00twayne** [comment]
i am also experiencing this issue

**Comment by stuszynski** [comment]
Having the same issue.

**Comment by vvchik** [comment]
Mee too :)
