### ISSUE TITLE
chef solo/zero throws error when using relative path for node attribute json file

### ISSUE THREAD

**Issue by darrendao** [chef/chef#6427]
## Description

Chef solo and chef client zero throws error when node attribute json is specified with relative path on the command line

## Chef Version
Chef: 13.4.19

## Platform Version

RHEL 7, chef 13.4.19

## Replication Case
My chef config solo.rb file
```
# Set chef homedir
chef_home_dir = File.expand_path('./')

# Download temporary files to /tmp
file_cache_path '/tmp'

# Set path to config
cookbook_path [ File.join(chef_home_dir, 'shared', 'cookbooks'),
                File.join(chef_home_dir, 'cookbooks'),
                File.join(chef_home_dir, 'third-party', 'cookbooks')
              ]
role_path File.join(chef_home_dir, 'roles')
environment_path File.join(chef_home_dir, 'environments')
data_bag_path File.join(chef_home_dir, 'data_bags')
# Chef log file
log_location '/var/log/chef/chef.log'
```
My node attribute json file
```
{
  "run_list": ["recipe[ddaotest]"]
}
```

Run either chef solo or chef zero
```
chef-solo -c config/solo.rb -j nodes/my_node.json
# or
chef-client -z -c config/solo.rb -j nodes/my_node.json
```

## Client Output
[2017-09-20T14:12:48-07:00] WARN: *****************************************
[2017-09-20T14:12:48-07:00] WARN: Did not find config file: /config/solo.rb, using command line options.
[2017-09-20T14:12:48-07:00] WARN: *****************************************[2017-09-20T14:12:48-07:00] FATAL: Cannot load configuration from nodes/my_node.json

## Observations
* If I use full path, then everything is fine.
* I believe the problem is when the `reconfigure` method is called, the PWD is `/` so when it tries to load the files, it fails to find it.

**Comment by DennyZhang** [comment]
@darrendao Noticed the same thing.

```
[root@www.dennyzhang.com ~]# chef --version
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.19
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.36.1
```

**Comment by alexpop** [comment]
Seeing the same error on chef-client `13.6.4`:
```
[root@myapache ~]# chef-client --json-attributes attrs.json
Starting Chef Client, version 13.6.4
...SNIP...
Chef Client finished, 0/2 resources updated in 05 seconds
[2017-12-21T11:09:33+00:00] FATAL: Cannot load configuration from attrs.json
```

But I can confirm that the attributes in my `attrs.json` have been used in the run.

**Comment by aryaNmlp** [comment]
Ask on google help forum. Please it is helpfu


thanks indu

**Comment by aryaNmlp** [comment]
http://www.editey.com/file/1R3-W350jP23OT7PMqOT3huJxAuSYFOiQ

**Comment by AlmogCohen** [comment]
Same error here on MacOSX 
```
Chef Development Kit Version: 3.1.0
chef-client version: 14.2.0
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.4
kitchen version: 1.22.0
inspec version: 2.1.72
```

`[2018-07-08T15:36:29-06:00] FATAL: Cannot load configuration from XXX`
