### ISSUE TITLE
windows_task start_day format incompatibility in 13.4+

### ISSUE THREAD

**Issue by croffe** [chef/chef#6439]
## Description

windows_task used to take in the start_day as MM/DD/YYYY before Chef Client 13.4
The documentation still shows start_day is required as 05/30/2017
windows_task starting with Chef Client 13.4 now only succeeds when the date comes in as 30-May-2017

## Chef Version

Chef Client 13.4 (Windows)

## Platform Version

Windows 2012 R2

## Replication Case

Create a windows_task with start_day as MM/DD/YYYY (it will fail with Chef Client 13.4+)

## Client Output

         * windows_task[chef-client] action create
       
           ================================================================================
           Error executing action `create` on resource 'windows_task[chef-client]'
           ================================================================================
       
           ArgumentError
           -------------
           invalid date
       
           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/my_chef_client/recipes/update_windows.rb
       
            25: windows_task 'chef-client' do
            26:    run_level :highest
            27:    command "C:/opscode/chef/bin/chef-client"
            28:    user "SYSTEM"
            29:    password nil
            30:    frequency :hourly
            31:    start_time (Time.now + 3600).strftime('%H:%M')
            32:    start_day Time.now.strftime('%m/%d/%Y')
            33: end
            34: 
       
           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/my_chef_client/recipes/update_windows.rb:25:in `from_file'
       
           windows_task("chef-client") do
             action :create
             default_guard_interpreter :default
             task_name "chef-client"
             declared_type :windows_task
             cookbook_name "my_chef_client"
             recipe_name "update_windows"
             run_level :highest
             command "C:/opscode/chef/bin/chef-client"
             user "SYSTEM"
             password nil
             frequency :hourly
             start_time "18:46"
             start_day "09/25/2017"
             execution_time_limit "PT72H"
           end
       
           System Info:
           ------------
           chef_version=13.4.24
           platform=windows
           platform_version=6.3.9600
           ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
           program_name=C:/opscode/chef/bin/chef-client
           executable=C:/opscode/chef/bin/chef-client

**Comment by croffe** [comment]
This is fixed with commit https://github.com/chef/chef/commit/b0d96997b7a1f53824c3cb0905de3e4bc770e534

**Comment by CodingSpiderFox** [comment]
For me, 13.4.24 worked, see discussion on #6434
