### ISSUE TITLE
Enable Multiple repos in chef resource package is not working in ol6.x

### ISSUE THREAD

**Issue by jagan495** [chef/chef#6448]
Cookbook version

[Version of the cookbook where you are encountering the issue]
[0.1.0]
System Info:
------------
chef_version=13.1.31
platform=oracle
platform_version=6.6
ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
program_name=chef-client worker: ppid=12981;start=03:14:33;
executable=/opt/chef/bin/chef-client
Platform Details

[Operating system distribution and release version. Cloud provider if running in the cloud]
platform_version=6.6

Scenario:

[What you are trying to achieve and you can't?]

i am trying to run below cookbook but throwing "base repo is not found. base repo is already there in /etc/yum.repos.d/pdrepo.repo. Even if we change repo order its keep on throwing error for second repo only. Same cookbook is working fine in other ol6.8 and ol7.x but not working in ol6.4,ol6.5.ol6.6, and ol6.7. Can some one please check on this.

  package "cloud-utils-growpart.x86_64" do
    version "0.27-9.el6"
    provider Chef::Provider::Package::Yum
    flush_cache [:before, :after]
    options '-c /etc/yum.repos.d/pdrepo.repo --disablerepo=* --enablerepo=addons,base'
    action :install
  end
FYIU Manually i executed below command and its working fine.

yum -c /etc/yum.repos.d/pditrepo.repo --disablerepo=* --enablerepo=addons,base install cloud-utils-growpart-0.27-9.el6.x86_64

Dependencies Resolved

=============================================================================================================================================
Package Arch Version Repository Size

Installing:
cloud-utils-growpart x86_64 0.27-9.el6 addons 24 k

I was stuck here. If we add more than two repos in --enablerepo=addons,base, its throwing error. If we add only single repo its working fine like --enablerepo=addons

**Comment by jagan495** [comment]
I was stuck here. If we add more than two repos in --enablerepo=addons,base, its throwing error. If we add only single repo its working fine like --enablerepo=addons

**Comment by jagan495** [comment]
Can someone please look into this

**Comment by lamont-granquist** [comment]
fixing in #6540
