### ISSUE TITLE
Using Kernel.require instead of Kernel.load to load library

### ISSUE THREAD

**Issue by Annih** [chef/chef#6450]
Cookbooks libraries are loaded using *Kernel.load* in the [cookbook loader](https://github.com/chef/chef/blob/e75454384a9763458ea7d6d0aa7472521025dcbd/lib/chef/run_context/cookbook_compiler.rb#L224). This means that one library could be loaded multiple times, producing warnings about constant redefinition and other weird behavior.

I did some archeology and it seems the `Kernel.require` call has been replaced by a `Kernel.load` a while ago (6 years) due to some [issue with the chef-client daemon](https://github.com/chef/chef/commit/c3c701f6efb5b7f8f4a2bb2b1140b9f9defd6c8e).

Would it be possible to reconsider this change? I don't know if the original issue is still present with the recent code base.
A possible workaround would be to use `Kernel.require` everywhere but empty the *$LOADED_FEATURES* array using `$LOADED_FEATURES.clear` 

In the case using `Kernel.require` is not an option, maybe you should add a comment to explain why this is not possible. This would save a lot of time to people in my situation :)

## Chef Version

All including current one (13.4.24)

*Cc.* @aboten

**Comment by thommay** [comment]
Please can you describe the actual problem you're encountering?

**Comment by Annih** [comment]
As I said, while Chef is loading all the cookbooks, ruby triggers some constant re-definition warnings:
> warning: already initialized constant XXX
> warning: previous definition of XXX was here

To avoid these warnings we need to write [defensive code like this](https://github.com/chef-cookbooks/windows/blob/master/libraries/version_helper.rb#L28) which pollute the rest of the file.

In testing environment, e.g. with Chefspec, it adds complexity to stub libraries, which can already be a pain. See chefspec/chefspec#562 & chefspec/chefspec#778

I can imagine more weird cases where my code (evaluated twice) can produce a different result or create side-effects. As a lazy and trustful developer I would expect Chef to load my libraries once, and let me do all the hacks I want without worrying to have my code evaluated multiple times.

Is it clearer with this explanation?

**Comment by coderanger** [comment]
This is almost entirely limited to being a problem in ChefSpec unless you do something Very Bad™ in your cookbook code. That said, with forking mode enforced it should be fine to reverse that change.

**Comment by Annih** [comment]
So is something you are going to revert in Chef14? :D

@thommay just to formalize an easy reproduction pattern, imagine you have libraries *A* en *B*, with *A* requiring that *B* is loaded before:
**libraries/A.rb**
```ruby
require_relative 'B.rb'
# do stuff with B
```
**libraries/B.rb**
```ruby
CONST = 0
```

Due to alphabetical sort, *A* will be loaded first, thanks to my `require_relative 'B.rb'` it'll still work properly. Then Chef is loading *B* again... triggering the below warning:
> B.rb:1: warning: already initialized constant CONST
> B.rb:1: warning: previous definition of CONST was here

I can think of more complex issues but @coderanger would say this is *Very Bad™*  :smile:

**Comment by coderanger** [comment]
Corry, as it exists today you should never use `require_relative` from Chef libraries/ code (or similar tricks). Either name your files such that they will be loaded in the right order or rely on late binding if possible.

**Comment by Annih** [comment]
As you said if you enforce the `forking mode`, libraries could be required instead of loaded, thus allowing people to do `require_relative`.
You can control the loading order of recipes and attributes using `include_recipe` & `include_attribute`, why not libraries?
Ruby has a proper way of requiring files, lets just use it instead of tricking it. :smile:

**Comment by coderanger** [comment]
Sure, hence why we should fix it, it's just that we already have well-worn patterns for this so it's mostly an incremental fix, not something hugely high priority.
