### ISSUE TITLE
Chef 13.5.3 universal-mingw32 missing from Rubygems.org

### ISSUE THREAD

**Issue by Annih** [chef/chef#6472]
Hello,

Chef 13.5.3 seems to be the latest release of chef-client (September 28, 2017), official packages for all platforms exist on https://downloads.chef.io/chef
But there is no gem for universal-mingw32 platform on rubygems.org :cry:

As for 13.3.42 tow months ago (#6338), any plan to release it soon?

Thanks :)

**Comment by Annih** [comment]
@lamont-granquist do you think you could manually release it sa you did for the 13.3.42 version?

Thanks in advance.

**Comment by tas50** [comment]
@Annih Our current release tooling misses this one and we have an issue open to add the push to rubygems. I manually pushed the gem up for you. Sorry about that.

**Comment by Annih** [comment]
Thanks a lot @tas50
