### ISSUE TITLE
Remove precedence levels from the NodeMap aka provides lines aka "make cookbooks always win"

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#6495]
Right now more specific provides lines always take precedence 

```
# this in core
provides :whatever do
  which("whatever")
end

# will always by design beat this in cookbooks
provides :whatever, platform :rhel

# leading to things like
provides :whatever, platform :rhel do
  true
end
```

To avoid warfare in cookbooks descending into always decorating provides lines with always-true blocks, we should probably rethink this design and go back to some form of last-writer-wins strategy.  This is also confusing for users since its fairly lightly documented.  Once you grok it, its pretty easy to figure out, but it constantly bites people, and it bit us internally when we started shipping core resources that were more specific than cookbook resources and were suddenly 'surprised' that cookbooks stopped winning.

This will be a disruptive breaking change though.

Much work probably needs to be done to lay the groundwork for this, including deprecation warnings and possibly an RFC.  Issuing correct deprecation warnings for the changing behavior may be...  interesting...  and might rise to the level of 3694 warnings.

This is currently a placeholder issue to track the fact that we've talked about this problem and acknowledged that it is a problem.  Since the solution is inherently disruptive this issue may linger for quite some time (the fact that it's sort of high impact vs high effort and likely high disruptive impact to fix means the cost/benefit and time analysis is somewhat fuzzy).

**Comment by coderanger** [comment]
This would also break the `noop` provider trick in much of core Chef.

**Comment by lamont-granquist** [comment]
Yep, but that was not the right approach.

**Comment by lamont-granquist** [comment]
So now I'm not sure this is the correct approach, or is the correct rationale anyway for doing this.

In the past when we've ported resources into core chef and not deprecated them in the cookbook this has created years-long arms races between core chef and the window cookbook, which was terrible for everyone involved.

The problem that we seemed to have with some resources it that we attempt to 'fix' them as we pull them into core chef, and by not copying the behavior of the cookbook we generate users which prefer the cookbook behavior over core chef.  Or else we simply have regressions in the core chef versions.  Both of those problems would go away if we did not mutate resources as we brought them into core (always fix the cookbook first), and if we treated regressions between the cookbook behavior and core chef as regressions and released bugfixes.  Basically, if we did more careful software development practices we could address those problems, while not creating the problem of the arms race between cookbooks and core.

I've done this three times now without a lot of problems (and all, oddly enough for windows resources, go figure...):

- registry_key:  we changed the behavior of this, so we changed the resource name, and then killed the version in the cookbook
- powershell_out:   this was faithfully copied, and the version in the cookbook was deprecated so core would win (manually), with big splash comments that patches would not be accepted, then it was removed
- chocolatey_package:   again the functionality was slightly different, so the name was changed.   it got some aggressive love in the beginning to make sure it was more functional than the one in the cookbook (which had no multipackage support, etc).

**Comment by coderanger** [comment]
Related to this is how different the core and cookbook testing stories are so we can't easily bulk-import a cookbook's tests. But at this point I'm reaching broken-record-of-preaching-to-the-choir levels with that one :)

**Comment by lamont-granquist** [comment]
Yeah, literally was talking to thom about that one in a 1-on-1 yesterday morning...

**Comment by lamont-granquist** [comment]
The whole cookbook/core precedence issue is being discussed in this RFC:  https://github.com/chef/chef-rfc/pull/305
