### ISSUE TITLE
chef-client cookbook does not work on Windows 2012R2 anymore

### ISSUE THREAD

**Issue by CodingSpiderFox** [chef/chef#6513]
## Description

We use the chef-client cookbook to setup chef-client in such a way that it is run every 5 minutes using the windows task scheduler

## Chef Version

ChefDK 2.3.4
chef-client 13.5.25
Tell us which version of chef-client you are using (see below for Server+ChefDK bugs).

## Platform Version

Windows Server 2012 R2 (6.3.9600)

## Replication Case

1. Assign the chef-client cookbook to the role which will be used for the node.

2. Set the attributes to

```
{
  "chef_client": {
    "interval": 300,
    "splay": 60
  }
}
```

3. Bootstrap the client with the command `PS D:\repo\<HIDDEN_PATH>> knife bootstrap windows winrm <HIDDEN_IP> -x '<HIDDEN_DOMAIN>\<HIDDEN_USERNAME>' --bootstrap-proxy <HIDDEN_PROXY> --bootstrap-no-proxy '<NO_PROXY_ADDRESSES>' --run-list 'role[<HIDDEN_ROLE>],' --node-ssl-verify-mode none --environment <HIDDEN_ENVIRONMENT> --node-name <HIDDEN_HOSTNAME> --bootstrap-version 13.5.22 --prerelease -V`

NOTE THAT chef-client 13.5.25 was installed instead of 13.5.22

4. Output 
[bootstrap.txt](https://github.com/chef/chef/files/1401675/bootstrap.txt)

5. Node was bootstrapped and shows up in chef-server UI. The chef-client scheduled windows task was created. Wait for first execution (runs after about 5 mins)

6. Output is:

6.1. chef-client.log
[chef-client run1.txt](https://github.com/chef/chef/files/1401676/chef-client.run1.txt)

6.2. stacktrace.out
[stacktrace1.txt](https://github.com/chef/chef/files/1401677/stacktrace1.txt)

6.3. In the chef-server web UI, the "last checkin" field's value keeps increasing, no successful checkin was recorded.

7. Run chef-client manually on the node: `cmd /c "C:/opscode/chef/bin/chef-client -L C:/chef/log/client.log -c C:/chef/client.rb -l debug"`

8. Output is:

8.1. chef-client.log
[chef-client 2.txt](https://github.com/chef/chef/files/1401685/chef-client.2.txt)

8.2. stacktrace.out (obviously almost the same)
[stacktrace2.txt](https://github.com/chef/chef/files/1401686/stacktrace2.txt)

## Client Output

see above

## Stacktrace

see above

**Comment by coderanger** [comment]
Is your issue with the cookbook or with the bootstrap process? If it's the cookbook, we would have to open this over on the cookbook as that is a separate project from Chef core itself.

**Comment by CodingSpiderFox** [comment]
To be honest, I don't really know.

This issue is related to #6434

**Comment by manheraz** [comment]
Hi there!

Our managed nodes running Windows Server 2016 Standard and Chef-Client 13.5.3 (latest stable release at the moment) have this problem too.

In our case, system language is English but date/time/currency is **Spanish** (so our date has the DD/MM/YYYY format)

We'll try downgrading to Chef-Client 13.4.24 until this is fixed. It seems that @CodingSpiderFox had success with that version (check comments in #6434 for more details)

**Comment by krzkowalczyk** [comment]
It seems to be the same issue as I reported and explained in [6480](https://github.com/chef/chef/issues/6480#issuecomment-338168654) and it occurs when no start_date is provided to windows_task resource and task already exists. Then new_resource.start_day is overridden by current_resource.start_day which is in local machine time format, and thus in non English systems cannot be parsed as not following "%m/%d/%Y" format.

**Comment by manheraz** [comment]
Yeah, it seems the same issue. This one should be marked as duplicate.

Great explanation, by the way...

Thank you!

**Comment by lamont-granquist** [comment]
closing as dup
