### ISSUE TITLE
knife ssh half-ignores -P if -i given

### ISSUE THREAD

**Issue by bby-bishopclark** [chef/chef#6516]
## Description

if one specifies a password on the command line, and also specifies an identity file, knife ssh will ask for the password again.

## Chef Version

chefdk-2.0.28-1.el7.x86_64

## Platform Version

RHEL/CentOS7 (up to date)

## Replication Case

cd ~/chef-repo ; knife ssh -m 10.1.2.3-x temp -i ~/.ssh/id_chef -P Tempp@ss -- uptime

## Client Output

temp@10.1.2.3's password:

### NOTE: CHEF CLIENT BUGS ONLY

https://github.com/chef/chef/blob/master/lib/chef/knife/ssh.rb#L263
probably 
   sed -i '263s/elsif/end\nif/'  
   that file and we're good. 

I think the elsif is inhibiting the *saving* of the password in the invocation, and a second bit of code sees the commandline '-P' with no password saved, and helpfully prompts the user.

If I'm not on crack.

**Comment by coderanger** [comment]
Why are you passing both though?

**Comment by bby-bishopclark** [comment]
One of them was in a config file, of course.  Sorry if that was somehow relevant, but it provokes nicely on the commandline with nothing set.

**Comment by coderanger** [comment]
Got it, that makes more sense :)
