### ISSUE TITLE
apt_repository resource generates bad source list files

### ISSUE THREAD

**Issue by Seb-Solon** [chef/chef#6524]
## Description

apt_repository resource will generate source list file as the following : 

```
deb      'uri' distribution components
```

The quotes around the uri are not necessary, apt will ignore them but not apt-file (binary use to search for file in packages). 
Apt-file will log an error : `W: Don't know how to handle "http`

See example of valid source lists : https://wiki.debian.org/SourcesList
See manpage of sources.list : https://manpages.debian.org/jessie/apt/sources.list.5.en.html

From what I have read, spaces (if this is the reason of such quotes) should be escaped with %20 or something like that

## Chef Version

Master : https://github.com/chef/chef/blob/master/lib/chef/provider/apt_repository.rb#L233

## Platform Version
Ubuntu / Debian as it is apt specific

## Replication Case

Create a simple cookbook doing an apt_repository. The example in the doc is good enough : https://docs.chef.io/resource_apt_repository.html

**Comment by Seb-Solon** [comment]
Any feedback on that? Is that legit for you guys? 

cc : @thommay @lamont-granquist  (as you worked on the related function)

**Comment by tas50** [comment]
This would be a good issue for someone to jump in on. It looks like we can just escape the URI and avoid the quoting.

**Comment by Seb-Solon** [comment]
Hi there, 

Note that apt-file binary won't complain about the double quote on "newer" version. It will still complain on single quote. So the bug could partially fix itself : https://github.com/chef/chef/blob/master/lib/chef/provider/apt_repository.rb#L325

The real failure would be having a uri with single quote.

Test I just made on my debian 9 :

```
$ cat /etc/apt/sources.list
[...]
deb "http://ftp.ca.debian.org/debian/" stretch-backports main contrib

$ sudo apt-file update
(no error)

---

cat /etc/apt/sources.list
[...]
deb 'http://ftp.ca.debian.org/debian/' stretch-backports main contrib

$ sudo apt-file update
E: The method driver /usr/lib/apt/methods/'http could not be found.
N: Is the package apt-transport-'http installed?
$ dpkg -l apt-file
ii  apt-file 3.1.4  all  search for files within Debian packages (command-line interface)

```
