### ISSUE TITLE
windows_path notifies even if value is not modified

### ISSUE THREAD

**Issue by sgtcoolguy** [chef/chef#6526]
## Description

I'm using `windows_path` to append binary folders to the PATH on windows. Under test-kitchen I need to reboot to have that reflect when I run tests against the PATH. So my windows_path resources use `notifies` to request a reboot at the end of the run. However, even if the PATH holds our expected directory, the `env` resource that `windows_path` defers to reports `up to date` but the `reboot` resource is notified.

## Chef Version

13.4.19

## Platform Version

Windows 10 Enterprise Edition virtual box VM (`gusztavvargadr/w10e 0.6.0` on vagrant)

## Replication Case

Tell us what steps to take to replicate your problem.  See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve)
for information on how to create a good replication case.

```
reboot 'env' do
  reason 'Going to reboot to finalise installation'
  action :nothing
end

windows_path 'C:\\Windows\\system32' do
  action :add
  notifies :request_reboot, 'reboot[env]', :immediately
end
```

## Chef-client output
In this example, I'm adding `C:\flex\bin` to the PATH, but it's already there from an easier run.

```
 * windows_path[C:\flex\bin] action add
           - Adding C:\flex\bin to path environment variable
           * env[path] action modify (up to date)
         
         * reboot[env] action request_reboot[2017-10-25T18:52:38+00:00] WARN: Reboot requested:'env'
       
           - request a system reboot to occur if the run succeeds

...

 Running handlers:
       Running handlers complete
       Chef Client finished, 10/51 resources updated in 11 seconds
       [2017-10-25T18:52:38+00:00] WARN: Rebooting server at a recipe's request. Details: {:delay_mins=>0, :reason=>"Going to reboot to finalise installation", :timestamp=>2017-10-25 18:52:38 +0000, :requested_by=>"env"}
       
       Running handlers:
       [2017-10-25T18:52:38+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2017-10-25T18:52:38+00:00] ERROR: Exception handlers complete
       Chef Client failed. 10 resources updated in 11 seconds
       [2017-10-25T18:52:38+00:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2017-10-25T18:52:38+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2017-10-25T18:52:38+00:00] FATAL: Chef::Exceptions::Reboot: Rebooting server at a recipe's request. Details: {:delay_mins=>0, :reason=>"Going to reboot to finalise installation", :timestamp=>2017-10-25 18:52:38 +0000, :requested_by=>"env"}
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <webkit-windows10ee>.  Please see .kitchen/logs/webkit-windows10ee.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by lamont-granquist** [comment]
@btm @NimishaS the converge_by here needs to be deleted:

https://github.com/chef/chef/blob/master/lib/chef/provider/windows_path.rb#L40

the env resource should probably be modified to better document what its doing using converge_by's there, the windows_path resource should just delegate that responsibility to the subresource:

```
 * windows_path[C:\flex\bin] action add
           * env[path] action modify (up to date)
                -  Adding C:\flex\bin to path environment variable
```

`converge_by` outputs logging as a side-effect of updating the resource and doing why-run stuff.  it shouldn't be used to try to output logging.  there's no real good way to output logging with the formatter for this kind of purpose, so its better to make the sub-resource output something more usefully descriptive.
