### ISSUE TITLE
`knife xxxx xxxx` CMD suddenly stops working

### ISSUE THREAD

**Issue by binlialfie** [chef/chef#6538]
## Description

All knife CMD suddenly stops working, such as `knife client list`, works all right before

## Chef Version

$ chef -v
Chef Development Kit Version: 2.3.4
chef-client version: 13.5.3
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.18.0
inspec version: 1.43.5

## Platform Version

$ rpm --query centos-release
centos-release-7-4.1708.el7.centos.x86_64

## Replication Case

run `knife xxxx xxx` CMD
I believe I saw some error related to fog at some stage.

## Client Output

$ knife client list
/opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require': cannot load such file -- knife-spork/version (LoadError)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /home/org-home/bin.li/.chefdk/gem/ruby/2.4.0/gems/knife-spork-1.7.0/lib/chef/knife/spork-version.rb:2:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:85:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:85:in `block in load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:85:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:85:in `load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:95:in `load_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife/core/subcommand_loader.rb:109:in `command_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife.rb:153:in `subcommand_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/knife.rb:214:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/lib/chef/application/knife.rb:156:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.4.19/bin/knife:25:in `<top (required)>'
	from /usr/bin/knife:267:in `load'
	from /usr/bin/knife:267:in `<main>'

## Chef Gem List

my gem list if helpful
 
$ chef gem list

*** LOCAL GEMS ***

activesupport (5.1.4, 4.2.9)
addressable (2.5.2)
app_conf (0.4.2)
appbundler (0.10.0)
artifactory (2.8.2)
ast (2.3.0)
autoparse (0.3.3)
aws-partitions (1.27.0)
aws-sdk (3.0.1, 2.10.73, 2.10.58, 2.10.53, 2.10.52, 2.10.50, 2.10.45, 2.10.40, 2.10.24)
aws-sdk-acm (1.0.0)
aws-sdk-apigateway (1.1.0)
aws-sdk-applicationautoscaling (1.3.0)
aws-sdk-applicationdiscoveryservice (1.0.0)
aws-sdk-appstream (1.2.0)
aws-sdk-athena (1.0.0)
aws-sdk-autoscaling (1.3.0)
aws-sdk-batch (1.1.0)
aws-sdk-budgets (1.2.0)
aws-sdk-clouddirectory (1.0.0)
aws-sdk-cloudformation (1.2.0)
aws-sdk-cloudfront (1.1.0)
aws-sdk-cloudhsm (1.3.0)
aws-sdk-cloudhsmv2 (1.0.0)
aws-sdk-cloudsearch (1.0.0)
aws-sdk-cloudsearchdomain (1.0.0)
aws-sdk-cloudtrail (1.0.0)
aws-sdk-cloudwatch (1.2.0)
aws-sdk-cloudwatchevents (1.1.0)
aws-sdk-cloudwatchlogs (1.2.0)
aws-sdk-codebuild (1.3.0)
aws-sdk-codecommit (1.1.0)
aws-sdk-codedeploy (1.0.0)
aws-sdk-codepipeline (1.1.0)
aws-sdk-codestar (1.1.0)
aws-sdk-cognitoidentity (1.0.0)
aws-sdk-cognitoidentityprovider (1.0.0)
aws-sdk-cognitosync (1.0.0)
aws-sdk-configservice (1.4.0)
aws-sdk-core (3.6.0, 2.10.73, 2.10.58, 2.10.53, 2.10.52, 2.10.50, 2.10.45, 2.10.40, 2.10.24)
aws-sdk-costandusagereportservice (1.0.0)
aws-sdk-databasemigrationservice (1.2.0)
aws-sdk-datapipeline (1.0.0)
aws-sdk-dax (1.0.0)
aws-sdk-devicefarm (1.2.0)
aws-sdk-directconnect (1.0.0)
aws-sdk-directoryservice (1.0.0)
aws-sdk-dynamodb (1.2.0)
aws-sdk-dynamodbstreams (1.0.0)
aws-sdk-ec2 (1.14.0)
aws-sdk-ecr (1.2.0)
aws-sdk-ecs (1.2.0)
aws-sdk-efs (1.0.0)
aws-sdk-elasticache (1.2.0)
aws-sdk-elasticbeanstalk (1.2.0)
aws-sdk-elasticloadbalancing (1.1.0)
aws-sdk-elasticloadbalancingv2 (1.4.0)
aws-sdk-elasticsearchservice (1.2.0)
aws-sdk-elastictranscoder (1.0.0)
aws-sdk-emr (1.0.0)
aws-sdk-firehose (1.0.0)
aws-sdk-gamelift (1.1.0)
aws-sdk-glacier (1.4.0)
aws-sdk-glue (1.1.0)
aws-sdk-greengrass (1.1.0)
aws-sdk-health (1.0.0)
aws-sdk-iam (1.3.0)
aws-sdk-importexport (1.0.0)
aws-sdk-inspector (1.1.0)
aws-sdk-iot (1.0.0)
aws-sdk-iotdataplane (1.0.0)
aws-sdk-kinesis (1.0.0)
aws-sdk-kinesisanalytics (1.1.0)
aws-sdk-kms (1.2.0)
aws-sdk-lambda (1.0.0)
aws-sdk-lambdapreview (1.0.0)
aws-sdk-lex (1.2.0)
aws-sdk-lexmodelbuildingservice (1.2.0)
aws-sdk-lightsail (1.1.0)
aws-sdk-machinelearning (1.0.0)
aws-sdk-marketplacecommerceanalytics (1.0.0)
aws-sdk-marketplaceentitlementservice (1.0.0)
aws-sdk-marketplacemetering (1.0.0)
aws-sdk-migrationhub (1.0.0)
aws-sdk-mobile (1.0.0)
aws-sdk-mturk (1.1.0)
aws-sdk-opsworks (1.1.0)
aws-sdk-opsworkscm (1.1.0)
aws-sdk-organizations (1.5.0)
aws-sdk-pinpoint (1.2.0)
aws-sdk-polly (1.3.0)
aws-sdk-rds (1.6.0)
aws-sdk-redshift (1.1.0)
aws-sdk-rekognition (1.0.0)
aws-sdk-resourcegroupstaggingapi (1.0.0)
aws-sdk-resources (3.1.0, 2.10.73, 2.10.58, 2.10.53, 2.10.52, 2.10.50, 2.10.45, 2.10.40, 2.10.24)
aws-sdk-route53 (1.3.0)
aws-sdk-route53domains (1.1.0)
aws-sdk-s3 (1.5.0)
aws-sdk-servicecatalog (1.1.0)
aws-sdk-ses (1.3.0)
aws-sdk-shield (1.0.0)
aws-sdk-simpledb (1.0.0)
aws-sdk-sms (1.0.0)
aws-sdk-snowball (1.1.0)
aws-sdk-sns (1.1.0)
aws-sdk-sqs (1.3.0)
aws-sdk-ssm (1.3.0)
aws-sdk-states (1.0.0)
aws-sdk-storagegateway (1.1.0)
aws-sdk-support (1.0.0)
aws-sdk-swf (1.0.0)
aws-sdk-v1 (1.67.0)
aws-sdk-waf (1.2.0)
aws-sdk-wafregional (1.2.0)
aws-sdk-workdocs (1.0.0)
aws-sdk-workspaces (1.0.0)
aws-sdk-xray (1.0.0)
aws-sigv2 (1.0.1)
aws-sigv4 (1.0.2)
backports (3.10.3)
berkshelf (6.3.1)
bigdecimal (default: 1.3.0)
binding_of_caller (0.7.3, 0.7.2)
blankslate (3.1.3, 2.1.2.4)
buff-config (2.0.0)
buff-extensions (2.0.0)
buff-ignore (1.2.0)
buff-ruby_engine (1.0.0)
buff-shell_out (1.1.0)
builder (3.2.3)
bundler (1.15.4, 1.15.1)
byebug (9.1.0)
celluloid (0.17.3, 0.16.0)
celluloid-essentials (0.20.5)
celluloid-extras (0.20.5)
celluloid-fsm (0.20.5)
celluloid-io (0.17.3, 0.16.2)
celluloid-pool (0.20.5)
celluloid-supervision (0.20.6)
CFPropertyList (2.3.5)
chef (13.5.3, 13.4.19)
chef-api (0.7.1)
chef-config (13.5.3, 13.4.19)
chef-dk (2.3.4)
chef-provisioning (2.5.0)
chef-provisioning-aws (2.2.2)
chef-provisioning-azure (0.6.0)
chef-provisioning-fog (0.26.0, 0.21.0)
chef-sugar (3.6.0, 3.5.0)
chef-vault (3.3.0)
chef-zero (13.1.0)
cheffish (13.1.0, 13.0.0)
chefspec (7.1.0)
chefstyle (0.6.0)
cleanroom (1.0.0)
coderay (1.1.2)
concurrent-ruby (1.0.5)
cookbook-omnifetch (0.6.0)
cookstyle (2.1.0)
cucumber (3.0.1, 2.4.0)
cucumber-core (3.0.0, 1.5.0)
cucumber-expressions (5.0.2, 4.0.4)
cucumber-tag_expressions (1.0.1)
cucumber-wire (0.0.1)
dbus-systemd (1.1.1)
dco (1.0.1)
debug_inspector (0.0.3)
declarative (0.0.10)
declarative-option (0.1.0)
dep-selector-libgecode (1.3.1)
dep_selector (1.0.6)
did_you_mean (1.1.2, 1.1.0)
diff-lcs (1.3)
diffy (3.2.0)
docker-api (1.33.6)
erubis (2.7.0)
excon (0.59.0)
extlib (0.9.16)
faraday (0.13.1)
fauxhai (5.4.0, 5.3.0)
ffi (1.9.18)
ffi-rzmq (2.0.5)
ffi-rzmq-core (1.0.6)
ffi-yajl (2.3.1)
fission (0.5.0)
fog (1.41.0)
fog-aliyun (0.2.0)
fog-atmos (0.1.0)
fog-aws (1.4.1)
fog-brightbox (0.13.0)
fog-cloudatcost (0.2.3, 0.1.2)
fog-core (1.45.0)
fog-digitalocean (0.3.0)
fog-dnsimple (1.0.0)
fog-dynect (0.2.0, 0.0.3)
fog-ecloud (0.3.0)
fog-google (0.6.0, 0.1.0)
fog-internet-archive (0.0.1)
fog-joyent (0.0.1)
fog-json (1.0.2)
fog-local (0.4.0)
fog-openstack (0.1.22, 0.1.21)
fog-powerdns (0.1.1)
fog-profitbricks (4.0.0)
fog-rackspace (0.1.5)
fog-radosgw (0.0.5)
fog-riakcs (0.1.0)
fog-sakuracloud (1.7.5)
fog-scaleway (0.3.0)
fog-serverlove (0.1.2)
fog-softlayer (1.1.4)
fog-storm_on_demand (0.1.1)
fog-terremark (0.1.0)
fog-vmfusion (0.1.0)
fog-voxel (0.1.0)
fog-vsphere (1.13.1, 1.12.0)
fog-xenserver (0.3.0)
fog-xml (0.1.3)
foodcritic (12.0.1, 11.4.0)
formatador (0.2.5)
fuzzyurl (0.9.0)
gherkin (5.0.0, 4.1.3)
git (1.3.0)
google-api-client (0.15.0, 0.8.7)
googleauth (0.6.1, 0.5.3)
gssapi (1.2.0)
guard (2.14.1)
gyoku (1.3.1)
hashie (3.5.6)
highline (1.7.8)
hitimes (1.2.6)
htmlentities (4.3.4)
httpclient (2.8.3)
i18n (0.9.0, 0.8.6)
inflecto (0.0.2)
inifile (3.0.0)
iniparse (1.4.4)
inspec (1.43.5, 1.36.1)
io-console (default: 0.4.6)
ipaddress (0.8.3)
iso8601 (0.9.1)
jmespath (1.3.1)
json (default: 2.0.4, 1.8.6)
jwt (2.1.0, 1.5.6)
kitchen-dokken (2.6.5)
kitchen-ec2 (1.3.2)
kitchen-hyperv (0.5.1)
kitchen-inspec (0.19.0)
kitchen-vagrant (1.2.1)
knife-acl (1.0.3)
knife-cfn (0.1.12)
knife-ec2 (0.15.0)
knife-elb (0.0.3)
knife-opc (0.3.2)
knife-push (1.0.3)
knife-spork (1.7.0, 1.6.3)
knife-windows (1.9.0)
launchy (2.4.3)
libyajl2 (1.2.0)
listen (3.1.5)
little-plugger (1.1.4)
lockfile (2.1.3)
logging (2.2.2)
logify (0.2.0)
lumberjack (1.0.12)
macaddr (1.7.1)
memoist (0.16.0)
method_source (0.9.0, 0.8.2)
mime-types (3.1)
mime-types-data (3.2016.0521)
mini_portile2 (2.3.0, 2.2.0)
minitar (0.6.1, 0.5.4)
minitest (5.10.3, 5.10.1)
mixlib-archive (0.4.1)
mixlib-authentication (1.4.2)
mixlib-cli (1.7.0)
mixlib-config (2.2.4)
mixlib-install (3.6.0, 2.1.12)
mixlib-log (1.7.1)
mixlib-shellout (2.3.2)
mixlib-versioning (1.2.2)
molinillo (0.6.3)
multi_json (1.12.2)
multi_test (0.1.2)
multipart-post (2.0.0)
nenv (0.3.0)
net-scp (1.2.1)
net-sftp (2.1.2)
net-ssh (4.2.0, 4.1.0)
net-ssh-gateway (2.0.0, 1.3.0)
net-ssh-multi (1.2.1)
net-telnet (0.1.1)
nio4r (2.1.0)
nokogiri (1.8.0)
nori (2.6.0)
notiffany (0.1.1)
octokit (4.7.0)
ohai (13.6.0, 13.4.0)
openssl (default: 2.0.5)
opscode-pushy-client (2.3.0)
os (1.0.0, 0.9.6)
paint (2.0.0, 1.0.1)
parallel (1.12.0)
parser (2.4.0.0)
parslet (1.8.0, 1.5.0)
plist (3.3.0)
polyglot (0.3.5)
power_assert (1.1.1, 0.4.1)
powerpack (0.1.1)
proxifier (1.0.3)
pry (0.11.2, 0.10.4)
pry-byebug (3.5.0)
pry-remote (0.1.8)
pry-stack_explorer (0.4.9.2)
psych (default: 2.2.2)
public_suffix (3.0.0)
rack (2.0.3)
rainbow (2.2.2)
rake (12.2.1, 12.1.0, 12.0.0)
rb-fsevent (0.10.2)
rb-inotify (0.9.10)
rb-readline (0.5.5)
rbvmomi (1.11.3)
rdoc (5.1.0, default: 5.0.0)
representable (3.0.4)
retriable (3.1.1, 1.4.1)
retryable (2.0.4)
ridley (5.1.1)
rspec (3.7.0, 3.6.0)
rspec-core (3.7.0, 3.6.0)
rspec-expectations (3.7.0, 3.6.0)
rspec-its (1.2.0)
rspec-mocks (3.7.0, 3.6.0)
rspec-support (3.7.0, 3.6.0)
rspec_junit_formatter (0.3.0, 0.2.3)
rubocop (0.51.0, 0.49.1)
ruby-dbus (0.14.0, 0.13.0)
ruby-prof (0.16.2)
ruby-progressbar (1.9.0, 1.8.3)
ruby-shadow (2.5.0)
ruby_dep (1.5.0)
rubygems-update (2.6.14, 2.6.13, 2.6.12)
rubyntlm (0.6.2)
rubyzip (1.2.1)
rufus-lru (1.1.0)
safe_yaml (1.0.4)
sawyer (0.8.1)
semverse (2.0.0)
serverspec (2.41.2, 2.40.0)
sfl (2.3)
shellany (0.0.1)
signet (0.8.1, 0.7.3)
slop (4.6.0, 3.6.0)
solve (4.0.0)
specinfra (2.72.0, 2.71.2)
sslshake (1.2.0)
stove (6.0.0)
stuartpreston-azure-sdk-for-ruby (0.7.2)
syslog-logger (1.6.8)
systemu (2.6.5)
test-kitchen (1.18.0, 1.17.0)
test-unit (3.2.6, 3.2.3)
thor (0.20.0, 0.19.1)
thread_safe (0.3.6)
timers (4.1.2, 4.0.4)
toml (0.1.2)
train (0.28.0, 0.26.2)
treetop (1.6.8)
trollop (2.1.2)
tzinfo (1.2.4, 1.2.3)
uber (0.1.0)
ubuntu_ami (0.4.1)
unicode-display_width (1.3.0)
uuid (2.3.8)
uuidtools (2.1.5)
varia_model (0.6.0)
winrm (2.2.3)
winrm-elevated (1.1.0)
winrm-fs (1.1.0, 1.0.2, 1.0.1)
wmi-lite (1.0.0)
xml-simple (1.1.5)
xmlrpc (0.3.0, 0.2.1)
yard (0.9.9)

**Comment by thommay** [comment]
It looks as though you've tried to install different versions into your ChefDK, which is not supported. Please delete your ~/.chefdk directory and try again.

**Comment by binlialfie** [comment]
Spot on,  thanks for the fast respond. 

deleted ~/.chefdk and running knife CMD all works fine.

btw, how can you tell that I am trying to install different ChefDK version??

**Comment by thommay** [comment]
it's in the stacktrace:
`from /home/org-home/bin.li/.chefdk/gem/ruby/2.4.0/gems/knife-spork-1.7.0/lib/chef/knife/spork-version.rb:2:in<top (required)>'`

And you have too many versions of some gems installed. Closing this now.
