### ISSUE TITLE
INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/data/ssl/self-signed

### ISSUE THREAD

**Issue by dev31000** [chef/chef#6539]
## Description
Running vagrant up I get the following error:
`INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/data/ssl/self-signed`
`ERROR: Failed to load data bag item: "ssl" "self-signed"`

## Chef Version
chef -v   
Chef Development Kit Version: 2.3.4
chef-client version: 13.4.19
delivery version: master
berks version: 6.3.1
kitchen version: 1.17.0
inspec version: 1.36.1

## Platform Version
omnibus.chef_version = '12.16.42'
Vagrant + VBox
macOS Sierra

## Stacktrace

==> cemnode:     
==> cemnode: - install version 0.9.4 of package curb
==> cemnode: 
==> cemnode: 
==> cemnode: [2017-10-27T20:32:00+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/data/ssl/self-signed
==> cemnode: [2017-10-27T20:32:00+00:00] ERROR: Failed to load data bag item: "ssl" "self-signed"
==> cemnode:   
==> cemnode: 
==> cemnode:   
==> cemnode: ================================================================================
==> cemnode:   
==> cemnode: Recipe Compile Error in /var/chef/cache/cookbooks/ben-onl/recipes/default.rb
==> cemnode:   
==> cemnode: ================================================================================
==> cemnode:   
==> cemnode: 
==> cemnode: 
==> cemnode:   
==> cemnode: Net::HTTPServerException
==> cemnode:   
==> cemnode: ------------------------
==> cemnode:   404 "Not Found"
==> cemnode:   
==> cemnode:   Cookbook Trace:
==> cemnode:   ---------------
==> cemnode:     /var/chef/cache/cookbooks/dx-bas/recipes/ssl.rb:14:in `from_file'
==> cemnode:     /var/chef/cache/cookbooks/dx-ben/recipes/dispatcher.rb:12:in `from_file'
==> cemnode:     /var/chef/cache/cookbooks/ben-onl/recipes/default.rb:12:in `from_file'
==> cemnode:   
==> cemnode:   Relevant File Content:
==> cemnode:   ----------------------
==> cemnode:   /var/chef/cache/cookbooks/dx-bas/recipes/ssl.rb:
==> cemnode:   
==> cemnode:    10:  if File.readable?('/etc/chef/encrypted_data_bag_secret')
==> cemnode:    11:    secret = Chef::EncryptedDataBagItem.load_secret('/etc/chef/encrypted_data_bag_secret')
==> cemnode:    12:    ssl = Chef::EncryptedDataBagItem.load(node['dx-bas']['ssl']['databag'], node['dx-bas']['ssl']['databag_entry'], secret)
==> cemnode:    13:  else
==> cemnode:    14>>   ssl = data_bag_item('ssl', 'self-signed')
==> cemnode:    15:  end
==> cemnode:    16:  
==> cemnode:    17:  directory node['dx-bas']['ssl']['cert_dir'] do
==> cemnode:    18:    owner 'root'
==> cemnode:    19:    group 'root'
==> cemnode:    20:    recursive true
==> cemnode:    21:    mode 0755
==> cemnode:    22:  end
==> cemnode:    23:  
==> cemnode:   
==> cemnode:   Platform:
==> cemnode:   ---------
==> cemnode:   x86_64-linux
==> cemnode:   
==> cemnode:   
==> cemnode:   Running handlers:
==> cemnode: [2017-10-27T20:32:00+00:00] ERROR: Running exception handlers
==> cemnode:   Running handlers complete
==> cemnode: [2017-10-27T20:32:00+00:00] ERROR: Exception handlers complete
==> cemnode:   Chef Client failed. 3 resources updated in 01 minutes 03 seconds
==> cemnode: [2017-10-27T20:32:00+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> cemnode: [2017-10-27T20:32:00+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> cemnode: [2017-10-27T20:32:00+00:00] ERROR: 404 "Not Found"
==> cemnode: [2017-10-27T20:32:00+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. You appear to be missing a data bag item.

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
