### ISSUE TITLE
Windows 2012r2 env / windows_path not propagated

### ISSUE THREAD

**Issue by k-brooks** [chef/chef#6545]
## Description

I've noticed two issues relevant to windows environment variables

1. When setting environment variables using the env resource, they are not propagated beyond the registry. This means that they are unavailable to subsequent processes.
2. Environment variables are expanded upon inclusion in the path variable. This means their values are now static.

## Chef Version

Client versions 13.4.24-1, 13.6.0-1
Server version 12.16.14-1

## Platform Version

Windows Server 2012r2

## Replication Case

1. Create a recipe which contains and env resource and a windows_path resource. The windows_path resource should reference the prior env resource name in variable form, for example

`env 'ANT_HOME' do
  value 'c:\\ant'
end

env 'ANT_OPTS' do
  value '-Xms256m -Xmx2048m'
end

windows_path "%ANT_HOME%\\bin" do
  action :add
end`

2. Converge
3. Open a command window, display all environment variables (set command) - note the missing ANT_HOME, ANT_OPTS, and PATH additions
4. Open the Environment Variables dialog - note the ANT_HOME, ANT_OPTS, and PATH values, including the expanded ANT_HOME value ***PRESSING OK will propagate***

**Comment by k-brooks** [comment]
After some investigation, this looks to be a long-standing issue
https://github.com/chef-cookbooks/windows/issues/111

After some experimentation, this looks to be a limitation within winrm
https://stackoverflow.com/questions/22094727/must-reboot-after-changing-path

I attempted setx via winrm and it resulted in the same behavior.

**Comment by k-brooks** [comment]
That will only work when running tests - real world is still broken.

**Comment by stuartpreston** [comment]
@k-brooks Chef Client does not run directly over WinRM connections in the normal case - in normal operation it runs scheduled on a machine, so can you clarify your concern here? Thanks.

**Comment by tas50** [comment]
Closing this since we never heard back from the user
