### ISSUE TITLE
Lazy evaluate properties in resources by default

### ISSUE THREAD

**Issue by tas50** [chef/chef#6548]
An issues I've seen come up multiple times in resources is setting the default value for a resource to a node attribute, and then becoming confused when it doesn't behave exactly like you would expect. It seems to be a pretty common thing that people want to do, but they get confused when they override the attribute somewhere and it doesn't become the default in the resource. Currently the solution is to lazy the property default value, but it seems like we could just do this by default for all properties and avoid this stumbling block to writing resources entirely.

**Comment by coderanger** [comment]
We can’t do it at the property leve without every value being wrapped in a block, but we could in theory change things to not evaluate the resource body block itself until later. I suspect that would break a bajillion things though.

**Comment by coderanger** [comment]
This is probably best turfed to the rfc repo unless someone has a concrete idea.
