### ISSUE TITLE
knife upload should exit with non-zero if error

### ISSUE THREAD

**Issue by akuzminsky** [chef/chef#6551]
# Description

If `knife cookbook upload` fails to upload a cookbook it should exit with non-zero.
Current version exits with zero which is misleading if used in a travis -ci job.

# ChefDK Version

13.4.19

# Platform Version

Ubuntu

# Stacktrace

A log from a "successful" job https://travis-ci.com/twindb/chef-repo/builds/57256001

```
$ knife cookbook upload --include-dependencies --force jumphost

ERROR: Could not find cookbook jumphost in your cookbook path, skipping it

WARN: Failed to read the private key /home/travis/build/twindb/chef-repo/.chef/mkryva.pem: #<Errno::ENOENT: No such file or directory @ rb_sysopen - /home/travis/build/twindb/chef-repo/.chef/mkryva.pem>

ERROR: Your private key could not be loaded from /home/travis/build/twindb/chef-repo/.chef/mkryva.pem

Check your configuration file and ensure that your private key is readable

after_success.2

0.60s$ knife cookbook upload --include-dependencies --force website_database

ERROR: Could not find cookbook website_database in your cookbook path, skipping it

WARN: Failed to read the private key /home/travis/build/twindb/chef-repo/.chef/mkryva.pem: #<Errno::ENOENT: No such file or directory @ rb_sysopen - /home/travis/build/twindb/chef-repo/.chef/mkryva.pem>

ERROR: Your private key could not be loaded from /home/travis/build/twindb/chef-repo/.chef/mkryva.pem

Check your configuration file and ensure that your private key is readable

after_success.3

0.61s$ knife cookbook upload --include-dependencies --force web_app

ERROR: Could not find cookbook web_app in your cookbook path, skipping it

WARN: Failed to read the private key /home/travis/build/twindb/chef-repo/.chef/mkryva.pem: #<Errno::ENOENT: No such file or directory @ rb_sysopen - /home/travis/build/twindb/chef-repo/.chef/mkryva.pem>

ERROR: Your private key could not be loaded from /home/travis/build/twindb/chef-repo/.chef/mkryva.pem

Check your configuration file and ensure that your private key is readable

```

**Comment by dee3sync** [comment]
We are experiencing the same issue on the windows platform.  Knife is returning an exit code of 0 when an error occurs.
![lec](https://user-images.githubusercontent.com/14794837/35229161-51e62426-ff58-11e7-960f-8c0d21141884.jpg)

**Comment by omacneil** [comment]
vagrant@chefworkstation01:~/cldev$ knife --version
Chef: 13.8.5

vagrant@chefworkstation01:~/cldev$ knife cookbook upload --all ;  echo ; echo '$? is' $?
WARNING: Could not find any cookbooks in your cookbook path: /home/vagrant/cldev/.chef../cookbooks. Use --cookbook-path to specify the desired path.

$? is 0

**Comment by tas50** [comment]
Putting this in our sustaining backlog. The issue may still be present in the `knife supermarket upload` command and we'll want to repro it and resolve it.
