### ISSUE TITLE
knife bootstrap with an option should avoid duplicate nodes with same IP

### ISSUE THREAD

**Issue by thechefcookbookie** [chef/chef#6561]
## Description

This is an enhancement request.

In our environment, currently we are facing the issue of duplicate nodes on the Chef server with them being bootstrapped multiple times with a different name and accidentally overlooking the need to delete the existing node and client objects. This problem is calling for a periodical audit of the duplicate nodes and their subsequent cleanup for an efficient node license management. As this problem would affect the node license management and as we don't have the necessity of having multiple nodes with the same IP on the Chef server, I am looking for an option in the "Knife bootstrap" command which while added to it would prevent the bootstrapping of the same server (IP) with a different name if a node with the same IP already exists on the Chef server.

For example: precisely, a command like:

knife bootstrap <IP> -N <node_name> -x <user> -P <password> **-U**

should fail if a node already exists with the same "IP" on the Chef server and should throw an error "A node already exists with the given IP".

Having an additional option wouldn't hurt the functionality of the "knife bootstrap" command and would allow it to use those who are in need to avoid the duplicate nodes on Chef server.

**Comment by coderanger** [comment]
Chef Server doesn't know anything about the node's IP (except as reported by Ohai way later on in the process). The de-duplication is on the node's name, which we usually recommend be the node's FQDN. If you are re-boostrapping nodes with new names the solution is to stop doing that (or write some cleanup scripts for the old names) :)

**Comment by thechefcookbookie** [comment]
Got you. I completely agree with your point of coming up with a script to cleanup. In fact we already have one. And on eliminating this issue, we do instruct users to bootstrap with FQDN as node name but still, you know the difficulty of getting things done as per the guidelines given the large workforce (users). Rather than being reactive, I want to be proactive and accordingly, I am looking for a solution/option from the Chef side which would stop from this happening. So, is there a way to reinforce the node_name to be fqdn while bootstrapping and throw an exception if not?

**Comment by coderanger** [comment]
No, that is not possible nor will it be, in fact we're working on better support for cases where that is not true like network device management. The correct fix here is client side, if you want to enforce you could make your own knife plugin or just a script to handle bootstrapping new nodes to reduce human error.

**Comment by cheeseplus** [comment]
As described, this isn't really a problem chef can or should be tackling that can't be done with custom bootstrap templates or a changing the bootstrap process itself. Closing.
