### ISSUE TITLE
"knife client create" will not work

### ISSUE THREAD

**Issue by Leonard72** [chef/chef#6566]
## Description

"knife client create" command will not work.

## Chef Version

13.06

## Platform Version

Ubuntu 16.04.2 LTS

## Replication Case

Run this command: "knife client create hostnameOfChefClient" and the problem will happen 100% of the time.

## Client Output

Here are two outputs:

ubuntu@chefserverhostname:~/.chef$ knife client create chefclienthostname
ERROR: You authenticated successfully to https://chefserverhostname/organizations/companynickname as chefserverhostname but you are not authorized for this action
Response:  missing update permission

ubuntu@chefserverhostname:~/.chef$ knife client create chefserverhostname
ERROR: knife encountered an unexpected error
This may be a bug in the 'client create' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `[]' for #<Chef::ApiClient:0x00000003afe058>

## Stacktrace

ubuntu@chefserverhostname:~/.chef$ knife client create chefserverhostname -VV
INFO: Using configuration from /home/ubuntu/.chef/knife.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as chefserverhostname
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating PUT to https://chefserverhostname/organizations/companynickname/clients/chefserverhostname
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Content-Type: application/json
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.0;
DEBUG: X-OPS-USERID: chefserverhostname
DEBUG: X-OPS-TIMESTAMP: 2017-11-05T18:23:02Z
DEBUG: X-OPS-CONTENT-HASH: cg4WVP2L9A4gdWpCjYlIQ2HuIoY=
DEBUG: X-OPS-AUTHORIZATION-1: P7DR70FAm//JOO3kG+LiBFTNCyktObupht6W9S0Duh4n2OhyTE5T7mHC6DSd
DEBUG: X-OPS-AUTHORIZATION-2: +ivn7Ldj+7NhKuVEZ7sfio69ledNGoCZW7P1ktoVQiY7gkjE4kBS4l4VEk/o
DEBUG: X-OPS-AUTHORIZATION-3: zeDufp47mu8+NdJyW/4gd7SeWongg8UWR5Qo4JU0gvfSkfFSmFyJU6iRT7We
DEBUG: X-OPS-AUTHORIZATION-4: BYzZFF1K5lhQ/T7wdvOULvlF0EKOjEutKvNVggCn8SRxKygl5/KpusFEPzuQ
DEBUG: X-OPS-AUTHORIZATION-5: i35BnqjHxp+TpE4RN0O4XpZHVtlWb11FhDjWrlgOEN+xqNFtSGSYQtq2thrW
DEBUG: X-OPS-AUTHORIZATION-6: K4aS4cC8bCrkzn+Nf6iCctcjRxE4l963P42pQLs9Hg==
DEBUG: HOST: chefserverhostname:443
DEBUG: X-REMOTE-REQUEST-ID: b25a4b55-12ac-4afd-be7c-d469a1b3255f
DEBUG: Content-Length: 86
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: server: openresty/1.11.2.1
DEBUG: date: Sun, 05 Nov 2017 18:23:02 GMT
DEBUG: content-type: application/json
DEBUG: transfer-encoding: chunked
DEBUG: connection: close
DEBUG: x-ops-server-api-version: {"min_version":"0","max_version":"1","request_version":"0","response_version":"0"}
DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=12.16.15+20171003194757
DEBUG: content-encoding: gzip
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: HTTP server did not include a Content-Length header in response, cannot identify truncated downloads.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
/usr/lib/ruby/vendor_ruby/chef/knife/client_create.rb:70:in `run': undefined method `[]' for #<Chef::ApiClient:0x00000003c77a38> (NoMethodError)
        from /usr/lib/ruby/vendor_ruby/chef/knife.rb:422:in `block in run_with_pretty_exceptions'
        from /usr/lib/ruby/vendor_ruby/chef/local_mode.rb:39:in `with_server_connectivity'
        from /usr/lib/ruby/vendor_ruby/chef/knife.rb:421:in `run_with_pretty_exceptions'
        from /usr/lib/ruby/vendor_ruby/chef/knife.rb:214:in `run'
        from /usr/lib/ruby/vendor_ruby/chef/application/knife.rb:142:in `run'
        from /usr/bin/knife:25:in `<main>'

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
