### ISSUE TITLE
windows_task error invalid date with frequency :on_logon

### ISSUE THREAD

**Issue by ingoplath** [chef/chef#6569]
## Description

We use windows_task to create a periodic chef run resource, the settings of this task will be checked/updated at each chef run. We use :on_logon for the frequency option. The first run will succesfully create the task. After a reboot the error "invalid date" comes up for the action create.

## Chef Version

Tryed with version 13.4.24, 13.5.3 and 13.6.0

## Platform Version

Windows 7 embedded

## Client Output
[2017-11-06T09:02:15+00:00] INFO: *** Chef 13.6.0 ***
[2017-11-06T09:02:15+00:00] INFO: Platform: x64-mingw32
[2017-11-06T09:02:15+00:00] INFO: Chef-client pid: 2876
[2017-11-06T09:02:19+00:00] INFO: Run List is 
[2017-11-06T09:02:19+00:00] INFO: Run List expands to 
[2017-11-06T09:02:19+00:00] INFO: Starting Chef Run for 
[2017-11-06T09:02:19+00:00] INFO: Running start handlers
[2017-11-06T09:02:19+00:00] WARN: Handler Chef::Handler::StartHandler executed
[2017-11-06T09:02:19+00:00] INFO: Start handlers complete.
Installing Cookbook Gems:
Compiling Cookbooks...
Recipe: PC::base
Recipe: PC::periodicChefRun
PC_chefClientReRunXml[enable chef-client rerun] action enable
template[/tmp/chef-solo/chefClientReRun.xml] action create[2017-11-06T09:02:31+00:00] INFO: template[/tmp/chef-solo/chefClientReRun.xml] created file /tmp/chef-solo/chefClientReRun.xml
create new file /tmp/chef-solo/chefClientReRun.xml[2017-11-06T09:02:31+00:00] INFO: template[/tmp/chef-solo/chefClientReRun.xml] updated file contents /tmp/chef-solo/chefClientReRun.xml
update content in file /tmp/chef-solo/chefClientReRun.xml from none to 98974c
 /tmp/chef-solo/chefClientReRun.xml    2017-11-06 09:02:31.000000000 +0000
/tmp/chef-solo/chef-chefClientReRun20171106-2876-comfkr.xml   2017-11-06 09:02:31.000000000 +0000
 windows_task[create chef client] action create
    ================================================================
      Error executing action `create` on resource 'windows_task[create chef client]'
      ================================================================
      ArgumentError
      -------------
      invalid date

      Resource Declaration:
      ---------------------
      # In C:/vagrant/cookbooks/PoliscanPC/resources/chefClientReRunXml.rb

       44:   windows_task "#{actionFlag} chef client" do
       45:     task_name 'Chef'
       46:     user new_resource.userAccount
       47:     password passwd
       48:     cwd basePath
       49:     command "#{basePath}/batch/runChefSolo.cmd #{new_resource.recipe}"
       50:     run_level :highest
       51:     frequency :on_logon
       52:     frequency_modifier 1
       53:     action actionFlag
       54:     notifies :run, "execute[#{executeCommandName}]", :immediately
       55:   end
       56:

      Compiled Resource:
      ------------------
      # Declared in C:/vagrant/cookbooks/PoliscanPC/resources/chefClientReRunXml.rb:44:in `block in class_from_file'

      windows_task("create chef client") do
        action [:create]
        default_guard_interpreter :default
        task_name "Chef"
        declared_type :windows_task
        cookbook_name :PoliscanPC
        execution_time_limit "PT72H"
        use_password true
        user ""
        password ""
        cwd "C:/vagrant"
        command "C:/vagrant/batch/runChefSolo.cmd"
        run_level :highest
        frequency :on_logon
        frequency_modifier 1
        start_time "N/A"
        start_day "N/A"
      end

      System Info:
      ------------
      chef_version=13.6.0
      platform=windows
      platform_version=6.1.7601
      ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x64-mingw32]
      program_name=c:/opscode/chef/bin/chef-solo
      executable=c:/opscode/chef/bin/chef-solo

## Stacktrace
[chef-stacktrace.txt](https://github.com/chef/chef/files/1445620/chef-stacktrace.txt)

**Comment by NimishaS** [comment]
@ingoplath , can you please confirm your system date format? Is it set to something else than `mm/dd/yyyy`?

**Comment by ingoplath** [comment]
@NimishaS 
The Date Settings in the System are German Settings dd.MM.yyyy

**Comment by NimishaS** [comment]
@ingoplath , this is a known issue and is resolved in https://github.com/chef/chef/pull/6544.

**Comment by NimishaS** [comment]
Here's another similar issue: https://github.com/chef/chef/issues/6480. @ingoplath , we'll close this issue and keep https://github.com/chef/chef/issues/6480 open for tracking till the PR is not merged.
