### ISSUE TITLE
Kitchen test is failing for s390x arch having suse-12

### ISSUE THREAD

**Issue by ashoka856** [chef/chef#6579]
## Description

Kitchen testing is failing when it is trying to install chef version 12.12.13 on EP, saying it is not supported

## Chef Version

12.12.13

## Platform Version

S390x arch having suse12
## Replication Case

configure kitchen for ssh and try to run kitchen test , will see following logs
kitchen converge default-s390x
-----> Starting Kitchen (v1.10.2)
-----> Converging <default-s390x>...
$$$$$$ Running legacy converge for 'Ssh' Driver
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.3.5...
       Removing non-cookbook files before transfer
       Preparing solo.rb
-----> Installing Chef Omnibus (12.12.13)
       Downloading https://omnitruck.chef.io/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       sles 12 s390x
       Getting information for chef stable 12.12.13 for sles...
       downloading https://omnitruck.chef.io/stable/chef/metadata?v=12.12.13&p=sles&pv=12&m=s390x
         to file /tmp/install.sh.26627/metadata.txt
       trying wget...
       ERROR 404
       Omnitruck artifact does not exist for version 12.12.13 on platform sles

       Either this means:
          - We do not support sles
          - We do not have an artifact for 12.12.13

       This is often the latter case due to running a prerelease or RC version of chef
       or a gem version which was only pushed to rubygems and not omnitruck.

       You may be able to set your knife[:bootstrap_version] to the most recent stable
       release of Chef to fix this problem (or the most recent stable major version number).

       In order to test the version parameter, adventurous users may take the Metadata URL
       below and modify the '&v=<number>' parameter until you successfully get a URL that
       does not 404 (e.g. via curl or wget).  You should be able to use '&v=11' or '&v=12'
       succesfully.

       If you cannot fix this problem by setting the bootstrap_version, it probably means
       that sles is not supported.

       Metadata URL: https://omnitruck.chef.io/stable/chef/metadata?v=12.12.13&p=sles&pv=12&m=s390x
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-s390x>.  Please see .kitchen/logs/default-s390x.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

## Client Output

Omnibus chef installation failure
## Stacktrace

Please include the stacktrace.out output or link to a gist of it, if there is one.

### NOTE: CHEF CLIENT BUGS ONLY

This issue tracker is for the code contained within this repo -- `chef-client`, base `knife` functionality (not
plugins), `chef-apply`, `chef-solo`, `chef-client -z`, etc.

* Requests for new or alternative functionality should be made to [feedback.chef.io](https://feedback.chef.io/forums/301644-chef-product-feedback/category/110832-chef-client)
* [Chef Server issues](https://github.com/chef/chef-server/issues/new)
* [ChefDK issues](https://github.com/chef/chef-dk/issues/new)
* Cookbook Issues (see the https://github.com/chef-cookbooks repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by thommay** [comment]
That's correct, we only introduced SLES-12 support relatively late in the 12 lifecycle, and we'd strongly recommend that you use chef client 13.

**Comment by ashoka856** [comment]
Thanks Thommay,
So in chef-client 13 supports, omnibus installation for sles 12 with s390x architecture? is my understanding is correct from your comment?

**Comment by thommay** [comment]
yes, that's correct.
