### ISSUE TITLE
`file` resource doesn't :delete list of files

### ISSUE THREAD

**Issue by shatil** [chef/chef#6601]
## Description

Declaring a `file` resource with a list of files as input doesn't result in `action` actually applying.

```chef
file %w(/etc/supervisord.conf /etc/init.d/supervisor) do                                                                                                                             
    action :delete
end
```

Running `chef-client`:

```
  * file[/etc/supervisord.conf, /etc/init.d/supervisor] action delete (up to date)
```

But afterward, the files are still present:

```bash
$ ls /etc/init.d/supervisor 
/etc/init.d/supervisor
```

_Declaring each file separately does perform the desired `action`._

## Chef Version

`12.21.26`

## Platform Version

Ubuntu Linux 14.04 ("Trusty")

## Replication Case

Create two files:

```bash
touch /tmp/first /tmp/second
```

Then declare a Chef resource to delete them both (saving to `/tmp/recipe.rb`):

```chef
file %w(/tmp/first /tmp/second) do
    action :delete
end
```

And run `chef-client -z /tmp/recipe.rb`

**Comment by coderanger** [comment]
Yes, the only core resource that supports array-ish behavior is packages, and that's because there is substantial overhead to doing multiple package operations individually, which is not the case with files. This doesn't seem common enough to warrant dedicated syntax, so use a loop:

```ruby
%w(/tmp/first /tmp/second).each do |path|
  file path do
    action :delete
  end
end
```
