### ISSUE TITLE
Regression in Chef 13.1.x when reading `-j dna.json` from command line with spurious FATAL

### ISSUE THREAD

**Issue by stevie911** [chef/chef#6613]
## Description

chef-cleint will exit out with en error when trying to read json file or json from stdin. It honors the attribute set but exits out with an error and status code 1. This makes it look like the chef-client run errored when infact it didn't.

## Chef Version

13.6.4

## Platform Version

RHEL6 RHEL7

## Replication Case

echo '{"attr":"value"}' | chef-client -j /dev/stdin

or chef-client -j test.json

With test.json like
```{ "attr": "value"}```

## Client Output
```
echo '{"attr":"value"}' | chef-client -j /dev/stdin
Starting Chef Client, version 13.6.4
Chef Client finished, 0/15 resources updated in 03 minutes 08 seconds
FATAL: Could not parse the provided JSON file (/dev/stdin): Top level JSON object must be a Hash or Array. (actual: NilClass)
FATAL: Could not parse the provided JSON file (/dev/stdin): Top level JSON object must be a Hash or Array. (actual: NilClass)
```

**Comment by lamont-granquist** [comment]
using `--no-fork` appears to avoid this issue.  its related to having the daemon process trying to re-read the json file, which fails on /dev/stdin after its already been parsed.

there's a meta-issue here that we should probably run in `--no-fork` by default from the command line (which i think there's an old issue i cut for that a long time ago, but in isolation this use case isn't really compelling enough to warrant bumping the priority of that one.

**Comment by stevie911** [comment]
this also is an error if we are using a local file. If using a local file would the daemon process not be able to re-read the file and not error.

**Comment by lamont-granquist** [comment]
the local file works, because you can reopen and reread all the contents.  if you reopen /dev/stdin the contents have been read so you get "" instead (which turns into NilClass).  /dev/stdin is a magical file that changes its contents all the time.

**Comment by stevie911** [comment]
No i am saying i get the same error using a local file.

**Comment by lamont-granquist** [comment]
ah that's different then

stacktrace:

```
/Users/lamont/oc/chef/lib/chef/config_fetcher.rb:47:in `read_local_config'
/Users/lamont/oc/chef/lib/chef/config_fetcher.rb:36:in `read_config'
/Users/lamont/oc/chef/lib/chef/config_fetcher.rb:24:in `fetch_json'
/Users/lamont/oc/chef/lib/chef/application/client.rb:369:in `reconfigure'
/Users/lamont/oc/chef/lib/chef/application/client.rb:471:in `sleep_then_run_chef_client'
/Users/lamont/oc/chef/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
/Users/lamont/oc/chef/lib/chef/application/client.rb:457:in `loop'
/Users/lamont/oc/chef/lib/chef/application/client.rb:457:in `interval_run_chef_client'
/Users/lamont/oc/chef/lib/chef/application/client.rb:441:in `run_application'
/Users/lamont/oc/chef/lib/chef/application.rb:59:in `run'
/Users/lamont/oc/chef/bin/chef-client:26:in `<top (required)>'
/Users/lamont/.rvm/gems/ruby-2.4.1/bin/chef-client:23:in `load'
/Users/lamont/.rvm/gems/ruby-2.4.1/bin/chef-client:23:in `<main>'
/Users/lamont/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/lamont/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by lamont-granquist** [comment]
@btm i think this broke in #6122 -- at least if i rewind to before that was merged it works correctly so it broke at or after that, and the stacktrace is relevant

**Comment by vladuemilian** [comment]
--no-fork worked for me! Chef: 13.6.4

**Comment by lamont-granquist** [comment]
Since we need to reconfigure when running in the loop, and we run --no-fork by default now, I'm considering this fixed.
