### ISSUE TITLE
windows_task: break sec_to_duration logic into a mixin

### ISSUE THREAD

**Issue by tas50** [chef/chef#6623]
Windows loves ISO8601. We should move this into a mixin so we can use it elsewhere and so that authors can use it in their cookbooks. There's no reason to confine this code to just the windows_task resource.

**Comment by dheerajd-msys** [comment]
Thanks @tas50 , Updated the code as per your comments.

**Comment by dheerajd-msys** [comment]
@tas50 Please close this issue as this is no longer required. Thanks.
