### ISSUE TITLE
windows_task: Allow dates to be entered in the system's native format

### ISSUE THREAD

**Issue by tas50** [chef/chef#6640]
We shouldn't force the world to use the US date format (MM/DD/YYYY) when most people use a different format (many actually). Instead we should investigate what it would take to determine the system's date format and just do the right thing. This is obviously a breaking change and something we'd want to do for Chef 14.

**Comment by spuder** [comment]
This might be a windows limitation. Looking at Schtasks.exe documentation

>/SD startdate
A value that specifies the first date on which to run the task. The format is mm/dd/yyyy. This value defaults to the current date. This is not applicable for the following schedule types: ONCE, ONSTART, ONLOGON, ONIDLE, and ONEVENT.

https://msdn.microsoft.com/en-us/library/windows/desktop/bb736357(v=vs.85).aspx

**Comment by tas50** [comment]
This most likely goes together with moving towards direct XML manipulation. The current date format mess is 100% a limitation imposed by the current CLI based approach

**Comment by tas50** [comment]
After discussing this further I think this is probably the wrong thing to do. We'd always be guessing and that magic is more likely to hurt customers than help them. We'd also end up in the really nasty situation where a cookbook could not be used on systems with different date formats. For instance a community cookbook written for en-us systems would not run properly on a en-gb system. Forcing people to use the weird US date format is a pain, but I think it's better than the alternative.
