### ISSUE TITLE
windows_env resource fails to create an environment variable when not using a literal to define its value

### ISSUE THREAD

**Issue by mascarua** [chef/chef#6662]
## Description

The env resource is not creating an environment variable if its value is defined using string interpolation.

## Chef Version

- Chef Development Kit Version 2.4.17
- chef-client version: 13.6.14
- delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
- berks version: 6.3.1
- kitchen version: 1.19.2
- inspec version: 1.45.13

## Platform Version

Windows 10

## Replication Case

Please see the attached cookbook; the README.md file contains a description to replicate the problem.
[SimpleCookbook.zip](https://github.com/chef/chef/files/1553717/SimpleCookbook.zip)

## Client Output

None so far; the result is observed in the results of the application above.

## Stacktrace

Not applicable.

**Comment by mascarua** [comment]
This problem seems to happen when we have environment variables http_proxy, https_proxy (both of which will work with a string value - i.e. without interpolation) and the variable named "no_proxy" will not even work with string values.

**Comment by tas50** [comment]
@lamont-granquist If we lazy'd the value field for ENV would this allow us to use values like this?
