### ISSUE TITLE
knife Bootstrap permissions error is misleading

### ISSUE THREAD

**Issue by marseille** [chef/chef#6668]
## Description
On bootstrapping a windows node , the message 

ERROR: You authenticated successfully to https://'''chef-server-url''' as '''user''' but you are not authorized for this action.
Response:  missing create permission

is displayed. This is not because <user> authenticated correctly or because the <user> is missing the create permission. It is because using user-credentials on a bootstrap, recreates the client and node -- stripping permissions of the existing client and node. When the "clients" group is not part of the READ+CREATE ACL of the nodes container, the recreated client cannot create the new node required for the bootstrap. Thus the missing create permission message. 

The error message is very misleading and cost me over two days of developer time -- it should be rewritten to provide more detail to what exactly is missing permission. Instead of indicating that the user authenticated correctly and display a missing permissions error interpreted as relevant to the user specified. This is very confusing as the user can be part of the admins group and seemingly have their permissions stripped from them.

## Chef Version
13.6.4 ( chefdk - 2.4.17-1_amd64.deb)

## Platform Version
Ubuntu 14.04

## Replication Case
Reference stackoverflow - https://stackoverflow.com/questions/47780723/cant-bootstrap-node-when-user-is-in-admin-group/47819382#47819382

Remove the clients group from the READ+CREATE ACL of containers nodes.

Attempt to bootstrap a remote node with user credentials.

## Client Output
ERROR: You authenticated successfully to https://'''chef-server-url''' as '''user''' but you are not authorized for this action.
Response:  missing create permission

## Stacktrace
https://gist.github.com/marseille/9eb5ba3a79b353fbeb75855ebab38ae7#file-gistfile1-txt-L3

**Comment by tas50** [comment]
@marseille In Chef Infra Client 15 we entirely rewrote how bootstrap works for Windows. I'm going to close this out at this point. If you're still seeing this sort of behavior in Chef Infra Client 15 please open it back up so we can dig in further.
