### ISSUE TITLE
Catch Errno::EINVAL in ConfigFetcher

### ISSUE THREAD

**Issue by martinmosegaard** [chef/chef#6724]
## Description

We can call `chef-client` with `-j` and a file path. But if we try passing a JSON string instead, on Windows, we get an exception trace mentioning `Errno::EINVAL`. In the source code, there are already checks for `Errno::ENOENT` and `Errno::EACCES`, so perhaps we could report a nice error here as well?

I understand from https://github.com/chef/chef/issues/6721 that this behavior is not supported, but it would be nice with a better error message.

## Chef Version

Chef v12 and v13

## Platform Version

Windows Server 2012 R2 and 2016

## Replication Case

I used a cookbook `testjson` with a recipe and attribute like this:

```
>type recipes\default.rb
attr1_value = node['testjson']['attr1']
file 'C:\Users\Administrator\generated-by-chef.txt' do
  content attr1_value
end

>type attributes\default.rb
default['testjson']['attr1'] = 'default value'
```

Observe that `chef-client -z -o "recipe[testjson::default]"` works as expected.

Create a JSON file like this:
```
echo {"testjson": {"attr1": "value from file"}} > myattr.json
```

Observe that `chef-client -z -o "recipe[testjson::default]" -j myattr.json` works.

Then try with inline JSON:

`chef-client -z -o "recipe[testjson::default]" -j '{"testjson": {"attr1": "inline value"}}'`

## Stacktrace

Abbreviated output:
```
.../config_fetcher.rb:47:in `read': Invalid argument @ rb_sysopen - {"testjson":{"attr1":"value from json"}} (Errno::EINVAL)
```

which comes from `read_local_config` in lib/chef/config_fetcher.rb
https://github.com/chef/chef/blob/master/lib/chef/config_fetcher.rb

**Comment by matthizzle** [comment]
Currently seeing the same error "FATAL: Errno::EINVAL:". 
additionally this...
Errno::EINVAL: Invalid argument @ rb_sysopen

 Any more information on this?
