### ISSUE TITLE
Knife share ERROR: Description can't be blank

### ISSUE THREAD

**Issue by bws0013** [chef/chef#6740]
## Description

I am getting the an error `ERROR: Description can't be blank` when attempting to upload a cookbook to the supermarket. 
## Chef Version

```
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13
```
## Platform Version

OSX 10.11.6
## Replication Case

`knife cookbook site share go_chef "Programming Languages" -V`
I have already berks installed and uploaded and can see my metadata file there too. My knife.rb is pointing to this directory as the one hosting my cookbooks so that isn't the issue and my metadata.rb file has a description in it. 
https://github.com/bws0013/go_chef/blob/master/metadata.rb
## Client Output

```
INFO: Using configuration from /Users/bensmith/.chef/knife.rb
INFO: Validating ruby files
INFO: Validating templates
INFO: Syntax OK
Generating metadata for go_chef from /var/folders/xf/q135cl3j00s959bx902md6fr0000gn/T/chef-go_chef-build20180114-68259-1z0anem/go_chef/metadata.rb
Making tarball go_chef.tgz
ERROR: Description can't be blank
```

**Comment by vsingh-msys** [comment]
@bws0013 `knife cookbook site share` is deprecated and will remove in future any change that you can test using `knife supermarket share` ?

**Comment by vsingh-msys** [comment]
Hi @bws0013, Is any chance that you can test `knife supermarket share` with latest version chefdk/ chef-workstation ?

**Comment by vsingh-msys** [comment]
Closing, for now, if you still face the issue feel free to reopen it
