### ISSUE TITLE
knife wildcard search for attrs with values containing spaces doesn't work

### ISSUE THREAD

**Issue by bby-bishopclark** [chef/chef#6741]
## Description
Knife search for attrs with spaces gives unexpected behaviour, like issue 2467

## Chef Version
chefdk-2.0.28-1.el7.x86_64
chef-server-core-12.17.15-1.el7.x86_64 on server

## Platform Version
client: Enterprise Linux 7 (rhel/centos)
server: Enterprise Linux 7 (rhel/centos)

## Replication Case
cd ~/chef-repo/knife/prod/
### on 12 nodes
knife node attribute set testbox updates.sched '0200 sun' 
### on 8 other nodes:
knife node attribute set nodeXX updates.sched '0200 wed' 

### and search
1. knife search node  'updates_sched:0200*sun' -a updates.sched
2. knife search node  'updates_sched:0200?sun' -a updates.sched
3. knife search node  'updates_sched:0200' -a updates.sched
4. knife search node  'updates_sched:0200*' -a updates.sched
5. knife search node  'updates_sched:0200?' -a updates.sched

## Client Output
(vv-output included for one; I can include for the others.  I'm also taking some license in truncating the output, but I can always repeat the searches and add then in and I'm hoping I made the output clear)

1.
search with '*' to cover the space: no results
:
DEBUG: Initiating POST to https://chef.our.org/organizations/org/search/node?q=updates_sched:0200*sun&start=0
:
0 items found

2.
Search with '?' to cover the space.  No hits
:
0 items found

3.
Search for the first 4 letters and find all the test subjects - test pass.
:
tstel7-01:
  updates.sched: 0200 sun

tstel7-02:
  updates.sched: 0200 wed
:
20 items found

4.
Search for 0200* and find the same expected list - test pass
:
20 items found

5.
Search for 0200? to cover the space again
:
0 items found

The debug output (chef-client -l debug) may be useful, but please link to a gist, or truncate it. -->

```

```

**Comment by lamont-granquist** [comment]
I'm not sure if there's chef-server-style solr-ish flags which let one do this or not, so I'm unclear if this is a bug or just a how-to-chef request.
