### ISSUE TITLE
:paranoid is deprecated, please use :verify_host_key

### ISSUE THREAD

**Issue by blimmer** [chef/chef#6785]
## Description
Using chef via the chef-dk docker image, I started noticing this message with calls to `Knife::SSH`:

```
Running knife-ssh...
:paranoid is deprecated, please use :verify_host_key. Supported values are exactly the same, only the name of the option has changed.
```

Running through the issues, I found that at one point the `net-ssh` gem was locked to `=4.1.0` in chef-dk,  because of this and other issues ([PR](https://github.com/chef/chef-dk/pull/1406)).

However, I now see that the gemspec seems to allow `net-ssh` to drift to 4.2:

https://github.com/chef/chef/blob/8324a3f2acabe056bbab2405ae7765f36a64a7c8/chef.gemspec#L28

I ran into some problems with a CLI tool that we use within the chef-dk docker image. Adding a lock in my own gemspec silenced the deprecation for me for now.

```ruby
gem 'net-ssh', '< 4.2'
```

Even today, chef still uses the old `paranoid` attribute:

https://github.com/chef/chef/blob/8324a3f2acabe056bbab2405ae7765f36a64a7c8/lib/chef/knife/ssh.rb#L278

There is [a PR to correct this](https://github.com/chef/chef/pull/6433) but it has been open for some time.

Should this be merged along with a lock of `>= 4.2` but `< 5`?

## Chef Version
```
# chef --version
Chef Development Kit Version: 2.4.23
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.49.2
```

## Platform Version
https://hub.docker.com/r/chef/chefdk (version 2.4.23)

## Replication Case
```console
docker run -it chef/chefdk:2.4.23 bash
gem install net-ssh -v 4.2.0

# in a script...
knife_ssh = Chef::Knife::Ssh.new
knife_ssh.name_args = ['some_machine_known_by_chef']
knife_ssh.run
```

You'll see the warning:
```
:paranoid is deprecated, please use :verify_host_key. Supported values are exactly the same, only the name of the option has changed.
```

**Comment by tarcinil** [comment]
This will be fixed by #6433.

**Comment by tarcinil** [comment]
@blimmer 

I have hit this issue as well.  I will likely create a PR tonight to resolve this based on the work of @petecheslock, but with the additions that have been requested the chef/maintainers.

**Comment by tarcinil** [comment]
@tas50 & @adamleff 

I wanted to verify that you want to not add backward compatibility before making a breaking change.

I was thinking of using:
```
# TODO: deprecate net-ssh 4.1.x in Chef 15.x
if ::Gem.loaded_specs['net-ssh'].version >= ::Gem::Version.create('4.2')
  opts[: verify_host_key] = false
else
  opts[: paranoid] = false
end
```

Otherwise, I will go forward in just locking to net-ssh with a pessimistic of `~> 4.2` which should cover 4.2 -> 5.0
