### ISSUE TITLE
ImmutableArrays and ImmutableHashes that have not had their cache populated are broken for internal ruby APIs

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#6792]
This is the other half of #6784 

```
% cat ./apply.rb
#!/usr/bin/env chef-apply

node.default['foo']['baz'] = [ "one", "two" ]
puts node['foo']['baz']
```

```
% ./apply.rb
[ ... no output ... ]
```

**Comment by lamont-granquist** [comment]
so the idea of monkeypatching puts works if you give it a single dimensional array pretty easily but nested arrays are another problem:

```
#!/usr/bin/env chef-apply

module Thingy
  def puts(*args, &block)
    args.each do |a|
      a.ensure_generated_cache! if a.respond_to?(:ensure_generated_cache!)
    end
    super
  end
end

Kernel.send(:prepend, Thingy)
IO.send(:prepend, Thingy)

#node.default['foo'] = [ [ "one", "two" ], [ "three", "four"] ]
node.default['foo'] = [ "one", "two" ]
puts node['foo']
```

that works, but switching to the 2x2 array there fails.

which would mean needing to deeply walk the arguments and populate any node caches which exist, which starts to smell wrong to me.

**Comment by lamont-granquist** [comment]
the monkeypatching puts option is terrible for any number of reasons, so not going to do that.

unclear of how to fix it.

for now `puts node['foo'].to_s` or `puts "#{node['foo']}"` will coerce the cache into populating before puts does its thing.

interested in any other 13.7 breakage in node attributes in other APIs (aside from #6784 which is fixed) since that may inform the correct way to go about fixing this bug.

**Comment by nicutor** [comment]
Hi @lamont-granquist, I wanted to open an issue about this and just found yours.
My entire chef structure is build on attributes based on other attributes values (mostly arrays) and after 13.7.16 everything has stopped to work. 
The quick fix is to downgrade back to 13.6.4, but, may I ask you if there is any ETA for this bug fix?
It seems to be a HUGE bug as many many cookbooks are using this.
Thank you for your time and work!

**Comment by martinb3** [comment]
Just ran into this as well, with the firewall cookbook doing this:
```
default['firewall']['iptables']['defaults'][:policy] = {
  input: 'DROP',
  forward: 'DROP',
  output: 'ACCEPT',
}
default['firewall']['iptables']['defaults'][:ruleset] = {
  '*filter' => 1,
  ":INPUT #{node['firewall']['iptables']['defaults'][:policy][:input]}" => 2,
  ":FORWARD #{node['firewall']['iptables']['defaults'][:policy][:forward]}" => 3,
  ":OUTPUT #{node['firewall']['iptables']['defaults'][:policy][:output]}" => 4,
  'COMMIT_FILTER' => 100,
}
```

This feels like a pretty big breaking change.

**Comment by thommay** [comment]
@nicutor @martinb3 should be fixed in 13.7.19, which is in the `current` channel (you're actually hitting #6784). Please could you test with that build and confirm?

**Comment by martinb3** [comment]
@thommay I am still having to add an extra `.to_h` (as in my example above) on 13.7.19. So I don't see it fixed.

**Comment by lamont-granquist** [comment]
@nicutor i need you to validate that you are not fixed by #6784 and #6790 and that you can replicate on 13.7.19 or later, and then post your use case.

right now i do not know how to go about fixing this bug, so if there's other related issues i need good bug reports around it (similar to what @martinb3 just posted)

**Comment by nicutor** [comment]
@lamont-granquist , @thommay I've tested 13.7.19 against 13.6.4 and I have the same result using kitchen converge (run 2 times consecutively):

I can confirm that 13.7.19 works so far. 

Using 13.7.16 has gave me 0 Resources always. (My wrapped cookbooks/recipes are included based on some array attributes which are depending by other array attributes, and, there was always 0 Resources converged because the arrays values was nil)

### Steps used:
**1. Using on .kitchen.yml:**
```
chef_omnibus_install_options: "-c current -P chef -v 13.7.19"
```
Commands:
```
kitchen converge centos-6
  Chef Client finished, 172/327 resources updated in 34 minutes 24 seconds
kitchen converge centos-6
  Chef Client finished, 3/286 resources updated in 01 minutes 10 seconds
kitchen destroy centos-6
```

**2. Using on .kitchen.yml:**
```
require_chef_omnibus: "13.6.4"
```
Commands:
```
kitchen converge centos-6
  Chef Client finished, 172/327 resources updated in 39 minutes 01 seconds
kitchen converge centos-6
  Chef Client finished, 3/286 resources updated in 01 minutes 37 seconds
```
**3. No omnibus options on .kitchen.yml. Inside VM I've upgraded chef from 13.6.4 to 13.7.19**
```
wget https://packages.chef.io/files/current/chef/13.7.19/el/6/chef-13.7.19-1.el6.x86_64.rpm
rpm -Uvh chef-13.7.19-1.el6.x86_64.rpm
```
Commands:
```
kitchen converge centos-6
Chef Client finished, 3/286 resources updated in 01 minutes 04 seconds
```

I will come back if I will find other issues.

Thank you for your work and time!

**Comment by dayne** [comment]
I just saw this note about potentially 13.7.19 fixing the issue so I tried see if it resolves the related issue found in: https://github.com/chef-cookbooks/firewall/issues/185

Added `chef_omnibus_install_options: "-c current -P chef -v 13.7.19"` to the [chef-cookbooks/firewall](https://github.com/chef-cookbooks/firewall)`/.kitchen.yml` and on a clean converge, verifying I saw it using 13.7.19, that cookbook still fails with corrupt iptables generation:
`kitchen destroy default-centos-69 && kitchen converge default-centos-69`

**Comment by lamont-granquist** [comment]
So the actual line which was broken in the cookbook which was broken is this:

```
diff --git a/libraries/helpers_iptables.rb b/libraries/helpers_iptables.rb
index 5797d17..8a0b987 100644
--- a/libraries/helpers_iptables.rb
+++ b/libraries/helpers_iptables.rb
@@ -104,7 +104,7 @@ module FirewallCookbook
         # hash regardless of ipv6 status
         %w(iptables ip6tables).each do |name|
           input[name] = {} unless input[name]
-          input[name].merge!(default_ruleset(current_node))
+          input[name].merge!(default_ruleset(current_node).to_h)
         end
       end
     end
```

**Comment by lamont-granquist** [comment]
So that is `Hash#merge!()` which is taking a ImmutableMash which `is_a?(Hash)` which makes `merge!()` ultimately not call any methods on the ImmutableMash and just pokes around in its internal ruby data structure to loop over the internal hash structure and merge it with the target hash.

So that expands the issue from ImmutableArrays to ImmutableMashes and every API in ruby which takes an Array or a Mash and pokes around directly with the contents.

**Comment by martinb3** [comment]
Thanks for chasing that @lamont-granquist -- we can at least fix it in the firewall cookbook 👍

**Comment by lamont-granquist** [comment]
Yeah this behavior is still horribly broken though.  Fixing it is taking some effort though.

**Comment by s-bernard** [comment]
Hi,

I have tested a problematic case with both hashes and arrays against different versions.

### Case

In attributes/default.rb:

```ruby
default[cookbook_name]['hash'] = { 'string' => 'some' }

default[cookbook_name]['array'] = [{ 'a' => 'some' }]
override[cookbook_name]['array'] = [{ 'b' => 'other' }]
```

In recipe/default.rb:

```ruby
puts({}.merge(node[cookbook_name]['hash']))
puts({}.merge(node[cookbook_name]['hash'].to_h))
puts({}.merge(node[cookbook_name]['hash']))

puts node[cookbook_name]['array']
puts node[cookbook_name]['array'].to_s
```

#### Result on broken versions

```ruby
{}
{"string"=>"some"}
{"string"=>"some"}
[{"b"=>"other", "a"=>"some"}]
```

#### Expected results

```ruby
{"string"=>"some"}
{"string"=>"some"}
{"string"=>"some"}
{"b"=>"other"}
[{"b"=>"other"}]
```

#### Notes

For hashes: if you use `node[cookbook_name]['hash']` directly, it will work. But if you encapsulate it in a `{}.merge`, it won't. A work-around is to `to_h` it. Then it will continue to work.

On arrays, at least two problems:
- first output is empty, `to_s` must be called
- there is a deep merge on hash in arrays between different precedence levels! The entire attribute should be replaced by the override value.

### Working versions

**13.6.4 - 13.6.26**

### Breaking version

**13.6.27** which might be explained by commit like 0c29acc106ca774e230c8ef45694c8bffd166b69

### Current

It is still broken on **13.7.24** and **14.0.59**.

### Code used for the tests

Code: https://gitlab.com/chef-platform/test-cookbook/tree/issue_6792
(you can easily test another version by modifying the `product_version: latest` parameter in `.kitchen.yml`)

Example of output on **14.0.59**: https://gitlab.com/chef-platform/test-cookbook/-/jobs/52936624 (interesting part is at the end)

**Comment by thommay** [comment]
@s-bernard thanks for the update. We're working on this in #6858 which should be pretty close to done.

**Comment by atheiman** [comment]
we ran into this too.. i made a simple test cookbook with a pr showing the failure only in the latest version of Chef available [travis failure](https://travis-ci.org/atheiman/test-cookbook/builds/345370813), [pr](https://github.com/atheiman/test-cookbook/pull/6)

**Comment by atheiman** [comment]
13.8 tag has the fix for me: [travis](https://travis-ci.org/atheiman/test-cookbook/builds/345390014), [test cookbook pr](https://github.com/atheiman/test-cookbook/pull/6)

**Comment by s-bernard** [comment]
13.8.0 works well for me (for this issue).

**Comment by lamont-granquist** [comment]
we reverted this, 13.7.x should be the only broken version(s).
