### ISSUE TITLE
systemd resource should support reenable

### ISSUE THREAD

**Issue by directionless** [chef/chef#6823]
## Description

From what I can tell, systemd only re-geneates unit aliases when a unit goes through a disable/enable cycle. This can cause fairly confusing behavior.

In our case:

1. rsyslog installs a unit file in `/lib` which gets Aliased to `/etc/...`
2. our chef run comes along and sets up a new rsyslog service with that Alias
3. systemd see the old unit as enabled, so doesn't re-generate the alias
4. restart restarts with the wrong unit file contents.

At least for rsyslog, this appears to be a pretty common problem. Related bugs in other projects:
* https://github.com/rsyslog/rsyslog/issues/2134
* https://github.com/systemd/systemd/issues/6338
* https://github.com/ansible/ansible/issues/16912

I think this could be fixed by creating a `reenable` action, and letting end users call that as they need. Or maybe a `triggers_reenable` flag. Or possible by doing something clever internally and calling it, but I think the logic is gnarly, and pushing it to the end users is cleaner.

**Comment by nathwill** [comment]
looks like they've made some fixes to upstream systemd for the bug you referenced, but the reenable action looks to be a directly-supported systemctl action, so i've added that in the PR above.

**Comment by tas50** [comment]
@nathwill got this added to his PR and it’s merged onto the master branch. It’ll ship in 14.0. Thanks for the report

**Comment by directionless** [comment]
This is perfect, thank you!
