### ISSUE TITLE
windows_task idle_time validation broken

### ISSUE THREAD

**Issue by k-brooks** [chef/chef#6824]
## Description
6cac5affe524a2fc481a944bebef4135a16a34b7 logic is faulty, causes validation of nil field in irrelevant frequency contexts.

## Chef Version
13.7.13+

## Platform Version
MS Server 2016

## Replication Case
attempt to create a windows_task with a frequency of onstart
windows_task 'test' do
  task_name 'test'
  command "set"
  run_level :highest
  frequency :onstart
  action :create
end

## Client Output
WinAgent001   ================================================================================
--
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   Recipe Compile Error in c:/chef/cache/cookbooks/buildagent/recipes/default.rb
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   ================================================================================
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   ArgumentError
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   -------------
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   idle_time property is only valid for tasks that run on_idle
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   Cookbook Trace:
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   ---------------
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001     c:/chef/cache/cookbooks/buildagent/recipes/windows-agent-service.rb:40:in `from_file'
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001     c:/chef/cache/cookbooks/buildagent/recipes/default.rb:11:in `from_file'
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   Relevant File Content:
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   ----------------------
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   c:/chef/cache/cookbooks/buildagent/recipes/windows-agent-service.rb:
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001    33:  }
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001    34:
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001    35:  template("#{node[:bamboo][:remoteAgent][:agentDir]}/bin/bamboo-capabilities.properties") {
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001    36:    source "#{node[:bamboo][:remoteAgent][:capabilitiesTemplate]}"
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001    37:    not_if { node[:bamboo][:remoteAgent][:capabilitiesTemplate].to_s.empty? }
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001    38:  }
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001    39:
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001    40>> windows_task 'agent_task' do
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001    41:    task_name 'Bamboo Agent'
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001    42:    user 'foo'
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001    43:    password 'bar'
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001    44:    command "#{node[:bamboo][:remoteAgent][:agentDir]}/bin/BambooAgent.bat"
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001    45:    run_level :highest
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001    46:    frequency :onstart
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001    48:    action [:create, :run]
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001    49:  end
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   System Info:
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   ------------
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   chef_version=13.7.16
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   platform=windows
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   platform_version=10.0.14393
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   program_name=C:/opscode/chef/bin/chef-client
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001   executable=C:/opscode/chef/bin/chef-client
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001
15:32:20 |   |   |  
15:32:20 |   |   | WinAgent001
15:17:12 |   |   | WinAgent001   ================================================================================
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   Recipe Compile Error in c:/chef/cache/cookbooks/buildagent/recipes/default.rb
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   ================================================================================
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   ArgumentError
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   -------------
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   idle_time property is only valid for tasks that run on_idle
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   Cookbook Trace:
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   ---------------
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001     c:/chef/cache/cookbooks/buildagent/recipes/windows-agent-service.rb:40:in `from_file'
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001     c:/chef/cache/cookbooks/buildagent/recipes/default.rb:11:in `from_file'
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   Relevant File Content:
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   ----------------------
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   c:/chef/cache/cookbooks/buildagent/recipes/windows-agent-service.rb:
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001    33:  }
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001    34:
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001    35:  template("#{node[:bamboo][:remoteAgent][:agentDir]}/bin/bamboo-capabilities.properties") {
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001    36:    source "#{node[:bamboo][:remoteAgent][:capabilitiesTemplate]}"
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001    37:    not_if { node[:bamboo][:remoteAgent][:capabilitiesTemplate].to_s.empty? }
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001    38:  }
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001    39:
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001    40>> windows_task 'create_agent_task' do
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001    41:    task_name 'Bamboo Agent'
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001    42:    user 'foo'
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001    43:    password 'bar'
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001    44:    command "#{node[:bamboo][:remoteAgent][:agentDir]}/bin/BambooAgent.bat"
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001    45:    run_level :highest
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001    46:    frequency :onstart
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001    47:    action :create
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001    48:  end
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001    49:
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   System Info:
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   ------------
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   chef_version=13.7.16
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   platform=windows
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   platform_version=10.0.14393
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   program_name=C:/opscode/chef/bin/chef-client
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001   executable=C:/opscode/chef/bin/chef-client
15:17:12 |   |   |  
15:17:12 |   |   | WinAgent001
15:17:12 |   |  

```

```

**Comment by tas50** [comment]
This is fixed on master (chef14) and we've back ported the same fix to the chef-13 branch. It'll go out soon (promise) once we get our last regression fix for chef 13 merged in.

**Comment by spuder** [comment]
I just tried upgrading to chef 13 and also ran into this issue. 
Back to chef 12 I go.

**Comment by tas50** [comment]
13.6.4 is the working chef 13 release until we get 13.8 released.
