### ISSUE TITLE
user resource never creates homedir

### ISSUE THREAD

**Issue by bby-bishopclark** [chef/chef#6829]
## Description
````
user testo do
  action [:create]
end

# grep HOME /etc/login.defs
CREATE_HOME     yes

# userdel -rf testo ; chef-client ; ls -ld /home/testo
... Starting Chef Client, version 13.7.16
:
:
ls: cannot access /home/testo: No such file or directory
````

the docs at https://docs.chef.io/resource_user.html strongly suggest this is a bug:

> manage_home
> Ruby Types: TrueClass, FalseClass
> 
> Manage a user’s home directory.
> 
> With the :create action, a user’s home directory is created based on HOME_DIR. If the home directory is missing, it is created unless CREATE_HOME in /etc/login.defs is set to no. When created, a skeleton set of files and sub-directories is also created in the home directory.

The homedir is definitely NOT being created.

````
user testo do
  action [:create, :manage]
end
````
Still not created; even when the user is explicitly deleted as shown above.  Documentation clearly shows this isn't expected behaviour.  Is manage_home no longer defaulting as documented?

## Chef Version
13.7.16
## Platform Version
centos/rhel7

**Comment by coderanger** [comment]
The docs are out of date, you need to explicitly supply `manage_home true`.

**Comment by bby-bishopclark** [comment]
If the plan is to not fix the code, be sure to change the documentation under `:force` as well.

**Comment by lamont-granquist** [comment]
definitely a doc bug, you must supply `manage_home: true`

**Comment by tas50** [comment]
I opened a PR to update the wording in the user docs. This should make it a bit more clear that you need to specify manage_home: https://github.com/chef/chef-web-docs/pull/1301
