### ISSUE TITLE
Knife::SSH#run runs a Kernel.exit with non-zero exit code

### ISSUE THREAD

**Issue by blimmer** [chef/chef#6844]
## Description
I'm utilizing `Knife::SSH` within some Ruby deployment code and when I use the `#run` method, it bails out of the entire code run because of this code block:

https://github.com/chef/chef/blob/a2a63b6ee82f7caabcda87cbcbb51e4fdc0fc9d9/lib/chef/knife/ssh.rb#L600-L605

To work around the problem, the command I pass to the instances targeted by Knife SSH looks like this:

```ruby
command = 'sudo chef-client || true'
```

but that's problematic for a few reasons. It would be nice if this method threw an exception that I could capture and handle on my own. For instance:

```ruby
if exit_status != 0
  raise Knife::SSH::NonZeroExitCodeError("instance abc123 failed with exit status #{exit_status}")
else
  # existing logic
end
```

Then, I could capture that exit code and do the retry logic, or whatever else I need. Having to capture a `SystemExit` event is pretty scary.

## Chef Version
2.4.23

## Platform Version
Docker image `chef/chefdk:2.4.23`

## Replication Case
```ruby
knife_ssh = Chef::Knife::Ssh.new
knife_ssh.name_args = ['machine1 machine2', 'eval "exit 2"'] # replace with two machines
knife_ssh.config = {}
puts "OK - running!"
knife_ssh.run
puts "I made it!" # you won't see this because the system exits
```

## Client Output

```
OK - running!
```

**Comment by btm** [comment]
There are simple "fixes" that could be implemented here, but we haven't considered Knife to be a library in the past and there are endless issues like this if we did.

I argue this isn't a supported pattern and if you want to build scripting around knife ssh, it should be through the cli, e.g. use `system('knife ssh')` or Mixlib::ShellOut.
