### ISSUE TITLE
Add ability to `ignore_failure` on apt_repository

### ISSUE THREAD

**Issue by hrak** [chef/chef#6865]
## Description
Request similar to https://github.com/chef-cookbooks/apt/issues/183

Add the ability to set `ignore_failure true` on a apt_repository resource. Sometimes when a repo is down and it is configured to fetch the gpg key from http, the entire Chef run fails while it would be fine to just continue.

**Comment by coderanger** [comment]
Does this not work already? `ignore_failure` is part of the API on the base `Resource` class so it should work on any resource.

**Comment by tas50** [comment]
@hrak Coderanger is right. You can ignore_failure on any resource in chef. It creates a lot of log noise when it fails, but the run will continue on.
