### ISSUE TITLE
No way to disable STDOUT logger when supplying a formatter with `log_location`

### ISSUE THREAD

**Issue by richardc** [chef/chef#6889]
## Description

No way to disable STDOUT logger when supplying a formatter with a `log_location`.

Some formatters (nyan cat as referred to from the documentation being one), assume/interact with a terminal, and so are less log formatters and more custom log sinks.  Adding a default STDOUT logger into that mix really messes up the output of these formatters.

In Chef 12 `force_logger false` (the default for that option) could incidentally be used to address this, but refactorings along the way have removed this option.

https://github.com/chef/chef/pull/5851
https://github.com/chef/chef/pull/6035

Please re-add a way to inhibit the additional STDOUT default logger.

## Chef Version

Chef 13+.  Replication case logs are from master@01ae5aac80444d6e849bb44ba0f5798e46978c7f aka v14.0.59.  Not present in v12.21.31

## Replication Case

Given the following configuration:

```ruby
# bug-config.rb
gem 'nyan-cat-chef-formatter'
require 'nyan-cat-chef-formatter'

log_location '/tmp/chef.log'

add_formatter :nyan
once true
```

Run `chef-client -z -c bug-config.rb -o ''`

We hope to see no lines in the output that look like `[2018-02-21T10:12:08+00:00] WARN: Bad things ahead!` but we do.

## Client Output

```console
$ chef-client -z -c bug-config.rb -o ''
[2018-02-21T10:12:08+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /Users/richardc/src/chef.
Starting Chef Client, version 14.0.59
resolving cookbooks for run list: []
Synchronizing cookbooks
done.
Compiling cookbooks
done.
[2018-02-21T10:12:14+00:00] WARN: Node penge.local has an empty run list.
Converging 0 resources
0/0: _,------,
0/0: _|  /\_/\
0/0: ~|_( - .-)
0/0:  ""  ""

System converged.
no resources updated
chef client finished, 0 resources updated
```

What's relevant are these lines:

```
[2018-02-21T10:12:08+00:00] WARN: No cookbooks directory found at or above current directory.  Assuming /Users/richardc/src/chef.
```

```
[2018-02-21T10:12:14+00:00] WARN: Node penge.local has an empty run list.
```

That's a logger connected to STDOUT.

## Stacktrace

N/A

**Comment by richardc** [comment]
We have a workaround in our current configuration, which is to be awful and monkey-patch `Chef::Application#want_additional_logger?`.  Sharing it here in case it's of use to other nyan cat fans:

```ruby
# config.rb
gem 'nyan-cat-chef-formatter'
require 'nyan-cat-chef-formatter'

log_location "/tmp/chef-log"

add_formatter :nyan
once true

# Icky monkey-patch - we never want an additional logger as the one in `log_location` is fine.
class ::Chef::Application
  def want_additional_logger?
    false
  end
end
```

**Comment by lamont-granquist** [comment]
does `--force-formatter` work and does `force_formatter true` in client.rb work in chef-client master past https://github.com/chef/chef/pull/6916 ?

**Comment by richardc** [comment]
Checked at 19608ab7e7a5904c0917686835b8e96babe12386 and no, that doesn't make any difference either on the CLI or in the client.rb.

**Comment by lamont-granquist** [comment]
did https://github.com/chef/chef/pull/7698 fix this?

**Comment by lamont-granquist** [comment]
closing as needing replication and will not be applicable after #9126
