### ISSUE TITLE
Weird gem issues

### ISSUE THREAD

**Issue by coderanger** [chef/chef#6954]
Opening this for tracking. Some time between 14.0.89 and 14.0.99 my integration tests for poise-ruby broke. The culprit appears to be something funky with `gem_package` causing `bundler` to show as up-to-date even if it isn't:

```
...
* ruby_gem[bundler] action upgrade (up to date)
...
kitchen@2a2d85915112:~$ /usr/bin/gem2.3 list

*** LOCAL GEMS ***

bigdecimal (1.2.8)
did_you_mean (1.0.0)
io-console (0.4.5)
json (1.8.3)
minitest (5.8.4)
net-telnet (0.1.1)
power_assert (0.2.7)
psych (2.0.17)
rake (10.5.0)
rdoc (4.2.1)
test-unit (3.1.7)
```

We should track this down :)

**Comment by coderanger** [comment]
Definitely something going wrong here:

```
# 14.0.114 (latest build)
irb(main):014:0> Chef::Provider::Package::Rubygems::AlternateGemEnvironment.new('/usr/bin/gem2.3').gem_specification.find_all_by_name('bundler', '>= 0').first.loaded_from
=> "/opt/chef/embedded/lib/ruby/gems/2.4.0/specifications/default/bundler-1.16.1.gemspec"
```

vs.

```
# 14.0.89
irb(main):003:0> Chef::Provider::Package::Rubygems::AlternateGemEnvironment.new('/usr/bin/gem2.3').gem_specification.find_all_by_name('bundler', '>= 0')
=> []
```

https://github.com/chef/chef/compare/v14.0.89...v14.0.99 shows all the changes in the target range, which almost certainly means its because of either the included bundler rev, the included ruygems, or appbundler.

**Comment by coderanger** [comment]
The core of the problem: 

```
kitchen@2a2d85915112:~$ ls /opt/chef/embedded/lib/ruby/gems/2.4.0/specifications/default/
bigdecimal-1.3.0.gemspec  bundler-1.16.1.gemspec  io-console-0.4.6.gemspec  json-2.0.4.gemspec  openssl-2.0.5.gemspec  psych-2.2.2.gemspec  rdoc-5.0.0.gemspec
```

vs. 

```
root@6c7a3cf08e72:/# ls /opt/chef/embedded/lib/ruby/gems/2.4.0/specifications/default/
bigdecimal-1.3.0.gemspec  io-console-0.4.6.gemspec  json-2.0.4.gemspec  openssl-2.0.5.gemspec  psych-2.2.2.gemspec  rdoc-5.0.0.gemspec
```

Given our current code, any gem in the default set cannot be usefully managed via `gem_package` because AlternateGemEnvironment will always see Chef's version of it. We can probably filter on `spec.loaded_from` to make this work though.

**Comment by coderanger** [comment]
Another possible fix would be in the build scripts, erasing the contents of that `default/` folder but I have no idea what the consequences of that would be.

**Comment by lamont-granquist** [comment]
Related discussion here i think: https://github.com/chef/chef/issues/3363
