### ISSUE TITLE
Cleanup of old gems

### ISSUE THREAD

**Issue by phoolish** [chef/chef#6977]
## Description
We noticed that several of our /opt/chef folders are around 1.5-2GB in size. This is all due to `/opt/chef/embedded/lib/ruby/gems/2.3.0/gems`. The problem seems to be related to the cleanup of  old gems.

## Chef Version
12.22.1 and 13.8.5

## Platform Version
Amazon Linux 2017.09
Centos 6.7

## Replication Case
* Create a simple test cookbook (1 recipe with a single resource)
* Add a `gem 'aws-sdk', '~> 2'` to the metadata.rb file.
* Use kitchen-test to converge the cookbook.
* Update the gem version constraint to be more stringent `= 2.10.134`
* Rerun kitchen-test converge.
* Login to kitchen-test instance and `ls /opt/chef/embedded/lib/ruby/gems/2.3.0/gems | grep aws`

```
aws-sdk-2.10.134
aws-sdk-2.11.11
aws-sdk-core-2.10.134
aws-sdk-core-2.11.11
aws-sdk-resources-2.10.134
aws-sdk-resources-2.11.11
aws-sigv4-1.0.2
```

**Comment by coderanger** [comment]
The issue is that when you upgrade the Chef packages, it doesn't remove any gems installed via `chef_gem` (or otherwise installed outside of the package). Similarly when rubygems does an ugprade of a gem, it leaves the original. You should be able to run `/opt/chef/embedded/bin/gem cleanup` to tidy things up.

**Comment by phoolish** [comment]
@coderanger that worked, but shouldn't this be managed as part of the chef-run?

**Comment by coderanger** [comment]
It could be, but you would have to do that from one of your recipes. We prefer to keep Chef itself unopinionated about such things because we have so many widely varying use cases. Might be a decent addition to the community `chef-client` cookbook though.

**Comment by phoolish** [comment]
That makes sense, but I am surprised other folks haven't run into this. Especially with such a widely used gem like aws-sdk. Thanks for the explanation.

**Comment by coderanger** [comment]
Disk space is cheap and most of us don't really check all that often :)

**Comment by phoolish** [comment]
Back in my day you paid an arm and a leg for a gig. Old habits die hard.
