### ISSUE TITLE
Chef::Provider::User::Useradd is poisoned by toxic ldap/ad accounts

### ISSUE THREAD

**Issue by bby-bishopclark** [chef/chef#6978]
## Description

Chef::Provider::User::Useradd is using 'useradd' instead of 'luseradd', etc, and thus will conflict when operating on a a host where the centralized auth config has a glitch.

https://github.com/chef/chef/blob/master/lib/chef/provider/user/linux.rb#L27

Story:  Someone added a dbadmin account to AD.  And suddenly we couldn't instantiate new db hosts.  

Yes, it will be said that it's "on us" to ensure no windows guys add dbadmin/apache/mail et al accounts into AD, but also it would be interesting to have chef runs be consistent and repeatable despite what the wingroup does this week.

Changing 'useradd' to 'luseradd' (and similar changes for the other ops) will cause useradd/etc to ignore remote auth methods when adding users.  

It does change the onus from ensuring no conflicting accounts exist to ensuring no conflicting accounts exist, but the chef run will not bail out.

I'm making the huge assumption that no one modifies their LDAP from client machines, for security reasons. If that options needs to be preserved, then please consider an option in the provider.

(And a link to 'building providers for chef and ruby noobs' may be useful if I can use it for a chef::provider::user::luseradd option)

## Chef Version
13.6.4

## Platform Version
rhel7

## Replication Case
1. add account to ad/ldap/nis
2. chef-apply -e 'user dbadmin'   (will probably do it)

## Client Output

```
10.1.5.6   * linux_user[dbadm] action create
10.1.5.6   
10.1.5.6      ================================================================================
10.1.5.6   Error executing action `create` on resource 'linux_user[dbadm]'
10.1.5.6   ================================================================================
10.1.5.6   
10.1.5.6   Mixlib::ShellOut::ShellCommandFailed
10.1.5.6   ------------------------------------
10.1.5.6   Expected process to exit with [0], but received '9'
10.1.5.6   ---- Begin output of ["useradd", "-g", "dbs", "-u", "16115", "-m", "dbadm"] ----
10.1.5.6   STDOUT:
10.1.5.6   STDERR: useradd: user 'dbadm' already exists
10.1.5.6   ---- End output of ["useradd", "-g", "dbs", "-u", "16115", "-m", "dbadm"] ----
10.1.5.6   Ran ["useradd", "-g", "dbs", "-u", "16115", "-m", "dbadm"] returned 9
10.1.5.6   
```

**Comment by coderanger** [comment]
Unfortunately the problems run much deeper. We directly call into the libc APIs for gathering user data (eg https://github.com/chef/chef/blob/master/lib/chef/provider/user.rb#L49) as part of the idempotence checks. Given that libc doesn't really offer a way to tell which source a user (or group) record came from so attempting to overlap multiple sources would make things very sad. I recommend building a custom resource for this use case.

**Comment by ianl678** [comment]
Puppet provides a "forcelocal" attribute for exactly this scenario
Ansible provides a "local" option

Every user of chef creating a custom resource isn't really a suitable solution for a basic function that's desperately needed

**Comment by ianl678** [comment]
Also, "getent" provides this functionality using the "-s" parameter, is it not calling the same libc API's?

**Comment by lamont-granquist** [comment]
We'd need to shellout to `getent -s` instead of `Etc.getpwnam` there since the ruby APIs don't support that option.

Unfortunately that is a change in the base class which runs across Solaris, Mac, AIX, even windows.   Would probably need to extract a hook like this in the superclass:

```ruby
def get_user_info
  Etc.getpwnam(new_resource.username)
end
```

and then do `shell_out!("getent -s")` and parse it and optionally remove the -s, etc, etc but only in the linux provider.  bonus points for seeing if AIX and Solaris worked with the same code.

**Comment by bby-bishopclark** [comment]
"Area:Mac"?  I'm seeing this on a standard RHEL7 host, as mentioned above.

**Comment by coderanger** [comment]
It can affect any OS that allows multiple sources of user data, which is basically all of them. The `user` resource makes fairly naive assumptions that work great for servers with only local users, but can fail when there are overlapping names/IDs in play.

**Comment by bby-bishopclark** [comment]
Sorry, let me re-ask that question.  Does 'area:Mac' marking this issue in such a way as to limit its scope to just Mac when it was visible on other OSes like Linux too?

**Comment by btm** [comment]
@bby-bishopclark no, the labels are only to help organize issues. It wouldn't limit the scope of the fix.
