### ISSUE TITLE
Authorization header isn't stripped after a redirect to a different host

### ISSUE THREAD

**Issue by bugok** [chef/chef#6984]
## Description
In http, the authentication header isn't stripped after a redirect to a different host.

This is how other popular http modules are doing this: 
- curl: https://github.com/curl/curl/blob/6beb0eee/lib/http.c#L710
- Python's requests module is doing it: https://github.com/request/request/pull/1184/
- gist example of how curl strips this header: https://gist.github.com/bugok/6551763aacb7b6ff2d463d2005bdb897

## Chef Version
12.21.31

## Platform Version
MacOS: 10.13.3

## Replication Case
Hitting httpbin.org with a redirect option to get redirected, observing that the auth headers are being sent upon the redirect.
```
$ cat exmaple.rb
http_request 'dummy' do
  action :get
  url 'https://httpbin.org/redirect-to?url=https://www.google.com'
  headers({'Authorization' => "Basic #{
    Base64.encode64('username:password')}",
  })
end
```
Then, I ran `chef-apply example.rb -l debug` 

## Client Output
https://gist.github.com/bugok/843f112c1171e934ce7c67c490ab3cbd
You can see that in line 414, the redirect request contains the auth header.

## Stacktrace
None

**Comment by bugok** [comment]
Closing, as the fix got merged.

**Comment by bugok** [comment]
As https://github.com/chef/chef/pull/6985 got reverted in https://github.com/chef/chef/pull/6996, reopening.

**Comment by tas50** [comment]
This was fixed with that PR merge back in 2018
