### ISSUE TITLE
Translating old (Chef 12) providers to Chef 13

### ISSUE THREAD

**Issue by zachsmorgan** [chef/chef#7020]
## Description

In our old (Chef 12) providers, we used a load_current_resource method like...
```
def load_current_resource
  @current_resource = Chef::Resource::MyResource.new(@new_resource.name)
  if the_thing_exists?
    @current_resource.exists = true
  end
end
```
What's the correct way to translate that sort of logic to the new Provider methodology? 
I've stumbled around and come up with like...
```
if Chef::VERSION ... < 13
... the old assignment ...
else
  @current_resource = @new_resource.dup
end
```
but that feels kludgey, to say the least. 

I would just run with that pattern if it was only cookbooks I maintained personally, but my organization contributes to some upstream cookbooks.

Can someone enlighten me as to the correct approach before I litter the community with my bad code?

## Chef Version
Chef 12, Chef 13

## Platform Version
Linux

## Replication Case
N/A

**Comment by lamont-granquist** [comment]
https://discourse.chef.io/t/chef11-lwrp-issue-with-chef13/12767/2

**Comment by lamont-granquist** [comment]
also see https://github.com/chef-cookbooks/chef_client_updater which is written in chef-11 style to support old chef-client versions.

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

...
