### ISSUE TITLE
Rework everything about state_properties + identity_properties and remove instance_variable_name: false use cases

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#7028]
most likely state_properties and identity_properties as separate declarations needs to just go away.  also we do a lot of hella strangeness to allow setting plain-old-ivars as state/identity_properties, which likely needs to go away.

it looks like state_properties must be a complete declaration of all state_properties or else we remove `desired_state:` off of prior declared properties:

https://github.com/chef/chef/blob/5401a701f1e40f41e76ff855aa4c6dbf411dd230/lib/chef/mixin/properties.rb#L207-L214

the way that we do this weirdness here if there's no existing property is also really weird:

https://github.com/chef/chef/blob/5401a701f1e40f41e76ff855aa4c6dbf411dd230/lib/chef/mixin/properties.rb#L201

if that can go away, then the whole use case for `instance_variable_name: false` goes away.  and the whole name for manually declaring accessor methods and then wrapping a property around them could go away.

then all these `if instance_variable_name` checks can go away because that will never be false:

https://github.com/chef/chef/blob/5401a701f1e40f41e76ff855aa4c6dbf411dd230/lib/chef/property.rb#L604-L629

**Comment by lamont-granquist** [comment]
I need to revisit if this got all fixed in Chef-16 or if there's anything remaining for Chef-16

**Comment by tas50** [comment]
I believe we still have a bunch of funky identity stuff
