### ISSUE TITLE
Port copy_properties_to from etcd cookbook into core chef

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#7046]
```ruby
def copy_properties_to(to, *properties)
  properties = self.class.properties.keys if properties.empty?
  properties.each do |p|
    # If the property is set on from, and exists on to, set the
    # property on to
    if to.class.properties.include?(p) && property_is_set?(p)
      to.send(p, send(p))
    end
  end
end
```

I think it would be better to have it shaped more like:

```ruby
declare_resource(:remote_file, name, &block).apply_properties(include: [ :group, :owner ], exclude: [ :headers ])
```

Maybe `include` is the obvious enough default to have it be `def apply_properties(*include, exclude: [])`

Kind of think it should hang off of Chef::Resource so it method chains better like that.  And rename it to not conflict with existing cookbooks.   Could also write a minimum viable compat_apply_properties cookbook to patch up old chef-client versions so other cookbooks could use it (not the entire crazysauce of compat_resource, but do-just-one-small-thing-only).

**Comment by lamont-granquist** [comment]
@coderanger points out that this could be more useful as well if it was a `..._from` API and didn't hardcode `self`:

```ruby
declare_resource(:remote_file, name, &block).copy_properties_from(self, [ :group, :owner ], exclude: [ :headers ])

remote_file "name" do
  copy_properties_from new_resource,  [ :group, :owner ], exclude: [ :headers ]
end
```

**Comment by lamont-granquist** [comment]
And should return self for method chaining...

**Comment by lamont-granquist** [comment]
And https://github.com/chef-cookbooks/aws/blob/master/resources/s3_file.rb#L117-L139 is Exhibit A for where its useful.  @coderanger also points out that it smells like aws_s3_file should subclass remote_file, but we can't do that from custom resources.

**Comment by lamont-granquist** [comment]
Also, @coderanger points out it could take a regexp for include/exclude instead of array of symbols.

**Comment by coderanger** [comment]
Just an overall :+1: to copy over from Slack. I think I am more in favor of limiting the auto-copy to props defined on both sides but not super strongly as there is value in being explicit :)

**Comment by lamont-granquist** [comment]
Yeah it clearly makes it easier to slap a resource over sub resources and not have to thinking about carving out the exact properties interface.  At the same time I wonder about spooky-action-at-a-distance effects when core chef resources gain new properties or when the wrapping custom resource has its API extended by properties that someone didn't intend to apply to the sub-resource.  Allowing both the include+exclude arguments to be omitted and just have it do what it can sort out itself has a lot of whip-it-up-itude going for it.

Note that for back-compat purposes the `property_is_set?` helps a lot there because you can introduce a property, that may even have a default value, and if its not set on the custom resource it won't get passed to the sub-resource, and if you're on an old version of chef-client that doesn't implement that property nothing with happen.

**Comment by lamont-granquist** [comment]
For include/exclude the way it works in my head is that excludes trump includes.  Which allows you to be lazy and construct a list of all the properties on the custom resource, and then case-by-case do excludes for sub-resources that
don't want certain properties -- so its just `[ includes] - [ excludes]` in set arithmetic.  Of course it is just syntactic sugar for doing exactly that.

**Comment by lamont-granquist** [comment]
Oh so circling back around on this:

```ruby
    # If the property is set on from, and exists on to, set the
    # property on to
    if to.class.properties.include?(p) && property_is_set?(p)
      to.send(p, send(p))
    end
```

If the user specifies something like `atomic_update` on the custom resource but we're running chef 11.5 (bear with me on the contrived example) and `atomic_update` does not yet exist on the remote_file resource we really need to blow up with a useful error message, otherwise the user is silently getting old behavior.  The `property_is_set?` check means that if the user does not set `atomic_update` on the custom resource we won't even try to apply it to the sub-resource, so on chef 11.5 we wouldn't blow up in that case.  If the user of the custom resource really intends to use atomic_update on chef >= 11.6 and then ignore it on chef < 11.6 then they need to gate that with `atomic_update false if Chef::Resource::RemoteFile.respond_to?(:atomic_update)` or something similar.
