### ISSUE TITLE
Convert windows_pagefile to powershell

### ISSUE THREAD

**Issue by tas50** [chef/chef#7047]
Instead of running wmic.exe and parsing the results we should just use powershell to make the WMI calls. It should be much easier to parse and is probably significantly faster when paired with the new powershell out work.

**Comment by johnmccrae** [comment]
https://help.pdq.com/hc/en-us/community/posts/115002970512-Powershell-script-to-change-Pagefile-Virtual-memory-size-on-remote-computers-using-PDQ-deploy-

$settings = Get-CimInstance -Class Win32_PageFileUsage | Select-Object *
(Get-CimInstance -Class Win32_PageFileUsage | Select-Object *).AllocatedBaseSize
Get-CimInstance -ClassName CIM_StorageVolume -Filter "Name='$($DL):\\'" -ErrorAction Stop

# experimental
Get-CimInstance -ClassName Win32_PageFileSetting -Filter "SettingID='pagefile.sys @ $($DriveLetter):'" -ErrorAction Stop | Set-CimInstance -Property @{InitialSize = $InitialSize ;MaximumSize = $MaximumSize ;} -ErrorAction Stop

# working? But it doesn't set the size... hmmm
#  Set automanage pagefile to false; min/max pagefile size
$computerSystem = Get-WmiObject -Class Win32_ComputerSystem -EnableAllPrivileges
$computerSystem.AutomaticManagedPagefile = $false
$computerSystem.Put() | Out-Null

$pageFileSetting = Get-WmiObject -Class Win32_PageFileSetting
$pageFileSetting.InitialSize = $initialsize
$pageFileSetting.MaximumSize = $maxsize
$pageFileSetting.Put() | Out-Null
