### ISSUE TITLE
chef-client -j can't handle a BOM

### ISSUE THREAD

**Issue by coderanger** [chef/chef#7054]
It would be nice to deal with UTF-8+BOM for Windows-y folks, or maybe even UTF-16+BOM if we're feeling adventurous. On older versions of PowerShell, the `Out-File` cmdlet defaults to UTF-16+BOM and if you ask for `-encoding UTF8` you get UTF-8+BOM (sidebar: whyyyyy?).

**Comment by lamont-granquist** [comment]
![Bomb](http://i0.kym-cdn.com/entries/icons/facebook/000/001/729/x.jpg)
