### ISSUE TITLE
Illegal UTF character test fails after Ruby 2.5.1 upgrade

### ISSUE THREAD

**Issue by tas50** [chef/chef#7100]
After the update to Ruby 2.5.1 the following test in the kitchen travis tests 

```ruby
# this caught a regression in 12.14.70 before it was released when i
# ran it in lamont-ci, so added the test here so everyone else other than
# me gets coverage for this as well.
file "/tmp/chef-test-\xFDmlaut" do
  content "testing illegal UTF-8 char in the filename"
end
```

The failure:
```
  * file[/tmp/chef-test-�mlaut] action create
    
    ================================================================================
    Error executing action `create` on resource 'file[/tmp/chef-test-�mlaut]'
    ================================================================================
    
    ArgumentError
    -------------
    invalid byte sequence in UTF-8
    
    Resource Declaration:
    ---------------------
    # In /opt/kitchen/cache/cookbooks/base/recipes/tests.rb
    
     19: file "/tmp/chef-test-\xFDmlaut" do
     20:   content "testing illegal UTF-8 char in the filename"
     21: end
    
    Compiled Resource:
    ------------------
    # Declared in /opt/kitchen/cache/cookbooks/base/recipes/tests.rb:19:in `from_file'
    
    file("/tmp/chef-test-�mlaut") do
      action [:create]
      default_guard_interpreter :default
      declared_type :file
      cookbook_name "base"
      recipe_name "tests"
      content "testing illegal UTF-8 char in the filename"
      owner nil
      group nil
      mode nil
      path "/tmp/chef-test-\xFDmlaut"
      verifications []
    end
    
    System Info:
    ------------
    chef_version=14.0.183
    platform=amazon
    platform_version=2
    ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
    program_name=/opt/chef/bin/chef-client
    executable=/opt/chef/bin/chef-client
```

Note: This didn't fail in the integration tests in Jenkins. We probably want to get this test into the integration tests so we could fail before promotion.

**Comment by robbkidd** [comment]
Tinkering with it, if I set the [file resource functional tests to use a base file name](https://github.com/chef/chef/blob/a002b8925b302224751e82ece3b84bb28428a449/spec/functional/resource/file_spec.rb#L25) of `file_spëc`, the tests pass.

If I set it to `file_\xFD_spëc`, they bomb with:

```
Errno::EILSEQ:
  file[/Users/rkidd/work/chef/spec/data/test-dir/file_?_spëc20180330-36293-1x0jo4r] (dynamically defined) had an error: Errno::EILSEQ: Illegal byte sequence @ rb_sysopen - /Users/rkidd/work/chef/spec/data/test-dir/file_?_spëc20180330-36293-1x0jo4r
```

Same error on macOS with Ruby 2.5.0 and 2.5.1.

📚 🔍 👀 `\xFD` is apparently UTF-16 and that is indeed an invalid character when the environment has `LANG` set to UTF-8. So, I'm left thinking that this error is correct. It is appropriate to error when "illegal byte sequences" appear in file paths.

I see in [the commit that added this test to the kitchen suite](https://github.com/chef/chef/commit/8779797e6dc67f34eb9fb7bf8908e77d86a70e74), that [`.scrub`](https://ruby-doc.org/core-2.5.0/String.html#method-i-scrub) was used in one spot to replace invalid bytes. Maybe more scrub needs to be rubbed upon the `file` resource and its cousins? Would it be awful to always scrub a string given for a path to the file-ish resources?

**Comment by robbkidd** [comment]
@lamont-granquist Can you share more about the use case this catches in lamont-ci?

**Comment by lamont-granquist** [comment]
i can't quite recall how this situation came up, but the test is operating, and it looks like failing, correctly.

we need to be able to manage files that have filenames that aren't in the default external encoding.  this is important when we have to set the external encoding to UTF-8 in order to read cookbooks and JSON and everything else, but where the encoding on the system is actually latin-1 or windows Japanese weirdness.
