### ISSUE TITLE
fix repair msi functionality

### ISSUE THREAD

**Issue by epackorigan** [chef/chef#7103]
## Description
Chef client installs from MSI on windows does not 'repair' properly if some files have been deleted. 

## Chef Version
`chef-client-13.6.4-1-x64.msi` was used for testing. will confirm with newer version when able.

## Platform Version
Windows 10 x64 fully updated.

## Replication Case
* Install the client, requesting specific feature (i don't believe it's important which one)
`msiexec /i C:\temp\chef-client-13.6.4-1-x64.msi /qn ADDLOCAL="ChefClientFeature,ChefSchTaskFeature,ChefPSModuleFeature"`
* Delete one of the files from the install:
`del C:\opscode\chef\bin\knife.bat`
* Attempt a repair of the package to restore the deleted file:
`msiexec /fa C:\temp\chef-client-13.6.4-1-x64.msi /qn REINSTALL=ALL REINSTALLMODE=vamus`
* Note the the file is not restored:
`dir C:\opscode\chef\bin\knife.bat`

## Client Output
no relevant output from chef-client. `Eventvwr` shows the following entries:
```
Product: Chef Client v13.6.4 -- Configuration completed successfully.

Windows Installer reconfigured the product. Product Name: Chef Client v13.6.4. Product Version: 13.6.4.1. Product Language: 1033. Manufacturer: Chef Software, Inc.. Reconfiguration success or error status: 0.

Ending a Windows Installer transaction: {F8E65571-5C6A-4470-BB6F-0B3BCFDCD586}. Client Process Id: 6700.
```

I also tried a few repair switches (/fa /fp among others), without the `REINSTALL`/`REINSTALLMODE` property, with the mode set to `vamus` and `vomus`, and with `ADDLOCAL` setup the same as the install. In addition, the actual UI button in the `add/remove program` appears to have the same behavior. None of them appear to restore the missing file(s).

**Comment by epackorigan** [comment]
it seems that the condition for 'fastunzip' is not correct here:

https://github.com/chef/chef/blob/9c0b576af2803ffcec616d031594c40643d81749/omnibus/resources/chef/msi/source.wxs.erb#L101

It might be as simple as:

```
<Custom Action="FastUnzip" After="InstallFiles">NOT Installed or REINSTALL</Custom>
```

so that the `FastUnzip` custom action is run when doing a repair.

**Comment by epackorigan** [comment]
This may not be perfect as a fix, as the cheflog.dll is being used, which may cause the unzip to fail while trying to rewrite that file to disk.

**Comment by epackorigan** [comment]
Initial testing shows that the cheflog.dll is not a problem with the fix above, as long as there is no current chef-client run in progress. I'll be trying to work on simulating the chef-run-in-progress situation later today when in front of a proper computer...

**Comment by epackorigan** [comment]
`msiexec /i chef-client-<newversion>.msi /qn ADDLOCAL="ChefClientFeature,ChefSchTaskFeature,ChefPSModuleFeature"` appear to also work properly as an upgrade from a previous version, though i'm not sure how to check if the components are being properly re-registered with the system or not. (chef-client ran just fine with my current setup).

**Comment by tas50** [comment]
This was fixed in both Chef 13 and 14.
