### ISSUE TITLE
windows_registry doesn't support editing REG_NONE registry type

### ISSUE THREAD

**Issue by sarahbakal** [chef/chef#7105]
## Description
chef-client errors when a registry key of type REG_NONE is a child value of a key that is being modified.

## Chef Version
13.8.5

## Platform Version
Windows Server 2016

## Replication Case
Create a key with type REG_NONE (using a .reg file like below)
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters]
"ReservedPorts"=hex(0):35,00,37,00,32,00,33,00,2d,00,35,00,37,00,32,00,33,00,\
  35,00,37,00,32,00,34,00,2d,00,35,00,37,00,32,00,34,00,00,00,35,00,31,00,39,\
  00,30,00,35,00,2d,00,35,00,31,00,39,00,30,00,38,00,00,00,00,00
```

Use chef to modify a registry key under 'HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters'
for example 

```
  registry_key '2016_HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters' do
    key 'HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Tcpip\Parameters'
    values [
      { name: 'TcpMaxDataRetransmissions', type: :dword, data: 3 },
    ]
    recursive true
    action :create
  end
```
## Stacktrace

See attachment
[reg_none_error.txt](https://github.com/chef/chef/files/1868831/reg_none_error.txt)

**Comment by NAshwini** [comment]
Hi @sarahbakal,

As per the above steps I have created `registry_key` & tried to modify it by chef recipe which is working successfully. Can you please give us the exact error message as in `reg_none_error.txt` it's not clear or steps to reproduce the issue. 

Thank You!!
Regards,
Ashwini

**Comment by sarahbakal** [comment]
@NAshwini,  i can reproduce it on 13.8.5 but not the latest 14. so I guess it was resolved at some point.
