### ISSUE TITLE
Chef-14: service :enable does not work on ubuntu 14.04

### ISSUE THREAD

**Issue by ccrebolder** [chef/chef#7119]
## Description
When I use the `:enable` action to a `service` resource in Ubuntu 14.04 the service is not actually enabled. The integration test for `should be_enabled` fails and I have confirmed the service is not running after rebooting the machine.

## Chef Version
Chef: 14.0.190

## Platform Version
I am using `bento/ubuntu-14.04     (virtualbox, 2.2.9)` in Test Kitchen.

## Replication Case
I discovered this with a private cookbook, but I can replicate using the master branch of the chef-client cookbook, which contains a test to verify the service is enabled.
```
$ kitchen verify service-upstart-ubuntu-1404                                                                                                                                                                                 
-----> Starting Kitchen (v1.17.0)
-----> Setting up <service-upstart-ubuntu-1404>...
       Finished setting up <service-upstart-ubuntu-1404> (0m0.00s).
-----> Verifying <service-upstart-ubuntu-1404>...
       Loaded tests from {:path=>"/home/creboldc/cookbooks/chef-client/test/integration/service_upstart"} 

Profile: tests from {:path=>"/home/creboldc/cookbooks/chef-client/test/integration/service_upstart"}
Version: (not specified)
Target:  ssh://vagrant@127.0.0.1:2222


  Processes chef-client
     ✔  should exist
  Service chef-client
     ∅  should be enabled
     expected that `Service chef-client` is enabled
     ✔  should be installed
     ✔  should be running

Test Summary: 3 successful, 1 failure, 0 skipped
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Verify failed on instance <service-upstart-ubuntu-1404>.  Please see .kitchen/logs/service-upstart-ubuntu-1404.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

## Client Output
The chef-client run tries to enable the service every run.

Let me know if more logs or stacktrace is needed.

**Comment by trappar** [comment]
Seeing this as well going. :enable worked as of chef-client 13.8.5 but is failing using 14.0.190 for me, also on Ubuntu 14.04.
