### ISSUE TITLE
Chef-14: macos_userdefaults resource cannot properly compare integers/strings/booleans

### ISSUE THREAD

**Issue by erikng** [chef/chef#7131]
## Description
Because of the dependence on the `defaults` binary for reading plist values, values read may be incorrect, leading to chef's inability to correct an invalid value.

This bug is also present in the mac_os_x cookbook, however throughout all of these years no one must have noticed it. It wasn't until I was debugging the new macos_userdefaults resource that I stumbled upon this.

From my testing, this is only a bug when attempting to compare integers, strings and booleans.

## Chef Version
14.0.190

## Platform Version
macOS 10.13.4

## Replication Case
Set a value to a boolean, string or integer that would return the same style of information.

```
macos_userdefaults 'com.apple.commerce' do
  domain '/Library/Preferences/com.apple.commerce'
  key 'AutoUpdate'
  value true
end
```

change the recipe to use a different type, but with the same information

(integer)
```
macos_userdefaults 'com.apple.commerce' do
  domain '/Library/Preferences/com.apple.commerce'
  key 'AutoUpdate'
  value 1
end
```

(string)
```
macos_userdefaults 'com.apple.commerce' do
  domain '/Library/Preferences/com.apple.commerce'
  key 'AutoUpdate'
  value 'true'
end
```

chef-client will think the key is correctly set. This is because the resource shells out to the `defaults` binary, which in this case will return a `1` for any of these values.

## Potential ideas for fixes
1. Easy - read the plist directly for manipulation. There could be flaws with this approach as sometimes preferences can be "cached" due to `cprefsd`. You would also need to handle binary plists
2. Hard - use the approach Python developers and create a a ruby bridge around the CoreFoundation API. This would allow you to read the values directly as an application would. This allows for cross-domain reading of keys (user/device domain).

**Comment by erikng** [comment]
Bumping this because of https://github.com/chef/chef/issues/10075 and https://github.com/chef/chef/issues/10083

Without a proper way to manage preferences, we may need to deprecate chef for these specific types of tasks.

**Comment by btm** [comment]
Chef 16.3 shipped with a rewritten macos_userdefaults resource as a short term improvement, but we believe we need to write a library to the preferences API for full coverage. That's represented in https://github.com/chef/chef/issues/10083.

**Comment by tas50** [comment]
Closing this in favor of the larger issue to use APIs directly
