### ISSUE TITLE
databags not been used at node

### ISSUE THREAD

**Issue by ReK2Fernandez** [chef/chef#7132]
### Cookbook version
latest 5.3.1

### Chef-client version
 chef-client -v
Chef: 13.8.5

### Platform Details
server is latest with ubuntu and node im testing with is centos

### Scenario:
I bootstraped and adding current users to be manage under chef.
I did not expect any changes with current users.. but it did not modify the comment information
after this Im trying to create with chef a total new user called testuser with no success
it just creates the groups

### Steps to Reproduce:
always
### Expected Result:
add new users, modify current users
### Actual Result:
nothing happens, runs and says nothing to change after the first time that added the groups.
run chef-client in :debug mode and no mention of errors nor reading databags or trying to create users at all.. like invisible
### Extra more details.
I follow the instructions on here, on the front page.
I include the users cookbook into my made from scrach cookbook
where I include in the metadata file the users cook book

example default.rb

```
include_recipe "users"

users_manage 'mygroup' do
  group_id 2000
  action [:create]
  data_bag 'MYUSERSDATABAG'
end
```
the other 2-3 groups are setup the same way with diff databags with users for that group
like I say, I am fine with the current users not been modified but new users are not getting  even created..

 Also added action create inside the item in the databags, no luck
I created t he default databag users and put the people in there, no luck
I enabled :debug searched results looking for errors... nothing.
I am starting to think is just plain ignoring the databags, like not even trying to read them.
Also I made sure the key is on /etc/chef/encrypted_data_bag_secret
I read the documentation over and over, here and on chef site... cant see what is wrong..

**Comment by cheeseplus** [comment]
The issue was already opened https://github.com/chef-cookbooks/users/issues/420 and isn't a core chef issue. Closing this as a dupe/not applicable.
