### ISSUE TITLE
Rubocop Lint/AssignmentInCondition error in lib/chef/http.rb

### ISSUE THREAD

**Issue by bugok** [chef/chef#7150]
## Description
Ran rubocop, and found as assignment within an if condition: https://github.com/chef/chef/blob/master/lib/chef/http.rb#L381

## Chef Version
master

## Platform Version
Irrelevant

## Replication Case
Look at source control

## Client Output
Irrelevant

**Comment by lamont-granquist** [comment]
We don't use rubocop on this repo, we use chefstyle, and that if condition is working as-intended.
