### ISSUE TITLE
chef-config 14.0.202 is not yet available on rubygems.org

### ISSUE THREAD

**Issue by sunpoet** [chef/chef#7163]
chef 14.0.202 is the latest version. It is downloadable on [rubygems.org](https://rubygems.org/gems/chef/versions/14.0.202) but its dependency (chef-config = 14.0.202) is not yet available.

**Comment by thommay** [comment]
Done https://rubygems.org/gems/chef-config/versions/14.0.202

**Comment by sunpoet** [comment]
Thank you!
