### ISSUE TITLE
Chef14: broken powershell version check

### ISSUE THREAD

**Issue by ttdgcp** [chef/chef#7166]
## Description
The PowerShell version check located [here](https://github.com/chef/chef/blob/master/lib/chef/provider/package/powershell.rb#L39) somehow breaks in Chef v14 (both 14.0.190 and 14.0.202). In all Chef v12 and v13 versions, this issue does not present itself.

On Windows Server 2016 with PowerShell 5.1 installed, the check fails with:
```Minimum installed Powershell Version required is 5```

This is despite PowerShell returning "5" for $PSVersionTable.PSVersion.Major.

I have been testing using the powershell_package resource:
`powershell_package xWebAdministration`

## Chef Version

14.0.190 and 14.0.202

## Platform Version

Windows Server 2016, chef client v14

## Replication Case

Windows Server 2016 image, using v14 chef-client
Install any package using powershell_package
It will fail with minimum installed version error

## Client Output

```
================================================================================
           Error executing action `install` on resource 'powershell_package[xwebadmin package]'
           ================================================================================

           RuntimeError
           ------------
           Minimum installed Powershell Version required is 5

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/cookbook/recipes/baseline.rb

            21: powershell_package 'xwebadmin package' do
            22:   package_name 'xWebAdministration'
            23:   version '1.19.0.0'
            24: end
            25:

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/cookbook/recipes/baseline.rb:21:in `from_file'

           powershell_package("xwebadmin package") do
             package_name ["xWebAdministration"]
             action [:install]
             default_guard_interpreter :default
             declared_type :powershell_package
             cookbook_name "cookbook"
             recipe_name "baseline"
             version ["1.19.0.0"]
           end

           System Info:
           ------------
           chef_version=14.0.202
           platform=windows
           platform_version=10.0.14393
           ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
           program_name=C:/opscode/chef/bin/chef-client
           executable=C:/opscode/chef/bin/chef-client
```

**Comment by stuartpreston** [comment]
Repro'd on my machine, error only appears via execution of the resource.  `powershell_out` is behaving as expected.  We are investigating.
