### ISSUE TITLE
subcommand-specific settings support in ~/.chef/credentials

### ISSUE THREAD

**Issue by scopenco** [chef/chef#7168]
Thank you for implementation https://github.com/chef/chef/pull/6660 but i found a little bug in it.
If I try to set subcommand-specific settings like
```
knife[:ssh_user] = 'user1'
```
It returns me the error:
```
ERROR: CONFIGURATION ERROR:Unable to parse Credentials file: /Users/user1/.chef/credentials

parse error on value "[" ("[")
```
The workaround will be to use `case` statement in ~/.chef/knife.rb like
```
case File.basename(client_key)
when 'mykey.pm'
  knife[:ssh_user] = 'user1'
end
``` 

Anyway, I think this should be fixed in credentials parser.

```
$ chef -v
Chef Development Kit Version: 2.5.3
```

**Comment by coderanger** [comment]
This is now supported via either hash keys or (preferably) subtables in the TOML:

```toml
[default]
# ...
[default.knife
ssh_user = "user1"
```
