### ISSUE TITLE
rhsm_register force option doesn't work.

### ISSUE THREAD

**Issue by donwlewis** [chef/chef#7171]
## Description
rhsm_register resource does not perform force register when force value is set to true.

## Chef Version
Not Sure

## Platform Version
RHEL7

## Replication Case
Set the force value to true for the `rhs_regsiter` resource, and after the machine has registered, the next time it runs, it won't register again.

## Client Output
N/A

## Stacktrace
N/A

I apologize for the lack of information here, but based on what I am seeing in the `rhsm_register` resource, this resource will suffer from the same that I posted about here:

https://github.com/chef-partners/redhat-subscription-manager-cookbook/pull/43

I do not currently have a setup to test with Chef 14, so I will try and get something stood up so I can.

**Comment by tas50** [comment]
Fixed by https://github.com/chef/chef/pull/7193. Thanks for the issue with the link
