### ISSUE TITLE
Using Chef 14 resource windows_feature to install IIS on a supported platform generates an error.

### ISSUE THREAD

**Issue by joshburt** [chef/chef#7177]
## Description

- Using the newly added resource windows_feature to install IIS on a supported platform generates an error.
- Note that this same failure can be seen when calling the default recipe of the IIS community cookbook.

## Chef Version
14.0.202

## Platform Version
Windows Server 2016 Core and DE (Desktop Experience)

### This is easy to reproduce with a single resource call:

```
windows_feature 'IIS-WebServerRole' do
  all true
  action :install
end
```

### This can also be reproduced by running the default recipe from the current IIS cookbook.  
```
runlist: 'recipe[iis]'
```

## Client Output
https://gist.github.com/joshburt/f1543f7c58b470148cc7a44a275ed636

## Stacktrace
https://gist.github.com/joshburt/f8f233a5e1c44ddfec6f1f981145d06b

**Comment by joshburt** [comment]
Found the issue.  Its in https://github.com/chef/chef/blob/master/lib/chef/resource/windows_feature_dism.rb

So for Windows there is both a 32 and 64-bit installer.  It appears that running the 32-bit install on windows causes the DISM.exe targeted to be 32-bit.  This is failing.

Line 175:
```
raw_list_of_features = shell_out("dism.exe /Get-Features /Online /Format:Table /English").stdout
```

This actually returns:
```
Deployment Image Servicing and Management tool
Version: 10.0.14393.0
Error: 11
You cannot service a running 64-bit operating system with a 32-bit version of DISM.
Please use the version of DISM that corresponds to your computer's architecture.
The DISM log file can be found at C:\Windows\Logs\DISM\dism.log
```

**Comment by stuartpreston** [comment]
@joshburt Is there anything preventing you moving to the 64-bit client?  We made a conscious decision to simplify the logic around locating dism.exe by using the dism.exe located in the path by default, and the 32-bit client will disappear from the downloads site at some point TBC.  

To get past your issue, we would encourage you to switch to using the PowerShell `windows_feature` and use the Name field as supplied by `Get-WindowsFeature`), e.g.:

```ruby
windows_feature 'Web-Server' do
  all true
  action :install
  install_method :windows_feature_powershell
end
```

![image](https://user-images.githubusercontent.com/6384654/39246920-dae88810-488f-11e8-8859-c1788432ae67.png)
