### ISSUE TITLE
Kitchen converge error:  No candidate version available for httpd

### ISSUE THREAD

**Issue by jinky07** [chef/chef#7182]
Hi,

May I ask for your assistance? We are trying the exercise in learn.chef.io modules about test kitchen for linux. However, we are getting error when trying to do kitchen converge.
Kindly see below error.

-----> Starting Kitchen (v1.20.0)
-----> Converging <default-rhel-7>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 6.3.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
-----> Chef Omnibus installation detected (install only if missing)
       Transferring files to <default-rhel-7>
       Starting Chef Client, version 12.16.42
       resolving cookbooks for run list: ["learn_chef_httpd::default"]
       Synchronizing Cookbooks:
         - learn_chef_httpd (0.1.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       Converging 5 resources
       Recipe: learn_chef_httpd::default
         * yum_package[httpd] action install
           * No candidate version available for httpd
           ================================================================================
           Error executing action `install` on resource 'yum_package[httpd]'
           ================================================================================

           Chef::Exceptions::Package
           -------------------------
           No candidate version available for httpd

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/learn_chef_httpd/recipes/default.rb

             7: package 'httpd'
             8:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/learn_chef_httpd/recipes/default.rb:7:in `from_file'

           yum_package("httpd") do
             package_name "httpd"
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :package
             cookbook_name "learn_chef_httpd"
             recipe_name "default"
             flush_cache {:before=>false, :after=>false}
           end

           Platform:
           ---------
           x86_64-linux

       Running handlers:
       [2018-04-24T07:45:12-05:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-04-24T07:45:12-05:00] ERROR: Exception handlers complete
       Chef Client failed. 0 resources updated in 14 seconds
       [2018-04-24T07:45:12-05:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-04-24T07:45:12-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-04-24T07:45:12-05:00] ERROR: yum_package[httpd] (learn_chef_httpd::default line 7) had an error: Chef::Exceptions::Package: No candidate version available for httpd
       [2018-04-24T07:45:12-05:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-rhel-7>.  Please see .kitchen/logs/default-rhel-7.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

We are using AWS as our virtual environment. 

Appreciate your feedback on this.

Thanks.
Jinky

**Comment by thommay** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
