### ISSUE TITLE
no_lazy_load false network connectivity performance regression in chef 13

### ISSUE THREAD

**Issue by pudquick** [chef/chef#7185]
## Description
Using no_lazy_load false for cookbook_file/remote_directory resources on Chef 13 seems to cause a considerable number of additional TCP connections and bandwidth usage compared to Chef 12.

## Chef Version
```
chef-client --version
Chef: 13.8.5
```

## Platform Version
macOS 10.13.4

## Replication Case
- Edit /etc/chef/client.rb and set no_lazy_load false
- Run a cookbook thats uses a remote_directory resource. For instance:
```
# Cookbook: default.rb
rd = remote_directory '/tmp/rd_test' do
  source 'some/folder'
  owner 'root'
  group 0
  mode 0755
  purge true
  recursive true
  action :nothing
end

rd.run_action(:create)
```
- This remote_directory resource should have 50 or more files located inside it to begin to see the impact.
- Perform a packet capture during a chef-client run, then compare activity between `false` and `true` settings.

**Comment by pudquick** [comment]
When we originally opened issue #6051, no_lazy_load false was not supported for remote_directory in chef 13 at all. It was very helpful to see it implemented, thank you!

However, now that we are doing client rollout with it, we've noticed a considerably different network connectivity load from chef 13 clients.

Wireshark captures, for an example run, showed 17 total TCP connections opened during the chef 13 client run with no_lazy_load `true` - and over 600 TCP connections when set to `false`.

This has resulted in considerable additional load on the chef servers themselves when attempting to use no_lazy_load false in the client.rb.

Having this setting as `false` in chef 12 did not appear to have the same performance impact. I'm working on collecting traces for it now for direct comparison with the same cookbook set.

Is there an implementation reason / difference why we would see such a performance hit for chef 13?

**Comment by pudquick** [comment]
Having performed the same analysis with chef-client 12.21.31:

- `no_lazy_load true` with the same cookbook comparison used for chef 13: identical number of TCP connections as chef 13 (under 20). And similar total byte transfer / raw bandwidth.
- `no_lazy_load true` on chef 12.21.31: Only **7** TCP connections (less, not more), and a total raw byte transfer with the chef server of 10% (again less, not more) compared to the `true` run.

So in summary:
- On chef-client 12, using `no_lazy_load false` with our remote_directory configuration represented a 90% bandwidth saving and 50%+ TCP connection saving vs chef-client `no_lazy_load true` runs.
- On chef-client 13, using `no_lazy_load false` with our remote_directory configuration represented a 100%+ bandwidth **increase** and a ~40 fold increase in the number of TCP connections - completely the opposite effect from what was observed in chef 12.

**Comment by coderanger** [comment]
@pudquick What's your specific reason for wanting lazy file loading? We've mostly ignored it as a very appendix-y feature and should probably talk about removing it given it's structurally incompatible with a lot of Chef usage (due to expiring links and long converges).

**Comment by jaymzh** [comment]
@coderanger because downloading the entire of every single cookbook is something we don't want. There's TONS of sourcefiles and template sources we don't use. There's no reason to download them, and they shouldn't be downloaded.

**Comment by coderanger** [comment]
@jaymzh Yeah, I only noticed @pudquick is a FBer after posting that :) Y'all are in that appendix-y niche for sure ;-)

**Comment by jaymzh** [comment]
@coderanger I'd argue it's the right for most places. By definition you don't know what recipes you're going to descend and thus don't know what sourcefiles you will need. I always that it was crazysauce it was changed.

**Comment by coderanger** [comment]
@jaymzh In the abstract, yes. But the realities of expiring S3-style signed URLs are a harsh boundary condition and it turned out non-lazy-loading was super useful for stuff like compat_resource and Halite-style cookbooks so we just kind of rolled with it as the default :)

**Comment by pudquick** [comment]
@thommay This looks like a great change, thank you.

Since 13 is still supported and we see this regression in 13, will an updated 13 release also incorporate this fix?
