### ISSUE TITLE
Enhance Request: support cookbook dependencies with chef-apply or chef-client -z

### ISSUE THREAD

**Issue by darkn3rd** [chef/chef#7188]
## Description

Simple use case: Run a chef recipe to do cloud provisioning, with Google's `google-gcompute` cookbook.

I did not want to create a full chef-repo with cookbook, and then run something like `chef-apply gce.rb` or `chef-client -z gce.rb`.

Also, there the general use case, where someone might want to use a resource or cookbook outside the limited core set shipped with ChefDK.  Cloud provisioning is definitely one use case.

## Chef Version

ChefDK 2.5.3

## Platform Version

Ubuntu 16.04

## Replication Case

```ruby
# .chef/knife.rb
chef_repo = File.join(File.dirname(__FILE__), '..')
cookbook_path "#{chef_repo}/berks-cookbooks"
```

```ruby
# Berksfile
source 'https://supermarket.chef.io'
source chef_repo: "berks-cookbooks"

cookbook 'google-gcompute', '~> 0.1.1'
```

```ruby
# gce.rb
gauth_credential 'default_cred' do
  action :defaultuseraccount
end

gcompute_machine_type 'n1-standard-1' do
  action :create
  zone 'us-east1-b'
  credential 'default_cred'
end
```

```bash
# chef-client -z way
berks vendor
chef-client -z gce.rb

# chef-apply way
berks vendor
chef-apply gce.rb
```

### chef-client -z
```
[2018-04-25T22:08:53-07:00] DEBUG: Re-raising exception: NoMethodError - undefined method `gauth_credential' for #<Chef::Recipe:0x0000000002a48088>
/home/joaquin/projarea/simple-elasticsearch/ninjapants-google/chef-gcompute/gce_instances.rb:3:in `from_file'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/mixin/from_file.rb:30:in `instance_eval'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/mixin/from_file.rb:30:in `from_file'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/run_context.rb:362:in `load_recipe_file'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/policy_builder/expand_node_object.rb:100:in `block in setup_run_context'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/policy_builder/expand_node_object.rb:99:in `each'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/policy_builder/expand_node_object.rb:99:in `setup_run_context'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/client.rb:513:in `setup_run_context'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/client.rb:281:in `run'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application.rb:292:in `block in fork_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application.rb:280:in `fork'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application.rb:280:in `fork_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application.rb:245:in `block in run_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/local_mode.rb:44:in `with_server_connectivity'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application.rb:233:in `run_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application/client.rb:469:in `sleep_then_run_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application/client.rb:458:in `block in interval_run_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application/client.rb:457:in `loop'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application/client.rb:457:in `interval_run_chef_client'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application/client.rb:441:in `run_application'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application.rb:59:in `run'
  /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/bin/chef-client:26:in `<top (required)>'
  /usr/bin/chef-client:250:in `load'
  /usr/bin/chef-client:250:in `<main>'
[0m
```

### chef-apply

```
[2018-04-25T22:11:57-07:00] DEBUG: NoMethodError: undefined method `gauth_credential' for cookbook: (chef-apply cookbook), recipe: (chef-apply recipe) :Chef::Recipe
gce_instances.rb:3:in `run_chef_recipe'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application/apply.rb:192:in `instance_eval'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application/apply.rb:192:in `run_chef_recipe'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application/apply.rb:204:in `run_application'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/lib/chef/application/apply.rb:216:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.8.5/bin/chef-apply:25:in `<top (required)>'
/usr/bin/chef-apply:250:in `load'
/usr/bin/chef-apply:250:in `<main>'
```

**Comment by coderanger** [comment]
This is out of scope for both of those modes. chef-apply is for very simple scripting and there aren't really well-defined semantics for how dependency loading would even work. Similarly the single-recipe mode in chef-client is mostly a hack and breaks the majority of our model. The correct way to do this is to create a top-level cookbook and run things from that. There is also the `chef provision` command in ChefDK specifically for use with chef-provisioning that simplifies the execution slightly.

**Comment by darkn3rd** [comment]
Basically, **TL;DR** `chef-apply recipe.rb` and `chef -z recipe.rb` are too limited with current official resources bundled with install of Chef, so cookbook dependency supported needed to make those useful.

I wanted to experiment with the officially coded/support Google Chef cookbook without need for chef-repo + cookbook, something quite common with outside Chef ecosystem.  Currently, Chef is promoting Terraform over `chef provision` in the community.  As it stands, Chef is not currently competitive (feature parity) with bundled configurable resources, and it hasn't been a market leader with Chef Provision.  

I came across only two in the industry using Chef Provision, where one was spending incredible amount of time maintaining it, keeping up or working around new releases and bugs, and another that wanted to move off of Chef Provision ASAP.

**Comment by coderanger** [comment]
@darkn3rd `chef-apply` is mostly aimed at very new users working with the Learn Chef tutorials, to introduce them to the very basics of Chef without having to dive in to what cookbooks are and all the workflow stuff around that. There was some idea that maybe it could be useful for shebang-style scripts but as community cookbooks have become more and more important over time, that use case dropped off (as you've now noticed). We are working on porting a lot of commonly used resources back to Chef core though, which might revive that use case a bit. Chef-provisioning is bundled with Chef itself for this reason too. As for the single-recipe mode of chef-client, it's largely a historical hack and we leave it be because it doesn't hurt any "normal" use cases. It is not intended to be a replacement for `chef-solo`. Chef as a community absolutely does not promote chef-provisioning and `chef provision` _over` Terraform, in fact we usually say the opposite, but continue to keep chef-provisioning alive as it's undeniably useful for people that have major investments in it or in the Chef ecosystem more broadly. Terraform is an A++ tool and we heartily encourage its use if you find it a better fit for your desired workflow :D

**Comment by coderanger** [comment]
As for using Chef code without making a cookbook, that is not really a thing. You'll need to create a cookbook.

**Comment by darkn3rd** [comment]
Understood.  Logistically, code being what it is, that makes sense.  Thanks for understanding the issue with limited resources.  Currently, embedded resources dwarf the competition.

On cloud provisioning, in my experiments, just exploring what Google offers, I couldn't recommend a solution that adds the complexity.  With tools like Ansible or Terraform, it can be a single small script, and your off to creating cloud resources.   With Chef, it is not (not technically challenging for my background, but complex for new comers).  

As for Chef Provisioning (miss the Chef Metal name), I only came across two cases in the industry and they weren't positive experiences.   For a time, the underlying fog driver didn't support new AWS long id (hopefully fixed).

**Comment by lamont-granquist** [comment]
I think @coderanger covered it.  I don't know what the code would look like in order to support cookbook dependencies in chef-apply and that would certainly require an [RFC](https://github.com/chef/chef-rfc)
