### ISSUE TITLE
Add skip_publisher_check to powershell_package resource

### ISSUE THREAD

**Issue by kitforbes** [chef/chef#7212]
This resource installs a PowerShell module through the PowerShell Package Manager. There are a few modules within the PSGallery that require the `-SkipPublisherCheck` switch to be added to the `Install-Module` command. I have noticed that the Chef run will not fail when PowerShell raises the exception in this case and will make it appear as though the module was successfully installed.

Some more details on this can be found in this [PowerShell Team blog post](https://blogs.msdn.microsoft.com/powershell/2016/09/29/powershellget-and-packagemanagement-in-powershell-gallery-and-github/) from 2016.

**Comment by tas50** [comment]
@Happycoil Fixed this up and it's been merged to master.
