### ISSUE TITLE
Habitat plan doesn't pin the Ruby version

### ISSUE THREAD

**Issue by jsirex** [chef/chef#7213]
Hello!

I'm investigation habitat and look into projects to learn how it can be done well.
But I see some minor issues:
In the plan defined dependency: `core/ruby`. So latest available version of ruby will be used.
So ruby version can change during minor build to a major version, because it wasn't pinned to something like 2.x, 2.5.x, etc: https://github.com/chef/chef/blob/master/habitat/plan.sh#L11
On other hand I see hard-coded version 2.3.0 in path: https://github.com/chef/chef/blob/master/habitat/hooks/run#L2

I'm very new to habitat, so may be I'm wrong here.

**Comment by tas50** [comment]
This does seem like an issue. Thanks for the report @jsirex
