### ISSUE TITLE
Route resource should support platforms other than Linux

### ISSUE THREAD

**Issue by tas50** [chef/chef#7241]
At the moment we support Linux. We should support additional platforms in this resource.

**Comment by tas50** [comment]
I'm going to close this one out at this point as a won't fix. It's an issue, but it's not something that fits into our current priority. If someone in the community wants to cleanup the route resources we'd gladly accept those changes, but the Infra Client team won't be completing that work.

**Comment by mbaitelman** [comment]
@tas50 I built https://github.com/mbaitelman/windows_route but couldnt figure out how to get it into chef/chef.
