### ISSUE TITLE
Consider updating GCC in build_essential for Solaris

### ISSUE THREAD

**Issue by tas50** [chef/chef#7245]
We currently pin this to version "4.8.2" with a note that we're not ready for 5.0. This probably isn't what most people would expect. I believe this was an internal decision for our builders.

**Comment by tas50** [comment]
@scotthain I know we added that pin based on our internal usage of the resource for build machines. Is that still a thing we should be doing?

**Comment by scotthain** [comment]
@tas50 4.8 was the latest when we did the original setup all those years ago - it looks like 5.3 is available now - I'll see if we can upgrade internally.

**Comment by tas50** [comment]
Thanks @scotthain

**Comment by tas50** [comment]
@scotthain did you get a chance to try this out?

**Comment by scotthain** [comment]
@tas50 I believe we looked into this and ran into blocking/showstopper issues for maintaining backwards compatibility - @jaymalasinha do you have the details?

**Comment by lamont-granquist** [comment]
This should get done for Chef-16 and a way to pin it back needs to be exposed in case we need it internally (and other people likely need it externally)
