### ISSUE TITLE
hostname resource will continually reboot if Windows a domain member

### ISSUE THREAD

**Issue by smastrorocco** [chef/chef#7255]
## Description
new Chef 14 hostname will continually detect drift on name if node is domain member

## Chef Version
v14.1.1

## Platform Version
Windows Server 2012 R2

## Replication Case
Set hostname resource on a Windows node that is a domain member

I believe this is because of this:
https://github.com/chef/chef/blob/92d85cf4c67680d778cbe8bc5c676f9a10fa1442/lib/chef/resource/hostname.rb#L220

```ruby
# update via netdom
declare_resource(:powershell_script, "set hostname") do
  code <<-EOH
    $sysInfo = Get-WmiObject -Class Win32_ComputerSystem
    $sysInfo.Rename("#{new_resource.hostname}")
  EOH
  notifies :request_reboot, "reboot[setting hostname]"
  not_if { Socket.gethostbyname(Socket.gethostname).first == new_resource.hostname }
end
```

The guard should probably look at either the output of the command `hostname` or the environment variable ENV['COMPUTERNAME'].  Either way Socket.gethostname will return the FQDN in Windows which will not match the requested hostname.

**Comment by marcosdiez** [comment]
I "solved" my problem like this ( please notice that node['name'] is properly set for me during chef bootstrap, but you can use any other variable instead) :

``` 
if node['hostname'] != node['name']
  # without this IF, we get a reboot loop. lovely !
  # and it seems this is a known 2 year old bug
  # https://github.com/chef/chef/issues/7255
  hostname 'chef_hostname' do
    hostname node['name']
    windows_reboot true
    action :set
  end
end
```

**Comment by tas50** [comment]
We've reworked how we set the hostname on windows for the upcoming Chef Infra Client 17.1 release. This update takes into account changing the hostname on domain attached systems. I'm going to close this issue out at this point. If you run into any issues with 17.1 or later feel free to open a new issue and we'll continue to dig in.
