### ISSUE TITLE
Gpg public key for signed chef-client rpm not publically available

### ISSUE THREAD

**Issue by mrsipan** [chef/chef#7271]
I have looked in this repository as well as in the main chef sites and I have failed to find the public key for the rpms available at the main [download site](https://downloads.chef.io/chef).

## Description

_Public key_ for signed rpms not available.

## Chef Version

`13.*.* - 14.*.*`
## Platform Version

- Redhat
- Centos
- Oracle linux

## Client Output

```
warning: rpmts_HdrFromFdno: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
```

**Comment by thommay** [comment]
https://docs.chef.io/packages.html#package-repositories ; https://packages.chef.io/chef.asc
