### ISSUE TITLE
windows_task: backslash in command property

### ISSUE THREAD

**Issue by ttdgcp** [chef/chef#7277]
## Description
The new windows_task in chef client v14 does not correctly parse backslashes in the command property- they end up being erased in the task on the node.

## Chef Version
14.1.2

## Platform Version
Windows Server 2016, running Chef as SYSTEM

## Replication Case
Use the windows_task resource and include backslashes in the command property, example:
```
windows_task 'test' do
  cwd 'C:\'
  command 'Powershell.exe -ExecutionPolicy Bypass C:\foo\bar\blah\script.ps1'
  run_level :highest
  frequency :daily
end
```
The resulting task has the resulting arguments:
```Powershell.exe -ExecutionPolicy Bypass C:foobarblahscript.ps1```

## Client Output
chef-client does not fail, it creates the resource incorrectly.

**Comment by Vasu1105** [comment]
@ttdgcp when passing wndows file path sent that in double quotes and slash as double back slash e.g. "C:\\folder\\file.exe"

**Comment by tas50** [comment]
Closing this since we merged in the fix. Thanks for the report @ttdgcp
