### ISSUE TITLE
systemd-managed chef-client service fails to resolve DNS after glibc update

### ISSUE THREAD

**Issue by mathewcrane** [chef/chef#7285]
## Description

After an update of the following packages, runs invoked by the systemd service 'chef-client' are unable to make DNS requests to upstream forwarders. /etc/hosts entries continue to work normally. A restart of the chef-client service is required for the nodes to start converging again. This causes the clients to become marooned from the chef server.

```
$ rpm -qa --last | head -25
glibc-2.17-222.el7.i686                       Thu 17 May 2018 06:00:28 PM UTC
python-perf-3.10.0-862.2.3.el7.x86_64         Thu 17 May 2018 06:00:27 PM UTC
microcode_ctl-2.1-29.0.2.el7.x86_64           Thu 17 May 2018 06:00:27 PM UTC
openssl-1.0.2k-12.0.1.el7.x86_64              Thu 17 May 2018 06:00:26 PM UTC
kernel-tools-3.10.0-862.2.3.el7.x86_64        Thu 17 May 2018 06:00:26 PM UTC
dbus-1.10.24-7.0.1.el7.x86_64                 Thu 17 May 2018 06:00:25 PM UTC
kernel-3.10.0-862.2.3.el7.x86_64              Thu 17 May 2018 06:00:24 PM UTC
glibc-headers-2.17-222.el7.x86_64             Thu 17 May 2018 06:00:20 PM UTC
glibc-devel-2.17-222.el7.x86_64               Thu 17 May 2018 06:00:20 PM UTC
kernel-headers-3.10.0-862.2.3.el7.x86_64      Thu 17 May 2018 06:00:19 PM UTC
linux-firmware-20180220-62.git6d51311.0.1.el7.noarch Thu 17 May 2018 06:00:18 PM UTC
openssl-libs-1.0.2k-12.0.1.el7.x86_64         Thu 17 May 2018 06:00:09 PM UTC
kernel-tools-libs-3.10.0-862.2.3.el7.x86_64   Thu 17 May 2018 06:00:09 PM UTC
dbus-libs-1.10.24-7.0.1.el7.x86_64            Thu 17 May 2018 06:00:09 PM UTC
glibc-2.17-222.el7.x86_64                     Thu 17 May 2018 06:00:08 PM UTC
glibc-common-2.17-222.el7.x86_64              Thu 17 May 2018 06:00:05 PM UTC
```

```
Packages Altered:
    Updated dbus-1:1.6.12-17.0.1.el7.x86_64                       ol7_x86_64_u3_base
    Update       1:1.10.24-7.0.1.el7.x86_64                       ol7_critical
    Updated dbus-libs-1:1.6.12-17.0.1.el7.x86_64                  ol7_x86_64_u3_base
    Update            1:1.10.24-7.0.1.el7.x86_64                  ol7_critical
    Updated glibc-2.17-196.el7_4.2.i686                           ol7_x86_64_latest
    Updated glibc-2.17-196.el7_4.2.x86_64                         ol7_x86_64_latest
    Update        2.17-222.el7.i686                               ol7_critical
    Update        2.17-222.el7.x86_64                             ol7_critical
    Updated glibc-common-2.17-196.el7_4.2.x86_64                  ol7_x86_64_latest
    Update               2.17-222.el7.x86_64                      ol7_critical
    Updated glibc-devel-2.17-196.el7_4.2.x86_64                   ol7_x86_64_latest
    Update              2.17-222.el7.x86_64                       ol7_critical
    Updated glibc-headers-2.17-196.el7_4.2.x86_64                 ol7_x86_64_latest
    Update                2.17-222.el7.x86_64                     ol7_critical
    Erase   kernel-3.10.0-693.2.2.el7.x86_64                      ol7_x86_64_latest
    Install kernel-3.10.0-862.2.3.el7.x86_64                      ol7_critical
    Updated kernel-headers-3.10.0-693.21.1.el7.x86_64             ol7_x86_64_latest
    Update                 3.10.0-862.2.3.el7.x86_64              ol7_critical
    Updated kernel-tools-3.10.0-693.21.1.el7.x86_64               ol7_x86_64_latest
    Update               3.10.0-862.2.3.el7.x86_64                ol7_critical
    Updated kernel-tools-libs-3.10.0-693.21.1.el7.x86_64          ol7_x86_64_latest
    Update                    3.10.0-862.2.3.el7.x86_64           ol7_critical
    Updated linux-firmware-20171128-57.git17e62881.0.2.el7.noarch ol7_x86_64_latest
    Update                 20180220-62.git6d51311.0.1.el7.noarch  ol7_critical
    Updated microcode_ctl-2:2.1-22.5.0.6.el7_4.x86_64             ol7_x86_64_latest
    Update                2:2.1-29.0.2.el7.x86_64                 ol7_critical
    Updated openssl-1:1.0.2k-8.0.1.el7.x86_64                     ol7_x86_64_latest
    Update          1:1.0.2k-12.0.1.el7.x86_64                    ol7_critical
    Updated openssl-libs-1:1.0.2k-8.0.1.el7.x86_64                ol7_x86_64_latest
    Update               1:1.0.2k-12.0.1.el7.x86_64               ol7_critical
    Updated python-perf-3.10.0-693.21.1.el7.x86_64                ol7_x86_64_latest
    Update              3.10.0-862.2.3.el7.x86_64                 ol7_critical
```

* The chef-client run invoked from the systemd service fails in the next run due to name resolution errors (getaddrinfo: Name or service not known).
* The issue can be replicated by running `killall -USR1 chef-client`.
* A run in the foreground works correctly via `sudo chef-client`.

Note that:
* `journactl` logging does not show anything unusual.
* This does not affect all nodes that had these changes applied, just a majority.

## Chef Version

12.20.3

## Platform Version

Oracle Linux 7

## Replication Case

Upgrade EL 7.4 to 7.5 (or just above packages) with systemd-managed chef-client service, wait for next run to fail.

## Client Output

```
[2018-05-18T18:46:28+00:00] INFO: Forking chef instance to converge...
[2018-05-18T18:46:28+00:00] INFO: *** Chef 12.20.3 ***
[2018-05-18T18:46:28+00:00] INFO: Platform: x86_64-linux
[2018-05-18T18:46:28+00:00] INFO: Chef-client pid: 23926
[2018-05-18T18:46:30+00:00] ERROR: Error connecting to https://chef-server-01/nodes/chef-client-01, retry 1/5
[2018-05-18T18:46:35+00:00] ERROR: Error connecting to https://chef-server-01/nodes/chef-client-01, retry 2/5
[2018-05-18T18:46:40+00:00] ERROR: Error connecting to https://chef-server-01/nodes/chef-client-01, retry 3/5
[2018-05-18T18:46:45+00:00] ERROR: Error connecting to https://chef-server-01/nodes/chef-client-01, retry 4/5
[2018-05-18T18:46:50+00:00] ERROR: Error connecting to https://chef-server-01/nodes/chef-client-01, retry 5/5
[2018-05-18T18:46:56+00:00] ERROR: Running exception handlers
[2018-05-18T18:46:56+00:00] ERROR: Exception handlers complete
[2018-05-18T18:46:56+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-05-18T18:46:56+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-05-18T18:46:56+00:00] ERROR: Error connecting to https://chef-server-01/nodes/chef-client-01 - Failed to open TCP connection to client-proxy-01:3128 (getaddrinfo: Name or service not known)
[2018-05-18T18:46:56+00:00] ERROR: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
[2018-05-18T19:10:59+00:00] FATAL: SIGTERM received, stopping
```

## Stacktrace

```
/usr/bin/chef-client:57:in `load'
/usr/bin/chef-client:57:in `<main>'

>>>> Caused by SocketError: getaddrinfo: Name or service not known
/opt/chef/embedded/lib/ruby/2.3.0/net/http.rb:880:in `initialize'
/opt/chef/embedded/lib/ruby/2.3.0/net/http.rb:880:in `open'
/opt/chef/embedded/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
/opt/chef/embedded/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/opt/chef/embedded/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/opt/chef/embedded/lib/ruby/2.3.0/net/http.rb:878:in `connect'
/opt/chef/embedded/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
/opt/chef/embedded/lib/ruby/2.3.0/net/http.rb:852:in `start'
/opt/chef/embedded/lib/ruby/2.3.0/net/http.rb:1398:in `request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/http/basic_client.rb:70:in `request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/http.rb:340:in `block in send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/http.rb:372:in `block in retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/http.rb:370:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/http.rb:370:in `retrying_http_errors'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/http.rb:333:in `send_http_request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/http.rb:148:in `request'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/http.rb:115:in `get'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/node.rb:581:in `load'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/node.rb:565:in `find_or_create'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/policy_builder/dynamic.rb:72:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/client.rb:470:in `load_node'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/client.rb:270:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application.rb:295:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application.rb:283:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application.rb:283:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application.rb:248:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application.rb:236:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/client.rb:450:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application/client.rb:434:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/application.rb:59:in `run'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:57:in `load'
/usr/bin/chef-client:57:in `<main>'```

**Comment by benclark** [comment]
We are running chef-client 13.8.5 (as systemd-managed service) on CentOS 7.5, and we are seeing the same exact behavior.

As of right now, more than half our nodes haven't converged in 52+ hours (because of the weekend). I know this is a real problem because I painstakingly went to each node on Friday and manually converged them just to make sure there wasn't some other sort of config drift. When I was done, `knife status` returned all green (i.e. all nodes had successfully converged within the last 30 mins).

This has been going on for at least a week now. It's possible that it started when we upgraded from CentOS 7.4 -> 7.5, like OP.

**Comment by benclark** [comment]
Looks like a restart of the chef-client service (`systemctl restart chef-client`) fixes this permanently, so I'm inclined to think this isn't a Chef issue and is instead due to the system libraries that were updated (likely glibc).

**Comment by lamont-granquist** [comment]
I don't see how this is a bug we can work around in chef.  Open to suggestions, but if you're seeing this, that suggests that you should really reboot the server after updating glibc.  This feels like an O/S level bug that upgrading glibc breaks name resolution for long-running processes that have open file handles to the old glibc.

People should probably engage RedHat/Oracle support and determine if this is some kind of O/S bug.  It seems like old processes should still hold open old filehandles to glibc and name resolution shouldn't break hard.  Even if the name resolution causes the new resolver library to be dynamically linked into the process after the upgrade from the old glibc happens, then i would expect all the symbols to still resolve properly and that should still be ABI compatible and work (although given what ohai does when chef-client runs, I'd be shocked if we hadn't done a pile of name resolution before getting to converge mode and upgrading glibc -- also that would still be some kind of internal ABI break done by patching glibc and nothing to do with chef).

**Comment by mathewcrane** [comment]
Thanks for the confirmation @benclark , and the input @lamont-granquist . I was afraid that answer was the case. I'll reach out to the vendor. In the meantime, we need to patch and keep nodes converging simultaneously, so I'll post any [hacky] workarounds I come up with in the short-term to hopefully benefit others hitting this issue.

**Comment by lamont-granquist** [comment]
Still keep in mind that rebooting after upgrading glibc is a commonly referenced best practice:

https://serverfault.com/questions/758129/do-i-have-to-restart-after-a-library-update-on-linux

We all like to laugh at windows users having to reboot 6 times every update and feel like Linux/Unix should never have to reboot on a package update, but when it comes to glibc, you're replacing all the brains of userspace in every process on the system.  It is also a bit weird to be having chef automatically updating glibc on its own.  If you have to, I'd pin/lock the glibc version so it never upgrades.  You could then script the upgrade of glibc which would detect it needs an upgrade, would unlock the rpm and upgrade and then force a reboot, but obviously you need some kind of orchestration to prevent simultaneous reboots of every single node taking out your services.   In my prior life the orchestration though was something like me running `knife ssh '*:*' -C1 "yum -y upgrade glibc; shutdown -r now"` although the script I used had a ping check that wouldn't move on to the next host until the current host came back up.

**Comment by lamont-granquist** [comment]
relevant issue:  https://tickets.opscode.com/browse/CHEF-4701

**Comment by benclark** [comment]
I concur with @lamont-granquist re: restarting after all glibc upgrades/changes, especially now that we've seen ill effects.

I'm not sure about @mathewcrane's setup, but we're using yum-cron to perform our package upgrades. Excluding glibc from yum-cron might work, or we could set up an alert (from our centralized logging service) when yum-cron _does_ upgrade it, and then react accordingly. I could be wrong, but I'd think that having Chef manage package upgrades wholesale is an anti-pattern.

**Comment by mathewcrane** [comment]
I am definitely in agreement that glibc is a package requiring a reboot after modification. Typically we staged package updates for a few days before reboot with the assumption that long-lived processes would be well behaved in their usage of deleted but in-memory libraries. We will have to adjust our patching processes. FWIW we are modeling our 'required reboot packageset' off of the yum-utils 'needs-restarting' binary.

https://github.com/rpm-software-management/yum-utils/blob/master/needs-restarting.py, lines 53/54.

Thanks for the detailed input.

**Comment by mathewcrane** [comment]
In case anyone runs into this and can't restart the node, or delay patching until a reboot window, the following is how I've temporarily solved it:

```
  service 'restart chef-client if required' do
    service_name 'chef-client'
    action :restart
    only_if 'needs-restarting -s | grep -q chef-client'
    only_if { node['platform_version'].to_i >= 7 }
  end

  ruby_block 'restart other services if required' do
    block do
      Chef::Resource::RubyBlock.send(:include, Chef::Mixin::ShellOut)

      services = "needs-restarting -s | grep -v -E '#{node['yum_client']['no_restart_after_upgrade'].join('|')}'"
      services_out = shell_out(services).stdout.split("\n") rescue []

      services_out.each do |service|
        run_context.resource_collection << restart_service = Chef::Resource::Service.new(service, run_context)
        restart_service.action :restart
      end

    end
    only_if { node['platform_version'].to_i >= 7 }
  end
```
