### ISSUE TITLE
chef-client (local mode) on Windows will sometimes fail to set ohai node domain attribute

### ISSUE THREAD

**Issue by Ryuzavi** [chef/chef#7296]
## Description
Hey.  I'm working on a Windows automation stack using chef-client in local mode and I've noticed that every so often that the automatic ohai node for domain doesn't populate correctly.  As a consequence node['fqdn'] only has the hostname set.

From what I've seen it happens fairly rarely.  But I've seen it several times today over numerous runs.  We depend on the domain parameter for quite a few things so it has an impact.

## Chef Version
14.1.12 now but also saw it happening in whatever chef-client version is in ChefDK 2.5.3

## Platform Version
Windows Server 2016

## Replication Case
Create a simple recipe that logs out the node['domain'] and node['fqdn'] variables on Windows and run it multiple times.  Hopefully you'll see them not set correctly at least once.

## Client Output
Just had the issue happen there with the following recipe:
```
%w(platform platform_version ipaddress macaddress fqdn hostname domain).each do |node_attr|
  log "node['#{node_attr}'] is #{node[node_attr]}"
end
```
The output was:
```
* log[node['platform'] is windows] action write
* log[node['platform_version'] is 10.0.14393] action write
* log[node['ipaddress'] is 10.177.17.228] action write
* log[node['macaddress'] is 00:50:56:97:5C:99] action write
* log[node['fqdn'] is qa-test-win-server] action write
* log[node['hostname'] is qa-test-win-server] action write
* log[node['domain'] is ] action write
```
Domain should've have been `lab.local`.

**Comment by lamont-granquist** [comment]
`node['fqdn']` requires DNS to work correctly, if the DNS lookup fails, it'll fail.  for that reason it isn't a good idea to use that and to instead use `node['hostname']` or `node['machinename']` instead.

**Comment by Ryuzavi** [comment]
The application I'm setting up needs the full address at points.  Isn't it weird that it only fails sometimes?  Is there anything I can do to make the DNS more hardy?

**Comment by lamont-granquist** [comment]
making DNS more hardy is well of out of scope of what we can do.

that is part of the lost art of system engineering.
