### ISSUE TITLE
Add new resource for powershell_gallery

### ISSUE THREAD

**Issue by tas50** [chef/chef#7321]
Add a resource for installing powershell modules from the powershell gallery. This is a modern version of our existing powershell_module resource in the powershell cookbook.

**Comment by Happycoil** [comment]
Doesn't `powershell_package` cover this?

**Comment by tas50** [comment]
I think it actually does after looking at things. We should probably get a powershell_package_source resource created at some point though so people can avoid adding sources via powershell commands.
