### ISSUE TITLE
User resource on windows applies comment as Full Name, does not allow for setting Full Name

### ISSUE THREAD

**Issue by sarahbakal** [chef/chef#7356]
## Description
User resource on windows applies comment as Full Name, does not allow for setting Description.

## Platform Version
Windows

## Replication Case
User resource on windows applies comment as Full Name, does not allow for setting Full Name
```
user 'testuser' do
  comment 'the comment'
  password 'password'
end
```
## Client Output

```

```

**Comment by stuartpreston** [comment]
Thanks for the report, we agree this should be possible but is not today.  Using the `powershell_script` resource (`New-LocalUser` cmdlet) is probably the easiest workaround if you need to set the Description correctly.
