### ISSUE TITLE
Deprecate knife cookbook site in favor of knife supermarket

### ISSUE THREAD

**Issue by tas50** [chef/chef#7368]
We currently have 2 different ways to interact with the Supermarket: knife cookbook site and knife supermarket. Knife supermarket is currently just an alias for the old knife cookbook site commands. Since we no longer have a cookbook (community) site it seems really odd that we have these old commands. We should remove the old commands in favor of the supermarket namespace.

### Benefits

- Speed up knife
- Remove double commands which confuse new users
- Align around the Supermarket name
- Shrink the size of our help output

**Comment by tas50** [comment]
PR opened to move the logic into the Supermarket plugin classes, which is step 1 #7466

**Comment by vsingh-msys** [comment]
@tas50 this one too?
