### ISSUE TITLE
cannot load such file -- chef/mixin/language

### ISSUE THREAD

**Issue by vinshas1** [chef/chef#7391]
## Description

I am running _chef-client --once_ command and getting below error on windows server 2016 standard x64. I am getting this error after upgrading the client from 12.5.1 to 14.2.0. 

-----------------------------------------------------------------------------------------
Recipe Compile Error in c:/chef/cache/cookbooks/windows/libraries/windows_package.rb
------------------------------------------------------------------------------------------
 Load Error
-----------
cannot find such file -- chef/mixin/language

## Chef Version

14.2.0

## Client Output

```

```

**Comment by coderanger** [comment]
When changing major versions of Chef, there are backwards-incompatible changes involved. This means that not all cookbooks which work with Chef 12 will also work with Chef 14. In this case that mixin no longer exists. You'll have to upgrade your `windows` cookbook to something compatible with Chef 14 (preferably the latest version of the cookbook but that's up to you to decide).

**Comment by vinshas1** [comment]
I do not know how to upgrade _windows_ cookbook. Please guide me with the steps/link so that I will upgrade it.. Thanks for quick reply...

**Comment by coderanger** [comment]
Unfortunately we have no way to know how you manage your cookbooks. You’ll need to ask around within your organization and find help there.
