### ISSUE TITLE
Discussion around lazy objects not memoizing their values

### ISSUE THREAD

**Issue by mal** [chef/chef#7392]
## Description
`lazy` properties are calculated late as designed, but are also re-calculated on each use. This is unfortunate as it means it's possible for the output value to change between calculations and perhaps more critically, expensive to calculate `lazy` properties can result in a considerably longer convergence time.

## Chef Version
14.1.12

## Platform Version
Ubuntu 18.04

## Replication Case
```rb
file '/tmp/chef-test-lazy' do
  debug = ->(msg) { run_context.events.whyrun_assumption(nil, nil, msg) }
  content lazy { debug.call('Sleeping for 1 second ...'); sleep(1); 'foo' }
end
```
_The `debug` lambda is just abusing event reporting to make it easier to parse the output._

## Client Output
**First run:**
```
Recipe: testcase::default
  * file[/tmp/chef-test-lazy] action create
    * Sleeping for 1 second ...
    * Sleeping for 1 second ...
    - create new file /tmp/chef-test-lazy
    * Sleeping for 1 second ...
    - update content in file /tmp/chef-test-lazy from none to 2c26b4
    --- /tmp/chef-test-lazy     2018-06-24 16:15:26.834267944 +0100
    +++ /tmp/.chef-chef-test-lazy20180624-20709-161x000 2018-06-24 16:15:26.834267944 +0100
    @@ -1 +1,2 @@
    +foo
```
**Subsequent runs:**
```
Recipe: testcase::default
  * file[/tmp/chef-test-lazy] action create
    * Sleeping for 1 second ...
    * Sleeping for 1 second ...
    * Sleeping for 1 second ...
     (up to date)
```

## Additional Comments

As you can see in the case of the `file` resource the `lazy` property is being calculated three separate times. This relies on an unsafe assumption the passed block is idempotent, and introduces significant time penalties for expensive lazy operations.

I originally tried to solve this issue by memoizing `call` inside `Chef::DelayedEvaluator`, however this does not remedy the issue as one might expect. This is because `DelayedEvaluator` properties are evaluated in `property.rb` using an `instance_exec` against the `resource`, bypassing the overriden `call`.

One possible solution to this could be memoization of `property.rb`'s `exec_in_resource` method. If this seems like a sane approach please let me know and I'll see what I can do WRT getting a PR sorted.

**Comment by lamont-granquist** [comment]
You cannot change that, it would affect lazy default values of properties where we do not expect those to get memoized.

You could maybe create a memoized_lazy object which was both lazy and memoized, but you can't modify lazy itself.

There's also maybe a bug here where the file provider should memoize its contents.

**Comment by lamont-granquist** [comment]
Also the obvious workaround is to call a method on something which appropriately memoizes the value in the caller's code.

**Comment by mal** [comment]
Would it be unacceptable to change the internal `lazy` usage to use `DelayedEvaluator` directly and have the `lazy` convenience method use a `MemoizedDelayedEvaluator` instead?

I can see why it may not be possible memoize across the board for internal reasons, but to have user defined lazy values effectively mutate on the fly seems more confusing than useful. I'd be interested in any sort of example you may be able to provide showing where such behaviour may be relied upon, in order to better understand the cases that must be protected while attempting to seek a middle ground.

**Comment by lamont-granquist** [comment]
No, changing the existing behavior of lazy is not acceptable.  You can introduce something else, but you can't memoize `lazy {}`, that is a public API, and memoization would change behavior that we depend on.

**Comment by mal** [comment]
No worries, I'm not going to touch `lazy`, I hear you.

I would still like to understand the "why" and see examples that show why `lazy` behaves the way it does. It's hard to come up with solid ideas for new features that increase the public surface of the API that justify the increased maintenance cost they introduce. Getting a better understanding of use cases of `lazy` beyond simple late evaluation seems like a good way to go in that respect.

I've asked a few times on slack but I fear that the query is for the most part too broad to attract responses. A few pointers would be very helpful. Thanks.

**Comment by mal** [comment]
Fair enough, at the outset it seemed like a pretty tricksy bug (I was generating a clean SSH key via `shell_out` inside a `lazy` block and getting completely different keys on each access which took waaaay too long to track down), and despite `lazy` being a public API, figured in the worst case we could "fix" for a future major version release, or with a new helper method (`late`, anyone?) that may have eventually been able to supersede `lazy` in the majority of cases.

If either of you believe there's merit there I'd be happy to put together an `chef-rfc` for it, but right now it feels like I misjudged how much of a "bug" this is in the wider community's eyes and that there's not really an appetite for such a feature, in which case I'll do as you suggest; fix it for me and drop this issue.

Thanks both for your input 👍
