### ISSUE TITLE
windows_task removes quotes from command

### ISSUE THREAD

**Issue by SteveLowe** [chef/chef#7413]
## Description
The windows_task resource removes all quotes from the command property.

This is a problem when you have a scheduled task with a path containing spaces.

## Chef Version
chef-client 14.2.0

## Platform Version
Tested on Windows Server 2008 R2 and 2016.

## Replication Case
```
windows_task "TestTask" do
  command "powershell.exe -file \"C:\\Program Files\\app\\script.ps1\""
  frequency :none
  action :create
end
```

## Workaround
This can be worked around for now, by surrounding the double quotes with single quotes.
```
windows_task "TestTask" do
  command "powershell.exe -file '\"C:\\Program Files\\app\\script.ps1\"'"
  frequency :none
  action :create
end
```
alternatively by setting the working directory to the spaced path
```
windows_task "TestTask" do
  command "powershell.exe -file script.ps1"
  cwd "C:\\Program Files\\app"
  frequency :none
  action :create
end
```

## Investigation
It looks like the problem is here: https://github.com/chef/chef/blob/master/lib/chef/provider/windows_task.rb#L230-L236
Shellwords.split() will remove the double quotes.

**Comment by stuartpreston** [comment]
Thanks for the report. I've added a test for this and we will investigate. https://github.com/chef/chef/compare/sp/7413
