### ISSUE TITLE
Chef failed to install Docker when using attribute default['docker']['version'] 

### ISSUE THREAD

**Issue by jyothish-git** [chef/chef#7422]
## Description

Chef failed to execute docker installation recipe when using default['docker']['version'] attribute. 
## Chef Version

chef_version=14.2.0
    
    ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
    program_name=/opt/chef/bin/chef-apply
    executable=/opt/chef/bin/chef-apply
## Platform Version

platform=centos
    platform_version=7.4.1708
## Replication Case

I have a recipe for installing particular version of docker. I specified the version of docker through attribute. I just used the attribute node.default['docker']['version'] = '1.12.6-1.el7.centos' , but the recipe failed.
It executed successfully when I used any attribute other than default['docker']['version'] say  node.default['docker']['xyz'] = '1.12.6-1.el7.centos'
Can anyone know why it failed when using default['docker']['version']
 
[root@master01 package]# cat  _docker.rb
node.default['docker']['version'] = '1.12.6-1.el7.centos'
package "lvm2"
package "device-mapper-persistent-data"

directory "/var/lib/docker"

directory "/etc/docker" do
        owner "root"
        group "root"
        mode "0744"
        action :create
    recursive true
end

package 'docker-engine' do
        version node['docker']['version']
        allow_downgrade true
end 
service "docker" do
  action :enable
end

Below,  I used attribute node.default['docker']['xyz'] = '1.12.6-1.el7.centos' and chef successfully ran the recipe.

[root@master01 package]# cat  _docker.rb
node.default['docker']['xyz'] = '1.12.6-1.el7.centos'

package 'docker-engine' do
        version node['docker']['xyz']
        allow_downgrade true
end 
```
[root@master01 package]# /opt/chef/bin/chef-apply  _docker.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * yum_package[lvm2] action install (up to date)
  * yum_package[device-mapper-persistent-data] action install (up to date)
  * directory[/var/lib/docker] action create (up to date)
  * directory[/etc/docker] action create (up to date)
  * yum_package[docker-engine] action install
    - install version 1.12.6-1.el7.centos of package docker-engine
```

## Client Output

```
[root@master01 package]# /opt/chef/bin/chef-apply  _docker.rb
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * yum_package[lvm2] action install (up to date)
  * yum_package[device-mapper-persistent-data] action install (up to date)
  * directory[/var/lib/docker] action create (up to date)
  * directory[/etc/docker] action create (up to date)
  * yum_package[docker-engine] action install
    * No candidate version available for docker-engine
    ================================================================================
    Error executing action `install` on resource 'yum_package[docker-engine]'
    ================================================================================

    Chef::Exceptions::Package
    -------------------------
    No candidate version available for docker-engine

    Resource Declaration:
    ---------------------
    # In _docker.rb

     16: package 'docker-engine' do
     17:         version node['docker']['version']
     18: #        version node['docker']['version']
     19:         allow_downgrade true
     20: end
     21:

    Compiled Resource:
    ------------------
    # Declared in _docker.rb:16:in `run_chef_recipe'

    yum_package("docker-engine") do
      package_name "docker-engine"
      action [:install]
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "(chef-apply cookbook)"
      recipe_name "(chef-apply recipe)"
      version "17.03.2"
      allow_downgrade true
    end

    System Info:
    ------------
    chef_version=14.2.0
    platform=centos
    platform_version=7.4.1708
    ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
    program_name=/opt/chef/bin/chef-apply
    executable=/opt/chef/bin/chef-apply

[2018-07-05T07:40:49+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-07-05T07:40:49+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-07-05T07:40:49+00:00] FATAL: Chef::Exceptions::Package: yum_package[docker-engine] ((chef-apply cookbook)::(chef-apply recipe) line 16) had an error: Chef::Exceptions::Package: No candidate version available for docker-engine
```

## Stacktrace

[stacktrace.txt](https://github.com/chef/chef/files/2166059/stacktrace.txt)

**Comment by tas50** [comment]
Try changing the property to lazy { node['docker']['version'] }

**Comment by lamont-granquist** [comment]
#
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
