### ISSUE TITLE
node.read isn't obvious to users coming from Ruby-land

### ISSUE THREAD

**Issue by mal** [chef/chef#7425]
## Description
Coming from Ruby-land it's not at all obvious that `node.read` is a thing. The equivalent in Ruby-land would be [`node.dig`](https://ruby-doc.org/core-2.4.0/Hash.html#method-i-dig), which is supported by other custom Chef structures (immutable array and hash), but not by attributes.

Following a [conversation with @coderanger](https://github.com/chef/chef/pull/7423#issuecomment-402853520) it seems like this might be something to support, but it's not as clear cut as it might be due to effectively introducing an alternative way to do something that's already supported.

This is probably more of an opinion gauge for now, to see what Chef maintainers think.

## Chef Version
Chef 14

**Comment by lamont-granquist** [comment]
this isn't a high enough priority to discuss really.  if anyone feels deeply about it a PR (well written and green with tests) would be better.  otherwise 100 other broken things are always going to take priority.
