### ISSUE TITLE
chef node not checking in with the server on Windows servers after upgrading the client from 12.5.1 to 14.2.0

### ISSUE THREAD

**Issue by vinshas1** [chef/chef#7429]
## Description
chef node not checking in with the server on Windows servers after upgrading the client from 12.5.1 to 14.2.0

## Chef Version
14.2.0

## Platform Version
Windows Server 2012R2

## Replication Case
Tried on multiple servers with different windows OS versions(2008R2, 2012)

## Client Output
Chef-Client is running without any issues just that it is not checking in with the server. No issue with SSL, cookbook etc..,

```

```

**Comment by coderanger** [comment]
Chef by itself does not offer this feature. You would have to have set it up yourself, commonly with the `chef-client` cookbook or similar. Check that that cookbook is still working as intended, and otherwise check the status of whichever option you picked for interval runs (there are several).
