### ISSUE TITLE
Add path property alias to scm resource

### ISSUE THREAD

**Issue by mal** [chef/chef#7434]
## Description
The `scm` resource takes a file path under it's `destination` property, in the vast majority of other core resources similar properties are named `path`. Would it be possible to introduce `path` as an alias for `destination` in this resource, to follow the approach of least surprise.

## Chef Version
Chef 14

**Comment by tas50** [comment]
@mal I'd be open to a PR to add change the resource to path with an alias so that destination still works. You'd want to add a note in description that the legacy destination properly will still function. We'd probably merge that in for Chef 15

**Comment by mal** [comment]
Closing as the change was rejected even despite being non-breaking.
