### ISSUE TITLE
Sysctl idempotency check needs to consider the existence of the sysctl.d file, not just the value

### ISSUE THREAD

**Issue by Poohblah** [chef/chef#7450]
## Description

The idempotency check in the sysctl resource only compares the existing value of the sysctl with the desired value.  If they match, it does nothing.  However, if the sysctl has *also* been changed outside of chef-client then the values may match, the /etc/sysctl.d file will not be written, and on a reboot the value will revert to whatever it was before.

If the /etc/sysctl.d file does not exist, then that should trigger the resource to fire and setup the /etc/sysctl.d file, even though the running value will not change.

## Chef Version
chef-client 14.1.12

## Platform Version
RHEL 7.5

## Replication Case
* Assume there is a sysctl parameter "foo" with a default value of "0"
* Set foo to "1" outside of Chef using `sysctl foo=1`
* Run a cookbook that contains the resource `sysctl('foo') { value(1) }`
* Reboot the system.

When the system comes back up, I expect that the sysctl parameter foo will retain the value configured by Chef (foo=1), however, it actually will change to its default value (foo=0).

I [originally reported this issue against the sysctl cookbook](https://github.com/sous-chefs/sysctl/issues/112).  I am re-reporting it here now that the sysctl resource is part of core Chef.

**Comment by tas50** [comment]
@Poohblah Thanks for the report. The fix for this will go out in Chef 14.4.

**Comment by Poohblah** [comment]
Thank you!
