### ISSUE TITLE
Ownership not being set for cookbook_file/template resources

### ISSUE THREAD

**Issue by TheLonelyGhost** [chef/chef#7463]
## Description
Converging one of the `file`-based resources (e.g., `cookbook_file` or `template`) and setting an owner or group results in neither owner nor group being set correctly. Re-converging the cookbook claims the file is up-to-date.

Example:

```ruby
directory '/tmp/foo' do
  mode '0744'
  owner 'vagrant'
  group 'vagrant'

  action :create
end

template '/tmp/foo/bar' do
  source 'bar.erb'

  mode '0644'
  owner 'vagrant'
  group 'vagrant'

  action :create
end
```

The `directory` resource will be created with proper ownership and umask, but the file will only have the proper umask. The file's owner and group will both be set to `root` (or whatever user is running chef-client).

Running the following inspec tests against it result in a partial failure:

```ruby
describe directory('/tmp/foo') do
  it { should exist }
  it { should be_owned_by('vagrant') }
  it { should be_executable.by_user('vagrant') }
  it { should be_readable.by_user('vagrant') }
end

describe file('/tmp/foo/bar') do
  it { should exist }
  it { should be_owned_by('vagrant') }
  it { should be_readable.by_user('vagrant') }
end
```

## Chef Version
14.3.37

## Platform Version
- OSX (from AndrewDryga/vagrant-box-osx)
- Ubuntu 16.04 (from bento/ubuntu-16.04)

## Replication Case
Try running `kitchen verify` for the following simple cookbook: [https://github.com/thelonelyghost/tlg_workspace](https://github.com/TheLonelyGhost/tlg_workstation/tree/58f1bb2e4e30da25ce1316ffa77b0293484c52ff)

## Client Output
Client output is just like normal for converging a `cookbook_file` or `template` resource, but InSpec checks and manual confirmation show the files created with those are owned by root, not the specified user or group

## Stacktrace

N/a

**Comment by coderanger** [comment]
Resolved on Slack, typo in the kitchen config.
