### ISSUE TITLE
Latest chefdk 3.1.0 is not working. Issues with the gem file. Working absolutely fine with 2.4.17 chefdk version

### ISSUE THREAD

**Issue by PranjalGohain** [chef/chef#7496]
## Description
 Chefdk version 3.1.0 is not developed properly it just works fine with the older versions

## Chef Version
 chef-13.10.0-1.el7

## Platform Version
Chef client is on both windows and linux (Ubuntu, CentOS)

## Replication Case
Just try to install a new hosted chef try to bootstrap a new node

**Comment by PranjalGohain** [comment]
it fails in the authentication process

**Comment by stuartpreston** [comment]
It is not very helpful to say [the software] "is not developed properly" without providing a few more details about what you tried.  As you can see there's a major version difference between 2.4.17 and 3.1.0 so perhaps [something has changed that you relied upon](https://github.com/chef/chef-dk/blob/master/CHANGELOG.md#v310-2018-07-05)?  

For anyone to start to help you we would need the specific command that you are running that "fails in the authentication process" - and the complete error output.  You may need to add `-l debug` to see more detail about the errors.  Lastly I would say there are a lot of people out there using ChefDK and GitHub issues are not the place for support so it is worth signing up to our [Community Slack](https://community-slack.chef.io) and asking this question in the #general channel before raising an issue against the project.

**Comment by PranjalGohain** [comment]
thanks for the response.. i will post the same in the community
