### ISSUE TITLE
the windows_service resource overwrites builtin service account passwords

### ISSUE THREAD

**Issue by joshs85** [chef/chef#7512]
## Description
the embedded windows_service resource overwrites builtin service account passwords.

## Chef Version
14.3.37

## Platform Version
Windows Server 2008 R2

## Replication Case
Given a recipe which contains a windows_service resource and a service which is already created and configured to run as the builtin Local Service account, the password is overwritten, causing the service to fail to start and requires manually re configuring the service's log on account in services.msc.  The password for this account is unknown therefore a password cannot be supplied and is auto entered when configuring the service. 

If the service is stopped and needs to start, I get this error due to the password being trampled on:

Please adjust this behavior so that the password isn't changed every time this runs or this builtin account is excluded or add an option for builtin accounts to automatically get the password and add it.

windows_service 'w32time' do
    action [ :enable, :start]
    run_as_user 'NT AUTHORITY\Local Service'
  end

## Client Output
Error message received If the service needs to be started:
```
The account specified for this service is different from the account specified for other services running in the same process. - StartService: The account specified for this service is different from the account specified for other services running in the same process.'
```

**Comment by stuartpreston** [comment]
@joshs85 As per https://docs.microsoft.com/en-us/windows/desktop/services/localservice-account you should specify the run_as_user as 'NT AUTHORITY\LocalService' then this shouldn't happen.

I'm going to close this issue.  Please join us in the #windows community at our [Chef Community Slack](https://community-slack.chef.io) if you continue to have problems here.
