### ISSUE TITLE
osx_profiles resource uses relative paths to profiles tool

### ISSUE THREAD

**Issue by jessepeterson** [chef/chef#7530]
## Description

The `osx_profiles` resource uses relative paths to profile tool. Had a user that had different system paths and thus had failing chef on this resource.

## Chef Version
E.g. current GH master. 7c9178e5dd4ec7b5a75993c148b087bac6e5b53d

In the code: https://github.com/chef/chef/blob/e2f21177cae1da7dc462a8f17a3f73e5c915cba0/lib/chef/provider/osx_profile.rb#L191

## Platform Version
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
```

## Replication Case
Place a `profiles` executable higher in your path order than the system profiles command, `/usr/bin/profiles`. See as the `osx_profiles` resource will use that instead of the system path.

**Comment by tas50** [comment]
Fixed by #7539. Thanks for the report
