### ISSUE TITLE
current_value function not available at compile time in Chef 14

### ISSUE THREAD

**Issue by petracvv** [chef/chef#7541]
## Description
If a custom resource is using the current_value function in an action and that action is set to run at compile-time by the user, the operation fails with a `NameError`. 

I am wondering if this is intended behavior in Chef 14 or if it is a bug. This function could be used in Chef 13 during the compile time phase of a Chef run.

## Chef Version
Latest Stable: 14.3.37
Also found in earliest Chef 14 version (14.0.190)

## Platform Version
CentOS 7.5.1804

## Replication Case
Please see my issue in the chef-vault cookbook for how to replicate: https://github.com/chef-cookbooks/chef-vault/issues/70

## Client Output
Normal run Gist output: https://gist.github.com/petracvv/221a00f91c5b72e7d35ddc5ddaeda978

## Stacktrace
Gist with stacktrace: https://gist.github.com/petracvv/d146f1ab637f9749d84d759bbd08b76a

**Comment by lamont-granquist** [comment]
Doesn't have anything to do with compile_time and actions need to use `current_resource` and not `current_value` and this was a breaking change in Chef-14.

**Comment by petracvv** [comment]
OK thanks! Must have missed that in the changelogs.
