### ISSUE TITLE
DataBagItem#to_hash method should be renamed to to_h

### ISSUE THREAD

**Issue by rantler** [chef/chef#7554]
The `Chef::DataBagItem` and subclasses, including `Chef::EncryptedDataBagItem` implement the method [`to_hash`](https://github.com/chef/chef/blob/master/lib/chef/data_bag_item.rb#L104) which returns a new Hash instance. The method should be renamed to `to_h`.

This is a misuse of the `to_hash` method for _explicit_ conversion. Instead explicit conversions should use `to_h` and _implicit_ conversions should use `to_hash`.

Furthermore, apparently it can be considered [dangerous](https://zverok.github.io/blog/2016-01-18-implicit-vs-expicit.html) to implement implicit conversion methods directly.

**Comment by coderanger** [comment]
They aren’t about coercion, they are hooks into the JSON serializer.

**Comment by rantler** [comment]
I must admit that I'm a Chef noob, so please forgive me if I'm barking up the wrong tree. This came up because we routinely use `to_h` to deal with potential `nil` values and when we applied that pattern in this case, we were forced to use `to_hash` instead.

Here's a simplified example of what we were trying to do:
```rb
creds = data_bag_item('credentials', creds_key)
...
creds.to_h.empty? ? do_default_thing : do_thing_with_creds(creds)
```

This lead to an exception:
```rb
NoMethodError
-------------
undefined method `to_h' for #<Chef::EncryptedDataBagItem:0x0000000003efbd40>
Did you mean?  to_hash
               to_s

Cookbook Trace:
---------------
```

In much of our other Ruby code, we use `to_h` for this purpose to take advantage of `nil.to_h == {}`, for example, and to avoid having to write things like `creds && !creds.empty? ? ... : ...`. According to my understanding of Ruby behavior, it is desirable to use `to_h` for this purpose rather than `to_hash`.

**Comment by coderanger** [comment]
So as you can see from the implementation you linked, the `to_hash` output would never be `empty?` because that fills in some boilerplate fields used by the Chef Server API. We already proxy all Hash methods for you: https://github.com/chef/chef/blob/49fd808d7e290a72de1d45c258fde78acf8782d8/lib/chef/data_bag_item.rb#L48, so you could do `creds.empty?` but in this case that isn't going to be useful because every data bag item has at least an `'id'` key as that's part the data bags API. What you probably want is something like this:

```ruby
creds.any? {|key, _| key != 'id' } ? do_default_thing : do_thing_with_creds(creds)
# Or if there is one key you can check for
creds.include?('somekey') ? do_default_thing : do_thing_with_creds(creds)
```

**Comment by coderanger** [comment]
Oh and re: dealing with nils, in theory `data_bag_item()` should never return nil because it raises an exception if the item doesn't exist but if you need to deal with that kind of thing elsewhere:

```ruby
creds&.include?('somekey')
```

**Comment by rantler** [comment]
Thanks so much for the lucid explanation! I'm closing this ticket. 🙇
