### ISSUE TITLE
Use expeditor to open backport PRs

### ISSUE THREAD

**Issue by tas50** [chef/chef#7626]
We want to be able to branch for Chef 15 while still backporting changes to the chef-14 branch. We can do this automatically with expeditor using labels. We just need to get it all wired up.

**Comment by tas50** [comment]
At the moment we'll need to figure out how to get a list of all commit shas in a PR so we can use that list to cherry pick. This isn't something expeditor has out of the box.

**Comment by lamont-granquist** [comment]
This probably needs to be tracked as an issue against expeditor not chef/chef

**Comment by tas50** [comment]
This is mostly writing a script to perform the backport using expeditor.
