### ISSUE TITLE
powershell_package_source behind proxy

### ISSUE THREAD

**Issue by nsmeef** [chef/chef#7628]
## Description
I am trying to a register PowershellGet behind a proxy and getting an error. 

## Chef Version
Chef Development Kit Version: 3.2.30
chef-client version: 14.4.56
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.6
kitchen version: 1.23.2
inspec version: 2.2.70

## Platform Version
Windows 2012 R2

## Replication Case
Run the below code behind a proxy. We're running it in a EC2 test kitchen context. With `http(s)_proxy` set in the provisioner block.

powershell_package_source 'PowerShellGet' do
  provider_name 'PowerShellGet'
  source_name 'PowerShellGet'
  trusted true
end

## Stacktrace
```           

================================================================================
           Error executing action `register` on resource 'powershell_package_source[PowerShellGet Source]'
           ================================================================================
           
           Chef::Exceptions::JSON::ParseError
           ----------------------------------
           lexical error: invalid char in json text.
                                           WARNING: MSG:UnableToDownload  
                         (right here) ------^
           
           Resource Declaration:
           ---------------------
           # In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/company-base-windows-2012-hybrid/recipes/locale.rb
           
             9: powershell_package_source 'PowerShellGet Source' do
            10:   provider_name 'PowerShellGet'
            11:   source_name 'PowerShellGet'
            12:   trusted true
            13: end
            14: 
           
           Compiled Resource:
           ------------------
           # Declared in C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/company-base-windows-2012-hybrid/recipes/locale.rb:9:in `from_file'
           
           powershell_package_source("PowerShellGet Source") do
             action [:register]
             default_guard_interpreter :default
             declared_type :powershell_package_source
             cookbook_name "company-base-windows-2012-hybrid"
             recipe_name "locale"
             provider_name "PowerShellGet"
             source_name "PowerShellGet"
             trusted true
           end
           
           System Info:
           ------------
           chef_version=14.4.56
           platform=windows
           platform_version=6.3.9600
           ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
           program_name=C:/opscode/chef/bin/chef-solo
           executable=C:/opscode/chef/bin/chef-solo
           
       
       Running handlers:
       [2018-09-07T02:00:05+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-09-07T02:00:05+00:00] ERROR: Exception handlers complete
       Chef Client failed. 5 resources updated in 01 minutes 37 seconds
       [2018-09-07T02:00:05+00:00] FATAL: Stacktrace dumped to C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2018-09-07T02:00:05+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-09-07T02:00:05+00:00] FATAL
```

**Comment by Happycoil** [comment]
This is because the resource doesn't handle the cmdlet being unable to bootstrap package providers. At a minimum we should give a proper error in this situation.

One normally handles this behind airgaps by manually placing the package provider dll in the appropriate folder. Not sure if the resource should try to do this.

**Comment by rdean716** [comment]
@Happycoil I still see the warning stream polluting the command output.

**Comment by Happycoil** [comment]
@rdean716 Yeah, that should be fixed now, thanks for catching the bare word error. Can you confirm it works now?

https://github.com/chef/chef/pull/8025 should stop the resource choking on the warnings PackageManagement emits when it can't reach the internet, but it looks like getting proxies to work means you need at least version `2.8.5.206` of the NuGet provider and you need to provide the `-Proxy` and `-ProxyCredentials` parameters. Possibly also a more recent version of `PackageManagement` than `1.0.0.1`. See https://github.com/OneGet/oneget/issues/171

**Comment by rdean716** [comment]
@Happycoil yes, it works now.
