### ISSUE TITLE
windows_service does not properly support sensitive

### ISSUE THREAD

**Issue by kitforbes** [chef/chef#7634]
## Description
Using the `windows_service` resource with the `sensitive true` property has no effect and exposes passwords in logs. This behaviour can be seen in Chef's code [here](https://github.com/chef/chef/blob/master/lib/chef/provider/service/windows.rb#L94)

## Chef Version
`12.21.4`
`13.8.5`

## Platform Version
Windows Server 2012 R2

## Replication Case
```ruby
windows_service 'Some Service' do
  run_as_user 'domain\\username'
  run_as_password 'my_password'
  sensitive true
  action %i( enable start )
end
```

## Client Output
```plaintext
[2018-09-11T15:59:20+01:00] INFO: windows_service[Some Service] configured with {:service_name=>"Some Service", :service_start_name=>"domain\\user", :password=>"my_password"}
```

## Stacktrace
n/a

**Comment by stuartpreston** [comment]
Build 14.6.20 has this fix, plus it will be in the following release of Chef 13.
