### ISSUE TITLE
ssh_agent_signing configuration option does not work

### ISSUE THREAD

**Issue by dkanejs** [chef/chef#7635]
## Description
Setting the `ssh_agent_signing true` option in `config.rb` to enable `knife` to use  `ssh-agent` instead of a Private key directly with `client_key` does not work.

## Chef Version

```
chef Development Kit Version: 3.2.30
chef-client version: 14.4.56
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.6
kitchen version: 1.23.2
inspec version: 2.2.70
```

## Platform Version

```
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G65
```

## Replication Case

1. Follow the Chef docs about encrypting your private key [here](https://github.com/chef/chef/blob/master/RELEASE_NOTES.md#ssh-agent-support-for-user-keys)
2. Ensure your key is available via `ssh-add -L`
3. Set `ssh_agent_signing true` in `config.rb`
4. Set `client_key` to the public key of the key shown in `ssh-add -L`
5. run `knife status` or similar

Also note, I'm using a YubiKey that contains my SSH key. This is exposed via `ssh-agent` and I can confirm I can see my key is available with `ssh-add -L`.

## Client Output

```
INFO: Using configuration from /Users/dk/.chef/config.rb
INFO: Sending query: *:*
ERROR: Chef::Exceptions::InvalidPrivateKey: The file /Users/dk/.ssh/id_rsa.pub or :raw_key option does not contain a correctly formatted private key or the key is encrypted.
The key file should begin with '-----BEGIN RSA PRIVATE KEY-----' and end with '-----END RSA PRIVATE KEY-----'
```

## Stacktrace

_Not sure how to do this?_

**Comment by coderanger** [comment]
Please run `knife config get` to check that the option appears enabled.

**Comment by dkanejs** [comment]
Had to remove some internal stuff, let me know if that's an issue.

```
cache_options:
  path: /Users/dk/.chef/checksums
cache_type:        BasicFile
chef_server_url:   <removed>
client_key:        /Users/dk/.ssh/id_rsa.pub
config_file:       /Users/dk/.chef/config.rb
cookbook_path:     /Users/dk/Projects/cookbooks
knife:
  ssh_user: <removed>
log_level:         warn
log_location:      STDOUT
node_name:         <removed>
ssh_agent_signing: true
```

**Comment by dkanejs** [comment]
Also, I can get it working by using the `knife-ssh-plugin` fork with the edit I have made [here](https://github.com/dkanejs/knife-ssh-agent/commit/4580d44e5d47eecd8ae576dcddb3c41833690107). I actually noticed the `ssh_agent_signing` in Chefs source when fixing that.

**Comment by coderanger** [comment]
Ahh so that needs to be reformatted as an RSA public key block. I wasn't super clear about that in the docs since the expectation was people migrating from existing RSA key files.

**Comment by coderanger** [comment]
Let me try and figure out the command to do that :)

**Comment by dkanejs** [comment]
I used:
```
ssh-keygen -f ./ssh/id_rsa.pub -e -m pem
```
Updated the config to point to a new file containing the above and it's all working!

**Comment by coderanger** [comment]
You beat me to it :)

**Comment by coderanger** [comment]
Would be happy to accept some improved parsing code to grok OpenSSH's format too, just wasn't trivial to add so I punted.

**Comment by coderanger** [comment]
(you would still need to convert to PEM format for attaching the key to your client in Chef Server though so maybe that's kind of pointless)

**Comment by dkanejs** [comment]
I can update the docs and add the example conversion command used above in the `ssh_agent_signing ` section to help out those who get stuck with this.

I'm just picking up Ruby (unfortunately) so improved code from me might be a push haha
