### ISSUE TITLE
Specifying an extra cookbook_path with parent dir that doesn't exist causes crash in chef-solo

### ISSUE THREAD

**Issue by brettcave** [chef/chef#7638]
## Description
If any one of the cookbook paths' parent directory does not exist, then chef-solo crashes on first run with `Exception raised! #<Errno::ENOENT: No such file or directory @ dir_s_mkdir - PARENT/nodes>` . Subsequent runs pass. 

## Chef Version
Reproduced in 12.22.5, 13.10.4 and 14.4.56

## Platform Version
Ubuntu 16.04

## Replication Case and Client Output
1. Given I have a chef run (I created a cookbook with `log "test"` in default recipe).
2. If I configure a cookbook path where the cookbook's parent directory doesn't exist: `echo 'cookbook_paths ["/var/chef/cookbooks", "/var/chef/nodir/cookbooks"]' > solo.rb`
3. When I run chef-solo, then the first run crashes, trying to create a `nodes` subdir in all cookbook paths, even where parent directories don't exist: `chef-solo -c solo.rb -o 'recipe[simple::default]'`:

    Exception raised! #<Errno::ENOENT: No such file or directory @ dir_s_mkdir - /var/chef/nodir/nodes>

The next run just uses `/var/chef/nodes` for node info and doesn't try to create `/var/chef/nodir/nodes`.

If the crash is by design, then it should crash on every run, but chef-solo would be more robust if non-existent cookbook paths can be added to config without causing a crash.

**Comment by brettcave** [comment]
https://github.com/chef/chef/blob/master/lib/chef/chef_fs/file_system/repository/chef_repository_file_system_root_dir.rb#L113

**Comment by vsingh-msys** [comment]
Fixed in https://github.com/chef/chef/pull/8202
