### ISSUE TITLE
windows_package checks if source exist even if package is installed

### ISSUE THREAD

**Issue by yamamoto52** [chef/chef#7670]
## Description
windows_package checks if source exist even if package is installed. If source was deleted after installation, second chef-client run is broken with "Source for package xyz does not exist". If I downloaded sources again, all process passed and windows_package was skipped becouse "up to date". It worked in version 13.5.28

## Chef Version
14.3.37 and 14.5.28

## Platform Version
Windows 2012r2
## Replication Case

-download sources manually

-implement modules like :

  windows_package package_name do
    source path_to_installation_file
    installer_type path_to_installation_file
  end

  file 'Coverity package' do
    path path_to_installation_file
    action :delete
    backup false
    retries 5
  end

-rerun chef-client

## Client Output

* windows_package[xyz] action install[2018-09-21T11:45:59+02:00] INFO: Processing
windows_package[xyz] action install (xyz::install line 37)

           * Source for package xyz does not exist
           ================================================================================
           Error executing action `install` on resource 'windows_package[xyz]'
           ================================================================================

           Chef::Exceptions::Package
           -------------------------
           Source for package xyz does not exist

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/xyz/recipes/install.rb

            37: windows_package package_name do
            38:   source path_to_installation_file
            39:   installer_type :custom
            40:   timeout 1800
            41: end
            42:

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/xyz/recipes/install.rb:37:in `from_file'

           windows_package("xyz") do
             package_name "xyz"
             action [:install]
             default_guard_interpreter :default
             declared_type :windows_package
             cookbook_name "coverity"
             recipe_name "install"
             source "c:\\chef\\cache\\xyz\\sources\\xyz.exe"
             installer_type :custom
             timeout 1800
           end

           System Info:
           ------------
           chef_version=14.5.28
           platform=windows
           platform_version=6.3.9600
           ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
           program_name=C:/opscode/chef/bin/chef-client
           executable=C:/opscode/chef/bin/chef-client

       [2018-09-21T11:45:59+02:00] INFO: Running queued delayed notifications before re-raising exception

**Comment by lamont-granquist** [comment]
This is generally correct behavior for the overall package resource (it doesn't entirely make sense for installing windows exe types, but for every other source package installer it makes sense).

If you want to avoid this you should use an `only_if { ::File.exist?("c:\\chef\\cache\\xyz\\sources\\xyz.exe") }` and essentially be explicit that you want to bypass that check.
