### ISSUE TITLE
`knife bootstrap` should support a `--sudo-command` argument

### ISSUE THREAD

**Issue by jacobtolar** [chef/chef#7689]
## Description
I sometimes need to run `knife bootstrap` on a host with extra arguments to sudo.

Here's the patch I applied locally to `/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.6.4/lib/chef/knife/bootstrap.rb` to do this. If this makes sense I can submit a PR.

```diff
--- knife/bootstrap.rb	2018-09-25 16:57:28.000000000 -0500
+++ knife/bootstrap-mine.rb	2018-09-25 16:57:20.000000000 -0500
@@ -139,6 +139,10 @@
         :description => "Execute the bootstrap via sudo",
         :boolean => true

+      option :sudo_command,
+        :long => "--sudo-command COMMAND",
+        :description => "The sudo command to use on the remote host"
+
       option :preserve_home,
         :long => "--sudo-preserve-home",
         :description => "Preserve non-root user HOME environment variable with sudo",
@@ -463,7 +467,8 @@
         command = render_template

         if config[:use_sudo]
-          sudo_prefix = config[:use_sudo_password] ? "echo '#{config[:ssh_password]}' | sudo -S " : "sudo "
+          sudo_cmd = config[:sudo_command] || 'sudo'
+          sudo_prefix = config[:use_sudo_password] ? "echo '#{config[:ssh_password]}' | #{sudo_cmd} -S " : "#{sudo_cmd} "
           command = config[:preserve_home] ? "#{sudo_prefix} #{command}" : "#{sudo_prefix} -H #{command}"
         end
```

Example -- in this case I have access to a host where only headless users can sudo as root: 

```bash
knife bootstrap -A somehost  -N somehost  -x jacob --sudo  -y --sudo-command 'sudo -u some_other_user sudo'
```

**Comment by vsingh-msys** [comment]
Hi @jacobtolar, sorry for the delayed response.

I think we have in place  `--bootstrap-preinstall-command COMMAND` option. You can run any desired command with or without sudo based on your need. Hope this will address your query?

Thanks!

**Comment by vsingh-msys** [comment]
Closing for now, hope the above workaround will work for you. Thanks

**Comment by jacobtolar** [comment]
I want pass additional options to `sudo` during actual bootstrap. 

Per this comment this still isn't really supported.

https://github.com/chef/chef/blob/63a4af262d777a80c24990368312c2f793eae11c/lib/chef/knife/bootstrap.rb

Since this has all been refactored, would you accept a pull request to add a new `--sudo-options` option?

**Comment by vsingh-msys** [comment]
Could you please try first with the latest chef-15 and provide the logs with your desired command?

**Comment by vsingh-msys** [comment]
Hey @jacobtolar, Feel free to open a PR and it would be good if you would mention something like:
```
 As a <<user_profile>>, 
 I want to <<functionality>>,
 so that <<benefit>>.
```
Thanks!
