### ISSUE TITLE
powershell_package misbehaves when network connectivity to the internet is not available

### ISSUE THREAD

**Issue by cnunemaker** [chef/chef#7700]
## Description

When no network connection to the internet is available, the powershell_package resource does not behave as expected in two different ways:
1. When a powershell_package resource **with no** version property is given, the resource appears to install successfully giving an `action install (up to date)` although in reality it has failed to do so due to a lack of access to the internet.
2. When a powershell_package resource **with** a version property is given, the resource fails to execute the install action due to an `ArgumentError` attributed to a `malformed version number string` even when given a valid version number string.
## Chef Version

Chef Client, version 14.5.33 x64
## Platform Version

Windows Server 2016 Version 1607 64-bit
## Replication Case

For this example we are using the [SecurityPolicyDsc](https://github.com/PowerShell/SecurityPolicyDsc/releases) PowerShell module.
Create a simple cookbook called `foobar` with either of the following `default.rb` recipes:
### Case 1
```ruby
powershell_package 'SecurityPolicyDsc'
```
### Case 2
```ruby
powershell_package 'SecurityPolicyDsc' do
  version '2.5.0.0'
end
```
Ensure network connectivity to the internet is disabled.
Run `chef-client -z -o foobar` to execute the cookbook.
### Case 1
For the first case where no version property is given, the following unexpected output is presented:
```
Converging 1 resources
Recipe: foobar::default
  * powershell_package[SecurityPolicyDsc] action install (up to date)
```
Full output log [here](https://gist.github.com/cnunemaker/a0867026c179971e1d9f8979728926c2).
It does however say `0/1 resources updated` at completion.

Upon running the same recipe with `-l debug` logging enabled gives the following warnings:
```
WARNING: Network connectivity may not be available, unable to reach remote sources.
WARNING: Unable to bootstrap the required package provider due to problems with network connectivity. Please fix your
network connection. If this is not possible, refer to 'Get-Help Install-PackageProvider' or
http://go.microsoft.com/fwlink/?LinkId=626941 for guidance on installing the package provider manually.
WARNING: MSG:UnableToDownload �https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409� ��
WARNING: Unable to download the list of available providers. Check your internet connection.
Get-Package : No package found for 'SecurityPolicyDsc'.
At line:1 char:3
+ ( Get-Package 'SecurityPolicyDsc' -Force -ForceBootstrap ).Version
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...lets.GetPackage:GetPackage) [Get-Package], Exception
    + FullyQualifiedErrorId : NoMatchFound,Microsoft.PowerShell.PackageManagement.Cmdlets.GetPackage
```
Full output log [here](https://gist.github.com/cnunemaker/6253dff0ab119e169f28b1aca62bef3a).
### Case 2
For the second case where a version property is given, the following error is presented:
```
Converging 1 resources
Recipe: foobar::default
  * powershell_package[SecurityPolicyDsc] action install

    ================================================================================
    Error executing action `install` on resource 'powershell_package[SecurityPolicyDsc]'
    ================================================================================

    ArgumentError
    -------------
    Malformed version number string WARNING: Network connectivity may not be available, unable to reach remote sources.
    WARNING: Unable to bootstrap the required package provider due to problems with network connectivity. Please fix your
    network connection. If this is not possible, refer to 'Get-Help Install-PackageProvider' or
    http://go.microsoft.com/fwlink/?LinkId=626941 for guidance on installing the package provider manually.
    WARNING: MSG:UnableToDownload �https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409� ��
    WARNING: Unable to download the list of available providers. Check your internet connection.
```
Full output log [here](https://gist.github.com/cnunemaker/b0085d66b60b2abf88c860f49cf9bbe0).

Upon running the same recipe with `-l debug` logging enabled gives similar output.
Full output log [here](https://gist.github.com/cnunemaker/29644ae7a51e6bfbc5ed5adfacd3e8bd).
### Case 1
No stacktraces generated.
### Case 2
[Trace 1](https://gist.github.com/cnunemaker/744eb50fd87db994292f758327b3c7a0)
[Trace 2](https://gist.github.com/cnunemaker/6dccea2da6ee14d8864d2e99dbf33cec)

**Comment by lamont-granquist** [comment]
Some combination of #7701, #7703, #7705 should have fixed this i think.
