### ISSUE TITLE
Odd behaviour where permissions are not set using remote_file with file:// path

### ISSUE THREAD

**Issue by lozzd** [chef/chef#7711]
## Description
If you write a resource like the following:
```
remote_file "/tmp/blah" do
  source "file:////usr/bin/true"
  mode '4755'
  owner 0
  group 0
end
```

If the destination file does not exist, it is copied and the sticky bit is correctly set. 
If the destination file does exist and the contents have not changed, Chef has nothing to do, so everything is good. 
If the destination file does exist and the contents *have* changed, the source is copied to the destination file but *the sticky bit is missing*
If the destination file does exist and the contents have not changed but the permissions are wrong (because of the above situation), the sticky bit is then set on the file. 

Essentially, if you copy a file using the above method with a sticky bit, the first Chef after the source has changed will copy the file, but miss the sticky bit. The second Chef run will fix the sticky bit. 

## Chef Version
chef-client (14.2.0), seen also in 12.17.44

## Platform Version
RHEL 7.3

## Replication Case
(all of the below can be replicated via chef-shell)

Create a recipe like:
```
remote_file "/tmp/blah" do
  source "file:////usr/bin/true"
  mode '4755'
  owner 0
  group 0
end
```

Run it so the file exists. From here on, you can now replicate behaviour. 

Observe the correct permissions after running the above:
```
# ls -laht /tmp/blah
-rwsr-xr-x 1 root root 29K Oct  2 13:58 /tmp/blah
```

Now run the following:
```
remote_file "/tmp/blah" do
  source "file:////usr/bin/false"
  mode '4755'
  owner 0
  group 0
end
```
Note the source file has changed, but perms have not.

The following output is printed:
```
chef:recipe (14.2.0)> run_chef
[2018-10-02T14:06:02-04:00] INFO: Processing remote_file[/tmp/blah] action create ((irb#3) line 1)
[2018-10-02T14:06:02-04:00] INFO: remote_file[/tmp/blah] backed up to /var/chef/backup/tmp/blah.chef-20181002140602.096783
[2018-10-02T14:06:02-04:00] INFO: remote_file[/tmp/blah] removed backup at /var/chef/backup/tmp/blah.chef-20181002134823.201924
[2018-10-02T14:06:02-04:00] INFO: remote_file[/tmp/blah] updated file contents /tmp/blah
```

Note there is no line about setting or updating permissions.
Observe the permissions on disk are now incorrect, missing sticky bit:
```
# ls -laht /tmp/blah
-rwxr-xr-x 1 root root 29K Oct  2 14:06 /tmp/blah
```

If you re-run the above *exactly* the same without changing the recipe, the sticky bit is re-added!

```
chef:recipe (14.2.0)> run_chef
[2018-10-02T14:07:29-04:00] INFO: Processing remote_file[/tmp/blah] action create ((irb#3) line 1)
[2018-10-02T14:07:29-04:00] INFO: remote_file[/tmp/blah] mode changed to 4755
```

This is demonstrated quite nicely if you now change the source back to `/bin/true` (so the source has once again changed) and put the same exact resource twice:

```
remote_file "/tmp/blah" do
  source "file:////usr/bin/true"
  mode '4755'
  owner 0
  group 0
end
remote_file "/tmp/blah" do
  source "file:////usr/bin/true"
  mode '4755'
  owner 0
  group 0
end
```

Now run the recipe:
```
chef:recipe (14.2.0)> run_chef
[2018-10-02T14:09:37-04:00] INFO: Processing remote_file[/tmp/blah] action create ((irb#1) line 1)
[2018-10-02T14:09:37-04:00] INFO: remote_file[/tmp/blah] backed up to /var/chef/backup/tmp/blah.chef-20181002140937.800594
[2018-10-02T14:09:37-04:00] INFO: remote_file[/tmp/blah] removed backup at /var/chef/backup/tmp/blah.chef-20181002134916.944724
[2018-10-02T14:09:37-04:00] INFO: remote_file[/tmp/blah] updated file contents /tmp/blah
[2018-10-02T14:09:37-04:00] INFO: Processing remote_file[/tmp/blah] action create ((irb#1) line 7)
[2018-10-02T14:09:37-04:00] INFO: remote_file[/tmp/blah] mode changed to 4755
```

Note the first time around (resource starting line 1) it copies the source to the destination, as it's changed, but perms aren't touched. The exact same resource a second time (line 7) then corrects the permissions. This demonstrates the lack of idempotence.

It may be the case that this is related to the behaviour of sticky bits, specifically:
``` 
When  the  owner  or  group  of  an  executable file are changed by an
  unprivileged user the S_ISUID  and  S_ISGID  mode  bits  are  cleared.
  POSIX  does not specify whether this also should happen when root does
  the chown(); the Linux behavior depends on  the  kernel  version.
```

it's unclear if Chef is doing a `chown()` on that first file copy when the source file changes - perhaps if it is, the sticky bit is being cleared on purpose and then Chef is able to set it back again on the second run (but why would it not notice the first time?)

**Comment by lamont-granquist** [comment]
That is happening here:

https://github.com/chef/chef/blob/master/lib/chef/file_content_management/deploy/mv_unix.rb#L37-L72

chmod happens before chgrp/chown, so it gets stripped.

also i wonder if the mv also helpfully strips sticky bits or not...  shockingly it looks like it does not...

**Comment by lozzd** [comment]
Many thanks! ❤️
