### ISSUE TITLE
windows_ad_join resource fails to join 

### ISSUE THREAD

**Issue by gsreynolds** [chef/chef#7715]
## Description
`windows_ad_join` fails with `Add-Computer : Computer 'HOSTNAMEHERE' failed to join domain
    'DOMAINHERE' from its current workgroup 'WORKGROUP' with following
    error message: Unable to update the password. The value provided as the
    current password is incorrect.`

Manually (via GUI or PS) joining the domain on the same machine with the same creds & domain FQDN works successfully.

## Chef Version
14.5.33

## Platform Version
Windows Server 2012R2

## Replication Case
```
windows_ad_join 'Join Domain' do
  action           :join
  domain_user      advault['username']
  domain_password  advault['password']
  domain_name      node['domainfqdn']
  ou_path          node['oupath']
  reboot           :delayed
  sensitive        true
end
```

After CCR fails, RDP'ing to the system and either using the Windows GUI or using PowerShell to join the domain with the same creds from the `advault` item and the domainfqdn in that environment's attributes works successfully. Replicated this on two 2k12R2 systems. 

## Client Output
```
Recipe: basenode::windows
  * windows_ad_join[Join Domain] action join[2018-10-03T12:33:19+01:00] INFO: Processing windows_ad_join[Join Domain] action join (basenode::windows line 8)

    ================================================================================
    Error executing action `join` on resource 'windows_ad_join[Join Domain]'
    ================================================================================

    RuntimeError
    ------------
    Failed to join the domain DOMAINHERE: Add-Computer : Computer 'HOSTNAMEHERE' failed to join domain
    'DOMAINHERE' from its current workgroup 'WORKGROUP' with following
    error message: Unable to update the password. The value provided as the
    current password is incorrect.

    At line:1 char:164
    + $pswd = ConvertTo-SecureString 'PASSWORDHERE' -AsPlainText
    -Force;$credential =  ...

    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : OperationStopped: (HOSTNAMEHERE:String) [Add-C
       omputer], InvalidOperationException
        + FullyQualifiedErrorId : FailToJoinDomainFromWorkgroup,Microsoft.PowerShe
       ll.Commands.AddComputerCommand
    }


    Resource Declaration:
    ---------------------
    suppressed sensitive resource output

    Compiled Resource:
    ------------------
    suppressed sensitive resource output


    System Info:
    ------------

    chef_version=14.5.33
    platform=windows
    platform_version=6.3.9600
    ruby=ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]
    program_name=C:/opscode/chef/bin/chef-client
    executable=C:/opscode/chef/bin/chef-client


[2018-10-03T12:33:22+01:00] INFO: Running queued delayed notifications before re-raising exception
Running handlers:
[2018-10-03T12:33:22+01:00] ERROR: Running exception handlers
Running handlers complete
[2018-10-03T12:33:22+01:00] ERROR: Exception handlers complete
Chef Client failed. 8 resources updated in 48 seconds
```

**Comment by Happycoil** [comment]
Does `advault['username']` contain `DOMAIN\samaccountname` or just `samaccountname`? I seem to remember some funky stuff about interactive vs noninteractive when it comes to `Add-Computer`.

**Comment by gsreynolds** [comment]
Good shout, I’ll pass that suggestion on; thanks for the PowerShell-fu @happycoil ! It had a few of us stumped pulling apart the recipe and the resource and the next step with them was to capture the `powershell_script` to compare.

**Comment by gsreynolds** [comment]
Just to update, using `DOMAIN\username` with the resource does work and fixed the problem. We should probably decide on a validation strategy and documentation change here and in #7718

**Comment by Happycoil** [comment]
@gsreynolds does using the DNS domain name as the resource name work as well? Are we seeing different behaviours because of different windows server versions and AD functional levels perhaps?

**Comment by RupertExact** [comment]
It doesn't seem to matter whether using UPN or domain\user, neither works. I'm wondering if there isn't a deeper issue as the elevation of powershell_script doesn't work either.

**Comment by RupertExact** [comment]
It doesn't seem to matter with the user is user@domain.com or domain\user or whether domain_name is specified or taken from resource name. None of them work. Maybe this is part of the same issue with elevation of powershell_script resource not working? Either way it's pretty limiting when working with windows machines.

**Comment by Blankf** [comment]
I have the same problem, and it has to do with that "SYSTEM" cannot join you to the domain.

https://social.technet.microsoft.com/Forums/en-US/cb6f2595-c37e-41e2-952d-9d9ae7ea8865/running-powerhshell-addcomputer-as-localsystem-fails?forum=winserverGP

it would be good to have the option to run this resource as another user.

**Comment by stuartpreston** [comment]
@Blankf That's interesting... I read that thread a different way...  the use of System account (via Chef) is to run the PowerShell, that takes the UPN (i.e. user@domain.local) and the password required from the resource and should be using these to join the domain. The System account is not (should not) be the account authenticating to the domain.

The most recent comment in that thread looked most relevant to me?
> But in a non-interactive environment, the domain is not known as such it’s a very simple fix, make sure you either include the short domain names like “contoso\DMAdmin” or the **full FQDN “DMAdmin@contoso.com.

**Comment by Blankf** [comment]
@stuartpreston the system account is not able to do network lookups so if you specify the domain you are still not able to connect to the domain, it needs to be done in a user context.

The standard windows_ad_join uses the user@fqdn \ password, but that will fail.
i even ran the code from the cookbook manually under system with psexec, it and failed.

i now used the dsc_resource computer with the PsDscRunAsCredential from a local account, that works fine, i rather have that option in the chef resource.
