### ISSUE TITLE
windows_task: Add support in windows_task to enable history for the task created .

### ISSUE THREAD

**Issue by Vasu1105** [chef/chef#7746]
## Description
windows_task currently don't have feature to support enable History. I am opening this PR in respect of this issue open in chef-web-docs https://github.com/chef/chef-web-docs/issues/1589

## Chef Version
Feature request

## Replication Case
Just run any windows_task recipe the history show as disabled.
```
windows_task 'hello' do
  frequency :onstart
  command 'echo Hello'
end
```

**Comment by kapilchouhan99** [comment]
@btm, @stuartpreston, @Vasu1105 ##Note: For task scheduler, if history is enabled it gets enabled for all tasks, it's not a task specific feature.

I have found a Powershell command `wevtutil set-log Microsoft-Windows-TaskScheduler/Operational /enabled:true` which enables the task history through a command line.

So adding this feature will enable the history for all the task and not for a particular task so just want to get confirmation should we add this as an option in the windows_task resource.

**Comment by stuartpreston** [comment]
Yes, we should not perform a global configuration change when the user is expecting just the individual task to be configured.  Is that possible today (to individually set the history to enabled on a task?)

**Comment by kapilchouhan99** [comment]
@stuartpreston through Desktop app also we have checked when we enable the history it gets enabled for all the task.

**Comment by Vasu1105** [comment]
@stuartpreston Currently individually enabling of task is not possible. Since this feature itself is not there in the taskscheduler.

**Comment by stuartpreston** [comment]
In that case my opinion is that we should not expose this setting as a property of a single task, as it will cause confusion.  Instead we should have a separate resource that is something like a `windows_eventlog_configuration` resource that takes the required settings and applies them globally and add a reference to the documentation.

**Comment by tas50** [comment]
I'm with @stuartpreston on this change. This is a global config and it breaks promise theory and Chef's overall model.
