### ISSUE TITLE
knife status --run-list -l shows invalid/incorrect output

### ISSUE THREAD

**Issue by dragon788** [chef/chef#7764]
Description
When running `knife status -l --run-list` I get an empty field between commas where the run-list/roles should be.

ChefDK Version
Chef Development Kit Version: 2.4.17
chef-client version: 13.6.4
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 6.3.1
kitchen version: 1.19.2
inspec version: 1.45.13

Platform Version
Ubuntu 16.04.3 LTS

Replication Case
Run `knife status -m --run-list` and observe the 3rd "field" being the role.
Run `knife status -l --run-list` and observe the 3rd "field" being empty (where the role should be).

**Comment by vsingh-msys** [comment]
Fixed in #8415
