### ISSUE TITLE
Remove "Code Can" from the logo in macOS DMGs

### ISSUE THREAD

**Issue by tas50** [chef/chef#7783]
This image need to get updated to a higher resolution and the old slogan needs to get removed.

<img width="762" alt="screen shot 2018-10-25 at 8 39 25 pm" src="https://user-images.githubusercontent.com/1015200/47543266-2dce7800-d896-11e8-84df-3e6b123a071f.png">

**Comment by lamont-granquist** [comment]
Did this ever get done?

**Comment by tas50** [comment]
Nope https://github.com/chef/chef/blob/master/omnibus/resources/chef/dmg/background.png

**Comment by tas50** [comment]
This was done in https://github.com/chef/chef/commit/2a1823174c72c655d942af79876a4abc8d231f8a
