### ISSUE TITLE
windows_task set's "Run only when user is logged on" if not using system account

### ISSUE THREAD

**Issue by chadmccune** [chef/chef#7801]
## Description
If specifying a username and password, the task gets set with the "Run only when user is logged on" flag

## Chef Version
14.6.47

## Platform Version
Windows Server 2016 (Version 1607 OS Build 14393.447)

## Replication Case

      windows_task 'my task' do
        command 'cmd /c echo see what I mean '
        action :create
        frequency :minute
        frequency_modifier 1
        execution_time_limit 28800 # 8 hours
        start_day '01/01/2018'
        start_time '00:00'
        user user
        password pass
        interactive_enabled true
      end

## Client Output
Sorry, already rolled back to 14.5.33, don't have the output available.

**Comment by tas50** [comment]
This will go out in Chef 14.7

**Comment by dotcircel** [comment]
I am still having this issue even with Chef 14.7

**Comment by Vasu1105** [comment]
@dotcircel Are you running the same recipe?

**Comment by dotcircel** [comment]
@Vasu1105 more or less. The only difference is that the user is domain user.

**Comment by Nimesh-Msys** [comment]
@dotcircel : you also need to set `interactive_enabled` as false

**Comment by dotcircel** [comment]
@Nimesh-Msys That indeed was the problem. Thanks for clearing it up.
