### ISSUE TITLE
Add ISO mounting support on Windows to core

### ISSUE THREAD

**Issue by gsreynolds** [chef/chef#7824]
Mounting ISOs on Windows is a semi-regularly requested feature for certain specific use cases. IMHO options are:

1. extend the `mount` resource by adding a `file` property and adding support to the windows provider using the `Mount-DiskImage` cmdlet
2. extend the `mount` resource by using the existing `device` property and in the windows provider matching on the file extension (e.g. `^.*\.iso$`) to switch behaviour to use `Mount-DiskImage` cmdlet 
3. have a specific `windows_mount_iso` resource separately and not extend `mount`

I'd tend towards option 2 as it's already possible to mount ISOs in *nix-land using the `mount` resource and the `device` property:
```ruby
  mount '/mnt' do
    device 'test.iso'
    options 'loop'
    action :mount
  end
```

I've created a quick custom resource modelled after the `mount` resource to do this: https://github.com/gsreynolds/mount_iso/blob/master/resources/windows_mount_iso.rb

```ruby
  windows_mount_iso 'Z:' do
    device 'test.iso'
    action :mount
  end
```

One thing to note is that the `Mount-DiskImage` cmdlet can't specify a drive letter to mount as, so needs to be mounted and then the drive letter can be changed in two steps.

If we go for option 3, there's an argument for making the ISO source the name property and the drive letter a property instead for semantics as the following isn't that descriptive:
```
         * remote_file[test.iso] action create (up to date)
         * windows_mount_iso[Z:] action mount
```

**Comment by stuartpreston** [comment]
@gsreynolds As per discussion, it would be good to make this generic and support VHD images (as the [underlying PowerShell cmdlet](https://docs.microsoft.com/en-us/powershell/module/storage/mount-diskimage?view=win10-ps) does).  Despite the semantics of the `mount` resource I think we should call this `windows_mount_image`, the `name_property` should be the image and we should take a `drive_letter` property too.  We'd end up with something like:
```ruby
windows_mount_image '\\mysmbshare\images\myiso.iso' do
  drive_letter 'Z:'
  access_mode :read_only
  action :mount
end
```
There may also be some user-mode restrictions to look at here (e.g. assigning a drive letter when you don't have an interactive session might cause some troubles).  Let's have a go with your custom resource and then we can look at bringing that in to core with Chef 15.  Thanks!

**Comment by tas50** [comment]
I'm going to close this issue out at this point since it's been 3 years and we haven't seen this move higher in our windows backlog priority. If someone is interested in working on this issue we'd gladly accept a PR for this functionality, bu the Infra Client team won't be working on it unless priorities change.
