### ISSUE TITLE
Add trusted_certificate resource to chef-client

### ISSUE THREAD

**Issue by tas50** [chef/chef#7861]
### Core Chef Resource Checklist

Before suggesting a resource for inclusion please make sure your suggestion meets these criteria for resources built into Chef:
 - [x] Automates an operating system component that ships by default on systems such as authentication, raid, disk partitions, firewalls, containers, or virtualization systems.
 - [x] Does not attempt automate 3rd party applications such as database, web, or application servers, which are best suited for cookbooks due to their fast moving nature.

### Describe the resource:
A trusted_certificate resource will allow you to install certificates on macos / linux systems that will be trusted by the OS and apps.

### Why should this be included out of the box?:

A lot of people need to install certificates on their nodes and this would give them an easy way to do it out of the box.

### What operating systems would it run on?
Linux and macOS would be easy to implement. We can already have windows_certificate so it wouldn't make sense to do it again here.

### Current cookbook implementation:
https://github.com/chef-cookbooks/trusted_certificate

**Comment by pantocrator27** [comment]
Should there also be an option to add a certificate to the certificate store that ships with Chef?

**Comment by tas50** [comment]
@pantocrator27 Ideally we'd have a resource `chef_certificate` to handle that. It would be entirely different than adding certs on linux vs. mac vs. windows where as the Chef certificate experience would be the same on every platform.
