### ISSUE TITLE
The `windows_printer` resource doesn't re-converge when properties change.

### ISSUE THREAD

**Issue by bmiller08** [chef/chef#7877]
## Description
Changing the properties of an existing `windows_printer` resource does not cause the printer to be updated unless the `device_id` changes because this becomes a "new" printer. It looks like this resource only checks the registry for the appropriate name (the `device_id` property) to confirm whether or not it exists and does not care about other properties.

## Chef Version
14.5.33

## Platform Version
Windows 10 1809

## Replication Case
Add a `windows_printer` resource to a cookbook. Run `chef-client`. Update this cookbook and change any property other then `device_id`. Run `chef-client` again and note that this resource says `already exists - nothing to do`.

**Comment by jasonwbarnett** [comment]
I believe the current implementation of the `windows_printer` is going to be challenging to make it idempotent. I think this is going to have to be re-implemented using the vbs scripts (`C:\Windows\System32\Printing_Admin_Scripts\en-US`) provided by Microsoft.

References:

- https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/prnmngr
- https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/prncnfg
- https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/prnport

**Comment by bmiller08** [comment]
There is also powershell:

https://docs.microsoft.com/en-us/powershell/module/printmanagement/?view=win10-ps

But that may limit OS compatibility to 8 and above where those VBS scripts
I believe are available from Windows 7 and up. There is also multiple ways
in which default printer management is handled in Windows 10 which makes
this difficult:

https://support.microsoft.com/en-us/help/4028622/windows-10-how-to-set-a-default-printer

Finally, the current implementation using wmic also sometimes results in
access denied errors although I have not been able to figure out why. For
now I built a custom resource to work around everything above using
Powershell.

Just some items for thought.

**Comment by tas50** [comment]
Fixed by https://github.com/chef/chef/pull/11703
