### ISSUE TITLE
Use of `win_friendly_path` in core chef

### ISSUE THREAD

**Issue by shoekstra** [chef/chef#7915]
`win_friendly_path` is referenced [here](https://github.com/chef/chef/blob/a19f38f1e8799419f33b12f13c3c622eff542e69/lib/chef/resource/windows_certificate.rb#L182) but I can't see where it is defined.

I found this when removing the windows cookbook as a dependency from a cookbook and looking if it had been ported to core Chef.

This method should probably be added to core Chef or this reference removed.

**Comment by tas50** [comment]
The cookbook side of the fix is here https://github.com/chef-cookbooks/windows/pull/589

**Comment by tas50** [comment]
This is fixed in master and backported to chef 14. The next release will fix it. Thanks for the report @shoekstra
