### ISSUE TITLE
Zypper_package prevents upgrade package on chef client > 12.6

### ISSUE THREAD

**Issue by rjnkmr04** [chef/chef#7919]
It appears that changes were made to zypper.rb that now prevents upgrades. This seems to be a fundamental problem. Would anyone happen to know if there is a possible work around for this issue or if there exists a patch? We see that even the latest available chef client versions also exhinit the same problem”.

Can you please update on this issue. Thanks in advance.

## Description
It appears that changes were made to zypper.rb that now prevents upgrades. This seems to be a fundamental problem. Would anyone happen to know if there is a possible work around for this issue or if there exists a patch? We see that even the latest available chef client versions also exist the same problem”.

## Chef Version
chef client > 12.6 

## Platform Version
SLES12 and SLES15

## Client Output
package is uptodate even there is new package is available in repo.

```

```

**Comment by rjnkmr04** [comment]
Do we have any latest update on this issue. Thanks

**Comment by lamont-granquist** [comment]
There's not enough information in this issue

**Comment by pixdrift** [comment]
@rjnkmr04 can you provide a reproducer for this? ie. what are you executing and what the result is vs. expected result?

**Comment by tas50** [comment]
I'm going to close this out at this point. If you want to open a new issue that provides the necessary examples of what you're trying to accomplish we can dig in and see what we can do. There's not enough information in this ticket though to investigate.
