### ISSUE TITLE
yum_resource Chef Resource with priority Attribute

### ISSUE THREAD

**Issue by pantocrator27** [chef/chef#7923]
## Description
The `yum_resource` exposes a `priority` attribute.  The idea based on the Chef documentation is `Assigns a priority to a repository where the priority value is between ‘1’ and ‘99’ inclusive. Priorities are used to enforce ordered protection of repositories. Packages from repositories with a lower priority (higher numerical value) will never be used to upgrade packages that were installed from a repository with a higher priority (lower numerical value). The repositories with the lowest numerical priority number have the highest priority.`  However in order for the `priority` attribute to work, the yum priority plugin must be installed which is not always the case by default.  

## Chef Version
All

## Platform Version
Any in which the yum_resource will work

**Comment by lamont-granquist** [comment]
i think we're going to leave this up to the end user to ensure that the plugin is installed if they want to use this.

**Comment by pantocrator27** [comment]
Can this at least be documented?
