### ISSUE TITLE
windows_share resource is not idempotent

### ISSUE THREAD

**Issue by chadmccune** [chef/chef#7933]
## Description
windows_share resource succeeds on first run, but fails on following runs

## Chef Version
14.7.17

## Platform Version
Windows Server 2016

## Replication Case
windows_share 'MyShare' do
  action :create
  path archive_folder
  full_users [ "domain\domain admins", "domain\user2" ]
  read_users [ "domain\user3" ]
end

## Client Output
STDERR: Revoke-SmbShareAccess : No mapping between account names and security IDs was done.

## Stacktrace

Generated at 2018-11-13 14:51:44 -0600
Mixlib::ShellOut::ShellCommandFailed: windows_share[ArchivedBackups] (selerix_archivers::default line 288) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of powershell.exe -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -Command "Revoke-SmbShareAccess -Name 'ArchivedBackups' -AccountName \"KITCHEN\Domain Admins,KITCHEN\sqlarchiver,KITCHEN\intranetmonitor,KITCHEN\intranetoperator,KITCHEN\nagios\" -Force" ----
STDOUT: 
STDERR: Revoke-SmbShareAccess : No mapping between account names and security IDs was done. 

At line:1 char:1

+ Revoke-SmbShareAccess -Name 'ArchivedBackups' -AccountName "KITCHEN\D ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (MSFT_SmbShare (...copeName = "*"):ROOT/Microsoft/Windows/SMB/MSFT_SMBShar 

   e) [Revoke-SmbShareAccess], CimException

    + FullyQualifiedErrorId : Windows System Error 1332,Revoke-SmbShareAccess
---- End output of powershell.exe -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -Command "Revoke-SmbShareAccess -Name 'ArchivedBackups' -AccountName \"KITCHEN\Domain Admins,KITCHEN\sqlarchiver,KITCHEN\intranetmonitor,KITCHEN\intranetoperator,KITCHEN\nagios\" -Force" ----
Ran powershell.exe -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -Command "Revoke-SmbShareAccess -Name 'ArchivedBackups' -AccountName \"KITCHEN\Domain Admins,KITCHEN\sqlarchiver,KITCHEN\intranetmonitor,KITCHEN\intranetoperator,KITCHEN\nagios\" -Force" returned 1
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.0-universal-mingw32/lib/mixlib/shellout.rb:297:in `invalid!'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.0-universal-mingw32/lib/mixlib/shellout.rb:284:in `error!'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/mixin/powershell_out.rb:48:in `powershell_out!'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource/windows_share.rb:303:in `revoke_user_permissions'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource/windows_share.rb:264:in `update_permissions'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource/windows_share.rb:199:in `block (2 levels) in <class:WindowsShare>'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/mixin/why_run.rb:51:in `add_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/provider.rb:227:in `converge_by'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/provider.rb:300:in `converge_if_changed'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource/windows_share.rb:185:in `block in <class:WindowsShare>'
(eval):2:in `block in action_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/provider.rb:236:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/provider.rb:236:in `compile_and_converge_action'
(eval):2:in `action_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/provider.rb:182:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource.rb:578:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/runner.rb:98:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/runner.rb:97:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/client.rb:720:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/client.rb:715:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/client.rb:715:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/client.rb:754:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/application.rb:279:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/application.rb:261:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/application/client.rb:440:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/application.rb:66:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/bin/chef-client:74:in `load'
C:/opscode/chef/bin/chef-client:74:in `<main>'

>>>> Caused by Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of powershell.exe -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -Command "Revoke-SmbShareAccess -Name 'ArchivedBackups' -AccountName \"KITCHEN\Domain Admins,KITCHEN\sqlarchiver,KITCHEN\intranetmonitor,KITCHEN\intranetoperator,KITCHEN\nagios\" -Force" ----
STDOUT: 
STDERR: Revoke-SmbShareAccess : No mapping between account names and security IDs was done. 

At line:1 char:1

+ Revoke-SmbShareAccess -Name 'ArchivedBackups' -AccountName "KITCHEN\D ...

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    + CategoryInfo          : NotSpecified: (MSFT_SmbShare (...copeName = "*"):ROOT/Microsoft/Windows/SMB/MSFT_SMBShar 

   e) [Revoke-SmbShareAccess], CimException

    + FullyQualifiedErrorId : Windows System Error 1332,Revoke-SmbShareAccess
---- End output of powershell.exe -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -Command "Revoke-SmbShareAccess -Name 'ArchivedBackups' -AccountName \"KITCHEN\Domain Admins,KITCHEN\sqlarchiver,KITCHEN\intranetmonitor,KITCHEN\intranetoperator,KITCHEN\nagios\" -Force" ----
Ran powershell.exe -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Unrestricted -InputFormat None -Command "Revoke-SmbShareAccess -Name 'ArchivedBackups' -AccountName \"KITCHEN\Domain Admins,KITCHEN\sqlarchiver,KITCHEN\intranetmonitor,KITCHEN\intranetoperator,KITCHEN\nagios\" -Force" returned 1
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.0-universal-mingw32/lib/mixlib/shellout.rb:297:in `invalid!'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/mixlib-shellout-2.4.0-universal-mingw32/lib/mixlib/shellout.rb:284:in `error!'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/mixin/powershell_out.rb:48:in `powershell_out!'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource/windows_share.rb:303:in `revoke_user_permissions'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource/windows_share.rb:264:in `update_permissions'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource/windows_share.rb:199:in `block (2 levels) in <class:WindowsShare>'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/mixin/why_run.rb:51:in `add_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/provider.rb:227:in `converge_by'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/provider.rb:300:in `converge_if_changed'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource/windows_share.rb:185:in `block in <class:WindowsShare>'
(eval):2:in `block in action_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/provider.rb:236:in `instance_eval'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/provider.rb:236:in `compile_and_converge_action'
(eval):2:in `action_create'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/provider.rb:182:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource.rb:578:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/runner.rb:70:in `run_action'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/runner.rb:98:in `block (2 levels) in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/runner.rb:98:in `each'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/runner.rb:98:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/runner.rb:97:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/client.rb:720:in `block in converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/client.rb:715:in `catch'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/client.rb:715:in `converge'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/client.rb:754:in `converge_and_save'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/client.rb:286:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/application.rb:279:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/local_mode.rb:44:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/application.rb:261:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/application/client.rb:440:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/lib/chef/application.rb:66:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.7.17-universal-mingw32/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/bin/chef-client:74:in `load'
C:/opscode/chef/bin/chef-client:74:in `<main>'

**Comment by derekgroh** [comment]
This error is occurring largely because the "Everyone" group is not included by default in this resource, however Windows creates grants this group Read Only access each time a share is created.

When the resource runs the second time, the value `current_resource.read_users` is now `[ "KITCHEN\user3", "Everyone" ]` while the `new_resource.read_users` is `[ "KITCHEN\user3" ]`

The quickest solution is to include "Everyone" in the read_users property, but I'm looking into a protection if people forget to do so as your other issue addresses the concern of removing "Everyone" if they are not defined.

```
windows_share 'MyShare' do
  action :create
  path archive_folder
  full_users [ "domain\domain admins", "domain\user2" ]
  read_users [ "Everyone", "domain\user3" ]
end
```

**Comment by chadmccune** [comment]
Including "Everyone" in the read_users list is not really an acceptable solution.  This share is not supposed to be readable by "everyone" :)

**Comment by derekgroh** [comment]
@tas50 There's a bug with Powershell 4 on Windows Server 2012 r2 where it is unable to convert to Json without the `-Compress` flag, would you like me to open another issue or tag it on here?

**Comment by tas50** [comment]
If you could open another PR for that I'd appreciate it
