### ISSUE TITLE
windows_share resource adds everyone group to share

### ISSUE THREAD

**Issue by chadmccune** [chef/chef#7934]
## Description
"everyone" is granted read access to shares created with the windows_share resource

## Chef Version
14.7.17

## Platform Version
Windows Server 2016

## Replication Case
windows_share 'MyShare' do
action :create
path archive_folder
full_users [ "domain\domain admins", "domain\user2" ]
read_users [ "domain\user3" ]
end

## Client Output
n/a

## Stacktrace
n/a

**Comment by derekgroh** [comment]
This is the default behavior of `New-SmbShare` powershell command as a default group needs access, similar to the CREATOR OWNER permission for NTFS.

The `everyone` group can be removed using `Revoke-SmbShareAccess -Name "MyShare" -AccountName "Everyone" -Force`.
