### ISSUE TITLE
/var/chef directory structure doesn't follow Filesystem Hierarchy Standard (FHS)

### ISSUE THREAD

**Issue by pixdrift** [chef/chef#8004]
## Description
The `/var/chef` directory structure used by default Chef configuration on Linux clients does not follow the Filesystem Hierarchy Standard (FHS) from Linux Standard Base (LSB).

From the FHS.
> Applications must generally not add directories to the top level of /var. Such directories should only be added if they have some system-wide implication, and in consultation with the FHS mailing list.

Source: http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05.html#purpose31

<br />

This could be moved to `/var/cache/chef` rather than `/var/chef/cache`
From the FHS.
> /var/cache is intended for cached data from applications. Such data is locally generated as a result of time-consuming I/O or calculation. The application must be able to regenerate or restore the data.

Source: http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s05.html

<br />

Alternatively, as the Chef package installs into `/opt/chef`, it could use `/var/opt/chef` directory/structure pattern:
> Variable data of the packages in /opt must be installed in /var/opt/\<subdir\>, where \<subdir\> is the name of the subtree in /opt where the static data from an add-on software package is stored, except where superseded by another file in /etc. No structure is imposed on the internal arrangement of /var/opt/<subdir>.

Source: http://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch05s12.html

## Chef Version
14.7.17

## Platform Version
CentOS / RHEL

**Comment by lamont-granquist** [comment]
We made a very deliberate decision nearly 8 years ago not to do this.  We don't consider this a bug to get fixed.  This would also be a very breaking change since tons of tooling expects omnibus chef installs into /opt/chef.  You're free to modify `Chef::Config[:file_cache_path]` if you like though.

**Comment by pixdrift** [comment]
The suggestion isn't to change the `/opt/chef` location, just to move the creation of the `chef` directory that is created directly at the `var` level, ie. changing the default location for `Chef::Config[:file_cache_path]` to `/var/cache/chef` or `/var/opt/chef`.
