### ISSUE TITLE
chef/provider/apt_repository.rb is creating temporary files as root in the running user home directory

### ISSUE THREAD

**Issue by omry** [chef/chef#8007]
## Description
1. lib/chef/provider/apt_repository.rb is using gpg to verify keys when installing a new repo
2. gpg by default is creating temporary file in the user home directory (if you use sudo chef-client, chef will create files in your home directory as root).
3. for users with nfs mounted home directory with root squash (very common setup), gpg will fail to create the temp file and the chef run will fail.

A proposed fix is to change 
`verify "gpg %{path}"`
to
`verify "gpg --homedir /tmp/ %{path}"`

in chef/provider/apt_repository.rb

Output proving it works:
```
omry@robodev001:~/opsfiles/chef/cookbooks/ros (master)$ sudo gpg  /var/chef/cache/https___raw_githubusercontent_com_ros_rosdistro_master_ros_key
gpg: failed to create temporary file `/nfs/home/omry/.gnupg/.#lk0x783310.robodev001.39807': Permission denied
gpg: keyblock resource `/nfs/home/omry/.gnupg/secring.gpg': general error
gpg: failed to create temporary file `/nfs/home/omry/.gnupg/.#lk0x783820.robodev001.39807': Permission denied
gpg: keyblock resource `/nfs/home/omry/.gnupg/pubring.gpg': general error
pub  1024D/B01FA116 2009-12-24 ROS Builder <rosbuild@ros.org>
sub  2048g/8F3611A0 2009-12-24
2 omry@robodev001:~/opsfiles/chef/cookbooks/ros (master)$ echo $?
2
omry@robodev001:~/opsfiles/chef/cookbooks/ros (master)$ sudo gpg --homedir /tmp/  /var/chef/cache/https___raw_githubusercontent_com_ros_rosdistro_master_ros_key
gpg: WARNING: unsafe permissions on homedir `/tmp/'
pub  1024D/B01FA116 2009-12-24 ROS Builder <rosbuild@ros.org>
sub  2048g/8F3611A0 2009-12-24
omry@robodev001:~/opsfiles/chef/cookbooks/ros (master)$ echo $?
0
```
## Chef Version
$ chef -v
Chef Development Kit Version: 3.5.13
chef-client version: 14.7.17
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.6
kitchen version: 1.23.2
inspec version: 3.0.52

## Platform Version
Ubuntu 16.04

## Replication Case
Create an apt repository with a key from a url:

      apt_repository("ros") do
        action [:add]
        default_guard_interpreter :default
        declared_type :apt_repository
        cookbook_name "ros"
        uri "http://packages.ros.org/ros/ubuntu"
        distribution "xenial"
        components ["main"]
        key ["https://raw.githubusercontent.com/ros/rosdistro/master/ros.key"]
        repo_name "ros"
      end

## Client Output
http://paste.ubuntu.com/p/HDcN3gFGcZ/

## Stacktrace
http://paste.ubuntu.com/p/DPqwRNQ8gW/

**Comment by tas50** [comment]
Adding this to sustaining backlog. We can probably just update the resource to do this work out of the chef cache directory, which will avoid permissions issues here.

**Comment by vijaymmali1990** [comment]
@omry Could you please tell me how you reproduced the issue? I mean are you getting this issue while running `knife bootstrap` command with the runlist as this recipe? Actually I am not able to reproduce the exact issue?

**Comment by omry** [comment]
@vijaymmali1990, I reproduced by running chef client.
Since my setup is with shared home directory with root squash, it means root can't write to my home directory so sudo chef-client fails for me.
however, if I sudo into root first, and then run chef-client it works.

You can demonstrate the problem by doing:
```wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
gpg ros.key
```
And notice that gpg is creating files in your home directory under ~/.gnupg/
(Rename that directory before running gpgp ros.key if it exists, and rename it back when you are done testing).

**Comment by vijaymmali1990** [comment]
@omry I tried to make a new setup with shared home directory with root squash, but sudo chef-client works for me in this case as well and when I run chef-client it throws me Privileges issue as it is unable to read /etc/chef/client.pem without root privileges.
Output:
chef-client
```
manik-client@manik-client:/nfs/home$ chef-client
Starting Chef Client, version 14.8.12
[2019-01-09T11:37:48+00:00] WARN: Failed to read the private key /etc/chef/client.pem: #<Errno::EACCES: Permission denied @ rb_sysopen - /etc/chef/client.pem>

================================================================================
Chef encountered an error attempting to create the client "manik-client"
================================================================================

Private Key Not Found:
----------------------
Your private key could not be loaded. If the key file exists, ensure that it is
readable by chef-client.

Relevant Config Settings:
-------------------------
validation_key "/etc/chef/validation.pem"

System Info:
------------
chef_version=14.8.12
ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
program_name=/usr/bin/chef-client
executable=/opt/chef/bin/chef-client


Running handlers:
[2019-01-09T11:37:48+00:00] ERROR: Running exception handlers
Running handlers complete
[2019-01-09T11:37:48+00:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 01 seconds
[2019-01-09T11:37:48+00:00] FATAL: Stacktrace dumped to /home/manik-client/.chef/cache/chef-stacktrace.out
[2019-01-09T11:37:48+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-01-09T11:37:48+00:00] FATAL: Chef::Exceptions::PrivateKeyMissing: I cannot read /etc/chef/client.pem, which you told me to use to sign requests!
```

sudo chef-client
```
manik-client@manik-client:/nfs/home$ sudo chef-client
Starting Chef Client, version 14.8.12
resolving cookbooks for run list: ["apt_repoo"]
Synchronizing Cookbooks:
  - apt_repoo (0.1.0)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 1 resources
Recipe: apt_repoo::default
  * apt_repository[ros] action add
    * remote_file[/var/chef/cache/https___raw_githubusercontent_com_ros_rosdistro_master_ros_key] action create
      - create new file /var/chef/cache/https___raw_githubusercontent_com_ros_rosdistro_master_ros_key
      - update content in file /var/chef/cache/https___raw_githubusercontent_com_ros_rosdistro_master_ros_key from none to c20cdc
      (new content is binary, diff output suppressed)
      - change mode from '' to '0644'
    * execute[apt-key add /var/chef/cache/https___raw_githubusercontent_com_ros_rosdistro_master_ros_key] action run
      - execute ["apt-key", "add", "/var/chef/cache/https___raw_githubusercontent_com_ros_rosdistro_master_ros_key"]
    * execute[apt-cache gencaches] action run
      - execute ["apt-cache", "gencaches"]
    * execute[apt-cache gencaches] action nothing (skipped due to action :nothing)
    * apt_update[ros] action nothing (skipped due to action :nothing)
    * file[/etc/apt/sources.list.d/ros.list] action create
      - create new file /etc/apt/sources.list.d/ros.list
      - update content in file /etc/apt/sources.list.d/ros.list from none to 5d3c2f
      --- /etc/apt/sources.list.d/ros.list	2019-01-09 10:03:39.799256324 +0000
      +++ /etc/apt/sources.list.d/.chef-ros20190109-23279-1f8t78w.list	2019-01-09 10:03:39.799256324 +0000
      @@ -1 +1,2 @@
      +deb      "http://packages.ros.org/ros/ubuntu" xenial main
      - change mode from '' to '0644'
      - change owner from '' to 'root'
      - change group from '' to 'root'
    * execute[apt-cache gencaches] action run
      - execute ["apt-cache", "gencaches"]
    * apt_update[ros] action update
      - force update new lists of packages
      * directory[/var/lib/apt/periodic] action create (up to date)
      * directory[/etc/apt/apt.conf.d] action create (up to date)
      * file[/etc/apt/apt.conf.d/15update-stamp] action create_if_missing (up to date)
      * execute[apt-get -q update] action run
        - execute ["apt-get", "-q", "update"]
    
  

Running handlers:
Running handlers complete
Chef Client finished, 8/13 resources updated in 12 seconds
manik-client@manik-client:/nfs/home$
```

**Comment by omry** [comment]
Could be unrelated to root squash:

```
omry@robodev001:~$ sudo su
root@robodev001:/nfs/home/omry# touch a
touch: cannot touch 'a': Permission denied
root@robodev001:/nfs/home/omry# mount | grep home
100.96.135.8:/mnt/storage/home on /nfs/home type nfs (rw,relatime,vers=3,rsize=131072,wsize=131072,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=100.96.135.8,mountvers=3,mountport=714,mountproto=udp,local_lock=none,addr=100.96.135.8)
```
I am not sure why root squash is not working for you and in fact why I don't have write access with root even when root squash is not enabled.

in any case, does your gpg create files in the user home directory? (mine does, version 1.4.20 on Ubuntu 16.04).
even if you can't reproduce the full problem, do you agree that a chef-client run should not be writing things to the home directory of the user running it?

**Comment by omry** [comment]
My root user not being able to write to the mount point has something to do with how freenas maps root user by default to another user.

Still, the issue of gpg leaving files in the home directory should be addressed:
for example - if you just ran sudo chef-client it may leave files owned by root in your home directory.

**Comment by vijaymmali1990** [comment]
These are the same outputs I am getting on my setup 
```
manik@manikclient:/nfs/home$ sudo su
root@manikclient:/nfs/home# touch a
touch: cannot touch 'a': Permission denied
root@manikclient:/nfs/home# mount | grep home
10.1.2.4:/home on /nfs/home type nfs4 (rw,noatime,vers=4.0,rsize=524288,wsize=524288,namlen=255,soft,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.1.2.5,local_lock=none,addr=10.1.2.4)
```

And for gpg command, yes I am able to create files as well
```
manik@manikserver:~$ gpg  /var/chef/cache/https___raw_githubusercontent_com_ros_rosdistro_master_ros_key
gpg: directory `/home/manik/.gnupg' created
gpg: new configuration file `/home/manik/.gnupg/gpg.conf' created
gpg: WARNING: options in `/home/manik/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/home/manik/.gnupg/secring.gpg' created
gpg: keyring `/home/manik/.gnupg/pubring.gpg' created
pub  1024D/B01FA116 2009-12-24 ROS Builder <rosbuild@ros.org>
sub  2048g/8F3611A0 2009-12-24
```

**Comment by vijaymmali1990** [comment]
And also can you successfully run 'chef-client' without sudo and without any recipe on your machine?

**Comment by omry** [comment]
chef-client fails for me if not running as root or with sudo, what do you expect it to do?

if you run gpg with sudo you should see the problem:
```
omry@robodev001:~/tmp$ wget -q https://raw.githubusercontent.com/ros/rosdistro/master/ros.key
omry@robodev001:~/tmp$ sudo gpg ros.key
[sudo] password for omry:
gpg: failed to create temporary file `/nfs/home/omry/.gnupg/.#lk0x9a0310.robodev001.robots.thefacebook.com.29971': Permission denied
gpg: keyblock resource `/nfs/home/omry/.gnupg/secring.gpg': general error
gpg: failed to create temporary file `/nfs/home/omry/.gnupg/.#lk0x9a0820.robodev001.robots.thefacebook.com.29971': Permission denied
gpg: keyblock resource `/nfs/home/omry/.gnupg/pubring.gpg': general error
pub  1024D/B01FA116 2009-12-24 ROS Builder <rosbuild@ros.org>
sub  2048g/8F3611A0 2009-12-24
```

**Comment by omry** [comment]
I feel like I am not being clear, somehow what I am saying is not understood.
Let me state the problem again, please read this carefully:

While running chef client with sudo, it calls gpg which in turns attempt to create files in the home directory of the user running sudo.
Chef client should not be doing it, it's wrong on many levels.
in my case, this also fails due to the setup of my systems, however - even for users with setup where this works it's still an incorrect thing to do:
if you sudo chef-client and it calls gpg to validate a certificate, gpg will create files in your home directory that are owned by root. this is just user hostile and makes no sense.
this will get in your way if you ever attempt to run gpg late without sudo (as you normally should).

My report contains a suggestion for a simple fix to this problem.
it took me several hours of looking at the chef code to identify the root cause of the problem.
please assume I know how to run chef.

**Comment by Vasu1105** [comment]
@omry Thank you for the details. And sorry if I sounded something different. We will check the things around gpg key.

**Comment by vijaymmali1990** [comment]
@omry yes when I run gpg with sudo I could see the problem:
```
manik@manikclient:/nfs/home/manik/tmp$ sudo gpg ros.key 
gpg: failed to create temporary file `/nfs/home/manik//.gnupg/.#lk0x112b310.manikclient.2284': Permission denied
gpg: keyblock resource `/nfs/home/manik//.gnupg/secring.gpg': general error
gpg: failed to create temporary file `/nfs/home/manik//.gnupg/.#lk0x112b350.manikclient.2284': Permission denied
gpg: keyblock resource `/nfs/home/manik//.gnupg/pubring.gpg': general error
pub  1024D/B01FA116 2009-12-24 ROS Builder <rosbuild@ros.org>
sub  2048g/8F3611A0 2009-12-24
```
and thank you for the detailed information as I am able to reproduce the issue now. Will soon give the fix after proper testing. :)

**Comment by omry** [comment]
great, thanks!
I think @tas50 suggested to create the temp files in a directory other than /tmp but I am fine with either solution.

**Comment by vijaymmali1990** [comment]
Ok I have added a temporary directory which is created on every chef client run and it works fine.

**Comment by omry** [comment]
lgtm, thanks for the fix.
