### ISSUE TITLE
windows 2016 detected as Windows 2008r2

### ISSUE THREAD

**Issue by abhimanyusingh0** [chef/chef#8051]
## Description

 On AWS cloud EC2 instance Windows server 2016 is detected as Windows 2008r2, and while bootstrapping it always download the old version 13.x of the chef-client not the latest which is 14.x.
## Chef Version

14.7.17
## Platform Version

Red Hat Enterprise Linux Server release 7.6 (Maipo)
## Replication Case

try to bootstrap windows server 2016 on AWS EC2 and the Chef server is running on RHEL.
## Client Output

```
 Detected Windows Version 10.0 Build 14393
 Warning: Unknown version of Windows, assuming default of Windows 2008r2
 
 C:\Users\Administrator>goto architecture_select 
 
 C:\Users\Administrator>IF "AMD64" == "x86" IF not defined PROCESSOR_ARCHITEW6432 
 
 C:\Users\Administrator>goto install 
 Checking for existing downloaded package at "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
 No existing downloaded packages to delete.
 Attempting to download client package using PowerShell if available...
 powershell.exe -ExecutionPolicy Unrestricted -InputFormat None -NoProfile -NonInteractive -File  C:\chef\wget.ps1 "https://www.chef.io/chef/download?p=windows&pv=2008r2&m=x86_64&DownloadContext=PowerShell&v=13" "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
 Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-28496-1544770336.bat" chunk 7 
 Rendering "C:\Users\ADMINI~1\AppData\Local\Temp\bootstrap-28496-1544770336.bat" chunk 8 
 Download via PowerShell succeeded.
 Installing downloaded client package...
[chef_version](https://user-images.githubusercontent.com/22068654/49995350-e4ef9180-ffb1-11e8-9f73-0320bc492690.PNG)

```

**Comment by stuartpreston** [comment]
Please can you provide more detail here on the bootstrap command that was issued at the command line via knife? Thanks.

**Comment by abhimanyusingh0** [comment]
Update:- problem seems to be in the image as it was customised image. Fixed after some OS update. Thank you.
Can we close the ticket?

**Comment by abhimanyusingh0** [comment]
Update:- problem seems to be in the image as it was customised image. Fixed after some OS update. Thank you.
Can we close the ticket?
