### ISSUE TITLE
windows_ad_join resource prints password even if sensitive is working 

### ISSUE THREAD

**Issue by yamamoto52** [chef/chef#8053]
## Description
windows_ad_join resource prints password even if sensitive is working when resource fails.

## Platform Version
windows 2012r2

## Replication Case
make resource to fail

## Client Output
* windows_ad_join[domainname] action join[2018-12-14T11:07:40+01:00] INFO: Processing windows_ad_join[domainname] action join (cmake-domain::default line 29)
       
       
           ================================================================================
           Error executing action `join` on resource 'windows_ad_join[domainname]'
           ================================================================================
       
           RuntimeError
           ------------
           Failed to join the domain domainname: Add-Computer : Computer 'WIN-TdssfETE' failed to join domain 'domainname' 
       
           from its current workgroup 'WORKGROUP' with following error message: The 
       
           account already exists.
       
           At line:1 char:156
       
           + $pswd = ConvertTo-SecureString 'password' -AsPlainText 
       
           -Force;$credential ...
       
           + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       
           ~~~
       
        + CategoryInfo          : OperationStopped: (WIN-TdssfETE:String) [Add- 
       
       Computer], InvalidOperationException
       
        + FullyQualifiedErrorId : FailToJoinDomainFromWorkgroup,Microsoft.PowerShe 
       
       ll.Commands.AddComputerCommand
       
       
       
           }
       
           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/cmake_domain/recipes/default.rb
       
            29: windows_ad_join 'domainname' do
            30:   domain_name domain
            31:   domain_user username
            32:   domain_password password
            33:   if node['ra']['testing'] == 'true'
            34:     rand = SecureRandom.alphanumeric(8)
            35:     new_hostname "#{cookbook_name.gsub!('_','-').slice(0..6)}#{rand}"
            36:   elsif !new_hotname.nil?
            37:     new_hostname new_hotname
            38:   end
            39:   reboot :immediate
            40:   ou_path OU
            41:   action :join
            42:   sensitive true
            43: end
       
           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/cmake/recipes/default.rb:29:in `from_file'
       
           windows_ad_join("domainname") do
             action [:join]
             default_guard_interpreter :default
             declared_type :windows_ad_join
             cookbook_name "ra-int-domain"
             recipe_name "default"
             domain_name "mydomain.com"
             domain_user "user"
             domain_password "password"
             new_hostname "cmake-WLX1Q0Xl"
             reboot :immediate
             ou_path "OU=OUName"
           end
       
           System Info:
           ------------
           chef_version=14.7.17
           platform=windows
           platform_version=6.3.9600
           ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
           program_name=C:/opscode/chef/bin/chef-client
           executable=C:/opscode/chef/bin/chef-client

**Comment by tas50** [comment]
This has been merged to master and backported to Chef 14. Thanks @Happycoil
