### ISSUE TITLE
forbidden error from knife supermarket unshare is now misleading

### ISSUE THREAD

**Issue by robbkidd** [chef/chef#8056]
## Description

`knife supermarket unshare` currently treats all [403 Forbidden responses](https://github.com/chef/chef/blob/8d1b7b12a4b4f6ac2150f0757cb75dc53a3750cc/lib/chef/knife/supermarket_unshare.rb#L49-L55) the same and presents a single error:  `Forbidden: You must be the maintainer of #{@cookbook_name} to unshare it.`

With [artifact yanking now able to be restricted in a Supermarket](https://github.com/chef/supermarket/pull/1789) to admins only, this error message is misleading to cookbook owners who attempt to remove a cookbook or cookbook version. The Supermarket v3.1.96+ will provide an error message with the forbidden response that will be more helpful to display.

## Chef Version

All of 'em

## Platform Version

All of these, too.

## Replication Case & Client Output

With a Supermarket configured to prevent owners from removing artifacts (the public Supermarket is now configured this way, or use a test Supermarket install):

```
> knife supermarket share blargle -m https://superkitchen -o .
Generating metadata for blargle from /var/folders/blah/blah/blargle/metadata.rb
Making tarball blargle.tgz
Upload complete
```

🎉 I'm the maintainer of a shiny,new cookbook!

```
> knife supermarket unshare blargle -m https://superkitchen
Do you really want to unshare all versions of the cookbook blargle? (Y/N) y
ERROR: Forbidden: You must be the maintainer of blargle to unshare it.
```

😕 Wait ... I _am_ the maintainer!

**Comment by lamont-granquist** [comment]
yep, that's now wrong.

**Comment by vagifzeynalov** [comment]
I have the same problem! Any solutions?

**Comment by robbkidd** [comment]
@vagifzeynalov Can you explain more about your particular problem? The error condition as described in this issue is a Supermarket instance configured to _disallow_ artifact removal results in an error about needing to be a maintainer instead of an error about artifact removal being disallowed. The fix for this issue is to correct the error message; users—even cookbook owners—will not be able to remove the artifact.

**Comment by vagifzeynalov** [comment]
@robbkidd it seems like I didn't read the original description of this issue carefully. I was thinking this conversation about the problem I couldn't remove my cookbook from Supermarket. But as it turned out, it was expected behavior, and only the message itself was incorrect...
Sorry, I confused you with my comment :)

**Comment by vsingh-msys** [comment]
I have come across the same scenario, where I have created 2 cookbooks for testing 
- https://supermarket.chef.io/cookbooks/vivek-test
- https://supermarket.chef.io/cookbooks/vivek-test2

And try to unshare it but raises `ERROR: Forbidden: You must be the maintainer...`

We can unshare the cookbook maintainer wants only if:

1. No followers & no downloads.

2. If it has only limited downloads less suppose less than 5 or 10.  Raise the waning to ask for the confirmation to unshare.

3. If the cookbook downloads more than 10 then raise the warning and asks the user to send the email to `cookbooks@chef.io` why he/she want to unshare it.

4. If the cookbook is followed by some users then raise the warning and asks the user to send the email to `cookbooks@chef.io` why he/she want to unshare it.

Any suggestion/query would be helpful?

**Comment by rshad** [comment]
Hi all!

I think this task should have a higher priority.

Kr,

Rshad

**Comment by tas50** [comment]
We should update this message to say you must be the maintainer OR you are on a Supermarket that has disabled unsharing cookbooks such as the public Supermarket.

**Comment by vkarve-chef** [comment]
@robbkidd this issue is addressed with latest Workstation release.
