### ISSUE TITLE
Windows_Service run_as_user does not work correctly

### ISSUE THREAD

**Issue by gdoddsy** [chef/chef#8079]
## Description
When trying to install a service in Windows 2016 using windows_service, I am not able to specify a domain username and password. Ideally, I'd like to be able to specified a [group managed service account](https://blogs.technet.microsoft.com/askpfeplat/2012/12/16/windows-server-2012-group-managed-service-accounts/), but I can't even add a regular domain account.

We need the service to run as a domain account so it can connect to other services on the network.

I think this is similar to issue 3521, which is marked as closed.

## Chef Version
14.7.17

## Platform Version
Windows Server 2016

## Replication Case
```
windows_service 'install My Service' do
	action :create
	display_name "My Service"
	service_name "myservice"
	binary_path_name "c:\\Program Files\\myservice\\myservice.exe"
	startup_type :automatic
	delayed_start true
	run_as_user "domain\\MyUser"
	run_as_password "mypassword"
	description "Some description of my service."
end

```

## Client Output
When it hits the line to install using a regular windows domain user:

```
FATAL: SystemCallError: windows_service[install My Service] (MyService::InstallMyService line 35) had an error: SystemCallError: The account name is invalid or does not exist, or the password is invalid for the account name specified. - CreateService: The account name is invalid or does not exist, or the password is invalid for the account name specified.
```

**Comment by gdoddsy** [comment]
Turns out we can register with a managed service account (without a password), but not with a normal windows account

**Comment by tas50** [comment]
Closing this out as there's a workaround.
