### ISSUE TITLE
FATAL: LoadError: cannot load such file -- chef/mixin/language

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [chef/chef#8084]
Hello.

I have a vagrant application that has `chef` inside. During the execution of command `vagrgant up` I received this error:

    ==> default: Installing Cookbook Gems:
    ==> default: Compiling Cookbooks...
    ==> default: 
        ==> default: Recipe Compile Error in 
    /var/chef/cache/cookbooks/windows/libraries/windows_package.rb
    ==> default: 
    ==> default: LoadError
    ==> default: ---------
    ==> default: cannot load such file -- chef/mixin/language
    ==> default: Cookbook Trace:
    ==> default: ---------------
    ==> default:   /var/chef/cache/cookbooks/windows/libraries/windows_package.rb:7:in `<top (required)>'
    ==> default: Relevant File Content:
    ==> default: ----------------------
    ==> default: /var/chef/cache/cookbooks/windows/libraries/windows_package.rb:
    ==> default:   1:  require 'chef/resource/lwrp_base'
    ==> default:   2:  require 'chef/provider/lwrp_base'
    ==> default:   3:
    ==> default:   4:  require 'win32/registry' if RUBY_PLATFORM =~ /mswin|mingw32|windows/
    ==> default:   5:
    ==> default:   6:  require 'chef/mixin/shell_out'
    ==> default:   7>> require 'chef/mixin/language'
    ==> default:   8:  class Chef
    ==> default:   9:    class Provider
    ==> default:  10:      class WindowsCookbookPackage < Chef::Provider::LWRPBase
    ==> default:  11:        include Chef::Mixin::ShellOut
    ==> default:  12:        include Windows::Helper
    ==> default:  13:
    ==> default:  14:        # the logic in all action methods mirror that of
    ==> default:  15:        # the Chef::Provider::Package which will make
    ==> default:  16:        # refactoring into core chef easy
    ==> default: System Info:
    ==> default: ------------
    ==> default: chef_version=14.8.12
    ==> default: platform=redhat
    ==> default: platform_version=6.5
    ==> default: ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
    ==> default: program_name=/usr/bin/chef-client
    ==> default: executable=/opt/chef/bin/chef-client
    ==> default: Running handlers:
    ==> default: [2018-12-29T07:42:51+00:00] ERROR: Running exception handlers
    ==> default: Running handlers complete
    ==> default: [2018-12-29T07:42:51+00:00] ERROR: Exception handlers complete
    ==> default: Chef Client failed. 0 resources updated in 15 seconds
    ==> default: [2018-12-29T07:42:51+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
    ==> default: [2018-12-29T07:42:51+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
    ==> default: [2018-12-29T07:42:51+00:00] FATAL: LoadError: cannot load such file -- chef/mixin/language
    Chef never successfully completed! Any errors should be visible in the
    output above. Please fix your recipes so that they properly complete.

**Comment by manisha1331** [comment]
From the logs it is visible that you are using chef-client 14.8 and chef/mixin/language is deprecated for chef 14+ version .So I would suggest you to upgrade the windows cookbooks to latest version and it should work.

**Comment by tas50** [comment]
Closing this out since as @manisha1331 mentioned you need to upgrade to a more recent windows cookbook to resolve this issue.

**Comment by SuperMasterBlasterLaser** [comment]
@manisha1331 How is it possible to upgrade cookbook?

**Comment by manisha1331** [comment]
@SuperMasterBlasterLaser You need to go to the chef supermarket and download the compatible version.
Here is the [url](https://supermarket.chef.io/)
