### ISSUE TITLE
Group resource: "append true" doesn't work right for adding users to multiple groups on Solaris.

### ISSUE THREAD

**Issue by jjustice6** [chef/chef#8161]
## Description
When using :modify on a group in `solaris2` (5.11) environments, `append true` doesn't work correctly when adding a user to *additional* groups. See `-G` flag comments on https://docs.oracle.com/cd/E26502_01/html/E29031/usermod-1m.html , note that the code for the usermod resource doesn't put `+` or `-` before the group name.

We're working on a fix for this.

## Chef Version
Chef 14.7.17, though the bug exists through many versions.

## Platform Version
Solaris 5.11. 

## Replication Case

```
group1_name = 'tstgrp1'
group1_id = 6789
group2_name = 'tstgrp2'
group2_id = 9876
group group1_name do
  action :create
  gid group1_id
end
group group2_name do
  action :create
  gid group2_id
end

group 'primary' do
  action :create
end

firstbatch = %w(user1 user2)
secondbatch = %w(user3 user4)
%w(user1 user2 user3 user4).each do |username|
  user username do
    group 'primary'
    manage_home true
  end
end

group 'add firstbatch to group1' do
  group_name group1_name
  action :modify
  members firstbatch
  append true
end

group 'add secondbatch to group2' do
  group_name group2_name
  action :modify
  members secondbatch
  append true
end

# Now, add them to the other group. The end result SHOULD be that all 4 users are in both groups.
group 'add firstbatch to group2' do
  group_name group2_name
  action :modify
  members firstbatch
  append true
end

group 'add secondbatch to group1' do
  group_name group1_name
  action :modify
  members secondbatch
  append true
end

```

## Client Output
Appears normal, until you actually look at the groups.

EXPECTED: All 4 users are in both groups.
ACTUAL:
```
# getent group tstgrp1
tstgrp1::6789:user3,user4
# getent group tstgrp2
tstgrp2::9876:user1,user2
```

Make sure that you think of it as "the user should be in X groups", not "the group should have X users" - if you only have one group and attempt to add users in successive `:modify` actions, that won't cause the problem. The problem here is not that "add secondbatch to group1" wiped out the firstbatch users from group 1 - it's that "add secondbatch to group1" _took them out of group 2_.

## Stacktrace
N/A

**Comment by tas50** [comment]
Fix merged to master and will be backported for the next Chef 14 release. Thanks @jjustice6
