### ISSUE TITLE
knife ssh error -- RbNaCl::LengthError: key was 257 bytes (Expected 32)

### ISSUE THREAD

**Issue by t-readyroc** [chef/chef#8171]
## Description
knife ssh error involving net-ssh that results in a rbnacl error complaining about key length. Have attempted to install different versions of both net-ssh & rbnacl to no avail. Interestingly, I've tested net-ssh on its own using the following code, which successfully created the connection:

```
require 'net/ssh'
require 'etc'

user = Etc.getlogin
host = 'host.com'
command = 'ls -lh'

keys = [ "~/.ssh/id_rsa" ]
  Net::SSH.start(host,user,:keys => keys,:use_agent => false,:verbose => :debug) do |session|
  res= session.exec!(command)
  print(res)
end
```

Related issues in the net-ssh project: 

- [#518](https://github.com/net-ssh/net-ssh/issues/518)
-  [#634](https://github.com/net-ssh/net-ssh/issues/634)

Additionally, I have several colleagues running the same environment who are _not_ experiencing this issue. Ruby version 2.3.5p376.

## Chef Version

```
Chef Development Kit Version: 1.6.11
chef-client version: 12.21.26
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: 5.6.4
kitchen version: 1.16.0
inspec version: 1.25.1
```
Gems:
```
net-ssh (5.1.0, 4.1.0)
rbnacl (4.0.2)
rbnacl-libsodium (1.0.16)
```

## Platform Version

```
      System Version: macOS 10.14.2 (18C54)
      Kernel Version: Darwin 18.2.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
```

## Replication Case

`knife ssh -a fqdn 'name:somename*' "find /path -type f -name '*somestring*' | grep anotherstring"`

## Client Output

`WARNING: Failed to connect to host.com -- RbNaCl::LengthError: key was 257 bytes (Expected 32)`

## Stack Trace

Gist [here](https://gist.github.com/t-readyroc/8373e7cde47a9ee8a8689b4d38b24972).

**Comment by lamont-granquist** [comment]
```
Chef Development Kit Version: 1.6.11
chef-client version: 12.21.26
```

Chef-12 and Chef-DK-1 is no longer supported.  You need to replicate this on Chef-14 and/or ChefDK 3.x.

**Comment by lamont-granquist** [comment]
see https://www.chef.io/eol-chef12-and-chefdk1/

**Comment by t-readyroc** [comment]
Reverting to the previous version of ssh keys did the trick. Needed to generate my key pair with the  -m PEM parameter. Default on Mojave is now to generate RFC4716 key pairs, which won't work with this environment.

**Comment by cdbattags** [comment]
I replicated this on chef-client version: 15.0.188 e26d943 just FYI. Please reopen.

Seems to be an issue in net-ssh. When is eta to bump?

**Comment by tas50** [comment]
We can't bump until other net-* gems are released as we have an unsolvable dependency at the moment.

**Comment by cdbattags** [comment]
@tas50 I just forked latest chef/chef and bumped net-ssh and things seem to be working great

What specifically would break that use the other net-* gems?

**Comment by tas50** [comment]
Chef gets bundled in Chef-DK / Chef Workstation and we need the dependencies there to be the same. In Chef-DK there is a dependency on net-scp that comes in via Test Kitchen. The current non-RC release of net-scp depends on net-ssh < 5.0. We can't have chef in DK and chef inside the client package behaving differently so at the moment we cannot bump the dependency in the actual chef gem. We've reached out the author of net-scp and an RC for a new release of net-scp has been released, but we're waiting on the final release.

**Comment by cdbattags** [comment]
@tas50 fantastic and thanks for the follow-up! I'm super glad it was so easy on my end anyways! Keep up the awesome work!

**Comment by lamont-granquist** [comment]
yeah it works on your end because you wind up compiling and linking against your distro's libsodium.

not all distros we ship against ship with libsodium, or with consistent versions of libsodium, so we have to package it and ship that in omnibus.   and that is where it all starts to fall apart for us on distros like mac and windows.
