### ISSUE TITLE
windows_task doesn't clear arguments when updating a task

### ISSUE THREAD

**Issue by nmcspadden** [chef/chef#8197]
## Description
When creating a `windows_task` with a ` command` property that has spaces, the first space-delimited element is set as the "Programs/scripts" and everything else after that becomes "arguments". You can observe this in the Task Scheduler:
```
command 'test.exe -arg stuff -arg2 stuff2'
```
Becomes:
Programs/script: "test.exe"
Arguments: "-arg stuff -arg2 stuff2"

When you update an existing task that has both Programs/Script and Arguments with a new `command` property that contains no space-delimited commands, the "Arguments" are never cleared and will persist.

## Chef Version
This exists in Chef 14 (up to Chef 14.10.9) and Chef 15.0.9 (current release).

## Platform Version
Windows 10 x64

## Replication Case
```
windows_task 'stuff\my_task' do
  command 'test.exe -arg1 stuff -arg2 stuff2'
  frequency :none
  action :create
end
```

Observe it create the task in Task Scheduler.
![task exe](https://user-images.githubusercontent.com/1202655/52153520-37067800-262f-11e9-8b65-819e487bc62c.png)

Now, change it and run Chef again:
```
windows_task 'stuff\my_task' do
  command 'somethingdifferent.exe'
  frequency :none
  action :create
end
```

In the Task Scheduler, you'll see:
Programs/Script: "somethingdifferent.exe"
Arguments: "-arg1 stuff -arg2 stuff2"

![test2 exe](https://user-images.githubusercontent.com/1202655/52153524-3bcb2c00-262f-11e9-81a8-de8f3414d6ea.png)

## Client Output
First output:
```
[2019-02-01T14:35:15-08:00] INFO: Processing windows_task[fbit\example] action create ((irb#1) line 5)
 => true
```

Second output:
```
[2019-02-01T14:37:54-08:00] INFO: Processing windows_task[fbit\example] action create ((irb#1) line 5)
[2019-02-01T14:37:54-08:00] INFO: Processing windows_task[fbit\example] action create ((irb#1) line 11)
 => true
```
## Stacktrace
No stacktrace.

**Comment by tas50** [comment]
This is fixed on master and backported to Chef 14 for release in the next chef release.
