### ISSUE TITLE
cron resource get confused by environement/property mismatch

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#8241]
## Description

If you use a `environment` for an entry that can also be specified as a  `property`, the `cron` resource will update every run.

## Chef Version
13.9, but based on code, I suspect all versions

## Platform Version
RHEL7

## Replication Case

```
cron 'test' do
  command '/bin/true'
  environment({'MAILTO' => 'root'})
end
```

**Comment by Vasu1105** [comment]
Fixed in #8455
