### ISSUE TITLE
template/file 'verify' provides no way to see materialized content

### ISSUE THREAD

**Issue by jaymzh** [chef/chef#8249]
## Description

If I use `verify` on a template, and the verification fails, let's say:

```
template '/etc/nginx.conf' do
  ...
  verify 'nginx -c %{path} -t'
end
```

And the verification fails, Chef will bail out and tell me the verification fails, but it does not leave the materialized template anywhere for me to see what was wrong. The only solution is to then change that code to something like:

```
template '/tmp/nginx.conf' do
  ...
end

template '/etc/nginx.conf' do
  ...
  verify 'nginx -c %{path} -t'
end
```

So that I can inspect /tmp/nginx.conf and see what went wrong.

## Chef Version
13.10, but I think this is still the case in 14/15

## Platform Version
RHEL7

**Comment by jaymzh** [comment]
It seems to me like we can do 1 of 2 things:

1. put this in a predictable place (maybe /var/chef/cache/failed_verifies/path/file) which always overwrites it self so we don't litter these forever
2. Treat them just like backups, with a timestamp (/var/chef/cache/failed_verifies/path/file-timestamp) and keep a certain number.

**Comment by lamont-granquist** [comment]
closing as a dup of #4793
