### ISSUE TITLE
msu_package doesn't work under plain package resource

### ISSUE THREAD

**Issue by Stromweld** [chef/chef#8277]
## Description
msu_package should be a sub resource of the primary package resource similar to windows_package etc...

## Chef Version
chef-client 14.10.9

## Platform Version
any supported windows version

## Replication Case
create a resource like:
```
package 'kb2999226' do
  source 'https://download.microsoft.com/download/D/1/3/D13E3150-3BB2-4B22-9D8A-47EE2D609FFF/Windows8.1-KB2999226-x64.msu'
end
```

## Client Output
You'll get an error stating it's unable to determine the install type for `.msu` file
if you use msu_package resource it installs correctly.

**Comment by tas50** [comment]
I'm going to close this out since there really isn't a way for us to accomplish this the way the providers work. It would be nice, but it's high effort to get it right.
