### ISSUE TITLE
Windows Audit Policy Resource

### ISSUE THREAD

**Issue by rachelrice** [chef/chef#8299]
### Core Chef Resource Checklist

Before suggesting a resource for inclusion please make sure your suggestion meets these criteria for resources built into Chef:
 - [x] Automates an operating system component that ships by default on systems such as authentication, raid, disk partitions, firewalls, containers, or virtualization systems.
 - [x] Does not attempt automate 3rd party applications such as database, web, or application servers, which are best suited for cookbooks due to their fast moving nature.

### Describe the resource:
CIS and other security standards dictate settings for the different categories of a Windows systems audit policy. There are several categories and subcategories that need to be set to either `Success`, `Failure`, or `Success and Failure`.  A `windows_audit_policy` resource would allow the user to set a category, subcategory, or array of the two then enable the categories `Success` or `Failure`. Here is a reference to the [best practice settings from windows](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/plan/security-best-practices/audit-policy-recommendations). Here is the documentation on the `auditpol` [command](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/auditpol).

### Why should this be included out of the box?:
The standard way to set these settings is through Group Policy but by using Chef a user can take advantage of the `auditpol` command. Currently though this often requires numerous `powershell_script` resource commands making the cookbook difficult to read and understand.

### What operating systems would it run on?
Windows.

### Current cookbook implementation:
https://github.com/chef/cis-windows-ms-2016/blob/master/resources/audit_policy.rb

### Can We Help You Implement This?:
Yes, @rmoles @rachelrice @james-stocks @TheLunaticScripter are all for moving this ourselves and helping better understand the process.

**Comment by tas50** [comment]
Closing since we shipped a resource for this.
