### ISSUE TITLE
Enhance knife supermarket to eliminate the need for Stove

### ISSUE THREAD

**Issue by tas50** [chef/chef#8347]
I propose that we roll some of the core functionality of Stove into knife supermarket itself in order to eliminate the need for the stove command line and to make sure that everyone uploading chef cookbooks has the same experience.

## Motivation

    As a end user,
    I want to cookbooks on the supermarket to contain a consistent set of files,
    so that I don't have to worry about how a cookbook was uploaded.

    As a cookbook author,
    I want to knife to upload only the files necessary for a cookbook,
    so that I can automate cookbook uploads without a full DK install.

    As a new Chef user
    I want to use knife for all interaction with Supermarket,
    so that I don't have to learn another tool to be successful with Chef.

## Specification

- Knife supermarket respects the blacklist in the chefignore file when uploading cookbook to slim down the contents that gets uploaded to Supermarket to just those that are pulled down to a chef-client itself anyways.
- A new flag allows uploading all files for those that want the artifact to match the repository contents

## Downstream Impact

- Eventually stove should go away. In the short term we'll probably want a warning that tells folks to stop using it.

**Comment by damacus** [comment]
Another thing that the might not be obvious is that we'd get to use the knife.rb logic, switching between accounts should be a much more plesent experience

**Comment by damacus** [comment]
I'm pretty sure it's been talked about before, but it would be useful to have an allowed list of files if chefignore wasn't there.

**Comment by tas50** [comment]
Let me update the use case for that. Not needing yet another config file is a solid reason to use this path.

**Comment by lamont-granquist** [comment]
What are the features of stove that are necessary, and presumably this would just be patches to `knife supermarket share`?

I.e. what does the actual design look like here? (and i'd argue that extending the chefignore functionality or having a default chefignore is out of scope of this issue)

**Comment by damacus** [comment]
Yeah, if we want bare stove functionality then it's totally scope creep

**Comment by lamont-granquist** [comment]
Yes, this needs to be minimum viable deprecation of stove.

**Comment by tas50** [comment]
We did this already
