### ISSUE TITLE
Allow use of net-ssh 5.2.0 gem

### ISSUE THREAD

**Issue by roperry** [chef/chef#8382]
## Description
host-key error when using net-ssh-4.2.0

Update the gem specification to use net-ssh-5.2.0.  net-ssh-5.2.0 fixes the following bug:

https://github.com/net-ssh/net-ssh/pull/601

Which occurs when running test kitchen:

 [2019-04-16T11:18:22.977009 #85258] ERROR -- default-Centos7: Message: SSH command failed (host key algorithm mismatch for signature 'ssh-rsa' != 'ssh-rsa-cert-v01@openssh.com')

The latest chef gem requires net-ssh-4.2.0.

## Gem Version
14.12.3

## Platform Version

Mac OSX. 10.14.4

## Replication Case

Using a bastion host and remote host with the following kex and host_key:

* kex: diffie-hellman-group1-sha1
* host_key: ssh-rsa-cert-v01@openssh.com

Attempt to run `kitchen converge`.

This can be fixed by updating the `chef.gemspec` and global specification 
`chef-<new-version>.gemspec` files to allow the most recent version.

**Comment by tas50** [comment]
This is actively being worked here for Chef 15: #8380

**Comment by vnz** [comment]
net-ssh requires the following gems for ed25519 support:
 * rbnacl (>= 3.2, < 5.0)
 * rbnacl-libsodium, if your system doesn't have libsodium installed.
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/478 for more information

You closed issue about net-ssh and rbnacl without actually fixing them.
This is bad work, chef is not reliable anymore.
Lets go ansible.

**Comment by tas50** [comment]
rb-nacl is required for net-ssh 4.x not net-ssh 5.x and rbnacl and other methods of using libsodium for ed25519 support are not compatible with all operating systems supported by Chef. We've removed several blockers to using net-ssh 5.x including getting the upstream to release versions of the other net-* gems we depend on in Chef and DK/Workstation. That has unblocked net-ssh 5.x for Chef 15 and allowed us to add the ed25519 gem to our gemspec as well as train/test-kitchen. As I noted in the comment above it's in the works. Please assume good intentions. There's real people working to support these projects and things are often more complex than they appear from the surface, especially when it comes to large dependency trees.

**Comment by tas50** [comment]
I'm closing this out at this point since we are allowing net-ssh 5 on master https://github.com/chef/chef/blob/master/chef.gemspec#L29 and we're shipping the ed25519 gems as well. They've also been added to Test Kitchen 2.1 and the upcoming train 2.0 release.
