### ISSUE TITLE
`node.name` returns fqdn instead of node_name value from client.rb

### ISSUE THREAD

**Issue by haidangwa** [chef/chef#8385]
## Description
From a recipe, I attempted to use `node.name` to retrieve the name of the node during a chef run. However, this appears to be returning the fqdn value instead of the node_name value that I've configured in my node's client.rb file.

## Chef Version
13.12.14

## Platform Version
RHEL 7.6 in AWS

## Replication Case
With `node_name` in client.rb set as follows: `node_name "bastion-us-west-2-qa-i-02d7ea7dc5a67bddd"`

See the chef-shell output below:
```
-bash-4.2$ chef-shell
loading configuration: none (standalone session)
Session type: standalone
Loading.....done.

This is the chef-shell.
 Chef Version: 13.12.14
 https://www.chef.io/
 https://docs.chef.io/

run `help' for help, `exit' or ^D to quit.

Ohai2u ec2-user@am-uw2-0a9c96d6.iaas.mydomain.com!
chef (13.12.14)> node.name
 => "am-uw2-0a9c96d6.iaas.mydomain.com" 
chef (13.12.14)> node['hostname']
 => "am-uw2-0a9c96d6" 
chef (13.12.14)> Chef::Config.node_name
 => "am-uw2-0a9c96d6.iaas.mydomain.com" 
chef (13.12.14)> Chef::Config['node_name']
 => "am-uw2-0a9c96d6.iaas.mydomain.com" 
chef (13.12.14)> node['fqdn']
 => "am-uw2-0a9c96d6.iaas.mydomain.com" 

```

## Client Output
see the chef-shell output I provided above

I expected `node.name` to return `bastion-us-west-2-qa-i-02d7ea7dc5a67bddd`, which is the value I have configured the chef-client in the node's client.rb file.

**Comment by lamont-granquist** [comment]
` Chef::Config.node_name` is returning "am-uw2-0a9c96d6.iaas.mydomain.com" though which indicates you aren't parsing the config.rb properly.

**Comment by haidangwa** [comment]
@lamont-granquist Thanks for that catch. It absolutely works when I use the right config:
