### ISSUE TITLE
chef 12/13: gem_package: support the --no-document flag needed for Ruby 2.6 / rubygems 3

### ISSUE THREAD

**Issue by poloka** [chef/chef#8416]
### Describe the Enhancement:

Trying to upgrade my services to utilize ruby 2.6, but because `gem_package` constructs the `gem install` command with `--no-rdoc --no-ri`, my installation utilizing chef 12.19.36 fails indicating 
```
STDERR: ERROR:  While executing gem ... (OptionParser::InvalidOption)
  invalid option: --no-rdoc
```

Would like the fix https://github.com/chef/chef/pull/7994 added to chef-14 to be patched to 12 and 13.

### Describe the Need:

This would continue to allow older enterprise solutions to support updates in services to eliminate security vulnerabilities. 

### Current Alternative

There is no alternative other than forcing an upgrade to 14.8.12 or higher.

### Can We Help You Implement This?:

What branch for 12 and 13 is their latest releases that I could submit a PR against?  What is the timeframe for releasing the change once merged to branch?

**Comment by bastien-jove-cbp** [comment]
Chef 12 is no longer supported and 13 will be end of life with the release of 15(which should be soon) so it's unlikely any of them will be patched.

What you can do as an alternative is taking #7994 state of file `lib/chef/provider/package/rubygems.rb` and save it in a cookbook's libraries directory to "monkey patch" the provider if you can't update Chef client right now.

**Comment by lamont-granquist** [comment]
yeah, there are no future chef-13 releases planned.
