### ISSUE TITLE
Dead link in Contributing.md

### ISSUE THREAD

**Issue by elliott-davis** [chef/chef#8421]
The maintainers file no longer resolves in master (linked here: https://github.com/chef/chef/blob/master/CONTRIBUTING.md#code-review-process)

**Comment by vsingh-msys** [comment]
Hey @elliott-davis,

Thanks for informing definitely we need to update the maintainers [link](https://github.com/chef/chef/blob/master/MAINTAINERS.md) mentioned in CONTRIBUTING.md
