### ISSUE TITLE
chocolatey_package fails using extra options

### ISSUE THREAD

**Issue by kenmacleod** [chef/chef#8437]
## Description
#8230 added options parameter while fetching list of available packages.  Some options that are allowed for choco install fail when running choco list.

## Chef Version
Showed up in 14.11.21, our TK dev instances saw this as recently as 2019-04-26.

## Platform Version
Windows, chef-client 14.11.21+

## Replication Case
```
chocolatey_package '<package-name>' do
 options '--install-arguments=NO_START=1'
end
```

## Client Output
From user report, if we need to add more, let us know.
```
No candidate version available for <package-name>
```

## Stacktrace
N/A

**Comment by vsingh-msys** [comment]
Hey @kenmacleod with the provided recipe option
```
chocolatey_package 'git' do
 options '--install-arguments=NO_START=1'
end
```
tested with multiple packages and it works fine.
Could you please provide chef-client run in debug mode?

**Comment by nimDevOps** [comment]
Same with me, starting from Chef-Client 14.11.21 **chocolatey_package** resource stopped working on our internal ProGet package server where our chocolatey packages are stored.  If the package has packageParameters chocolatey_package resource sends them to the source via **choco list** command and resulted response code 2 breaks the build. Without packageParameters  or if I use ChocoGalery source it works fine:

C:\WINDOWS\system32>choco.exe list -r git.install -source <myProGet> --packageParameters="/NoAutoCrlf /GitAndUnixToolsOnPath"
C:\WINDOWS\system32>echo %errorlevel%
2

C:\WINDOWS\system32>choco.exe list -r git.install -source <myProGet>
git.install|2.21.0
C:\WINDOWS\system32>echo %errorlevel%
0
C:\WINDOWS\system32>choco.exe list -r git.install --packageParameters="/NoAutoCrlf /GitAndUnixToolsOnPath"
git.install|2.21.0
git|2.21.0
jivkok.tools|1.1.0.7
SuperCollider|3.9.3.0

C:\WINDOWS\system32>echo %errorlevel%
0

C:\WINDOWS\system32>choco.exe list -r git.install
git.install|2.21.0
git|2.21.0
SuperCollider|3.9.3.0
jivkok.tools|1.1.0.7

C:\WINDOWS\system32>echo %errorlevel%
0

I think the issue here is "unexpected options sent to the source" which will fail choco list command.
For example --packageParameters option by design should be applied only for package itself and should not be sent to the source.

**Comment by nimDevOps** [comment]
Here is output from my cookbook (chocolatey_res_wrapper) execution 

         * log[Applying chocolatey_package Name=(git.install), Version=(2.21.0) Options=(--packageParameters="/NoAutoCrlf /GitAndUnixToolsOnPath") Source=(**myProGet**) Returns=([0]) Action=(install)] action write

         * reboot[Reboot by Chef] action nothing (skipped due to action :nothing)
         * chocolatey_package[git.install] action install

           ================================================================================
           Error executing action `install` on resource 'chocolatey_package[git.install]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '2'
           ---- Begin output of C:\ProgramData\chocolatey/bin/choco.exe list -r git.install -source **myProGet** --packageParameters="/NoAutoCrlf /GitAndUnixToolsOnPath" ----
           STDOUT:
           STDERR:
           ---- End output of C:\ProgramData\chocolatey/bin/choco.exe list -r git.install -source **myProGet** --packageParameters="/NoAutoCrlf /GitAndUnixToolsOnPath" ----
           Ran C:\ProgramData\chocolatey/bin/choco.exe list -r git.install -source **myProGet** --packageParameters="/NoAutoCrlf /GitAndUnixToolsOnPath" returned 2

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey_package_res_wrapper/recipes/default.rb

           169:   chocolatey_package name do
           170:     version params['version'] unless params['version'].nil?
           171:     options params['options'] unless params['options'].nil?
           172:     timeout params['timeout'] unless params['timeout'].nil?
           173:     source source
           174:     returns returns
           175:     action  action
           176:     notifies reboot_action, 'reboot[Reboot by Chef]', :immediately
           177:   end
           178: end

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/chocolatey_package_res_wrapper/recipes/default.rb:169:in `block in from_file'

           chocolatey_package("git.install") do
             package_name ["git.install"]
             action [:install]
             default_guard_interpreter :default
             declared_type :chocolatey_package
             cookbook_name "chocolatey_package_res_wrapper"
             recipe_name "default"
             version ["2.21.0"]
             options "--packageParameters=\"/NoAutoCrlf /GitAndUnixToolsOnPath\""
             source "**myProGet**"
             returns [0]
           end

           System Info:
           ------------
           chef_version=14.11.21
           platform=windows
           platform_version=10.0.14393
           ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]
           program_name=C:/opscode/chef/bin/chef-client
           executable=C:/opscode/chef/bin/chef-client

**Comment by Rage2010** [comment]
I have the same problem when using --params in options.
For example with the following chocolatey resource:
chocolatey_package 'sqlserver2008express' do
  action :upgrade
  source choco_source
  options "--params \"/instanceName:#{name_to_create} /adminAccount:#{admin_user}\""
end

the nuget server receive this request:
"GET /api/v2/Search()?$filter=IsLatestVersion&$skip=0&$top=30&searchTerm='sqlserver2008express%20--params%20%2Finstancename%3Amssqlserver%20%2Fadminaccount%3A.%5C%5Ckitchen'&targetFramework=''&includePrerelease=false HTTP/1.1" 200 1398 "-" "Chocolatey Core"

which fails to find the package for several nuget servers.
I tried with chocolatier (https://github.com/MelonSmasher/Chocolatier), artifactory and azuredevops nuget feed and they all fail to find the package when using --params as above.

Maybe we should have two sets of options, one for choco install and one for choco list.
Another solution would be to filter out options that are "invalid" for the choco list command.

**Comment by samodelkinas** [comment]
This is affecting chef-client 15.1.36 as well. When a package from Artifactory is installed without additional options passed via resource, installation succeeds, otherwise "No candidate version available for consul"

**Comment by nimDevOps** [comment]
Tested again with latest current version 15.2.32 and the issue is still there. It looks like all following stable builds 15.2.20,15.1.36,15.0.300,15.0.298,15.0.293,14.13.11,14.12.9,14.12.3,14.11.21 have chocolatey resource broken.

**Comment by armartins-gcm** [comment]
I'm facing the same problem with chef version 15.2.20 when I try to run the command:

```
chocolatey_package 'awscli' do
    options "--allowEmptyChecksums"
    action :install
    not_if "where.exe aws"
  end
```

> C:\ProgramData\chocolatey/bin/choco.exe list -r awscli --allowemptychecksums

Invalid URI: The format of the URI could not be determined.

**Comment by nimDevOps** [comment]
I'm using choco version 0.10.15, and the issue started when chocolatey_package resource is called with options that are being sent to Chocolatey package repository: some servers cannot handle extra options. Examples above are Artifactory and ProGet . Some servers are Ok with this new feature, for example ChocoGallery.

**Comment by trickyearlobe** [comment]
Confirmed to be affecting customers. See Zendesk 23195
