### ISSUE TITLE
Windows_Task not setting the run as user correctly

### ISSUE THREAD

**Issue by sydnguyen** [chef/chef#8438]
# Describe the problem

The windows_task resource is not setting the user run as correctly.  Instead, it puts the user name in the author field in Task Scheduler.

## Software Version

Windows 10
Chef-client version 14.12.9

## Stacktrace

<details><summary>  </summary>
```
```
</details>

**Comment by manikafsgarg1** [comment]
@sydnguyen Could you please provide me some more details like `recipe, logs` as it is working fine with me on `Windows 10` with chef-client `14.12.9`

**Comment by lamont-granquist** [comment]
Closing this as the problem description is lacking and requires too much replication work.
