### ISSUE TITLE
Bootstrap: If the SSH fingerprint is unknown offer to continue anyways

### ISSUE THREAD

**Issue by tas50** [chef/chef#8482]
If we encounter an unknown ssh key we should offer to continue. Just about everyone is going to hit this and then have to start over with the flag to ignore the unknown keys.

```
Creating new client for tim_test
Creating new node for tim_test
Connecting to ec2-34-221-181-2.us-west-2.compute.amazonaws.com
ERROR: Train::Transports::SSHFailed: SSH command failed (fingerprint SHA256:ll/BKqLRTOgQXaFCFUaHx5/JxDYvOpAbSS80NVTek8Q is unknown for "ec2-34-221-181-2.us-west-2.compute.amazonaws.com,34.221.181.2")
```

**Comment by NAshwini** [comment]
@marcparadise facing same issue on knife-google for chef-15 
`SSH command failed (fingerprint SHA256:xGprjh8ZRyroWgyEjqWJAe1LiV3FCrvLsuhH+G9Ec2w is unknown for "34.73.227.153") (Train::Transports::SSHFailed)`

**Comment by btm** [comment]
I'm getting this error from `knife bootstrap` even after I've ssh'd into a system and accepted the fingerprint using `ssh`.
