### ISSUE TITLE
The first install of chef shows an error trying to removing an existing install

### ISSUE THREAD

**Issue by tas50** [chef/chef#8484]
The first time install of Chef Client looks like something went wrong as it can't remove the previous install directory:

```
 [ec2-52-88-252-105.us-west-2.compute.amazonaws.com] removing /opt/chef...
 [ec2-52-88-252-105.us-west-2.compute.amazonaws.com] mv: cannot stat ‘/opt/chef’: No such file or directory
```

**Comment by lamont-granquist** [comment]
need to know the distro.  someone changed behavior of rm -rf that has been stable for at least 30 years...

**Comment by lamont-granquist** [comment]
oh no, that's mv right.  fuck.
