### ISSUE TITLE
Chef 15: knife bootstrap without --bootstrap-version option fails

### ISSUE THREAD

**Issue by vijaymmali1990** [chef/chef#8490]
## Description
If we run the `knife bootstrap` without `--bootstrap-version` option, It looks for the stable/15 version of the chef-client. But we don't have the latest stable version available.

Output:

> Omnitruck artifact does not exist for version 15 on platform ubuntu
> Either this means:
>  - We do not support ubuntu
>   - We do not have an artifact for 15

## Chef Version
Chef Infra Client: 15.0.266

## Platform Version
Ubuntu 18.04

## Replication Case
`knife bootstrap user@ip -P password -N test-node  --sudo`
## Client Output

> Omnitruck artifact does not exist for version 15 on platform ubuntu
> Either this means:
> 
> We do not support ubuntu
> We do not have an artifact for 15

```

```

**Comment by marcparadise** [comment]
This is expected.  You can use the deprecated `--prerelease` flag or specify `--channel current` to pull in the latest versions of chef.

**Comment by marcparadise** [comment]
This is expected.  You can use the deprecated `--prerelease` flag or specify `--channel current` to pull in the latest versions of chef.
