### ISSUE TITLE
Chef 15: Missing --session-timeout bootstrap option 

### ISSUE THREAD

**Issue by vsingh-msys** [chef/chef#8491]
### Describe the Enhancement:

As per the documentation https://github.com/chef/chef/blob/master/RELEASE_NOTES.md#changed-flags we have `--session-timeout` option for the both `ssh` and `winrm` but only `--winrm-session-timeout` available

### Describe the Need:

1.  `--session-timout` for both winrm & ssh
OR 
2. `--winrm-session-timeout` and `--ssh-session-timeout` for winrm and ssh respectively.
OR
3. Need to update the RELEASE_NOTE.md 

--session-timeout MINUTES | --session-timeout SECONDS | New for ssh, existing for winrm. The unit has changed from MINUTES to SECONDS for consistency with other timeouts.
-- | -- | --

### Can We Help You Implement This?:
Based on the above suggestions need clarification which one should be implemented.

**Comment by marcparadise** [comment]
Let's rename winrm-sessin -timeout to session-timeout, and add winrm-session-timeout to deprecations.  You'll also need to verify that we're passing that option through to train source from get_config(:session_timeout) instead of :winrm_session_timeout

**Comment by vsingh-msys** [comment]
Fixed in https://github.com/chef/chef/pull/8521
