### ISSUE TITLE
Chef 15: knife bootstrap fails for passwordless ssh on node

### ISSUE THREAD

**Issue by vijaymmali1990** [chef/chef#8493]
## Description
When we try to bootstrap the passwordless node where the public key of the workstation has been added, It fails to bootstrap the node.

## Chef Version
Chef Infra Client: 15.0.266

## Platform Version
Ubuntu 18.04

## Replication Case

> 1. Create a node and add the public key of a workstation. (Passwordless ssh connection should happen.)
> 2. Run the command `knife bootstrap USER@IP -N node1`

## Client Output

>ERROR: Train::ClientError: Your SSH Agent has no keys added, and you have not specified a password or a key file

```

```

**Comment by marcparadise** [comment]
In my passwordless bootstrapping I have not seen this. Taking a look.

**Comment by marcparadise** [comment]
I was able to succesfully bootstrap using: 
* `--ssh-identity-file` 
* using `ssh-add` to add the key to the agent, without specifying it on the CLI. 

Is your ssh-agent running locally with the key added (ssh-add /path/to/key.pem)? 


Was the key to access the new node loaded in the local ssh-agent ? The error above suggests that it may not have been.

**Comment by vijaymmali1990** [comment]
> I was able to succesfully bootstrap using:
> 
> * `--ssh-identity-file`
> * using `ssh-add` to add the key to the agent, without specifying it on the CLI.
> 
> Is your ssh-agent running locally with the key added (ssh-add /path/to/key.pem)?
> 
> Was the key to access the new node loaded in the local ssh-agent ? The error above suggests that it may not have been.

Tried by restarting the ssh-agent and adding the key. Still, it gives the same error.

**Comment by vijaymmali1990** [comment]
Now its showing different error while knife bootstrap

> ERROR: ChefCore::TargetHost::ConnectionFailure: ChefCore::TargetHost::ConnectionFailure

**Comment by btm** [comment]
@vijaymmali1990 could you be more specific about your platforms? Are both your workstation and the server you're trying to bootstrap Ubuntu 18.04? Can you post the output of `knife bootstrap -VV ....` to gist.github.com and share it? Are you seeing the #8482 as well?

**Comment by vijaymmali1990** [comment]
@btm With `15.0.293` I am able to do passwordless knife bootstrap on node successfully. We can close this issue.
