### ISSUE TITLE
yum_package: RPMdb read lock not released when there is wildcard in disablerepo defined in option

### ISSUE THREAD

**Issue by lytao** [chef/chef#8515]
## Description
In Chef 14, when we have such a yum_package resource to run:
```
yum_package 'mypackage' do
  options '--disablerepo=* --enablerepo=myrepo'
  action :upgrade
end
```
The wildcard is not processed well in yum_helper.py. However, the worst thing is, it will cause yum_helper.py exit not in a right way (not killed by any of SIGINT/SIGHUP/SIGPIPI/SIGQUIT) and no exception raised. So the exit_handler is not tiggered. That way, rpmdb got locked after running chef-client for several times.

## Chef Version
14.12.9

## Platform Version
CentOS 7.6

## Client Output                             
Chef-client will not raise any exception, but once RPM db locked, the next chef-client run will raise:
```
error: rpmdb: BDB0113 Thread/process 186206/139995210921792 failed: BDB1507 Thread 
died in Berkeley DB library                                                        
error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, 
run database recovery                                                              
error: cannot open Packages index using db5 -  (-30973)                            
error: cannot open Packages database in /var/lib/rpm                               
error: rpmdb: BDB0113 Thread/process 186206/139995210921792 failed: BDB1507 Thread 
died in Berkeley DB library                                                        
error: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, 
run database recovery                                                              
error: cannot open Packages database in /var/lib/rpm                               
```

**Comment by lytao** [comment]
Today I got another case related to the same issue. When we have a broken yum repository defined in "/etc/yum.repos.d", we got same rpmdb lock issue.
Then I traced the processes, and found there is no exceptions catch in method "query(command)" in lib/chef/provider/package/yum/yum_helper.py. That means, any yum failure can cause rpmdb locked.

You should catch all exceptions in the code block:
```
    if command['action'] == "whatinstalled":      
        query(command)                            
    elif command['action'] == "whatavailable":    
        query(command)                            
    elif command['action'] == "versioncompare":   
        versioncompare(command['versions'])       
    elif command['action'] == "installonlypkgs":  
         install_only_packages(command['package'])
    else:                                         
        raise RuntimeError("bad command")         
```
and release rpmdb lock!

**Comment by lamont-granquist** [comment]
Nice debugging, I'll take a look at both of these when I get a chance.
