### ISSUE TITLE
chef.psm1 PowerShell Module uses unapproved verbs

### ISSUE THREAD

**Issue by johnmccrae** [chef/chef#8525]
The Chef powershell module uses unapproved verbs for naming functions and should be updated to reflect proper coding techniques. 

Current -> Suggested
Run-RubyCommand -> Invoke-RubyCommand
Run-ExecutableAndWait -> Invoke-ExecutableAndWait
Load-WIn32Bindings -> Initialize-WIn32Bindings

The win32 Kernel code at the top could be refactored following the example at the end of this page to make it more readable. https://www.raydbg.com/2017/Call-Native-Win32-API-in-PowerShell/

## Motivation

    As a software developer,
    I want to have confidence in Chef software because it uses current coding standards,
    so that I can trust their products and more confidently use them and talk them up to my peers.

## Specification

1 - rename the functions to the suggested or to a compatible verb-noun format
2 - refactor the win32 binding to be more readable. 

Attached is the suggested changes already made. I included help tips and got rid of extra whitespace as well. 

[chef-suggested.psm1.txt](https://github.com/chef/chef-workstation/files/3099069/chef-suggested.psm1.txt)

## Downstream Impact

Any hard-coded references to the functions will be impacted. However, since only the chef* functions are actually exported for use by the end-user, the impact should be minimal.

**Comment by tas50** [comment]
@johnmccrae can you open a PR to fix this?

**Comment by johnmccrae** [comment]
Happy to! Cheers

**Comment by tas50** [comment]
Closing this out since I believe we fixed it.
