### ISSUE TITLE
[CHEF 15] Bootstrapping a server now causes 'No such file or directory' all of a sudden.

### ISSUE THREAD

**Issue by breisig** [chef/chef#8534]
I have upgraded from Chef client 14.xx to Chef Infra Client: 15.0.293 and tried bootstrapping a server as normal [had to replace -x on the command line with --connection-user and  --connection-password] but now I keep getting the follow error message when attempting to boostrap a server.

Performing legacy client registration with the validation key at /home/test/.chef/mychefserver.pem..."
Delete your validation key in order to use your user credentials for client registration instead.
Connecting to test.mytestsite.com
ERROR: Errno::ENOENT: No such file or directory @ rb_sysopen - /tmp/d20190514-10948-1pq02vu/test.mytestsite.com.pem

**Comment by marcparadise** [comment]
Thanks for reporting this @breisig. Could you let us know what your workstation OS/version is, and the OS/version of the node you're bootstrapping?  It would also help to know which cloud provider for the target node, or if the target node is internal/local.

**Comment by breisig** [comment]
@marcparadise  Both the workstation and bootstrapped server is using the latest CentOS 7.6 64bit. The target server is just an internal VM running on a fresh CentOS 7.6 minimal image [with all patches].

**Comment by marcparadise** [comment]
Thanks, I'll see if I can get the same to occur.  

Would you be able to include the redacted CLI  and its output when run with -VV? (Note two Vs and not three - two will not give the stack trace I'm hoping for - ref https://github.com/chef/chef/issues/8433 for the curious...)

**Comment by dheerajd-msys** [comment]
@breisig Until you confirm with the complete `stacktrace` I would like to say that I was getting the similar error from Windows workstation with `chef v15` here https://github.com/chef/knife-ec2/issues/575. In my `knife.rb` there was an entry for `validation_key` which is old process for client registration. Deleting the entry and file from the path resolved my error. Could you please cross-verify if you are doing the same.

Thanks,
