### ISSUE TITLE
Habitat plan needs to be updated to use Ruby 2.6

### ISSUE THREAD

**Issue by tas50** [chef/chef#8540]
Right now our habitat plan for Chef uses the Ruby plan, but that's Ruby 2.5. We need to match the ruby version in the omnibus packages.

**Comment by vsingh-msys** [comment]
In PR https://github.com/chef/chef/pull/8789 we have added specific ruby version `core/ruby26` in hab plan.
https://github.com/chef/chef/blob/eba5e508378bee322d3501adcd501992dcd8f98e/habitat/plan.sh#L14

**Comment by btm** [comment]
Fixed in v15.0.295+
