### ISSUE TITLE
Chef-client 15 breaks all unattended installs

### ISSUE THREAD

**Issue by voroniys** [chef/chef#8547]
## Description
chef-client 15 requires to accept the licenses what breaks all unattended installs.  
## Chef Version

15.0.293
## Client Output

```
Chef Infra Client cannot execute without accepting the license
Chef Infra Client cannot execute without accepting the license

```

**Comment by gryte** [comment]
Per the release notes

> *...Chef EULA
> Chef Infra Client now requires a EULA to be accepted by users before it can run. Users can accept the EULA in a variety of ways:
> 
> chef-client --chef-license accept
> chef-client --chef-license accept-no-persist
> CHEF_LICENSE="accept" chef-client
> CHEF_LICENSE="accept-no-persist" chef-client...*

- [Chef Infra Client 15.0.293 Released!](https://discourse.chef.io/t/chef-infra-client-15-0-293-released/15110)

Per the client.rb documentation

> *...chef_license
> Used to accept the Chef license. Performs a no-op on versions where the license is not required. Can be set to accept or accept-no-persist....*

- [client.rb](https://docs.chef.io/config_rb_client.html)

Per the chef-client cookbook readme

> *...node['chef_client']['license'] - Set to 'accept' or 'accept-no-persist' to accept the license before upgrading to Chef 15....*

- [chef-client](https://supermarket.chef.io/cookbooks/chef-client)


Does this help?

**Comment by rcorning** [comment]
Having the same problem.  None of the above solutions work with chef-solo for my packer builds.  

Any ideas?

**Comment by tas50** [comment]
@rcorning We released 15.0.300 today which includes `--chef-license` cli flag support in chef-solo.

**Comment by rcorning** [comment]
@tas50 It works perfectly, thank you!!!

**Comment by mginster** [comment]
> @tas50 It works perfectly, thank you!!!

How did you pass that down via chef-solo in the packer provisioner? The actual execute is buried in the batch.
