### ISSUE TITLE
Include filename when rendering templates with Erubis to deliver better errors

### ISSUE THREAD

**Issue by brodock** [chef/chef#8561]
### Describe the Enhancement:
I want to annotate `Erubis::Eruby` invocation to inform the `filename` as well, not only the `template` content, so we could trace easier where exceptions are coming from.

### Describe the Need:
When you have a `NoMethodError` happening inside a template, it's usually hard to figure out where it is coming from. When using chefspec, all you get is the spec line that triggered it, but sometimes it can be not obvious which template it triggered (consider the use-case when you have a cookbook coordinating several others).

While the `TemplateError` can output some nice information, that is not displayed in RSpec, because it calls `exception.message` instead of `exception.to_s` which is where Chef adds all sorts of information like a brief snippet of the content, the line number and the template filename.

This would allow us to move from: 

```bash
     Chef::Mixin::Template::TemplateError:
       undefined method `[]' for nil:NilClass
     ...
     # ./spec/chef/recipes/nginx_spec.rb:37:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `[]' for nil:NilClass
     #   (erubis):169:in `block in evaluate'
```

To something better like:

```
     Chef::Mixin::Template::TemplateError:
       undefined method `[]' for nil:NilClass
     ...
     # ./spec/chef/recipes/nginx_spec.rb:37:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `[]' for nil:NilClass
     #   ./path/to/templates/default/nginx-gitlab-http.conf.erb:169:in `block in evaluate'
```
### Current Alternative
No 😢 

### Can We Help You Implement This?:
I can send a PR with the changes. 👍

**Comment by btm** [comment]
Fixed by #8562
