### ISSUE TITLE
Old knife bootstrap windows winrm -x short arg should raise a deprecation

### ISSUE THREAD

**Issue by btm** [chef/chef#8566]
Before Chef 15 / knife-windows 3, running `knife bootstrap windows winrm` took a `-x USER` short flag. We've deprecated `--winrm-user` to `--connection-user` but we should also catch `-x` and tell the user to use `-U` instead. 

What you get right now is:
```
Error: invalid option: -x
[snip --help output]
```

**Comment by f0rkz** [comment]
This really threw a wrench in our gears. Even the documentation specifies `-x USER` bootstrapping a node.

https://docs.chef.io/install_bootstrap.html
