### ISSUE TITLE
Chef -15: Missing deprecated options warning

### ISSUE THREAD

**Issue by vsingh-msys** [chef/chef#8572]
## Description

As per the release note, we have deprecated following options:

| Flag        | New option |
| ------------- |:-------------:|
| --forward-agent | --ssh-forward-agent
| --ssh-port | --connection-port 
| --winrm-ssl-verify-mode MODE | --winrm-no-verify-cert 
| --winrm-transport TRANSPORT | --winrm-ssl 

But if we use these flags it showed invalid option.

Error: invalid option: --ssh-port

## Related Issues
https://github.com/chef/chef/issues/8566

**Comment by tas50** [comment]
This has been fixed in master
