### ISSUE TITLE
Reboot resource giving exception after chef-client run on linux & Windows

### ISSUE THREAD

**Issue by borraviram** [chef/chef#8596]
## Description
We are facing a node failure issues while spin up a machine through scalr. 

Here the problem is machine is loaded with chef runlists, one of the recipe is calling system reboot after chef-client finish and system being rebooted and system state showing failed in scalr(scalr is integrated to AWS console). 

This reboot request was running fine with chef-client 12. now the problem with recent upgraded chef-client 14. we do foodcritic and no warning for reboot resource, no changes in  chef-client 14 release notes. we have this issue for both linux and windows machines while calling reboot resource

## Chef Version
chef-client -- 14.10.9

## Platform Version

CentOS 7.X Final (64bit)

## Replication Case
Below is the sample code to replicate the issue
one of the recipe test.rb in runlist and 
#recipe start
file '/tmp/hello' do
  action :create
  notifies :request_reboot, 'reboot[Restart Computer]', :delayed
end

reboot 'Restart Computer' do
  action :nothing
  reason 'Need to reboot when the run completes successfully.'
  delay_mins 2
  ignore_failure true
end
#recipe end

## Client Output
outout from scalr console
==================
Command "/usr/bin/chef-client" exited with code 35 

Chef trace:
Generated at 2019-05-27 08:32:17 +0000
Chef::Exceptions::Reboot: Rebooting server at a recipe's request. Details: {:delay_mins=>2, :reason=>"Need to reboot when the run completes successfully.", :timestamp=>2019-05-27 08:32:16 +0000, :requested_by=>"Restart Computer"}
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/platform/rebooter.rb:59:in `reboot!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/platform/rebooter.rb:65:in `reboot_if_needed!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/client.rb:308:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application/client.rb:444:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/bin/chef-client:25:in `<top (required)>'

output from the server log
=================
Chef Client finished, 126/189 resources updated in 04 minutes 50 secondsESC[0m
[2019-05-27T08:32:17+00:00] WARN: Rebooting server at a recipe's request. Details: {:delay_mins=>2, :reason=>"Need to reboot when the run completes successfully.", :timestamp=>2019-05-27 08:32:16 +0000, :requested_by=>"Restart Computer"}
ESC[0m
Running handlers:ESC[0m
[2019-05-27T08:32:17+00:00] ERROR: Running exception handlers
  - Chef::Handler::TimestampESC[0m
Running handlers complete
ESC[0m[2019-05-27T08:32:17+00:00] ERROR: Exception handlers complete
Chef Client failed. 126 resources updated in 04 minutes 50 secondsESC[0m
[2019-05-27T08:32:17+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2019-05-27T08:32:17+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-05-27T08:32:17+00:00] FATAL: Chef::Exceptions::Reboot: Rebooting server at a recipe's request. Details: {:delay_mins=>2, :reason=>"Need to reboot when the run completes successfully.", :timestamp=>2019-05-27 08:32:16 +0000, :requested_by=>"Restart Computer"}

## Stacktrace
Generated at 2019-05-27 08:32:17 +0000
Chef::Exceptions::Reboot: Rebooting server at a recipe's request. Details: {:delay_mins=>2, :reason=>"Need to reboot when the run completes successfully.", :timestamp=>2019-05-27 08:32:16 +0000, :requested_by=>"Restart Computer"}
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/platform/rebooter.rb:59:in `reboot!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/platform/rebooter.rb:65:in `reboot_if_needed!'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/client.rb:308:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application.rb:261:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application/client.rb:444:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application.rb:66:in `run'
/opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:74:in `load'
/usr/bin/chef-client:74:in `<main>'

Thanks in advance!

**Comment by jordan3825** [comment]
I have this same problem. I believe these two commit are related to this. 

https://github.com/chef/chef/commit/4a3a0e13f658d894989c91ee5bc85429b22d51c8
https://github.com/chef/chef/commit/dfab5dcee8e8bfa25bba7b87b5a4366347d53279

**Comment by recipe** [comment]
It should be fixed in Scalarizr 7.14.5

**Comment by borraviram** [comment]
> It should be fixed in Scalarizr 7.14.5

Thanks Vitaliy , it worked after scalarizr update to 7.14.5
