### ISSUE TITLE
Raise an error on Chef 14 when trying to bootstrap Chef 15

### ISSUE THREAD

**Issue by btm** [chef/chef#8623]
### Describe the Enhancement:
`knife bootstrap` on Chef 14 should check what version we're going to install and if it is >= 15 we should raise an error.

### Describe the Need:
The license acceptance features of Chef 15 would be difficult to backport to Chef 14 given the refactoring and improvements to `knife bootstrap` in Chef 15. We should raise an error that says "You must use Chef 15 or later to bootstrap Chef 15 nodes"

### Current Alternative
It currently breaks and doesn't work.

**Comment by shindemahendra** [comment]
Add raise an error on Chef 14 when trying to bootstrap Chef 15 #8777

Chef-14: Raise an error on Chef 14 when trying to bootstrap Chef 15 #8782
