### ISSUE TITLE
knife Exception: NameError: uninitialized constant Chef::Knife::Bootstrap::ChefVaultHandler

### ISSUE THREAD

**Issue by BGaudreault-EDR** [chef/chef#8645]
## Description
Cannot get knife to bootstrap an instance.  I get the error "Exception: NameError: uninitialized constant Chef::Knife::Bootstrap::ChefVaultHandler"

## Chef Version
Chef Development Kit Version: 4.0.60
chef-client version: 15.0.300

## Platform Version
Windows 10 Enterprise 10.0.16299 N/A Build 16299

## Replication Case
I run the following command: 'knife bootstrap windows winrm ^NAME^ -N ^name^ -x Domain\Username -V -y -E prod --bootstrap-version '13.6.4' -r 'recipe[chef-client::default]''

## Client Output
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300-universal-mingw32/lib/chef/knife/bootstrap.rb:31: warning: already initialized constant Chef::Knife::Bootstrap::SUPPORTED_CONNECTION_PROTOCOLS
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300-universal-mingw32/lib/chef/knife/bootstrap.rb:31: warning: previous definition of SUPPORTED_CONNECTION_PROTOCOLS was here
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300-universal-mingw32/lib/chef/knife/bootstrap.rb:32: warning: already initialized constant Chef::Knife::Bootstrap::WINRM_AUTH_PROTOCOL_LIST
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300-universal-mingw32/lib/chef/knife/bootstrap.rb:32: warning: previous definition of WINRM_AUTH_PROTOCOL_LIST was here
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300-universal-mingw32/lib/chef/knife/bootstrap.rb:350: warning: already initialized constant Chef::Knife::Bootstrap::DEPRECATED_FLAGS
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300-universal-mingw32/lib/chef/knife/bootstrap.rb:350: warning: previous definition of DEPRECATED_FLAGS was here
C:/opscode/chefdk/embedded/lib/ruby/gems/2.6.0/gems/rbvmomi-1.13.0/lib/rbvmomi/vim.rb:8: warning: Win32API is deprecated after Ruby 1.9.1; use fiddle directly instead
INFO: Using configuration from C:/Users/Username/.chef/knife.rb
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_shell and found value cmd
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key ca_trust_file and found value
DEBUG: Looking for key winrm_user and found value Domain\Username
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_transport and found value plaintext
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_password and found value
DEBUG: Looking for key winrm_port and found value 5985
DEBUG: Looking for key session_timeout and found value 30
DEBUG: Looking for key session_timeout and found value 30
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_transport and found value plaintext
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key winrm_transport and found value plaintext
DEBUG: Looking for key winrm_authentication_protocol and found value negotiate
DEBUG: Looking for key ca_trust_file and found value
DEBUG: Looking for key ssl_peer_fingerprint and found value
DEBUG: Looking for key winrm_shell and found value cmd
DEBUG: Looking for key winrm_codepage and found value 65001
Enter your password:
DEBUG: Looking for key ca_trust_file and found value
DEBUG: Adding NAME
DEBUG: WinRM::WinRMWebService options: {:user=>"DOMAIN\\Username", :password=>"PASSWORD", :basic_auth_only=>false, :disable_sspi=>false, :no_ssl_peer_verification=>false, :ssl_peer_fingerprint=>nil, :endpoint=>"http://NAME:5985/wsman", :transport=>:negotiate, :ca_trust_path=>nil, :operation_timeout=>1800}
DEBUG: Endpoint: http://NAME:5985/wsman
DEBUG: Transport: negotiate
ERROR: knife encountered an unexpected error
This may be a bug in the 'bootstrap windows winrm' knife command or plugin
Please collect the output of this command with the `-VVV` option before filing a bug report.
Exception: NameError: uninitialized constant Chef::Knife::Bootstrap::ChefVaultHandler

## Stacktrace
N/A?

**Comment by vsingh-msys** [comment]
Hey @BGaudreault-EDR it is similar to https://github.com/chef/chef/issues/8461 as we have already fixed in https://github.com/chef/knife-windows/pull/480. Could you please you update the knife-windows plugin.

**Comment by vsingh-msys** [comment]
Closing for now as no response. Feel free to reopen if you still face the issue.
