### ISSUE TITLE
'-s' has different meaning depending on which 'knife data bag' commands are used

### ISSUE THREAD

**Issue by mattray** [chef/chef#8647]
# Description

`knife data bag show -s`
and 
`knife data bag delete BAG -s`
have different meanings of `-s`. For `show` it means `--secret` and for `delete` it means `--server-url`. It would probably make sense to deprecate and remove the -s in favor of only supporting longform commands to prevent issues. We were able to catch it by looking through the -VVV output.

# ChefDK Version

At least since chefdk-2.4.17, it was reported by a large customer and it's still the same behavior.

**Comment by vsingh-msys** [comment]
Fixed in #8909
