### ISSUE TITLE
inspec missing from chef-15 package

### ISSUE THREAD

**Issue by nicutor** [chef/chef#8652]
## Description
Hi all,

I've installed chef-15 and I find out that inspec is no longer shipped with chef package.
Can somebody confirm this? I need to install inspec separatelly now?

When I am using chef-client first time, its asking to accept the license for inspec too, so I guess there is something missing.

If inspec need to be installed separatelly, can you please guide me how can I do this automatically when using kitchen?

## Chef Version
Chef Infra Client: 15.0.300

## Platform Version
debian 8/9, ubuntu 14/16/18, centos 6/7

**Comment by tas50** [comment]
Thanks for the report @nicutor. I've merged in the extra gem we needed in Chef 15 to add back the binaries. Keep in mind that the InSpec that comes with Chef is not the full InSpec though. It's inspec-core which is missing a bunch of the plugin packs.
