### ISSUE TITLE
Property Aliases documentation

### ISSUE THREAD

**Issue by mjingle** [chef/chef#8656]
### Describe the Enhancement:

Currently, property aliases are not documented for chef/chef. (See [this example of aliases](https://github.com/chef/chef/blob/master/lib/chef/resource/git.rb).) Ideally, this gap in documentation should be fixed.

### Describe the Need:

Property aliases may be something that users use, yet users are not able to cross-reference within the docs.

### Current Alternative:

Currently, property aliases can be found in the code, but not in the docs. It's just something that magically works for folks.

### Can We Help You Implement This?:

Please determine if documenting property aliases is something to invest time in. Another factor in this decision is how to automate the documentation of property aliases if the answer is yes.

**Comment by lamont-granquist** [comment]
That isn't a "property alias", that is just a ruby alias of the method.  Maybe the aliases could be added to the property itself, but that particular ruby statement can't really be extended itself in any way.

**Comment by tas50** [comment]
Yeah the point was that we're just using the method aliases and those aren't known by chef in any way. We probably need a "chef way" of doing this in the resource class that allows us to bubble up aliases in the docs.

**Comment by tas50** [comment]
Closing this out since we don't really have any way to fix it. In general if we have an alias we should create a cookstyle rule to get folks off the old name. I've done that for yum_repository that had some historic names.
