### ISSUE TITLE
Bootstrapping Chef node Exception: 404 -- 404 "Not Found"  (This is normal if you do not have Chef Automate)

### ISSUE THREAD

**Issue by viniciobombacino** [chef/chef#8657]
## Description

I'm getting the below error while provisioning servers using SOftlayer API. 
ERROR: Excon::Error::Socket: Connection reset by peer (Errno::ECONNRESET) 

We use the Knife Softlayer command to provision Servers as below: 
knife softlayer server create 

## Chef Version
Chef Client, version 12.21.3

## Platform Version
Platform: x86_64-linux

## Replication Case
Run the following command:
knife softlayer server create 

## Client Output
Launching SoftLayer VM, this may take a few minutes.
[2019-06-11T07:31:50+0200] INFO: spark-worker11-06-2019-SJHO9M2QP5-Prod-1 node does not exist
[2019-06-11T07:31:52+0200] INFO: spark-worker11-06-2019-SJHO9M2QP5-Prod-1 node does not exist
[2019-06-11T07:31:53+0200] INFO: Submitting request to provision worker node: spark-worker11-06-2019-SJHO9M2QP5-Prod-1
[2019-06-11T07:31:53+0200] INFO: Creating Virtual Server for node = spark-worker11-06-2019-SJHO9M2QP5-Prod-1
[2019-06-11T07:31:53+0200] INFO: Using following parameters to create virtual 
 --server:spark-worker11-06-2019-SJHO9M2QP5-Prod-1 
 --image-id ded69c20-61e0-4e4f-99ac-98ce0de6bccc 
 --ssh-keys 1046023 
 --hostname spark-worker11-06-2019-SJHO9M2QP5-Prod-1 
 --network-interface-speed 100 
 --domain kantar.com 
 --cores 4 
 --ram 16 
 --datacenter osl01 
 --node-name spark-worker11-06-2019-SJHO9M2QP5-Prod-1 
 --private-network-only 
 --private-vlan 2212173 
 --use-private-network 
 -x root 
 -i /home/finmcadmprd/.ssh/id_rsa 
 -t 1500
Launching SoftLayer VM, this may take a few minutes.
[2019-06-11T07:31:55+0200] INFO: spark-worker11-06-2019-SJHO9M2QP5-Prod-2 node does not exist
[2019-06-11T07:31:57+0200] INFO: spark-worker11-06-2019-SJHO9M2QP5-Prod-2 node does not exist
[2019-06-11T07:31:58+0200] INFO: Submitting request to provision worker node: spark-worker11-06-2019-SJHO9M2QP5-Prod-2
[2019-06-11T07:31:58+0200] INFO: Creating Virtual Server for node = spark-worker11-06-2019-SJHO9M2QP5-Prod-2
[2019-06-11T07:31:58+0200] INFO: Using following parameters to create virtual 
 --server:spark-worker11-06-2019-SJHO9M2QP5-Prod-2 
 --image-id ded69c20-61e0-4e4f-99ac-98ce0de6bccc 
 --ssh-keys 1046023 
 --hostname spark-worker11-06-2019-SJHO9M2QP5-Prod-2 
 --network-interface-speed 100 
 --domain kantar.com 
 --cores 4 
 --ram 16 
 --datacenter osl01 
 --node-name spark-worker11-06-2019-SJHO9M2QP5-Prod-2 
 --private-network-only 
 --private-vlan 2212173 
 --use-private-network 
 -x root 
 -i /home/finmcadmprd/.ssh/id_rsa 
 -t 1500
Launching SoftLayer VM, this may take a few minutes.
.....................................................................................................................................................

Bootstrapping Chef node, this may take a few minutes.
.10.180.103.120 -----> Existing Chef installation detected
10.180.103.120 Starting the first Chef Client run...
............10.180.103.120 [2019-06-11T00:32:26-05:00] INFO: Forking chef instance to converge...
10.180.103.120 Starting Chef Client, version 12.21.3
10.180.103.120 [2019-06-11T00:32:26-05:00] INFO: *** Chef 12.21.3 ***
10.180.103.120 [2019-06-11T00:32:26-05:00] INFO: Platform: x86_64-linux
10.180.103.120 [2019-06-11T00:32:26-05:00] INFO: Chef-client pid: 1878
10.180.103.120 [2019-06-11T00:32:26-05:00] INFO: The plugin path /etc/chef/ohai/plugins does not exist. Skipping...
.....10.180.103.120 [2019-06-11T00:32:29-05:00] ERROR: Unable to fetch softlayer metadata from https://api.service.softlayer.com/rest/v3.1/SoftLayer_Resource_Metadata/getFullyQualifiedDomainName.txt: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server hello A: wrong version number
..10.180.103.120 Creating a new client identity for spark-worker11-06-2019-SJHO9M2QP5-Prod-1 using the validator key.
10.180.103.120 [2019-06-11T00:32:30-05:00] INFO: Client key /etc/chef/client.pem is not present - registering
10.180.103.120 [2019-06-11T00:32:30-05:00] INFO: HTTP Request Returned 404 Object Not Found: error
10.180.103.120 [2019-06-11T00:32:30-05:00] INFO: Run List is []
10.180.103.120 [2019-06-11T00:32:30-05:00] INFO: Run List expands to []
10.180.103.120 [2019-06-11T00:32:30-05:00] INFO: Starting Chef Run for spark-worker11-06-2019-SJHO9M2QP5-Prod-1
10.180.103.120 [2019-06-11T00:32:30-05:00] INFO: Running start handlers
10.180.103.120 [2019-06-11T00:32:30-05:00] INFO: Start handlers complete.
10.180.103.120 [2019-06-11T00:32:30-05:00] INFO: HTTP Request Returned 404 Not Found: 
10.180.103.120 [2019-06-11T00:32:30-05:00] INFO: HTTP Request Returned 404 Not Found: 
10.180.103.120 [2019-06-11T00:32:30-05:00] INFO: Error while reporting run start to Data Collector. URL: https://10.180.103.106//organizations/kantar-media/data-collector Exception: 404 -- 404 "Not Found"  (This is normal if you do not have Chef Automate)
10.180.103.120 resolving cookbooks for run list: []
.10.180.103.120 [2019-06-11T00:32:30-05:00] INFO: Loading cookbooks []
10.180.103.120 Synchronizing Cookbooks:
10.180.103.120 Installing Cookbook Gems:
10.180.103.120 Compiling Cookbooks...
10.180.103.120 [2019-06-11T00:32:30-05:00] WARN: Node spark-worker11-06-2019-SJHO9M2QP5-Prod-1 has an empty run list.
10.180.103.120 [2019-06-11T00:32:30-05:00] INFO: HTTP Request Returned 404 Not Found: 
10.180.103.120 Converging 0 resources
10.180.103.120 [2019-06-11T00:32:30-05:00] INFO: Chef Run complete in 0.188501673 seconds
10.180.103.120 
10.180.103.120 Running handlers:
10.180.103.120 [2019-06-11T00:32:30-05:00] INFO: Running report handlers
10.180.103.120 Running handlers complete
10.180.103.120 [2019-06-11T00:32:30-05:00] INFO: Report handlers complete
10.180.103.120 Chef Client finished, 0/0 resources updated in 03 seconds
Applying tags to Chef node.

**Comment by lamont-granquist** [comment]
12.21.3 is an unsupported chef-client version and the message clearly specifies "This is normal if you do not have Chef Automate".

That message is suppressed if you're only using the formatter and not the logger, which is the default behavior on chef > 13

Don't really see how there's a bug report here.
