### ISSUE TITLE
Chef::Knife::Bootstrap::RemoteExecutionFailed

### ISSUE THREAD

**Issue by singh0009** [chef/chef#8697]
Chef::Knife::Bootstrap::RemoteExecutionFailed

# Describe the problem

While I am trying to add a new node in to the hosted chef server, I am keep getting "Chef::Knife::Bootstrap::RemoteExecutionFailed" error. Please help
root@osboxes:/home/osboxes/chef-repo# knife bootstrap 192.168.92.130 --connection-user osboxes  --sudo --use-sudo-password --node-name Node1 --run-list 'recipe[learn_chef_apache2]' --connection-password 'osboxes.org'
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300/lib/chef/knife/bootstrap.rb:31: warning: already initialized constant Chef::Knife::Bootstrap::SUPPORTED_CONNECTION_PROTOCOLS
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300/lib/chef/knife/bootstrap.rb:31: warning: previous definition of SUPPORTED_CONNECTION_PROTOCOLS was here
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300/lib/chef/knife/bootstrap.rb:32: warning: already initialized constant Chef::Knife::Bootstrap::WINRM_AUTH_PROTOCOL_LIST
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300/lib/chef/knife/bootstrap.rb:32: warning: previous definition of WINRM_AUTH_PROTOCOL_LIST was here
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300/lib/chef/knife/bootstrap.rb:350: warning: already initialized constant Chef::Knife::Bootstrap::DEPRECATED_FLAGS
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.300/lib/chef/knife/bootstrap.rb:350: warning: previous definition of DEPRECATED_FLAGS was here
Node Node1 exists, overwrite it? (Y/N) Y
Client Node1 exists, overwrite it? (Y/N) Y
Creating new client for Node1
Creating new node for Node1
Connecting to 192.168.92.130
WARN: [SSH] PTY requested: stderr will be merged into stdout
The authenticity of host '192.168.92.130 ()' can't be established.
fingerprint is SHA256:EgHkEDdS+sDWCmsyWq1n+qMnlwxULnNnEsa+zsoeco0.

Are you sure you want to continue connecting
? (Y/N) Y
WARN: [SSH] PTY requested: stderr will be merged into stdout
ERROR: Chef::Knife::Bootstrap::RemoteExecutionFailed: Chef::Knife::Bootstrap::RemoteExecutionFailed

## Software Version

ubuntu 19.04
## Replication Case

knife bootstrap 192.168.92.130 --connection-user osboxes  --sudo --use-sudo-password --node-name Node1 --run-list 'recipe[learn_chef_apache2]' --connection-password 'osboxes.org'

## Stacktrace

<details><summary>  </summary>
```
```
</details>

**Comment by Vasu1105** [comment]
@singh0009 could you please add stacktrace using verbose option i.e. -VV

**Comment by Vasu1105** [comment]
@singh009 feel free to reopen this if you still facing this.
