### ISSUE TITLE
Chef Client for Ubuntu 18.04 aarch64

### ISSUE THREAD

**Issue by timorkal** [chef/chef#8703]
Hello,
I wanted to know if there is a Chef Client version for for Ubuntu 18.04 aarch64.
And if not, what are the possible ways to run it?

**Comment by mattray** [comment]
@timorkal I've been doing 32-bit ARM builds for CentOS, Debian and Raspbian and documenting them here: https://mattray.github.io/2019/07/02/chef-15-on-arm.html

You should be able to take the instructions and do your own aarch64 builds. Feel free to ping me if you have any questions or need anything.

**Comment by timorkal** [comment]
@mattray , Thank you, I think it will help.

**Comment by mattray** [comment]
I expect you'll run into this issue like I did: https://github.com/chef/omnibus-software/issues/1070

Not specific to ARM, it's an Ubuntu 18.04 and later issue.

**Comment by mattray** [comment]
This patch appears to work on Debian 10, kicking off Ubuntu 18.04 aarch64 builds soon.
https://github.com/chef/omnibus-software/pull/1071

**Comment by mattray** [comment]
Ubuntu 18.04 aarch64 worked fine and the client's been running for a bit on my Raspberry Pi 3 B+. I'll update my blog with the next Chef client build, but here's a link to the .DEB if you want it in the meantime for testing: https://www.dropbox.com/s/gh28ov10bx5yjzg/chef_15.1.36%2B20190710203700-1_arm64.deb?dl=0
