### ISSUE TITLE
knife bootstrap Net::SSH::ConnectionTimeout

### ISSUE THREAD

**Issue by johnreed00** [chef/chef#8721]
# Description
Boostrapping a node runs into issue:
```
$ knife bootstrap 192.169.1.1 -N domain.local -x chefadmin --sudo
ERROR: Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout
```
Briefly describe the issue

The issue is similar to #1174  - the same command and error. 
First was created chef-server with chefdk and workstation on it. 
Running on virtual machines in Asure.

# ChefDK Version

Tell us which version of the ChefDK you are running. Run `chef --version` to display the version.

```
$ chef --version
Chef Development Kit Version: 3.5.13
chef-client version: 14.7.17
delivery version: master (6862f27aba89109a9630f0b6c6798efec56b4efe)
berks version: 7.0.6
kitchen version: 1.23.2
inspec version: 3.0.52
```

# Platform Version

Tell us which operating system distribution and version ChefDK is running on.

```
server/workstation/nodes:
CentOS Linux 7 (Core) 

Name        : chefdk
Version     : 3.5.13
Release     : 1.el7
Architecture: x86_64

```
# Replication Case

Tell us what steps to take to replicate your problem. See [How to create a Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) for information on how to create a good replication case.

Create Chef Server
Create & Configure workstation with Starter pak
Confirm above
Create Node1
Configure SSH access
Attempt to bootstrap (both password and key tried, both user and root tried)

# Stacktrace

username: 'chefadmin@DOMAIN.LOCAL' 
node: node1.domain.local

Please include the stacktrace.out output or link to a gist of it, if there is one.

$ knife bootstrap 192.169.1.9 -N node1.domain.local -x chefadmin --sudo
or
$ knife bootstrap node1.domain.local --ssh-user 'chefadmin@DOMAIN.LOCAL' --ssh-password 'qwerty' --node-name node1
or 
$ knife bootstrap 192.169.1.9 -x 'chefadmin@DOMAIN.LOCAL' -i key.rsa --sudo -N node1.domain.local -V --no-fips
```
Creating new client for node1.domain.local 
Creating new node for node1.domain.local 
Connecting to 192.169.1.9
#<Thread:0x0000000007065408@/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:471 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        8: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'
        7: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session_actions.rb:36:in `block (2 levels) in sessions'
        6: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:138:in `session'
        5: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:488:in `next_session'
        4: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:186:in `new_session'
        3: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `start'
        2: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh.rb:237:in `new'
        1: from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:56:in `initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/net-ssh-4.2.0/lib/net/ssh/transport/session.rb:90:in `rescue in initialize': Net::SSH::ConnectionTimeout (Net::SSH::ConnectionTimeout)
ERROR: Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout
```
sshd DEBUG3 get no logs.
tcpdump get SYN, SYN ACK and RESET packets only (!) on both sides. May be it's threading issue(?).
script mentioned in #1174  works too.

## NOTE: CHEFDK BUGS ONLY

This issue tracker is for the code contained within this repo -- `chefdk`.

- [Server issues](https://github.com/chef/chef-server/issues/new)
- [Chef-client issues](https://github.com/chef/chef/issues/new)
- Cookbook Issues (see the <https://github.com/chef-cookbooks> repos or search [Supermarket](https://supermarket.chef.io) or GitHub/Google)

**Comment by vsingh-msys** [comment]
Closing for now, feel free to reopen it if you still face the issue. Thanks!
