### ISSUE TITLE
Infra Client Core Resources 2019 H2

### ISSUE THREAD

**Issue by btm** [chef/chef#8734]
- file\_edit: [https://github.com/chef/chef/tree/lcg/file-edit](https://github.com/chef/chef/tree/lcg/file-edit)
- trusted\_certificate: [https://github.com/chef/chef/issues/7861](https://github.com/chef/chef/issues/7861)

Aha! Link: https://chef.aha.io/epics/CHEF-E-52

**Comment by tas50** [comment]
Closing this out since 2019 is over
