### ISSUE TITLE
chef-client STDOUT output with duplicated lines

### ISSUE THREAD

**Issue by grdz** [chef/chef#8745]
## Description
When manually running chef-client with lines like these:

```
log_location '/var/log/logfile.log'
log_level :info 
```

in client.rb, the output on the terminal seems duplicated:

```
  * cookbook_file[/path/to/some/cookbook/file.sh] action create[2019-07-16T08:34:51+02:00] INFO: Processing cookbook_file[/path/to/some/cookbook/file.sh] action create (configs-cl::default line 56)
 (up to date)
  * cookbook_file[/path/to/other/file/something.txt] action create[2019-07-16T08:34:51+02:00] INFO: Processing cookbook_file[/path/to/other/file/something.txt] action create (configs-cl::default line 56)
 (up to date)
  * cookbook_file[/usr/path/example/1.php] action create[2019-07-16T08:34:51+02:00] INFO: Processing cookbook_file[/usr/path/example/1.php] action create (configs-cl::default line 56)
 (up to date)
```

There are lines that should be seen on the screen, the ones without a date (`* cookbook_file`[...]), but they are stuck together with lines that should appear in the `/var/log/logfile.log`, the ones that contain date (starting with `[2019-07-16T`[...]). The log file itself is not affected, only the output on the terminal. There is a workaround - you can set `log_location   STDOUT` in your client.rb, but then you will not get INFO logged into the log file.

## Chef Version
I've seen it in 14.12.3 and 15.1.36 (the error was not present in 14.5.33 on the server with the same configuration)

## Platform Version
CentOS 7.6 (CloudLinux release 7.6)

## Replication Case
Install chef-client 14.12.3 on CentOS 7.6. Make sure that in /etc/chef/client.rb there are lines like these:

```
log_location '/var/log/logfile.log'
log_level :info 
```

then run `chef-client`
## Client Output
Bad output (14.12.3):
```
  * cookbook_file[/path/to/some/cookbook/file.sh] action create[2019-07-16T08:34:51+02:00] INFO: Processing cookbook_file[/path/to/some/cookbook/file.sh] action create (configs-cl::default line 56)
 (up to date)
  * cookbook_file[/path/to/other/file/something.txt] action create[2019-07-16T08:34:51+02:00] INFO: Processing cookbook_file[/path/to/other/file/something.txt] action create (configs-cl::default line 56)
 (up to date)
  * cookbook_file[/usr/path/example/1.php] action create[2019-07-16T08:34:51+02:00] INFO: Processing cookbook_file[/usr/path/example/1.php] action create (configs-cl::default line 56)
 (up to date)
```
Proper output (14.5.33):
```
  * cookbook_file[/path/to/some/cookbook/file.sh] action create (up to date)
  * cookbook_file[/path/to/other/file/something.txt] action create (up to date)
  * cookbook_file[/usr/path/example/1.php] action create (up to date)
```

## Stacktrace
There is no stacktrace

**Comment by lamont-granquist** [comment]
dup of #2931 more or less.

the 14.12.3 output is actually correct.  you should not be using `log_level :info` and should be using `log_level :auto` or `log_level :warn` instead.

there was most likely a bug in 14.5.33 where `:info` output was being suppressed which was fixed at some point.

**Comment by grdz** [comment]
I hope it's not a problem if I will comment on clossed issue.

Using `:auto` fixed problem with double lines as they are not appearing anymore, but then when chef-client is being executed by systemd service, not by interactive terminal, it is not logging anything to log file configured in client.rb.

Is there some proper way to have clean output while executing chef-client manually and logging everything that chef-client does when run by systemd service? I need to get "Running handlers complete" or "Chef Client finished" in log file configured in client.rb for monitoring purposes.
