### ISSUE TITLE
knife bootstrap behavior changed - no longer prompts for password when password not provided

### ISSUE THREAD

**Issue by chadmccune** [chef/chef#8746]
## Description
Before the rewrite, if you didn't provide the password in the bootstrap command, you would be prompted for it.  Now it appears the password parameter is mandatory.

## Chef Version

root@3b0bc4ce587d:/# chef --version
Chef Workstation version: 0.5.1
Chef Infra Client version: 15.1.36
Chef InSpec version: 4.6.9
Test Kitchen version: 2.2.5
Foodcritic version: 16.1.1
Cookstyle version: 5.0.0

## Platform Version
Ubuntu 18.04

## Replication Case
Attempt to bootstrap new windows node from linux node without providing password parameter

## Client Output
ERROR: RuntimeError: password is a required option

**Comment by chadmccune** [comment]
Also, I found this out the hard way...if you mistype said password in the parameter, it just appears to continuously try and locks your domain account out :)

**Comment by mattray** [comment]
ChefDK 3.11.3
```
$ knife bootstrap wernstrom -x pi
Connecting to wernstrom
pi@wernstrom's password:  
```

ChefDK 4.3.13
```
$ knife bootstrap wernstrom -U pi 
Connecting to wernstrom
ERROR: Train::ClientError: Your SSH Agent has no keys added, and you have not specified a password or a key file
```

**Comment by pa-jberanek** [comment]
Getting something which may be related, with Chef Infra Client 15.2.20

`WARN: [SSH] PTY requested: stderr will be merged into stdout
WARN: [SSH] connection failed, terminating (#<Net::SSH::AuthenticationFailed: Authentication failed for user john@server.example.com>)
ERROR: Train::Transports::SSHFailed: SSH session could not be established
`

I'm not prompted for the SSH passphrase...

**Comment by vsingh-msys** [comment]
@pa-jberanek this issue is address in PR https://github.com/chef/chef/pull/8856.

**Comment by mattray** [comment]
I have verified with Workstation 0.15.18 and Chef Client 15.7.32 that this is no longer an issue on MacOS 10.14 and Debian Linux 10.

**Comment by mattray** [comment]
MacOS 10.14: 
```
$ knife --version
Chef Infra Client: 15.8.23
$ knife bootstrap ndnd -U mattray
Connecting to ndnd
WARNING: Failed to authenticate mattray to ndnd - trying password auth
Enter password for mattray@ndnd.
```

Debian Linux 10
```
$ knife --version
Chef Infra Client: 15.8.23
$ knife bootstrap ndnd -U mattray
Connecting to ndnd
WARNING: Failed to authenticate mattray to ndnd - trying password auth
Enter password for mattray@ndnd.
```

**Comment by mattray** [comment]
ChefDK 4.5.0 with Chef 15.4.45 is when the error changed from "ERROR: Train::ClientError: Your SSH Agent has no keys added, and you have not specified a password or a key file" to asking for a password with "knife bootstrap SERVER -U USER"

**Comment by Nareshdevops12** [comment]
root@chef-dk:~/chef-repo# knife bootstrap 10.128.15.202 -x root -P root -N "node2"
-x/--winrm-user: This flag is deprecated. Use -U/--connection-user instead.
Connecting to 10.128.15.202
The authenticity of host '10.128.15.202 ()' can't be established.
WARN: [SSH] connection failed, terminating (#<Net::SSH::AuthenticationFailed: Authentication failed for user root@10.128.15.202>)
ERROR: Train::Transports::SSHFailed: SSH session could not be established

**Comment by vsingh-msys** [comment]
Fixed in https://github.com/chef/chef/pull/9635
