### ISSUE TITLE
metadata 'gem' installer always calls bundle install, even if nothing to do

### ISSUE THREAD

**Issue by jjustice6** [chef/chef#8753]
## Description

https://github.com/chef/chef/blob/master/lib/chef/cookbook/gem_installer.rb

The `gem_installer` code that handles the `gem 'foo'` lines in metadata.rb appears to invoke the dependency resolver on every single Chef run.

We have an artifactory instance which hosts a great many things, Chef invoking bundler in its regular cron job is the single largest load on artifactory.

This will affect anyone who's mirroring rubygems internally, whether using artifactory or some other mirroring software; and may even be a noticeable fraction of the load on rubygems.org due to chef nodes that are set up to use the internet at large.

## Chef Version
14.7.17, code appears to be the same through current master (15.1.54 is the latest version at time of writing).

## Platform Version
It's OS-independent.

## Replication Case
Use [`chef-sugar`](https://github.com/sethvargo/chef-sugar/blob/v5.0.1/metadata.rb) or some other popular cookbook with a `gem` line in metadata.rb, such as [`chef-vault`](https://github.com/chef-cookbooks/chef-vault/blob/v3.1.1/metadata.rb).

## Client Output

Here's an output from a node running a policy with just chef-sugar and chef-vault.

```
---- Begin output of bundle install ----
STDOUT: Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching source index from http://artifactory.CORPORATE.com/artifactory/api/gems/rubygems/
Resolving dependencies...
Using bundler 1.16.1
Using chef-sugar 5.0.1
Using chef-vault 3.4.3
Bundle complete! 2 Gemfile dependencies, 3 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

Notice that neither of these gems have any additional dependencies outside of development, and this happens on _every_ chef run, even though those versions of the relevant gems are already installed.

## Stacktrace

N/A

**Comment by jjustice6** [comment]
One of the things to note about the existing code is it invokes `Dir.mktmpdir` every run; so there's no keeping the Gemfile.lock around currently.

**Comment by jbotelho2-bb** [comment]
Keeping around the `Gemfile.lock` in combination with running bundler in deployment would avoid the resolution on every Chef run. Unfortunately, the `bundle install` command and shell environment seem to be hard-coded currently:

https://github.com/chef/chef/blob/a9c2e4f2f6974b2b9e1c168305b942433d67707f/lib/chef/cookbook/gem_installer.rb#L69

**Comment by lamont-granquist** [comment]
deleting the lockfile and recreating it i think is a deliberate choice.  otherwise you could have a 2 month old stale lockfile that is still pulling down old versions of the gem.  you'd also need to deal with the situation where the cookbooks update and the lockfile becomes out of date with the gemfile itself.

**Comment by jjustice6** [comment]
Agreed, it's got to be something more robust than just keeping the lockfile. Both the examples I reference do not specify a particular gem version, so they're getting the latest gem version (modulo any dependency resolving shenanigans, though for those two gems in particular that shouldn't matter).  I wonder if it's viable to simply check if all gems in the gemfile are the latest version of the gem and if so, don't invoke bundle install; but then there you're still having to query rubygems somehow. It doesn't look like there's a _trivial_ solution, but there's got to be some kind of solution. Maybe the fix actually needs to be in Bundler  to not start depsolving if it's already got everything?

**Comment by joewood** [comment]
Could it only delete the lockfile if it's older than a configured duration?

**Comment by jjustice6** [comment]
Here's an alternative thought process: what if building a policyfile entailed bundling up the specific versions of the gems _as part of the policy_?

That's a bigger change, but I think it'd be semantically quite solid, as now the version of the gem would be explicitly tied to what was tested with that version of the cookbook at policy build time.

**Comment by jjustice6** [comment]
(From there I think you'd need a client.rb option to choose between doing things the current way, and using the metadata gem bundle that comes with the policy, in order to not break existing users/non-policy users. I'm 100% fine with that, myself.)

**Comment by lamont-granquist** [comment]
yeah that's a lot of surgery but that's saner.  so you move the bundle install/update to the client workstation or whatever that generates the policy and the required gem versions are frozen as part of the policy and then the installation of the equality pinned versions happens at runtime.

**Comment by jjustice6** [comment]
Yeah. Does that sound like something we could get on the roadmap? I imagine this is something you'd tie to a major version like 16, but it seems _really_ useful to be able to pin gem versions when building a policy rather than having to rely on cookbook authors to pin them in metadata.rb, which they aren't doing. Right now, in theory chef-sugar could actually induce breakage on a locked policy by removing a function in the gem (as a hypothetical, I don't think kind of breakage would be deliberately induced :) ).

You could even take it to the next level by uploading the gems to the chef server like for cookbooks, and eliminate the need for an external source of gem downloads altogether - even better for airgapped environments.

**Comment by lamont-granquist** [comment]
So the way it was expected that the feature would be used would be that a site would have a wrapper cookbook or even their base role that would also pull in chef-sugar but would pin it via `gem "chef-sugar", "= 1.2.3"` or whatever policy they'd use, and the code which generates the lockfile will de-dup that with the `gem "chef-sugar"` that floats in the chef-sugar cookbook.

And I definitely don't have time to pick this up, so if you're asking me then it probably doesn't get on the roadmap.  It would need to go through as part of a contract to get staffed via teams that handle those kinds of issues.

My reaction though is that this process is starting to feel wrong and the gem metadata approach feels like it has so many edge cases that it shouldn't be used.  Its only really a solution to the chef-sugar and chef-vault use cases and maybe those should just be pulled into core chef rather than needing to do early installation of those gems.

**Comment by jbotelho2-bb** [comment]
@lamont-granquist are you suggesting that the chef-sugar and chef-vault gems could just become dependencies of the main chef gem?

**Comment by jjustice6** [comment]
Here's an idea. How about keeping the lockfile by default, and clearing it if the cookbook cache changes at the start of the run?

If there are no changes to the cookbook cache, the cookbooks are clearly the same, so the older gems should be workable. So, trigger deleting the old lockfile and running bundler fresh when the cookbook cache is known to change at the start of the run. In a Policy or Berks-based environment, that means a new Policyfile or Berksfile has been deployed, which would be a reasonable trigger. In a "cookbooks directly uploaded to the chef server" setup, this means at least one cookbook has been changed.

**Comment by jjustice6** [comment]
It looks like there's been some progress made in #8847 - maybe the options in there can help us out some.

**Comment by jjustice6** [comment]
@lamont-granquist Probably worth revisiting our earlier discussion about building the gems into the policy (and possibly vendoring them like cookbooks) given recent events?

**Comment by lamont-granquist** [comment]
chef-sugar and chef-vault are coming into chef-core and poise and such are dead, so the gem metadata installer itself probably needs to die, this is not going to ever be getting fixed with all those use cases going away.
