### ISSUE TITLE
sudo resource does not check if command aliases are already in use

### ISSUE THREAD

**Issue by drzewiec** [chef/chef#8763]
## Description
The sudo resource (as of chef-client 14.4.56) does not check whether a command alias is already defined before adding it to a file within sudoers.d. This will cause sudo to break, unable to parse the sudoers config.

## Chef Version
14.4.56

## Platform Version
CentOS/RHEL 7

## Replication Case
1. Create a sudo resource in a recipe which defines some command alias along with the user who should run it
2. Make a separate file in sudoers.d which contains the identical Cmnd_Alias to what chef-client will produce in its sudoers.d file
3. Run chef-client
4. Attempt to sudo will fail, as the Cmnd_Alias is duplicated in two files

**Comment by lamont-granquist** [comment]
We should really attempt to validate the sudoers file with the file validator.  Pretty sure sudo has a validation argument.

**Comment by lamont-granquist** [comment]
`visudo --check` possibly, although the file modes check might not work against the tempfile.

**Comment by drzewiec** [comment]
I poked into the code a bit (but haven't had time to write up a possible fix yet), and this is the part which does the actual checking:

https://github.com/chef/chef/blob/a5854d7ae6100a4f4a125d15dbef8fa69ca1cfad/lib/chef/resource/sudo.rb#L162-L192

In particular note lines 169/188 - they have the template resource validating itself with `visudo --check` as you mentioned. The thing that is tricky here is that the current code only validates the single file it is working on at that time (the `-f` parameter), so it doesn't catch a case where the individual sudoers.d file is valid in a vacuum, but causes sudoers to have an overall invalid state.

One idea for how to work around this is to have the resource follow a slightly different workflow when running:

1. Run `visudo -c` to check that the sudoers config currently works
2. Place template and validate the individual template file as it does today
3. Run `visudo -c` again to ensure that sudoers config still works

If step 1 fails you can bail early as sudoers is already broken, if step 2 fails the individual sudoers.d template is bad, and if step 3 fails then you know that the file is good but it conflicts with something in your existing setup (and can roll it back). You could probably simplify it down to just step 3, though, if identifying the different cases isn't really valuable.
