### ISSUE TITLE
When chef-client is run via knife ssh, then we are not being informed about the resource that is executed at present

### ISSUE THREAD

**Issue by grdz** [chef/chef#8778]
## Description
When we run chef-client while being logged into the node, then we could see the name of the resource that is being executed, and action that is being performed ("action run" for example):

```
  * execute[sleep-for-60-seconds] action run
```

and then when it has been executed, we could see a new line, usually green, saying that the resource has actually been executed:

```
  * execute[sleep-for-60-seconds] action run
    - execute sleep 60s
```

But when we run chef-client using knife ssh, then we do not see the first line saying that the resource is being executed right now. We only get it along with the second line, after the resource has been finished executing.

## Chef Version
14.13.11

## Platform Version
CentOS 7.6

## Replication Case
Just set resource like this:

```
execute 'sleep-for-60-seconds' do
  command 'sleep 60s'
  action :run
end
```

and run it on a node via knife ssh like this:

`knife ssh 'name:some-node.com' --ssh-user root -i ~/.ssh/id_rsa 'chef-client' --attribute ipaddress`

You will see that you will not get line saying that this resource is being executed. You don't know what resource is being executed right now, without looking at the recipe code. But while executing chef-client directly on a node, you will first see information that resource execution started, and then after 60 seconds a green line saying that it finished executing, so you know what is being executed right now. Both workstation where knife ssh is being executed, and a node, have `log_level :info` set.

## Client Output
Just as described above

## Stacktrace
There is no stacktrace available

**Comment by lamont-granquist** [comment]
Ultimately this comes down to ssh's buffering, but there's no way to force pty allocation from knife ssh to Net::SSH and it doesn't look like knife ssh supports arbitrary session options Net::SSH.  It would be solvable in .ssh/config, but Net::SSH doesn't know how to parse the RequestTTY option.  more fuel for inspec/train#30

**Comment by tas50** [comment]
Closing this as declined since we can't actually fix this behavior without fundamentally changing how we handle connections.
