### ISSUE TITLE
   SSH session could not be established

### ISSUE THREAD

**Issue by Nara-Sagar** [chef/chef#8792]
![image](https://user-images.githubusercontent.com/48256252/62411102-61e87d80-b60c-11e9-842c-73ff75c25e54.png)
please, anyone, help me I am getting an error while bootstrapping chef node   SSH session could not be established
this error i am getting.

**Comment by vsingh-msys** [comment]
For now, you can use `-U` or `--connection-user` to provide ssh user.

**Comment by Vasu1105** [comment]
@Nara-Sagar Please also provide details of the Chef-Infra version and using verbose mode to give detailed log which will help in resolving issue if any.

**Comment by LemonAndroid** [comment]
@Vasu1105 is there an extremely easy way to post the detailed log here?

**Comment by Vasu1105** [comment]
> @Vasu1105 is there an extremely easy way to post the detailed log here?

@LemonAndroid I am not sure what you are asking for but using -VV option with your command that you are using is the easiest way which I know.

**Comment by LemonAndroid** [comment]
@Vasu1105 ok, and yet I mean even easier. like automatically sending the data on errors. if there are privacy concerns it could be a simple opt-in.

**Comment by Nara-Sagar** [comment]
I have fixed this issue actually I have not mentioned the location of the .pem file hence I am getting this error you can see this in the bootstrap screenshot the actual command  requires -i .\ nodes.pem
Thanks!!
