### ISSUE TITLE
git resource does not clean working directory if there are uncommitted changes

### ISSUE THREAD

**Issue by drzewiec** [chef/chef#8793]
## Description
According to the git resource docs (https://docs.chef.io/resource_git.html), the `:sync` action will hard reset and discard any untracked changes. This is true, but _only_ if there are committed changes locally. Any uncommitted changes will cause the resource to report up-to-date, even though one would expect it to sync the source repository to overwrite those changes.

## Chef Version
14.4.56, but looking at the source code in master this appears to not be fixed even in the latest version.

## Platform Version
Linux

## Replication Case
1. Use git resource to sync some repo to a test machine
2. Make a change to the copy of the repo on the test machine (can be either modifying an existing file or adding a new one)
3. `chef-client` will not do anything to revert those changes, unless you commit them locally

## Relevant Code

https://github.com/chef/chef/blob/fc07ead366d5ef3acd9f7fe3dd36503e5a3ed1c5/lib/chef/provider/git.rb#L94-L106

This code checks `current_revision_matches_target_revision` which is good, but since uncommitted changes don't show up in a `git rev-parse HEAD` (which is how current_revision gets set) they will not trigger this check. Something else needs to be added, perhaps parsing the output of `git status`.

**Comment by lamont-granquist** [comment]
This probably couldn't be the default behavior.  There are likely many people who expect the git checkout to be able to be dirtied after being checked out that this would break.

**Comment by tas50** [comment]
If someone would like to build a property of `reset_hard_before` we'd accept that PR, but this isn't an issue that Chef will be working on directly.
