### ISSUE TITLE
windows_certificate_binding does not bind ssl certificate to the default web site

### ISSUE THREAD

**Issue by ngeegoh** [chef/chef#8797]
### Cookbook version
windows (5.3.1)
### Chef-client version
Chef Workstation version: 0.5.1
Chef Infra Client version: 15.1.36
Chef InSpec version: 4.6.9
Test Kitchen version: 2.2.5
Foodcritic version: 16.1.1
Cookstyle version: 5.0.0
Chef Infra Client version: 15.1.36

### Platform Details
Chef Solo in Windows 2016 Datacentre

### Scenario:
I got this code in my recipe, when I ran it, it did not bind the certificate to the https in "Default Web Site" as expected (it did nothing, but it worked before for some reasons I am not sure). I suspect it might be the windows cookbook bug that causes this issue.

```ruby 
windows_certificate_binding "Bind IIS HTTPS Certificate" do
        action :create
        cert_name "<thumbprint string>"
        name_kind :hash
        address '0.0.0.0'
        port 443
    end
```

### Expected Result:
I tried to remove and add different windows_certificate_binding options but none of them worked. 
I can bind the SSL certificate to https manually and ensure the certificate is in an exportable stage. 

### Actual Result:
It output as success, but nothing actually happened 
```powershell 
* windows_certificate_binding[Bind IIS HTTPS Certificate] action create (up to date)
```

**Comment by tas50** [comment]
@ngeegoh I'm going to close this out since this is actually a bug in the windows cookbook. You'll want to file it there: https://github.com/chef-cookboks/windows

**Comment by ngeegoh** [comment]
Yes, I've created one here https://github.com/chef-cookbooks/windows/issues/614
