### ISSUE TITLE
knife bootstrap now requiring sudo

### ISSUE THREAD

**Issue by robbkidd** [chef/chef#8814]
(opening on behalf of a user in the Community Slack)

## Description

`knife bootstrap` has started requiring `sudo` on the target host. It should not.

## Chef Version

[Reporting user reported](https://chefcommunity.slack.com/archives/CAUSHGN3U/p1565686061027400) Chef 15.2.20.

`sudo` appears to have become a requirement in #8795 (in commit 104f68b71ba523b7fa4e8a6c28a45449a2a67751). 

## Platform Version

Reporting user was targeting a Debian host that does not have `sudo`.

This also affects FreeBSD.

**Comment by vsingh-msys** [comment]
Hi @robbkidd & @tas50 working on it to resolve sudo issue with AIX node as well as part of https://github.com/chef/chef/issues/8764.
Looking for changing the owner without sudo in AIX or for other hosts.

**Comment by KrisShannon** [comment]
@vsingh-msys  If you look at the code before b595d89891d429606b37e2d6ad9bf99cabd473ec you can see it uses two separate calls to `run_command!`

Does it work on AIX if you do that?

e.g.  something like:
```
cmd = "mkdir -p %s" % dir
run_command!(cmd)
cmd = "chown #{config[:user]} '#{dir}'"
run_command!(cmd)
```

**Comment by vsingh-msys** [comment]
@KrisShannon Above code fails if we provide `--sudo` options because dir created with root privilege.

Provided fix #8815 which will work for all host.

Thanks!

**Comment by zedtux** [comment]
Thank you @robbkidd 👍

**Comment by vsingh-msys** [comment]
Fixed in https://github.com/chef/chef/pull/8815
