### ISSUE TITLE
Subscribe should be able to listen to attributes

### ISSUE THREAD

**Issue by dbeezt** [chef/chef#8822]
### Describe the Enhancement:
I'm implementing a service resource that subscribes to a number of changing files, but I couldn't help that one of these files has a doppelgänger attribute that if changed would warrant a similar action trigger.

### Describe the Need:
It's not an essential enhancement at all, but it's a little bit of added functionality that might suit some users better than the default behaviour of only listening for changing resources. I believe it would be applicable to all users involved in service provision/management.

### Current Alternative
Yes, can easily use the current default behaviour of listening to a resource.

### Can We Help You Implement This?:
Yes, let me know if it's worth an implementation.

**Comment by tas50** [comment]
@dbeezt Can you provide some more detailed examples of exactly what you're trying to accomplish. We're a bit confused on what the requested functionality is.

**Comment by lamont-granquist** [comment]
Closing due to lack of response.
