### ISSUE TITLE
Integrate windows_user_privilege in chef core

### ISSUE THREAD

**Issue by Annih** [chef/chef#8853]
### Core Chef Resource Checklist

Before suggesting a resource for inclusion please make sure your suggestion meets these criteria for resources built into Chef:
 - [ ] Automates an operating system component that ships by default on systems such as authentication, raid, disk partitions, firewalls, containers, or virtualization systems.
 - [ ] Does not attempt automate 3rd party applications such as database, web, or application servers, which are best suited for cookbooks due to their fast moving nature.

### Describe the resource:
The `windows_user_privilege` adds the `principal` (User/Group) to the specified privileges (such as `Logon as a batch job` or `Logon as a Service`).

### Why should this be included out of the box?:
* Automating windows servers frequently requires that you edit account privileges, to setup services or schedule tasks for instances.
* When you want to setup a simple cron task on linux you don't need to include the "linux" cookbook, it's a pain to have to include "windows" on windows for such a trivial thing.
* The base libaries used in the implementation are located in Chef core, it would make sens to have the resource implementation at the same place
* Windows Services reimplement this resource to grant `SeServiceLoginRight`, it could be refactored to take advantage of this new resource.

### What operating systems would it run on?
Windows only

### Current cookbook implementation:
https://github.com/chef-cookbooks/windows

### Can We Help You Implement This?:
I'm OK to move the code as it, this is trivial, but should I:
- change the copyrights
- add chefspecs (there is none in in windows cookbook)

**Comment by btm** [comment]
@Annih we wouldn't remove any copyrights when copying code across, only add additional ones if we made significant changes are part of the move. that said, I don't see a copyright on that file in the windows cookbook, just an author line which I would treat the same way.

We should add a functional test (`spec/functional/resource`) though.

I wondered a bit about adding `privilege` property to the existing `windows_user` resource.

```
windows_user  'Administrator' do
  privilege %w(SeBatchLogonRight SeServiceLogonRight)
  action :modify
end
```

Although the existing actions wouldn't give you the ability to add or remove specific privileges, only explicitly set all of them.

**Comment by Vasu1105** [comment]
This is in progress with #9279

**Comment by tas50** [comment]
This is merged into master for Chef Infra Client 16
