### ISSUE TITLE
Remove chef bootstrap script from command line / ps output

### ISSUE THREAD

**Issue by btm** [chef/chef#8859]
When bootstrapping in Chef Infra 15, the chef-full script is now run through train, for the most part fixing #3871. However https://github.com/chef/chef/blob/master/lib/chef/knife/bootstrap/templates/chef-full.erb still is wrapped by a `sh -c '... '` block which means the contents end up in ps output.

We should be able to simply remove that block from the template, but will need to test and verify tests.

**Comment by lamont-granquist** [comment]
#8885 fixed
