### ISSUE TITLE
`bundle install` not working on chef 12-15 on Ubuntu 18.04

### ISSUE THREAD

**Issue by timvisher** [chef/chef#8918]
## Description
`bundle install` can't work on Ubuntu 18.04 in any version of chef after chef installs a chef gem during the pre-compile phase.

## Chef Version
12-15

## Platform Version
Ubuntu 18.04

## Replication Case
https://github.com/timvisher/temp_bundler_1804

## Client Output
See https://github.com/timvisher/temp_bundler_1804

## Stacktrace
See https://github.com/timvisher/temp_bundler_1804

```
.kitchen.kitchen-chef12.yml/logs/kitchen.log:>>>>>>     Converge failed on instance <test-vagrant-1804>.  Please see .kitchen/logs/test-vagrant-1804.log for more details
.kitchen.kitchen-chef12.yml/logs/kitchen.log:>>>>>>     Converge failed on instance <test-ubuntu-1804>.  Please see .kitchen/logs/test-ubuntu-1804.log for more details
.kitchen.kitchen-chef13.yml/logs/kitchen.log:>>>>>>     Converge failed on instance <test-vagrant-1804>.  Please see .kitchen/logs/test-vagrant-1804.log for more details
.kitchen.kitchen-chef13.yml/logs/kitchen.log:>>>>>>     Converge failed on instance <test-ubuntu-1804>.  Please see .kitchen/logs/test-ubuntu-1804.log for more details
.kitchen.kitchen-chef14.yml/logs/kitchen.log:>>>>>>     Converge failed on instance <test-ubuntu-1804>.  Please see .kitchen/logs/test-ubuntu-1804.log for more details
.kitchen.kitchen-chef14.yml/logs/kitchen.log:>>>>>>     Converge failed on instance <test-vagrant-1804>.  Please see .kitchen/logs/test-vagrant-1804.log for more details
.kitchen.kitchen-chef15.yml/logs/kitchen.log:>>>>>>     Converge failed on instance <test-ubuntu-1804>.  Please see .kitchen/logs/test-ubuntu-1804.log for more details
.kitchen.kitchen-chef15.yml/logs/kitchen.log:>>>>>>     Converge failed on instance <test-vagrant-1804>.  Please see .kitchen/logs/test-vagrant-1804.log for more details
```

**Comment by lamont-granquist** [comment]
This is a bug against bento isn't it?

**Comment by timvisher** [comment]
I don't think so given that it's replicable across both bento and stock ubuntu 18.04 images.

**Comment by lamont-granquist** [comment]
Oh so this is that the gem metadata installer is picking up the $HOME and writing to /home/vagrant/.bundle as root then you're switching to the vagrant user?  That still kind of feels like $HOME/$USER/etc shouldn't be pointing to vagrant's user when running as root because that is going to cause these kinds of problems.

**Comment by timvisher** [comment]
@lamont-granquist Sure? It's very easy to reproduce in that project. Maybe I have something misconfigured? Like I said it works on 14.04 and 16.04 though across all chef versions tested.

**Comment by lamont-granquist** [comment]
Yeah the fact that you flip the switch from 14.04/16.04 to 18.04 suggests that this is something to do with the 18.04 bento package and nothing to do with code in this repo...

**Comment by lamont-granquist** [comment]
closing this as it doesn't seem actionable, and the direction we're going to go is deprecating the gem metadata installer
