### ISSUE TITLE
Add more platform matchers to core

### ISSUE THREAD

**Issue by btm** [chef/chef#8919]
Add additional platform helpers to core Chef to provide users with helpers that more specifically match their requirements. The chef-sugar cookbook has provided information in the past as to useful helpers which have made their way into core.

Where possible and applicable implement in such a way that chef-sugar users could begin using core helpers with minimal cookbook code changes.

[RFC-087](https://github.com/chef-boneyard/chef-rfc/blob/master/rfc087-distro-sugar-helpers.md) is a guide for this work.

**Comment by lamont-granquist** [comment]
#8920 and #8922
