### ISSUE TITLE
Release chef-14 branch to resolve regression in chef_gem usage

### ISSUE THREAD

**Issue by tas50** [chef/chef#8982]
Chef 14.14.14 introduced a regression in chef-14 that broke installation of gems via chef_gem. We need to release the current contents of the chef-14 branch

- [x] Get a build out via Buildkite
- [x] Write basic release notes
- [x] Promote
- [ ] Announce on discourse

**Comment by bgs113** [comment]
We're seeing the issue on 14.14.14 with gem installs included through metadata.rb, for example:

`gem 'oauth2', '~> 1.4.1'`

However, installing the same gem in a recipe with the chef_gem resource ran successfully.

**Comment by tas50** [comment]
@bgs113 that'll be resolved

**Comment by tas50** [comment]
@christopher-snapp did this this morning
