### ISSUE TITLE
This installation package could not be opened.  Contact the application vendor to verify that this is a valid Windows Installer package.

### ISSUE THREAD

**Issue by DarrenV79** [chef/chef#8985]
## Description
Chef fails to install the windows msi.  Claims that it is invalid.  Looking at the downloaded file it is zero (0) bytes in size.  This happens 9/10 times.  Sometimes its totally fine.  I have network connections on every instance I try this on (AWS).  AMI's used hasn't changed in over a month.  The only assumption I have is that https://www.chef.io/chef/download?p=windows&pv=2016&m=x86_64&DownloadContext=PowerShell&v=14.13.11 is unable to serve the file sometimes.

If this is just a problem with the endpoint not able to serve this file the output should indicate this rather than try and continue with a failed file.  

## Chef Version
14.13.11

## Platform Version
Windows 2019 (Core and Standard)

## Replication Case
Try and install

## Client Output

Detected Windows Version 10.0 Build 17763
C:\Users\Administrator>goto Version10.0
C:\Users\Administrator>goto architecture_select
C:\Users\Administrator>IF "AMD64" == "x86" IF not defined PROCESSOR_ARCHITEW6432
C:\Users\Administrator>goto install
Checking for existing downloaded package at "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
Found existing downloaded package, deleting.
Attempting to download client package using PowerShell if available...
powershell.exe -ExecutionPolicy Unrestricted -InputFormat None -NoProfile -NonInteractive -File  C:\chef\wget.ps1 "https://www.chef.io/chef/download?p=windows&pv=2016&m=x86_64&DownloadContext=PowerShell&v=14.13.11" "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
Download via PowerShell succeeded.
Installing downloaded client package...

C:\Users\Administrator>msiexec /qn /log "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-msi13689.log" /i "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
This installation package could not be opened.  Contact the application vendor to verify that this is a valid Windows Installer package.

WARNING: Failed to install Chef Client MSI package in remote context with status code 1620.
WARNING: This may be due to a defect in operating system update KB2918614: http://support.microsoft.com/kb/2918614
WARNING: Task may not run because /ST is earlier than current time.

**Comment by lamont-granquist** [comment]
not clear where the code is that is causing the issue or what the context is.
