### ISSUE TITLE
yum_package resource only installs/check first package from multiple package list and when arch attribute is set

### ISSUE THREAD

**Issue by bipinbachhao-lilly** [chef/chef#8991]
## Description

I have a yum_package resource installing a half dozen packages with the i686 architecture on an x86_64 machine, have action as upgrade or install.

Trying to install package by provide list to yum_package resource, yum_package resource only installs only first package from the list and report all other as up to date where as they are not installed.

## Chef Version
 14.11.21 tried on Chef Infra Client: 15.2.20 same behaviour 

## Platform Version
RHEL 7 and Centos 7

## Replication Case

yum_package %w(libpng libXrandr libXcursor libXinerama) do
  arch 'i686'
  action :install
end

yum_package %w[compat-libf2c-34 compat-libstdc++-33] do
  arch 'i686'
  action :upgrade
end

This will only install libpng and upgrade compat-libf2c-34 and will not install or upgrade any others from the list

Where as if i do will install all the packages

['libpng', 'libXrandr', 'libXcursor', 'libXinerama'].each do |p|
  yum_package p do
    arch 'i686'
    action :install
  end
end

**Comment by lamont-granquist** [comment]
you should use either the arch in the name (which is preferable):

```
yum_package %w[compat-libf2c-34.i686 compat-libstdc++-33.i686]
```

or else the arch as a property (which is discouraged and may lead to other bugs):

```
yum_package %w[compat-libf2c-34 compat-libstdc++-33] do
arch %w[i686 i686]
action :upgrade
end
```
