### ISSUE TITLE
sudo resource fails on 2nd converge when Cmnd_Alias is used

### ISSUE THREAD

**Issue by Rudikza** [chef/chef#9001]
## Description
When testing with chef 15.4.45 and running multiple converges, using the sudo resource with a  Cmnd_Alias the second converge fails due to the following error:

```
           Chef::Exceptions::ValidationFailed
           ----------------------------------
           template[/etc/sudoers.d/sudoreplay] (/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45/lib/chef/resource/sudo.rb line 165) had an error: Chef::Exceptions::ValidationFailed: Proposed content for /etc/sudoers.d/sudoreplay failed verification cat /etc/sudoers %{path} | /usr/sbin/visudo -cf -
```
The second converge does not fail when using chef version 15.3.14.

As far as I can tell the issue is that when concating the `/etc/sudoers` file and the `/etc/sudoers.d/other_sudo` file the file in /etc/sudoers.d/ is called twice because of the include in `/etc/sudoers`.

## Chef Version
15.4.45

## Platform Version
Centos 7

## Replication Case

Create a cookbook, add a sudo resource which creates a new sudoers entry that includes a cmnd_aliases. Run multiple converges.

I've created a basic repo where the issue can be replicated by changing the chef version in the kitchen.yml file: https://github.com/Rudikza/test-sudo.git

## Client Output

https://gist.github.com/Rudikza/1cb89e20d2080d90dc720b32f26bf8fc

**Comment by fretb** [comment]
Wondering how this can be fixed without reverting to the previous verify command... Excluding all `includedir`'s from /etc/sudoers, adding all files in those `includedir`'s files to the `cat` command, but excluding the file's path that's being verified?

**Comment by fretb** [comment]
I'm afraid this will have to be reopened, as the merged code creates a new problem:

```
1214            Chef::Exceptions::ValidationFailed
1215            ----------------------------------
1216            sudo[cmbmonit_check_procs-sre] (/var/tmp/kitchen/cache/cookbooks/monitoring/resources/nrpe.rb line 91) had an error: Chef::Exceptions::ValidationFailed: template[/etc/sudoers.d/cmbmonit_check_procs-sre] (/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.7.14/lib/chef/resource/sudo.rb line 174) had an error: Chef::Exceptions::ValidationFailed: Proposed content for /etc/sudoers.d/cmbmonit_check_procs-sre failed verification cat /etc/sudoers %{path} | /usr/sbin/visudo -cf -
1217            STDOUT: 
1218            STDERR: visudo: unable to open -: No such file or directory
```
