### ISSUE TITLE
Move the chocolatey config directly into this repo

### ISSUE THREAD

**Issue by tas50** [chef/chef#9023]
### Describe the Enhancement:
Move the chocolatey config to this repo and handle promotions of those packages just like any other package.

### Describe the Need:
We want to make sure as soon as we promote Chef Infra Client that we publish the new version to chocolatey.org without a person having to do it by hand. It's basically the only by hand action in the Chef release at this point other than the overall announcement and only a few people even have permission to do it.

**Comment by robbkidd** [comment]
Another option for automated choco publishing could be to wire up https://github.com/chef/chocolatey-packages with expeditor subscriptions to omnibus packages getting promoted to stable to trigger expeditor performing a scripted update to the files there and having _that_ repo do the publish. I haven't thought deeply yet about the trade-offs between these two options, though.

**Comment by robbkidd** [comment]
🤔 🤔 🤔 🤔 

Though, as you said, there's something to be said for `chef/chef` owning the destiny of all its artifacts.

**Comment by tas50** [comment]
Nope. Chocolatey packages are still produced and pushed manually for this repo.

**Comment by gep13** [comment]
@tas50 anything that we can do to help with this?

**Comment by tas50** [comment]
It's all kinda on our side. We were doing workstation first and that kept blowing up for a number of different reasons. I think now it's just the large package size, which it sounds like we just have to live with. Setting up the same automation on this repo is just a matter of priority.

**Comment by gep13** [comment]
The larger package size, and the need for manual exemption is something that we want to get fixed, just need to get to that. In the interim, you can pre-upload the binaries to virus total which would help with the package scanner process.

**Comment by tas50** [comment]
Replacing with https://chefio.atlassian.net/browse/IPACK-68
