### ISSUE TITLE
chef_version metadata violation raises incorrect error

### ISSUE THREAD

**Issue by kimbernator** [chef/chef#9038]
## Description
If a run-list includes a cookbook with a chef_version constraint that is not permissive of the version of chef infra client running, the error raised is incorrect due to an error in the code to finalize the run with an end message:

```
Running handlers:
[2019-10-31T13:22:15-05:00] ERROR: Running exception handlers
Running handlers complete
[2019-10-31T13:22:15-05:00] ERROR: Exception handlers complete
Chef Infra Client failed. 0 resources updated in 10 seconds
[2019-10-31T13:22:15-05:00] FATAL: NoMethodError: undefined method `filtered_collection' for nil:NilClass
```

Running `chef-client -l trace` reveals an attempt at re-raising the correct error, which is:

```
[2019-10-31T13:22:15-05:00] TRACE: Re-raising exception: Chef::Exceptions::CookbookChefVersionMismatch - Cookbook '<cookbook_name>' version '0.5.0' depends on chef version [">= 12.14", "< 15"], but the running chef version is 15.4.45
```

In these lines: https://github.com/chef/chef/blob/b499e050480780dcd2f8d30fa3a83374ba879b40/lib/chef/client.rb#L303-L317

The exception is re-raised in a trace log, but line 308's `run_failed` call experiences its own error which is unhandled and results in all code until `ensure` (lines 310-312) not being executed and the `CookbookChefVersionMismatch` not being raised.  

The unhandled error occurs when formatting the run ending message as a result of the `updated_resources` method in chef/resource_reporter.rb: 
https://github.com/chef/chef/blob/b499e050480780dcd2f8d30fa3a83374ba879b40/lib/chef/resource_reporter.rb#L184-L187

Changing line 186 to the following results in a chef-client failure that includes the more useful CookbookChefVersionMismatch error:
```
@updated_resources ||= action_collection&.filtered_collection(max_nesting: 0, up_to_date: false, skipped: false, unprocessed: false) || {}
```
(Changes being the `&` after `action_collection` to return nil instead of throwing a NoMethodError, and `|| {}` at the end to assign `{}` to `@updated_resources`)

I am hesitant to submit a PR with this change since it feels like a cheap hack to resolve one specific error without addressing the fact that `@action_collection` is not being defined early enough for this error to be properly raised.

## Chef Version
15.4.45

## Platform Version
RHEL 6 and Windows Server 2008R2

## Replication Case
Include a cookbook with chef_version constraints in metadata.rb that exclude the chef-client version running. Make sure cookbook synchronization is not disabled. No policy files.

## Client Output
Included in description

## Stacktrace
N/A

**Comment by lamont-granquist** [comment]
thats the correct fix, can you submit the PR?
