### ISSUE TITLE
Windows performance profiling

### ISSUE THREAD

**Issue by robbkidd** [chef/chef#9076]
Where's all the IO coming from, yo?

Update this with our plan and learnings for profiling Windows performance.

**Comment by lamont-granquist** [comment]
So I did a bunch of work on this with simple timing on windows/unix awhile back and strace on unix.  That led to:

https://github.com/rubygems/rubygems/issues/2762

Which led to:

https://bugs.ruby-lang.org/issues/15856

Which led to:

https://github.com/chef/omnibus-software/pull/1113

**Comment by lamont-granquist** [comment]
I also found that stat-vs-open doesn't make much of a different on either windows or unix.  I don't know why ruby tends to use `open` rather than `stat` to check if a file exists, i suspect that helps with resolving complicated acl issues so that you validate that it both exists and is readable at the same time.  Either way it seems to not make a difference.

**Comment by lamont-granquist** [comment]
And on unix what I've mostly done is just:

```bash
time /opt/chef/bin/chef-client
strace -c /opt/chef/bin/chef-client
strace trace=open,stat /opt/chef/bin/chef-client
```

**Comment by lamont-granquist** [comment]
And the top calls typically looks like this:

```
Chef Infra Client: 15.0.276
/opt/chef/bin/chef-client --version  2.43s user 0.90s system 83% cpu 4.011 total

% strace -f -c /opt/chef/bin/chef-client --version
strace: Process 44180 attached
Chef Infra Client: 15.0.276
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 47.55    0.360709           3    138777    134075 stat
 39.71    0.301194           3    105846    102814 open
  5.87    0.044508           2     18266           lstat
```

100,000-ish stat+open calls is typical.

So the TL;DR of fixing it looks like:

1.  investigate how to make all that I/O go away entirely
2.  investigate why that I/O is so slow on windows in particular (and maybe our way of building windows in particular?)

**Comment by lamont-granquist** [comment]
Using RubyInstaller 2.6.5p114 with non-appbundled chef-client binstub:

2.96 2.98 2.91 2.88

Using RubyInstaller 2.6.5p114 with appbundled chef-client binstubs:

3.14 3.25 3.17 3.36

**Comment by lamont-granquist** [comment]
Chef 15.4.45 with non-appbundled chef-client binstubs:

4.15 4.42 4.21 4.09

Chef 15.4.45 with appbundled chef-client binstubs:

4.27 3.98 4.14 4.23

**Comment by lamont-granquist** [comment]
So 22% speed improvement from using RubyInstaller over our homegrown builds

**Comment by lamont-granquist** [comment]
Chef 15.5.4 performance with appbundled chef-client binstubs (chef-client --version timing):

3.77 3.62 3.56 3.91 = 3.7150 seconds

Compared to the prior 4.15500 seconds, so 10% net speedup between the -O2 to -O3 fix and the patch to ruby

**Comment by tas50** [comment]
This part of the project is complete
