### ISSUE TITLE
Chef::Config[:cache_path] should default to C:\chef on windows

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#9094]
I don't think it currently does?

https://github.com/chef/chef/blob/8a7e29d52882c39d0c903eef83bd3472e4f334af/chef-config/lib/chef-config/config.rb#L281-L302

Most windows users must be getting this setting from the chef-client cookbook?

https://github.com/chef-cookbooks/chef-client/blob/517e866e6aa2154663087e33a14cceddeec5e287/attributes/default.rb#L163

**Comment by snehaldwivedi** [comment]
@lamont-granquist I think this will now be cover in #9094

**Comment by snehaldwivedi** [comment]
Fixed by #11592
