### ISSUE TITLE
Creating new user with mac_user on chef-client 15.4.45 client throws a NilClass error. 

### ISSUE THREAD

**Issue by johnmccrae** [chef/chef#9109]
## Description
Facebook reports a NilClient error creating a user resource. Below is my repro of the error. 

## Chef Version
    System Info:
    ------------
    chef_version=15.4.45
    platform=mac_os_x
    platform_version=10.15.1
    ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin17]
    program_name=/opt/chef-workstation/bin/chef-client
    executable=/opt/chef-workstation/bin/chef-client

## Platform Version
Mac OSX 10.15.1

## Replication Case
1. build a cookbook called whatever (I used cpe_test).
2. the cookbook should have one recipe in it.
3. that recipe should look like this:
```ruby
user 'fooadmin' do

end
```
4. Now run sudo chef-client -z -o cpe_test
5. You get a NilClass error

## Client Output

```
Recipe: cpe_test::default
  * mac_user[fooadmin] action create
    - create user
    ================================================================================
    Error executing action `create` on resource 'mac_user[fooadmin]'
    ================================================================================
    
    NoMethodError
    -------------
    undefined method `[]' for nil:NilClass
    
    Resource Declaration:
    ---------------------
    # In /Users/johnmccrae/.chef/local-mode-cache/cache/cookbooks/cpe_test/recipes/default.rb
    
      1: user 'fooadmin' do
      2: 
      3: end
    
    Compiled Resource:
    ------------------
    # Declared in /Users/johnmccrae/.chef/local-mode-cache/cache/cookbooks/cpe_test/recipes/default.rb:1:in `from_file'
    
    mac_user("fooadmin") do
      action [:create]
      default_guard_interpreter :default
      declared_type :user
      cookbook_name "cpe_test"
      recipe_name "default"
      username "fooadmin"
      home "/Users/fooadmin"
    end
    
    System Info:
    ------------
    chef_version=15.4.45
    platform=mac_os_x
    platform_version=10.15.1
    ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin17]
    program_name=/opt/chef-workstation/bin/chef-client
    executable=/opt/chef-workstation/bin/chef-client
```

## Stacktrace
https://gist.github.com/johnmccrae/1adaca34434034c9baa9057d1523cfe5

**Comment by johnmccrae** [comment]
The bug also repros on the 15.5.9 client as well.

**Comment by johnmccrae** [comment]
Second update. If you look through the local users list in System Preferences after you run the code sample, you'll see that it actually created the user but you can't set most attributes after the fact and if you set a password you can't read the user?

**Comment by lamont-granquist** [comment]
Looks like dscl is just broken in macos >= 10.15 and we have no workaround and don't know how to patch this.

See:

https://forums.developer.apple.com/thread/120437

**Comment by lamont-granquist** [comment]
Okay looks like that may have been fixed in 10.15.1 (or maybe .0 as well) and that has nothing to do with this bug.

**Comment by lamont-granquist** [comment]
It has something to do with ShadowHashData not existing for the user.  Once I start to fix issues around that being nil I hit errors where https://github.com/macmule/ADPassMon/issues/93 might be related.

**Comment by lamont-granquist** [comment]
somewhat hopeful that #9158 fixes this.

if people still find this bug in wild please open a new issue.
