### ISSUE TITLE
Inspec testing for the test-kitchen tests

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#9115]
We need some bare minimum inspec verifiers written around the kitchen-tests in this repo.

Came up when build_essential failed silently, we could be checking that we get appropriate compilers and stuff on platforms that it works on.

I think I tried to do this ages ago but, i think, we were stuck on an old version of kitchen-dokken due to the need to hack up the kitchen.yml with kitchen-appbundle-updater -- and that old version of kitchen-dokken was buggy and did not support inspec.  But now with kitchen-appbundle-updater being replaced by lifecycle hooks, and kitchen-dokken being updated, we should be no longer blocked?

**Comment by tas50** [comment]
We have our first here to validate that inspec itself runs: https://github.com/chef/chef/blob/master/kitchen-tests/test/integration/end-to-end/_chef_client_config.rb
