### ISSUE TITLE
gem_package doesn't correctly install gems

### ISSUE THREAD

**Issue by fasmat** [chef/chef#9118]
## Description
Using ``gem_package`` to install gems causes them to be installed in the embedded environment of chef workstation, but not globally.

## Chef Version
Chef workstation 0.11.21

## Platform Version
Ubuntu 18.04 with Ruby 2.5.1 (from official repositories)

## Replication Case
In one of my recipes i install the solargraph gem with the following code snippet:

```ruby
gem_package "solargraph" do
  version "~>0.34"
  action :install
end
```

## Client Output
```
...
 * gem_package[solargraph] action install (up to date)
...
```

Calling ``gem list`` will not list the gem as being installed, unless I first call ``eval "$(chef shell-init bash)"``, then the gem will be listed (among many more that are not listed without using chef shell-init).

**Comment by bobchaos** [comment]
The gem binary that is detected by default is found in `$PATH` + `RbConfig::CONFIG["bindir"]`. 
See here: https://github.com/chef/chef/blob/9009b12f14272522c08b2d19c94ae3e418867f56/lib/chef/provider/package/rubygems.rb#L436
and here: https://github.com/chef/chef/blob/9009b12f14272522c08b2d19c94ae3e418867f56/chef-utils/lib/chef-utils/dsl/which.rb#L51
If you're interested in the details.

What values do you have for $PATH and `RbConfig::CONFIG["bindir"]` during your Chef runs? How is your recipe being executed? chef-apply, chef-client, chef-zero?

As a workaround, you can explicitly set `gem_binary` in your resource declaration to target the correct file, or even add your own bin search logic.

**Comment by fasmat** [comment]
Thanks for the tip to use `gem_binary`! I now set the path to my system gem binary (`/usr/bin/gem`) and chef installs the gems correctly. For some reason it would always use the gem binary of the embedded ruby before. This fix works for me.

In case someone wants to dig deeper when they stumble upon the same issue:
* I was using chef-client from chef-workstation 0.11.21
* Ubuntu 18.04.3 with ruby from the official repositories
* Relevant environment variables during the chef run (as set by ``chef shell-init bash``): 
```
PATH="/opt/chef-workstation/bin:/home/vagrant/.chefdk/gem/ruby/2.6.0/bin:/opt/chef-workstation/embedded/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/adr/src:/usr/local/adr/src:/usr/local/adr/src:/home/vagrant/go/bin:/opt/chef-workstation/gitbin"
GEM_ROOT="/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0"
GEM_HOME="/home/vagrant/.chefdk/gem/ruby/2.6.0"
GEM_PATH="/home/vagrant/.chefdk/gem/ruby/2.6.0:/opt/chef-workstation/embedded/lib/ruby/gems/2.6.0"
```
