### ISSUE TITLE
End the formatter and logger confusion and have the formatter output log messages

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#9126]
For Chef-16 we should have the formatter output logger warnings through events and turn off the logger by default, and have logger-vs-formatter be an either-or setting and stop allowing the formatter and logger to run at the same time.

Several closed issues referenced below are still relevant and are rolled up under solving this issue.

The default behavior should be to use the formatter.  If a user sends the output to a -L logfile then the formatter output should go to the log file and not the output to stdout.

We may need to deprecate the setting of log_location in the config.rb as something that nobody should be doing (so that log_location is not forced to the /var/log output file for command line usage, and that the -L option should be used from systemd/cron/whatever instead by daemon processes).  As a stretch goal we might still support cloning the output to STDOUT when on a tty if the logic can be made simple enough to not be the buggy mess that we've had to deal with.  I don't mind that as a use case, but its implementation has been a disaster.

Using --force-logger should turn off the formatter and turn on the logger and that should just be what you get.  If there's any STDOUT cloning then either the formatter goes to both places or the logger goes to both places, and we don't ever cross the streams.  The ability have pretty formatter output to users and logger output to syslog is going to go away permanently.  For those affected users, they should really setup better systems involving the data collector to gather and parse output.

**Comment by lamont-granquist** [comment]
So design:

- move the responsibility of the logger + event system initialization earlier in the run from Chef::Client to the Chef::Application

- move the `log_location` cli argument to a `log_location_cli` argument and keep it separate from the `log_location` in the chef config

- set the default config `log_location` to nil

- combine the log_location with the log_location_cli to form an array of log_locations.

- if any of the log_locations are STDOUT and STDOUT is closed, then remove them (this replaces magical STDOUT-is-a-tty logic with its much simpler inverse to just close STDOUT logging if we're daemonized and have no STDOUT)

- remove any dups in the list after combining them

- have Chef::Log when we're in formatter mode wired up to a logger which sends messages to the event system instead of printing them out.

- fix up references in Ohai to Ohai::Log.XXXX to use logger.XXXX and/or to inject the logger into the Ohai::Log global correctly

What this should achieve:

- No double logging to STDOUT

- No need to de-duplicate STDOUT != STDOUT

- De-duplication based on the filesystem path

- Users that specify a log_location in the config.rb get both daemonized and CLI chef-client runs logging to that location

- Open Question:  How to ensure the formatter outputs to all the log_locations correctly?  Or does it do that already?

I think this keeps most everyone happy other than people mucking about too much in the Chef internals.

**Comment by josegonzalez** [comment]
@lamont-granquist #2931 is still locked.

**Comment by lamont-granquist** [comment]
I think I'm going to declare victory here and #2931 is better for tracking the issue of having the formatter natively handle syslog log lines better and fix the wonky formatting

**Comment by HarshRajIN** [comment]
With this change, the logs are no more getting written to the console if we are passing --logfile/-L option. This was a breaking change for me as I was no more getting logs output in the jenkins console (I am calling chef-client using powershell script in my jenkins jobs).
@lamont-granquist has mentioned above- 

> As a stretch goal we might still support cloning the output to STDOUT when on a tty if the logic can be made simple enough to not be the buggy mess that we've had to deal with.

Looks like this is not implemented yet.
