### ISSUE TITLE
chocolatey_package unable to find SSRS package

### ISSUE THREAD

**Issue by Kundan22** [chef/chef#9161]
## Description

I have a cookbook which installs SSRS 2017 using `chocolatey_package` but it fails with error "* No candidate version available for ssrs".

However this was working fine till now and works for other packages and also command `choco install ssrs --version=14.0.600.1109` is running correctly on same machine

Can someone please look into this issue?

```
chocolatey_package("ssrs") do
  package_name ["ssrs"]
  action [:install]
  default_guard_interpreter :default
  declared_type :chocolatey_package
  cookbook_name "dev-ssrs"
  recipe_name "default"
  version ["14.0.600.1274"]
  options "--ignore-checksums"
end
```

## Chef Version
Chef Infra Client: 15.1.36

## Platform Version
Windows Server: 2016

## Client Output

* No candidate version available for ssrs
================================================================
Error executing action `install` on resource 'chocolatey_package[ssrs]'
================================================================

Running handlers:
[2019-12-13T17:06:40+01:00] ERROR: Running exception handlers
Running handlers complete
[2019-12-13T17:06:40+01:00] ERROR: Exception handlers complete
Chef Infra Client failed. 2 resources updated in 33 seconds
[2019-12-13T17:06:40+01:00] ERROR: Failed to post reporting data to server (HTTP 400), saving to c:/chef/cache/failed-re
porting-data.json
[2019-12-13T17:06:40+01:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
[2019-12-13T17:06:40+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2019-12-13T17:06:40+01:00] FATAL: Chef::Exceptions::Package: chocolatey_package[ssrs] (dev-ssrs::default line 6) had an
 error: Chef::Exceptions::Package: No candidate version available for ssrs

```

```

**Comment by vsingh-msys** [comment]
Hey @Kundan22 thanks for reporting the issue. seems that this issue we addressed already and fixes available in  v15.6.13 & higher version.

So could you please update your Chef Infra Client to  v15.6.13 or the latest version?

**Comment by Kundan22** [comment]
@vsingh-msys can you give more details about the issue that you fixed? what was the issue and what is fixed in latest version?

upgrading to latest version v15.6.13 throws different error now and I am getting following error in windows_share 


> FrozenError
> -----------
> can't modify frozen String
> 
> System Info:
> ------------
> chef_version=15.6.10
> platform=windows
> platform_version=10.0.14393
> ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]
> program_name=C:/opscode/chef/bin/chef-client
> executable=C:/opscode/chef/bin/chef-client
> 
> 
> Running handlers:
> [2019-12-15T09:07:23+01:00] ERROR: Running exception handlers
> Running handlers complete
> [2019-12-15T09:07:23+01:00] ERROR: Exception handlers complete
> Chef Infra Client failed. 0 resources updated in 22 seconds
> [2019-12-15T09:07:24+01:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
> [2019-12-15T09:07:24+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
> [2019-12-15T09:07:24+01:00] FATAL: FrozenError: can't modify frozen String


```
windows_share 'AppConfig' do
  action :nothing
  path <Value from Attribute Here>
  full_users <Value from Attribute Here>
end
```

**Comment by Kundan22** [comment]
now this is happening for `chocolatey_package("googlechrome")` as well

**Comment by Kundan22** [comment]
& with chef_version=15.5.17 it throws compilation error at

```
 19:  windows_share 'Config' do
 20:    action :nothing
 21>>   path node['A']['B']['C']
 22:  end
```

Error is

> Running handlers:
> [2019-12-16T15:10:55+01:00] ERROR: Running exception handlers
> Running handlers complete
> [2019-12-16T15:10:55+01:00] ERROR: Exception handlers complete
> Chef Infra Client failed. 0 resources updated in 19 seconds
> [2019-12-16T15:10:55+01:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
> [2019-12-16T15:10:55+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
> [2019-12-16T15:10:55+01:00] FATAL: FrozenError: can't modify frozen String

**Comment by vsingh-msys** [comment]
> @vsingh-msys can you give more details about the issue that was fixed? what was the issue and what is fixed in latest version?

We have fixed the chocolatey related issue in PR https://github.com/chef/chef/pull/8765

Let me know if you still face issues related to choco package?

will look `windows_share` related issue revert you back thanks.

**Comment by vsingh-msys** [comment]
Closing as already fixed available in https://github.com/chef/chef/pull/8765
