### ISSUE TITLE
Forgot to uncomment this line

### ISSUE THREAD

**Issue by axos88** [chef/chef#9162]
https://github.com/chef/chef/blob/d75137590c6a1e138c02f5a42f8c9e12732c94c7/lib/chef/provider.rb#L79-L82

**Comment by tas50** [comment]
Personally I think we should just remove this line entirely. Causing failures for use_inline_resources provides us pretty minimal value in terms of cleaning up code in chef/chef and creates a blocker for upgrading chef-client releases. We're now cleaning these up automatically in cookstyle, which is probably the place do it.
