### ISSUE TITLE
windows_share: can't modify frozen String

### ISSUE THREAD

**Issue by Kundan22** [chef/chef#9166]
## Description
Compilation fails with error "can't modify frozen String". It shows error at **path** in the windows_share method.

```
19:  windows_share 'AppFabricConfig' do
20:    action :nothing
21>>   path config_path
22:  end
```

## Chef Version
**15.5.17**

## Platform Version
Windows Server 2016

System Info:
------------

> chef_version=15.5.17
> platform=windows
> platform_version=10.0.14393
> ruby=ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]
> program_name=C:/opscode/chef/bin/chef-client
> executable=C:/opscode/chef/bin/chef-client

## Replication Case
Occurs every time when I am trying to run a chef-client. It doesn't compile.

## Client Output

> Running handlers:
> [2019-12-16T15:28:29+01:00] ERROR: Running exception handlers
> Running handlers complete
> [2019-12-16T15:28:29+01:00] ERROR: Exception handlers complete
> Chef Infra Client failed. 0 resources updated in 19 seconds
> [2019-12-16T15:28:29+01:00] FATAL: Stacktrace dumped to c:/chef/cache/chef-stacktrace.out
> [2019-12-16T15:28:29+01:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
> [2019-12-16T15:28:29+01:00] FATAL: FrozenError: can't modify frozen String

```
```

**Comment by lamont-granquist** [comment]
We would probably need the contents of the stacktrace.out file to track this down.

**Comment by Kundan22** [comment]
Attached
[chef-stacktrace.out.log](https://github.com/chef/chef/files/3972357/chef-stacktrace.out.log)

**Comment by Kundan22** [comment]
**can you please increase the priority of this issue as we are not able to compile our cookbooks because of this issue.**

**Comment by lamont-granquist** [comment]
For escalating support issues you should inquire to our sales people about pricing for a support agreement and should be going through our helpdesk.

You can fix the root cause of this yourself though since the problem is going to be that the config_path string is frozen and you can either remove that .freeze or if that comes from somewhere else you should be able to dup the string one way or another to bypass it.

**Comment by tas50** [comment]
@Kundan22 what type of value is the config_path variable and where is that being set?

**Comment by dheerajd-msys** [comment]
@Kundan22 Any updates on ^

**Comment by Kundan22** [comment]
@tas50 : C:\AppFabricConfig

@dheerajd-msys 
I am going to try with [v15.8.23] (https://downloads.chef.io/chef/stable/15.8.23) and update on the outcome.

**Comment by dheerajd-msys** [comment]
Ok, Thanks @Kundan22

**Comment by Kundan22** [comment]
@dheerajd-msys  still same error with v15.8.23 as well

**Comment by tas50** [comment]
@dheerajd-msys I think we can just change the gsub! here to gsub

https://github.com/chef/chef/blob/master/lib/chef/resource/windows_share.rb#L42

You'll want to make sure we have some specs in place for that coersion so that it continues to function correctly.

**Comment by abousias** [comment]
@tas50 You are correct, the `!` is throwing this error when you use it with a variable, e.g. if you pass in an attribute value for `path` it is easily reproducible. 

With @Kundan22, we are now doing `thePath.dup` to avoid cloning the frozen flag.

**Comment by dheerajd-msys** [comment]
@tas50 Ok, We will update that as said.

Thanks @abousias about update
