### ISSUE TITLE
Longer search box in GitHub enterprise web app

### ISSUE THREAD

**Issue by Kundan22** [chef/chef#9167]
### Describe the Enhancement:
Can you provide a longer search box in enterprise version of Github web app??

### Describe the Need:
We have repository names categorized along with organization (e.g. Organization/RepoName) so while searching we **can't see full name of the repository in suggestions list** and every item in the suggested list is truncated with three dots. If the repository names are starting with similar prefix and ending with different name then there no way to choose correct on from the suggestions list.

There is enough space to the right to expand the search textbox

![image](https://user-images.githubusercontent.com/31039343/70925994-92194180-202c-11ea-8fde-600b8a1e21d6.png)

**Comment by lamont-granquist** [comment]
This has nothing to do with Chef Software, you are in the wrong repository
