### ISSUE TITLE
The new mac_user resource has several critical flaws

### ISSUE THREAD

**Issue by chilcote** [chef/chef#9171]
## Description

15.6.16 fixed the crashing bug in the `mac_user` resource, but now that it's not crashing, it has exposed several other critical issues.

- Setting a home directory with `sysadminctl` or `dscl` now require `SystemPolicySysAdminFiles` whitelisting, which cannot be set indefinitely without an MDM server (i.e. it will prompt every time chef calls the resource, asking you to "allow" Terminal to manage your system.)
- When creating a user, it does not respect `system: true` (i.e. all users are >500)
- When creating a user, it does not set the GID to its numerical GID; it uses the group "name" (i.e. "admin" instead 80)
    - this causes problems when doing things like "chown," or, more critically, using a `dir` resource to manage a home dir that's not under /Users.

I appreciate the work that went into fixing the crashing bug, and hopefully we can get these addressed as well. 

## Chef Version
15.6.16

## Platform Version
10.15.2

## Replication Case
It's as easy as trying to manage a user on macOS. For example, this resource fails all three of the points above.
```
user 'fooadmin' do
  gid 'admin'
  home '/Users/fooadmin'
  shell '/bin/bash'
  password 'this_is_a_terrible_password'
  iterations 40000
  manage_home true
  system true
  action :create
end
```

## Client Output
The output looks correct. because the user is being created (and if the process is being called via launchd, then thankfully we don't see the user permission prompts. However, if you set system to true, you can verify that the UID is still >500, and you can inspect the user plist to verify that the UniqueGID is not being set correctly.

## Stacktrace
n/a

**Comment by chilcote** [comment]
Anyone?

**Comment by jessepeterson** [comment]
Regarding the group ID issue just to expound a bit. It looks like macOS effectively disables a user on the system that's created with an invalid GID. I.e. the system acts like the user doesn't even exist (despite the record actually existing the Local DS plist 'database.'

I think @chilcote and I probably came up with the same solution at the same time to the `PrimaryGroupID` issue. Here's my diff:

```diff
$ diff -wu mac.rb.prev mac.rb
--- mac.rb.prev	2019-12-15 21:19:05.000000000 -0800
+++ mac.rb	2020-01-24 09:03:37.000000000 -0800
@@ -196,7 +196,7 @@
             end.run_action(group_action)
 
             converge_by("create primary group ID") do
-              run_dscl("create", "/Users/#{new_resource.username}", "PrimaryGroupID", new_resource.gid)
+              run_dscl("create", "/Users/#{new_resource.username}", "PrimaryGroupID", group_id)
             end
           end
 
@@ -272,7 +272,7 @@
 
           if diverged?(:gid)
             converge_by("alter group membership") do
-              run_dscl("create", "/Users/#{new_resource.username}", "PrimaryGroupID", new_resource.gid)
+              run_dscl("create", "/Users/#{new_resource.username}", "PrimaryGroupID", group_id)
             end
           end
 
@@ -411,12 +411,8 @@
 
           group_name, group_id = user_group_info
 
-          if current_resource.gid.is_a?(String)
-            current_resource.gid != group_name
-          else
             current_resource.gid != group_id.to_i
           end
-        end
 
         def password_diverged?
           # There are three options for configuring the password:
```

Because we're changing the divergence-checking code as well this patch will remediate the ill-created users, too.
