### ISSUE TITLE
Testing:  buildkite omnibus tests need to run `bundle exec rake spec`

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#9172]
Currently we only run functional tests on BK.  We are missing unit and integration tests which are important because some of the distros only run in the BK omnibus test phase (e.g. AIX) so we're missing
unit + integ coverage entirely for those distros.  Our unit testing also has some func testing baked into it so that some tests run only on certain distros so if they are omitted we are omitting testing.

Furthermore we're now missing testing chef-config and chef-utils because of bypassing the rake tasks, so we need to be using `bundle exec rake spec` to test, and not `bundle exec rspec spec/whatever`.

**Comment by tas50** [comment]
We did this
