### ISSUE TITLE
build_essentials (installing xcode command line tools) fails to install on Catalina

### ISSUE THREAD

**Issue by w0de** [chef/chef#9177]
## Description

Catalina's output for `softwareupdate -l` with a pending Command Line Tools update looks like this:

```
Software Update Tool

Finding available software
Software Update found the following new or updated software:
* Label: Command Line Tools for Xcode-11.2
	Title: Command Line Tools for Xcode, Version: 11.2, Size: 224942K, Recommended: YES,
* Label: Command Line Tools for Xcode-11.3
	Title: Command Line Tools for Xcode, Version: 11.3, Size: 224878K, Recommended: YES,
```

The "Label: " tag before the name of update items is new. It breaks the script used to parse this output, and so breaks the install:

```
softwareupdate -i "Label: Command Line Tools for Xcode-11.3" --verbose
Software Update Tool

Label: Command Line Tools for Xcode-11.3: No such update
No updates are available.
```

## Chef Version

Chef: 14.12.9

(I believe the bug persists in 15)

## Platform Version

macOS 10.15.2

## Replication Case

1. (Preferably) Boot macOS >= 10.15 without CL tools installed - ever.  Or: uninstall CommandLineTools. (Full disclosure, I can't do this on demand on a SIP mac. One can `rm -rf /Library/Developer/CommandLineTools`, but the package receipt is SIP protected and remains. It appears macOS removes the receipt on a schedule if the files are removed, but I can't say when or how.)
2. Run this resource. The execute step will silently fail to install CL Tools. The execute block has an empty output.

## Client Output
```
      * execute[install XCode Command Line tools] action run[2019-12-18T11:48:06-07:00] INFO: Processing execute[install XCode Command Line tools] action run (/var/chef/cache/cookbooks/build-essential/resources/xcode_command_line_tools.rb line 29)

        [execute] Software Update Tool

```

**Comment by tas50** [comment]
Fixed with the merge of #9178. Thanks for the report and the initial work here @w0de
