### ISSUE TITLE
Chef 16: Track down code to support EL 5 and remove it

### ISSUE THREAD

**Issue by tas50** [chef/chef#9179]
We have code in Chef that support EL 5 that we should remove at this point

**Comment by dheerajd-msys** [comment]
@tas50 Just went through code and there is no such code supporting `EL 5` other than just a comment at https://github.com/chef/chef/blob/master/spec/support/shared/unit/provider/useradd_based_user_provider.rb#L205, 

Thanks!

**Comment by tas50** [comment]
Closing this out since the major one was build_essential and I covered that already
