### ISSUE TITLE
dnf_package guard is not working properly

### ISSUE THREAD

**Issue by asvinours** [chef/chef#9201]
# Describe the problem

When using the dnf_package resource and providing a version number, the package gets re-installed at every chef run.

## Software Version

15.6.10

## Replication Case

```
package 'auditbeat' do
    version '7.3.1-1'
end
```
Deploy a package resource on CentOS 8 with a version number

## Stacktrace

```
[2020-01-01T17:57:02-05:00] TRACE: dnf_package[auditbeat] auditbeat 0:7.3.1-1.x86_64 needs updating to 7.3.1-1
[2020-01-01T17:57:02-05:00] TRACE: dnf_package[auditbeat] auditbeat 0:7.3.1-1.x86_64 needs updating to 7.3.1-1
```
It seems that the compare_version function is not returning the expected result.
https://github.com/chef/chef/blob/v15.6.10/lib/chef/provider/package/dnf.rb#L134
```
"input version_compare 0:7.3.1-1.x86_64 - 7.3.1-1"
"output version_compare 1"
```

**Comment by breisig** [comment]
I have been having this issue for awhile now with chef-client on CentOS 8 *always* re-installing a package on every run.

```
  * dnf_package[redis] action install
    - install version 5.0.7-1 of package redis
```

**Comment by breisig** [comment]
I found a workaround for the issue by putting the version number in the package name.

Example:

from
```
package 'auditbeat' do
    action :install
    version '7.3.1-1'
end
```

to
```
package 'auditbeat-7.3.1-1' do
    action :install
end
```

**Comment by breisig** [comment]
That fix adding aarch el8 does not fix this issue.

**Comment by lamont-granquist** [comment]
did you check it?  because there's a specific test in there forward ported from the yum_package provider which implicitly checks comparisons between evra's and evr's, along with the code fixes in the version comparison function to make it work.
