### ISSUE TITLE
Multiple chef-client processes consuming all memory

### ISSUE THREAD

**Issue by ebrenessdev** [chef/chef#9208]
When running this command to show the amount of chef-processes I got 943

`ps -fe | grep chef-client | wc -l`
`943`

after some time the system runs out of memory. 
chef-client is running as daemon.

## Chef Version
Chef: 12.8.1

## Platform Version
CentOS 7

what do I need to do in order to keep only one chef-client process running at a time? what could be causing the process not to end properly?

Thanks

**Comment by tas50** [comment]
Chef 12.8.1 was released on March 10, 2016 and has been end of life for over a year. You'll need to upgrade to a modern release, which includes hundreds of bug fixes and enhancements.
