### ISSUE TITLE
Report client run mode to data collector

### ISSUE THREAD

**Issue by kmacgugan** [chef/chef#9218]
### Describe the Enhancement:
With the current client run reports we are unable to determine if a client run was run under the effortless pattern, in target mode, or other modes. It would be better if we had a top level field that reported the circumstances of the run (target mode, effortless, local mode, chef-server?, others?).

### Describe the Need:
We can display this information in automate, and users can have a better idea of the types of nodes they are running. 

### Current Alternative
We use the chef_server_fqdn to determine if it was run as localmode, as this should be localhost if so. We have no other information to go on.

### Can We Help You Implement This?:
Yes.

**Comment by TheLunaticScripter** [comment]
This would be awesome. Just for the effortless side of things we currently have two ways to pass in things like this, the [client.rb](https://github.com/chef/effortless/blob/master/scaffolding-chef-infra/lib/linux/client-chunk.rb) file and in the [chef-client](https://github.com/chef/effortless/blob/0e0ead93362b91922be7adf201e7ea32aec55b44/scaffolding-chef-infra/lib/linux/run.bash#L32) command. Not sure if adding another flag for effortless is the best option or a setting in the `client.rb`.

**Comment by lamont-granquist** [comment]
`Chef::Config.target_mode?` could just be rendered into the payload somewhere.

how strict is the ingestion of the JSON on the server-side?  i've been wary of adding any top-level keys to the data collector output for fear of breaking it (and creating a backwards incompatibility issue).

**Comment by kmacgugan** [comment]
I think we could reuse the top level source field in the current payload. From the original RFC it is an enum of chef_client and chef_solo, and we don't have validation on the values received in automate. 
https://github.com/chef-boneyard/chef-rfc/blob/master/rfc077-mode-agnostic-data-collection.md

**Comment by tas50** [comment]
I'm going to close this for now until this idea gets picked back up by the Automate team.
