### ISSUE TITLE
knife bootstrap on Windows creates a directory called C:chef in Linux node home directories

### ISSUE THREAD

**Issue by Firenice03** [chef/chef#9224]
# Describe the problem

Noticed a bug with chef-workstation (windows) version 0.13.35 also confirmed on 0.14.16.

When using CW to bootstrap a Linux box (distro independent), it creates a directory called C:chef in the home directory for the user that was used to login.

This in turn does not populate the /etc/chef and further chef-client runs fail  complaining about  client/validator.pem files, although running a validator-less bootstrap run. 

## Software Version

System/Desktop: Windows 10 Enterprise v. 1803
Chef Workstation: 0.13.35 also confirmed on 0.14.16

## Replication Case

Appears to be restricted to Windows version of Chef Workstation (0.13.35 and 0.14.16). Confirmed  with same version on Ubuntu and worked as expected.

**Comment by lamont-granquist** [comment]
What command is actually being run?  `chef <something>` or `knife bootstrap`?

**Comment by subhro** [comment]
knife bootstrap.

**Comment by marcparadise** [comment]
@subhro could you paste in the full bootstrap command?

**Comment by Firenice03** [comment]
The basic command:  knife bootstrap xx.xx.xx.xx -N HOST -U USER --sudo
Have tried with both run-list and/or policyfiles: 
--run-list 'cookbook' 
--policy-name 'policy_name' --policy-group 'staging'

All failed the same...

**Comment by marcparadise** [comment]
Thanks @Firenice03

**Comment by Firenice03** [comment]
Knife.rb contents:

# See https://docs.getchef.com/config_rb_knife.html for more information on knife configuration options

current_dir = File.dirname(__FILE__)
log_level                :info
log_location             STDOUT
node_name                "user-id"
client_key               "#{current_dir}/user-id.pem"
chef_server_url          "https://chef-test.domain.org/organizations/chef-test"
cookbook_path            ["#{current_dir}/../cookbooks"]

**Comment by Firenice03** [comment]
Just an FYI - This continued to occur thru at least 0.14.19...
But does appear to be resolved in 0.15.0  :)

**Comment by tas50** [comment]
Workstation 0.15 has Chef 15.7.30 which includes the fix
