### ISSUE TITLE
Release Chef Infra Client 15.7

### ISSUE THREAD

**Issue by tas50** [chef/chef#9228]
We need to release Chef Infra Client 15.7 so we can fork for Chef Infra Client 16 development.

- [ ] Evaluate remaining PRs that we should merge
- [ ] Select the build number
- [ ] Write release notes
- [ ] Ship
- [ ] Push to Chocolatey / Homebrew

**Comment by lamont-granquist** [comment]
#9219 i think is the only one that 15.7 should potentially block on, everything else isn't critical

**Comment by tas50** [comment]
Done
