### ISSUE TITLE
Description for -a option should be amended in knife-ssh manual 

### ISSUE THREAD

**Issue by teklabania** [chef/chef#9231]
## Description
`knife-ssh` manual under `-a` option states:
"The default attribute is the FQDN of the host."
which is not true according to code:
https://github.com/chef/chef/blob/01526978908b095b49f259522835dc8641e66331/lib/chef/knife/ssh.rb#L209
I was struggling with ssh timeouts to nodes because `cloud.public_hostname` was used by `knife ssh` instead of `fqdn`. ssh is not open in public on these hosts. It's easy to use `-a fqdn`, but it should be clearly stated that `fqdn` is NOT a default option.

## Chef Version
knife --version
Chef: 13.6.4

## Platform Version
Arch Linux

## Replication Case
man knife-ssh

## Client Output
N/A

## Stacktrace
N/A

**Comment by lamont-granquist** [comment]
13.6.4 is very old, and we've removed the man pages entirely so there's nothing to fix here.

the `--help` output shows:

`"The attribute to use for opening the connection - default depends on the context."`
