### ISSUE TITLE
launchd: incorrect capitalization for hard resource limit: "HardreSourceLimits"

### ISSUE THREAD

**Issue by rb2k** [chef/chef#9238]
## Description
When setting hard_resource_limits with the launchd cookbook, you end up with the wrong capitalization.

hard_resource_limits { 'NumberOfFiles' => 4096 }

results in <key>HardreSourceLimits</key>

## Chef Version
up to master

## Platform Version
macOS

## Replication Case
Use hard_resource_limits in the launchd cookbook

**Comment by tas50** [comment]
Released in 15.7.30. Thanks @rb2k
