### ISSUE TITLE
Warn, don't fail on 413 and 429 responses

### ISSUE THREAD

**Issue by sean-horn** [chef/chef#9248]
### Problem:
The chef-client run proper completes successfully.
However, when attempting to do audit cookbook report handling, the chef-client receives a 429 response code from Automate. For some customers, it would be nicer if this were a warning, not a fatal failure

```
[2020-01-14T20:33:55+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

### Describe the Enhancement:

Generate a warning instead of a fatal/failure of the chef-client when the response codes while submitting reports to Automate through a report handler come back 413/429 here https://github.com/chef/chef/blob/292a91b4dc7829af1640c75f06c5f8ba659f9b29/lib/chef/resource_reporter.rb#L91-L110

This code that implements `enable_reporting_url_fatals` only handles the 404 and 406 cases. This enhancement request advocates handling 429 and 413 as well.

### Describe the Need:
Many enterprise users. Don't fail the whole run when the chef-client run was successful, but the automate report submission has a temporary failure of 404, 406, 429. 413.

### Current Alternative
N/A

**Comment by sean-horn** [comment]
Zendesk 24185

**Comment by lamont-granquist** [comment]
413 is "payload too large"

429 is "too many requests"

**Comment by danielcbright** [comment]
@lamont-granquist I believe the 429 error is misleading here, in the case of the customer referenced this error occurs when the payload is over 4mb.

**Comment by zmaupin** [comment]
@lamont-granquist 
> 413 is "payload too large"
> 
> 429 is "too many requests"

What we're asking here is that we don't fail a chef-client run that was otherwise successful because the payload is too large or Automate is under load. We simply don't want a successful chef-client run to fail due to a problem with Automate. The two options available in the Chef client config file seem to word it as though the run itself won't fail if Automate isn't available. However, this appears to only work if Automate is _completely_ unavailable.

Our ask:

Provide an option available in the Chef client config file so that no failures related to Automate cause a Chef-client failure. We'd also like to be able to configure the allowed size of the payload if possible.

**Comment by lamont-granquist** [comment]
Modern Automate 2 should definitely be going in through the data_collector which has a setting to suppress those errors:

https://github.com/chef/chef/blob/master/lib/chef/data_collector.rb#L194

I think even old Automate was using the Data Collector and not the old Resource Reporter.  AFAIK the only thing using the old RR is Hosted Chef at this point (and maybe some non-automate chef-server users that yolo their own reporting).

This should probably not be getting fixed and the RR should be getting retired, and anyone on an old enough codebase to need the old RR should be getting upgraded.

**Comment by zmaupin** [comment]
We already have this set in the client.rb on all nodes even the ones that were failing.
```
data_collector.raise_on_failure false
```

**Comment by lamont-granquist** [comment]
So, I don't know what code to fix here, since we definitely have this feature in Chef 15.

**Comment by lamont-granquist** [comment]
The data collector was also nearly rewritten in Chef 15, this may be an old bug that this doesn't work somehow.

**Comment by lamont-granquist** [comment]
AFAIK there's nothing to fix here.  Chef-12 is long EOL.
