### ISSUE TITLE
systemd_unit generates invalid units when passing a hash

### ISSUE THREAD

**Issue by gregkare** [chef/chef#9259]
## Description
`systemd_unit` generates invalid systemd units when passing a hash as the content. The official docs say you can use a hash and provide an example: https://docs.chef.io/resource_systemd_unit.html

## Chef Version
Chef Infra Client 15.6.10

## Replication Case

Use the following in a recipe:

```ruby
systemd_unit 'bitcoind.service' do
  content({
    Unit: {
      Description: "Bitcoin Core daemon",
      Documentation: ["https://bitcoincore.org"],
      After: "network.target"
    },
    Service: {
      User: "bitcoind",
      Type: "exec",
      ExecStart: "/snap/bin/bitcoin-core.daemon",
      PIDFile: "/home/bitcoind/snap/bitcoin-core/common/.bitcoin/bitcoind.pid",
      Restart: "on-failure",
    },
    Install: {
      WantedBy: "multi-user.target"
    }
  })
end
```

This generates the following systemd unit file:

```ini
[Unit]
Description = Bitcoin Core daemon
Documentation = https://bitcoincore.org
After = network.target

[Service]
User = bitcoind
Type = exec
ExecStart = /snap/bin/bitcoin-core.daemon
PIDFile = /home/bitcoind/snap/bitcoin-core/common/.bitcoin/bitcoind.pid
Restart = on-failure

[Install]
WantedBy = multi-user.target
```

This causes the following error:

```
$ systemctl status bitcoind
[snip]
/etc/systemd/system/bitcoind.service:8: Failed to parse service type, ignoring: exec
```

This is caused by the iniparse library, that adds spaces around the equal signs: https://github.com/chef/chef/blob/262026a09745719784d7fc4b140228912307b4de/lib/chef/resource/systemd_unit.rb#L71-L81

Rewriting the Type line to omit the spaces around the equal sign fixes it:

```ini
Type=exec
```

The generates systemd service should not have spaces around the equal signs.

**Comment by antima-gupta** [comment]
@gregkare I have fixed spaces around the equal sign in this [PR](https://github.com/chef/chef/pull/11856), but this issue will be still there because after running above recipe by using `action: [:create, :enable]` .
To resolve this issue you need to run `action` `start` or `restart`.
