### ISSUE TITLE
Test and Promote Habitat builds on Linux

### ISSUE THREAD

**Issue by btm** [chef/chef#9282]
### Describe the Enhancement:
In #8731 we created a functional test pipeline for Windows Habitat packages, but we lack functional testing for the Linux Habitat packages. As such, we still currently manually promote the Windows Habitat packages to stable as there wasn't a way to promote the packages for a single platform.

Note that the expected challenge is getting the functional tests to succeed given the nature of how Habitat packages are isolated from the underlying system.

acceptance criteria:
- pipelines for Linux to match `.expeditor/verify.habitat.pipeline.yml` and `habitat-test.pipeline.yml`
- above pipelines run `rspec spec/functional` successfully
- habitat packages are promoted to stable after omnibus packages are
    Add: `- built_in:promote_habitat_packages`
    To:    `- workload: artifact_published:stable:chef:{{version_constraint}}`
    In:    `.expeditor/config.yml`

### Current Alternative
manual promotion of packages on https://bldr.habitat.sh/#/pkgs/chef/chef-infra-client/latest

Aha! Link: https://chef.aha.io/features/SH-109

**Comment by VanWolf29** [comment]
I can take this one.

**Comment by btm** [comment]
I'm not sure why https://bldr.habitat.sh/#/pkgs/chef/chef-infra-client/latest has 16.0.257/20200428080931 as the latest stable infra client linux build, when there are newer linux builds like https://bldr.habitat.sh/#/pkgs/chef/chef-infra-client/16.2.44. I presume that something happened with expeditor during the promotion.

**Comment by btm** [comment]
https://github.com/habitat-sh/habitat/issues/7135 was fixed, so we should be able to do the linux pipeline now.
