### ISSUE TITLE
Knife cli fuzzy search does not work as documented

### ISSUE THREAD

**Issue by mimato** [chef/chef#9285]
###  Description
As documented here: https://docs.chef.io/knife_search.html#syntax, the behaviour for a node search that does not have a `:` in the search string should be to do a fuzzy search like `tags:*#{@query}* OR roles:*#{@query}* OR fqdn:*#{@query}* OR addresses:*#{@query}*`. However, after upgrading Chef from 12 to 14, we noticed this was no longer working.  

## Chef Version
14.12.3

## Platform Version
macOS 10.14.6

## Replication Case
Given a chef server with a node `mynode` and a properly configured knife set-up
* run `knife node show mynode` (the node should display)
* run `knife search node 'name:mynode'` (the node should display)
* run `knife search mynode` (the node should display but does not)

## Client Output
```
knife search node 'name:a-fake-node' -i
1 items found

a-fake-node
```

```
knife search 'name:a-fake-node' -i
1 items found

a-fake-node
```

```
knife search a-fake-node -i
0 items found
```

**Comment by lamont-granquist** [comment]
closed by #9287
