### ISSUE TITLE
chef_gem does not work as expected on macOS 10.15

### ISSUE THREAD

**Issue by ryanmoon** [chef/chef#9338]
## Description

- when using the `chef_gem` resource in 10.15 you cannot install a gem via `chef_gem` because `/` is a protected part of the filesystem.
- this happens when `chef-client` or `chef-apply` is run via a LaunchDaemon
- when `chef-client` or `chef-apply` is run via `sudo` the issue does not appear
- I believe this is why I didn't catch this when testing via test-kitchen.

## Chef Version

- verified this issue happens on Chef 14.2.0 and up.

## Platform Version

- macOS 10.15.x

## Replication Case

- on a machine running macOS 10.15, with chef-client version 14.2.0
- create a file at `/tmp/chef_gem.rb` with the following contents:
```
  chef_gem 'httparty' do
    compile_time true
    version '0.17.3'
    action :install
  end
```
- create a launchd, at `/Library/LaunchDaemons/local.job.plist` with the following contents:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>local.job</string>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/local/bin/chef-apply</string>
		<string>/tmp/chef_gem.rb</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>StandardOutPath</key>
	<string>/tmp/local.job.stdout</string>
	<key>StartInterval</key>
	<integer>120</integer>
</dict>
</plist>

```

If you're running on a newer version of chef-client, you would need to modify the plist to be:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Label</key>
	<string>local.job</string>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/local/bin/chef-apply</string>
		<string>--chef-license</string>
		<string>accept</string>
		<string>/tmp/chef_gem.rb</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
	<key>StandardErrorPath</key>
	<string>/tmp/local.job.stderr</string>
	<key>StandardOutPath</key>
	<string>/tmp/local.job.stdout</string>
	<key>StartInterval</key>
	<integer>120</integer>
</dict>
</plist>
```

- then load the launchdaemon, `sudo launchctl load /Library/LaunchDaemons/local.job.plist`
- check the output at `/tmp/local.job.stdout`
- then unload the launchdaemon, `sudo launchctl unload /Library/LaunchDaemons/local/job.plist`

## Client Output

```
    Read-only file system @ dir_s_mkdir - /.gem
---- End output of /opt/chef/embedded/bin/gem install httparty -q --no-rdoc --no-ri -v "0.17.3" --source=https://www.rubygems.org ----
Ran /opt/chef/embedded/bin/gem install httparty -q --no-rdoc --no-ri -v "0.17.3" --source=https://www.rubygems.org returned 1
[2020-02-06T08:25:35-08:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: chef_gem[httparty] ((chef-apply cookbook)::(chef-apply recipe) line 1) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/chef/embedded/bin/gem install httparty -q --no-rdoc --no-ri -v "0.17.3" --source=https://www.rubygems.org ----
STDOUT: 
STDERR: ERROR:  While executing gem ... (Errno::EROFS)
    Read-only file system @ dir_s_mkdir - /.gem
---- End output of /opt/chef/embedded/bin/gem install httparty -q --no-rdoc --no-ri -v "0.17.3" --source=https://www.rubygems.org ----
Ran /opt/chef/embedded/bin/gem install httparty -q --no-rdoc --no-ri -v "0.17.3" --source=https://www.rubygems.org returned 1
```

## WORKAROUND

- this is not ideal, because you don't get the `compile_time true` option, but as a workaround using this:
```
  bash 'httparty' do
    code <<-EOH
  HOME=/opt
  export HOME
  /usr/local/bin/chef-apply --chef-license 'accept' -e 'chef_gem "httparty" do version "0.17.3" end'
  EOH
    action :run
  end
```

works.

**Comment by ryanmoon** [comment]
I do want to note, that the while the workaround does not fail. It does not make the gem available to `chef` when `chef-client` is run via a launchd. Is there something I'm missing in making a gem available to `chef-client` when it is run via a service vs `chef-client` running via `sudo chef-client`?

**Comment by lamont-granquist** [comment]
Looking at my mac it looks like the HOME of root in /etc/passwd on mac is /var/root.

I'm leaning very heavily towards this being a problem with launchd not respecting the HOME, and that the plist probably has an option somewhere to set the env vars, and that this should go there.

Having home setup sane is a prereq for chef-client to run, and either it needs to go into the launchd config, or it needs to be set explicitly in config.rb or in the code if the user wants to override it.

You haven't set your HOME variable, so not having it set on the shell out is 100% correct behavior, and I can't read your mind to know that this was a mistake, and gem is behaving entirely correctly.

**Comment by ryanmoon** [comment]
Working directory by default in LaunchD appears to be `/` which is problematic in 10.15 and above. It seems like you would need to specify that explicitly in the `chef-client` cookbook template.

**Comment by ryanmoon** [comment]
I'd suggest adding `<key>WorkingDirectory</key>` to the chef-client cookbook for the macOS template, as that's the cookbook we use for setting chef-client to run. Should I close this, as this is more of a bug I found when using the community cookbook?
