### ISSUE TITLE
Add the ability for the windows_certificate resource to be exportable.

### ISSUE THREAD

**Issue by danielcbright** [chef/chef#9355]
### Describe the Enhancement:
Add the ability for the `windows_certificate` resource to be exportable.
### Describe the Need:
There is a need from many customers to be able to import a certificate into the Windows Certificate Store and it be marked as `exportable` for certain use cases.
### Current Alternative
Currently, customers are using powershell scripts to accomplish the task of importing the cert, the default when using the `Import-PfxCertificate` is to set the `exportable` flag to `true`, which solves the problem

### Can We Help You Implement This?:
I can provide more specific information as needed. An example import that enables the `exportable` flag looks like this:

`pfx.Import($certPath,$certPass,"Exportable,PersistKeySet")`

**Comment by chefbob** [comment]
This problem is forcing a number of our project to use a powershell script instead of the windows_certificate resource.  We have more of these projects in the pipeline and would appreciate any time that can be put into this.
