### ISSUE TITLE
knfie config get-profile is not working as expected

### ISSUE THREAD

**Issue by vsingh-msys** [chef/chef#9372]
## Description

seems that `knife config get-profile` is not picking the profile that we have set in `config.rb`

## Chef Version

Chef Infra Client: 16.0.65

## Platform Version

Ubuntu 16.04 & 18.04

## Replication Case

- Add `profile :aws-engg` in config.rb
- hit `knife config get-profile` still showing default
```
default
```

but `knife config get` works as expected.

```
Loading from credentials file /.chef/credentials
Loading from configuration file /.chef/config.rb
Loading from .d/ configuration file /.chef/config.d/test.rb
Loading from .d/ configuration file /.chef/config.d/test2.rb
chef_server_url: https://chef-server.test/organizations/4thcoffee
client_key:     /.chef/chefadmin12.pem
config_file:     /.chef/config.rb
cookbook_path:
  /chef-cookbooks
  /cookbooks
knife:
  editor: /usr/bin/vim
log_level:       warn
log_location:    STDOUT
node_name:       chefadmin
profile:         aws-engg
```

**Comment by tas50** [comment]
The get profile command is for getting the profile from the knife credentials file not the config.rb file
