### ISSUE TITLE
Backport 8756 to Chef 14

### ISSUE THREAD

**Issue by btm** [chef/chef#9392]
##  Description 
#8756 fixed an issue but a customer is hitting it on Chef 14 and we need to backport it there.

## Related Issues
https://github.com/chef/customer-bugs/issues/106
https://getchef.zendesk.com/agent/tickets/23256

**Comment by dheerajd-msys** [comment]
PR https://github.com/chef/chef/pull/9405 to backport

**Comment by dheerajd-msys** [comment]
Closing this issue since https://github.com/chef/chef/pull/9405 is merged
