### ISSUE TITLE
rhsm Resouces should support RHEL 8

### ISSUE THREAD

**Issue by donwlewis** [chef/chef#9399]
### Describe the Enhancement:
`rhsm` should be able to support RHEL 8 which uses dnf as package manager.

### Describe the Need:
`rhsm` resources currently leverage `yum_package` or execute `yum` commands.  We should add logic so that dnf package manager can be leveraged as this currently doesn't work for RHEL 8.

### Current Alternative
Currently you would have to write your own execute blocks to do this instead of leveraging the `rhsm` resources.

### Can We Help You Implement This?:
I will be more than happy to help with this.  I will put in a pull request for what I think the path forward should be.  Currently thinking to just replace `yum_package` with just regular `package` resource, but will need to think about logic for `execute` blocks that leverage `yum`. Will need some guidance on testing.

**Comment by tas50** [comment]
Fixed in #9409. Thanks for the report @donwlewis

**Comment by tas50** [comment]
This is fixed on master. Thanks for pointing it out.

**Comment by donwlewis** [comment]
Thanks @tas50.  Do we know when this will be released?  Trying to figure out if I should move forward with a work around for now, or wait cause I am lazy.

**Comment by tas50** [comment]
Early next month we'll ship this in Chef Infra Client 15.9
