### ISSUE TITLE
Update the resource docs generator rake task for the new format

### ISSUE THREAD

**Issue by tas50** [chef/chef#9412]
The docs site templates out resource pages from a YAML file now. We need to generate that YAML page per resource now instead of generating the RST pages via ERB. This should actually be much easier going forward. We can also potentially start storing markdown values in the resource documentation fields so that no human interaction is necessary for this generation.

The legacy rake task to generate RST files: https://github.com/chef/chef/blob/master/tasks/docs.rb

**Comment by phiggins** [comment]
Can we close this after #9750?

**Comment by tas50** [comment]
This is done enough to close this out. It's all minor tweaks from here.
