### ISSUE TITLE
Chocolate_resource options causing extra quotes in resulting call to choco and creating issues with parsing choco installer args

### ISSUE THREAD

**Issue by dave-q** [chef/chef#9413]
## Description
I recently upgraded a server from Chef Client 14.12.9.1 to 15.4.45.

I made no changes to our cookbook and a recipe started failing.

The issue was that the installer arguments we pass to choco via -ia were not being passed properly and it wasn't installing where we wanted.

Here is the resource, with any sensitive stuff redacted

```ruby
chocolatey_package 'Install Service' do
  package_name 'My_Package'
  source node[cb]['choco_source']
  options "--no-progress --% -ia \"INSTALLDIR=\"#{node[cb][:install_dir]}\\bin\" SERVICENAME=\"My_service\" \""
  version node[cb]['version']
  action :install
end
```

I dove into the choco logs to see exactly what was being passed to it.

There was 1 difference between the version seen when running with chef-client 14.12.9.1 and chef client 15.4.45 - There was an extra set of quotes around the choco arguments that I had provided via the resources options property and the escaped quotes were still escaped

**Chef-Client 14 Choco Log**
`Command line: "C:\ProgramData\chocolatey\choco.exe" install -y --version 1.0.0 --no-progress --% -ia "INSTALLDIR="c:\mydir\morefolders\installhere" SERVICENAME="My_service" " -source https://choco_source My_Package `

**Chef-Client 15 Choco Log**
`Command line: "C:\ProgramData\chocolatey\choco.exe" install -y --version 1.0.0 "--no-progress --% -ia \"INSTALLDIR=\"c:\mydir\morefolders\installhere\" SERVICENAME=\"My_service\" \"" -source https://choco_source My_Package`

## Chef Version
Chef Infra Client: 15.4.45

## Platform Version
Windows Server 2019

## Replication Case
Using chocolately_resource pass a string that contains escaped quotes, by either explicity escaping them or by utilising one of rubys many ways of having quotes in a string.

In chef 14 - the escaped sequences are interpreted correctly, ie ' \" ' is passed to choco as ' " '
In Chef 15 because of these extra quotes (I suspect) ' \" ' is passed to choco as ' \\" '

## Client Output

```

```

**Comment by insulind** [comment]
just to add on here, that it seems that something is adding an extra set of quotes around interpolated strings I think.

`chocolately_resource 'install package' do
  package_name 'my package'
  options "--no-progress -ia INSTALLDIR=#{install_dir}"
end`

the above produces a call to choco that looks roughly like this

choco.exe install "--no-progress -ia INSTALLDIR=c:\my_dir my_package

note the quotes around what I passed as the options. However if I change my resource to pass a string array to the options

`chocolately_resource 'install package' do
  package_name 'my package'
  options ['--no-progress', '-ia', "INSTALLDIR=#{install_dir}"]
end`

we get something like this

choco.exe install --no-progress -ia "INSTALLDIR=c:\my_dir" my_package

noticed that only the interpolated string is in quotes now.

This behavior change has broken a lot of my recipes, which I can deal with... but what's annoying is it isn't documented anywhere that I can see

**Comment by barchestera** [comment]
In case it helps, I've been experimenting with various forms of "options" string for the chocolatey_package resource. I was unable to find any that works for both Chef 14 _and_ Chef 15, except an approach like the following:
```ruby
options = ['--no-progress', '--%', '-ia', %("INSTALLDIR=#{install_dir} SERVICENAME=#{service_name}")]
options = options.join(' ') if Chef::VERSION =~ /^14/
```
Is this a viable approach for folks to use until/unless this issue gets fixed so that Chef 14-style options strings work with the chocolatey_package resource under Chef 15?
