### ISSUE TITLE
Update Hostname resource to use PowerShell Rename-Computer Cmdlet

### ISSUE THREAD

**Issue by tas50** [chef/chef#9451]
### Describe the Enhancement:
Use Rename-Computer to rename computers now that we can assume PowerShell 3.0+ where this was introduced.

### Describe the Need:
We're doing it via WMI. This Cmdlet without a doubt has additional error handling that we should utilize. Eventually we can also use it to rename a cmputer on a domain given domain creds. That would take additional work, but would be a nice win eventually.

**Comment by johnmccrae** [comment]
MS is moving away from WMI and using Rename-Computer makes the code more cross-platform.

**Comment by tas50** [comment]
Fixed in https://github.com/chef/chef/pull/11537

**Comment by johnmccrae** [comment]
Done and PR merged
