### ISSUE TITLE
windows_firewall_rule provided description works only once

### ISSUE THREAD

**Issue by pschaumburg** [chef/chef#9512]
## Description
When running a recipe with the windows_firewall_rule initially, the new firewall rule is being created with the provided description. If nothing is set, 'Firewall rule' will be provided as default value. When changing the property, nothing will be changed.

## Chef Version
15.x + 16.x

## Platform Version
Windows

## Replication Case
In a recipe, set the following:

```ruby
windows_firewall_rule 'test1' 
```

The result will be: a new firewall rule with the name 'test1' and when opening it, you'll see in the description 'Firewall rule'

Now we want to change the description:
```ruby
windows_firewall_rule 'test1' do
  description 'ABC'
end 
```

The result will show us, nothing has changed.

**Comment by tas50** [comment]
Closed by #9514
