### ISSUE TITLE
windows_firewall_rule provides no displayname for GUI

### ISSUE THREAD

**Issue by pschaumburg** [chef/chef#9513]
### Describe the Enhancement:
The windows_firewall_rule is not able to give me a proper way of adding a display name, which is not the same like the rule_name itself (this is the current implementation for that. 

### Describe the Need:
This functionality is needed for all the users, who don't want to see a technical name in the GUI of the firewall in windows.

### Current Alternative
The alternative for this would be a powershell_script resource, which adds the display name to all already added firewall rules.

**Comment by tas50** [comment]
Closed by #9514
