### ISSUE TITLE
systemd_unit not respecting sensitive property

### ISSUE THREAD

**Issue by jessepeterson** [chef/chef#9539]
## Description

`systemd_unit` resource appears not to be respecting the `senstive` property as the documentation suggests it should.

It looks like the created file resource doesn't pass on the supplied sensitive to the underlying file resource, but just a guess:

https://github.com/chef/chef/blob/9326d7d9f55fa62e9fafd1e6d4e3874adaa288df/lib/chef/provider/systemd_unit.rb#L235-L243

Documentation says it should support this (under the 'common' resource properties):

https://docs.chef.io/resources/systemd_unit/

## Chef Version

14.5.33 (but the current GitHub code looks like it suffers the issue, too)

## Platform Version

```
$ uname -a
Linux localhost 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

## Replication Case

Create a systemd_unit resource, see that it outputs the `/etc/systemd/system/<name>.service` diffs in the verbose log.

## Client Output
see above

## Stacktrace
n/a

**Comment by tas50** [comment]
Thanks for the report @jessepeterson. This fix will go out in Chef Infra Client 16.0
