### ISSUE TITLE
chef/spec/data/ssl/chef-rspec.cert is about to expire

### ISSUE THREAD

**Issue by SpudNL** [chef/chef#9541]
## Description
Hello,

I got a notification from my monitoring system that the chef-rspec.cert is about to expire.
I'm wondering what the impact is going to be if this expires, and what to do about this. Sadly i have no experience with chef at all. Just trying to maintain the system. 

## Chef Version
Don't know where to find the version to be honest. 

## Platform Version
Oracle Linux Server release 7.7

## Replication Case
openssl x509 -in /opt/gitlab/embedded/lib/ruby/gems/2.3.0/gems/chef-13.6.4/spec/data/ssl/chef-rspec.cert -text -noout

## Client Output
Validity
            Not Before: Apr 10 19:11:31 2010 GMT
            Not After : Apr  7 19:11:31 2020 GMT

**Comment by lamont-granquist** [comment]
We're after that date, and nothing blew up.  Is this even necessary or is it just getting ignored by the tests?

**Comment by SpudNL** [comment]
Nope nothing blew up, all i did was just ignore that certificate for now until its patched or removed in future patches.

**Comment by kapilchouhan99** [comment]
I have check it, this certificate `chef/spec/data/ssl/chef-rspec.cert` is used in some of the test cases, how can we generate a new certificate, so that we can use a new certificate instead of the old ones. @lamont Please give me your thoughts on this.
