### ISSUE TITLE
Add resources for managing Chef Infra Client running on a schedule

### ISSUE THREAD

**Issue by tas50** [chef/chef#9545]
Users should be able to setup Chef Infra Client to run on a schedule out of the box without the need for cookbooks like chef-client or homegrown solutions.

Resources to add:

- [x] chef_client_cron
- [x] chef_client_scheduled_task
- [x] chef_client_systemd_timer
- [x] chef_client_launchd

Aha! Link: https://chef.aha.io/features/SH-116

**Comment by pschaumburg** [comment]
I think this is a great idea to implement this into the core of chef. 
So your idea is something like this?

```ruby
chef_client 'set my schedule' do
  cron '5 4 * * *'
  type 'cron'
  action :enable
end
```

**Comment by tas50** [comment]
@pschaumburg Pretty close. The first two are already merged in:

https://github.com/chef/chef/blob/master/lib/chef/resource/chef_client_cron.rb
https://github.com/chef/chef/blob/master/lib/chef/resource/chef_client_scheduled_task.rb

**Comment by pschaumburg** [comment]
Hm....can't we just easily move it into a single chef resource? So we don't have the need for changing every specified resource. Or am I wrong at some point?

**Comment by tas50** [comment]
There isn't really any overlap in the properties so it would be a mess. You'd have a single resource, but all the properties would be specific to the implementation. It would be easier from a documentation standpoint to read it as 4 different resources.

**Comment by pschaumburg** [comment]
Alright, got it :) Thank you for clarification on that.
