### ISSUE TITLE
Chef - Agent Version support for old versions that depends a cookbook. 

### ISSUE THREAD

**Issue by Doltair** [chef/chef#9547]
Is there a better recommendation to check the chef agent version on a node via metadata.rb? what we want is to support older chef agents while we do migrating them by batch to a newer and we the case is that the older version depends on a cookbook (in particular, its the chef_handler cookbook). The newer version of chef infra agent from 14 onward its already part as a chef resource and no longer depends on a cookbook. For what attempted, this is the code tried:

```
if "#{Chef::VERSION.split('.')[0]}" <= '13'
  depends 'chef_handler' 
end
```

**Comment by lamont-granquist** [comment]
No, metadata.rb is compiled to JSON so you can't usefully use `if` statements at all, for anything (and conditional dependency graphs based on the target chef-client version would make everything about dependency resolution and management quite crazy).  You'll need to have two different versions of the cookbook to be able to have entirely different dependent cookbooks based on which version you are on.  You may want to fork the cookbook entirely and abandon the old one depending on how complicated it is.
