### ISSUE TITLE
get GUID from DMI instead of creating it

### ISSUE THREAD

**Issue by btm** [chef/chef#9578]
### Describe the Enhancement:
We generate a random GUID which is sent to Automate as the unique ID for a node. This does not survive a reformat of a computer. It doesn't typically matter for disposable servers, but as a desktop administrator a laptop might want to be considered the same node even if it has to be reformatted (except if it is for a new user?)

Can we get a GUID from DMI?

This is a placeholder, more thoughts later.

**Comment by lamont-granquist** [comment]
GUIDs from hardware is also problematic if you ever swap out CPUs or ethernet cards, etc.

**Comment by btm** [comment]
@lamont-granquist I don't think dmi/system/uuid should change unless you swap a motherboard. I think we'd still want to write it to disk rather than look up every time. The biggest conceptual risk there would be if you took a motherboard out of a server for some reason, and it was still good, so you put it in another server but kept the first one. I guess that is real?

dmi/system/uuid is supposedly bogus sometimes though, so we'd have to filter that out.

**Comment by lamont-granquist** [comment]
You also have to consider systems from aix to solaris to raspberry pis.  You may not have DMI, may not have that DMI and that DMI value may not be sane.  There's going to be a lot of edge conditions.

**Comment by btm** [comment]
@lamont-granquist yes, many won't, but we would simply generate one if that information wasn't available.

If we don't have a guid on disk, then
  - look for a decent one in dmi/system/uuid
  - or generate one
write it to disk

This is primarily to benefit the desktop use case.

There's a separate related thread not discussed there about if inspec/chef should look for each others guid if they don't have one, so we can associate them in automate.

**Comment by btm** [comment]
I talked with some people about this idea and came to the conclusion that the benefits could be realized without the drawbacks if this was an Automate feature to identify two UUIDs that appear related (same serial number) and allowed them to be optionally linked.
