### ISSUE TITLE
Powershell_Package does not throw error when it cannot connect to powershell gallery

### ISSUE THREAD

**Issue by Xorima** [chef/chef#9610]
## Description
When using `powershell_package` chef marks the resource as (up to date) when it is not, if the client does not support tls 1.2 

## Platform Version
(2012, 2012R2 and 2016 do not by default)

## Replication Case
Try to install a powershell package with tls 1.2 disabled on the machine (IE a default windows vm) it will mark as up to date when an error is actually thrown

## Possible Fixes

To resolve this internally there are two options, one is invasive, one is not:

Putting this above the install-module line will allow it to run tls 1.2:
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

Alternatively settings the following registry keys will make powershell run tls 1.2 by default (It does turn off other ciphers such as sslv3 though):

```
registry_key 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\.NETFramework\\v4.0.30319' do
  values [{
    name: 'SchUseStrongCrypto',
    type: :dword,
    data: 1,
  }]
end
registry_key 'HKEY_LOCAL_MACHINE\\SOFTWARE\\Wow6432Node\\Microsoft\\.NETFramework\\v4.0.30319' do
  values [{
    name: 'SchUseStrongCrypto',
    type: :dword,
    data: 1,
  }]
end
```

**Comment by tas50** [comment]
I know that releng worked around issues with chocolatey and TLS 1.2 by forcing powershell to use 1.2. We'll want to use that path forward since we can't modify TLS settings host wide with the registry key.

**Comment by lamont-granquist** [comment]
yeah, we can't fiddle with the TLS settings in the registry key.  the other solution would be acceptable.

**Comment by Xorima** [comment]
I am fully happy with the `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12` method, I guess where should I be looking at when implementing this as it is getting really really needed.
