### ISSUE TITLE
yum_repository - Add support for reposdir

### ISSUE THREAD

**Issue by wildcrazyman** [chef/chef#9618]
### Describe the Enhancement:

Create .repo files in other locations then the default /etc/yum.repos.d/.  The main configs of yum.conf and dnf.conf supports reposdir=, where you can add or override the default location.

man info:
reposdir  Directories where yum should look for repository files with a .repo extension. The default directory is /etc/yum.repos.d.

Directory is hard coded in /provider/yum_repository.rb
declare_resource(:template, "/etc/yum.repos.d/#{new_resource.repositoryid}.repo") do

### Describe the Need:

Enterprise companies and users that specify other locations for .repo files.  Unknown number of users.

**Comment by tas50** [comment]
@wildcrazyman If you can open a PR to add this new property to the resource we can see about merging it in for Chef Infra Client 16.

**Comment by tas50** [comment]
@wildcrazyman  This will ship in 16.9 this week
