### ISSUE TITLE
Invalid UTF-8 string error in ruby_block when calling node.to_json

### ISSUE THREAD

**Issue by yangpeng-chn** [chef/chef#9637]
## Description
The following code cause error:
`Invalid UTF-8 string '���� (�W����)': cannot encode to UTF-8`

```
ruby_block 'save_node_attributes' do
  block do
    IO.write('C:/tmp/node-attribute.json', node.to_json) 
  end
end
```

## Chef Version
15.0.298

## Platform Version
platform=windows
platform_version=10.0.14393
Microsoft Windows Server 2016 Datacenter

## Replication Case
To generate the node attributes into a json file with node.json, an error occurs, and I have found from Chef Automate GUI that the following attribute is probably the one caused the error, I have no idea why it shows like this.

```
"time" :
{
"timezone" :
"���� (�W����)"
},
```

## Client Output
```
mynode.com   * ruby_block[save_node_attributes] action run
mynode.com
mynode.com     ================================================================================
mynode.com     Error executing action `run` on resource 'ruby_block[save_node_attributes]'
mynode.com     ================================================================================
mynode.com
mynode.com     Chef::Exceptions::JSON::EncodeError
mynode.com     -----------------------------------
mynode.com     Invalid UTF-8 string '���� (�W����)': cannot encode to UTF-8
mynode.com
mynode.com     Cookbook Trace:
mynode.com     ---------------
mynode.com     c:/chef/cache/cookbooks/sv_os_config/recipes/win_os_hardening.rb:18:in `block (2 levels) in from_fi
le'
```
## Stacktrace

Any workaround for this issue?

**Comment by lamont-granquist** [comment]
Use `Node#to_json(validate_utf8: false)` which will sanitize/scrub all non-utf8 strings in the input.

**Comment by yangpeng-chn** [comment]
> Use `Node#to_json(validate_utf8: false)` which will sanitize/scrub all non-utf8 strings in the input.

Thank you, the option worked, but it fails (wrong json format error) to read the json file in Inspec profiles with the code below,
I was wondering if there are any options for `node = json(attribute_file).params` to bypass the non-utf8 characters? As I tried to manually remove the non-utf8 characters from the json file, the code works.

```ruby
attribute_file = 'C:/tmp/node-attribute.json'
node = json(attribute_file).params
build_osset_dir = node['default']['os_config']['build_osset']
describe file(build_osset_dir) do
  it { should exist }
end
```
