### ISSUE TITLE
ssh: ed25519 keys fail to auth from Windows host. 

### ISSUE THREAD

**Issue by marcparadise** [chef/chef#9639]
## Description
When using a command such as `knife bootstrap` or `knife ssh` from a Windows host and providing an ed25519 key,  it fails as follows:

```
 C:\opscode\chef> .\bin\knife ssh -m 192.168.1.133 -x marc -i C:\Users\marc\Documents\id_ed25519
 - snip - 
OpenSSH keys only supported if ED25519 is available (NotImplementedError)
net-ssh requires the following gems for ed25519 support:
 * ed25519 (>= 1.2, < 2.0)
 * bcrypt_pbkdf (>= 1.0, < 2.0)
See https://github.com/net-ssh/net-ssh/issues/565 for more information
```

These gems are [both installed](https://github.com/chef/chef/blob/master/chef.gemspec#L36-L37) in the chef package; however on Windows the installation only includes platform native extension for rubies 2.0-2.3, and fails to load a non-existent 2.6 extension

This is because the gem download only contained native extensions for ruby 2.0-2-3.  The PR linked in comments extends this to 2.0->2.7.

 
## Chef Version
15.9.17 (earlier too) 

## Platform Version

Windows.* 

## Replication Case
1. Install chef-client
2. Generate an ed25519 key
3. Use this key to authenticate to a known-good host using `knife ssh`: 
`knife ssh -m HOST -x USER -i ED25519-KEY-PATH

## Client Output

See description.

**Comment by marcparadise** [comment]
This will be fixed by this PR, all that should be necessary is to bump the version we pull in: https://github.com/mfazekas/bcrypt_pbkdf-ruby/pull/2

**Comment by lamont-granquist** [comment]
1.1.0.rc1 is released

**Comment by tas50** [comment]
@marcparadise Can you test that using 1.1.0rc1 would fix this?
