### ISSUE TITLE
windows_firewall_rule support for multiple remote_address

### ISSUE THREAD

**Issue by smartynenko** [chef/chef#9711]
### Describe the Enhancement:
Unable to list multiple destinations as parameter for remote_address

### Describe the Need:
Allow remote_address to accept list of destinations as array type parameter (similar to ports)

### Current Alternative
There is no good alternative, except either using powershell script resource directly or declaring resource multiple times

**Comment by timbourne** [comment]
It looks like the New-NetFirewallRule supports arrays for remote_address like this:

New-NetFirewallRule -DisplayName "MyRule" -Protocol TCP -LocalPort 1434 -RemoteAddress @("10.17.3.101","172.7.7.53")

Can the windows_firewall_rule resource be updated to use that method?
