### ISSUE TITLE
Fix Windows unit tests to run properly in Buildkite

### ISSUE THREAD

**Issue by tas50** [chef/chef#9745]
Right now we run all our unit tests in Buildkite on Windows but we're not properly exiting on failure so there's a large number of failures that aren't being raised up. We need to fix the script that executes these tests to properly raise and we need to fix the tests / code to actually run on Windows.

**Comment by btm** [comment]
Was this fixed by https://github.com/chef/chef/pull/9752?

**Comment by tas50** [comment]
Sort of. They're just all failing now.

**Comment by btm** [comment]
Properly failing? :D

**Comment by tas50** [comment]
Depends on how you look at it
