### ISSUE TITLE
add a `gather-logs` command

### ISSUE THREAD

**Issue by moutons** [chef/chef#9748]
### Describe the Enhancement:
Add `gather-logs` subcommand to all of the top-level commands (e.g., `chef-client`, `knife`) under the chef/chef umbrella

### Describe the Need:
`gather-logs` is a command which Chef server products have implemented to bundle up useful troubleshooting information to be attached to support tickets. Although there are flags for log level and log location, it's quite challenging for the average user to get good troubleshooting information out of the client/workstation products, particularly `chef-client` and `knife`.

### Current Alternative
No, there's not really a current alternative. As I said above, the existing work to enable this is spotty and doesn't work well in practice.

### Can We Help You Implement This?:
I can write some of this, but I would need guidance on where the work should go.

**Comment by moutons** [comment]
one of the things that distinguishes the `gather-logs` commands from the log-level command is not only the debug or trace level output, but also system information, like rudimentary network information and platform information. log-level debug information from chef-client or knife would be a component of the output bundle.

**Comment by moutons** [comment]
@chef/support-team FYI

**Comment by tas50** [comment]
@moutons This should really be directed through AHA and not github.

**Comment by moutons** [comment]
This way I've got a reminder to work on it @tas50, I don't expect y'all to do the work since it's primarily to improve Support's workflows. As I mentioned, mainly I want to make sure that we're putting the work in the client in a way that's not going to make things harder for y'all.

**Comment by lamont-granquist** [comment]
How do you expect this to work?  `knife gather-logs <node>`?  that'll need to be train-ified and work over ssh and winrm.  As a local command to run that's just not our typical API.  Users may also have directed log output at syslog to some random directory or external syslog service.  I don't think this is as easy to write against the client because the client is much more of an app, and less appliance-like compared to the server.

**Comment by moutons** [comment]
What we're working on is building a gather-logs bundle for the client, not for any server product which it might be connecting to.

The output of chef-client or knife run at debug log level is often helpful, but it doesn't give all of the output we need for troubleshooting client-side issues and we're frequently relying on prior experience and assumptions about their node's configuration when suggesting next steps.

**Comment by moutons** [comment]
As for the log output issue, if the command is internal to knife or chef-client, we should be able to pass configuration for that run to add another log output stream for that execution only, right?

I know how to do it for chef-client already, but I haven't figured out how to do it for knife yet.

**Comment by tas50** [comment]
I'm going to close this out since this is something that support is going to have to lead. If something is designed and submitted as a PR that's fine, but it's not really going to get prioritized via GH.
