### ISSUE TITLE
dnf_package (and most likely yum_package) issues with version property

### ISSUE THREAD

**Issue by lamont-granquist** [chef/chef#9763]
These all work correctly:

```
dnf_package "zabbix-agent-4.0.15"
dnf_package "zabbix-agent-4.0*"
dnf_package "zabbix-agent-4.0.15-1.fc31"
dnf_package "zabbix-agent-4.0*-1.fc31"
dnf_package "zabbix-agent-4.0.15-*"
dnf_package "zabbix-agent-4.0*-*"
dnf_package "zabbix-agent-1:4.0.15"
dnf_package "zabbix-agent-1:4.0.*"
dnf_package "zabbix-agent-1:4.0.15-1.fc31"
dnf_package "zabbix-agent-1:4.0*-1.fc31"
dnf_package "zabbix-agent-*:4.0.15-*"
dnf_package "zabbix-agent-*:4.0*-*"
```

These do all do not work (but correctly so):

```
#dnf_package "zabbix-agent-4.0"
#dnf_package "zabbix-agent-4.0.15-1"
#dnf_package "zabbix-agent-1:4.0.15-1"
#dnf_package "zabbix-agent-*:4.0.15-1"
#dnf_package "zabbix-agent-*:4.0.15-1.fc31"
```

The CLI does not support those five either:

```
[root@default-fedora-latest vagrant]# dnf install zabbix-agent-4.0
Last metadata expiration check: 0:20:31 ago on Wed 29 Apr 2020 01:09:14 AM UTC.
No match for argument: zabbix-agent-4.0
Error: Unable to find a match: zabbix-agent-4.0
[root@default-fedora-latest vagrant]# dnf install zabbix-agent-4.0.15-1
Last metadata expiration check: 0:20:37 ago on Wed 29 Apr 2020 01:09:14 AM UTC.
No match for argument: zabbix-agent-4.0.15-1
Error: Unable to find a match: zabbix-agent-4.0.15-1
[root@default-fedora-latest vagrant]# dnf install zabbix-agent-1:4.0.15-1
Last metadata expiration check: 0:20:44 ago on Wed 29 Apr 2020 01:09:14 AM UTC.
No match for argument: zabbix-agent-1:4.0.15-1
Error: Unable to find a match: zabbix-agent-1:4.0.15-1
[root@default-fedora-latest vagrant]# dnf install 'zabbix-agent-*:4.0.15-1'
Last metadata expiration check: 0:21:06 ago on Wed 29 Apr 2020 01:09:14 AM UTC.
No match for argument: zabbix-agent-*:4.0.15-1
Error: Unable to find a match: zabbix-agent-*:4.0.15-1
[root@default-fedora-latest vagrant]# dnf install 'zabbix-agent-*:4.0.15-1.fc31'
Last metadata expiration check: 0:21:16 ago on Wed 29 Apr 2020 01:09:14 AM UTC.
No match for argument: zabbix-agent-*:4.0.15-1.fc31
Error: Unable to find a match: zabbix-agent-*:4.0.15-1.fc31
```

When used as a version property the only use case which works entirely correctly is the fully specified case:

```
dnf_package "zabbix-agent" do
  version "1:4.0.15-1.fc31"
end
```

When used as a version property the following use case crash hard:

```
dnf_package "zabbix-agent" do
  version "*:4.0.15-*"
end

dnf_package "zabbix-agent" do
  version "-*:4.0*-*"
end
```

The exception is probably fixable and is:

```
[2020-04-29T01:35:31+00:00] FATAL: RuntimeError: dnf_package[zabbix-agent] ((chef-apply cookbook)::(chef-apply recipe) line 7) had an error: RuntimeError: dnf-helper.py had stderr/stdout output:

Traceback (most recent call last):
  File "/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/provider/package/dnf/dnf_helper.py", line 166, in <module>
    query(command)
  File "/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/provider/package/dnf/dnf_helper.py", line 101, in query
    q = q.filterm(epoch=int(command['epoch']))
ValueError: invalid literal for int() with base 10: '-*'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/chef/embedded/lib/ruby/gems/2.7.0/gems/chef-16.0.257/lib/chef/provider/package/dnf/dnf_helper.py", line 173, in <module>
    base.closeRpmDB()
AttributeError: 'Base' object has no attribute 'closeRpmDB'
```

When used as a version property the following uses cases appear to work but are not idempotent:

```

dnf_package "zabbix-agent" do
  version "4.0.15"
end

dnf_package "zabbix-agent" do
  version "4.0*"
end

dnf_package "zabbix-agent" do
  version "4.0.15-1.fc31"
end

dnf_package "zabbix-agent" do
  version "4.0*-1.fc31"
end

dnf_package "zabbix-agent" do
  version "4.0.15-*"
end

dnf_package "zabbix-agent" do
  version "4.0*-*"
end

dnf_package "zabbix-agent" do
  version "1:4.0.15"
end

dnf_package "zabbix-agent" do
  version "1:4.0.*"
end

dnf_package "zabbix-agent" do
  version "1:4.0*-1.fc31"
end
```

Tested On:  Fedora release 31 (Thirty One)

Client version: Chef Infra Client: 16.0.257

Aha! Link: https://chef.aha.io/features/SH-111

**Comment by Swampcritter** [comment]
I can confirm this is also happening under Chef with yum_package, rpm_package and the newer 'package' resource as well under Chef Habitat.

Both of these Chef recipes fail:

package 'NessusAgent' do 
  source "#{Chef::Config[:file_cache_path]}/NessusAgent-7.4.3-es7.x86_64.rpm" 
  version '7.4.3-es7' 
  action :install 
  flush_cache [ :before ]
end

-AND-

package 'NessusAgent-7.4.3-es7.x86_64' do 
  source "#{Chef::Config[:file_cache_path]}/NessusAgent-7.4.3-es7.x86_64.rpm" 
  action :install 
  flush_cache [ :before ]
end

Per chef-stacktrace.out, error is showing up through the ShellOut command:

>>>> Caused by Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of rpm -qp --queryformat '%{NAME} %{EPOCH} %{VERSION} %{RELEASE} %{ARCH}
' /hab/svc/wabtec_base_tools/data/cache/cache/NessusAgent-7.4.3-es7.x86_64.rpm ----
STDOUT:
STDERR: rpm: unrecognized option: -

For debugging purposes, I ran the rpm queryformat at the command line to see what it sees:

>> rpm -qp --queryformat '%{NAME} %{EPOCH} %{VERSION} %{RELEASE} %{ARCH}\n' NessusAgent-7.4.3-es7.x86_64.rpm
NessusAgent (none) 7.4.3 es7 x86_64

It seems that the %{EPOCH} is deeming the (none) as a null value, but since it cannot query against it, the rpm command fails.

**Comment by lamont-granquist** [comment]
@Swampcritter that has nothing to do with this issue, please cut a separate issue for tracking that.

**Comment by ricsil** [comment]
Can confirm yum_package has similar issues.

```
package 'package_name' do
  version config['version']
end
```

will constantly install if `config['version']` is missing iteration, as in `20.0.1` vs `20.0.1-1`.
