### ISSUE TITLE
file resource fails to update across filesystem devices (EXDEV, ETXTBSY)

### ISSUE THREAD

**Issue by jasimmons** [chef/chef#9768]
## Description

When attempting to update a binary file (in my case via `remote_file`, but being a derivative of `file` I assume the problem would exist there as well), if that file is on a different filesystem device than that of the tempfile which Chef creates, the Chef run will fail with `Errno::ETXTBSY`.

Failure seen with `strace`, showing it's in the [`::FileUtils.mv`](https://github.com/chef/chef/blob/v12.21.14/lib/chef/file_content_management/deploy/mv_unix.rb#L71) call, which does a `rename`, erroring on `Invalid cross-device link` and then `Text file busy`:

```
13569 rename("/tmp/chef-rest20200429-46598-1y6743b", "/opt/service/bin/service") = -1 EXDEV (Invalid cross-device link)
13569 openat(AT_FDCWD, "/opt/service/bin/service", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0100755) = -1 ETXTBSY (Text file busy)
```

## Chef Version

12.21.14

## Platform Version

Ubuntu 18.04.3 LTS

## Replication Case

Assuming:
1. A device mounted to `/opt`, separate from the device where Chef stores tempfiles.
2. A binary on that device,  at `/opt/service/bin/service`.
3. Execution of that binary (e.g. upstart, systemd, or just running it in the background).
4. Run `chef-client` with a recipe which would replace that binary:
    ```ruby
    remote_file '/opt/service/bin/service' do
      source 'http://some_url/path/to/binary'
      mode 0755
    end
    ```

## Client Output

```
  * remote_file[/opt/service/bin/service] action create

    ================================================================================
    Error executing action `create` on resource 'remote_file[/opt/service/bin/service]'
    ================================================================================

    Errno::ETXTBSY
    --------------
    Text file busy @ rb_sysopen - /opt/service/bin/service
```

## Stacktrace

```
>>>> Caused by Errno::EXDEV: Invalid cross-device link @ rb_file_s_rename - (/tmp/chef-rest20200429-46598-1y6743b, /opt/service/bin/service)
/opt/chef/embedded/lib/ruby/2.3.0/fileutils.rb:529:in `rename'
/opt/chef/embedded/lib/ruby/2.3.0/fileutils.rb:529:in `block in mv'
/opt/chef/embedded/lib/ruby/2.3.0/fileutils.rb:1572:in `block in fu_each_src_dest'
/opt/chef/embedded/lib/ruby/2.3.0/fileutils.rb:1588:in `fu_each_src_dest0'
/opt/chef/embedded/lib/ruby/2.3.0/fileutils.rb:1570:in `fu_each_src_dest'
/opt/chef/embedded/lib/ruby/2.3.0/fileutils.rb:518:in `mv'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.14/lib/chef/file_content_management/deploy/mv_unix.rb:71:in `deploy'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.21.14/lib/chef/provider/file.rb:389:in `update_file_contents'
...
```

**Comment by lamont-granquist** [comment]
* check that `Chef::Config[:file_staging_uses_destdir]` is set to `:auto` and fix that if it is not
* check that `/opt/service/bin` exists and that there's no other issues with using that as a tempfile location
* if you can't fixing writing to `/opt/service/bin` then you need to manually set `atomic_updates false` on the resource to avoid doing the mv
* please update your chef client, it is EOL we aren't fixing bugs or accepting bug reports for it.
