### ISSUE TITLE
dnf_package with exlude option

### ISSUE THREAD

**Issue by boniek83** [chef/chef#9779]
## Description
When yum repository definition includes _exclude_ I have problems when installing packages from this repo using chef.

## Chef Version
16.0.257

## Platform Version
Fedora 32

## Replication Case
Create yum repo (from official kubernetes install guide):
> yum_repository 'kubernetes' do
    baseurl 'https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch'
    gpgkey 'https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg'
    exclude 'kubelet kubeadm kubectl'
    repo_gpgcheck true
    enabled false
    action :create
end

Try to install package:

> ['kubelet','kubeadm','kubectl'].each do |p|
  package p do
    options '--disableexcludes=kubernetes --enablerepo=kubernetes'
  end
end

It fails.

Raw dnf command:
> dnf install kubelet --disableexcludes=kubernetes --enablerepo=kubernetes

works.

## Client Output
https://gist.github.com/boniek83/197021fbe92e2325868f6fbaab49d7ec
## Stacktrace
https://gist.github.com/boniek83/5ef42e4b2bacb939e8da1cd08ed12a5f

**Comment by lamont-granquist** [comment]
This is basically a dup of #2728
