### ISSUE TITLE
chef_client_cron creates log dir with wrong permissions.

### ISSUE THREAD

**Issue by jimwise** [chef/chef#9780]
Permissions should be '0750', as this is a directory.

https://github.com/chef/chef/blob/f7cb3c30b6b032e30a532f88f1daaa8bed31fc0e/lib/chef/resource/chef_client_cron.rb#L146

Also, better to use 'not_if' instead of wrapping resource in unless.

**Comment by tas50** [comment]
This is fixed now on master. The conditional around the resource is intentional and preferred here since it avoids excessive logging for a resource we only want to fire once. not_if and only_if area very noisy in logs.
