### ISSUE TITLE
cron_access resource: support for non-Linux platforms

### ISSUE THREAD

**Issue by aklyachkin** [chef/chef#9785]
### Describe the Enhancement:
cron_access resource manages the files cron.allow and cron.deny. As for now the paths to these files are hard-coded in the resource and Linux-specific. 

The paths to the files on AIX are /var/adm/cron/cron.allow and /var/adm/cron/cron.deny. See - https://www.ibm.com/support/knowledgecenter/ssw_aix_72/c_commands/crontab.html

On Solaris - /etc/cron.d/cron.allow and /etc/cron.d/cron.deny. See https://docs.oracle.com/cd/E23824_01/html/821-1451/sysrescron-23.html

### Describe the Need:
Support for other platforms.

### Current Alternative
Use cookbook_file

### Can We Help You Implement This?:
Pull request follows...

**Comment by tas50** [comment]
This shipped
