### ISSUE TITLE
"Remove failed: No such file or directory" installing chef in place

### ISSUE THREAD

**Issue by jtimberman** [chef/chef#9799]
@tas50 asked that I open this issue. I'm seeing this output on CentOS 7 systems where I installed Chef 16.0.275 in place over 16.0.257.

https://gist.github.com/jtimberman/20e3683d8cc1c425542f483605644706

**Comment by tas50** [comment]
I tried to reproduce this one with installs in a few different ways and I'm not able to get the same errors. I'm going to close this one out at this point.
