### ISSUE TITLE
windows_package fails due to version property as String when package is installed

### ISSUE THREAD

**Issue by Tensibai** [chef/chef#9806]
## Description

Follow up on #9770 

Due to the enforcement of single version package and the way load_current_resource is done, populating the version property fails when a package is already installed.

The current resource version property is done here https://github.com/chef/chef/blob/7235856d859bbb32482b3f3b12f758b63a0eb8eb/lib/chef/provider/package/windows.rb#L65-L66

With the version property being defined as String since [this MR](https://github.com/chef/chef/commit/6ed90220893285f80513c6155620ebd0d2fbda1e#diff-3c9b1a519cef717fb2fa5d2f52a30477) 

Both msi and exe provider used in `package_provider.installed_version` can ends up returning an array with map(..).uniq:

 - https://github.com/chef/chef/blob/7235856d859bbb32482b3f3b12f758b63a0eb8eb/lib/chef/provider/package/windows/exe.rb#L93-L98:

- https://github.com/chef/chef/blob/7235856d859bbb32482b3f3b12f758b63a0eb8eb/lib/chef/provider/package/windows/msi.rb#L48-L59

## Chef Version
16.0.275

## Platform Version
Non relevant

## Replication Case
Converge twice with a windows_package resource, the second run will fail.

## Client Output
```
================================================================================
    Error executing action `install` on resource 'windows_package[Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.40660]'
    ================================================================================
    Chef::Exceptions::ValidationFailed
    ----------------------------------
    Property version must be one of: String!  You passed ["12.0.40660.0"].
    Resource Declaration:
    ---------------------
    # In c:/chef/local-mode-cache/cache/cookbooks/vcruntime/recipes/vc12.rb
     24:     windows_package node['vcruntime']['vc12']['x64'][node['vcruntime']['vc12']['version']]['name'] do
     25:       checksum node['vcruntime']['vc12']['x64'][node['vcruntime']['vc12']['version']]['sha256sum']
     26:       source node['vcruntime']['vc12']['x64'][node['vcruntime']['vc12']['version']]['url']
     27:       installer_type :custom
     28:       returns [0, 3010]
     29:       options '/q'
     30:     end
     31:     windows_package node['vcruntime']['vc12']['x86'][node['vcruntime']['vc12']['version']]['name'] do
    Compiled Resource:
    ------------------
    # Declared in c:/chef/local-mode-cache/cache/cookbooks/vcruntime/recipes/vc12.rb:24:in `from_file'
    windows_package("Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.40660") do
      package_name "Microsoft Visual C++ 2013 Redistributable (x64) - 12.0.40660"
      action [:install]
      default_guard_interpreter :default
      declared_type :windows_package
      cookbook_name "vcruntime"
      recipe_name "vc12"
      source "https://download.microsoft.com/download/0/5/6/056DCDA9-D667-4E27-8001-8A0C6971D6B1/vcredist_x64.exe"
      installer_type :custom
      options "/q"
      checksum "20e2645b7cd5873b1fa3462b99a665ac8d6e14aae83ded9d875fea35ffdd7d7e"
      returns [0, 3010]
    end
```

## Stacktrace
N/A

**Comment by haidars** [comment]
Hi, 

I got exactly the same error today and  came to raise the same issue.

`
 Recipe: win-lbntools::default
         * windows_package[WinAgents EventLog Translation Service] action remove

           ================================================================================
           Error executing action `remove` on resource 'windows_package[WinAgents EventLog Translation Service]'
           ================================================================================

           Chef::Exceptions::ValidationFailed
           ----------------------------------
           Property version must be one of: String!  You passed ["1.5"].

           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/win-lbntools/recipes/default.rb

            37:     package node['winagent']['program_name'] do
            38:       installer_type  :custom
            39:       #source          node['winagent']['repo_url']
            40:       action          :remove
            41:       version         'abc'
            42:       options         ' /quiet /passive /norestart'
            43:       only_if         { node['winagent']['uninstall'] }
            44:     end
            45:   end

           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/win-lbntools/recipes/default.rb:37:in `from_file'

           windows_package("WinAgents EventLog Translation Service") do
             package_name "WinAgents EventLog Translation Service"
             action [:remove]
             default_guard_interpreter :default
             declared_type :package
             cookbook_name "win-lbntools"
             recipe_name "default"
             version "abc"
             options " /quiet /passive /norestart"
             installer_type :custom
             only_if { #code block }
           end

           System Info:
           ------------
           chef_version=16.0.275
           platform=windows
           platform_version=10.0.14393
           ruby=ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x64-mingw32]
           program_name=C:/opscode/chef/bin/chef-client
           executable=C:/opscode/chef/bin/chef-client


       Running handlers:
       [2020-05-06T12:42:03+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2020-05-06T12:42:03+00:00] ERROR: Exception handlers complete
       Chef Infra Client failed. 0 resources updated in 19 seconds
       [2020-05-06T12:42:03+00:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2020-05-06T12:42:03+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2020-05-06T12:42:03+00:00] FATAL: Chef::Exceptions::ValidationFailed: windows_package[WinAgents EventLog Translation Service] (win-lbntools::default line 37) had an error: Chef::Exceptions::ValidationFailed: Property version must be one of: String!  You passed ["1.5"].
`

And also it ignore the property version of the resource windows_package

```
`
            37:     package node['winagent']['program_name'] do
            38:       installer_type  :custom
            39:       #source          node['winagent']['repo_url']
            40:       action          :remove
            **41:       version         'abc'**
            42:       options         ' /quiet /passive /norestart'
            43:       only_if         { node['winagent']['uninstall'] }
            44:     end
            45:   end
` 


```

The same code work well with version 14 and 15

**Comment by tas50** [comment]
Fixed in current. Release incoming. Thanks for the report @Tensibai

**Comment by cookiecurse** [comment]
Hey @tas50 do we know a date when we can expect the release by any chance? Sorry, we are kind of dead in the water on this resource until the fixes get released :)
