### ISSUE TITLE
Issue with pinning a version

### ISSUE THREAD

**Issue by cookiecurse** [chef/chef#9840]
## Description
I have a cookbook that I am trying to pin a version to, but I get an error. 16.0.275 should exist: https://github.com/chef/chef/blob/master/RELEASE_NOTES.md

## Replication Case
In metadata set this:

```
chef_version '= 16.0.275' 
depends 'audit', '~> 9.0'
depends 'chef-client', '~> 11.4.0'
```

## Client Output
```
FATAL: Chef::Exceptions::CookbookChefVersionMismatch: Cookbook 'mycookbook' version '1.2.3' depends on Chef Infra Client version ["= 16.0.275"], but the running Chef Infra Client version is 16.0.257
```

**Comment by tas50** [comment]
This is just telling you that you need to actually update the chef-client release on your system. It's working as expected to tell you that this cookbook requires 16.0.275 and won't work on 16.0.257
