### ISSUE TITLE
[tracking] Functional tests for windows_service habitat build

### ISSUE THREAD

**Issue by TheLunaticScripter** [chef/chef#9841]
## Description
Currently, the habitat builds are failing the functional tests for the windows_service.

Aha! Link: https://chef.aha.io/features/SH-112

**Comment by btm** [comment]
Fixed by https://github.com/chef/chef/pull/10070.

**Comment by OBrienCommaJosh** [comment]
Comment added by Bryan McLellan in Aha! - [View](https://chef.aha.io/comments/6844928295536577999)

Hab Infra Windows packages are passing habitat/test again after [chef#10070,](https://github.com/chef/chef/pull/10070) and promoting to current.
