### ISSUE TITLE
Move Windows testers to Ruby 2.7

### ISSUE THREAD

**Issue by tas50** [chef/chef#9853]
Our windows testers are still running Ruby 2.6. In order to complete this we need to be able to do the following:

- Run Ruby 2.7 on an Windows AMI
- Run Ruby 2.6 on an Windows AMI
- Run Ruby 2.7 on a Windows docker container
- Run Ruby 2.6 on a Windows docker container

If we had an AMI that included both 2.6 and 2.7 and allowed us to switch between the two that would be fine. For the containers, it might be best to have two different containers since the pull time increases with the size of Ruby

Once we have the images in place we can work to update our verify pipeline setup to use those.

**Comment by christopher-snapp** [comment]
Added Windows 2019 docker images with Ruby 2.6.6 and 2.7.1 versions via this PR:

https://github.com/chef/rubydistros/pull/4

Docker images were built and deployed to dockerhub and added to Chef master via this PR:

https://github.com/chef/chef/pull/9877

**Comment by christopher-snapp** [comment]
I'm pretty sure we're good to move forward with only using docker images rather than requiring any AMI modifications, but let me know if I'm missing something.

**Comment by christopher-snapp** [comment]
ruby 2.6 + 2.7 are now baked into the windows 2019 ami and are activated using `uru 266` or `uru 271` in the verify pipeline
