### ISSUE TITLE
Add Test Kitchen testing on Windows

### ISSUE THREAD

**Issue by tas50** [chef/chef#9854]
We need to make sure we're testing each PR on Windows the same way we test it on Linux.

**Comment by tas50** [comment]
It looks like BTM is working on adding this via a private verify pipeline, but ideally we figure out how to run this similar to how we do our existing Linux stuff so that we can run it on each PR and without the need for spinning up systems. This is the long term solution. Spinning up some azure boxes gets us testing today.

**Comment by btm** [comment]
Yup, added an Azure based instance in verify/private in #9857 and #9862.. That had to be on the private side to get access to our Azure credentials in the vault. We can start nailing down what coverage we want now for whatever improvement comes later.

**Comment by tas50** [comment]
I think we can close this out since phase 1 is done.
