### ISSUE TITLE
Add new 'toml_file' resource

### ISSUE THREAD

**Issue by mattray** [chef/chef#9911]
A resource for writing out [TOML](https://github.com/toml-lang/toml) files would replace many of the use of templates or the `file` resource to write these out. It would be an extension of the `file` resource, replacing the `content` with a hash and keeping all the existing properties.

## Motivation

As a user, I want to pass a hash of attributes to a `toml_file` resource and have it render them appropriately.

## Specification

```
a = {
    'golf': 'hotel',
    'india': {
        'juliett': true
        },
    'alpha': {
        'charlie': 'delta',
        'bravo': 10,
        },
    'echo': 'foxtrot'
    }

toml_file '/tmp/file.toml' do
    content a
end
```

produces the file `/tmp/file.toml`
```
echo = "foxtrot"
golf = "hotel"
[alpha]
bravo = 10
charlie = "delta"
[india]
juliett = true
```

**Comment by mattray** [comment]
Example implementation with tests here: https://github.com/mattray/toml-cookbook

**Comment by lamont-granquist** [comment]
If you're going to do this it'd be better to actually subclass the File class for this one, which eliminates all of the boilerplate code.

It also feels like this is a bit too trivial, you've got literally one line of code in here.  While the cost is that this is yet another resource in the docs.  I'm not sure that's worth it just so people don't have to write `content TomlRB.dump(content)`.

I think I'd rather push that into a property of the file resource itself (toml_content or whatever).  Although I'm not sure how that'd behave when inherited by the remote_file resource and I just woke up...

**Comment by lamont-granquist** [comment]
I think I'd rather seem some kind of DSL sugar added:

```
hash = { ... }
file "/etc/whatever.xyz" do
  content render_toml(hash)
end
```

**Comment by mattray** [comment]
I agree that the implementation for this (and the YAML and JSON variants) will all subclass File, they're intended to be "batteries included" approaches. I wanted to avoid "DSL sugar" because that implies that the user has to know about Ruby. My goal was for a user to populate some attributes in a Policyfile and have them rendered as TOML.

**Comment by lamont-granquist** [comment]
> because that implies that the user has to know about Ruby

Except that the `render_toml` call in my example isn't any more ruby than your file resources are.

**Comment by lamont-granquist** [comment]
I'm really very, very hard "NO" on doing this any way other than the DSL helper to be abundantly clear.

**Comment by lytao** [comment]
I tend to use the `file` resource to write contents to toml. However, the problem is, I see the gem tomlrb didn't get updated in the past chef infra client releases, and it is lacking of of the feature to write hash in toml format (render_toml call in the above example). I am happy to see the gem is still in maintainence recently, but just sad that it is design as only a parser.

I see another one having the dumper feature: https://rubygems.org/gems/toml-rb/, maybe it is worth to include it in chef infra client, or just replace tomlrb.

**Comment by tas50** [comment]
render_toml has been added for 17.3
