### ISSUE TITLE
Add new 'json_file' resource

### ISSUE THREAD

**Issue by mattray** [chef/chef#9913]
A resource for writing out JSON files would replace many of the use of templates or the `file` resource to write these out. It would be an extension of the `file` resource, replacing the `content` with a hash and keeping all the existing properties.

## Motivation

As a user, I want to pass a hash of attributes to a `json_file` resource and have it render them appropriately.

## Specification

```
a = {
    "golf": "hotel",
    "kilo": ["lima", "mike", "november"],
    "india": {
        "juliett": true
        },
    "alpha": {
        "charlie": "delta",
        "bravo": 10,
        },
    "echo": "foxtrot"
    }

json_file '/tmp/file.json' do
    content a
end
```
produces the file `/tmp/file.json`
```
{
  "alpha": {
    "bravo": 10,
    "charlie": "delta"
  },
  "echo": "foxtrot",
  "golf": "hotel",
  "india": {
    "juliett": true
  },
  "kilo": [
    "lima",
    "mike",
    "november"
  ]
}
```

**Comment by lamont-granquist** [comment]
closing to track in #9911

**Comment by tas50** [comment]
a new helper for handling this has been added for 17.3
