### ISSUE TITLE
chef_client_scheduled_task frequency_modifier default is problematic for daily, weekly, or even hourly schedules

### ISSUE THREAD

**Issue by chef-davin** [chef/chef#9918]
### Describe the Enhancement:

The new `chef_client_scheduled_task` resource is awesome.  The only issue I've found is with the default frequency modifier.  Having a modifier of 30 is great when you're using the default frequency of minutes, but it's awful when you try to use daily, weekly, or monthly, or hourly.  Ideally you should only need to use this parameter when you need an odd schedule (like bi-weekly, every other day, etc...).  Can this be adjusted to only be 30 when the default "minutes" frequency is used, and left at 1 otherwise?

### Describe the Need:

After setting up a scheduled task with the following code and running chef-client, you'll see that the next chef-client run will be 3am in a month.  The expected result of this resource block would be 3am the next day.

```ruby
chef_client_scheduled_task 'Run chef-client in audit mode' do
  start_time '03:00'
  frequency 'daily'
  splay 600
  daemon_options ['-n audit_only']
end
```

### Current Alternative

Obviously, you can adjust the frequency_modifier parameter, but I think this resource would be much more intuitive if we just put a little logic in the resource.  Something like
`if new_resource.frequency != minutes` that would then differentiate the default for minutes (30) and everything else (1)

```ruby
chef_client_scheduled_task 'Run chef-client in audit mode' do
  start_time '03:00'
  frequency 'daily'
  frequency_modifier 1
  splay 600
  daemon_options ['-n audit_only']
end
```

### Can We Help You Implement This?:

I'll try to create a pull request for this. I don't believe I'll need help with it, but will reach out if I do.

**Comment by phiggins** [comment]
Fixed in #9920.
