### ISSUE TITLE
dnf package resource version comparison failures.

### ISSUE THREAD

**Issue by epilatow** [chef/chef#9940]
While using a recent snapshot of the chef dnf package provider ([3494a29604b7719ab640a325becabbcdc57a7bce](https://github.com/chef/chef/pull/9500)) I saw chef failing to upgrade rpm packages when it should have. The failures occurred on Centos 8 with Chef 13.10 (after I monkeypatched in the aforementioned new dnf package provider into it).

Looking at one specific failure scenario, the following package was installed on a machine: grub2-efi-x64-2.02-78.el8.x86_64.rpm. In chef there was a "grub2-efi-x64" package resource that specified the following version: 2.02-78.el8_1.1

But when chef ran it did not upgrade the installed package. Doing a debug chef run I tracked the problem down to versioncompare in dnf_helper.py. The problem can be reproduced with the following dnf_helper.py invocation (which mirrors what chef was doing):

    echo '{"action": "versioncompare", "versions": ["1:2.02-78.el8.x86_64","1:2.02-78.el8_1.1"]}' | /usr/libexec/platform-python ~/dnf_helper.py 2>&1 | head -1

If you run this command (as root) you'll get an output of 0, saying that these two version strings are equal, when they are clearly not. This failure occurs because dnf_helper.py has been asked to do the impossible. It's been asked to parse and compare EVRs and EVRAs without knowing which it has been given. (As a simple example, imagine being given the following string: 1:2.02-78.el8. Is this an EVR or an EVRA? Now assume the existence of an el8 architecture and attempt to answer the question again.)

For dnf_helper.py versioncompare to work successfully it must know the type of version input strings (EVR or EVRA) that it is dealing with.

It's worth noting that this problem doesn't occur if, instead of using the package resource version property, we instead include a NEVR in the package resource package_name property. This is because, in this scenario chef doesn't detect the existing installed package, so it never invokes versioncompare to do version comparisons.

**Comment by lamont-granquist** [comment]
closing as dup of #9763 and #9847
