### ISSUE TITLE
MacOS 10.14:

### ISSUE THREAD

**Issue by shamangar-lab** [chef/chef#9945]
MacOS 10.14: 
```
$ knife --version
Chef Infra Client: 15.8.23
$ knife bootstrap ndnd -U mattray
Connecting to ndnd
WARNING: Failed to authenticate mattray to ndnd - trying password auth
Enter password for mattray@ndnd.
```

Debian Linux 10
```
$ knife --version
Chef Infra Client: 15.8.23
$ knife bootstrap ndnd -U mattray
Connecting to ndnd
WARNING: Failed to authenticate mattray to ndnd - trying password auth
Enter password for mattray@ndnd.
```

_Originally posted by @mattray in https://github.com/chef/chef/issues/8746#issuecomment-587987597_

**Comment by shamangar-lab** [comment]
I have same issue, Anybody any idea to solve this issue

**Comment by tas50** [comment]
@shamangar-lab 15.8 is a pretty old release. We've fixed a lot of bootstrap issues since that time including the issue that @mattray is commenting on. You'll want to upgrade to a newer release of Workstation or chef-client to get the latest fixes.
