### ISSUE TITLE
yum_package showing wrong version of package when EPOCH specified

### ISSUE THREAD

**Issue by aleksey-hariton** [chef/chef#9965]
## Description

Chef client showing misleading information about package version with package have EPOCH in metadata. On instance with already installed docker-ce 19.03.9-3.el7 package:

```
         * yum_package[docker-ce] action install
           - install version 19.03.9-3.el7 of package docker-ce-cli
```

Message is misleading because:
1. Package already installed
2. yum_package installing package version `3:19.03.9-3.el7` (epoch in the beginning).

## Chef Version

All chef versions

## Replica case

On CentOS install any package with EPOCH != 0 in metadata, for example official Docker CE package - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-19.03.9-3.el7.x86_64.rpm

**Comment by lamont-granquist** [comment]
This is ultimately a dup of #9763
