### ISSUE TITLE
Educational : How to find out any fix is done on which release

### ISSUE THREAD

**Issue by dheerajd-msys** [chef/chef#9999]
_**git tag helps us find these :**_

Sometimes `git sha's` change on merge if github does a rebase which some people do, so:
looking at https://github.com/chef/knife-windows/pull/500/commits, I see the commit text for this fix was "Fixed Exception: NameError: uninitialized constant Chef::Knife::Winrm"
I look at git log for knife-windows and see in master that commit was c66c7b6 (is the same commit sha from the branch)

>> git tag --contains c66c7b6
v3.0.17
v4.0.0
v4.0.1
v4.0.2

So I can say to someone that bug was fixed in v3.0.17+

Looking at https://rubygems.org/gems/knife-windows, I can see all 4 of those version numbers were released as gems. (promoted using expeditor).

`git blame components/gems/Gemfile.lock` in chef-workstation lets me see when different gems were updated in workstation.

I can see this line:
```b6a5b3106 (Tim Smith        2020-06-01 08:44:17 -0700  596)     knife-windows (4.0.2)```

If I git show b6a5b3106 I can see what the previous version was, which was 3.0.17, which did have the fix as well.

So then I `git blame b6a5b3106^1 -- components/gems/Gemfile.lock`  in workstation again. The `^1` after the SHA is a shortcut that means "_I want the commit before this work_" so what we're staying here is showing me that file before that commit. The `--` tells git that what comes after is the filename

Now I see:
```809b0caaf (Tim Smith        2020-05-17 12:13:22 -0700  596)     knife-windows (3.0.17)```

If I git show 809b0caaf , I see that the previous version was 3.0.16, which was before the fix. but to be clear 809b0caaf, bumped it to 3.0.17 which has the fix. so 809b0caaf "fixed" knife-windows in the workstation.

Now I use git tag --contains 809b0caaf in workstation.

>> git tag --contains 809b0caaf
20.5.42
20.5.43
...

There are a bunch of versions listed. I snipped them. sometimes the sorting isn't numeric so you have to be careful to find the latest version. (*note below)

So in this case any build of chef-workstation 20.5.42 and later should fix https://github.com/chef/chef-workstation/issues/1180.

The fastest way to see good builds is to look at https://downloads.chef.io/chef-workstation/current.

20.5.44
20.5.41
from that list, I can see that 20.5.42 did not build, so 20.5.44 is the first build that has that fix.

so then on https://github.com/chef/chef-workstation/issues/1180 I would post something like "This was fixed in knife-windows#500, and in chef-workstation releases 20.5.44 and later"

Thanks!!

**Comment by lamont-granquist** [comment]
This really needs to be turned into either a PR against https://github.com/chef/chef/tree/master/docs/dev or a PR against https://github.com/chef/chef-web-docs/, as an issue here its not so helpful and creates noise that makes it hard to track all the other issues coming into the repository.

**Comment by tas50** [comment]
Tags are hard, but the changelog has a version by version comment in it though.
